infix using "C:\COUNTRIES\GH7J\GHBQ7JFL.dct"

label variable qhclust  "Cluster number"
label variable qhnumber "Household number"
label variable qline    "Individual line number"
label variable q212     "Line number of child"
label variable q212b    "Single or Multiple Birth"
label variable q212c    "Born alive/dead or miscarriage/abortion"
label variable q212d    "Did baby cry, move or breathe"
label variable q213     "Sex of child"
label variable q215d    "Day of birth"
label variable q215m    "Month of birth"
label variable q215y    "Year of birth"
label variable q216     "Child is still alive"
label variable q217     "Current age of child"
label variable q220u    "Age at death (units)"
label variable q220n    "Age at death (number)"
label variable q220aad  "Day of dead"
label variable q220aam  "Month of dead"
label variable q220aay  "Year of dead"
label variable q220abd  "Day of pregnancy termination"
label variable q220abm  "Month of pregnancy termination"
label variable q220aby  "Year of pregnancy termination"
label variable q220ac   "Pregnancy duration"
label variable q220ad   "Do something to end the pregnancy"
label variable q221     "Live birth between births"
label variable qlast5   "Child born alive/dead in the last 5 years"
label variable q215c    "Date of birth of child (CMC)"
label variable q215cd   "Date of birth of child Century Day Code (CDC)"
label variable q215di   "Imputed day of birth"
label variable q215f    "Date flag for Q215C"
label variable q220c    "Age at death months (imputed)"
label variable q220f    "Date flag for Q220C"
label variable pregout  "Pregnancy outcome"
label variable q403     "Line number"
label variable q405     "Received antenatal care for pregnancy"
label variable q406     "Reason not seeing anyone for antenatal care"
label variable q407     "Provider of antenatal care for pregnancy"
label variable q408     "Where antenatal care took place"
label variable q409     "Months pregnant at first antenatal care"
label variable q410     "First antenatal care because of problems or checkup"
label variable q411     "Problems during first antenatal care"
label variable q412     "Antenatal visits during pregnancy"
label variable q413a    "Antenatal care: Blood pressure"
label variable q413b    "Antenatal care: Urine sample"
label variable q413c    "Antenatal care: Blood sample"
label variable q413d    "Antenatal care: Weight"
label variable q413e    "During any antenatal care told about pregnancy complications"
label variable q413f    "Told about where to go if had any complications"
label variable q414     "Tetanus injection during pregnancy"
label variable q415     "Number of tetanus injections"
label variable q417     "Tetanus injections before pregnancy"
label variable q418     "Number of tetanus injections before pregnancy"
label variable q419     "Years ago received last tetanus injection before pregnancy"
label variable q420     "Iron tablets during pregnancy"
label variable q421     "Number of days took iron tablets"
label variable q422     "Drugs for intestinal parasites"
label variable q423     "During pregnancy took SP/Fansidar for malaria"
label variable q424     "How many times took SP/Fansidar (Malaria)"
label variable q425     "Took SP/Fansidar during antenatal visit (Malaria)"
label variable q426b    "Size of child at birth"
label variable q427     "Weighed at birth"
label variable q428u    "Weight at birth (units)"
label variable q428n    "Weight in Kilograms"
label variable q429     "Assistance at delivery"
label variable q430     "Place of delivery"
label variable q431a    "Reason not delivering at hospital/health centre"
label variable q431ba   "Procedure at delivery: Forceps or vacuum"
label variable q431bb   "Procedure at delivery: Blood transfusion"
label variable q431bc   "Procedure at delivery: Intravenous fluid"
label variable q431c    "Suffered from any problem before/after delivery"
label variable q431d    "Problems suffered before/after delivery"
label variable q431e    "Saw anyone about the problem"
label variable q431f    "Reason not seeing anyone about the problem"
label variable q431g    "Who saw the problem"
label variable q431h    "Where was treated for the problem"
label variable q431i    "Condition improved after treated"
label variable q431j    "Referred/told to go to another place"
label variable q431k    "Where was referred/told to go for treatment"
label variable q431l    "Went to the referred place"
label variable q431m    "Reason not going to the referred place for treatment"
label variable q432u    "Time spent in health facility after delivery (Units)"
label variable q432n    "Time spent in health facility after delivery (Number)"
label variable q433a    "Delivery by caesarean section"
label variable q433b    "Timing of decision on caesarean section"
label variable q434     "Child was put on the chest immediately after birth"
label variable q434a    "Child bare skin touched respondent bare skin"
label variable q435     "Postnatal check on respondent before discharge"
label variable q436u    "First postnatal check on respondent (Units)"
label variable q436n    "First postnatal check on respondent (Number)"
label variable q437     "Person giving postnatal care to respondent"
label variable q438b    "First postnatal check on child in facility"
label variable q439u    "Time first postnatal check on child in facility (unit)"
label variable q439n    "Time first postnatal check on child in facility (number)"
label variable q440     "Person giving postnatal care to child  in facility"
label variable q441     "Checkup on respondent after discharge from place of delivery"
label variable q442u    "Time checkup on respondent after discharge (unit)"
label variable q442n    "Time checkup on respondent after discharge (number)"
label variable q443     "Person giving checkup on respondent after discharge"
label variable q444     "Place of checkup on respondent after discharge"
label variable q445b    "Health child checked in first 2 months after birth"
label variable q446u    "First postnatal check on child (unit)"
label variable q446n    "First postnatal check on child (number)"
label variable q447     "Person giving postnatal check on child"
label variable q448     "Place of first postnatal check"
label variable q449     "Respondent received postnatal check after home delivery"
label variable q450u    "Time respondent received postnatal check after home delivery (units)"
label variable q450n    "Time respondent received postnatal check after home delivery (number)"
label variable q451     "Person giving postnatal check on respondent after home delivery"
label variable q452     "Place postnatal check on respondent after home delivery"
label variable q453b    "Child received postnatal check after home delivery"
label variable q454u    "Time child received postnatal check after home delivery (units)"
label variable q454n    "Time child received postnatal check after home delivery (number)"
label variable q455     "Person giving postnatal check on child after home delivery"
label variable q456     "Place postnatal check on child after home delivery"
label variable q457a    "During first two days, health care provider: examine the cord"
label variable q457b    "During first two days, health care provider: measure temperature"
label variable q457c    "During first two days, health care provider: counsel on danger signs for newborn"
label variable q457d    "During first two days, health care provider: counsel on breastfeeding"
label variable q457e    "During first two days, health care provider: observe breastfeeding"
label variable q500     "Line number of recent abortion in 2012 or later"
label variable q501     "Year of most recent abortion in 2012 or after"
label variable q502a    "Main reason for abortion"
label variable q502b    "Any other reason for abortion"
label variable q502c    "Other reasons for abortion"
label variable q503     "Partner's attitude toward abortion"
label variable q504     "Multiple steps to end pregnancy"
label variable q505u    "Time between first attempt and final (Units)"
label variable q505n    "Time between first attempt and final (Number)"
label variable q506     "First action to end pregnancy"
label variable q507     "Provider for first step to end pregnancy"
label variable q508     "Source for first step to end pregnancy"
label variable q509a    "Anything paid to get procedure done"
label variable q509b    "Person who paid for first step to end pregnancy"
label variable q510     "Bleeding from first step to end pregnancy"
label variable q511     "Bleeding was mild/moderate/severe"
label variable q512     "Pain from first step to end pregnancy"
label variable q513     "Pain was mild/moderate/severe"
label variable q514     "Fever from first step to end pregnancy"
label variable q515     "Fever was mild/moderate/severe"
label variable q516     "Injury or perforation from first step to end pregnancy"
label variable q517     "Injury or perforation was mild/moderate/severe"
label variable q518     "Vaginal discharge from first step to end pregnancy"
label variable q519     "Vaginal discharge was mild/moderate/severe"
label variable q520     "Any other problem (1) from first step to end pregnancy"
label variable q521     "Problem (1) from first step to end pregnancy"
label variable q522     "Problem (1) mild/moderate/severe from first step to end pregnancy"
label variable q523     "Any other problem (2) from first step to end pregnancy"
label variable q524     "Problem (2) from first step to end pregnancy"
label variable q525     "Problem (2) mild/moderate/severe from first step to end pregnancy"
label variable q526     "Any other problem (3) from first step to end pregnancy"
label variable q527     "Problem (3) from first step to end pregnancy"
label variable q528     "Problem (3) mild/moderate/severe from first step to end pregnancy"
label variable q529     "Any other problem (4) from first step to end pregnancy"
label variable q530     "Problem (4) from first step to end pregnancy"
label variable q531     "Problem (4) mild/moderate/severe from first step to end pregnancy"
label variable q532     "Took any pain relievers after first step to end pregnancy"
label variable q533     "Last action to end pregnancy"
label variable q534     "Provider for last step to end pregnancy"
label variable q535     "Source for last step to end pregnancy"
label variable q536a    "Anything paid to get procedure done"
label variable q536b    "Person who paid for last step to end pregnancy"
label variable q537     "Took antibiotics after abortion"
label variable q538     "Took any pain relievers after last step to end pregnancy"
label variable q539b    "Local anesthesia for abortion"
label variable q540     "Health problems in first month after abortion"
label variable q541     "Bleeding in first month after abortion"
label variable q542     "Bleeding was mild/moderate/severe"
label variable q543     "Pain in first month after abortion"
label variable q544     "Pain was mild/moderate/severe"
label variable q545     "Fever in first month after abortion"
label variable q546     "Fever was mild/moderate/severe"
label variable q547     "Injury or perforation in first month after abortion"
label variable q548     "Injury or perforation was mild/moderate/severe"
label variable q549     "Foul-smelling discharge in first month after abortion"
label variable q550     "Foul-smelling discharge was mild/moderate/severe"
label variable q551     "Any other problem (1) in first month after abortion"
label variable q552     "Problem (1) in first month after abortion"
label variable q553     "Problem (1) mild/moderate/severe in first month after abortion"
label variable q554     "Any other problem (2) in first month after abortion"
label variable q555     "Problem (2) in first month after abortion"
label variable q556     "Problem (2) mild/moderate/severe in first month after abortion"
label variable q557     "Any other problem (3) in first month after abortion"
label variable q558     "Problem (3) in first month after abortion"
label variable q559     "Problem (3) mild/moderate/severe in first month after abortion"
label variable q560     "Any other problem (4) in first month after abortion"
label variable q561     "Problem (4) in first month after abortion"
label variable q562     "Problem (4) mild/moderate/severe in first month after abortion"
label variable q563b    "Received treatment for health problems due to abortion"
label variable q564     "Type of treatment received for health problems due to abortion"
label variable q565     "Source of treatment for health problems due to abortion"
label variable q566a    "Spent any nights in a health facility in the first month after abortion"
label variable q566bu   "Time spent in health facility due to abortion (Units)"
label variable q566bn   "Time spent in health facility due to abortion (Number)"
label variable q567     "Visited by doctor or health worker before or after abortion"
label variable q568     "Any health problems six months after abortion"
label variable q569     "Health problems six months after abortion"
label variable q570     "Using contraception at the time she became pregnant"
label variable q571     "Contraception used at the time she became pregnant"
label variable q572     "Health professional spoke about contraception before or after abortion"
label variable q573     "When health professional spoke about contraception"
label variable q574     "Health worker gave contraception method or FP advice after abortion"
label variable q575     "Given method of contraception, prescription or referral after abortion"
label variable q577     "Ever heard of abortion"
label variable q578     "Could decide on your own to get an abortion"
label variable q579     "Knows where to get an abortion"
label variable q580     "Where to go for abortion"
label variable q581     "Abortion legal in Ghana"
label variable q582     "Conditions of legal abortion in Ghana"
label variable q600     "Line number of recent miscarriage in 2012 or later"
label variable q601     "Year of most recent miscarriage in 2012 or after"
label variable q602     "Cause of miscarriage"
label variable q603     "Where miscarriage occurred"
label variable q604a    "Sought help for miscarriage"
label variable q604b    "From whom sought help for miscarriage"
label variable q604c    "Place got help for miscarriage"
label variable q605     "Uterus cleaned after miscarriage"
label variable q606     "Method to clean uterus"
label variable q607     "Took antibiotics after miscarriage"
label variable q608     "Given pain relievers after miscarriage"
label variable q609b    "Anesthesia for miscarriage"
label variable q610     "Any health problems due to miscarriage"
label variable q611     "Bleeding from miscarriage"
label variable q612     "Bleeding was mild/moderate/severe"
label variable q613     "Pain from miscarriage"
label variable q614     "Pain was mild/moderate/severe"
label variable q615     "Fever from miscarriage"
label variable q616     "Fever was mild/moderate/severe"
label variable q617     "Injury or perforation from miscarriage"
label variable q618     "Injury or perforation was mild/moderate/severe"
label variable q619     "Foul-smelling discharge from miscarriage"
label variable q620     "Foul-smelling discharge was mild/moderate/severe"
label variable q621     "Any other problem (1) from miscarriage"
label variable q622     "Problem (1) from miscarriage"
label variable q623     "Problem (1) mild/moderate/severe from miscarriage"
label variable q624     "Any other problem (2) from miscarriage"
label variable q625     "Problem (2) from miscarriage"
label variable q626     "Problem (2) mild/moderate/severe from miscarriage"
label variable q627     "Any other problem (3) from miscarriage"
label variable q628     "Problem (3) from miscarriage"
label variable q629     "Problem (3) mild/moderate/severe from miscarriage"
label variable q630     "Any other problem (4) from miscarriage"
label variable q631     "Problem (4) from miscarriage"
label variable q632     "Problem (4) mild/moderate/severe from miscarriage"
label variable q633     "Received treatment for health problems due to miscarriage"
label variable q634     "Type of treatment received for health problems due to miscarriage"
label variable q635     "Source of treatment for health problems due to miscarriage"
label variable q636a    "Spent any nights in a health facility in the first month after miscarriage"
label variable q636bu   "Time spent in health facility due to miscarriage (Units)"
label variable q636bn   "Time spent in health facility due to miscarriage (Number)"
label variable q637     "Visited by doctor or health worker before or after miscarriage"
label variable q638     "Any health problems six months after miscarriage"
label variable q639     "Health problems six months after miscarriage"
label variable q640     "Using contraception at the time she became pregnant"
label variable q641     "Contraception used at the time she became pregnant"
label variable q642     "Health professional spoke about contraception before or after miscarriage"
label variable q643     "When health professional spoke about contraception"
label variable q644     "Health worker gave contraception method or FP advice after miscarriage"
label variable q645     "Given method of contraception, prescription or referral after miscarriage"

#delimit ;
label define Q212B   
     1 "Single"
     2 "Multiple"
;
label define Q212C   
     1 "Born alive"
     2 "Born dead"
     3 "Miscarriage"
     4 "Abortion"
;
label define Q212D   
     1 "Yes"
     2 "No"
;
label define Q213    
     1 "Boy"
     2 "Girl"
;
label define Q215D   
    98 "Don't know day"
;
label define Q215M   
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    97 "Inconsistent"
    98 "Don't know month"
;
label define Q215Y   
  9997 "Inconsistent"
  9998 "Don't know year"
;
label define Q216    
     1 "Yes"
     2 "No"
;
label define Q217    
    97 "Inconsistent"
    98 "Don't know age"
;
label define Q220U   
     1 "Days"
     2 "Months"
     3 "Years"
     9 "Special answers"
;
label define Q220AAD 
    98 "Don't know day"
;
label define Q220AAM 
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    98 "Don't know month"
;
label define Q220AAY 
  9998 "Don't know year"
;
label define Q220ABD 
    98 "Don't know day"
;
label define Q220ABM 
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    97 "Inconsistent"
    98 "Don't know month"
;
label define Q220ABY 
  9997 "Inconsistent"
  9998 "Don't know year"
;
label define Q220AD  
     1 "Yes"
     2 "No"
;
label define Q221    
     1 "Yes"
     2 "No"
;
label define QLAST5  
     0 "No"
     1 "Yes"
;
label define Q215F   
     0 "Month, year and day"
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define Q220F   
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
;
label define PREGOUT 
     1 "Live birth"
     2 "Stillbirth"
     3 "Miscarriage"
     4 "Abortion"
;
label define Q405    
     1 "Yes"
     2 "No"
;
label define Q409    
    98 "Don't know"
;
label define Q410    
     1 "Problem"
     2 "Just checkup"
;
label define Q412    
    98 "Don't know"
;
label define Q413A   
     1 "Yes"
     2 "No"
;
label define Q413B   
     1 "Yes"
     2 "No"
;
label define Q413C   
     1 "Yes"
     2 "No"
;
label define Q413D   
     1 "Yes"
     2 "No"
;
label define Q413E   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q413F   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q414    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q415    
     7 "7 or more"
     8 "Don't know"
;
label define Q417    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q418    
     7 "7 or more"
     8 "Don't know"
;
label define Q420    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q421    
     0 "Didn't take any"
   998 "Don't know"
;
label define Q422    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q423    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q424    
    98 "Don't know"
;
label define Q425    
     1 "Antenatal visit"
     2 "Another facility visit"
     6 "Other source"
;
label define Q426B   
     1 "Very large"
     2 "Larger than average"
     3 "Average"
     4 "Smaller than average"
     5 "Very small"
     8 "Don't know"
;
label define Q427    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q428U   
     1 "Kilograms from card"
     2 "Kilograms from recall"
     9 "Special answers"
;
label define Q430    
    11 "Her home"
    12 "Other home"
    21 "Public: Govt hospital"
    22 "Public: Govt health center/clinic"
    23 "Public: Govt health post/chps"
    24 "Public: Mobile clinic/outreach"
    26 "Public: Other public sector"
    31 "Private: Hospital/clinic"
    32 "Private: Fp/ppag clinic"
    33 "Private: Mobile clinic/outreach"
    34 "Private: Maternity home"
    36 "Private: Other private med sector"
    96 "Other"
;
label define Q431BA  
     1 "Yes"
     2 "No"
;
label define Q431BB  
     1 "Yes"
     2 "No"
;
label define Q431BC  
     1 "Yes"
     2 "No"
;
label define Q431C   
     1 "Yes"
     2 "No"
;
label define Q431E   
     1 "Yes"
     2 "No"
;
label define Q431H   
    11 "Her home"
    12 "Other home"
    21 "Public: Govt hospital"
    22 "Public: Govt health center/clinic"
    23 "Public: Govt health post/chps"
    24 "Public: Mobile clinic/outreach"
    26 "Public: Other public sector"
    31 "Private: Hospital/clinic"
    32 "Private: Fp/ppag clinic"
    33 "Private: Mobile clinic/outreach"
    34 "Private: Maternity home"
    36 "Private: Other private med sector"
    96 "Other"
;
label define Q431I   
     1 "No change"
     2 "Improved"
     3 "Worsened"
     8 "Don't know"
;
label define Q431J   
     1 "Yes"
     2 "No"
;
label define Q431K   
    21 "Public: Govt hospital"
    22 "Public: Govt health center/clinic"
    23 "Public: Govt health post/chps"
    24 "Public: Mobile clinic/outreach"
    26 "Public: Other public sector"
    31 "Private: Hospital/clinic"
    32 "Private: Fp/ppag clinic"
    33 "Private: Mobile clinic/outreach"
    34 "Private: Maternity home"
    36 "Private: Other private med sector"
    96 "Other"
;
label define Q431L   
     1 "Yes"
     2 "No"
;
label define Q432U   
     1 "Hours"
     2 "Days"
     3 "Weeks"
     9 "Special answers"
;
label define Q432N   
    98 "Don't know"
;
label define Q433A   
     1 "Yes"
     2 "No"
;
label define Q433B   
     1 "Before"
     2 "After"
;
label define Q434    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q434A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q435    
     1 "Yes"
     2 "No"
;
label define Q436U   
     1 "Hours"
     2 "Days"
     3 "Weeks"
     9 "Special answers"
;
label define Q436N   
    98 "Don't know"
;
label define Q437    
    11 "Health personnel: Doctor"
    12 "Health personnel: Nurse/midwife"
    13 "Health personnel: Com  health officer/nurse"
    21 "Other person: Traditional birth attendant"
    22 "Other person: Village health volunteer"
    23 "Other person: Traditional health practitioner"
    96 "Other"
;
label define Q438B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q439U   
     1 "Hours"
     2 "Days"
     3 "Weeks"
     9 "Special answers"
;
label define Q439N   
    98 "Don't know"
;
label define Q440    
    11 "Health personnel: Doctor"
    12 "Health personnel: Nurse/midwife"
    13 "Health personnel: Com  health officer/nurse"
    21 "Other person: Traditional birth attendant"
    22 "Other person: Village health volunteer"
    23 "Other person: Traditional health practitioner"
    96 "Other"
;
label define Q441    
     1 "Yes"
     2 "No"
;
label define Q442U   
     1 "Hours"
     2 "Days"
     3 "Weeks"
     9 "Special answers"
;
label define Q442N   
    98 "Don't know"
;
label define Q443    
    11 "Health personnel: Doctor"
    12 "Health personnel: Nurse/midwife"
    13 "Health personnel: Com  health officer/nurse"
    21 "Other person: Traditional birth attendant"
    22 "Other person: Village health volunteer"
    23 "Other person: Traditional health practitioner"
    96 "Other"
;
label define Q444    
    11 "Her home"
    12 "Other home"
    21 "Public: Govt hospital"
    22 "Public: Govt health center/clinic"
    23 "Public: Govt health post/chps"
    24 "Public: Mobile clinic/outreach"
    26 "Public: Other public sector"
    31 "Private: Hospital/clinic"
    32 "Private: Fp/ppag clinic"
    33 "Private: Mobile clinic/outreach"
    34 "Private: Maternity home"
    36 "Private: Other private med sector"
    96 "Other"
;
label define Q445B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q446U   
     1 "Hours"
     2 "Days"
     3 "Weeks"
     9 "Special answers"
;
label define Q446N   
    98 "Don't know"
;
label define Q447    
    11 "Health personnel: Doctor"
    12 "Health personnel: Nurse/midwife"
    13 "Health personnel: Com  health officer/nurse"
    21 "Other person: Traditional birth attendant"
    22 "Other person: Village health volunteer"
    23 "Other person: Traditional health practitioner"
    96 "Other"
;
label define Q448    
    11 "Her home"
    12 "Other home"
    21 "Public: Govt hospital"
    22 "Public: Govt health center/clinic"
    23 "Public: Govt health post/chps"
    24 "Public: Mobile clinic/outreach"
    26 "Public: Other public sector"
    31 "Private: Hospital/clinic"
    32 "Private: Fp/ppag clinic"
    33 "Private: Mobile clinic/outreach"
    34 "Private: Maternity home"
    36 "Private: Other private med sector"
    96 "Other"
;
label define Q449    
     1 "Yes"
     2 "No"
;
label define Q450U   
     1 "Hours"
     2 "Days"
     3 "Weeks"
     9 "Special answers"
;
label define Q450N   
    98 "Don't know"
;
label define Q451    
    11 "Health personnel: Doctor"
    12 "Health personnel: Nurse/midwife"
    13 "Health personnel: Com  health officer/nurse"
    21 "Other person: Traditional birth attendant"
    22 "Other person: Village health volunteer"
    23 "Other person: Traditional health practitioner"
    96 "Other"
;
label define Q452    
    11 "Her home"
    12 "Other home"
    21 "Public: Govt hospital"
    22 "Public: Govt health center/clinic"
    23 "Public: Govt health post/chps"
    24 "Public: Mobile clinic/outreach"
    26 "Public: Other public sector"
    31 "Private: Hospital/clinic"
    32 "Private: Fp/ppag clinic"
    33 "Private: Mobile clinic/outreach"
    34 "Private: Maternity home"
    36 "Private: Other private med sector"
    96 "Other"
;
label define Q453B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q454U   
     1 "Hours after birth"
     2 "Days after birth"
     3 "Weeks after birth"
     9 "Special answers"
;
label define Q454N   
    98 "Don't know"
;
label define Q455    
    11 "Health personnel: Doctor"
    12 "Health personnel: Nurse/midwife"
    13 "Health personnel: Com  health officer/nurse"
    21 "Other person: Traditional birth attendant"
    22 "Other person: Village health volunteer"
    23 "Other person: Traditional health practitioner"
    96 "Other"
;
label define Q456    
    11 "Her home"
    12 "Other home"
    21 "Public: Govt hospital"
    22 "Public: Govt health center/clinic"
    23 "Public: Govt health post/chps"
    24 "Public: Mobile clinic/outreach"
    26 "Public: Other public sector"
    31 "Private: Hospital/clinic"
    32 "Private: Fp/ppag clinic"
    33 "Private: Mobile clinic/outreach"
    34 "Private: Maternity home"
    36 "Private: Other private med sector"
    96 "Other"
;
label define Q457A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q457B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q457C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q457D   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q457E   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q501    
  2012 "2012"
  2013 "2013"
  2014 "2014"
  2015 "2015"
  2016 "2016"
  2017 "2017"
  9998 "DK year"
;
label define Q502A   
     1 "Health of mother"
     2 "Risk of birth defect"
     3 "Fetus not viable"
     4 "No money to take care of baby"
     5 "Too young to have child"
     6 "Not ready to be a mother"
     7 "No one to help me look after the child"
     8 "Wanted to delay childbearing"
     9 "Wanted to space child"
    10 "Wanted to continue schooling"
    11 "Wanted to continue working"
    12 "Wanted no more children"
    13 "Did not love the father"
    14 "Did not want to stay with the father"
    15 "Partner did not want child/denied the pregnancy"
    16 "Father of child died"
    17 "Child's sex"
    18 "Because of rape"
    19 "To avoid shame"
    20 "Afraid of parents"
    21 "Parents insisted"
    96 "Other"
;
label define Q502B   
     1 "Yes"
     2 "No"
;
label define Q503    
     1 "Favored"
     2 "Opposed"
     3 "Neutral"
     4 "He did not know"
     5 "Don't know/don't remember"
;
label define Q504    
     1 "Yes"
     2 "No"
;
label define Q505U   
     1 "Days"
     2 "Weeks"
     9 "Special answers"
;
label define Q505N   
    98 "Don't know"
;
label define Q506    
    11 "Drank milk/coffee/alcohol/other liquid with lots of sugar"
    12 "Drank herbal concoction"
    13 "Drank other home remedies"
    14 "Used any herbal enema"
    15 "Inserted herb/object/other substance in the vagina"
    16 "Heavy massage"
    17 "Excessive physical activity"
    18 "Tablets (exact kind unknown)"
    21 "Cytotec tablets (Misoprostol)"
    22 "Mifepristone + Misoprostol (Medabon,etc)"
    23 "IV / Oxytocin"
    31 "D&C / D&E"
    32 "Vacuum aspiration"
    33 "Injection in abdomen (saline instillation)"
    34 "Catheter"
    35 "Other injection"
    96 "Other"
;
label define Q507    
     1 "Health personnel: Doctor"
     2 "Health personnel: Nurse/midwife"
     3 "Health personnel: Com  health officer/nurse"
     4 "Other person: Pharmacist/chemical seller"
     5 "Other person: Traditional birth attendant"
     6 "Other person: Community health volunteer"
     7 "Other person: Relative/friend"
     8 "Other person: Traditional practitioner"
     9 "No one"
    96 "Other"
;
label define Q508    
    11 "Public: Govt hospital"
    12 "Public: Govt health center/clinic"
    13 "Public: Govt health post/chps"
    14 "Public: Mobile clinic/outreach"
    16 "Public: Other public sector"
    21 "Private: Hospital/clinic"
    22 "Private: Fp/ppag clinic"
    23 "Private: Mobile clinic/outreach"
    24 "Private: Maternity home"
    25 "Private: Pharmacy/chemist/drug store"
    26 "Private: Other private medical sector"
    31 "Respondent's home"
    32 "Other home"
    33 "TBA's home"
    96 "Other"
;
label define Q509A   
     1 "Yes"
     2 "No"
;
label define Q510    
     1 "Yes"
     2 "No"
;
label define Q511    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q512    
     1 "Yes"
     2 "No"
;
label define Q513    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q514    
     1 "Yes"
     2 "No"
;
label define Q515    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q516    
     1 "Yes"
     2 "No"
;
label define Q517    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q518    
     1 "Yes"
     2 "No"
;
label define Q519    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q520    
     1 "Yes"
     2 "No"
;
label define Q521    
  9996 "Other problem"
;
label define Q522    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q523    
     1 "Yes"
     2 "No"
;
label define Q524    
  9996 "Other problem"
;
label define Q525    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q526    
     1 "Yes"
     2 "No"
;
label define Q527    
  9996 "Other problem"
;
label define Q528    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q529    
     1 "Yes"
     2 "No"
;
label define Q530    
  9996 "Other problem"
;
label define Q531    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q532    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q533    
    11 "Drank milk/coffee/alcohol/other liquid with lots of sugar"
    12 "Drank herbal concoction"
    13 "Drank other home remedies"
    14 "Used any herbal enema"
    15 "Inserted herb/object/other substance in the vagina"
    16 "Heavy massage"
    17 "Excessive physical activity"
    18 "Tablets (exact kind unknown)"
    21 "Cytotec tablets (Misoprostol)"
    22 "Mifepristone + Misoprostol (Medabon,etc)"
    23 "IV / Oxytocin"
    31 "D&C / D&E"
    32 "Vacuum aspiration"
    33 "Injection in abdomen (saline instillation)"
    34 "Catheter"
    35 "Other injection"
    96 "Other"
;
label define Q534    
     1 "Health personnel: Doctor"
     2 "Health personnel: Nurse/midwife"
     3 "Health personnel: Com  health officer/nurse"
     4 "Other person: Pharmacist/chemical seller"
     5 "Other person: Traditional birth attendant"
     6 "Other person: Community health volunteer"
     7 "Other person: Relative/friend"
     8 "Other person: Traditional practitioner"
     9 "No one"
    96 "Other"
;
label define Q535    
    11 "Public: Govt hospital"
    12 "Public: Govt health center/clinic"
    13 "Public: Govt health post/chps"
    14 "Public: Mobile clinic/outreach"
    16 "Public: Other public sector"
    21 "Private: Hospital/clinic"
    22 "Private: Fp/ppag clinic"
    23 "Private: Mobile clinic/outreach"
    24 "Private: Maternity home"
    25 "Private: Pharmacy/chemist/drug store"
    26 "Private: Other private medical sector"
    31 "Respondent's home"
    32 "Other home"
    33 "TBA's home"
    96 "Other"
;
label define Q536A   
     1 "Yes"
     2 "No"
;
label define Q537    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q538    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q539B   
     1 "Local"
     2 "General"
     3 "Neither"
     8 "Don't know"
;
label define Q540    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q541    
     1 "Yes"
     2 "No"
;
label define Q542    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q543    
     1 "Yes"
     2 "No"
;
label define Q544    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q545    
     1 "Yes"
     2 "No"
;
label define Q546    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q547    
     1 "Yes"
     2 "No"
;
label define Q548    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q549    
     1 "Yes"
     2 "No"
;
label define Q550    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q551    
     1 "Yes"
     2 "No"
;
label define Q552    
  9996 "Other problem"
;
label define Q553    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q554    
     1 "Yes"
     2 "No"
;
label define Q555    
  9996 "Other problem"
;
label define Q556    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q557    
     1 "Yes"
     2 "No"
;
label define Q558    
  9996 "Other problem"
;
label define Q559    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q560    
     1 "Yes"
     2 "No"
;
label define Q561    
  9996 "Other problem"
;
label define Q562    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q563B   
     1 "Yes"
     2 "No"
;
label define Q566A   
     1 "Yes"
     2 "No"
;
label define Q566BU  
     1 "Nights"
     2 "Weeks"
     9 "Special answers"
;
label define Q566BN  
    98 "Don't know"
;
label define Q567    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q568    
     1 "Yes"
     2 "No"
     3 "Not yet 6 months"
     8 "Don't know"
;
label define Q570    
     1 "Yes"
     2 "No"
;
label define Q571    
     1 "Female sterilization"
     2 "Male sterilization"
     3 "Iud"
     4 "Injectables"
     5 "Implants"
     6 "Pill"
     7 "Condom"
     8 "Female condom"
     9 "Diaphragm"
    10 "Foam/jelly"
    11 "Lactational amenorrhea method"
    12 "Rhythm method"
    13 "Withdrawal"
    96 "Other"
;
label define Q572    
     1 "Yes"
     2 "No"
;
label define Q573    
     1 "Before the abortion"
     2 "After the abortion"
     3 "Both before and after the abortion"
     8 "Don't know"
;
label define Q574    
     1 "Yes"
     2 "No"
;
label define Q575    
     1 "Gave method"
     2 "Prescribed a method"
     3 "Gave referral"
     8 "Don't know"
;
label define Q577    
     1 "Yes"
     2 "No"
;
label define Q578    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q579    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q581    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q601    
  2012 "2012"
  2013 "2013"
  2014 "2014"
  2015 "2015"
  2016 "2016"
  2017 "2017"
  9998 "DK year"
;
label define Q602    
     1 "Accident"
     2 "Ate something"
     3 "Someone hurt me"
     4 "Spontaneous"
     6 "Other"
     8 "Don't know"
;
label define Q603    
    11 "Public: Govt hospital"
    12 "Public: Govt health center/clinic"
    13 "Public: Govt health post/chps"
    14 "Public: Mobile clinic/outreach"
    16 "Public: Other public sector"
    21 "Private: Hospital/clinic"
    22 "Private: Fp/ppag clinic"
    23 "Private: Mobile clinic/outreach"
    24 "Private: Maternity home"
    25 "Private: Pharmacy/chemist/drug store"
    26 "Private: Other private medical sector"
    31 "Respondent's home"
    32 "Other home"
    33 "TBA's home"
    41 "Workplace"
    51 "Public place"
    96 "Other"
;
label define Q604A   
     1 "Yes"
     2 "No"
;
label define Q605    
     1 "Yes"
     2 "No"
;
label define Q606    
     1 "D&c"
     2 "Vacuum aspiration"
     3 "Oxytocin"
     4 "Cytotec tablets (misoprostol)"
     5 "Mifepristone + misoprostol"
     6 "Catheter"
     7 "Tablets for insertion"
     8 "Herbal mixture insertion"
    96 "Other"
    98 "Don't know"
;
label define Q607    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q608    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q609B   
     1 "Local"
     2 "General"
     3 "Neither"
     8 "Don't know"
;
label define Q610    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q611    
     1 "Yes"
     2 "No"
;
label define Q612    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q613    
     1 "Yes"
     2 "No"
;
label define Q614    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q615    
     1 "Yes"
     2 "No"
;
label define Q616    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q617    
     1 "Yes"
     2 "No"
;
label define Q618    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q619    
     1 "Yes"
     2 "No"
;
label define Q620    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q621    
     1 "Yes"
     2 "No"
;
label define Q622    
  9996 "Other problem"
;
label define Q623    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q624    
     1 "Yes"
     2 "No"
;
label define Q625    
  9996 "Other problem"
;
label define Q626    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q627    
     1 "Yes"
     2 "No"
;
label define Q628    
  9996 "Other problem"
;
label define Q629    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q630    
     1 "Yes"
     2 "No"
;
label define Q631    
  9996 "Other problem"
;
label define Q632    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q633    
     1 "Yes"
     2 "No"
;
label define Q636A   
     1 "Yes"
     2 "No"
;
label define Q636BU  
     1 "Nights"
     2 "Weeks"
     9 "Special answers"
;
label define Q636BN  
    98 "Don't know"
;
label define Q637    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q638    
     1 "Yes"
     2 "No"
     3 "Not yet 6 months"
     8 "Don't know"
;
label define Q640    
     1 "Yes"
     2 "No"
;
label define Q641    
     1 "Female sterilization"
     2 "Male sterilization"
     3 "Iud"
     4 "Injectables"
     5 "Implants"
     6 "Pill"
     7 "Condom"
     8 "Female condom"
     9 "Diaphragm"
    10 "Foam/jelly"
    11 "Lactational amenorrhea method"
    12 "Rhythm method"
    13 "Withdrawal"
    96 "Other"
;
label define Q642    
     1 "Yes"
     2 "No"
;
label define Q643    
     1 "Before the miscarriage"
     2 "After the miscarriage"
     3 "Both before and after the miscarriage"
     8 "Don't know"
;
label define Q644    
     1 "Yes"
     2 "No"
;
label define Q645    
     1 "Gave method"
     2 "Prescribed a method"
     3 "Gave referral"
     8 "Don't know"
;

#delimit cr
label values q212b    Q212B   
label values q212c    Q212C   
label values q212d    Q212D   
label values q213     Q213    
label values q215d    Q215D   
label values q215m    Q215M   
label values q215y    Q215Y   
label values q216     Q216    
label values q217     Q217    
label values q220u    Q220U   
label values q220aad  Q220AAD 
label values q220aam  Q220AAM 
label values q220aay  Q220AAY 
label values q220abd  Q220ABD 
label values q220abm  Q220ABM 
label values q220aby  Q220ABY 
label values q220ad   Q220AD  
label values q221     Q221    
label values qlast5   QLAST5  
label values q215f    Q215F   
label values q220f    Q220F   
label values pregout  PREGOUT 
label values q405     Q405    
label values q409     Q409    
label values q410     Q410    
label values q412     Q412    
label values q413a    Q413A   
label values q413b    Q413B   
label values q413c    Q413C   
label values q413d    Q413D   
label values q413e    Q413E   
label values q413f    Q413F   
label values q414     Q414    
label values q415     Q415    
label values q417     Q417    
label values q418     Q418    
label values q420     Q420    
label values q421     Q421    
label values q422     Q422    
label values q423     Q423    
label values q424     Q424    
label values q425     Q425    
label values q426b    Q426B   
label values q427     Q427    
label values q428u    Q428U   
label values q428n    Q428N   
label values q430     Q430    
label values q431ba   Q431BA  
label values q431bb   Q431BB  
label values q431bc   Q431BC  
label values q431c    Q431C   
label values q431e    Q431E   
label values q431h    Q431H   
label values q431i    Q431I   
label values q431j    Q431J   
label values q431k    Q431K   
label values q431l    Q431L   
label values q432u    Q432U   
label values q432n    Q432N   
label values q433a    Q433A   
label values q433b    Q433B   
label values q434     Q434    
label values q434a    Q434A   
label values q435     Q435    
label values q436u    Q436U   
label values q436n    Q436N   
label values q437     Q437    
label values q438b    Q438B   
label values q439u    Q439U   
label values q439n    Q439N   
label values q440     Q440    
label values q441     Q441    
label values q442u    Q442U   
label values q442n    Q442N   
label values q443     Q443    
label values q444     Q444    
label values q445b    Q445B   
label values q446u    Q446U   
label values q446n    Q446N   
label values q447     Q447    
label values q448     Q448    
label values q449     Q449    
label values q450u    Q450U   
label values q450n    Q450N   
label values q451     Q451    
label values q452     Q452    
label values q453b    Q453B   
label values q454u    Q454U   
label values q454n    Q454N   
label values q455     Q455    
label values q456     Q456    
label values q457a    Q457A   
label values q457b    Q457B   
label values q457c    Q457C   
label values q457d    Q457D   
label values q457e    Q457E   
label values q501     Q501    
label values q502a    Q502A   
label values q502b    Q502B   
label values q503     Q503    
label values q504     Q504    
label values q505u    Q505U   
label values q505n    Q505N   
label values q506     Q506    
label values q507     Q507    
label values q508     Q508    
label values q509a    Q509A   
label values q510     Q510    
label values q511     Q511    
label values q512     Q512    
label values q513     Q513    
label values q514     Q514    
label values q515     Q515    
label values q516     Q516    
label values q517     Q517    
label values q518     Q518    
label values q519     Q519    
label values q520     Q520    
label values q521     Q521    
label values q522     Q522    
label values q523     Q523    
label values q524     Q524    
label values q525     Q525    
label values q526     Q526    
label values q527     Q527    
label values q528     Q528    
label values q529     Q529    
label values q530     Q530    
label values q531     Q531    
label values q532     Q532    
label values q533     Q533    
label values q534     Q534    
label values q535     Q535    
label values q536a    Q536A   
label values q537     Q537    
label values q538     Q538    
label values q539b    Q539B   
label values q540     Q540    
label values q541     Q541    
label values q542     Q542    
label values q543     Q543    
label values q544     Q544    
label values q545     Q545    
label values q546     Q546    
label values q547     Q547    
label values q548     Q548    
label values q549     Q549    
label values q550     Q550    
label values q551     Q551    
label values q552     Q552    
label values q553     Q553    
label values q554     Q554    
label values q555     Q555    
label values q556     Q556    
label values q557     Q557    
label values q558     Q558    
label values q559     Q559    
label values q560     Q560    
label values q561     Q561    
label values q562     Q562    
label values q563b    Q563B   
label values q566a    Q566A   
label values q566bu   Q566BU  
label values q566bn   Q566BN  
label values q567     Q567    
label values q568     Q568    
label values q570     Q570    
label values q571     Q571    
label values q572     Q572    
label values q573     Q573    
label values q574     Q574    
label values q575     Q575    
label values q577     Q577    
label values q578     Q578    
label values q579     Q579    
label values q581     Q581    
label values q601     Q601    
label values q602     Q602    
label values q603     Q603    
label values q604a    Q604A   
label values q605     Q605    
label values q606     Q606    
label values q607     Q607    
label values q608     Q608    
label values q609b    Q609B   
label values q610     Q610    
label values q611     Q611    
label values q612     Q612    
label values q613     Q613    
label values q614     Q614    
label values q615     Q615    
label values q616     Q616    
label values q617     Q617    
label values q618     Q618    
label values q619     Q619    
label values q620     Q620    
label values q621     Q621    
label values q622     Q622    
label values q623     Q623    
label values q624     Q624    
label values q625     Q625    
label values q626     Q626    
label values q627     Q627    
label values q628     Q628    
label values q629     Q629    
label values q630     Q630    
label values q631     Q631    
label values q632     Q632    
label values q633     Q633    
label values q636a    Q636A   
label values q636bu   Q636BU  
label values q636bn   Q636BN  
label values q637     Q637    
label values q638     Q638    
label values q640     Q640    
label values q641     Q641    
label values q642     Q642    
label values q643     Q643    
label values q644     Q644    
label values q645     Q645    
