infix using "C:\COUNTRIES\KE81\KEPR81FL.dct"

label variable hhid     "Case Identification"
label variable hvidx    "Line number"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv008a   "Date of interview Century Day Code (CDC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv011    "NA - Number of eligible men in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 14 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "Household selected for male interview"
label variable hv028    "Household weight for male subsample (6 decimals)"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv035    "Number of eligible children for height and weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "Total adults measured"
label variable hv042    "Household selected for hemoglobin"
label variable hv045a   "Language of questionnaire"
label variable hv045b   "Language of interview"
label variable hv045c   "Native language of respondent"
label variable hv046    "Translator used"
label variable hv801    "Time interview started (hhmm - 24 hour clock)"
label variable hv802    "Time interview ended (hhmm - 24 hour clock)"
label variable hv803    "Length of interview in minutes"
label variable hv804    "Number of visits for biomarker"
label variable hv807d   "Day of biomarker visit"
label variable hv807m   "Month of biomarker visit"
label variable hv807y   "Year of biomarker visit"
label variable hv807c   "Date of biomarker (CMC)"
label variable hv807a   "Date of biomarker Century Day Code (CDC)"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv201a   "NA - Water not available for at least a day last two weeks"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "Has mosquito bed net for sleeping"
label variable hv228    "Children under 5 slept under mosquito bed net last night"
label variable hv235    "Location of source for water"
label variable hv238    "Number of households sharing toilet"
label variable hv238a   "Location of toilet facility"
label variable hv239    "NA - Food cooked on stove or open fire"
label variable hv240    "NA - Household has a chimney, hood or neither"
label variable hv241    "NA - Food cooked in the house/ separate building/ outdoors"
label variable hv242    "NA - Household has separate room used as kitchen"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "Has watch"
label variable hv243c   "Has animal-drawn cart"
label variable hv243d   "Has boat with a motor"
label variable hv243e   "Has a computer"
label variable hv244    "Owns land usable for agriculture"
label variable hv245    "Hectares of agricultural land (1 decimal)"
label variable hv246    "Owns livestock, herds or farm animals"
label variable hv246a   "Owns cattle"
label variable hv246b   "Owns cows/ bulls"
label variable hv246c   "NA - Owns horses/ donkeys/ mules"
label variable hv246d   "Owns goats"
label variable hv246e   "Owns sheep"
label variable hv246f   "Owns chickens/poultry"
label variable hv246g   "Owns horses"
label variable hv246h   "Owns donkeys"
label variable hv246i   "Owns mules"
label variable hv246j   "Owns pigs"
label variable hv246k   "NA - Owns CS"
label variable hv247    "Has bank account"
label variable hv270    "Wealth index combined"
label variable hv271    "Wealth index factor score combined (5 decimals)"
label variable hv270a   "Wealth index for urban/rural"
label variable hv271a   "Wealth index factor score for urban/rural (5 decimals)"
label variable hml1     "Number of mosquito bed nets"
label variable hml1a    "Number of mosquito bed nets with specific information"
label variable hml2     "Number of children under mosquito bed net previous night"
label variable shcounty "County"
label variable shzone   "Malaria endemicity zone"
label variable sh109    "Type of cooking device"
label variable sh110    "Type of fuel/energy source for cooking device"
label variable sh116g   "Has solar panel"
label variable sh116h   "Has table"
label variable sh116i   "Has chair"
label variable sh116j   "Has sofa"
label variable sh116k   "Has bed"
label variable sh116l   "Has cupboard"
label variable sh116m   "Has clock"
label variable sh116n   "Has microwave oven"
label variable sh116o   "Has DVD player"
label variable sh116p   "Has CD player"
label variable sh119    "Member use phone for financial transactions"
label variable sh119a   "Household used mosquito repellent spray"
label variable hv101    "Relationship to head"
label variable hv102    "Usual resident"
label variable hv103    "Slept last night"
label variable hv104    "Sex of household member"
label variable hv105    "Age of household members"
label variable hv117    "Eligibility for female interview"
label variable hv120    "Children eligibility for height/weight and hemoglobin"
label variable hc0      "Index to Household Schedule"
label variable hc1      "Child's age in months"
label variable hc1a     "Child's age in days"
label variable hc16     "Day of birth"
label variable hc17     "Date measured (day)"
label variable hc18     "Date measured (month)"
label variable hc19     "Date measured (year)"
label variable hc20     "Century Day Code (CDC) of measurement"
label variable hc21     "Fieldworker measurer code"
label variable hc27     "Sex"
label variable hc30     "Month of birth"
label variable hc31     "Year of birth"
label variable hc32     "Date of birth (CMC)"
label variable hc32a    "Century Day Code (CDC) of birth"
label variable hc33     "Completeness of HC32 information"
label variable hc51     "Line number of parent/caretaker"
label variable hc52     "Read consent statement - hemoglobin"
label variable hc53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55     "Result of measurement - hemoglobin"
label variable hc56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57     "Anemia level"
label variable hc58     "NA - Agrees to referral - anemia"
label variable hc60     "Mother's line number (woman's questionnaire)"
label variable hc61     "Mother's highest educational level"
label variable hc62     "Mother's highest year of education"
label variable hc63     "Preceding birth interval (months)"
label variable hc64     "Birth order number"
label variable hc68     "Mother's highest educational level (for preliminary and final report)"
label variable shc1     "Child's age in months ( country specific version of HC1 )"
label variable shc1a    "Child's age in days ( country specific version of HC1A )"
label variable sb115a   "Illness or symptoms: extreme weakness"
label variable sb115b   "Illness or symptoms: heart problems"
label variable sb115c   "Illness or symptoms: loss of consciousness"
label variable sb115d   "Illness or symptoms: rapid breathing"
label variable sb115e   "Illness or symptoms: seizures"
label variable sb115f   "Illness or symptoms: bleeding"
label variable sb115g   "Illness or symptoms: jaundice"
label variable sb115h   "Illness or symptoms: dark urine"
label variable sb119    "Taken ACT for malaria treatment in the past two weeks"
label variable sb122    "Accepted medicine"
label variable sb123    "Fieldworker number for malaria medicine"
label variable sb128d   "Day of data collection"
label variable sb128m   "Month of data collection"
label variable sb128y   "Year of data collection"
label variable hmlidx   "Mosquito Bed Net Designation Number"
label variable hml3     "Net observed by interviewer"
label variable hml4     "Months ago net obtained"
label variable hml5     "NA - Net treated with insecticide when bought"
label variable hml6     "NA - Net treatment status"
label variable hml7     "Brand of net"
label variable hml8     "NA - Net treated since received"
label variable hml9     "NA - Time since last re-treatment (months)"
label variable hml10    "Insecticide-Treated Net (ITN)"
label variable hml11    "Number of persons who slept under this net"
label variable hml21    "Someone slept under this net last night"
label variable hmla     "Line number of person who slept in this net"
label variable hmlb     "Line number of person who slept in this net"
label variable hmlc     "Line number of person who slept in this net"
label variable hmld     "Line number of person who slept in this net"
label variable hmle     "NA - Line number of person who slept in this net"
label variable hml22    "Obtained net from campaign, antenatal or immunization visit"
label variable hml23    "Place where net was obtained"
label variable sh130    "Main reason bed net not used"
label variable hmhidx   "Index to Household Schedule"
label variable hml12    "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml13    "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml14    "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml15    "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml16    "Corrected age from Individual file"
label variable hml16a   "Age in months (for children)"
label variable hml17    "Flag for age from Individual file"
label variable hml18    "Pregnancy status from Individual file"
label variable hml19    "Person slept under an ever-treated net"
label variable hml20    "Person slept under an LLIN net"
label variable hml30    "Line number of parent/caretaker (for malaria testing)"
label variable hml31    "Read consent statement for malaria"
label variable hml32    "Final result of malaria from blood smear test"
label variable hml32a   "Presence of species: falciparum (Pf)"
label variable hml32b   "Presence of species: malariae (Pm)"
label variable hml32c   "Presence of species: ovale (Po)"
label variable hml32d   "Presence of species: vivax (Pv)"
label variable hml32e   "NA - Presence of species: CS"
label variable hml32f   "NA - Presence of species: CS"
label variable hml32g   "NA - Presence of species: CS"
label variable hml33    "Result of malaria measurement"
label variable hml34    "Bar code for blood smear sample"
label variable hml35    "Result of malaria rapid test"
label variable hml36    "Fieldworker measurer code for malaria"
label variable sml16a   "Child's age in months ( country specific version of HML16A )"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV022   
     1 "Urban Nairobi"
     2 "Rural Nyandarua"
     3 "Urban Nyandarua"
     4 "Rural Nyeri"
     5 "Urban Nyeri"
     6 "Rural Kirinyaga"
     7 "Urban Kirinyaga"
     8 "Rural Muranga"
     9 "Urban Muranga"
    10 "Rural Kiambu"
    11 "Urban Kiambu"
    12 "Urban Mombasa"
    13 "Rural Kwale"
    14 "Urban Kwale"
    15 "Rural Kilifi"
    16 "Urban Kilifi"
    17 "Rural Tana River"
    18 "Urban Tana River"
    19 "Rural Lamu"
    20 "Urban Lamu"
    21 "Rural Taita Taveta"
    22 "Urban Taita Taveta"
    23 "Rural Marsabit"
    24 "Urban Marsabit"
    25 "Rural Isiolo"
    26 "Urban Isiolo"
    27 "Rural Meru"
    28 "Urban Meru"
    29 "Rural Tharaka"
    30 "Urban Tharaka"
    31 "Rural Embu"
    32 "Urban Embu"
    33 "Rural Kitui"
    34 "Urban Kitui"
    35 "Rural Machakos"
    36 "Urban Machakos"
    37 "Rural Makueni"
    38 "Urban Makueni"
    39 "Rural Garissa"
    40 "Urban Garissa"
    41 "Rural Wajir"
    42 "Urban Wajir"
    43 "Rural Mandera"
    44 "Urban Mandera"
    45 "Rural Siaya"
    46 "Urban Siaya"
    47 "Rural Kisumu"
    48 "Urban Kisumu"
    49 "Rural Migori"
    50 "Urban Migori"
    51 "Rural Homa Bay"
    52 "Urban Homa Bay"
    53 "Rural Kisii"
    54 "Urban Kisii"
    55 "Rural Nyamira"
    56 "Urban Nyamira"
    57 "Rural Turkana"
    58 "Urban Turkana"
    59 "Rural West Pokot"
    60 "Urban West Pokot"
    61 "Rural Samburu"
    62 "Urban Samburu"
    63 "Rural Trans-Nzoia"
    64 "Urban Trans-Nzoia"
    65 "Rural Baringo"
    66 "Urban Baringo"
    67 "Rural Uasin Gishu"
    68 "Urban Uasin Gishu"
    69 "Rural Elgeyo Marakwet"
    70 "Urban Elgeyo Marakwet"
    71 "Rural Nandi"
    72 "Urban Nandi"
    73 "Rural Laikipia"
    74 "Urban Laikipia"
    75 "Rural Nakuru"
    76 "Urban Nakuru"
    77 "Rural Narok"
    78 "Urban Narok"
    79 "Rural Kajiado"
    80 "Urban Kajiado"
    81 "Rural Kericho"
    82 "Urban Kericho"
    83 "Rural Bomet"
    84 "Urban Bomet"
    85 "Rural Kakamega"
    86 "Urban Kakamega"
    87 "Rural Vihiga"
    88 "Urban Vihiga"
    89 "Rural Bungoma"
    90 "Urban Bungoma"
    91 "Rural Busia"
    92 "Urban Busia"
;
label define HV023   
     1 "Urban Nairobi"
     2 "Rural Nyandarua"
     3 "Urban Nyandarua"
     4 "Rural Nyeri"
     5 "Urban Nyeri"
     6 "Rural Kirinyaga"
     7 "Urban Kirinyaga"
     8 "Rural Muranga"
     9 "Urban Muranga"
    10 "Rural Kiambu"
    11 "Urban Kiambu"
    12 "Urban Mombasa"
    13 "Rural Kwale"
    14 "Urban Kwale"
    15 "Rural Kilifi"
    16 "Urban Kilifi"
    17 "Rural Tana River"
    18 "Urban Tana River"
    19 "Rural Lamu"
    20 "Urban Lamu"
    21 "Rural Taita Taveta"
    22 "Urban Taita Taveta"
    23 "Rural Marsabit"
    24 "Urban Marsabit"
    25 "Rural Isiolo"
    26 "Urban Isiolo"
    27 "Rural Meru"
    28 "Urban Meru"
    29 "Rural Tharaka"
    30 "Urban Tharaka"
    31 "Rural Embu"
    32 "Urban Embu"
    33 "Rural Kitui"
    34 "Urban Kitui"
    35 "Rural Machakos"
    36 "Urban Machakos"
    37 "Rural Makueni"
    38 "Urban Makueni"
    39 "Rural Garissa"
    40 "Urban Garissa"
    41 "Rural Wajir"
    42 "Urban Wajir"
    43 "Rural Mandera"
    44 "Urban Mandera"
    45 "Rural Siaya"
    46 "Urban Siaya"
    47 "Rural Kisumu"
    48 "Urban Kisumu"
    49 "Rural Migori"
    50 "Urban Migori"
    51 "Rural Homa Bay"
    52 "Urban Homa Bay"
    53 "Rural Kisii"
    54 "Urban Kisii"
    55 "Rural Nyamira"
    56 "Urban Nyamira"
    57 "Rural Turkana"
    58 "Urban Turkana"
    59 "Rural West Pokot"
    60 "Urban West Pokot"
    61 "Rural Samburu"
    62 "Urban Samburu"
    63 "Rural Trans-Nzoia"
    64 "Urban Trans-Nzoia"
    65 "Rural Baringo"
    66 "Urban Baringo"
    67 "Rural Uasin Gishu"
    68 "Urban Uasin Gishu"
    69 "Rural Elgeyo Marakwet"
    70 "Urban Elgeyo Marakwet"
    71 "Rural Nandi"
    72 "Urban Nandi"
    73 "Rural Laikipia"
    74 "Urban Laikipia"
    75 "Rural Nakuru"
    76 "Urban Nakuru"
    77 "Rural Narok"
    78 "Urban Narok"
    79 "Rural Kajiado"
    80 "Urban Kajiado"
    81 "Rural Kericho"
    82 "Urban Kericho"
    83 "Rural Bomet"
    84 "Urban Bomet"
    85 "Rural Kakamega"
    86 "Urban Kakamega"
    87 "Rural Vihiga"
    88 "Urban Vihiga"
    89 "Rural Bungoma"
    90 "Urban Bungoma"
    91 "Rural Busia"
    92 "Urban Busia"
;
label define HV024   
     1 "Coast"
     2 "North Eastern"
     3 "Eastern"
     4 "Central"
     5 "Rift Valley"
     7 "Western"
     8 "Nyanza"
     9 "Nairobi"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV045A  
     1 "English"
     2 "Kiswahili"
;
label define HV045B  
     1 "English"
     2 "Kiswahili"
     3 "Borana"
     4 "Embu"
     5 "Kalenjin"
     6 "Kamba"
     7 "Kikuyu"
     8 "Kisii"
     9 "Luhya"
    10 "Maragoli"
    11 "Luo"
    12 "Maasi"
    13 "Meru"
    14 "Mijkenda"
    15 "Pokot"
    16 "Somali"
    17 "Turkana"
    96 "Other"
;
label define HV045C  
     1 "English"
     2 "Kiswahili"
     3 "Borana"
     4 "Embu"
     5 "Kalenjin"
     6 "Kamba"
     7 "Kikuyu"
     8 "Kisii"
     9 "Luhya"
    10 "Maragoli"
    11 "Luo"
    12 "Maasi"
    13 "Meru"
    14 "Mijkenda"
    15 "Pokot"
    16 "Somali"
    17 "Turkana"
    96 "Other"
;
label define HV046   
     0 "No"
     1 "Yes"
;
label define HV801   
  9999 "Missing"
;
label define HV802   
  9999 "Missing"
;
label define HV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define HV804   
     9 "Missing"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV201A  
     0 "No, not interrupted for a full day"
     1 "Yes, interrupted for a full day or more"
     8 "Don't know"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
;
label define HV214   
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Dirt"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
;
label define HV215   
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Iron sheets"
    32 "Wood"
    33 "Calamine/cement fiber"
    34 "Brick/clay tiles"
    35 "Cement"
    36 "Roofing shingles"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    12 "Solar"
    13 "Alcohol/ethanol"
    14 "Gasoline/diesel"
    95 "No food cooked in house"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV238A  
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     0 "Neither chimney or hood"
     1 "Chimney"
     2 "Hood"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV243E  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
   950 "95 or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HV270A  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SHCOUNTY
   101 "Nairobi"
   201 "Nyandarua"
   202 "Nyeri"
   203 "Kirinyaga"
   204 "Muranga"
   205 "Kiambu"
   301 "Mombasa"
   302 "Kwale"
   303 "Kilifi"
   304 "Tana River"
   305 "Lamu"
   306 "Taita Taveta"
   401 "Marsabit"
   402 "Isiolo"
   403 "Meru"
   404 "Tharaka"
   405 "Embu"
   406 "Kitui"
   407 "Machakos"
   408 "Makueni"
   501 "Garissa"
   502 "Wajir"
   503 "Mandera"
   601 "Siaya"
   602 "Kisumu"
   603 "Migori"
   604 "Homa Bay"
   605 "Kisii"
   606 "Nyamira"
   701 "Turkana"
   702 "West Pokot"
   703 "Samburu"
   704 "Trans-Nzoia"
   705 "Baringo"
   706 "Uasin Gishu"
   707 "Elgeyo Marakwet"
   708 "Nandi"
   709 "Laikipia"
   710 "Nakuru"
   711 "Narok"
   712 "Kajiado"
   713 "Kericho"
   714 "Bomet"
   801 "Kakamega"
   802 "Vihiga"
   803 "Bungoma"
   804 "Busia"
;
label define SHZONE  
     1 "Highland Epidemic Prone"
     2 "Lake Endemic"
     3 "Coastal Endemic"
     4 "Seasonal"
     5 "Low Risk"
;
label define SH109   
     1 "Electric stove"
     2 "Solar cooker"
     3 "Liquefied petroleum gas (LPG)/cooking gas stove"
     4 "Piped natural gas stove"
     5 "Biogas stove"
     6 "Liquid fuel stove"
     7 "Manufactured solid fuel stove"
     8 "Traditional solid fuel stove"
     9 "Three stone stove/open fire"
    95 "No food cooked in household"
    96 "Other"
;
label define SH110   
     1 "Alcohol/ethanol"
     2 "Gasoline/diesel"
     3 "Kerosene/paraffin"
     4 "Coal/lignite"
     5 "Charcoal"
     6 "Wood"
     7 "Straw/shrubs/grass"
     8 "Agricultural crop"
     9 "Animal dung/waste"
    10 "Processed biomass (pellets) or woodchips"
    11 "Garbage/plastic"
    12 "Sawdust"
    96 "Other"
;
label define SH116G  
     0 "No"
     1 "Yes"
;
label define SH116H  
     0 "No"
     1 "Yes"
;
label define SH116I  
     0 "No"
     1 "Yes"
;
label define SH116J  
     0 "No"
     1 "Yes"
;
label define SH116K  
     0 "No"
     1 "Yes"
;
label define SH116L  
     0 "No"
     1 "Yes"
;
label define SH116M  
     0 "No"
     1 "Yes"
;
label define SH116N  
     0 "No"
     1 "Yes"
;
label define SH116O  
     0 "No"
     1 "Yes"
;
label define SH116P  
     0 "No"
     1 "Yes"
;
label define SH119   
     0 "No"
     1 "Yes"
;
label define SH119A  
     0 "No"
     1 "Yes"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster/step child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    98 "Don't know"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HC1     
    60 "60+"
;
label define HC1A    
  2501 "2501+"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present/other"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC62    
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary"
     2 "Post-primary/vocational"
     3 "Secondary/'A' level"
     4 "College (middle level)"
     5 "University"
     8 "Don't know"
;
label define SB115A  
     0 "No"
     1 "Yes"
;
label define SB115B  
     0 "No"
     1 "Yes"
;
label define SB115C  
     0 "No"
     1 "Yes"
;
label define SB115D  
     0 "No"
     1 "Yes"
;
label define SB115E  
     0 "No"
     1 "Yes"
;
label define SB115F  
     0 "No"
     1 "Yes"
;
label define SB115G  
     0 "No"
     1 "Yes"
;
label define SB115H  
     0 "No"
     1 "Yes"
;
label define SB119   
     0 "No"
     1 "Yes"
;
label define SB122   
     1 "Accepted medicine"
     2 "Refused"
     6 "Other"
;
label define SB128D  
    98 "Don't know"
;
label define SB128M  
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    98 "DK month"
;
label define SB128Y  
  2020 "2020"
  2021 "2021"
;
label define HML3    
     0 "Not seen"
     1 "Yes, seen"
;
label define HML4    
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML5    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HML6    
     0 "Not pretreated"
     1 "Pretreated, permanent treatment"
     2 "Pretreated, requiring future treatment"
     3 "Not pretreated, came with kit and treated at home"
     4 "Pretreated, treatment type not known"
     6 "Other"
     8 "Don't know"
;
label define HML7    
    10 "Long-lasting insecticide treated nets (LLIN)"
    11 "Olyset (Supanet extra)"
    12 "Permanet (Supanet extra)"
    13 "Netprotect"
    14 "Yorkool"
    15 "Dawa Plus"
    16 "Other/Don't know brand (LLIN)"
    20 "Pretreated net"
    96 "Other brand (not LLIN)"
    98 "Don't know type"
;
label define HML8    
     0 "No"
     1 "Yes"
     2 "Permanent/LLIN net"
     8 "Not sure"
;
label define HML9    
    95 "25+ months ago"
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML10   
     0 "No, don't know"
     1 "Yes"
;
label define HML11   
     5 "5+"
;
label define HML21   
     0 "No"
     1 "Yes"
     8 "Not sure (DK)"
;
label define HMLA    
     0 "No one"
;
label define HMLB    
    99 "Missing"
;
label define HMLC    
    99 "Missing"
;
label define HML22   
     0 "No"
     1 "Yes, campaign"
     2 "Yes, antenatal care"
     3 "Yes, child welfare visit"
;
label define HML23   
    10 "Government health facility"
    20 "Private health facility"
    30 "Other sources"
    31 "Pharmacy"
    32 "Shop/market"
    33 "CHW"
    34 "Religious institution"
    35 "School"
    96 "Other"
    98 "Don't know"
;
label define SH130   
     1 "Too hot"
     2 "Don't like net shape/color/size"
     3 "Don't like smell"
     4 "Unable to hang net"
     5 "Slept outdoors"
     6 "Usual user didn't sleep here last night"
     7 "No mosquitoes/no malaria"
     8 "Extra net/saving for later"
     9 "Net too small/short"
    10 "Net brought bedbugs"
    11 "Net in poor condition"
    96 "Other"
;
label define HML12   
     0 "Did not sleep under a net"
     1 "Only treated (ITN) nets"
     2 "Both treated (ITN) and untreated nets"
     3 "Only untreated nets"
;
label define HML13   
     0 "Did not sleep under net"
;
label define HML16   
    97 "97+"
    98 "Don't know"
;
label define HML16A  
    60 "60+"
;
label define HML17   
     0 "No data from Individual file"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HML18   
     0 "Not pregnant, don't know"
     1 "Pregnant"
;
label define HML19   
     0 "No"
     1 "Yes"
;
label define HML20   
     0 "No"
     1 "Yes"
;
label define HML30   
     0 "Not in household"
;
label define HML31   
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define HML32   
     0 "Negative"
     1 "Positive"
     6 "Test undetermined"
     7 "Sample not found in lab database"
;
label define HML32A  
     0 "No"
     1 "Yes"
;
label define HML32B  
     0 "No"
     1 "Yes"
;
label define HML32C  
     0 "No"
     1 "Yes"
;
label define HML32D  
     0 "No"
     1 "Yes"
;
label define HML32E  
     0 "No"
     1 "Yes"
;
label define HML32F  
     0 "No"
     1 "Yes"
;
label define HML32G  
     0 "No"
     1 "Yes"
;
label define HML33   
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HML35   
     0 "Negative"
     1 "Positive"
;

#delimit cr
label values hv003    HV003   
label values hv015    HV015   
label values hv020    HV020   
label values hv022    HV022   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv045a   HV045A  
label values hv045b   HV045B  
label values hv045c   HV045C  
label values hv046    HV046   
label values hv803    HV803   
label values hv201    HV201   
label values hv202    HV202   
label values hv201a   HV201A  
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv235    HV235   
label values hv238    HV238   
label values hv238a   HV238A  
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv243e   HV243E  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv270    HV270   
label values hv270a   HV270A  
label values hml1     HML1    
label values shcounty SHCOUNTY
label values shzone   SHZONE  
label values sh109    SH109   
label values sh110    SH110   
label values sh116g   SH116G  
label values sh116h   SH116H  
label values sh116i   SH116I  
label values sh116j   SH116J  
label values sh116k   SH116K  
label values sh116l   SH116L  
label values sh116m   SH116M  
label values sh116n   SH116N  
label values sh116o   SH116O  
label values sh116p   SH116P  
label values sh119    SH119   
label values sh119a   SH119A  
label values hv101    HV101   
label values hv102    HV102   
label values hv103    HV103   
label values hv104    HV104   
label values hv105    HV105   
label values hv117    HV117   
label values hv120    HV120   
label values hc1      HC1     
label values hc1a     HC1A    
label values hc16     HC16    
label values hc27     HC27    
label values hc30     HC30    
label values hc31     HC31    
label values hc33     HC33    
label values hc51     HC51    
label values hc52     HC52    
label values hc53     HC53    
label values hc55     HC55    
label values hc56     HC56    
label values hc57     HC57    
label values hc58     HC58    
label values hc60     HC60    
label values hc61     HC61    
label values hc62     HC62    
label values hc68     HC68    
label values sb115a   SB115A  
label values sb115b   SB115B  
label values sb115c   SB115C  
label values sb115d   SB115D  
label values sb115e   SB115E  
label values sb115f   SB115F  
label values sb115g   SB115G  
label values sb115h   SB115H  
label values sb119    SB119   
label values sb122    SB122   
label values sb128d   SB128D  
label values sb128m   SB128M  
label values sb128y   SB128Y  
label values hml3     HML3    
label values hml4     HML4    
label values hml5     HML5    
label values hml6     HML6    
label values hml7     HML7    
label values hml8     HML8    
label values hml9     HML9    
label values hml10    HML10   
label values hml11    HML11   
label values hml21    HML21   
label values hmla     HMLA    
label values hml22    HML22   
label values hml23    HML23   
label values sh130    SH130   
label values hml12    HML12   
label values hml13    HML13   
label values hml16    HML16   
label values hml16a   HML16A  
label values hml17    HML17   
label values hml18    HML18   
label values hml19    HML19   
label values hml20    HML20   
label values hml30    HML30   
label values hml31    HML31   
label values hml32    HML32   
label values hml32a   HML32A  
label values hml32b   HML32B  
label values hml32c   HML32C  
label values hml32d   HML32D  
label values hml32e   HML32E  
label values hml32f   HML32F  
label values hml32g   HML32G  
label values hml33    HML33   
label values hml35    HML35   
