infix using "C:\COUNTRIES\CD51\CDMR51FL.dct"

label variable mcaseid  "Case Identification"
label variable mv000    "Country code and phase"
label variable mv001    "Cluster number"
label variable mv002    "Household number"
label variable mv003    "Respondent's line number"
label variable mv004    "Ultimate area unit"
label variable mv005    "Sample weight"
label variable mv006    "Month of interview"
label variable mv007    "Year of interview"
label variable mv008    "Date of interview (CMC)"
label variable mv009    "Respondent's month of birth"
label variable mv010    "Respondent's year of birth"
label variable mv011    "Date of birth (CMC)"
label variable mv012    "Current age - respondent"
label variable mv013    "Age 5-year groups"
label variable mv014    "Completeness of information"
label variable mv015    "Result of individual interview"
label variable mv016    "Day of interview"
label variable mv021    "Primary sampling unit"
label variable mv022    "Sample stratum number"
label variable mv023    "Sample domain"
label variable mv024    "Region"
label variable mv025    "Type of place of residence"
label variable mv026    "De facto place of residence"
label variable mv027    "Number of visits"
label variable mv028    "Interviewer identification"
label variable mv029    "Keyer identification"
label variable mv030    "Field supervisor"
label variable mv031    "Field editor"
label variable mv032    "Office editor"
label variable mv033    "Ultimate area selection pro-NA"
label variable mv034_1  "Line numbers of wives, partners"
label variable mv034_2  "Line numbers of wives, partners"
label variable mv034_3  "Line numbers of wives, partners"
label variable mv034_4  "Line numbers of wives, partners"
label variable mv034_5  "Line numbers of wives, partners"
label variable mv034_6  "Line numbers of wives, partners"
label variable mv034_7  "Line numbers of wives, partners"
label variable mv034_8  "Line numbers of wives, partners"
label variable mv034a_1 "Wife or partner"
label variable mv034a_2 "Wife or partner"
label variable mv034a_3 "Wife or partner"
label variable mv034a_4 "Wife or partner"
label variable mv034a_5 "Wife or partner"
label variable mv034a_6 "Wife or partner"
label variable mv034a_7 "Wife or partner"
label variable mv034a_8 "Wife or partner"
label variable mv034b_1 "Age of wife/partner"
label variable mv034b_2 "Age of wife/partner"
label variable mv034b_3 "Age of wife/partner"
label variable mv034b_4 "Age of wife/partner"
label variable mv034b_5 "Age of wife/partner"
label variable mv034b_6 "Age of wife/partner"
label variable mv034b_7 "Age of wife/partner"
label variable mv034b_8 "Age of wife/partner"
label variable mv035    "Number of wives, partners"
label variable mv801    "Time interview started"
label variable mv802    "Time interview ended"
label variable mv803    "Length of interview in minutes"
label variable mv101    "Region"
label variable mv102    "Type of place of residence"
label variable mv103    "Childhood place of residence"
label variable mv104    "Years lived in place of res."
label variable mv105    "Type of place of previous res."
label variable mv106    "Highest educational level"
label variable mv107    "Highest year of education"
label variable mv130    "Religion"
label variable mv131    "Ethnicity"
label variable mv133    "Education in single years"
label variable mv134    "De facto place of residence"
label variable mv135    "Usual resident or visitor"
label variable mv136    "Number of household members"
label variable mv138    "Number of eligible men in HH"
label variable mv149    "Educational attainment"
label variable mv150    "Relationship to household head"
label variable mv151    "Sex of household head"
label variable mv152    "Age of household head"
label variable mv155    "Literacy"
label variable mv156    "Ever participated in a literacy program outside of primary"
label variable mv157    "Frequency of reading newpaper or magazine"
label variable mv158    "Frequency of listening to radio"
label variable mv159    "Frequency of watching television"
label variable mv167    "Times away from home in last 12 months"
label variable mv168    "Away for more than one month"
label variable mv190    "Wealth index"
label variable mv191    "Wealth index factor score (5 decimals)"
label variable mv201    "Total children ever born"
label variable mv202    "Sons at home"
label variable mv203    "Daughters at home"
label variable mv204    "Sons elsewhere"
label variable mv205    "Daughters elsewhere"
label variable mv206    "Sons who have died"
label variable mv207    "Daughters who have died"
label variable mv212    "Age of respondent at 1st birth"
label variable mv213    "Partner currently pregnant"
label variable mv217    "Knowledge of ovulatory cycle"
label variable mv218    "Number of living children"
label variable mv225    "Current pregnancy wanted   -NA"
label variable mv245    "Women fathered children with"
label variable mv246    "Married to mother when firs-NA"
label variable mv247    "Age of youngest child      -NA"
label variable mv248    "Antenatal check-ups for the-NA"
label variable mv249    "Respondent present during c-NA"
label variable mv250    "Place of birth of youngest -NA"
label variable mv251    "Reason for not delivering y-NA"
label variable mv252    "Drinking pattern when child-NA"
label variable mv301    "Knowledge of any method"
label variable mv302    "Ever use of any method"
label variable m304a_01 "Type of method"
label variable m304a_02 "Type of method"
label variable m304a_03 "Type of method"
label variable m304a_04 "Type of method"
label variable m304a_05 "Type of method"
label variable m304a_06 "Type of method"
label variable m304a_07 "Type of method"
label variable m304a_08 "Type of method"
label variable m304a_09 "Type of method"
label variable m304a_10 "Type of method"
label variable m304a_11 "Type of method"
label variable m304a_12 "Type of method"
label variable m304a_13 "Type of method"
label variable m304a_14 "Type of method"
label variable m304a_15 "Type of method"
label variable m304a_16 "Type of method"
label variable m304a_17 "Type of method"
label variable m304a_18 "Type of method"
label variable m304a_19 "Type of method"
label variable m304a_20 "Type of method"
label variable mv304_01 "Knows method"
label variable mv304_02 "Knows method"
label variable mv304_03 "Knows method"
label variable mv304_04 "Knows method"
label variable mv304_05 "Knows method"
label variable mv304_06 "Knows method"
label variable mv304_07 "Knows method"
label variable mv304_08 "Knows method"
label variable mv304_09 "Knows method"
label variable mv304_10 "Knows method"
label variable mv304_11 "Knows method"
label variable mv304_12 "Knows method"
label variable mv304_13 "Knows method"
label variable mv304_14 "Knows method"
label variable mv304_15 "Knows method"
label variable mv304_16 "Knows method"
label variable mv304_17 "Knows method"
label variable mv304_18 "Knows method"
label variable mv304_19 "Knows method"
label variable mv304_20 "Knows method"
label variable mv305_01 "Ever used method           -NA"
label variable mv305_02 "Ever used method           -NA"
label variable mv305_03 "Ever used method           -NA"
label variable mv305_04 "Ever used method           -NA"
label variable mv305_05 "Ever used method           -NA"
label variable mv305_06 "Ever used method           -NA"
label variable mv305_07 "Ever used method           -NA"
label variable mv305_08 "Ever used method           -NA"
label variable mv305_09 "Ever used method           -NA"
label variable mv305_10 "Ever used method           -NA"
label variable mv305_11 "Ever used method           -NA"
label variable mv305_12 "Ever used method           -NA"
label variable mv305_13 "Ever used method           -NA"
label variable mv305_14 "Ever used method           -NA"
label variable mv305_15 "Ever used method           -NA"
label variable mv305_16 "Ever used method           -NA"
label variable mv305_17 "Ever used method           -NA"
label variable mv305_18 "Ever used method           -NA"
label variable mv305_19 "Ever used method           -NA"
label variable mv305_20 "Ever used method           -NA"
label variable mv307_01 "Method currently used      -NA"
label variable mv307_02 "Method currently used      -NA"
label variable mv307_03 "Method currently used      -NA"
label variable mv307_04 "Method currently used      -NA"
label variable mv307_05 "Method currently used      -NA"
label variable mv307_06 "Method currently used      -NA"
label variable mv307_07 "Method currently used      -NA"
label variable mv307_08 "Method currently used      -NA"
label variable mv307_09 "Method currently used      -NA"
label variable mv307_10 "Method currently used      -NA"
label variable mv307_11 "Method currently used      -NA"
label variable mv307_12 "Method currently used      -NA"
label variable mv307_13 "Method currently used      -NA"
label variable mv307_14 "Method currently used      -NA"
label variable mv307_15 "Method currently used      -NA"
label variable mv307_16 "Method currently used      -NA"
label variable mv307_17 "Method currently used      -NA"
label variable mv307_18 "Method currently used      -NA"
label variable mv307_19 "Method currently used      -NA"
label variable mv307_20 "Method currently used      -NA"
label variable mv312    "Current contraceptive metho-NA"
label variable mv313    "Current use by method type -NA"
label variable mv323a   "Brand of condom used       -NA"
label variable mv325b   "Cost of condoms last time o-NA"
label variable mv372a   "Shown condom package       -NA"
label variable mv384a   "Heard FP on radio last mont-NA"
label variable mv384b   "Heard FP on TV last months -NA"
label variable mv384c   "Heard FP newspaper last mon-NA"
label variable mv395    "Discussed FP with health worker last few months"
label variable mv396    "Can a woman who is breastfeeding get pregnant"
label variable mv3a09b  "How many condoms did get la-NA"
label variable mv3b17   "Source of condoms"
label variable mv3b25a  "Contraception is woman's business, man should not worry"
label variable mv3b25b  "Women who use contraception become promiscuous"
label variable mv463a   "Smokes cigarettes          -NA"
label variable mv463b   "Smokes pipe                -NA"
label variable mv463c   "Cheweing  tobacco          -NA"
label variable mv463d   "Smokes Snuff               -NA"
label variable mv463e   "Smokes country specific    -NA"
label variable mv463f   "Smokes country specific    -NA"
label variable mv463g   "Smokes country specific    -NA"
label variable mv463x   "Smokes other               -NA"
label variable mv463z   "Smokes nothing             -NA"
label variable mv464    "Number of cigarettes in las-NA"
label variable mv474    "Heard of Tuberculosis or TB-NA"
label variable mv474a   "Tuberculosis spread by: air-NA"
label variable mv474b   "Tuberculosis spread by: sha-NA"
label variable mv474c   "Tuberculosis spread by: tou-NA"
label variable mv474d   "Tuberculosis spread through-NA"
label variable mv474e   "Tuberculosis spread by: sex-NA"
label variable mv474f   "Tuberculosis spread by: mos-NA"
label variable mv474g   "Tuberculosis spread by: CS -NA"
label variable mv474h   "Tuberculosis spread by: CS -NA"
label variable mv474i   "Tuberculosis spread by: CS -NA"
label variable mv474j   "Tuberculosis spread by: CS -NA"
label variable mv474x   "Tuberculosis spread by: oth-NA"
label variable mv474z   "Tuberculosis spread by: don-NA"
label variable mv475    "Can tuberculosis be cured  -NA"
label variable mv476    "Keep secret when family mem-NA"
label variable mv477    "Number of injections in las-NA"
label variable mv478    "Injections administered by -NA"
label variable mv479    "Source for injection by hea-NA"
label variable mv480    "Syinge and needle from new,-NA"
label variable mv481    "Covered by health insurance-NA"
label variable mv481a   "Health insurance type: mutu-NA"
label variable mv481b   "Health insurance type: prov-NA"
label variable mv481c   "Health insurance type: soci-NA"
label variable mv481d   "Health insurance type: priv-NA"
label variable mv481e   "Health insurance type: CS  -NA"
label variable mv481f   "Health insurance type: CS  -NA"
label variable mv481g   "Health insurance type: CS  -NA"
label variable mv481h   "Health insurance type: CS  -NA"
label variable mv481x   "Health insurance type: othe-NA"
label variable mv482a   "Arrange care of biological -NA"
label variable mv482b   "Primary caregiver of childr-NA"
label variable mv482c   "Arrange care of non-biologi-NA"
label variable mv483    "Is respondent circumcised"
label variable mv501    "Current marital status"
label variable mv502    "Currently/formerly/never marr."
label variable mv503    "Number of unions"
label variable mv504    "Wife/partner lives with res-NA"
label variable mv505    "Number of wives, partners"
label variable mv507    "Month of first marriage"
label variable mv508    "Year of first marriage"
label variable mv509    "Date of first marriage (CMC)"
label variable mv510    "Completeness of date inform."
label variable mv511    "Age at first marriage"
label variable mv512    "Years since first marriage"
label variable mv513    "Marital duration (grouped)"
label variable mv525    "Age at first intercourse"
label variable mv527    "Time since last intercourse"
label variable mv528    "Time since last intercourse(g)"
label variable mv529    "Time since last intercourse(imputed)"
label variable mv531    "Age at first intercourse (imp)"
label variable mv532    "Flag for MV531"
label variable mv535    "Have ever been married"
label variable mv536    "Recent sexual activity"
label variable mv541    "Intend to wait until married to have sex"
label variable mv602    "Fertility preference"
label variable mv603    "Preferred waiting time"
label variable mv604    "Preferred waiting time (grpd)"
label variable mv605    "Desire for more children"
label variable mv613    "Ideal number of children"
label variable mv614    "Ideal number of children (grp)"
label variable mv616    "Time for future birth"
label variable mv621    "Wifes desire for children  -NA"
label variable mv627    "Ideal number of boys"
label variable mv628    "Ideal number of girls"
label variable mv629    "Ideal number of either sex"
label variable mv631    "Problem if became pregnant -NA"
label variable mv633a   "Reason for not having sex: -NA"
label variable mv633b   "Reason for not having sex: -NA"
label variable mv633c   "Reason for not having sex: -NA"
label variable mv633d   "Reason for not having sex: -NA"
label variable mv633e   "Reason for not having sex: -NA"
label variable mv633f   "Reason for not having sex: -NA"
label variable mv633g   "Reason for not having sex: -NA"
label variable mv634a   "Husband has right to: get a-NA"
label variable mv634b   "Husband has right to: refus-NA"
label variable mv634c   "Husband has right to: use f-NA"
label variable mv634d   "Husband has right to: have -NA"
label variable mv714    "Respondent currently working"
label variable mv714a   "Have a job from which respo-NA"
label variable mv716    "Respondent's occupation"
label variable mv717    "Respondent's occupation"
label variable mv719    "Work for family, others, se-NA"
label variable mv721    "Works at home or away      -NA"
label variable mv731    "Worked in last 12 months"
label variable mv732    "Employment all year/seasona-NA"
label variable mv739    "Who decides how to spend money"
label variable mv740    "Type of land where resp. works"
label variable mv741    "Type of earnings for work"
label variable mv743a   "Final say on own health car-NA"
label variable mv743b   "Final say on making large h-NA"
label variable mv743c   "Final say on making househo-NA"
label variable mv743d   "Final say on visits to fami-NA"
label variable mv743e   "Final say on food to be coo-NA"
label variable mv743f   "Final say on deciding what -NA"
label variable mv743g   "Final say on deciding how m-NA"
label variable mv744a   "Wife beating justified if s-NA"
label variable mv744b   "Wife beating justified if s-NA"
label variable mv744c   "Wife beating justified if s-NA"
label variable mv744d   "Wife beating justified if s-NA"
label variable mv744e   "Wife beating justified if s-NA"
label variable mv747a   "Childbearing is a woman's c-NA"
label variable mv747b   "Important for mother/child -NA"
label variable mv750    "Heard sexual transmit. disease"
label variable mv751    "Ever heard of AIDS"
label variable mv754bp  "Reduce risk of getting AIDS by not having sex at all"
label variable mv754cp  "Reduce chances of AIDS by always using condoms during sex"
label variable mv754dp  "Reduce chance of AIDS: have 1 sex partner with no oth partnr"
label variable mv754jp  "Get AIDS from mosquito bites"
label variable mv754wp  "Get AIDS by sharing food with person who has AIDS"
label variable mv756    "Can a healthy person have AIDS"
label variable mv761    "Last intercourse used condom"
label variable mv761b   "Intercourse with other woman (1) used condom"
label variable mv761c   "Intercourse with other woman (2) used condom"
label variable mv762aa  "Source for condoms: Government hospital"
label variable mv762ab  "Source for condoms: Government health center/post"
label variable mv762ac  "Source for condoms: Family planning clinic"
label variable mv762ad  "Source for condoms: Mobile -NA"
label variable mv762ae  "Source for condoms: Public field worker"
label variable mv762af  "Source for condoms: Other public"
label variable mv762ag  "Source for condoms: Public -NA"
label variable mv762ah  "Source for condoms: Public -NA"
label variable mv762ai  "Source for condoms: Public -NA"
label variable mv762aj  "Source for condoms: Private hosp, clinic"
label variable mv762ak  "Source for condoms: Pharmacy"
label variable mv762al  "Source for condoms: Private-NA"
label variable mv762am  "Source for condoms: Private-NA"
label variable mv762an  "Source for condoms: Private field worker"
label variable mv762ao  "Source for condoms: Other private"
label variable mv762ap  "Source for condoms: Amo Congo (CS)"
label variable mv762aq  "Source for condoms: Private-NA"
label variable mv762ar  "Source for condoms: Private-NA"
label variable mv762as  "Source for condoms: Shop"
label variable mv762at  "Source for condoms: Church -NA"
label variable mv762au  "Source for condoms: Friends, relatives"
label variable mv762av  "Source for condoms: Bar/nightclub (CS)"
label variable mv762aw  "Source for condoms: Kiosk/Street Vendor (CS)"
label variable mv762ax  "Source for condoms: Other"
label variable mv762az  "Source for condoms: DK source for condom"
label variable mv762ba  "Source for female condoms: -NA"
label variable mv762bb  "Source for female condoms: -NA"
label variable mv762bc  "Source for female condoms: -NA"
label variable mv762bd  "Source for female condoms: -NA"
label variable mv762be  "Source for female condoms: -NA"
label variable mv762bf  "Source for female condoms: -NA"
label variable mv762bg  "Source for female condoms: -NA"
label variable mv762bh  "Source for female condoms: -NA"
label variable mv762bi  "Source for female condoms: -NA"
label variable mv762bj  "Source for female condoms: -NA"
label variable mv762bk  "Source for female condoms: -NA"
label variable mv762bl  "Source for female condoms: -NA"
label variable mv762bm  "Source for female condoms: -NA"
label variable mv762bn  "Source for female condoms: -NA"
label variable mv762bo  "Source for female condoms: -NA"
label variable mv762bp  "Source for female condoms: -NA"
label variable mv762bq  "Source for female condoms: -NA"
label variable mv762br  "Source for female condoms: -NA"
label variable mv762bs  "Source for female condoms: -NA"
label variable mv762bt  "Source for female condoms: -NA"
label variable mv762bu  "Source for female condoms: -NA"
label variable mv762bv  "Source for female condoms: -NA"
label variable mv762bw  "Source for female condoms: -NA"
label variable mv762bx  "Source for female condoms: -NA"
label variable mv762bz  "Source for female condoms: -NA"
label variable mv763a   "Had any STD in last 12 months"
label variable mv763b   "Had genital sore/ulcer in last 12 months"
label variable mv763c   "Had genital discharge in last 12 months"
label variable mv763d   "Last 12 months had CS STD  -NA"
label variable mv763e   "Last 12 months had CS STD  -NA"
label variable mv763f   "Last 12 months had CS STD  -NA"
label variable mv763g   "Last 12 months had CS STD  -NA"
label variable mv766a   "No. other than wife had sex in last 12 months"
label variable mv766b   "No. had sex including wife in last 12 months"
label variable mv767a   "Relationship with last sex partner"
label variable mv767b   "Relationship with other sex partner (1)"
label variable mv767c   "Relationship with other sex partner (2)"
label variable mv768a   "Length of time knows last partner"
label variable mv768b   "Length of time knows other partner (1)"
label variable mv768c   "Length of time knows other partner (2)"
label variable mv769    "Could get a condom"
label variable mv769a   "Could get a female condom  -NA"
label variable mv770    "Seek advice for last disease"
label variable mv770a   "Seek advice ITS: govt hospital"
label variable mv770b   "Seek advice ITS: health center"
label variable mv770c   "Seek advice ITS: public VCT center"
label variable mv770d   "Seek advice ITS: FP clinic"
label variable mv770e   "Seek advice ITS: mobile cli-NA"
label variable mv770f   "Seek advice ITS: fieldworker"
label variable mv770g   "Seek advice ITS: Public CTA clinic (CS)"
label variable mv770h   "Seek advice ITS: Maternity clinic (CS)"
label variable mv770i   "Seek advice ITS: CS public -NA"
label variable mv770j   "Seek advice ITS: other public"
label variable mv770k   "Seek advice ITS: private hosp/clinic/doctor"
label variable mv770l   "Seek advice ITS: private VC-NA"
label variable mv770m   "Seek advice ITS: pharmacy"
label variable mv770n   "Seek advice ITS: mobile cli-NA"
label variable mv770o   "Seek advice ITS: fieldworker"
label variable mv770p   "Seek advice ITS: Private Maternity clinic (CS)"
label variable mv770q   "Seek advice ITS: Private CTA clinic (CS)"
label variable mv770r   "Seek advice ITS: CS private-NA"
label variable mv770s   "Seek advice ITS: other private"
label variable mv770t   "Seek advice ITS: shop"
label variable mv770u   "Seek advice ITS: Traditional healer (CS)"
label variable mv770v   "Seek advice ITS: CS other  -NA"
label variable mv770w   "Seek advice ITS: CS other  -NA"
label variable mv770x   "Seek advice other"
label variable mv774a   "AIDS transmit. during pregnancy"
label variable mv774b   "AIDS transmit. during delivery"
label variable mv774c   "AIDS transmit. by breastfeeding"
label variable mv775    "Knows someone who has or died of AIDS"
label variable mv777    "Allowed to keep AIDS infection secret"
label variable mv778    "Willing to care for relative with AIDS"
label variable mv779    "Person with AIDS allowed to continue teaching"
label variable mv780    "Should children be taught about condoms"
label variable mv781    "Ever been tested for AIDS"
label variable mv783    "Know a place to get AIDS test"
label variable mv784a   "Place for AIDS test: govt hospital"
label variable mv784b   "Place for AIDS test:health center"
label variable mv784c   "Place for AIDS test: public VCT center"
label variable mv784d   "Place for AIDS test: FP clinic"
label variable mv784e   "Place for AIDS test: mobile clinic"
label variable mv784f   "Place for AIDS test: filedw-NA"
label variable mv784g   "Place for AIDS test: CTA clinic (CS)"
label variable mv784h   "Place for AIDS test: CS pub-NA"
label variable mv784i   "Place for AIDS test: CS pub-NA"
label variable mv784j   "Place for AIDS test: other public"
label variable mv784k   "Place for AIDS test: private hosp/clinic/doctor"
label variable mv784l   "Place for AIDS test: privat-NA"
label variable mv784m   "Place for AIDS test: pharma-NA"
label variable mv784n   "Place for AIDS test: mobile clinic"
label variable mv784o   "Place for AIDS test: fieldworker"
label variable mv784p   "Place for AIDS test: private CTA clinic (CS)"
label variable mv784q   "Place for AIDS test: Youth centre (CS)"
label variable mv784r   "Place for AIDS test: CS pri-NA"
label variable mv784s   "Place for AIDS test: other private"
label variable mv784t   "Place for AIDS test: CS oth-NA"
label variable mv784u   "Place for AIDS test: CS oth-NA"
label variable mv784v   "Place for AIDS test: CS oth-NA"
label variable mv784x   "Place for AIDS test: other"
label variable mv785    "Heard about other STDs"
label variable mv793    "Paid for sex last 12 months"
label variable mv793a   "Condom used when paid for sex last 12 months"
label variable mv793b   "Condom used every time paid for sex last 12 months"
label variable mv820    "Condom used at first sexual intercourse"
label variable mv822    "Wife justified to ask husba-NA"
label variable mv823    "Can get AIDS by witchcraft or supernatural means"
label variable mv824    "Drugs to avoid AIDS transmission to baby during pregnancy"
label variable mv825    "Would buy vegetables from vendor with AIDS"
label variable mv826    "When was last time you were tested"
label variable mv827    "Last test was on your own, offered or required"
label variable mv828    "Did get results for last test"
label variable mv829    "Place were last AIDS test was taken"
label variable mv832b   "Time since last intercourse-NA"
label variable mv832c   "Time since last intercourse-NA"
label variable mv833a   "Used condom every time had sex with last sex partner (last 1"
label variable mv833b   "Used condom every time had sex with next to last sex partner"
label variable mv833c   "Used condom every time had sex with second to last sex partn"
label variable mv835a   "Alcohol consumption last time had sex"
label variable mv835b   "Alcohol consumption next to last time had sex"
label variable mv835c   "Alcohol consumption second to last time had sex"
label variable mv836    "Total lifetime number of sexual partners"
label variable mv837    "Heard of drugs to help infected people to live longer"
label variable mv844    "Knows someone denied health services because of AIDS last 12"
label variable mv845    "Knows someone denied social events because of AIDS last 12 m"
label variable mv846    "Knows someone verbally abused because of AIDS last 12 months"
label variable mv847    "People with AIDS should be ashamed of themselves"
label variable mv848    "People with AIDS should be blamed for bringing disease to co"
label variable mv849    "Children 12-14 should wait for sex until marriage"
label variable mv851a   "Young men should wait for s-NA"
label variable mv851b   "Most young men wait for sex-NA"
label variable mv851c   "Unmarried sexually active m-NA"
label variable mv851d   "Most unmarried sexually act-NA"
label variable mv851e   "Married men should only hav-NA"
label variable mv851f   "Most married men only have -NA"
label variable mv851g   "Young women should wait for-NA"
label variable mv851h   "Most young women wait for s-NA"
label variable mv851i   "Unmarried sexually active w-NA"
label variable mv851j   "Most unmarried sexually act-NA"
label variable mv851k   "Married women should only h-NA"
label variable mv851l   "Most married women only hav-NA"
label variable smeduc   "Education categories used in main report tables"
label variable sm121    "Work in last 12 months"
label variable sm130a   "Parents both from same tribe as respondent"
label variable sm130b   "Been sick in last 2 weeks"
label variable sm130c   "Received medical  attention"
label variable sm130d   "How much paid for medical attention"
label variable sm130ea  "Why did not receive medical attention : cost"
label variable sm130eb  "Why did not receive medical attention : distance"
label variable sm130ec  "Why did not receive medical attention : health professionals"
label variable sm130ed  "Why did not receive medical attention : other"
label variable sm304a   "Heard of 'collier' (Safe period) method"
label variable sm306c   "Women should be responsible for using contraception because "
label variable sm405    "Regular or occasional sex partner (married men only)"
label variable sm406    "Regular or occasional sex partner (never married men)"
label variable sm416d   "Age of person with whom had first sex"
label variable sm419a   "Reason condom not used : last partner"
label variable sm419b   "Reason condom not used : second to last partner"
label variable sm419c   "Reason condom not used : third to last partner"
label variable sm422a   "Used method other than condom : last partner"
label variable sm422b   "Used method other than condom : second to last partner"
label variable sm422c   "Used method other than condom : third to last partner"
label variable sm423a   "Method used other than condom : last partner"
label variable sm423b   "Method used other than condom : second to last partner"
label variable sm423c   "Method used other than condom : third to last partner"
label variable sm425a   "Reason did not use method to avoid pregnancy : last partner"
label variable sm425b   "Reason did not use method to avoid pregnancy : second to las"
label variable sm425c   "Reason did not use method to avoid pregnancy : third to last"
label variable sm436b   "Used condom last paid for sex"
label variable sm438c   "Anyone forced respondent to have intercourse"
label variable sm438d   "First intercourse was wanted or forced"
label variable sm438e   "Anyone forced respondent to have intercourse in last 12 m"
label variable sm507    "Approves of Family Planning"
label variable sm511a   "Discussed FP with partner in the last month"
label variable sm511b   "Discussed FP with mother in the last month"
label variable sm511c   "Discussed FP with father in the last month"
label variable sm511d   "Discussed FP with sister(s) in the last month"
label variable sm511e   "Discussed FP with brother(s) in the last month"
label variable sm511f   "Discussed FP with daughter(s) in the last month"
label variable sm511g   "Discussed FP with mother-in-law in the last month"
label variable sm511h   "Discussed FP with friends/nbrs in the last month"
label variable sm511i   "Discussed FP with son(s) in the last month"
label variable sm511x   "Discussed FP with others in the last month"
label variable sm511y   "Discussed FP with no-one in the last month"
label variable sm609a   "Ways to avoid AIDS: abstain from sex"
label variable sm609b   "Ways to avoid AIDS: use condoms during sex"
label variable sm609c   "Ways to avoid AIDS: only one sex partner"
label variable sm609d   "Ways to avoid AIDS: Limit number of sex partners"
label variable sm609e   "Ways to avoid AIDS: avoid sex prostitutes"
label variable sm609f   "Ways to avoid AIDS: Avoid partners who have many partners"
label variable sm609g   "Ways to avoid AIDS: avoid sex homosexuals"
label variable sm609h   "Ways to avoid AIDS: Avoid sex with intravenous drug users"
label variable sm609i   "Ways to avoid AIDS: avoid blood transfusions"
label variable sm609j   "Ways to avoid AIDS: avoid injections"
label variable sm609k   "Ways to avoid AIDS: avoid sharing razor blades with AIDS pat"
label variable sm609l   "Ways to avoid AIDS: avoid kissing"
label variable sm609m   "Ways to avoid AIDS: avoid mosquito bites"
label variable sm609n   "Ways to avoid AIDS: protection trad. healer"
label variable sm609w   "Ways to avoid AIDS: other responses"
label variable sm609x   "Ways to avoid AIDS: other responses"
label variable sm609z   "Ways to avoid AIDS: DK ways to avoid AIDS"
label variable sm642a   "Man's symptoms of STI"
label variable sm642b   "Man's symptoms of STI"
label variable sm642c   "Man's symptoms of STI"
label variable sm642d   "Man's symptoms of STI"
label variable sm642e   "Man's symptoms of STI"
label variable sm642f   "Man's symptoms of STI"
label variable sm642g   "Man's symptoms of STI"
label variable sm642h   "Man's symptoms of STI"
label variable sm642i   "Man's symptoms of STI"
label variable sm642j   "Man's symptoms of STI"
label variable sm642k   "Man's symptoms of STI"
label variable sm642l   "Man's symptoms of STI"
label variable sm642w   "Man's symptoms of STI"
label variable sm642x   "Man's symptoms of STI"
label variable sm642y   "Man's symptoms of STI"
label variable sm642z   "Man's symptoms of STI"
label variable sm643a   "Woman's symptoms of STI"
label variable sm643b   "Woman's symptoms of STI"
label variable sm643c   "Woman's symptoms of STI"
label variable sm643d   "Woman's symptoms of STI"
label variable sm643e   "Woman's symptoms of STI"
label variable sm643f   "Woman's symptoms of STI"
label variable sm643g   "Woman's symptoms of STI"
label variable sm643h   "Woman's symptoms of STI"
label variable sm643i   "Woman's symptoms of STI"
label variable sm643j   "Woman's symptoms of STI"
label variable sm643k   "Woman's symptoms of STI"
label variable sm643l   "Woman's symptoms of STI"
label variable sm643w   "Woman's symptoms of STI"
label variable sm643x   "Woman's symptoms of STI"
label variable sm643y   "Woman's symptoms of STI"
label variable sm643z   "Woman's symptoms of STI"
label variable sm653a   "Source of treatment for partner: govt hospital"
label variable sm653b   "Source of treatment for partner: health center"
label variable sm653c   "Source of treatment for partner: public CTA center"
label variable sm653d   "Source of treatment for partner: STD centre"
label variable sm653e   "Source of treatment for partner: family planning clinic"
label variable sm653f   "Source of treatment for partner: fieldworker"
label variable sm653g   "Source of treatment for partner: Public maternity clinic"
label variable sm653h   "Source of treatment for partner: other public"
label variable sm653i   "Source of treatment for partner: private hosp/clinic/doctor"
label variable sm653j   "Source of treatment for partner: private maternity clinic"
label variable sm653k   "Source of treatment for partner: pharmacy"
label variable sm653l   "Source of treatment for partner: private CTA clinic"
label variable sm653m   "Source of treatment for partner: Private fieldworker"
label variable sm653n   "Source of treatment for partner: Other private medical"
label variable sm653q   "Source of treatment for partner: Traditional healer"
label variable sm653r   "Source of treatment for partner: Shop"
label variable sm653x   "Source of treatment for partner: Other"
label variable sm653y   "Source of treatment for partner: did not seek treatment"
label variable smallwgt "Weight used for combined men/women HIV/AIDS indicators"

#delimit ;
label define MV007   
  2007 "***Undefined Label"
;
label define MV013   
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
     8 "50-54"
     9 "55-59"
    10 "60-64"
;
label define MV014   
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define MV015   
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define MV023   
     0 "National"
     1 "Country specific"
;
label define MV024   
    10 "Kinshasa"
    20 "Bas-Congo"
    30 "Bandundu"
    40 "Equateur"
    50 "Orientale"
    61 "Nord-Kivu"
    62 "Maniema"
    63 "Sud-Kivu"
    70 "Katanga"
    80 "Kasaï Oriental"
    90 "Kasaï Occident"
;
label define MV025   
     1 "Urban"
     2 "Rural"
;
label define MV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV028   
   999 "Missing"
;
label define MV029   
    99 "Missing"
;
label define MV030   
   999 "Missing"
;
label define MV031   
   999 "Missing"
;
label define MV032   
    99 "Missing"
;
label define MV034_1 
     0 "Wife not in HH"
;
label define MV034_2 
     0 "Wife not in HH"
;
label define MV034_3 
     0 "Wife not in HH"
;
label define MV034_4 
     0 "Wife not in HH"
;
label define MV034_5 
     0 "Wife not in HH"
;
label define MV034_6 
     0 "Wife not in HH"
;
label define MV034_7 
     0 "Wife not in HH"
;
label define MV034_8 
     0 "Wife not in HH"
;
label define MV034A_1
     1 "Wife"
     2 "Partner"
;
label define MV034A_2
     1 "Wife"
     2 "Partner"
;
label define MV034A_3
     1 "Wife"
     2 "Partner"
;
label define MV034A_4
     1 "Wife"
     2 "Partner"
;
label define MV034A_5
     1 "Wife"
     2 "Partner"
;
label define MV034A_6
     1 "Wife"
     2 "Partner"
;
label define MV034A_7
     1 "Wife"
     2 "Partner"
;
label define MV034A_8
     1 "Wife"
     2 "Partner"
;
label define MV034B_1
    99 "Missing"
;
label define MV034B_2
    99 "Missing"
;
label define MV034B_3
    99 "Missing"
;
label define MV034B_4
    99 "Missing"
;
label define MV034B_5
    99 "Missing"
;
label define MV034B_6
    99 "Missing"
;
label define MV034B_7
    99 "Missing"
;
label define MV034B_8
    99 "Missing"
;
label define MV035   
     0 "No wives/partners"
;
label define MV801   
  9999 "Missing"
;
label define MV802   
  9999 "Missing"
;
label define MV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define MV101   
    10 "Kinshasa"
    20 "Bas-Congo"
    30 "Bandundu"
    40 "Equateur"
    50 "Orientale"
    61 "Nord-Kivu"
    62 "Maniema"
    63 "Sud-Kivu"
    70 "Katanga"
    80 "Kasaï Oriental"
    90 "Kasaï Occident"
;
label define MV102   
     1 "Urban"
     2 "Rural"
;
label define MV103   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV104   
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV105   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV106   
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define MV107   
    99 "Missing"
;
label define MV130   
     1 "Catholic"
     2 "Protestant"
     3 "Salvation Army"
     4 "Kimbanguist"
     5 "Other Christian"
     6 "Muslim"
     7 "Animist"
     8 "No religion"
    96 "Other"
;
label define MV131   
     1 "Bakongo North and South"
     2 "Bas-Kasai and Kwilu-Kwngo"
     3 "Cuvette central"
     4 "Ubangi and Itimbiri"
     5 "Uele Lake Albert"
     6 "Basele-K , Man. and Kivu"
     7 "Kasai, Katanga, Tanganika"
     8 "Lunda"
     9 "Pygmy"
    96 "Others"
;
label define MV133   
    97 "Inconsistent"
;
label define MV134   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV135   
     1 "Usual resident"
     2 "Visitor"
;
label define MV149   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define MV150   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nehew by blood"
    14 "Niece/nephew by marriage"
    98 "DK"
;
label define MV151   
     1 "Male"
     2 "Female"
;
label define MV152   
    97 "97+"
    98 "DK"
;
label define MV155   
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define MV156   
     0 "No"
     1 "Yes"
;
label define MV157   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV158   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV159   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV167   
    97 "Inconsistent"
    98 "DK"
;
label define MV168   
     0 "No"
     1 "Yes"
;
label define MV190   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define MV212   
    99 "Missing"
;
label define MV213   
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV217   
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define MV225   
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
;
label define MV245   
    99 "Missing"
;
label define MV246   
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV247   
    99 "Missing"
;
label define MV248   
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV249   
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV250   
     1 "***Undefined Label"
     2 "***Undefined Label"
;
label define MV251   
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     4 "***Undefined Label"
     5 "***Undefined Label"
     6 "***Undefined Label"
     7 "***Undefined Label"
     8 "***Undefined Label"
     9 "***Undefined Label"
    96 "***Undefined Label"
    98 "***Undefined Label"
;
label define MV252   
     0 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     4 "***Undefined Label"
     5 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV301   
     0 "Knows no method"
     1 "Knows only folkloric"
     2 "Knows only trad. mth"
     3 "Knows modern method"
;
label define MV302   
     0 "Never used"
     1 "Used only folkloric"
     2 "Used only trad. meth"
     3 "Used modern method"
;
label define M304A_01
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_02
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_03
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_04
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_05
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_06
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_07
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_08
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_09
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_10
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_11
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_12
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_13
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_14
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_15
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_16
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_17
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_18
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_19
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define M304A_20
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define MV304_01
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_02
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_03
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_04
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_05
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_06
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_07
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_08
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_09
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_10
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_11
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_12
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_13
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_14
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_15
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_16
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_17
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_18
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_19
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV304_20
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV305_01
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_02
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_03
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_04
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_05
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_06
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_07
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_08
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_09
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_10
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_11
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_12
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_13
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_14
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_15
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_16
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_17
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_18
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_19
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV305_20
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_01
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_02
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_03
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_04
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_05
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_06
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_07
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_08
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_09
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_10
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_11
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_12
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_13
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_14
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_15
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_16
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_17
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_18
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_19
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV307_20
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV312   
     0 "***Undefined Label"
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     4 "***Undefined Label"
     5 "***Undefined Label"
     6 "***Undefined Label"
     7 "***Undefined Label"
     8 "***Undefined Label"
     9 "***Undefined Label"
    10 "***Undefined Label"
    11 "***Undefined Label"
    12 "***Undefined Label"
    13 "***Undefined Label"
    14 "***Undefined Label"
    15 "***Undefined Label"
    16 "***Undefined Label"
    17 "***Undefined Label"
    18 "***Undefined Label"
    19 "***Undefined Label"
    20 "***Undefined Label"
    98 "***Undefined Label"
;
label define MV313   
     0 "***Undefined Label"
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV323A  
    98 "***Undefined Label"
;
label define MV325B  
9999995 "***Undefined Label"
9999998 "***Undefined Label"
;
label define MV372A  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV384A  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV384B  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV384C  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV395   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "DK"
;
label define MV396   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "DK"
;
label define MV3A09B 
   998 "***Undefined Label"
;
label define MV3B17  
    10 "PUBLIC"
    11 "Government hospital"
    12 "Government health center/clinic"
    13 "Government health post"
    14 "Maternity clinic"
    15 "Community health worker"
    16 "Other public"
    20 "PRIVATE MEDICAL"
    21 "Private Hospital, clinic"
    22 "Pharmacy"
    23 "Amo-Congo"
    24 "Private fieldworker"
    26 "Other private medical"
    30 "OTHER PRIVATE"
    31 "Shop"
    32 "Bar,nightclub"
    33 "Kiosk"
    34 "Street Vendor"
    35 "Friends, relatives"
    36 "Hotel,motel"
    37 "Former partner"
    96 "OTHER"
    98 "DK"
;
label define MV3B25A 
     0 "Disagree"
     1 "Agree"
     8 "DK"
;
label define MV3B25B 
     0 "Disagree"
     1 "Agree"
     8 "DK"
;
label define MV463A  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV463B  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV463C  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV463D  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV463E  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV463F  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV463G  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV463X  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV463Z  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV464   
    98 "***Undefined Label"
;
label define MV474   
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV474A  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV474B  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV474C  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV474D  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV474E  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV474F  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV474G  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV474H  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV474I  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV474J  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV474X  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV474Z  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV475   
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV476   
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV477   
     0 "***Undefined Label"
    90 "***Undefined Label"
    98 "***Undefined Label"
;
label define MV478   
     0 "***Undefined Label"
    90 "***Undefined Label"
    98 "***Undefined Label"
;
label define MV479   
    10 "***Undefined Label"
    11 "***Undefined Label"
    12 "***Undefined Label"
    16 "***Undefined Label"
    20 "***Undefined Label"
    21 "***Undefined Label"
    22 "***Undefined Label"
    23 "***Undefined Label"
    24 "***Undefined Label"
    26 "***Undefined Label"
    30 "***Undefined Label"
    31 "***Undefined Label"
    96 "***Undefined Label"
;
label define MV480   
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV481   
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV481A  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV481B  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV481C  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV481D  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV481E  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV481F  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV481G  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV481H  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV481X  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV482A  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV482B  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV482C  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV483   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV501   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define MV502   
     0 "Never married"
     1 "Currently married"
     2 "Formerly married"
;
label define MV503   
     1 "Once"
     2 "More than once"
;
label define MV504   
     1 "***Undefined Label"
     2 "***Undefined Label"
;
label define MV505   
    99 "Missing"
;
label define MV510   
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "***Undefined Label"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define MV513   
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define MV525   
     0 "Not had intercourse"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV527   
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   301 "Months: 1"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV528   
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV529   
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV531   
     0 "Not had intercourse"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV532   
     0 "No flag"
     1 "After interview"
     2 "After concep >= 1 yr"
     3 "After concep < 1 yr"
     4 "At marr, never marr"
     5 "At marr,after concep"
     6 "After marriage"
;
label define MV535   
     0 "No"
     1 "Formerly married"
     2 "Lived with a woman"
     3 "Both, formerly married and lived with a woman"
;
label define MV536   
     0 "Never had intercourse"
     1 "Active in last 4 weeks"
     3 "Not active in last 4 weeks"
;
label define MV541   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV602   
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized"
     5 "Wife declared infecund"
     6 "Never had sex"
     7 "Man declared infecund"
     8 "Man has no partner"
;
label define MV603   
   993 "After marriage"
   994 "Soon, now"
   995 "***Undefined Label"
   996 "Other, Non-numeric"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV604   
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
;
label define MV605   
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized"
     7 "Declared infecund"
     8 "Never had sex"
;
label define MV613   
    96 "Non-numeric response"
    98 "DK"
;
label define MV614   
     6 "6+"
     7 "Non-numeric response"
;
label define MV616   
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "DK"
;
label define MV621   
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV627   
    96 "Other"
    97 "***Undefined Label"
    98 "DK"
;
label define MV628   
    96 "Other"
    97 "***Undefined Label"
    98 "DK"
;
label define MV629   
    96 "Other"
    97 "***Undefined Label"
    98 "DK"
;
label define MV631   
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     4 "***Undefined Label"
;
label define MV633A  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV633B  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV633C  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV633D  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV633E  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV633F  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV633G  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV634A  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV634B  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV634C  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV634D  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV714   
     0 "No"
     1 "Yes"
;
label define MV714A  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV716   
     0 "Not working"
     1 "Legislators, Senior officials and Managers"
     2 "Scientific and Academic professionals"
     3 "Technicians and associate professionals"
     4 "Clerks and Administrative assistants"
     5 "Service workers and shop and market sales workers"
     6 "Skilled agricultural and fishery workers"
     7 "Craft and related trade workers"
     8 "Plant and machine operators and assemblers"
     9 "Sales and services, domestic workers, building caretakers, messengers, unskilled laborers"
    99 "Not declared"
;
label define MV717   
     0 "Not working"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
;
label define MV721   
     1 "***Undefined Label"
     2 "***Undefined Label"
;
label define MV731   
     0 "No"
     1 "In the past year"
     2 "Currently working"
;
label define MV739   
     1 "Respondent alone"
     2 "Respondent and husband/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
;
label define MV740   
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     4 "Terre de moitié *"
     6 "Other *"
     8 "Don't know"
;
label define MV741   
     0 "Not paid"
     1 "Cash only"
     2 "Cash and kind"
     3 "In kind only"
;
label define MV743A  
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     4 "***Undefined Label"
     5 "***Undefined Label"
     6 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV743B  
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     4 "***Undefined Label"
     5 "***Undefined Label"
     6 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV743C  
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     4 "***Undefined Label"
     5 "***Undefined Label"
     6 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV743D  
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     4 "***Undefined Label"
     5 "***Undefined Label"
     6 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV743E  
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     4 "***Undefined Label"
     5 "***Undefined Label"
     6 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV743F  
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     4 "***Undefined Label"
     5 "***Undefined Label"
     6 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV743G  
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     4 "***Undefined Label"
     5 "***Undefined Label"
     6 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV744A  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV744B  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV744C  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV744D  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV744E  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV747A  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV747B  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV750   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV751   
     0 "No"
     1 "Yes"
;
label define MV754BP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754CP 
     0 "No"
     1 "Reduce chances of AIDS by always using condoms during sex"
     8 "Don't know"
;
label define MV754DP 
     0 "No"
     1 "Reduce chance of AIDS: have 1 sex partnr with no oth partner"
     8 "Don't know"
;
label define MV754JP 
     0 "No"
     1 "Get AIDS from mosquito bites"
     8 "Don't know"
;
label define MV754WP 
     0 "No"
     1 "Get AIDS by sharing food with person who has AIDS"
     8 "Don't know"
;
label define MV756   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV761   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV761B  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV761C  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV762AA 
     0 "No"
     1 "Yes: Government hospital"
;
label define MV762AB 
     0 "No"
     1 "Yes: Government health center/post"
;
label define MV762AC 
     0 "No"
     1 "Yes: Family planning clinic"
;
label define MV762AD 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762AE 
     0 "No"
     1 "Yes: Public field worker"
;
label define MV762AF 
     0 "No"
     1 "Yes: Other public"
;
label define MV762AG 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762AH 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762AI 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762AJ 
     0 "No"
     1 "Yes: Private hosp, clinic"
;
label define MV762AK 
     0 "No"
     1 "Yes: Pharmacy"
;
label define MV762AL 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762AM 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762AN 
     0 "No"
     1 "Yes: Private field worker"
;
label define MV762AO 
     0 "No"
     1 "Yes: Other private"
;
label define MV762AP 
     0 "No"
     1 "Yes: Private CS"
;
label define MV762AQ 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762AR 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762AS 
     0 "No"
     1 "Yes: Shop"
;
label define MV762AT 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762AU 
     0 "No"
     1 "Yes: Friends, relatives"
;
label define MV762AV 
     0 "No"
     1 "Yes"
;
label define MV762AW 
     0 "No"
     1 "Yes"
;
label define MV762AX 
     0 "No"
     1 "Yes: Other"
;
label define MV762AZ 
     0 "No"
     1 "Yes: DK source for condom"
;
label define MV762BA 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BB 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BC 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BD 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BE 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BF 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BG 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BH 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BI 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BJ 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BK 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BL 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BM 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BN 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BO 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BP 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BQ 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BR 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BS 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BT 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BU 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BV 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BW 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BX 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV762BZ 
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV763A  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV763B  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV763C  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV763D  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV763E  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV763F  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV763G  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV766A  
    98 "DK"
;
label define MV766B  
    98 "DK"
;
label define MV767A  
     1 "Spouse"
     2 "Girlfriend/fiancee"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767B  
     1 "Spouse"
     2 "Girlfriend/fiancee"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767C  
     1 "Spouse"
     2 "Girlfriend/fiancee"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV768A  
   101 "One day"
   201 "One week"
   301 "One month"
   401 "One year"
;
label define MV768B  
   101 "One day"
   201 "One week"
   301 "One month"
   401 "One year"
;
label define MV768C  
   101 "One day"
   201 "One week"
   301 "One month"
   401 "One year"
;
label define MV769   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV769A  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV770   
     0 "No"
     1 "Yes"
;
label define MV770A  
     0 "No"
     1 "Yes"
;
label define MV770B  
     0 "No"
     1 "Yes"
;
label define MV770C  
     0 "No"
     1 "Yes"
;
label define MV770D  
     0 "No"
     1 "Yes"
;
label define MV770E  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV770F  
     0 "No"
     1 "Yes"
;
label define MV770G  
     0 "No"
     1 "Yes"
;
label define MV770H  
     0 "No"
     1 "Yes"
;
label define MV770I  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV770J  
     0 "No"
     1 "Yes"
;
label define MV770K  
     0 "No"
     1 "Yes"
;
label define MV770L  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV770M  
     0 "No"
     1 "Yes"
;
label define MV770N  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV770O  
     0 "No"
     1 "Yes"
;
label define MV770P  
     0 "No"
     1 "Yes"
;
label define MV770Q  
     0 "No"
     1 "Yes"
;
label define MV770R  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV770S  
     0 "No"
     1 "Yes"
;
label define MV770T  
     0 "No"
     1 "Yes"
;
label define MV770U  
     0 "No"
     1 "Yes"
;
label define MV770V  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV770W  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV770X  
     0 "No"
     1 "Yes"
;
label define MV774A  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV774B  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV774C  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV775   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV777   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV778   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV779   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV780   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV781   
     0 "No"
     1 "Yes"
;
label define MV783   
     0 "No"
     1 "Yes"
;
label define MV784A  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784B  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784C  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784D  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784E  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784F  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV784G  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784H  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV784I  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV784J  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784K  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784L  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV784M  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV784N  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784O  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784P  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784Q  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784R  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV784S  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784T  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV784U  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV784V  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define MV784X  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV785   
     0 "No"
     1 "Yes"
;
label define MV793   
     0 "No"
     1 "Yes"
;
label define MV793A  
     0 "No"
     1 "Yes"
;
label define MV793B  
     0 "No"
     1 "Yes"
     8 "Not sure/can't remember *"
;
label define MV820   
     0 "No"
     1 "Yes"
;
label define MV822   
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV823   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV824   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV825   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV826   
     1 "Less than 12 months"
     2 "12-23 months"
     3 "2 years or more"
;
label define MV827   
     1 "Asked for the test"
     2 "Offered and accepted"
     3 "Required"
;
label define MV828   
     0 "No"
     1 "Yes"
;
label define MV829   
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Public stand-alone VCT center"
    14 "Public family planning clinic"
    15 "Public mobile clinic"
    16 "Public field worker"
    17 "Other public"
    20 "PRIVATE MEDICAL"
    21 "Private hospital, clinic or doctor"
    22 "Private stand-alone VCT center"
    23 "Private pharmacy"
    24 "Private mobile clinic"
    25 "Private field worker"
    26 "Other private medical"
    96 "Other"
;
label define MV832B  
   100 "***Undefined Label"
   101 "***Undefined Label"
   201 "***Undefined Label"
   301 "***Undefined Label"
   401 "***Undefined Label"
   995 "***Undefined Label"
   996 "***Undefined Label"
   997 "***Undefined Label"
   998 "***Undefined Label"
;
label define MV832C  
   100 "***Undefined Label"
   101 "***Undefined Label"
   201 "***Undefined Label"
   301 "***Undefined Label"
   401 "***Undefined Label"
   995 "***Undefined Label"
   996 "***Undefined Label"
   997 "***Undefined Label"
   998 "***Undefined Label"
;
label define MV833A  
     0 "No"
     1 "Yes"
;
label define MV833B  
     0 "No"
     1 "Yes"
;
label define MV833C  
     0 "No"
     1 "Yes"
;
label define MV835A  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835B  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835C  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV836   
    95 "95+"
    98 "Don't know"
;
label define MV837   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV844   
     0 "No"
     1 "Yes"
     2 "Don't know anyone with AIDS"
;
label define MV845   
     0 "No"
     1 "Yes"
;
label define MV846   
     0 "No"
     1 "Yes"
;
label define MV847   
     0 "Disagree"
     1 "Agree"
     8 "Don't know / no opinion"
;
label define MV848   
     0 "Disagree"
     1 "Agree"
     8 "Don't know / no opinion"
;
label define MV849   
     0 "No"
     1 "Yes"
     8 "Don't know / depends"
;
label define MV851A  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV851B  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV851C  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV851D  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV851E  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV851F  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV851G  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV851H  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV851I  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV851J  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV851K  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define MV851L  
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define SMEDUC  
     0 "No education"
     1 "Primary"
     2 "Secondary or higher"
;
label define SM121   
     1 "Went to school, college"
     2 "Looked for work"
     3 "Did not do anything"
     4 "Cannot work, disabled"
     5 "Looked after children"
     6 "Other"
;
label define SM130A  
     0 "No"
     1 "Yes"
;
label define SM130B  
     0 "No"
     1 "Yes"
;
label define SM130C  
     0 "No"
     1 "Yes"
;
label define SM130D  
 99994 "99994 ou plus"
 99995 "Free (no charge)"
 99996 "Don't know"
;
label define SM130EA 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM130EB 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM130EC 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM130ED 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM304A  
     0 "No"
     1 "Yes"
;
label define SM306C  
     1 "Agrees"
     2 "Does not agree"
     8 "Don't know"
;
label define SM405   
     1 "Regular partner only"
     2 "Occasional partner only"
     3 "Occasional and regular partner"
     4 "No other partner"
;
label define SM406   
     1 "Regular partner only"
     2 "Occasional partner only"
     3 "Occasional and regular partner"
     4 "No other partner"
;
label define SM416D  
    98 "Don't know"
;
label define SM419A  
     1 "Avoid HIV/AIDS"
     2 "Prevent pregnancy"
     3 "Avoid HIV/AIDS and prevent pregnancy"
     4 "Did not trust partner"
     5 "Partner insisted"
     6 "Other"
     8 "Does not know"
;
label define SM419B  
     1 "Avoid HIV/AIDS"
     2 "Prevent pregnancy"
     3 "Avoid HIV/AIDS and prevent pregnancy"
     4 "Did not trust partner"
     5 "Partner insisted"
     6 "Other"
     8 "Does not know"
;
label define SM419C  
     1 "Avoid HIV/AIDS"
     2 "Prevent pregnancy"
     3 "Avoid HIV/AIDS and prevent pregnancy"
     4 "Did not trust partner"
     5 "Partner insisted"
     6 "Other"
     8 "Does not know"
;
label define SM422A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM422B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM422C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM423A  
     1 "Female Sterilization"
     3 "Pill"
     4 "IUD"
     5 "Injections"
     6 "Implants"
     7 "Condom"
     8 "Female condom"
     9 "Diaphragm"
    10 "Foam or jelly"
    12 "Periodic Abstinence"
    13 "Withdrawal"
    96 "Other"
;
label define SM423B  
     1 "Female Sterilization"
     3 "Pill"
     4 "IUD"
     5 "Injections"
     6 "Implants"
     7 "Condom"
     8 "Female condom"
     9 "Diaphragm"
    10 "Foam or jelly"
    12 "Periodic Abstinence"
    13 "Withdrawal"
    96 "Other"
;
label define SM423C  
     1 "Female Sterilization"
     3 "Pill"
     4 "IUD"
     5 "Injections"
     6 "Implants"
     7 "Condom"
     8 "Female condom"
     9 "Diaphragm"
    10 "Foam or jelly"
    12 "Periodic Abstinence"
    13 "Withdrawal"
    96 "Other"
;
label define SM425A  
    11 "Occasional sex partner/not his responsibility"
    12 "Contraception is the affair of women"
    13 "No need, condom was used to avoid HIV/AIDS"
    20 "FERTILITY-RELATED"
    23 "Wife/partner menopausal or had hysterectomy"
    24 "Subfecund, infecund"
    25 "Wife/partner pregnant"
    26 "Wife/partner post-partum"
    27 "Wife/partner breastfeeding"
    28 "Wants more children"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Husband opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    96 "Other"
    98 "DK"
;
label define SM425B  
    11 "Occasional sex partner/not his responsibility"
    12 "Contraception is the affair of women"
    13 "No need, condom was used to avoid HIV/AIDS"
    20 "FERTILITY-RELATED"
    23 "Wife/partner menopausal or had hysterectomy"
    24 "Subfecund, infecund"
    25 "Wife/partner pregnant"
    26 "Wife/partner post-partum"
    27 "Wife/partner breastfeeding"
    28 "Wants more children"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Husband opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    96 "Other"
    98 "DK"
;
label define SM425C  
    11 "Occasional sex partner/not his responsibility"
    12 "Contraception is the affair of women"
    13 "No need, condom was used to avoid HIV/AIDS"
    20 "FERTILITY-RELATED"
    23 "Wife/partner menopausal or had hysterectomy"
    24 "Subfecund, infecund"
    25 "Wife/partner pregnant"
    26 "Wife/partner post-partum"
    27 "Wife/partner breastfeeding"
    28 "Wants more children"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Husband opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    96 "Other"
    98 "DK"
;
label define SM436B  
     1 "Yes"
     0 "No"
;
label define SM438C  
     1 "Yes"
     0 "No"
     3 "Refused to answer / no response"
     4 "Privacy not obtained - no response"
;
label define SM438D  
     1 "Wanted to"
     2 "Forced to"
     3 "Refused to answer / no response"
;
label define SM438E  
     1 "Yes"
     0 "No"
     3 "Refused to answer / no response"
;
label define SM507   
     1 "Approves"
     2 "Disapproves"
     8 "Don't know/no opinion"
;
label define SM511A  
     0 "No"
     1 "Yes"
;
label define SM511B  
     0 "No"
     1 "Yes"
;
label define SM511C  
     0 "No"
     1 "Yes"
;
label define SM511D  
     0 "No"
     1 "Yes"
;
label define SM511E  
     0 "No"
     1 "Yes"
;
label define SM511F  
     0 "No"
     1 "Yes"
;
label define SM511G  
     0 "No"
     1 "Yes"
;
label define SM511H  
     0 "No"
     1 "Yes"
;
label define SM511I  
     0 "No"
     1 "Yes"
;
label define SM511X  
     0 "No"
     1 "Yes"
;
label define SM511Y  
     0 "No"
     1 "Yes"
;
label define SM609A  
     0 "No"
     1 "Abstain from sex"
     8 "DK"
;
label define SM609B  
     0 "No"
     1 "Condoms during sex"
     8 "DK"
;
label define SM609C  
     0 "No"
     1 "Only one sex partner"
     8 "DK"
;
label define SM609D  
     0 "No"
     1 "Limit number of sex partners"
     8 "DK"
;
label define SM609E  
     0 "No"
     1 "Avoid prostitutes"
     8 "DK"
;
label define SM609F  
     0 "No"
     1 "Avoid partners who have many partners"
     8 "DK"
;
label define SM609G  
     0 "No"
     1 "Avoid homosexuals"
     8 "DK"
;
label define SM609H  
     0 "No"
     1 "Avoid sex with intravenous drug users"
     8 "DK"
;
label define SM609I  
     0 "No"
     1 "Avoid blood transfus"
     8 "DK"
;
label define SM609J  
     0 "No"
     1 "Avoid injections"
     8 "DK"
;
label define SM609K  
     0 "No"
     1 "Avoid sharing razor blades with AIDS patient"
     8 "DK"
;
label define SM609L  
     0 "No"
     1 "Avoid kissing"
     8 "DK"
;
label define SM609M  
     0 "No"
     1 "Avoid mosquito bites"
     8 "DK"
;
label define SM609N  
     0 "No"
     1 "Seek trad. healing"
     8 "DK"
;
label define SM609W  
     0 "No"
     1 "Other responses"
     8 "DK"
;
label define SM609X  
     0 "No"
     1 "Other responses"
     8 "DK"
;
label define SM609Z  
     0 "No: knows ways"
     1 "Yes: DK ways"
     8 "DK"
;
label define SM642A  
     0 "No"
     1 "Abdominal pain"
;
label define SM642B  
     0 "No"
     1 "Genital discharge/dripping"
;
label define SM642C  
     0 "No"
     1 "Foul smelling discharge"
;
label define SM642D  
     0 "No"
     1 "Buring pain during urination"
;
label define SM642E  
     0 "No"
     1 "Redness/inflamation"
;
label define SM642F  
     0 "No"
     1 "Swelling"
;
label define SM642G  
     0 "No"
     1 "Sores/ulcers"
;
label define SM642H  
     0 "No"
     1 "Warts"
;
label define SM642I  
     0 "No"
     1 "Itching"
;
label define SM642J  
     0 "No"
     1 "Blood in urine"
;
label define SM642K  
     0 "No"
     1 "Weight loss"
;
label define SM642L  
     0 "No"
     1 "Impotence"
;
label define SM642W  
     0 "No"
     1 "Other"
;
label define SM642X  
     0 "No"
     1 "Other"
;
label define SM642Y  
     0 "Yes, has symptoms"
     1 "No symptoms"
;
label define SM642Z  
     0 "Knows symptoms"
     1 "Don't know symptoms"
;
label define SM643A  
     0 "No"
     1 "Abdominal pain"
;
label define SM643B  
     0 "No"
     1 "Genital discharge/dripping"
;
label define SM643C  
     0 "No"
     1 "Foul smelling discharge"
;
label define SM643D  
     0 "No"
     1 "Buring pain during urination"
;
label define SM643E  
     0 "No"
     1 "Redness/inflamation"
;
label define SM643F  
     0 "No"
     1 "Swelling"
;
label define SM643G  
     0 "No"
     1 "Sores/ulcers"
;
label define SM643H  
     0 "No"
     1 "Warts"
;
label define SM643I  
     0 "No"
     1 "Itching"
;
label define SM643J  
     0 "No"
     1 "Blood in urine"
;
label define SM643K  
     0 "No"
     1 "Weight loss"
;
label define SM643L  
     0 "No"
     1 "Difficulty getting pregnant, infertility"
;
label define SM643W  
     0 "No"
     1 "Other"
;
label define SM643X  
     0 "No"
     1 "Other"
;
label define SM643Y  
     0 "Yes, has symptoms"
     1 "No symptoms"
;
label define SM643Z  
     0 "Knows symptoms"
     1 "Don't know symptoms"
;
label define SM653A  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653B  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653C  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653D  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653E  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653F  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653G  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653H  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653I  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653J  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653K  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653L  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653M  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653N  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653Q  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653R  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653X  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM653Y  
     0 "No"
     1 "Yes"
     8 "DK"
;

#delimit cr
label values mv007    MV007   
label values mv013    MV013   
label values mv014    MV014   
label values mv015    MV015   
label values mv023    MV023   
label values mv024    MV024   
label values mv025    MV025   
label values mv026    MV026   
label values mv034_1  MV034   
label values mv034_2  MV034   
label values mv034_3  MV034   
label values mv034_4  MV034   
label values mv034_5  MV034   
label values mv034_6  MV034   
label values mv034_7  MV034   
label values mv034_8  MV034   
label values mv034a_1 MV034A  
label values mv034a_2 MV034A  
label values mv034a_3 MV034A  
label values mv034a_4 MV034A  
label values mv034a_5 MV034A  
label values mv034a_6 MV034A  
label values mv034a_7 MV034A  
label values mv034a_8 MV034A  
label values mv035    MV035   
label values mv803    MV803   
label values mv101    MV101   
label values mv102    MV102   
label values mv103    MV103   
label values mv104    MV104   
label values mv105    MV105   
label values mv106    MV106   
label values mv130    MV130   
label values mv131    MV131   
label values mv133    MV133   
label values mv134    MV134   
label values mv135    MV135   
label values mv149    MV149   
label values mv150    MV150   
label values mv151    MV151   
label values mv152    MV152   
label values mv155    MV155   
label values mv156    MV156   
label values mv157    MV157   
label values mv158    MV158   
label values mv159    MV159   
label values mv167    MV167   
label values mv168    MV168   
label values mv190    MV190   
label values mv213    MV213   
label values mv217    MV217   
label values mv225    MV225   
label values mv246    MV246   
label values mv248    MV248   
label values mv249    MV249   
label values mv250    MV250   
label values mv251    MV251   
label values mv252    MV252   
label values mv301    MV301   
label values mv302    MV302   
label values m304a_01 M304A   
label values m304a_02 M304A   
label values m304a_03 M304A   
label values m304a_04 M304A   
label values m304a_05 M304A   
label values m304a_06 M304A   
label values m304a_07 M304A   
label values m304a_08 M304A   
label values m304a_09 M304A   
label values m304a_10 M304A   
label values m304a_11 M304A   
label values m304a_12 M304A   
label values m304a_13 M304A   
label values m304a_14 M304A   
label values m304a_15 M304A   
label values m304a_16 M304A   
label values m304a_17 M304A   
label values m304a_18 M304A   
label values m304a_19 M304A   
label values m304a_20 M304A   
label values mv304_01 MV304   
label values mv304_02 MV304   
label values mv304_03 MV304   
label values mv304_04 MV304   
label values mv304_05 MV304   
label values mv304_06 MV304   
label values mv304_07 MV304   
label values mv304_08 MV304   
label values mv304_09 MV304   
label values mv304_10 MV304   
label values mv304_11 MV304   
label values mv304_12 MV304   
label values mv304_13 MV304   
label values mv304_14 MV304   
label values mv304_15 MV304   
label values mv304_16 MV304   
label values mv304_17 MV304   
label values mv304_18 MV304   
label values mv304_19 MV304   
label values mv304_20 MV304   
label values mv305_01 MV305   
label values mv305_02 MV305   
label values mv305_03 MV305   
label values mv305_04 MV305   
label values mv305_05 MV305   
label values mv305_06 MV305   
label values mv305_07 MV305   
label values mv305_08 MV305   
label values mv305_09 MV305   
label values mv305_10 MV305   
label values mv305_11 MV305   
label values mv305_12 MV305   
label values mv305_13 MV305   
label values mv305_14 MV305   
label values mv305_15 MV305   
label values mv305_16 MV305   
label values mv305_17 MV305   
label values mv305_18 MV305   
label values mv305_19 MV305   
label values mv305_20 MV305   
label values mv307_01 MV307   
label values mv307_02 MV307   
label values mv307_03 MV307   
label values mv307_04 MV307   
label values mv307_05 MV307   
label values mv307_06 MV307   
label values mv307_07 MV307   
label values mv307_08 MV307   
label values mv307_09 MV307   
label values mv307_10 MV307   
label values mv307_11 MV307   
label values mv307_12 MV307   
label values mv307_13 MV307   
label values mv307_14 MV307   
label values mv307_15 MV307   
label values mv307_16 MV307   
label values mv307_17 MV307   
label values mv307_18 MV307   
label values mv307_19 MV307   
label values mv307_20 MV307   
label values mv312    MV312   
label values mv313    MV313   
label values mv323a   MV323A  
label values mv325b   MV325B  
label values mv372a   MV372A  
label values mv384a   MV384A  
label values mv384b   MV384B  
label values mv384c   MV384C  
label values mv395    MV395   
label values mv396    MV396   
label values mv3a09b  MV3A09B 
label values mv3b17   MV3B17  
label values mv3b25a  MV3B25A 
label values mv3b25b  MV3B25B 
label values mv463a   MV463A  
label values mv463b   MV463B  
label values mv463c   MV463C  
label values mv463d   MV463D  
label values mv463e   MV463E  
label values mv463f   MV463F  
label values mv463g   MV463G  
label values mv463x   MV463X  
label values mv463z   MV463Z  
label values mv464    MV464   
label values mv474    MV474   
label values mv474a   MV474A  
label values mv474b   MV474B  
label values mv474c   MV474C  
label values mv474d   MV474D  
label values mv474e   MV474E  
label values mv474f   MV474F  
label values mv474g   MV474G  
label values mv474h   MV474H  
label values mv474i   MV474I  
label values mv474j   MV474J  
label values mv474x   MV474X  
label values mv474z   MV474Z  
label values mv475    MV475   
label values mv476    MV476   
label values mv477    MV477   
label values mv478    MV478   
label values mv479    MV479   
label values mv480    MV480   
label values mv481    MV481   
label values mv481a   MV481A  
label values mv481b   MV481B  
label values mv481c   MV481C  
label values mv481d   MV481D  
label values mv481e   MV481E  
label values mv481f   MV481F  
label values mv481g   MV481G  
label values mv481h   MV481H  
label values mv481x   MV481X  
label values mv482a   MV482A  
label values mv482b   MV482B  
label values mv482c   MV482C  
label values mv483    MV483   
label values mv501    MV501   
label values mv502    MV502   
label values mv503    MV503   
label values mv504    MV504   
label values mv510    MV510   
label values mv513    MV513   
label values mv525    MV525   
label values mv527    MV527   
label values mv528    MV528   
label values mv529    MV529   
label values mv531    MV531   
label values mv532    MV532   
label values mv535    MV535   
label values mv536    MV536   
label values mv541    MV541   
label values mv602    MV602   
label values mv603    MV603   
label values mv604    MV604   
label values mv605    MV605   
label values mv613    MV613   
label values mv614    MV614   
label values mv616    MV616   
label values mv621    MV621   
label values mv627    MV627   
label values mv628    MV628   
label values mv629    MV629   
label values mv631    MV631   
label values mv633a   MV633A  
label values mv633b   MV633B  
label values mv633c   MV633C  
label values mv633d   MV633D  
label values mv633e   MV633E  
label values mv633f   MV633F  
label values mv633g   MV633G  
label values mv634a   MV634A  
label values mv634b   MV634B  
label values mv634c   MV634C  
label values mv634d   MV634D  
label values mv714    MV714   
label values mv714a   MV714A  
label values mv716    MV716   
label values mv717    MV717   
label values mv721    MV721   
label values mv731    MV731   
label values mv739    MV739   
label values mv740    MV740   
label values mv741    MV741   
label values mv743a   MV743A  
label values mv743b   MV743B  
label values mv743c   MV743C  
label values mv743d   MV743D  
label values mv743e   MV743E  
label values mv743f   MV743F  
label values mv743g   MV743G  
label values mv744a   MV744A  
label values mv744b   MV744B  
label values mv744c   MV744C  
label values mv744d   MV744D  
label values mv744e   MV744E  
label values mv747a   MV747A  
label values mv747b   MV747B  
label values mv750    MV750   
label values mv751    MV751   
label values mv754bp  MV754BP 
label values mv754cp  MV754CP 
label values mv754dp  MV754DP 
label values mv754jp  MV754JP 
label values mv754wp  MV754WP 
label values mv756    MV756   
label values mv761    MV761   
label values mv761b   MV761B  
label values mv761c   MV761C  
label values mv762aa  MV762AA 
label values mv762ab  MV762AB 
label values mv762ac  MV762AC 
label values mv762ad  MV762AD 
label values mv762ae  MV762AE 
label values mv762af  MV762AF 
label values mv762ag  MV762AG 
label values mv762ah  MV762AH 
label values mv762ai  MV762AI 
label values mv762aj  MV762AJ 
label values mv762ak  MV762AK 
label values mv762al  MV762AL 
label values mv762am  MV762AM 
label values mv762an  MV762AN 
label values mv762ao  MV762AO 
label values mv762ap  MV762AP 
label values mv762aq  MV762AQ 
label values mv762ar  MV762AR 
label values mv762as  MV762AS 
label values mv762at  MV762AT 
label values mv762au  MV762AU 
label values mv762av  MV762AV 
label values mv762aw  MV762AW 
label values mv762ax  MV762AX 
label values mv762az  MV762AZ 
label values mv762ba  MV762BA 
label values mv762bb  MV762BB 
label values mv762bc  MV762BC 
label values mv762bd  MV762BD 
label values mv762be  MV762BE 
label values mv762bf  MV762BF 
label values mv762bg  MV762BG 
label values mv762bh  MV762BH 
label values mv762bi  MV762BI 
label values mv762bj  MV762BJ 
label values mv762bk  MV762BK 
label values mv762bl  MV762BL 
label values mv762bm  MV762BM 
label values mv762bn  MV762BN 
label values mv762bo  MV762BO 
label values mv762bp  MV762BP 
label values mv762bq  MV762BQ 
label values mv762br  MV762BR 
label values mv762bs  MV762BS 
label values mv762bt  MV762BT 
label values mv762bu  MV762BU 
label values mv762bv  MV762BV 
label values mv762bw  MV762BW 
label values mv762bx  MV762BX 
label values mv762bz  MV762BZ 
label values mv763a   MV763A  
label values mv763b   MV763B  
label values mv763c   MV763C  
label values mv763d   MV763D  
label values mv763e   MV763E  
label values mv763f   MV763F  
label values mv763g   MV763G  
label values mv766a   MV766A  
label values mv766b   MV766B  
label values mv767a   MV767A  
label values mv767b   MV767B  
label values mv767c   MV767C  
label values mv768a   MV768A  
label values mv768b   MV768B  
label values mv768c   MV768C  
label values mv769    MV769   
label values mv769a   MV769A  
label values mv770    MV770   
label values mv770a   MV770A  
label values mv770b   MV770B  
label values mv770c   MV770C  
label values mv770d   MV770D  
label values mv770e   MV770E  
label values mv770f   MV770F  
label values mv770g   MV770G  
label values mv770h   MV770H  
label values mv770i   MV770I  
label values mv770j   MV770J  
label values mv770k   MV770K  
label values mv770l   MV770L  
label values mv770m   MV770M  
label values mv770n   MV770N  
label values mv770o   MV770O  
label values mv770p   MV770P  
label values mv770q   MV770Q  
label values mv770r   MV770R  
label values mv770s   MV770S  
label values mv770t   MV770T  
label values mv770u   MV770U  
label values mv770v   MV770V  
label values mv770w   MV770W  
label values mv770x   MV770X  
label values mv774a   MV774A  
label values mv774b   MV774B  
label values mv774c   MV774C  
label values mv775    MV775   
label values mv777    MV777   
label values mv778    MV778   
label values mv779    MV779   
label values mv780    MV780   
label values mv781    MV781   
label values mv783    MV783   
label values mv784a   MV784A  
label values mv784b   MV784B  
label values mv784c   MV784C  
label values mv784d   MV784D  
label values mv784e   MV784E  
label values mv784f   MV784F  
label values mv784g   MV784G  
label values mv784h   MV784H  
label values mv784i   MV784I  
label values mv784j   MV784J  
label values mv784k   MV784K  
label values mv784l   MV784L  
label values mv784m   MV784M  
label values mv784n   MV784N  
label values mv784o   MV784O  
label values mv784p   MV784P  
label values mv784q   MV784Q  
label values mv784r   MV784R  
label values mv784s   MV784S  
label values mv784t   MV784T  
label values mv784u   MV784U  
label values mv784v   MV784V  
label values mv784x   MV784X  
label values mv785    MV785   
label values mv793    MV793   
label values mv793a   MV793A  
label values mv793b   MV793B  
label values mv820    MV820   
label values mv822    MV822   
label values mv823    MV823   
label values mv824    MV824   
label values mv825    MV825   
label values mv826    MV826   
label values mv827    MV827   
label values mv828    MV828   
label values mv829    MV829   
label values mv832b   MV832B  
label values mv832c   MV832C  
label values mv833a   MV833A  
label values mv833b   MV833B  
label values mv833c   MV833C  
label values mv835a   MV835A  
label values mv835b   MV835B  
label values mv835c   MV835C  
label values mv836    MV836   
label values mv837    MV837   
label values mv844    MV844   
label values mv845    MV845   
label values mv846    MV846   
label values mv847    MV847   
label values mv848    MV848   
label values mv849    MV849   
label values mv851a   MV851A  
label values mv851b   MV851B  
label values mv851c   MV851C  
label values mv851d   MV851D  
label values mv851e   MV851E  
label values mv851f   MV851F  
label values mv851g   MV851G  
label values mv851h   MV851H  
label values mv851i   MV851I  
label values mv851j   MV851J  
label values mv851k   MV851K  
label values mv851l   MV851L  
label values smeduc   SMEDUC  
label values sm121    SM121   
label values sm130a   SM130A  
label values sm130b   SM130B  
label values sm130c   SM130C  
label values sm130d   SM130D  
label values sm130ea  SM130EA 
label values sm130eb  SM130EB 
label values sm130ec  SM130EC 
label values sm130ed  SM130ED 
label values sm304a   SM304A  
label values sm306c   SM306C  
label values sm405    SM405   
label values sm406    SM406   
label values sm416d   SM416D  
label values sm419a   SM419A  
label values sm419b   SM419B  
label values sm419c   SM419C  
label values sm422a   SM422A  
label values sm422b   SM422B  
label values sm422c   SM422C  
label values sm423a   SM423A  
label values sm423b   SM423B  
label values sm423c   SM423C  
label values sm425a   SM425A  
label values sm425b   SM425B  
label values sm425c   SM425C  
label values sm436b   SM436B  
label values sm438c   SM438C  
label values sm438d   SM438D  
label values sm438e   SM438E  
label values sm507    SM507   
label values sm511a   SM511A  
label values sm511b   SM511B  
label values sm511c   SM511C  
label values sm511d   SM511D  
label values sm511e   SM511E  
label values sm511f   SM511F  
label values sm511g   SM511G  
label values sm511h   SM511H  
label values sm511i   SM511I  
label values sm511x   SM511X  
label values sm511y   SM511Y  
label values sm609a   SM609A  
label values sm609b   SM609B  
label values sm609c   SM609C  
label values sm609d   SM609D  
label values sm609e   SM609E  
label values sm609f   SM609F  
label values sm609g   SM609G  
label values sm609h   SM609H  
label values sm609i   SM609I  
label values sm609j   SM609J  
label values sm609k   SM609K  
label values sm609l   SM609L  
label values sm609m   SM609M  
label values sm609n   SM609N  
label values sm609w   SM609W  
label values sm609x   SM609X  
label values sm609z   SM609Z  
label values sm642a   SM642A  
label values sm642b   SM642B  
label values sm642c   SM642C  
label values sm642d   SM642D  
label values sm642e   SM642E  
label values sm642f   SM642F  
label values sm642g   SM642G  
label values sm642h   SM642H  
label values sm642i   SM642I  
label values sm642j   SM642J  
label values sm642k   SM642K  
label values sm642l   SM642L  
label values sm642w   SM642W  
label values sm642x   SM642X  
label values sm642y   SM642Y  
label values sm642z   SM642Z  
label values sm643a   SM643A  
label values sm643b   SM643B  
label values sm643c   SM643C  
label values sm643d   SM643D  
label values sm643e   SM643E  
label values sm643f   SM643F  
label values sm643g   SM643G  
label values sm643h   SM643H  
label values sm643i   SM643I  
label values sm643j   SM643J  
label values sm643k   SM643K  
label values sm643l   SM643L  
label values sm643w   SM643W  
label values sm643x   SM643X  
label values sm643y   SM643Y  
label values sm643z   SM643Z  
label values sm653a   SM653A  
label values sm653b   SM653B  
label values sm653c   SM653C  
label values sm653d   SM653D  
label values sm653e   SM653E  
label values sm653f   SM653F  
label values sm653g   SM653G  
label values sm653h   SM653H  
label values sm653i   SM653I  
label values sm653j   SM653J  
label values sm653k   SM653K  
label values sm653l   SM653L  
label values sm653m   SM653M  
label values sm653n   SM653N  
label values sm653q   SM653Q  
label values sm653r   SM653R  
label values sm653x   SM653X  
label values sm653y   SM653Y  
