infix using "CGIR5AFL.dct"

label variable caseid   "Case Identification"
label variable v000     "Country code and phase"
label variable v001     "Cluster number"
label variable v002     "Household number"
label variable v003     "Respondent's line number"
label variable v004     "Ultimate area unit"
label variable v005     "Sample weight"
label variable v006     "Month of interview"
label variable v007     "Year of interview"
label variable v008     "Date of interview (CMC)"
label variable v009     "Respondent's month of birth"
label variable v010     "Respondent's year of birth"
label variable v011     "Date of birth (CMC)"
label variable v012     "Current age - respondent"
label variable v013     "Age 5-year groups"
label variable v014     "Completeness of information"
label variable v015     "Result of individual interview"
label variable v016     "Day of interview"
label variable v017     "NA - CMC start of calendar"
label variable v018     "NA - Row of month of interview"
label variable v019     "NA - Length of calendar"
label variable v019a    "NA - Number of calendar columns"
label variable v020     "Ever-married sample"
label variable v021     "Primary sampling unit"
label variable v022     "Sample stratum number"
label variable v023     "Sample domain"
label variable v024     "Region"
label variable v025     "Type of place of residence"
label variable v026     "De facto place of residence"
label variable v027     "Number of visits"
label variable v028     "Interviewer identification"
label variable v029     "Keyer identification"
label variable v030     "Field supervisor"
label variable v031     "NA - Field editor"
label variable v032     "Office editor"
label variable v033     "NA - Ultimate area selection prob."
label variable v034     "Line number of husband"
label variable v040     "NA - Cluster altitude in meters"
label variable v042     "NA - Household selection for hemoglobin"
label variable v043     "NA - Selection for women's status module"
label variable v044     "NA - Selection for domestic violence module"
label variable v101     "Region"
label variable v102     "Type of place of residence"
label variable v103     "NA - Childhood place of residence"
label variable v104     "NA - Years lived in place of res."
label variable v105     "NA - Type of place of previous res."
label variable v106     "Highest educational level"
label variable v107     "Highest year of education"
label variable v113     "Source of drinking water"
label variable v115     "Time to get to water source"
label variable v116     "Type of toilet facility"
label variable v119     "Has electricity"
label variable v120     "Has radio"
label variable v121     "Has television"
label variable v122     "Has refrigerator"
label variable v123     "Has bicycle"
label variable v124     "Has motorcycle/scooter"
label variable v125     "Has car/truck"
label variable v127     "Main floor material"
label variable v128     "Main wall material"
label variable v129     "Main roof material"
label variable v130     "Religion"
label variable v131     "Ethnicity"
label variable v133     "Education in single years"
label variable v134     "De facto place of residence"
label variable v135     "Usual resident or visitor"
label variable v136     "Number of household members"
label variable v137     "Number of children 5 and under"
label variable v138     "Number of eligible women in HH"
label variable v139     "De jure region of residence"
label variable v140     "De jure type of place of res."
label variable v141     "De jure place of residence"
label variable v149     "Educational attainment"
label variable v150     "Relationship to household head"
label variable v151     "Sex of household head"
label variable v152     "Age of household head"
label variable v153     "Has telephone"
label variable awfactt  "All woman factor - total"
label variable awfactu  "All woman factor - urban/rural"
label variable awfactr  "All woman factor - regional"
label variable awfacte  "All woman factor - educational"
label variable awfactw  "All woman factor - wealth index"
label variable v155     "NA - Literacy"
label variable v156     "NA - Ever participated in a literacy program outside of prim"
label variable v157     "NA - Frequency of reading newspaper or magazine"
label variable v158     "NA - Frequency of listening to radio"
label variable v159     "NA - Frequency of watching television"
label variable v160     "Toilet facilities shared"
label variable v161     "Type of cooking fuel"
label variable v166     "Results of salt iodine test"
label variable v167     "Number of trips in last 12 months"
label variable v168     "Away for more than one month in last 12 months"
label variable v190     "Wealth index"
label variable v191     "Wealth index factor score (5 decimals)"
label variable ml101    "NA - Type of bednet(s) slept under last night"
label variable v201     "Total children ever born"
label variable v202     "Sons at home"
label variable v203     "Daughters at home"
label variable v204     "Sons elsewhere"
label variable v205     "Daughters elsewhere"
label variable v206     "Sons who have died"
label variable v207     "Daughters who have died"
label variable v208     "NA - Births in last five years"
label variable v209     "NA - Births in past year"
label variable v210     "NA - Births in month of interview"
label variable v211     "NA - Date of first birth (CMC)"
label variable v212     "NA - Age of respondent at 1st birth"
label variable v213     "Currently pregnant"
label variable v214     "NA - Duration of current pregnancy"
label variable v215     "NA - Time since last menstrual perd"
label variable v216     "NA - Menstruated in last six weeks"
label variable v217     "NA - Knowledge of ovulatory cycle"
label variable v218     "NA - Number of living children"
label variable v219     "NA - Living children + current preg"
label variable v220     "NA - Living children + curr preg 6+"
label variable v221     "NA - Marriage to first birth int."
label variable v222     "NA - Last birth to interview"
label variable v223     "NA - Completeness of curr preg. inf"
label variable v224     "NA - Entries in birth history"
label variable v225     "NA - Current pregnancy wanted"
label variable v226     "NA - Time since last period (comp)"
label variable v227     "NA - Flag for last period"
label variable v228     "NA - Ever had a terminated preg."
label variable v229     "NA - Month pregnancy ended"
label variable v230     "NA - Year pregnancy ended"
label variable v231     "NA - CMC pregnancy ended"
label variable v232     "NA - Completeness of last term. inf"
label variable v233     "NA - Months when pregnancy ended"
label variable v234     "NA - Other such pregnancies"
label variable v235     "NA - Index last child prior to cal."
label variable v237     "NA - Birth between last & interview"
label variable v238     "NA - Births in last three years"
label variable v239     "NA - Pregnancies terminated before calendar beginning"
label variable v240     "NA - Month of last termination prior to calendar"
label variable v241     "NA - Year of last termination prior to calendar"
label variable v242     "NA - CMC termination ended prior to calendar"
label variable v243     "NA - Completeness of last termination date prior to calendar"
label variable v452b    "Line no. of parent/caretaker"
label variable v473a    "Read consent statement (HIV)"
label variable v473b    "Result of measuring (HIV)"
label variable v501     "Current marital status"
label variable v502     "Currently/formerly/never marr."
label variable v503     "Number of unions"
label variable v504     "Husband lives in house"
label variable v505     "Number of other wives"
label variable v506     "NA - Wife rank number"
label variable v507     "Month of first marriage"
label variable v508     "Year of first marriage"
label variable v509     "Date of first marriage (CMC)"
label variable v510     "Completeness of date inform."
label variable v511     "Age at first marriage"
label variable v512     "Years since first marriage"
label variable v513     "Marital duration (grouped)"
label variable v525     "Age at first intercourse"
label variable v527     "Time since last intercourse"
label variable v528     "Time since last intercourse(g)"
label variable v529     "Time since last intercourse(imputed)"
label variable v530     "Flag for V529"
label variable v531     "Age at first intercourse (imp)"
label variable v532     "Flag for V531"
label variable v535     "Have ever been married"
label variable v536     "Recent sexual activity"
label variable v537     "Months of abstinence"
label variable v538     "NA - How previous marriage or union ended"
label variable v539     "NA - Who received most of late husbands property"
label variable v540     "NA - Respondent received any of late husband's assets or val"
label variable v541     "NA - Intends to postpone intercourse until marriage"
label variable v714     "Respondent currently working"
label variable v714a    "Have a job from which respondent was absent"
label variable v730     "Partners age"
label variable v731     "Worked in last 12 months"
label variable v750     "Heard sexual transmit. disease"
label variable v751     "Ever heard of AIDS"
label variable v754bp   "Reduce risk of getting AIDS by not having sex at all"
label variable v754cp   "Reduce chances of AIDS by always using condoms during sex"
label variable v754dp   "Reduce chance of AIDS: have 1 sex partner with no oth partne"
label variable v754jp   "Get AIDS from mosquito bites"
label variable v754wp   "Get AIDS by sharing food with person who has AIDS"
label variable v756     "Can a healthy person have AIDS"
label variable v761     "Last intercourse used condom"
label variable v761b    "Intercourse with other man (1) used condom"
label variable v761c    "Intercourse with other man (2) used condom"
label variable v762aa   "Source for condoms: Government hospital"
label variable v762ab   "Source for condoms: Government health center"
label variable v762ac   "NA - Source for condoms: Family planning clinic"
label variable v762ad   "NA - Source for condoms: Mobile clinic"
label variable v762ae   "NA - Source for condoms: Public field worker"
label variable v762af   "NA - Source for condoms: Other public"
label variable v762ag   "Source for condoms: Public CS - health post"
label variable v762ah   "NA - Source for condoms: Public CS"
label variable v762ai   "NA - Source for condoms: Public CS"
label variable v762aj   "Source for condoms: Private hosp, clinic"
label variable v762ak   "Source for condoms: Pharmacy"
label variable v762al   "Source for condoms: Private doctor"
label variable v762am   "NA - Source for condoms: Private mobile clinic"
label variable v762an   "NA - Source for condoms: Private field worker"
label variable v762ao   "NA - Source for condoms: Other private"
label variable v762ap   "Source for condoms: Private CS - nursing facilities"
label variable v762aq   "Source for condoms: Private CS social & medical center"
label variable v762ar   "Source for condoms: Private CS Association for family wellbe"
label variable v762as   "Source for condoms: Shop"
label variable v762at   "Source for condoms: Church"
label variable v762au   "Source for condoms: Friends, relatives"
label variable v762av   "Source for condoms: CS - traditional healer"
label variable v762aw   "Source for condoms: CS - itinerant vendor"
label variable v762ax   "Source for condoms: Other"
label variable v762az   "Source for condoms: DK source for condom"
label variable v762ba   "NA - Source for female condoms: Government hospital"
label variable v762bb   "NA - Source for female condoms: Government health center/pos"
label variable v762bc   "NA - Source for female condoms: Family planning clinic"
label variable v762bd   "NA - Source for female condoms: Mobile clinic"
label variable v762be   "NA - Source for female condoms: Public field worker"
label variable v762bf   "NA - Source for female condoms: Other public"
label variable v762bg   "NA - Source for female condoms: Public CS"
label variable v762bh   "NA - Source for female condoms: Public CS"
label variable v762bi   "NA - Source for female condoms: Public CS"
label variable v762bj   "NA - Source for female condoms: Private hosp, clinic"
label variable v762bk   "NA - Source for female condoms: Pharmacy"
label variable v762bl   "NA - Source for female condoms: Private doctor"
label variable v762bm   "NA - Source for female condoms: Private mobile clinic"
label variable v762bn   "NA - Source for female condoms: Private field worker"
label variable v762bo   "NA - Source for female condoms: Other private"
label variable v762bp   "NA - Source for female condoms: Private CS"
label variable v762bq   "NA - Source for female condoms: Private CS"
label variable v762br   "NA - Source for female condoms: Private CS"
label variable v762bs   "NA - Source for female condoms: Shop"
label variable v762bt   "NA - Source for female condoms: Church"
label variable v762bu   "NA - Source for female condoms: Friends, relatives"
label variable v762bv   "NA - Source for female condoms: CS"
label variable v762bw   "NA - Source for female condoms: CS"
label variable v762bx   "NA - Source for female condoms: Other"
label variable v762bz   "NA - Source for female condoms: DK source for condom"
label variable v763a    "Had any STD in last 12 months"
label variable v763b    "Had genital sore/ulcer in last 12 months"
label variable v763c    "Had genital discharge in last 12 months"
label variable v763d    "NA - Last 12 months had CS STD"
label variable v763e    "NA - Last 12 months had CS STD"
label variable v763f    "NA - Last 12 months had CS STD"
label variable v763g    "NA - Last 12 months had CS STD"
label variable v766a    "No. other than husband had sex in last 12 months"
label variable v766b    "No. had sex including husband in last 12 months"
label variable v767a    "Relationship with last sex partner"
label variable v767b    "Relationship with other sex partner (1)"
label variable v767c    "Relationship with other sex partner (2)"
label variable v768a    "NA - Length of time knows last partner"
label variable v768b    "NA - Length of time knows other partner (1)"
label variable v768c    "NA - Length of time knows other partner (2)"
label variable v769     "Could get a condom"
label variable v769a    "NA - Could get a female condom"
label variable v770     "Seek advice for last disease"
label variable v770a    "Seek advice STI: govt hospital"
label variable v770b    "Seek advice STI: health center"
label variable v770c    "NA - Seek advice STI: public VCT center"
label variable v770d    "NA - Seek advice STI: FP clinic"
label variable v770e    "NA - Seek advice STI: mobile clinic"
label variable v770f    "NA - Seek advice STI: fieldworker"
label variable v770g    "Seek advice STI: CS public health post"
label variable v770h    "NA - Seek advice STI: CS public"
label variable v770i    "NA - Seek advice STI: CS public"
label variable v770j    "NA - Seek advice STI: other public"
label variable v770k    "Seek advice STI: private hosp/clinic/doctor"
label variable v770l    "NA - Seek advice STI: private VCT center"
label variable v770m    "Seek advice STI: pharmacy"
label variable v770n    "NA - Seek advice STI: mobile clinic"
label variable v770o    "NA - Seek advice STI: fieldworker"
label variable v770p    "Seek advice STI: CS private doctor"
label variable v770q    "Seek advice STI: CS private nursing facilities"
label variable v770r    "Seek advice STI: CS private Association for family wellbeing"
label variable v770s    "NA - Seek advice STI: other private"
label variable v770t    "Seek advice STI: shop"
label variable v770u    "Seek advice STI: CS traditional healer"
label variable v770v    "Seek advice STI: CS spiritual medecine center"
label variable v770w    "Seek advice STI: CS itinerant vendor"
label variable v770x    "Seek advice other"
label variable v774a    "AIDS transmit. during pregnancy"
label variable v774b    "AIDS transmit. during delivery"
label variable v774c    "AIDS transmit. by breastfeeding"
label variable v775     "NA - Knows someone who has or died of AIDS"
label variable v777     "Allowed to keep AIDS infection secret"
label variable v778     "Willing to care for relative with AIDS"
label variable v779     "Person with AIDS allowed to continue teaching"
label variable v780     "NA - Should children be taught about condoms"
label variable v781     "Ever been tested for AIDS"
label variable v783     "Know a place to get AIDS test"
label variable v784a    "Place for AIDS test: govt hospital"
label variable v784b    "Place for AIDS test:health center"
label variable v784c    "Place for AIDS test: public VCT center"
label variable v784d    "NA - Place for AIDS test: FP clinic"
label variable v784e    "NA - Place for AIDS test: mobile clinic"
label variable v784f    "NA - Place for AIDS test: filedworker"
label variable v784g    "Place for AIDS test: CS public national lab"
label variable v784h    "NA - Place for AIDS test: CS public"
label variable v784i    "NA - Place for AIDS test: CS public"
label variable v784j    "NA - Place for AIDS test: other public"
label variable v784k    "Place for AIDS test: private hosp/clinic/doctor"
label variable v784l    "Place for AIDS test: private VCT center"
label variable v784m    "NA - Place for AIDS test: pharmacy"
label variable v784n    "NA - Place for AIDS test: mobile clinic"
label variable v784o    "NA - Place for AIDS test: fieldworker"
label variable v784p    "Place for AIDS test: CS private medical center"
label variable v784q    "Place for AIDS test: CS private social & medical center"
label variable v784r    "Place for AIDS test: CS private association for family wellb"
label variable v784s    "NA - Place for AIDS test: other private"
label variable v784t    "NA - Place for AIDS test: CS other"
label variable v784u    "NA - Place for AIDS test: CS other"
label variable v784v    "NA - Place for AIDS test: CS other"
label variable v784x    "Place for AIDS test: other"
label variable v785     "Heard about other STDs"
label variable v820     "Condom used at first sexual intercourse"
label variable v821a    "NA - Last sexual partner younger, the same age or older"
label variable v821b    "NA - Next to last sexual partner younger, the same age or ol"
label variable v821c    "NA - Second to last sexual partner younger, the same age or "
label variable v822     "NA - Wife justified to ask husband to use condom if he has S"
label variable v823     "Can get AIDS by witchcraft or supernatural means"
label variable v824     "Drugs to avoid AIDS transmission to baby during pregnancy"
label variable v825     "Would buy vegetables from vendor with AIDS"
label variable v826     "When was last time you were tested"
label variable v827     "Last test was on your own, offered or required"
label variable v828     "Did get results for last test"
label variable v829     "Place were last AIDS test was taken"
label variable v830     "NA - Age of first sexual partner"
label variable v831     "NA - First sexual partner younger, same age or older"
label variable v832b    "Time since last intercourse with next to last sexual partner"
label variable v832c    "Time since last intercourse with second to last sexual partn"
label variable v833a    "Used condom every time had sex with last sex partner (last 1"
label variable v833b    "Used condom every time had sex with next to last sex partner"
label variable v833c    "Used condom every time had sex with second to last sex partn"
label variable v834a    "NA - Age of last sexual partner"
label variable v834b    "NA - Age of next to last sexual partner"
label variable v834c    "NA - Age of second to last sexual partner"
label variable v835a    "NA - Alcohol consumption last time had sex"
label variable v835b    "NA - Alcohol consumption next to last time had sex"
label variable v835c    "NA - Alcohol consumption second to last time had sex"
label variable v836     "Total lifetime number of sexual partners"
label variable v837     "Heard of drugs to help infected people to live longer"
label variable v838a    "Talk during antenatal visit: AIDS transmitted mother to chil"
label variable v838b    "Talk during antenatal visit: things to do to prevent AIDS"
label variable v838c    "Talk during antenatal visit: getting tested for AIDS virus"
label variable v839     "Offered AIDS test as part of antenatal visit"
label variable v840     "Tested for AIDS virus as part of antenatal visit"
label variable v841     "Got results of AIDS test as part of antenatal visit"
label variable v842     "Place were AIDS test was taken as part of antenatal visit"
label variable v843     "Tested for AIDS since test as part of antenatal visit"
label variable v844     "NA - Knows someone denied health services because of AIDS la"
label variable v845     "NA - Knows someone denied social events because of AIDS last"
label variable v846     "NA - Knows someone verbally abused because of AIDS last 12 m"
label variable v847     "NA - People with AIDS should be ashamed of themselves"
label variable v848     "NA - People with AIDS should be blamed for bringing disease "
label variable v849     "NA - Children 12-14 should wait for sex until marriage"
label variable v850a    "NA - Can respondent refuse sex"
label variable v850b    "NA - Can ask partner to use condom"
label variable v851a    "NA - Young men should wait for sex until marriage"
label variable v851b    "NA - Most young men wait for sex until marriage"
label variable v851c    "NA - Unmarried sexually active men should only having sex wi"
label variable v851d    "NA - Most unmarried sexually active men have only one partne"
label variable v851e    "NA - Married men should only have sex with their wives"
label variable v851f    "NA - Most married men only have sex with their wives"
label variable v851g    "NA - Young women should wait for sex until marriage"
label variable v851h    "NA - Most young women wait for sex until marriage"
label variable v851i    "NA - Unmarried sexually active women should have only one pa"
label variable v851j    "NA - Most unmarried sexually active women have only one part"
label variable v851k    "NA - Married women should only have sex with their husbands"
label variable v851l    "NA - Most married women only have sex with their husbands"
label variable v801     "Time interview started"
label variable v802     "Time interview ended"
label variable v803     "Length of interview in minutes"
label variable v804     "Number of visits"
label variable v805     "Interviewer identification"
label variable v806     "Keyer identification"
label variable v811     "NA - Pres. children < 10 (sec 7)"
label variable v812     "NA - Pres. husband (sec 7)"
label variable v813     "NA - Pres. other males (sec 7)"
label variable v814     "NA - Pres. other females (sec 7)"
label variable aidsex   "Sex of respondent"
label variable sdistr   "District of residence"
label variable sarrond  "Arrondissement of residence"
label variable sreg     "Region"
label variable svilles  "Eleven cities"
label variable surbrur  "Urban/semi-urban/rural"
label variable sintlg   "Langue of interview"
label variable sinterp  "Interpreter"
label variable shivwgt  "HIV sample weights"
label variable s105     "Level of education"
label variable s117     "Occupation in last 12 months"
label variable s124     "Circumcised"
label variable s125     "Age at circumcision"
label variable s126     "Who performed circumcision"
label variable s212c    "Date of last birth (CMC)"
label variable s212f    "Date flag for Q212C"
label variable s212m    "Month of last birth"
label variable s212y    "Year of last birth"
label variable s213     "NA - How many years ago was last birth"
label variable s307_01  "Line numbers of wives, partners"
label variable s307_02  "Line numbers of wives, partners"
label variable s307_03  "Line numbers of wives, partners"
label variable s307_04  "Line numbers of wives, partners"
label variable s307_05  "Line numbers of wives, partners"
label variable s307_06  "Line numbers of wives, partners"
label variable s307_07  "Line numbers of wives, partners"
label variable s307_08  "Line numbers of wives, partners"
label variable s307_09  "Line numbers of wives, partners"
label variable s307_10  "Line numbers of wives, partners"
label variable s307_11  "Line numbers of wives, partners"
label variable s307_12  "Line numbers of wives, partners"
label variable s307_13  "Line numbers of wives, partners"
label variable s307_14  "Line numbers of wives, partners"
label variable s307_15  "Line numbers of wives, partners"
label variable s307_16  "Line numbers of wives, partners"
label variable s307_17  "Line numbers of wives, partners"
label variable s307_18  "Line numbers of wives, partners"
label variable s307_19  "Line numbers of wives, partners"
label variable s308_01  "Age of wife/partner"
label variable s308_02  "Age of wife/partner"
label variable s308_03  "Age of wife/partner"
label variable s308_04  "Age of wife/partner"
label variable s308_05  "Age of wife/partner"
label variable s308_06  "Age of wife/partner"
label variable s308_07  "Age of wife/partner"
label variable s308_08  "Age of wife/partner"
label variable s308_09  "Age of wife/partner"
label variable s308_10  "Age of wife/partner"
label variable s308_11  "Age of wife/partner"
label variable s308_12  "Age of wife/partner"
label variable s308_13  "Age of wife/partner"
label variable s308_14  "Age of wife/partner"
label variable s308_15  "Age of wife/partner"
label variable s308_16  "Age of wife/partner"
label variable s308_17  "Age of wife/partner"
label variable s308_18  "Age of wife/partner"
label variable s308_19  "Age of wife/partner"
label variable s333ca   "Time since first intercourse with last partner"
label variable s333cb   "Time since first intercourse with last partner (1)"
label variable s333cc   "Time since first intercourse with last partner (2)"
label variable s333da   "Times had sex with last sex partner"
label variable s333db   "Times had sex with other sex partner (1)"
label variable s333dc   "Times had sex with other sex partner (2)"
label variable s346     "Paid for sex last 12 months"
label variable s347     "Used condom during last paid sex"
label variable s348     "Used condom every time paid for sex in last 12 months"
label variable s351a    "Source for condoms: Government hospital"
label variable s351b    "Source for condoms: Government health center"
label variable s351c    "Source for condoms: Government health post"
label variable s351d    "Source for condoms: private clinic"
label variable s351e    "Source for condoms: private doctor"
label variable s351f    "Source for condoms: private nursing care facility"
label variable s351g    "Source for condoms: medical & social center"
label variable s351h    "Source for condoms: Association for family wellbeing"
label variable s351i    "Source for condoms: private pharmacy"
label variable s351j    "NA - Source for condoms: traditional healer"
label variable s351k    "Source for condoms: spiritual medical center"
label variable s351l    "Source for condoms: itinerant vendor"
label variable s351m    "Source for condoms: shop/market"
label variable s351n    "Source for condoms: bar/night club/hotel"
label variable s351o    "Source for condoms: relatives/friends"
label variable s351x    "Source for condoms: other"
label variable s415     "Antenatal visit for last pregnancy"
label variable s416a    "Place of ANC: Home"
label variable s416b    "Place of ANC: other home"
label variable s416c    "Place of ANC: public hospital"
label variable s416d    "Place of ANC: public health center"
label variable s416e    "Place of ANC: public health post"
label variable s416f    "Place of ANC: private clinic"
label variable s416g    "Place of ANC: private doctor"
label variable s416h    "Place of ANC: private nursing care facility"
label variable s416i    "Place of ANC: Social & medical center"
label variable s416j    "Place of ANC: spiritual medical center"
label variable s416x    "Place of ANC: other"
label variable s509a    "Seek advice STI: govt hospital"
label variable s509b    "Seek advice STI: health center"
label variable s509c    "Seek advice STI: health post"
label variable s509d    "Seek advice STI: private clinic"
label variable s509e    "Seek advice STI: private doctor"
label variable s509f    "Seek advice STI: private nursing care facility"
label variable s509g    "Seek advice STI: medical & social center"
label variable s509h    "Seek advice STI: Association for family wellbeing"
label variable s509i    "Seek advice STI: private pharmacy"
label variable s509j    "Seek advice STI: traditional healer"
label variable s509k    "Seek advice STI: spiritual medical center"
label variable s509l    "Seek advice STI: itinerant vendor"
label variable s509m    "Seek advice STI: shop/market"
label variable s509x    "Seek advice other"
label variable s607     "Read consent additional tests"

#delimit ;
label define V007    
  2009 "***Undefined Label"
;
label define V013    
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define V014    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define V015    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define V018    
     0 "No calendar"
;
label define V019    
     0 "No calendar"
;
label define V020    
     0 "All woman sample"
     1 "Ever married sample"
;
label define V023    
     0 "National"
     1 "Country specific"
;
label define V024    
     1 "Kouilou"
     2 "Niari"
     3 "Lékoumou"
     4 "Bouénza"
     5 "Pool"
     6 "Plateaux"
     7 "Cuvette"
     8 "Cuvette-Ouest"
     9 "Sangha"
    10 "Likouala"
    11 "Brazzaville"
    12 "Pointe-Noire"
;
label define V025    
     1 "Urban"
     2 "Rural"
;
label define V026    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V028    
   999 "Missing"
;
label define V029    
    99 "Missing"
;
label define V030    
   999 "Missing"
;
label define V031    
   999 "Missing"
;
label define V032    
    99 "Missing"
;
label define V034    
     0 "Husband not in HH"
;
label define V042    
     0 "Not selected"
     1 "Selected"
;
label define V043    
     0 "Woman not selected"
     1 "Woman selected"
;
label define V044    
     0 "Woman not selected"
     1 "Woman selected and interviewed"
     2 "Woman selected, but privacy not possible"
     3 "Woman selected, but not interviewed"
;
label define V101    
     1 "Kouilou"
     2 "Niari"
     3 "Lékoumou"
     4 "Bouénza"
     5 "Pool"
     6 "Plateaux"
     7 "Cuvette"
     8 "Cuvette-Ouest"
     9 "Sangha"
    10 "Likouala"
    11 "Brazzaville"
    12 "Pointe-Noire"
;
label define V102    
     1 "Urban"
     2 "Rural"
;
label define V103    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define V104    
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define V105    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define V106    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define V107    
    99 "Missing"
;
label define V113    
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irirgation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
    97 "Not dejure resident"
;
label define V115    
   996 "On premises"
   997 "Not dejure resident"
;
label define V116    
    10 "FLUSH TOILET"
    20 "PIT TOILET LATRINE"
    30 "NO FACILITY"
    31 "***Undefined Label"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "OTHER"
    97 "Not dejure resident"
;
label define V119    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V120    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V121    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V122    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V123    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V124    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V125    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V127    
    10 "NATURAL"
    11 "Earth, sand"
    20 "RUDIMENTARY"
    21 "Wood planks"
    30 "FINISHED"
    31 "Parquet, polished wood"
    32 "Vinyl, linoleum"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "OTHER"
    97 "Not dejure resident"
;
label define V128    
    10 "NATURAL"
    11 "Sand"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Sand bricks"
    23 "Metal"
    30 "FINISHED"
    31 "Bricks"
    32 "Cement"
    96 "OTHER"
    97 "Not dejure resident"
;
label define V129    
    10 "NATURAL"
    11 "Grass"
    30 "FINISHED"
    31 "Metal"
    32 "Roofing shingles"
    96 "OTHER"
    97 "Not dejure resident"
;
label define V130    
     1 "Catholic"
     2 "Protestant"
     3 "Muslim"
     4 "Kimbanguiste"
     5 "Armée du salut"
     6 "Zéphirin/matsouaniste/ngunza"
     7 "Adventist/jehova"
     8 "Animist"
     9 "Eglise de réveil"
    11 "None"
    96 "Other"
;
label define V131    
     1 "KONGO"
     2 "PUNU"
     3 "DUMA"
     4 "MBERE MBETI"
     5 "TEKE"
     6 "MBOCHI"
     7 "SANGHA"
     8 "KOTA"
     9 "KELE"
    10 "MAKAA"
    11 "BAYA"
    12 "OUBANGUIENS"
    13 "PYGMEES"
    14 "NATURALISES CONGOLAIS"
    95 "ETRANGERS"
;
label define V133    
    97 "Inconsistent"
;
label define V134    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V135    
     1 "Usual resident"
     2 "Visitor"
;
label define V139    
     0 "Abroad"
     1 "Kouilou"
     2 "Niari"
     3 "Lékoumou"
     4 "Bouénza"
     5 "Pool"
     6 "Plateaux"
     7 "Cuvette"
     8 "Cuvette-Ouest"
     9 "Sangha"
    10 "Likouala"
    11 "Brazzaville"
    12 "Pointe-Noire"
    97 "Not dejure resident"
;
label define V140    
     0 "Abroad"
     1 "Urban"
     2 "Rural"
     7 "Not dejure resident"
;
label define V141    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     7 "Not dejure resident"
;
label define V149    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define V150    
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    98 "DK"
;
label define V151    
     1 "Male"
     2 "Female"
;
label define V152    
    97 "97+"
    98 "DK"
;
label define V153    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V155    
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define V156    
     0 "No"
     1 "Yes"
;
label define V157    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V158    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V159    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V160    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V161    
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw / shrubs / grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in HH"
    96 "Other"
    97 "Not dejure resident"
;
label define V166    
     0 "0 ppm (no iodine)"
     7 "7 ppm"
    15 "15 ppm"
    30 "30 ppm"
   994 "Salt not tested"
   995 "No salt"
   997 "Not dejure resident"
;
label define V167    
     0 "None"
;
label define V168    
     0 "No"
     1 "Yes"
;
label define V190    
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define ML101   
     0 "No bednet"
     1 "Only treated bednets"
     2 "Both treated and untreated bednets"
     3 "Only untreated bednets"
;
label define V213    
     0 "No or unsure"
     1 "Yes"
;
label define V215    
   994 "In menopause"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
;
label define V216    
     0 "No"
     1 "Yes"
;
label define V217    
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define V220    
     6 "6+"
;
label define V221    
   996 "Negative interval"
;
label define V223    
     7 "Month - exact date"
     8 "None - date placed"
;
label define V225    
     1 "Then"
     2 "Later"
     3 "Not at all"
;
label define V226    
   994 "In menopause"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
;
label define V227    
     0 "No flag"
     1 "N > int. since birth"
     2 "N + amen. > interval"
     3 "N, but per. not ret."
     4 "95, but no birth"
     5 "95, but per.returned"
     6 "96, but per.returned"
     7 "N, last per. in preg"
     8 "96, had children"
     9 "N, per.bef.last birth"
;
label define V228    
     0 "No"
     1 "Yes"
;
label define V229    
    97 "Inconsistent"
    98 "DK"
;
label define V230    
  9997 "Inconsistent"
  9998 "DK"
;
label define V231    
  9997 "Inconsistent"
  9998 "DK"
;
label define V232    
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     6 "***Undefined Label"
     7 "Month"
     8 "None"
;
label define V233    
    97 "Inconsistent"
    98 "Don't know"
;
label define V234    
     0 "No"
     1 "Yes"
;
label define V235    
     0 "No prior child"
;
label define V237    
     0 "No"
     1 "Yes"
;
label define V239    
     0 "No"
     1 "Yes"
;
label define V240    
    97 "Inconsistent"
    98 "Don't know"
;
label define V241    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V242    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V243    
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     6 "***Undefined Label"
     7 "Month"
     8 "None"
;
label define V452B   
     0 "Not in household"
;
label define V473A   
     1 "Granted"
     2 "Parent/other refused"
     3 "Respondent refused"
;
label define V473B   
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define V501    
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define V502    
     0 "Never married"
     1 "Currently married"
     2 "Formerly married"
;
label define V503    
     1 "Once"
     2 "More than once"
;
label define V504    
     1 "Living with her"
     2 "Staying elsewhere"
;
label define V505    
     0 "No other wives"
    98 "Don't know"
;
label define V506    
    98 "Don't know"
;
label define V510    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "***Undefined Label"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define V513    
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define V525    
     0 "Not had intercourse"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
;
label define V527    
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   301 "Months: 1"
   399 "***Undefined Label"
   401 "Years: 1"
   499 "***Undefined Label"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define V528    
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
;
label define V529    
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define V530    
     0 "No flag"
     1 "N > int. since birth"
     2 "N + abst. > interval"
     3 "N, but sex not res."
     4 "96, but no birth"
     5 "96, but curr.preg."
     6 "96, but resumed sex"
     7 "N, last sex bef preg"
     8 "N, inconsis 4 weeks"
     9 "N, sex bef last birth"
;
label define V531    
     0 "Not had intercourse"
    97 "Inconsistent"
    98 "Don't know"
;
label define V532    
     0 "No flag"
     1 "After interview"
     2 "After concep >= 1 yr"
     3 "After concep < 1 yr"
     4 "At marr, never marr"
     5 "At marr,after concep"
     6 "After marriage"
;
label define V535    
     0 "No"
     1 "Formerly married"
     2 "Lived with a man"
;
label define V536    
     0 "Never had intercourse"
     1 "Active in last 4 weeks"
     2 "Not active in last 4 weeks - postpartum abst."
     3 "Not active in last 4 weeks - not postpartum abst."
;
label define V537    
    60 "60+"
    96 "Before last birth"
    97 "Inconsistent"
    98 "DK"
;
label define V538    
     1 "Death / widowhood"
     2 "Divorce"
     3 "Separation"
;
label define V539    
     1 "Respondent"
     2 "Other wife"
     3 "Spouse's children"
     4 "Spouse's family"
     6 "Other"
     7 "No property"
;
label define V540    
     0 "No"
     1 "Yes"
;
label define V541    
     0 "No"
     1 "Yes"
     8 "Don't know / unsure"
;
label define V714    
     0 "No"
     1 "Yes"
;
label define V714A   
     0 "No"
     1 "Yes"
;
label define V730    
    96 "96+"
    97 "***Undefined Label"
    98 "DK"
;
label define V731    
     0 "No"
     1 "In the past year"
     2 "Currently working"
     3 "Have a job, but on leave last 7 days"
;
label define V750    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V751    
     0 "No"
     1 "Yes"
;
label define V754BP  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V754CP  
     0 "No"
     1 "Reduce chances of AIDS by always using condoms during sex"
     8 "Don't know"
;
label define V754DP  
     0 "No"
     1 "Reduce chance of AIDS: have 1 sex partner with no oth partner"
     8 "Don't know"
;
label define V754JP  
     0 "No"
     1 "Get AIDS from mosquito bites"
     8 "Don't know"
;
label define V754WP  
     0 "No"
     1 "Get AIDS by sharing food with person who has AIDS"
     8 "Don't know"
;
label define V756    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V761    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V761B   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V761C   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V762AA  
     0 "No"
     1 "Yes"
;
label define V762AB  
     0 "No"
     1 "Yes"
;
label define V762AC  
     0 "No"
     1 "Yes"
;
label define V762AD  
     0 "No"
     1 "Yes"
;
label define V762AE  
     0 "No"
     1 "Yes"
;
label define V762AF  
     0 "No"
     1 "Yes"
;
label define V762AG  
     0 "No"
     1 "Yes"
;
label define V762AH  
     0 "No"
     1 "Yes"
;
label define V762AI  
     0 "No"
     1 "Yes"
;
label define V762AJ  
     0 "No"
     1 "Yes"
;
label define V762AK  
     0 "No"
     1 "Yes"
;
label define V762AL  
     0 "No"
     1 "Yes"
;
label define V762AM  
     0 "No"
     1 "Yes"
;
label define V762AN  
     0 "No"
     1 "Yes"
;
label define V762AO  
     0 "No"
     1 "Yes"
;
label define V762AP  
     0 "No"
     1 "Yes"
;
label define V762AQ  
     0 "No"
     1 "Yes"
;
label define V762AR  
     0 "No"
     1 "Yes"
;
label define V762AS  
     0 "No"
     1 "Yes"
;
label define V762AT  
     0 "No"
     1 "Yes"
;
label define V762AU  
     0 "No"
     1 "Yes"
;
label define V762AV  
     0 "No"
     1 "Yes"
;
label define V762AW  
     0 "No"
     1 "Yes"
;
label define V762AX  
     0 "No"
     1 "Yes"
;
label define V762AZ  
     0 "No: source known"
     1 "Yes: no source known"
;
label define V762BA  
     0 "No"
     1 "Yes"
;
label define V762BB  
     0 "No"
     1 "Yes"
;
label define V762BC  
     0 "No"
     1 "Yes"
;
label define V762BD  
     0 "No"
     1 "Yes"
;
label define V762BE  
     0 "No"
     1 "Yes"
;
label define V762BF  
     0 "No"
     1 "Yes"
;
label define V762BG  
     0 "No"
     1 "Yes"
;
label define V762BH  
     0 "No"
     1 "Yes"
;
label define V762BI  
     0 "No"
     1 "Yes"
;
label define V762BJ  
     0 "No"
     1 "Yes"
;
label define V762BK  
     0 "No"
     1 "Yes"
;
label define V762BL  
     0 "No"
     1 "Yes"
;
label define V762BM  
     0 "No"
     1 "Yes"
;
label define V762BN  
     0 "No"
     1 "Yes"
;
label define V762BO  
     0 "No"
     1 "Yes"
;
label define V762BP  
     0 "No"
     1 "Yes"
;
label define V762BQ  
     0 "No"
     1 "Yes"
;
label define V762BR  
     0 "No"
     1 "Yes"
;
label define V762BS  
     0 "No"
     1 "Yes"
;
label define V762BT  
     0 "No"
     1 "Yes"
;
label define V762BU  
     0 "No"
     1 "Yes"
;
label define V762BV  
     0 "No"
     1 "Yes"
;
label define V762BW  
     0 "No"
     1 "Yes"
;
label define V762BX  
     0 "No"
     1 "Yes"
;
label define V762BZ  
     0 "No: source known"
     1 "Yes: no source known"
;
label define V763A   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V763B   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V763C   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V763D   
     0 "No"
     1 "Country specific"
     8 "DK"
;
label define V763E   
     0 "No"
     1 "Country specific"
     8 "DK"
;
label define V763F   
     0 "No"
     1 "Country specific"
     8 "DK"
;
label define V763G   
     0 "No"
     1 "Country specific"
     8 "DK"
;
label define V766A   
    98 "DK"
;
label define V766B   
    98 "DK"
;
label define V767A   
     1 "Spouse"
     2 "Boyfriend not living with respondent"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define V767B   
     1 "Spouse"
     2 "Boyfriend not living with respondent"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define V767C   
     1 "Spouse"
     2 "Boyfriend not living with respondent"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define V768A   
   201 "One month"
   301 "One year"
;
label define V768B   
   101 "One day"
   201 "One month"
   301 "One year"
;
label define V768C   
   101 "One day"
   201 "One month"
   301 "One year"
;
label define V769    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V769A   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V770    
     0 "No"
     1 "Yes"
;
label define V770A   
     0 "No"
     1 "Yes"
;
label define V770B   
     0 "No"
     1 "Yes"
;
label define V770C   
     0 "No"
     1 "Yes"
;
label define V770D   
     0 "No"
     1 "Yes"
;
label define V770E   
     0 "No"
     1 "Yes"
;
label define V770F   
     0 "No"
     1 "Yes"
;
label define V770G   
     0 "No"
     1 "Yes"
;
label define V770H   
     0 "No"
     1 "Yes"
;
label define V770I   
     0 "No"
     1 "Yes"
;
label define V770J   
     0 "No"
     1 "Yes"
;
label define V770K   
     0 "No"
     1 "Yes"
;
label define V770L   
     0 "No"
     1 "Yes"
;
label define V770M   
     0 "No"
     1 "Yes"
;
label define V770N   
     0 "No"
     1 "Yes"
;
label define V770O   
     0 "No"
     1 "Yes"
;
label define V770P   
     0 "No"
     1 "Yes"
;
label define V770Q   
     0 "No"
     1 "Yes"
;
label define V770R   
     0 "No"
     1 "Yes"
;
label define V770S   
     0 "No"
     1 "Yes"
;
label define V770T   
     0 "No"
     1 "Yes"
;
label define V770U   
     0 "No"
     1 "Yes"
;
label define V770V   
     0 "No"
     1 "Yes"
;
label define V770W   
     0 "No"
     1 "Yes"
;
label define V770X   
     0 "No"
     1 "Yes"
;
label define V774A   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V774B   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V774C   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V775    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V777    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V778    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V779    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V780    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V781    
     0 "No"
     1 "Yes"
;
label define V783    
     0 "No"
     1 "Yes"
;
label define V784A   
     0 "No"
     1 "Yes"
;
label define V784B   
     0 "No"
     1 "Yes"
;
label define V784C   
     0 "No"
     1 "Yes"
;
label define V784D   
     0 "No"
     1 "Yes"
;
label define V784E   
     0 "No"
     1 "Yes"
;
label define V784F   
     0 "No"
     1 "Yes"
;
label define V784G   
     0 "No"
     1 "Yes"
;
label define V784H   
     0 "No"
     1 "Yes"
;
label define V784I   
     0 "No"
     1 "Yes"
;
label define V784J   
     0 "No"
     1 "Yes"
;
label define V784K   
     0 "No"
     1 "Yes"
;
label define V784L   
     0 "No"
     1 "Yes"
;
label define V784M   
     0 "No"
     1 "Yes"
;
label define V784N   
     0 "No"
     1 "Yes"
;
label define V784O   
     0 "No"
     1 "Yes"
;
label define V784P   
     0 "No"
     1 "Yes"
;
label define V784Q   
     0 "No"
     1 "Yes"
;
label define V784R   
     0 "No"
     1 "Yes"
;
label define V784S   
     0 "No"
     1 "Yes"
;
label define V784T   
     0 "No"
     1 "Yes"
;
label define V784U   
     0 "No"
     1 "Yes"
;
label define V784V   
     0 "No"
     1 "Yes"
;
label define V784X   
     0 "No"
     1 "Yes"
;
label define V785    
     0 "No"
     1 "Yes"
;
label define V820    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V821A   
     1 "Younger"
     2 "About the same age"
     3 "Less than 10 years older"
     4 "10 or more years older"
     5 "Older, don't know difference"
     8 "Don't know"
;
label define V821B   
     1 "Younger"
     2 "About the same age"
     3 "Less than 10 years older"
     4 "10 or more years older"
     5 "Older, don't know difference"
     8 "Don't know"
;
label define V821C   
     1 "Younger"
     2 "About the same age"
     3 "Less than 10 years older"
     4 "10 or more years older"
     5 "Older, don't know difference"
     8 "Don't know"
;
label define V822    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V823    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V824    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V825    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V826    
     1 "Less than 12 months"
     2 "12-23 months"
     3 "2 years or more"
;
label define V827    
     1 "Asked for the test"
     2 "Offered and accepted"
     3 "Required"
;
label define V828    
     0 "No"
     1 "Yes"
;
label define V829    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Public national lab"
    14 "Public stand-alone VCT center"
    20 "PRIVATE MEDICAL"
    21 "Private hospital, clinic or doctor"
    22 "Private medical center"
    23 "Private lab"
    24 "Private medical & social center"
    25 "Association for family wellbeing"
    96 "Other"
;
label define V830    
    95 "95+"
    98 "Don't know"
;
label define V831    
     1 "Younger"
     2 "About the same age"
     3 "Less than 10 years older"
     4 "10 or more years older"
     5 "Older, don't know difference"
     8 "Don't know"
;
label define V832B   
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   301 "Months: 1"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define V832C   
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   301 "Months: 1"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define V833A   
     0 "No"
     1 "Yes"
;
label define V833B   
     0 "No"
     1 "Yes"
;
label define V833C   
     0 "No"
     1 "Yes"
;
label define V834A   
    95 "95+"
    98 "Don't know"
;
label define V834B   
    95 "95+"
    98 "Don't know"
;
label define V834C   
    95 "95+"
    98 "Don't know"
;
label define V835A   
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define V835B   
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define V835C   
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define V836    
    95 "95+"
    98 "Don't know"
;
label define V837    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V838A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V838B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V838C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V839    
     0 "No"
     1 "Yes"
;
label define V840    
     0 "No"
     1 "Yes"
;
label define V841    
     0 "No"
     1 "Yes"
;
label define V842    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Public national lab"
    14 "Public stand-alone VCT center"
    20 "PRIVATE MEDICAL"
    21 "Private hospital, clinic or doctor"
    22 "Private medical center"
    23 "Private lab"
    24 "Private medical & social center"
    25 "Association for family wellbeing"
    96 "Other"
    96 "Other"
;
label define V843    
     0 "No"
     1 "Yes"
;
label define V844    
     0 "No"
     1 "Yes"
     2 "Don't know anyone with AIDS"
;
label define V845    
     0 "No"
     1 "Yes"
;
label define V846    
     0 "No"
     1 "Yes"
;
label define V847    
     0 "Disagree"
     1 "Agree"
     8 "Don't know / no opinion"
;
label define V848    
     0 "Disagree"
     1 "Agree"
     8 "Don't know / no opinion"
;
label define V849    
     0 "No"
     1 "Yes"
     8 "Don't know / depends"
;
label define V850A   
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define V850B   
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define V851A   
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define V851B   
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define V851C   
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define V851D   
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define V851E   
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define V851F   
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define V851G   
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define V851H   
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define V851I   
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define V851J   
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define V851K   
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define V851L   
     0 "No"
     1 "Yes"
     8 "DK, not sure, depends"
;
label define V801    
  9999 "Missing"
;
label define V802    
  9999 "Missing"
;
label define V803    
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define V805    
   999 "Missing"
;
label define V806    
    99 "Missing"
;
label define V811    
     0 "No"
     1 "Yes - listening"
     2 "Yes - not listening"
;
label define V812    
     0 "No"
     1 "Yes - listening"
     2 "Yes - not listening"
;
label define V813    
     0 "No"
     1 "Yes - listening"
     2 "Yes - not listening"
;
label define V814    
     0 "No"
     1 "Yes - listening"
     2 "Yes - not listening"
;
label define AIDSEX  
     1 "Male"
     2 "Female"
;
label define SREG    
     1 "Brazzaville"
     2 "Pointe-Noire"
     3 "Sud"
     4 "Nord"
;
label define SVILLES 
     0 "No"
     1 "Yes"
;
label define SURBRUR 
     1 "Urban"
     2 "Semi-urban"
     3 "Rural"
;
label define SINTLG  
     1 "Français"
     2 "Lingala"
     3 "Kituba"
     4 "Autre"
;
label define SINTERP 
     1 "Oui"
     2 "Non"
;
label define S105    
     1 "Primary"
     2 "Secondary I"
     3 "Secondary II"
     4 "Higher"
     8 "DK"
;
label define S117    
     1 "Aller à l'école / étudier"
     2 "Chercher un travail"
     3 "Retraité"
     4 "Trop malade pour travailler"
     5 "Handicapé/peut pas travailler"
     6 "Ménagère/soins enfants"
    96 "Autre"
;
label define S124    
     0 "No"
     1 "Yes"
;
label define S125    
     1 "Less than 5 years/ during infancy"
     2 "5-9 years"
     3 "10 years or more"
     8 "Don't know"
;
label define S126    
     1 "Health worker"
     2 "Other"
     8 "Don't know"
;
label define S212F   
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define S212M   
    98 "Don't Know"
;
label define S212Y   
  9998 "Don't know"
;
label define S213    
    98 "Don't know"
;
label define S307_01 
     0 "Wife not in HH"
;
label define S307_02 
     0 "Wife not in HH"
;
label define S307_03 
     0 "Wife not in HH"
;
label define S307_04 
     0 "Wife not in HH"
;
label define S307_05 
     0 "Wife not in HH"
;
label define S307_06 
     0 "Wife not in HH"
;
label define S307_07 
     0 "Wife not in HH"
;
label define S307_08 
     0 "Wife not in HH"
;
label define S307_09 
     0 "Wife not in HH"
;
label define S307_10 
     0 "Wife not in HH"
;
label define S307_11 
     0 "Wife not in HH"
;
label define S307_12 
     0 "Wife not in HH"
;
label define S307_13 
     0 "Wife not in HH"
;
label define S307_14 
     0 "Wife not in HH"
;
label define S307_15 
     0 "Wife not in HH"
;
label define S307_16 
     0 "Wife not in HH"
;
label define S307_17 
     0 "Wife not in HH"
;
label define S307_18 
     0 "Wife not in HH"
;
label define S307_19 
     0 "Wife not in HH"
;
label define S308_01 
    97 "Inconsistent"
    98 "DK"
;
label define S308_02 
    97 "Inconsistent"
    98 "DK"
;
label define S308_03 
    97 "Inconsistent"
    98 "DK"
;
label define S308_04 
    97 "Inconsistent"
    98 "DK"
;
label define S308_05 
    97 "Inconsistent"
    98 "DK"
;
label define S308_06 
    97 "Inconsistent"
    98 "DK"
;
label define S308_07 
    97 "Inconsistent"
    98 "DK"
;
label define S308_08 
    97 "Inconsistent"
    98 "DK"
;
label define S308_09 
    97 "Inconsistent"
    98 "DK"
;
label define S308_10 
    97 "Inconsistent"
    98 "DK"
;
label define S308_11 
    97 "Inconsistent"
    98 "DK"
;
label define S308_12 
    97 "Inconsistent"
    98 "DK"
;
label define S308_13 
    97 "Inconsistent"
    98 "DK"
;
label define S308_14 
    97 "Inconsistent"
    98 "DK"
;
label define S308_15 
    97 "Inconsistent"
    98 "DK"
;
label define S308_16 
    97 "Inconsistent"
    98 "DK"
;
label define S308_17 
    97 "Inconsistent"
    98 "DK"
;
label define S308_18 
    97 "Inconsistent"
    98 "DK"
;
label define S308_19 
    97 "Inconsistent"
    98 "DK"
;
label define S333CA  
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   299 "***Undefined Label"
   301 "Months: 1"
   399 "***Undefined Label"
   401 "Years: 1"
   499 "***Undefined Label"
   997 "Inconsistent"
   998 "Don't know"
;
label define S333CB  
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   299 "***Undefined Label"
   301 "Months: 1"
   399 "***Undefined Label"
   401 "Years: 1"
   499 "***Undefined Label"
   997 "Inconsistent"
   998 "Don't know"
;
label define S333CC  
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   299 "***Undefined Label"
   301 "Months: 1"
   399 "***Undefined Label"
   401 "Years: 1"
   499 "***Undefined Label"
   997 "Inconsistent"
   998 "Don't know"
;
label define S333DA  
     1 "One time"
     2 "Two times"
     3 "More"
;
label define S333DB  
     1 "One time"
     2 "Two times"
     3 "More"
;
label define S333DC  
     1 "One time"
     2 "Two times"
     3 "More"
;
label define S346    
     0 "No"
     1 "Yes"
;
label define S347    
     0 "No"
     1 "Yes"
;
label define S348    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define S351A   
     0 "No"
     1 "Yes"
;
label define S351B   
     0 "No"
     1 "Yes"
;
label define S351C   
     0 "No"
     1 "Yes"
;
label define S351D   
     0 "No"
     1 "Yes"
;
label define S351E   
     0 "No"
     1 "Yes"
;
label define S351F   
     0 "No"
     1 "Yes"
;
label define S351G   
     0 "No"
     1 "Yes"
;
label define S351H   
     0 "No"
     1 "Yes"
;
label define S351I   
     0 "No"
     1 "Yes"
;
label define S351J   
     0 "No"
     1 "Yes"
;
label define S351K   
     0 "No"
     1 "Yes"
;
label define S351L   
     0 "No"
     1 "Yes"
;
label define S351M   
     0 "No"
     1 "Yes"
;
label define S351N   
     0 "No"
     1 "Yes"
;
label define S351O   
     0 "No"
     1 "Yes"
;
label define S351X   
     0 "No"
     1 "Yes"
;
label define S415    
     0 "No"
     1 "Yes"
;
label define S416A   
     0 "No"
     1 "Yes"
;
label define S416B   
     0 "No"
     1 "Yes"
;
label define S416C   
     0 "No"
     1 "Yes"
;
label define S416D   
     0 "No"
     1 "Yes"
;
label define S416E   
     0 "No"
     1 "Yes"
;
label define S416F   
     0 "No"
     1 "Yes"
;
label define S416G   
     0 "No"
     1 "Yes"
;
label define S416H   
     0 "No"
     1 "Yes"
;
label define S416I   
     0 "No"
     1 "Yes"
;
label define S416J   
     0 "No"
     1 "Yes"
;
label define S416X   
     0 "No"
     1 "Yes"
;
label define S509A   
     0 "No"
     1 "Yes"
;
label define S509B   
     0 "No"
     1 "Yes"
;
label define S509C   
     0 "No"
     1 "Yes"
;
label define S509D   
     0 "No"
     1 "Yes"
;
label define S509E   
     0 "No"
     1 "Yes"
;
label define S509F   
     0 "No"
     1 "Yes"
;
label define S509G   
     0 "No"
     1 "Yes"
;
label define S509H   
     0 "No"
     1 "Yes"
;
label define S509I   
     0 "No"
     1 "Yes"
;
label define S509J   
     0 "No"
     1 "Yes"
;
label define S509K   
     0 "No"
     1 "Yes"
;
label define S509L   
     0 "No"
     1 "Yes"
;
label define S509M   
     0 "No"
     1 "Yes"
;
label define S509X   
     0 "No"
     1 "Yes"
;
label define S607    
     1 "Granted"
     2 "Parent/other refused"
     3 "Respondent refused"
;

#delimit cr
label values v007     V007    
label values v013     V013    
label values v014     V014    
label values v015     V015    
label values v018     V018    
label values v019     V019    
label values v020     V020    
label values v023     V023    
label values v024     V024    
label values v025     V025    
label values v026     V026    
label values v034     V034    
label values v042     V042    
label values v043     V043    
label values v044     V044    
label values v101     V101    
label values v102     V102    
label values v103     V103    
label values v104     V104    
label values v105     V105    
label values v106     V106    
label values v113     V113    
label values v115     V115    
label values v116     V116    
label values v119     V119    
label values v120     V120    
label values v121     V121    
label values v122     V122    
label values v123     V123    
label values v124     V124    
label values v125     V125    
label values v127     V127    
label values v128     V128    
label values v129     V129    
label values v130     V130    
label values v131     V131    
label values v133     V133    
label values v134     V134    
label values v135     V135    
label values v139     V139    
label values v140     V140    
label values v141     V141    
label values v149     V149    
label values v150     V150    
label values v151     V151    
label values v152     V152    
label values v153     V153    
label values v155     V155    
label values v156     V156    
label values v157     V157    
label values v158     V158    
label values v159     V159    
label values v160     V160    
label values v161     V161    
label values v166     V166    
label values v167     V167    
label values v168     V168    
label values v190     V190    
label values ml101    ML101   
label values v213     V213    
label values v215     V215    
label values v216     V216    
label values v217     V217    
label values v220     V220    
label values v221     V221    
label values v223     V223    
label values v225     V225    
label values v226     V226    
label values v227     V227    
label values v228     V228    
label values v229     V229    
label values v230     V230    
label values v231     V231    
label values v232     V232    
label values v233     V233    
label values v234     V234    
label values v235     V235    
label values v237     V237    
label values v239     V239    
label values v240     V240    
label values v241     V241    
label values v242     V242    
label values v243     V243    
label values v452b    V452B   
label values v473a    V473A   
label values v473b    V473B   
label values v501     V501    
label values v502     V502    
label values v503     V503    
label values v504     V504    
label values v505     V505    
label values v506     V506    
label values v510     V510    
label values v513     V513    
label values v525     V525    
label values v527     V527    
label values v528     V528    
label values v529     V529    
label values v530     V530    
label values v531     V531    
label values v532     V532    
label values v535     V535    
label values v536     V536    
label values v537     V537    
label values v538     V538    
label values v539     V539    
label values v540     V540    
label values v541     V541    
label values v714     V714    
label values v714a    V714A   
label values v730     V730    
label values v731     V731    
label values v750     V750    
label values v751     V751    
label values v754bp   V754BP  
label values v754cp   V754CP  
label values v754dp   V754DP  
label values v754jp   V754JP  
label values v754wp   V754WP  
label values v756     V756    
label values v761     V761    
label values v761b    V761B   
label values v761c    V761C   
label values v762aa   V762AA  
label values v762ab   V762AB  
label values v762ac   V762AC  
label values v762ad   V762AD  
label values v762ae   V762AE  
label values v762af   V762AF  
label values v762ag   V762AG  
label values v762ah   V762AH  
label values v762ai   V762AI  
label values v762aj   V762AJ  
label values v762ak   V762AK  
label values v762al   V762AL  
label values v762am   V762AM  
label values v762an   V762AN  
label values v762ao   V762AO  
label values v762ap   V762AP  
label values v762aq   V762AQ  
label values v762ar   V762AR  
label values v762as   V762AS  
label values v762at   V762AT  
label values v762au   V762AU  
label values v762av   V762AV  
label values v762aw   V762AW  
label values v762ax   V762AX  
label values v762az   V762AZ  
label values v762ba   V762BA  
label values v762bb   V762BB  
label values v762bc   V762BC  
label values v762bd   V762BD  
label values v762be   V762BE  
label values v762bf   V762BF  
label values v762bg   V762BG  
label values v762bh   V762BH  
label values v762bi   V762BI  
label values v762bj   V762BJ  
label values v762bk   V762BK  
label values v762bl   V762BL  
label values v762bm   V762BM  
label values v762bn   V762BN  
label values v762bo   V762BO  
label values v762bp   V762BP  
label values v762bq   V762BQ  
label values v762br   V762BR  
label values v762bs   V762BS  
label values v762bt   V762BT  
label values v762bu   V762BU  
label values v762bv   V762BV  
label values v762bw   V762BW  
label values v762bx   V762BX  
label values v762bz   V762BZ  
label values v763a    V763A   
label values v763b    V763B   
label values v763c    V763C   
label values v763d    V763D   
label values v763e    V763E   
label values v763f    V763F   
label values v763g    V763G   
label values v766a    V766A   
label values v766b    V766B   
label values v767a    V767A   
label values v767b    V767B   
label values v767c    V767C   
label values v768a    V768A   
label values v768b    V768B   
label values v768c    V768C   
label values v769     V769    
label values v769a    V769A   
label values v770     V770    
label values v770a    V770A   
label values v770b    V770B   
label values v770c    V770C   
label values v770d    V770D   
label values v770e    V770E   
label values v770f    V770F   
label values v770g    V770G   
label values v770h    V770H   
label values v770i    V770I   
label values v770j    V770J   
label values v770k    V770K   
label values v770l    V770L   
label values v770m    V770M   
label values v770n    V770N   
label values v770o    V770O   
label values v770p    V770P   
label values v770q    V770Q   
label values v770r    V770R   
label values v770s    V770S   
label values v770t    V770T   
label values v770u    V770U   
label values v770v    V770V   
label values v770w    V770W   
label values v770x    V770X   
label values v774a    V774A   
label values v774b    V774B   
label values v774c    V774C   
label values v775     V775    
label values v777     V777    
label values v778     V778    
label values v779     V779    
label values v780     V780    
label values v781     V781    
label values v783     V783    
label values v784a    V784A   
label values v784b    V784B   
label values v784c    V784C   
label values v784d    V784D   
label values v784e    V784E   
label values v784f    V784F   
label values v784g    V784G   
label values v784h    V784H   
label values v784i    V784I   
label values v784j    V784J   
label values v784k    V784K   
label values v784l    V784L   
label values v784m    V784M   
label values v784n    V784N   
label values v784o    V784O   
label values v784p    V784P   
label values v784q    V784Q   
label values v784r    V784R   
label values v784s    V784S   
label values v784t    V784T   
label values v784u    V784U   
label values v784v    V784V   
label values v784x    V784X   
label values v785     V785    
label values v820     V820    
label values v821a    V821A   
label values v821b    V821B   
label values v821c    V821C   
label values v822     V822    
label values v823     V823    
label values v824     V824    
label values v825     V825    
label values v826     V826    
label values v827     V827    
label values v828     V828    
label values v829     V829    
label values v830     V830    
label values v831     V831    
label values v832b    V832B   
label values v832c    V832C   
label values v833a    V833A   
label values v833b    V833B   
label values v833c    V833C   
label values v834a    V834A   
label values v834b    V834B   
label values v834c    V834C   
label values v835a    V835A   
label values v835b    V835B   
label values v835c    V835C   
label values v836     V836    
label values v837     V837    
label values v838a    V838A   
label values v838b    V838B   
label values v838c    V838C   
label values v839     V839    
label values v840     V840    
label values v841     V841    
label values v842     V842    
label values v843     V843    
label values v844     V844    
label values v845     V845    
label values v846     V846    
label values v847     V847    
label values v848     V848    
label values v849     V849    
label values v850a    V850A   
label values v850b    V850B   
label values v851a    V851A   
label values v851b    V851B   
label values v851c    V851C   
label values v851d    V851D   
label values v851e    V851E   
label values v851f    V851F   
label values v851g    V851G   
label values v851h    V851H   
label values v851i    V851I   
label values v851j    V851J   
label values v851k    V851K   
label values v851l    V851L   
label values v803     V803    
label values v811     V811    
label values v812     V812    
label values v813     V813    
label values v814     V814    
label values aidsex   AIDSEX  
label values sreg     SREG    
label values svilles  SVILLES 
label values surbrur  SURBRUR 
label values sintlg   SINTLG  
label values sinterp  SINTERP 
label values s105     S105    
label values s117     S117    
label values s124     S124    
label values s125     S125    
label values s126     S126    
label values s212f    S212F   
label values s212m    S212M   
label values s212y    S212Y   
label values s213     S213    
label values s307_01  S307    
label values s307_02  S307    
label values s307_03  S307    
label values s307_04  S307    
label values s307_05  S307    
label values s307_06  S307    
label values s307_07  S307    
label values s307_08  S307    
label values s307_09  S307    
label values s307_10  S307    
label values s307_11  S307    
label values s307_12  S307    
label values s307_13  S307    
label values s307_14  S307    
label values s307_15  S307    
label values s307_16  S307    
label values s307_17  S307    
label values s307_18  S307    
label values s307_19  S307    
label values s308_01  S308    
label values s308_02  S308    
label values s308_03  S308    
label values s308_04  S308    
label values s308_05  S308    
label values s308_06  S308    
label values s308_07  S308    
label values s308_08  S308    
label values s308_09  S308    
label values s308_10  S308    
label values s308_11  S308    
label values s308_12  S308    
label values s308_13  S308    
label values s308_14  S308    
label values s308_15  S308    
label values s308_16  S308    
label values s308_17  S308    
label values s308_18  S308    
label values s308_19  S308    
label values s333ca   S333CA  
label values s333cb   S333CB  
label values s333cc   S333CC  
label values s333da   S333DA  
label values s333db   S333DB  
label values s333dc   S333DC  
label values s346     S346    
label values s347     S347    
label values s348     S348    
label values s351a    S351A   
label values s351b    S351B   
label values s351c    S351C   
label values s351d    S351D   
label values s351e    S351E   
label values s351f    S351F   
label values s351g    S351G   
label values s351h    S351H   
label values s351i    S351I   
label values s351j    S351J   
label values s351k    S351K   
label values s351l    S351L   
label values s351m    S351M   
label values s351n    S351N   
label values s351o    S351O   
label values s351x    S351X   
label values s415     S415    
label values s416a    S416A   
label values s416b    S416B   
label values s416c    S416C   
label values s416d    S416D   
label values s416e    S416E   
label values s416f    S416F   
label values s416g    S416G   
label values s416h    S416H   
label values s416i    S416I   
label values s416j    S416J   
label values s416x    S416X   
label values s509a    S509A   
label values s509b    S509B   
label values s509c    S509C   
label values s509d    S509D   
label values s509e    S509E   
label values s509f    S509F   
label values s509g    S509G   
label values s509h    S509H   
label values s509i    S509I   
label values s509j    S509J   
label values s509k    S509K   
label values s509l    S509L   
label values s509m    S509M   
label values s509x    S509X   
label values s607     S607    
