infix using "C:\COUNTRIES\KE7A\KEKR7AFL.dct"

label variable caseid   "Case Identification"
label variable hidx     "Index to birth history"
label variable v000     "Country code and phase"
label variable v001     "Cluster number"
label variable v002     "Household number"
label variable v003     "Respondent's line number"
label variable v004     "Ultimate area unit"
label variable v005     "Women's individual sample weight (6 decimals)"
label variable v006     "Month of interview"
label variable v007     "Year of interview"
label variable v008     "Date of interview (CMC)"
label variable v009     "Respondent's month of birth"
label variable v010     "Respondent's year of birth"
label variable v011     "Date of birth (CMC)"
label variable v012     "Respondent's current age"
label variable v013     "Age in 5-year groups"
label variable v014     "Completeness of age information"
label variable v015     "Result of individual interview"
label variable v016     "Day of interview"
label variable v017     "NA - CMC start of calendar"
label variable v018     "NA - Row of month of interview"
label variable v019     "NA - Length of calendar"
label variable v019a    "NA - Number of calendar columns"
label variable v020     "Ever-married sample"
label variable v021     "Primary sampling unit"
label variable v022     "Sample strata for sampling errors"
label variable v023     "Stratification used in sample design"
label variable v024     "Region"
label variable v025     "Type of place of residence"
label variable v026     "NA - De facto place of residence"
label variable v027     "Number of visits"
label variable v028     "Interviewer identification"
label variable v029     "NA - Keyer identification"
label variable v030     "Field supervisor"
label variable v031     "NA - Field editor"
label variable v032     "NA - Office editor"
label variable v034     "NA - Line number of husband"
label variable v040     "Cluster altitude in meters"
label variable v042     "Household selected for hemoglobin"
label variable v044     "NA - Selected for Domestic Violence module"
label variable v101     "Region"
label variable v102     "Type of place of residence"
label variable v103     "NA - Childhood place of residence"
label variable v104     "NA - Years lived in place of residence"
label variable v105     "NA - Type of place of previous residence"
label variable v106     "Highest educational level"
label variable v107     "Highest year of education"
label variable v113     "Source of drinking water"
label variable v115     "Time to get to water source"
label variable v116     "Type of toilet facility"
label variable v119     "Household has: electricity"
label variable v120     "Household has: radio"
label variable v121     "Household has: television"
label variable v122     "Household has: refrigerator"
label variable v123     "Household has: bicycle"
label variable v124     "Household has: motorcycle/scooter"
label variable v125     "Household has: car/truck"
label variable v127     "Main floor material"
label variable v128     "Main wall material"
label variable v129     "Main roof material"
label variable v130     "Religion"
label variable v131     "Ethnicity"
label variable v133     "Education in single years"
label variable v134     "NA - De facto place of residence"
label variable v135     "Usual resident or visitor"
label variable v136     "Number of household members (listed)"
label variable v137     "Number of children 14 and under in household (de jure)"
label variable v138     "Number of eligible women in household (de facto)"
label variable v139     "De jure region of residence"
label variable v140     "De jure type of place of residence"
label variable v141     "NA - De jure place of residence"
label variable v149     "Educational attainment"
label variable v150     "Relationship to household head"
label variable v151     "Sex of household head"
label variable v152     "Age of household head"
label variable v153     "Household has: telephone (land-line)"
label variable awfactt  "All woman factor - total"
label variable awfactu  "All woman factor - urban/rural"
label variable awfactr  "All woman factor - regional"
label variable awfacte  "All woman factor - educational"
label variable awfactw  "All woman factor - wealth index"
label variable v155     "Literacy"
label variable v156     "NA - Ever participated in a literacy program outside of primary"
label variable v157     "NA - Frequency of reading newspaper or magazine"
label variable v158     "NA - Frequency of listening to radio"
label variable v159     "NA - Frequency of watching television"
label variable v160     "Toilet facilities shared with other households"
label variable v161     "NA - Type of cooking fuel"
label variable v166     "NA - Result of salt test for iodine"
label variable v167     "NA - Number of trips in last 12 months"
label variable v168     "NA - Away for more than one month in last 12 months"
label variable v190     "Wealth index"
label variable v191     "Wealth index factor score (5 decimals)"
label variable ml101    "Type of mosquito bed net(s) slept under last night"
label variable v201     "Total children ever born"
label variable v202     "Sons at home"
label variable v203     "Daughters at home"
label variable v204     "Sons elsewhere"
label variable v205     "Daughters elsewhere"
label variable v206     "Sons who have died"
label variable v207     "Daughters who have died"
label variable v208     "Births in last five years"
label variable v209     "Births in past year"
label variable v210     "Births in month of interview"
label variable v211     "NA - Date of first birth (CMC)"
label variable v212     "NA - Age of respondent at 1st birth"
label variable v213     "Currently pregnant"
label variable v214     "Duration of current pregnancy"
label variable v215     "NA - Time since last menstrual period"
label variable v216     "NA - Menstruated in last six weeks"
label variable v217     "NA - Knowledge of ovulatory cycle"
label variable v218     "Number of living children"
label variable v219     "Living children + current pregnancy"
label variable v220     "Living children + current pregnancy (grouped)"
label variable v221     "NA - Marriage to first birth interval (months)"
label variable v222     "Last birth to interview (months)"
label variable v223     "Completeness of current pregnancy information"
label variable v224     "Entries in birth history"
label variable v225     "NA - Current pregnancy wanted"
label variable v226     "NA - Time since last period (comp) (months)"
label variable v227     "NA - Flag for last period"
label variable v228     "NA - Ever had a terminated pregnancy"
label variable v229     "NA - Month pregnancy ended"
label variable v230     "NA - Year pregnancy ended"
label variable v231     "NA - CMC pregnancy ended"
label variable v232     "NA - Completeness of last termination information"
label variable v233     "NA - Months when pregnancy ended"
label variable v234     "NA - Other such pregnancies"
label variable v235     "NA - Index last child prior to maternity-health (calendar)"
label variable v237     "NA - Birth between last and interview"
label variable v238     "Births in last three years"
label variable v239     "NA - Pregnancies terminated before calendar beginning"
label variable v240     "NA - Month of last termination prior to calendar"
label variable v241     "NA - Year of last termination prior to calendar"
label variable v242     "NA - CMC termination ended prior to calendar"
label variable v243     "NA - Completeness of last termination date prior to calendar"
label variable bidx     "Birth column number"
label variable bord     "Birth order number"
label variable b0       "Child is twin"
label variable b1       "Month of birth"
label variable b2       "Year of birth"
label variable b3       "Date of birth (CMC)"
label variable b4       "Sex of child"
label variable b5       "Child is alive"
label variable b6       "NA - Age at death"
label variable b7       "NA - Age at death (months, imputed)"
label variable b8       "Current age of child"
label variable b9       "Child lives with whom"
label variable b10      "Completeness of information"
label variable b11      "Preceding birth interval (months)"
label variable b12      "Succeeding birth interval (months)"
label variable b13      "NA - Flag for age at death"
label variable b15      "Live birth between births"
label variable b16      "Child's line number in household"
label variable s216d    "Day of birth"
label variable midx     "Index to Birth History"
label variable m2a      "Prenatal: doctor"
label variable m2b      "Prenatal: nurse/midwife"
label variable m2c      "NA - Prenatal: CS health professional"
label variable m2d      "NA - Prenatal: CS health professional"
label variable m2e      "NA - Prenatal: CS health professional"
label variable m2f      "NA - Prenatal: CS health professional"
label variable m2g      "Prenatal: traditional birth attendant"
label variable m2h      "Prenatal: community health worker"
label variable m2i      "NA - Prenatal: CS other person"
label variable m2j      "NA - Prenatal: CS other person"
label variable m2k      "Prenatal: other"
label variable m2l      "NA - Prenatal: CS other"
label variable m2m      "NA - Prenatal: CS other"
label variable m2n      "Prenatal: no one"
label variable m14      "Number of antenatal visits during pregnancy"
label variable m49a     "During pregnancy took: SP/fansidar for malaria"
label variable h22      "Had fever in last two weeks"
label variable h31      "NA - Had cough in last two weeks"
label variable h31b     "NA - Short, rapid breaths"
label variable h31c     "NA - Problem in the chest or blocked or running nose"
label variable h31d     "NA - Had fever/cough in last 2 weeks: amount offered to drink"
label variable h31e     "NA - Had fever/cough in last 2 weeks: amount offered to eat"
label variable h32a     "Fever/cough: government hospital"
label variable h32b     "Fever/cough: government health center"
label variable h32c     "Fever/cough: government dispensary"
label variable h32d     "Fever/cough: other public"
label variable h32e     "NA - Fever/cough: CS public sector"
label variable h32f     "NA - Fever/cough: CS public sector"
label variable h32g     "NA - Fever/cough: CS public sector"
label variable h32h     "NA - Fever/cough: CS public sector"
label variable h32i     "NA - Fever/cough: CS public sector"
label variable h32j     "Fever/cough: mission hospital / clinic"
label variable h32k     "Fever/cough: pharmacy"
label variable h32l     "Fever/cough: private hospital / clinic"
label variable h32m     "Fever/cough: other private"
label variable h32n     "Fever/cough: mobile clinic"
label variable h32o     "Fever/cough: community health worker"
label variable h32p     "NA - Fever/cough: CS private medical"
label variable h32q     "NA - Fever/cough: CS private medical"
label variable h32r     "NA - Fever/cough: CS private medical"
label variable h32s     "Fever/cough: shop"
label variable h32t     "Fever/cough: traditional healer"
label variable h32u     "Fever/cough: relative/friend"
label variable h32v     "NA - Fever/cough: CS other sector"
label variable h32w     "NA - Fever/cough: CS other sector"
label variable h32x     "Fever/cough: other"
label variable h32y     "Fever/cough: no treatment"
label variable h32z     "Fever/cough: medical treatment"
label variable h37a     "NA - SP/Fansidar taken for fever/cough"
label variable h37b     "NA - Chloroquine taken for fever/cough"
label variable h37c     "NA - Amodiaquine taken for fever/cough"
label variable h37d     "NA - Quinine taken for fever/cough"
label variable h37e     "NA - Combination with artemisinin taken for fever/cough"
label variable h37f     "NA - CS antimalarial taken for fever/cough"
label variable h37g     "NA - CS antimalarial taken for fever/cough"
label variable h37h     "NA - Other antimalarial taken for fever/cough"
label variable h37i     "NA - Antibiotic pill/syrup taken for fever/cough"
label variable h37j     "NA - Antibiotic injection taken for fever/cough"
label variable h37k     "NA - Aspirin taken for fever/cough"
label variable h37l     "NA - Acetaminophen/paracetamol/panadol taken for fever/cough"
label variable h37m     "NA - Ibuprofen taken for fever/cough"
label variable h37n     "NA - CS other taken for fever/cough"
label variable h37o     "NA - CS other for fever/cough"
label variable h37p     "NA - CS other for fever/cough"
label variable h37x     "NA - Other taken for fever/cough"
label variable h37y     "NA - Nothing taken and didn't seek treatment for fever/cough"
label variable h37z     "NA - Don't know if or what was taken for fever/cough"
label variable h46a     "Place first sought treatment for fever"
label variable h46b     "NA - Days after fever sought advice or treatment"
label variable h47      "Blood taken from child's finger/heel for testing"
label variable idxml    "Index to Birth History"
label variable ml0      "Type of mosquito bed net(s) child slept under last night"
label variable ml1      "Number of times took fansidar during pregnancy"
label variable ml2      "Source of antimalarial during pregnancy"
label variable ml11     "NA - Child has fever/cough now"
label variable ml12     "NA - Child has had convulsions in last 2 weeks"
label variable ml13a    "Fansidar taken for fever/cough"
label variable ml13b    "Chloroquine taken for fever/cough"
label variable ml13c    "Amodiaquine taken for fever/cough"
label variable ml13d    "Quinine ( pills ) taken for fever/cough"
label variable ml13e    "Combination with artemisinin taken for fever/cough"
label variable ml13f    "Quinine ( injection/IV )taken for fever/cough"
label variable ml13g    "Artesunate ( rectal ) taken for fever/cough"
label variable ml13h    "Other antimalarial taken for fever/cough"
label variable ml13i    "Antibiotic pill/syrup taken for fever/cough"
label variable ml13j    "Antibiotic injection taken for fever/cough"
label variable ml13k    "Aspirin taken for fever/cough"
label variable ml13l    "Acetaminophen/paracetamol/panadol taken for fever/cough"
label variable ml13m    "Ibuprofen taken for fever/cough"
label variable ml13n    "Artesunate ( injection ) taken for fever/cough"
label variable ml13o    "NA - CS other taken for fever/cough"
label variable ml13p    "NA - CS other taken for fever/cough"
label variable ml13x    "Other taken for fever/cough"
label variable ml13y    "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13z    "Don't know if or what was taken for fever/cough"
label variable ml14a    "NA - Injection given for fever/convulsion***"
label variable ml14b    "NA - Suppository given for fever/convulsion***"
label variable ml14y    "NA - No suppository or injection given for fever/convulsion***"
label variable ml14z    "NA - Don't know if suppository or injection given for fever/convulsion***"
label variable ml15a    "Timing of start of fansidar"
label variable ml15b    "NA - Number of days child took fansidar"
label variable ml15c    "NA - First source for fansidar"
label variable ml16a    "Timing of start of chloroquine"
label variable ml16b    "NA - Number of days child took chloroquine"
label variable ml16c    "NA - First source for chloroquine"
label variable ml17a    "Timing of start of amodiaquine"
label variable ml17b    "NA - Number of days child took amodiaquine"
label variable ml17c    "NA - First source for amodiaquine"
label variable ml18a    "Timing of start of quinine"
label variable ml18b    "NA - Number of days child took quinine"
label variable ml18c    "NA - First source for quinine"
label variable ml19a    "NA - For fever/convulsion: consulted traditional healer***"
label variable ml19b    "NA - For fever/convulsion: gave tepid sponging***"
label variable ml19c    "NA - For fever/convulsion: gave herbs***"
label variable ml19d    "NA - For fever/convulsion: CS***"
label variable ml19e    "NA - For fever/convulsion: CS***"
label variable ml19f    "NA - For fever/convulsion: CS***"
label variable ml19x    "NA - For fever/convulsion: other***"
label variable ml19y    "NA - For fever/convulsion: gave/did nothing***"
label variable ml19z    "NA - For fever/convulsion: don't know if something else was done***"
label variable ml20a    "Timing of start of DHAP"
label variable ml20b    "NA - Number of days child took combination with artemisinin"
label variable ml20c    "NA - First source for combination with artemisinin"
label variable ml21a    "Timing of start AL use"
label variable ml21b    "NA - Number of days child took CS antimalarial"
label variable ml21c    "NA - First source for CS antimalarial"
label variable ml22a    "Timing of start of Artesunate/Amodiaquine"
label variable ml22b    "NA - Number of days child took CS antimalarial"
label variable ml22c    "NA - First source for CS antimalarial"
label variable ml23a    "NA - Timing of start of other anti-malarial use"
label variable ml23b    "NA - Number of days child took other anti-malarial"
label variable ml23c    "NA - First source for other anti-malarial"
label variable ml24c    "NA - First source for antibiotic pill/syrup"
label variable s411a    "AL taken for fever/cough ( part of ML13E )"
label variable s411b    "Artesunate/Amodiaquine taken for fever/cough ( part of ML13E )"
label variable s411c    "DHAP taken for fever/cough ( part of ML13E )"
label variable ml25a    "Timing of start of artesunate"
label variable s412b    "Logo for AL/Artesunate-Amodiaquine"
label variable scounty  "County"
label variable szone    "Malaria endemicity"
label variable slang    "Language of questionnaire"
label variable slangint "Language of interview"
label variable stransl  "Translator used"
label variable s105     "Highest educational level"
label variable s106     "Highest grade/form/year at that level"
label variable s111     "Have seen or heard any messages about malaria"
label variable s112a    "Have seen or heard messages on the radio"
label variable s112b    "Have seen or heard messages on the television"
label variable s112c    "Have seen or heard messages on a poster or billboard"
label variable s112d    "Have seen or heard messages from a community health worker"
label variable s112e    "Have seen or heard messages at a community event"
label variable s112f    "Have seen or heard messages anywhere else"
label variable s427b    "Importance of seeking antimalarial treatment"
label variable s427c    "Affordability of fever treatment"
label variable s427d    "Recommended treatment for malaria"
label variable s427e    "Seen or heard any information about ACT or AL"
label variable s427f1   "Where heard about ACT or AL: television"
label variable s427f2   "Where heard about ACT or AL: radio"
label variable s427f3   "Where heard about ACT or AL: newspaper"
label variable s427f4   "Where heard about ACT or AL: baraza"
label variable s427f5   "Where heard about ACT or AL: relative/friend"
label variable s427f6   "Where heard about ACT or AL: community leader/elder"
label variable s427f7   "Where heard about ACT or AL: community health worker"
label variable s427f8   "Where heard about ACT or AL: road show"
label variable s427f9   "Where heard about ACT or AL: other"
label variable sv112e   "Computer"
label variable sv112g   "Solar panel"
label variable sv112h   "Table"
label variable sv112i   "Chair"
label variable sv112j   "Sofa"
label variable sv112k   "Bed"
label variable sv112l   "Cupboard"
label variable sv112m   "Clock"
label variable sv112n   "Microwave oven"
label variable sv112o   "DVD player"
label variable sv112p   "CD player"

#delimit ;
label define V013    
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define V014    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define V015    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partially completed"
     6 "Respondent incapacitated"
     7 "Other"
;
label define V018    
     0 "No calendar"
;
label define V019    
     0 "No calendar"
;
label define V019A   
     0 "No calendar"
;
label define V020    
     0 "All woman sample"
     1 "Ever married sample"
;
label define V024    
     1 "Coast"
     2 "North Eastern"
     3 "Eastern"
     4 "Central"
     5 "Rift Valley"
     7 "Western"
     8 "Nyanza"
     9 "Nairobi"
;
label define V025    
     1 "Urban"
     2 "Rural"
;
label define V026    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V027    
     9 "Missing"
;
label define V028    
   999 "Missing"
;
label define V029    
    99 "Missing"
;
label define V030    
   999 "Missing"
;
label define V031    
   999 "Missing"
;
label define V032    
    99 "Missing"
;
label define V034    
     0 "Husband not in household"
;
label define V040    
  9999 "Missing"
;
label define V042    
     0 "Not selected"
     1 "Selected"
;
label define V044    
     0 "Woman not selected"
     1 "Woman selected and interviewed"
     2 "Woman selected, but privacy not possible"
     3 "Woman selected, but not interviewed"
;
label define V101    
     1 "Coast"
     2 "North Eastern"
     3 "Eastern"
     4 "Central"
     5 "Rift Valley"
     7 "Western"
     8 "Nyanza"
     9 "Nairobi"
;
label define V102    
     1 "Urban"
     2 "Rural"
;
label define V103    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define V104    
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define V105    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define V106    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define V107    
     0 "No years completed at level V106"
;
label define V113    
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    14 "Public to neighborhood"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
    97 "Not a dejure resident"
;
label define V115    
   996 "On premises"
   997 "Not a dejure resident"
   998 "Don't know"
;
label define V116    
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
    97 "Not a dejure resident"
;
label define V119    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V120    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V121    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V122    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V123    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V124    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V125    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V127    
    11 "Earth/sand"
    12 "Dung"
    21 "Wood planks"
    22 "Palm/bamboo"
    31 "Parquet or polished wood"
    32 "Vinyl/PVC or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
    97 "Not a dejure resident"
;
label define V128    
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Dung/mud/sod"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    27 "Iron sheets"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
    97 "Not a dejure resident"
;
label define V129    
    11 "No walls"
    12 "Thatch/grass/makuti"
    13 "Dung/mud/sod"
    21 "Iron sheets"
    22 "Tin cans"
    31 "Asbestos sheet"
    32 "Concrete"
    33 "Tiles"
    96 "Other"
    97 "Not a dejure resident"
;
label define V130    
     1 "Roman Catholic"
     2 "Protestant/other Christian"
     3 "Muslim"
     4 "No religion"
    96 "Other"
;
label define V131    
     1 "Embu"
     2 "Kalenjin"
     3 "Kamba"
     4 "Kikuyu"
     5 "Kisii"
     6 "Luhya"
     7 "Luo"
     8 "Maasai"
     9 "Meru"
    10 "Mijikenda/Swahili"
    11 "Somali"
    12 "Taita/Taveta"
    13 "Borana"
    14 "Maragoli"
    15 "Pokot"
    16 "Turkana"
    96 "Other"
;
label define V133    
    97 "Inconsistent"
;
label define V134    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V135    
     1 "Usual resident"
     2 "Visitor"
;
label define V139    
     0 "Abroad"
     1 "Coast"
     2 "North Eastern"
     3 "Eastern"
     4 "Central"
     5 "Rift Valley"
     7 "Western"
     8 "Nyanza"
     9 "Nairobi"
    97 "Not dejure resident"
;
label define V140    
     0 "Abroad"
     1 "Urban"
     2 "Rural"
     7 "Not a dejure resident"
;
label define V141    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     7 "Not a dejure resident"
;
label define V149    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     6 "to be added"
;
label define V150    
     1 "Head"
     2 "Wife"
     3 "Daughter"
     4 "Daughter-in-law"
     5 "Granddaughter"
     6 "Mother"
     7 "Mother-in-law"
     8 "Sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "Don't know"
;
label define V151    
     1 "Male"
     2 "Female"
;
label define V152    
    97 "97+"
    98 "Don't know"
;
label define V153    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V155    
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define V156    
     0 "No"
     1 "Yes"
;
label define V157    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V158    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V159    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V160    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V161    
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in house"
    96 "Other"
    97 "Not a dejure resident"
;
label define V166    
     0 "0 ppm (no iodine)"
     7 "7 ppm"
    15 "15 ppm"
    30 "30 ppm"
   994 "Salt not tested"
   995 "No salt"
   997 "Not a dejure resident"
;
label define V167    
     0 "None"
    90 "90+"
;
label define V168    
     0 "No"
     1 "Yes"
;
label define V190    
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define ML101   
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define V208    
     0 "No births"
;
label define V209    
     0 "No births"
;
label define V213    
     0 "No or unsure"
     1 "Yes"
;
label define V215    
   100 "Day of interview"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
   994 "In menopause/had hysterectomy"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
;
label define V216    
     0 "No"
     1 "Yes"
;
label define V217    
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define V220    
     6 "6+"
;
label define V221    
   996 "Negative interval"
;
label define V223    
     7 "Month - exact date"
     8 "None - date placed"
;
label define V225    
     1 "Then"
     2 "Later"
     3 "Not at all"
;
label define V226    
   994 "In menopause"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
;
label define V227    
     0 "No flag"
     1 "N > interval since birth"
     2 "N + amen. > interval"
     3 "N, but period not returned"
     4 "95, but no birth"
     5 "95, but period returned"
     6 "96, but period returned"
     7 "N, last period during pregnancy"
     8 "96, had children"
     9 "N, period before last birth"
;
label define V228    
     0 "No"
     1 "Yes"
;
label define V229    
    97 "Inconsistent"
    98 "Don't know"
;
label define V230    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V231    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V232    
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     7 "Month"
     8 "None"
;
label define V233    
    97 "Inconsistent"
    98 "Don't know"
;
label define V234    
     0 "No"
     1 "Yes"
;
label define V235    
     0 "No prior child"
;
label define V237    
     0 "No"
     1 "Yes"
;
label define V239    
     0 "No"
     1 "Yes"
;
label define V240    
    97 "Inconsistent"
    98 "Don't know"
;
label define V241    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V242    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V243    
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     7 "Month"
     8 "None"
;
label define B0      
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
;
label define B4      
     1 "Male"
     2 "Female"
;
label define B5      
     0 "No"
     1 "Yes"
;
label define B6      
   100 "Died on day of birth"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
   997 "Inconsistent"
   998 "Don't know"
;
label define B9      
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
;
label define B10     
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define B13     
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
;
label define B15     
     0 "No"
     1 "Yes"
;
label define B16     
     0 "Not listed in household"
;
label define S216D   
    98 "Don't know"
;
label define M2A     
     0 "No"
     1 "Yes"
;
label define M2B     
     0 "No"
     1 "Yes"
;
label define M2C     
     0 "No"
     1 "Yes"
;
label define M2D     
     0 "No"
     1 "Yes"
;
label define M2E     
     0 "No"
     1 "Yes"
;
label define M2F     
     0 "No"
     1 "Yes"
;
label define M2G     
     0 "No"
     1 "Yes"
;
label define M2H     
     0 "No"
     1 "Yes"
;
label define M2I     
     0 "No"
     1 "Yes"
;
label define M2J     
     0 "No"
     1 "Yes"
;
label define M2K     
     0 "No"
     1 "Yes"
;
label define M2L     
     0 "No"
     1 "Yes"
;
label define M2M     
     0 "No"
     1 "Yes"
;
label define M2N     
     0 "No: some care"
     1 "Yes: no care"
;
label define M14     
     0 "No antenatal visits"
    98 "Don't know"
;
label define M49A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H22     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H31     
     0 "No"
     1 "Yes, last 24 hours"
     2 "Yes, last two weeks"
     8 "Don't know"
;
label define H31B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H31C    
     1 "Chest only"
     2 "Nose only"
     3 "Both"
     6 "Other"
     8 "Don't know"
;
label define H31D    
     0 "Nothing to drink"
     2 "Much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define H31E    
     0 "Stopped food"
     1 "Never gave food"
     2 "Much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define H32A    
     0 "No"
     1 "Yes"
;
label define H32B    
     0 "No"
     1 "Yes"
;
label define H32C    
     0 "No"
     1 "Yes"
;
label define H32D    
     0 "No"
     1 "Yes"
;
label define H32E    
     0 "No"
     1 "Yes"
;
label define H32F    
     0 "No"
     1 "Yes"
;
label define H32G    
     0 "No"
     1 "Yes"
;
label define H32H    
     0 "No"
     1 "Yes"
;
label define H32I    
     0 "No"
     1 "Yes"
;
label define H32J    
     0 "No"
     1 "Yes"
;
label define H32K    
     0 "No"
     1 "Yes"
;
label define H32L    
     0 "No"
     1 "Yes"
;
label define H32M    
     0 "No"
     1 "Yes"
;
label define H32N    
     0 "No"
     1 "Yes"
;
label define H32O    
     0 "No"
     1 "Yes"
;
label define H32P    
     0 "No"
     1 "Yes"
;
label define H32Q    
     0 "No"
     1 "Yes"
;
label define H32R    
     0 "No"
     1 "Yes"
;
label define H32S    
     0 "No"
     1 "Yes"
;
label define H32T    
     0 "No"
     1 "Yes"
;
label define H32U    
     0 "No"
     1 "Yes"
;
label define H32V    
     0 "No"
     1 "Yes"
;
label define H32W    
     0 "No"
     1 "Yes"
;
label define H32X    
     0 "No"
     1 "Yes"
;
label define H32Y    
     0 "No: received treatment"
     1 "Yes: no treatment"
;
label define H32Z    
     0 "No"
     1 "Yes"
;
label define H37A    
     0 "No"
     1 "Yes"
;
label define H37B    
     0 "No"
     1 "Yes"
;
label define H37C    
     0 "No"
     1 "Yes"
;
label define H37D    
     0 "No"
     1 "Yes"
;
label define H37E    
     0 "No"
     1 "Yes"
;
label define H37F    
     0 "No"
     1 "Yes"
;
label define H37G    
     0 "No"
     1 "Yes"
;
label define H37H    
     0 "No"
     1 "Yes"
;
label define H37I    
     0 "No"
     1 "Yes"
;
label define H37J    
     0 "No"
     1 "Yes"
;
label define H37K    
     0 "No"
     1 "Yes"
;
label define H37L    
     0 "No"
     1 "Yes"
;
label define H37M    
     0 "No"
     1 "Yes"
;
label define H37N    
     0 "No"
     1 "Yes"
;
label define H37O    
     0 "No"
     1 "Yes"
;
label define H37P    
     0 "No"
     1 "Yes"
;
label define H37X    
     0 "No"
     1 "Yes"
;
label define H37Y    
     0 "No"
     1 "Yes, nothing taken"
;
label define H37Z    
     0 "No"
     1 "Yes, don't know"
;
label define H46A    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Government dispensary"
    14 "Other public"
    20 "PRIVATE SECTOR"
    21 "Mission hospital, clinic"
    22 "Private hospital, clinic"
    23 "Pharmacy"
    24 "Other private"
    25 "Mobile clinic"
    26 "Community health worker"
    30 "OTHER"
    31 "Shop"
    32 "Traditional healer"
    33 "Relative/friend"
    96 "Other"
;
label define H46B    
     0 "Same day"
    98 "Don't know"
;
label define H47     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define ML0     
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define ML1     
    98 "Don't know"
;
label define ML2     
     1 "Antenatal visit"
     2 "Another facility visit"
     6 "Other source"
;
label define ML11    
     0 "No"
     1 "Yes, fever only"
     2 "Yes, cough only"
     3 "Both fever and cough"
     8 "Don't know"
;
label define ML12    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define ML13A   
     0 "No"
     1 "Yes"
;
label define ML13B   
     0 "No"
     1 "Yes"
;
label define ML13C   
     0 "No"
     1 "Yes"
;
label define ML13D   
     0 "No"
     1 "Yes"
;
label define ML13E   
     0 "No"
     1 "Yes"
;
label define ML13F   
     0 "No"
     1 "Yes"
;
label define ML13G   
     0 "No"
     1 "Yes"
;
label define ML13H   
     0 "No"
     1 "Yes"
;
label define ML13I   
     0 "No"
     1 "Yes"
;
label define ML13J   
     0 "No"
     1 "Yes"
;
label define ML13K   
     0 "No"
     1 "Yes"
;
label define ML13L   
     0 "No"
     1 "Yes"
;
label define ML13M   
     0 "No"
     1 "Yes"
;
label define ML13N   
     0 "No"
     1 "Yes"
;
label define ML13O   
     0 "No"
     1 "Yes"
;
label define ML13P   
     0 "No"
     1 "Yes"
;
label define ML13X   
     0 "No"
     1 "Yes"
;
label define ML13Y   
     0 "No"
     1 "Yes, nothing taken"
;
label define ML13Z   
     0 "No"
     1 "Yes, don't know"
;
label define ML14A   
     0 "No"
     1 "Yes"
;
label define ML14B   
     0 "No"
     1 "Yes"
;
label define ML14Y   
     0 "No"
     1 "Yes"
;
label define ML14Z   
     0 "No"
     1 "Yes"
;
label define ML15A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML15B   
     7 "7+ days"
     8 "Don't know"
;
label define ML15C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML16A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML16B   
     7 "7+ days"
     8 "Don't know"
;
label define ML16C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML17A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML17B   
     7 "7+ days"
     8 "Don't know"
;
label define ML17C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML18A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML18B   
     7 "7+ days"
     8 "Don't know"
;
label define ML18C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML19A   
     0 "No"
     1 "Yes"
;
label define ML19B   
     0 "No"
     1 "Yes"
;
label define ML19C   
     0 "No"
     1 "Yes"
;
label define ML19D   
     0 "No"
     1 "Yes"
;
label define ML19E   
     0 "No"
     1 "Yes"
;
label define ML19F   
     0 "No"
     1 "Yes"
;
label define ML19X   
     0 "No"
     1 "Yes"
;
label define ML19Y   
     0 "No"
     1 "Yes"
;
label define ML19Z   
     0 "No"
     1 "Yes"
;
label define ML20A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML20B   
     7 "7+ days"
     8 "Don't know"
;
label define ML20C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML21A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML21B   
     7 "7+ days"
     8 "Don't know"
;
label define ML21C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML22A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML22B   
     7 "7+ days"
     8 "Don't know"
;
label define ML22C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML23A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML23B   
     7 "7+ days"
     8 "Don't know"
;
label define ML23C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML24C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define S411A   
     0 "No"
     1 "Yes"
;
label define S411B   
     0 "No"
     1 "Yes"
;
label define S411C   
     0 "No"
     1 "Yes"
;
label define ML25A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define S412B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SCOUNTY 
   101 "NAIROBI"
   201 "NYANDARUA"
   202 "NYERI"
   203 "KIRINYAGA"
   204 "MURANGA"
   205 "KIAMBU"
   301 "MOMBASA"
   302 "KWALE"
   303 "KILIFI"
   304 "TANA RIVER"
   305 "LAMU"
   306 "TAITA TAVETA"
   401 "MARSABIT"
   402 "ISIOLO"
   403 "MERU"
   404 "THARAKA"
   405 "EMBU"
   406 "KITUI"
   407 "MACHAKOS"
   408 "MAKUENI"
   501 "GARISSA"
   502 "WAJIR"
   503 "MANDERA"
   601 "SIAYA"
   602 "KISUMU"
   603 "MIGORI"
   604 "HOMA BAY"
   605 "KISII"
   606 "NYAMIRA"
   701 "TURKANA"
   702 "WEST POKOT"
   703 "SAMBURU"
   704 "TRANS-NZOIA"
   705 "BARINGO"
   706 "UASIN GISHU"
   707 "ELGEYO MARAKWET"
   708 "NANDI"
   709 "LAIKIPIA"
   710 "NAKURU"
   711 "NAROK"
   712 "KAJIADO"
   713 "KERICHO"
   714 "BOMET"
   801 "KAKAMEGA"
   802 "VIHIGA"
   803 "BUNGOMA"
   804 "BUSIA"
;
label define SZONE   
     1 "Highland epidemic"
     2 "Lake endemic"
     3 "Coast endemic"
     4 "Semi-arid, seasonal"
     5 "Low risk"
;
label define SLANG   
     1 "English"
     2 "Kiswahili"
;
label define SLANGINT
     1 "English"
     2 "Kiswahili"
     3 "Borana"
     4 "Embu"
     5 "Kalenjin"
     6 "Kamba"
     7 "Kikuyu"
     8 "Kisii"
     9 "Luhya"
    10 "Maragoli"
    11 "Luo"
    12 "Maasai"
    13 "Meru"
    14 "Mijikenda"
    15 "Pokot"
    16 "Somali"
    17 "Turkana"
    18 "Other"
;
label define STRANSL 
     0 "No"
     1 "Yes"
;
label define S105    
     1 "Primary"
     2 "Post-primary/vocational"
     3 "Secondary / 'A' level"
     4 "College ( middle level )"
     5 "University"
;
label define S111    
     0 "No"
     1 "Yes"
;
label define S112A   
     0 "No"
     1 "Yes"
;
label define S112B   
     0 "No"
     1 "Yes"
;
label define S112C   
     0 "No"
     1 "Yes"
;
label define S112D   
     0 "No"
     1 "Yes"
;
label define S112E   
     0 "No"
     1 "Yes"
;
label define S112F   
     0 "No"
     1 "Yes"
;
label define S427B   
     1 "Extremely important"
     2 "Very important"
     3 "A little important"
     4 "Not at all important"
;
label define S427C   
     1 "Very affordable"
     2 "Affordable"
     3 "Unaffordable"
     4 "Very unaffordable"
;
label define S427D   
     1 "ACT/AL"
     2 "SP/Fansidar"
     3 "Chloroquine"
     4 "Amodiaquine"
     6 "Other"
     8 "Don't know"
;
label define S427E   
     0 "No"
     1 "Yes"
;
label define S427F1  
     0 "No"
     1 "Yes"
;
label define S427F2  
     0 "No"
     1 "Yes"
;
label define S427F3  
     0 "No"
     1 "Yes"
;
label define S427F4  
     0 "No"
     1 "Yes"
;
label define S427F5  
     0 "No"
     1 "Yes"
;
label define S427F6  
     0 "No"
     1 "Yes"
;
label define S427F7  
     0 "No"
     1 "Yes"
;
label define S427F8  
     0 "No"
     1 "Yes"
;
label define S427F9  
     0 "No"
     1 "Yes"
;
label define SV112E  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112G  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112H  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112I  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112J  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112K  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112L  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112M  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112N  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112O  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112P  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;

#delimit cr
label values v013     V013    
label values v014     V014    
label values v015     V015    
label values v018     V018    
label values v019     V019    
label values v019a    V019A   
label values v020     V020    
label values v024     V024    
label values v025     V025    
label values v026     V026    
label values v034     V034    
label values v042     V042    
label values v044     V044    
label values v101     V101    
label values v102     V102    
label values v103     V103    
label values v104     V104    
label values v105     V105    
label values v106     V106    
label values v107     V107    
label values v113     V113    
label values v115     V115    
label values v116     V116    
label values v119     V119    
label values v120     V120    
label values v121     V121    
label values v122     V122    
label values v123     V123    
label values v124     V124    
label values v125     V125    
label values v127     V127    
label values v128     V128    
label values v129     V129    
label values v130     V130    
label values v131     V131    
label values v133     V133    
label values v134     V134    
label values v135     V135    
label values v139     V139    
label values v140     V140    
label values v141     V141    
label values v149     V149    
label values v150     V150    
label values v151     V151    
label values v152     V152    
label values v153     V153    
label values v155     V155    
label values v156     V156    
label values v157     V157    
label values v158     V158    
label values v159     V159    
label values v160     V160    
label values v161     V161    
label values v166     V166    
label values v167     V167    
label values v168     V168    
label values v190     V190    
label values ml101    ML101   
label values v208     V208    
label values v209     V209    
label values v213     V213    
label values v215     V215    
label values v216     V216    
label values v217     V217    
label values v220     V220    
label values v221     V221    
label values v223     V223    
label values v225     V225    
label values v226     V226    
label values v227     V227    
label values v228     V228    
label values v229     V229    
label values v230     V230    
label values v231     V231    
label values v232     V232    
label values v233     V233    
label values v234     V234    
label values v235     V235    
label values v237     V237    
label values v239     V239    
label values v240     V240    
label values v241     V241    
label values v242     V242    
label values v243     V243    
label values b0       B0      
label values b4       B4      
label values b5       B5      
label values b6       B6      
label values b9       B9      
label values b10      B10     
label values b13      B13     
label values b15      B15     
label values b16      B16     
label values s216d    S216D   
label values m2a      M2A     
label values m2b      M2B     
label values m2c      M2C     
label values m2d      M2D     
label values m2e      M2E     
label values m2f      M2F     
label values m2g      M2G     
label values m2h      M2H     
label values m2i      M2I     
label values m2j      M2J     
label values m2k      M2K     
label values m2l      M2L     
label values m2m      M2M     
label values m2n      M2N     
label values m14      M14     
label values m49a     M49A    
label values h22      H22     
label values h31      H31     
label values h31b     H31B    
label values h31c     H31C    
label values h31d     H31D    
label values h31e     H31E    
label values h32a     H32A    
label values h32b     H32B    
label values h32c     H32C    
label values h32d     H32D    
label values h32e     H32E    
label values h32f     H32F    
label values h32g     H32G    
label values h32h     H32H    
label values h32i     H32I    
label values h32j     H32J    
label values h32k     H32K    
label values h32l     H32L    
label values h32m     H32M    
label values h32n     H32N    
label values h32o     H32O    
label values h32p     H32P    
label values h32q     H32Q    
label values h32r     H32R    
label values h32s     H32S    
label values h32t     H32T    
label values h32u     H32U    
label values h32v     H32V    
label values h32w     H32W    
label values h32x     H32X    
label values h32y     H32Y    
label values h32z     H32Z    
label values h37a     H37A    
label values h37b     H37B    
label values h37c     H37C    
label values h37d     H37D    
label values h37e     H37E    
label values h37f     H37F    
label values h37g     H37G    
label values h37h     H37H    
label values h37i     H37I    
label values h37j     H37J    
label values h37k     H37K    
label values h37l     H37L    
label values h37m     H37M    
label values h37n     H37N    
label values h37o     H37O    
label values h37p     H37P    
label values h37x     H37X    
label values h37y     H37Y    
label values h37z     H37Z    
label values h46a     H46A    
label values h46b     H46B    
label values h47      H47     
label values ml0      ML0     
label values ml1      ML1     
label values ml2      ML2     
label values ml11     ML11    
label values ml12     ML12    
label values ml13a    ML13A   
label values ml13b    ML13B   
label values ml13c    ML13C   
label values ml13d    ML13D   
label values ml13e    ML13E   
label values ml13f    ML13F   
label values ml13g    ML13G   
label values ml13h    ML13H   
label values ml13i    ML13I   
label values ml13j    ML13J   
label values ml13k    ML13K   
label values ml13l    ML13L   
label values ml13m    ML13M   
label values ml13n    ML13N   
label values ml13o    ML13O   
label values ml13p    ML13P   
label values ml13x    ML13X   
label values ml13y    ML13Y   
label values ml13z    ML13Z   
label values ml14a    ML14A   
label values ml14b    ML14B   
label values ml14y    ML14Y   
label values ml14z    ML14Z   
label values ml15a    ML15A   
label values ml15b    ML15B   
label values ml15c    ML15C   
label values ml16a    ML16A   
label values ml16b    ML16B   
label values ml16c    ML16C   
label values ml17a    ML17A   
label values ml17b    ML17B   
label values ml17c    ML17C   
label values ml18a    ML18A   
label values ml18b    ML18B   
label values ml18c    ML18C   
label values ml19a    ML19A   
label values ml19b    ML19B   
label values ml19c    ML19C   
label values ml19d    ML19D   
label values ml19e    ML19E   
label values ml19f    ML19F   
label values ml19x    ML19X   
label values ml19y    ML19Y   
label values ml19z    ML19Z   
label values ml20a    ML20A   
label values ml20b    ML20B   
label values ml20c    ML20C   
label values ml21a    ML21A   
label values ml21b    ML21B   
label values ml21c    ML21C   
label values ml22a    ML22A   
label values ml22b    ML22B   
label values ml22c    ML22C   
label values ml23a    ML23A   
label values ml23b    ML23B   
label values ml23c    ML23C   
label values ml24c    ML24C   
label values s411a    S411A   
label values s411b    S411B   
label values s411c    S411C   
label values ml25a    ML25A   
label values s412b    S412B   
label values scounty  SCOUNTY 
label values szone    SZONE   
label values slang    SLANG   
label values slangint SLANGINT
label values stransl  STRANSL 
label values s105     S105    
label values s111     S111    
label values s112a    S112A   
label values s112b    S112B   
label values s112c    S112C   
label values s112d    S112D   
label values s112e    S112E   
label values s112f    S112F   
label values s427b    S427B   
label values s427c    S427C   
label values s427d    S427D   
label values s427e    S427E   
label values s427f1   S427F1  
label values s427f2   S427F2  
label values s427f3   S427F3  
label values s427f4   S427F4  
label values s427f5   S427F5  
label values s427f6   S427F6  
label values s427f7   S427F7  
label values s427f8   S427F8  
label values s427f9   S427F9  
label values sv112e   SV112E  
label values sv112g   SV112G  
label values sv112h   SV112H  
label values sv112i   SV112I  
label values sv112j   SV112J  
label values sv112k   SV112K  
label values sv112l   SV112L  
label values sv112m   SV112M  
label values sv112n   SV112N  
label values sv112o   SV112O  
label values sv112p   SV112P  
