infix using "C:\COUNTRIES\GH7B\GHPR7BFL.dct"

label variable hhid     "Case Identification"
label variable hvidx    "Line number"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv008a   "Date of interview Century Day Code (CDC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv030    "Field supervisor"
label variable hv035    "Number of eligible children for height and weight"
label variable hv040    "Cluster altitude in meters"
label variable hv042    "Household selected for hemoglobin"
label variable hv045a   "Language of questionnaire"
label variable hv045b   "Language of interview"
label variable hv045c   "Native language of respondent"
label variable hv046    "Translator used"
label variable hv801    "Time interview started (hhmm - 24 hour clock)"
label variable hv802    "Time interview ended (hhmm - 24 hour clock)"
label variable hv803    "Length of interview in minutes"
label variable hv804    "Number of visits for biomarker"
label variable hv807d   "Day of biomarker visit"
label variable hv807m   "Month of biomarker visit"
label variable hv807y   "Year of biomarker visit"
label variable hv807c   "Date of biomarker (CMC)"
label variable hv807a   "Date of biomarker Century Day Code (CDC)"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "Has mosquito bed net for sleeping"
label variable hv228    "Children under 5 slept under mosquito bed net last night"
label variable hv235    "Location of source for water"
label variable hv238    "Number of households sharing toilet"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "Has wrist watch"
label variable hv243c   "Has animal-drawn cart"
label variable hv243d   "Has boat with a motor"
label variable hv243e   "Has a computer or tablet"
label variable hv244    "Owns land usable for agriculture"
label variable hv245    "Hectares of agricultural land (1 decimal)"
label variable hv246    "Owns livestock, herds or farm animals"
label variable hv246a   "Owns cattle"
label variable hv246b   "Owns cows/ bulls"
label variable hv246c   "Owns horses/ donkeys/ mules"
label variable hv246d   "Owns goats"
label variable hv246e   "Owns sheep"
label variable hv246f   "Owns chickens/poultry"
label variable hv246g   "Owns pigs"
label variable hv246h   "Owns rabbits"
label variable hv246i   "Owns grasscutter"
label variable hv246j   "NA - Owns CS"
label variable hv246k   "NA - Owns CS"
label variable hv247    "Has bank account"
label variable hv253    "Has dwelling been sprayed against mosquitoes in last 12 months"
label variable hv253a   "Dwelling sprayed by: government worker/program"
label variable hv253b   "Dwelling sprayed by: private company"
label variable hv253c   "Dwelling sprayed by: NGO"
label variable hv253d   "NA - Dwelling sprayed by: CS"
label variable hv253e   "NA - Dwelling sprayed by: CS"
label variable hv253f   "NA - Dwelling sprayed by: CS"
label variable hv253g   "NA - Dwelling sprayed by: CS"
label variable hv253h   "NA - Dwelling sprayed by: CS"
label variable hv253x   "Dwelling sprayed by: other"
label variable hv253z   "Dwelling sprayed by: don't know"
label variable hv270    "Wealth index combined"
label variable hv271    "Wealth index factor score combined (5 decimals)"
label variable hv270a   "Wealth index for urban/rural"
label variable hv271a   "Wealth index factor score for urban/rural (5 decimals)"
label variable hml1     "Number of mosquito bed nets"
label variable hml1a    "Number of mosquito bed nets with specific information"
label variable hml2     "Number of children under mosquito bed net previous night"
label variable shdistrict "District"
label variable sh113u   "Hectares for agricultural land (unit)"
label variable sh113n   "Hectares for agricultural land (number)"
label variable sh114g   "Freezer"
label variable sh114h   "Electric generator/invertor"
label variable sh114i   "Washing machine"
label variable sh114j   "Camera"
label variable sh114k   "Video/DVD/VCD"
label variable sh114l   "Sewing machine"
label variable sh114m   "Bed"
label variable sh114n   "Table"
label variable sh114o   "Chair"
label variable sh114p   "Cabinet/cupboard"
label variable sh115h   "Boat without a motor"
label variable sblangq  "Language of questionnaire (biomarker visit)"
label variable sblangi  "Language of interview (biomarker visit)"
label variable sblangr  "Language of respondent (biomarker visit)"
label variable sbtrans  "Translator used (biomarker visit)"
label variable hv101    "Relationship to head"
label variable hv102    "Usual resident"
label variable hv103    "Slept last night"
label variable hv104    "Sex of household member"
label variable hv105    "Age of household members"
label variable hv117    "Eligibility for female interview"
label variable hv120    "Children eligibility for height/weight and hemoglobin"
label variable sh07ad   "Date of birth 0-6 years: day"
label variable sh07am   "Date of birth 0-6 years: month"
label variable sh07ay   "Date of birth 0-6 years: year"
label variable hc0      "Index to Household Schedule"
label variable hc1      "Child's age in months"
label variable hc1a     "Child's age in days"
label variable hc16     "Day of birth"
label variable hc17     "Date measured (day)"
label variable hc18     "Date measured (month)"
label variable hc19     "Date measured (year)"
label variable hc20     "Century Day Code (CDC) of measurement"
label variable hc21     "Fieldworker measurer code"
label variable hc27     "Sex"
label variable hc30     "Month of birth"
label variable hc31     "Year of birth"
label variable hc32     "Date of birth (CMC)"
label variable hc32a    "Century Day Code (CDC) of birth"
label variable hc33     "Completeness of HC32 information"
label variable hc51     "Line number of parent/caretaker"
label variable hc52     "Read consent statement - hemoglobin"
label variable hc53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55     "Result of measurement - hemoglobin"
label variable hc56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57     "Anemia level"
label variable hc60     "Mother's line number (woman's questionnaire)"
label variable hc61     "Mother's highest educational level"
label variable hc62     "Mother's highest year of education"
label variable hc63     "Preceding birth interval (months)"
label variable hc64     "Birth order number"
label variable hc68     "Mother's highest educational level (for preliminary and final report)"
label variable hmlidx   "Mosquito Bed Net Designation Number"
label variable hml3     "Net observed by interviewer"
label variable hml4     "Months ago net obtained"
label variable hml5     "NA - Net treated with insecticide when bought"
label variable hml6     "NA - Net treatment status"
label variable hml7     "Brand of net"
label variable hml8     "Net treated since receiving"
label variable hml9     "Time since last re-treatment (months)"
label variable hml10    "Insecticide-Treated Net (ITN)"
label variable hml11    "Number of persons who slept under this net"
label variable hml21    "Someone slept under this net last night"
label variable hmla     "Line number of person who slept in this net"
label variable hmlb     "Line number of person who slept in this net"
label variable hmlc     "Line number of person who slept in this net"
label variable hmld     "Line number of person who slept in this net"
label variable hmle     "NA - Line number of person who slept in this net"
label variable hml22    "Obtained net from campaign, antenatal or immunization visit"
label variable hml23    "Place where net was obtained"
label variable sh121    "Shown Net"
label variable hmhidx   "Index to Household Schedule"
label variable hml12    "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml13    "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml14    "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml15    "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml16    "Corrected age from Individual file"
label variable hml16a   "Age in months (for children)"
label variable hml17    "Flag for age from Individual file"
label variable hml18    "Pregnancy status from Individual file"
label variable hml19    "Person slept under an ever-treated net"
label variable hml20    "Person slept under an LLIN net"
label variable hml30    "Line number of parent/caretaker (for malaria testing)"
label variable hml31    "Read consent statement for malaria"
label variable hml32    "Final result of malaria from blood smear test"
label variable hml32a   "NA - Presence of species: falciparum (Pf)"
label variable hml32b   "NA - Presence of species: malariae (Pm)"
label variable hml32c   "NA - Presence of species: ovale (Po)"
label variable hml32d   "NA - Presence of species: vivax (Pv)"
label variable hml32e   "NA - Presence of species: CS"
label variable hml32f   "NA - Presence of species: CS"
label variable hml32g   "NA - Presence of species: CS"
label variable hml33    "Result of malaria measurement"
label variable hml34    "Bar code for blood smear sample"
label variable hml35    "Result of malaria rapid test"
label variable hml36    "Fieldworker measurer code for malaria"
label variable sb115    "Result of the malaria RDT"
label variable sb118a   "Child suffering any illnesses or symptoms: Extreme weakness"
label variable sb118b   "Child suffering any illnesses or symptoms: Inability to drink or breastfeed"
label variable sb118c   "Child suffering any illnesses or symptoms: Vomiting everything"
label variable sb118d   "Child suffering any illnesses or symptoms: Loss of consciousness"
label variable sb118e   "Child suffering any illnesses or symptoms: Deep and labored breathing"
label variable sb118f   "Child suffering any illnesses or symptoms: Multiple convulsions"
label variable sb118g   "Child suffering any illnesses or symptoms: Abnormal spontaneous bleeding"
label variable sb118h   "Child suffering any illnesses or symptoms: Yellow eyes/jaundice"
label variable sb121    "Taking ACT given by a doctor/health center to treat the malaria"
label variable sb125    "Accepted medicine for malaria treatment"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV006   
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV018   
 99999 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV024   
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Brong Ahafo"
     8 "Northern"
     9 "Upper East"
    10 "Upper West"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV030   
 99999 "Missing"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV045A  
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
;
label define HV045B  
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     6 "Other"
;
label define HV045C  
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     6 "Other"
;
label define HV046   
     0 "No"
     1 "Yes"
;
label define HV801   
  9999 "Missing"
;
label define HV802   
  9999 "Missing"
;
label define HV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define HV804   
     9 "Missing"
;
label define HV807M  
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    72 "Sachet water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    96 "Other"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic/marble/porcelain tiles/terrazo"
    34 "Cement"
    35 "Woolen carpet/synthetic carpet"
    36 "Linoleum/rubber carpet"
    96 "Other"
;
label define HV214   
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Mud/landcrete"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
;
label define HV215   
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Zinc/aluminum"
    32 "Wood"
    33 "Calamine/cement fiber"
    34 "Ceramic/brick tiles"
    35 "Cement"
    36 "Roofing shingles"
    37 "Asbestos/slate roofing sheets"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    95 "95+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop residue"
    11 "Animal dung"
    95 "No food cooked in household"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV243E  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
   950 "95 or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV253   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253Z  
     0 "No"
     1 "Yes: don't know who sprayed the dwelling"
     8 "Don't know if it was sprayed"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HV270A  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
     7 "7 or more"
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SH113U  
     1 "Hectares"
     2 "Acres"
     3 "Plots"
     9 "Special values"
;
label define SH113N  
  95.0 "More than 95"
;
label define SH114G  
     0 "No"
     1 "Yes"
;
label define SH114H  
     0 "No"
     1 "Yes"
;
label define SH114I  
     0 "No"
     1 "Yes"
;
label define SH114J  
     0 "No"
     1 "Yes"
;
label define SH114K  
     0 "No"
     1 "Yes"
;
label define SH114L  
     0 "No"
     1 "Yes"
;
label define SH114M  
     0 "No"
     1 "Yes"
;
label define SH114N  
     0 "No"
     1 "Yes"
;
label define SH114O  
     0 "No"
     1 "Yes"
;
label define SH114P  
     0 "No"
     1 "Yes"
;
label define SH115H  
     0 "No"
     1 "Yes"
;
label define SBLANGQ 
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
;
label define SBLANGI 
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     6 "Other"
;
label define SBLANGR 
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     6 "Other"
;
label define SBTRANS 
     0 "No"
     1 "Yes"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    98 "Don't know"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define SH07AD  
    98 "Don't know"
;
label define SH07AM  
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    98 "Don't know"
;
label define SH07AY  
  9998 "Don't know"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC18    
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present/other"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Middle/JSS/JHS"
     3 "Secondary/SSS/SHS"
     4 "Higher"
;
label define HC62    
     0 "Less than one year"
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary"
     2 "Middle/JSS/JHS"
     3 "Secondary/SSS/SHS or Higher"
     8 "Don't know"
;
label define HML3    
     0 "Not seen"
     1 "Yes, seen"
;
label define HML4    
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML5    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HML6    
     0 "Not pretreated"
     1 "Pretreated, permanent treatment"
     2 "Pretreated, requiring future treatment"
     3 "Not pretreated, came with kit and treated at home"
     4 "Pretreated, treatment type not known"
     6 "Other"
     8 "Don't know"
;
label define HML7    
    10 "Long-lasting insecticide treated nets (LLIN)"
    11 "Olyset"
    12 "Permanet"
    13 "Interceptor"
    14 "Netprotect"
    15 "Duranet"
    16 "Life net"
    17 "Dawa plus"
    18 "Magnet"
    19 "Yorkool"
    20 "Other/don't know brand"
    96 "Other type"
    98 "DK type"
;
label define HML8    
     0 "No"
     1 "Yes"
     2 "Permanent/LLIN net"
     8 "Not sure"
;
label define HML9    
    95 "25+ months ago"
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML10   
     0 "No, don't know"
     1 "Yes"
;
label define HML11   
     5 "5+"
;
label define HML21   
     0 "No"
     1 "Yes"
     8 "Not sure (DK)"
;
label define HMLA    
     0 "No one"
;
label define HMLB    
    99 "Missing"
;
label define HMLC    
    99 "Missing"
;
label define HML22   
     0 "No"
     1 "Yes, 2014-2016 mass distribution campaign"
     2 "Yes, antenatal care"
     3 "Yes, immunization visit"
;
label define HML23   
    10 "Government health facility"
    20 "Private health facility"
    21 "NGO"
    30 "Other sources"
    31 "Pharmacy/ chemist/ drug store"
    32 "Shop/market"
    33 "Community Health Worker (CHW)"
    34 "Religious institution"
    35 "Primary schools"
    36 "Community Based Agents (CBAs)"
    37 "Petrol station/mobile mart"
    96 "Other"
    98 "Don't know"
;
label define SH121   
     0 "Not observed"
     1 "Observed hanging"
     2 "Observed not hanging"
;
label define HML12   
     0 "Did not sleep under a net"
     1 "Only treated (ITN) nets"
     2 "Both treated (ITN) and untreated nets"
     3 "Only untreated nets"
;
label define HML13   
     0 "Did not sleep under net"
;
label define HML16   
    95 "95+"
    98 "Don't know"
;
label define HML17   
     0 "No data from Individual file"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HML18   
     0 "Not pregnant, don't know"
     1 "Pregnant"
;
label define HML19   
     0 "No"
     1 "Yes"
;
label define HML20   
     0 "No"
     1 "Yes"
;
label define HML30   
     0 "Not in household"
;
label define HML31   
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define HML32   
     0 "Negative"
     1 "Positive"
     3 "Unreadable"
     6 "Test undetermined"
     7 "Sample not found in lab database"
;
label define HML32A  
     0 "No"
     1 "Yes"
;
label define HML32B  
     0 "No"
     1 "Yes"
;
label define HML32C  
     0 "No"
     1 "Yes"
;
label define HML32D  
     0 "No"
     1 "Yes"
;
label define HML32E  
     0 "No"
     1 "Yes"
;
label define HML32F  
     0 "No"
     1 "Yes"
;
label define HML32G  
     0 "No"
     1 "Yes"
;
label define HML33   
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HML35   
     0 "Negative"
     1 "Positive"
     6 "Other"
;
label define SB115   
     1 "Positive, Pf"
     2 "Positive, PAN"
     3 "Positive, Pf and PAN"
     4 "Negative"
     6 "Other"
;
label define SB118A  
     0 "No"
     1 "Yes"
;
label define SB118B  
     0 "No"
     1 "Yes"
;
label define SB118C  
     0 "No"
     1 "Yes"
;
label define SB118D  
     0 "No"
     1 "Yes"
;
label define SB118E  
     0 "No"
     1 "Yes"
;
label define SB118F  
     0 "No"
     1 "Yes"
;
label define SB118G  
     0 "No"
     1 "Yes"
;
label define SB118H  
     0 "No"
     1 "Yes"
;
label define SB121   
     0 "No"
     1 "Yes"
;
label define SB125   
     1 "Accepted medicine"
     2 "Refused"
     6 "Other"
;

#delimit cr
label values hv003    HV003   
label values hv006    HV006   
label values hv015    HV015   
label values hv020    HV020   
label values hv024    HV024   
label values hv025    HV025   
label values hv042    HV042   
label values hv045a   HV045A  
label values hv045b   HV045B  
label values hv045c   HV045C  
label values hv046    HV046   
label values hv803    HV803   
label values hv807m   HV807M  
label values hv201    HV201   
label values hv202    HV202   
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv235    HV235   
label values hv238    HV238   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv243e   HV243E  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv253    HV253   
label values hv253a   HV253A  
label values hv253b   HV253B  
label values hv253c   HV253C  
label values hv253d   HV253D  
label values hv253e   HV253E  
label values hv253f   HV253F  
label values hv253g   HV253G  
label values hv253h   HV253H  
label values hv253x   HV253X  
label values hv253z   HV253Z  
label values hv270    HV270   
label values hv270a   HV270A  
label values hml1     HML1    
label values sh113u   SH113U  
label values sh113n   SH113N  
label values sh114g   SH114G  
label values sh114h   SH114H  
label values sh114i   SH114I  
label values sh114j   SH114J  
label values sh114k   SH114K  
label values sh114l   SH114L  
label values sh114m   SH114M  
label values sh114n   SH114N  
label values sh114o   SH114O  
label values sh114p   SH114P  
label values sh115h   SH115H  
label values sblangq  SBLANGQ 
label values sblangi  SBLANGI 
label values sblangr  SBLANGR 
label values sbtrans  SBTRANS 
label values hv101    HV101   
label values hv102    HV102   
label values hv103    HV103   
label values hv104    HV104   
label values hv105    HV105   
label values hv117    HV117   
label values hv120    HV120   
label values sh07ad   SH07AD  
label values sh07am   SH07AM  
label values sh07ay   SH07AY  
label values hc16     HC16    
label values hc18     HC18    
label values hc27     HC27    
label values hc30     HC30    
label values hc31     HC31    
label values hc33     HC33    
label values hc51     HC51    
label values hc52     HC52    
label values hc53     HC53    
label values hc55     HC55    
label values hc56     HC56    
label values hc57     HC57    
label values hc60     HC60    
label values hc61     HC61    
label values hc62     HC62    
label values hc68     HC68    
label values hml3     HML3    
label values hml4     HML4    
label values hml5     HML5    
label values hml6     HML6    
label values hml7     HML7    
label values hml8     HML8    
label values hml9     HML9    
label values hml10    HML10   
label values hml11    HML11   
label values hml21    HML21   
label values hmla     HMLA    
label values hml22    HML22   
label values hml23    HML23   
label values sh121    SH121   
label values hml12    HML12   
label values hml13    HML13   
label values hml16    HML16   
label values hml17    HML17   
label values hml18    HML18   
label values hml19    HML19   
label values hml20    HML20   
label values hml30    HML30   
label values hml31    HML31   
label values hml32    HML32   
label values hml32a   HML32A  
label values hml32b   HML32B  
label values hml32c   HML32C  
label values hml32d   HML32D  
label values hml32e   HML32E  
label values hml32f   HML32F  
label values hml32g   HML32G  
label values hml33    HML33   
label values hml35    HML35   
label values sb115    SB115   
label values sb118a   SB118A  
label values sb118b   SB118B  
label values sb118c   SB118C  
label values sb118d   SB118D  
label values sb118e   SB118E  
label values sb118f   SB118F  
label values sb118g   SB118G  
label values sb118h   SB118H  
label values sb121    SB121   
label values sb125    SB125   
