infix using "C:\COUNTRIES\GH82\GHKR82FL.dct"

label variable caseid   "Case Identification"
label variable hidxa    "Index to birth history"
label variable v000     "Country code and phase"
label variable v001     "Cluster number"
label variable v002     "Household number"
label variable v003     "Respondent's line number"
label variable v004     "Ultimate area unit"
label variable v005     "Women's individual sample weight (6 decimals)"
label variable v006     "Month of interview"
label variable v007     "Year of interview"
label variable v008     "Date of interview (CMC)"
label variable v008a    "Date of interview Century Day Code (CDC)"
label variable v009     "Respondent's month of birth"
label variable v010     "Respondent's year of birth"
label variable v011     "Date of birth (CMC)"
label variable v012     "Respondent's current age"
label variable v013     "Age in 5-year groups"
label variable v014     "Completeness of age information"
label variable v015     "Result of individual interview"
label variable v016     "Day of interview"
label variable v017     "NA - CMC start of calendar"
label variable v018     "NA - Row of month of interview"
label variable v019     "NA - Length of calendar"
label variable v019a    "NA - Number of calendar columns"
label variable v020     "Ever-married sample"
label variable v021     "Primary sampling unit"
label variable v022     "Sample strata for sampling errors"
label variable v023     "Stratification used in sample design"
label variable v024     "Region"
label variable v025     "Type of place of residence"
label variable v026     "NA - De facto place of residence"
label variable v027     "Number of visits"
label variable v028     "Interviewer identification"
label variable v029     "NA - Keyer identification"
label variable v030     "Field supervisor"
label variable v031     "NA - Field editor"
label variable v032     "NA - Office editor"
label variable v034     "NA - Line number of husband"
label variable v040     "Cluster altitude in meters"
label variable v042     "Household selected for hemoglobin"
label variable v044     "NA - Selected for Domestic Violence module"
label variable v045a    "Language of questionnaire"
label variable v045b    "Language of interview"
label variable v045c    "Native language of respondent"
label variable v046     "Translator used"
label variable v101     "Region"
label variable v102     "Type of place of residence"
label variable v106     "Highest educational level"
label variable v107     "Highest year of education"
label variable v113     "Source of drinking water"
label variable v115     "Time to get to water source"
label variable v116     "Type of toilet facility"
label variable v119     "Household has: electricity"
label variable v120     "Household has: radio"
label variable v121     "Household has: television"
label variable v122     "Household has: refrigerator"
label variable v123     "Household has: bicycle"
label variable v124     "Household has: motorcycle/scooter"
label variable v125     "Household has: car/truck"
label variable v127     "Main floor material"
label variable v128     "Main wall material"
label variable v129     "Main roof material"
label variable v130     "Religion"
label variable v131     "Ethnicity"
label variable v133     "Education in single years"
label variable v135     "Usual resident or visitor"
label variable v136     "Number of household members (listed)"
label variable v137     "Number of children 5 and under in household (de jure)"
label variable v138     "Number of eligible women in household (de facto)"
label variable v139     "De jure region of residence"
label variable v140     "De jure type of place of residence"
label variable v149     "Educational attainment"
label variable v150     "Relationship to household head"
label variable v151     "Sex of household head"
label variable v152     "Age of household head"
label variable v153     "Household has: telephone (land-line)"
label variable awfactt  "NA - All woman factor - total"
label variable awfactu  "NA - All woman factor - urban/rural"
label variable awfactr  "NA - All woman factor - regional"
label variable awfacte  "NA - All woman factor - educational"
label variable awfactw  "NA - All woman factor - wealth index"
label variable v155     "Literacy"
label variable v160     "Toilet facilities shared with other households"
label variable v161     "Type of cooking fuel"
label variable v190     "Wealth index combined"
label variable v191     "Wealth index factor score combined (5 decimals)"
label variable v190a    "Wealth index for urban/rural"
label variable v191a    "Wealth index factor score for urban/rural (5 decimals)"
label variable ml101    "Type of mosquito bed net(s) slept under last night"
label variable v201     "Total children ever born"
label variable v202     "Sons at home"
label variable v203     "Daughters at home"
label variable v204     "Sons elsewhere"
label variable v205     "Daughters elsewhere"
label variable v206     "Sons who have died"
label variable v207     "Daughters who have died"
label variable v208     "Births in last five years"
label variable v209     "Births in past year"
label variable v210     "Births in month of interview"
label variable v213     "Currently pregnant"
label variable v214     "Duration of current pregnancy"
label variable v218     "Number of living children"
label variable v219     "Living children + current pregnancy"
label variable v220     "Living children + current pregnancy (grouped)"
label variable v222     "Last birth to interview (months)"
label variable v223     "Completeness of current pregnancy information"
label variable v224     "Entries in birth history"
label variable v237     "Birth between last and interview"
label variable v238     "Births in last three years"
label variable v417     "Entries in pregnancy and postnatal care roster"
label variable v418a    "Entries in child health roster"
label variable v419     "Entries in height/weight roster"
label variable v459     "Have mosquito bed net for sleeping (from household questionnaire)"
label variable v460     "Children under 5 slept under mosquito bed net last night (household questionnair"
label variable v461     "Respondent slept under mosquito bed net"
label variable v468     "Record for Last Birth"
label variable v481     "Covered by health insurance"
label variable v481a    "Health insurance type: mutual/community organization"
label variable v481b    "Health insurance type: provided by employer"
label variable v481c    "Health insurance type: social security - national/district health insurance (NHI"
label variable v481d    "Health insurance type: private/commercially purchased"
label variable v481e    "NA - Health insurance type: CS"
label variable v481f    "NA - Health insurance type: CS"
label variable v481g    "NA - Health insurance type: CS"
label variable v481h    "NA - Health insurance type: CS"
label variable v481x    "Health insurance type: other"
label variable bidx     "Birth column number"
label variable bord     "Birth order number"
label variable b0       "Child is twin"
label variable b1       "Month of birth"
label variable b2       "Year of birth"
label variable b3       "Date of birth (CMC)"
label variable b4       "Sex of child"
label variable b5       "Child is alive"
label variable b8       "Current age of child"
label variable b9       "Child lives with whom"
label variable b10      "Completeness of information"
label variable b11      "Preceding birth interval (months)"
label variable b12      "Succeeding birth interval (months)"
label variable b15      "Live birth between births"
label variable b16      "Child's line number in household"
label variable b17      "Day of birth"
label variable b18      "Century Day Code of birth (CDC)"
label variable b19      "Current age of child in months (months since birth for dead children)"
label variable midx     "Index to Birth History"
label variable m2a      "Prenatal: doctor"
label variable m2b      "Prenatal: nurse/midwife"
label variable m2c      "Prenatal: community health officer/nurse"
label variable m2d      "NA - Prenatal: CS health professional"
label variable m2e      "NA - Prenatal: CS health professional"
label variable m2f      "NA - Prenatal: CS health professional"
label variable m2g      "Prenatal: traditional birth attendant"
label variable m2h      "Prenatal: community/village health worker"
label variable m2i      "Prenatal: traditional health practitioner"
label variable m2j      "NA - Prenatal: CS other person"
label variable m2k      "Prenatal: other"
label variable m2l      "NA - Prenatal: CS other"
label variable m2m      "NA - Prenatal: CS other"
label variable m2n      "Prenatal: no one"
label variable m13      "Timing of 1st antenatal check (months)"
label variable m14      "Number of antenatal visits during pregnancy"
label variable m49a     "During pregnancy took: SP/fansidar for malaria"
label variable m49b     "NA - During pregnancy took: chloroquine for malaria"
label variable m49c     "NA - During pregnancy took: CS drug for malaria"
label variable m49d     "NA - During pregnancy took: CS drug for malaria"
label variable m49e     "NA - During pregnancy took: CS drug for malaria"
label variable m49f     "NA - During pregnancy took: CS drug for malaria"
label variable m49g     "NA - During pregnancy took: CS drug for malaria"
label variable m49x     "NA - During pregnancy took: other drug for malaria"
label variable m49z     "NA - During pregnancy took: don't know"
label variable m49y     "NA - During pregnancy took: no drug for malaria"
label variable m57a     "Antenatal care: respondent's home"
label variable m57b     "Antenatal care: other home"
label variable m57c     "NA - Antenatal care: CS home"
label variable m57d     "NA - Antenatal care: CS home"
label variable m57e     "Antenatal care: government hospital"
label variable m57f     "Antenatal care: government health center"
label variable m57g     "Antenatal care: government health post"
label variable m57h     "Antenatal care: other public sector"
label variable m57i     "NA - Antenatal care: CS public health"
label variable m57j     "NA - Antenatal care: CS public health"
label variable m57k     "NA - Antenatal care: CS public health"
label variable m57l     "NA - Antenatal care: CS public health"
label variable m57m     "Antenatal care: private hospital/clinic"
label variable m57n     "Antenatal care: other private medical sector"
label variable m57o     "NA - Antenatal care: CS private medical"
label variable m57p     "NA - Antenatal care: CS private medical"
label variable m57q     "NA - Antenatal care: CS private medical"
label variable m57r     "NA - Antenatal care: CS private medical"
label variable m57s     "NA - Antenatal care: CS other"
label variable m57t     "NA - Antenatal care: CS other"
label variable m57u     "NA - Antenatal care: CS other"
label variable m57v     "NA - Antenatal care: CS other"
label variable m57x     "Antenatal care: other"
label variable h22      "Had fever in last two weeks"
label variable h32a     "Fever/cough: govt hospital"
label variable h32b     "Fever/cough: govt health center"
label variable h32c     "Fever/cough: govt health post/CHPS"
label variable h32d     "Fever/cough: public mobile clinic"
label variable h32e     "Fever/cough: public fieldworker/CHW"
label variable h32f     "Fever/cough: other public sector"
label variable h32g     "NA - Fever/cough: CS public sector"
label variable h32h     "NA - Fever/cough: CS public sector"
label variable h32i     "NA - Fever/cough: CS public sector"
label variable h32j     "Fever/cough: private hospital/clinic"
label variable h32k     "Fever/cough: private pharmacy"
label variable h32l     "Fever/cough: private doctor"
label variable h32m     "Fever/cough: private chemist/drug store"
label variable h32n     "Fever/cough: private FPG/PPAG clinic"
label variable h32o     "Fever/cough: private mobile clinic"
label variable h32p     "Fever/cough: private fieldworker/CHW"
label variable h32q     "Fever/cough: other private medical sector"
label variable h32r     "NA - Fever/cough: CS private medical"
label variable h32s     "Fever/cough: shop"
label variable h32t     "Fever/cough: traditional practitioner"
label variable h32u     "Fever/cough: market"
label variable h32v     "Fever/cough: itinerant drug seller"
label variable h32w     "NA - Fever/cough: CS other sector"
label variable h32x     "Fever/cough: other"
label variable h32y     "Fever/cough: no treatment"
label variable h32z     "Fever/cough: medical treatment"
label variable h46a     "Place first sought treatment for fever"
label variable h46b     "Number of days after fever began sought advice or treatment"
label variable h47      "Blood taken from child's finger/heel for testing"
label variable hwidx    "Index to Birth History"
label variable hw1      "Child's age in months"
label variable hw16     "Day of birth of child"
label variable hw17     "Date measured (day)"
label variable hw18     "Date measured (month)"
label variable hw19     "Date measured (year)"
label variable hw51     "Line number of parent/caretaker"
label variable hw52     "Read consent statement - hemoglobin"
label variable hw53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hw55     "Result of measurement - hemoglobin"
label variable hw56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hw57     "Anemia level"
label variable idxml    "Index to Birth History"
label variable ml0      "Type of mosquito bed net(s) child slept under last night"
label variable ml1      "Number of times took fansidar during pregnancy"
label variable ml2      "Source of antimalarial during pregnancy"
label variable ml11     "NA - Child has fever/cough now"
label variable ml12     "NA - Child has had convulsions in last 2 weeks"
label variable ml13a    "Fansidar taken for fever"
label variable ml13b    "Chloroquine taken for fever"
label variable ml13c    "Amodiaquine taken for fever"
label variable ml13d    "Quinine taken for fever"
label variable ml13da   "Quinine injection/IV taken for fever"
label variable ml13e    "Combination with artemisinin taken for fever"
label variable ml13aa   "Artesunate rectal taken for fever"
label variable ml13ab   "Artesunate injection/IV taken for fever"
label variable ml13f    "NA - CS antimalarial taken for fever"
label variable ml13g    "NA - CS antimalarial taken for fever"
label variable ml13h    "Other antimalarial taken for fever"
label variable ml13i    "Antibiotic pill/syrup taken for fever"
label variable ml13j    "Antibiotic injection taken for fever"
label variable ml13k    "Aspirin taken for fever"
label variable ml13l    "Acetaminophen/paracetamol/panadol taken for fever"
label variable ml13m    "Ibuprofen taken for fever"
label variable ml13n    "Herbal medicine taken for fever"
label variable ml13o    "NA - CS other taken for fever"
label variable ml13p    "NA - CS other taken for fever"
label variable ml13x    "Other taken for fever"
label variable ml13y    "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13z    "Don't know if or what was taken for fever"
label variable ml14a    "NA - Injection given for fever/convulsion"
label variable ml14b    "NA - Suppository given for fever/convulsion"
label variable ml14y    "NA - No suppository or injection given for fever/convulsion"
label variable ml14z    "NA - Don't know if suppository or injection given for fever/convulsion"
label variable ml15a    "Timing of start of fansidar"
label variable ml15b    "NA - Number of days child took fansidar"
label variable ml15c    "NA - First source for fansidar"
label variable ml16a    "Timing of start of chloroquine"
label variable ml16b    "NA - Number of days child took chloroquine"
label variable ml16c    "NA - First source for chloroquine"
label variable ml17a    "Timing of start of amodiaquine"
label variable ml17b    "NA - Number of days child took amodiaquine"
label variable ml17c    "NA - First source for amodiaquine"
label variable ml18a    "Timing of start of quinine"
label variable ml18b    "NA - Number of days child took quinine"
label variable ml18c    "NA - First source for quinine"
label variable ml19a    "NA - For fever/convulsion: consulted traditional healer"
label variable ml19b    "NA - For fever/convulsion: gave tepid sponging"
label variable ml19c    "NA - For fever/convulsion: gave herbs"
label variable ml19d    "NA - For fever/convulsion: CS"
label variable ml19e    "NA - For fever/convulsion: CS"
label variable ml19f    "NA - For fever/convulsion: CS"
label variable ml19x    "NA - For fever/convulsion: other"
label variable ml19y    "NA - For fever/convulsion: gave/did nothing"
label variable ml19z    "NA - For fever/convulsion: don't know if something else was done"
label variable ml20a    "Timing of start of combination with artemisinin"
label variable ml20b    "NA - Number of days child took combination with artemisinin"
label variable ml20c    "NA - First source for combination with artemisinin"
label variable ml21a    "NA - Timing of start of CS antimalarial use"
label variable ml21b    "NA - Number of days child took CS antimalarial"
label variable ml21c    "NA - First source for CS antimalarial"
label variable ml22a    "NA - Timing of start of CS antimalarial use"
label variable ml22b    "NA - Number of days child took CS antimalarial"
label variable ml22c    "NA - First source for CS antimalarial"
label variable ml23a    "Timing of start of other anti-malarial use"
label variable ml23b    "NA - Number of days child took other anti-malarial"
label variable ml23c    "NA - First source for other anti-malarial"
label variable ml24c    "NA - First source for antibiotic pill/syrup"
label variable ml25a    "Timing of start of artesunate"
label variable sdistrict "District"
label variable s105     "Highest educational level"
label variable s105a    "Highest educational level"
label variable s111     "Registered by health insurance"
label variable s114     "Aware that malaria is covered under the NHIS"
label variable s211     "Number of live births in 2014-2019"
label variable s501     "Seen or heard any messages about malaria in past 6 months"
label variable s502a    "Heard malaria messages on: radio"
label variable s502b    "Heard malaria messages on: tv"
label variable s502c    "Heard malaria messages on: poster/billboard"
label variable s502d    "Heard malaria messages on: newspaper/magazine"
label variable s502e    "Heard malaria messages on: leaflet/brochure"
label variable s502f    "Heard malaria messages on: health worker"
label variable s502g    "Heard malaria messages on: CHW"
label variable s502h    "Heard malaria messages on: community volunteer/CBA"
label variable s502i    "Heard malaria messages on: word of mouth"
label variable s502j    "Heard malaria messages on: community event/durbar meeting"
label variable s502x    "Heard malaria messages on: anywhere else"
label variable s502z    "Heard malaria messages on: don't remember"
label variable s503a    "Have seen or heard malaria messages on the radio"
label variable s503b    "Have seen or heard malaria messages on the tv"
label variable s503c    "Have seen or heard malaria messages on a poster/billboard"
label variable s503d    "Have seen or heard malaria messages in a newspaper/magazine"
label variable s503e    "Have seen or heard malaria messages on a leaflet/brochure"
label variable s503f    "Have seen or heard malaria messages from a health worker"
label variable s503g    "Have seen or heard malaria messages from a CHW"
label variable s503h    "Have seen or heard malaria messages from a community volunteer/CBA"
label variable s503i    "Have seen or heard malaria messages from word of mouth"
label variable s503j    "Have seen or heard malaria messages at a community event/durbar meeting"
label variable s504a    "Messages seen/heard in past 6 months: if have fever go to health facility"
label variable s504b    "Messages seen/heard in past 6 months: sleep under an insecticide-treated mosquit"
label variable s504c    "Messages seen/heard in past 6 months: pregnant women should take drugs to preven"
label variable s504d    "Messages seen/heard in past 6 months: SP protects pregnant women and unborn baby"
label variable s504e    "Messages seen/heard in past 6 months: always test before treating malaria"
label variable s504f    "Messages seen/heard in past 6 months: treat malaria with ACTs"
label variable s504g    "Messages seen/heard in past 6 months: malaria kills"
label variable s504h    "Messages seen/heard in past 6 months: keep surroundings clean"
label variable s504x    "Messages seen/heard in past 6 months: other"
label variable s504z    "Messages seen/heard in past 6 months: don't know/remember"
label variable s505a    "Seen/heard Goodlife campaign recommending pregnant women to sleep under treated "
label variable s505b    "Seen/heard Goodlife campaign recommending sleeping under treated bed nets every "
label variable s505c    "Seen/heard advert about 'My net my life'"
label variable s505d    "Seen/heard advert where people were asked to test first before treated"
label variable s506     "Seen/heard advert on use of ACTs/malaria meds in past 6 months"
label variable s507a    "Source of message on use of ACTs/malaria meds: tv"
label variable s507b    "Source of message on use of ACTs/malaria meds: radio"
label variable s507c    "Source of message on use of ACTs/malaria meds: newspaper/magazine"
label variable s507d    "Source of message on use of ACTs/malaria meds: poster/leaflets"
label variable s507e    "Source of message on use of ACTs/malaria meds: billboard"
label variable s507x    "Source of message on use of ACTs/malaria meds: other"
label variable s507z    "Source of message on use of ACTs/malaria meds: don't know/remember"
label variable s508a    "Ways to protect against malaria: sleep under a mosquito net"
label variable s508b    "Ways to protect against malaria: sleep under an ITN"
label variable s508c    "Ways to protect against malaria: use mosquito repellent"
label variable s508d    "Ways to protect against malaria: take preventative medications"
label variable s508e    "Ways to protect against malaria: spray house with insecticide"
label variable s508f    "Ways to protect against malaria: fill in stagnant waters (puddles)"
label variable s508g    "Ways to protect against malaria: keep surrounding clean"
label variable s508h    "Ways to protect against malaria: put mosquito screen on windows"
label variable s508x    "Ways to protect against malaria: other"
label variable s508z    "Ways to protect against malaria: don't know"
label variable s509     "Almost always worry it might be malaria when a child has fever"
label variable s510     "Don't worry about malaria because it can be easily treated"
label variable s511     "Heard about malaria vaccine"
label variable s512     "Allow child to be vaccinated against malaria"
label variable idx94    "Index to Birth History"
label variable s305ba   "Took SP/Fansidar only 1-2 times: facility too far"
label variable s305bb   "Took SP/Fansidar only 1-2 times: had no money"
label variable s305bc   "Took SP/Fansidar only 1-2 times: side effects"
label variable s305bd   "Took SP/Fansidar only 1-2 times: not aware had to take more"
label variable s305be   "Took SP/Fansidar only 1-2 times: did not want to take"
label variable s305bf   "Took SP/Fansidar only 1-2 times: not given"
label variable s305bg   "Took SP/Fansidar only 1-2 times: not available"
label variable s305bx   "Took SP/Fansidar only 1-2 times: other"
label variable s305bz   "Took SP/Fansidar only 1-2 times: don't know"
label variable idx95    "Index to Birth History"
label variable s403a    "Enrolled in program to receive medicine monthly for 4 months to prevent malaria"
label variable s403b1   "Number of doses taken in 2017"
label variable s403b2   "Number of doses taken in 2018"
label variable s405a    "Result of malaria blood test"
label variable s407ba   "Reason sought advice/treatment from source: child just fell ill"
label variable s407bb   "Reason sought advice/treatment from source: child not very ill"
label variable s407bc   "Reason sought advice/treatment from source: clinic too far"
label variable s407bd   "Reason sought advice/treatment from source: have no money"
label variable s407be   "Reason sought advice/treatment from source: waiting for child's father"
label variable s407bf   "Reason sought advice/treatment from source: don't know what to do"
label variable s407bg   "Reason sought advice/treatment from source: this site was closer"
label variable s407bh   "Reason sought advice/treatment from source: trust this source"
label variable s407bi   "Reason sought advice/treatment from source: instruction by household head"
label variable s407bx   "Reason sought advice/treatment from source: other"
label variable s412ba   "Reason did not take antimalarial: fever was not malaria"
label variable s412bb   "Reason did not take antimalarial: none available at facility"
label variable s412bc   "Reason did not take antimalarial: provider did not offer antimalarial"
label variable s412bd   "Reason did not take antimalarial: provider refused to give antimalarial"
label variable s412be   "Reason did not take antimalarial: afraid of effects of drugs on health"
label variable s412bf   "Reason did not take antimalarial: child not very ill"
label variable s412bg   "Reason did not take antimalarial: clinic too far"
label variable s412bh   "Reason did not take antimalarial: have no money"
label variable s412bi   "Reason did not take antimalarial: do not know to take antimalarial"
label variable s412bj   "Reason did not take antimalarial: medicine at home"
label variable s412bk   "Reason did not take antimalarial: did not think it was malaria"
label variable s412bx   "Reason did not take antimalarial: other"

#delimit ;
label define V013    
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define V014    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define V015    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partially completed"
     6 "Respondent incapacitated"
     7 "Other"
;
label define V018    
     0 "No calendar"
;
label define V019    
     0 "No calendar"
;
label define V019A   
     0 "No calendar"
;
label define V020    
     0 "All woman sample"
     1 "Ever married sample"
;
label define V022    
     1 "Western: Urban"
     2 "Western: Rural"
     3 "Central: Urban"
     4 "Central: Rural"
     5 "Greater Accra: Urban"
     6 "Greater Accra: Rural"
     7 "Volta: Urban"
     8 "Volta: Rural"
     9 "Eastern: Urban"
    10 "Eastern: Rural"
    11 "Ashanti: Urban"
    12 "Ashanti: Rural"
    13 "Brong Ahafo: Urban"
    14 "Brong Ahafo: Rural"
    15 "Northern: Urban"
    16 "Northern: Rural"
    17 "Upper East: Urban"
    18 "Upper East: Rural"
    19 "Upper West: Urban"
    20 "Upper West: Rural"
;
label define V023    
     1 "Western: Urban"
     2 "Western: Rural"
     3 "Central: Urban"
     4 "Central: Rural"
     5 "Greater Accra: Urban"
     6 "Greater Accra: Rural"
     7 "Volta: Urban"
     8 "Volta: Rural"
     9 "Eastern: Urban"
    10 "Eastern: Rural"
    11 "Ashanti: Urban"
    12 "Ashanti: Rural"
    13 "Brong Ahafo: Urban"
    14 "Brong Ahafo: Rural"
    15 "Northern: Urban"
    16 "Northern: Rural"
    17 "Upper East: Urban"
    18 "Upper East: Rural"
    19 "Upper West: Urban"
    20 "Upper West: Rural"
;
label define V024    
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Brong Ahafo"
     8 "Northern"
     9 "Upper East"
    10 "Upper West"
;
label define V025    
     1 "Urban"
     2 "Rural"
;
label define V026    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V027    
     9 "Missing"
;
label define V034    
     0 "Husband not in household"
;
label define V040    
  9999 "Missing"
;
label define V042    
     0 "Not selected"
     1 "Selected"
;
label define V044    
     0 "Woman not selected"
     1 "Woman selected and interviewed"
     2 "Woman selected, but privacy not possible"
     3 "Woman selected, but not interviewed"
;
label define V045A   
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     5 "Dagbani"
;
label define V045B   
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     5 "Dagbani"
     6 "Other"
;
label define V045C   
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     5 "Dagbani"
     6 "Other"
;
label define V046    
     0 "No"
     1 "Yes"
;
label define V101    
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Brong Ahafo"
     8 "Northern"
     9 "Upper East"
    10 "Upper West"
;
label define V102    
     1 "Urban"
     2 "Rural"
;
label define V106    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define V107    
     0 "No years completed at level V106"
;
label define V113    
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    72 "Sachet water"
    96 "Other"
    97 "Not a dejure resident"
;
label define V115    
   996 "On premises"
   997 "Not a dejure resident"
   998 "Don't know"
;
label define V116    
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    16 "Flush, bio-digester (biofil)"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
    97 "Not a dejure resident"
;
label define V119    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V120    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V121    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V122    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V123    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V124    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V125    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V127    
    10 "NATURAL"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic/marble/porcelain tiles/terrazo"
    34 "Cement"
    35 "Woolen carpet/synthetic carpet"
    36 "Linoleum/rubber carpet"
    96 "Other"
    97 "Not a dejure resident"
;
label define V128    
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Mud/landcrete"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
    97 "Not a dejure resident"
;
label define V129    
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Zinc/aluminum"
    32 "Wood"
    33 "Ceramic/brick tiles"
    34 "Cement"
    35 "Roofing shingles"
    36 "Asbestos/slate roofing sheets"
    96 "Other"
    97 "Not a dejure resident"
;
label define V130    
     1 "Catholic"
     2 "Anglican"
     3 "Methodist"
     4 "Presbyterian"
     5 "Pentecostal/Charismatic"
     6 "Other Christian"
     7 "Islam"
     8 "Traditional/Spiritualist"
    95 "No religion"
    96 "Other"
;
label define V131    
     1 "Akan"
     2 "Ga/Dangme"
     3 "Ewe"
     4 "Guan"
     5 "Mole-Dagbani"
     6 "Grusi"
     7 "Gurma"
     8 "Mande"
    96 "Other"
;
label define V133    
    97 "Inconsistent"
;
label define V135    
     1 "Usual resident"
     2 "Visitor"
;
label define V139    
     0 "Abroad"
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Brong Ahafo"
     8 "Northern"
     9 "Upper East"
    10 "Upper West"
    97 "Not dejure resident"
;
label define V140    
     0 "Abroad"
     1 "Urban"
     2 "Rural"
     7 "Not a dejure resident"
;
label define V149    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define V150    
     1 "Head"
     2 "Wife"
     3 "Daughter"
     4 "Daughter-in-law"
     5 "Granddaughter"
     6 "Mother"
     7 "Mother-in-law"
     8 "Sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "Don't know"
;
label define V151    
     1 "Male"
     2 "Female"
;
label define V152    
    95 "95+"
    98 "Don't know"
;
label define V153    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V155    
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define V160    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V161    
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in house"
    96 "Other"
    97 "Not a dejure resident"
;
label define V190    
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define V190A   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define ML101   
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define V208    
     0 "No births"
;
label define V209    
     0 "No births"
;
label define V213    
     0 "No or unsure"
     1 "Yes"
;
label define V220    
     6 "6+"
;
label define V223    
     7 "Month - exact date"
     8 "None - date placed"
;
label define V237    
     0 "No"
     1 "Yes"
;
label define V459    
     0 "No"
     1 "Yes"
;
label define V460    
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define V461    
     0 "No"
     1 "Yes"
;
label define V468    
     0 "See specific questions"
     1 "Last birth only"
     2 "All births in last 5 years"
;
label define V481    
     0 "No"
     1 "Yes"
;
label define V481A   
     0 "No"
     1 "Yes"
;
label define V481B   
     0 "No"
     1 "Yes"
;
label define V481C   
     0 "No"
     1 "Yes"
;
label define V481D   
     0 "No"
     1 "Yes"
;
label define V481E   
     0 "No"
     1 "Yes"
;
label define V481F   
     0 "No"
     1 "Yes"
;
label define V481G   
     0 "No"
     1 "Yes"
;
label define V481H   
     0 "No"
     1 "Yes"
;
label define V481X   
     0 "No"
     1 "Yes"
;
label define B0      
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
;
label define B4      
     1 "Male"
     2 "Female"
;
label define B5      
     0 "No"
     1 "Yes"
;
label define B9      
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
;
label define B10     
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define B15     
     0 "No"
     1 "Yes"
;
label define B16     
     0 "Not listed in household"
;
label define M2A     
     0 "No"
     1 "Yes"
;
label define M2B     
     0 "No"
     1 "Yes"
;
label define M2C     
     0 "No"
     1 "Yes"
;
label define M2D     
     0 "No"
     1 "Yes"
;
label define M2E     
     0 "No"
     1 "Yes"
;
label define M2F     
     0 "No"
     1 "Yes"
;
label define M2G     
     0 "No"
     1 "Yes"
;
label define M2H     
     0 "No"
     1 "Yes"
;
label define M2I     
     0 "No"
     1 "Yes"
;
label define M2J     
     0 "No"
     1 "Yes"
;
label define M2K     
     0 "No"
     1 "Yes"
;
label define M2L     
     0 "No"
     1 "Yes"
;
label define M2M     
     0 "No"
     1 "Yes"
;
label define M2N     
     0 "No: some care"
     1 "Yes: no care"
;
label define M13     
    98 "Don't know"
;
label define M14     
     0 "No antenatal visits"
    98 "Don't know"
;
label define M49A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49C    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49D    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49E    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49F    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49G    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49X    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49Z    
     0 "No"
     1 "Yes: don't know which drug taken"
     8 "Don't know"
;
label define M49Y    
     0 "No"
     1 "Yes, took no drug"
     8 "Don't know"
;
label define M57A    
     0 "No"
     1 "Yes"
;
label define M57B    
     0 "No"
     1 "Yes"
;
label define M57C    
     0 "No"
     1 "Yes"
;
label define M57D    
     0 "No"
     1 "Yes"
;
label define M57E    
     0 "No"
     1 "Yes"
;
label define M57F    
     0 "No"
     1 "Yes"
;
label define M57G    
     0 "No"
     1 "Yes"
;
label define M57H    
     0 "No"
     1 "Yes"
;
label define M57I    
     0 "No"
     1 "Yes"
;
label define M57J    
     0 "No"
     1 "Yes"
;
label define M57K    
     0 "No"
     1 "Yes"
;
label define M57L    
     0 "No"
     1 "Yes"
;
label define M57M    
     0 "No"
     1 "Yes"
;
label define M57N    
     0 "No"
     1 "Yes"
;
label define M57O    
     0 "No"
     1 "Yes"
;
label define M57P    
     0 "No"
     1 "Yes"
;
label define M57Q    
     0 "No"
     1 "Yes"
;
label define M57R    
     0 "No"
     1 "Yes"
;
label define M57S    
     0 "No"
     1 "Yes"
;
label define M57T    
     0 "No"
     1 "Yes"
;
label define M57U    
     0 "No"
     1 "Yes"
;
label define M57V    
     0 "No"
     1 "Yes"
;
label define M57X    
     0 "No"
     1 "Yes"
;
label define H22     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H32A    
     0 "No"
     1 "Yes"
;
label define H32B    
     0 "No"
     1 "Yes"
;
label define H32C    
     0 "No"
     1 "Yes"
;
label define H32D    
     0 "No"
     1 "Yes"
;
label define H32E    
     0 "No"
     1 "Yes"
;
label define H32F    
     0 "No"
     1 "Yes"
;
label define H32G    
     0 "No"
     1 "Yes"
;
label define H32H    
     0 "No"
     1 "Yes"
;
label define H32I    
     0 "No"
     1 "Yes"
;
label define H32J    
     0 "No"
     1 "Yes"
;
label define H32K    
     0 "No"
     1 "Yes"
;
label define H32L    
     0 "No"
     1 "Yes"
;
label define H32M    
     0 "No"
     1 "Yes"
;
label define H32N    
     0 "No"
     1 "Yes"
;
label define H32O    
     0 "No"
     1 "Yes"
;
label define H32P    
     0 "No"
     1 "Yes"
;
label define H32Q    
     0 "No"
     1 "Yes"
;
label define H32R    
     0 "No"
     1 "Yes"
;
label define H32S    
     0 "No"
     1 "Yes"
;
label define H32T    
     0 "No"
     1 "Yes"
;
label define H32U    
     0 "No"
     1 "Yes"
;
label define H32V    
     0 "No"
     1 "Yes"
;
label define H32W    
     0 "No"
     1 "Yes"
;
label define H32X    
     0 "No"
     1 "Yes"
;
label define H32Y    
     0 "No: received treatment"
     1 "Yes: no treatment"
;
label define H32Z    
     0 "No"
     1 "Yes"
;
label define H46A    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Government health post/CHPS"
    14 "Mobile clinic"
    15 "Fieldworker/CHW"
    16 "Other public sector"
    20 "PRIVATE SECTOR"
    21 "Private hospital/clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "Chemist/drug store"
    25 "FPG/PPAG clinic"
    26 "Mobile clinic"
    27 "Fieldworker/CHW"
    28 "Other private medical sector"
    30 "OTHER"
    31 "Shop"
    32 "Traditional practitioner"
    33 "Market"
    34 "Itinerant drug seller"
    96 "Other"
;
label define H46B    
     0 "Same day"
    98 "Don't know"
;
label define H47     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HW16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HW51    
     0 "Not in household"
;
label define HW52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HW53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HW55    
     0 "Measured"
     1 "Dead"
     3 "Not present"
     4 "Refused"
     6 "Other"
     7 "No measurement found in household"
;
label define HW56    
   997 "Inconsistent"
;
label define HW57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define ML0     
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define ML1     
    98 "Don't know"
;
label define ML2     
     1 "Antenatal visit"
     2 "Another facility visit"
     6 "Other source"
;
label define ML11    
     0 "No"
     1 "Yes, fever only"
     2 "Yes, cough only"
     3 "Both fever and cough"
     8 "Don't know"
;
label define ML12    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define ML13A   
     0 "No"
     1 "Yes"
;
label define ML13B   
     0 "No"
     1 "Yes"
;
label define ML13C   
     0 "No"
     1 "Yes"
;
label define ML13D   
     0 "No"
     1 "Yes"
;
label define ML13DA  
     0 "No"
     1 "Yes"
;
label define ML13E   
     0 "No"
     1 "Yes"
;
label define ML13AA  
     0 "No"
     1 "Yes"
;
label define ML13AB  
     0 "No"
     1 "Yes"
;
label define ML13F   
     0 "No"
     1 "Yes"
;
label define ML13G   
     0 "No"
     1 "Yes"
;
label define ML13H   
     0 "No"
     1 "Yes"
;
label define ML13I   
     0 "No"
     1 "Yes"
;
label define ML13J   
     0 "No"
     1 "Yes"
;
label define ML13K   
     0 "No"
     1 "Yes"
;
label define ML13L   
     0 "No"
     1 "Yes"
;
label define ML13M   
     0 "No"
     1 "Yes"
;
label define ML13N   
     0 "No"
     1 "Yes"
;
label define ML13O   
     0 "No"
     1 "Yes"
;
label define ML13P   
     0 "No"
     1 "Yes"
;
label define ML13X   
     0 "No"
     1 "Yes"
;
label define ML13Y   
     0 "No"
     1 "Yes, nothing taken"
;
label define ML13Z   
     0 "No"
     1 "Yes, don't know"
;
label define ML14A   
     0 "No"
     1 "Yes"
;
label define ML14B   
     0 "No"
     1 "Yes"
;
label define ML14Y   
     0 "No"
     1 "Yes"
;
label define ML14Z   
     0 "No"
     1 "Yes"
;
label define ML15A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     8 "Don't know"
;
label define ML15B   
     7 "7+ days"
     8 "Don't know"
;
label define ML15C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML16A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     8 "Don't know"
;
label define ML16B   
     7 "7+ days"
     8 "Don't know"
;
label define ML16C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML17A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     8 "Don't know"
;
label define ML17B   
     7 "7+ days"
     8 "Don't know"
;
label define ML17C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML18A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     8 "Don't know"
;
label define ML18B   
     7 "7+ days"
     8 "Don't know"
;
label define ML18C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML19A   
     0 "No"
     1 "Yes"
;
label define ML19B   
     0 "No"
     1 "Yes"
;
label define ML19C   
     0 "No"
     1 "Yes"
;
label define ML19D   
     0 "No"
     1 "Yes"
;
label define ML19E   
     0 "No"
     1 "Yes"
;
label define ML19F   
     0 "No"
     1 "Yes"
;
label define ML19X   
     0 "No"
     1 "Yes"
;
label define ML19Y   
     0 "No"
     1 "Yes"
;
label define ML19Z   
     0 "No"
     1 "Yes"
;
label define ML20A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     8 "Don't know"
;
label define ML20B   
     7 "7+ days"
     8 "Don't know"
;
label define ML20C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML21A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML21B   
     7 "7+ days"
     8 "Don't know"
;
label define ML21C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML22A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML22B   
     7 "7+ days"
     8 "Don't know"
;
label define ML22C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML23A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     8 "Don't know"
;
label define ML23B   
     7 "7+ days"
     8 "Don't know"
;
label define ML23C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML24C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML25A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     8 "Don't know"
;
label define SDISTRICT
   101 "Jomoro"
   103 "Nzema East"
   104 "Ahanta West"
   105 "Sekondi Takoradi Metropolis"
   108 "Tarkwa Nsuaem Municipal"
   109 "Prestea/Huni Valley"
   110 "Wassa Amenfi East"
   112 "Aowin"
   114 "Sefwi Wiawso"
   115 "Sefwi Bibiani-Ahwiaso Bekwai"
   117 "Bia west"
   120 "Suaman"
   201 "Komenda-Edina-Egyafo-Abirem Municipal"
   202 "Cape Coast Metropolis"
   203 "Abura-Asebu-Kwamankese"
   204 "Mfantsiman"
   205 "Ajumako-Enyan-Essiam"
   206 "Gomoa West"
   207 "Effutu Municipal"
   208 "Gomoa East"
   209 "Ewutu Senya"
   210 "Agona East"
   211 "Agona West Municipal"
   212 "Asikuma-Odoben Brakwa"
   213 "Assin South"
   214 "Assin North Municipal"
   217 "Upper Denkyira West"
   219 "Ekumfi"
   220 "Awutu Senya East Municipal"
   301 "Ga South Municipal"
   302 "Ga West Municipal"
   303 "Ga East Municipal"
   304 "Accra Metropolis"
   306 "Ledzokuku/Krowor Municipal"
   307 "Ashaiman Municipal"
   308 "Tema Metropolis"
   310 "Ada East"
   311 "Ga Central Municipal"
   312 "La Dade Kotopon Municipal"
   313 "La Nkwantanang Madina Municipal"
   401 "South Tongu"
   402 "Keta Municapal"
   403 "Ketu South"
   405 "Akatsi"
   407 "Adaklu"
   408 "Ho Municipal"
   409 "South Dayi"
   411 "Hohoe Municipal"
   413 "Jasikan"
   414 "Kadjebi"
   415 "Krachi East"
   417 "Nkwanta South"
   419 "North Tongu"
   420 "Akatsi North"
   422 "Ho West"
   424 "North Dayi"
   501 "Birim South"
   502 "Birim Municipal"
   504 "Suhum Municipal"
   506 "Akwapem North"
   507 "New Juaben Municipal"
   509 "Lower Manya"
   510 "Asuogyaman"
   512 "Fanteakwa"
   513 "East Akim Municipal"
   514 "Kwaebibirem"
   516 "Birim North"
   517 "Atiwa"
   518 "Kwahu West Municipal"
   521 "Kwahu Afram Plains North"
   522 "Upper West Akyem"
   525 "Denkyembuor"
   601 "Atwima Mponua"
   603 "Amansie Central"
   605 "Obuasi Municipal"
   606 "Adansi North"
   608 "Bosome Freho"
   610 "Asante Akim Central Municipal"
   611 "Ejisu Juaben Municipal"
   614 "Kumasi Metropolis"
   615 "Atwima Nwabiagya"
   616 "Ahafo Ano South"
   619 "Afigya Kwabre"
   623 "Sekyere East"
   624 "Sekyere Afram Plains"
   628 "Asokore Mampong Municipal"
   702 "Asunafo North Municipal"
   704 "Dormaa Municipal"
   707 "Tano North"
   708 "Sunyani Municipal"
   710 "Berekum Municipal"
   712 "Jaman North"
   713 "Tain"
   715 "Techiman Municipal"
   716 "Nkoranza South"
   718 "Atebubu Amantin"
   720 "Pru"
   722 "Kintampo North Municipal"
   723 "Asutifi South"
   727 "Sene East"
   801 "Bole"
   804 "Gonja Central"
   805 "East Gonja"
   806 "Kpandai"
   808 "Nanumba North"
   810 "Yendi Municipal"
   811 "Tamale Metropolis"
   813 "Savelugu Nanton"
   816 "Saboba"
   818 "Bunkpurugu Yonyo"
   819 "Mamprusi East"
   820 "Mamprusi West"
   822 "Kumbumgu"
   823 "Sagnerigu Municipal"
   825 "Tatale"
   901 "Builsa North"
   902 "Kasena Nankana West"
   903 "Kasena Nankana East"
   904 "Bolgatanga Municipal"
   905 "Talensi"
   906 "Bongo"
   907 "Bawku West"
   908 "Garu Tempane"
   909 "Bawku Municipal"
   910 "Builsa South"
   912 "Binduri"
  1001 "Wa West"
  1002 "Wa Municipal"
  1003 "Wa East"
  1004 "Sissala East"
  1005 "Nadowli-Kaleo"
  1006 "Jirapa"
  1007 "Sissala West"
  1008 "Lambussie Karni"
  1009 "Lawra"
  1011 "Nandom"
;
label define S105    
     1 "Primary"
     2 "Middle"
     3 "JSS/JHS"
     4 "SSS/SHS"
     5 "Secondary"
     6 "Higher"
;
label define S105A   
     0 "No education"
     1 "Primary"
     2 "Middle/JSS/JHS"
     3 "Secondary/SSS/SHS or Higher"
;
label define S111    
     0 "No"
     1 "Yes"
;
label define S114    
     0 "No"
     1 "Yes"
;
label define S211    
     0 "None"
;
label define S501    
     0 "No"
     1 "Yes"
;
label define S502A   
     0 "No"
     1 "Yes"
;
label define S502B   
     0 "No"
     1 "Yes"
;
label define S502C   
     0 "No"
     1 "Yes"
;
label define S502D   
     0 "No"
     1 "Yes"
;
label define S502E   
     0 "No"
     1 "Yes"
;
label define S502F   
     0 "No"
     1 "Yes"
;
label define S502G   
     0 "No"
     1 "Yes"
;
label define S502H   
     0 "No"
     1 "Yes"
;
label define S502I   
     0 "No"
     1 "Yes"
;
label define S502J   
     0 "No"
     1 "Yes"
;
label define S502X   
     0 "No"
     1 "Yes"
;
label define S502Z   
     0 "No"
     1 "Yes"
;
label define S503A   
     0 "No"
     1 "Yes"
;
label define S503B   
     0 "No"
     1 "Yes"
;
label define S503C   
     0 "No"
     1 "Yes"
;
label define S503D   
     0 "No"
     1 "Yes"
;
label define S503E   
     0 "No"
     1 "Yes"
;
label define S503F   
     0 "No"
     1 "Yes"
;
label define S503G   
     0 "No"
     1 "Yes"
;
label define S503H   
     0 "No"
     1 "Yes"
;
label define S503I   
     0 "No"
     1 "Yes"
;
label define S503J   
     0 "No"
     1 "Yes"
;
label define S504A   
     0 "No"
     1 "Yes"
;
label define S504B   
     0 "No"
     1 "Yes"
;
label define S504C   
     0 "No"
     1 "Yes"
;
label define S504D   
     0 "No"
     1 "Yes"
;
label define S504E   
     0 "No"
     1 "Yes"
;
label define S504F   
     0 "No"
     1 "Yes"
;
label define S504G   
     0 "No"
     1 "Yes"
;
label define S504H   
     0 "No"
     1 "Yes"
;
label define S504X   
     0 "No"
     1 "Yes"
;
label define S504Z   
     0 "No"
     1 "Yes"
;
label define S505A   
     0 "No"
     1 "Yes, on TV"
     2 "Yes, on radio"
     3 "Yes, on TV and radio"
;
label define S505B   
     0 "No"
     1 "Yes, on TV"
     2 "Yes, on radio"
     3 "Yes, on TV and radio"
;
label define S505C   
     0 "No"
     1 "Yes, on TV"
     2 "Yes, on radio"
     3 "Yes, on TV and radio"
;
label define S505D   
     0 "No"
     1 "Yes, on TV"
     2 "Yes, on radio"
     3 "Yes, on TV and radio"
;
label define S506    
     0 "No"
     1 "Yes"
;
label define S507A   
     0 "No"
     1 "Yes"
;
label define S507B   
     0 "No"
     1 "Yes"
;
label define S507C   
     0 "No"
     1 "Yes"
;
label define S507D   
     0 "No"
     1 "Yes"
;
label define S507E   
     0 "No"
     1 "Yes"
;
label define S507X   
     0 "No"
     1 "Yes"
;
label define S507Z   
     0 "No"
     1 "Yes"
;
label define S508A   
     0 "No"
     1 "Yes"
;
label define S508B   
     0 "No"
     1 "Yes"
;
label define S508C   
     0 "No"
     1 "Yes"
;
label define S508D   
     0 "No"
     1 "Yes"
;
label define S508E   
     0 "No"
     1 "Yes"
;
label define S508F   
     0 "No"
     1 "Yes"
;
label define S508G   
     0 "No"
     1 "Yes"
;
label define S508H   
     0 "No"
     1 "Yes"
;
label define S508X   
     0 "No"
     1 "Yes"
;
label define S508Z   
     0 "No"
     1 "Yes"
;
label define S509    
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define S510    
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define S511    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define S512    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define S305BA  
     0 "No"
     1 "Yes"
;
label define S305BB  
     0 "No"
     1 "Yes"
;
label define S305BC  
     0 "No"
     1 "Yes"
;
label define S305BD  
     0 "No"
     1 "Yes"
;
label define S305BE  
     0 "No"
     1 "Yes"
;
label define S305BF  
     0 "No"
     1 "Yes"
;
label define S305BG  
     0 "No"
     1 "Yes"
;
label define S305BX  
     0 "No"
     1 "Yes"
;
label define S305BZ  
     0 "No"
     1 "Yes"
;
label define S403A   
     0 "No, never enrolled"
     1 "Yes, in 2017"
     2 "Yes, in 2018"
     3 "Yes, in 2017 and 2018"
;
label define S405A   
     0 "Negative"
     1 "Positive malaria"
     2 "Positive other illness"
     8 "Don't know/don't remember"
;
label define S407BA  
     0 "No"
     1 "Yes"
;
label define S407BB  
     0 "No"
     1 "Yes"
;
label define S407BC  
     0 "No"
     1 "Yes"
;
label define S407BD  
     0 "No"
     1 "Yes"
;
label define S407BE  
     0 "No"
     1 "Yes"
;
label define S407BF  
     0 "No"
     1 "Yes"
;
label define S407BG  
     0 "No"
     1 "Yes"
;
label define S407BH  
     0 "No"
     1 "Yes"
;
label define S407BI  
     0 "No"
     1 "Yes"
;
label define S407BX  
     0 "No"
     1 "Yes"
;
label define S412BA  
     0 "No"
     1 "Yes"
;
label define S412BB  
     0 "No"
     1 "Yes"
;
label define S412BC  
     0 "No"
     1 "Yes"
;
label define S412BD  
     0 "No"
     1 "Yes"
;
label define S412BE  
     0 "No"
     1 "Yes"
;
label define S412BF  
     0 "No"
     1 "Yes"
;
label define S412BG  
     0 "No"
     1 "Yes"
;
label define S412BH  
     0 "No"
     1 "Yes"
;
label define S412BI  
     0 "No"
     1 "Yes"
;
label define S412BJ  
     0 "No"
     1 "Yes"
;
label define S412BK  
     0 "No"
     1 "Yes"
;
label define S412BX  
     0 "No"
     1 "Yes"
;

#delimit cr
label values v013     V013    
label values v014     V014    
label values v015     V015    
label values v018     V018    
label values v019     V019    
label values v019a    V019A   
label values v020     V020    
label values v022     V022    
label values v023     V023    
label values v024     V024    
label values v025     V025    
label values v026     V026    
label values v034     V034    
label values v042     V042    
label values v044     V044    
label values v045a    V045A   
label values v045b    V045B   
label values v045c    V045C   
label values v046     V046    
label values v101     V101    
label values v102     V102    
label values v106     V106    
label values v107     V107    
label values v113     V113    
label values v115     V115    
label values v116     V116    
label values v119     V119    
label values v120     V120    
label values v121     V121    
label values v122     V122    
label values v123     V123    
label values v124     V124    
label values v125     V125    
label values v127     V127    
label values v128     V128    
label values v129     V129    
label values v130     V130    
label values v131     V131    
label values v133     V133    
label values v135     V135    
label values v139     V139    
label values v140     V140    
label values v149     V149    
label values v150     V150    
label values v151     V151    
label values v152     V152    
label values v153     V153    
label values v155     V155    
label values v160     V160    
label values v161     V161    
label values v190     V190    
label values v190a    V190A   
label values ml101    ML101   
label values v208     V208    
label values v209     V209    
label values v213     V213    
label values v220     V220    
label values v223     V223    
label values v237     V237    
label values v459     V459    
label values v460     V460    
label values v461     V461    
label values v468     V468    
label values v481     V481    
label values v481a    V481A   
label values v481b    V481B   
label values v481c    V481C   
label values v481d    V481D   
label values v481e    V481E   
label values v481f    V481F   
label values v481g    V481G   
label values v481h    V481H   
label values v481x    V481X   
label values b0       B0      
label values b4       B4      
label values b5       B5      
label values b9       B9      
label values b10      B10     
label values b15      B15     
label values b16      B16     
label values m2a      M2A     
label values m2b      M2B     
label values m2c      M2C     
label values m2d      M2D     
label values m2e      M2E     
label values m2f      M2F     
label values m2g      M2G     
label values m2h      M2H     
label values m2i      M2I     
label values m2j      M2J     
label values m2k      M2K     
label values m2l      M2L     
label values m2m      M2M     
label values m2n      M2N     
label values m13      M13     
label values m14      M14     
label values m49a     M49A    
label values m49b     M49B    
label values m49c     M49C    
label values m49d     M49D    
label values m49e     M49E    
label values m49f     M49F    
label values m49g     M49G    
label values m49x     M49X    
label values m49z     M49Z    
label values m49y     M49Y    
label values m57a     M57A    
label values m57b     M57B    
label values m57c     M57C    
label values m57d     M57D    
label values m57e     M57E    
label values m57f     M57F    
label values m57g     M57G    
label values m57h     M57H    
label values m57i     M57I    
label values m57j     M57J    
label values m57k     M57K    
label values m57l     M57L    
label values m57m     M57M    
label values m57n     M57N    
label values m57o     M57O    
label values m57p     M57P    
label values m57q     M57Q    
label values m57r     M57R    
label values m57s     M57S    
label values m57t     M57T    
label values m57u     M57U    
label values m57v     M57V    
label values m57x     M57X    
label values h22      H22     
label values h32a     H32A    
label values h32b     H32B    
label values h32c     H32C    
label values h32d     H32D    
label values h32e     H32E    
label values h32f     H32F    
label values h32g     H32G    
label values h32h     H32H    
label values h32i     H32I    
label values h32j     H32J    
label values h32k     H32K    
label values h32l     H32L    
label values h32m     H32M    
label values h32n     H32N    
label values h32o     H32O    
label values h32p     H32P    
label values h32q     H32Q    
label values h32r     H32R    
label values h32s     H32S    
label values h32t     H32T    
label values h32u     H32U    
label values h32v     H32V    
label values h32w     H32W    
label values h32x     H32X    
label values h32y     H32Y    
label values h32z     H32Z    
label values h46a     H46A    
label values h46b     H46B    
label values h47      H47     
label values hw16     HW16    
label values hw51     HW51    
label values hw52     HW52    
label values hw53     HW53    
label values hw55     HW55    
label values hw56     HW56    
label values hw57     HW57    
label values ml0      ML0     
label values ml1      ML1     
label values ml2      ML2     
label values ml11     ML11    
label values ml12     ML12    
label values ml13a    ML13A   
label values ml13b    ML13B   
label values ml13c    ML13C   
label values ml13d    ML13D   
label values ml13da   ML13DA  
label values ml13e    ML13E   
label values ml13aa   ML13AA  
label values ml13ab   ML13AB  
label values ml13f    ML13F   
label values ml13g    ML13G   
label values ml13h    ML13H   
label values ml13i    ML13I   
label values ml13j    ML13J   
label values ml13k    ML13K   
label values ml13l    ML13L   
label values ml13m    ML13M   
label values ml13n    ML13N   
label values ml13o    ML13O   
label values ml13p    ML13P   
label values ml13x    ML13X   
label values ml13y    ML13Y   
label values ml13z    ML13Z   
label values ml14a    ML14A   
label values ml14b    ML14B   
label values ml14y    ML14Y   
label values ml14z    ML14Z   
label values ml15a    ML15A   
label values ml15b    ML15B   
label values ml15c    ML15C   
label values ml16a    ML16A   
label values ml16b    ML16B   
label values ml16c    ML16C   
label values ml17a    ML17A   
label values ml17b    ML17B   
label values ml17c    ML17C   
label values ml18a    ML18A   
label values ml18b    ML18B   
label values ml18c    ML18C   
label values ml19a    ML19A   
label values ml19b    ML19B   
label values ml19c    ML19C   
label values ml19d    ML19D   
label values ml19e    ML19E   
label values ml19f    ML19F   
label values ml19x    ML19X   
label values ml19y    ML19Y   
label values ml19z    ML19Z   
label values ml20a    ML20A   
label values ml20b    ML20B   
label values ml20c    ML20C   
label values ml21a    ML21A   
label values ml21b    ML21B   
label values ml21c    ML21C   
label values ml22a    ML22A   
label values ml22b    ML22B   
label values ml22c    ML22C   
label values ml23a    ML23A   
label values ml23b    ML23B   
label values ml23c    ML23C   
label values ml24c    ML24C   
label values ml25a    ML25A   
label values sdistrict SDISTRICT
label values s105     S105    
label values s105a    S105A   
label values s111     S111    
label values s114     S114    
label values s211     S211    
label values s501     S501    
label values s502a    S502A   
label values s502b    S502B   
label values s502c    S502C   
label values s502d    S502D   
label values s502e    S502E   
label values s502f    S502F   
label values s502g    S502G   
label values s502h    S502H   
label values s502i    S502I   
label values s502j    S502J   
label values s502x    S502X   
label values s502z    S502Z   
label values s503a    S503A   
label values s503b    S503B   
label values s503c    S503C   
label values s503d    S503D   
label values s503e    S503E   
label values s503f    S503F   
label values s503g    S503G   
label values s503h    S503H   
label values s503i    S503I   
label values s503j    S503J   
label values s504a    S504A   
label values s504b    S504B   
label values s504c    S504C   
label values s504d    S504D   
label values s504e    S504E   
label values s504f    S504F   
label values s504g    S504G   
label values s504h    S504H   
label values s504x    S504X   
label values s504z    S504Z   
label values s505a    S505A   
label values s505b    S505B   
label values s505c    S505C   
label values s505d    S505D   
label values s506     S506    
label values s507a    S507A   
label values s507b    S507B   
label values s507c    S507C   
label values s507d    S507D   
label values s507e    S507E   
label values s507x    S507X   
label values s507z    S507Z   
label values s508a    S508A   
label values s508b    S508B   
label values s508c    S508C   
label values s508d    S508D   
label values s508e    S508E   
label values s508f    S508F   
label values s508g    S508G   
label values s508h    S508H   
label values s508x    S508X   
label values s508z    S508Z   
label values s509     S509    
label values s510     S510    
label values s511     S511    
label values s512     S512    
label values s305ba   S305BA  
label values s305bb   S305BB  
label values s305bc   S305BC  
label values s305bd   S305BD  
label values s305be   S305BE  
label values s305bf   S305BF  
label values s305bg   S305BG  
label values s305bx   S305BX  
label values s305bz   S305BZ  
label values s403a    S403A   
label values s405a    S405A   
label values s407ba   S407BA  
label values s407bb   S407BB  
label values s407bc   S407BC  
label values s407bd   S407BD  
label values s407be   S407BE  
label values s407bf   S407BF  
label values s407bg   S407BG  
label values s407bh   S407BH  
label values s407bi   S407BI  
label values s407bx   S407BX  
label values s412ba   S412BA  
label values s412bb   S412BB  
label values s412bc   S412BC  
label values s412bd   S412BD  
label values s412be   S412BE  
label values s412bf   S412BF  
label values s412bg   S412BG  
label values s412bh   S412BH  
label values s412bi   S412BI  
label values s412bj   S412BJ  
label values s412bk   S412BK  
label values s412bx   S412BX  
