infix using "C:\COUNTRIES\ET81\ETHR81FL.dct"

label variable hhid     "Case Identification"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv008a   "Date of interview Century Day Code (CDC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv011    "NA - Number of eligible men in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "NA - Household selected for male interview"
label variable hv028    "NA - Household weight for male subsample (6 decimals)"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv035    "Number of eligible children for height and weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "NA - Total adults measured"
label variable hv042    "NA - Household selected for hemoglobin"
label variable hv044    "NA - Household selected for Domestic Violence module"
label variable hv045a   "NA - Language of questionnaire"
label variable hv045b   "Language of interview"
label variable hv045c   "Native language of respondent"
label variable hv046    "Translator used"
label variable hv801    "Time interview started (hhmm - 24 hour clock)"
label variable hv802    "Time interview ended (hhmm - 24 hour clock)"
label variable hv803    "Length of interview in minutes"
label variable hv804    "Number of visits for biomarker"
label variable hv807d   "Day of biomarker visit"
label variable hv807m   "Month of biomarker visit"
label variable hv807y   "Year of biomarker visit"
label variable hv807c   "Date of biomarker (CMC)"
label variable hv807a   "Date of biomarker Century Day Code (CDC)"
label variable hv201    "Source of drinking water"
label variable hv202    "NA - Source of non-drinking water"
label variable hv201a   "NA - Water not available for at least a day last two weeks"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "NA - Has mosquito bed net for sleeping"
label variable hv228    "NA - Children under 5 slept under mosquito bed net last night"
label variable hv230a   "NA - Place where household members wash their hands"
label variable hv230b   "NA - Presence of water at hand washing place"
label variable hv232    "NA - Items present: Soap or detergent"
label variable hv232b   "NA - Items present: Ash, mud, sand"
label variable hv232c   "NA - Items present: CS"
label variable hv232d   "NA - Items present: CS"
label variable hv232e   "NA - Items present: CS"
label variable hv232y   "NA - Items present: None"
label variable hv234    "NA - Result of salt test for iodine (PPM)"
label variable hv234a   "NA - Result of salt test for iodine"
label variable hv235    "Location of source for water"
label variable hv236    "NA - Person fetching water"
label variable hv237    "NA - Anything done to water to make safe to drink"
label variable hv237a   "NA - Water usually treated by: boil"
label variable hv237b   "NA - Water usually treated by: add bleach/chlorine"
label variable hv237c   "NA - Water usually treated by: strain through a cloth"
label variable hv237d   "NA - Water usually treated by: use water filter"
label variable hv237e   "NA - Water usually treated by: solar disinfection"
label variable hv237f   "NA - Water usually treated by: let it stand and settle"
label variable hv237g   "NA - Water usually treated by: CS"
label variable hv237h   "NA - Water usually treated by: CS"
label variable hv237i   "NA - Water usually treated by: CS"
label variable hv237j   "NA - Water usually treated by: CS"
label variable hv237k   "NA - Water usually treated by: CS"
label variable hv237x   "NA - Water usually treated by: other"
label variable hv237z   "NA - Water usually treated by: don't know"
label variable hv238    "Number of households sharing toilet"
label variable hv238a   "Location of toilet facility"
label variable hv239    "NA - Food cooked on stove or open fire"
label variable hv240    "NA - Household has a chimney, hood or neither"
label variable hv241    "Food cooked in the house/ separate building/ outdoors"
label variable hv242    "Household has separate room used as kitchen"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "Has watch"
label variable hv243c   "Has animal-drawn cart"
label variable hv243d   "NA -Has boat with a motor"
label variable hv243e   "Has a computer"
label variable hv244    "Owns land usable for agriculture"
label variable hv245    "Hectares of agricultural land (1 decimal)"
label variable hv246    "Owns livestock, herds or farm animals"
label variable hv246a   "Other cattle"
label variable hv246b   "Owns cows/ bulls"
label variable hv246c   "Owns horses/ donkeys/ mules"
label variable hv246d   "Owns goats"
label variable hv246e   "Owns sheep"
label variable hv246f   "Owns chickens/poultry"
label variable hv246g   "Owns: Camels"
label variable hv246h   "Owns: Beehives"
label variable hv246i   "NA - Owns CS"
label variable hv246j   "NA - Owns CS"
label variable hv246k   "NA - Owns CS"
label variable hv247    "Has bank account"
label variable hv252    "NA - Frequency household members smoke inside the house"
label variable hv253    "NA - Has dwelling been sprayed against mosquitoes in last 12 months"
label variable hv253a   "NA - Dwelling sprayed by: government worker/program"
label variable hv253b   "NA - Dwelling sprayed by: private company"
label variable hv253c   "NA - Dwelling sprayed by: NGO"
label variable hv253d   "NA - Dwelling sprayed by: CS"
label variable hv253e   "NA - Dwelling sprayed by: CS"
label variable hv253f   "NA - Dwelling sprayed by: CS"
label variable hv253g   "NA - Dwelling sprayed by: CS"
label variable hv253h   "NA - Dwelling sprayed by: CS"
label variable hv253x   "NA - Dwelling sprayed by: other"
label variable hv253z   "NA - Dwelling sprayed by: don't know"
label variable hv270    "Wealth index combined"
label variable hv271    "Wealth index factor score combined (5 decimals)"
label variable hv270a   "Wealth index for urban/rural"
label variable hv271a   "Wealth index factor score for urban/rural (5 decimals)"
label variable hml1     "NA - Number of mosquito bed nets"
label variable hml1a    "NA - Number of mosquito bed nets with specific information"
label variable hml2     "NA - Number of children under mosquito bed net previous night"
label variable chl0     "NA - Number of de-jure children 5-14 for child labor module"
label variable sh121g   "Table"
label variable sh121h   "Chair"
label variable sh121i   "Bed with cotton/spring mattress"
label variable sh121j   "Electric mitad"
label variable sh121k   "Kerosene lamp/ preassure lamp"
label variable sh124    "Receiving cash of food from the safety Net Program"
label variable sh125    "Enrolling in a community based health insurance scheme"
label variable sh126    "Own this dwelling, occupy free of charge or rent from kebele, agency,indi."
label variable shintd   "Day of household interview (Ethiopia calendar)"
label variable shintm   "Month of household interview  (Ethiopia calendar)"
label variable sh122g   "Bajaj"
label variable hvidx_01 "Line number"
label variable hvidx_02 "Line number"
label variable hvidx_03 "Line number"
label variable hvidx_04 "Line number"
label variable hvidx_05 "Line number"
label variable hvidx_06 "Line number"
label variable hvidx_07 "Line number"
label variable hvidx_08 "Line number"
label variable hvidx_09 "Line number"
label variable hvidx_10 "Line number"
label variable hvidx_11 "Line number"
label variable hvidx_12 "Line number"
label variable hvidx_13 "Line number"
label variable hvidx_14 "Line number"
label variable hvidx_15 "Line number"
label variable hvidx_16 "Line number"
label variable hvidx_17 "Line number"
label variable hvidx_18 "Line number"
label variable hvidx_19 "Line number"
label variable hvidx_20 "Line number"
label variable hvidx_21 "Line number"
label variable hvidx_22 "Line number"
label variable hvidx_23 "Line number"
label variable hvidx_24 "Line number"
label variable hv101_01 "Relationship to head"
label variable hv101_02 "Relationship to head"
label variable hv101_03 "Relationship to head"
label variable hv101_04 "Relationship to head"
label variable hv101_05 "Relationship to head"
label variable hv101_06 "Relationship to head"
label variable hv101_07 "Relationship to head"
label variable hv101_08 "Relationship to head"
label variable hv101_09 "Relationship to head"
label variable hv101_10 "Relationship to head"
label variable hv101_11 "Relationship to head"
label variable hv101_12 "Relationship to head"
label variable hv101_13 "Relationship to head"
label variable hv101_14 "Relationship to head"
label variable hv101_15 "Relationship to head"
label variable hv101_16 "Relationship to head"
label variable hv101_17 "Relationship to head"
label variable hv101_18 "Relationship to head"
label variable hv101_19 "Relationship to head"
label variable hv101_20 "Relationship to head"
label variable hv101_21 "Relationship to head"
label variable hv101_22 "Relationship to head"
label variable hv101_23 "Relationship to head"
label variable hv101_24 "Relationship to head"
label variable hv102_01 "Usual resident"
label variable hv102_02 "Usual resident"
label variable hv102_03 "Usual resident"
label variable hv102_04 "Usual resident"
label variable hv102_05 "Usual resident"
label variable hv102_06 "Usual resident"
label variable hv102_07 "Usual resident"
label variable hv102_08 "Usual resident"
label variable hv102_09 "Usual resident"
label variable hv102_10 "Usual resident"
label variable hv102_11 "Usual resident"
label variable hv102_12 "Usual resident"
label variable hv102_13 "Usual resident"
label variable hv102_14 "Usual resident"
label variable hv102_15 "Usual resident"
label variable hv102_16 "Usual resident"
label variable hv102_17 "Usual resident"
label variable hv102_18 "Usual resident"
label variable hv102_19 "Usual resident"
label variable hv102_20 "Usual resident"
label variable hv102_21 "Usual resident"
label variable hv102_22 "Usual resident"
label variable hv102_23 "Usual resident"
label variable hv102_24 "Usual resident"
label variable hv103_01 "Slept last night"
label variable hv103_02 "Slept last night"
label variable hv103_03 "Slept last night"
label variable hv103_04 "Slept last night"
label variable hv103_05 "Slept last night"
label variable hv103_06 "Slept last night"
label variable hv103_07 "Slept last night"
label variable hv103_08 "Slept last night"
label variable hv103_09 "Slept last night"
label variable hv103_10 "Slept last night"
label variable hv103_11 "Slept last night"
label variable hv103_12 "Slept last night"
label variable hv103_13 "Slept last night"
label variable hv103_14 "Slept last night"
label variable hv103_15 "Slept last night"
label variable hv103_16 "Slept last night"
label variable hv103_17 "Slept last night"
label variable hv103_18 "Slept last night"
label variable hv103_19 "Slept last night"
label variable hv103_20 "Slept last night"
label variable hv103_21 "Slept last night"
label variable hv103_22 "Slept last night"
label variable hv103_23 "Slept last night"
label variable hv103_24 "Slept last night"
label variable hv104_01 "Sex of household member"
label variable hv104_02 "Sex of household member"
label variable hv104_03 "Sex of household member"
label variable hv104_04 "Sex of household member"
label variable hv104_05 "Sex of household member"
label variable hv104_06 "Sex of household member"
label variable hv104_07 "Sex of household member"
label variable hv104_08 "Sex of household member"
label variable hv104_09 "Sex of household member"
label variable hv104_10 "Sex of household member"
label variable hv104_11 "Sex of household member"
label variable hv104_12 "Sex of household member"
label variable hv104_13 "Sex of household member"
label variable hv104_14 "Sex of household member"
label variable hv104_15 "Sex of household member"
label variable hv104_16 "Sex of household member"
label variable hv104_17 "Sex of household member"
label variable hv104_18 "Sex of household member"
label variable hv104_19 "Sex of household member"
label variable hv104_20 "Sex of household member"
label variable hv104_21 "Sex of household member"
label variable hv104_22 "Sex of household member"
label variable hv104_23 "Sex of household member"
label variable hv104_24 "Sex of household member"
label variable hv105_01 "Age of household members"
label variable hv105_02 "Age of household members"
label variable hv105_03 "Age of household members"
label variable hv105_04 "Age of household members"
label variable hv105_05 "Age of household members"
label variable hv105_06 "Age of household members"
label variable hv105_07 "Age of household members"
label variable hv105_08 "Age of household members"
label variable hv105_09 "Age of household members"
label variable hv105_10 "Age of household members"
label variable hv105_11 "Age of household members"
label variable hv105_12 "Age of household members"
label variable hv105_13 "Age of household members"
label variable hv105_14 "Age of household members"
label variable hv105_15 "Age of household members"
label variable hv105_16 "Age of household members"
label variable hv105_17 "Age of household members"
label variable hv105_18 "Age of household members"
label variable hv105_19 "Age of household members"
label variable hv105_20 "Age of household members"
label variable hv105_21 "Age of household members"
label variable hv105_22 "Age of household members"
label variable hv105_23 "Age of household members"
label variable hv105_24 "Age of household members"
label variable hv106_01 "Highest educational level attained"
label variable hv106_02 "Highest educational level attained"
label variable hv106_03 "Highest educational level attained"
label variable hv106_04 "Highest educational level attained"
label variable hv106_05 "Highest educational level attained"
label variable hv106_06 "Highest educational level attained"
label variable hv106_07 "Highest educational level attained"
label variable hv106_08 "Highest educational level attained"
label variable hv106_09 "Highest educational level attained"
label variable hv106_10 "Highest educational level attained"
label variable hv106_11 "Highest educational level attained"
label variable hv106_12 "Highest educational level attained"
label variable hv106_13 "Highest educational level attained"
label variable hv106_14 "Highest educational level attained"
label variable hv106_15 "Highest educational level attained"
label variable hv106_16 "Highest educational level attained"
label variable hv106_17 "Highest educational level attained"
label variable hv106_18 "Highest educational level attained"
label variable hv106_19 "Highest educational level attained"
label variable hv106_20 "Highest educational level attained"
label variable hv106_21 "Highest educational level attained"
label variable hv106_22 "Highest educational level attained"
label variable hv106_23 "Highest educational level attained"
label variable hv106_24 "Highest educational level attained"
label variable hv107_01 "Highest year of education completed"
label variable hv107_02 "Highest year of education completed"
label variable hv107_03 "Highest year of education completed"
label variable hv107_04 "Highest year of education completed"
label variable hv107_05 "Highest year of education completed"
label variable hv107_06 "Highest year of education completed"
label variable hv107_07 "Highest year of education completed"
label variable hv107_08 "Highest year of education completed"
label variable hv107_09 "Highest year of education completed"
label variable hv107_10 "Highest year of education completed"
label variable hv107_11 "Highest year of education completed"
label variable hv107_12 "Highest year of education completed"
label variable hv107_13 "Highest year of education completed"
label variable hv107_14 "Highest year of education completed"
label variable hv107_15 "Highest year of education completed"
label variable hv107_16 "Highest year of education completed"
label variable hv107_17 "Highest year of education completed"
label variable hv107_18 "Highest year of education completed"
label variable hv107_19 "Highest year of education completed"
label variable hv107_20 "Highest year of education completed"
label variable hv107_21 "Highest year of education completed"
label variable hv107_22 "Highest year of education completed"
label variable hv107_23 "Highest year of education completed"
label variable hv107_24 "Highest year of education completed"
label variable hv108_01 "Education completed in single years"
label variable hv108_02 "Education completed in single years"
label variable hv108_03 "Education completed in single years"
label variable hv108_04 "Education completed in single years"
label variable hv108_05 "Education completed in single years"
label variable hv108_06 "Education completed in single years"
label variable hv108_07 "Education completed in single years"
label variable hv108_08 "Education completed in single years"
label variable hv108_09 "Education completed in single years"
label variable hv108_10 "Education completed in single years"
label variable hv108_11 "Education completed in single years"
label variable hv108_12 "Education completed in single years"
label variable hv108_13 "Education completed in single years"
label variable hv108_14 "Education completed in single years"
label variable hv108_15 "Education completed in single years"
label variable hv108_16 "Education completed in single years"
label variable hv108_17 "Education completed in single years"
label variable hv108_18 "Education completed in single years"
label variable hv108_19 "Education completed in single years"
label variable hv108_20 "Education completed in single years"
label variable hv108_21 "Education completed in single years"
label variable hv108_22 "Education completed in single years"
label variable hv108_23 "Education completed in single years"
label variable hv108_24 "Education completed in single years"
label variable hv109_01 "Educational attainment"
label variable hv109_02 "Educational attainment"
label variable hv109_03 "Educational attainment"
label variable hv109_04 "Educational attainment"
label variable hv109_05 "Educational attainment"
label variable hv109_06 "Educational attainment"
label variable hv109_07 "Educational attainment"
label variable hv109_08 "Educational attainment"
label variable hv109_09 "Educational attainment"
label variable hv109_10 "Educational attainment"
label variable hv109_11 "Educational attainment"
label variable hv109_12 "Educational attainment"
label variable hv109_13 "Educational attainment"
label variable hv109_14 "Educational attainment"
label variable hv109_15 "Educational attainment"
label variable hv109_16 "Educational attainment"
label variable hv109_17 "Educational attainment"
label variable hv109_18 "Educational attainment"
label variable hv109_19 "Educational attainment"
label variable hv109_20 "Educational attainment"
label variable hv109_21 "Educational attainment"
label variable hv109_22 "Educational attainment"
label variable hv109_23 "Educational attainment"
label variable hv109_24 "Educational attainment"
label variable hv110_01 "NA - Member still in school"
label variable hv110_02 "NA - Member still in school"
label variable hv110_03 "NA - Member still in school"
label variable hv110_04 "NA - Member still in school"
label variable hv110_05 "NA - Member still in school"
label variable hv110_06 "NA - Member still in school"
label variable hv110_07 "NA - Member still in school"
label variable hv110_08 "NA - Member still in school"
label variable hv110_09 "NA - Member still in school"
label variable hv110_10 "NA - Member still in school"
label variable hv110_11 "NA - Member still in school"
label variable hv110_12 "NA - Member still in school"
label variable hv110_13 "NA - Member still in school"
label variable hv110_14 "NA - Member still in school"
label variable hv110_15 "NA - Member still in school"
label variable hv110_16 "NA - Member still in school"
label variable hv110_17 "NA - Member still in school"
label variable hv110_18 "NA - Member still in school"
label variable hv110_19 "NA - Member still in school"
label variable hv110_20 "NA - Member still in school"
label variable hv110_21 "NA - Member still in school"
label variable hv110_22 "NA - Member still in school"
label variable hv110_23 "NA - Member still in school"
label variable hv110_24 "NA - Member still in school"
label variable hv111_01 "NA - Mother alive"
label variable hv111_02 "NA - Mother alive"
label variable hv111_03 "NA - Mother alive"
label variable hv111_04 "NA - Mother alive"
label variable hv111_05 "NA - Mother alive"
label variable hv111_06 "NA - Mother alive"
label variable hv111_07 "NA - Mother alive"
label variable hv111_08 "NA - Mother alive"
label variable hv111_09 "NA - Mother alive"
label variable hv111_10 "NA - Mother alive"
label variable hv111_11 "NA - Mother alive"
label variable hv111_12 "NA - Mother alive"
label variable hv111_13 "NA - Mother alive"
label variable hv111_14 "NA - Mother alive"
label variable hv111_15 "NA - Mother alive"
label variable hv111_16 "NA - Mother alive"
label variable hv111_17 "NA - Mother alive"
label variable hv111_18 "NA - Mother alive"
label variable hv111_19 "NA - Mother alive"
label variable hv111_20 "NA - Mother alive"
label variable hv111_21 "NA - Mother alive"
label variable hv111_22 "NA - Mother alive"
label variable hv111_23 "NA - Mother alive"
label variable hv111_24 "NA - Mother alive"
label variable hv112_01 "NA - Mother's line number"
label variable hv112_02 "NA - Mother's line number"
label variable hv112_03 "NA - Mother's line number"
label variable hv112_04 "NA - Mother's line number"
label variable hv112_05 "NA - Mother's line number"
label variable hv112_06 "NA - Mother's line number"
label variable hv112_07 "NA - Mother's line number"
label variable hv112_08 "NA - Mother's line number"
label variable hv112_09 "NA - Mother's line number"
label variable hv112_10 "NA - Mother's line number"
label variable hv112_11 "NA - Mother's line number"
label variable hv112_12 "NA - Mother's line number"
label variable hv112_13 "NA - Mother's line number"
label variable hv112_14 "NA - Mother's line number"
label variable hv112_15 "NA - Mother's line number"
label variable hv112_16 "NA - Mother's line number"
label variable hv112_17 "NA - Mother's line number"
label variable hv112_18 "NA - Mother's line number"
label variable hv112_19 "NA - Mother's line number"
label variable hv112_20 "NA - Mother's line number"
label variable hv112_21 "NA - Mother's line number"
label variable hv112_22 "NA - Mother's line number"
label variable hv112_23 "NA - Mother's line number"
label variable hv112_24 "NA - Mother's line number"
label variable hv113_01 "NA - Father alive"
label variable hv113_02 "NA - Father alive"
label variable hv113_03 "NA - Father alive"
label variable hv113_04 "NA - Father alive"
label variable hv113_05 "NA - Father alive"
label variable hv113_06 "NA - Father alive"
label variable hv113_07 "NA - Father alive"
label variable hv113_08 "NA - Father alive"
label variable hv113_09 "NA - Father alive"
label variable hv113_10 "NA - Father alive"
label variable hv113_11 "NA - Father alive"
label variable hv113_12 "NA - Father alive"
label variable hv113_13 "NA - Father alive"
label variable hv113_14 "NA - Father alive"
label variable hv113_15 "NA - Father alive"
label variable hv113_16 "NA - Father alive"
label variable hv113_17 "NA - Father alive"
label variable hv113_18 "NA - Father alive"
label variable hv113_19 "NA - Father alive"
label variable hv113_20 "NA - Father alive"
label variable hv113_21 "NA - Father alive"
label variable hv113_22 "NA - Father alive"
label variable hv113_23 "NA - Father alive"
label variable hv113_24 "NA - Father alive"
label variable hv114_01 "NA - Father's line number"
label variable hv114_02 "NA - Father's line number"
label variable hv114_03 "NA - Father's line number"
label variable hv114_04 "NA - Father's line number"
label variable hv114_05 "NA - Father's line number"
label variable hv114_06 "NA - Father's line number"
label variable hv114_07 "NA - Father's line number"
label variable hv114_08 "NA - Father's line number"
label variable hv114_09 "NA - Father's line number"
label variable hv114_10 "NA - Father's line number"
label variable hv114_11 "NA - Father's line number"
label variable hv114_12 "NA - Father's line number"
label variable hv114_13 "NA - Father's line number"
label variable hv114_14 "NA - Father's line number"
label variable hv114_15 "NA - Father's line number"
label variable hv114_16 "NA - Father's line number"
label variable hv114_17 "NA - Father's line number"
label variable hv114_18 "NA - Father's line number"
label variable hv114_19 "NA - Father's line number"
label variable hv114_20 "NA - Father's line number"
label variable hv114_21 "NA - Father's line number"
label variable hv114_22 "NA - Father's line number"
label variable hv114_23 "NA - Father's line number"
label variable hv114_24 "NA - Father's line number"
label variable hv115_01 "NA - Current marital status"
label variable hv115_02 "NA - Current marital status"
label variable hv115_03 "NA - Current marital status"
label variable hv115_04 "NA - Current marital status"
label variable hv115_05 "NA - Current marital status"
label variable hv115_06 "NA - Current marital status"
label variable hv115_07 "NA - Current marital status"
label variable hv115_08 "NA - Current marital status"
label variable hv115_09 "NA - Current marital status"
label variable hv115_10 "NA - Current marital status"
label variable hv115_11 "NA - Current marital status"
label variable hv115_12 "NA - Current marital status"
label variable hv115_13 "NA - Current marital status"
label variable hv115_14 "NA - Current marital status"
label variable hv115_15 "NA - Current marital status"
label variable hv115_16 "NA - Current marital status"
label variable hv115_17 "NA - Current marital status"
label variable hv115_18 "NA - Current marital status"
label variable hv115_19 "NA - Current marital status"
label variable hv115_20 "NA - Current marital status"
label variable hv115_21 "NA - Current marital status"
label variable hv115_22 "NA - Current marital status"
label variable hv115_23 "NA - Current marital status"
label variable hv115_24 "NA - Current marital status"
label variable hv116_01 "NA - Currently, formerly, never married"
label variable hv116_02 "NA - Currently, formerly, never married"
label variable hv116_03 "NA - Currently, formerly, never married"
label variable hv116_04 "NA - Currently, formerly, never married"
label variable hv116_05 "NA - Currently, formerly, never married"
label variable hv116_06 "NA - Currently, formerly, never married"
label variable hv116_07 "NA - Currently, formerly, never married"
label variable hv116_08 "NA - Currently, formerly, never married"
label variable hv116_09 "NA - Currently, formerly, never married"
label variable hv116_10 "NA - Currently, formerly, never married"
label variable hv116_11 "NA - Currently, formerly, never married"
label variable hv116_12 "NA - Currently, formerly, never married"
label variable hv116_13 "NA - Currently, formerly, never married"
label variable hv116_14 "NA - Currently, formerly, never married"
label variable hv116_15 "NA - Currently, formerly, never married"
label variable hv116_16 "NA - Currently, formerly, never married"
label variable hv116_17 "NA - Currently, formerly, never married"
label variable hv116_18 "NA - Currently, formerly, never married"
label variable hv116_19 "NA - Currently, formerly, never married"
label variable hv116_20 "NA - Currently, formerly, never married"
label variable hv116_21 "NA - Currently, formerly, never married"
label variable hv116_22 "NA - Currently, formerly, never married"
label variable hv116_23 "NA - Currently, formerly, never married"
label variable hv116_24 "NA - Currently, formerly, never married"
label variable hv117_01 "Eligibility for female interview"
label variable hv117_02 "Eligibility for female interview"
label variable hv117_03 "Eligibility for female interview"
label variable hv117_04 "Eligibility for female interview"
label variable hv117_05 "Eligibility for female interview"
label variable hv117_06 "Eligibility for female interview"
label variable hv117_07 "Eligibility for female interview"
label variable hv117_08 "Eligibility for female interview"
label variable hv117_09 "Eligibility for female interview"
label variable hv117_10 "Eligibility for female interview"
label variable hv117_11 "Eligibility for female interview"
label variable hv117_12 "Eligibility for female interview"
label variable hv117_13 "Eligibility for female interview"
label variable hv117_14 "Eligibility for female interview"
label variable hv117_15 "Eligibility for female interview"
label variable hv117_16 "Eligibility for female interview"
label variable hv117_17 "Eligibility for female interview"
label variable hv117_18 "Eligibility for female interview"
label variable hv117_19 "Eligibility for female interview"
label variable hv117_20 "Eligibility for female interview"
label variable hv117_21 "Eligibility for female interview"
label variable hv117_22 "Eligibility for female interview"
label variable hv117_23 "Eligibility for female interview"
label variable hv117_24 "Eligibility for female interview"
label variable hv118_01 "NA - Eligibility for male interview"
label variable hv118_02 "NA - Eligibility for male interview"
label variable hv118_03 "NA - Eligibility for male interview"
label variable hv118_04 "NA - Eligibility for male interview"
label variable hv118_05 "NA - Eligibility for male interview"
label variable hv118_06 "NA - Eligibility for male interview"
label variable hv118_07 "NA - Eligibility for male interview"
label variable hv118_08 "NA - Eligibility for male interview"
label variable hv118_09 "NA - Eligibility for male interview"
label variable hv118_10 "NA - Eligibility for male interview"
label variable hv118_11 "NA - Eligibility for male interview"
label variable hv118_12 "NA - Eligibility for male interview"
label variable hv118_13 "NA - Eligibility for male interview"
label variable hv118_14 "NA - Eligibility for male interview"
label variable hv118_15 "NA - Eligibility for male interview"
label variable hv118_16 "NA - Eligibility for male interview"
label variable hv118_17 "NA - Eligibility for male interview"
label variable hv118_18 "NA - Eligibility for male interview"
label variable hv118_19 "NA - Eligibility for male interview"
label variable hv118_20 "NA - Eligibility for male interview"
label variable hv118_21 "NA - Eligibility for male interview"
label variable hv118_22 "NA - Eligibility for male interview"
label variable hv118_23 "NA - Eligibility for male interview"
label variable hv118_24 "NA - Eligibility for male interview"
label variable hv120_01 "Children eligibility for height/weight and hemoglobin"
label variable hv120_02 "Children eligibility for height/weight and hemoglobin"
label variable hv120_03 "Children eligibility for height/weight and hemoglobin"
label variable hv120_04 "Children eligibility for height/weight and hemoglobin"
label variable hv120_05 "Children eligibility for height/weight and hemoglobin"
label variable hv120_06 "Children eligibility for height/weight and hemoglobin"
label variable hv120_07 "Children eligibility for height/weight and hemoglobin"
label variable hv120_08 "Children eligibility for height/weight and hemoglobin"
label variable hv120_09 "Children eligibility for height/weight and hemoglobin"
label variable hv120_10 "Children eligibility for height/weight and hemoglobin"
label variable hv120_11 "Children eligibility for height/weight and hemoglobin"
label variable hv120_12 "Children eligibility for height/weight and hemoglobin"
label variable hv120_13 "Children eligibility for height/weight and hemoglobin"
label variable hv120_14 "Children eligibility for height/weight and hemoglobin"
label variable hv120_15 "Children eligibility for height/weight and hemoglobin"
label variable hv120_16 "Children eligibility for height/weight and hemoglobin"
label variable hv120_17 "Children eligibility for height/weight and hemoglobin"
label variable hv120_18 "Children eligibility for height/weight and hemoglobin"
label variable hv120_19 "Children eligibility for height/weight and hemoglobin"
label variable hv120_20 "Children eligibility for height/weight and hemoglobin"
label variable hv120_21 "Children eligibility for height/weight and hemoglobin"
label variable hv120_22 "Children eligibility for height/weight and hemoglobin"
label variable hv120_23 "Children eligibility for height/weight and hemoglobin"
label variable hv120_24 "Children eligibility for height/weight and hemoglobin"
label variable hv121_01 "Member attended school during current school year"
label variable hv121_02 "Member attended school during current school year"
label variable hv121_03 "Member attended school during current school year"
label variable hv121_04 "Member attended school during current school year"
label variable hv121_05 "Member attended school during current school year"
label variable hv121_06 "Member attended school during current school year"
label variable hv121_07 "Member attended school during current school year"
label variable hv121_08 "Member attended school during current school year"
label variable hv121_09 "Member attended school during current school year"
label variable hv121_10 "Member attended school during current school year"
label variable hv121_11 "Member attended school during current school year"
label variable hv121_12 "Member attended school during current school year"
label variable hv121_13 "Member attended school during current school year"
label variable hv121_14 "Member attended school during current school year"
label variable hv121_15 "Member attended school during current school year"
label variable hv121_16 "Member attended school during current school year"
label variable hv121_17 "Member attended school during current school year"
label variable hv121_18 "Member attended school during current school year"
label variable hv121_19 "Member attended school during current school year"
label variable hv121_20 "Member attended school during current school year"
label variable hv121_21 "Member attended school during current school year"
label variable hv121_22 "Member attended school during current school year"
label variable hv121_23 "Member attended school during current school year"
label variable hv121_24 "Member attended school during current school year"
label variable hv122_01 "Educational level during current school year"
label variable hv122_02 "Educational level during current school year"
label variable hv122_03 "Educational level during current school year"
label variable hv122_04 "Educational level during current school year"
label variable hv122_05 "Educational level during current school year"
label variable hv122_06 "Educational level during current school year"
label variable hv122_07 "Educational level during current school year"
label variable hv122_08 "Educational level during current school year"
label variable hv122_09 "Educational level during current school year"
label variable hv122_10 "Educational level during current school year"
label variable hv122_11 "Educational level during current school year"
label variable hv122_12 "Educational level during current school year"
label variable hv122_13 "Educational level during current school year"
label variable hv122_14 "Educational level during current school year"
label variable hv122_15 "Educational level during current school year"
label variable hv122_16 "Educational level during current school year"
label variable hv122_17 "Educational level during current school year"
label variable hv122_18 "Educational level during current school year"
label variable hv122_19 "Educational level during current school year"
label variable hv122_20 "Educational level during current school year"
label variable hv122_21 "Educational level during current school year"
label variable hv122_22 "Educational level during current school year"
label variable hv122_23 "Educational level during current school year"
label variable hv122_24 "Educational level during current school year"
label variable hv123_01 "Grade of education during current school year"
label variable hv123_02 "Grade of education during current school year"
label variable hv123_03 "Grade of education during current school year"
label variable hv123_04 "Grade of education during current school year"
label variable hv123_05 "Grade of education during current school year"
label variable hv123_06 "Grade of education during current school year"
label variable hv123_07 "Grade of education during current school year"
label variable hv123_08 "Grade of education during current school year"
label variable hv123_09 "Grade of education during current school year"
label variable hv123_10 "Grade of education during current school year"
label variable hv123_11 "Grade of education during current school year"
label variable hv123_12 "Grade of education during current school year"
label variable hv123_13 "Grade of education during current school year"
label variable hv123_14 "Grade of education during current school year"
label variable hv123_15 "Grade of education during current school year"
label variable hv123_16 "Grade of education during current school year"
label variable hv123_17 "Grade of education during current school year"
label variable hv123_18 "Grade of education during current school year"
label variable hv123_19 "Grade of education during current school year"
label variable hv123_20 "Grade of education during current school year"
label variable hv123_21 "Grade of education during current school year"
label variable hv123_22 "Grade of education during current school year"
label variable hv123_23 "Grade of education during current school year"
label variable hv123_24 "Grade of education during current school year"
label variable hv124_01 "Education in single years - current school year"
label variable hv124_02 "Education in single years - current school year"
label variable hv124_03 "Education in single years - current school year"
label variable hv124_04 "Education in single years - current school year"
label variable hv124_05 "Education in single years - current school year"
label variable hv124_06 "Education in single years - current school year"
label variable hv124_07 "Education in single years - current school year"
label variable hv124_08 "Education in single years - current school year"
label variable hv124_09 "Education in single years - current school year"
label variable hv124_10 "Education in single years - current school year"
label variable hv124_11 "Education in single years - current school year"
label variable hv124_12 "Education in single years - current school year"
label variable hv124_13 "Education in single years - current school year"
label variable hv124_14 "Education in single years - current school year"
label variable hv124_15 "Education in single years - current school year"
label variable hv124_16 "Education in single years - current school year"
label variable hv124_17 "Education in single years - current school year"
label variable hv124_18 "Education in single years - current school year"
label variable hv124_19 "Education in single years - current school year"
label variable hv124_20 "Education in single years - current school year"
label variable hv124_21 "Education in single years - current school year"
label variable hv124_22 "Education in single years - current school year"
label variable hv124_23 "Education in single years - current school year"
label variable hv124_24 "Education in single years - current school year"
label variable hv125_01 "NA - Member attended school during previous school year"
label variable hv125_02 "NA - Member attended school during previous school year"
label variable hv125_03 "NA - Member attended school during previous school year"
label variable hv125_04 "NA - Member attended school during previous school year"
label variable hv125_05 "NA - Member attended school during previous school year"
label variable hv125_06 "NA - Member attended school during previous school year"
label variable hv125_07 "NA - Member attended school during previous school year"
label variable hv125_08 "NA - Member attended school during previous school year"
label variable hv125_09 "NA - Member attended school during previous school year"
label variable hv125_10 "NA - Member attended school during previous school year"
label variable hv125_11 "NA - Member attended school during previous school year"
label variable hv125_12 "NA - Member attended school during previous school year"
label variable hv125_13 "NA - Member attended school during previous school year"
label variable hv125_14 "NA - Member attended school during previous school year"
label variable hv125_15 "NA - Member attended school during previous school year"
label variable hv125_16 "NA - Member attended school during previous school year"
label variable hv125_17 "NA - Member attended school during previous school year"
label variable hv125_18 "NA - Member attended school during previous school year"
label variable hv125_19 "NA - Member attended school during previous school year"
label variable hv125_20 "NA - Member attended school during previous school year"
label variable hv125_21 "NA - Member attended school during previous school year"
label variable hv125_22 "NA - Member attended school during previous school year"
label variable hv125_23 "NA - Member attended school during previous school year"
label variable hv125_24 "NA - Member attended school during previous school year"
label variable hv126_01 "NA - Educational level during previous school year"
label variable hv126_02 "NA - Educational level during previous school year"
label variable hv126_03 "NA - Educational level during previous school year"
label variable hv126_04 "NA - Educational level during previous school year"
label variable hv126_05 "NA - Educational level during previous school year"
label variable hv126_06 "NA - Educational level during previous school year"
label variable hv126_07 "NA - Educational level during previous school year"
label variable hv126_08 "NA - Educational level during previous school year"
label variable hv126_09 "NA - Educational level during previous school year"
label variable hv126_10 "NA - Educational level during previous school year"
label variable hv126_11 "NA - Educational level during previous school year"
label variable hv126_12 "NA - Educational level during previous school year"
label variable hv126_13 "NA - Educational level during previous school year"
label variable hv126_14 "NA - Educational level during previous school year"
label variable hv126_15 "NA - Educational level during previous school year"
label variable hv126_16 "NA - Educational level during previous school year"
label variable hv126_17 "NA - Educational level during previous school year"
label variable hv126_18 "NA - Educational level during previous school year"
label variable hv126_19 "NA - Educational level during previous school year"
label variable hv126_20 "NA - Educational level during previous school year"
label variable hv126_21 "NA - Educational level during previous school year"
label variable hv126_22 "NA - Educational level during previous school year"
label variable hv126_23 "NA - Educational level during previous school year"
label variable hv126_24 "NA - Educational level during previous school year"
label variable hv127_01 "NA - Grade of education during previous school year"
label variable hv127_02 "NA - Grade of education during previous school year"
label variable hv127_03 "NA - Grade of education during previous school year"
label variable hv127_04 "NA - Grade of education during previous school year"
label variable hv127_05 "NA - Grade of education during previous school year"
label variable hv127_06 "NA - Grade of education during previous school year"
label variable hv127_07 "NA - Grade of education during previous school year"
label variable hv127_08 "NA - Grade of education during previous school year"
label variable hv127_09 "NA - Grade of education during previous school year"
label variable hv127_10 "NA - Grade of education during previous school year"
label variable hv127_11 "NA - Grade of education during previous school year"
label variable hv127_12 "NA - Grade of education during previous school year"
label variable hv127_13 "NA - Grade of education during previous school year"
label variable hv127_14 "NA - Grade of education during previous school year"
label variable hv127_15 "NA - Grade of education during previous school year"
label variable hv127_16 "NA - Grade of education during previous school year"
label variable hv127_17 "NA - Grade of education during previous school year"
label variable hv127_18 "NA - Grade of education during previous school year"
label variable hv127_19 "NA - Grade of education during previous school year"
label variable hv127_20 "NA - Grade of education during previous school year"
label variable hv127_21 "NA - Grade of education during previous school year"
label variable hv127_22 "NA - Grade of education during previous school year"
label variable hv127_23 "NA - Grade of education during previous school year"
label variable hv127_24 "NA - Grade of education during previous school year"
label variable hv128_01 "NA - Education in single years - previous school year"
label variable hv128_02 "NA - Education in single years - previous school year"
label variable hv128_03 "NA - Education in single years - previous school year"
label variable hv128_04 "NA - Education in single years - previous school year"
label variable hv128_05 "NA - Education in single years - previous school year"
label variable hv128_06 "NA - Education in single years - previous school year"
label variable hv128_07 "NA - Education in single years - previous school year"
label variable hv128_08 "NA - Education in single years - previous school year"
label variable hv128_09 "NA - Education in single years - previous school year"
label variable hv128_10 "NA - Education in single years - previous school year"
label variable hv128_11 "NA - Education in single years - previous school year"
label variable hv128_12 "NA - Education in single years - previous school year"
label variable hv128_13 "NA - Education in single years - previous school year"
label variable hv128_14 "NA - Education in single years - previous school year"
label variable hv128_15 "NA - Education in single years - previous school year"
label variable hv128_16 "NA - Education in single years - previous school year"
label variable hv128_17 "NA - Education in single years - previous school year"
label variable hv128_18 "NA - Education in single years - previous school year"
label variable hv128_19 "NA - Education in single years - previous school year"
label variable hv128_20 "NA - Education in single years - previous school year"
label variable hv128_21 "NA - Education in single years - previous school year"
label variable hv128_22 "NA - Education in single years - previous school year"
label variable hv128_23 "NA - Education in single years - previous school year"
label variable hv128_24 "NA - Education in single years - previous school year"
label variable hv129_01 "NA - School attendance status"
label variable hv129_02 "NA - School attendance status"
label variable hv129_03 "NA - School attendance status"
label variable hv129_04 "NA - School attendance status"
label variable hv129_05 "NA - School attendance status"
label variable hv129_06 "NA - School attendance status"
label variable hv129_07 "NA - School attendance status"
label variable hv129_08 "NA - School attendance status"
label variable hv129_09 "NA - School attendance status"
label variable hv129_10 "NA - School attendance status"
label variable hv129_11 "NA - School attendance status"
label variable hv129_12 "NA - School attendance status"
label variable hv129_13 "NA - School attendance status"
label variable hv129_14 "NA - School attendance status"
label variable hv129_15 "NA - School attendance status"
label variable hv129_16 "NA - School attendance status"
label variable hv129_17 "NA - School attendance status"
label variable hv129_18 "NA - School attendance status"
label variable hv129_19 "NA - School attendance status"
label variable hv129_20 "NA - School attendance status"
label variable hv129_21 "NA - School attendance status"
label variable hv129_22 "NA - School attendance status"
label variable hv129_23 "NA - School attendance status"
label variable hv129_24 "NA - School attendance status"
label variable hv140_01 "NA - Member has a birth certificate"
label variable hv140_02 "NA - Member has a birth certificate"
label variable hv140_03 "NA - Member has a birth certificate"
label variable hv140_04 "NA - Member has a birth certificate"
label variable hv140_05 "NA - Member has a birth certificate"
label variable hv140_06 "NA - Member has a birth certificate"
label variable hv140_07 "NA - Member has a birth certificate"
label variable hv140_08 "NA - Member has a birth certificate"
label variable hv140_09 "NA - Member has a birth certificate"
label variable hv140_10 "NA - Member has a birth certificate"
label variable hv140_11 "NA - Member has a birth certificate"
label variable hv140_12 "NA - Member has a birth certificate"
label variable hv140_13 "NA - Member has a birth certificate"
label variable hv140_14 "NA - Member has a birth certificate"
label variable hv140_15 "NA - Member has a birth certificate"
label variable hv140_16 "NA - Member has a birth certificate"
label variable hv140_17 "NA - Member has a birth certificate"
label variable hv140_18 "NA - Member has a birth certificate"
label variable hv140_19 "NA - Member has a birth certificate"
label variable hv140_20 "NA - Member has a birth certificate"
label variable hv140_21 "NA - Member has a birth certificate"
label variable hv140_22 "NA - Member has a birth certificate"
label variable hv140_23 "NA - Member has a birth certificate"
label variable hv140_24 "NA - Member has a birth certificate"
label variable idxh4_01 "Index to Household Schedule"
label variable idxh4_02 "Index to Household Schedule"
label variable idxh4_03 "Index to Household Schedule"
label variable idxh4_04 "Index to Household Schedule"
label variable idxh4_05 "Index to Household Schedule"
label variable idxh4_06 "Index to Household Schedule"
label variable idxh4_07 "Index to Household Schedule"
label variable idxh4_08 "Index to Household Schedule"
label variable idxh4_09 "Index to Household Schedule"
label variable idxh4_10 "Index to Household Schedule"
label variable idxh4_11 "Index to Household Schedule"
label variable idxh4_12 "Index to Household Schedule"
label variable idxh4_13 "Index to Household Schedule"
label variable idxh4_14 "Index to Household Schedule"
label variable idxh4_15 "Index to Household Schedule"
label variable idxh4_16 "Index to Household Schedule"
label variable idxh4_17 "Index to Household Schedule"
label variable idxh4_18 "Index to Household Schedule"
label variable idxh4_19 "Index to Household Schedule"
label variable idxh4_20 "Index to Household Schedule"
label variable idxh4_21 "Index to Household Schedule"
label variable idxh4_22 "Index to Household Schedule"
label variable idxh4_23 "Index to Household Schedule"
label variable idxh4_24 "Index to Household Schedule"
label variable sh16_01  "Ever attended school"
label variable sh16_02  "Ever attended school"
label variable sh16_03  "Ever attended school"
label variable sh16_04  "Ever attended school"
label variable sh16_05  "Ever attended school"
label variable sh16_06  "Ever attended school"
label variable sh16_07  "Ever attended school"
label variable sh16_08  "Ever attended school"
label variable sh16_09  "Ever attended school"
label variable sh16_10  "Ever attended school"
label variable sh16_11  "Ever attended school"
label variable sh16_12  "Ever attended school"
label variable sh16_13  "Ever attended school"
label variable sh16_14  "Ever attended school"
label variable sh16_15  "Ever attended school"
label variable sh16_16  "Ever attended school"
label variable sh16_17  "Ever attended school"
label variable sh16_18  "Ever attended school"
label variable sh16_19  "Ever attended school"
label variable sh16_20  "Ever attended school"
label variable sh16_21  "Ever attended school"
label variable sh16_22  "Ever attended school"
label variable sh16_23  "Ever attended school"
label variable sh16_24  "Ever attended school"
label variable sh17a_01 "Level of education attended"
label variable sh17a_02 "Level of education attended"
label variable sh17a_03 "Level of education attended"
label variable sh17a_04 "Level of education attended"
label variable sh17a_05 "Level of education attended"
label variable sh17a_06 "Level of education attended"
label variable sh17a_07 "Level of education attended"
label variable sh17a_08 "Level of education attended"
label variable sh17a_09 "Level of education attended"
label variable sh17a_10 "Level of education attended"
label variable sh17a_11 "Level of education attended"
label variable sh17a_12 "Level of education attended"
label variable sh17a_13 "Level of education attended"
label variable sh17a_14 "Level of education attended"
label variable sh17a_15 "Level of education attended"
label variable sh17a_16 "Level of education attended"
label variable sh17a_17 "Level of education attended"
label variable sh17a_18 "Level of education attended"
label variable sh17a_19 "Level of education attended"
label variable sh17a_20 "Level of education attended"
label variable sh17a_21 "Level of education attended"
label variable sh17a_22 "Level of education attended"
label variable sh17a_23 "Level of education attended"
label variable sh17a_24 "Level of education attended"
label variable sh17b_01 "Highest grade completed"
label variable sh17b_02 "Highest grade completed"
label variable sh17b_03 "Highest grade completed"
label variable sh17b_04 "Highest grade completed"
label variable sh17b_05 "Highest grade completed"
label variable sh17b_06 "Highest grade completed"
label variable sh17b_07 "Highest grade completed"
label variable sh17b_08 "Highest grade completed"
label variable sh17b_09 "Highest grade completed"
label variable sh17b_10 "Highest grade completed"
label variable sh17b_11 "Highest grade completed"
label variable sh17b_12 "Highest grade completed"
label variable sh17b_13 "Highest grade completed"
label variable sh17b_14 "Highest grade completed"
label variable sh17b_15 "Highest grade completed"
label variable sh17b_16 "Highest grade completed"
label variable sh17b_17 "Highest grade completed"
label variable sh17b_18 "Highest grade completed"
label variable sh17b_19 "Highest grade completed"
label variable sh17b_20 "Highest grade completed"
label variable sh17b_21 "Highest grade completed"
label variable sh17b_22 "Highest grade completed"
label variable sh17b_23 "Highest grade completed"
label variable sh17b_24 "Highest grade completed"
label variable sh18_01  "Attend school current year"
label variable sh18_02  "Attend school current year"
label variable sh18_03  "Attend school current year"
label variable sh18_04  "Attend school current year"
label variable sh18_05  "Attend school current year"
label variable sh18_06  "Attend school current year"
label variable sh18_07  "Attend school current year"
label variable sh18_08  "Attend school current year"
label variable sh18_09  "Attend school current year"
label variable sh18_10  "Attend school current year"
label variable sh18_11  "Attend school current year"
label variable sh18_12  "Attend school current year"
label variable sh18_13  "Attend school current year"
label variable sh18_14  "Attend school current year"
label variable sh18_15  "Attend school current year"
label variable sh18_16  "Attend school current year"
label variable sh18_17  "Attend school current year"
label variable sh18_18  "Attend school current year"
label variable sh18_19  "Attend school current year"
label variable sh18_20  "Attend school current year"
label variable sh18_21  "Attend school current year"
label variable sh18_22  "Attend school current year"
label variable sh18_23  "Attend school current year"
label variable sh18_24  "Attend school current year"
label variable sh19a_01 "Level of education attending"
label variable sh19a_02 "Level of education attending"
label variable sh19a_03 "Level of education attending"
label variable sh19a_04 "Level of education attending"
label variable sh19a_05 "Level of education attending"
label variable sh19a_06 "Level of education attending"
label variable sh19a_07 "Level of education attending"
label variable sh19a_08 "Level of education attending"
label variable sh19a_09 "Level of education attending"
label variable sh19a_10 "Level of education attending"
label variable sh19a_11 "Level of education attending"
label variable sh19a_12 "Level of education attending"
label variable sh19a_13 "Level of education attending"
label variable sh19a_14 "Level of education attending"
label variable sh19a_15 "Level of education attending"
label variable sh19a_16 "Level of education attending"
label variable sh19a_17 "Level of education attending"
label variable sh19a_18 "Level of education attending"
label variable sh19a_19 "Level of education attending"
label variable sh19a_20 "Level of education attending"
label variable sh19a_21 "Level of education attending"
label variable sh19a_22 "Level of education attending"
label variable sh19a_23 "Level of education attending"
label variable sh19a_24 "Level of education attending"
label variable sh19b_01 "Grade attending"
label variable sh19b_02 "Grade attending"
label variable sh19b_03 "Grade attending"
label variable sh19b_04 "Grade attending"
label variable sh19b_05 "Grade attending"
label variable sh19b_06 "Grade attending"
label variable sh19b_07 "Grade attending"
label variable sh19b_08 "Grade attending"
label variable sh19b_09 "Grade attending"
label variable sh19b_10 "Grade attending"
label variable sh19b_11 "Grade attending"
label variable sh19b_12 "Grade attending"
label variable sh19b_13 "Grade attending"
label variable sh19b_14 "Grade attending"
label variable sh19b_15 "Grade attending"
label variable sh19b_16 "Grade attending"
label variable sh19b_17 "Grade attending"
label variable sh19b_18 "Grade attending"
label variable sh19b_19 "Grade attending"
label variable sh19b_20 "Grade attending"
label variable sh19b_21 "Grade attending"
label variable sh19b_22 "Grade attending"
label variable sh19b_23 "Grade attending"
label variable sh19b_24 "Grade attending"
label variable ha0_1    "NA - Index to Household Schedule"
label variable ha0_2    "NA - Index to Household Schedule"
label variable ha1_1    "NA - Woman's age in years"
label variable ha1_2    "NA - Woman's age in years"
label variable ha2_1    "NA - Woman's weight in kilograms (1 decimal)"
label variable ha2_2    "NA - Woman's weight in kilograms (1 decimal)"
label variable ha3_1    "NA - Woman's height in centimeters (1 decimal)"
label variable ha3_2    "NA - Woman's height in centimeters (1 decimal)"
label variable ha4_1    "NA - Height/Age percentile"
label variable ha4_2    "NA - Height/Age percentile"
label variable ha5_1    "NA - Height/Age standard deviation"
label variable ha5_2    "NA - Height/Age standard deviation"
label variable ha6_1    "NA - Height/Age percent ref. median"
label variable ha6_2    "NA - Height/Age percent ref. median"
label variable ha11_1   "NA - Weight/Height standard deviation (DHS)"
label variable ha11_2   "NA - Weight/Height standard deviation (DHS)"
label variable ha12_1   "NA - Weight/Height percent ref. median (DHS)"
label variable ha12_2   "NA - Weight/Height percent ref. median (DHS)"
label variable ha12a_1  "NA - Weight/Height percent ref. median (Fog)"
label variable ha12a_2  "NA - Weight/Height percent ref. median (Fog)"
label variable ha12b_1  "NA - Weight/Height percent ref. median (WHO)"
label variable ha12b_2  "NA - Weight/Height percent ref. median (WHO)"
label variable ha13_1   "NA - Result of measurement - height/weight"
label variable ha13_2   "NA - Result of measurement - height/weight"
label variable ha21_1   "NA - Fieldworker measurer code"
label variable ha21_2   "NA - Fieldworker measurer code"
label variable ha32_1   "NA - Date of birth (CMC)"
label variable ha32_2   "NA - Date of birth (CMC)"
label variable ha33_1   "NA - Completeness of HA32 information"
label variable ha33_2   "NA - Completeness of HA32 information"
label variable ha35_1   "NA - Smoking (cigarettes in last 24 hours)"
label variable ha35_2   "NA - Smoking (cigarettes in last 24 hours)"
label variable ha40_1   "NA - Body Mass Index"
label variable ha40_2   "NA - Body Mass Index"
label variable ha41_1   "NA - Rohrer's index"
label variable ha41_2   "NA - Rohrer's index"
label variable ha50_1   "NA - Under age 18"
label variable ha50_2   "NA - Under age 18"
label variable ha51_1   "NA - Line number of parent/caretaker"
label variable ha51_2   "NA - Line number of parent/caretaker"
label variable ha52_1   "NA - Read consent statement - hemoglobin"
label variable ha52_2   "NA - Read consent statement - hemoglobin"
label variable ha53_1   "NA - Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_2   "NA - Hemoglobin level (g/dl - 1 decimal)"
label variable ha54_1   "NA - Currently pregnant"
label variable ha54_2   "NA - Currently pregnant"
label variable ha55_1   "NA - Result of measurement - hemoglobin"
label variable ha55_2   "NA - Result of measurement - hemoglobin"
label variable ha56_1   "NA - Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_2   "NA - Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha57_1   "NA - Anemia level"
label variable ha57_2   "NA - Anemia level"
label variable ha58_1   "NA - Agrees to referral - anemia"
label variable ha58_2   "NA - Agrees to referral - anemia"
label variable ha60_1   "NA - Marital status"
label variable ha60_2   "NA - Marital status"
label variable ha61_1   "NA - Read consent statement - HIV"
label variable ha61_2   "NA - Read consent statement - HIV"
label variable ha62_1   "NA - Bar code for HIV blood sample"
label variable ha62_2   "NA - Bar code for HIV blood sample"
label variable ha63_1   "NA - Result of measurement - HIV"
label variable ha63_2   "NA - Result of measurement - HIV"
label variable ha64_1   "NA - Consent for additional tests"
label variable ha64_2   "NA - Consent for additional tests"
label variable ha65_1   "NA - Result of woman's individual interview"
label variable ha65_2   "NA - Result of woman's individual interview"
label variable ha66_1   "NA - Woman's highest educational level"
label variable ha66_2   "NA - Woman's highest educational level"
label variable ha67_1   "NA - Woman's highest year of education"
label variable ha67_2   "NA - Woman's highest year of education"
label variable ha68_1   "NA - Woman's highest educational level (for preliminary and final report)"
label variable ha68_2   "NA - Woman's highest educational level (for preliminary and final report)"
label variable ha69_1   "NA - HIV weight (6 decimals)"
label variable ha69_2   "NA - HIV weight (6 decimals)"
label variable ha70_1   "NA - Interviewer that took blood for HIV testing"
label variable ha70_2   "NA - Interviewer that took blood for HIV testing"
label variable hc0_1    "Index to Household Schedule"
label variable hc0_2    "Index to Household Schedule"
label variable hc0_3    "Index to Household Schedule"
label variable hc0_4    "Index to Household Schedule"
label variable hc0_5    "Index to Household Schedule"
label variable hc1_1    "Child's age in months"
label variable hc1_2    "Child's age in months"
label variable hc1_3    "Child's age in months"
label variable hc1_4    "Child's age in months"
label variable hc1_5    "Child's age in months"
label variable hc1a_1   "Child's age in days"
label variable hc1a_2   "Child's age in days"
label variable hc1a_3   "Child's age in days"
label variable hc1a_4   "Child's age in days"
label variable hc1a_5   "Child's age in days"
label variable hc2_1    "Child's weight in kilograms (1 decimal)"
label variable hc2_2    "Child's weight in kilograms (1 decimal)"
label variable hc2_3    "Child's weight in kilograms (1 decimal)"
label variable hc2_4    "Child's weight in kilograms (1 decimal)"
label variable hc2_5    "Child's weight in kilograms (1 decimal)"
label variable hc3_1    "Child's height in centimeters (1 decimal)"
label variable hc3_2    "Child's height in centimeters (1 decimal)"
label variable hc3_3    "Child's height in centimeters (1 decimal)"
label variable hc3_4    "Child's height in centimeters (1 decimal)"
label variable hc3_5    "Child's height in centimeters (1 decimal)"
label variable hc4_1    "Height/Age percentile"
label variable hc4_2    "Height/Age percentile"
label variable hc4_3    "Height/Age percentile"
label variable hc4_4    "Height/Age percentile"
label variable hc4_5    "Height/Age percentile"
label variable hc5_1    "Height/Age standard deviation"
label variable hc5_2    "Height/Age standard deviation"
label variable hc5_3    "Height/Age standard deviation"
label variable hc5_4    "Height/Age standard deviation"
label variable hc5_5    "Height/Age standard deviation"
label variable hc6_1    "Height/Age percent of ref. median"
label variable hc6_2    "Height/Age percent of ref. median"
label variable hc6_3    "Height/Age percent of ref. median"
label variable hc6_4    "Height/Age percent of ref. median"
label variable hc6_5    "Height/Age percent of ref. median"
label variable hc7_1    "Weight/Age percentile"
label variable hc7_2    "Weight/Age percentile"
label variable hc7_3    "Weight/Age percentile"
label variable hc7_4    "Weight/Age percentile"
label variable hc7_5    "Weight/Age percentile"
label variable hc8_1    "Weight/Age standard deviation"
label variable hc8_2    "Weight/Age standard deviation"
label variable hc8_3    "Weight/Age standard deviation"
label variable hc8_4    "Weight/Age standard deviation"
label variable hc8_5    "Weight/Age standard deviation"
label variable hc9_1    "Weight/Age percent of ref. median"
label variable hc9_2    "Weight/Age percent of ref. median"
label variable hc9_3    "Weight/Age percent of ref. median"
label variable hc9_4    "Weight/Age percent of ref. median"
label variable hc9_5    "Weight/Age percent of ref. median"
label variable hc10_1   "Weight/Height percentile"
label variable hc10_2   "Weight/Height percentile"
label variable hc10_3   "Weight/Height percentile"
label variable hc10_4   "Weight/Height percentile"
label variable hc10_5   "Weight/Height percentile"
label variable hc11_1   "Weight/Height standard deviation"
label variable hc11_2   "Weight/Height standard deviation"
label variable hc11_3   "Weight/Height standard deviation"
label variable hc11_4   "Weight/Height standard deviation"
label variable hc11_5   "Weight/Height standard deviation"
label variable hc12_1   "Weight/Height percent of ref. median"
label variable hc12_2   "Weight/Height percent of ref. median"
label variable hc12_3   "Weight/Height percent of ref. median"
label variable hc12_4   "Weight/Height percent of ref. median"
label variable hc12_5   "Weight/Height percent of ref. median"
label variable hc13_1   "Result of measurement - height/weight"
label variable hc13_2   "Result of measurement - height/weight"
label variable hc13_3   "Result of measurement - height/weight"
label variable hc13_4   "Result of measurement - height/weight"
label variable hc13_5   "Result of measurement - height/weight"
label variable hc15_1   "Height: lying or standing"
label variable hc15_2   "Height: lying or standing"
label variable hc15_3   "Height: lying or standing"
label variable hc15_4   "Height: lying or standing"
label variable hc15_5   "Height: lying or standing"
label variable hc16_1   "Day of birth"
label variable hc16_2   "Day of birth"
label variable hc16_3   "Day of birth"
label variable hc16_4   "Day of birth"
label variable hc16_5   "Day of birth"
label variable hc17_1   "Date measured (day)"
label variable hc17_2   "Date measured (day)"
label variable hc17_3   "Date measured (day)"
label variable hc17_4   "Date measured (day)"
label variable hc17_5   "Date measured (day)"
label variable hc18_1   "Date measured (month)"
label variable hc18_2   "Date measured (month)"
label variable hc18_3   "Date measured (month)"
label variable hc18_4   "Date measured (month)"
label variable hc18_5   "Date measured (month)"
label variable hc19_1   "Date measured (year)"
label variable hc19_2   "Date measured (year)"
label variable hc19_3   "Date measured (year)"
label variable hc19_4   "Date measured (year)"
label variable hc19_5   "Date measured (year)"
label variable hc20_1   "Century Day Code (CDC) of measurement"
label variable hc20_2   "Century Day Code (CDC) of measurement"
label variable hc20_3   "Century Day Code (CDC) of measurement"
label variable hc20_4   "Century Day Code (CDC) of measurement"
label variable hc20_5   "Century Day Code (CDC) of measurement"
label variable hc21_1   "Fieldworker measurer code"
label variable hc21_2   "Fieldworker measurer code"
label variable hc21_3   "Fieldworker measurer code"
label variable hc21_4   "Fieldworker measurer code"
label variable hc21_5   "Fieldworker measurer code"
label variable hc27_1   "Sex"
label variable hc27_2   "Sex"
label variable hc27_3   "Sex"
label variable hc27_4   "Sex"
label variable hc27_5   "Sex"
label variable hc30_1   "Month of birth"
label variable hc30_2   "Month of birth"
label variable hc30_3   "Month of birth"
label variable hc30_4   "Month of birth"
label variable hc30_5   "Month of birth"
label variable hc31_1   "Year of birth"
label variable hc31_2   "Year of birth"
label variable hc31_3   "Year of birth"
label variable hc31_4   "Year of birth"
label variable hc31_5   "Year of birth"
label variable hc32_1   "Date of birth (CMC)"
label variable hc32_2   "Date of birth (CMC)"
label variable hc32_3   "Date of birth (CMC)"
label variable hc32_4   "Date of birth (CMC)"
label variable hc32_5   "Date of birth (CMC)"
label variable hc32a_1  "Century Day Code (CDC) of birth"
label variable hc32a_2  "Century Day Code (CDC) of birth"
label variable hc32a_3  "Century Day Code (CDC) of birth"
label variable hc32a_4  "Century Day Code (CDC) of birth"
label variable hc32a_5  "Century Day Code (CDC) of birth"
label variable hc33_1   "Completeness of HC32 information"
label variable hc33_2   "Completeness of HC32 information"
label variable hc33_3   "Completeness of HC32 information"
label variable hc33_4   "Completeness of HC32 information"
label variable hc33_5   "Completeness of HC32 information"
label variable hc51_1   "NA - Line number of parent/caretaker"
label variable hc51_2   "NA - Line number of parent/caretaker"
label variable hc51_3   "NA - Line number of parent/caretaker"
label variable hc51_4   "NA - Line number of parent/caretaker"
label variable hc51_5   "NA - Line number of parent/caretaker"
label variable hc52_1   "NA - Read consent statement - hemoglobin"
label variable hc52_2   "NA - Read consent statement - hemoglobin"
label variable hc52_3   "NA - Read consent statement - hemoglobin"
label variable hc52_4   "NA - Read consent statement - hemoglobin"
label variable hc52_5   "NA - Read consent statement - hemoglobin"
label variable hc53_1   "NA - Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_2   "NA - Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_3   "NA - Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_4   "NA - Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_5   "NA - Hemoglobin level (g/dl - 1 decimal)"
label variable hc55_1   "NA - Result of measurement - hemoglobin"
label variable hc55_2   "NA - Result of measurement - hemoglobin"
label variable hc55_3   "NA - Result of measurement - hemoglobin"
label variable hc55_4   "NA - Result of measurement - hemoglobin"
label variable hc55_5   "NA - Result of measurement - hemoglobin"
label variable hc56_1   "NA - Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_2   "NA - Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_3   "NA - Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_4   "NA - Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_5   "NA - Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57_1   "NA - Anemia level"
label variable hc57_2   "NA - Anemia level"
label variable hc57_3   "NA - Anemia level"
label variable hc57_4   "NA - Anemia level"
label variable hc57_5   "NA - Anemia level"
label variable hc58_1   "NA - Agrees to referral - anemia"
label variable hc58_2   "NA - Agrees to referral - anemia"
label variable hc58_3   "NA - Agrees to referral - anemia"
label variable hc58_4   "NA - Agrees to referral - anemia"
label variable hc58_5   "NA - Agrees to referral - anemia"
label variable hc60_1   "Mother's line number (woman's questionnaire)"
label variable hc60_2   "Mother's line number (woman's questionnaire)"
label variable hc60_3   "Mother's line number (woman's questionnaire)"
label variable hc60_4   "Mother's line number (woman's questionnaire)"
label variable hc60_5   "Mother's line number (woman's questionnaire)"
label variable hc61_1   "Mother's highest educational level"
label variable hc61_2   "Mother's highest educational level"
label variable hc61_3   "Mother's highest educational level"
label variable hc61_4   "Mother's highest educational level"
label variable hc61_5   "Mother's highest educational level"
label variable hc62_1   "Mother's highest year of education"
label variable hc62_2   "Mother's highest year of education"
label variable hc62_3   "Mother's highest year of education"
label variable hc62_4   "Mother's highest year of education"
label variable hc62_5   "Mother's highest year of education"
label variable hc63_1   "Preceding birth interval (months)"
label variable hc63_2   "Preceding birth interval (months)"
label variable hc63_3   "Preceding birth interval (months)"
label variable hc63_4   "Preceding birth interval (months)"
label variable hc63_5   "Preceding birth interval (months)"
label variable hc64_1   "Birth order number"
label variable hc64_2   "Birth order number"
label variable hc64_3   "Birth order number"
label variable hc64_4   "Birth order number"
label variable hc64_5   "Birth order number"
label variable hc68_1   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_2   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_3   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_4   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_5   "Mother's highest educational level (for preliminary and final report)"
label variable hc70_1   "Height/Age standard deviation (new WHO)"
label variable hc70_2   "Height/Age standard deviation (new WHO)"
label variable hc70_3   "Height/Age standard deviation (new WHO)"
label variable hc70_4   "Height/Age standard deviation (new WHO)"
label variable hc70_5   "Height/Age standard deviation (new WHO)"
label variable hc71_1   "Weight/Age standard deviation (new WHO)"
label variable hc71_2   "Weight/Age standard deviation (new WHO)"
label variable hc71_3   "Weight/Age standard deviation (new WHO)"
label variable hc71_4   "Weight/Age standard deviation (new WHO)"
label variable hc71_5   "Weight/Age standard deviation (new WHO)"
label variable hc72_1   "Weight/Height standard deviation (new WHO)"
label variable hc72_2   "Weight/Height standard deviation (new WHO)"
label variable hc72_3   "Weight/Height standard deviation (new WHO)"
label variable hc72_4   "Weight/Height standard deviation (new WHO)"
label variable hc72_5   "Weight/Height standard deviation (new WHO)"
label variable hc73_1   "BMI standard deviation (new WHO)"
label variable hc73_2   "BMI standard deviation (new WHO)"
label variable hc73_3   "BMI standard deviation (new WHO)"
label variable hc73_4   "BMI standard deviation (new WHO)"
label variable hc73_5   "BMI standard deviation (new WHO)"
label variable hc2a_1   "Child's weight in kilograms (1 decimal) - first measurement"
label variable hc2a_2   "Child's weight in kilograms (1 decimal) - first measurement"
label variable hc2a_3   "Child's weight in kilograms (1 decimal) - first measurement"
label variable hc2a_4   "Child's weight in kilograms (1 decimal) - first measurement"
label variable hc2a_5   "Child's weight in kilograms (1 decimal) - first measurement"
label variable hc3a_1   "Child's height in centimeters (1 decimal) - first measurement"
label variable hc3a_2   "Child's height in centimeters (1 decimal) - first measurement"
label variable hc3a_3   "Child's height in centimeters (1 decimal) - first measurement"
label variable hc3a_4   "Child's height in centimeters (1 decimal) - first measurement"
label variable hc3a_5   "Child's height in centimeters (1 decimal) - first measurement"
label variable hc15a_1  "Height: lying or standing - first measurement"
label variable hc15a_2  "Height: lying or standing - first measurement"
label variable hc15a_3  "Height: lying or standing - first measurement"
label variable hc15a_4  "Height: lying or standing - first measurement"
label variable hc15a_5  "Height: lying or standing - first measurement"
label variable hc2b_1   "Child's weight in kilograms (1 decimal) - re-measurement"
label variable hc2b_2   "Child's weight in kilograms (1 decimal) - re-measurement"
label variable hc2b_3   "Child's weight in kilograms (1 decimal) - re-measurement"
label variable hc2b_4   "Child's weight in kilograms (1 decimal) - re-measurement"
label variable hc2b_5   "Child's weight in kilograms (1 decimal) - re-measurement"
label variable hc3b_1   "Child's height in centimeters (1 decimal) - re-measurement"
label variable hc3b_2   "Child's height in centimeters (1 decimal) - re-measurement"
label variable hc3b_3   "Child's height in centimeters (1 decimal) - re-measurement"
label variable hc3b_4   "Child's height in centimeters (1 decimal) - re-measurement"
label variable hc3b_5   "Child's height in centimeters (1 decimal) - re-measurement"
label variable hc15b_1  "Height: lying or standing - re-measurement"
label variable hc15b_2  "Height: lying or standing - re-measurement"
label variable hc15b_3  "Height: lying or standing - re-measurement"
label variable hc15b_4  "Height: lying or standing - re-measurement"
label variable hc15b_5  "Height: lying or standing - re-measurement"
label variable hc35_1   "Reason for re-measurement"
label variable hc35_2   "Reason for re-measurement"
label variable hc35_3   "Reason for re-measurement"
label variable hc35_4   "Reason for re-measurement"
label variable hc35_5   "Reason for re-measurement"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV022   
     1 "Tigray-urban"
     2 "Tigray-rural"
     3 "Afar-Urban"
     4 "Afar-rural"
     5 "Amhara-urban"
     6 "Amhara-rural"
     7 "Oromia-urban"
     8 "Oromia-rural"
     9 "Somali-urban"
    10 "Somali-rural"
    11 "Benishangul-Gumuz-urban"
    12 "Benishangul-Gumuz-rural"
    13 "SNNPR-urban"
    14 "SNNPR-rural"
    15 "Gambela-urban"
    16 "Gambela-rural"
    17 "Harari-urban"
    18 "Harari-rural"
    19 "Addis Ababa"
    20 "Dire Dawa-urban"
    21 "Dire Dawa -rural"
;
label define HV023   
     1 "Tigray-urban"
     2 "Tigray-rural"
     3 "Afar-Urban"
     4 "Afar-rural"
     5 "Amhara-urban"
     6 "Amhara-rural"
     7 "Oromia-urban"
     8 "Oromia-rural"
     9 "Somali-urban"
    10 "Somali-rural"
    11 "Benishangul-Gumuz-urban"
    12 "Benishangul-Gumuz-rural"
    13 "SNNPR-urban"
    14 "SNNPR-rural"
    15 "Gambela-urban"
    16 "Gambela-rural"
    17 "Harari-urban"
    18 "Harari-rural"
    19 "Addis Ababa"
    20 "Dire Dawa-urban"
    21 "Dire Dawa -rural"
;
label define HV024   
     1 "Tigray"
     2 "Afar"
     3 "Amhara"
     4 "Oromia"
     5 "Somali"
     6 "Benishangul-Gumuz"
     7 "SNNPR"
     8 "Gambela"
     9 "Harari"
    10 "Addis Ababa"
    11 "Dire Dawa"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV045A  
     1 "English"
     2 "Amarigna"
     3 "Oromigna"
     4 "Tigrigna"
     6 "Afarigna"
     7 "Somaligna"
     8 "Wolyitgna"
     9 "Gamogna/Dorzigna/Zagulna"
    10 "Hadiygna"
    11 "Kembatigna"
    12 "Sidamigna"
    13 "Gedeogna"
    14 "Guragigna/Meskan/Welane"
    15 "Keffigna/Kefficho"
    16 "Hararigna/Adirigna"
    17 "Agewigna/Awi"
    18 "Agnwakigna"
    19 "Nuwerigna/Gambeligna"
    20 "Ginirgna"
    21 "Mezengrigna"
    22 "Gumuzigna/Bangagna"
    23 "Siltigna"
    24 "Arigna"
    25 "Basketigna"
    26 "Burjigna"
    27 "Dawerogna"
    28 "Goffagna"
    29 "Halibigna"
    30 "Ruteangna"
    31 "Shehogna"
    32 "Shekogna"
    33 "Benichigna"
    34 "Darashegna"
    35 "Kebegna"
    36 "Kontegna"
    37 "Konsogna"
    38 "Maogna"
    39 "Shekichogna/Mochagna"
    40 "Shinashigna"
    41 "Yemigna"
    42 "Zeyisegna"
    43 "Bertigna"
    44 "Komogna"
    45 "Dezigna/Majigna"
    46 "Saho/Erobigna"
    47 "Gofegna"
    48 "Hemetgna"
    96 "Other"
;
label define HV045B  
     1 "English"
     2 "Amarigna"
     3 "Oromigna"
     4 "Tigrigna"
     6 "Afarigna"
     7 "Somaligna"
     8 "Wolyitgna"
     9 "Gamogna/Dorzigna/Zagulna"
    10 "Hadiygna"
    11 "Kembatigna"
    12 "Sidamigna"
    13 "Gedeogna"
    14 "Guragigna/Meskan/Welane"
    15 "Keffigna/Kefficho"
    16 "Hararigna/Adirigna"
    17 "Agewigna/Awi"
    18 "Agnwakigna"
    19 "Nuwerigna/Gambeligna"
    20 "Ginirgna"
    21 "Mezengrigna"
    22 "Gumuzigna/Bangagna"
    23 "Siltigna"
    24 "Arigna"
    25 "Basketigna"
    26 "Burjigna"
    27 "Dawerogna"
    28 "Goffagna"
    29 "Halibigna"
    30 "Ruteangna"
    31 "Shehogna"
    32 "Shekogna"
    33 "Benichigna"
    34 "Darashegna"
    35 "Kebegna"
    36 "Kontegna"
    37 "Konsogna"
    38 "Maogna"
    39 "Shekichogna/Mochagna"
    40 "Shinashigna"
    41 "Yemigna"
    42 "Zeyisegna"
    43 "Bertigna"
    44 "Komogna"
    45 "Dezigna/Majigna"
    46 "Saho/Erobigna"
    47 "Gofegna"
    48 "Hemetgna"
    96 "Other"
;
label define HV045C  
     1 "English"
     2 "Amarigna"
     3 "Oromigna"
     4 "Tigrigna"
     6 "Afarigna"
     7 "Somaligna"
     8 "Wolyitgna"
     9 "Gamogna/Dorzigna/Zagulna"
    10 "Hadiygna"
    11 "Kembatigna"
    12 "Sidamigna"
    13 "Gedeogna"
    14 "Guragigna/Meskan/Welane"
    15 "Keffigna/Kefficho"
    16 "Hararigna/Adirigna"
    17 "Agewigna/Awi"
    18 "Agnwakigna"
    19 "Nuwerigna/Gambeligna"
    20 "Ginirgna"
    21 "Mezengrigna"
    22 "Gumuzigna/Bangagna"
    23 "Siltigna"
    24 "Arigna"
    25 "Basketigna"
    26 "Burjigna"
    27 "Dawerogna"
    28 "Goffagna"
    29 "Halibigna"
    30 "Ruteangna"
    31 "Shehogna"
    32 "Shekogna"
    33 "Benichigna"
    34 "Darashegna"
    35 "Kebegna"
    36 "Kontegna"
    37 "Konsogna"
    38 "Maogna"
    39 "Shekichogna/Mochagna"
    40 "Shinashigna"
    41 "Yemigna"
    42 "Zeyisegna"
    43 "Bertigna"
    44 "Komogna"
    45 "Dezigna/Majigna"
    46 "Saho/Erobigna"
    47 "Gofegna"
    48 "Hemetgna"
    96 "Other"
;
label define HV046   
     0 "No"
     1 "Yes"
;
label define HV801   
  9999 "Missing"
;
label define HV802   
  9999 "Missing"
;
label define HV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define HV804   
     9 "Missing"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV201A  
     0 "No, not interrupted for a full day"
     1 "Yes, interrupted for a full day or more"
     8 "Don't know"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
;
label define HV214   
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks/reed"
    13 "Dirt"
    20 "RUDIMENTARY"
    21 "Bamboo/wood with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
;
label define HV215   
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/mud"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Metal/ corrugated iron"
    32 "Wood"
    33 "Calamine/cement fiber"
    34 "Ceramic tiles"
    35 "Cement"
    36 "Roofing shingles"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in house"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV230A  
     1 "Observed, fixed place"
     2 "Observed, mobile place"
     3 "Not observed: not in dwelling"
     4 "Not observed: no permission to see"
     5 "Not observed: other reason"
;
label define HV230B  
     0 "Water not available"
     1 "Water is available"
;
label define HV232   
     0 "No"
     1 "Yes"
;
label define HV232B  
     0 "No"
     1 "Yes"
;
label define HV232C  
     0 "No"
     1 "Yes"
;
label define HV232D  
     0 "No"
     1 "Yes"
;
label define HV232E  
     0 "No"
     1 "Yes"
;
label define HV232Y  
     0 "No"
     1 "Yes: no cleansing agent observed"
;
label define HV234   
     0 "0 PPM (no iodine)"
     7 "Below 15 PPM"
    15 "15 PPM and above"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define HV234A  
     0 "No iodine"
     1 "Iodine present"
     3 "No salt in household"
     6 "Salt not tested"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV236   
     1 "Adult woman"
     2 "Adult man"
     3 "Female child under 15 years old"
     4 "Male child under 15 years old"
     6 "Other"
;
label define HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237I  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237J  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237K  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237Z  
     0 "No"
     1 "Yes: don't know what is done to water"
     8 "Don't know"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV238A  
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     0 "Neither chimney or hood"
     1 "Chimney"
     2 "Hood"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV243E  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
   950 "95 or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV252   
     0 "Never"
     1 "Daily"
     2 "Weekly"
     3 "Monthly"
     4 "Less than once a month"
;
label define HV253   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253Z  
     0 "No"
     1 "Yes: don't know who sprayed the dwelling"
     8 "Don't know if it was sprayed"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HV270A  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SH121G  
     0 "No"
     1 "Yes"
;
label define SH121H  
     0 "No"
     1 "Yes"
;
label define SH121I  
     0 "No"
     1 "Yes"
;
label define SH121J  
     0 "No"
     1 "Yes"
;
label define SH121K  
     0 "No"
     1 "Yes"
;
label define SH124   
     0 "No"
     1 "Yes"
;
label define SH125   
     0 "No"
     1 "Yes"
;
label define SH126   
     1 "Owned"
     2 "Free of charge"
     3 "Rented from Kebele/agency/employer/individuals"
     6 "Other"
;
label define SH122G  
     0 "No"
     1 "Yes"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    98 "Don't know"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV107   
    98 "Don't know"
;
label define HV108   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
;
label define HV110   
     0 "No"
     1 "Yes"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV112   
     0 "Mother not in household"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV114   
     0 "Father not in household"
;
label define HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever married"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV123   
    98 "Don't know"
;
label define HV124   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV127   
    98 "Don't know"
;
label define HV128   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "Don't know"
;
label define HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     8 "Don't know"
;
label define SH16    
     0 "No"
     1 "Yes"
;
label define SH17A   
     0 "Preschool"
     1 "Primary"
     2 "Secondary"
     3 "Technical/ vocational"
     4 "Higher"
     8 "Don't know"
;
label define SH17B   
     0 "Less than 1 year completed"
    98 "Don't know"
;
label define SH18    
     0 "No"
     1 "Yes"
;
label define SH19A   
     0 "Preschool"
     1 "Primary"
     2 "Secondary"
     3 "Technical/ vocational"
     4 "Higher"
     8 "Don't know"
;
label define SH19B   
    98 "Don't know"
;
label define HA2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA4     
  9998 "Flagged cases"
;
label define HA5     
  9998 "Flagged cases"
;
label define HA6     
 99998 "Flagged cases"
;
label define HA11    
  9998 "Flagged cases"
;
label define HA12    
 99998 "Flagged cases"
;
label define HA12A   
 99998 "Flagged cases"
;
label define HA12B   
 99998 "Flagged cases"
;
label define HA13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA33    
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HA35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
;
label define HA40    
  9998 "Flagged cases"
;
label define HA41    
  9998 "Flagged cases"
;
label define HA50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HA51    
     0 "Not in household"
;
label define HA52    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define HA53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HA54    
     0 "No/don't know"
     1 "Yes"
;
label define HA55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA56    
   997 "Inconsistent"
;
label define HA57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HA58    
     0 "No"
     1 "Yes"
;
label define HA60    
     1 "Never in union"
     2 "Other"
;
label define HA61    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
     6 "Sample not tested/lost/not enough DBS"
;
label define HA63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost/damaged/insufficient"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HA64    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     6 "Sample not tested/lost/not enough DBS"
;
label define HA65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HA66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HA67    
    98 "Don't know"
;
label define HA68    
     0 "Labels to be populated according to country"
     8 "Don't know"
;
label define HC2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC4     
  9998 "Flagged cases"
;
label define HC5     
  9998 "Flagged cases"
;
label define HC6     
 99998 "Flagged cases"
;
label define HC7     
  9998 "Flagged cases"
;
label define HC8     
  9998 "Flagged cases"
;
label define HC9     
 99998 "Flagged cases"
;
label define HC10    
  9998 "Flagged cases"
;
label define HC11    
  9998 "Flagged cases"
;
label define HC12    
 99998 "Flagged cases"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC15    
     0 "Not measured"
     1 "Lying"
     2 "Standing"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present/other"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Technical/vocational"
     4 "Higher"
     8 "Don't know"
;
label define HC62    
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Technical/vocational"
     4 "Higher"
     8 "Don't know"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC2A    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3A    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC15A   
     0 "Not measured"
     1 "Lying"
     2 "Standing"
;
label define HC2B    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3B    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC15B   
     0 "Not measured"
     1 "Lying"
     2 "Standing"
;
label define HC35    
     0 "Not remeasured"
     1 "Random"
     2 "Z-Scores"
     3 "Both random & Z-scores"
;

#delimit cr
label values hv003    HV003   
label values hv015    HV015   
label values hv020    HV020   
label values hv022    HV022   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv044    HV044   
label values hv045a   HV045A  
label values hv045b   HV045B  
label values hv045c   HV045C  
label values hv046    HV046   
label values hv803    HV803   
label values hv201    HV201   
label values hv202    HV202   
label values hv201a   HV201A  
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv230a   HV230A  
label values hv230b   HV230B  
label values hv232    HV232   
label values hv232b   HV232B  
label values hv232c   HV232C  
label values hv232d   HV232D  
label values hv232e   HV232E  
label values hv232y   HV232Y  
label values hv234    HV234   
label values hv234a   HV234A  
label values hv235    HV235   
label values hv236    HV236   
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237g   HV237G  
label values hv237h   HV237H  
label values hv237i   HV237I  
label values hv237j   HV237J  
label values hv237k   HV237K  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv238a   HV238A  
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv243e   HV243E  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv252    HV252   
label values hv253    HV253   
label values hv253a   HV253A  
label values hv253b   HV253B  
label values hv253c   HV253C  
label values hv253d   HV253D  
label values hv253e   HV253E  
label values hv253f   HV253F  
label values hv253g   HV253G  
label values hv253h   HV253H  
label values hv253x   HV253X  
label values hv253z   HV253Z  
label values hv270    HV270   
label values hv270a   HV270A  
label values hml1     HML1    
label values sh121g   SH121G  
label values sh121h   SH121H  
label values sh121i   SH121I  
label values sh121j   SH121J  
label values sh121k   SH121K  
label values sh124    SH124   
label values sh125    SH125   
label values sh126    SH126   
label values sh122g   SH122G  
label values hv101_01 HV101   
label values hv101_02 HV101   
label values hv101_03 HV101   
label values hv101_04 HV101   
label values hv101_05 HV101   
label values hv101_06 HV101   
label values hv101_07 HV101   
label values hv101_08 HV101   
label values hv101_09 HV101   
label values hv101_10 HV101   
label values hv101_11 HV101   
label values hv101_12 HV101   
label values hv101_13 HV101   
label values hv101_14 HV101   
label values hv101_15 HV101   
label values hv101_16 HV101   
label values hv101_17 HV101   
label values hv101_18 HV101   
label values hv101_19 HV101   
label values hv101_20 HV101   
label values hv101_21 HV101   
label values hv101_22 HV101   
label values hv101_23 HV101   
label values hv101_24 HV101   
label values hv102_01 HV102   
label values hv102_02 HV102   
label values hv102_03 HV102   
label values hv102_04 HV102   
label values hv102_05 HV102   
label values hv102_06 HV102   
label values hv102_07 HV102   
label values hv102_08 HV102   
label values hv102_09 HV102   
label values hv102_10 HV102   
label values hv102_11 HV102   
label values hv102_12 HV102   
label values hv102_13 HV102   
label values hv102_14 HV102   
label values hv102_15 HV102   
label values hv102_16 HV102   
label values hv102_17 HV102   
label values hv102_18 HV102   
label values hv102_19 HV102   
label values hv102_20 HV102   
label values hv102_21 HV102   
label values hv102_22 HV102   
label values hv102_23 HV102   
label values hv102_24 HV102   
label values hv103_01 HV103   
label values hv103_02 HV103   
label values hv103_03 HV103   
label values hv103_04 HV103   
label values hv103_05 HV103   
label values hv103_06 HV103   
label values hv103_07 HV103   
label values hv103_08 HV103   
label values hv103_09 HV103   
label values hv103_10 HV103   
label values hv103_11 HV103   
label values hv103_12 HV103   
label values hv103_13 HV103   
label values hv103_14 HV103   
label values hv103_15 HV103   
label values hv103_16 HV103   
label values hv103_17 HV103   
label values hv103_18 HV103   
label values hv103_19 HV103   
label values hv103_20 HV103   
label values hv103_21 HV103   
label values hv103_22 HV103   
label values hv103_23 HV103   
label values hv103_24 HV103   
label values hv104_01 HV104   
label values hv104_02 HV104   
label values hv104_03 HV104   
label values hv104_04 HV104   
label values hv104_05 HV104   
label values hv104_06 HV104   
label values hv104_07 HV104   
label values hv104_08 HV104   
label values hv104_09 HV104   
label values hv104_10 HV104   
label values hv104_11 HV104   
label values hv104_12 HV104   
label values hv104_13 HV104   
label values hv104_14 HV104   
label values hv104_15 HV104   
label values hv104_16 HV104   
label values hv104_17 HV104   
label values hv104_18 HV104   
label values hv104_19 HV104   
label values hv104_20 HV104   
label values hv104_21 HV104   
label values hv104_22 HV104   
label values hv104_23 HV104   
label values hv104_24 HV104   
label values hv105_01 HV105   
label values hv105_02 HV105   
label values hv105_03 HV105   
label values hv105_04 HV105   
label values hv105_05 HV105   
label values hv105_06 HV105   
label values hv105_07 HV105   
label values hv105_08 HV105   
label values hv105_09 HV105   
label values hv105_10 HV105   
label values hv105_11 HV105   
label values hv105_12 HV105   
label values hv105_13 HV105   
label values hv105_14 HV105   
label values hv105_15 HV105   
label values hv105_16 HV105   
label values hv105_17 HV105   
label values hv105_18 HV105   
label values hv105_19 HV105   
label values hv105_20 HV105   
label values hv105_21 HV105   
label values hv105_22 HV105   
label values hv105_23 HV105   
label values hv105_24 HV105   
label values hv106_01 HV106   
label values hv106_02 HV106   
label values hv106_03 HV106   
label values hv106_04 HV106   
label values hv106_05 HV106   
label values hv106_06 HV106   
label values hv106_07 HV106   
label values hv106_08 HV106   
label values hv106_09 HV106   
label values hv106_10 HV106   
label values hv106_11 HV106   
label values hv106_12 HV106   
label values hv106_13 HV106   
label values hv106_14 HV106   
label values hv106_15 HV106   
label values hv106_16 HV106   
label values hv106_17 HV106   
label values hv106_18 HV106   
label values hv106_19 HV106   
label values hv106_20 HV106   
label values hv106_21 HV106   
label values hv106_22 HV106   
label values hv106_23 HV106   
label values hv106_24 HV106   
label values hv107_01 HV107   
label values hv107_02 HV107   
label values hv107_03 HV107   
label values hv107_04 HV107   
label values hv107_05 HV107   
label values hv107_06 HV107   
label values hv107_07 HV107   
label values hv107_08 HV107   
label values hv107_09 HV107   
label values hv107_10 HV107   
label values hv107_11 HV107   
label values hv107_12 HV107   
label values hv107_13 HV107   
label values hv107_14 HV107   
label values hv107_15 HV107   
label values hv107_16 HV107   
label values hv107_17 HV107   
label values hv107_18 HV107   
label values hv107_19 HV107   
label values hv107_20 HV107   
label values hv107_21 HV107   
label values hv107_22 HV107   
label values hv107_23 HV107   
label values hv107_24 HV107   
label values hv108_01 HV108   
label values hv108_02 HV108   
label values hv108_03 HV108   
label values hv108_04 HV108   
label values hv108_05 HV108   
label values hv108_06 HV108   
label values hv108_07 HV108   
label values hv108_08 HV108   
label values hv108_09 HV108   
label values hv108_10 HV108   
label values hv108_11 HV108   
label values hv108_12 HV108   
label values hv108_13 HV108   
label values hv108_14 HV108   
label values hv108_15 HV108   
label values hv108_16 HV108   
label values hv108_17 HV108   
label values hv108_18 HV108   
label values hv108_19 HV108   
label values hv108_20 HV108   
label values hv108_21 HV108   
label values hv108_22 HV108   
label values hv108_23 HV108   
label values hv108_24 HV108   
label values hv109_01 HV109   
label values hv109_02 HV109   
label values hv109_03 HV109   
label values hv109_04 HV109   
label values hv109_05 HV109   
label values hv109_06 HV109   
label values hv109_07 HV109   
label values hv109_08 HV109   
label values hv109_09 HV109   
label values hv109_10 HV109   
label values hv109_11 HV109   
label values hv109_12 HV109   
label values hv109_13 HV109   
label values hv109_14 HV109   
label values hv109_15 HV109   
label values hv109_16 HV109   
label values hv109_17 HV109   
label values hv109_18 HV109   
label values hv109_19 HV109   
label values hv109_20 HV109   
label values hv109_21 HV109   
label values hv109_22 HV109   
label values hv109_23 HV109   
label values hv109_24 HV109   
label values hv110_01 HV110   
label values hv110_02 HV110   
label values hv110_03 HV110   
label values hv110_04 HV110   
label values hv110_05 HV110   
label values hv110_06 HV110   
label values hv110_07 HV110   
label values hv110_08 HV110   
label values hv110_09 HV110   
label values hv110_10 HV110   
label values hv110_11 HV110   
label values hv110_12 HV110   
label values hv110_13 HV110   
label values hv110_14 HV110   
label values hv110_15 HV110   
label values hv110_16 HV110   
label values hv110_17 HV110   
label values hv110_18 HV110   
label values hv110_19 HV110   
label values hv110_20 HV110   
label values hv110_21 HV110   
label values hv110_22 HV110   
label values hv110_23 HV110   
label values hv110_24 HV110   
label values hv111_01 HV111   
label values hv111_02 HV111   
label values hv111_03 HV111   
label values hv111_04 HV111   
label values hv111_05 HV111   
label values hv111_06 HV111   
label values hv111_07 HV111   
label values hv111_08 HV111   
label values hv111_09 HV111   
label values hv111_10 HV111   
label values hv111_11 HV111   
label values hv111_12 HV111   
label values hv111_13 HV111   
label values hv111_14 HV111   
label values hv111_15 HV111   
label values hv111_16 HV111   
label values hv111_17 HV111   
label values hv111_18 HV111   
label values hv111_19 HV111   
label values hv111_20 HV111   
label values hv111_21 HV111   
label values hv111_22 HV111   
label values hv111_23 HV111   
label values hv111_24 HV111   
label values hv112_01 HV112   
label values hv112_02 HV112   
label values hv112_03 HV112   
label values hv112_04 HV112   
label values hv112_05 HV112   
label values hv112_06 HV112   
label values hv112_07 HV112   
label values hv112_08 HV112   
label values hv112_09 HV112   
label values hv112_10 HV112   
label values hv112_11 HV112   
label values hv112_12 HV112   
label values hv112_13 HV112   
label values hv112_14 HV112   
label values hv112_15 HV112   
label values hv112_16 HV112   
label values hv112_17 HV112   
label values hv112_18 HV112   
label values hv112_19 HV112   
label values hv112_20 HV112   
label values hv112_21 HV112   
label values hv112_22 HV112   
label values hv112_23 HV112   
label values hv112_24 HV112   
label values hv113_01 HV113   
label values hv113_02 HV113   
label values hv113_03 HV113   
label values hv113_04 HV113   
label values hv113_05 HV113   
label values hv113_06 HV113   
label values hv113_07 HV113   
label values hv113_08 HV113   
label values hv113_09 HV113   
label values hv113_10 HV113   
label values hv113_11 HV113   
label values hv113_12 HV113   
label values hv113_13 HV113   
label values hv113_14 HV113   
label values hv113_15 HV113   
label values hv113_16 HV113   
label values hv113_17 HV113   
label values hv113_18 HV113   
label values hv113_19 HV113   
label values hv113_20 HV113   
label values hv113_21 HV113   
label values hv113_22 HV113   
label values hv113_23 HV113   
label values hv113_24 HV113   
label values hv114_01 HV114   
label values hv114_02 HV114   
label values hv114_03 HV114   
label values hv114_04 HV114   
label values hv114_05 HV114   
label values hv114_06 HV114   
label values hv114_07 HV114   
label values hv114_08 HV114   
label values hv114_09 HV114   
label values hv114_10 HV114   
label values hv114_11 HV114   
label values hv114_12 HV114   
label values hv114_13 HV114   
label values hv114_14 HV114   
label values hv114_15 HV114   
label values hv114_16 HV114   
label values hv114_17 HV114   
label values hv114_18 HV114   
label values hv114_19 HV114   
label values hv114_20 HV114   
label values hv114_21 HV114   
label values hv114_22 HV114   
label values hv114_23 HV114   
label values hv114_24 HV114   
label values hv115_01 HV115   
label values hv115_02 HV115   
label values hv115_03 HV115   
label values hv115_04 HV115   
label values hv115_05 HV115   
label values hv115_06 HV115   
label values hv115_07 HV115   
label values hv115_08 HV115   
label values hv115_09 HV115   
label values hv115_10 HV115   
label values hv115_11 HV115   
label values hv115_12 HV115   
label values hv115_13 HV115   
label values hv115_14 HV115   
label values hv115_15 HV115   
label values hv115_16 HV115   
label values hv115_17 HV115   
label values hv115_18 HV115   
label values hv115_19 HV115   
label values hv115_20 HV115   
label values hv115_21 HV115   
label values hv115_22 HV115   
label values hv115_23 HV115   
label values hv115_24 HV115   
label values hv116_01 HV116   
label values hv116_02 HV116   
label values hv116_03 HV116   
label values hv116_04 HV116   
label values hv116_05 HV116   
label values hv116_06 HV116   
label values hv116_07 HV116   
label values hv116_08 HV116   
label values hv116_09 HV116   
label values hv116_10 HV116   
label values hv116_11 HV116   
label values hv116_12 HV116   
label values hv116_13 HV116   
label values hv116_14 HV116   
label values hv116_15 HV116   
label values hv116_16 HV116   
label values hv116_17 HV116   
label values hv116_18 HV116   
label values hv116_19 HV116   
label values hv116_20 HV116   
label values hv116_21 HV116   
label values hv116_22 HV116   
label values hv116_23 HV116   
label values hv116_24 HV116   
label values hv117_01 HV117   
label values hv117_02 HV117   
label values hv117_03 HV117   
label values hv117_04 HV117   
label values hv117_05 HV117   
label values hv117_06 HV117   
label values hv117_07 HV117   
label values hv117_08 HV117   
label values hv117_09 HV117   
label values hv117_10 HV117   
label values hv117_11 HV117   
label values hv117_12 HV117   
label values hv117_13 HV117   
label values hv117_14 HV117   
label values hv117_15 HV117   
label values hv117_16 HV117   
label values hv117_17 HV117   
label values hv117_18 HV117   
label values hv117_19 HV117   
label values hv117_20 HV117   
label values hv117_21 HV117   
label values hv117_22 HV117   
label values hv117_23 HV117   
label values hv117_24 HV117   
label values hv118_01 HV118   
label values hv118_02 HV118   
label values hv118_03 HV118   
label values hv118_04 HV118   
label values hv118_05 HV118   
label values hv118_06 HV118   
label values hv118_07 HV118   
label values hv118_08 HV118   
label values hv118_09 HV118   
label values hv118_10 HV118   
label values hv118_11 HV118   
label values hv118_12 HV118   
label values hv118_13 HV118   
label values hv118_14 HV118   
label values hv118_15 HV118   
label values hv118_16 HV118   
label values hv118_17 HV118   
label values hv118_18 HV118   
label values hv118_19 HV118   
label values hv118_20 HV118   
label values hv118_21 HV118   
label values hv118_22 HV118   
label values hv118_23 HV118   
label values hv118_24 HV118   
label values hv120_01 HV120   
label values hv120_02 HV120   
label values hv120_03 HV120   
label values hv120_04 HV120   
label values hv120_05 HV120   
label values hv120_06 HV120   
label values hv120_07 HV120   
label values hv120_08 HV120   
label values hv120_09 HV120   
label values hv120_10 HV120   
label values hv120_11 HV120   
label values hv120_12 HV120   
label values hv120_13 HV120   
label values hv120_14 HV120   
label values hv120_15 HV120   
label values hv120_16 HV120   
label values hv120_17 HV120   
label values hv120_18 HV120   
label values hv120_19 HV120   
label values hv120_20 HV120   
label values hv120_21 HV120   
label values hv120_22 HV120   
label values hv120_23 HV120   
label values hv120_24 HV120   
label values hv121_01 HV121   
label values hv121_02 HV121   
label values hv121_03 HV121   
label values hv121_04 HV121   
label values hv121_05 HV121   
label values hv121_06 HV121   
label values hv121_07 HV121   
label values hv121_08 HV121   
label values hv121_09 HV121   
label values hv121_10 HV121   
label values hv121_11 HV121   
label values hv121_12 HV121   
label values hv121_13 HV121   
label values hv121_14 HV121   
label values hv121_15 HV121   
label values hv121_16 HV121   
label values hv121_17 HV121   
label values hv121_18 HV121   
label values hv121_19 HV121   
label values hv121_20 HV121   
label values hv121_21 HV121   
label values hv121_22 HV121   
label values hv121_23 HV121   
label values hv121_24 HV121   
label values hv122_01 HV122   
label values hv122_02 HV122   
label values hv122_03 HV122   
label values hv122_04 HV122   
label values hv122_05 HV122   
label values hv122_06 HV122   
label values hv122_07 HV122   
label values hv122_08 HV122   
label values hv122_09 HV122   
label values hv122_10 HV122   
label values hv122_11 HV122   
label values hv122_12 HV122   
label values hv122_13 HV122   
label values hv122_14 HV122   
label values hv122_15 HV122   
label values hv122_16 HV122   
label values hv122_17 HV122   
label values hv122_18 HV122   
label values hv122_19 HV122   
label values hv122_20 HV122   
label values hv122_21 HV122   
label values hv122_22 HV122   
label values hv122_23 HV122   
label values hv122_24 HV122   
label values hv123_01 HV123   
label values hv123_02 HV123   
label values hv123_03 HV123   
label values hv123_04 HV123   
label values hv123_05 HV123   
label values hv123_06 HV123   
label values hv123_07 HV123   
label values hv123_08 HV123   
label values hv123_09 HV123   
label values hv123_10 HV123   
label values hv123_11 HV123   
label values hv123_12 HV123   
label values hv123_13 HV123   
label values hv123_14 HV123   
label values hv123_15 HV123   
label values hv123_16 HV123   
label values hv123_17 HV123   
label values hv123_18 HV123   
label values hv123_19 HV123   
label values hv123_20 HV123   
label values hv123_21 HV123   
label values hv123_22 HV123   
label values hv123_23 HV123   
label values hv123_24 HV123   
label values hv124_01 HV124   
label values hv124_02 HV124   
label values hv124_03 HV124   
label values hv124_04 HV124   
label values hv124_05 HV124   
label values hv124_06 HV124   
label values hv124_07 HV124   
label values hv124_08 HV124   
label values hv124_09 HV124   
label values hv124_10 HV124   
label values hv124_11 HV124   
label values hv124_12 HV124   
label values hv124_13 HV124   
label values hv124_14 HV124   
label values hv124_15 HV124   
label values hv124_16 HV124   
label values hv124_17 HV124   
label values hv124_18 HV124   
label values hv124_19 HV124   
label values hv124_20 HV124   
label values hv124_21 HV124   
label values hv124_22 HV124   
label values hv124_23 HV124   
label values hv124_24 HV124   
label values hv125_01 HV125   
label values hv125_02 HV125   
label values hv125_03 HV125   
label values hv125_04 HV125   
label values hv125_05 HV125   
label values hv125_06 HV125   
label values hv125_07 HV125   
label values hv125_08 HV125   
label values hv125_09 HV125   
label values hv125_10 HV125   
label values hv125_11 HV125   
label values hv125_12 HV125   
label values hv125_13 HV125   
label values hv125_14 HV125   
label values hv125_15 HV125   
label values hv125_16 HV125   
label values hv125_17 HV125   
label values hv125_18 HV125   
label values hv125_19 HV125   
label values hv125_20 HV125   
label values hv125_21 HV125   
label values hv125_22 HV125   
label values hv125_23 HV125   
label values hv125_24 HV125   
label values hv126_01 HV126   
label values hv126_02 HV126   
label values hv126_03 HV126   
label values hv126_04 HV126   
label values hv126_05 HV126   
label values hv126_06 HV126   
label values hv126_07 HV126   
label values hv126_08 HV126   
label values hv126_09 HV126   
label values hv126_10 HV126   
label values hv126_11 HV126   
label values hv126_12 HV126   
label values hv126_13 HV126   
label values hv126_14 HV126   
label values hv126_15 HV126   
label values hv126_16 HV126   
label values hv126_17 HV126   
label values hv126_18 HV126   
label values hv126_19 HV126   
label values hv126_20 HV126   
label values hv126_21 HV126   
label values hv126_22 HV126   
label values hv126_23 HV126   
label values hv126_24 HV126   
label values hv127_01 HV127   
label values hv127_02 HV127   
label values hv127_03 HV127   
label values hv127_04 HV127   
label values hv127_05 HV127   
label values hv127_06 HV127   
label values hv127_07 HV127   
label values hv127_08 HV127   
label values hv127_09 HV127   
label values hv127_10 HV127   
label values hv127_11 HV127   
label values hv127_12 HV127   
label values hv127_13 HV127   
label values hv127_14 HV127   
label values hv127_15 HV127   
label values hv127_16 HV127   
label values hv127_17 HV127   
label values hv127_18 HV127   
label values hv127_19 HV127   
label values hv127_20 HV127   
label values hv127_21 HV127   
label values hv127_22 HV127   
label values hv127_23 HV127   
label values hv127_24 HV127   
label values hv128_01 HV128   
label values hv128_02 HV128   
label values hv128_03 HV128   
label values hv128_04 HV128   
label values hv128_05 HV128   
label values hv128_06 HV128   
label values hv128_07 HV128   
label values hv128_08 HV128   
label values hv128_09 HV128   
label values hv128_10 HV128   
label values hv128_11 HV128   
label values hv128_12 HV128   
label values hv128_13 HV128   
label values hv128_14 HV128   
label values hv128_15 HV128   
label values hv128_16 HV128   
label values hv128_17 HV128   
label values hv128_18 HV128   
label values hv128_19 HV128   
label values hv128_20 HV128   
label values hv128_21 HV128   
label values hv128_22 HV128   
label values hv128_23 HV128   
label values hv128_24 HV128   
label values hv129_01 HV129   
label values hv129_02 HV129   
label values hv129_03 HV129   
label values hv129_04 HV129   
label values hv129_05 HV129   
label values hv129_06 HV129   
label values hv129_07 HV129   
label values hv129_08 HV129   
label values hv129_09 HV129   
label values hv129_10 HV129   
label values hv129_11 HV129   
label values hv129_12 HV129   
label values hv129_13 HV129   
label values hv129_14 HV129   
label values hv129_15 HV129   
label values hv129_16 HV129   
label values hv129_17 HV129   
label values hv129_18 HV129   
label values hv129_19 HV129   
label values hv129_20 HV129   
label values hv129_21 HV129   
label values hv129_22 HV129   
label values hv129_23 HV129   
label values hv129_24 HV129   
label values hv140_01 HV140   
label values hv140_02 HV140   
label values hv140_03 HV140   
label values hv140_04 HV140   
label values hv140_05 HV140   
label values hv140_06 HV140   
label values hv140_07 HV140   
label values hv140_08 HV140   
label values hv140_09 HV140   
label values hv140_10 HV140   
label values hv140_11 HV140   
label values hv140_12 HV140   
label values hv140_13 HV140   
label values hv140_14 HV140   
label values hv140_15 HV140   
label values hv140_16 HV140   
label values hv140_17 HV140   
label values hv140_18 HV140   
label values hv140_19 HV140   
label values hv140_20 HV140   
label values hv140_21 HV140   
label values hv140_22 HV140   
label values hv140_23 HV140   
label values hv140_24 HV140   
label values sh16_01  SH16    
label values sh16_02  SH16    
label values sh16_03  SH16    
label values sh16_04  SH16    
label values sh16_05  SH16    
label values sh16_06  SH16    
label values sh16_07  SH16    
label values sh16_08  SH16    
label values sh16_09  SH16    
label values sh16_10  SH16    
label values sh16_11  SH16    
label values sh16_12  SH16    
label values sh16_13  SH16    
label values sh16_14  SH16    
label values sh16_15  SH16    
label values sh16_16  SH16    
label values sh16_17  SH16    
label values sh16_18  SH16    
label values sh16_19  SH16    
label values sh16_20  SH16    
label values sh16_21  SH16    
label values sh16_22  SH16    
label values sh16_23  SH16    
label values sh16_24  SH16    
label values sh17a_01 SH17A   
label values sh17a_02 SH17A   
label values sh17a_03 SH17A   
label values sh17a_04 SH17A   
label values sh17a_05 SH17A   
label values sh17a_06 SH17A   
label values sh17a_07 SH17A   
label values sh17a_08 SH17A   
label values sh17a_09 SH17A   
label values sh17a_10 SH17A   
label values sh17a_11 SH17A   
label values sh17a_12 SH17A   
label values sh17a_13 SH17A   
label values sh17a_14 SH17A   
label values sh17a_15 SH17A   
label values sh17a_16 SH17A   
label values sh17a_17 SH17A   
label values sh17a_18 SH17A   
label values sh17a_19 SH17A   
label values sh17a_20 SH17A   
label values sh17a_21 SH17A   
label values sh17a_22 SH17A   
label values sh17a_23 SH17A   
label values sh17a_24 SH17A   
label values sh17b_01 SH17B   
label values sh17b_02 SH17B   
label values sh17b_03 SH17B   
label values sh17b_04 SH17B   
label values sh17b_05 SH17B   
label values sh17b_06 SH17B   
label values sh17b_07 SH17B   
label values sh17b_08 SH17B   
label values sh17b_09 SH17B   
label values sh17b_10 SH17B   
label values sh17b_11 SH17B   
label values sh17b_12 SH17B   
label values sh17b_13 SH17B   
label values sh17b_14 SH17B   
label values sh17b_15 SH17B   
label values sh17b_16 SH17B   
label values sh17b_17 SH17B   
label values sh17b_18 SH17B   
label values sh17b_19 SH17B   
label values sh17b_20 SH17B   
label values sh17b_21 SH17B   
label values sh17b_22 SH17B   
label values sh17b_23 SH17B   
label values sh17b_24 SH17B   
label values sh18_01  SH18    
label values sh18_02  SH18    
label values sh18_03  SH18    
label values sh18_04  SH18    
label values sh18_05  SH18    
label values sh18_06  SH18    
label values sh18_07  SH18    
label values sh18_08  SH18    
label values sh18_09  SH18    
label values sh18_10  SH18    
label values sh18_11  SH18    
label values sh18_12  SH18    
label values sh18_13  SH18    
label values sh18_14  SH18    
label values sh18_15  SH18    
label values sh18_16  SH18    
label values sh18_17  SH18    
label values sh18_18  SH18    
label values sh18_19  SH18    
label values sh18_20  SH18    
label values sh18_21  SH18    
label values sh18_22  SH18    
label values sh18_23  SH18    
label values sh18_24  SH18    
label values sh19a_01 SH19A   
label values sh19a_02 SH19A   
label values sh19a_03 SH19A   
label values sh19a_04 SH19A   
label values sh19a_05 SH19A   
label values sh19a_06 SH19A   
label values sh19a_07 SH19A   
label values sh19a_08 SH19A   
label values sh19a_09 SH19A   
label values sh19a_10 SH19A   
label values sh19a_11 SH19A   
label values sh19a_12 SH19A   
label values sh19a_13 SH19A   
label values sh19a_14 SH19A   
label values sh19a_15 SH19A   
label values sh19a_16 SH19A   
label values sh19a_17 SH19A   
label values sh19a_18 SH19A   
label values sh19a_19 SH19A   
label values sh19a_20 SH19A   
label values sh19a_21 SH19A   
label values sh19a_22 SH19A   
label values sh19a_23 SH19A   
label values sh19a_24 SH19A   
label values sh19b_01 SH19B   
label values sh19b_02 SH19B   
label values sh19b_03 SH19B   
label values sh19b_04 SH19B   
label values sh19b_05 SH19B   
label values sh19b_06 SH19B   
label values sh19b_07 SH19B   
label values sh19b_08 SH19B   
label values sh19b_09 SH19B   
label values sh19b_10 SH19B   
label values sh19b_11 SH19B   
label values sh19b_12 SH19B   
label values sh19b_13 SH19B   
label values sh19b_14 SH19B   
label values sh19b_15 SH19B   
label values sh19b_16 SH19B   
label values sh19b_17 SH19B   
label values sh19b_18 SH19B   
label values sh19b_19 SH19B   
label values sh19b_20 SH19B   
label values sh19b_21 SH19B   
label values sh19b_22 SH19B   
label values sh19b_23 SH19B   
label values sh19b_24 SH19B   
label values ha2_1    HA2     
label values ha2_2    HA2     
label values ha3_1    HA3     
label values ha3_2    HA3     
label values ha4_1    HA4     
label values ha4_2    HA4     
label values ha5_1    HA5     
label values ha5_2    HA5     
label values ha6_1    HA6     
label values ha6_2    HA6     
label values ha11_1   HA11    
label values ha11_2   HA11    
label values ha12_1   HA12    
label values ha12_2   HA12    
label values ha12a_1  HA12A   
label values ha12a_2  HA12A   
label values ha12b_1  HA12B   
label values ha12b_2  HA12B   
label values ha13_1   HA13    
label values ha13_2   HA13    
label values ha33_1   HA33    
label values ha33_2   HA33    
label values ha35_1   HA35    
label values ha35_2   HA35    
label values ha40_1   HA40    
label values ha40_2   HA40    
label values ha41_1   HA41    
label values ha41_2   HA41    
label values ha50_1   HA50    
label values ha50_2   HA50    
label values ha51_1   HA51    
label values ha51_2   HA51    
label values ha52_1   HA52    
label values ha52_2   HA52    
label values ha53_1   HA53    
label values ha53_2   HA53    
label values ha54_1   HA54    
label values ha54_2   HA54    
label values ha55_1   HA55    
label values ha55_2   HA55    
label values ha56_1   HA56    
label values ha56_2   HA56    
label values ha57_1   HA57    
label values ha57_2   HA57    
label values ha58_1   HA58    
label values ha58_2   HA58    
label values ha60_1   HA60    
label values ha60_2   HA60    
label values ha61_1   HA61    
label values ha61_2   HA61    
label values ha63_1   HA63    
label values ha63_2   HA63    
label values ha64_1   HA64    
label values ha64_2   HA64    
label values ha65_1   HA65    
label values ha65_2   HA65    
label values ha66_1   HA66    
label values ha66_2   HA66    
label values ha67_1   HA67    
label values ha67_2   HA67    
label values ha68_1   HA68    
label values ha68_2   HA68    
label values hc2_1    HC2     
label values hc2_2    HC2     
label values hc2_3    HC2     
label values hc2_4    HC2     
label values hc2_5    HC2     
label values hc3_1    HC3     
label values hc3_2    HC3     
label values hc3_3    HC3     
label values hc3_4    HC3     
label values hc3_5    HC3     
label values hc4_1    HC4     
label values hc4_2    HC4     
label values hc4_3    HC4     
label values hc4_4    HC4     
label values hc4_5    HC4     
label values hc5_1    HC5     
label values hc5_2    HC5     
label values hc5_3    HC5     
label values hc5_4    HC5     
label values hc5_5    HC5     
label values hc6_1    HC6     
label values hc6_2    HC6     
label values hc6_3    HC6     
label values hc6_4    HC6     
label values hc6_5    HC6     
label values hc7_1    HC7     
label values hc7_2    HC7     
label values hc7_3    HC7     
label values hc7_4    HC7     
label values hc7_5    HC7     
label values hc8_1    HC8     
label values hc8_2    HC8     
label values hc8_3    HC8     
label values hc8_4    HC8     
label values hc8_5    HC8     
label values hc9_1    HC9     
label values hc9_2    HC9     
label values hc9_3    HC9     
label values hc9_4    HC9     
label values hc9_5    HC9     
label values hc10_1   HC10    
label values hc10_2   HC10    
label values hc10_3   HC10    
label values hc10_4   HC10    
label values hc10_5   HC10    
label values hc11_1   HC11    
label values hc11_2   HC11    
label values hc11_3   HC11    
label values hc11_4   HC11    
label values hc11_5   HC11    
label values hc12_1   HC12    
label values hc12_2   HC12    
label values hc12_3   HC12    
label values hc12_4   HC12    
label values hc12_5   HC12    
label values hc13_1   HC13    
label values hc13_2   HC13    
label values hc13_3   HC13    
label values hc13_4   HC13    
label values hc13_5   HC13    
label values hc15_1   HC15    
label values hc15_2   HC15    
label values hc15_3   HC15    
label values hc15_4   HC15    
label values hc15_5   HC15    
label values hc16_1   HC16    
label values hc16_2   HC16    
label values hc16_3   HC16    
label values hc16_4   HC16    
label values hc16_5   HC16    
label values hc27_1   HC27    
label values hc27_2   HC27    
label values hc27_3   HC27    
label values hc27_4   HC27    
label values hc27_5   HC27    
label values hc30_1   HC30    
label values hc30_2   HC30    
label values hc30_3   HC30    
label values hc30_4   HC30    
label values hc30_5   HC30    
label values hc31_1   HC31    
label values hc31_2   HC31    
label values hc31_3   HC31    
label values hc31_4   HC31    
label values hc31_5   HC31    
label values hc33_1   HC33    
label values hc33_2   HC33    
label values hc33_3   HC33    
label values hc33_4   HC33    
label values hc33_5   HC33    
label values hc51_1   HC51    
label values hc51_2   HC51    
label values hc51_3   HC51    
label values hc51_4   HC51    
label values hc51_5   HC51    
label values hc52_1   HC52    
label values hc52_2   HC52    
label values hc52_3   HC52    
label values hc52_4   HC52    
label values hc52_5   HC52    
label values hc53_1   HC53    
label values hc53_2   HC53    
label values hc53_3   HC53    
label values hc53_4   HC53    
label values hc53_5   HC53    
label values hc55_1   HC55    
label values hc55_2   HC55    
label values hc55_3   HC55    
label values hc55_4   HC55    
label values hc55_5   HC55    
label values hc56_1   HC56    
label values hc56_2   HC56    
label values hc56_3   HC56    
label values hc56_4   HC56    
label values hc56_5   HC56    
label values hc57_1   HC57    
label values hc57_2   HC57    
label values hc57_3   HC57    
label values hc57_4   HC57    
label values hc57_5   HC57    
label values hc58_1   HC58    
label values hc58_2   HC58    
label values hc58_3   HC58    
label values hc58_4   HC58    
label values hc58_5   HC58    
label values hc60_1   HC60    
label values hc60_2   HC60    
label values hc60_3   HC60    
label values hc60_4   HC60    
label values hc60_5   HC60    
label values hc61_1   HC61    
label values hc61_2   HC61    
label values hc61_3   HC61    
label values hc61_4   HC61    
label values hc61_5   HC61    
label values hc62_1   HC62    
label values hc62_2   HC62    
label values hc62_3   HC62    
label values hc62_4   HC62    
label values hc62_5   HC62    
label values hc68_1   HC68    
label values hc68_2   HC68    
label values hc68_3   HC68    
label values hc68_4   HC68    
label values hc68_5   HC68    
label values hc70_1   HC70    
label values hc70_2   HC70    
label values hc70_3   HC70    
label values hc70_4   HC70    
label values hc70_5   HC70    
label values hc71_1   HC71    
label values hc71_2   HC71    
label values hc71_3   HC71    
label values hc71_4   HC71    
label values hc71_5   HC71    
label values hc72_1   HC72    
label values hc72_2   HC72    
label values hc72_3   HC72    
label values hc72_4   HC72    
label values hc72_5   HC72    
label values hc73_1   HC73    
label values hc73_2   HC73    
label values hc73_3   HC73    
label values hc73_4   HC73    
label values hc73_5   HC73    
label values hc2a_1   HC2A    
label values hc2a_2   HC2A    
label values hc2a_3   HC2A    
label values hc2a_4   HC2A    
label values hc2a_5   HC2A    
label values hc3a_1   HC3A    
label values hc3a_2   HC3A    
label values hc3a_3   HC3A    
label values hc3a_4   HC3A    
label values hc3a_5   HC3A    
label values hc15a_1  HC15A   
label values hc15a_2  HC15A   
label values hc15a_3  HC15A   
label values hc15a_4  HC15A   
label values hc15a_5  HC15A   
label values hc2b_1   HC2B    
label values hc2b_2   HC2B    
label values hc2b_3   HC2B    
label values hc2b_4   HC2B    
label values hc2b_5   HC2B    
label values hc3b_1   HC3B    
label values hc3b_2   HC3B    
label values hc3b_3   HC3B    
label values hc3b_4   HC3B    
label values hc3b_5   HC3B    
label values hc15b_1  HC15B   
label values hc15b_2  HC15B   
label values hc15b_3  HC15B   
label values hc15b_4  HC15B   
label values hc15b_5  HC15B   
label values hc35_1   HC35    
label values hc35_2   HC35    
label values hc35_3   HC35    
label values hc35_4   HC35    
label values hc35_5   HC35    
