infix using "C:\COUNTRIES\NG71\NGKR71FL.dct"

label variable caseid   "Case Identification"
label variable hidx     "Index to birth history"
label variable v000     "Country code and phase"
label variable v001     "Cluster number"
label variable v002     "Household number"
label variable v003     "Respondent's line number"
label variable v004     "Ultimate area unit"
label variable v005     "Women's individual sample weight (6 decimals)"
label variable v006     "Month of interview"
label variable v007     "Year of interview"
label variable v008     "Date of interview (CMC)"
label variable v009     "Respondent's month of birth"
label variable v010     "Respondent's year of birth"
label variable v011     "Date of birth (CMC)"
label variable v012     "Respondent's current age"
label variable v013     "Age in 5-year groups"
label variable v014     "Completeness of age information"
label variable v015     "Result of individual interview"
label variable v016     "Day of interview"
label variable v017     "NA - CMC start of calendar"
label variable v018     "NA - Row of month of interview"
label variable v019     "NA - Length of calendar"
label variable v019a    "NA - Number of calendar columns"
label variable v020     "Ever-married sample"
label variable v021     "Primary sampling unit"
label variable v022     "Sample strata for sampling errors"
label variable v023     "Stratification used in sample design"
label variable v024     "Region"
label variable v025     "Type of place of residence"
label variable v026     "NA - De facto place of residence"
label variable v027     "Number of visits"
label variable v028     "Interviewer identification"
label variable v029     "NA - Keyer identification"
label variable v030     "Field supervisor"
label variable v031     "NA - Field editor"
label variable v032     "NA - Office editor"
label variable v034     "NA - Line number of husband"
label variable v040     "Cluster altitude in meters"
label variable v042     "Household selected for hemoglobin"
label variable v044     "NA - Selected for Domestic Violence module"
label variable v101     "Region"
label variable v102     "Type of place of residence"
label variable v103     "NA - Childhood place of residence"
label variable v104     "NA - Years lived in place of residence"
label variable v105     "NA - Type of place of previous residence"
label variable v106     "Highest educational level"
label variable v107     "Highest year of education"
label variable v113     "Source of drinking water"
label variable v115     "Time to get to water source"
label variable v116     "Type of toilet facility"
label variable v119     "Household has: electricity"
label variable v120     "Household has: radio"
label variable v121     "Household has: television"
label variable v122     "Household has: refrigerator"
label variable v123     "Household has: bicycle"
label variable v124     "Household has: motorcycle/scooter"
label variable v125     "Household has: car/truck"
label variable v127     "Main floor material"
label variable v128     "Main wall material"
label variable v129     "Main roof material"
label variable v130     "Religion"
label variable v131     "Ethnicity"
label variable v133     "Education in single years"
label variable v134     "NA - De facto place of residence"
label variable v135     "Usual resident or visitor"
label variable v136     "Number of household members (listed)"
label variable v137     "Number of children 5 and under in household (de jure)"
label variable v138     "Number of eligible women in household (de facto)"
label variable v139     "De jure region of residence"
label variable v140     "De jure type of place of residence"
label variable v141     "NA - De jure place of residence"
label variable v149     "Educational attainment"
label variable v150     "Relationship to household head"
label variable v151     "Sex of household head"
label variable v152     "Age of household head"
label variable v153     "Household has: telephone (land-line)"
label variable awfactt  "All woman factor - total"
label variable awfactu  "All woman factor - urban/rural"
label variable awfactr  "All woman factor - regional"
label variable awfacte  "All woman factor - educational"
label variable awfactw  "All woman factor - wealth index"
label variable v155     "Literacy"
label variable v156     "NA - Ever participated in a literacy program outside of primary"
label variable v157     "NA - Frequency of reading newspaper or magazine"
label variable v158     "NA - Frequency of listening to radio"
label variable v159     "NA - Frequency of watching television"
label variable v160     "Toilet facilities shared with other households"
label variable v161     "Type of cooking fuel"
label variable v166     "NA - Result of salt test for iodine"
label variable v167     "NA - Number of trips in last 12 months"
label variable v168     "NA - Away for more than one month in last 12 months"
label variable v190     "Wealth index"
label variable v191     "Wealth index factor score (5 decimals)"
label variable v190a    "Wealth index for urban/rural"
label variable v191a    "Wealth index factor score for urban/rural (5 decimals)"
label variable ml101    "Type of mosquito bed net(s) slept under last night"
label variable v201     "Total children ever born"
label variable v202     "Sons at home"
label variable v203     "Daughters at home"
label variable v204     "Sons elsewhere"
label variable v205     "Daughters elsewhere"
label variable v206     "Sons who have died"
label variable v207     "Daughters who have died"
label variable v208     "Births in last five years"
label variable v209     "Births in past year"
label variable v210     "Births in month of interview"
label variable v211     "NA - Date of first birth (CMC)"
label variable v212     "NA - Age of respondent at 1st birth"
label variable v213     "Currently pregnant"
label variable v214     "Duration of current pregnancy"
label variable v215     "NA - Time since last menstrual period"
label variable v216     "NA - Menstruated in last six weeks"
label variable v217     "NA - Knowledge of ovulatory cycle"
label variable v218     "Number of living children"
label variable v219     "Living children + current pregnancy"
label variable v220     "Living children + current pregnancy (grouped)"
label variable v221     "NA - Marriage to first birth interval (months)"
label variable v222     "NA - Last birth to interview (months)"
label variable v223     "Completeness of current pregnancy information"
label variable v224     "Entries in birth history"
label variable v225     "NA - Current pregnancy wanted"
label variable v226     "NA - Time since last period (comp) (months)"
label variable v227     "NA - Flag for last period"
label variable v228     "NA - Ever had a terminated pregnancy"
label variable v229     "NA - Month pregnancy ended"
label variable v230     "NA - Year pregnancy ended"
label variable v231     "NA - CMC pregnancy ended"
label variable v232     "NA - Completeness of last termination information"
label variable v233     "NA - Months when pregnancy ended"
label variable v234     "NA - Other such pregnancies"
label variable v235     "NA - Index last child prior to maternity-health (calendar)"
label variable v237     "Birth between last and interview"
label variable v238     "Births in last three years"
label variable v239     "NA - Pregnancies terminated before calendar beginning"
label variable v240     "NA - Month of last termination prior to calendar"
label variable v241     "NA - Year of last termination prior to calendar"
label variable v242     "NA - CMC termination ended prior to calendar"
label variable v243     "NA - Completeness of last termination date prior to calendar"
label variable v401     "NA - Last birth a caesarean section"
label variable v404     "NA - Currently breastfeeding"
label variable v405     "NA - Currently amenorrheic"
label variable v406     "NA - Currently abstaining"
label variable v407     "NA - Number of times breastfed during night"
label variable v408     "NA - Number of times breastfed during day"
label variable v409     "NA - Gave child plain water"
label variable v409a    "NA - Gave child sugar water"
label variable v410     "NA - Gave child juice"
label variable v410a    "NA - Gave child tea or coffee"
label variable v411     "NA - Gave child tinned, powdered or fresh milk"
label variable v411a    "NA - Gave child baby formula"
label variable v412     "NA - Gave child fresh milk"
label variable v412a    "NA - Gave child fortified baby food (cerelac, etc)"
label variable v412b    "NA - Gave child other porridge/gruel"
label variable v412c    "NA - Gave child soup/clear broth"
label variable v413     "NA - Gave child other liquid"
label variable v413a    "NA - Gave child CS liquid"
label variable v413b    "NA - Gave child CS liquid"
label variable v413c    "NA - Gave child CS liquid"
label variable v413d    "NA - Gave child CS liquid"
label variable v414a    "NA - Gave child CS foods"
label variable v414b    "NA - Gave child CS foods"
label variable v414c    "NA - Gave child CS foods"
label variable v414d    "NA - Gave child CS foods"
label variable v414e    "NA - Gave child bread, noodles, other made from grains"
label variable v414f    "NA - Gave child potatoes, cassava, or other tubers"
label variable v414g    "NA - Gave child eggs"
label variable v414h    "NA - Gave child meat (beef, pork, lamb, chicken, etc)"
label variable v414i    "NA - Gave child pumpkin, carrots, squash (yellow or orange inside)"
label variable v414j    "NA - Gave child any dark green leafy vegetables"
label variable v414k    "NA - Gave child mangoes, papayas, other vitamin A fruits"
label variable v414l    "NA - Gave child any other fruits"
label variable v414m    "NA - Gave child liver, heart, other organs"
label variable v414n    "NA - Gave child fish or shellfish"
label variable v414o    "NA - Gave child food made from beans, peas, lentils, nuts"
label variable v414p    "NA - Gave child cheese, yogurt, other milk products"
label variable v414q    "NA - Gave child oil, fats, butter, products made of them"
label variable v414r    "NA - Gave child chocolates, sweets, candies, pastries, etc"
label variable v414s    "NA - Gave child other solid-semisolid food"
label variable v414t    "NA - Gave child CS foods"
label variable v414u    "NA - Gave child CS foods"
label variable v414v    "NA - Gave child yogurt"
label variable v414w    "NA - Gave child CS foods"
label variable v415     "NA - Drank from bottle with nipple yesterday/last night"
label variable v416     "NA - Heard of oral rehydration"
label variable v417     "Entries in maternity table"
label variable v418     "Entries in health table"
label variable v419     "Entries in height/weight table"
label variable v420     "NA - Measurer's code"
label variable v421     "NA - Assistant measurer's code"
label variable v426     "NA - When child put to breast"
label variable v437     "NA - Respondent's weight in kilograms (1 decimal)"
label variable v438     "NA - Respondent's height in centimeters (1 decimal)"
label variable v439     "NA - Height/Age percentile"
label variable v440     "NA - Height/Age standard deviation"
label variable v441     "NA - Height/Age percent ref. median"
label variable v442     "NA - Weight/Height percent ref. median (DHS)"
label variable v443     "NA - Weight/Height percent ref. median (Fog)"
label variable v444     "NA - Weight/Height percent ref. median (WHO)"
label variable v444a    "NA - Weight/Height standard deviation (DHS)"
label variable v445     "NA - Body Mass Index"
label variable v446     "NA - Rohrer's index"
label variable v447     "NA - Result of measurement - height/weight"
label variable v447a    "NA - Women's age in years (from household questionnaire)"
label variable v452a    "NA - Under age 18 (from household questionnaire)"
label variable v452b    "NA - Line number of parent/caretaker"
label variable v452c    "NA - Read consent statement - hemoglobin"
label variable v453     "NA - Hemoglobin level (g/dl - 1 decimal)"
label variable v454     "NA - Currently pregnant (from household questionnaire)"
label variable v455     "NA - Result of measurement - hemoglobin"
label variable v456     "NA - Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable v457     "NA - Anemia level"
label variable v458     "NA - Agrees to referral - anemia"
label variable v459     "Have mosquito bed net for sleeping (from household questionnaire)"
label variable v460     "Children under 5 slept under mosquito bed net last night (household questionnair"
label variable v461     "Respondent slept under mosquito bed net"
label variable v462     "NA - Washed hands before preparing last meal"
label variable v463a    "NA - Smokes cigarettes"
label variable v463b    "NA - Smokes pipe"
label variable v463c    "NA - Uses chewing tobacco"
label variable v463d    "NA - Uses snuff"
label variable v463e    "NA - Smokes cigars"
label variable v463f    "NA - Smokes country specific"
label variable v463g    "NA - Smokes country specific"
label variable v463x    "NA - Smokes other"
label variable v463z    "NA - Does not use tobacco"
label variable v464     "NA - Number of cigarettes in last 24 hours"
label variable v465     "NA - Disposal of youngest child's stools when not using toilet"
label variable v466     "NA - When child is seriously ill, can decide whether medical treatment sought"
label variable v467a    "NA - Getting medical help for self: know where to go"
label variable v467b    "NA - Getting medical help for self: getting permission to go"
label variable v467c    "NA - Getting medical help for self: getting money needed for treatment"
label variable v467d    "NA - Getting medical help for self: distance to health facility"
label variable v467e    "NA - Getting medical help for self: having to take transport"
label variable v467f    "NA - Getting medical help for self: not wanting to go alone"
label variable v467g    "NA - Getting medical help for self: concern no female health provider"
label variable v467h    "NA - Getting medical help for self: concern no provider"
label variable v467i    "NA - Getting medical help for self: concern no drugs available"
label variable v467j    "NA - Getting medical help for self: CS"
label variable v467k    "NA - Getting medical help for self: CS"
label variable v467l    "NA - Getting medical help for self: CS"
label variable v467m    "NA - Getting medical help for self: CS"
label variable v468     "NA - Record for Last Birth"
label variable v469e    "NA - Times gave child powdered/tinned/fresh milk"
label variable v469f    "NA - Times gave child infant formula"
label variable v469x    "NA - Times gave child yogurt"
label variable v471a    "NA - Mother had tinned, powdered or fresh milk"
label variable v471b    "NA - Mother had tea or coffee"
label variable v471c    "NA - Mother had any other liquid"
label variable v471d    "NA - Mother had CS liquid"
label variable v471e    "NA - Mother had CS liquid"
label variable v471f    "NA - Mother had CS liquid"
label variable v471g    "NA - Mother had CS liquid"
label variable v472a    "NA - Mother had CS foods"
label variable v472b    "NA - Mother had CS foods"
label variable v472c    "NA - Mother had CS foods"
label variable v472d    "NA - Mother had CS foods"
label variable v472e    "NA - Mother had bread, noodles, other made from grains"
label variable v472f    "NA - Mother had potatoes, cassava, or other tubers"
label variable v472g    "NA - Mother had eggs"
label variable v472h    "NA - Mother had meat (beef, pork, lamb, chicken, etc)"
label variable v472i    "NA - Mother had pumpkin, carrots, squash (yellow or orange inside)"
label variable v472j    "NA - Mother had any dark green leafy vegetables"
label variable v472k    "NA - Mother had mangoes, papayas, other vitamin A fruits"
label variable v472l    "NA - Mother had any other fruits"
label variable v472m    "NA - Mother had liver, heart, other organs"
label variable v472n    "NA - Mother had fish or shellfish"
label variable v472o    "NA - Mother had food made from beans, peas, lentils, nuts"
label variable v472p    "NA - Mother had cheese, yogurt, other milk products"
label variable v472q    "NA - Mother had oil, fats, butter, products made of them"
label variable v472r    "NA - Mother had chocolates, sweets, candies, pastries, etc"
label variable v472s    "NA - Mother had other solid-semisolid food"
label variable v472t    "NA - Mother had CS foods"
label variable v472u    "NA - Mother had CS foods"
label variable v473a    "NA - Read consent statement - HIV"
label variable v473b    "NA - Result of measurement - HIV"
label variable v474     "NA - Heard of tuberculosis or TB"
label variable v474a    "NA - Tuberculosis spread by: air when coughing or sneezing"
label variable v474b    "NA - Tuberculosis spread by: sharing utensils"
label variable v474c    "NA - Tuberculosis spread by: touching a person with TB"
label variable v474d    "NA - Tuberculosis spread by: food"
label variable v474e    "NA - Tuberculosis spread by: sexual contact"
label variable v474f    "NA - Tuberculosis spread by: mosquito bites"
label variable v474g    "NA - Tuberculosis spread by: CS"
label variable v474h    "NA - Tuberculosis spread by: CS"
label variable v474i    "NA - Tuberculosis spread by: CS"
label variable v474j    "NA - Tuberculosis spread by: CS"
label variable v474x    "NA - Tuberculosis spread by: other"
label variable v474z    "NA - Tuberculosis spread by: don't know"
label variable v475     "NA - Tuberculosis can be cured"
label variable v476     "NA - Keep secret when family member gets TB"
label variable v477     "NA - Number of injections in last 12 months"
label variable v478     "NA - Number of injections administered by a health worker"
label variable v479     "NA - Place of injection by health worker"
label variable v480     "NA - Syringe and needle from new, unopened package"
label variable v481     "NA - Covered by health insurance"
label variable v481a    "NA - Health insurance type: mutual/community organization"
label variable v481b    "NA - Health insurance type: provided by employer"
label variable v481c    "NA - Health insurance type: social security"
label variable v481d    "NA - Health insurance type: private/commercially purchased"
label variable v481e    "NA - Health insurance type: CS"
label variable v481f    "NA - Health insurance type: CS"
label variable v481g    "NA - Health insurance type: CS"
label variable v481h    "NA - Health insurance type: CS"
label variable v481x    "NA - Health insurance type: other"
label variable v482a    "NA - Arrange care of biological children under age 18"
label variable v482b    "NA - Primary caregiver of children under age 18"
label variable v482c    "NA - Arrange care of non-biological children < 18"
label variable bidx     "Birth column number"
label variable bord     "Birth order number"
label variable b0       "Child is twin"
label variable b1       "Month of birth"
label variable b2       "Year of birth"
label variable b3       "Date of birth (CMC)"
label variable b4       "Sex of child"
label variable b5       "Child is alive"
label variable b6       "NA - Age at death"
label variable b7       "NA - Age at death (months, imputed)"
label variable b8       "Current age of child"
label variable b9       "Child lives with whom"
label variable b10      "Completeness of information"
label variable b11      "Preceding birth interval (months)"
label variable b12      "Succeeding birth interval (months)"
label variable b13      "NA - Flag for age at death"
label variable b15      "Live birth between births"
label variable b16      "Child's line number in household"
label variable midx     "Index to Birth History"
label variable m1       "NA - Number of tetanus injections before birth"
label variable m1a      "NA - Number of tetanus injections before pregnancy"
label variable m1b      "NA - Month of last tetanus injection before pregnancy"
label variable m1c      "NA - Year of last tetanus injection before pregnancy"
label variable m1d      "NA - Years ago received last tetanus injection before pregnancy"
label variable m1e      "NA - Last tetanus injection before pregnancy (CMC)"
label variable m2a      "Prenatal: doctor"
label variable m2b      "Prenatal: nurse/midwife"
label variable m2c      "Prenatal: auxillary midwife"
label variable m2d      "Prenatal: community health extension worker (CHEW)"
label variable m2e      "NA - Prenatal: CS health professional"
label variable m2f      "NA - Prenatal: CS health professional"
label variable m2g      "Prenatal: traditional birth attendant"
label variable m2h      "Prenatal: village health worker (VHW)"
label variable m2i      "Prenatal: rural model caregiver (RMC)"
label variable m2j      "Prenatal: community directed distributor (CDD)"
label variable m2k      "Prenatal: other"
label variable m2l      "NA - Prenatal: CS other"
label variable m2m      "NA - Prenatal: CS other"
label variable m2n      "Prenatal: no one"
label variable m3a      "NA - Assistance: doctor"
label variable m3b      "NA - Assistance: CS health professional"
label variable m3c      "NA - Assistance: CS health professional"
label variable m3d      "NA - Assistance: CS health professional"
label variable m3e      "NA - Assistance: CS health professional"
label variable m3f      "NA - Assistance: CS health professional"
label variable m3g      "NA - Assistance: traditional birth attendant"
label variable m3h      "NA - Assistance: CS other person"
label variable m3i      "NA - Assistance: CS other person"
label variable m3j      "NA - Assistance: CS other person"
label variable m3k      "NA - Assistance: other"
label variable m3l      "NA - Assistance: CS other"
label variable m3m      "NA - Assistance: CS other"
label variable m3n      "NA - Assistance: no one"
label variable m4       "NA - Duration of breastfeeding"
label variable m5       "NA - Months of breastfeeding"
label variable m6       "NA - Duration of amenorrhea"
label variable m7       "NA - Months of amenorrhea"
label variable m8       "NA - Duration of abstinence"
label variable m9       "NA - Months of abstinence"
label variable m10      "NA - Wanted pregnancy when became pregnant"
label variable m11      "NA - Desired time would have waited"
label variable m13      "NA - Timing of 1st antenatal check (months)"
label variable m14      "NA - Number of antenatal visits during pregnancy"
label variable m15      "NA - Place of delivery"
label variable m17      "NA - Delivery by caesarean section"
label variable m18      "NA - Size of child at birth"
label variable m19      "NA - Birth weight in kilograms (3 decimals)"
label variable m19a     "NA - Weight at birth/recall"
label variable m27      "NA - Flag for breastfeeding"
label variable m28      "NA - Flag for amenorrhea"
label variable m29      "NA - Flag for abstinence"
label variable m34      "NA - When child put to breast"
label variable m35      "NA - Number of times breastfed during previous night"
label variable m36      "NA - Number of times breastfed during previous day"
label variable m38      "NA - Drank from bottle with nipple yesterday/last night"
label variable m39a     "NA - Did eat any solid, semi-solid or soft foods yesterday"
label variable m39      "NA - Number of times ate solid, semi-solid or soft food yesterday"
label variable m42a     "NA - During pregnancy: weighed"
label variable m42b     "NA - During pregnancy: height measured"
label variable m42c     "NA - During pregnancy: blood pressure taken"
label variable m42d     "NA - During pregnancy: urine sample taken"
label variable m42e     "NA - During pregnancy: blood sample taken"
label variable m43      "NA - Told about pregnancy complications"
label variable m44      "NA - Told where to go for pregnancy complications"
label variable m45      "NA - During pregnancy, given or bought iron tablets/syrup"
label variable m46      "NA - Days tablets or syrup taken"
label variable m47      "NA - During pregnancy, had difficulty with daylight vision"
label variable m48      "NA - During pregnancy, had difficulty with night blindness"
label variable m49a     "During pregnancy took: SP/fansidar for malaria"
label variable m49b     "NA - During pregnancy took: chloroquine for malaria"
label variable m49c     "NA - During pregnancy took: CS drug for malaria"
label variable m49d     "NA - During pregnancy took: CS drug for malaria"
label variable m49e     "NA - During pregnancy took: CS drug for malaria"
label variable m49f     "NA - During pregnancy took: CS drug for malaria"
label variable m49g     "NA - During pregnancy took: CS drug for malaria"
label variable m49x     "NA - During pregnancy took: other drug for malaria"
label variable m49z     "NA - During pregnancy took: don't know"
label variable m49y     "NA - During pregnancy took: no drug for malaria"
label variable m50      "NA - Respondent's check up after delivery"
label variable m51      "NA - Respondent's checkup after deliver timing"
label variable m52      "NA - Respondent's health professional checked up after delivery"
label variable m54      "NA - Received Vitamin A dose in first 2 months after delivery"
label variable m55a     "NA - First 3 days, given milk (other than breast milk)"
label variable m55b     "NA - First 3 days, given plain water"
label variable m55c     "NA - First 3 days, given sugar/glucose water"
label variable m55d     "NA - First 3 days, given gripe water"
label variable m55e     "NA - First 3 days, given sugar/salt solution"
label variable m55f     "NA - First 3 days, given fruit juice"
label variable m55g     "NA - First 3 days, given infant formula"
label variable m55h     "NA - First 3 days, given tea/infusions"
label variable m55i     "NA - First 3 days, given honey"
label variable m55j     "NA - First 3 days, given coffee"
label variable m55k     "NA - First 3 days, given country specific"
label variable m55l     "NA - First 3 days, given country specific"
label variable m55m     "NA - First 3 days, given country specific"
label variable m55n     "NA - First 3 days, given country specific"
label variable m55o     "NA - First 3 days, given country specific"
label variable m55x     "NA - First 3 days, given other"
label variable m55z     "NA - First 3 days, given nothing"
label variable m57a     "NA - Antenatal care: respondent's home"
label variable m57b     "NA - Antenatal care: other home"
label variable m57c     "NA - Antenatal care: CS home"
label variable m57d     "NA - Antenatal care: CS home"
label variable m57e     "NA - Antenatal care: government hospital"
label variable m57f     "NA - Antenatal care: CS public health"
label variable m57g     "NA - Antenatal care: CS public health"
label variable m57h     "NA - Antenatal care: CS public health"
label variable m57i     "NA - Antenatal care: CS public health"
label variable m57j     "NA - Antenatal care: CS public health"
label variable m57k     "NA - Antenatal care: CS public health"
label variable m57l     "NA - Antenatal care: CS public health"
label variable m57m     "NA - Antenatal care: private hospital/clinic"
label variable m57n     "NA - Antenatal care: CS private medical"
label variable m57o     "NA - Antenatal care: CS private medical"
label variable m57p     "NA - Antenatal care: CS private medical"
label variable m57q     "NA - Antenatal care: CS private medical"
label variable m57r     "NA - Antenatal care: CS private medical"
label variable m57s     "NA - Antenatal care: CS other"
label variable m57t     "NA - Antenatal care: CS other"
label variable m57u     "NA - Antenatal care: CS other"
label variable m57v     "NA - Antenatal care: CS other"
label variable m57x     "NA - Antenatal care: other"
label variable m60      "NA - Drugs for intestinal parasites during pregnancy"
label variable m61      "NA - Time spent at place of delivery"
label variable m62      "NA - Respondent's health checked before discharge"
label variable m65a     "NA - Reason didn't deliver at health facility: cost too much"
label variable m65b     "NA - Reason didn't deliver at health facility: facility not open"
label variable m65c     "NA - Reason didn't deliver at health facility: too far/no transport"
label variable m65d     "NA - Reason didn't deliver at health facility: don't trust facility/poor service"
label variable m65e     "NA - Reason didn't deliver at health facility: no female provider"
label variable m65f     "NA - Reason didn't deliver at health facility: husband/family didn't allow"
label variable m65g     "NA - Reason didn't deliver at health facility: not necessary"
label variable m65h     "NA - Reason didn't deliver at health facility: not customary"
label variable m65i     "NA - Reason didn't deliver at health facility: CS"
label variable m65j     "NA - Reason didn't deliver at health facility: CS"
label variable m65k     "NA - Reason didn't deliver at health facility: CS"
label variable m65l     "NA - Reason didn't deliver at health facility: CS"
label variable m65x     "NA - Reason didn't deliver at health facility: other"
label variable m66      "NA - Respondent's health checked after discharge/delivery at home"
label variable m70      "NA - Baby postnatal check within 2 months"
label variable m71      "NA - Time after delivery postnatal check took place"
label variable m72      "NA - Person who performed postnatal checkup"
label variable m73      "NA - Place baby was first checked"
label variable h1       "NA - Has health card"
label variable h2       "NA - Received BCG"
label variable h2d      "NA - BCG day"
label variable h2m      "NA - BCG month"
label variable h2y      "NA - BCG year"
label variable h3       "NA - Received DPT 1"
label variable h3d      "NA - DPT 1 day"
label variable h3m      "NA - DPT 1 month"
label variable h3y      "NA - DPT 1 year"
label variable h4       "NA - Received POLIO 1"
label variable h4d      "NA - POLIO 1 day"
label variable h4m      "NA - POLIO 1 month"
label variable h4y      "NA - POLIO 1 year"
label variable h5       "NA - Received DPT 2"
label variable h5d      "NA - DPT 2 day"
label variable h5m      "NA - DPT 2 month"
label variable h5y      "NA - DPT 2 year"
label variable h6       "NA - Received POLIO 2"
label variable h6d      "NA - POLIO 2 day"
label variable h6m      "NA - POLIO 2 month"
label variable h6y      "NA - POLIO 2 year"
label variable h7       "NA - Received DPT 3"
label variable h7d      "NA - DPT 3 day"
label variable h7m      "NA - DPT 3 month"
label variable h7y      "NA - DPT 3 year"
label variable h8       "NA - Received POLIO 3"
label variable h8d      "NA - POLIO 3 day"
label variable h8m      "NA - POLIO 3 month"
label variable h8y      "NA - POLIO 3 year"
label variable h9       "NA - Received MEASLES"
label variable h9d      "NA - MEASLES day"
label variable h9m      "NA - MEASLES month"
label variable h9y      "NA - MEASLES year"
label variable h0       "NA - Received POLIO 0"
label variable h0d      "NA - POLIO 0 day"
label variable h0m      "NA - POLIO 0 month"
label variable h0y      "NA - POLIO 0 year"
label variable h10      "NA - Ever had vaccination"
label variable h11      "NA - Had diarrhea recently"
label variable h11b     "NA - Blood in the stools"
label variable h12a     "NA - Diarrhea: government hospital"
label variable h12b     "NA - Diarrhea: CS public sector"
label variable h12c     "NA - Diarrhea: CS public sector"
label variable h12d     "NA - Diarrhea: CS public sector"
label variable h12e     "NA - Diarrhea: CS public sector"
label variable h12f     "NA - Diarrhea: CS public sector"
label variable h12g     "NA - Diarrhea: CS public sector"
label variable h12h     "NA - Diarrhea: CS public sector"
label variable h12i     "NA - Diarrhea: CS public sector"
label variable h12j     "NA - Diarrhea: private hospital/clinic"
label variable h12k     "NA - Diarrhea: private pharmacy"
label variable h12l     "NA - Diarrhea: private doctor"
label variable h12m     "NA - Diarrhea: CS private medical"
label variable h12n     "NA - Diarrhea: CS private medical"
label variable h12o     "NA - Diarrhea: CS private medical"
label variable h12p     "NA - Diarrhea: CS private medical"
label variable h12q     "NA - Diarrhea: CS private medical"
label variable h12r     "NA - Diarrhea: CS private medical"
label variable h12s     "NA - Diarrhea: CS other sector"
label variable h12t     "NA - Diarrhea: CS other sector"
label variable h12u     "NA - Diarrhea: CS other sector"
label variable h12v     "NA - Diarrhea: CS other sector"
label variable h12w     "NA - Diarrhea: CS other sector"
label variable h12x     "NA - Diarrhea: Other"
label variable h12y     "NA - Diarrhea: no treatment"
label variable h12z     "NA - Diarrhea: medical treatment"
label variable h13      "NA - Given oral rehydration"
label variable h13b     "NA - Given pre-packaged ORS liquid"
label variable h14      "NA - Given recommended home solution"
label variable h15      "NA - Given antibiotic pills or syrups"
label variable h15a     "NA - Given antimotility"
label variable h15b     "NA - Given antibiotic injection"
label variable h15c     "NA - Given intravenous (IV)"
label variable h15d     "NA - Given home remedy, herbal medicine"
label variable h15e     "NA - Given zinc"
label variable h15f     "NA - Given other (not antibiotic, antimotility, zinc)"
label variable h15g     "NA - Given unknown pill or syrup"
label variable h15h     "NA - Given non-antibiotic injection"
label variable h15i     "NA - Given unknown injection"
label variable h15j     "NA - Given CS"
label variable h15k     "NA - Given CS"
label variable h15l     "NA - Given CS"
label variable h15m     "NA - Given CS"
label variable h20      "NA - Given other treatment"
label variable h21a     "NA - Given no treatment"
label variable h21      "NA - Received any treatment"
label variable h22      "Had fever in last two weeks"
label variable h31      "NA - Had cough in last two weeks"
label variable h31b     "NA - Short, rapid breaths"
label variable h31c     "NA - Problem in the chest or blocked or running nose"
label variable h31d     "NA - Had fever/cough in last 2 weeks: amount offered to drink"
label variable h31e     "NA - Had fever/cough in last 2 weeks: amount offered to eat"
label variable h32a     "Fever/cough: government hospital"
label variable h32b     "Fever/cough: government health center"
label variable h32c     "Fever/cough: government health post"
label variable h32d     "Fever/cough: free mobile clinic"
label variable h32e     "Fever/cough: role model caregiver/community worker"
label variable h32f     "Fever/cough: other public sector"
label variable h32g     "NA - Fever/cough: CS public sector"
label variable h32h     "NA - Fever/cough: CS public sector"
label variable h32i     "NA - Fever/cough: CS public sector"
label variable h32j     "Fever/cough: private hospital/clinic"
label variable h32k     "Fever/cough: private pharmacy"
label variable h32l     "Fever/cough: private doctor"
label variable h32m     "Fever/cough: chemist/PMV"
label variable h32n     "Fever/cough: private mobile clinic"
label variable h32o     "Fever/cough: other pricate sector"
label variable h32p     "NA - Fever/cough: CS private medical"
label variable h32q     "NA - Fever/cough: CS private medical"
label variable h32r     "NA - Fever/cough: CS private medical"
label variable h32s     "Fever/cough: shop"
label variable h32t     "Fever/cough: traditional practitioner"
label variable h32u     "Fever/cough: drug hawker"
label variable h32v     "NA - Fever/cough: CS other sector"
label variable h32w     "NA - Fever/cough: CS other sector"
label variable h32x     "Fever/cough: other"
label variable h32y     "Fever/cough: no treatment"
label variable h32z     "Fever/cough: medical treatment"
label variable h33      "NA - Received Vitamin A1 (most recent)"
label variable h33d     "NA - Vitamin A1 day"
label variable h33m     "NA - Vitamin A1 month"
label variable h33y     "NA - Vitamin A1 year"
label variable h34      "NA - Vitamin A in last 6 months"
label variable h35      "NA - Any vaccinations in last 2 years part of campaign"
label variable h36a     "NA - Vaccinated during Campaign A"
label variable h36b     "NA - Vaccinated during Campaign B"
label variable h36c     "NA - Vaccinated during Campaign C"
label variable h36d     "NA - Vaccinated during Campaign D"
label variable h36e     "NA - Vaccinated during Campaign E"
label variable h36f     "NA - Vaccinated during Campaign F"
label variable h37a     "NA - SP/Fansidar taken for fever/cough"
label variable h37b     "NA - Chloroquine taken for fever/cough"
label variable h37c     "NA - Amodiaquine taken for fever/cough"
label variable h37d     "NA - Quinine taken for fever/cough"
label variable h37e     "NA - Combination with artemisinin taken for fever/cough"
label variable h37f     "NA - CS antimalarial taken for fever/cough"
label variable h37g     "NA - CS antimalarial taken for fever/cough"
label variable h37h     "NA - Other antimalarial taken for fever/cough"
label variable h37i     "NA - Antibiotic pill/syrup taken for fever/cough"
label variable h37j     "NA - Antibiotic injection taken for fever/cough"
label variable h37k     "NA - Aspirin taken for fever/cough"
label variable h37l     "NA - Acetaminophen/paracetamol/panadol taken for fever/cough"
label variable h37m     "NA - Ibuprofen taken for fever/cough"
label variable h37n     "NA - CS other taken for fever/cough"
label variable h37o     "NA - CS other for fever/cough"
label variable h37p     "NA - CS other for fever/cough"
label variable h37x     "NA - Other taken for fever/cough"
label variable h37y     "NA - Nothing taken for fever/cough"
label variable h37z     "NA - Don't know if or what was taken for fever/cough"
label variable h38      "NA - Diarrhea in last 2 weeks: amount offered to drink"
label variable h39      "NA - Diarrhea in last 2 weeks: amount offered to eat"
label variable h40      "NA - Received Vitamin A2 (2nd most recent)"
label variable h40d     "NA - Vitamin A2 day"
label variable h40m     "NA - Vitamin A2 month"
label variable h40y     "NA - Vitamin A2 year"
label variable h41a     "NA - Received vitamin A after most recent in card"
label variable h41b     "NA - Ever received Vitamin A dose"
label variable h42      "NA - Taking iron pills, sprinkles or syrup"
label variable h43      "NA - Drugs for intestinal parasites in last 6 months"
label variable h44a     "NA - Place first sought treatment for diarrhea"
label variable h44b     "NA - Days after diarrhea sought advice or treatment"
label variable h44c     "NA - Still has diarrhea"
label variable h45      "NA - Times zinc was given"
label variable h46a     "Place first sought treatment for fever"
label variable h46b     "Days after fever sought advice or treatment"
label variable h47      "Blood taken from child's finger/heel for testing"
label variable hwidx    "Index to Birth History"
label variable hw1      "Child's age in months"
label variable hw2      "NA - Child's weight in kilograms (1 decimal)"
label variable hw3      "NA - Child's height in centimeters (1 decimal)"
label variable hw4      "NA - Height/Age percentile"
label variable hw5      "NA - Height/Age standard deviation"
label variable hw6      "NA - Height/Age percent of ref. median"
label variable hw7      "NA - Weight/Age percentile"
label variable hw8      "NA - Weight/Age standard deviation"
label variable hw9      "NA - Weight/Age percent of ref. median"
label variable hw10     "NA - Weight/Height percentile"
label variable hw11     "NA - Weight/Height standard deviation"
label variable hw12     "NA - Weight/Height percent of ref. median"
label variable hw13     "NA - Result of measurement - height/weight"
label variable hw15     "NA - Height: lying or standing"
label variable hw16     "Day of birth of child"
label variable hw17     "Date measured (day)"
label variable hw18     "Date measured (month)"
label variable hw19     "Date measured (year)"
label variable hw51     "Line number of parent/caretaker"
label variable hw52     "Read consent statement - hemoglobin"
label variable hw53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hw55     "Result of measurement - hemoglobin"
label variable hw56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hw57     "Anemia level"
label variable hw58     "NA - Agrees to referral - anemia"
label variable hw70     "NA - Height/Age standard deviation (new WHO)"
label variable hw71     "NA - Weight/Age standard deviation (new WHO)"
label variable hw72     "NA - Weight/Height standard deviation (new WHO)"
label variable hw73     "NA - BMI standard deviation (new WHO)"
label variable idxml    "Index to Birth History"
label variable ml0      "Type of mosquito bed net(s) child slept under last night"
label variable ml1      "Number of times took fansidar during pregnancy"
label variable ml2      "Source of antimalarial during pregnancy"
label variable ml11     "NA - Child has fever/cough now"
label variable ml12     "NA - Child has had convulsions in last 2 weeks"
label variable ml13a    "SP/fansidar/amalar/maloxine taken for fever/cough"
label variable ml13b    "Chloroquine taken for fever/cough"
label variable ml13c    "Amodiaquine taken for fever/cough"
label variable ml13d    "Quinine taken for fever/cough"
label variable ml13e    "Combination with artemisinin (ACT) taken for fever/cough"
label variable ml13f    "Artesunate (rectal)  taken for fever/cough"
label variable ml13g    "Artesunate (injection/IV) for fever/cough"
label variable ml13h    "Other antimalarial taken for fever/cough"
label variable ml13i    "Antibiotic pill/syrup taken for fever/cough"
label variable ml13j    "Antibiotic injection taken for fever/cough"
label variable ml13k    "Aspirin taken for fever/cough"
label variable ml13l    "Acetaminophen taken for fever/cough"
label variable ml13m    "Ibuprofen taken for fever/cough"
label variable ml13n    "Paracetamol taken for fever/cough"
label variable ml13o    "NA - CS other taken for fever"
label variable ml13p    "NA - CS other taken for fever"
label variable ml13x    "Other taken for fever/cough"
label variable ml13y    "Nothing taken for fever/cough"
label variable ml13z    "Don't know if or what was taken for fever/cough"
label variable ml14a    "NA - Injection given for fever/convulsion***"
label variable ml14b    "NA - Suppository given for fever/convulsion***"
label variable ml14y    "NA - No suppository or injection given for fever/convulsion***"
label variable ml14z    "NA - Don't know if suppository or injection given for fever/convulsion***"
label variable ml15a    "Timing of start of SP/fansidar"
label variable ml15b    "NA - Number of days child took fansidar"
label variable ml15c    "NA - First source for fansidar"
label variable ml16a    "Timing of start of chloroquine"
label variable ml16b    "NA - Number of days child took chloroquine"
label variable ml16c    "NA - First source for chloroquine"
label variable ml17a    "Timing of start of amodiaquine"
label variable ml17b    "NA - Number of days child took amodiaquine"
label variable ml17c    "NA - First source for amodiaquine"
label variable ml18a    "Timing of start of quinine"
label variable ml18b    "NA - Number of days child took quinine"
label variable ml18c    "NA - First source for quinine"
label variable ml19a    "NA - For fever/convulsion: consulted traditional healer***"
label variable ml19b    "NA - For fever/convulsion: gave tepid sponging***"
label variable ml19c    "NA - For fever/convulsion: gave herbs***"
label variable ml19d    "NA - For fever/convulsion: CS***"
label variable ml19e    "NA - For fever/convulsion: CS***"
label variable ml19f    "NA - For fever/convulsion: CS***"
label variable ml19x    "NA - For fever/convulsion: other***"
label variable ml19y    "NA - For fever/convulsion: gave/did nothing***"
label variable ml19z    "NA - For fever/convulsion: don't know if something else was done***"
label variable ml20a    "Timing of start of combination with artemisinin"
label variable ml20b    "NA - Number of days child took combination with artemisinin"
label variable ml20c    "NA - First source for combination with artemisinin"
label variable ml21a    "Timing of start of artesunate"
label variable ml21b    "NA - Number of days child took artesunate"
label variable ml21c    "NA - First source for artesunate"
label variable ml22a    "NA - Timing of start of CS antimalarial use"
label variable ml22b    "NA - Number of days child took CS antimalarial"
label variable ml22c    "NA - First source for CS antimalarial"
label variable ml23a    "Timing of start of other anti-malarial use"
label variable ml23b    "NA - Number of days child took other anti-malarial"
label variable ml23c    "NA - First source for other anti-malarial"
label variable ml24c    "NA - First source for antibiotic pill/syrup"
label variable sstate   "State"
label variable slangint "Language of interview"
label variable slangnat "Native language of respondent"
label variable stransl  "Translator used"
label variable s107d    "Has mobile telephone"
label variable s107g    "Has cable TV"
label variable s107h    "Has generating set"
label variable s107i    "Has air conditioner"
label variable s107j    "Has computer"
label variable s107k    "Has electric iron"
label variable s107l    "Has fan"
label variable s210     "Births in the last six years (2010 or later)"
label variable s501     "Ever heard of malaria"
label variable s502a    "Malaria knowledge, symptoms of malaria: fever"
label variable s502b    "Malaria knowledge, symptoms of malaria: chills/shivering"
label variable s502c    "Malaria knowledge, symptoms of malaria: headache"
label variable s502d    "Malaria knowledge, symptoms of malaria: joint pain"
label variable s502e    "Malaria knowledge, symptoms of malaria: poor appetite"
label variable s502f    "Malaria knowledge, symptoms of malaria: vomitting"
label variable s502g    "Malaria knowledge, symptoms of malaria: convulsion"
label variable s502h    "Malaria knowledge, symptoms of malaria: cough"
label variable s502i    "Malaria knowledge, symptoms of malaria: nasal congestion"
label variable s502x    "Malaria knowledge, symptoms of malaria: other"
label variable s502z    "Malaria knowledge, symptoms of malaria: don't know"
label variable s503a    "Malaria knowledge, most at risk to get malaria: children"
label variable s503b    "Malaria knowledge, most at risk to get malaria: pregnant women"
label variable s503c    "Malaria knowledge, most at risk to get malaria: adults"
label variable s503d    "Malaria knowledge, most at risk to get malaria: elderly"
label variable s503e    "Malaria knowledge, most at risk to get malaria: everyone"
label variable s503z    "Malaria knowledge, most at risk to get malaria: don't know"
label variable s504a    "Malaria knowledge, causes of malaria: mosquitos"
label variable s504b    "Malaria knowledge, causes of malaria: stagnant water"
label variable s504c    "Malaria knowledge, causes of malaria: dirty surroundings"
label variable s504d    "Malaria knowledge, causes of malaria: beer"
label variable s504e    "Malaria knowledge, causes of malaria: certain foods"
label variable s504x    "Malaria knowledge, causes of malaria: other"
label variable s504z    "Malaria knowledge, causes of malaria: don't know"
label variable s505     "Are ways to avoid getting malaria"
label variable s506a    "Know way to avoid malaria: sleep inside a mosquito net"
label variable s506b    "Know way to avoid malaria: sleep inside an ITN/LLIN"
label variable s506c    "Know way to avoid malaria: use home insecticide spray"
label variable s506d    "Know way to avoid malaria: use mosquito coils"
label variable s506e    "Know way to avoid malaria: keep doors and windows closed"
label variable s506f    "Know way to avoid malaria: use insect repellant"
label variable s506g    "Know way to avoid malaria: keep surroundings clean"
label variable s506h    "Know way to avoid malaria: cut the grass"
label variable s506i    "Know way to avoid malaria: eliminate stagnant water around living area"
label variable s506x    "Know way to avoid malaria: other"
label variable s506z    "Know way to avoid malaria: don't know"
label variable s507a    "Know way to prevent malaria: sleep inside a mosquito net"
label variable s507b    "Know way to prevent malaria: sleep inside an ITN/LLIN"
label variable s507c    "Know way to prevent malaria: use home insecticide spray"
label variable s507d    "Know way to prevent malaria: use mosquito coils"
label variable s507e    "Know way to prevent malaria: keep doors and windows closed"
label variable s507f    "Know way to prevent malaria: use insect repellant"
label variable s507g    "Know way to prevent malaria: keep surroundings clean"
label variable s507h    "Know way to prevent malaria: cut the grass"
label variable s507i    "Know way to prevent malaria: eliminate stagnant water around living area"
label variable s507j    "Know way to prevent malaria: shut doors/windows"
label variable s507x    "Know way to prevent malaria: other"
label variable s507z    "Know way to prevent malaria: don't know"
label variable s508a    "Malaria prevention for pregnant women: sleep inside mosquito net"
label variable s508b    "Malaria prevention for pregnant women: sleep inside an ITN/LLIN"
label variable s508c    "Malaria prevention for pregnant women: keep environment clean"
label variable s508d    "Malaria prevention for pregnant women: take SP/Fansidar given during antenatal c"
label variable s508e    "Malaria prevention for pregnant women: take daraprim tablets (Sunday-Sunday medi"
label variable s508x    "Malaria prevention for pregnant women: other"
label variable s508z    "Malaria prevention for pregnant women: don't know"
label variable s509     "Malaria can be treated"
label variable s510a    "Malaria medication knowledge: SP/Fansidar"
label variable s510b    "Malaria medication knowledge: chloroquine"
label variable s510c    "Malaria medication knowledge: artesunate"
label variable s510d    "Malaria medication knowledge: quinine"
label variable s510e    "Malaria medication knowledge: ACT"
label variable s510f    "Malaria medication knowledge: aspirin/panadol/paracetamol"
label variable s510g    "Malaria medication knowledge: antimalarial (unknown component)"
label variable s510x    "Malaria medication knowledge: other"
label variable s510z    "Malaria medication knowledge: don't know"
label variable s511a    "Malaria medication for children: SP/Fansidar"
label variable s511b    "Malaria medication for children: chloroquine"
label variable s511c    "Malaria medication for children: artesunate"
label variable s511d    "Malaria medication for children: quinine"
label variable s511e    "Malaria medication for children: ACT"
label variable s511f    "Malaria medication for children: aspirin/panadol/paracetamol"
label variable s511g    "Malaria medication for children: antimalarial (unknown component)"
label variable s511x    "Malaria medication for children: other"
label variable s511z    "Malaria medication for children: don't know"
label variable s512     "Heard or seen any message about malaria in the last 6 months"
label variable s513a    "Messages heard/seen about malaria: malaria is dangerous"
label variable s513b    "Messages heard/seen about malaria: malaria can kill"
label variable s513c    "Messages heard/seen about malaria: mosquitos spread malaria"
label variable s513d    "Messages heard/seen about malaria: sleeping inside a mosquito net is important"
label variable s513e    "Messages heard/seen about malaria: who should sleep inside a mosquito net"
label variable s513f    "Messages heard/seen about malaria: seek treatment for fever"
label variable s513g    "Messages heard/seen about malaria: seek treatment for fever promptly (within 24 "
label variable s513h    "Messages heard/seen about malaria: importance of house spraying"
label variable s513i    "Messages heard/seen about malaria: environmental sanitation activities"
label variable s513j    "Messages heard/seen about malaria: seek testing before treatment for malaria"
label variable s513k    "Messages heard/seen about malaria: early registration for ANC"
label variable s513l    "Messages heard/seen about malaria: pregnant women should take SP/Fansidar"
label variable s513x    "Messages heard/seen about malaria: other"
label variable s513z    "Messages heard/seen about malaria: don't know"
label variable s514a    "Place where malaria messages heard/seen: radio"
label variable s514b    "Place where malaria messages heard/seen: television"
label variable s514c    "Place where malaria messages heard/seen: community health extension worker (CHEW"
label variable s514d    "Place where malaria messages heard/seen: village health worker (VHW)"
label variable s514e    "Place where malaria messages heard/seen: role model caregiver (RMC)"
label variable s514f    "Place where malaria messages heard/seen: community directed distributor (CDD)"
label variable s514g    "Place where malaria messages heard/seen: mosque/church"
label variable s514h    "Place where malaria messages heard/seen: town announcer"
label variable s514i    "Place where malaria messages heard/seen: community event"
label variable s514j    "Place where malaria messages heard/seen: billboard"
label variable s514k    "Place where malaria messages heard/seen: poster"
label variable s514l    "Place where malaria messages heard/seen: t-shirt"
label variable s514m    "Place where malaria messages heard/seen: leaflet/fact sheet/brochure"
label variable s514n    "Place where malaria messages heard/seen: relative/friend/neighbor/school"
label variable s514o    "Place where malaria messages heard/seen: social media (Facebook, Twitter, etc)"
label variable s514p    "Place where malaria messages heard/seen: antenatal care visit"
label variable s514q    "Place where malaria messages heard/seen: health center or hospital"
label variable s514x    "Place where malaria messages heard/seen: other"
label variable s515a    "Opinions of malaria: chances of getting malaria are same whether or not sleeping"
label variable s515b    "Opinions of malaria: medicine prenant women use to prevent malaria works well"
label variable s515c    "Opinions of malaria: malaria tests are a good way to know if a person has malari"
label variable s515d    "Opinions of malaria: ACTs work quickly to treat malaria"
label variable s515aa   "Slept inside a treated mosquito net last night"
label variable s516a    "Encouragement to sleep under net: if net did not smell"
label variable s516b    "Encouragement to sleep under net: had a different shape/size"
label variable s516c    "Encouragement to sleep under net: had a different color"
label variable s516d    "Encouragement to sleep under net: if net were not itchy/irritating"
label variable s516e    "Encouragement to sleep under net: if net were bigger/not claustrophobic"
label variable s516x    "Encouragement to sleep under net: other"
label variable s516z    "Encouragement to sleep under net: don't know"
label variable s516aa   "Color of net preference"
label variable s516bb   "Shape of net preference"
label variable s516cc   "Size of net preference"
label variable s516dd   "Brand of net preference"
label variable idx94    "Index to Birth History"
label variable s310     "Received a mosquito net during an antenatal visit"
label variable idx95    "Index to Birth History"
label variable s404a    "Suspect child had malaria"
label variable s405a    "Child was tested for malaria"
label variable s405b    "Result of the malaria test"
label variable s411f    "Quinine (pills) taken for fever/cough"
label variable s411g    "Quinine (injection/IV) taken for fever/cough"

#delimit ;
label define V013    
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define V014    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define V015    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partially completed"
     6 "Respondent incapacitated"
     7 "Other"
;
label define V018    
     0 "No calendar"
;
label define V019    
     0 "No calendar"
;
label define V019A   
     0 "No calendar"
;
label define V020    
     0 "All woman sample"
     1 "Ever married sample"
;
label define V022    
     0 "National"
     1 "Sokoto - Urban"
     2 "Sokoto - Rural"
     3 "Zamfara - Urban"
     4 "Zamfara - Rural"
     5 "Katsina - Urban"
     6 "Katsina - Rural"
     7 "Jigawa - Urban"
     8 "Jigawa - Rural"
     9 "Yobe - Urban"
    10 "Yobe - Rural"
    11 "Borno - Urban"
    13 "Adamawa - Urban"
    14 "Adamawa - Rural"
    15 "Gombe - Urban"
    16 "Gombe - Rural"
    17 "Bauchi - Urban"
    18 "Bauchi - Rural"
    19 "Kano - Urban"
    20 "Kano - Rural"
    21 "Kaduna - Urban"
    22 "Kaduna - Rural"
    23 "Kebbi - Urban"
    24 "Kebbi - Rural"
    25 "Niger - Urban"
    26 "Niger - Rural"
    27 "FCT Abuja - Urban"
    28 "FCT Abuja - Rural"
    29 "Nasarawa - Urban"
    30 "Nasarawa - Rural"
    31 "Plateau - Urban"
    32 "Plateau - Rural"
    33 "Taraba - Urban"
    34 "Taraba - Rural"
    35 "Benue - Urban"
    36 "Benue - Rural"
    37 "Kogi - Urban"
    38 "Kogi - Rural"
    39 "Kwara - Urban"
    40 "Kwara - Rural"
    41 "Oyo - Urban"
    42 "Oyo - Rural"
    43 "Osun - Urban"
    44 "Osun - Rural"
    45 "Ekiti - Urban"
    46 "Ekiti - Rural"
    47 "Ondo - Urban"
    48 "Ondo - Rural"
    49 "Edo - Urban"
    50 "Edo - Rural"
    51 "Anambra - Urban"
    52 "Anambra - Rural"
    53 "Enugu - Urban"
    54 "Enugu - Rural"
    55 "Ebonyi - Urban"
    56 "Ebonyi - Rural"
    57 "Cross River - Urban"
    58 "Cross River - Rural"
    59 "Akwa Ibom - Urban"
    60 "Akwa Ibom - Rural"
    61 "Abia - Urban"
    62 "Abia - Rural"
    63 "Imo - Urban"
    64 "Imo - Rural"
    65 "Rivers - Urban"
    66 "Rivers - Rural"
    67 "Bayelsa - Urban"
    68 "Bayelsa - Rural"
    69 "Delta - Urban"
    70 "Delta - Rural"
    71 "Lagos - Urban"
    73 "Ogun - Urban"
    74 "Ogun - Rural"
;
label define V023    
     0 "National"
     1 "Sokoto - Urban"
     2 "Sokoto - Rural"
     3 "Zamfara - Urban"
     4 "Zamfara - Rural"
     5 "Katsina - Urban"
     6 "Katsina - Rural"
     7 "Jigawa - Urban"
     8 "Jigawa - Rural"
     9 "Yobe - Urban"
    10 "Yobe - Rural"
    11 "Borno - Urban"
    13 "Adamawa - Urban"
    14 "Adamawa - Rural"
    15 "Gombe - Urban"
    16 "Gombe - Rural"
    17 "Bauchi - Urban"
    18 "Bauchi - Rural"
    19 "Kano - Urban"
    20 "Kano - Rural"
    21 "Kaduna - Urban"
    22 "Kaduna - Rural"
    23 "Kebbi - Urban"
    24 "Kebbi - Rural"
    25 "Niger - Urban"
    26 "Niger - Rural"
    27 "FCT Abuja - Urban"
    28 "FCT Abuja - Rural"
    29 "Nasarawa - Urban"
    30 "Nasarawa - Rural"
    31 "Plateau - Urban"
    32 "Plateau - Rural"
    33 "Taraba - Urban"
    34 "Taraba - Rural"
    35 "Benue - Urban"
    36 "Benue - Rural"
    37 "Kogi - Urban"
    38 "Kogi - Rural"
    39 "Kwara - Urban"
    40 "Kwara - Rural"
    41 "Oyo - Urban"
    42 "Oyo - Rural"
    43 "Osun - Urban"
    44 "Osun - Rural"
    45 "Ekiti - Urban"
    46 "Ekiti - Rural"
    47 "Ondo - Urban"
    48 "Ondo - Rural"
    49 "Edo - Urban"
    50 "Edo - Rural"
    51 "Anambra - Urban"
    52 "Anambra - Rural"
    53 "Enugu - Urban"
    54 "Enugu - Rural"
    55 "Ebonyi - Urban"
    56 "Ebonyi - Rural"
    57 "Cross River - Urban"
    58 "Cross River - Rural"
    59 "Akwa Ibom - Urban"
    60 "Akwa Ibom - Rural"
    61 "Abia - Urban"
    62 "Abia - Rural"
    63 "Imo - Urban"
    64 "Imo - Rural"
    65 "Rivers - Urban"
    66 "Rivers - Rural"
    67 "Bayelsa - Urban"
    68 "Bayelsa - Rural"
    69 "Delta - Urban"
    70 "Delta - Rural"
    71 "Lagos - Urban"
    73 "Ogun - Urban"
    74 "Ogun - Rural"
;
label define V024    
     1 "North central"
     2 "North east"
     3 "North west"
     4 "South east"
     5 "South south"
     6 "South west"
;
label define V025    
     1 "Urban"
     2 "Rural"
;
label define V026    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V027    
     9 "Missing"
;
label define V028    
  9999 "Missing"
;
label define V029    
    99 "Missing"
;
label define V030    
  9999 "Missing"
;
label define V031    
   999 "Missing"
;
label define V032    
    99 "Missing"
;
label define V034    
     0 "Husband not in household"
;
label define V040    
  9999 "Missing"
;
label define V042    
     0 "Not selected"
     1 "Selected"
;
label define V044    
     0 "Woman not selected"
     1 "Woman selected and interviewed"
     2 "Woman selected, but privacy not possible"
     3 "Woman selected, but not interviewed"
;
label define V101    
     1 "North central"
     2 "North east"
     3 "North west"
     4 "South east"
     5 "South south"
     6 "South west"
;
label define V102    
     1 "Urban"
     2 "Rural"
;
label define V103    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define V104    
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define V105    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define V106    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define V107    
     0 "No years completed at level V106"
;
label define V113    
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    14 "Piped to neighbor"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    72 "Sachet water"
    96 "Other"
    97 "Not a dejure resident"
;
label define V115    
   996 "On premises"
   997 "Not a dejure resident"
   998 "Don't know"
;
label define V116    
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
    97 "Not a dejure resident"
;
label define V119    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V120    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V121    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V122    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V123    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V124    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V125    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V127    
    10 "NATURAL"
    11 "Earth, sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm, bamboo"
    30 "FINISHED"
    31 "Parquet, polished wood"
    32 "Vinyl, asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
    97 "Not a dejure resident"
;
label define V128    
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Dirt"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
    97 "Not a dejure resident"
;
label define V129    
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Zinc/metal"
    32 "Wood"
    33 "Calamine/cement fiber"
    34 "Ceramic tiles"
    35 "Cement"
    36 "Roofing shingles"
    96 "Other"
    97 "Not a dejure resident"
;
label define V130    
     1 "Christianity"
     2 "Islam"
     3 "Traditional religion"
     4 "No religion"
    96 "Other"
;
label define V131    
     1 "Abua"
     2 "Adra/Adarawa"
     3 "Adun"
     4 "Afcabeya"
     5 "Afemai"
     6 "Afizire"
    10 "Afo"
     7 "Agatu"
   327 "Agazawa"
     8 "Agbassa"
     9 "Agbor"
   378 "Ahu"
    11 "Ajowa"
    12 "Akpa"
    13 "Akwai"
    14 "Akye"
    15 "Alago"
    16 "Amamong"
    17 "Amo"
    18 "Ana"
    19 "Anaguta"
   392 "Andoni"
   323 "Angas"
    20 "Ankwai"
    21 "Annang"
   370 "Antocha"
    22 "Arab"
    23 "Arabo"
    24 "Arbar"
    25 "Arugu"
    26 "Aten/Atam"
    27 "Attakar"
    28 "Auchi"
    29 "Aulliminden"
    30 "Awo"
    31 "Ayetoro Gbede"
    71 "Badakare/Dakarkari"
    32 "Badarare"
    33 "Bade/Badawe"
    34 "Bafeke"
    35 "Bagathiya"
   377 "Bageri"
    36 "Baggara"
    37 "Bagunge/Badagire"
    38 "Bahnake"
    39 "Baji/Biji"
    40 "Bajju"
   315 "Bakabe"
   326 "Bakenga"
    41 "Bambaro"
    42 "Bambuka"
    43 "Bandawa"
    44 "Banguji"
    45 "Bankalawa"
    47 "Barabaci"
    48 "Barawa"
    49 "Bargawa"
   371 "Baruba/Baruntin"
   379 "Basange"
   369 "Bashama"
    50 "Bassa"
   388 "Batala"
   381 "Batunu"
    46 "Bchama"
    51 "Bekworas"
    53 "Berom"
   368 "Beteer"
   337 "Bile"
    54 "Bini/Edo"
   324 "Bobari"
    55 "Bogom"
    56 "Boiyawa/Bozaya"
    57 "Bolawa/Bolewa"
    59 "Buduma"
   354 "Buh"
    60 "Buko"
    61 "Bura/Babur"
   316 "Burmanch"
    62 "Buzu"
    63 "Byazhi"
   356 "Chakeem"
    65 "Chala"
   344 "Cham"
    66 "Chamba"
    67 "Chiba"
    68 "Chibok(g)"
    69 "Chip"
    70 "Dadiya"
    72 "Dakka/Doka"
    73 "Dangula"
   391 "Dara"
    74 "Daurawa/Dagarawa"
    75 "Defaka"
    76 "Degima"
    77 "Delta Ibo"
   373 "Dibba"
    78 "Dibo"
    79 "Diguza"
    80 "Djerma"
    81 "Dmoko"
    82 "Dolchi"
   342 "Dukawa"
   334 "Dumak"
    83 "Ebira/Igbira"
    84 "Ebu"
    85 "Efik"
    86 "Egba"
    87 "Egbado"
   390 "Egbema"
    88 "Eggon"
   308 "Egi"
    89 "Egun"
    90 "Eket"
    91 "Ekoi"
    92 "Ekpeye/Afisa/Epie"
    94 "Ekulu"
    95 "Eleme"
    96 "Emu"
    97 "Esan"
    98 "Etina"
    99 "Etsako"
   100 "Etulo"
   350 "Ezza"
   102 "Fanso"
   103 "Femawa"
   104 "Fer"
   105 "Filiya/Fali"
   106 "Fon"
   107 "Foron"
   108 "French"
   109 "Fulani"
   313 "Fulfulde"
   349 "Gaanda"
   110 "Gamaku"
   111 "Gamaru"
   112 "Gamuni"
   113 "Gana Gana"
   114 "Ganawuri"
   375 "Gasawa"
   115 "Gbaju/Gbagi"
   116 "Gede/Gude/Gai"
   117 "Gerawa"
   365 "Gizi Yobe"
   118 "Gizmawa"
   119 "Glauda"
   120 "Gmenchi"
   122 "Gobiri/Gobirawa/Bogobiri"
   121 "Gomo/Gamoyaya"
   124 "Guemai"
   123 "Gujjurawa"
   125 "Gumbarawa"
   126 "Gunganchi"
   386 "Guruma"
   352 "Gusu"
   127 "Gwandara"
   128 "Gwantu"
   305 "Gwari"
   328 "Gwoza"
   101 "Hadejawa"
   332 "Hanbagda"
   129 "Hankwe"
   130 "Hausa"
   131 "Higgi"
   362 "Honna"
   132 "Ibariba"
   133 "Ibibio"
   134 "Ichen"
   135 "Idanre"
   136 "Idoma"
   137 "Igala"
   302 "Igbanko"
   138 "Igbo/Ibo"
   139 "Igede"
   140 "Ijaw/Izon"
   141 "Ijede"
   142 "Ijeme"
   143 "Ika"
   144 "Ikajo"
   145 "Ikara"
   146 "Ikpeshi"
   147 "Ikpide"
   353 "Ikpoma"
   148 "Ikulu"
   149 "Ikwere"
   150 "Ilaje"
   151 "Irigwe"
   152 "Ishan"
   153 "Isoko"
   154 "Itsekiri"
   395 "Iyala"
   155 "Jaba"
   156 "Jajiri"
   157 "Jakatoe"
   158 "Jaku"
   159 "Jara"
   160 "Jarawa"
   364 "Jere"
   396 "Jibawa"
   162 "Jibu"
   357 "Jipal"
   163 "Jonjo"
   164 "Jukun"
   165 "Kabawa"
   314 "Kabba/Okun"
   166 "Kadara"
   167 "Kagoma"
   168 "Kagoro"
   301 "Kaje"
   169 "Kaka"
   170 "Kakanda"
   317 "Kalabari"
   171 "Kamantam"
   172 "Kambari"
   173 "Kambu/Kangu"
   345 "Kamo"
   174 "Kamuku"
   175 "Kanakuru"
   176 "Kanawa"
   177 "Kaninko"
   178 "Kantanawa"
   374 "Kanum"
   179 "Kanuri/Beriberi"
   363 "Kapsiki"
   181 "Karekare"
   366 "Karekare"
   321 "Karimjo"
   182 "Kataf/Atyap"
   183 "Kento"
   184 "Kibaku"
   185 "Kilba"
   186 "Kirdi"
   187 "Kodki"
   188 "Kofyar"
   359 "Koma"
   189 "Kona"
   190 "Koro"
   191 "Koto"
   351 "Kubasawa."
   192 "Kuenuem"
   367 "Kulere"
   193 "Kumbo"
   194 "Kunkawa/Kawa"
   195 "Kurama"
   196 "Kuteb"
   197 "Kuturm"
   322 "Kwa"
   198 "Kwale/Ukwuani"
   335 "Kwalla"
   199 "Kwanzo"
   200 "Lagelu"
   346 "Lala"
   201 "Lantang"
   347 "Laru"
   202 "Lemoro"
   348 "Lisa"
   203 "Loh"
   204 "Lunguda"
   205 "Maba/Mbadowa"
   206 "Mada"
   207 "Mafa/Maka/Maga"
   208 "Mambila"
   209 "Mandara"
   180 "Manga"
   210 "Mangus/Manju"
   211 "Marghi/mangi"
   311 "Marwa"
   212 "Mbwa"
   304 "Migili"
   213 "Mingo"
   214 "Mirnang"
   320 "Miship"
   215 "Montor"
   310 "Moroa"
   216 "Mtchiga/Michika"
   217 "Mumuye"
   218 "Munga"
   397 "Mungaduso"
   219 "Mupung"
   376 "Muryan"
   220 "Mushere"
   355 "Mushere"
   221 "Mwagavol"
   222 "Naiawum"
   380 "Nakere"
   223 "Namoen"
   224 "Ndokwa"
   225 "Ndola"
   372 "Nezou"
   226 "Ngamo"
   331 "Ngezim"
   228 "Ngoshe"
   229 "Nili"
   343 "Ningi"
   230 "Ninnma"
   231 "Ninzom"
   333 "Njanyi"
   232 "Nkoroo"
   233 "Nnebe"
   234 "Numana"
   384 "Numuro"
   235 "Nungu"
   236 "nunku"
   237 "Nupe"
   330 "Nyangdang"
   393 "Obolo"
   238 "Obubua"
   239 "Odu"
   338 "Offa"
   309 "Ogba"
   389 "Ogbo"
   240 "Ogoja"
   241 "Ogoni"
   242 "Ogugu"
   383 "Ohari"
   307 "Okirika"
   398 "Okobo"
   243 "Okori/Ogori"
   244 "Omele"
   245 "Ora"
   246 "Oron"
   387 "Otuwo"
   247 "Owan"
   249 "Owo"
   250 "Pa'awa"
   251 "Paburi"
   252 "Paibun"
   253 "Panya"
   254 "Pasama"
   394 "Pegan"
   255 "Pero"
   256 "Piya"
   340 "Pura Pura"
   257 "Pyem"
   341 "Rindre"
   258 "Rukuba"
   259 "Rulere"
   260 "Rundawa"
   382 "Sanga"
   261 "Sayawa/Siyawa"
   262 "Sekere"
   263 "Sharawa"
   264 "Shomo"
   265 "Shuwa"
   266 "Somunka"
   267 "Sullubawa"
   268 "Sura"
   269 "Taira"
   270 "Tangale"
   385 "Tangale"
   272 "Tarok"
   273 "Tera"
   274 "Teskwa"
   275 "Tiguni"
   276 "Tiv"
   277 "Tiyari"
   312 "Toff"
   278 "Tula"
   279 "Ubaija"
   280 "Ugbia"
   358 "Ugeb"
   281 "Uhionigbe"
   227 "Ukale"
   282 "Ukwuani"
   283 "Urhobo"
   306 "Uru"
   284 "Uyo"
   285 "Uzaurue"
   286 "Uzeba"
   360 "Verre/Kila"
   287 "Waja"
   288 "Waka"
   289 "Wanu"
   290 "Wari"
   291 "Warjawa"
   292 "Wodaabe"
   293 "Wurkum"
   294 "Yakurr"
   295 "Yandang"
   325 "Yarimawa"
   296 "Yendre"
   336 "Yeskwa and Mubula"
   297 "Yonubi"
   298 "Yoruba"
   339 "Yungur"
   299 "Zabarmawa"
   329 "Zalidva"
   361 "Zuru"
   996 "Others"
   998 "Don't know"
;
label define V133    
    97 "Inconsistent"
;
label define V134    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V135    
     1 "Usual resident"
     2 "Visitor"
;
label define V139    
     0 "Abroad"
     1 "North central"
     2 "North east"
     3 "North west"
     4 "South east"
     5 "South south"
     6 "South west"
    97 "Not dejure resident"
;
label define V140    
     0 "Abroad"
     1 "Urban"
     2 "Rural"
     7 "Not a dejure resident"
;
label define V141    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     7 "Not a dejure resident"
;
label define V149    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define V150    
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster/step child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    98 "Don't know"
;
label define V151    
     1 "Male"
     2 "Female"
;
label define V152    
    97 "97+"
    98 "Don't know"
;
label define V153    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V155    
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define V156    
     0 "No"
     1 "Yes"
;
label define V157    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V158    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V159    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V160    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V161    
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in house"
    96 "Other"
    97 "Not a dejure resident"
;
label define V166    
     0 "0 ppm (no iodine)"
     7 "7 ppm"
    15 "15 ppm"
    30 "30 ppm"
   994 "Salt not tested"
   995 "No salt"
   997 "Not a dejure resident"
;
label define V167    
     0 "None"
    90 "90+"
;
label define V168    
     0 "No"
     1 "Yes"
;
label define V190    
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define V190A   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define ML101   
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define V208    
     0 "No births"
;
label define V209    
     0 "No births"
;
label define V213    
     0 "No or unsure"
     1 "Yes"
;
label define V215    
   100 "Day of interview"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
   994 "In menopause/had hysterectomy"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
;
label define V216    
     0 "No"
     1 "Yes"
;
label define V217    
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define V220    
     6 "6+"
;
label define V221    
   996 "Negative interval"
;
label define V223    
     7 "Month - exact date"
     8 "None - date placed"
;
label define V225    
     1 "Then"
     2 "Later"
     3 "Not at all"
;
label define V226    
   994 "In menopause"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
;
label define V227    
     0 "No flag"
     1 "N > interval since birth"
     2 "N + amen. > interval"
     3 "N, but period not returned"
     4 "95, but no birth"
     5 "95, but period returned"
     6 "96, but period returned"
     7 "N, last period during pregnancy"
     8 "96, had children"
     9 "N, period before last birth"
;
label define V228    
     0 "No"
     1 "Yes"
;
label define V229    
    97 "Inconsistent"
    98 "Don't know"
;
label define V230    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V231    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V232    
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     7 "Month"
     8 "None"
;
label define V233    
    97 "Inconsistent"
    98 "Don't know"
;
label define V234    
     0 "No"
     1 "Yes"
;
label define V235    
     0 "No prior child"
;
label define V237    
     0 "No"
     1 "Yes"
;
label define V239    
     0 "No"
     1 "Yes"
;
label define V240    
    97 "Inconsistent"
    98 "Don't know"
;
label define V241    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V242    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V243    
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     7 "Month"
     8 "None"
;
label define V401    
     0 "No"
     1 "Yes"
;
label define V404    
     0 "No"
     1 "Yes"
;
label define V405    
     0 "No"
     1 "Yes"
;
label define V406    
     0 "No"
     1 "Yes"
;
label define V407    
    96 "On demand"
;
label define V408    
    96 "On demand"
;
label define V409    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V409A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V410    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V410A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V411    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V411A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V412    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V412A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V412B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V412C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V413    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V413A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V413B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V413C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V413D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414F   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414G   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414H   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414I   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414J   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414K   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414L   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414M   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414N   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414O   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414P   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414Q   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414R   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414S   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414T   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414U   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414V   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414W   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V415    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V416    
     0 "Never heard of"
     1 "Used ORS"
     2 "Heard of ORS"
;
label define V420    
   999 "Missing"
;
label define V421    
   999 "Missing"
;
label define V426    
     0 "Immediately"
   100 "Within first hour"
   101 "Hours: 1"
   199 "Hours: number missing"
   201 "Days: 1"
   299 "Days: number missing"
;
label define V437    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define V438    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define V439    
  9998 "Flagged cases"
;
label define V440    
  9998 "Flagged cases"
;
label define V441    
 99998 "Flagged cases"
;
label define V442    
 99998 "Flagged cases"
;
label define V443    
 99998 "Flagged cases"
;
label define V444    
 99998 "Flagged cases"
;
label define V444A   
  9998 "Flagged cases"
;
label define V445    
  9998 "Flagged cases"
;
label define V446    
  9998 "Flagged cases"
;
label define V447    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
     7 "No measurement found in household"
;
label define V452A   
     1 "Under age 18"
     2 "Age 18 or older"
;
label define V452B   
     0 "Not in household"
;
label define V452C   
     1 "Granted"
     2 "Parent/other refused"
     3 "Respondent refused"
;
label define V453    
   999 "Missing"
;
label define V454    
     0 "No/don't know"
     1 "Yes"
;
label define V455    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
     7 "No measurement found in household"
;
label define V456    
   999 "Missing"
;
label define V457    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define V458    
     0 "No"
     1 "Yes"
;
label define V459    
     0 "No"
     1 "Yes"
;
label define V460    
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define V461    
     0 "No"
     1 "Yes"
;
label define V462    
     0 "No"
     1 "Yes"
     2 "Never prepared meal"
;
label define V463A   
     0 "No"
     1 "Yes"
;
label define V463B   
     0 "No"
     1 "Yes"
;
label define V463C   
     0 "No"
     1 "Yes"
;
label define V463D   
     0 "No"
     1 "Yes"
;
label define V463E   
     0 "No"
     1 "Yes"
;
label define V463F   
     0 "No"
     1 "Yes"
;
label define V463G   
     0 "No"
     1 "Yes"
;
label define V463X   
     0 "No"
     1 "Yes"
;
label define V463Z   
     0 "No"
     1 "Yes, smokes nothing"
;
label define V464    
    80 "80+"
    98 "Don't know"
;
label define V465    
     1 "Used toilet/latrine"
     2 "Put/rinsed in toilet/latrine"
     3 "Put/rinsed into drain or ditch"
     4 "Throw into garbage"
     5 "Buried"
     6 "Rinse away"
     7 "Use disposable diapers"
     8 "Use washable diapers"
     9 "Left in the open/not disposed of"
    96 "Other"
;
label define V466    
     0 "No"
     1 "Yes"
     2 "Depends"
;
label define V467A   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467B   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467C   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467D   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467E   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467F   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467G   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467H   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467I   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467J   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467K   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467L   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467M   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V468    
     0 "See specific questions"
     1 "Last birth only"
     2 "All births in last 5 years"
;
label define V469E   
     0 "No"
     7 "7+"
     8 "DK"
;
label define V469F   
     0 "No"
     7 "7+"
     8 "DK"
;
label define V469X   
     0 "No"
     7 "7+"
     8 "DK"
;
label define V471A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471F   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471G   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472F   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472G   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472H   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472I   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472J   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472K   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472L   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472M   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472N   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472O   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472P   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472Q   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472R   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472S   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472T   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472U   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V473A   
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Sample not tested/lost/not enough DBS"
;
label define V473B   
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost/damaged/insufficient"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define V474    
     0 "No"
     1 "Yes"
;
label define V474A   
     0 "No"
     1 "Yes"
;
label define V474B   
     0 "No"
     1 "Yes"
;
label define V474C   
     0 "No"
     1 "Yes"
;
label define V474D   
     0 "No"
     1 "Yes"
;
label define V474E   
     0 "No"
     1 "Yes"
;
label define V474F   
     0 "No"
     1 "Yes"
;
label define V474G   
     0 "No"
     1 "Yes"
;
label define V474H   
     0 "No"
     1 "Yes"
;
label define V474I   
     0 "No"
     1 "Yes"
;
label define V474J   
     0 "No"
     1 "Yes"
;
label define V474X   
     0 "No"
     1 "Yes"
;
label define V474Z   
     0 "No"
     1 "Yes"
;
label define V475    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V476    
     0 "No"
     1 "Yes, remain a secret"
     8 "Don't know/not sure/depends"
;
label define V477    
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define V478    
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define V479    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    16 "Other public sector"
    20 "PRIVATE SECTOR"
    21 "Private hospital/clinic/doctor"
    22 "Dental clinic/office"
    23 "Pharmacy"
    24 "Office or home of nurse/health worker"
    26 "Other private sector"
    30 "OTHER NON-MEDICAL"
    31 "Respondent's home"
    96 "Other"
;
label define V480    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V481    
     0 "No"
     1 "Yes"
;
label define V481A   
     0 "No"
     1 "Yes"
;
label define V481B   
     0 "No"
     1 "Yes"
;
label define V481C   
     0 "No"
     1 "Yes"
;
label define V481D   
     0 "No"
     1 "Yes"
;
label define V481E   
     0 "No"
     1 "Yes"
;
label define V481F   
     0 "No"
     1 "Yes"
;
label define V481G   
     0 "No"
     1 "Yes"
;
label define V481H   
     0 "No"
     1 "Yes"
;
label define V481X   
     0 "No"
     1 "Yes"
;
label define V482A   
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define V482B   
     0 "No"
     1 "Yes"
;
label define V482C   
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define B0      
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
;
label define B4      
     1 "Male"
     2 "Female"
;
label define B5      
     0 "No"
     1 "Yes"
;
label define B6      
   100 "Died on day of birth"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
   997 "Inconsistent"
   998 "Don't know"
;
label define B9      
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
;
label define B10     
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define B13     
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
;
label define B15     
     0 "No"
     1 "Yes"
;
label define B16     
     0 "Not listed in household"
;
label define M1      
     0 "Received no injection"
     7 "7+"
     8 "Don't know"
;
label define M1A     
     0 "Received no injection"
     7 "7+"
     8 "Don't know"
;
label define M1B     
    97 "Inconsistent"
    98 "Don't know month"
;
label define M1C     
  9997 "Inconsistent"
  9998 "Don't know year"
;
label define M1D     
    99 "Missing"
;
label define M1E     
  9996 "Can't be determined"
;
label define M2A     
     0 "No"
     1 "Yes"
;
label define M2B     
     0 "No"
     1 "Yes"
;
label define M2C     
     0 "No"
     1 "Yes"
;
label define M2D     
     0 "No"
     1 "Yes"
;
label define M2E     
     0 "No"
     1 "Yes"
;
label define M2F     
     0 "No"
     1 "Yes"
;
label define M2G     
     0 "No"
     1 "Yes"
;
label define M2H     
     0 "No"
     1 "Yes"
;
label define M2I     
     0 "No"
     1 "Yes"
;
label define M2J     
     0 "No"
     1 "Yes"
;
label define M2K     
     0 "No"
     1 "Yes"
;
label define M2L     
     0 "No"
     1 "Yes"
;
label define M2M     
     0 "No"
     1 "Yes"
;
label define M2N     
     0 "No: some care"
     1 "Yes: no care"
;
label define M3A     
     0 "No"
     1 "Yes"
;
label define M3B     
     0 "No"
     1 "Yes"
;
label define M3C     
     0 "No"
     1 "Yes"
;
label define M3D     
     0 "No"
     1 "Yes"
;
label define M3E     
     0 "No"
     1 "Yes"
;
label define M3F     
     0 "No"
     1 "Yes"
;
label define M3G     
     0 "No"
     1 "Yes"
;
label define M3H     
     0 "No"
     1 "Yes"
;
label define M3I     
     0 "No"
     1 "Yes"
;
label define M3J     
     0 "No"
     1 "Yes"
;
label define M3K     
     0 "No"
     1 "Yes"
;
label define M3L     
     0 "No"
     1 "Yes"
;
label define M3M     
     0 "No"
     1 "Yes"
;
label define M3N     
     0 "No: some assistance"
     1 "Yes: no assistance"
;
label define M4      
    93 "Ever breastfed, not currently breastfeeding"
    94 "Never breastfed"
    95 "Still breastfeeding"
    96 "Breastfed until died"
    97 "Inconsistent"
    98 "Don't know"
;
label define M5      
    93 "Ever breastfed, not currently breastfeeding"
    94 "Never breastfed"
    97 "Inconsistent"
    98 "Don't know"
;
label define M6      
    96 "Period not returned"
    97 "Inconsistent"
    98 "Don't know"
;
label define M7      
    97 "Inconsistent"
    98 "Don't know"
;
label define M8      
    96 "Still abstaining"
    97 "Inconsistent"
    98 "Don't know"
;
label define M9      
    97 "Inconsistent"
    98 "Don't know"
;
label define M10     
     1 "Then"
     2 "Later"
     3 "No more"
;
label define M11     
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   998 "Don't know"
;
label define M13     
    98 "Don't know"
;
label define M14     
     0 "No antenatal visits"
    98 "Don't know"
;
label define M15     
    10 "HOME"
    11 "Respondent's home"
    12 "Other home"
    20 "PUBLIC SECTOR"
    21 "Government hospital"
    22 "CS Govt health professional"
    23 "CS Govt health professional"
    26 "Other public sector"
    30 "PRIVATE SECTOR"
    31 "Private hospital/clinic"
    36 "Other private sector"
    96 "Other"
;
label define M17     
     0 "No"
     1 "Yes"
;
label define M18     
     1 "Very large"
     2 "Larger than average"
     3 "Average"
     4 "Smaller than average"
     5 "Very small"
     8 "Don't know"
;
label define M19     
  9996 "Not weighed at birth"
  9998 "Don't know"
;
label define M19A    
     0 "Not weighed"
     1 "From written card"
     2 "From mother's recall"
     8 "Don't know"
     9 "Special answers"
;
label define M27     
     0 "No flag"
     1 "> interval"
     2 "> interval by 1 month"
     3 "> age at death"
     4 "During pregnancy in calendar"
;
label define M28     
     0 "No flag"
     1 "> interval"
     2 "> interval by 1 month"
     4 "During pregnancy in calendar"
;
label define M29     
     0 "No flag"
     1 "> interval"
     2 "> interval by 1 month"
     4 "During pregnancy in calendar"
;
label define M34     
     0 "Immediately"
   100 "Within first hour"
   101 "Hours: 1"
   199 "Hours: number missing"
   201 "Days: 1"
   299 "Days: number missing"
;
label define M35     
    96 "On demand"
;
label define M36     
    96 "On demand"
;
label define M38     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M39A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M39     
     0 "None"
     7 "7+"
     8 "Don't know"
;
label define M42A    
     0 "No"
     1 "Yes"
;
label define M42B    
     0 "No"
     1 "Yes"
;
label define M42C    
     0 "No"
     1 "Yes"
;
label define M42D    
     0 "No"
     1 "Yes"
;
label define M42E    
     0 "No"
     1 "Yes"
;
label define M43     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M44     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M45     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M46     
     0 "Were not taken"
   998 "Don't know"
;
label define M47     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M48     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49C    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49D    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49E    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49F    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49G    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49X    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49Z    
     0 "No"
     1 "Yes: don't know which drug taken"
     8 "Don't know"
;
label define M49Y    
     0 "No"
     1 "Yes, took no drug"
     8 "Don't know"
;
label define M50     
     0 "No"
     1 "Yes"
;
label define M51     
   100 "Zero hours"
   101 "1 Hours"
   199 "Hours missing"
   200 "0 Days"
   201 "1 Days"
   299 "Days missing"
   301 "1 Week"
   399 "Weeks missing"
   998 "Don't know"
;
label define M52     
    10 "HEALTH PROFESSIONAL"
    11 "Doctor"
    12 "Nurse/midwife"
    13 "Auxiliary midwife"
    20 "OTHER PERSON"
    21 "Traditional birth attendant"
    96 "Other"
;
label define M54     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M55A    
     0 "No"
     1 "Yes"
;
label define M55B    
     0 "No"
     1 "Yes"
;
label define M55C    
     0 "No"
     1 "Yes"
;
label define M55D    
     0 "No"
     1 "Yes"
;
label define M55E    
     0 "No"
     1 "Yes"
;
label define M55F    
     0 "No"
     1 "Yes"
;
label define M55G    
     0 "No"
     1 "Yes"
;
label define M55H    
     0 "No"
     1 "Yes"
;
label define M55I    
     0 "No"
     1 "Yes"
;
label define M55J    
     0 "No"
     1 "Yes"
;
label define M55K    
     0 "No"
     1 "Yes"
;
label define M55L    
     0 "No"
     1 "Yes"
;
label define M55M    
     0 "No"
     1 "Yes"
;
label define M55N    
     0 "No"
     1 "Yes"
;
label define M55O    
     0 "No"
     1 "Yes"
;
label define M55X    
     0 "No"
     1 "Yes"
;
label define M55Z    
     0 "No: given something"
     1 "Yes: given nothing"
;
label define M57A    
     0 "No"
     1 "Yes"
;
label define M57B    
     0 "No"
     1 "Yes"
;
label define M57C    
     0 "No"
     1 "Yes"
;
label define M57D    
     0 "No"
     1 "Yes"
;
label define M57E    
     0 "No"
     1 "Yes"
;
label define M57F    
     0 "No"
     1 "Yes"
;
label define M57G    
     0 "No"
     1 "Yes"
;
label define M57H    
     0 "No"
     1 "Yes"
;
label define M57I    
     0 "No"
     1 "Yes"
;
label define M57J    
     0 "No"
     1 "Yes"
;
label define M57K    
     0 "No"
     1 "Yes"
;
label define M57L    
     0 "No"
     1 "Yes"
;
label define M57M    
     0 "No"
     1 "Yes"
;
label define M57N    
     0 "No"
     1 "Yes"
;
label define M57O    
     0 "No"
     1 "Yes"
;
label define M57P    
     0 "No"
     1 "Yes"
;
label define M57Q    
     0 "No"
     1 "Yes"
;
label define M57R    
     0 "No"
     1 "Yes"
;
label define M57S    
     0 "No"
     1 "Yes"
;
label define M57T    
     0 "No"
     1 "Yes"
;
label define M57U    
     0 "No"
     1 "Yes"
;
label define M57V    
     0 "No"
     1 "Yes"
;
label define M57X    
     0 "No"
     1 "Yes"
;
label define M60     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M61     
   100 "Hours: 0"
   101 "Hours: 1"
   199 "Hours: number missing"
   201 "Days: 1"
   299 "Days: number missing"
   301 "Weeks: 1"
   399 "Weeks: number missing"
   998 "Don't know"
;
label define M62     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M65A    
     0 "No"
     1 "Yes"
;
label define M65B    
     0 "No"
     1 "Yes"
;
label define M65C    
     0 "No"
     1 "Yes"
;
label define M65D    
     0 "No"
     1 "Yes"
;
label define M65E    
     0 "No"
     1 "Yes"
;
label define M65F    
     0 "No"
     1 "Yes"
;
label define M65G    
     0 "No"
     1 "Yes"
;
label define M65H    
     0 "No"
     1 "Yes"
;
label define M65I    
     0 "No"
     1 "Yes"
;
label define M65J    
     0 "No"
     1 "Yes"
;
label define M65K    
     0 "No"
     1 "Yes"
;
label define M65L    
     0 "No"
     1 "Yes"
;
label define M65X    
     0 "No"
     1 "Yes"
;
label define M66     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M70     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M71     
   100 "Immediately/in first hour"
   101 "Hours: 1"
   199 "Hours: number missing"
   201 "Days: 1"
   299 "Days: number missing"
   301 "Weeks: 1"
   399 "Weeks: number missing"
   998 "Don't know"
;
label define M72     
    10 "MEDICAL PERSONNEL"
    11 "Doctor"
    12 "Nurse, midwife"
    13 "Auxiliary midwife"
    20 "OTHER PERSON"
    21 "Traditional birth attendant"
    22 "Community/village health worker"
    96 "Other"
;
label define M73     
    10 "HOME"
    11 "Respondent's home"
    12 "Other home"
    20 "PUBLIC SECTOR"
    21 "Government hospital"
    22 "Government health center"
    23 "Government health post"
    26 "Other public sector"
    30 "PRIVATE SECTOR"
    31 "Private hospital, clinic"
    36 "Other private sector"
    96 "Other"
;
label define H1      
     0 "No card"
     1 "Yes, seen"
     2 "Yes, not seen"
     3 "No longer has card"
;
label define H2      
     0 "No"
     1 "Vaccination date on card"
     2 "Reported by mother"
     3 "Vaccination marked on card"
     8 "Don't know"
;
label define H2D     
    97 "Inconsistent"
    98 "Don't know"
;
label define H2M     
    97 "Inconsistent"
    98 "Don't know"
;
label define H2Y     
  9997 "Inconsistent"
  9998 "Don't know"
;
label define H3      
     0 "No"
     1 "Vaccination date on card"
     2 "Reported by mother"
     3 "Vaccination marked on card"
     8 "Don't know"
;
label define H3D     
    97 "Inconsistent"
    98 "Don't know"
;
label define H3M     
    97 "Inconsistent"
    98 "Don't know"
;
label define H3Y     
  9997 "Inconsistent"
  9998 "Don't know"
;
label define H4      
     0 "No"
     1 "Vaccination date on card"
     2 "Reported by mother"
     3 "Vaccination marked on card"
     8 "Don't know"
;
label define H4D     
    97 "Inconsistent"
    98 "Don't know"
;
label define H4M     
    97 "Inconsistent"
    98 "Don't know"
;
label define H4Y     
  9997 "Inconsistent"
  9998 "Don't know"
;
label define H5      
     0 "No"
     1 "Vaccination date on card"
     2 "Reported by mother"
     3 "Vaccination marked on card"
     8 "Don't know"
;
label define H5D     
    97 "Inconsistent"
    98 "Don't know"
;
label define H5M     
    97 "Inconsistent"
    98 "Don't know"
;
label define H5Y     
  9997 "Inconsistent"
  9998 "Don't know"
;
label define H6      
     0 "No"
     1 "Vaccination date on card"
     2 "Reported by mother"
     3 "Vaccination marked on card"
     8 "Don't know"
;
label define H6D     
    97 "Inconsistent"
    98 "Don't know"
;
label define H6M     
    97 "Inconsistent"
    98 "Don't know"
;
label define H6Y     
  9997 "Inconsistent"
  9998 "Don't know"
;
label define H7      
     0 "No"
     1 "Vaccination date on card"
     2 "Reported by mother"
     3 "Vaccination marked on card"
     8 "Don't know"
;
label define H7D     
    97 "Inconsistent"
    98 "Don't know"
;
label define H7M     
    97 "Inconsistent"
    98 "Don't know"
;
label define H7Y     
  9997 "Inconsistent"
  9998 "Don't know"
;
label define H8      
     0 "No"
     1 "Vaccination date on card"
     2 "Reported by mother"
     3 "Vaccination marked on card"
     8 "Don't know"
;
label define H8D     
    97 "Inconsistent"
    98 "Don't know"
;
label define H8M     
    97 "Inconsistent"
    98 "Don't know"
;
label define H8Y     
  9997 "Inconsistent"
  9998 "Don't know"
;
label define H9      
     0 "No"
     1 "Vaccination date on card"
     2 "Reported by mother"
     3 "Vaccination marked on card"
     8 "Don't know"
;
label define H9D     
    97 "Inconsistent"
    98 "Don't know"
;
label define H9M     
    97 "Inconsistent"
    98 "Don't know"
;
label define H9Y     
  9997 "Inconsistent"
  9998 "Don't know"
;
label define H0      
     0 "No"
     1 "Vaccination date on card"
     2 "Reported by mother"
     3 "Vaccination marked on card"
     8 "Don't know"
;
label define H0D     
    97 "Inconsistent"
    98 "Don't know"
;
label define H0M     
    97 "Inconsistent"
    98 "Don't know"
;
label define H0Y     
  9997 "Inconsistent"
  9998 "Don't know"
;
label define H10     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H11     
     0 "No"
     1 "Yes, last 24 hours"
     2 "Yes, last two weeks"
     8 "Don't know"
;
label define H11B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H12A    
     0 "No"
     1 "Yes"
;
label define H12B    
     0 "No"
     1 "Yes"
;
label define H12C    
     0 "No"
     1 "Yes"
;
label define H12D    
     0 "No"
     1 "Yes"
;
label define H12E    
     0 "No"
     1 "Yes"
;
label define H12F    
     0 "No"
     1 "Yes"
;
label define H12G    
     0 "No"
     1 "Yes"
;
label define H12H    
     0 "No"
     1 "Yes"
;
label define H12I    
     0 "No"
     1 "Yes"
;
label define H12J    
     0 "No"
     1 "Yes"
;
label define H12K    
     0 "No"
     1 "Yes"
;
label define H12L    
     0 "No"
     1 "Yes"
;
label define H12M    
     0 "No"
     1 "Yes"
;
label define H12N    
     0 "No"
     1 "Yes"
;
label define H12O    
     0 "No"
     1 "Yes"
;
label define H12P    
     0 "No"
     1 "Yes"
;
label define H12Q    
     0 "No"
     1 "Yes"
;
label define H12R    
     0 "No"
     1 "Yes"
;
label define H12S    
     0 "No"
     1 "Yes"
;
label define H12T    
     0 "No"
     1 "Yes"
;
label define H12U    
     0 "No"
     1 "Yes"
;
label define H12V    
     0 "No"
     1 "Yes"
;
label define H12W    
     0 "No"
     1 "Yes"
;
label define H12X    
     0 "No"
     1 "Yes"
;
label define H12Y    
     0 "No: received treatment"
     1 "Yes: no treatment"
;
label define H12Z    
     0 "No"
     1 "Yes"
;
label define H13     
     0 "No"
     1 "Yes: ORS - spontaneous"
     2 "Yes: ORS - probed"
     8 "Don't know"
;
label define H13B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H14     
     0 "No"
     1 "Yes: RHS - spontaneous"
     2 "Yes: RHS - probed"
     8 "Don't know"
;
label define H15     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H15A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H15B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H15C    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H15D    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H15E    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H15F    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H15G    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H15H    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H15I    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H15J    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H15K    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H15L    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H15M    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H20     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H21A    
     0 "No: received treatment"
     1 "Yes: no treatment"
     8 "Don't know"
;
label define H21     
     0 "No"
     1 "Yes"
;
label define H22     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H31     
     0 "No"
     1 "Yes, last 24 hours"
     2 "Yes, last two weeks"
     8 "Don't know"
;
label define H31B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H31C    
     1 "Chest only"
     2 "Nose only"
     3 "Both"
     6 "Other"
     8 "Don't know"
;
label define H31D    
     0 "Nothing to drink"
     2 "Much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define H31E    
     0 "Stopped food"
     1 "Never gave food"
     2 "Much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define H32A    
     0 "No"
     1 "Yes"
;
label define H32B    
     0 "No"
     1 "Yes"
;
label define H32C    
     0 "No"
     1 "Yes"
;
label define H32D    
     0 "No"
     1 "Yes"
;
label define H32E    
     0 "No"
     1 "Yes"
;
label define H32F    
     0 "No"
     1 "Yes"
;
label define H32G    
     0 "No"
     1 "Yes"
;
label define H32H    
     0 "No"
     1 "Yes"
;
label define H32I    
     0 "No"
     1 "Yes"
;
label define H32J    
     0 "No"
     1 "Yes"
;
label define H32K    
     0 "No"
     1 "Yes"
;
label define H32L    
     0 "No"
     1 "Yes"
;
label define H32M    
     0 "No"
     1 "Yes"
;
label define H32N    
     0 "No"
     1 "Yes"
;
label define H32O    
     0 "No"
     1 "Yes"
;
label define H32P    
     0 "No"
     1 "Yes"
;
label define H32Q    
     0 "No"
     1 "Yes"
;
label define H32R    
     0 "No"
     1 "Yes"
;
label define H32S    
     0 "No"
     1 "Yes"
;
label define H32T    
     0 "No"
     1 "Yes"
;
label define H32U    
     0 "No"
     1 "Yes"
;
label define H32V    
     0 "No"
     1 "Yes"
;
label define H32W    
     0 "No"
     1 "Yes"
;
label define H32X    
     0 "No"
     1 "Yes"
;
label define H32Y    
     0 "No: received treatment"
     1 "Yes: no treatment"
;
label define H32Z    
     0 "No"
     1 "Yes"
;
label define H33     
     0 "No"
     1 "Vaccination date on card"
     2 "Reported by mother"
     3 "Vaccination marked on card"
     8 "Don't know"
;
label define H33D    
    97 "Inconsistent"
    98 "Don't know"
;
label define H33M    
    97 "Inconsistent"
    98 "Don't know"
;
label define H33Y    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define H34     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H35     
     0 "No"
     1 "Yes"
     2 "No vaccination in last 2 years"
     8 "Don't know"
;
label define H36A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H36B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H36C    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H36D    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H36E    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H36F    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H37A    
     0 "No"
     1 "Yes"
;
label define H37B    
     0 "No"
     1 "Yes"
;
label define H37C    
     0 "No"
     1 "Yes"
;
label define H37D    
     0 "No"
     1 "Yes"
;
label define H37E    
     0 "No"
     1 "Yes"
;
label define H37F    
     0 "No"
     1 "Yes"
;
label define H37G    
     0 "No"
     1 "Yes"
;
label define H37H    
     0 "No"
     1 "Yes"
;
label define H37I    
     0 "No"
     1 "Yes"
;
label define H37J    
     0 "No"
     1 "Yes"
;
label define H37K    
     0 "No"
     1 "Yes"
;
label define H37L    
     0 "No"
     1 "Yes"
;
label define H37M    
     0 "No"
     1 "Yes"
;
label define H37N    
     0 "No"
     1 "Yes"
;
label define H37O    
     0 "No"
     1 "Yes"
;
label define H37P    
     0 "No"
     1 "Yes"
;
label define H37X    
     0 "No"
     1 "Yes"
;
label define H37Y    
     0 "No"
     1 "Yes, nothing taken"
;
label define H37Z    
     0 "No"
     1 "Yes, don't know"
;
label define H38     
     0 "Nothing to drink"
     2 "Much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define H39     
     0 "Stopped food"
     1 "Never gave food"
     2 "Much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define H40     
     0 "No"
     1 "Vaccination date on card"
     2 "Reported by mother"
     3 "Vaccination marked on card"
     8 "Don't know"
;
label define H40D    
    97 "Inconsistent"
    98 "Don't know"
;
label define H40M    
    97 "Inconsistent"
    98 "Don't know"
;
label define H40Y    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define H41A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H41B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H42     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H43     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H44A    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "CS public"
    13 "CS public"
    14 "CS public"
    15 "CS public"
    16 "CS public"
    20 "PRIVATE SECTOR"
    21 "Private hospital, clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "CS private"
    25 "CS private"
    26 "CS private"
    30 "OTHER"
    31 "CS other"
    32 "CS other"
    96 "Other"
;
label define H44B    
     0 "Same day"
    98 "Don't know"
;
label define H44C    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H45     
    98 "Don't know"
;
label define H46A    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Government health post"
    14 "Free mobile clinic"
    15 "Role model caregiver/community worker"
    16 "Other public sector"
    20 "PRIVATE SECTOR"
    21 "Private hospital, clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "Chemist/PMV"
    25 "Private mobile clinic"
    26 "Other private sector"
    30 "OTHER"
    31 "Shop"
    32 "Traditional practitioner"
    33 "Drug hawker"
    96 "Other"
;
label define H46B    
     0 "Same day"
    98 "Don't know"
;
label define H47     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HW2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HW3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HW4     
  9998 "Flagged cases"
;
label define HW5     
  9998 "Flagged cases"
;
label define HW6     
 99998 "Flagged cases"
;
label define HW7     
  9998 "Flagged cases"
;
label define HW8     
  9998 "Flagged cases"
;
label define HW9     
 99998 "Flagged cases"
;
label define HW10    
  9998 "Flagged cases"
;
label define HW11    
  9998 "Flagged cases"
;
label define HW12    
 99998 "Flagged cases"
;
label define HW13    
     0 "Measured"
     1 "Dead"
     2 "Sick"
     3 "Not present"
     4 "Refused"
     5 "Mother refused"
     6 "Other"
     7 "No measurement found in household"
;
label define HW15    
     0 "Not measured"
     1 "Lying"
     2 "Standing"
;
label define HW16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HW51    
     0 "Not in household"
;
label define HW52    
     1 "Granted"
     2 "Refused"
     4 "Not present"
     6 "Other"
;
label define HW53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HW55    
     0 "Measured"
     1 "Dead"
     3 "Not present"
     4 "Refused"
     6 "Other"
     7 "No measurement found in household"
;
label define HW56    
  9997 "Inconsistent"
;
label define HW57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HW58    
     0 "No"
     1 "Yes"
;
label define HW70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HW71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HW72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HW73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define ML0     
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define ML1     
    98 "Don't know"
;
label define ML2     
     1 "Antenatal visit"
     2 "Another facility visit"
     3 "Community health extrension worker (CHEW)"
     6 "Other source"
;
label define ML11    
     0 "No"
     1 "Yes, fever only"
     2 "Yes, cough only"
     3 "Both fever and cough"
     8 "Don't know"
;
label define ML12    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define ML13A   
     0 "No"
     1 "Yes"
;
label define ML13B   
     0 "No"
     1 "Yes"
;
label define ML13C   
     0 "No"
     1 "Yes"
;
label define ML13D   
     0 "No"
     1 "Yes"
;
label define ML13E   
     0 "No"
     1 "Yes"
;
label define ML13F   
     0 "No"
     1 "Yes"
;
label define ML13G   
     0 "No"
     1 "Yes"
;
label define ML13H   
     0 "No"
     1 "Yes"
;
label define ML13I   
     0 "No"
     1 "Yes"
;
label define ML13J   
     0 "No"
     1 "Yes"
;
label define ML13K   
     0 "No"
     1 "Yes"
;
label define ML13L   
     0 "No"
     1 "Yes"
;
label define ML13M   
     0 "No"
     1 "Yes"
;
label define ML13N   
     0 "No"
     1 "Yes"
;
label define ML13O   
     0 "No"
     1 "Yes"
;
label define ML13P   
     0 "No"
     1 "Yes"
;
label define ML13X   
     0 "No"
     1 "Yes"
;
label define ML13Y   
     0 "No"
     1 "Yes, nothing taken"
;
label define ML13Z   
     0 "No"
     1 "Yes, don't know"
;
label define ML14A   
     0 "No"
     1 "Yes"
;
label define ML14B   
     0 "No"
     1 "Yes"
;
label define ML14Y   
     0 "No"
     1 "Yes"
;
label define ML14Z   
     0 "No"
     1 "Yes"
;
label define ML15A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML15B   
     7 "7+ days"
     8 "Don't know"
;
label define ML15C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML16A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML16B   
     7 "7+ days"
     8 "Don't know"
;
label define ML16C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML17A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML17B   
     7 "7+ days"
     8 "Don't know"
;
label define ML17C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML18A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML18B   
     7 "7+ days"
     8 "Don't know"
;
label define ML18C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML19A   
     0 "No"
     1 "Yes"
;
label define ML19B   
     0 "No"
     1 "Yes"
;
label define ML19C   
     0 "No"
     1 "Yes"
;
label define ML19D   
     0 "No"
     1 "Yes"
;
label define ML19E   
     0 "No"
     1 "Yes"
;
label define ML19F   
     0 "No"
     1 "Yes"
;
label define ML19X   
     0 "No"
     1 "Yes"
;
label define ML19Y   
     0 "No"
     1 "Yes"
;
label define ML19Z   
     0 "No"
     1 "Yes"
;
label define ML20A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML20B   
     7 "7+ days"
     8 "Don't know"
;
label define ML20C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML21A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML21B   
     7 "7+ days"
     8 "Don't know"
;
label define ML21C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML22A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML22B   
     7 "7+ days"
     8 "Don't know"
;
label define ML22C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML23A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML23B   
     7 "7+ days"
     8 "Don't know"
;
label define ML23C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML24C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define SSTATE  
    10 "SOKOTO"
    20 "ZAMFARA"
    30 "KATSINA"
    40 "JIGAWA"
    50 "YOBE"
    60 "BORNO"
    70 "ADAMAWA"
    80 "GOMBE"
    90 "BAUCHI"
   100 "KANO"
   110 "KADUNA"
   120 "KEBBI"
   130 "NIGER"
   140 "FCT ABUJA"
   150 "NASARAWA"
   160 "PLATEAU"
   170 "TARABA"
   180 "BENUE"
   190 "KOGI"
   200 "KWARA"
   210 "OYO"
   220 "OSUN"
   230 "EKITI"
   240 "ONDO"
   250 "EDO"
   260 "ANAMBRA"
   270 "ENUGU"
   280 "EBONYI"
   290 "CROSS RIVER"
   300 "AKWA IBOM"
   310 "ABIA"
   320 "IMO"
   330 "RIVERS"
   340 "BAYELSA"
   350 "DELTA"
   360 "LAGOS"
   370 "OGUN"
;
label define SLANGINT
     1 "Hausa"
     2 "Yoruba"
     3 "Igbo"
     4 "English"
     6 "Other"
;
label define SLANGNAT
     1 "Hausa"
     2 "Yoruba"
     3 "Igbo"
     4 "English"
     6 "Other"
;
label define STRANSL 
     0 "No"
     1 "Yes"
;
label define S107D   
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define S107G   
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define S107H   
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define S107I   
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define S107J   
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define S107K   
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define S107L   
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define S501    
     0 "No"
     1 "Yes"
;
label define S502A   
     0 "No"
     1 "Yes"
;
label define S502B   
     0 "No"
     1 "Yes"
;
label define S502C   
     0 "No"
     1 "Yes"
;
label define S502D   
     0 "No"
     1 "Yes"
;
label define S502E   
     0 "No"
     1 "Yes"
;
label define S502F   
     0 "No"
     1 "Yes"
;
label define S502G   
     0 "No"
     1 "Yes"
;
label define S502H   
     0 "No"
     1 "Yes"
;
label define S502I   
     0 "No"
     1 "Yes"
;
label define S502X   
     0 "No"
     1 "Yes"
;
label define S502Z   
     0 "No"
     1 "Yes"
;
label define S503A   
     0 "No"
     1 "Yes"
;
label define S503B   
     0 "No"
     1 "Yes"
;
label define S503C   
     0 "No"
     1 "Yes"
;
label define S503D   
     0 "No"
     1 "Yes"
;
label define S503E   
     0 "No"
     1 "Yes"
;
label define S503Z   
     0 "No"
     1 "Yes"
;
label define S504A   
     0 "No"
     1 "Yes"
;
label define S504B   
     0 "No"
     1 "Yes"
;
label define S504C   
     0 "No"
     1 "Yes"
;
label define S504D   
     0 "No"
     1 "Yes"
;
label define S504E   
     0 "No"
     1 "Yes"
;
label define S504X   
     0 "No"
     1 "Yes"
;
label define S504Z   
     0 "No"
     1 "Yes"
;
label define S505    
     0 "No"
     1 "Yes"
;
label define S506A   
     0 "No"
     1 "Yes"
;
label define S506B   
     0 "No"
     1 "Yes"
;
label define S506C   
     0 "No"
     1 "Yes"
;
label define S506D   
     0 "No"
     1 "Yes"
;
label define S506E   
     0 "No"
     1 "Yes"
;
label define S506F   
     0 "No"
     1 "Yes"
;
label define S506G   
     0 "No"
     1 "Yes"
;
label define S506H   
     0 "No"
     1 "Yes"
;
label define S506I   
     0 "No"
     1 "Yes"
;
label define S506X   
     0 "No"
     1 "Yes"
;
label define S506Z   
     0 "No"
     1 "Yes"
;
label define S507A   
     0 "No"
     1 "Yes"
;
label define S507B   
     0 "No"
     1 "Yes"
;
label define S507C   
     0 "No"
     1 "Yes"
;
label define S507D   
     0 "No"
     1 "Yes"
;
label define S507E   
     0 "No"
     1 "Yes"
;
label define S507F   
     0 "No"
     1 "Yes"
;
label define S507G   
     0 "No"
     1 "Yes"
;
label define S507H   
     0 "No"
     1 "Yes"
;
label define S507I   
     0 "No"
     1 "Yes"
;
label define S507J   
     0 "No"
     1 "Yes"
;
label define S507X   
     0 "No"
     1 "Yes"
;
label define S507Z   
     0 "No"
     1 "Yes"
;
label define S508A   
     0 "No"
     1 "Yes"
;
label define S508B   
     0 "No"
     1 "Yes"
;
label define S508C   
     0 "No"
     1 "Yes"
;
label define S508D   
     0 "No"
     1 "Yes"
;
label define S508E   
     0 "No"
     1 "Yes"
;
label define S508X   
     0 "No"
     1 "Yes"
;
label define S508Z   
     0 "No"
     1 "Yes"
;
label define S509    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define S510A   
     0 "No"
     1 "Yes"
;
label define S510B   
     0 "No"
     1 "Yes"
;
label define S510C   
     0 "No"
     1 "Yes"
;
label define S510D   
     0 "No"
     1 "Yes"
;
label define S510E   
     0 "No"
     1 "Yes"
;
label define S510F   
     0 "No"
     1 "Yes"
;
label define S510G   
     0 "No"
     1 "Yes"
;
label define S510X   
     0 "No"
     1 "Yes"
;
label define S510Z   
     0 "No"
     1 "Yes"
;
label define S511A   
     0 "No"
     1 "Yes"
;
label define S511B   
     0 "No"
     1 "Yes"
;
label define S511C   
     0 "No"
     1 "Yes"
;
label define S511D   
     0 "No"
     1 "Yes"
;
label define S511E   
     0 "No"
     1 "Yes"
;
label define S511F   
     0 "No"
     1 "Yes"
;
label define S511G   
     0 "No"
     1 "Yes"
;
label define S511X   
     0 "No"
     1 "Yes"
;
label define S511Z   
     0 "No"
     1 "Yes"
;
label define S512    
     0 "No"
     1 "Yes"
;
label define S513A   
     0 "No"
     1 "Yes"
;
label define S513B   
     0 "No"
     1 "Yes"
;
label define S513C   
     0 "No"
     1 "Yes"
;
label define S513D   
     0 "No"
     1 "Yes"
;
label define S513E   
     0 "No"
     1 "Yes"
;
label define S513F   
     0 "No"
     1 "Yes"
;
label define S513G   
     0 "No"
     1 "Yes"
;
label define S513H   
     0 "No"
     1 "Yes"
;
label define S513I   
     0 "No"
     1 "Yes"
;
label define S513J   
     0 "No"
     1 "Yes"
;
label define S513K   
     0 "No"
     1 "Yes"
;
label define S513L   
     0 "No"
     1 "Yes"
;
label define S513X   
     0 "No"
     1 "Yes"
;
label define S513Z   
     0 "No"
     1 "Yes"
;
label define S514A   
     0 "No"
     1 "Yes"
;
label define S514B   
     0 "No"
     1 "Yes"
;
label define S514C   
     0 "No"
     1 "Yes"
;
label define S514D   
     0 "No"
     1 "Yes"
;
label define S514E   
     0 "No"
     1 "Yes"
;
label define S514F   
     0 "No"
     1 "Yes"
;
label define S514G   
     0 "No"
     1 "Yes"
;
label define S514H   
     0 "No"
     1 "Yes"
;
label define S514I   
     0 "No"
     1 "Yes"
;
label define S514J   
     0 "No"
     1 "Yes"
;
label define S514K   
     0 "No"
     1 "Yes"
;
label define S514L   
     0 "No"
     1 "Yes"
;
label define S514M   
     0 "No"
     1 "Yes"
;
label define S514N   
     0 "No"
     1 "Yes"
;
label define S514O   
     0 "No"
     1 "Yes"
;
label define S514P   
     0 "No"
     1 "Yes"
;
label define S514Q   
     0 "No"
     1 "Yes"
;
label define S514X   
     0 "No"
     1 "Yes"
;
label define S515A   
     1 "Agree"
     2 "Disagree"
     8 "Don't know"
;
label define S515B   
     1 "Agree"
     2 "Disagree"
     8 "Don't know"
;
label define S515C   
     1 "Agree"
     2 "Disagree"
     8 "Don't know"
;
label define S515D   
     1 "Agree"
     2 "Disagree"
     8 "Don't know"
;
label define S515AA  
     0 "No"
     1 "Yes"
;
label define S516A   
     0 "No"
     1 "Yes"
;
label define S516B   
     0 "No"
     1 "Yes"
;
label define S516C   
     0 "No"
     1 "Yes"
;
label define S516D   
     0 "No"
     1 "Yes"
;
label define S516E   
     0 "No"
     1 "Yes"
;
label define S516X   
     0 "No"
     1 "Yes"
;
label define S516Z   
     0 "No"
     1 "Yes"
;
label define S516AA  
     1 "Green"
     2 "Dark blue"
     3 "Light blue"
     4 "Red"
     5 "Black"
     6 "White"
    96 "Other"
    98 "Don't know/no preference"
;
label define S516BB  
     1 "Conical"
     2 "Rectangle"
     6 "Other"
     8 "Don't know/no preference"
;
label define S516CC  
     1 "Cot/crib"
     2 "Single"
     3 "Double"
     4 "Triple"
     6 "Other"
     8 "Don't know/no preference"
;
label define S516DD  
     0 "Show pictures of nets"
     1 "Permanet"
     2 "Olyset"
     3 "Iconlife"
     4 "Duranet"
     5 "Netprotect"
     6 "Basf interceptor"
    96 "Other"
    98 "Don't know/no preference"
;
label define S310    
     0 "No"
     1 "Yes"
;
label define S404A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define S405A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define S405B   
     1 "Positive"
     2 "Negative"
     8 "Don't know"
;
label define S411F   
     0 "No"
     1 "Yes"
;
label define S411G   
     0 "No"
     1 "Yes"
;

#delimit cr
label values v013     V013    
label values v014     V014    
label values v015     V015    
label values v018     V018    
label values v019     V019    
label values v019a    V019A   
label values v020     V020    
label values v022     V022    
label values v023     V023    
label values v024     V024    
label values v025     V025    
label values v026     V026    
label values v034     V034    
label values v042     V042    
label values v044     V044    
label values v101     V101    
label values v102     V102    
label values v103     V103    
label values v104     V104    
label values v105     V105    
label values v106     V106    
label values v107     V107    
label values v113     V113    
label values v115     V115    
label values v116     V116    
label values v119     V119    
label values v120     V120    
label values v121     V121    
label values v122     V122    
label values v123     V123    
label values v124     V124    
label values v125     V125    
label values v127     V127    
label values v128     V128    
label values v129     V129    
label values v130     V130    
label values v131     V131    
label values v133     V133    
label values v134     V134    
label values v135     V135    
label values v139     V139    
label values v140     V140    
label values v141     V141    
label values v149     V149    
label values v150     V150    
label values v151     V151    
label values v152     V152    
label values v153     V153    
label values v155     V155    
label values v156     V156    
label values v157     V157    
label values v158     V158    
label values v159     V159    
label values v160     V160    
label values v161     V161    
label values v166     V166    
label values v167     V167    
label values v168     V168    
label values v190     V190    
label values v190a    V190A   
label values ml101    ML101   
label values v208     V208    
label values v209     V209    
label values v213     V213    
label values v215     V215    
label values v216     V216    
label values v217     V217    
label values v220     V220    
label values v221     V221    
label values v223     V223    
label values v225     V225    
label values v226     V226    
label values v227     V227    
label values v228     V228    
label values v229     V229    
label values v230     V230    
label values v231     V231    
label values v232     V232    
label values v233     V233    
label values v234     V234    
label values v235     V235    
label values v237     V237    
label values v239     V239    
label values v240     V240    
label values v241     V241    
label values v242     V242    
label values v243     V243    
label values v401     V401    
label values v404     V404    
label values v405     V405    
label values v406     V406    
label values v407     V407    
label values v408     V408    
label values v409     V409    
label values v409a    V409A   
label values v410     V410    
label values v410a    V410A   
label values v411     V411    
label values v411a    V411A   
label values v412     V412    
label values v412a    V412A   
label values v412b    V412B   
label values v412c    V412C   
label values v413     V413    
label values v413a    V413A   
label values v413b    V413B   
label values v413c    V413C   
label values v413d    V413D   
label values v414a    V414A   
label values v414b    V414B   
label values v414c    V414C   
label values v414d    V414D   
label values v414e    V414E   
label values v414f    V414F   
label values v414g    V414G   
label values v414h    V414H   
label values v414i    V414I   
label values v414j    V414J   
label values v414k    V414K   
label values v414l    V414L   
label values v414m    V414M   
label values v414n    V414N   
label values v414o    V414O   
label values v414p    V414P   
label values v414q    V414Q   
label values v414r    V414R   
label values v414s    V414S   
label values v414t    V414T   
label values v414u    V414U   
label values v414v    V414V   
label values v414w    V414W   
label values v415     V415    
label values v416     V416    
label values v426     V426    
label values v437     V437    
label values v438     V438    
label values v439     V439    
label values v440     V440    
label values v441     V441    
label values v442     V442    
label values v443     V443    
label values v444     V444    
label values v444a    V444A   
label values v445     V445    
label values v446     V446    
label values v447     V447    
label values v452a    V452A   
label values v452b    V452B   
label values v452c    V452C   
label values v454     V454    
label values v455     V455    
label values v457     V457    
label values v458     V458    
label values v459     V459    
label values v460     V460    
label values v461     V461    
label values v462     V462    
label values v463a    V463A   
label values v463b    V463B   
label values v463c    V463C   
label values v463d    V463D   
label values v463e    V463E   
label values v463f    V463F   
label values v463g    V463G   
label values v463x    V463X   
label values v463z    V463Z   
label values v464     V464    
label values v465     V465    
label values v466     V466    
label values v467a    V467A   
label values v467b    V467B   
label values v467c    V467C   
label values v467d    V467D   
label values v467e    V467E   
label values v467f    V467F   
label values v467g    V467G   
label values v467h    V467H   
label values v467i    V467I   
label values v467j    V467J   
label values v467k    V467K   
label values v467l    V467L   
label values v467m    V467M   
label values v468     V468    
label values v469e    V469E   
label values v469f    V469F   
label values v469x    V469X   
label values v471a    V471A   
label values v471b    V471B   
label values v471c    V471C   
label values v471d    V471D   
label values v471e    V471E   
label values v471f    V471F   
label values v471g    V471G   
label values v472a    V472A   
label values v472b    V472B   
label values v472c    V472C   
label values v472d    V472D   
label values v472e    V472E   
label values v472f    V472F   
label values v472g    V472G   
label values v472h    V472H   
label values v472i    V472I   
label values v472j    V472J   
label values v472k    V472K   
label values v472l    V472L   
label values v472m    V472M   
label values v472n    V472N   
label values v472o    V472O   
label values v472p    V472P   
label values v472q    V472Q   
label values v472r    V472R   
label values v472s    V472S   
label values v472t    V472T   
label values v472u    V472U   
label values v473a    V473A   
label values v473b    V473B   
label values v474     V474    
label values v474a    V474A   
label values v474b    V474B   
label values v474c    V474C   
label values v474d    V474D   
label values v474e    V474E   
label values v474f    V474F   
label values v474g    V474G   
label values v474h    V474H   
label values v474i    V474I   
label values v474j    V474J   
label values v474x    V474X   
label values v474z    V474Z   
label values v475     V475    
label values v476     V476    
label values v477     V477    
label values v478     V478    
label values v479     V479    
label values v480     V480    
label values v481     V481    
label values v481a    V481A   
label values v481b    V481B   
label values v481c    V481C   
label values v481d    V481D   
label values v481e    V481E   
label values v481f    V481F   
label values v481g    V481G   
label values v481h    V481H   
label values v481x    V481X   
label values v482a    V482A   
label values v482b    V482B   
label values v482c    V482C   
label values b0       B0      
label values b4       B4      
label values b5       B5      
label values b6       B6      
label values b9       B9      
label values b10      B10     
label values b13      B13     
label values b15      B15     
label values b16      B16     
label values m1       M1      
label values m1a      M1A     
label values m1b      M1B     
label values m1c      M1C     
label values m1e      M1E     
label values m2a      M2A     
label values m2b      M2B     
label values m2c      M2C     
label values m2d      M2D     
label values m2e      M2E     
label values m2f      M2F     
label values m2g      M2G     
label values m2h      M2H     
label values m2i      M2I     
label values m2j      M2J     
label values m2k      M2K     
label values m2l      M2L     
label values m2m      M2M     
label values m2n      M2N     
label values m3a      M3A     
label values m3b      M3B     
label values m3c      M3C     
label values m3d      M3D     
label values m3e      M3E     
label values m3f      M3F     
label values m3g      M3G     
label values m3h      M3H     
label values m3i      M3I     
label values m3j      M3J     
label values m3k      M3K     
label values m3l      M3L     
label values m3m      M3M     
label values m3n      M3N     
label values m4       M4      
label values m5       M5      
label values m6       M6      
label values m7       M7      
label values m8       M8      
label values m9       M9      
label values m10      M10     
label values m11      M11     
label values m13      M13     
label values m14      M14     
label values m15      M15     
label values m17      M17     
label values m18      M18     
label values m19      M19     
label values m19a     M19A    
label values m27      M27     
label values m28      M28     
label values m29      M29     
label values m34      M34     
label values m35      M35     
label values m36      M36     
label values m38      M38     
label values m39a     M39A    
label values m39      M39     
label values m42a     M42A    
label values m42b     M42B    
label values m42c     M42C    
label values m42d     M42D    
label values m42e     M42E    
label values m43      M43     
label values m44      M44     
label values m45      M45     
label values m46      M46     
label values m47      M47     
label values m48      M48     
label values m49a     M49A    
label values m49b     M49B    
label values m49c     M49C    
label values m49d     M49D    
label values m49e     M49E    
label values m49f     M49F    
label values m49g     M49G    
label values m49x     M49X    
label values m49z     M49Z    
label values m49y     M49Y    
label values m50      M50     
label values m51      M51     
label values m52      M52     
label values m54      M54     
label values m55a     M55A    
label values m55b     M55B    
label values m55c     M55C    
label values m55d     M55D    
label values m55e     M55E    
label values m55f     M55F    
label values m55g     M55G    
label values m55h     M55H    
label values m55i     M55I    
label values m55j     M55J    
label values m55k     M55K    
label values m55l     M55L    
label values m55m     M55M    
label values m55n     M55N    
label values m55o     M55O    
label values m55x     M55X    
label values m55z     M55Z    
label values m57a     M57A    
label values m57b     M57B    
label values m57c     M57C    
label values m57d     M57D    
label values m57e     M57E    
label values m57f     M57F    
label values m57g     M57G    
label values m57h     M57H    
label values m57i     M57I    
label values m57j     M57J    
label values m57k     M57K    
label values m57l     M57L    
label values m57m     M57M    
label values m57n     M57N    
label values m57o     M57O    
label values m57p     M57P    
label values m57q     M57Q    
label values m57r     M57R    
label values m57s     M57S    
label values m57t     M57T    
label values m57u     M57U    
label values m57v     M57V    
label values m57x     M57X    
label values m60      M60     
label values m61      M61     
label values m62      M62     
label values m65a     M65A    
label values m65b     M65B    
label values m65c     M65C    
label values m65d     M65D    
label values m65e     M65E    
label values m65f     M65F    
label values m65g     M65G    
label values m65h     M65H    
label values m65i     M65I    
label values m65j     M65J    
label values m65k     M65K    
label values m65l     M65L    
label values m65x     M65X    
label values m66      M66     
label values m70      M70     
label values m71      M71     
label values m72      M72     
label values m73      M73     
label values h1       H1      
label values h2       H2      
label values h2d      H2D     
label values h2m      H2M     
label values h2y      H2Y     
label values h3       H3      
label values h3d      H3D     
label values h3m      H3M     
label values h3y      H3Y     
label values h4       H4      
label values h4d      H4D     
label values h4m      H4M     
label values h4y      H4Y     
label values h5       H5      
label values h5d      H5D     
label values h5m      H5M     
label values h5y      H5Y     
label values h6       H6      
label values h6d      H6D     
label values h6m      H6M     
label values h6y      H6Y     
label values h7       H7      
label values h7d      H7D     
label values h7m      H7M     
label values h7y      H7Y     
label values h8       H8      
label values h8d      H8D     
label values h8m      H8M     
label values h8y      H8Y     
label values h9       H9      
label values h9d      H9D     
label values h9m      H9M     
label values h9y      H9Y     
label values h0       H0      
label values h0d      H0D     
label values h0m      H0M     
label values h0y      H0Y     
label values h10      H10     
label values h11      H11     
label values h11b     H11B    
label values h12a     H12A    
label values h12b     H12B    
label values h12c     H12C    
label values h12d     H12D    
label values h12e     H12E    
label values h12f     H12F    
label values h12g     H12G    
label values h12h     H12H    
label values h12i     H12I    
label values h12j     H12J    
label values h12k     H12K    
label values h12l     H12L    
label values h12m     H12M    
label values h12n     H12N    
label values h12o     H12O    
label values h12p     H12P    
label values h12q     H12Q    
label values h12r     H12R    
label values h12s     H12S    
label values h12t     H12T    
label values h12u     H12U    
label values h12v     H12V    
label values h12w     H12W    
label values h12x     H12X    
label values h12y     H12Y    
label values h12z     H12Z    
label values h13      H13     
label values h13b     H13B    
label values h14      H14     
label values h15      H15     
label values h15a     H15A    
label values h15b     H15B    
label values h15c     H15C    
label values h15d     H15D    
label values h15e     H15E    
label values h15f     H15F    
label values h15g     H15G    
label values h15h     H15H    
label values h15i     H15I    
label values h15j     H15J    
label values h15k     H15K    
label values h15l     H15L    
label values h15m     H15M    
label values h20      H20     
label values h21a     H21A    
label values h21      H21     
label values h22      H22     
label values h31      H31     
label values h31b     H31B    
label values h31c     H31C    
label values h31d     H31D    
label values h31e     H31E    
label values h32a     H32A    
label values h32b     H32B    
label values h32c     H32C    
label values h32d     H32D    
label values h32e     H32E    
label values h32f     H32F    
label values h32g     H32G    
label values h32h     H32H    
label values h32i     H32I    
label values h32j     H32J    
label values h32k     H32K    
label values h32l     H32L    
label values h32m     H32M    
label values h32n     H32N    
label values h32o     H32O    
label values h32p     H32P    
label values h32q     H32Q    
label values h32r     H32R    
label values h32s     H32S    
label values h32t     H32T    
label values h32u     H32U    
label values h32v     H32V    
label values h32w     H32W    
label values h32x     H32X    
label values h32y     H32Y    
label values h32z     H32Z    
label values h33      H33     
label values h33d     H33D    
label values h33m     H33M    
label values h33y     H33Y    
label values h34      H34     
label values h35      H35     
label values h36a     H36A    
label values h36b     H36B    
label values h36c     H36C    
label values h36d     H36D    
label values h36e     H36E    
label values h36f     H36F    
label values h37a     H37A    
label values h37b     H37B    
label values h37c     H37C    
label values h37d     H37D    
label values h37e     H37E    
label values h37f     H37F    
label values h37g     H37G    
label values h37h     H37H    
label values h37i     H37I    
label values h37j     H37J    
label values h37k     H37K    
label values h37l     H37L    
label values h37m     H37M    
label values h37n     H37N    
label values h37o     H37O    
label values h37p     H37P    
label values h37x     H37X    
label values h37y     H37Y    
label values h37z     H37Z    
label values h38      H38     
label values h39      H39     
label values h40      H40     
label values h40d     H40D    
label values h40m     H40M    
label values h40y     H40Y    
label values h41a     H41A    
label values h41b     H41B    
label values h42      H42     
label values h43      H43     
label values h44a     H44A    
label values h44b     H44B    
label values h44c     H44C    
label values h45      H45     
label values h46a     H46A    
label values h46b     H46B    
label values h47      H47     
label values hw2      HW2     
label values hw3      HW3     
label values hw4      HW4     
label values hw5      HW5     
label values hw6      HW6     
label values hw7      HW7     
label values hw8      HW8     
label values hw9      HW9     
label values hw10     HW10    
label values hw11     HW11    
label values hw12     HW12    
label values hw13     HW13    
label values hw15     HW15    
label values hw16     HW16    
label values hw51     HW51    
label values hw52     HW52    
label values hw53     HW53    
label values hw55     HW55    
label values hw56     HW56    
label values hw57     HW57    
label values hw58     HW58    
label values hw70     HW70    
label values hw71     HW71    
label values hw72     HW72    
label values hw73     HW73    
label values ml0      ML0     
label values ml1      ML1     
label values ml2      ML2     
label values ml11     ML11    
label values ml12     ML12    
label values ml13a    ML13A   
label values ml13b    ML13B   
label values ml13c    ML13C   
label values ml13d    ML13D   
label values ml13e    ML13E   
label values ml13f    ML13F   
label values ml13g    ML13G   
label values ml13h    ML13H   
label values ml13i    ML13I   
label values ml13j    ML13J   
label values ml13k    ML13K   
label values ml13l    ML13L   
label values ml13m    ML13M   
label values ml13n    ML13N   
label values ml13o    ML13O   
label values ml13p    ML13P   
label values ml13x    ML13X   
label values ml13y    ML13Y   
label values ml13z    ML13Z   
label values ml14a    ML14A   
label values ml14b    ML14B   
label values ml14y    ML14Y   
label values ml14z    ML14Z   
label values ml15a    ML15A   
label values ml15b    ML15B   
label values ml15c    ML15C   
label values ml16a    ML16A   
label values ml16b    ML16B   
label values ml16c    ML16C   
label values ml17a    ML17A   
label values ml17b    ML17B   
label values ml17c    ML17C   
label values ml18a    ML18A   
label values ml18b    ML18B   
label values ml18c    ML18C   
label values ml19a    ML19A   
label values ml19b    ML19B   
label values ml19c    ML19C   
label values ml19d    ML19D   
label values ml19e    ML19E   
label values ml19f    ML19F   
label values ml19x    ML19X   
label values ml19y    ML19Y   
label values ml19z    ML19Z   
label values ml20a    ML20A   
label values ml20b    ML20B   
label values ml20c    ML20C   
label values ml21a    ML21A   
label values ml21b    ML21B   
label values ml21c    ML21C   
label values ml22a    ML22A   
label values ml22b    ML22B   
label values ml22c    ML22C   
label values ml23a    ML23A   
label values ml23b    ML23B   
label values ml23c    ML23C   
label values ml24c    ML24C   
label values sstate   SSTATE  
label values slangint SLANGINT
label values slangnat SLANGNAT
label values stransl  STRANSL 
label values s107d    S107D   
label values s107g    S107G   
label values s107h    S107H   
label values s107i    S107I   
label values s107j    S107J   
label values s107k    S107K   
label values s107l    S107L   
label values s501     S501    
label values s502a    S502A   
label values s502b    S502B   
label values s502c    S502C   
label values s502d    S502D   
label values s502e    S502E   
label values s502f    S502F   
label values s502g    S502G   
label values s502h    S502H   
label values s502i    S502I   
label values s502x    S502X   
label values s502z    S502Z   
label values s503a    S503A   
label values s503b    S503B   
label values s503c    S503C   
label values s503d    S503D   
label values s503e    S503E   
label values s503z    S503Z   
label values s504a    S504A   
label values s504b    S504B   
label values s504c    S504C   
label values s504d    S504D   
label values s504e    S504E   
label values s504x    S504X   
label values s504z    S504Z   
label values s505     S505    
label values s506a    S506A   
label values s506b    S506B   
label values s506c    S506C   
label values s506d    S506D   
label values s506e    S506E   
label values s506f    S506F   
label values s506g    S506G   
label values s506h    S506H   
label values s506i    S506I   
label values s506x    S506X   
label values s506z    S506Z   
label values s507a    S507A   
label values s507b    S507B   
label values s507c    S507C   
label values s507d    S507D   
label values s507e    S507E   
label values s507f    S507F   
label values s507g    S507G   
label values s507h    S507H   
label values s507i    S507I   
label values s507j    S507J   
label values s507x    S507X   
label values s507z    S507Z   
label values s508a    S508A   
label values s508b    S508B   
label values s508c    S508C   
label values s508d    S508D   
label values s508e    S508E   
label values s508x    S508X   
label values s508z    S508Z   
label values s509     S509    
label values s510a    S510A   
label values s510b    S510B   
label values s510c    S510C   
label values s510d    S510D   
label values s510e    S510E   
label values s510f    S510F   
label values s510g    S510G   
label values s510x    S510X   
label values s510z    S510Z   
label values s511a    S511A   
label values s511b    S511B   
label values s511c    S511C   
label values s511d    S511D   
label values s511e    S511E   
label values s511f    S511F   
label values s511g    S511G   
label values s511x    S511X   
label values s511z    S511Z   
label values s512     S512    
label values s513a    S513A   
label values s513b    S513B   
label values s513c    S513C   
label values s513d    S513D   
label values s513e    S513E   
label values s513f    S513F   
label values s513g    S513G   
label values s513h    S513H   
label values s513i    S513I   
label values s513j    S513J   
label values s513k    S513K   
label values s513l    S513L   
label values s513x    S513X   
label values s513z    S513Z   
label values s514a    S514A   
label values s514b    S514B   
label values s514c    S514C   
label values s514d    S514D   
label values s514e    S514E   
label values s514f    S514F   
label values s514g    S514G   
label values s514h    S514H   
label values s514i    S514I   
label values s514j    S514J   
label values s514k    S514K   
label values s514l    S514L   
label values s514m    S514M   
label values s514n    S514N   
label values s514o    S514O   
label values s514p    S514P   
label values s514q    S514Q   
label values s514x    S514X   
label values s515a    S515A   
label values s515b    S515B   
label values s515c    S515C   
label values s515d    S515D   
label values s515aa   S515AA  
label values s516a    S516A   
label values s516b    S516B   
label values s516c    S516C   
label values s516d    S516D   
label values s516e    S516E   
label values s516x    S516X   
label values s516z    S516Z   
label values s516aa   S516AA  
label values s516bb   S516BB  
label values s516cc   S516CC  
label values s516dd   S516DD  
label values s310     S310    
label values s404a    S404A   
label values s405a    S405A   
label values s405b    S405B   
label values s411f    S411F   
label values s411g    S411G   
