infix using "C:\COUNTRIES\CG61\CGMR61FL.dct"

label variable mcaseid  "Case Identification"
label variable mv000    "Country code and phase"
label variable mv001    "Cluster number"
label variable mv002    "Household number"
label variable mv003    "Respondent's line number"
label variable mv004    "Ultimate area unit"
label variable mv005    "Men's sample weight (6 decimals)"
label variable mv006    "Month of interview"
label variable mv007    "Year of interview"
label variable mv008    "Date of interview (CMC)"
label variable mv009    "Month of birth"
label variable mv010    "Year of birth"
label variable mv011    "Date of birth (CMC)"
label variable mv012    "Current age"
label variable mv013    "Age in 5-year groups"
label variable mv014    "Completeness of age information"
label variable mv015    "Result of interview"
label variable mv016    "Day of interview"
label variable mv021    "Primary sampling unit"
label variable mv022    "Sample stratum number"
label variable mv023    "NA - Sample domain"
label variable mv024    "Region"
label variable mv025    "Type of place of residence"
label variable mv026    "De facto place of residence"
label variable mv027    "Number of visits"
label variable mv028    "Interviewer identification"
label variable mv029    "Keyer identification"
label variable mv030    "Field supervisor"
label variable mv031    "Field editor"
label variable mv032    "Office editor"
label variable mv034_1  "Line number of wife/partner"
label variable mv034_2  "Line number of wife/partner"
label variable mv034_3  "Line number of wife/partner"
label variable mv034_4  "Line number of wife/partner"
label variable mv034_5  "Line number of wife/partner"
label variable mv034_6  "Line number of wife/partner"
label variable mv034_7  "Line number of wife/partner"
label variable mv034_8  "Line number of wife/partner"
label variable mv034a_1 "NA - Wife or partner***"
label variable mv034a_2 "NA - Wife or partner***"
label variable mv034a_3 "NA - Wife or partner***"
label variable mv034a_4 "NA - Wife or partner***"
label variable mv034a_5 "NA - Wife or partner***"
label variable mv034a_6 "NA - Wife or partner***"
label variable mv034a_7 "NA - Wife or partner***"
label variable mv034a_8 "NA - Wife or partner***"
label variable mv034b_1 "Age of wife/partner"
label variable mv034b_2 "Age of wife/partner"
label variable mv034b_3 "Age of wife/partner"
label variable mv034b_4 "Age of wife/partner"
label variable mv034b_5 "Age of wife/partner"
label variable mv034b_6 "Age of wife/partner"
label variable mv034b_7 "Age of wife/partner"
label variable mv034b_8 "Age of wife/partner"
label variable mv035    "Number of wives/partners"
label variable mv801    "Time interview started (hhmm - 24 hour clock)"
label variable mv802    "Time interview ended (hhmm - 24 hour clock)"
label variable mv803    "Length of interview in minutes"
label variable mv101    "Region"
label variable mv102    "Type of place of residence"
label variable mv103    "NA - Childhood place of residence***"
label variable mv104    "NA - Years lived in place of residence"
label variable mv105    "NA - Type of place of previous residence"
label variable mv106    "Educational level"
label variable mv107    "Highest year of education (at level in MV106)"
label variable mv130    "Religion"
label variable mv131    "Ethnicity"
label variable mv133    "Total number of years of education"
label variable mv134    "De facto place of residence"
label variable mv135    "Usual resident or visitor"
label variable mv136    "Number of household members (total listed)"
label variable mv138    "Number of eligible men in household (de facto)"
label variable mv149    "Educational attainment"
label variable mv150    "Relationship to household head"
label variable mv151    "Sex of household head"
label variable mv152    "Age of household head"
label variable mv155    "Literacy"
label variable mv156    "NA - Ever participated in a literacy program (excluding primary school)"
label variable mv157    "Frequency of reading newspaper or magazine"
label variable mv158    "Frequency of listening to radio"
label variable mv159    "Frequency of watching television"
label variable mv167    "NA - Times away from home in last 12 months"
label variable mv168    "NA - Away for more than one month in last 12 months"
label variable mv190    "Wealth index"
label variable mv191    "Wealth index factor score (5 decimals)"
label variable mv201    "Total children ever born"
label variable mv202    "Sons at home"
label variable mv203    "Daughters at home"
label variable mv204    "Sons elsewhere"
label variable mv205    "Daughters elsewhere"
label variable mv206    "Sons who have died"
label variable mv207    "Daughters who have died"
label variable mv212    "Age of respondent at 1st birth"
label variable mv213    "Partner currently pregnant"
label variable mv217    "NA - Knowledge of ovulatory cycle"
label variable mv218    "Number of living children"
label variable mv225    "NA - Most recent pregnancy wanted***"
label variable mv245    "Number of women fathered children with"
label variable mv246    "NA - Married to mother when first child was born***"
label variable mv247    "NA - Age of most recent child"
label variable mv248    "NA - Antenatal check-ups for the mother of most recent child"
label variable mv249    "NA - Respondent present during check-ups for most recent child"
label variable mv250    "NA - Place of birth of most recent child"
label variable mv251    "NA - Reason for not delivering most recent child in health facility"
label variable mv252    "NA - Amount a child should drink, when that child has diarrhea"
label variable mv301    "Knowledge of any contraceptive method"
label variable mv302    "NA - Ever use of any contraceptive method"
label variable m304a_01 "Type of contraceptive method"
label variable m304a_02 "Type of contraceptive method"
label variable m304a_03 "Type of contraceptive method"
label variable m304a_04 "Type of contraceptive method"
label variable m304a_05 "Type of contraceptive method"
label variable m304a_06 "Type of contraceptive method"
label variable m304a_07 "Type of contraceptive method"
label variable m304a_08 "Type of contraceptive method"
label variable m304a_09 "Type of contraceptive method"
label variable m304a_10 "Type of contraceptive method"
label variable m304a_11 "Type of contraceptive method"
label variable m304a_12 "Type of contraceptive method"
label variable m304a_13 "Type of contraceptive method"
label variable m304a_14 "Type of contraceptive method"
label variable m304a_15 "Type of contraceptive method"
label variable m304a_16 "Type of contraceptive method"
label variable m304a_17 "Type of contraceptive method"
label variable m304a_18 "Type of contraceptive method"
label variable m304a_19 "Type of contraceptive method"
label variable m304a_20 "Type of contraceptive method"
label variable mv304_01 "Knows contraceptive method"
label variable mv304_02 "Knows contraceptive method"
label variable mv304_03 "Knows contraceptive method"
label variable mv304_04 "Knows contraceptive method"
label variable mv304_05 "Knows contraceptive method"
label variable mv304_06 "Knows contraceptive method"
label variable mv304_07 "Knows contraceptive method"
label variable mv304_08 "Knows contraceptive method"
label variable mv304_09 "Knows contraceptive method"
label variable mv304_10 "Knows contraceptive method"
label variable mv304_11 "Knows contraceptive method"
label variable mv304_12 "Knows contraceptive method"
label variable mv304_13 "Knows contraceptive method"
label variable mv304_14 "Knows contraceptive method"
label variable mv304_15 "Knows contraceptive method"
label variable mv304_16 "Knows contraceptive method"
label variable mv304_17 "Knows contraceptive method"
label variable mv304_18 "Knows contraceptive method"
label variable mv304_19 "Knows contraceptive method"
label variable mv304_20 "Knows contraceptive method"
label variable mv305_01 "NA - Ever used contraceptive method"
label variable mv305_02 "NA - Ever used contraceptive method"
label variable mv305_03 "NA - Ever used contraceptive method"
label variable mv305_04 "NA - Ever used contraceptive method"
label variable mv305_05 "NA - Ever used contraceptive method"
label variable mv305_06 "NA - Ever used contraceptive method"
label variable mv305_07 "NA - Ever used contraceptive method"
label variable mv305_08 "NA - Ever used contraceptive method"
label variable mv305_09 "NA - Ever used contraceptive method"
label variable mv305_10 "NA - Ever used contraceptive method"
label variable mv305_11 "NA - Ever used contraceptive method"
label variable mv305_12 "NA - Ever used contraceptive method"
label variable mv305_13 "NA - Ever used contraceptive method"
label variable mv305_14 "NA - Ever used contraceptive method"
label variable mv305_15 "NA - Ever used contraceptive method"
label variable mv305_16 "NA - Ever used contraceptive method"
label variable mv305_17 "NA - Ever used contraceptive method"
label variable mv305_18 "NA - Ever used contraceptive method"
label variable mv305_19 "NA - Ever used contraceptive method"
label variable mv305_20 "NA - Ever used contraceptive method"
label variable mv307_01 "Contraceptive method currently used"
label variable mv307_02 "Contraceptive method currently used"
label variable mv307_03 "Contraceptive method currently used"
label variable mv307_04 "Contraceptive method currently used"
label variable mv307_05 "Contraceptive method currently used"
label variable mv307_06 "Contraceptive method currently used"
label variable mv307_07 "Contraceptive method currently used"
label variable mv307_08 "Contraceptive method currently used"
label variable mv307_09 "Contraceptive method currently used"
label variable mv307_10 "Contraceptive method currently used"
label variable mv307_11 "Contraceptive method currently used"
label variable mv307_12 "Contraceptive method currently used"
label variable mv307_13 "Contraceptive method currently used"
label variable mv307_14 "Contraceptive method currently used"
label variable mv307_15 "Contraceptive method currently used"
label variable mv307_16 "Contraceptive method currently used"
label variable mv307_17 "Contraceptive method currently used"
label variable mv307_18 "Contraceptive method currently used"
label variable mv307_19 "Contraceptive method currently used"
label variable mv307_20 "Contraceptive method currently used"
label variable mv312    "NA - Current contraceptive method"
label variable mv313    "NA - Current contraceptive by method type"
label variable mv323a   "NA - Brand of condom used"
label variable mv325b   "NA - Cost of condoms (in CURRENCY) last time obtained"
label variable mv372a   "NA - Interviewer shown condom package"
label variable mv384a   "NA - On radio heard about Family Planning in the last few months"
label variable mv384b   "NA - On TV saw about Family Planning in the last few months"
label variable mv384c   "NA - In newspaper read about Family Planning in the last few months"
label variable mv395    "NA - Discussed Family Planning with health worker in last few months"
label variable mv396    "NA - Possible for a breastfeeding woman to get pregnant"
label variable mv3a09b  "NA - Number of condoms did get last time"
label variable mv3b17   "Source of condoms"
label variable mv3b25a  "NA - Contraception is woman's business, man should not worry"
label variable mv3b25b  "NA - Women who use contraception become promiscuous"
label variable mv463a   "Smokes cigarettes"
label variable mv463b   "Smokes pipe"
label variable mv463c   "Uses chewing tobacco"
label variable mv463d   "Uses snuff"
label variable mv463e   "NA - Smokes CS"
label variable mv463f   "NA - Smokes CS"
label variable mv463g   "NA - Smokes CS"
label variable mv463x   "Smokes other"
label variable mv463z   "Smokes nothing"
label variable mv464    "Number of cigarettes in last 24 hours"
label variable mv474    "NA - Heard of tuberculosis or TB"
label variable mv474a   "NA - Tuberculosis spread by: air through coughing or sneezing"
label variable mv474b   "NA - Tuberculosis spread by: sharing utensils"
label variable mv474c   "NA - Tuberculosis spread by: touching a person with TB"
label variable mv474d   "NA - Tuberculosis spread by: food"
label variable mv474e   "NA - Tuberculosis spread by: sexual contact"
label variable mv474f   "NA - Tuberculosis spread by: mosquito bites"
label variable mv474g   "NA - Tuberculosis spread by: CS"
label variable mv474h   "NA - Tuberculosis spread by: CS"
label variable mv474i   "NA - Tuberculosis spread by: CS"
label variable mv474j   "NA - Tuberculosis spread by: CS"
label variable mv474x   "NA - Tuberculosis spread by: other"
label variable mv474z   "NA - Don't know how tuberculosis is spread"
label variable mv475    "NA - Tuberculosis can be cured"
label variable mv476    "NA - Would want tuberculosis infection in family to remain secret"
label variable mv477    "Number of injections in last 12 months"
label variable mv478    "Number of injections administered by a health worker"
label variable mv479    "NA - Place where given injection by health worker"
label variable mv480    "Syringe and needle from new, unopened package"
label variable mv481    "Covered by health insurance"
label variable mv481a   "Health insurance type: mutual/community organization"
label variable mv481b   "Health insurance type: provided by employer"
label variable mv481c   "Health insurance type: social security"
label variable mv481d   "Health insurance type: private/commercially purchased"
label variable mv481e   "NA - Health insurance type: CS"
label variable mv481f   "NA - Health insurance type: CS"
label variable mv481g   "NA - Health insurance type: CS"
label variable mv481h   "NA - Health insurance type: CS"
label variable mv481x   "Health insurance type: other"
label variable mv482a   "NA - Arrange care of biological children under age 18***"
label variable mv482b   "NA - Primary caregiver of children under age 18***"
label variable mv482c   "NA - Arrange care of non-biological children < 18***"
label variable mv483    "Respondent circumcised"
label variable mv483a   "Age at circumcision"
label variable mv483b   "Who performed the circumcision"
label variable mv483c   "NA - Place where circumcision was done"
label variable mv501    "Current marital status"
label variable mv502    "Currently/formerly/never in union"
label variable mv503    "Number of unions"
label variable mv504    "Currently residing with wife/partner"
label variable mv505    "Number of wives/partners"
label variable mv507    "Month of first cohabitation"
label variable mv508    "Year of first cohabitation"
label variable mv509    "Date of first cohabitation (CMC)"
label variable mv510    "Completeness of date information in MV509"
label variable mv511    "Age at first cohabitation"
label variable mv512    "Years since first cohabitation"
label variable mv513    "Cohabitation duration (grouped)"
label variable mv525    "Age at first sex"
label variable mv527    "Time since last sex"
label variable mv528    "Time since last sex (in days)"
label variable mv529    "Time since last sex (in months)"
label variable mv531    "Age at first sex (imputed)"
label variable mv532    "Flag for MV531"
label variable mv535    "Ever been married or in union"
label variable mv536    "Recent sexual activity"
label variable mv541    "NA - Intends to wait until marriage to have sex"
label variable mv602    "Fertility preference"
label variable mv603    "Preferred waiting time for birth of a/another child"
label variable mv604    "Preferred waiting time for birth of a/another child (grouped)"
label variable mv605    "Desire for more children"
label variable mv613    "Ideal number of children"
label variable mv614    "Ideal number of children (grouped)"
label variable mv616    "Desired time for future birth"
label variable mv621    "NA - Wife's desire for children***"
label variable mv627    "Ideal number of boys"
label variable mv628    "Ideal number of girls"
label variable mv629    "Ideal number of either sex"
label variable mv631    "NA - Problem if wife became pregnant***"
label variable mv633a   "NA - Wife justified refusing sex: husband has STI"
label variable mv633b   "Wife justified refusing sex: husband has other women"
label variable mv633c   "NA - Wife justified refusing sex: recent birth"
label variable mv633d   "NA - Wife justified refusing sex: tired, not in mood"
label variable mv633e   "NA - Wife justified refusing sex: CS reason"
label variable mv633f   "NA - Wife justified refusing sex: CS reason"
label variable mv633g   "NA - Wife justified refusing sex: CS reason"
label variable mv634a   "NA - Wife refuses to have sex, husband has right to: get angry"
label variable mv634b   "NA - Wife refuses to have sex, husband has right to: refuse financial support"
label variable mv634c   "NA - Wife refuses to have sex, husband has right to: use force for sex"
label variable mv634d   "NA - Wife refuses to have sex, husband has right to: have sex with another women"
label variable mv714    "Currently working"
label variable mv714a   "Have a job, but currently absent"
label variable mv716    "Occupation"
label variable mv717    "Occupation (grouped)"
label variable mv719    "NA - Works for family, others, self"
label variable mv721    "NA - Works at home or away"
label variable mv731    "Worked in last 12 months"
label variable mv732    "Employment all year/seasonal"
label variable mv739    "NA - Person who usually decides how to spend respondent's earnings"
label variable mv740    "NA - Type of land where respondent works"
label variable mv741    "Type of earnings from respondent's work"
label variable mv743a   "NA - Person who should have greater say: respondent's health care"
label variable mv743b   "NA - Person who should have greater say: large household purchases"
label variable mv743c   "NA - Person who should have greater say: daily household purchases"
label variable mv743d   "NA - Person who should have greater say: visits to family or relatives"
label variable mv743e   "NA - Person who should have greater say: food to be cooked each day"
label variable mv743f   "NA - Person who should have greater say: deciding what to do with money wife ear"
label variable mv743g   "NA - Person who should have greater say: deciding how many children to have"
label variable mv744a   "Beating justified: wife goes out without telling husband"
label variable mv744b   "Beating justified: wife neglects the children"
label variable mv744c   "NA - Beating justified: wife argues with husband"
label variable mv744d   "Beating justified: wife refuses to have sex with husband"
label variable mv744e   "NA - Beating justified: wife burns food"
label variable mv745a   "NA - Owns a house alone or jointly"
label variable mv745b   "NA - Owns land alone or jointly"
label variable mv747a   "NA - Childbearing is a woman's concern"
label variable mv747b   "NA - Important for mother/child health to get assistance at delivery"
label variable mv750    "Ever heard of a Sexually Transmitted Infection (STI)"
label variable mv751    "Ever heard of AIDS"
label variable mv754bp  "NA - Reduce risk of getting HIV: do not have sex at all"
label variable mv754cp  "Reduce risk of getting HIV: always use condoms during sex"
label variable mv754dp  "Reduce risk of getting HIV: have 1 sex partner only, who has no other partners"
label variable mv754jp  "Can get HIV from mosquito bites"
label variable mv754wp  "Can get HIV by sharing food with person who has AIDS"
label variable mv756    "A healthy looking person can have HIV"
label variable mv761    "Condom used during last sex with most recent partner"
label variable mv761b   "Condom used during last sex with 2nd to most recent partner"
label variable mv761c   "Condom used during last sex with 3rd to most recent partner"
label variable mv762aa  "Source for condoms: government hospital"
label variable mv762ab  "Source for condoms: government health center"
label variable mv762ac  "Source for condoms: government health post"
label variable mv762ad  "NA - Source for condoms: CS public"
label variable mv762ae  "NA - Source for condoms: CS public"
label variable mv762af  "NA - Source for condoms: CS public"
label variable mv762ag  "NA - Source for condoms: CS public"
label variable mv762ah  "NA - Source for condoms: CS public"
label variable mv762ai  "NA - Source for condoms: CS public"
label variable mv762aj  "Source for condoms: private hospital/clinic"
label variable mv762ak  "Source for condoms: pharmacy"
label variable mv762al  "Source for condoms: private doctor"
label variable mv762am  "Source for condoms:  Congolese Association of Family Welfare"
label variable mv762an  "NA - Source for condoms: CS private"
label variable mv762ao  "NA - Source for condoms: CS private"
label variable mv762ap  "NA - Source for condoms: CS private"
label variable mv762aq  "NA - Source for condoms: CS private"
label variable mv762ar  "NA - Source for condoms: CS private"
label variable mv762as  "Source for condoms: street seller / pharmacy on the ground"
label variable mv762at  "Source for condoms: shop/market"
label variable mv762au  "Source for condoms: bar/night club"
label variable mv762av  "Source for condoms: friends/relatives"
label variable mv762aw  "NA - Source for condoms: CS other"
label variable mv762ax  "Source for condoms: other"
label variable mv762az  "Don't know any source for condoms"
label variable mv762ba  "NA - Source for female condoms: government hospital"
label variable mv762bb  "NA - Source for female condoms: CS public"
label variable mv762bc  "NA - Source for female condoms: CS public"
label variable mv762bd  "NA - Source for female condoms: CS public"
label variable mv762be  "NA - Source for female condoms: CS public"
label variable mv762bf  "NA - Source for female condoms: CS public"
label variable mv762bg  "NA - Source for female condoms: CS public"
label variable mv762bh  "NA - Source for female condoms: CS public"
label variable mv762bi  "NA - Source for female condoms: CS public"
label variable mv762bj  "NA - Source for female condoms: private hospital/clinic"
label variable mv762bk  "NA - Source for female condoms: pharmacy"
label variable mv762bl  "NA - Source for female condoms: private doctor"
label variable mv762bm  "NA - Source for female condoms: CS private"
label variable mv762bn  "NA - Source for female condoms: CS private"
label variable mv762bo  "NA - Source for female condoms: CS private"
label variable mv762bp  "NA - Source for female condoms: CS private"
label variable mv762bq  "NA - Source for female condoms: CS private"
label variable mv762br  "NA - Source for female condoms: CS private"
label variable mv762bs  "NA - Source for female condoms: CS other"
label variable mv762bt  "NA - Source for female condoms: CS other"
label variable mv762bu  "NA - Source for female condoms: CS other"
label variable mv762bv  "NA - Source for female condoms: CS other"
label variable mv762bw  "NA - Source for female condoms: CS other"
label variable mv762bx  "NA - Source for female condoms: other"
label variable mv762bz  "NA - Don't know any source for female condoms"
label variable mv763a   "Had any STI in last 12 months"
label variable mv763b   "Had genital sore/ulcer in last 12 months"
label variable mv763c   "Had genital discharge in last 12 months"
label variable mv763d   "NA - Had CS STI in last 12 months"
label variable mv763e   "NA - Had CS STI in last 12 months"
label variable mv763f   "NA - Had CS STI in last 12 months"
label variable mv763g   "NA - Had CS STI in last 12 months"
label variable mv766a   "Number of sex partners, excluding spouse, in last 12 months"
label variable mv766b   "Number of sex partners, including spouse, in last 12 months"
label variable mv767a   "Relationship with most recent sex partner"
label variable mv767b   "Relationship with 2nd to most recent sex partner"
label variable mv767c   "Relationship with 3rd to most recent sex partner"
label variable mv768a   "NA - Length of time had sex relations with most recent partner"
label variable mv768b   "NA - Length of time had sex relations with 2nd to most recent partner"
label variable mv768c   "NA - Length of time had sex relations with 3rd to most recent partner"
label variable mv769    "Can get a condom"
label variable mv769a   "NA - Can get a female condom"
label variable mv770    "Sought advice/treatment for last STI infection"
label variable mv770a   "Sought STI advice/treatment from: government hospital"
label variable mv770b   "Sought STI advice/treatment from: government health center"
label variable mv770c   "Sought STI advice/treatment from: government health post"
label variable mv770d   "NA - Sought STI advice/treatment from: CS public"
label variable mv770e   "NA - Sought STI advice/treatment from: CS public"
label variable mv770f   "NA - Sought STI advice/treatment from: CS public"
label variable mv770g   "NA - Sought STI advice/treatment from: CS public"
label variable mv770h   "NA - Sought STI advice/treatment from: CS public"
label variable mv770i   "NA - Sought STI advice/treatment from: CS public"
label variable mv770j   "NA - Sought STI advice/treatment from: CS public"
label variable mv770k   "Sought STI advice/treatment from: private hospital/clinic/doctor"
label variable mv770l   "Sought STI advice/treatment from: private doctor"
label variable mv770m   "Sought STI advice/treatment from: private pharmacy"
label variable mv770n   "NA - Sought STI advice/treatment from: CS private"
label variable mv770o   "NA - Sought STI advice/treatment from: CS private"
label variable mv770p   "NA - Sought STI advice/treatment from: CS private"
label variable mv770q   "NA - Sought STI advice/treatment from: CS private"
label variable mv770r   "NA - Sought STI advice/treatment from: CS private"
label variable mv770s   "NA - Sought STI advice/treatment from: CS private"
label variable mv770t   "Sought STI advice/treatment from: traditional healer"
label variable mv770u   "Sought STI advice/treatment from: street seller / pharmacy on the ground"
label variable mv770v   "Sought STI advice/treatment from: shop/market"
label variable mv770w   "NA - Sought STI advice/treatment from: CS other"
label variable mv770x   "Sought STI advice/treatment from: other"
label variable mv774a   "HIV transmitted during pregnancy"
label variable mv774b   "HIV transmitted during delivery"
label variable mv774c   "HIV transmitted by breastfeeding"
label variable mv775    "NA - Knows someone who has, or is suspected of having, HIV"
label variable mv777    "Would want HIV infection in family to remain secret"
label variable mv778    "Willing to care for relative with AIDS"
label variable mv779    "A female teacher infected with HIV, but is not sick, should be allowed to contin"
label variable mv780    "Children should be taught about condoms to avoid AIDS"
label variable mv781    "Ever been tested for HIV"
label variable mv783    "Know a place to get HIV test"
label variable mv784a   "Place for HIV test: government hospital"
label variable mv784b   "Place for HIV test: government health center"
label variable mv784c   "Place for HIV test: national laboratory"
label variable mv784d   "Place for HIV test: public stand-alone VCT center"
label variable mv784e   "NA - Place for HIV test: CS public"
label variable mv784f   "NA - Place for HIV test: CS public"
label variable mv784g   "NA - Place for HIV test: CS public"
label variable mv784h   "NA - Place for HIV test: CS public"
label variable mv784i   "NA - Place for HIV test: CS public"
label variable mv784j   "NA - Place for HIV test: CS public"
label variable mv784k   "Place for HIV test: private hospital/clinic/doctor"
label variable mv784l   "Place for HIV test: private doctor"
label variable mv784m   "Place for HIV test: private laboratory"
label variable mv784n   "NA - Place for HIV test: CS private"
label variable mv784o   "NA - Place for HIV test: CS private"
label variable mv784p   "NA - Place for HIV test: CS private"
label variable mv784q   "NA - Place for HIV test: CS private"
label variable mv784r   "NA - Place for HIV test: CS private"
label variable mv784s   "NA - Place for HIV test: CS other"
label variable mv784t   "NA - Place for HIV test: CS other"
label variable mv784u   "NA - Place for HIV test: CS other"
label variable mv784v   "NA - Place for HIV test: CS other"
label variable mv784x   "Place for HIV test: other"
label variable mv785    "Heard about other STIs"
label variable mv791    "Have ever paid anyone in exchange for sex"
label variable mv793    "Paid for sex in last 12 months"
label variable mv793a   "Condom used last time paid for sex in last 12 months"
label variable mv793b   "Condom used every time paid for sex in last 12 months"
label variable mv820    "NA - Condom used at first sex"
label variable mv822    "Wife justified asking husband to use condom if he has STI"
label variable mv823    "Can get HIV by witchcraft or supernatural means"
label variable mv824    "Drugs to avoid HIV transmission to baby during pregnancy"
label variable mv825    "Would buy vegetables from vendor with HIV"
label variable mv826    "NA - Last time tested for HIV"
label variable mv826a   "Months ago most recent HIV test"
label variable mv827    "NA - Last HIV test: on your own, offered or required"
label variable mv828    "Received result from last HIV test"
label variable mv829    "Place where last HIV test was taken"
label variable mv832b   "Time since last sex with 2nd to most recent partner"
label variable mv832c   "Time since last sex with 3rd to most recent partner"
label variable mv833a   "Used condom every time had sex with most recent partner in last 12 months"
label variable mv833b   "Used condom every time had sex with 2nd to most recent partner in last 12 months"
label variable mv833c   "Used condom every time had sex with 3rd to most recent partner in last 12 months"
label variable mv834a   "Age of most recent partner"
label variable mv834b   "Age of 2nd to most recent partner"
label variable mv834c   "Age of 3rd to most recent partner"
label variable mv835a   "NA - Alcohol consumption at last sex with most recent partner"
label variable mv835b   "NA - Alcohol consumption at last sex with 2nd to most recent partner"
label variable mv835c   "NA - Alcohol consumption at last sex with 3rd to most recent partner"
label variable mv836    "Total lifetime number of sex partners"
label variable mv837    "NA - Heard of drugs to help HIV infected people live longer"
label variable mv844    "NA - Knows someone denied health services for having, or suspected of having, HI"
label variable mv845    "NA - Knows someone denied social event for having, or suspected of having, HIV; "
label variable mv846    "NA - Knows someone verbally abused for having, or suspected of having, HIV; in l"
label variable mv847    "NA - People with HIV should be ashamed of themselves"
label variable mv848    "NA - People with HIV should be blamed for bringing disease to community"
label variable mv849    "NA - Children 12-14 should be taught to wait for sex until marriage"
label variable mv851a   "NA - Young men should wait for sex until marriage"
label variable mv851b   "NA - Most young men wait for sex until marriage"
label variable mv851c   "NA - Unmarried sexually active men should have only one partner"
label variable mv851d   "NA - Most unmarried sexually active men have only one partner"
label variable mv851e   "NA - Married men should only have sex with their wives"
label variable mv851f   "NA - Most married men only have sex with their wives"
label variable mv851g   "NA - Young women should wait for sex until marriage"
label variable mv851h   "NA - Most young women wait for sex until marriage"
label variable mv851i   "NA - Unmarried sexually active women should have only one partner"
label variable mv851j   "NA - Most unmarried sexually active women have only one partner"
label variable mv851k   "NA - Married women should only have sex with their husbands"
label variable mv851l   "NA - Most married women only have sex with their husbands"
label variable mv852a   "How long ago first had sex with most recent partner"
label variable mv852b   "How long ago first had sex with 2nd most recent partner"
label variable mv852c   "How long ago first had sex with 3rd most recent partner"
label variable mv853a   "Times in last 12 months had sex with most recent partner"
label variable mv853b   "Times in last 12 months had sex with 2nd most recent partner"
label variable mv853c   "Times in last 12 months had sex with 3rd most recent partner"
label variable mv854a   "Concurrent sexual partners"
label variable mv854b   "Cumulative concurrent sexual partners"
label variable smstruct "Structure number"
label variable sm105    "Highest educational level (questionnaire configuration)"
label variable sm607a   "Justifies domestic violence: Wife is unfaithful"
label variable sm607d   "Justifies domestic violence: disrespects her husband"
label variable sm607e   "Justifies domestic violence: Wife disrespects her husband's family"
label variable sm607g   "Justifies domestic violence: Wife neglects housework"
label variable sm607h   "Justifies domestic violence: Wife spends household money without permission"
label variable sm701a   "Place heard of AIDS: radio/TV/newspaper"
label variable sm701b   "Place heard of AIDS: church"
label variable sm701c   "Place heard of AIDS: father"
label variable sm701d   "Place heard of AIDS: mother"
label variable sm701e   "Place heard of AIDS: brother/sister"
label variable sm701f   "Place heard of AIDS: neighbors"
label variable sm701g   "Place heard of AIDS: friends"
label variable sm701h   "Place heard of AIDS: other relatives"
label variable sm701i   "Place heard of AIDS: Yellow line (MTN)"
label variable sm701j   "Place heard of AIDS: school Teacher"
label variable sm701k   "Place heard of AIDS: posters, awareness campaign"
label variable sm701l   "Place heard of AIDS: other"
label variable sm803    "Who performed the circumcision"
label variable sm814    "Ever heard of fistula"
label variable sm815a   "Information on fistula: radio/TV/newspaper"
label variable sm815b   "Information on fistula: health facility/worker"
label variable sm815c   "Information on fistula: campaign worker"
label variable sm815d   "Information on fistula: friends/relatives"
label variable sm815x   "Information on fistula: other"
label variable sm816    "Knows someone who ever had fistula"
label variable sm817    "Can get fistula by witchcraft or supernatural means"
label variable sm818    "Can fistula be cured"
label variable sm819    "Willing to live with a family member suffering from fistula"

#delimit ;
label define MV013   
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
     8 "50-54"
     9 "55-59"
    10 "60-64"
;
label define MV014   
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define MV015   
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define MV023   
     0 "National"
     1 "Country specific"
;
label define MV024   
     1 "Kouilou"
     2 "Niari"
     3 "Lékoumou"
     4 "Bouenza"
     5 "Pool"
     6 "Plateaux"
     7 "Cuvette"
     8 "Cuvette-Ouest"
     9 "Sangha"
    10 "Likouala"
    11 "Brazzaville"
    12 "Pointe-Noire"
;
label define MV025   
     1 "Urban"
     2 "Rural"
;
label define MV026   
     0 "Brazzaville"
     1 "Pointe  Noire"
     2 "Other towns"
     3 "Countryside"
;
label define MV027   
     9 "Missing"
;
label define MV028   
   999 "Missing"
;
label define MV029   
    99 "Missing"
;
label define MV030   
   999 "Missing"
;
label define MV031   
   999 "Missing"
;
label define MV032   
    99 "Missing"
;
label define MV034   
     0 "Wife not in household"
;
label define MV034A  
     1 "Wife"
     2 "Partner"
;
label define MV034B  
    99 "Missing"
;
label define MV035   
     0 "No wives/partners"
;
label define MV801   
  9999 "Missing"
;
label define MV802   
  9999 "Missing"
;
label define MV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define MV101   
     1 "Kouilou"
     2 "Niari"
     3 "Lékoumou"
     4 "Bouenza"
     5 "Pool"
     6 "Plateaux"
     7 "Cuvette"
     8 "Cuvette-Ouest"
     9 "Sangha"
    10 "Likouala"
    11 "Brazzaville"
    12 "Pointe-Noire"
;
label define MV102   
     1 "Urban"
     2 "Rural"
;
label define MV103   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV104   
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV105   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV106   
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define MV107   
     0 "No years completed at level MV106"
;
label define MV130   
     1 "Catholic"
     2 "Protestant"
     3 "Muslim"
     4 "Kibanguist"
     5 "Salvation army"
     6 "Zephirrin/Matsouanist/Ngunza"
     7 "Adventist/Jehova"
     8 "Animist"
     9 "Eglise de réveil"
    11 "No religion"
    96 "Other"
;
label define MV131   
     1 "Kongo"
     2 "Punu"
     3 "Duma"
     4 "Mbéré/Mbéti/Kélé"
     5 "Téké"
     6 "Mbochi"
     7 "Sangha"
     8 "Kota"
     9 "Makaa"
    10 "Oubanguiens"
    11 "Pygmée"
    12 "Etranger"
   996 "Other"
;
label define MV133   
    97 "Inconsistent"
;
label define MV134   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV135   
     1 "Usual resident"
     2 "Visitor"
;
label define MV149   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define MV150   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    98 "Don't know"
;
label define MV151   
     1 "Male"
     2 "Female"
;
label define MV152   
    97 "97+"
    98 "Don't know"
;
label define MV155   
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define MV156   
     0 "No"
     1 "Yes"
;
label define MV157   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV158   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV159   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV167   
     0 "None"
    90 "90+"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV168   
     0 "No"
     1 "Yes"
;
label define MV190   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define MV212   
    97 "Inconsistent"
;
label define MV213   
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV217   
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define MV225   
     1 "Then"
     2 "Later"
     3 "Not at all"
;
label define MV245   
    99 "Missing"
;
label define MV246   
     0 "No"
     1 "Yes"
;
label define MV247   
    99 "Missing"
;
label define MV248   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV249   
     0 "Not present"
     1 "Present"
;
label define MV250   
     1 "Hospital, health facility"
     2 "Other"
;
label define MV251   
     1 "Cost too much"
     2 "Facility closed"
     3 "Too far/no transportation"
     4 "Don't trust facility/poor quality service"
     5 "No female provider"
     6 "Not the first child"
     7 "Mother did not think it necessary"
     8 "Respondent did not think it necessary"
     9 "Family did not think it necessary"
    96 "Other"
    98 "Don't know"
;
label define MV252   
     0 "Nothing to drink"
     2 "Less than usual/much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define MV301   
     0 "Knows no method"
     1 "Knows only folkloric method"
     2 "Knows only traditional method"
     3 "Knows modern method"
;
label define MV302   
     0 "Never used"
     1 "Used only folkloric method"
     2 "Used only traditional method"
     3 "Used modern method"
;
label define M304A   
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define MV304   
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV305   
     0 "No"
     1 "Yes"
;
label define MV307   
     0 "No"
     1 "Yes"
;
label define MV312   
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Implants/Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea (LAM)"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Other modern method"
    18 "Survey Specific method 2"
    19 "Survey Specific method 3"
    20 "Survey Specific method 4"
    98 "Don't know"
;
label define MV313   
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     8 "Don't know"
;
label define MV323A  
    96 "Other"
    98 "Don't know"
;
label define MV325B  
9999995 "Free"
9999998 "Don't know"
;
label define MV372A  
     0 "Package not seen"
     1 "Package seen"
;
label define MV384A  
     0 "No"
     1 "Yes"
;
label define MV384B  
     0 "No"
     1 "Yes"
;
label define MV384C  
     0 "No"
     1 "Yes"
;
label define MV395   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "Don't know"
;
label define MV396   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "Don't know"
;
label define MV3A09B 
   998 "Don't know"
;
label define MV3B17  
    10 "PUBLIC SECTOR"
    11 "Hospital"
    12 "Health center"
    13 "Health post"
    20 "PRIVATE SECTOR"
    21 "Clinic"
    22 "Medical consulting room"
    23 "Congolese Association of Family Welfare"
    24 "Pharmacy"
    30 "OTHER SOURCE"
    31 "Street seller / pharmacy on the ground"
    32 "Shop/market"
    33 "Bar/night club/hotel"
    34 "Friend/relative"
    96 "Other"
;
label define MV3B25A 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV3B25B 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV463A  
     0 "No"
     1 "Yes"
;
label define MV463B  
     0 "No"
     1 "Yes"
;
label define MV463C  
     0 "No"
     1 "Yes"
;
label define MV463D  
     0 "No"
     1 "Yes"
;
label define MV463E  
     0 "No"
     1 "Yes"
;
label define MV463F  
     0 "No"
     1 "Yes"
;
label define MV463G  
     0 "No"
     1 "Yes"
;
label define MV463X  
     0 "No"
     1 "Yes"
;
label define MV463Z  
     0 "No"
     1 "Yes, smokes nothing"
;
label define MV464   
    98 "DK"
;
label define MV474   
     0 "No"
     1 "Yes"
;
label define MV474A  
     0 "No"
     1 "Yes"
;
label define MV474B  
     0 "No"
     1 "Yes"
;
label define MV474C  
     0 "No"
     1 "Yes"
;
label define MV474D  
     0 "No"
     1 "Yes"
;
label define MV474E  
     0 "No"
     1 "Yes"
;
label define MV474F  
     0 "No"
     1 "Yes"
;
label define MV474G  
     0 "No"
     1 "Yes"
;
label define MV474H  
     0 "No"
     1 "Yes"
;
label define MV474I  
     0 "No"
     1 "Yes"
;
label define MV474J  
     0 "No"
     1 "Yes"
;
label define MV474X  
     0 "No"
     1 "Yes"
;
label define MV474Z  
     0 "No"
     1 "Yes"
;
label define MV475   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV476   
     0 "No"
     1 "Yes, remain a secret"
     8 "Don't know/not sure/depends"
;
label define MV477   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV478   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV479   
    10 "PUBLIC SECTOR"
    20 "PRIVATE SECTOR"
    30 "OTHER"
    96 "Other"
;
label define MV480   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV481   
     0 "No"
     1 "Yes"
;
label define MV481A  
     0 "No"
     1 "Yes"
;
label define MV481B  
     0 "No"
     1 "Yes"
;
label define MV481C  
     0 "No"
     1 "Yes"
;
label define MV481D  
     0 "No"
     1 "Yes"
;
label define MV481E  
     0 "No"
     1 "Yes"
;
label define MV481F  
     0 "No"
     1 "Yes"
;
label define MV481G  
     0 "No"
     1 "Yes"
;
label define MV481H  
     0 "No"
     1 "Yes"
;
label define MV481X  
     0 "No"
     1 "Yes"
;
label define MV482A  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV482B  
     0 "No"
     1 "Yes"
;
label define MV482C  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV483   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV483A  
    95 "During childhood <5 years"
    98 "Don't know"
;
label define MV483B  
     1 "Traditional practitioner / family friend"
     2 "Health worker / professional"
    96 "Other"
    98 "Don't know"
;
label define MV483C  
     1 "Health facility"
     2 "Home of a health worker / professional"
     3 "Circumcision done at home"
     4 "Ritual site"
    96 "Other home / place"
    98 "Don't know"
;
label define MV501   
     0 "Never in union"
     1 "Married"
     2 "Living with partner"
     3 "Widowed"
     4 "Divorced"
     5 "No longer living together/separated"
;
label define MV502   
     0 "Never in union"
     1 "Currently in union/living with a woman"
     2 "Formerly in union/living with a woman"
;
label define MV503   
     1 "Once"
     2 "More than once"
;
label define MV504   
     1 "Living with him"
     2 "Staying elsewhere"
;
label define MV505   
    99 "Missing"
;
label define MV510   
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define MV513   
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define MV525   
     0 "Not had sex"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV527   
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV528   
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV529   
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV531   
     0 "Not had sex"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV532   
     0 "No flag"
     1 "After interview"
     2 "After conception >= 1 year"
     3 "After conception < 1 year"
     4 "At marriage, but never married"
     5 "At marriage, but after conception"
     6 "After marriage"
;
label define MV535   
     0 "No"
     1 "Formerly married"
     2 "Formerly lived with a woman"
     3 "Both, formerly married and lived with a woman"
;
label define MV536   
     0 "Never had sex"
     1 "Active in last 4 weeks"
     3 "Not active in last 4 weeks"
;
label define MV541   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV602   
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized (respondent or partner(s))"
     5 "Declared infecund (respondent or partner(s))"
     6 "Never had sex"
     7 "Man declared infecund"
     8 "Man has no partner"
;
label define MV603   
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon, now"
   996 "Other, non-numeric"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV604   
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
;
label define MV605   
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized (respondent or partner(s))"
     7 "Declared infecund (respondent or partner(s))"
     8 "Never had sex"
;
label define MV613   
    96 "Non-numeric response"
    98 "Don't know"
;
label define MV614   
     6 "6+"
     7 "Non-numeric response"
;
label define MV616   
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "Don't know"
;
label define MV621   
     1 "Both want same"
     2 "Wife wants more"
     3 "Wife wants fewer"
     8 "Don't know"
;
label define MV627   
    96 "Other"
    98 "Don't know"
;
label define MV628   
    96 "Other"
    98 "Don't know"
;
label define MV629   
    96 "Other"
    98 "Don't know"
;
label define MV631   
     1 "Big problem"
     2 "Small problem"
     3 "No problem"
     4 "Says she can't get pregnant/not having sex"
;
label define MV633A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV634A  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634B  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634C  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634D  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV714   
     0 "No"
     1 "Yes"
;
label define MV714A  
     0 "No"
     1 "Yes"
;
label define MV716   
     0 "Not working"
     1 "Président de la république"
     2 "Chef du gouvernement"
     3 "Ministre, Secrétaire d'Etat et assimilés"
     4 "Préfet, Haut commissaire"
     5 "Député, Sénateur"
     6 "Maire, Sous-Prefet"
     7 "Conseiller des collectivités locales"
     8 "Membre de l'exécutif et du corps législatif non classé ailleurs"
     9 "Secrétaire général (ministère)"
    10 "Directeur de cabinet (ministre)"
    11 "Administrateur"
    12 "Inspecteur d'Etat"
    13 "Directeur général"
    14 "Directeur (chef de division)"
    15 "Ambassadeur"
    16 "Chargé d'affaires"
    17 "Consul général"
    18 "Secrétaire d'ambassade"
    19 "Directeur Départemental"
    20 "Préfet de police"
    21 "Trésorier payeur (général, départemental)"
    22 "Cadres supérieurs de l'administration publique non classés ailleurs"
    23 "Chef coutumier"
    24 "Chef de village"
    25 "Chef de quartier"
    26 "Dirigeant de parti politique"
    27 "Cadre supérieur de partie politique"
    28 "Dirigeant syndical"
    29 "Cadre supérieur de syndicat"
    30 "Dirigeant d'organisation d'employeurs"
    31 "Cadre supérieur d'organisation d'employeurs"
    32 "Dirigeant d'organisation humanitaire, d'ONGs et d'associations"
    33 "Cadre supérieur d'organisation humanitaire, ONG, associations"
    34 "Dirigeants et cadres supérieurs d'organismes spécialisés non classés ailleurs"
    35 "Chef d'entreprise"
    36 "Administrateur, gérant d'entreprise"
    37 "Directeur d'entreprise"
    38 "Directeur général d'entreprise"
    39 "Président directeur général"
    40 "Industriel"
    41 "Directeur (lycée, collège et primaire)"
    42 "Recteur, université"
    43 "Cadre de direction"
    44 "Directeurs cadre de société non classés ailleurs"
    45 "Physicien"
    46 "Climatologiste, climatologue"
    47 "Ingénieurs météorologiste"
    48 "Métorologue"
    49 "Chimiste"
    50 "Géologue"
    51 "Ingénieur géologue"
    52 "Hydrologiste"
    53 "Physiciens, chimistes et assimilés non classés ailleurs"
    54 "Mathématicien"
    55 "Actuaire"
    56 "Statisticien"
    57 "Démographe"
    58 "Mathématiciens, statisticiens et assimilés non classés ailleurs"
    59 "Informaticien"
    60 "Programmeur"
    61 "Spécialistes de l'informatique non classés ailleurs"
    62 "Architecte"
    63 "Urbaniste"
    64 "Ingénieur, génie civil"
    65 "Ingénieur, génie rural"
    66 "Ingénieurs, ponts et chaussées"
    67 "Technicien supérieur, génie civil"
    68 "Technicien supérieur, génie rural"
    69 "Ingénieur électricien"
    70 "Ingénieur électronicien"
    71 "Ingénieur des télécommunications"
    72 "Technicien supérieur / électricien"
    73 "Technicien supérieur / télécommunication"
    74 "Ingénieur frigoriste"
    75 "Ingénieur mécanicien"
    76 "Ingénieur naval"
    77 "Ingénieur chimiste"
    78 "Technicien supérieur, chimie"
    79 "Ingénieur des mines"
    80 "Ingénieur métallurgiste"
    81 "Ingénieur sidérrurgiste"
    82 "Technicien supérieur, métallurgiste"
    83 "Cartographe"
    84 "Géomètre"
    85 "Architectes, ingénieurs et assimilés non classés ailleurs"
    86 "Bactériologiste"
    87 "Biologiste"
    88 "Botaniste"
    89 "Biochimiste"
    90 "Ecologiste"
    91 "Zoologiste"
    92 "Anatomiste"
    93 "Biophysicien"
    94 "Pathologiste"
    95 "Pharmacologue"
    96 "Physiologiste"
    97 "Toxicologue"
    98 "Agronome"
    99 "Ingénieur agronome, agricole"
   100 "Ingénieur forestier"
   101 "Pédologue"
   102 "Spécialistes des sciences de la vie non classés ailleurs"
   103 "Médecin généraliste"
   104 "Médecin spécialiste (chirurgie, gynécologie, pédiatre, ophtalmologue, orthopédiste, etc.)"
   105 "Dentiste"
   106 "Vétérinaire"
   107 "Pharmacien"
   108 "Medécins et assimilés non classés ailleurs"
   109 "Infirmier diplômé"
   110 "Sage-femme diplômé"
   111 "Cadres infirmiers non classés ailleurs"
   112 "Chargé de cours, université"
   113 "Professeur d'université (assistant, maître assistant, maître de conférence)"
   114 "Chercheur (attaché de recherches, chargé de recherches,"
   115 "Directeur de recherches, maître de recherches"
   116 "Professeur d'enseignement secondaire"
   117 "Enseignant, éducation spéciale (sourds, aveugle, handicapé, etc.)"
   118 "Inspecteur d'enseignement (primaire ou secondaire)"
   119 "Conseiller pédagogique"
   120 "Autre spécialiste de l'enseignement NCA"
   121 "Cadre comptable"
   122 "Chef comptable"
   123 "Expert-comptable"
   124 "Vérificateur de compte"
   125 "Cadres comptables non classés ailleurs"
   126 "Spécialistes, gestion des ressources humaines"
   127 "Spécialistes des fonctions administratives et commerciales des entreprises non classés ailleurs"
   128 "Avocat"
   129 "Juge"
   130 "Magistrat"
   131 "Greffier"
   132 "Huissier"
   133 "Notaire"
   134 "Juriste non classé ailleurs"
   135 "Archivistes"
   136 "Conservateur"
   137 "Bibliothécaire"
   138 "Documentaliste"
   139 "Archivistes, bibliothécaires, documentalistes et assimilés non classés ailleurs"
   140 "Economiste"
   141 "Anthropologue"
   142 "Archéologue"
   143 "Ethnologue"
   144 "Criminologue"
   145 "Géographe"
   146 "Sociologue"
   147 "Historien"
   148 "Philosophe"
   149 "Politologue, spécialiste des sciences politiques"
   150 "Interprète"
   151 "Linguiste"
   152 "Traducteur"
   153 "Psychologue"
   154 "Animateur, centre communautaire"
   155 "Assistant médico-social"
   156 "Assistant social"
   157 "Spécialistes du travail social non classés ailleurs"
   158 "Spécialistes des sciences sociales et humaines Non classés ailleurs"
   159 "Auteurs"
   160 "Biographe"
   161 "Chroniqueur"
   162 "Commentateur (radio, télé, sport, etc.)"
   163 "Correspondant (presse, journaux, etc.)"
   164 "Critique"
   165 "Journaliste"
   166 "Poète"
   167 "Romancier"
   168 "scénariste"
   169 "Auteurs, journalistes et autres écrivains non classés ailleurs"
   170 "Artiste peintre"
   171 "Déssinateur (publicité, bandes déssinées, etc.)"
   172 "Sculpteur"
   173 "Musicien (guitariste, pianiste, saxophoniste)"
   174 "Chanteur, cantatrice"
   175 "Compositeur"
   176 "Chorégraphe"
   177 "Danseur"
   178 "Acteur, comédien"
   179 "Metteur en scène (théatre, cinéma, télévision)"
   180 "Réalisateur (cinéma, télévision, radio)"
   181 "Acteurs et metteurs en scènes de cinéma, de théatres et d'autres spectacles non classés ailleurs"
   182 "Personnel du culte chrétien"
   183 "Personnel du culte musulman (marabout, imam, maître coranique)"
   184 "Administrateur civil"
   185 "Attaché administratif"
   186 "Cadre supérieur de police (Commissaire, inspecteur de police)"
   187 "Inspecteur des affaires administratives"
   188 "Inspecteur du travail et des lois sociales"
   189 "Cadre supérieur de la sécurité sociale"
   190 "Attaché d'intendance universitaire"
   191 "proviseur"
   192 "censeur"
   193 "Administrateur et attachés des hôpitaux"
   194 "ingénieur sanitaire"
   195 "Autre cadres supérieurs des affaires sociales"
   196 "nutritionniste"
   197 "Diététicien"
   198 "Assistant de santé, attaché de santé"
   199 "Assistant médical"
   200 "Assitant dentiste"
   201 "Assistant pharmacien"
   202 "Préparateur en pharmaçie"
   203 "Kinésithérapeute"
   204 "Masseur"
   205 "Opticien"
   206 "Technicien de radiologie médicale"
   207 "Praticien de médecine traditionnelle et guérisseurs"
   208 "inspecteur des T.P."
   209 "Ingénieur de l'équipement rural et de l'hydraulique"
   210 "cadre sup. des P et T (Ingénieur des P et T, Administrateur des P et T)"
   211 "cadre sup. et technicien de l'équipement rural"
   212 "Inspecteur mécanicien, marine marchande"
   213 "Officier mécanicien, navire"
   214 "Officier de navigation"
   215 "Pilote de navire"
   216 "Mécanicien navigant, avion"
   217 "Pilote d'avion"
   218 "Contrôleur de la circulation aérienne"
   219 "Technicien, sécurité aérienne"
   220 "Instructeur, navigation"
   221 "Moniteur, auto-école"
   222 "Courtier maritime"
   223 "Agent maritime"
   224 "Agent, dédouanement"
   225 "Déclarant en douane"
   226 "Transitaire"
   227 "Cadre supérieur des affaires économiques"
   228 "Cadre supérieur de banque"
   229 "Cadre supérieur des assurances"
   230 "Inspecteur des douanes"
   231 "Inspecteurs des impôts"
   232 "Inspecteurs du trésor"
   233 "Autres cadre sup. des ressources financières (trésor, impôts, douanes, domaine, enregistrement)"
   234 "Administrateur des services fiscaux et des services financiers"
   235 "Planificateur"
   236 "Autres cadres supérieurs statisticiens et démographes"
   237 "Contrôleur des prix"
   238 "Contrôleur de qualité"
   239 "Conseiller agricole"
   240 "Conseiller forestier"
   241 "Vulgarisateur agricole"
   242 "Ingénieur et conseiller FJA (Formateur de Jeunes Agriculteurs)"
   243 "Autres cadres sup. de l'agriculture"
   244 "Autres cadres sup. des Eaux et Forêts et de pêche"
   245 "Autres cadres sup. de l'élevage"
   246 "Autres techniciens des sciences biologiques  et agronomiques"
   247 "Autres cadres supérieur de la géologie et des mines non classés ailleurs"
   248 "Président de la cour d'appel"
   249 "Cadre sup. des affaires étrangères"
   250 "Cadre sup. de la presse et de la communication"
   251 "Décorateur, dessinateur de modèle"
   252 "Caméraman (cinéma, télévision)"
   253 "Photographe (commerciel, industriel, presse, publicitaire, etc.)"
   254 "Manageur sportif"
   255 "Professeur d'éducation permanente et physique"
   256 "Inspecteur de la jeunesse et des sports"
   257 "Conseiller de la jeunesse et d'animation"
   258 "Administrateur des affaires culturelles"
   259 "Cadre sup. des services touristiques et hôteliers"
   260 "Technicien chimiste"
   261 "Technicien de laboratoire"
   262 "Technicien géologue"
   263 "Technicien physicien"
   264 "Technicien géométre"
   265 "Technicien météorologiste"
   266 "Technicien de génie civil"
   267 "Technicien géomètre"
   268 "Electrotechnicien"
   269 "Technicien électronicien"
   270 "Technicien des télécommunications"
   271 "Technicien frigoriste"
   272 "Technicien mécanicien"
   273 "Technicien métallurgiste"
   274 "Technicien, mines"
   275 "Déssinateur (industriel, génie civil, etc,)"
   276 "Assistant informatique"
   277 "Technicien, appareil audio-visuel"
   278 "Technicien appareil médical"
   279 "Technicien spécialiste des sciences de la vie (bilogiste, botanique, etc,)"
   280 "Professions intermédiaires - cadres siupérieurs non classés ailleurs"
   281 "Ssecrétaire de direction"
   282 "Secrétaire administratif"
   283 "Contrôleur de travail"
   284 "Assistant administratif"
   285 "Maître, instituteur, enseignement primaire"
   286 "Maître, instituteur, enseignement préprimaire"
   287 "Jardinière d'enfants"
   288 "Moniteur, enseignement préprimaire"
   289 "Educateur spécialisés (aveugle, sourds, etc.)"
   290 "Assistant FJA (Formateur de Jeunes Agriculteurs)"
   291 "Surveillant de lycées et collèges"
   292 "Maître d'éducation physique et sportive - Educateur sportif"
   293 "Cadre moyen de la documentation"
   294 "infirmier d'Etat spécialisé et breveté"
   295 "sage-femme d'Etat ou spécialisée"
   296 "Technicien et assistant d'assainissement"
   297 "Prothésiste dentaire"
   298 "Laborantin"
   299 "Gestionnaire des hôpitaux"
   300 "Aide sociale - éducateur social"
   301 "Puéricultrice"
   302 "Autre cadre moyen de santé et de l'action sociele"
   303 "Chef de chantier"
   304 "Chef mécanicien"
   305 "Adjoint technique des T.P."
   306 "Contrôleur - receveur des P et T"
   307 "Assistant météorologiste et de la navigation aérienne"
   308 "Technicien du génie rural"
   309 "Contremaître"
   310 "Contrôleur des impôts"
   311 "Contrôleurs des douanes"
   312 "Contrôleur du trésor"
   313 "Percepteur"
   314 "Comptable"
   315 "Autres cadres moyens du budget, des ressources financières"
   316 "Assistant des affaires économiques et économe"
   317 "Assistant statisticien (adjoint technique de la statistique)"
   318 "Assistant, actuaire"
   319 "Assistant comptable"
   320 "Technicien agronome"
   321 "Technicien forestier"
   322 "Assistant vétérinaire"
   323 "Conducteur des travaux agricoles"
   324 "agent technique d'agriculture spécialisé"
   325 "Contrôleurs des eaux et forêts"
   326 "Assistant et agent technique d'élevage spécialisé"
   327 "Technicien de la géologie et des mines"
   328 "Mandataire de justice"
   329 "Secrétaire des affaires étrangères"
   330 "Agent de maîtrise de l'information"
   331 "Reporter, speaker, animateur (radio et télévision)"
   332 "Arbitre, sport"
   333 "Entraîneur"
   334 "Moniteur sportif"
   335 "Athlète profesionnel (coureur, footballeur, boxeur, etc,)"
   336 "Luteur professionnel"
   337 "Jockey"
   338 "Moniteur, culture sportive"
   339 "autres professions intermédiaires - cadre moyen NCA"
   340 "Agent de police"
   341 "Animateur rural"
   342 "Encadreur d'agriculture (Organisme de développement rural)"
   343 "Moniteur et formateur de jeunes agriculteurs (FJA)"
   344 "Préposé des eaux et forêt"
   345 "Agent technique d'agriculture et d'élevage"
   346 "Infirmier vétérinaire"
   347 "Employé de service administratif"
   348 "Adjoint administratif"
   349 "Aide- comptable"
   350 "Caissier, Guichetier"
   351 "Cadre subalterne du budget, et des ressources financières"
   352 "Agents administratif"
   353 "Agent de bureau (de recouvrement, des services fiscaux, de constatation d'assiette )"
   354 "Collecteur d'impôt"
   355 "Agent de douane, préposé des douanes"
   356 "Préposé, contrôle économique"
   357 "Cadre subalterne des affaires économiques - préposé des affaires économiques"
   358 "Secrétaire"
   359 "Dactylographe"
   360 "Standardiste - réceptionniste - téléphoniste"
   361 "planton - agent de liaison - commis d'administration"
   362 "relieur -  reprographe"
   363 "agent et assistant technique de la statistique"
   364 "Agent de saisie, opérateur sur machine"
   365 "Agent de change"
   366 "Courtier, bourse"
   367 "Agent d'assurances"
   368 "Assureur"
   369 "Courtier, assurances"
   370 "Agent immobilier"
   371 "Courtier, immobilier"
   372 "Agent de voyages"
   373 "Agent commercial"
   374 "Démarcheur commercial"
   375 "Agent d'approvisionnement"
   376 "Commissaire-priseur"
   377 "Opérateur topographe"
   378 "Cheminot"
   379 "Opérateur du génie rural"
   380 "Agent de maîtrise de la géologie et des mines"
   381 "Cadre subalterne des transmissions météo"
   382 "Aide météo"
   383 "Cadre subalterne des P et T, facteur, opérateur des téléphones et télégraphes"
   384 "Surveillant des télécommunications"
   385 "Garçon ou fille de salle"
   386 "Agent itinérant de santé"
   387 "Distributeur de comprimés"
   388 "Aide infirmier - aide-soignant"
   389 "Accoucheuse auxiliaire - matrone"
   390 "Aide-laborantin"
   391 "Agent d'hygiène ; d'assainissement"
   392 "Autre personnel de santé subalterne"
   393 "Employé de bibliothèque, classeurs archivistes"
   394 "Employé d'approvisionnement"
   395 "Manoeuvre"
   396 "Ouvrier"
   397 "Magasinier"
   398 "Vérificateur"
   399 "Employé de bureau non classé ailleurs"
   400 "autre personnel du type administratif et cadre subalterne de l'administration NCA"
   401 "Hôtesse, steward"
   402 "Chef de train"
   403 "Receveur (de train, du bus, etc.)"
   404 "Guide"
   405 "Boy-cuisinier, Gouvernante"
   406 "Chef de cuisine, cuisinier"
   407 "Pâtissier"
   408 "Boulanger"
   409 "Charcutier"
   410 "Poissonnier"
   411 "Presseur d'huile"
   412 "Barman"
   413 "maître et gérant d'hôtel"
   414 "serveur de restaurant - garçon d'hôtel"
   415 "propriétaires de restaurants"
   416 "servante de bar"
   417 "taxi man - conducteur de bus"
   418 "chauffeur"
   419 "coiffeur - coiffeuse"
   420 "Barbier"
   421 "laveur - nettoyeur"
   422 "Baby-sitter"
   423 "Astrologue, Diseur de bonne aventure"
   424 "Mannequins, modèles"
   425 "Garde de corps"
   426 "Détective, police privée"
   427 "Commis de magasin"
   428 "Pompiste"
   429 "Vendeur, établissement de commerce"
   430 "Commerçant (propriétaire, gérant de commerce de gros et de détail)"
   431 "boutiquier"
   432 "vendeur de tissus et friperie"
   433 "vendeur de fruits"
   434 "vendeur de céréales"
   435 "vendeur de vivres frais (alloco, igname, taro, autres féculents)"
   436 "vendeur de beignets et d'autres aliments préparés (vendeur d'aliments)"
   437 "vendeur de légumes et arachides et tous condiments"
   438 "aide vendeur"
   439 "conseiller commercial"
   440 "libraire"
   441 "boucher"
   442 "meunier"
   443 "Marchand de bois"
   444 "Gargotier/dibitier"
   445 "autres métiers de service et vendeurs NCA"
   446 "Cultivateur"
   447 "maraîcher"
   448 "jardinier"
   449 "exploitant de verger - pépiniériste"
   450 "Exploitant forestier"
   451 "bûcheron"
   452 "éleveur de bétail"
   453 "éleveur de volaille"
   454 "berger - garde-animaux"
   455 "pêcheur"
   456 "marin pêcheur"
   457 "chasseur"
   458 "Apiculteur"
   459 "sériculteur"
   460 "pisciculteur"
   461 "charbonnier"
   462 "ouvrier qualifié de l'agriculture"
   463 "autres métiers de ce groupe non classés ailleurs"
   464 "Mineur"
   465 "Foreur de puits"
   466 "Carrier"
   467 "Tailleur de pierre"
   468 "Marbier"
   469 "Creuseur de puits"
   470 "maçon - tâcheron"
   471 "entrepreneur"
   472 "Ferrailleur"
   473 "Echafaudeur"
   474 "Charpentier"
   475 "Carreleur, poseur revêtement de sol"
   476 "Plafonneur"
   477 "Plâtrier"
   478 "Vitrier"
   479 "Plombier"
   480 "Puisatier"
   481 "Electricien"
   482 "Peintre en bâtiment"
   483 "Peintre, carrosserie"
   484 "Soudeur"
   485 "Chaudronier"
   486 "Ferblantier"
   487 "Tôlier"
   488 "Forgeron"
   489 "Armurier"
   490 "Serrurier"
   491 "Mécanicien, garagiste"
   492 "Mécanicien, réparateur de petit engin"
   493 "Electromécanicien"
   494 "Dépanneur : récepteur radio et télévision"
   495 "Bijoutier, joallier, orfévre"
   496 "Potier"
   497 "Menuisier, Ebéniste, artisan article en bois"
   498 "Vannier / artisan tressage de corbeille"
   499 "Tailleur / brodeur"
   500 "Tisserand"
   501 "Tricoteur"
   502 "Teinturier / artisan du textile"
   503 "Imprimeur"
   504 "Boucher"
   505 "Matelassier"
   506 "Tapissier"
   507 "Taneur"
   508 "Cordonnier"
   509 "Maroquinier"
   510 "Réparateur de chaussures"
   511 "dolotière"
   512 "fileuse de coton"
   513 "réparateur de montre - horloger"
   514 "autres métiers de ce groupe non classé ailleurs"
   515 "Conducteur de machine et installation fixe"
   516 "Conducteur de train, locomotive"
   517 "Coursier (cycliste, motocyclette)"
   518 "Conducteur d'autobus et d'autocar"
   519 "Conductuer de camion (citerne, remorque)"
   520 "Conducteur d'engin agricole et forestier"
   521 "Conducteur d'engins de chantier"
   522 "Batelier"
   523 "Matelot"
   524 "Monteur"
   525 "autres métiers de ce groupe non classé ailleurs"
   526 "Marchand ambulant"
   527 "Colporteur"
   528 "Vendeur de journaux"
   529 "Livreur, distributeur"
   530 "Cireur de chaussure"
   531 "Garçons de courses"
   532 "Laveur ambulant (vitre de voiture)"
   533 "Domestique, bonne, aide ménagère"
   534 "Nettoyeur"
   535 "Plongeur"
   536 "Blanchisseur"
   537 "Concierge"
   538 "Gardien - veilleur de nuit"
   539 "Eboueur"
   540 "Balayeur"
   541 "Ouvrier, manœuvre agricole"
   542 "Manœuvre en bâtiment"
   543 "Charretier"
   544 "Docker"
   545 "autres métiers de ce groupe non classé ailleurs"
   546 "militaire"
   547 "gendarme"
   548 "pompier"
   549 "policier"
   550 "autre personnel de l'armée et de la sécurité"
   996 "autres professions non classées ailleurs"
   998 "sans profession"
;
label define MV717   
     0 "Not working"
     1 "Professional/technical/managerial"
     2 "Clerical"
     3 "Sales"
     4 "Agriculture - self employed"
     5 "Agriculture - employee"
     6 "Household and domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
;
label define MV719   
     1 "For family member"
     2 "For someone else"
     3 "Self-employed"
;
label define MV721   
     1 "At home"
     2 "Away"
;
label define MV731   
     0 "No"
     1 "In the past year"
     2 "Currently working"
;
label define MV732   
     1 "All year"
     2 "Seasonal"
     3 "Occasional"
;
label define MV739   
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
;
label define MV740   
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
;
label define MV741   
     0 "Not paid"
     1 "Cash only"
     2 "Cash and in-kind"
     3 "In-kind only"
;
label define MV743A  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Other"
     8 "Don't know/depends"
;
label define MV743B  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Other"
     8 "Don't know/depends"
;
label define MV743C  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743D  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743E  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743F  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743G  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV744A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV745A  
     0 "Does not own"
     1 "Alone only"
     2 "Jointly only"
     3 "Both alone and jointly"
;
label define MV745B  
     0 "Does not own"
     1 "Alone only"
     2 "Jointly only"
     3 "Both alone and jointly"
;
label define MV747A  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV747B  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV750   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV751   
     0 "No"
     1 "Yes"
;
label define MV754BP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754CP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754DP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754JP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754WP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV756   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV762AA 
     0 "No"
     1 "Yes"
;
label define MV762AB 
     0 "No"
     1 "Yes"
;
label define MV762AC 
     0 "No"
     1 "Yes"
;
label define MV762AD 
     0 "No"
     1 "Yes"
;
label define MV762AE 
     0 "No"
     1 "Yes"
;
label define MV762AF 
     0 "No"
     1 "Yes"
;
label define MV762AG 
     0 "No"
     1 "Yes"
;
label define MV762AH 
     0 "No"
     1 "Yes"
;
label define MV762AI 
     0 "No"
     1 "Yes"
;
label define MV762AJ 
     0 "No"
     1 "Yes"
;
label define MV762AK 
     0 "No"
     1 "Yes"
;
label define MV762AL 
     0 "No"
     1 "Yes"
;
label define MV762AM 
     0 "No"
     1 "Yes"
;
label define MV762AN 
     0 "No"
     1 "Yes"
;
label define MV762AO 
     0 "No"
     1 "Yes"
;
label define MV762AP 
     0 "No"
     1 "Yes"
;
label define MV762AQ 
     0 "No"
     1 "Yes"
;
label define MV762AR 
     0 "No"
     1 "Yes"
;
label define MV762AS 
     0 "No"
     1 "Yes"
;
label define MV762AT 
     0 "No"
     1 "Yes"
;
label define MV762AU 
     0 "No"
     1 "Yes"
;
label define MV762AV 
     0 "No"
     1 "Yes"
;
label define MV762AW 
     0 "No"
     1 "Yes"
;
label define MV762AX 
     0 "No"
     1 "Yes"
;
label define MV762AZ 
     0 "No"
     1 "Yes: don't know"
;
label define MV762BA 
     0 "No"
     1 "Yes"
;
label define MV762BB 
     0 "No"
     1 "Yes"
;
label define MV762BC 
     0 "No"
     1 "Yes"
;
label define MV762BD 
     0 "No"
     1 "Yes"
;
label define MV762BE 
     0 "No"
     1 "Yes"
;
label define MV762BF 
     0 "No"
     1 "Yes"
;
label define MV762BG 
     0 "No"
     1 "Yes"
;
label define MV762BH 
     0 "No"
     1 "Yes"
;
label define MV762BI 
     0 "No"
     1 "Yes"
;
label define MV762BJ 
     0 "No"
     1 "Yes"
;
label define MV762BK 
     0 "No"
     1 "Yes"
;
label define MV762BL 
     0 "No"
     1 "Yes"
;
label define MV762BM 
     0 "No"
     1 "Yes"
;
label define MV762BN 
     0 "No"
     1 "Yes"
;
label define MV762BO 
     0 "No"
     1 "Yes"
;
label define MV762BP 
     0 "No"
     1 "Yes"
;
label define MV762BQ 
     0 "No"
     1 "Yes"
;
label define MV762BR 
     0 "No"
     1 "Yes"
;
label define MV762BS 
     0 "No"
     1 "Yes"
;
label define MV762BT 
     0 "No"
     1 "Yes"
;
label define MV762BU 
     0 "No"
     1 "Yes"
;
label define MV762BV 
     0 "No"
     1 "Yes"
;
label define MV762BW 
     0 "No"
     1 "Yes"
;
label define MV762BX 
     0 "No"
     1 "Yes"
;
label define MV762BZ 
     0 "No"
     1 "Yes: don't know"
;
label define MV763A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV766A  
    98 "Don't know"
;
label define MV766B  
    98 "Don't know"
;
label define MV767A  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767B  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767C  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV768A  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768B  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768C  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV769   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV769A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV770   
     0 "No"
     1 "Yes"
;
label define MV770A  
     0 "No"
     1 "Yes"
;
label define MV770B  
     0 "No"
     1 "Yes"
;
label define MV770C  
     0 "No"
     1 "Yes"
;
label define MV770D  
     0 "No"
     1 "Yes"
;
label define MV770E  
     0 "No"
     1 "Yes"
;
label define MV770F  
     0 "No"
     1 "Yes"
;
label define MV770G  
     0 "No"
     1 "Yes"
;
label define MV770H  
     0 "No"
     1 "Yes"
;
label define MV770I  
     0 "No"
     1 "Yes"
;
label define MV770J  
     0 "No"
     1 "Yes"
;
label define MV770K  
     0 "No"
     1 "Yes"
;
label define MV770L  
     0 "No"
     1 "Yes"
;
label define MV770M  
     0 "No"
     1 "Yes"
;
label define MV770N  
     0 "No"
     1 "Yes"
;
label define MV770O  
     0 "No"
     1 "Yes"
;
label define MV770P  
     0 "No"
     1 "Yes"
;
label define MV770Q  
     0 "No"
     1 "Yes"
;
label define MV770R  
     0 "No"
     1 "Yes"
;
label define MV770S  
     0 "No"
     1 "Yes"
;
label define MV770T  
     0 "No"
     1 "Yes"
;
label define MV770U  
     0 "No"
     1 "Yes"
;
label define MV770V  
     0 "No"
     1 "Yes"
;
label define MV770W  
     0 "No"
     1 "Yes"
;
label define MV770X  
     0 "No"
     1 "Yes"
;
label define MV774A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV774B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV774C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV775   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV777   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV778   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV779   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV780   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV781   
     0 "No"
     1 "Yes"
;
label define MV783   
     0 "No"
     1 "Yes"
;
label define MV784A  
     0 "No"
     1 "Yes"
;
label define MV784B  
     0 "No"
     1 "Yes"
;
label define MV784C  
     0 "No"
     1 "Yes"
;
label define MV784D  
     0 "No"
     1 "Yes"
;
label define MV784E  
     0 "No"
     1 "Yes"
;
label define MV784F  
     0 "No"
     1 "Yes"
;
label define MV784G  
     0 "No"
     1 "Yes"
;
label define MV784H  
     0 "No"
     1 "Yes"
;
label define MV784I  
     0 "No"
     1 "Yes"
;
label define MV784J  
     0 "No"
     1 "Yes"
;
label define MV784K  
     0 "No"
     1 "Yes"
;
label define MV784L  
     0 "No"
     1 "Yes"
;
label define MV784M  
     0 "No"
     1 "Yes"
;
label define MV784N  
     0 "No"
     1 "Yes"
;
label define MV784O  
     0 "No"
     1 "Yes"
;
label define MV784P  
     0 "No"
     1 "Yes"
;
label define MV784Q  
     0 "No"
     1 "Yes"
;
label define MV784R  
     0 "No"
     1 "Yes"
;
label define MV784S  
     0 "No"
     1 "Yes"
;
label define MV784T  
     0 "No"
     1 "Yes"
;
label define MV784U  
     0 "No"
     1 "Yes"
;
label define MV784V  
     0 "No"
     1 "Yes"
;
label define MV784X  
     0 "No"
     1 "Yes"
;
label define MV785   
     0 "No"
     1 "Yes"
;
label define MV791   
     0 "No"
     1 "Yes"
;
label define MV793   
     0 "No"
     1 "Yes"
;
label define MV793A  
     0 "No"
     1 "Yes"
;
label define MV793B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV820   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV822   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV823   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV824   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV825   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV826   
     1 "Less than 12 months"
     2 "12-23 months"
     3 "2 years or more"
;
label define MV826A  
    95 "Two or more years"
    98 "Don't know"
;
label define MV827   
     1 "Asked for the test"
     2 "Offered and accepted"
     3 "Required"
;
label define MV828   
     0 "No"
     1 "Yes"
;
label define MV829   
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "National laboratory"
    14 "Public stand-alone VCT center"
    20 "PRIVATE SECTOR"
    21 "Private hospital or clinic"
    22 "Private doctor"
    23 "Private laboratory"
    96 "Other"
;
label define MV832B  
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV832C  
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV833A  
     0 "No"
     1 "Yes"
;
label define MV833B  
     0 "No"
     1 "Yes"
;
label define MV833C  
     0 "No"
     1 "Yes"
;
label define MV834A  
    95 "95+"
    98 "Don't know"
;
label define MV834B  
    95 "95+"
    98 "Don't know"
;
label define MV834C  
    95 "95+"
    98 "Don't know"
;
label define MV835A  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835B  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835C  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV836   
    95 "95+"
    98 "Don't know"
;
label define MV837   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV844   
     0 "No"
     1 "Yes"
     8 "Don't know anyone with AIDS"
;
label define MV845   
     0 "No"
     1 "Yes"
;
label define MV846   
     0 "No"
     1 "Yes"
;
label define MV847   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/no opinion"
;
label define MV848   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/no opinion"
;
label define MV849   
     0 "No"
     1 "Yes"
     8 "Don't know/depends"
;
label define MV851A  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851B  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851C  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851D  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851E  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851F  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851G  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851H  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851I  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851J  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851K  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851L  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV852A  
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV852B  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV852C  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV853A  
    95 "95+"
    98 "Don't know"
;
label define MV853B  
    95 "95+"
    98 "Don't know"
;
label define MV853C  
    95 "95+"
    98 "Don't know"
;
label define MV854A  
     0 "No"
     1 "Yes"
;
label define MV854B  
     0 "No"
     1 "Yes"
;
label define SM105   
     0 "No education"
     1 "Primary"
     2 "Secondary I"
     3 "Secondary II"
     4 "Higher"
     8 "Don't know"
;
label define SM607A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM607D  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM607E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM607G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM607H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM701A  
     0 "No"
     1 "Yes"
;
label define SM701B  
     0 "No"
     1 "Yes"
;
label define SM701C  
     0 "No"
     1 "Yes"
;
label define SM701D  
     0 "No"
     1 "Yes"
;
label define SM701E  
     0 "No"
     1 "Yes"
;
label define SM701F  
     0 "No"
     1 "Yes"
;
label define SM701G  
     0 "No"
     1 "Yes"
;
label define SM701H  
     0 "No"
     1 "Yes"
;
label define SM701I  
     0 "No"
     1 "Yes"
;
label define SM701J  
     0 "No"
     1 "Yes"
;
label define SM701K  
     0 "No"
     1 "Yes"
;
label define SM701L  
     0 "No"
     1 "Yes"
;
label define SM803   
     1 "Traditional practitioner"
     2 "Family / friend"
     3 "Health worker / professional"
     4 "Other"
     8 "Don't know"
;
label define SM814   
     0 "No"
     1 "Yes"
;
label define SM815A  
     0 "No"
     1 "Yes"
;
label define SM815B  
     0 "No"
     1 "Yes"
;
label define SM815C  
     0 "No"
     1 "Yes"
;
label define SM815D  
     0 "No"
     1 "Yes"
;
label define SM815X  
     0 "No"
     1 "Yes"
;
label define SM816   
     0 "No"
     1 "Yes"
;
label define SM817   
     0 "No"
     1 "Yes"
;
label define SM818   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM819   
     0 "No"
     1 "Yes"
     8 "Don't know"
;

#delimit cr
label values mv013    MV013   
label values mv014    MV014   
label values mv015    MV015   
label values mv023    MV023   
label values mv024    MV024   
label values mv025    MV025   
label values mv026    MV026   
label values mv034_1  MV034   
label values mv034_2  MV034   
label values mv034_3  MV034   
label values mv034_4  MV034   
label values mv034_5  MV034   
label values mv034_6  MV034   
label values mv034_7  MV034   
label values mv034_8  MV034   
label values mv034a_1 MV034A  
label values mv034a_2 MV034A  
label values mv034a_3 MV034A  
label values mv034a_4 MV034A  
label values mv034a_5 MV034A  
label values mv034a_6 MV034A  
label values mv034a_7 MV034A  
label values mv034a_8 MV034A  
label values mv035    MV035   
label values mv803    MV803   
label values mv101    MV101   
label values mv102    MV102   
label values mv103    MV103   
label values mv104    MV104   
label values mv105    MV105   
label values mv106    MV106   
label values mv107    MV107   
label values mv130    MV130   
label values mv131    MV131   
label values mv133    MV133   
label values mv134    MV134   
label values mv135    MV135   
label values mv149    MV149   
label values mv150    MV150   
label values mv151    MV151   
label values mv152    MV152   
label values mv155    MV155   
label values mv156    MV156   
label values mv157    MV157   
label values mv158    MV158   
label values mv159    MV159   
label values mv167    MV167   
label values mv168    MV168   
label values mv190    MV190   
label values mv212    MV212   
label values mv213    MV213   
label values mv217    MV217   
label values mv225    MV225   
label values mv246    MV246   
label values mv248    MV248   
label values mv249    MV249   
label values mv250    MV250   
label values mv251    MV251   
label values mv252    MV252   
label values mv301    MV301   
label values mv302    MV302   
label values m304a_01 M304A   
label values m304a_02 M304A   
label values m304a_03 M304A   
label values m304a_04 M304A   
label values m304a_05 M304A   
label values m304a_06 M304A   
label values m304a_07 M304A   
label values m304a_08 M304A   
label values m304a_09 M304A   
label values m304a_10 M304A   
label values m304a_11 M304A   
label values m304a_12 M304A   
label values m304a_13 M304A   
label values m304a_14 M304A   
label values m304a_15 M304A   
label values m304a_16 M304A   
label values m304a_17 M304A   
label values m304a_18 M304A   
label values m304a_19 M304A   
label values m304a_20 M304A   
label values mv304_01 MV304   
label values mv304_02 MV304   
label values mv304_03 MV304   
label values mv304_04 MV304   
label values mv304_05 MV304   
label values mv304_06 MV304   
label values mv304_07 MV304   
label values mv304_08 MV304   
label values mv304_09 MV304   
label values mv304_10 MV304   
label values mv304_11 MV304   
label values mv304_12 MV304   
label values mv304_13 MV304   
label values mv304_14 MV304   
label values mv304_15 MV304   
label values mv304_16 MV304   
label values mv304_17 MV304   
label values mv304_18 MV304   
label values mv304_19 MV304   
label values mv304_20 MV304   
label values mv305_01 MV305   
label values mv305_02 MV305   
label values mv305_03 MV305   
label values mv305_04 MV305   
label values mv305_05 MV305   
label values mv305_06 MV305   
label values mv305_07 MV305   
label values mv305_08 MV305   
label values mv305_09 MV305   
label values mv305_10 MV305   
label values mv305_11 MV305   
label values mv305_12 MV305   
label values mv305_13 MV305   
label values mv305_14 MV305   
label values mv305_15 MV305   
label values mv305_16 MV305   
label values mv305_17 MV305   
label values mv305_18 MV305   
label values mv305_19 MV305   
label values mv305_20 MV305   
label values mv307_01 MV307   
label values mv307_02 MV307   
label values mv307_03 MV307   
label values mv307_04 MV307   
label values mv307_05 MV307   
label values mv307_06 MV307   
label values mv307_07 MV307   
label values mv307_08 MV307   
label values mv307_09 MV307   
label values mv307_10 MV307   
label values mv307_11 MV307   
label values mv307_12 MV307   
label values mv307_13 MV307   
label values mv307_14 MV307   
label values mv307_15 MV307   
label values mv307_16 MV307   
label values mv307_17 MV307   
label values mv307_18 MV307   
label values mv307_19 MV307   
label values mv307_20 MV307   
label values mv312    MV312   
label values mv313    MV313   
label values mv323a   MV323A  
label values mv325b   MV325B  
label values mv372a   MV372A  
label values mv384a   MV384A  
label values mv384b   MV384B  
label values mv384c   MV384C  
label values mv395    MV395   
label values mv396    MV396   
label values mv3a09b  MV3A09B 
label values mv3b17   MV3B17  
label values mv3b25a  MV3B25A 
label values mv3b25b  MV3B25B 
label values mv463a   MV463A  
label values mv463b   MV463B  
label values mv463c   MV463C  
label values mv463d   MV463D  
label values mv463e   MV463E  
label values mv463f   MV463F  
label values mv463g   MV463G  
label values mv463x   MV463X  
label values mv463z   MV463Z  
label values mv464    MV464   
label values mv474    MV474   
label values mv474a   MV474A  
label values mv474b   MV474B  
label values mv474c   MV474C  
label values mv474d   MV474D  
label values mv474e   MV474E  
label values mv474f   MV474F  
label values mv474g   MV474G  
label values mv474h   MV474H  
label values mv474i   MV474I  
label values mv474j   MV474J  
label values mv474x   MV474X  
label values mv474z   MV474Z  
label values mv475    MV475   
label values mv476    MV476   
label values mv477    MV477   
label values mv478    MV478   
label values mv479    MV479   
label values mv480    MV480   
label values mv481    MV481   
label values mv481a   MV481A  
label values mv481b   MV481B  
label values mv481c   MV481C  
label values mv481d   MV481D  
label values mv481e   MV481E  
label values mv481f   MV481F  
label values mv481g   MV481G  
label values mv481h   MV481H  
label values mv481x   MV481X  
label values mv482a   MV482A  
label values mv482b   MV482B  
label values mv482c   MV482C  
label values mv483    MV483   
label values mv483a   MV483A  
label values mv483b   MV483B  
label values mv483c   MV483C  
label values mv501    MV501   
label values mv502    MV502   
label values mv503    MV503   
label values mv504    MV504   
label values mv510    MV510   
label values mv513    MV513   
label values mv525    MV525   
label values mv527    MV527   
label values mv528    MV528   
label values mv529    MV529   
label values mv531    MV531   
label values mv532    MV532   
label values mv535    MV535   
label values mv536    MV536   
label values mv541    MV541   
label values mv602    MV602   
label values mv603    MV603   
label values mv604    MV604   
label values mv605    MV605   
label values mv613    MV613   
label values mv614    MV614   
label values mv616    MV616   
label values mv621    MV621   
label values mv627    MV627   
label values mv628    MV628   
label values mv629    MV629   
label values mv631    MV631   
label values mv633a   MV633A  
label values mv633b   MV633B  
label values mv633c   MV633C  
label values mv633d   MV633D  
label values mv633e   MV633E  
label values mv633f   MV633F  
label values mv633g   MV633G  
label values mv634a   MV634A  
label values mv634b   MV634B  
label values mv634c   MV634C  
label values mv634d   MV634D  
label values mv714    MV714   
label values mv714a   MV714A  
label values mv716    MV716   
label values mv717    MV717   
label values mv719    MV719   
label values mv721    MV721   
label values mv731    MV731   
label values mv732    MV732   
label values mv739    MV739   
label values mv740    MV740   
label values mv741    MV741   
label values mv743a   MV743A  
label values mv743b   MV743B  
label values mv743c   MV743C  
label values mv743d   MV743D  
label values mv743e   MV743E  
label values mv743f   MV743F  
label values mv743g   MV743G  
label values mv744a   MV744A  
label values mv744b   MV744B  
label values mv744c   MV744C  
label values mv744d   MV744D  
label values mv744e   MV744E  
label values mv745a   MV745A  
label values mv745b   MV745B  
label values mv747a   MV747A  
label values mv747b   MV747B  
label values mv750    MV750   
label values mv751    MV751   
label values mv754bp  MV754BP 
label values mv754cp  MV754CP 
label values mv754dp  MV754DP 
label values mv754jp  MV754JP 
label values mv754wp  MV754WP 
label values mv756    MV756   
label values mv761    MV761   
label values mv761b   MV761B  
label values mv761c   MV761C  
label values mv762aa  MV762AA 
label values mv762ab  MV762AB 
label values mv762ac  MV762AC 
label values mv762ad  MV762AD 
label values mv762ae  MV762AE 
label values mv762af  MV762AF 
label values mv762ag  MV762AG 
label values mv762ah  MV762AH 
label values mv762ai  MV762AI 
label values mv762aj  MV762AJ 
label values mv762ak  MV762AK 
label values mv762al  MV762AL 
label values mv762am  MV762AM 
label values mv762an  MV762AN 
label values mv762ao  MV762AO 
label values mv762ap  MV762AP 
label values mv762aq  MV762AQ 
label values mv762ar  MV762AR 
label values mv762as  MV762AS 
label values mv762at  MV762AT 
label values mv762au  MV762AU 
label values mv762av  MV762AV 
label values mv762aw  MV762AW 
label values mv762ax  MV762AX 
label values mv762az  MV762AZ 
label values mv762ba  MV762BA 
label values mv762bb  MV762BB 
label values mv762bc  MV762BC 
label values mv762bd  MV762BD 
label values mv762be  MV762BE 
label values mv762bf  MV762BF 
label values mv762bg  MV762BG 
label values mv762bh  MV762BH 
label values mv762bi  MV762BI 
label values mv762bj  MV762BJ 
label values mv762bk  MV762BK 
label values mv762bl  MV762BL 
label values mv762bm  MV762BM 
label values mv762bn  MV762BN 
label values mv762bo  MV762BO 
label values mv762bp  MV762BP 
label values mv762bq  MV762BQ 
label values mv762br  MV762BR 
label values mv762bs  MV762BS 
label values mv762bt  MV762BT 
label values mv762bu  MV762BU 
label values mv762bv  MV762BV 
label values mv762bw  MV762BW 
label values mv762bx  MV762BX 
label values mv762bz  MV762BZ 
label values mv763a   MV763A  
label values mv763b   MV763B  
label values mv763c   MV763C  
label values mv763d   MV763D  
label values mv763e   MV763E  
label values mv763f   MV763F  
label values mv763g   MV763G  
label values mv766a   MV766A  
label values mv766b   MV766B  
label values mv767a   MV767A  
label values mv767b   MV767B  
label values mv767c   MV767C  
label values mv768a   MV768A  
label values mv768b   MV768B  
label values mv768c   MV768C  
label values mv769    MV769   
label values mv769a   MV769A  
label values mv770    MV770   
label values mv770a   MV770A  
label values mv770b   MV770B  
label values mv770c   MV770C  
label values mv770d   MV770D  
label values mv770e   MV770E  
label values mv770f   MV770F  
label values mv770g   MV770G  
label values mv770h   MV770H  
label values mv770i   MV770I  
label values mv770j   MV770J  
label values mv770k   MV770K  
label values mv770l   MV770L  
label values mv770m   MV770M  
label values mv770n   MV770N  
label values mv770o   MV770O  
label values mv770p   MV770P  
label values mv770q   MV770Q  
label values mv770r   MV770R  
label values mv770s   MV770S  
label values mv770t   MV770T  
label values mv770u   MV770U  
label values mv770v   MV770V  
label values mv770w   MV770W  
label values mv770x   MV770X  
label values mv774a   MV774A  
label values mv774b   MV774B  
label values mv774c   MV774C  
label values mv775    MV775   
label values mv777    MV777   
label values mv778    MV778   
label values mv779    MV779   
label values mv780    MV780   
label values mv781    MV781   
label values mv783    MV783   
label values mv784a   MV784A  
label values mv784b   MV784B  
label values mv784c   MV784C  
label values mv784d   MV784D  
label values mv784e   MV784E  
label values mv784f   MV784F  
label values mv784g   MV784G  
label values mv784h   MV784H  
label values mv784i   MV784I  
label values mv784j   MV784J  
label values mv784k   MV784K  
label values mv784l   MV784L  
label values mv784m   MV784M  
label values mv784n   MV784N  
label values mv784o   MV784O  
label values mv784p   MV784P  
label values mv784q   MV784Q  
label values mv784r   MV784R  
label values mv784s   MV784S  
label values mv784t   MV784T  
label values mv784u   MV784U  
label values mv784v   MV784V  
label values mv784x   MV784X  
label values mv785    MV785   
label values mv791    MV791   
label values mv793    MV793   
label values mv793a   MV793A  
label values mv793b   MV793B  
label values mv820    MV820   
label values mv822    MV822   
label values mv823    MV823   
label values mv824    MV824   
label values mv825    MV825   
label values mv826    MV826   
label values mv826a   MV826A  
label values mv827    MV827   
label values mv828    MV828   
label values mv829    MV829   
label values mv832b   MV832B  
label values mv832c   MV832C  
label values mv833a   MV833A  
label values mv833b   MV833B  
label values mv833c   MV833C  
label values mv834a   MV834A  
label values mv834b   MV834B  
label values mv834c   MV834C  
label values mv835a   MV835A  
label values mv835b   MV835B  
label values mv835c   MV835C  
label values mv836    MV836   
label values mv837    MV837   
label values mv844    MV844   
label values mv845    MV845   
label values mv846    MV846   
label values mv847    MV847   
label values mv848    MV848   
label values mv849    MV849   
label values mv851a   MV851A  
label values mv851b   MV851B  
label values mv851c   MV851C  
label values mv851d   MV851D  
label values mv851e   MV851E  
label values mv851f   MV851F  
label values mv851g   MV851G  
label values mv851h   MV851H  
label values mv851i   MV851I  
label values mv851j   MV851J  
label values mv851k   MV851K  
label values mv851l   MV851L  
label values mv852a   MV852A  
label values mv852b   MV852B  
label values mv852c   MV852C  
label values mv853a   MV853A  
label values mv853b   MV853B  
label values mv853c   MV853C  
label values mv854a   MV854A  
label values mv854b   MV854B  
label values sm105    SM105   
label values sm607a   SM607A  
label values sm607d   SM607D  
label values sm607e   SM607E  
label values sm607g   SM607G  
label values sm607h   SM607H  
label values sm701a   SM701A  
label values sm701b   SM701B  
label values sm701c   SM701C  
label values sm701d   SM701D  
label values sm701e   SM701E  
label values sm701f   SM701F  
label values sm701g   SM701G  
label values sm701h   SM701H  
label values sm701i   SM701I  
label values sm701j   SM701J  
label values sm701k   SM701K  
label values sm701l   SM701L  
label values sm803    SM803   
label values sm814    SM814   
label values sm815a   SM815A  
label values sm815b   SM815B  
label values sm815c   SM815C  
label values sm815d   SM815D  
label values sm815x   SM815X  
label values sm816    SM816   
label values sm817    SM817   
label values sm818    SM818   
label values sm819    SM819   
