infix using "C:\COUNTRIES\NG81\NGPR81FL.dct"

label variable hhid     "Case Identification"
label variable hvidx    "Line number"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv008a   "Date of interview Century Day Code (CDC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv011    "NA - Number of eligible men in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "Household selected for male interview"
label variable hv028    "Household weight for male subsample (6 decimals)"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv035    "Number of eligible children for height and weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "NA - Total adults measured"
label variable hv042    "Household selected for hemoglobin"
label variable hv045a   "Language of questionnaire"
label variable hv045b   "Language of interview"
label variable hv045c   "Native language of respondent"
label variable hv046    "Translator used"
label variable hv047    "Team number"
label variable hv801    "Time interview started (hhmm - 24 hour clock)"
label variable hv802    "Time interview ended (hhmm - 24 hour clock)"
label variable hv803    "Length of interview in minutes"
label variable hv804    "Number of visits for biomarker"
label variable hv807d   "Day of biomarker visit"
label variable hv807m   "Month of biomarker visit"
label variable hv807y   "Year of biomarker visit"
label variable hv807c   "Date of biomarker (CMC)"
label variable hv807a   "Date of biomarker Century Day Code (CDC)"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv201a   "NA - Water not available for at least a day last two weeks"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv222    "Type of cookstove"
label variable hv223    "Type of cooking fuel"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "Has mosquito bed net for sleeping"
label variable hv228    "Children under 5 slept under mosquito bed net last night"
label variable hv235    "Location of source for water"
label variable hv238    "Number of households sharing toilet"
label variable hv238a   "Location of toilet facility"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "Has watch"
label variable hv243c   "Has animal-drawn cart"
label variable hv243d   "Has boat with a motor"
label variable hv243e   "Has a computer"
label variable hv244    "Owns land usable for agriculture"
label variable hv245    "Hectares of agricultural land (1 decimal)"
label variable hv246    "Owns livestock, herds or farm animals"
label variable hv246a   "Owns cattle"
label variable hv246b   "Owns cows/ bulls"
label variable hv246c   "Owns horses/ donkeys/ mules"
label variable hv246d   "Owns goats"
label variable hv246e   "Owns sheep"
label variable hv246f   "Owns chickens/poultry"
label variable hv246g   "Owns pigs"
label variable hv246h   "Owns camels"
label variable hv246i   "NA - Owns CS"
label variable hv246j   "NA - Owns CS"
label variable hv246k   "NA - Owns CS"
label variable hv247    "Has bank account"
label variable hv270    "Wealth index combined"
label variable hv271    "Wealth index factor score combined (5 decimals)"
label variable hv270a   "Wealth index for urban/rural"
label variable hv271a   "Wealth index factor score for urban/rural (5 decimals)"
label variable hml1     "Number of mosquito bed nets"
label variable hml1a    "Number of mosquito bed nets with specific information"
label variable hml2     "Number of children under mosquito bed net previous night"
label variable shlga    "Local government area"
label variable shtsuperv "Team supervisor number"
label variable shregion "Region"
label variable shbonny  "Bonny State"
label variable sh116g   "Has table"
label variable sh116h   "Has chair"
label variable sh116i   "Has bed"
label variable sh116j   "Has sofa"
label variable sh116k   "Has cupboard"
label variable sh116l   "Has air conditioner"
label variable sh116m   "Has electric iron"
label variable sh116n   "Has generator"
label variable sh116o   "Has fan"
label variable sh117h   "Has canoe"
label variable sh117i   "Has keke napep"
label variable sh119    "Used mobile phone for financial transactions"
label variable hv101    "Relationship to head"
label variable hv102    "Usual resident"
label variable hv103    "Slept last night"
label variable hv104    "Sex of household member"
label variable hv105    "Age of household members"
label variable hv117    "Eligibility for female interview"
label variable hv120    "Children eligibility for height/weight and hemoglobin"
label variable hc0      "Index to Household Schedule"
label variable hc1      "Child's age in months"
label variable hc1a     "Child's age in days"
label variable hc16     "Day of birth"
label variable hc17     "Date measured (day)"
label variable hc18     "Date measured (month)"
label variable hc19     "Date measured (year)"
label variable hc20     "Century Day Code (CDC) of measurement"
label variable hc21     "Fieldworker measurer code"
label variable hc27     "Sex"
label variable hc30     "Month of birth"
label variable hc31     "Year of birth"
label variable hc32     "Date of birth (CMC)"
label variable hc32a    "Century Day Code (CDC) of birth"
label variable hc33     "Completeness of HC32 information"
label variable hc51     "Line number of parent/caretaker"
label variable hc52     "Read consent statement - hemoglobin"
label variable hc53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55     "Result of measurement - hemoglobin"
label variable hc56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57     "Anemia level"
label variable hc58     "NA - Agrees to referral - anemia"
label variable hc60     "Mother's line number (woman's questionnaire)"
label variable hc61     "Mother's highest educational level"
label variable hc62     "Mother's highest year of education"
label variable hc63     "Preceding birth interval (months)"
label variable hc64     "Birth order number"
label variable hc68     "Mother's highest educational level (for preliminary and final report)"
label variable sb110b   "Read consent statement for DBS"
label variable sb110c   "Fieldworker measurer code for DBS"
label variable sb110e   "Read consent statement for additional testing"
label variable sb110f   "Fieldworker measurer code for additional testing"
label variable hmlidx   "Mosquito Bed Net Designation Number"
label variable hml3     "Net observed by interviewer"
label variable hml4     "Months ago net obtained"
label variable hml5     "NA - Net treated with insecticide when bought"
label variable hml6     "NA - Net treatment status"
label variable hml7     "Brand of net"
label variable hml8     "NA - Net treated since received"
label variable hml9     "NA - Time since last re-treatment (months)"
label variable hml10    "Insecticide-Treated Net (ITN)"
label variable hml11    "Number of persons who slept under this net"
label variable hml21    "Someone slept under this net last night"
label variable hmla     "Line number of person who slept in this net"
label variable hmlb     "Line number of person who slept in this net"
label variable hmlc     "Line number of person who slept in this net"
label variable hmld     "Line number of person who slept in this net"
label variable hmle     "NA - Line number of person who slept in this net"
label variable hml22    "Obtained net from campaign, antenatal or immunization visit"
label variable hml23    "Place where net was obtained"
label variable sh130    "Reason net was not used"
label variable hmhidx   "Index to Household Schedule"
label variable hml12    "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml13    "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml14    "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml15    "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml16    "Corrected age from Individual file"
label variable hml16a   "Age in months (for children)"
label variable hml17    "Flag for age from Individual file"
label variable hml18    "Pregnancy status from Individual file"
label variable hml19    "Person slept under an ever-treated net"
label variable hml20    "Person slept under an LLIN net"
label variable hml30    "Line number of parent/caretaker (for malaria testing)"
label variable hml31    "Read consent statement for malaria"
label variable hml32    "Final result of malaria from blood smear test"
label variable hml32a   "Presence of species: falciparum (Pf)"
label variable hml32b   "Presence of species: malariae (Pm)"
label variable hml32c   "Presence of species: ovale (Po)"
label variable hml32d   "Presence of species: vivax (Pv)"
label variable hml32e   "NA - Presence of species: CS"
label variable hml32f   "NA - Presence of species: CS"
label variable hml32g   "NA - Presence of species: CS"
label variable hml33    "Result of malaria measurement"
label variable hml34    "Bar code for blood smear sample"
label variable hml35    "Result of malaria rapid test"
label variable hml36    "Fieldworker measurer code for malaria"
label variable hml37a   "Suffer from illness/symptom: extreme weakness"
label variable hml37b   "Suffer from illness/symptom: heart problems"
label variable hml37c   "Suffer from illness/symptom: loss of consciousness"
label variable hml37d   "Suffer from illness/symptom: rapid or difficult breathing"
label variable hml37e   "Suffer from illness/symptom: seizures"
label variable hml37f   "Suffer from illness/symptom: abnormal bleeding"
label variable hml37g   "Suffer from illness/symptom: jaundice or yellow skin"
label variable hml37h   "Suffer from illness/symptom: dark urine"
label variable hml37i   "Suffer from illness/symptom: vomiting"
label variable hml37j   "Suffer from illness/symptom: pallor"
label variable hml37k   "Suffer from illness/symptom: refusal to eat"
label variable hml37l   "Suffer from illness/symptom: very cold hands and feet"
label variable hml37m   "NA - Suffer from illness/symptom: CS"
label variable hml38    "Child taken or taking first line medicine given by health provider for malaria"
label variable hml39    "Parent accept first line medicine to treat malaria"
label variable hml40    "Fieldworker provided first line medicine for malaria"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV022   
     1 "Abia_Urban"
     2 "Abia_Rural"
     3 "Adamawa_Urban"
     4 "Adamawa_Rural"
     5 "Akwa Ibom_Urban"
     6 "Akwa Ibom_Rural"
     7 "Anambra_Urban"
     8 "Anambra_Rural"
     9 "Bauchi_Urban"
    10 "Bauchi_Rural"
    11 "Bayelsa_Urban"
    12 "Bayelsa_Rural"
    13 "Benue_Urban"
    14 "Benue_Rural"
    15 "Borno_Urban"
    16 "Borno_Rural"
    17 "Cross River_Urban"
    18 "Cross River_Rural"
    19 "Delta_Urban"
    20 "Delta_Rural"
    21 "Ebonyi_Urban"
    22 "Ebonyi_Rural"
    23 "Edo_Urban"
    24 "Edo_Rural"
    25 "Ekiti_Urban"
    26 "Ekiti_Rural"
    27 "Enugu_Urban"
    28 "Enugu_Rural"
    29 "Fct_Urban"
    30 "Fct_Rural"
    31 "Gombe_Urban"
    32 "Gombe_Rural"
    33 "Imo_Urban"
    34 "Imo_Rural"
    35 "Jigawa_Urban"
    36 "Jigawa_Rural"
    37 "Kaduna_Urban"
    38 "Kaduna_Rural"
    39 "Kano_Urban"
    40 "Kano_Rural"
    41 "Katsina_Urban"
    42 "Katsina_Rural"
    43 "Kebbi_Urban"
    44 "Kebbi_Rural"
    45 "Kogi_Urban"
    46 "Kogi_Rural"
    47 "Kwara_Urban"
    48 "Kwara_Rural"
    49 "Lagos_Urban"
    50 "Lagos_Rural"
    51 "Nasarawa_Urban"
    52 "Nasarawa_Rural"
    53 "Niger_Urban"
    54 "Niger_Rural"
    55 "Ogun_Urban"
    56 "Ogun_Rural"
    57 "Ondo_Urban"
    58 "Ondo_Rural"
    59 "Osun_Urban"
    60 "Osun_Rural"
    61 "Oyo_Urban"
    62 "Oyo_Rural"
    63 "Plateau_Urban"
    64 "Plateau_Rural"
    65 "Rivers_Urban"
    66 "Rivers_Urban"
    67 "Rivers_Rural"
    68 "Rivers_Rural"
    69 "Sokoto_Urban"
    70 "Sokoto_Rural"
    71 "Taraba_Urban"
    72 "Taraba_Rural"
    73 "Yobe_Urban"
    74 "Yobe_Rural"
    75 "Zamfara_Urban"
    76 "Zamfara_Rural"
;
label define HV023   
     1 "Abia_Urban"
     2 "Abia_Rural"
     3 "Adamawa_Urban"
     4 "Adamawa_Rural"
     5 "Akwa Ibom_Urban"
     6 "Akwa Ibom_Rural"
     7 "Anambra_Urban"
     8 "Anambra_Rural"
     9 "Bauchi_Urban"
    10 "Bauchi_Rural"
    11 "Bayelsa_Urban"
    12 "Bayelsa_Rural"
    13 "Benue_Urban"
    14 "Benue_Rural"
    15 "Borno_Urban"
    16 "Borno_Rural"
    17 "Cross River_Urban"
    18 "Cross River_Rural"
    19 "Delta_Urban"
    20 "Delta_Rural"
    21 "Ebonyi_Urban"
    22 "Ebonyi_Rural"
    23 "Edo_Urban"
    24 "Edo_Rural"
    25 "Ekiti_Urban"
    26 "Ekiti_Rural"
    27 "Enugu_Urban"
    28 "Enugu_Rural"
    29 "Fct_Urban"
    30 "Fct_Rural"
    31 "Gombe_Urban"
    32 "Gombe_Rural"
    33 "Imo_Urban"
    34 "Imo_Rural"
    35 "Jigawa_Urban"
    36 "Jigawa_Rural"
    37 "Kaduna_Urban"
    38 "Kaduna_Rural"
    39 "Kano_Urban"
    40 "Kano_Rural"
    41 "Katsina_Urban"
    42 "Katsina_Rural"
    43 "Kebbi_Urban"
    44 "Kebbi_Rural"
    45 "Kogi_Urban"
    46 "Kogi_Rural"
    47 "Kwara_Urban"
    48 "Kwara_Rural"
    49 "Lagos_Urban"
    50 "Lagos_Rural"
    51 "Nasarawa_Urban"
    52 "Nasarawa_Rural"
    53 "Niger_Urban"
    54 "Niger_Rural"
    55 "Ogun_Urban"
    56 "Ogun_Rural"
    57 "Ondo_Urban"
    58 "Ondo_Rural"
    59 "Osun_Urban"
    60 "Osun_Rural"
    61 "Oyo_Urban"
    62 "Oyo_Rural"
    63 "Plateau_Urban"
    64 "Plateau_Rural"
    65 "Rivers_Urban"
    66 "Rivers_Urban"
    67 "Rivers_Rural"
    68 "Rivers_Rural"
    69 "Sokoto_Urban"
    70 "Sokoto_Rural"
    71 "Taraba_Urban"
    72 "Taraba_Rural"
    73 "Yobe_Urban"
    74 "Yobe_Rural"
    75 "Zamfara_Urban"
    76 "Zamfara_Rural"
;
label define HV024   
     1 "Sokoto"
     2 "Zamfara"
     3 "Katsina"
     4 "Jigawa"
     5 "Yobe"
     6 "Borno"
     7 "Adamawa"
     8 "Gombe"
     9 "Bauchi"
    10 "Kano"
    11 "Kaduna"
    12 "Kebbi"
    13 "Niger"
    14 "FCT"
    15 "Nasarawa"
    16 "Plateau"
    17 "Taraba"
    18 "Benue"
    19 "Kogi"
    20 "Kwara"
    21 "Oyo"
    22 "Osun"
    23 "Ekiti"
    24 "Ondo"
    25 "Edo"
    26 "Anambra"
    27 "Enugu"
    28 "Ebonyi"
    29 "Cross River"
    30 "Akwa Ibom"
    31 "Abia"
    32 "Imo"
    33 "Rivers"
    34 "Bayelsa"
    35 "Delta"
    36 "Lagos"
    37 "Ogun"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV045A  
     1 "English"
     2 "Hausa"
     3 "Yoruba"
     4 "Igbo"
;
label define HV045B  
     1 "English"
     2 "Hausa"
     3 "Yoruba"
     4 "Igbo"
;
label define HV045C  
     1 "English"
     2 "Hausa"
     3 "Yoruba"
     4 "Igbo"
     5 "Fulfulde"
     6 "Other"
;
label define HV046   
     0 "No"
     1 "Yes"
;
label define HV801   
  9999 "Missing"
;
label define HV802   
  9999 "Missing"
;
label define HV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define HV804   
     9 "Missing"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    72 "Sachet water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    96 "Other"
;
label define HV201A  
     0 "No, not interrupted for a full day"
     1 "Yes, interrupted for a full day or more"
     8 "Don't know"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
;
label define HV214   
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Dirt"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
;
label define HV215   
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Grass"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Metal/Zinc"
    32 "Wood"
    33 "Calamine/cement fiber"
    34 "Ceramic tiles"
    35 "Cement"
    36 "Roofing shingles"
    37 "Asbestos"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV222   
     1 "Electric stove"
     2 "Solar cooker"
     3 "Liquefied petrolium gas (LPG)/cooking gas stove"
     4 "Piped natural gas stove"
     5 "Biogas stove"
     6 "Kerosene stove"
     7 "Manufactured solid fuel stove"
     8 "Traditional solid fuel stove"
     9 "Three stone stove/open fire"
    95 "No food cooked in household"
    96 "Other"
;
label define HV223   
     1 "Alcohol/ethanol"
     2 "Gasoline/diesel"
     3 "Kerosene/Paraffin"
     4 "Coal/lignite"
     5 "Charcoal"
     6 "Wood"
     7 "Straw/shrubs/grass"
     8 "Agricultural crop"
     9 "Animal dung/waste"
    10 "Processed biomass (pellets) or woodchips"
    11 "Garbage/plastic"
    12 "Sawdust"
    96 "Other"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "Solar cooker"
     3 "LPG"
     4 "Natural gas"
     5 "Biogas"
     6 "Alcohol/ethanol"
     7 "Gasoline/diesel"
     8 "Kerosene/paraffin"
     9 "Coal/lignite"
    10 "Charcoal"
    11 "Wood"
    12 "Straw/shrubs/grass"
    13 "Agricultural crop"
    14 "Animal dung/waste"
    15 "Processed biomass (pellets) or woodchips"
    16 "Garbage/plastic"
    17 "Sawdust"
    95 "No food cooked in house"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV238A  
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV243E  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
   950 "95 or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HV270A  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SHREGION
     1 "North Central"
     2 "North East"
     3 "North West"
     4 "South East"
     5 "South South"
     6 "South West"
;
label define SHBONNY 
     0 "No"
     1 "Yes"
;
label define SH116G  
     0 "No"
     1 "Yes"
;
label define SH116H  
     0 "No"
     1 "Yes"
;
label define SH116I  
     0 "No"
     1 "Yes"
;
label define SH116J  
     0 "No"
     1 "Yes"
;
label define SH116K  
     0 "No"
     1 "Yes"
;
label define SH116L  
     0 "No"
     1 "Yes"
;
label define SH116M  
     0 "No"
     1 "Yes"
;
label define SH116N  
     0 "No"
     1 "Yes"
;
label define SH116O  
     0 "No"
     1 "Yes"
;
label define SH117H  
     1 "Yes"
     0 "No"
;
label define SH117I  
     1 "Yes"
     0 "No"
;
label define SH119   
     1 "Yes"
     0 "No"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster/step child"
    12 "Not related"
    98 "Don't know"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present/other"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC62    
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define SB110B  
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define SB110E  
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define HML3    
     0 "Not seen"
     1 "Yes, seen"
;
label define HML4    
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML5    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HML6    
     0 "Not pretreated"
     1 "Pretreated, permanent treatment"
     2 "Pretreated, requiring future treatment"
     3 "Not pretreated, came with kit and treated at home"
     4 "Pretreated, treatment type not known"
     6 "Other"
     8 "Don't know"
;
label define HML7    
    11 "Permanet"
    12 "Olyset"
    13 "Iconlife"
    14 "Duranet"
    15 "Netprotect"
    16 "Basf Interceptor"
    17 "Yorkool"
    18 "Magnet"
    19 "Dawaplus 2.0"
    20 "Royal Security"
    21 "Royal Sentry"
    22 "Permanet 2.0"
    23 "Permanet 3.0"
    24 "Veeralin"
    25 "Interceptor G2"
    26 "Royal Guard"
    36 "Other/Don't know brand (LLIN)"
    96 "Other brand"
    98 "Don't know brand"
;
label define HML8    
     0 "No"
     1 "Yes"
     2 "Permanent/LLIN net"
     8 "Not sure"
;
label define HML9    
    95 "25+ months ago"
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML10   
     0 "No, don't know"
     1 "Yes"
;
label define HML11   
     5 "5+"
;
label define HML21   
     0 "No"
     1 "Yes"
     8 "Not sure (Don't know)"
;
label define HMLA    
     0 "No one"
;
label define HMLB    
    99 "Missing"
;
label define HMLC    
    99 "Missing"
;
label define HML22   
     0 "No"
     1 "Yes, mass distribution campaign"
     2 "Yes, antenatal care"
     3 "Yes, immunization visit"
;
label define HML23   
    10 "Government health facility"
    11 "Government health facility"
    20 "Private health facility"
    21 "Private health facility"
    30 "Other sources"
    31 "Pharmacy"
    32 "Shop/market"
    33 "CHW"
    34 "Religious institution"
    35 "School"
    96 "Other"
    98 "Don't know"
;
label define SH130   
     1 "No mosquitoes"
     2 "No malaria"
     3 "Too hot"
     4 "Don't like smell"
     5 "Feel 'closed in'"
     6 "Net too old/torn"
     7 "Net too dirty"
     8 "Net not available last night (washing)"
     9 "Usual users did not sleep here last night"
    10 "Net not needed last night"
    11 "Bed bugs"
    96 "Other"
    98 "Don't know"
    99 "Missing"
;
label define HML12   
     0 "Did not sleep under a net"
     1 "Only treated (ITN) nets"
     2 "Both treated (ITN) and untreated nets"
     3 "Only untreated nets"
;
label define HML13   
     0 "Did not sleep under net"
;
label define HML16   
    97 "97+"
    98 "Don't know"
;
label define HML17   
     0 "No data from Individual file"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HML18   
     0 "Not pregnant, don't know"
     1 "Pregnant"
;
label define HML19   
     0 "No"
     1 "Yes"
;
label define HML20   
     0 "No"
     1 "Yes"
;
label define HML30   
     0 "Not in household"
;
label define HML31   
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define HML32   
     0 "Negative"
     1 "Positive"
     6 "Test undetermined"
     7 "Sample not found in lab database"
;
label define HML32A  
     0 "No"
     1 "Yes"
;
label define HML32B  
     0 "No"
     1 "Yes"
;
label define HML32C  
     0 "No"
     1 "Yes"
;
label define HML32D  
     0 "No"
     1 "Yes"
;
label define HML32E  
     0 "No"
     1 "Yes"
;
label define HML32F  
     0 "No"
     1 "Yes"
;
label define HML32G  
     0 "No"
     1 "Yes"
;
label define HML33   
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HML35   
     0 "Negative"
     1 "Positive"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HML37A  
     0 "No"
     1 "Yes"
;
label define HML37B  
     0 "No"
     1 "Yes"
;
label define HML37C  
     0 "No"
     1 "Yes"
;
label define HML37D  
     0 "No"
     1 "Yes"
;
label define HML37E  
     0 "No"
     1 "Yes"
;
label define HML37F  
     0 "No"
     1 "Yes"
;
label define HML37G  
     0 "No"
     1 "Yes"
;
label define HML37H  
     0 "No"
     1 "Yes"
;
label define HML37I  
     0 "No"
     1 "Yes"
;
label define HML37J  
     0 "No"
     1 "Yes"
;
label define HML37K  
     0 "No"
     1 "Yes"
;
label define HML37L  
     0 "No"
     1 "Yes"
;
label define HML37M  
     0 "No"
     1 "Yes"
;
label define HML38   
     0 "No"
     1 "Yes"
;
label define HML39   
     0 "Refused medicine"
     1 "Accepted medicine"
     6 "Other"
;

#delimit cr
label values hv003    HV003   
label values hv015    HV015   
label values hv020    HV020   
label values hv022    HV022   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv045a   HV045A  
label values hv045b   HV045B  
label values hv045c   HV045C  
label values hv046    HV046   
label values hv803    HV803   
label values hv201    HV201   
label values hv202    HV202   
label values hv201a   HV201A  
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv222    HV222   
label values hv223    HV223   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv235    HV235   
label values hv238    HV238   
label values hv238a   HV238A  
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv243e   HV243E  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv270    HV270   
label values hv270a   HV270A  
label values hml1     HML1    
label values shregion SHREGION
label values shbonny  SHBONNY 
label values sh116g   SH116G  
label values sh116h   SH116H  
label values sh116i   SH116I  
label values sh116j   SH116J  
label values sh116k   SH116K  
label values sh116l   SH116L  
label values sh116m   SH116M  
label values sh116n   SH116N  
label values sh116o   SH116O  
label values sh117h   SH117H  
label values sh117i   SH117I  
label values sh119    SH119   
label values hv101    HV101   
label values hv102    HV102   
label values hv103    HV103   
label values hv104    HV104   
label values hv105    HV105   
label values hv117    HV117   
label values hv120    HV120   
label values hc16     HC16    
label values hc27     HC27    
label values hc30     HC30    
label values hc31     HC31    
label values hc33     HC33    
label values hc51     HC51    
label values hc52     HC52    
label values hc53     HC53    
label values hc55     HC55    
label values hc56     HC56    
label values hc57     HC57    
label values hc58     HC58    
label values hc60     HC60    
label values hc61     HC61    
label values hc62     HC62    
label values hc68     HC68    
label values sb110b   SB110B  
label values sb110e   SB110E  
label values hml3     HML3    
label values hml4     HML4    
label values hml5     HML5    
label values hml6     HML6    
label values hml7     HML7    
label values hml8     HML8    
label values hml9     HML9    
label values hml10    HML10   
label values hml11    HML11   
label values hml21    HML21   
label values hmla     HMLA    
label values hml22    HML22   
label values hml23    HML23   
label values sh130    SH130   
label values hml12    HML12   
label values hml13    HML13   
label values hml16    HML16   
label values hml17    HML17   
label values hml18    HML18   
label values hml19    HML19   
label values hml20    HML20   
label values hml30    HML30   
label values hml31    HML31   
label values hml32    HML32   
label values hml32a   HML32A  
label values hml32b   HML32B  
label values hml32c   HML32C  
label values hml32d   HML32D  
label values hml32e   HML32E  
label values hml32f   HML32F  
label values hml32g   HML32G  
label values hml33    HML33   
label values hml35    HML35   
label values hml37a   HML37A  
label values hml37b   HML37B  
label values hml37c   HML37C  
label values hml37d   HML37D  
label values hml37e   HML37E  
label values hml37f   HML37F  
label values hml37g   HML37G  
label values hml37h   HML37H  
label values hml37i   HML37I  
label values hml37j   HML37J  
label values hml37k   HML37K  
label values hml37l   HML37L  
label values hml37m   HML37M  
label values hml38    HML38   
label values hml39    HML39   
