infix using "CDPR51FL.dct"

label variable hhid     "Case Identification"
label variable hvidx    "Line number"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number"
label variable hv004    "Ultimate area unit"
label variable hv005    "Sample weight"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in HH"
label variable hv011    "Number of eligible men in HH"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample stratum number      -NA"
label variable hv023    "Sample domain"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "Place of residence"
label variable hv027    "Selection for male/husb. int."
label variable hv028    "Sample weight for male subsamp"
label variable hv030    "Field supervisor"
label variable hv031    "Field editor"
label variable hv032    "Office editor"
label variable hv033    "Ultimate area selection pro-NA"
label variable hv035    "Number of eligible children for height & weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "Total adults measured"
label variable hv042    "Selection for hemoglobin"
label variable hv043    "Selection for women's statu-NA"
label variable hv044    "Selection for domestic violence module"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking wate-NA"
label variable hv204    "Time to get to water source"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material         -NA"
label variable hv215    "Main roof material"
label variable hv216    "Rooms used for sleeping    -NA"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of househ."
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "Have bednet for sleeping"
label variable hv228    "Children under 5 slept under bednet last night"
label variable hv234    "Test salt for Iodine       -NA"
label variable hv235    "Location of source for wate-NA"
label variable hv236    "Person fetching water      -NA"
label variable hv237    "Anything done to water to m-NA"
label variable hv237a   "Water usually treated by: b-NA"
label variable hv237b   "Water usually treated by: a-NA"
label variable hv237c   "Water usually treated by: s-NA"
label variable hv237d   "Water usually treated by: u-NA"
label variable hv237e   "Water usually treated by: s-NA"
label variable hv237f   "Water usually treated by: l-NA"
label variable hv237g   "Water usually treated by: C-NA"
label variable hv237h   "Water usually treated by: C-NA"
label variable hv237i   "Water usually treated by: C-NA"
label variable hv237j   "Water usually treated by: C-NA"
label variable hv237k   "Water usually treated by: C-NA"
label variable hv237x   "Water usually treated by: o-NA"
label variable hv237z   "Water usually treated by: d-NA"
label variable hv238    "Number of households sharin-NA"
label variable hv239    "Food cooked on stove or ope-NA"
label variable hv240    "Household has a chimney, ho-NA"
label variable hv241    "Food cooked in the house / -NA"
label variable hv242    "Household has separate room-NA"
label variable hv243a   "Has a mobile telephone"
label variable hv243b   "Has a watch                -NA"
label variable hv243c   "Has an animal-drawn cart   -NA"
label variable hv243d   "Has a boat with a motor    -NA"
label variable hv244    "Own land usable for agricul-NA"
label variable hv245    "Hectares for agricultural l-NA"
label variable hv246    "Livestock, herds or farm an-NA"
label variable hv246a   "Cattle own                 -NA"
label variable hv246b   "Cows, bulls own            -NA"
label variable hv246c   "Horses, donkeys, mules own -NA"
label variable hv246d   "Goats own                  -NA"
label variable hv246e   "Sheep own                  -NA"
label variable hv246f   "Chickens own               -NA"
label variable hv246g   "CS own                     -NA"
label variable hv246h   "CS own                     -NA"
label variable hv246i   "CS own                     -NA"
label variable hv246j   "CS own                     -NA"
label variable hv246k   "CS own                     -NA"
label variable hv247    "Owns a bank account        -NA"
label variable hv248    "Number of sick people 18-59-NA"
label variable hv249    "Member of the HH died last -NA"
label variable hv250    "Number of members who died -NA"
label variable hv251    "Number of orphans and vulne-NA"
label variable hv270    "Wealth index"
label variable hv271    "Wealth index factor score (5 decimals)"
label variable hml1     "Number of mosquito nets"
label variable hml1a    "Number of mosquito nets with specific information"
label variable hml2     "Number of children under bednet previous night"
label variable sh105g   "Has grill, heater"
label variable sh105h   "Has chair(s)"
label variable sh105i   "Has bed(s)"
label variable sh105j   "Has lamp(s)"
label variable sh105k   "Has stove, cooker"
label variable sh105l   "Has hoe(s)"
label variable sh105m   "Has sewing machine"
label variable sh108_d  "Has canoe, dugout"
label variable sh108a   "Time to get to health facility"
label variable sh108b   "Type of health facility"
label variable sh121    "Cost of treating bednet"
label variable sh121aa  "Reason for not using bed net : Too expensive"
label variable sh121ab  "Reason for not using bed net : No bednets for sale"
label variable sh121ac  "Reason for not using bed net : Don't know about bed nets"
label variable sh121ad  "Reason for not using bed net : Spray bedroom"
label variable sh121ae  "Reason for not using bed net : Uncomfortable, too hot"
label variable sh121af  "Reason for not using bed net : No mosquitoes in vicinity"
label variable sh121ag  "Reason for not using bed net : Gave net to others"
label variable sh121ax  "Reason for not using bed net : Other"
label variable sh122    "Test salt for Iodine"
label variable sh402    "Family member died in last 12 months"
label variable sh403    "Family member aged 18-59 died in last 12 months"
label variable sh404    "Family member aged 18-59 who died in last 12 months and was "
label variable hv101    "Relationship to head"
label variable hv102    "Usual resident"
label variable hv103    "Slept last night"
label variable hv104    "Sex of household member"
label variable hv105    "Age of household members"
label variable hv106    "Highest educational level"
label variable hv107    "Highest year of education"
label variable hv108    "Education in single years"
label variable hv109    "Educational attainment"
label variable hv110    "Member still in school     -NA"
label variable hv111    "Mother alive"
label variable hv112    "Mother's line number"
label variable hv113    "Father alive"
label variable hv114    "Father's line number"
label variable hv115    "Current marital status"
label variable hv116    "Currently, formerly, never m."
label variable hv117    "Eligibility for female interview"
label variable hv118    "Eligibility for male interview"
label variable hv120    "Children eligibility for height/weight and hemoglobin"
label variable hv121    "Member attended school during current school year"
label variable hv122    "Educational level during current school year"
label variable hv123    "Grade of education during current school year"
label variable hv124    "Education in single years - current school year"
label variable hv125    "Member attended school during previous school year"
label variable hv126    "Educational level during previous school year"
label variable hv127    "Grade of education during previous school year"
label variable hv128    "Education in single years - previous school year"
label variable hv129    "School attendance status"
label variable hv130    "Member has been very sick for 3+ months last year"
label variable hv131    "Mother has been very sick for 3+ months last year"
label variable hv132    "Father has been very sick for 3+ months last year"
label variable hv133    "Mother/father dead or been -NA"
label variable hv134    "Both parents alive         -NA"
label variable hv135    "Has brothers/sisters under -NA"
label variable hv136    "Brothers/sisters under 18 t-NA"
label variable hv137    "Member has a blanket       -NA"
label variable hv138    "Member has a pair of shoes -NA"
label variable hv139    "Member has 2+ sets of cloth-NA"
label variable hv140    "Member has a birth certific-NA"
label variable idxh4    "Index to household schedule"
label variable sh204    "Works for someone else other than family member"
label variable sh205    "Number of hours worked"
label variable sh206    "Worked in last 12 months"
label variable sh207    "Helps with household chores"
label variable sh208    "Number of hours worked on housework"
label variable sh209    "Works for household on farm/compound"
label variable sh210    "Number of hours worked for household on farm/compound"
label variable sh413    "Emotional support in last 3 months"
label variable sh415    "Material support in last 3 months"
label variable sh417    "Social support in last 3 months"
label variable sh419    "Support for school"
label variable sh507a   "oedèmes"
label variable sh509    "Né aucours du mois d'enquete ou 5 derniers mois"
label variable ha0      "Index to household schedule"
label variable ha1      "Women's age in years"
label variable ha2      "Respondent's weight (kilos-1d)"
label variable ha3      "Respondent's height (cms-1d)"
label variable ha4      "Ht/A Percentile (resp.)"
label variable ha5      "Ht/A Standard deviations (resp"
label variable ha6      "Ht/A Percent ref. median (resp"
label variable ha11     "Wt/Ht Std deviations(resp) DHS"
label variable ha12     "Wt/Ht Percent ref. median (DHS"
label variable ha12a    "Wt/Ht Percent ref. median (Fog"
label variable ha12b    "Wt/Ht Percent ref. median (WHO"
label variable ha13     "Result of measurement of resp."
label variable ha32     "Date of birth (cmc)"
label variable ha33     "Completeness of information"
label variable ha35     "Smoking"
label variable ha40     "Body mass index for respondent"
label variable ha41     "Rohrer's index for respondent"
label variable ha50     "Under age 18"
label variable ha51     "Line no. of parent/caretaker"
label variable ha52     "Read consent statement"
label variable ha53     "Hemoglobin level (g/dl - 1 decimal)"
label variable ha54     "Currently pregnant"
label variable ha55     "Result of measuring (Hemoglobin)"
label variable ha56     "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable ha57     "Anemia level"
label variable ha58     "Agrees to referral         -NA"
label variable ha60     "Marital status"
label variable ha61     "Read consent statement (HIV)"
label variable ha62     "Blood sample ID number"
label variable ha63     "Result of measuring (HIV)"
label variable ha64     "Consent for additional tests"
label variable ha65     "Result of woman individual interview"
label variable ha66     "Woman's highest educational level"
label variable ha67     "Woman's highest year of education"
label variable ha68     "Highest educational level (CS for prelimnary & final report)"
label variable ha69     "HIV weight (6 decimals)"
label variable hc0      "Index to household schedule"
label variable hc1      "Age in months"
label variable hc2      "Weight in kilograms (1 dec.)"
label variable hc3      "Height in centimeters (1 dec.)"
label variable hc4      "Ht/A Percentile"
label variable hc5      "Ht/A Standard deviations"
label variable hc6      "Ht/A Percent of ref. median"
label variable hc7      "Wt/A Percentile"
label variable hc8      "Wt/A Standard deviations"
label variable hc9      "Wt/A Percent of ref. median"
label variable hc10     "Wt/Ht Percentile"
label variable hc11     "Wt/Ht Standard deviations"
label variable hc12     "Wt/Ht Percent of ref. median"
label variable hc13     "Reason not measured"
label variable hc15     "Height: lying or standing"
label variable hc16     "Day of birth of child"
label variable hc17     "Date measured (day)"
label variable hc18     "Date measured (month)"
label variable hc19     "Date measured (year)"
label variable hc27     "Sex"
label variable hc30     "Month of birth of child"
label variable hc31     "Year of birth of child"
label variable hc32     "Date of birth (cmc)"
label variable hc33     "Completeness of information"
label variable hc51     "Line no. of parent/caretaker"
label variable hc52     "Read consent statement"
label variable hc53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55     "Result of measuring (Hemoglobin)"
label variable hc56     "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hc57     "Anemia level"
label variable hc58     "Agrees to referral         -NA"
label variable hc60     "Mother's line number from woman's questionnaire"
label variable hc61     "Mother's highest educational level"
label variable hc62     "Mother's highest year of education"
label variable hc63     "Preceding birth interval"
label variable hc64     "Birth order number"
label variable hc68     "Highest educational level (CS for prelimnary & final report)"
label variable hc70     "Ht/A Standard deviations (according to WHO)"
label variable hc71     "Wt/A Standard deviations (according to WHO)"
label variable hc72     "Wt/Ht Standard deviations (according to WHO)"
label variable hc73     "BMI Standard deviations (according to WHO)"
label variable hb0      "Index to household schedule"
label variable hb1      "Men's age in years"
label variable hb2      "Respondent's weight (kilos--NA"
label variable hb3      "Respondent's height (cms-1d-NA"
label variable hb4      "Ht/A Percentile (resp.)"
label variable hb5      "Ht/A Standard deviations (resp"
label variable hb6      "Ht/A Percent ref. median (resp"
label variable hb11     "Wt/Ht Std deviations(resp) DHS"
label variable hb12     "Wt/Ht Percent ref. median (DHS"
label variable hb12a    "Wt/Ht Percent ref. median (Fog"
label variable hb12b    "Wt/Ht Percent ref. median (WHO"
label variable hb13     "Result of measurement of re-NA"
label variable hb32     "Date of birth (cmc)"
label variable hb33     "Completeness of information"
label variable hb35     "Smoking                    -NA"
label variable hb40     "Body mass index for respondent"
label variable hb41     "Rohrer's index for respondent"
label variable hb50     "Under age 18"
label variable hb51     "Line no. of parent/caretaker"
label variable hb52     "Read consent statement"
label variable hb53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hb55     "Result of measuring (Hemoglobin)"
label variable hb56     "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hb57     "Anemia level"
label variable hb58     "Agrees to referral         -NA"
label variable hb60     "Marital status"
label variable hb61     "Read consent statement (HIV)"
label variable hb62     "Blood sample ID number"
label variable hb63     "Result of measuring (HIV)"
label variable hb64     "Consent for additional test-NA"
label variable hb65     "Result of man individual interview"
label variable hb66     "Man's highest educational level"
label variable hb67     "Man's highest year of education"
label variable hb68     "Highest educational level (CS for prelimnary & final report)"
label variable hb69     "HIV weight (6 decimals)"
label variable hmlidx   "Net number"
label variable hml3     "Net observed"
label variable hml4     "Months ago obtained mosquito net"
label variable hml5     "Was net treated with insecticide when bought"
label variable hml6     "Mosquito net treated with i-NA"
label variable hml7     "Brand of bednet            -NA"
label variable hml8     "Bednet treated since receiving"
label variable hml9     "Months ago re-treated"
label variable hml10    "ITN net"
label variable hml11    "Number of persons who slept under this net"
label variable hml21    "Did someone sleep under bednet last night"
label variable hmla     "Person who slept in mosquito net"
label variable hmlb     "Person who slept in mosquito net"
label variable hmlc     "Person who slept in mosquito net"
label variable hmld     "Person who slept in mosquito net"
label variable hmle     "Person who slept in mosquito net"
label variable sh113    "Cost of bednet"
label variable hmhidx   "Index to household schedule"
label variable hml12    "Type of bednet(s) person slept under last night"
label variable hml13    "1st net number for net person slept under last night"
label variable hml14    "2nd net number for net person slept under last night"
label variable hml15    "3rd net number for net pers-NA"
label variable hml16    "Corrected age from individual questionnaire"
label variable hml17    "Flag for AH07 age from individual file"
label variable hml18    "Pregnancy from individual questionnaire"
label variable hml19    "Person sleep under an ever treated bednet"
label variable hovidx   "Index to household schedule"
label variable ho100    "Age of child"
label variable ho101    "Free medical support last 12 months"
label variable ho102    "Free emotional support last 12 months"
label variable ho103    "Emotional support last 3 months"
label variable ho104    "Free material support last 12 months"
label variable ho105    "Material support last 3 months"
label variable ho106    "Free social support last 12 months"
label variable ho107    "Social support last 3 months"
label variable ho108    "Free any support           -NA"

#delimit ;
label define HV003   
     0 "Not in the household *"
;
label define HV007   
  2007 "***Undefined Label"
;
label define HV015   
     1 "Completed"
     2 "HH present, no resp"
     3 "HH absent"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV023   
     0 "National"
     1 "Country specific"
;
label define HV024   
    10 "Kinshasa"
    20 "Bas-Congo"
    30 "Bandundu"
    40 "Equateur"
    50 "Orientale"
    61 "Nord-Kivu"
    62 "Maniema"
    63 "Sud-Kivu"
    70 "Katanga"
    80 "Kasaï Oriental"
    90 "Kasaï Occident"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV032   
    99 "Missing"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV043   
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well in dwelling"
    32 "Protected well in yard/plot"
    33 "Protected public well"
    34 "Open well in dwelling"
    35 "Open well in yard/plot"
    36 "Open public well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/stream"
    44 "Sea, lake"
    45 "Dam"
    51 "Rainwater"
    61 "Tanker truck"
    71 "Bottled water"
    96 "Other"
;
label define HV202   
    10 "***Undefined Label"
    11 "***Undefined Label"
    12 "***Undefined Label"
    13 "***Undefined Label"
    20 "***Undefined Label"
    21 "***Undefined Label"
    30 "***Undefined Label"
    31 "***Undefined Label"
    32 "***Undefined Label"
    40 "***Undefined Label"
    41 "***Undefined Label"
    42 "***Undefined Label"
    43 "***Undefined Label"
    51 "***Undefined Label"
    61 "***Undefined Label"
    62 "***Undefined Label"
    71 "***Undefined Label"
    96 "***Undefined Label"
;
label define HV204   
   996 "On premises"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush toilet"
    20 "PIT TOILET LATRINE"
    21 "Traditional pit toilet (uncovered)"
    22 "Traditional pit toilet (covered)"
    23 "Ventilated improved pit latrine"
    30 "NO FACILITY"
    31 "No facility, bush, field"
    96 "OTHER"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Terre/sable"
    20 "RUDIMENTARY"
    21 "Bois/Autres Végétaux"
    30 "FINISHED"
    31 "Ciment"
    32 "Carrelage"
    33 "Autres matériaux moderne"
    96 "OTHER"
;
label define HV214   
    10 "***Undefined Label"
    20 "***Undefined Label"
    30 "***Undefined Label"
    31 "***Undefined Label"
    96 "***Undefined Label"
;
label define HV215   
    10 "NATURAL"
    11 "Chaume/Palme/Feuilles"
    20 "RUDIMENTARY"
    21 "Natte"
    22 "Palme/Bambou"
    23 "Planches en bois"
    30 "FINISHED"
    31 "Dalles en Béton"
    32 "Tuiles/Ardoise/Eternit"
    33 "Tôle"
    96 "OTHER"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opp. sex"
     3 "Two adults, same sex"
     4 "Three+ related adult"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "DK"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw / shrubs / grass"
    10 "Agricultural crop"
    11 "Animal dung"
    12 "Wood chips"
    95 "No food cooked in HH"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No bednet in HH"
;
label define HV234   
     0 "***Undefined Label"
     7 "***Undefined Label"
    15 "***Undefined Label"
    30 "***Undefined Label"
   994 "***Undefined Label"
   995 "***Undefined Label"
;
label define HV235   
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
;
label define HV236   
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     4 "***Undefined Label"
     6 "***Undefined Label"
;
label define HV237   
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define HV237A  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV237B  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV237C  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV237D  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV237E  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV237F  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV237G  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV237H  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV237I  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV237J  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV237K  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV237X  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV237Z  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV238   
    95 "***Undefined Label"
    98 "***Undefined Label"
;
label define HV239   
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     6 "***Undefined Label"
;
label define HV240   
     0 "***Undefined Label"
     1 "***Undefined Label"
     2 "***Undefined Label"
;
label define HV241   
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     6 "***Undefined Label"
;
label define HV242   
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV243C  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV243D  
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV244   
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV245   
    95 "***Undefined Label"
    98 "***Undefined Label"
;
label define HV246   
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV246A  
     0 "***Undefined Label"
    95 "***Undefined Label"
    98 "***Undefined Label"
;
label define HV246B  
     0 "***Undefined Label"
    95 "***Undefined Label"
    98 "***Undefined Label"
;
label define HV246C  
     0 "***Undefined Label"
    95 "***Undefined Label"
    98 "***Undefined Label"
;
label define HV246D  
     0 "***Undefined Label"
    95 "***Undefined Label"
    98 "***Undefined Label"
;
label define HV246E  
     0 "***Undefined Label"
    95 "***Undefined Label"
    98 "***Undefined Label"
;
label define HV246F  
     0 "***Undefined Label"
    95 "***Undefined Label"
    98 "***Undefined Label"
;
label define HV246G  
     0 "***Undefined Label"
    95 "***Undefined Label"
    98 "***Undefined Label"
;
label define HV246H  
     0 "***Undefined Label"
    95 "***Undefined Label"
    98 "***Undefined Label"
;
label define HV246I  
     0 "***Undefined Label"
    95 "***Undefined Label"
    98 "***Undefined Label"
;
label define HV246J  
     0 "***Undefined Label"
    95 "***Undefined Label"
    98 "***Undefined Label"
;
label define HV246K  
     0 "***Undefined Label"
    95 "***Undefined Label"
    98 "***Undefined Label"
;
label define HV247   
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV249   
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
     9 "***Undefined Label"
;
label define HV250   
     8 "***Undefined Label"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SH105G  
     0 "No"
     1 "Yes"
;
label define SH105H  
     0 "No"
     1 "Yes"
;
label define SH105I  
     0 "No"
     1 "Yes"
;
label define SH105J  
     0 "No"
     1 "Yes"
;
label define SH105K  
     0 "No"
     1 "Yes"
;
label define SH105L  
     0 "No"
     1 "Yes"
;
label define SH105M  
     0 "No"
     1 "Yes"
;
label define SH108_D 
     0 "No"
     1 "Yes"
;
label define SH108A  
   999 "Missing"
;
label define SH108B  
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Government health post"
    14 "Government Maternity clinic"
    16 "Other public"
    20 "PRIVATE MEDICAL"
    21 "Private hospital, clinic"
    22 "Pharmacy"
    23 "Private doctor"
    26 "Other private"
    30 "OTHER MEDICAL"
    31 "Medical, religious"
    96 "Other"
;
label define SH121   
 99995 "Free"
 99996 "Don't know"
;
label define SH121AA 
     0 "No"
     1 "Yes"
;
label define SH121AB 
     0 "No"
     1 "Yes"
;
label define SH121AC 
     0 "No"
     1 "Yes"
;
label define SH121AD 
     0 "No"
     1 "Yes"
;
label define SH121AE 
     0 "No"
     1 "Yes"
;
label define SH121AF 
     0 "No"
     1 "Yes"
;
label define SH121AG 
     0 "No"
     1 "Yes"
;
label define SH121AX 
     0 "No"
     1 "Yes"
;
label define SH122   
     0 "0 PPM (No Iodine)"
     1 "< 15 PPM"
     2 ">= 15 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define SH402   
     0 "No"
     1 "Yes"
;
label define SH403   
     0 "No"
     1 "Yes"
;
label define SH404   
     0 "No"
     1 "Yes"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nehew by blood"
    14 "Niece/nephew by marriage"
    98 "DK"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    97 "97+"
    98 "DK"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV107   
    98 "DK"
;
label define HV108   
    97 "Inconsistent"
    98 "DK"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
;
label define HV110   
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV112   
     0 "Mother not in HH"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV114   
     0 "Father not in HH"
;
label define HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV123   
    98 "DK"
;
label define HV124   
    97 "Inconsistent"
    98 "DK"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV127   
    98 "DK"
;
label define HV128   
    97 "Inconsistent"
    98 "DK"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
;
label define HV130   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV131   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV132   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV133   
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV134   
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV135   
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define HV136   
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HV137   
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define HV138   
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define HV139   
     0 "***Undefined Label"
     1 "***Undefined Label"
     8 "***Undefined Label"
;
label define HV140   
     0 "***Undefined Label"
     1 "***Undefined Label"
     2 "***Undefined Label"
     8 "***Undefined Label"
;
label define SH204   
     0 "No"
     1 "Yes, paid"
     2 "Yes, unpaid"
;
label define SH205   
    95 "> 94"
;
label define SH206   
     0 "No"
     1 "Yes, paid"
     2 "Yes, unpaid"
;
label define SH207   
     0 "No"
     1 "Yes"
;
label define SH208   
    95 "> 94"
;
label define SH209   
     0 "No"
     1 "Yes"
;
label define SH210   
    95 "> 94"
;
label define SH413   
     1 "Yes"
     0 "No"
     8 "Don't know"
;
label define SH415   
     1 "Yes"
     0 "No"
     8 "Don't know"
;
label define SH417   
     1 "Yes"
     0 "No"
     8 "Don't know"
;
label define SH419   
     1 "Yes"
     0 "No"
     8 "Don't know"
;
label define SH507A  
     0 "No"
     1 "Yes"
;
label define SH509   
     1 "0-5 mois"
     2 "Plus âgé"
;
label define HA2     
  9999 "Missing"
;
label define HA3     
  9999 "Missing"
;
label define HA4     
  9998 "Flagged cases"
;
label define HA5     
  9998 "Flagged cases"
;
label define HA6     
 99998 "Flagged cases"
;
label define HA11    
  9998 "Flagged cases"
;
label define HA12    
 99998 "Flagged cases"
;
label define HA12A   
 99998 "Flagged cases"
;
label define HA12B   
 99998 "Flagged cases"
;
label define HA13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA33    
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     5 "***Undefined Label"
     6 "Age"
     7 "Month"
     8 "None"
;
label define HA35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
;
label define HA40    
  9998 "Flagged cases"
;
label define HA41    
  9998 "Flagged cases"
;
label define HA50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HA51    
     0 "Not in household"
;
label define HA52    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
;
label define HA53    
   999 "Missing"
;
label define HA54    
     0 "No/don't know"
     1 "Yes"
;
label define HA55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     5 "***Undefined Label"
     6 "Other"
;
label define HA56    
   999 "Missing"
;
label define HA57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HA58    
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HA60    
     1 "Never in union"
     2 "Other"
;
label define HA61    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
;
label define HA63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Technical problem at lab *"
     5 "Sample taken but not received at lab *"
     6 "Other"
;
label define HA64    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
;
label define HA65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HA66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define HA67    
    99 "Missing"
;
label define HA68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define HC2     
  9999 "Missing"
;
label define HC3     
  9999 "Missing"
;
label define HC4     
  9998 "Flagged cases"
;
label define HC5     
  9998 "Flagged cases"
;
label define HC6     
 99998 "Flagged cases"
;
label define HC7     
  9998 "Flagged cases"
;
label define HC8     
  9998 "Flagged cases"
;
label define HC9     
 99998 "Flagged cases"
;
label define HC10    
  9998 "Flagged cases"
;
label define HC11    
  9998 "Flagged cases"
;
label define HC12    
 99998 "Flagged cases"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     5 "***Undefined Label"
     6 "Other"
;
label define HC15    
     1 "Lying"
     2 "Standing"
;
label define HC16    
    99 "Missing"
;
label define HC19    
  2007 "***Undefined Label"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "DK"
;
label define HC31    
  9997 "Inconsistent"
  9998 "DK"
;
label define HC33    
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     5 "***Undefined Label"
     6 "Age"
     7 "Month"
     8 "None"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
;
label define HC53    
   999 "Missing"
;
label define HC55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     5 "***Undefined Label"
     6 "Other"
;
label define HC56    
   999 "Missing"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define HC62    
    99 "Missing"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HB2     
  9999 "Missing"
;
label define HB3     
  9999 "Missing"
;
label define HB4     
  9998 "Flagged cases"
;
label define HB5     
  9998 "Flagged cases"
;
label define HB6     
 99998 "Flagged cases"
;
label define HB11    
  9998 "Flagged cases"
;
label define HB12    
 99998 "Flagged cases"
;
label define HB12A   
 99998 "Flagged cases"
;
label define HB12B   
 99998 "Flagged cases"
;
label define HB13    
     0 "***Undefined Label"
     3 "***Undefined Label"
     4 "***Undefined Label"
     5 "***Undefined Label"
     6 "***Undefined Label"
;
label define HB33    
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     5 "***Undefined Label"
     6 "Age"
     7 "Month"
     8 "None"
;
label define HB35    
     0 "***Undefined Label"
    80 "***Undefined Label"
    94 "***Undefined Label"
;
label define HB40    
  9998 "Flagged cases"
;
label define HB41    
  9998 "Flagged cases"
;
label define HB50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HB51    
     0 "Not in household"
;
label define HB52    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
;
label define HB53    
   999 "Missing"
;
label define HB55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     5 "***Undefined Label"
     6 "Other"
;
label define HB56    
   999 "Missing"
;
label define HB57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HB58    
     0 "***Undefined Label"
     1 "***Undefined Label"
;
label define HB60    
     1 "Never in union"
     2 "Other"
;
label define HB61    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
;
label define HB63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Technical problem at lab *"
     5 "Sample taken but not received at lab *"
     6 "Other"
;
label define HB64    
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
;
label define HB65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HB66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HB67    
    99 "Missing"
;
label define HB68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HML3    
     0 "Not seen"
     1 "Yes, seen"
;
label define HML4    
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML5    
     0 "No"
     1 "Yes"
     8 "Not sure/don't know *"
;
label define HML6    
     0 "***Undefined Label"
     1 "***Undefined Label"
     2 "***Undefined Label"
     3 "***Undefined Label"
     4 "***Undefined Label"
     6 "***Undefined Label"
     8 "***Undefined Label"
;
label define HML7    
    98 "***Undefined Label"
;
label define HML8    
     0 "No"
     1 "Yes"
     2 "Permanent net"
     8 "Not sure"
;
label define HML9    
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML10   
     0 "No, don't know"
     1 "Yes"
;
label define HML11   
     5 "5+"
;
label define HML21   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HMLA    
     0 "No one"
;
label define HMLB    
    99 "Missing"
;
label define HMLC    
    99 "Missing"
;
label define SH113   
     0 "Free of charge"
 99996 "Don't know"
;
label define HML12   
     0 "No bednet"
     1 "Only treated bednets"
     2 "Both treated and untreated bednets"
     3 "Only untreated bednets"
;
label define HML13   
     0 "Did not sleep under net"
;
label define HML16   
    97 "97+"
    98 "DK"
;
label define HML17   
     0 "No data from individual questionnaire"
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define HML18   
     0 "Not pregnant, don't know"
     1 "Pregnant"
;
label define HML19   
     0 "No"
     1 "Yes"
;
label define HO100   
    99 "Missing"
;
label define HO101   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO102   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO103   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO104   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO105   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO106   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO107   
     0 "No"
     1 "Yes"
     8 "DK"
;

#delimit cr
label values hv003    HV003   
label values hv007    HV007   
label values hv015    HV015   
label values hv020    HV020   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv043    HV043   
label values hv044    HV044   
label values hv201    HV201   
label values hv202    HV202   
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv234    HV234   
label values hv235    HV235   
label values hv236    HV236   
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237g   HV237G  
label values hv237h   HV237H  
label values hv237i   HV237I  
label values hv237j   HV237J  
label values hv237k   HV237K  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv249    HV249   
label values hv250    HV250   
label values hv270    HV270   
label values hml1     HML1    
label values sh105g   SH105G  
label values sh105h   SH105H  
label values sh105i   SH105I  
label values sh105j   SH105J  
label values sh105k   SH105K  
label values sh105l   SH105L  
label values sh105m   SH105M  
label values sh108_d  SH108_D 
label values sh108b   SH108B  
label values sh121    SH121   
label values sh121aa  SH121AA 
label values sh121ab  SH121AB 
label values sh121ac  SH121AC 
label values sh121ad  SH121AD 
label values sh121ae  SH121AE 
label values sh121af  SH121AF 
label values sh121ag  SH121AG 
label values sh121ax  SH121AX 
label values sh122    SH122   
label values sh402    SH402   
label values sh403    SH403   
label values sh404    SH404   
label values hv101    HV101   
label values hv102    HV102   
label values hv103    HV103   
label values hv104    HV104   
label values hv105    HV105   
label values hv106    HV106   
label values hv107    HV107   
label values hv108    HV108   
label values hv109    HV109   
label values hv110    HV110   
label values hv111    HV111   
label values hv112    HV112   
label values hv113    HV113   
label values hv114    HV114   
label values hv115    HV115   
label values hv116    HV116   
label values hv117    HV117   
label values hv118    HV118   
label values hv120    HV120   
label values hv121    HV121   
label values hv122    HV122   
label values hv123    HV123   
label values hv124    HV124   
label values hv125    HV125   
label values hv126    HV126   
label values hv127    HV127   
label values hv128    HV128   
label values hv129    HV129   
label values hv130    HV130   
label values hv131    HV131   
label values hv132    HV132   
label values hv133    HV133   
label values hv134    HV134   
label values hv135    HV135   
label values hv136    HV136   
label values hv137    HV137   
label values hv138    HV138   
label values hv139    HV139   
label values hv140    HV140   
label values sh204    SH204   
label values sh205    SH205   
label values sh206    SH206   
label values sh207    SH207   
label values sh208    SH208   
label values sh209    SH209   
label values sh210    SH210   
label values sh413    SH413   
label values sh415    SH415   
label values sh417    SH417   
label values sh419    SH419   
label values sh507a   SH507A  
label values sh509    SH509   
label values ha4      HA4     
label values ha5      HA5     
label values ha6      HA6     
label values ha11     HA11    
label values ha12     HA12    
label values ha12a    HA12A   
label values ha12b    HA12B   
label values ha13     HA13    
label values ha33     HA33    
label values ha35     HA35    
label values ha40     HA40    
label values ha41     HA41    
label values ha50     HA50    
label values ha51     HA51    
label values ha52     HA52    
label values ha54     HA54    
label values ha55     HA55    
label values ha57     HA57    
label values ha58     HA58    
label values ha60     HA60    
label values ha61     HA61    
label values ha63     HA63    
label values ha64     HA64    
label values ha65     HA65    
label values ha66     HA66    
label values ha68     HA68    
label values hc4      HC4     
label values hc5      HC5     
label values hc6      HC6     
label values hc7      HC7     
label values hc8      HC8     
label values hc9      HC9     
label values hc10     HC10    
label values hc11     HC11    
label values hc12     HC12    
label values hc13     HC13    
label values hc15     HC15    
label values hc19     HC19    
label values hc27     HC27    
label values hc30     HC30    
label values hc31     HC31    
label values hc33     HC33    
label values hc51     HC51    
label values hc52     HC52    
label values hc55     HC55    
label values hc57     HC57    
label values hc58     HC58    
label values hc60     HC60    
label values hc61     HC61    
label values hc68     HC68    
label values hc70     HC70    
label values hc71     HC71    
label values hc72     HC72    
label values hc73     HC73    
label values hb4      HB4     
label values hb5      HB5     
label values hb6      HB6     
label values hb11     HB11    
label values hb12     HB12    
label values hb12a    HB12A   
label values hb12b    HB12B   
label values hb13     HB13    
label values hb33     HB33    
label values hb35     HB35    
label values hb40     HB40    
label values hb41     HB41    
label values hb50     HB50    
label values hb51     HB51    
label values hb52     HB52    
label values hb55     HB55    
label values hb57     HB57    
label values hb58     HB58    
label values hb60     HB60    
label values hb61     HB61    
label values hb63     HB63    
label values hb64     HB64    
label values hb65     HB65    
label values hb66     HB66    
label values hb68     HB68    
label values hml3     HML3    
label values hml4     HML4    
label values hml5     HML5    
label values hml6     HML6    
label values hml7     HML7    
label values hml8     HML8    
label values hml9     HML9    
label values hml10    HML10   
label values hml11    HML11   
label values hml21    HML21   
label values hmla     HMLA    
label values sh113    SH113   
label values hml12    HML12   
label values hml13    HML13   
label values hml16    HML16   
label values hml17    HML17   
label values hml18    HML18   
label values hml19    HML19   
label values ho101    HO101   
label values ho102    HO102   
label values ho103    HO103   
label values ho104    HO104   
label values ho105    HO105   
label values ho106    HO106   
label values ho107    HO107   
