infix using "C:\COUNTRIES\GH82\GHIR82FL.dct"

label variable caseid   "Case Identification"
label variable v000     "Country code and phase"
label variable v001     "Cluster number"
label variable v002     "Household number"
label variable v003     "Respondent's line number"
label variable v004     "Ultimate area unit"
label variable v005     "Women's individual sample weight (6 decimals)"
label variable v006     "Month of interview"
label variable v007     "Year of interview"
label variable v008     "Date of interview (CMC)"
label variable v008a    "Date of interview Century Day Code (CDC)"
label variable v009     "Respondent's month of birth"
label variable v010     "Respondent's year of birth"
label variable v011     "Date of birth (CMC)"
label variable v012     "Respondent's current age"
label variable v013     "Age in 5-year groups"
label variable v014     "Completeness of age information"
label variable v015     "Result of individual interview"
label variable v016     "Day of interview"
label variable v017     "NA - CMC start of calendar"
label variable v018     "NA - Row of month of interview"
label variable v019     "NA - Length of calendar"
label variable v019a    "NA - Number of calendar columns"
label variable v020     "Ever-married sample"
label variable v021     "Primary sampling unit"
label variable v022     "Sample strata for sampling errors"
label variable v023     "Stratification used in sample design"
label variable v024     "Region"
label variable v025     "Type of place of residence"
label variable v026     "NA - De facto place of residence"
label variable v027     "Number of visits"
label variable v028     "Interviewer identification"
label variable v029     "NA - Keyer identification"
label variable v030     "Field supervisor"
label variable v031     "NA - Field editor"
label variable v032     "NA - Office editor"
label variable v034     "NA - Line number of husband"
label variable v040     "Cluster altitude in meters"
label variable v042     "Household selected for hemoglobin"
label variable v044     "NA - Selected for Domestic Violence module"
label variable v045a    "Language of questionnaire"
label variable v045b    "Language of interview"
label variable v045c    "Native language of respondent"
label variable v046     "Translator used"
label variable v101     "Region"
label variable v102     "Type of place of residence"
label variable v106     "Highest educational level"
label variable v107     "Highest year of education"
label variable v113     "Source of drinking water"
label variable v115     "Time to get to water source"
label variable v116     "Type of toilet facility"
label variable v119     "Household has: electricity"
label variable v120     "Household has: radio"
label variable v121     "Household has: television"
label variable v122     "Household has: refrigerator"
label variable v123     "Household has: bicycle"
label variable v124     "Household has: motorcycle/scooter"
label variable v125     "Household has: car/truck"
label variable v127     "Main floor material"
label variable v128     "Main wall material"
label variable v129     "Main roof material"
label variable v130     "Religion"
label variable v131     "Ethnicity"
label variable v133     "Education in single years"
label variable v135     "Usual resident or visitor"
label variable v136     "Number of household members (listed)"
label variable v137     "Number of children 5 and under in household (de jure)"
label variable v138     "Number of eligible women in household (de facto)"
label variable v139     "De jure region of residence"
label variable v140     "De jure type of place of residence"
label variable v149     "Educational attainment"
label variable v150     "Relationship to household head"
label variable v151     "Sex of household head"
label variable v152     "Age of household head"
label variable v153     "Household has: telephone (land-line)"
label variable awfactt  "NA - All woman factor - total"
label variable awfactu  "NA - All woman factor - urban/rural"
label variable awfactr  "NA - All woman factor - regional"
label variable awfacte  "NA - All woman factor - educational"
label variable awfactw  "NA - All woman factor - wealth index"
label variable v155     "Literacy"
label variable v160     "Toilet facilities shared with other households"
label variable v161     "Type of cooking fuel"
label variable v190     "Wealth index combined"
label variable v191     "Wealth index factor score combined (5 decimals)"
label variable v190a    "Wealth index for urban/rural"
label variable v191a    "Wealth index factor score for urban/rural (5 decimals)"
label variable ml101    "Type of mosquito bed net(s) slept under last night"
label variable bidx_01  "Birth column number"
label variable bidx_02  "Birth column number"
label variable bidx_03  "Birth column number"
label variable bidx_04  "Birth column number"
label variable bidx_05  "Birth column number"
label variable bidx_06  "Birth column number"
label variable bidx_07  "Birth column number"
label variable bidx_08  "Birth column number"
label variable bidx_09  "Birth column number"
label variable bidx_10  "Birth column number"
label variable bidx_11  "Birth column number"
label variable bidx_12  "Birth column number"
label variable bidx_13  "Birth column number"
label variable bidx_14  "Birth column number"
label variable bidx_15  "Birth column number"
label variable bidx_16  "Birth column number"
label variable bidx_17  "Birth column number"
label variable bidx_18  "Birth column number"
label variable bidx_19  "Birth column number"
label variable bidx_20  "Birth column number"
label variable bord_01  "Birth order number"
label variable bord_02  "Birth order number"
label variable bord_03  "Birth order number"
label variable bord_04  "Birth order number"
label variable bord_05  "Birth order number"
label variable bord_06  "Birth order number"
label variable bord_07  "Birth order number"
label variable bord_08  "Birth order number"
label variable bord_09  "Birth order number"
label variable bord_10  "Birth order number"
label variable bord_11  "Birth order number"
label variable bord_12  "Birth order number"
label variable bord_13  "Birth order number"
label variable bord_14  "Birth order number"
label variable bord_15  "Birth order number"
label variable bord_16  "Birth order number"
label variable bord_17  "Birth order number"
label variable bord_18  "Birth order number"
label variable bord_19  "Birth order number"
label variable bord_20  "Birth order number"
label variable b0_01    "Child is twin"
label variable b0_02    "Child is twin"
label variable b0_03    "Child is twin"
label variable b0_04    "Child is twin"
label variable b0_05    "Child is twin"
label variable b0_06    "Child is twin"
label variable b0_07    "Child is twin"
label variable b0_08    "Child is twin"
label variable b0_09    "Child is twin"
label variable b0_10    "Child is twin"
label variable b0_11    "Child is twin"
label variable b0_12    "Child is twin"
label variable b0_13    "Child is twin"
label variable b0_14    "Child is twin"
label variable b0_15    "Child is twin"
label variable b0_16    "Child is twin"
label variable b0_17    "Child is twin"
label variable b0_18    "Child is twin"
label variable b0_19    "Child is twin"
label variable b0_20    "Child is twin"
label variable b1_01    "Month of birth"
label variable b1_02    "Month of birth"
label variable b1_03    "Month of birth"
label variable b1_04    "Month of birth"
label variable b1_05    "Month of birth"
label variable b1_06    "Month of birth"
label variable b1_07    "Month of birth"
label variable b1_08    "Month of birth"
label variable b1_09    "Month of birth"
label variable b1_10    "Month of birth"
label variable b1_11    "Month of birth"
label variable b1_12    "Month of birth"
label variable b1_13    "Month of birth"
label variable b1_14    "Month of birth"
label variable b1_15    "Month of birth"
label variable b1_16    "Month of birth"
label variable b1_17    "Month of birth"
label variable b1_18    "Month of birth"
label variable b1_19    "Month of birth"
label variable b1_20    "Month of birth"
label variable b2_01    "Year of birth"
label variable b2_02    "Year of birth"
label variable b2_03    "Year of birth"
label variable b2_04    "Year of birth"
label variable b2_05    "Year of birth"
label variable b2_06    "Year of birth"
label variable b2_07    "Year of birth"
label variable b2_08    "Year of birth"
label variable b2_09    "Year of birth"
label variable b2_10    "Year of birth"
label variable b2_11    "Year of birth"
label variable b2_12    "Year of birth"
label variable b2_13    "Year of birth"
label variable b2_14    "Year of birth"
label variable b2_15    "Year of birth"
label variable b2_16    "Year of birth"
label variable b2_17    "Year of birth"
label variable b2_18    "Year of birth"
label variable b2_19    "Year of birth"
label variable b2_20    "Year of birth"
label variable b3_01    "Date of birth (CMC)"
label variable b3_02    "Date of birth (CMC)"
label variable b3_03    "Date of birth (CMC)"
label variable b3_04    "Date of birth (CMC)"
label variable b3_05    "Date of birth (CMC)"
label variable b3_06    "Date of birth (CMC)"
label variable b3_07    "Date of birth (CMC)"
label variable b3_08    "Date of birth (CMC)"
label variable b3_09    "Date of birth (CMC)"
label variable b3_10    "Date of birth (CMC)"
label variable b3_11    "Date of birth (CMC)"
label variable b3_12    "Date of birth (CMC)"
label variable b3_13    "Date of birth (CMC)"
label variable b3_14    "Date of birth (CMC)"
label variable b3_15    "Date of birth (CMC)"
label variable b3_16    "Date of birth (CMC)"
label variable b3_17    "Date of birth (CMC)"
label variable b3_18    "Date of birth (CMC)"
label variable b3_19    "Date of birth (CMC)"
label variable b3_20    "Date of birth (CMC)"
label variable b4_01    "Sex of child"
label variable b4_02    "Sex of child"
label variable b4_03    "Sex of child"
label variable b4_04    "Sex of child"
label variable b4_05    "Sex of child"
label variable b4_06    "Sex of child"
label variable b4_07    "Sex of child"
label variable b4_08    "Sex of child"
label variable b4_09    "Sex of child"
label variable b4_10    "Sex of child"
label variable b4_11    "Sex of child"
label variable b4_12    "Sex of child"
label variable b4_13    "Sex of child"
label variable b4_14    "Sex of child"
label variable b4_15    "Sex of child"
label variable b4_16    "Sex of child"
label variable b4_17    "Sex of child"
label variable b4_18    "Sex of child"
label variable b4_19    "Sex of child"
label variable b4_20    "Sex of child"
label variable b5_01    "Child is alive"
label variable b5_02    "Child is alive"
label variable b5_03    "Child is alive"
label variable b5_04    "Child is alive"
label variable b5_05    "Child is alive"
label variable b5_06    "Child is alive"
label variable b5_07    "Child is alive"
label variable b5_08    "Child is alive"
label variable b5_09    "Child is alive"
label variable b5_10    "Child is alive"
label variable b5_11    "Child is alive"
label variable b5_12    "Child is alive"
label variable b5_13    "Child is alive"
label variable b5_14    "Child is alive"
label variable b5_15    "Child is alive"
label variable b5_16    "Child is alive"
label variable b5_17    "Child is alive"
label variable b5_18    "Child is alive"
label variable b5_19    "Child is alive"
label variable b5_20    "Child is alive"
label variable b8_01    "Current age of child"
label variable b8_02    "Current age of child"
label variable b8_03    "Current age of child"
label variable b8_04    "Current age of child"
label variable b8_05    "Current age of child"
label variable b8_06    "Current age of child"
label variable b8_07    "Current age of child"
label variable b8_08    "Current age of child"
label variable b8_09    "Current age of child"
label variable b8_10    "Current age of child"
label variable b8_11    "Current age of child"
label variable b8_12    "Current age of child"
label variable b8_13    "Current age of child"
label variable b8_14    "Current age of child"
label variable b8_15    "Current age of child"
label variable b8_16    "Current age of child"
label variable b8_17    "Current age of child"
label variable b8_18    "Current age of child"
label variable b8_19    "Current age of child"
label variable b8_20    "Current age of child"
label variable b9_01    "Child lives with whom"
label variable b9_02    "Child lives with whom"
label variable b9_03    "Child lives with whom"
label variable b9_04    "Child lives with whom"
label variable b9_05    "Child lives with whom"
label variable b9_06    "Child lives with whom"
label variable b9_07    "Child lives with whom"
label variable b9_08    "Child lives with whom"
label variable b9_09    "Child lives with whom"
label variable b9_10    "Child lives with whom"
label variable b9_11    "Child lives with whom"
label variable b9_12    "Child lives with whom"
label variable b9_13    "Child lives with whom"
label variable b9_14    "Child lives with whom"
label variable b9_15    "Child lives with whom"
label variable b9_16    "Child lives with whom"
label variable b9_17    "Child lives with whom"
label variable b9_18    "Child lives with whom"
label variable b9_19    "Child lives with whom"
label variable b9_20    "Child lives with whom"
label variable b10_01   "Completeness of information"
label variable b10_02   "Completeness of information"
label variable b10_03   "Completeness of information"
label variable b10_04   "Completeness of information"
label variable b10_05   "Completeness of information"
label variable b10_06   "Completeness of information"
label variable b10_07   "Completeness of information"
label variable b10_08   "Completeness of information"
label variable b10_09   "Completeness of information"
label variable b10_10   "Completeness of information"
label variable b10_11   "Completeness of information"
label variable b10_12   "Completeness of information"
label variable b10_13   "Completeness of information"
label variable b10_14   "Completeness of information"
label variable b10_15   "Completeness of information"
label variable b10_16   "Completeness of information"
label variable b10_17   "Completeness of information"
label variable b10_18   "Completeness of information"
label variable b10_19   "Completeness of information"
label variable b10_20   "Completeness of information"
label variable b11_01   "Preceding birth interval (months)"
label variable b11_02   "Preceding birth interval (months)"
label variable b11_03   "Preceding birth interval (months)"
label variable b11_04   "Preceding birth interval (months)"
label variable b11_05   "Preceding birth interval (months)"
label variable b11_06   "Preceding birth interval (months)"
label variable b11_07   "Preceding birth interval (months)"
label variable b11_08   "Preceding birth interval (months)"
label variable b11_09   "Preceding birth interval (months)"
label variable b11_10   "Preceding birth interval (months)"
label variable b11_11   "Preceding birth interval (months)"
label variable b11_12   "Preceding birth interval (months)"
label variable b11_13   "Preceding birth interval (months)"
label variable b11_14   "Preceding birth interval (months)"
label variable b11_15   "Preceding birth interval (months)"
label variable b11_16   "Preceding birth interval (months)"
label variable b11_17   "Preceding birth interval (months)"
label variable b11_18   "Preceding birth interval (months)"
label variable b11_19   "Preceding birth interval (months)"
label variable b11_20   "Preceding birth interval (months)"
label variable b12_01   "Succeeding birth interval (months)"
label variable b12_02   "Succeeding birth interval (months)"
label variable b12_03   "Succeeding birth interval (months)"
label variable b12_04   "Succeeding birth interval (months)"
label variable b12_05   "Succeeding birth interval (months)"
label variable b12_06   "Succeeding birth interval (months)"
label variable b12_07   "Succeeding birth interval (months)"
label variable b12_08   "Succeeding birth interval (months)"
label variable b12_09   "Succeeding birth interval (months)"
label variable b12_10   "Succeeding birth interval (months)"
label variable b12_11   "Succeeding birth interval (months)"
label variable b12_12   "Succeeding birth interval (months)"
label variable b12_13   "Succeeding birth interval (months)"
label variable b12_14   "Succeeding birth interval (months)"
label variable b12_15   "Succeeding birth interval (months)"
label variable b12_16   "Succeeding birth interval (months)"
label variable b12_17   "Succeeding birth interval (months)"
label variable b12_18   "Succeeding birth interval (months)"
label variable b12_19   "Succeeding birth interval (months)"
label variable b12_20   "Succeeding birth interval (months)"
label variable b15_01   "Live birth between births"
label variable b15_02   "Live birth between births"
label variable b15_03   "Live birth between births"
label variable b15_04   "Live birth between births"
label variable b15_05   "Live birth between births"
label variable b15_06   "Live birth between births"
label variable b15_07   "Live birth between births"
label variable b15_08   "Live birth between births"
label variable b15_09   "Live birth between births"
label variable b15_10   "Live birth between births"
label variable b15_11   "Live birth between births"
label variable b15_12   "Live birth between births"
label variable b15_13   "Live birth between births"
label variable b15_14   "Live birth between births"
label variable b15_15   "Live birth between births"
label variable b15_16   "Live birth between births"
label variable b15_17   "Live birth between births"
label variable b15_18   "Live birth between births"
label variable b15_19   "Live birth between births"
label variable b15_20   "Live birth between births"
label variable b16_01   "Child's line number in household"
label variable b16_02   "Child's line number in household"
label variable b16_03   "Child's line number in household"
label variable b16_04   "Child's line number in household"
label variable b16_05   "Child's line number in household"
label variable b16_06   "Child's line number in household"
label variable b16_07   "Child's line number in household"
label variable b16_08   "Child's line number in household"
label variable b16_09   "Child's line number in household"
label variable b16_10   "Child's line number in household"
label variable b16_11   "Child's line number in household"
label variable b16_12   "Child's line number in household"
label variable b16_13   "Child's line number in household"
label variable b16_14   "Child's line number in household"
label variable b16_15   "Child's line number in household"
label variable b16_16   "Child's line number in household"
label variable b16_17   "Child's line number in household"
label variable b16_18   "Child's line number in household"
label variable b16_19   "Child's line number in household"
label variable b16_20   "Child's line number in household"
label variable b17_01   "Day of birth"
label variable b17_02   "Day of birth"
label variable b17_03   "Day of birth"
label variable b17_04   "Day of birth"
label variable b17_05   "Day of birth"
label variable b17_06   "Day of birth"
label variable b17_07   "Day of birth"
label variable b17_08   "Day of birth"
label variable b17_09   "Day of birth"
label variable b17_10   "Day of birth"
label variable b17_11   "Day of birth"
label variable b17_12   "Day of birth"
label variable b17_13   "Day of birth"
label variable b17_14   "Day of birth"
label variable b17_15   "Day of birth"
label variable b17_16   "Day of birth"
label variable b17_17   "Day of birth"
label variable b17_18   "Day of birth"
label variable b17_19   "Day of birth"
label variable b17_20   "Day of birth"
label variable b18_01   "Century Day Code of birth (CDC)"
label variable b18_02   "Century Day Code of birth (CDC)"
label variable b18_03   "Century Day Code of birth (CDC)"
label variable b18_04   "Century Day Code of birth (CDC)"
label variable b18_05   "Century Day Code of birth (CDC)"
label variable b18_06   "Century Day Code of birth (CDC)"
label variable b18_07   "Century Day Code of birth (CDC)"
label variable b18_08   "Century Day Code of birth (CDC)"
label variable b18_09   "Century Day Code of birth (CDC)"
label variable b18_10   "Century Day Code of birth (CDC)"
label variable b18_11   "Century Day Code of birth (CDC)"
label variable b18_12   "Century Day Code of birth (CDC)"
label variable b18_13   "Century Day Code of birth (CDC)"
label variable b18_14   "Century Day Code of birth (CDC)"
label variable b18_15   "Century Day Code of birth (CDC)"
label variable b18_16   "Century Day Code of birth (CDC)"
label variable b18_17   "Century Day Code of birth (CDC)"
label variable b18_18   "Century Day Code of birth (CDC)"
label variable b18_19   "Century Day Code of birth (CDC)"
label variable b18_20   "Century Day Code of birth (CDC)"
label variable b19_01   "Current age of child in months (months since birth for dead children)"
label variable b19_02   "Current age of child in months (months since birth for dead children)"
label variable b19_03   "Current age of child in months (months since birth for dead children)"
label variable b19_04   "Current age of child in months (months since birth for dead children)"
label variable b19_05   "Current age of child in months (months since birth for dead children)"
label variable b19_06   "Current age of child in months (months since birth for dead children)"
label variable b19_07   "Current age of child in months (months since birth for dead children)"
label variable b19_08   "Current age of child in months (months since birth for dead children)"
label variable b19_09   "Current age of child in months (months since birth for dead children)"
label variable b19_10   "Current age of child in months (months since birth for dead children)"
label variable b19_11   "Current age of child in months (months since birth for dead children)"
label variable b19_12   "Current age of child in months (months since birth for dead children)"
label variable b19_13   "Current age of child in months (months since birth for dead children)"
label variable b19_14   "Current age of child in months (months since birth for dead children)"
label variable b19_15   "Current age of child in months (months since birth for dead children)"
label variable b19_16   "Current age of child in months (months since birth for dead children)"
label variable b19_17   "Current age of child in months (months since birth for dead children)"
label variable b19_18   "Current age of child in months (months since birth for dead children)"
label variable b19_19   "Current age of child in months (months since birth for dead children)"
label variable b19_20   "Current age of child in months (months since birth for dead children)"
label variable v201     "Total children ever born"
label variable v202     "Sons at home"
label variable v203     "Daughters at home"
label variable v204     "Sons elsewhere"
label variable v205     "Daughters elsewhere"
label variable v206     "Sons who have died"
label variable v207     "Daughters who have died"
label variable v208     "Births in last five years"
label variable v209     "Births in past year"
label variable v210     "Births in month of interview"
label variable v213     "Currently pregnant"
label variable v214     "Duration of current pregnancy"
label variable v218     "Number of living children"
label variable v219     "Living children + current pregnancy"
label variable v220     "Living children + current pregnancy (grouped)"
label variable v222     "Last birth to interview (months)"
label variable v223     "Completeness of current pregnancy information"
label variable v224     "Entries in birth history"
label variable v237     "Birth between last and interview"
label variable v238     "Births in last three years"
label variable midx_1   "Index to Birth History"
label variable midx_2   "Index to Birth History"
label variable midx_3   "Index to Birth History"
label variable midx_4   "Index to Birth History"
label variable midx_5   "Index to Birth History"
label variable midx_6   "Index to Birth History"
label variable m2a_1    "Prenatal: doctor"
label variable m2a_2    "Prenatal: doctor"
label variable m2a_3    "Prenatal: doctor"
label variable m2a_4    "Prenatal: doctor"
label variable m2a_5    "Prenatal: doctor"
label variable m2a_6    "Prenatal: doctor"
label variable m2b_1    "Prenatal: nurse/midwife"
label variable m2b_2    "Prenatal: nurse/midwife"
label variable m2b_3    "Prenatal: nurse/midwife"
label variable m2b_4    "Prenatal: nurse/midwife"
label variable m2b_5    "Prenatal: nurse/midwife"
label variable m2b_6    "Prenatal: nurse/midwife"
label variable m2c_1    "Prenatal: community health officer/nurse"
label variable m2c_2    "Prenatal: community health officer/nurse"
label variable m2c_3    "Prenatal: community health officer/nurse"
label variable m2c_4    "Prenatal: community health officer/nurse"
label variable m2c_5    "Prenatal: community health officer/nurse"
label variable m2c_6    "Prenatal: community health officer/nurse"
label variable m2d_1    "NA - Prenatal: CS health professional"
label variable m2d_2    "NA - Prenatal: CS health professional"
label variable m2d_3    "NA - Prenatal: CS health professional"
label variable m2d_4    "NA - Prenatal: CS health professional"
label variable m2d_5    "NA - Prenatal: CS health professional"
label variable m2d_6    "NA - Prenatal: CS health professional"
label variable m2e_1    "NA - Prenatal: CS health professional"
label variable m2e_2    "NA - Prenatal: CS health professional"
label variable m2e_3    "NA - Prenatal: CS health professional"
label variable m2e_4    "NA - Prenatal: CS health professional"
label variable m2e_5    "NA - Prenatal: CS health professional"
label variable m2e_6    "NA - Prenatal: CS health professional"
label variable m2f_1    "NA - Prenatal: CS health professional"
label variable m2f_2    "NA - Prenatal: CS health professional"
label variable m2f_3    "NA - Prenatal: CS health professional"
label variable m2f_4    "NA - Prenatal: CS health professional"
label variable m2f_5    "NA - Prenatal: CS health professional"
label variable m2f_6    "NA - Prenatal: CS health professional"
label variable m2g_1    "Prenatal: traditional birth attendant"
label variable m2g_2    "Prenatal: traditional birth attendant"
label variable m2g_3    "Prenatal: traditional birth attendant"
label variable m2g_4    "Prenatal: traditional birth attendant"
label variable m2g_5    "Prenatal: traditional birth attendant"
label variable m2g_6    "Prenatal: traditional birth attendant"
label variable m2h_1    "Prenatal: community/village health worker"
label variable m2h_2    "Prenatal: community/village health worker"
label variable m2h_3    "Prenatal: community/village health worker"
label variable m2h_4    "Prenatal: community/village health worker"
label variable m2h_5    "Prenatal: community/village health worker"
label variable m2h_6    "Prenatal: community/village health worker"
label variable m2i_1    "Prenatal: traditional health practitioner"
label variable m2i_2    "Prenatal: traditional health practitioner"
label variable m2i_3    "Prenatal: traditional health practitioner"
label variable m2i_4    "Prenatal: traditional health practitioner"
label variable m2i_5    "Prenatal: traditional health practitioner"
label variable m2i_6    "Prenatal: traditional health practitioner"
label variable m2j_1    "NA - Prenatal: CS other person"
label variable m2j_2    "NA - Prenatal: CS other person"
label variable m2j_3    "NA - Prenatal: CS other person"
label variable m2j_4    "NA - Prenatal: CS other person"
label variable m2j_5    "NA - Prenatal: CS other person"
label variable m2j_6    "NA - Prenatal: CS other person"
label variable m2k_1    "Prenatal: other"
label variable m2k_2    "Prenatal: other"
label variable m2k_3    "Prenatal: other"
label variable m2k_4    "Prenatal: other"
label variable m2k_5    "Prenatal: other"
label variable m2k_6    "Prenatal: other"
label variable m2l_1    "NA - Prenatal: CS other"
label variable m2l_2    "NA - Prenatal: CS other"
label variable m2l_3    "NA - Prenatal: CS other"
label variable m2l_4    "NA - Prenatal: CS other"
label variable m2l_5    "NA - Prenatal: CS other"
label variable m2l_6    "NA - Prenatal: CS other"
label variable m2m_1    "NA - Prenatal: CS other"
label variable m2m_2    "NA - Prenatal: CS other"
label variable m2m_3    "NA - Prenatal: CS other"
label variable m2m_4    "NA - Prenatal: CS other"
label variable m2m_5    "NA - Prenatal: CS other"
label variable m2m_6    "NA - Prenatal: CS other"
label variable m2n_1    "Prenatal: no one"
label variable m2n_2    "Prenatal: no one"
label variable m2n_3    "Prenatal: no one"
label variable m2n_4    "Prenatal: no one"
label variable m2n_5    "Prenatal: no one"
label variable m2n_6    "Prenatal: no one"
label variable m13_1    "Timing of 1st antenatal check (months)"
label variable m13_2    "Timing of 1st antenatal check (months)"
label variable m13_3    "Timing of 1st antenatal check (months)"
label variable m13_4    "Timing of 1st antenatal check (months)"
label variable m13_5    "Timing of 1st antenatal check (months)"
label variable m13_6    "Timing of 1st antenatal check (months)"
label variable m14_1    "Number of antenatal visits during pregnancy"
label variable m14_2    "Number of antenatal visits during pregnancy"
label variable m14_3    "Number of antenatal visits during pregnancy"
label variable m14_4    "Number of antenatal visits during pregnancy"
label variable m14_5    "Number of antenatal visits during pregnancy"
label variable m14_6    "Number of antenatal visits during pregnancy"
label variable m49a_1   "During pregnancy took: SP/fansidar for malaria"
label variable m49a_2   "During pregnancy took: SP/fansidar for malaria"
label variable m49a_3   "During pregnancy took: SP/fansidar for malaria"
label variable m49a_4   "During pregnancy took: SP/fansidar for malaria"
label variable m49a_5   "During pregnancy took: SP/fansidar for malaria"
label variable m49a_6   "During pregnancy took: SP/fansidar for malaria"
label variable m49b_1   "NA - During pregnancy took: chloroquine for malaria"
label variable m49b_2   "NA - During pregnancy took: chloroquine for malaria"
label variable m49b_3   "NA - During pregnancy took: chloroquine for malaria"
label variable m49b_4   "NA - During pregnancy took: chloroquine for malaria"
label variable m49b_5   "NA - During pregnancy took: chloroquine for malaria"
label variable m49b_6   "NA - During pregnancy took: chloroquine for malaria"
label variable m49c_1   "NA - During pregnancy took: CS drug for malaria"
label variable m49c_2   "NA - During pregnancy took: CS drug for malaria"
label variable m49c_3   "NA - During pregnancy took: CS drug for malaria"
label variable m49c_4   "NA - During pregnancy took: CS drug for malaria"
label variable m49c_5   "NA - During pregnancy took: CS drug for malaria"
label variable m49c_6   "NA - During pregnancy took: CS drug for malaria"
label variable m49d_1   "NA - During pregnancy took: CS drug for malaria"
label variable m49d_2   "NA - During pregnancy took: CS drug for malaria"
label variable m49d_3   "NA - During pregnancy took: CS drug for malaria"
label variable m49d_4   "NA - During pregnancy took: CS drug for malaria"
label variable m49d_5   "NA - During pregnancy took: CS drug for malaria"
label variable m49d_6   "NA - During pregnancy took: CS drug for malaria"
label variable m49e_1   "NA - During pregnancy took: CS drug for malaria"
label variable m49e_2   "NA - During pregnancy took: CS drug for malaria"
label variable m49e_3   "NA - During pregnancy took: CS drug for malaria"
label variable m49e_4   "NA - During pregnancy took: CS drug for malaria"
label variable m49e_5   "NA - During pregnancy took: CS drug for malaria"
label variable m49e_6   "NA - During pregnancy took: CS drug for malaria"
label variable m49f_1   "NA - During pregnancy took: CS drug for malaria"
label variable m49f_2   "NA - During pregnancy took: CS drug for malaria"
label variable m49f_3   "NA - During pregnancy took: CS drug for malaria"
label variable m49f_4   "NA - During pregnancy took: CS drug for malaria"
label variable m49f_5   "NA - During pregnancy took: CS drug for malaria"
label variable m49f_6   "NA - During pregnancy took: CS drug for malaria"
label variable m49g_1   "NA - During pregnancy took: CS drug for malaria"
label variable m49g_2   "NA - During pregnancy took: CS drug for malaria"
label variable m49g_3   "NA - During pregnancy took: CS drug for malaria"
label variable m49g_4   "NA - During pregnancy took: CS drug for malaria"
label variable m49g_5   "NA - During pregnancy took: CS drug for malaria"
label variable m49g_6   "NA - During pregnancy took: CS drug for malaria"
label variable m49x_1   "NA - During pregnancy took: other drug for malaria"
label variable m49x_2   "NA - During pregnancy took: other drug for malaria"
label variable m49x_3   "NA - During pregnancy took: other drug for malaria"
label variable m49x_4   "NA - During pregnancy took: other drug for malaria"
label variable m49x_5   "NA - During pregnancy took: other drug for malaria"
label variable m49x_6   "NA - During pregnancy took: other drug for malaria"
label variable m49z_1   "NA - During pregnancy took: don't know"
label variable m49z_2   "NA - During pregnancy took: don't know"
label variable m49z_3   "NA - During pregnancy took: don't know"
label variable m49z_4   "NA - During pregnancy took: don't know"
label variable m49z_5   "NA - During pregnancy took: don't know"
label variable m49z_6   "NA - During pregnancy took: don't know"
label variable m49y_1   "NA - During pregnancy took: no drug for malaria"
label variable m49y_2   "NA - During pregnancy took: no drug for malaria"
label variable m49y_3   "NA - During pregnancy took: no drug for malaria"
label variable m49y_4   "NA - During pregnancy took: no drug for malaria"
label variable m49y_5   "NA - During pregnancy took: no drug for malaria"
label variable m49y_6   "NA - During pregnancy took: no drug for malaria"
label variable m57a_1   "Antenatal care: respondent's home"
label variable m57a_2   "Antenatal care: respondent's home"
label variable m57a_3   "Antenatal care: respondent's home"
label variable m57a_4   "Antenatal care: respondent's home"
label variable m57a_5   "Antenatal care: respondent's home"
label variable m57a_6   "Antenatal care: respondent's home"
label variable m57b_1   "Antenatal care: other home"
label variable m57b_2   "Antenatal care: other home"
label variable m57b_3   "Antenatal care: other home"
label variable m57b_4   "Antenatal care: other home"
label variable m57b_5   "Antenatal care: other home"
label variable m57b_6   "Antenatal care: other home"
label variable m57c_1   "NA - Antenatal care: CS home"
label variable m57c_2   "NA - Antenatal care: CS home"
label variable m57c_3   "NA - Antenatal care: CS home"
label variable m57c_4   "NA - Antenatal care: CS home"
label variable m57c_5   "NA - Antenatal care: CS home"
label variable m57c_6   "NA - Antenatal care: CS home"
label variable m57d_1   "NA - Antenatal care: CS home"
label variable m57d_2   "NA - Antenatal care: CS home"
label variable m57d_3   "NA - Antenatal care: CS home"
label variable m57d_4   "NA - Antenatal care: CS home"
label variable m57d_5   "NA - Antenatal care: CS home"
label variable m57d_6   "NA - Antenatal care: CS home"
label variable m57e_1   "Antenatal care: government hospital"
label variable m57e_2   "Antenatal care: government hospital"
label variable m57e_3   "Antenatal care: government hospital"
label variable m57e_4   "Antenatal care: government hospital"
label variable m57e_5   "Antenatal care: government hospital"
label variable m57e_6   "Antenatal care: government hospital"
label variable m57f_1   "Antenatal care: government health center"
label variable m57f_2   "Antenatal care: government health center"
label variable m57f_3   "Antenatal care: government health center"
label variable m57f_4   "Antenatal care: government health center"
label variable m57f_5   "Antenatal care: government health center"
label variable m57f_6   "Antenatal care: government health center"
label variable m57g_1   "Antenatal care: government health post"
label variable m57g_2   "Antenatal care: government health post"
label variable m57g_3   "Antenatal care: government health post"
label variable m57g_4   "Antenatal care: government health post"
label variable m57g_5   "Antenatal care: government health post"
label variable m57g_6   "Antenatal care: government health post"
label variable m57h_1   "Antenatal care: other public sector"
label variable m57h_2   "Antenatal care: other public sector"
label variable m57h_3   "Antenatal care: other public sector"
label variable m57h_4   "Antenatal care: other public sector"
label variable m57h_5   "Antenatal care: other public sector"
label variable m57h_6   "Antenatal care: other public sector"
label variable m57i_1   "NA - Antenatal care: CS public health"
label variable m57i_2   "NA - Antenatal care: CS public health"
label variable m57i_3   "NA - Antenatal care: CS public health"
label variable m57i_4   "NA - Antenatal care: CS public health"
label variable m57i_5   "NA - Antenatal care: CS public health"
label variable m57i_6   "NA - Antenatal care: CS public health"
label variable m57j_1   "NA - Antenatal care: CS public health"
label variable m57j_2   "NA - Antenatal care: CS public health"
label variable m57j_3   "NA - Antenatal care: CS public health"
label variable m57j_4   "NA - Antenatal care: CS public health"
label variable m57j_5   "NA - Antenatal care: CS public health"
label variable m57j_6   "NA - Antenatal care: CS public health"
label variable m57k_1   "NA - Antenatal care: CS public health"
label variable m57k_2   "NA - Antenatal care: CS public health"
label variable m57k_3   "NA - Antenatal care: CS public health"
label variable m57k_4   "NA - Antenatal care: CS public health"
label variable m57k_5   "NA - Antenatal care: CS public health"
label variable m57k_6   "NA - Antenatal care: CS public health"
label variable m57l_1   "NA - Antenatal care: CS public health"
label variable m57l_2   "NA - Antenatal care: CS public health"
label variable m57l_3   "NA - Antenatal care: CS public health"
label variable m57l_4   "NA - Antenatal care: CS public health"
label variable m57l_5   "NA - Antenatal care: CS public health"
label variable m57l_6   "NA - Antenatal care: CS public health"
label variable m57m_1   "Antenatal care: private hospital/clinic"
label variable m57m_2   "Antenatal care: private hospital/clinic"
label variable m57m_3   "Antenatal care: private hospital/clinic"
label variable m57m_4   "Antenatal care: private hospital/clinic"
label variable m57m_5   "Antenatal care: private hospital/clinic"
label variable m57m_6   "Antenatal care: private hospital/clinic"
label variable m57n_1   "Antenatal care: other private medical sector"
label variable m57n_2   "Antenatal care: other private medical sector"
label variable m57n_3   "Antenatal care: other private medical sector"
label variable m57n_4   "Antenatal care: other private medical sector"
label variable m57n_5   "Antenatal care: other private medical sector"
label variable m57n_6   "Antenatal care: other private medical sector"
label variable m57o_1   "NA - Antenatal care: CS private medical"
label variable m57o_2   "NA - Antenatal care: CS private medical"
label variable m57o_3   "NA - Antenatal care: CS private medical"
label variable m57o_4   "NA - Antenatal care: CS private medical"
label variable m57o_5   "NA - Antenatal care: CS private medical"
label variable m57o_6   "NA - Antenatal care: CS private medical"
label variable m57p_1   "NA - Antenatal care: CS private medical"
label variable m57p_2   "NA - Antenatal care: CS private medical"
label variable m57p_3   "NA - Antenatal care: CS private medical"
label variable m57p_4   "NA - Antenatal care: CS private medical"
label variable m57p_5   "NA - Antenatal care: CS private medical"
label variable m57p_6   "NA - Antenatal care: CS private medical"
label variable m57q_1   "NA - Antenatal care: CS private medical"
label variable m57q_2   "NA - Antenatal care: CS private medical"
label variable m57q_3   "NA - Antenatal care: CS private medical"
label variable m57q_4   "NA - Antenatal care: CS private medical"
label variable m57q_5   "NA - Antenatal care: CS private medical"
label variable m57q_6   "NA - Antenatal care: CS private medical"
label variable m57r_1   "NA - Antenatal care: CS private medical"
label variable m57r_2   "NA - Antenatal care: CS private medical"
label variable m57r_3   "NA - Antenatal care: CS private medical"
label variable m57r_4   "NA - Antenatal care: CS private medical"
label variable m57r_5   "NA - Antenatal care: CS private medical"
label variable m57r_6   "NA - Antenatal care: CS private medical"
label variable m57s_1   "NA - Antenatal care: CS other"
label variable m57s_2   "NA - Antenatal care: CS other"
label variable m57s_3   "NA - Antenatal care: CS other"
label variable m57s_4   "NA - Antenatal care: CS other"
label variable m57s_5   "NA - Antenatal care: CS other"
label variable m57s_6   "NA - Antenatal care: CS other"
label variable m57t_1   "NA - Antenatal care: CS other"
label variable m57t_2   "NA - Antenatal care: CS other"
label variable m57t_3   "NA - Antenatal care: CS other"
label variable m57t_4   "NA - Antenatal care: CS other"
label variable m57t_5   "NA - Antenatal care: CS other"
label variable m57t_6   "NA - Antenatal care: CS other"
label variable m57u_1   "NA - Antenatal care: CS other"
label variable m57u_2   "NA - Antenatal care: CS other"
label variable m57u_3   "NA - Antenatal care: CS other"
label variable m57u_4   "NA - Antenatal care: CS other"
label variable m57u_5   "NA - Antenatal care: CS other"
label variable m57u_6   "NA - Antenatal care: CS other"
label variable m57v_1   "NA - Antenatal care: CS other"
label variable m57v_2   "NA - Antenatal care: CS other"
label variable m57v_3   "NA - Antenatal care: CS other"
label variable m57v_4   "NA - Antenatal care: CS other"
label variable m57v_5   "NA - Antenatal care: CS other"
label variable m57v_6   "NA - Antenatal care: CS other"
label variable m57x_1   "Antenatal care: other"
label variable m57x_2   "Antenatal care: other"
label variable m57x_3   "Antenatal care: other"
label variable m57x_4   "Antenatal care: other"
label variable m57x_5   "Antenatal care: other"
label variable m57x_6   "Antenatal care: other"
label variable v417     "Entries in pregnancy and postnatal care roster"
label variable v418a    "Entries in child health roster"
label variable v419     "Entries in height/weight roster"
label variable v459     "Have mosquito bed net for sleeping (from household questionnaire)"
label variable v460     "Children under 5 slept under mosquito bed net last night (household questionnair"
label variable v461     "Respondent slept under mosquito bed net"
label variable v468     "Record for Last Birth"
label variable v481     "Covered by health insurance"
label variable v481a    "Health insurance type: mutual/community organization"
label variable v481b    "Health insurance type: provided by employer"
label variable v481c    "Health insurance type: social security - national/district health insurance (NHI"
label variable v481d    "Health insurance type: private/commercially purchased"
label variable v481e    "NA - Health insurance type: CS"
label variable v481f    "NA - Health insurance type: CS"
label variable v481g    "NA - Health insurance type: CS"
label variable v481h    "NA - Health insurance type: CS"
label variable v481x    "Health insurance type: other"
label variable hidxa_1  "Index to birth history"
label variable hidxa_2  "Index to birth history"
label variable hidxa_3  "Index to birth history"
label variable hidxa_4  "Index to birth history"
label variable hidxa_5  "Index to birth history"
label variable hidxa_6  "Index to birth history"
label variable h22_1    "Had fever in last two weeks"
label variable h22_2    "Had fever in last two weeks"
label variable h22_3    "Had fever in last two weeks"
label variable h22_4    "Had fever in last two weeks"
label variable h22_5    "Had fever in last two weeks"
label variable h22_6    "Had fever in last two weeks"
label variable h32a_1   "Fever/cough: govt hospital"
label variable h32a_2   "Fever/cough: govt hospital"
label variable h32a_3   "Fever/cough: govt hospital"
label variable h32a_4   "Fever/cough: govt hospital"
label variable h32a_5   "Fever/cough: govt hospital"
label variable h32a_6   "Fever/cough: govt hospital"
label variable h32b_1   "Fever/cough: govt health center"
label variable h32b_2   "Fever/cough: govt health center"
label variable h32b_3   "Fever/cough: govt health center"
label variable h32b_4   "Fever/cough: govt health center"
label variable h32b_5   "Fever/cough: govt health center"
label variable h32b_6   "Fever/cough: govt health center"
label variable h32c_1   "Fever/cough: govt health post/CHPS"
label variable h32c_2   "Fever/cough: govt health post/CHPS"
label variable h32c_3   "Fever/cough: govt health post/CHPS"
label variable h32c_4   "Fever/cough: govt health post/CHPS"
label variable h32c_5   "Fever/cough: govt health post/CHPS"
label variable h32c_6   "Fever/cough: govt health post/CHPS"
label variable h32d_1   "Fever/cough: public mobile clinic"
label variable h32d_2   "Fever/cough: public mobile clinic"
label variable h32d_3   "Fever/cough: public mobile clinic"
label variable h32d_4   "Fever/cough: public mobile clinic"
label variable h32d_5   "Fever/cough: public mobile clinic"
label variable h32d_6   "Fever/cough: public mobile clinic"
label variable h32e_1   "Fever/cough: public fieldworker/CHW"
label variable h32e_2   "Fever/cough: public fieldworker/CHW"
label variable h32e_3   "Fever/cough: public fieldworker/CHW"
label variable h32e_4   "Fever/cough: public fieldworker/CHW"
label variable h32e_5   "Fever/cough: public fieldworker/CHW"
label variable h32e_6   "Fever/cough: public fieldworker/CHW"
label variable h32f_1   "Fever/cough: other public sector"
label variable h32f_2   "Fever/cough: other public sector"
label variable h32f_3   "Fever/cough: other public sector"
label variable h32f_4   "Fever/cough: other public sector"
label variable h32f_5   "Fever/cough: other public sector"
label variable h32f_6   "Fever/cough: other public sector"
label variable h32g_1   "NA - Fever/cough: CS public sector"
label variable h32g_2   "NA - Fever/cough: CS public sector"
label variable h32g_3   "NA - Fever/cough: CS public sector"
label variable h32g_4   "NA - Fever/cough: CS public sector"
label variable h32g_5   "NA - Fever/cough: CS public sector"
label variable h32g_6   "NA - Fever/cough: CS public sector"
label variable h32h_1   "NA - Fever/cough: CS public sector"
label variable h32h_2   "NA - Fever/cough: CS public sector"
label variable h32h_3   "NA - Fever/cough: CS public sector"
label variable h32h_4   "NA - Fever/cough: CS public sector"
label variable h32h_5   "NA - Fever/cough: CS public sector"
label variable h32h_6   "NA - Fever/cough: CS public sector"
label variable h32i_1   "NA - Fever/cough: CS public sector"
label variable h32i_2   "NA - Fever/cough: CS public sector"
label variable h32i_3   "NA - Fever/cough: CS public sector"
label variable h32i_4   "NA - Fever/cough: CS public sector"
label variable h32i_5   "NA - Fever/cough: CS public sector"
label variable h32i_6   "NA - Fever/cough: CS public sector"
label variable h32j_1   "Fever/cough: private hospital/clinic"
label variable h32j_2   "Fever/cough: private hospital/clinic"
label variable h32j_3   "Fever/cough: private hospital/clinic"
label variable h32j_4   "Fever/cough: private hospital/clinic"
label variable h32j_5   "Fever/cough: private hospital/clinic"
label variable h32j_6   "Fever/cough: private hospital/clinic"
label variable h32k_1   "Fever/cough: private pharmacy"
label variable h32k_2   "Fever/cough: private pharmacy"
label variable h32k_3   "Fever/cough: private pharmacy"
label variable h32k_4   "Fever/cough: private pharmacy"
label variable h32k_5   "Fever/cough: private pharmacy"
label variable h32k_6   "Fever/cough: private pharmacy"
label variable h32l_1   "Fever/cough: private doctor"
label variable h32l_2   "Fever/cough: private doctor"
label variable h32l_3   "Fever/cough: private doctor"
label variable h32l_4   "Fever/cough: private doctor"
label variable h32l_5   "Fever/cough: private doctor"
label variable h32l_6   "Fever/cough: private doctor"
label variable h32m_1   "Fever/cough: private chemist/drug store"
label variable h32m_2   "Fever/cough: private chemist/drug store"
label variable h32m_3   "Fever/cough: private chemist/drug store"
label variable h32m_4   "Fever/cough: private chemist/drug store"
label variable h32m_5   "Fever/cough: private chemist/drug store"
label variable h32m_6   "Fever/cough: private chemist/drug store"
label variable h32n_1   "Fever/cough: private FPG/PPAG clinic"
label variable h32n_2   "Fever/cough: private FPG/PPAG clinic"
label variable h32n_3   "Fever/cough: private FPG/PPAG clinic"
label variable h32n_4   "Fever/cough: private FPG/PPAG clinic"
label variable h32n_5   "Fever/cough: private FPG/PPAG clinic"
label variable h32n_6   "Fever/cough: private FPG/PPAG clinic"
label variable h32o_1   "Fever/cough: private mobile clinic"
label variable h32o_2   "Fever/cough: private mobile clinic"
label variable h32o_3   "Fever/cough: private mobile clinic"
label variable h32o_4   "Fever/cough: private mobile clinic"
label variable h32o_5   "Fever/cough: private mobile clinic"
label variable h32o_6   "Fever/cough: private mobile clinic"
label variable h32p_1   "Fever/cough: private fieldworker/CHW"
label variable h32p_2   "Fever/cough: private fieldworker/CHW"
label variable h32p_3   "Fever/cough: private fieldworker/CHW"
label variable h32p_4   "Fever/cough: private fieldworker/CHW"
label variable h32p_5   "Fever/cough: private fieldworker/CHW"
label variable h32p_6   "Fever/cough: private fieldworker/CHW"
label variable h32q_1   "Fever/cough: other private medical sector"
label variable h32q_2   "Fever/cough: other private medical sector"
label variable h32q_3   "Fever/cough: other private medical sector"
label variable h32q_4   "Fever/cough: other private medical sector"
label variable h32q_5   "Fever/cough: other private medical sector"
label variable h32q_6   "Fever/cough: other private medical sector"
label variable h32r_1   "NA - Fever/cough: CS private medical"
label variable h32r_2   "NA - Fever/cough: CS private medical"
label variable h32r_3   "NA - Fever/cough: CS private medical"
label variable h32r_4   "NA - Fever/cough: CS private medical"
label variable h32r_5   "NA - Fever/cough: CS private medical"
label variable h32r_6   "NA - Fever/cough: CS private medical"
label variable h32s_1   "Fever/cough: shop"
label variable h32s_2   "Fever/cough: shop"
label variable h32s_3   "Fever/cough: shop"
label variable h32s_4   "Fever/cough: shop"
label variable h32s_5   "Fever/cough: shop"
label variable h32s_6   "Fever/cough: shop"
label variable h32t_1   "Fever/cough: traditional practitioner"
label variable h32t_2   "Fever/cough: traditional practitioner"
label variable h32t_3   "Fever/cough: traditional practitioner"
label variable h32t_4   "Fever/cough: traditional practitioner"
label variable h32t_5   "Fever/cough: traditional practitioner"
label variable h32t_6   "Fever/cough: traditional practitioner"
label variable h32u_1   "Fever/cough: market"
label variable h32u_2   "Fever/cough: market"
label variable h32u_3   "Fever/cough: market"
label variable h32u_4   "Fever/cough: market"
label variable h32u_5   "Fever/cough: market"
label variable h32u_6   "Fever/cough: market"
label variable h32v_1   "Fever/cough: itinerant drug seller"
label variable h32v_2   "Fever/cough: itinerant drug seller"
label variable h32v_3   "Fever/cough: itinerant drug seller"
label variable h32v_4   "Fever/cough: itinerant drug seller"
label variable h32v_5   "Fever/cough: itinerant drug seller"
label variable h32v_6   "Fever/cough: itinerant drug seller"
label variable h32w_1   "NA - Fever/cough: CS other sector"
label variable h32w_2   "NA - Fever/cough: CS other sector"
label variable h32w_3   "NA - Fever/cough: CS other sector"
label variable h32w_4   "NA - Fever/cough: CS other sector"
label variable h32w_5   "NA - Fever/cough: CS other sector"
label variable h32w_6   "NA - Fever/cough: CS other sector"
label variable h32x_1   "Fever/cough: other"
label variable h32x_2   "Fever/cough: other"
label variable h32x_3   "Fever/cough: other"
label variable h32x_4   "Fever/cough: other"
label variable h32x_5   "Fever/cough: other"
label variable h32x_6   "Fever/cough: other"
label variable h32y_1   "Fever/cough: no treatment"
label variable h32y_2   "Fever/cough: no treatment"
label variable h32y_3   "Fever/cough: no treatment"
label variable h32y_4   "Fever/cough: no treatment"
label variable h32y_5   "Fever/cough: no treatment"
label variable h32y_6   "Fever/cough: no treatment"
label variable h32z_1   "Fever/cough: medical treatment"
label variable h32z_2   "Fever/cough: medical treatment"
label variable h32z_3   "Fever/cough: medical treatment"
label variable h32z_4   "Fever/cough: medical treatment"
label variable h32z_5   "Fever/cough: medical treatment"
label variable h32z_6   "Fever/cough: medical treatment"
label variable h46a_1   "Place first sought treatment for fever"
label variable h46a_2   "Place first sought treatment for fever"
label variable h46a_3   "Place first sought treatment for fever"
label variable h46a_4   "Place first sought treatment for fever"
label variable h46a_5   "Place first sought treatment for fever"
label variable h46a_6   "Place first sought treatment for fever"
label variable h46b_1   "Number of days after fever began sought advice or treatment"
label variable h46b_2   "Number of days after fever began sought advice or treatment"
label variable h46b_3   "Number of days after fever began sought advice or treatment"
label variable h46b_4   "Number of days after fever began sought advice or treatment"
label variable h46b_5   "Number of days after fever began sought advice or treatment"
label variable h46b_6   "Number of days after fever began sought advice or treatment"
label variable h47_1    "Blood taken from child's finger/heel for testing"
label variable h47_2    "Blood taken from child's finger/heel for testing"
label variable h47_3    "Blood taken from child's finger/heel for testing"
label variable h47_4    "Blood taken from child's finger/heel for testing"
label variable h47_5    "Blood taken from child's finger/heel for testing"
label variable h47_6    "Blood taken from child's finger/heel for testing"
label variable hwidx_1  "Index to Birth History"
label variable hwidx_2  "Index to Birth History"
label variable hwidx_3  "Index to Birth History"
label variable hwidx_4  "Index to Birth History"
label variable hwidx_5  "Index to Birth History"
label variable hwidx_6  "Index to Birth History"
label variable hw1_1    "Child's age in months"
label variable hw1_2    "Child's age in months"
label variable hw1_3    "Child's age in months"
label variable hw1_4    "Child's age in months"
label variable hw1_5    "Child's age in months"
label variable hw1_6    "Child's age in months"
label variable hw16_1   "Day of birth of child"
label variable hw16_2   "Day of birth of child"
label variable hw16_3   "Day of birth of child"
label variable hw16_4   "Day of birth of child"
label variable hw16_5   "Day of birth of child"
label variable hw16_6   "Day of birth of child"
label variable hw17_1   "Date measured (day)"
label variable hw17_2   "Date measured (day)"
label variable hw17_3   "Date measured (day)"
label variable hw17_4   "Date measured (day)"
label variable hw17_5   "Date measured (day)"
label variable hw17_6   "Date measured (day)"
label variable hw18_1   "Date measured (month)"
label variable hw18_2   "Date measured (month)"
label variable hw18_3   "Date measured (month)"
label variable hw18_4   "Date measured (month)"
label variable hw18_5   "Date measured (month)"
label variable hw18_6   "Date measured (month)"
label variable hw19_1   "Date measured (year)"
label variable hw19_2   "Date measured (year)"
label variable hw19_3   "Date measured (year)"
label variable hw19_4   "Date measured (year)"
label variable hw19_5   "Date measured (year)"
label variable hw19_6   "Date measured (year)"
label variable hw51_1   "Line number of parent/caretaker"
label variable hw51_2   "Line number of parent/caretaker"
label variable hw51_3   "Line number of parent/caretaker"
label variable hw51_4   "Line number of parent/caretaker"
label variable hw51_5   "Line number of parent/caretaker"
label variable hw51_6   "Line number of parent/caretaker"
label variable hw52_1   "Read consent statement - hemoglobin"
label variable hw52_2   "Read consent statement - hemoglobin"
label variable hw52_3   "Read consent statement - hemoglobin"
label variable hw52_4   "Read consent statement - hemoglobin"
label variable hw52_5   "Read consent statement - hemoglobin"
label variable hw52_6   "Read consent statement - hemoglobin"
label variable hw53_1   "Hemoglobin level (g/dl - 1 decimal)"
label variable hw53_2   "Hemoglobin level (g/dl - 1 decimal)"
label variable hw53_3   "Hemoglobin level (g/dl - 1 decimal)"
label variable hw53_4   "Hemoglobin level (g/dl - 1 decimal)"
label variable hw53_5   "Hemoglobin level (g/dl - 1 decimal)"
label variable hw53_6   "Hemoglobin level (g/dl - 1 decimal)"
label variable hw55_1   "Result of measurement - hemoglobin"
label variable hw55_2   "Result of measurement - hemoglobin"
label variable hw55_3   "Result of measurement - hemoglobin"
label variable hw55_4   "Result of measurement - hemoglobin"
label variable hw55_5   "Result of measurement - hemoglobin"
label variable hw55_6   "Result of measurement - hemoglobin"
label variable hw56_1   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hw56_2   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hw56_3   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hw56_4   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hw56_5   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hw56_6   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hw57_1   "Anemia level"
label variable hw57_2   "Anemia level"
label variable hw57_3   "Anemia level"
label variable hw57_4   "Anemia level"
label variable hw57_5   "Anemia level"
label variable hw57_6   "Anemia level"
label variable v801     "Time interview started (hhmm - 24 hour clock)"
label variable v802     "Time interview ended (hhmm - 24 hour clock)"
label variable v803     "Length of interview in minutes"
label variable v804     "Number of visits"
label variable v805     "Interviewer identification"
label variable idxml_1  "Index to Birth History"
label variable idxml_2  "Index to Birth History"
label variable idxml_3  "Index to Birth History"
label variable idxml_4  "Index to Birth History"
label variable idxml_5  "Index to Birth History"
label variable idxml_6  "Index to Birth History"
label variable ml0_1    "Type of mosquito bed net(s) child slept under last night"
label variable ml0_2    "Type of mosquito bed net(s) child slept under last night"
label variable ml0_3    "Type of mosquito bed net(s) child slept under last night"
label variable ml0_4    "Type of mosquito bed net(s) child slept under last night"
label variable ml0_5    "Type of mosquito bed net(s) child slept under last night"
label variable ml0_6    "Type of mosquito bed net(s) child slept under last night"
label variable ml1_1    "Number of times took fansidar during pregnancy"
label variable ml1_2    "Number of times took fansidar during pregnancy"
label variable ml1_3    "Number of times took fansidar during pregnancy"
label variable ml1_4    "Number of times took fansidar during pregnancy"
label variable ml1_5    "Number of times took fansidar during pregnancy"
label variable ml1_6    "Number of times took fansidar during pregnancy"
label variable ml2_1    "Source of antimalarial during pregnancy"
label variable ml2_2    "Source of antimalarial during pregnancy"
label variable ml2_3    "Source of antimalarial during pregnancy"
label variable ml2_4    "Source of antimalarial during pregnancy"
label variable ml2_5    "Source of antimalarial during pregnancy"
label variable ml2_6    "Source of antimalarial during pregnancy"
label variable ml11_1   "NA - Child has fever/cough now"
label variable ml11_2   "NA - Child has fever/cough now"
label variable ml11_3   "NA - Child has fever/cough now"
label variable ml11_4   "NA - Child has fever/cough now"
label variable ml11_5   "NA - Child has fever/cough now"
label variable ml11_6   "NA - Child has fever/cough now"
label variable ml12_1   "NA - Child has had convulsions in last 2 weeks"
label variable ml12_2   "NA - Child has had convulsions in last 2 weeks"
label variable ml12_3   "NA - Child has had convulsions in last 2 weeks"
label variable ml12_4   "NA - Child has had convulsions in last 2 weeks"
label variable ml12_5   "NA - Child has had convulsions in last 2 weeks"
label variable ml12_6   "NA - Child has had convulsions in last 2 weeks"
label variable ml13a_1  "Fansidar taken for fever"
label variable ml13a_2  "Fansidar taken for fever"
label variable ml13a_3  "Fansidar taken for fever"
label variable ml13a_4  "Fansidar taken for fever"
label variable ml13a_5  "Fansidar taken for fever"
label variable ml13a_6  "Fansidar taken for fever"
label variable ml13b_1  "Chloroquine taken for fever"
label variable ml13b_2  "Chloroquine taken for fever"
label variable ml13b_3  "Chloroquine taken for fever"
label variable ml13b_4  "Chloroquine taken for fever"
label variable ml13b_5  "Chloroquine taken for fever"
label variable ml13b_6  "Chloroquine taken for fever"
label variable ml13c_1  "Amodiaquine taken for fever"
label variable ml13c_2  "Amodiaquine taken for fever"
label variable ml13c_3  "Amodiaquine taken for fever"
label variable ml13c_4  "Amodiaquine taken for fever"
label variable ml13c_5  "Amodiaquine taken for fever"
label variable ml13c_6  "Amodiaquine taken for fever"
label variable ml13d_1  "Quinine taken for fever"
label variable ml13d_2  "Quinine taken for fever"
label variable ml13d_3  "Quinine taken for fever"
label variable ml13d_4  "Quinine taken for fever"
label variable ml13d_5  "Quinine taken for fever"
label variable ml13d_6  "Quinine taken for fever"
label variable ml13da_1 "Quinine injection/IV taken for fever"
label variable ml13da_2 "Quinine injection/IV taken for fever"
label variable ml13da_3 "Quinine injection/IV taken for fever"
label variable ml13da_4 "Quinine injection/IV taken for fever"
label variable ml13da_5 "Quinine injection/IV taken for fever"
label variable ml13da_6 "Quinine injection/IV taken for fever"
label variable ml13e_1  "Combination with artemisinin taken for fever"
label variable ml13e_2  "Combination with artemisinin taken for fever"
label variable ml13e_3  "Combination with artemisinin taken for fever"
label variable ml13e_4  "Combination with artemisinin taken for fever"
label variable ml13e_5  "Combination with artemisinin taken for fever"
label variable ml13e_6  "Combination with artemisinin taken for fever"
label variable ml13aa_1 "Artesunate rectal taken for fever"
label variable ml13aa_2 "Artesunate rectal taken for fever"
label variable ml13aa_3 "Artesunate rectal taken for fever"
label variable ml13aa_4 "Artesunate rectal taken for fever"
label variable ml13aa_5 "Artesunate rectal taken for fever"
label variable ml13aa_6 "Artesunate rectal taken for fever"
label variable ml13ab_1 "Artesunate injection/IV taken for fever"
label variable ml13ab_2 "Artesunate injection/IV taken for fever"
label variable ml13ab_3 "Artesunate injection/IV taken for fever"
label variable ml13ab_4 "Artesunate injection/IV taken for fever"
label variable ml13ab_5 "Artesunate injection/IV taken for fever"
label variable ml13ab_6 "Artesunate injection/IV taken for fever"
label variable ml13f_1  "NA - CS antimalarial taken for fever"
label variable ml13f_2  "NA - CS antimalarial taken for fever"
label variable ml13f_3  "NA - CS antimalarial taken for fever"
label variable ml13f_4  "NA - CS antimalarial taken for fever"
label variable ml13f_5  "NA - CS antimalarial taken for fever"
label variable ml13f_6  "NA - CS antimalarial taken for fever"
label variable ml13g_1  "NA - CS antimalarial taken for fever"
label variable ml13g_2  "NA - CS antimalarial taken for fever"
label variable ml13g_3  "NA - CS antimalarial taken for fever"
label variable ml13g_4  "NA - CS antimalarial taken for fever"
label variable ml13g_5  "NA - CS antimalarial taken for fever"
label variable ml13g_6  "NA - CS antimalarial taken for fever"
label variable ml13h_1  "Other antimalarial taken for fever"
label variable ml13h_2  "Other antimalarial taken for fever"
label variable ml13h_3  "Other antimalarial taken for fever"
label variable ml13h_4  "Other antimalarial taken for fever"
label variable ml13h_5  "Other antimalarial taken for fever"
label variable ml13h_6  "Other antimalarial taken for fever"
label variable ml13i_1  "Antibiotic pill/syrup taken for fever"
label variable ml13i_2  "Antibiotic pill/syrup taken for fever"
label variable ml13i_3  "Antibiotic pill/syrup taken for fever"
label variable ml13i_4  "Antibiotic pill/syrup taken for fever"
label variable ml13i_5  "Antibiotic pill/syrup taken for fever"
label variable ml13i_6  "Antibiotic pill/syrup taken for fever"
label variable ml13j_1  "Antibiotic injection taken for fever"
label variable ml13j_2  "Antibiotic injection taken for fever"
label variable ml13j_3  "Antibiotic injection taken for fever"
label variable ml13j_4  "Antibiotic injection taken for fever"
label variable ml13j_5  "Antibiotic injection taken for fever"
label variable ml13j_6  "Antibiotic injection taken for fever"
label variable ml13k_1  "Aspirin taken for fever"
label variable ml13k_2  "Aspirin taken for fever"
label variable ml13k_3  "Aspirin taken for fever"
label variable ml13k_4  "Aspirin taken for fever"
label variable ml13k_5  "Aspirin taken for fever"
label variable ml13k_6  "Aspirin taken for fever"
label variable ml13l_1  "Acetaminophen/paracetamol/panadol taken for fever"
label variable ml13l_2  "Acetaminophen/paracetamol/panadol taken for fever"
label variable ml13l_3  "Acetaminophen/paracetamol/panadol taken for fever"
label variable ml13l_4  "Acetaminophen/paracetamol/panadol taken for fever"
label variable ml13l_5  "Acetaminophen/paracetamol/panadol taken for fever"
label variable ml13l_6  "Acetaminophen/paracetamol/panadol taken for fever"
label variable ml13m_1  "Ibuprofen taken for fever"
label variable ml13m_2  "Ibuprofen taken for fever"
label variable ml13m_3  "Ibuprofen taken for fever"
label variable ml13m_4  "Ibuprofen taken for fever"
label variable ml13m_5  "Ibuprofen taken for fever"
label variable ml13m_6  "Ibuprofen taken for fever"
label variable ml13n_1  "Herbal medicine taken for fever"
label variable ml13n_2  "Herbal medicine taken for fever"
label variable ml13n_3  "Herbal medicine taken for fever"
label variable ml13n_4  "Herbal medicine taken for fever"
label variable ml13n_5  "Herbal medicine taken for fever"
label variable ml13n_6  "Herbal medicine taken for fever"
label variable ml13o_1  "NA - CS other taken for fever"
label variable ml13o_2  "NA - CS other taken for fever"
label variable ml13o_3  "NA - CS other taken for fever"
label variable ml13o_4  "NA - CS other taken for fever"
label variable ml13o_5  "NA - CS other taken for fever"
label variable ml13o_6  "NA - CS other taken for fever"
label variable ml13p_1  "NA - CS other taken for fever"
label variable ml13p_2  "NA - CS other taken for fever"
label variable ml13p_3  "NA - CS other taken for fever"
label variable ml13p_4  "NA - CS other taken for fever"
label variable ml13p_5  "NA - CS other taken for fever"
label variable ml13p_6  "NA - CS other taken for fever"
label variable ml13x_1  "Other taken for fever"
label variable ml13x_2  "Other taken for fever"
label variable ml13x_3  "Other taken for fever"
label variable ml13x_4  "Other taken for fever"
label variable ml13x_5  "Other taken for fever"
label variable ml13x_6  "Other taken for fever"
label variable ml13y_1  "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13y_2  "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13y_3  "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13y_4  "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13y_5  "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13y_6  "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13z_1  "Don't know if or what was taken for fever"
label variable ml13z_2  "Don't know if or what was taken for fever"
label variable ml13z_3  "Don't know if or what was taken for fever"
label variable ml13z_4  "Don't know if or what was taken for fever"
label variable ml13z_5  "Don't know if or what was taken for fever"
label variable ml13z_6  "Don't know if or what was taken for fever"
label variable ml14a_1  "NA - Injection given for fever/convulsion"
label variable ml14a_2  "NA - Injection given for fever/convulsion"
label variable ml14a_3  "NA - Injection given for fever/convulsion"
label variable ml14a_4  "NA - Injection given for fever/convulsion"
label variable ml14a_5  "NA - Injection given for fever/convulsion"
label variable ml14a_6  "NA - Injection given for fever/convulsion"
label variable ml14b_1  "NA - Suppository given for fever/convulsion"
label variable ml14b_2  "NA - Suppository given for fever/convulsion"
label variable ml14b_3  "NA - Suppository given for fever/convulsion"
label variable ml14b_4  "NA - Suppository given for fever/convulsion"
label variable ml14b_5  "NA - Suppository given for fever/convulsion"
label variable ml14b_6  "NA - Suppository given for fever/convulsion"
label variable ml14y_1  "NA - No suppository or injection given for fever/convulsion"
label variable ml14y_2  "NA - No suppository or injection given for fever/convulsion"
label variable ml14y_3  "NA - No suppository or injection given for fever/convulsion"
label variable ml14y_4  "NA - No suppository or injection given for fever/convulsion"
label variable ml14y_5  "NA - No suppository or injection given for fever/convulsion"
label variable ml14y_6  "NA - No suppository or injection given for fever/convulsion"
label variable ml14z_1  "NA - Don't know if suppository or injection given for fever/convulsion"
label variable ml14z_2  "NA - Don't know if suppository or injection given for fever/convulsion"
label variable ml14z_3  "NA - Don't know if suppository or injection given for fever/convulsion"
label variable ml14z_4  "NA - Don't know if suppository or injection given for fever/convulsion"
label variable ml14z_5  "NA - Don't know if suppository or injection given for fever/convulsion"
label variable ml14z_6  "NA - Don't know if suppository or injection given for fever/convulsion"
label variable ml15a_1  "Timing of start of fansidar"
label variable ml15a_2  "Timing of start of fansidar"
label variable ml15a_3  "Timing of start of fansidar"
label variable ml15a_4  "Timing of start of fansidar"
label variable ml15a_5  "Timing of start of fansidar"
label variable ml15a_6  "Timing of start of fansidar"
label variable ml15b_1  "NA - Number of days child took fansidar"
label variable ml15b_2  "NA - Number of days child took fansidar"
label variable ml15b_3  "NA - Number of days child took fansidar"
label variable ml15b_4  "NA - Number of days child took fansidar"
label variable ml15b_5  "NA - Number of days child took fansidar"
label variable ml15b_6  "NA - Number of days child took fansidar"
label variable ml15c_1  "NA - First source for fansidar"
label variable ml15c_2  "NA - First source for fansidar"
label variable ml15c_3  "NA - First source for fansidar"
label variable ml15c_4  "NA - First source for fansidar"
label variable ml15c_5  "NA - First source for fansidar"
label variable ml15c_6  "NA - First source for fansidar"
label variable ml16a_1  "Timing of start of chloroquine"
label variable ml16a_2  "Timing of start of chloroquine"
label variable ml16a_3  "Timing of start of chloroquine"
label variable ml16a_4  "Timing of start of chloroquine"
label variable ml16a_5  "Timing of start of chloroquine"
label variable ml16a_6  "Timing of start of chloroquine"
label variable ml16b_1  "NA - Number of days child took chloroquine"
label variable ml16b_2  "NA - Number of days child took chloroquine"
label variable ml16b_3  "NA - Number of days child took chloroquine"
label variable ml16b_4  "NA - Number of days child took chloroquine"
label variable ml16b_5  "NA - Number of days child took chloroquine"
label variable ml16b_6  "NA - Number of days child took chloroquine"
label variable ml16c_1  "NA - First source for chloroquine"
label variable ml16c_2  "NA - First source for chloroquine"
label variable ml16c_3  "NA - First source for chloroquine"
label variable ml16c_4  "NA - First source for chloroquine"
label variable ml16c_5  "NA - First source for chloroquine"
label variable ml16c_6  "NA - First source for chloroquine"
label variable ml17a_1  "Timing of start of amodiaquine"
label variable ml17a_2  "Timing of start of amodiaquine"
label variable ml17a_3  "Timing of start of amodiaquine"
label variable ml17a_4  "Timing of start of amodiaquine"
label variable ml17a_5  "Timing of start of amodiaquine"
label variable ml17a_6  "Timing of start of amodiaquine"
label variable ml17b_1  "NA - Number of days child took amodiaquine"
label variable ml17b_2  "NA - Number of days child took amodiaquine"
label variable ml17b_3  "NA - Number of days child took amodiaquine"
label variable ml17b_4  "NA - Number of days child took amodiaquine"
label variable ml17b_5  "NA - Number of days child took amodiaquine"
label variable ml17b_6  "NA - Number of days child took amodiaquine"
label variable ml17c_1  "NA - First source for amodiaquine"
label variable ml17c_2  "NA - First source for amodiaquine"
label variable ml17c_3  "NA - First source for amodiaquine"
label variable ml17c_4  "NA - First source for amodiaquine"
label variable ml17c_5  "NA - First source for amodiaquine"
label variable ml17c_6  "NA - First source for amodiaquine"
label variable ml18a_1  "Timing of start of quinine"
label variable ml18a_2  "Timing of start of quinine"
label variable ml18a_3  "Timing of start of quinine"
label variable ml18a_4  "Timing of start of quinine"
label variable ml18a_5  "Timing of start of quinine"
label variable ml18a_6  "Timing of start of quinine"
label variable ml18b_1  "NA - Number of days child took quinine"
label variable ml18b_2  "NA - Number of days child took quinine"
label variable ml18b_3  "NA - Number of days child took quinine"
label variable ml18b_4  "NA - Number of days child took quinine"
label variable ml18b_5  "NA - Number of days child took quinine"
label variable ml18b_6  "NA - Number of days child took quinine"
label variable ml18c_1  "NA - First source for quinine"
label variable ml18c_2  "NA - First source for quinine"
label variable ml18c_3  "NA - First source for quinine"
label variable ml18c_4  "NA - First source for quinine"
label variable ml18c_5  "NA - First source for quinine"
label variable ml18c_6  "NA - First source for quinine"
label variable ml19a_1  "NA - For fever/convulsion: consulted traditional healer"
label variable ml19a_2  "NA - For fever/convulsion: consulted traditional healer"
label variable ml19a_3  "NA - For fever/convulsion: consulted traditional healer"
label variable ml19a_4  "NA - For fever/convulsion: consulted traditional healer"
label variable ml19a_5  "NA - For fever/convulsion: consulted traditional healer"
label variable ml19a_6  "NA - For fever/convulsion: consulted traditional healer"
label variable ml19b_1  "NA - For fever/convulsion: gave tepid sponging"
label variable ml19b_2  "NA - For fever/convulsion: gave tepid sponging"
label variable ml19b_3  "NA - For fever/convulsion: gave tepid sponging"
label variable ml19b_4  "NA - For fever/convulsion: gave tepid sponging"
label variable ml19b_5  "NA - For fever/convulsion: gave tepid sponging"
label variable ml19b_6  "NA - For fever/convulsion: gave tepid sponging"
label variable ml19c_1  "NA - For fever/convulsion: gave herbs"
label variable ml19c_2  "NA - For fever/convulsion: gave herbs"
label variable ml19c_3  "NA - For fever/convulsion: gave herbs"
label variable ml19c_4  "NA - For fever/convulsion: gave herbs"
label variable ml19c_5  "NA - For fever/convulsion: gave herbs"
label variable ml19c_6  "NA - For fever/convulsion: gave herbs"
label variable ml19d_1  "NA - For fever/convulsion: CS"
label variable ml19d_2  "NA - For fever/convulsion: CS"
label variable ml19d_3  "NA - For fever/convulsion: CS"
label variable ml19d_4  "NA - For fever/convulsion: CS"
label variable ml19d_5  "NA - For fever/convulsion: CS"
label variable ml19d_6  "NA - For fever/convulsion: CS"
label variable ml19e_1  "NA - For fever/convulsion: CS"
label variable ml19e_2  "NA - For fever/convulsion: CS"
label variable ml19e_3  "NA - For fever/convulsion: CS"
label variable ml19e_4  "NA - For fever/convulsion: CS"
label variable ml19e_5  "NA - For fever/convulsion: CS"
label variable ml19e_6  "NA - For fever/convulsion: CS"
label variable ml19f_1  "NA - For fever/convulsion: CS"
label variable ml19f_2  "NA - For fever/convulsion: CS"
label variable ml19f_3  "NA - For fever/convulsion: CS"
label variable ml19f_4  "NA - For fever/convulsion: CS"
label variable ml19f_5  "NA - For fever/convulsion: CS"
label variable ml19f_6  "NA - For fever/convulsion: CS"
label variable ml19x_1  "NA - For fever/convulsion: other"
label variable ml19x_2  "NA - For fever/convulsion: other"
label variable ml19x_3  "NA - For fever/convulsion: other"
label variable ml19x_4  "NA - For fever/convulsion: other"
label variable ml19x_5  "NA - For fever/convulsion: other"
label variable ml19x_6  "NA - For fever/convulsion: other"
label variable ml19y_1  "NA - For fever/convulsion: gave/did nothing"
label variable ml19y_2  "NA - For fever/convulsion: gave/did nothing"
label variable ml19y_3  "NA - For fever/convulsion: gave/did nothing"
label variable ml19y_4  "NA - For fever/convulsion: gave/did nothing"
label variable ml19y_5  "NA - For fever/convulsion: gave/did nothing"
label variable ml19y_6  "NA - For fever/convulsion: gave/did nothing"
label variable ml19z_1  "NA - For fever/convulsion: don't know if something else was done"
label variable ml19z_2  "NA - For fever/convulsion: don't know if something else was done"
label variable ml19z_3  "NA - For fever/convulsion: don't know if something else was done"
label variable ml19z_4  "NA - For fever/convulsion: don't know if something else was done"
label variable ml19z_5  "NA - For fever/convulsion: don't know if something else was done"
label variable ml19z_6  "NA - For fever/convulsion: don't know if something else was done"
label variable ml20a_1  "Timing of start of combination with artemisinin"
label variable ml20a_2  "Timing of start of combination with artemisinin"
label variable ml20a_3  "Timing of start of combination with artemisinin"
label variable ml20a_4  "Timing of start of combination with artemisinin"
label variable ml20a_5  "Timing of start of combination with artemisinin"
label variable ml20a_6  "Timing of start of combination with artemisinin"
label variable ml20b_1  "NA - Number of days child took combination with artemisinin"
label variable ml20b_2  "NA - Number of days child took combination with artemisinin"
label variable ml20b_3  "NA - Number of days child took combination with artemisinin"
label variable ml20b_4  "NA - Number of days child took combination with artemisinin"
label variable ml20b_5  "NA - Number of days child took combination with artemisinin"
label variable ml20b_6  "NA - Number of days child took combination with artemisinin"
label variable ml20c_1  "NA - First source for combination with artemisinin"
label variable ml20c_2  "NA - First source for combination with artemisinin"
label variable ml20c_3  "NA - First source for combination with artemisinin"
label variable ml20c_4  "NA - First source for combination with artemisinin"
label variable ml20c_5  "NA - First source for combination with artemisinin"
label variable ml20c_6  "NA - First source for combination with artemisinin"
label variable ml21a_1  "NA - Timing of start of CS antimalarial use"
label variable ml21a_2  "NA - Timing of start of CS antimalarial use"
label variable ml21a_3  "NA - Timing of start of CS antimalarial use"
label variable ml21a_4  "NA - Timing of start of CS antimalarial use"
label variable ml21a_5  "NA - Timing of start of CS antimalarial use"
label variable ml21a_6  "NA - Timing of start of CS antimalarial use"
label variable ml21b_1  "NA - Number of days child took CS antimalarial"
label variable ml21b_2  "NA - Number of days child took CS antimalarial"
label variable ml21b_3  "NA - Number of days child took CS antimalarial"
label variable ml21b_4  "NA - Number of days child took CS antimalarial"
label variable ml21b_5  "NA - Number of days child took CS antimalarial"
label variable ml21b_6  "NA - Number of days child took CS antimalarial"
label variable ml21c_1  "NA - First source for CS antimalarial"
label variable ml21c_2  "NA - First source for CS antimalarial"
label variable ml21c_3  "NA - First source for CS antimalarial"
label variable ml21c_4  "NA - First source for CS antimalarial"
label variable ml21c_5  "NA - First source for CS antimalarial"
label variable ml21c_6  "NA - First source for CS antimalarial"
label variable ml22a_1  "NA - Timing of start of CS antimalarial use"
label variable ml22a_2  "NA - Timing of start of CS antimalarial use"
label variable ml22a_3  "NA - Timing of start of CS antimalarial use"
label variable ml22a_4  "NA - Timing of start of CS antimalarial use"
label variable ml22a_5  "NA - Timing of start of CS antimalarial use"
label variable ml22a_6  "NA - Timing of start of CS antimalarial use"
label variable ml22b_1  "NA - Number of days child took CS antimalarial"
label variable ml22b_2  "NA - Number of days child took CS antimalarial"
label variable ml22b_3  "NA - Number of days child took CS antimalarial"
label variable ml22b_4  "NA - Number of days child took CS antimalarial"
label variable ml22b_5  "NA - Number of days child took CS antimalarial"
label variable ml22b_6  "NA - Number of days child took CS antimalarial"
label variable ml22c_1  "NA - First source for CS antimalarial"
label variable ml22c_2  "NA - First source for CS antimalarial"
label variable ml22c_3  "NA - First source for CS antimalarial"
label variable ml22c_4  "NA - First source for CS antimalarial"
label variable ml22c_5  "NA - First source for CS antimalarial"
label variable ml22c_6  "NA - First source for CS antimalarial"
label variable ml23a_1  "Timing of start of other anti-malarial use"
label variable ml23a_2  "Timing of start of other anti-malarial use"
label variable ml23a_3  "Timing of start of other anti-malarial use"
label variable ml23a_4  "Timing of start of other anti-malarial use"
label variable ml23a_5  "Timing of start of other anti-malarial use"
label variable ml23a_6  "Timing of start of other anti-malarial use"
label variable ml23b_1  "NA - Number of days child took other anti-malarial"
label variable ml23b_2  "NA - Number of days child took other anti-malarial"
label variable ml23b_3  "NA - Number of days child took other anti-malarial"
label variable ml23b_4  "NA - Number of days child took other anti-malarial"
label variable ml23b_5  "NA - Number of days child took other anti-malarial"
label variable ml23b_6  "NA - Number of days child took other anti-malarial"
label variable ml23c_1  "NA - First source for other anti-malarial"
label variable ml23c_2  "NA - First source for other anti-malarial"
label variable ml23c_3  "NA - First source for other anti-malarial"
label variable ml23c_4  "NA - First source for other anti-malarial"
label variable ml23c_5  "NA - First source for other anti-malarial"
label variable ml23c_6  "NA - First source for other anti-malarial"
label variable ml24c_1  "NA - First source for antibiotic pill/syrup"
label variable ml24c_2  "NA - First source for antibiotic pill/syrup"
label variable ml24c_3  "NA - First source for antibiotic pill/syrup"
label variable ml24c_4  "NA - First source for antibiotic pill/syrup"
label variable ml24c_5  "NA - First source for antibiotic pill/syrup"
label variable ml24c_6  "NA - First source for antibiotic pill/syrup"
label variable ml25a_1  "Timing of start of artesunate"
label variable ml25a_2  "Timing of start of artesunate"
label variable ml25a_3  "Timing of start of artesunate"
label variable ml25a_4  "Timing of start of artesunate"
label variable ml25a_5  "Timing of start of artesunate"
label variable ml25a_6  "Timing of start of artesunate"
label variable sdistrict "District"
label variable s105     "Highest educational level"
label variable s105a    "Highest educational level"
label variable s111     "Registered by health insurance"
label variable s114     "Aware that malaria is covered under the NHIS"
label variable s211     "Number of live births in 2014-2019"
label variable s501     "Seen or heard any messages about malaria in past 6 months"
label variable s502a    "Heard malaria messages on: radio"
label variable s502b    "Heard malaria messages on: tv"
label variable s502c    "Heard malaria messages on: poster/billboard"
label variable s502d    "Heard malaria messages on: newspaper/magazine"
label variable s502e    "Heard malaria messages on: leaflet/brochure"
label variable s502f    "Heard malaria messages on: health worker"
label variable s502g    "Heard malaria messages on: CHW"
label variable s502h    "Heard malaria messages on: community volunteer/CBA"
label variable s502i    "Heard malaria messages on: word of mouth"
label variable s502j    "Heard malaria messages on: community event/durbar meeting"
label variable s502x    "Heard malaria messages on: anywhere else"
label variable s502z    "Heard malaria messages on: don't remember"
label variable s503a    "Have seen or heard malaria messages on the radio"
label variable s503b    "Have seen or heard malaria messages on the tv"
label variable s503c    "Have seen or heard malaria messages on a poster/billboard"
label variable s503d    "Have seen or heard malaria messages in a newspaper/magazine"
label variable s503e    "Have seen or heard malaria messages on a leaflet/brochure"
label variable s503f    "Have seen or heard malaria messages from a health worker"
label variable s503g    "Have seen or heard malaria messages from a CHW"
label variable s503h    "Have seen or heard malaria messages from a community volunteer/CBA"
label variable s503i    "Have seen or heard malaria messages from word of mouth"
label variable s503j    "Have seen or heard malaria messages at a community event/durbar meeting"
label variable s504a    "Messages seen/heard in past 6 months: if have fever go to health facility"
label variable s504b    "Messages seen/heard in past 6 months: sleep under an insecticide-treated mosquit"
label variable s504c    "Messages seen/heard in past 6 months: pregnant women should take drugs to preven"
label variable s504d    "Messages seen/heard in past 6 months: SP protects pregnant women and unborn baby"
label variable s504e    "Messages seen/heard in past 6 months: always test before treating malaria"
label variable s504f    "Messages seen/heard in past 6 months: treat malaria with ACTs"
label variable s504g    "Messages seen/heard in past 6 months: malaria kills"
label variable s504h    "Messages seen/heard in past 6 months: keep surroundings clean"
label variable s504x    "Messages seen/heard in past 6 months: other"
label variable s504z    "Messages seen/heard in past 6 months: don't know/remember"
label variable s505a    "Seen/heard Goodlife campaign recommending pregnant women to sleep under treated "
label variable s505b    "Seen/heard Goodlife campaign recommending sleeping under treated bed nets every "
label variable s505c    "Seen/heard advert about 'My net my life'"
label variable s505d    "Seen/heard advert where people were asked to test first before treated"
label variable s506     "Seen/heard advert on use of ACTs/malaria meds in past 6 months"
label variable s507a    "Source of message on use of ACTs/malaria meds: tv"
label variable s507b    "Source of message on use of ACTs/malaria meds: radio"
label variable s507c    "Source of message on use of ACTs/malaria meds: newspaper/magazine"
label variable s507d    "Source of message on use of ACTs/malaria meds: poster/leaflets"
label variable s507e    "Source of message on use of ACTs/malaria meds: billboard"
label variable s507x    "Source of message on use of ACTs/malaria meds: other"
label variable s507z    "Source of message on use of ACTs/malaria meds: don't know/remember"
label variable s508a    "Ways to protect against malaria: sleep under a mosquito net"
label variable s508b    "Ways to protect against malaria: sleep under an ITN"
label variable s508c    "Ways to protect against malaria: use mosquito repellent"
label variable s508d    "Ways to protect against malaria: take preventative medications"
label variable s508e    "Ways to protect against malaria: spray house with insecticide"
label variable s508f    "Ways to protect against malaria: fill in stagnant waters (puddles)"
label variable s508g    "Ways to protect against malaria: keep surrounding clean"
label variable s508h    "Ways to protect against malaria: put mosquito screen on windows"
label variable s508x    "Ways to protect against malaria: other"
label variable s508z    "Ways to protect against malaria: don't know"
label variable s509     "Almost always worry it might be malaria when a child has fever"
label variable s510     "Don't worry about malaria because it can be easily treated"
label variable s511     "Heard about malaria vaccine"
label variable s512     "Allow child to be vaccinated against malaria"
label variable idx94_1  "Index to Birth History"
label variable idx94_2  "Index to Birth History"
label variable idx94_3  "Index to Birth History"
label variable idx94_4  "Index to Birth History"
label variable idx94_5  "Index to Birth History"
label variable idx94_6  "Index to Birth History"
label variable s305ba_1 "Took SP/Fansidar only 1-2 times: facility too far"
label variable s305ba_2 "Took SP/Fansidar only 1-2 times: facility too far"
label variable s305ba_3 "Took SP/Fansidar only 1-2 times: facility too far"
label variable s305ba_4 "Took SP/Fansidar only 1-2 times: facility too far"
label variable s305ba_5 "Took SP/Fansidar only 1-2 times: facility too far"
label variable s305ba_6 "Took SP/Fansidar only 1-2 times: facility too far"
label variable s305bb_1 "Took SP/Fansidar only 1-2 times: had no money"
label variable s305bb_2 "Took SP/Fansidar only 1-2 times: had no money"
label variable s305bb_3 "Took SP/Fansidar only 1-2 times: had no money"
label variable s305bb_4 "Took SP/Fansidar only 1-2 times: had no money"
label variable s305bb_5 "Took SP/Fansidar only 1-2 times: had no money"
label variable s305bb_6 "Took SP/Fansidar only 1-2 times: had no money"
label variable s305bc_1 "Took SP/Fansidar only 1-2 times: side effects"
label variable s305bc_2 "Took SP/Fansidar only 1-2 times: side effects"
label variable s305bc_3 "Took SP/Fansidar only 1-2 times: side effects"
label variable s305bc_4 "Took SP/Fansidar only 1-2 times: side effects"
label variable s305bc_5 "Took SP/Fansidar only 1-2 times: side effects"
label variable s305bc_6 "Took SP/Fansidar only 1-2 times: side effects"
label variable s305bd_1 "Took SP/Fansidar only 1-2 times: not aware had to take more"
label variable s305bd_2 "Took SP/Fansidar only 1-2 times: not aware had to take more"
label variable s305bd_3 "Took SP/Fansidar only 1-2 times: not aware had to take more"
label variable s305bd_4 "Took SP/Fansidar only 1-2 times: not aware had to take more"
label variable s305bd_5 "Took SP/Fansidar only 1-2 times: not aware had to take more"
label variable s305bd_6 "Took SP/Fansidar only 1-2 times: not aware had to take more"
label variable s305be_1 "Took SP/Fansidar only 1-2 times: did not want to take"
label variable s305be_2 "Took SP/Fansidar only 1-2 times: did not want to take"
label variable s305be_3 "Took SP/Fansidar only 1-2 times: did not want to take"
label variable s305be_4 "Took SP/Fansidar only 1-2 times: did not want to take"
label variable s305be_5 "Took SP/Fansidar only 1-2 times: did not want to take"
label variable s305be_6 "Took SP/Fansidar only 1-2 times: did not want to take"
label variable s305bf_1 "Took SP/Fansidar only 1-2 times: not given"
label variable s305bf_2 "Took SP/Fansidar only 1-2 times: not given"
label variable s305bf_3 "Took SP/Fansidar only 1-2 times: not given"
label variable s305bf_4 "Took SP/Fansidar only 1-2 times: not given"
label variable s305bf_5 "Took SP/Fansidar only 1-2 times: not given"
label variable s305bf_6 "Took SP/Fansidar only 1-2 times: not given"
label variable s305bg_1 "Took SP/Fansidar only 1-2 times: not available"
label variable s305bg_2 "Took SP/Fansidar only 1-2 times: not available"
label variable s305bg_3 "Took SP/Fansidar only 1-2 times: not available"
label variable s305bg_4 "Took SP/Fansidar only 1-2 times: not available"
label variable s305bg_5 "Took SP/Fansidar only 1-2 times: not available"
label variable s305bg_6 "Took SP/Fansidar only 1-2 times: not available"
label variable s305bx_1 "Took SP/Fansidar only 1-2 times: other"
label variable s305bx_2 "Took SP/Fansidar only 1-2 times: other"
label variable s305bx_3 "Took SP/Fansidar only 1-2 times: other"
label variable s305bx_4 "Took SP/Fansidar only 1-2 times: other"
label variable s305bx_5 "Took SP/Fansidar only 1-2 times: other"
label variable s305bx_6 "Took SP/Fansidar only 1-2 times: other"
label variable s305bz_1 "Took SP/Fansidar only 1-2 times: don't know"
label variable s305bz_2 "Took SP/Fansidar only 1-2 times: don't know"
label variable s305bz_3 "Took SP/Fansidar only 1-2 times: don't know"
label variable s305bz_4 "Took SP/Fansidar only 1-2 times: don't know"
label variable s305bz_5 "Took SP/Fansidar only 1-2 times: don't know"
label variable s305bz_6 "Took SP/Fansidar only 1-2 times: don't know"
label variable idx95_1  "Index to Birth History"
label variable idx95_2  "Index to Birth History"
label variable idx95_3  "Index to Birth History"
label variable idx95_4  "Index to Birth History"
label variable idx95_5  "Index to Birth History"
label variable idx95_6  "Index to Birth History"
label variable s403a_1  "Enrolled in program to receive medicine monthly for 4 months to prevent malaria"
label variable s403a_2  "Enrolled in program to receive medicine monthly for 4 months to prevent malaria"
label variable s403a_3  "Enrolled in program to receive medicine monthly for 4 months to prevent malaria"
label variable s403a_4  "Enrolled in program to receive medicine monthly for 4 months to prevent malaria"
label variable s403a_5  "Enrolled in program to receive medicine monthly for 4 months to prevent malaria"
label variable s403a_6  "Enrolled in program to receive medicine monthly for 4 months to prevent malaria"
label variable s403b1_1 "Number of doses taken in 2017"
label variable s403b1_2 "Number of doses taken in 2017"
label variable s403b1_3 "Number of doses taken in 2017"
label variable s403b1_4 "Number of doses taken in 2017"
label variable s403b1_5 "Number of doses taken in 2017"
label variable s403b1_6 "Number of doses taken in 2017"
label variable s403b2_1 "Number of doses taken in 2018"
label variable s403b2_2 "Number of doses taken in 2018"
label variable s403b2_3 "Number of doses taken in 2018"
label variable s403b2_4 "Number of doses taken in 2018"
label variable s403b2_5 "Number of doses taken in 2018"
label variable s403b2_6 "Number of doses taken in 2018"
label variable s405a_1  "Result of malaria blood test"
label variable s405a_2  "Result of malaria blood test"
label variable s405a_3  "Result of malaria blood test"
label variable s405a_4  "Result of malaria blood test"
label variable s405a_5  "Result of malaria blood test"
label variable s405a_6  "Result of malaria blood test"
label variable s407ba_1 "Reason sought advice/treatment from source: child just fell ill"
label variable s407ba_2 "Reason sought advice/treatment from source: child just fell ill"
label variable s407ba_3 "Reason sought advice/treatment from source: child just fell ill"
label variable s407ba_4 "Reason sought advice/treatment from source: child just fell ill"
label variable s407ba_5 "Reason sought advice/treatment from source: child just fell ill"
label variable s407ba_6 "Reason sought advice/treatment from source: child just fell ill"
label variable s407bb_1 "Reason sought advice/treatment from source: child not very ill"
label variable s407bb_2 "Reason sought advice/treatment from source: child not very ill"
label variable s407bb_3 "Reason sought advice/treatment from source: child not very ill"
label variable s407bb_4 "Reason sought advice/treatment from source: child not very ill"
label variable s407bb_5 "Reason sought advice/treatment from source: child not very ill"
label variable s407bb_6 "Reason sought advice/treatment from source: child not very ill"
label variable s407bc_1 "Reason sought advice/treatment from source: clinic too far"
label variable s407bc_2 "Reason sought advice/treatment from source: clinic too far"
label variable s407bc_3 "Reason sought advice/treatment from source: clinic too far"
label variable s407bc_4 "Reason sought advice/treatment from source: clinic too far"
label variable s407bc_5 "Reason sought advice/treatment from source: clinic too far"
label variable s407bc_6 "Reason sought advice/treatment from source: clinic too far"
label variable s407bd_1 "Reason sought advice/treatment from source: have no money"
label variable s407bd_2 "Reason sought advice/treatment from source: have no money"
label variable s407bd_3 "Reason sought advice/treatment from source: have no money"
label variable s407bd_4 "Reason sought advice/treatment from source: have no money"
label variable s407bd_5 "Reason sought advice/treatment from source: have no money"
label variable s407bd_6 "Reason sought advice/treatment from source: have no money"
label variable s407be_1 "Reason sought advice/treatment from source: waiting for child's father"
label variable s407be_2 "Reason sought advice/treatment from source: waiting for child's father"
label variable s407be_3 "Reason sought advice/treatment from source: waiting for child's father"
label variable s407be_4 "Reason sought advice/treatment from source: waiting for child's father"
label variable s407be_5 "Reason sought advice/treatment from source: waiting for child's father"
label variable s407be_6 "Reason sought advice/treatment from source: waiting for child's father"
label variable s407bf_1 "Reason sought advice/treatment from source: don't know what to do"
label variable s407bf_2 "Reason sought advice/treatment from source: don't know what to do"
label variable s407bf_3 "Reason sought advice/treatment from source: don't know what to do"
label variable s407bf_4 "Reason sought advice/treatment from source: don't know what to do"
label variable s407bf_5 "Reason sought advice/treatment from source: don't know what to do"
label variable s407bf_6 "Reason sought advice/treatment from source: don't know what to do"
label variable s407bg_1 "Reason sought advice/treatment from source: this site was closer"
label variable s407bg_2 "Reason sought advice/treatment from source: this site was closer"
label variable s407bg_3 "Reason sought advice/treatment from source: this site was closer"
label variable s407bg_4 "Reason sought advice/treatment from source: this site was closer"
label variable s407bg_5 "Reason sought advice/treatment from source: this site was closer"
label variable s407bg_6 "Reason sought advice/treatment from source: this site was closer"
label variable s407bh_1 "Reason sought advice/treatment from source: trust this source"
label variable s407bh_2 "Reason sought advice/treatment from source: trust this source"
label variable s407bh_3 "Reason sought advice/treatment from source: trust this source"
label variable s407bh_4 "Reason sought advice/treatment from source: trust this source"
label variable s407bh_5 "Reason sought advice/treatment from source: trust this source"
label variable s407bh_6 "Reason sought advice/treatment from source: trust this source"
label variable s407bi_1 "Reason sought advice/treatment from source: instruction by household head"
label variable s407bi_2 "Reason sought advice/treatment from source: instruction by household head"
label variable s407bi_3 "Reason sought advice/treatment from source: instruction by household head"
label variable s407bi_4 "Reason sought advice/treatment from source: instruction by household head"
label variable s407bi_5 "Reason sought advice/treatment from source: instruction by household head"
label variable s407bi_6 "Reason sought advice/treatment from source: instruction by household head"
label variable s407bx_1 "Reason sought advice/treatment from source: other"
label variable s407bx_2 "Reason sought advice/treatment from source: other"
label variable s407bx_3 "Reason sought advice/treatment from source: other"
label variable s407bx_4 "Reason sought advice/treatment from source: other"
label variable s407bx_5 "Reason sought advice/treatment from source: other"
label variable s407bx_6 "Reason sought advice/treatment from source: other"
label variable s412ba_1 "Reason did not take antimalarial: fever was not malaria"
label variable s412ba_2 "Reason did not take antimalarial: fever was not malaria"
label variable s412ba_3 "Reason did not take antimalarial: fever was not malaria"
label variable s412ba_4 "Reason did not take antimalarial: fever was not malaria"
label variable s412ba_5 "Reason did not take antimalarial: fever was not malaria"
label variable s412ba_6 "Reason did not take antimalarial: fever was not malaria"
label variable s412bb_1 "Reason did not take antimalarial: none available at facility"
label variable s412bb_2 "Reason did not take antimalarial: none available at facility"
label variable s412bb_3 "Reason did not take antimalarial: none available at facility"
label variable s412bb_4 "Reason did not take antimalarial: none available at facility"
label variable s412bb_5 "Reason did not take antimalarial: none available at facility"
label variable s412bb_6 "Reason did not take antimalarial: none available at facility"
label variable s412bc_1 "Reason did not take antimalarial: provider did not offer antimalarial"
label variable s412bc_2 "Reason did not take antimalarial: provider did not offer antimalarial"
label variable s412bc_3 "Reason did not take antimalarial: provider did not offer antimalarial"
label variable s412bc_4 "Reason did not take antimalarial: provider did not offer antimalarial"
label variable s412bc_5 "Reason did not take antimalarial: provider did not offer antimalarial"
label variable s412bc_6 "Reason did not take antimalarial: provider did not offer antimalarial"
label variable s412bd_1 "Reason did not take antimalarial: provider refused to give antimalarial"
label variable s412bd_2 "Reason did not take antimalarial: provider refused to give antimalarial"
label variable s412bd_3 "Reason did not take antimalarial: provider refused to give antimalarial"
label variable s412bd_4 "Reason did not take antimalarial: provider refused to give antimalarial"
label variable s412bd_5 "Reason did not take antimalarial: provider refused to give antimalarial"
label variable s412bd_6 "Reason did not take antimalarial: provider refused to give antimalarial"
label variable s412be_1 "Reason did not take antimalarial: afraid of effects of drugs on health"
label variable s412be_2 "Reason did not take antimalarial: afraid of effects of drugs on health"
label variable s412be_3 "Reason did not take antimalarial: afraid of effects of drugs on health"
label variable s412be_4 "Reason did not take antimalarial: afraid of effects of drugs on health"
label variable s412be_5 "Reason did not take antimalarial: afraid of effects of drugs on health"
label variable s412be_6 "Reason did not take antimalarial: afraid of effects of drugs on health"
label variable s412bf_1 "Reason did not take antimalarial: child not very ill"
label variable s412bf_2 "Reason did not take antimalarial: child not very ill"
label variable s412bf_3 "Reason did not take antimalarial: child not very ill"
label variable s412bf_4 "Reason did not take antimalarial: child not very ill"
label variable s412bf_5 "Reason did not take antimalarial: child not very ill"
label variable s412bf_6 "Reason did not take antimalarial: child not very ill"
label variable s412bg_1 "Reason did not take antimalarial: clinic too far"
label variable s412bg_2 "Reason did not take antimalarial: clinic too far"
label variable s412bg_3 "Reason did not take antimalarial: clinic too far"
label variable s412bg_4 "Reason did not take antimalarial: clinic too far"
label variable s412bg_5 "Reason did not take antimalarial: clinic too far"
label variable s412bg_6 "Reason did not take antimalarial: clinic too far"
label variable s412bh_1 "Reason did not take antimalarial: have no money"
label variable s412bh_2 "Reason did not take antimalarial: have no money"
label variable s412bh_3 "Reason did not take antimalarial: have no money"
label variable s412bh_4 "Reason did not take antimalarial: have no money"
label variable s412bh_5 "Reason did not take antimalarial: have no money"
label variable s412bh_6 "Reason did not take antimalarial: have no money"
label variable s412bi_1 "Reason did not take antimalarial: do not know to take antimalarial"
label variable s412bi_2 "Reason did not take antimalarial: do not know to take antimalarial"
label variable s412bi_3 "Reason did not take antimalarial: do not know to take antimalarial"
label variable s412bi_4 "Reason did not take antimalarial: do not know to take antimalarial"
label variable s412bi_5 "Reason did not take antimalarial: do not know to take antimalarial"
label variable s412bi_6 "Reason did not take antimalarial: do not know to take antimalarial"
label variable s412bj_1 "Reason did not take antimalarial: medicine at home"
label variable s412bj_2 "Reason did not take antimalarial: medicine at home"
label variable s412bj_3 "Reason did not take antimalarial: medicine at home"
label variable s412bj_4 "Reason did not take antimalarial: medicine at home"
label variable s412bj_5 "Reason did not take antimalarial: medicine at home"
label variable s412bj_6 "Reason did not take antimalarial: medicine at home"
label variable s412bk_1 "Reason did not take antimalarial: did not think it was malaria"
label variable s412bk_2 "Reason did not take antimalarial: did not think it was malaria"
label variable s412bk_3 "Reason did not take antimalarial: did not think it was malaria"
label variable s412bk_4 "Reason did not take antimalarial: did not think it was malaria"
label variable s412bk_5 "Reason did not take antimalarial: did not think it was malaria"
label variable s412bk_6 "Reason did not take antimalarial: did not think it was malaria"
label variable s412bx_1 "Reason did not take antimalarial: other"
label variable s412bx_2 "Reason did not take antimalarial: other"
label variable s412bx_3 "Reason did not take antimalarial: other"
label variable s412bx_4 "Reason did not take antimalarial: other"
label variable s412bx_5 "Reason did not take antimalarial: other"
label variable s412bx_6 "Reason did not take antimalarial: other"

#delimit ;
label define V013    
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define V014    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define V015    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partially completed"
     6 "Respondent incapacitated"
     7 "Other"
;
label define V018    
     0 "No calendar"
;
label define V019    
     0 "No calendar"
;
label define V019A   
     0 "No calendar"
;
label define V020    
     0 "All woman sample"
     1 "Ever married sample"
;
label define V022    
     1 "Western: Urban"
     2 "Western: Rural"
     3 "Central: Urban"
     4 "Central: Rural"
     5 "Greater Accra: Urban"
     6 "Greater Accra: Rural"
     7 "Volta: Urban"
     8 "Volta: Rural"
     9 "Eastern: Urban"
    10 "Eastern: Rural"
    11 "Ashanti: Urban"
    12 "Ashanti: Rural"
    13 "Brong Ahafo: Urban"
    14 "Brong Ahafo: Rural"
    15 "Northern: Urban"
    16 "Northern: Rural"
    17 "Upper East: Urban"
    18 "Upper East: Rural"
    19 "Upper West: Urban"
    20 "Upper West: Rural"
;
label define V023    
     1 "Western: Urban"
     2 "Western: Rural"
     3 "Central: Urban"
     4 "Central: Rural"
     5 "Greater Accra: Urban"
     6 "Greater Accra: Rural"
     7 "Volta: Urban"
     8 "Volta: Rural"
     9 "Eastern: Urban"
    10 "Eastern: Rural"
    11 "Ashanti: Urban"
    12 "Ashanti: Rural"
    13 "Brong Ahafo: Urban"
    14 "Brong Ahafo: Rural"
    15 "Northern: Urban"
    16 "Northern: Rural"
    17 "Upper East: Urban"
    18 "Upper East: Rural"
    19 "Upper West: Urban"
    20 "Upper West: Rural"
;
label define V024    
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Brong Ahafo"
     8 "Northern"
     9 "Upper East"
    10 "Upper West"
;
label define V025    
     1 "Urban"
     2 "Rural"
;
label define V026    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V027    
     9 "Missing"
;
label define V034    
     0 "Husband not in household"
;
label define V040    
  9999 "Missing"
;
label define V042    
     0 "Not selected"
     1 "Selected"
;
label define V044    
     0 "Woman not selected"
     1 "Woman selected and interviewed"
     2 "Woman selected, but privacy not possible"
     3 "Woman selected, but not interviewed"
;
label define V045A   
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     5 "Dagbani"
;
label define V045B   
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     5 "Dagbani"
     6 "Other"
;
label define V045C   
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     5 "Dagbani"
     6 "Other"
;
label define V046    
     0 "No"
     1 "Yes"
;
label define V101    
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Brong Ahafo"
     8 "Northern"
     9 "Upper East"
    10 "Upper West"
;
label define V102    
     1 "Urban"
     2 "Rural"
;
label define V106    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define V107    
     0 "No years completed at level V106"
;
label define V113    
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    72 "Sachet water"
    96 "Other"
    97 "Not a dejure resident"
;
label define V115    
   996 "On premises"
   997 "Not a dejure resident"
   998 "Don't know"
;
label define V116    
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    16 "Flush, bio-digester (biofil)"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
    97 "Not a dejure resident"
;
label define V119    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V120    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V121    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V122    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V123    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V124    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V125    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V127    
    10 "NATURAL"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic/marble/porcelain tiles/terrazo"
    34 "Cement"
    35 "Woolen carpet/synthetic carpet"
    36 "Linoleum/rubber carpet"
    96 "Other"
    97 "Not a dejure resident"
;
label define V128    
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Mud/landcrete"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
    97 "Not a dejure resident"
;
label define V129    
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Zinc/aluminum"
    32 "Wood"
    33 "Ceramic/brick tiles"
    34 "Cement"
    35 "Roofing shingles"
    36 "Asbestos/slate roofing sheets"
    96 "Other"
    97 "Not a dejure resident"
;
label define V130    
     1 "Catholic"
     2 "Anglican"
     3 "Methodist"
     4 "Presbyterian"
     5 "Pentecostal/Charismatic"
     6 "Other Christian"
     7 "Islam"
     8 "Traditional/Spiritualist"
    95 "No religion"
    96 "Other"
;
label define V131    
     1 "Akan"
     2 "Ga/Dangme"
     3 "Ewe"
     4 "Guan"
     5 "Mole-Dagbani"
     6 "Grusi"
     7 "Gurma"
     8 "Mande"
    96 "Other"
;
label define V133    
    97 "Inconsistent"
;
label define V135    
     1 "Usual resident"
     2 "Visitor"
;
label define V139    
     0 "Abroad"
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Brong Ahafo"
     8 "Northern"
     9 "Upper East"
    10 "Upper West"
    97 "Not dejure resident"
;
label define V140    
     0 "Abroad"
     1 "Urban"
     2 "Rural"
     7 "Not a dejure resident"
;
label define V149    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define V150    
     1 "Head"
     2 "Wife"
     3 "Daughter"
     4 "Daughter-in-law"
     5 "Granddaughter"
     6 "Mother"
     7 "Mother-in-law"
     8 "Sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "Don't know"
;
label define V151    
     1 "Male"
     2 "Female"
;
label define V152    
    95 "95+"
    98 "Don't know"
;
label define V153    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V155    
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define V160    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V161    
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in house"
    96 "Other"
    97 "Not a dejure resident"
;
label define V190    
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define V190A   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define ML101   
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define B0      
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
;
label define B4      
     1 "Male"
     2 "Female"
;
label define B5      
     0 "No"
     1 "Yes"
;
label define B9      
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
;
label define B10     
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define B15     
     0 "No"
     1 "Yes"
;
label define B16     
     0 "Not listed in household"
;
label define V208    
     0 "No births"
;
label define V209    
     0 "No births"
;
label define V213    
     0 "No or unsure"
     1 "Yes"
;
label define V220    
     6 "6+"
;
label define V223    
     7 "Month - exact date"
     8 "None - date placed"
;
label define V237    
     0 "No"
     1 "Yes"
;
label define M2A     
     0 "No"
     1 "Yes"
;
label define M2B     
     0 "No"
     1 "Yes"
;
label define M2C     
     0 "No"
     1 "Yes"
;
label define M2D     
     0 "No"
     1 "Yes"
;
label define M2E     
     0 "No"
     1 "Yes"
;
label define M2F     
     0 "No"
     1 "Yes"
;
label define M2G     
     0 "No"
     1 "Yes"
;
label define M2H     
     0 "No"
     1 "Yes"
;
label define M2I     
     0 "No"
     1 "Yes"
;
label define M2J     
     0 "No"
     1 "Yes"
;
label define M2K     
     0 "No"
     1 "Yes"
;
label define M2L     
     0 "No"
     1 "Yes"
;
label define M2M     
     0 "No"
     1 "Yes"
;
label define M2N     
     0 "No: some care"
     1 "Yes: no care"
;
label define M13     
    98 "Don't know"
;
label define M14     
     0 "No antenatal visits"
    98 "Don't know"
;
label define M49A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49C    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49D    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49E    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49F    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49G    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49X    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49Z    
     0 "No"
     1 "Yes: don't know which drug taken"
     8 "Don't know"
;
label define M49Y    
     0 "No"
     1 "Yes, took no drug"
     8 "Don't know"
;
label define M57A    
     0 "No"
     1 "Yes"
;
label define M57B    
     0 "No"
     1 "Yes"
;
label define M57C    
     0 "No"
     1 "Yes"
;
label define M57D    
     0 "No"
     1 "Yes"
;
label define M57E    
     0 "No"
     1 "Yes"
;
label define M57F    
     0 "No"
     1 "Yes"
;
label define M57G    
     0 "No"
     1 "Yes"
;
label define M57H    
     0 "No"
     1 "Yes"
;
label define M57I    
     0 "No"
     1 "Yes"
;
label define M57J    
     0 "No"
     1 "Yes"
;
label define M57K    
     0 "No"
     1 "Yes"
;
label define M57L    
     0 "No"
     1 "Yes"
;
label define M57M    
     0 "No"
     1 "Yes"
;
label define M57N    
     0 "No"
     1 "Yes"
;
label define M57O    
     0 "No"
     1 "Yes"
;
label define M57P    
     0 "No"
     1 "Yes"
;
label define M57Q    
     0 "No"
     1 "Yes"
;
label define M57R    
     0 "No"
     1 "Yes"
;
label define M57S    
     0 "No"
     1 "Yes"
;
label define M57T    
     0 "No"
     1 "Yes"
;
label define M57U    
     0 "No"
     1 "Yes"
;
label define M57V    
     0 "No"
     1 "Yes"
;
label define M57X    
     0 "No"
     1 "Yes"
;
label define V459    
     0 "No"
     1 "Yes"
;
label define V460    
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define V461    
     0 "No"
     1 "Yes"
;
label define V468    
     0 "See specific questions"
     1 "Last birth only"
     2 "All births in last 5 years"
;
label define V481    
     0 "No"
     1 "Yes"
;
label define V481A   
     0 "No"
     1 "Yes"
;
label define V481B   
     0 "No"
     1 "Yes"
;
label define V481C   
     0 "No"
     1 "Yes"
;
label define V481D   
     0 "No"
     1 "Yes"
;
label define V481E   
     0 "No"
     1 "Yes"
;
label define V481F   
     0 "No"
     1 "Yes"
;
label define V481G   
     0 "No"
     1 "Yes"
;
label define V481H   
     0 "No"
     1 "Yes"
;
label define V481X   
     0 "No"
     1 "Yes"
;
label define H22     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H32A    
     0 "No"
     1 "Yes"
;
label define H32B    
     0 "No"
     1 "Yes"
;
label define H32C    
     0 "No"
     1 "Yes"
;
label define H32D    
     0 "No"
     1 "Yes"
;
label define H32E    
     0 "No"
     1 "Yes"
;
label define H32F    
     0 "No"
     1 "Yes"
;
label define H32G    
     0 "No"
     1 "Yes"
;
label define H32H    
     0 "No"
     1 "Yes"
;
label define H32I    
     0 "No"
     1 "Yes"
;
label define H32J    
     0 "No"
     1 "Yes"
;
label define H32K    
     0 "No"
     1 "Yes"
;
label define H32L    
     0 "No"
     1 "Yes"
;
label define H32M    
     0 "No"
     1 "Yes"
;
label define H32N    
     0 "No"
     1 "Yes"
;
label define H32O    
     0 "No"
     1 "Yes"
;
label define H32P    
     0 "No"
     1 "Yes"
;
label define H32Q    
     0 "No"
     1 "Yes"
;
label define H32R    
     0 "No"
     1 "Yes"
;
label define H32S    
     0 "No"
     1 "Yes"
;
label define H32T    
     0 "No"
     1 "Yes"
;
label define H32U    
     0 "No"
     1 "Yes"
;
label define H32V    
     0 "No"
     1 "Yes"
;
label define H32W    
     0 "No"
     1 "Yes"
;
label define H32X    
     0 "No"
     1 "Yes"
;
label define H32Y    
     0 "No: received treatment"
     1 "Yes: no treatment"
;
label define H32Z    
     0 "No"
     1 "Yes"
;
label define H46A    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Government health post/CHPS"
    14 "Mobile clinic"
    15 "Fieldworker/CHW"
    16 "Other public sector"
    20 "PRIVATE SECTOR"
    21 "Private hospital/clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "Chemist/drug store"
    25 "FPG/PPAG clinic"
    26 "Mobile clinic"
    27 "Fieldworker/CHW"
    28 "Other private medical sector"
    30 "OTHER"
    31 "Shop"
    32 "Traditional practitioner"
    33 "Market"
    34 "Itinerant drug seller"
    96 "Other"
;
label define H46B    
     0 "Same day"
    98 "Don't know"
;
label define H47     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HW16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HW51    
     0 "Not in household"
;
label define HW52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HW53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HW55    
     0 "Measured"
     1 "Dead"
     3 "Not present"
     4 "Refused"
     6 "Other"
     7 "No measurement found in household"
;
label define HW56    
   997 "Inconsistent"
;
label define HW57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define V801    
  9999 "Missing"
;
label define V802    
  9999 "Missing"
;
label define V803    
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define V804    
     9 "Missing"
;
label define ML0     
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define ML1     
    98 "Don't know"
;
label define ML2     
     1 "Antenatal visit"
     2 "Another facility visit"
     6 "Other source"
;
label define ML11    
     0 "No"
     1 "Yes, fever only"
     2 "Yes, cough only"
     3 "Both fever and cough"
     8 "Don't know"
;
label define ML12    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define ML13A   
     0 "No"
     1 "Yes"
;
label define ML13B   
     0 "No"
     1 "Yes"
;
label define ML13C   
     0 "No"
     1 "Yes"
;
label define ML13D   
     0 "No"
     1 "Yes"
;
label define ML13DA  
     0 "No"
     1 "Yes"
;
label define ML13E   
     0 "No"
     1 "Yes"
;
label define ML13AA  
     0 "No"
     1 "Yes"
;
label define ML13AB  
     0 "No"
     1 "Yes"
;
label define ML13F   
     0 "No"
     1 "Yes"
;
label define ML13G   
     0 "No"
     1 "Yes"
;
label define ML13H   
     0 "No"
     1 "Yes"
;
label define ML13I   
     0 "No"
     1 "Yes"
;
label define ML13J   
     0 "No"
     1 "Yes"
;
label define ML13K   
     0 "No"
     1 "Yes"
;
label define ML13L   
     0 "No"
     1 "Yes"
;
label define ML13M   
     0 "No"
     1 "Yes"
;
label define ML13N   
     0 "No"
     1 "Yes"
;
label define ML13O   
     0 "No"
     1 "Yes"
;
label define ML13P   
     0 "No"
     1 "Yes"
;
label define ML13X   
     0 "No"
     1 "Yes"
;
label define ML13Y   
     0 "No"
     1 "Yes, nothing taken"
;
label define ML13Z   
     0 "No"
     1 "Yes, don't know"
;
label define ML14A   
     0 "No"
     1 "Yes"
;
label define ML14B   
     0 "No"
     1 "Yes"
;
label define ML14Y   
     0 "No"
     1 "Yes"
;
label define ML14Z   
     0 "No"
     1 "Yes"
;
label define ML15A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     8 "Don't know"
;
label define ML15B   
     7 "7+ days"
     8 "Don't know"
;
label define ML15C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML16A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     8 "Don't know"
;
label define ML16B   
     7 "7+ days"
     8 "Don't know"
;
label define ML16C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML17A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     8 "Don't know"
;
label define ML17B   
     7 "7+ days"
     8 "Don't know"
;
label define ML17C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML18A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     8 "Don't know"
;
label define ML18B   
     7 "7+ days"
     8 "Don't know"
;
label define ML18C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML19A   
     0 "No"
     1 "Yes"
;
label define ML19B   
     0 "No"
     1 "Yes"
;
label define ML19C   
     0 "No"
     1 "Yes"
;
label define ML19D   
     0 "No"
     1 "Yes"
;
label define ML19E   
     0 "No"
     1 "Yes"
;
label define ML19F   
     0 "No"
     1 "Yes"
;
label define ML19X   
     0 "No"
     1 "Yes"
;
label define ML19Y   
     0 "No"
     1 "Yes"
;
label define ML19Z   
     0 "No"
     1 "Yes"
;
label define ML20A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     8 "Don't know"
;
label define ML20B   
     7 "7+ days"
     8 "Don't know"
;
label define ML20C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML21A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML21B   
     7 "7+ days"
     8 "Don't know"
;
label define ML21C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML22A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML22B   
     7 "7+ days"
     8 "Don't know"
;
label define ML22C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML23A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     8 "Don't know"
;
label define ML23B   
     7 "7+ days"
     8 "Don't know"
;
label define ML23C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML24C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML25A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     8 "Don't know"
;
label define SDISTRICT
   101 "Jomoro"
   103 "Nzema East"
   104 "Ahanta West"
   105 "Sekondi Takoradi Metropolis"
   108 "Tarkwa Nsuaem Municipal"
   109 "Prestea/Huni Valley"
   110 "Wassa Amenfi East"
   112 "Aowin"
   114 "Sefwi Wiawso"
   115 "Sefwi Bibiani-Ahwiaso Bekwai"
   117 "Bia west"
   120 "Suaman"
   201 "Komenda-Edina-Egyafo-Abirem Municipal"
   202 "Cape Coast Metropolis"
   203 "Abura-Asebu-Kwamankese"
   204 "Mfantsiman"
   205 "Ajumako-Enyan-Essiam"
   206 "Gomoa West"
   207 "Effutu Municipal"
   208 "Gomoa East"
   209 "Ewutu Senya"
   210 "Agona East"
   211 "Agona West Municipal"
   212 "Asikuma-Odoben Brakwa"
   213 "Assin South"
   214 "Assin North Municipal"
   217 "Upper Denkyira West"
   219 "Ekumfi"
   220 "Awutu Senya East Municipal"
   301 "Ga South Municipal"
   302 "Ga West Municipal"
   303 "Ga East Municipal"
   304 "Accra Metropolis"
   306 "Ledzokuku/Krowor Municipal"
   307 "Ashaiman Municipal"
   308 "Tema Metropolis"
   310 "Ada East"
   311 "Ga Central Municipal"
   312 "La Dade Kotopon Municipal"
   313 "La Nkwantanang Madina Municipal"
   401 "South Tongu"
   402 "Keta Municapal"
   403 "Ketu South"
   405 "Akatsi"
   407 "Adaklu"
   408 "Ho Municipal"
   409 "South Dayi"
   411 "Hohoe Municipal"
   413 "Jasikan"
   414 "Kadjebi"
   415 "Krachi East"
   417 "Nkwanta South"
   419 "North Tongu"
   420 "Akatsi North"
   422 "Ho West"
   424 "North Dayi"
   501 "Birim South"
   502 "Birim Municipal"
   504 "Suhum Municipal"
   506 "Akwapem North"
   507 "New Juaben Municipal"
   509 "Lower Manya"
   510 "Asuogyaman"
   512 "Fanteakwa"
   513 "East Akim Municipal"
   514 "Kwaebibirem"
   516 "Birim North"
   517 "Atiwa"
   518 "Kwahu West Municipal"
   521 "Kwahu Afram Plains North"
   522 "Upper West Akyem"
   525 "Denkyembuor"
   601 "Atwima Mponua"
   603 "Amansie Central"
   605 "Obuasi Municipal"
   606 "Adansi North"
   608 "Bosome Freho"
   610 "Asante Akim Central Municipal"
   611 "Ejisu Juaben Municipal"
   614 "Kumasi Metropolis"
   615 "Atwima Nwabiagya"
   616 "Ahafo Ano South"
   619 "Afigya Kwabre"
   623 "Sekyere East"
   624 "Sekyere Afram Plains"
   628 "Asokore Mampong Municipal"
   702 "Asunafo North Municipal"
   704 "Dormaa Municipal"
   707 "Tano North"
   708 "Sunyani Municipal"
   710 "Berekum Municipal"
   712 "Jaman North"
   713 "Tain"
   715 "Techiman Municipal"
   716 "Nkoranza South"
   718 "Atebubu Amantin"
   720 "Pru"
   722 "Kintampo North Municipal"
   723 "Asutifi South"
   727 "Sene East"
   801 "Bole"
   804 "Gonja Central"
   805 "East Gonja"
   806 "Kpandai"
   808 "Nanumba North"
   810 "Yendi Municipal"
   811 "Tamale Metropolis"
   813 "Savelugu Nanton"
   816 "Saboba"
   818 "Bunkpurugu Yonyo"
   819 "Mamprusi East"
   820 "Mamprusi West"
   822 "Kumbumgu"
   823 "Sagnerigu Municipal"
   825 "Tatale"
   901 "Builsa North"
   902 "Kasena Nankana West"
   903 "Kasena Nankana East"
   904 "Bolgatanga Municipal"
   905 "Talensi"
   906 "Bongo"
   907 "Bawku West"
   908 "Garu Tempane"
   909 "Bawku Municipal"
   910 "Builsa South"
   912 "Binduri"
  1001 "Wa West"
  1002 "Wa Municipal"
  1003 "Wa East"
  1004 "Sissala East"
  1005 "Nadowli-Kaleo"
  1006 "Jirapa"
  1007 "Sissala West"
  1008 "Lambussie Karni"
  1009 "Lawra"
  1011 "Nandom"
;
label define S105    
     1 "Primary"
     2 "Middle"
     3 "JSS/JHS"
     4 "SSS/SHS"
     5 "Secondary"
     6 "Higher"
;
label define S105A   
     0 "No education"
     1 "Primary"
     2 "Middle/JSS/JHS"
     3 "Secondary/SSS/SHS or Higher"
;
label define S111    
     0 "No"
     1 "Yes"
;
label define S114    
     0 "No"
     1 "Yes"
;
label define S211    
     0 "None"
;
label define S501    
     0 "No"
     1 "Yes"
;
label define S502A   
     0 "No"
     1 "Yes"
;
label define S502B   
     0 "No"
     1 "Yes"
;
label define S502C   
     0 "No"
     1 "Yes"
;
label define S502D   
     0 "No"
     1 "Yes"
;
label define S502E   
     0 "No"
     1 "Yes"
;
label define S502F   
     0 "No"
     1 "Yes"
;
label define S502G   
     0 "No"
     1 "Yes"
;
label define S502H   
     0 "No"
     1 "Yes"
;
label define S502I   
     0 "No"
     1 "Yes"
;
label define S502J   
     0 "No"
     1 "Yes"
;
label define S502X   
     0 "No"
     1 "Yes"
;
label define S502Z   
     0 "No"
     1 "Yes"
;
label define S503A   
     0 "No"
     1 "Yes"
;
label define S503B   
     0 "No"
     1 "Yes"
;
label define S503C   
     0 "No"
     1 "Yes"
;
label define S503D   
     0 "No"
     1 "Yes"
;
label define S503E   
     0 "No"
     1 "Yes"
;
label define S503F   
     0 "No"
     1 "Yes"
;
label define S503G   
     0 "No"
     1 "Yes"
;
label define S503H   
     0 "No"
     1 "Yes"
;
label define S503I   
     0 "No"
     1 "Yes"
;
label define S503J   
     0 "No"
     1 "Yes"
;
label define S504A   
     0 "No"
     1 "Yes"
;
label define S504B   
     0 "No"
     1 "Yes"
;
label define S504C   
     0 "No"
     1 "Yes"
;
label define S504D   
     0 "No"
     1 "Yes"
;
label define S504E   
     0 "No"
     1 "Yes"
;
label define S504F   
     0 "No"
     1 "Yes"
;
label define S504G   
     0 "No"
     1 "Yes"
;
label define S504H   
     0 "No"
     1 "Yes"
;
label define S504X   
     0 "No"
     1 "Yes"
;
label define S504Z   
     0 "No"
     1 "Yes"
;
label define S505A   
     0 "No"
     1 "Yes, on TV"
     2 "Yes, on radio"
     3 "Yes, on TV and radio"
;
label define S505B   
     0 "No"
     1 "Yes, on TV"
     2 "Yes, on radio"
     3 "Yes, on TV and radio"
;
label define S505C   
     0 "No"
     1 "Yes, on TV"
     2 "Yes, on radio"
     3 "Yes, on TV and radio"
;
label define S505D   
     0 "No"
     1 "Yes, on TV"
     2 "Yes, on radio"
     3 "Yes, on TV and radio"
;
label define S506    
     0 "No"
     1 "Yes"
;
label define S507A   
     0 "No"
     1 "Yes"
;
label define S507B   
     0 "No"
     1 "Yes"
;
label define S507C   
     0 "No"
     1 "Yes"
;
label define S507D   
     0 "No"
     1 "Yes"
;
label define S507E   
     0 "No"
     1 "Yes"
;
label define S507X   
     0 "No"
     1 "Yes"
;
label define S507Z   
     0 "No"
     1 "Yes"
;
label define S508A   
     0 "No"
     1 "Yes"
;
label define S508B   
     0 "No"
     1 "Yes"
;
label define S508C   
     0 "No"
     1 "Yes"
;
label define S508D   
     0 "No"
     1 "Yes"
;
label define S508E   
     0 "No"
     1 "Yes"
;
label define S508F   
     0 "No"
     1 "Yes"
;
label define S508G   
     0 "No"
     1 "Yes"
;
label define S508H   
     0 "No"
     1 "Yes"
;
label define S508X   
     0 "No"
     1 "Yes"
;
label define S508Z   
     0 "No"
     1 "Yes"
;
label define S509    
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define S510    
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define S511    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define S512    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define S305BA  
     0 "No"
     1 "Yes"
;
label define S305BB  
     0 "No"
     1 "Yes"
;
label define S305BC  
     0 "No"
     1 "Yes"
;
label define S305BD  
     0 "No"
     1 "Yes"
;
label define S305BE  
     0 "No"
     1 "Yes"
;
label define S305BF  
     0 "No"
     1 "Yes"
;
label define S305BG  
     0 "No"
     1 "Yes"
;
label define S305BX  
     0 "No"
     1 "Yes"
;
label define S305BZ  
     0 "No"
     1 "Yes"
;
label define S403A   
     0 "No, never enrolled"
     1 "Yes, in 2017"
     2 "Yes, in 2018"
     3 "Yes, in 2017 and 2018"
;
label define S405A   
     0 "Negative"
     1 "Positive malaria"
     2 "Positive other illness"
     8 "Don't know/don't remember"
;
label define S407BA  
     0 "No"
     1 "Yes"
;
label define S407BB  
     0 "No"
     1 "Yes"
;
label define S407BC  
     0 "No"
     1 "Yes"
;
label define S407BD  
     0 "No"
     1 "Yes"
;
label define S407BE  
     0 "No"
     1 "Yes"
;
label define S407BF  
     0 "No"
     1 "Yes"
;
label define S407BG  
     0 "No"
     1 "Yes"
;
label define S407BH  
     0 "No"
     1 "Yes"
;
label define S407BI  
     0 "No"
     1 "Yes"
;
label define S407BX  
     0 "No"
     1 "Yes"
;
label define S412BA  
     0 "No"
     1 "Yes"
;
label define S412BB  
     0 "No"
     1 "Yes"
;
label define S412BC  
     0 "No"
     1 "Yes"
;
label define S412BD  
     0 "No"
     1 "Yes"
;
label define S412BE  
     0 "No"
     1 "Yes"
;
label define S412BF  
     0 "No"
     1 "Yes"
;
label define S412BG  
     0 "No"
     1 "Yes"
;
label define S412BH  
     0 "No"
     1 "Yes"
;
label define S412BI  
     0 "No"
     1 "Yes"
;
label define S412BJ  
     0 "No"
     1 "Yes"
;
label define S412BK  
     0 "No"
     1 "Yes"
;
label define S412BX  
     0 "No"
     1 "Yes"
;

#delimit cr
label values v013     V013    
label values v014     V014    
label values v015     V015    
label values v018     V018    
label values v019     V019    
label values v019a    V019A   
label values v020     V020    
label values v022     V022    
label values v023     V023    
label values v024     V024    
label values v025     V025    
label values v026     V026    
label values v034     V034    
label values v042     V042    
label values v044     V044    
label values v045a    V045A   
label values v045b    V045B   
label values v045c    V045C   
label values v046     V046    
label values v101     V101    
label values v102     V102    
label values v106     V106    
label values v107     V107    
label values v113     V113    
label values v115     V115    
label values v116     V116    
label values v119     V119    
label values v120     V120    
label values v121     V121    
label values v122     V122    
label values v123     V123    
label values v124     V124    
label values v125     V125    
label values v127     V127    
label values v128     V128    
label values v129     V129    
label values v130     V130    
label values v131     V131    
label values v133     V133    
label values v135     V135    
label values v139     V139    
label values v140     V140    
label values v149     V149    
label values v150     V150    
label values v151     V151    
label values v152     V152    
label values v153     V153    
label values v155     V155    
label values v160     V160    
label values v161     V161    
label values v190     V190    
label values v190a    V190A   
label values ml101    ML101   
label values b0_01    B0      
label values b0_02    B0      
label values b0_03    B0      
label values b0_04    B0      
label values b0_05    B0      
label values b0_06    B0      
label values b0_07    B0      
label values b0_08    B0      
label values b0_09    B0      
label values b0_10    B0      
label values b0_11    B0      
label values b0_12    B0      
label values b0_13    B0      
label values b0_14    B0      
label values b0_15    B0      
label values b0_16    B0      
label values b0_17    B0      
label values b0_18    B0      
label values b0_19    B0      
label values b0_20    B0      
label values b4_01    B4      
label values b4_02    B4      
label values b4_03    B4      
label values b4_04    B4      
label values b4_05    B4      
label values b4_06    B4      
label values b4_07    B4      
label values b4_08    B4      
label values b4_09    B4      
label values b4_10    B4      
label values b4_11    B4      
label values b4_12    B4      
label values b4_13    B4      
label values b4_14    B4      
label values b4_15    B4      
label values b4_16    B4      
label values b4_17    B4      
label values b4_18    B4      
label values b4_19    B4      
label values b4_20    B4      
label values b5_01    B5      
label values b5_02    B5      
label values b5_03    B5      
label values b5_04    B5      
label values b5_05    B5      
label values b5_06    B5      
label values b5_07    B5      
label values b5_08    B5      
label values b5_09    B5      
label values b5_10    B5      
label values b5_11    B5      
label values b5_12    B5      
label values b5_13    B5      
label values b5_14    B5      
label values b5_15    B5      
label values b5_16    B5      
label values b5_17    B5      
label values b5_18    B5      
label values b5_19    B5      
label values b5_20    B5      
label values b9_01    B9      
label values b9_02    B9      
label values b9_03    B9      
label values b9_04    B9      
label values b9_05    B9      
label values b9_06    B9      
label values b9_07    B9      
label values b9_08    B9      
label values b9_09    B9      
label values b9_10    B9      
label values b9_11    B9      
label values b9_12    B9      
label values b9_13    B9      
label values b9_14    B9      
label values b9_15    B9      
label values b9_16    B9      
label values b9_17    B9      
label values b9_18    B9      
label values b9_19    B9      
label values b9_20    B9      
label values b10_01   B10     
label values b10_02   B10     
label values b10_03   B10     
label values b10_04   B10     
label values b10_05   B10     
label values b10_06   B10     
label values b10_07   B10     
label values b10_08   B10     
label values b10_09   B10     
label values b10_10   B10     
label values b10_11   B10     
label values b10_12   B10     
label values b10_13   B10     
label values b10_14   B10     
label values b10_15   B10     
label values b10_16   B10     
label values b10_17   B10     
label values b10_18   B10     
label values b10_19   B10     
label values b10_20   B10     
label values b15_01   B15     
label values b15_02   B15     
label values b15_03   B15     
label values b15_04   B15     
label values b15_05   B15     
label values b15_06   B15     
label values b15_07   B15     
label values b15_08   B15     
label values b15_09   B15     
label values b15_10   B15     
label values b15_11   B15     
label values b15_12   B15     
label values b15_13   B15     
label values b15_14   B15     
label values b15_15   B15     
label values b15_16   B15     
label values b15_17   B15     
label values b15_18   B15     
label values b15_19   B15     
label values b15_20   B15     
label values b16_01   B16     
label values b16_02   B16     
label values b16_03   B16     
label values b16_04   B16     
label values b16_05   B16     
label values b16_06   B16     
label values b16_07   B16     
label values b16_08   B16     
label values b16_09   B16     
label values b16_10   B16     
label values b16_11   B16     
label values b16_12   B16     
label values b16_13   B16     
label values b16_14   B16     
label values b16_15   B16     
label values b16_16   B16     
label values b16_17   B16     
label values b16_18   B16     
label values b16_19   B16     
label values b16_20   B16     
label values v208     V208    
label values v209     V209    
label values v213     V213    
label values v220     V220    
label values v223     V223    
label values v237     V237    
label values m2a_1    M2A     
label values m2a_2    M2A     
label values m2a_3    M2A     
label values m2a_4    M2A     
label values m2a_5    M2A     
label values m2a_6    M2A     
label values m2b_1    M2B     
label values m2b_2    M2B     
label values m2b_3    M2B     
label values m2b_4    M2B     
label values m2b_5    M2B     
label values m2b_6    M2B     
label values m2c_1    M2C     
label values m2c_2    M2C     
label values m2c_3    M2C     
label values m2c_4    M2C     
label values m2c_5    M2C     
label values m2c_6    M2C     
label values m2d_1    M2D     
label values m2d_2    M2D     
label values m2d_3    M2D     
label values m2d_4    M2D     
label values m2d_5    M2D     
label values m2d_6    M2D     
label values m2e_1    M2E     
label values m2e_2    M2E     
label values m2e_3    M2E     
label values m2e_4    M2E     
label values m2e_5    M2E     
label values m2e_6    M2E     
label values m2f_1    M2F     
label values m2f_2    M2F     
label values m2f_3    M2F     
label values m2f_4    M2F     
label values m2f_5    M2F     
label values m2f_6    M2F     
label values m2g_1    M2G     
label values m2g_2    M2G     
label values m2g_3    M2G     
label values m2g_4    M2G     
label values m2g_5    M2G     
label values m2g_6    M2G     
label values m2h_1    M2H     
label values m2h_2    M2H     
label values m2h_3    M2H     
label values m2h_4    M2H     
label values m2h_5    M2H     
label values m2h_6    M2H     
label values m2i_1    M2I     
label values m2i_2    M2I     
label values m2i_3    M2I     
label values m2i_4    M2I     
label values m2i_5    M2I     
label values m2i_6    M2I     
label values m2j_1    M2J     
label values m2j_2    M2J     
label values m2j_3    M2J     
label values m2j_4    M2J     
label values m2j_5    M2J     
label values m2j_6    M2J     
label values m2k_1    M2K     
label values m2k_2    M2K     
label values m2k_3    M2K     
label values m2k_4    M2K     
label values m2k_5    M2K     
label values m2k_6    M2K     
label values m2l_1    M2L     
label values m2l_2    M2L     
label values m2l_3    M2L     
label values m2l_4    M2L     
label values m2l_5    M2L     
label values m2l_6    M2L     
label values m2m_1    M2M     
label values m2m_2    M2M     
label values m2m_3    M2M     
label values m2m_4    M2M     
label values m2m_5    M2M     
label values m2m_6    M2M     
label values m2n_1    M2N     
label values m2n_2    M2N     
label values m2n_3    M2N     
label values m2n_4    M2N     
label values m2n_5    M2N     
label values m2n_6    M2N     
label values m13_1    M13     
label values m13_2    M13     
label values m13_3    M13     
label values m13_4    M13     
label values m13_5    M13     
label values m13_6    M13     
label values m14_1    M14     
label values m14_2    M14     
label values m14_3    M14     
label values m14_4    M14     
label values m14_5    M14     
label values m14_6    M14     
label values m49a_1   M49A    
label values m49a_2   M49A    
label values m49a_3   M49A    
label values m49a_4   M49A    
label values m49a_5   M49A    
label values m49a_6   M49A    
label values m49b_1   M49B    
label values m49b_2   M49B    
label values m49b_3   M49B    
label values m49b_4   M49B    
label values m49b_5   M49B    
label values m49b_6   M49B    
label values m49c_1   M49C    
label values m49c_2   M49C    
label values m49c_3   M49C    
label values m49c_4   M49C    
label values m49c_5   M49C    
label values m49c_6   M49C    
label values m49d_1   M49D    
label values m49d_2   M49D    
label values m49d_3   M49D    
label values m49d_4   M49D    
label values m49d_5   M49D    
label values m49d_6   M49D    
label values m49e_1   M49E    
label values m49e_2   M49E    
label values m49e_3   M49E    
label values m49e_4   M49E    
label values m49e_5   M49E    
label values m49e_6   M49E    
label values m49f_1   M49F    
label values m49f_2   M49F    
label values m49f_3   M49F    
label values m49f_4   M49F    
label values m49f_5   M49F    
label values m49f_6   M49F    
label values m49g_1   M49G    
label values m49g_2   M49G    
label values m49g_3   M49G    
label values m49g_4   M49G    
label values m49g_5   M49G    
label values m49g_6   M49G    
label values m49x_1   M49X    
label values m49x_2   M49X    
label values m49x_3   M49X    
label values m49x_4   M49X    
label values m49x_5   M49X    
label values m49x_6   M49X    
label values m49z_1   M49Z    
label values m49z_2   M49Z    
label values m49z_3   M49Z    
label values m49z_4   M49Z    
label values m49z_5   M49Z    
label values m49z_6   M49Z    
label values m49y_1   M49Y    
label values m49y_2   M49Y    
label values m49y_3   M49Y    
label values m49y_4   M49Y    
label values m49y_5   M49Y    
label values m49y_6   M49Y    
label values m57a_1   M57A    
label values m57a_2   M57A    
label values m57a_3   M57A    
label values m57a_4   M57A    
label values m57a_5   M57A    
label values m57a_6   M57A    
label values m57b_1   M57B    
label values m57b_2   M57B    
label values m57b_3   M57B    
label values m57b_4   M57B    
label values m57b_5   M57B    
label values m57b_6   M57B    
label values m57c_1   M57C    
label values m57c_2   M57C    
label values m57c_3   M57C    
label values m57c_4   M57C    
label values m57c_5   M57C    
label values m57c_6   M57C    
label values m57d_1   M57D    
label values m57d_2   M57D    
label values m57d_3   M57D    
label values m57d_4   M57D    
label values m57d_5   M57D    
label values m57d_6   M57D    
label values m57e_1   M57E    
label values m57e_2   M57E    
label values m57e_3   M57E    
label values m57e_4   M57E    
label values m57e_5   M57E    
label values m57e_6   M57E    
label values m57f_1   M57F    
label values m57f_2   M57F    
label values m57f_3   M57F    
label values m57f_4   M57F    
label values m57f_5   M57F    
label values m57f_6   M57F    
label values m57g_1   M57G    
label values m57g_2   M57G    
label values m57g_3   M57G    
label values m57g_4   M57G    
label values m57g_5   M57G    
label values m57g_6   M57G    
label values m57h_1   M57H    
label values m57h_2   M57H    
label values m57h_3   M57H    
label values m57h_4   M57H    
label values m57h_5   M57H    
label values m57h_6   M57H    
label values m57i_1   M57I    
label values m57i_2   M57I    
label values m57i_3   M57I    
label values m57i_4   M57I    
label values m57i_5   M57I    
label values m57i_6   M57I    
label values m57j_1   M57J    
label values m57j_2   M57J    
label values m57j_3   M57J    
label values m57j_4   M57J    
label values m57j_5   M57J    
label values m57j_6   M57J    
label values m57k_1   M57K    
label values m57k_2   M57K    
label values m57k_3   M57K    
label values m57k_4   M57K    
label values m57k_5   M57K    
label values m57k_6   M57K    
label values m57l_1   M57L    
label values m57l_2   M57L    
label values m57l_3   M57L    
label values m57l_4   M57L    
label values m57l_5   M57L    
label values m57l_6   M57L    
label values m57m_1   M57M    
label values m57m_2   M57M    
label values m57m_3   M57M    
label values m57m_4   M57M    
label values m57m_5   M57M    
label values m57m_6   M57M    
label values m57n_1   M57N    
label values m57n_2   M57N    
label values m57n_3   M57N    
label values m57n_4   M57N    
label values m57n_5   M57N    
label values m57n_6   M57N    
label values m57o_1   M57O    
label values m57o_2   M57O    
label values m57o_3   M57O    
label values m57o_4   M57O    
label values m57o_5   M57O    
label values m57o_6   M57O    
label values m57p_1   M57P    
label values m57p_2   M57P    
label values m57p_3   M57P    
label values m57p_4   M57P    
label values m57p_5   M57P    
label values m57p_6   M57P    
label values m57q_1   M57Q    
label values m57q_2   M57Q    
label values m57q_3   M57Q    
label values m57q_4   M57Q    
label values m57q_5   M57Q    
label values m57q_6   M57Q    
label values m57r_1   M57R    
label values m57r_2   M57R    
label values m57r_3   M57R    
label values m57r_4   M57R    
label values m57r_5   M57R    
label values m57r_6   M57R    
label values m57s_1   M57S    
label values m57s_2   M57S    
label values m57s_3   M57S    
label values m57s_4   M57S    
label values m57s_5   M57S    
label values m57s_6   M57S    
label values m57t_1   M57T    
label values m57t_2   M57T    
label values m57t_3   M57T    
label values m57t_4   M57T    
label values m57t_5   M57T    
label values m57t_6   M57T    
label values m57u_1   M57U    
label values m57u_2   M57U    
label values m57u_3   M57U    
label values m57u_4   M57U    
label values m57u_5   M57U    
label values m57u_6   M57U    
label values m57v_1   M57V    
label values m57v_2   M57V    
label values m57v_3   M57V    
label values m57v_4   M57V    
label values m57v_5   M57V    
label values m57v_6   M57V    
label values m57x_1   M57X    
label values m57x_2   M57X    
label values m57x_3   M57X    
label values m57x_4   M57X    
label values m57x_5   M57X    
label values m57x_6   M57X    
label values v459     V459    
label values v460     V460    
label values v461     V461    
label values v468     V468    
label values v481     V481    
label values v481a    V481A   
label values v481b    V481B   
label values v481c    V481C   
label values v481d    V481D   
label values v481e    V481E   
label values v481f    V481F   
label values v481g    V481G   
label values v481h    V481H   
label values v481x    V481X   
label values h22_1    H22     
label values h22_2    H22     
label values h22_3    H22     
label values h22_4    H22     
label values h22_5    H22     
label values h22_6    H22     
label values h32a_1   H32A    
label values h32a_2   H32A    
label values h32a_3   H32A    
label values h32a_4   H32A    
label values h32a_5   H32A    
label values h32a_6   H32A    
label values h32b_1   H32B    
label values h32b_2   H32B    
label values h32b_3   H32B    
label values h32b_4   H32B    
label values h32b_5   H32B    
label values h32b_6   H32B    
label values h32c_1   H32C    
label values h32c_2   H32C    
label values h32c_3   H32C    
label values h32c_4   H32C    
label values h32c_5   H32C    
label values h32c_6   H32C    
label values h32d_1   H32D    
label values h32d_2   H32D    
label values h32d_3   H32D    
label values h32d_4   H32D    
label values h32d_5   H32D    
label values h32d_6   H32D    
label values h32e_1   H32E    
label values h32e_2   H32E    
label values h32e_3   H32E    
label values h32e_4   H32E    
label values h32e_5   H32E    
label values h32e_6   H32E    
label values h32f_1   H32F    
label values h32f_2   H32F    
label values h32f_3   H32F    
label values h32f_4   H32F    
label values h32f_5   H32F    
label values h32f_6   H32F    
label values h32g_1   H32G    
label values h32g_2   H32G    
label values h32g_3   H32G    
label values h32g_4   H32G    
label values h32g_5   H32G    
label values h32g_6   H32G    
label values h32h_1   H32H    
label values h32h_2   H32H    
label values h32h_3   H32H    
label values h32h_4   H32H    
label values h32h_5   H32H    
label values h32h_6   H32H    
label values h32i_1   H32I    
label values h32i_2   H32I    
label values h32i_3   H32I    
label values h32i_4   H32I    
label values h32i_5   H32I    
label values h32i_6   H32I    
label values h32j_1   H32J    
label values h32j_2   H32J    
label values h32j_3   H32J    
label values h32j_4   H32J    
label values h32j_5   H32J    
label values h32j_6   H32J    
label values h32k_1   H32K    
label values h32k_2   H32K    
label values h32k_3   H32K    
label values h32k_4   H32K    
label values h32k_5   H32K    
label values h32k_6   H32K    
label values h32l_1   H32L    
label values h32l_2   H32L    
label values h32l_3   H32L    
label values h32l_4   H32L    
label values h32l_5   H32L    
label values h32l_6   H32L    
label values h32m_1   H32M    
label values h32m_2   H32M    
label values h32m_3   H32M    
label values h32m_4   H32M    
label values h32m_5   H32M    
label values h32m_6   H32M    
label values h32n_1   H32N    
label values h32n_2   H32N    
label values h32n_3   H32N    
label values h32n_4   H32N    
label values h32n_5   H32N    
label values h32n_6   H32N    
label values h32o_1   H32O    
label values h32o_2   H32O    
label values h32o_3   H32O    
label values h32o_4   H32O    
label values h32o_5   H32O    
label values h32o_6   H32O    
label values h32p_1   H32P    
label values h32p_2   H32P    
label values h32p_3   H32P    
label values h32p_4   H32P    
label values h32p_5   H32P    
label values h32p_6   H32P    
label values h32q_1   H32Q    
label values h32q_2   H32Q    
label values h32q_3   H32Q    
label values h32q_4   H32Q    
label values h32q_5   H32Q    
label values h32q_6   H32Q    
label values h32r_1   H32R    
label values h32r_2   H32R    
label values h32r_3   H32R    
label values h32r_4   H32R    
label values h32r_5   H32R    
label values h32r_6   H32R    
label values h32s_1   H32S    
label values h32s_2   H32S    
label values h32s_3   H32S    
label values h32s_4   H32S    
label values h32s_5   H32S    
label values h32s_6   H32S    
label values h32t_1   H32T    
label values h32t_2   H32T    
label values h32t_3   H32T    
label values h32t_4   H32T    
label values h32t_5   H32T    
label values h32t_6   H32T    
label values h32u_1   H32U    
label values h32u_2   H32U    
label values h32u_3   H32U    
label values h32u_4   H32U    
label values h32u_5   H32U    
label values h32u_6   H32U    
label values h32v_1   H32V    
label values h32v_2   H32V    
label values h32v_3   H32V    
label values h32v_4   H32V    
label values h32v_5   H32V    
label values h32v_6   H32V    
label values h32w_1   H32W    
label values h32w_2   H32W    
label values h32w_3   H32W    
label values h32w_4   H32W    
label values h32w_5   H32W    
label values h32w_6   H32W    
label values h32x_1   H32X    
label values h32x_2   H32X    
label values h32x_3   H32X    
label values h32x_4   H32X    
label values h32x_5   H32X    
label values h32x_6   H32X    
label values h32y_1   H32Y    
label values h32y_2   H32Y    
label values h32y_3   H32Y    
label values h32y_4   H32Y    
label values h32y_5   H32Y    
label values h32y_6   H32Y    
label values h32z_1   H32Z    
label values h32z_2   H32Z    
label values h32z_3   H32Z    
label values h32z_4   H32Z    
label values h32z_5   H32Z    
label values h32z_6   H32Z    
label values h46a_1   H46A    
label values h46a_2   H46A    
label values h46a_3   H46A    
label values h46a_4   H46A    
label values h46a_5   H46A    
label values h46a_6   H46A    
label values h46b_1   H46B    
label values h46b_2   H46B    
label values h46b_3   H46B    
label values h46b_4   H46B    
label values h46b_5   H46B    
label values h46b_6   H46B    
label values h47_1    H47     
label values h47_2    H47     
label values h47_3    H47     
label values h47_4    H47     
label values h47_5    H47     
label values h47_6    H47     
label values hw16_1   HW16    
label values hw16_2   HW16    
label values hw16_3   HW16    
label values hw16_4   HW16    
label values hw16_5   HW16    
label values hw16_6   HW16    
label values hw51_1   HW51    
label values hw51_2   HW51    
label values hw51_3   HW51    
label values hw51_4   HW51    
label values hw51_5   HW51    
label values hw51_6   HW51    
label values hw52_1   HW52    
label values hw52_2   HW52    
label values hw52_3   HW52    
label values hw52_4   HW52    
label values hw52_5   HW52    
label values hw52_6   HW52    
label values hw53_1   HW53    
label values hw53_2   HW53    
label values hw53_3   HW53    
label values hw53_4   HW53    
label values hw53_5   HW53    
label values hw53_6   HW53    
label values hw55_1   HW55    
label values hw55_2   HW55    
label values hw55_3   HW55    
label values hw55_4   HW55    
label values hw55_5   HW55    
label values hw55_6   HW55    
label values hw56_1   HW56    
label values hw56_2   HW56    
label values hw56_3   HW56    
label values hw56_4   HW56    
label values hw56_5   HW56    
label values hw56_6   HW56    
label values hw57_1   HW57    
label values hw57_2   HW57    
label values hw57_3   HW57    
label values hw57_4   HW57    
label values hw57_5   HW57    
label values hw57_6   HW57    
label values v803     V803    
label values ml0_1    ML0     
label values ml0_2    ML0     
label values ml0_3    ML0     
label values ml0_4    ML0     
label values ml0_5    ML0     
label values ml0_6    ML0     
label values ml1_1    ML1     
label values ml1_2    ML1     
label values ml1_3    ML1     
label values ml1_4    ML1     
label values ml1_5    ML1     
label values ml1_6    ML1     
label values ml2_1    ML2     
label values ml2_2    ML2     
label values ml2_3    ML2     
label values ml2_4    ML2     
label values ml2_5    ML2     
label values ml2_6    ML2     
label values ml11_1   ML11    
label values ml11_2   ML11    
label values ml11_3   ML11    
label values ml11_4   ML11    
label values ml11_5   ML11    
label values ml11_6   ML11    
label values ml12_1   ML12    
label values ml12_2   ML12    
label values ml12_3   ML12    
label values ml12_4   ML12    
label values ml12_5   ML12    
label values ml12_6   ML12    
label values ml13a_1  ML13A   
label values ml13a_2  ML13A   
label values ml13a_3  ML13A   
label values ml13a_4  ML13A   
label values ml13a_5  ML13A   
label values ml13a_6  ML13A   
label values ml13b_1  ML13B   
label values ml13b_2  ML13B   
label values ml13b_3  ML13B   
label values ml13b_4  ML13B   
label values ml13b_5  ML13B   
label values ml13b_6  ML13B   
label values ml13c_1  ML13C   
label values ml13c_2  ML13C   
label values ml13c_3  ML13C   
label values ml13c_4  ML13C   
label values ml13c_5  ML13C   
label values ml13c_6  ML13C   
label values ml13d_1  ML13D   
label values ml13d_2  ML13D   
label values ml13d_3  ML13D   
label values ml13d_4  ML13D   
label values ml13d_5  ML13D   
label values ml13d_6  ML13D   
label values ml13da_1 ML13DA  
label values ml13da_2 ML13DA  
label values ml13da_3 ML13DA  
label values ml13da_4 ML13DA  
label values ml13da_5 ML13DA  
label values ml13da_6 ML13DA  
label values ml13e_1  ML13E   
label values ml13e_2  ML13E   
label values ml13e_3  ML13E   
label values ml13e_4  ML13E   
label values ml13e_5  ML13E   
label values ml13e_6  ML13E   
label values ml13aa_1 ML13AA  
label values ml13aa_2 ML13AA  
label values ml13aa_3 ML13AA  
label values ml13aa_4 ML13AA  
label values ml13aa_5 ML13AA  
label values ml13aa_6 ML13AA  
label values ml13ab_1 ML13AB  
label values ml13ab_2 ML13AB  
label values ml13ab_3 ML13AB  
label values ml13ab_4 ML13AB  
label values ml13ab_5 ML13AB  
label values ml13ab_6 ML13AB  
label values ml13f_1  ML13F   
label values ml13f_2  ML13F   
label values ml13f_3  ML13F   
label values ml13f_4  ML13F   
label values ml13f_5  ML13F   
label values ml13f_6  ML13F   
label values ml13g_1  ML13G   
label values ml13g_2  ML13G   
label values ml13g_3  ML13G   
label values ml13g_4  ML13G   
label values ml13g_5  ML13G   
label values ml13g_6  ML13G   
label values ml13h_1  ML13H   
label values ml13h_2  ML13H   
label values ml13h_3  ML13H   
label values ml13h_4  ML13H   
label values ml13h_5  ML13H   
label values ml13h_6  ML13H   
label values ml13i_1  ML13I   
label values ml13i_2  ML13I   
label values ml13i_3  ML13I   
label values ml13i_4  ML13I   
label values ml13i_5  ML13I   
label values ml13i_6  ML13I   
label values ml13j_1  ML13J   
label values ml13j_2  ML13J   
label values ml13j_3  ML13J   
label values ml13j_4  ML13J   
label values ml13j_5  ML13J   
label values ml13j_6  ML13J   
label values ml13k_1  ML13K   
label values ml13k_2  ML13K   
label values ml13k_3  ML13K   
label values ml13k_4  ML13K   
label values ml13k_5  ML13K   
label values ml13k_6  ML13K   
label values ml13l_1  ML13L   
label values ml13l_2  ML13L   
label values ml13l_3  ML13L   
label values ml13l_4  ML13L   
label values ml13l_5  ML13L   
label values ml13l_6  ML13L   
label values ml13m_1  ML13M   
label values ml13m_2  ML13M   
label values ml13m_3  ML13M   
label values ml13m_4  ML13M   
label values ml13m_5  ML13M   
label values ml13m_6  ML13M   
label values ml13n_1  ML13N   
label values ml13n_2  ML13N   
label values ml13n_3  ML13N   
label values ml13n_4  ML13N   
label values ml13n_5  ML13N   
label values ml13n_6  ML13N   
label values ml13o_1  ML13O   
label values ml13o_2  ML13O   
label values ml13o_3  ML13O   
label values ml13o_4  ML13O   
label values ml13o_5  ML13O   
label values ml13o_6  ML13O   
label values ml13p_1  ML13P   
label values ml13p_2  ML13P   
label values ml13p_3  ML13P   
label values ml13p_4  ML13P   
label values ml13p_5  ML13P   
label values ml13p_6  ML13P   
label values ml13x_1  ML13X   
label values ml13x_2  ML13X   
label values ml13x_3  ML13X   
label values ml13x_4  ML13X   
label values ml13x_5  ML13X   
label values ml13x_6  ML13X   
label values ml13y_1  ML13Y   
label values ml13y_2  ML13Y   
label values ml13y_3  ML13Y   
label values ml13y_4  ML13Y   
label values ml13y_5  ML13Y   
label values ml13y_6  ML13Y   
label values ml13z_1  ML13Z   
label values ml13z_2  ML13Z   
label values ml13z_3  ML13Z   
label values ml13z_4  ML13Z   
label values ml13z_5  ML13Z   
label values ml13z_6  ML13Z   
label values ml14a_1  ML14A   
label values ml14a_2  ML14A   
label values ml14a_3  ML14A   
label values ml14a_4  ML14A   
label values ml14a_5  ML14A   
label values ml14a_6  ML14A   
label values ml14b_1  ML14B   
label values ml14b_2  ML14B   
label values ml14b_3  ML14B   
label values ml14b_4  ML14B   
label values ml14b_5  ML14B   
label values ml14b_6  ML14B   
label values ml14y_1  ML14Y   
label values ml14y_2  ML14Y   
label values ml14y_3  ML14Y   
label values ml14y_4  ML14Y   
label values ml14y_5  ML14Y   
label values ml14y_6  ML14Y   
label values ml14z_1  ML14Z   
label values ml14z_2  ML14Z   
label values ml14z_3  ML14Z   
label values ml14z_4  ML14Z   
label values ml14z_5  ML14Z   
label values ml14z_6  ML14Z   
label values ml15a_1  ML15A   
label values ml15a_2  ML15A   
label values ml15a_3  ML15A   
label values ml15a_4  ML15A   
label values ml15a_5  ML15A   
label values ml15a_6  ML15A   
label values ml15b_1  ML15B   
label values ml15b_2  ML15B   
label values ml15b_3  ML15B   
label values ml15b_4  ML15B   
label values ml15b_5  ML15B   
label values ml15b_6  ML15B   
label values ml15c_1  ML15C   
label values ml15c_2  ML15C   
label values ml15c_3  ML15C   
label values ml15c_4  ML15C   
label values ml15c_5  ML15C   
label values ml15c_6  ML15C   
label values ml16a_1  ML16A   
label values ml16a_2  ML16A   
label values ml16a_3  ML16A   
label values ml16a_4  ML16A   
label values ml16a_5  ML16A   
label values ml16a_6  ML16A   
label values ml16b_1  ML16B   
label values ml16b_2  ML16B   
label values ml16b_3  ML16B   
label values ml16b_4  ML16B   
label values ml16b_5  ML16B   
label values ml16b_6  ML16B   
label values ml16c_1  ML16C   
label values ml16c_2  ML16C   
label values ml16c_3  ML16C   
label values ml16c_4  ML16C   
label values ml16c_5  ML16C   
label values ml16c_6  ML16C   
label values ml17a_1  ML17A   
label values ml17a_2  ML17A   
label values ml17a_3  ML17A   
label values ml17a_4  ML17A   
label values ml17a_5  ML17A   
label values ml17a_6  ML17A   
label values ml17b_1  ML17B   
label values ml17b_2  ML17B   
label values ml17b_3  ML17B   
label values ml17b_4  ML17B   
label values ml17b_5  ML17B   
label values ml17b_6  ML17B   
label values ml17c_1  ML17C   
label values ml17c_2  ML17C   
label values ml17c_3  ML17C   
label values ml17c_4  ML17C   
label values ml17c_5  ML17C   
label values ml17c_6  ML17C   
label values ml18a_1  ML18A   
label values ml18a_2  ML18A   
label values ml18a_3  ML18A   
label values ml18a_4  ML18A   
label values ml18a_5  ML18A   
label values ml18a_6  ML18A   
label values ml18b_1  ML18B   
label values ml18b_2  ML18B   
label values ml18b_3  ML18B   
label values ml18b_4  ML18B   
label values ml18b_5  ML18B   
label values ml18b_6  ML18B   
label values ml18c_1  ML18C   
label values ml18c_2  ML18C   
label values ml18c_3  ML18C   
label values ml18c_4  ML18C   
label values ml18c_5  ML18C   
label values ml18c_6  ML18C   
label values ml19a_1  ML19A   
label values ml19a_2  ML19A   
label values ml19a_3  ML19A   
label values ml19a_4  ML19A   
label values ml19a_5  ML19A   
label values ml19a_6  ML19A   
label values ml19b_1  ML19B   
label values ml19b_2  ML19B   
label values ml19b_3  ML19B   
label values ml19b_4  ML19B   
label values ml19b_5  ML19B   
label values ml19b_6  ML19B   
label values ml19c_1  ML19C   
label values ml19c_2  ML19C   
label values ml19c_3  ML19C   
label values ml19c_4  ML19C   
label values ml19c_5  ML19C   
label values ml19c_6  ML19C   
label values ml19d_1  ML19D   
label values ml19d_2  ML19D   
label values ml19d_3  ML19D   
label values ml19d_4  ML19D   
label values ml19d_5  ML19D   
label values ml19d_6  ML19D   
label values ml19e_1  ML19E   
label values ml19e_2  ML19E   
label values ml19e_3  ML19E   
label values ml19e_4  ML19E   
label values ml19e_5  ML19E   
label values ml19e_6  ML19E   
label values ml19f_1  ML19F   
label values ml19f_2  ML19F   
label values ml19f_3  ML19F   
label values ml19f_4  ML19F   
label values ml19f_5  ML19F   
label values ml19f_6  ML19F   
label values ml19x_1  ML19X   
label values ml19x_2  ML19X   
label values ml19x_3  ML19X   
label values ml19x_4  ML19X   
label values ml19x_5  ML19X   
label values ml19x_6  ML19X   
label values ml19y_1  ML19Y   
label values ml19y_2  ML19Y   
label values ml19y_3  ML19Y   
label values ml19y_4  ML19Y   
label values ml19y_5  ML19Y   
label values ml19y_6  ML19Y   
label values ml19z_1  ML19Z   
label values ml19z_2  ML19Z   
label values ml19z_3  ML19Z   
label values ml19z_4  ML19Z   
label values ml19z_5  ML19Z   
label values ml19z_6  ML19Z   
label values ml20a_1  ML20A   
label values ml20a_2  ML20A   
label values ml20a_3  ML20A   
label values ml20a_4  ML20A   
label values ml20a_5  ML20A   
label values ml20a_6  ML20A   
label values ml20b_1  ML20B   
label values ml20b_2  ML20B   
label values ml20b_3  ML20B   
label values ml20b_4  ML20B   
label values ml20b_5  ML20B   
label values ml20b_6  ML20B   
label values ml20c_1  ML20C   
label values ml20c_2  ML20C   
label values ml20c_3  ML20C   
label values ml20c_4  ML20C   
label values ml20c_5  ML20C   
label values ml20c_6  ML20C   
label values ml21a_1  ML21A   
label values ml21a_2  ML21A   
label values ml21a_3  ML21A   
label values ml21a_4  ML21A   
label values ml21a_5  ML21A   
label values ml21a_6  ML21A   
label values ml21b_1  ML21B   
label values ml21b_2  ML21B   
label values ml21b_3  ML21B   
label values ml21b_4  ML21B   
label values ml21b_5  ML21B   
label values ml21b_6  ML21B   
label values ml21c_1  ML21C   
label values ml21c_2  ML21C   
label values ml21c_3  ML21C   
label values ml21c_4  ML21C   
label values ml21c_5  ML21C   
label values ml21c_6  ML21C   
label values ml22a_1  ML22A   
label values ml22a_2  ML22A   
label values ml22a_3  ML22A   
label values ml22a_4  ML22A   
label values ml22a_5  ML22A   
label values ml22a_6  ML22A   
label values ml22b_1  ML22B   
label values ml22b_2  ML22B   
label values ml22b_3  ML22B   
label values ml22b_4  ML22B   
label values ml22b_5  ML22B   
label values ml22b_6  ML22B   
label values ml22c_1  ML22C   
label values ml22c_2  ML22C   
label values ml22c_3  ML22C   
label values ml22c_4  ML22C   
label values ml22c_5  ML22C   
label values ml22c_6  ML22C   
label values ml23a_1  ML23A   
label values ml23a_2  ML23A   
label values ml23a_3  ML23A   
label values ml23a_4  ML23A   
label values ml23a_5  ML23A   
label values ml23a_6  ML23A   
label values ml23b_1  ML23B   
label values ml23b_2  ML23B   
label values ml23b_3  ML23B   
label values ml23b_4  ML23B   
label values ml23b_5  ML23B   
label values ml23b_6  ML23B   
label values ml23c_1  ML23C   
label values ml23c_2  ML23C   
label values ml23c_3  ML23C   
label values ml23c_4  ML23C   
label values ml23c_5  ML23C   
label values ml23c_6  ML23C   
label values ml24c_1  ML24C   
label values ml24c_2  ML24C   
label values ml24c_3  ML24C   
label values ml24c_4  ML24C   
label values ml24c_5  ML24C   
label values ml24c_6  ML24C   
label values ml25a_1  ML25A   
label values ml25a_2  ML25A   
label values ml25a_3  ML25A   
label values ml25a_4  ML25A   
label values ml25a_5  ML25A   
label values ml25a_6  ML25A   
label values sdistrict SDISTRICT
label values s105     S105    
label values s105a    S105A   
label values s111     S111    
label values s114     S114    
label values s211     S211    
label values s501     S501    
label values s502a    S502A   
label values s502b    S502B   
label values s502c    S502C   
label values s502d    S502D   
label values s502e    S502E   
label values s502f    S502F   
label values s502g    S502G   
label values s502h    S502H   
label values s502i    S502I   
label values s502j    S502J   
label values s502x    S502X   
label values s502z    S502Z   
label values s503a    S503A   
label values s503b    S503B   
label values s503c    S503C   
label values s503d    S503D   
label values s503e    S503E   
label values s503f    S503F   
label values s503g    S503G   
label values s503h    S503H   
label values s503i    S503I   
label values s503j    S503J   
label values s504a    S504A   
label values s504b    S504B   
label values s504c    S504C   
label values s504d    S504D   
label values s504e    S504E   
label values s504f    S504F   
label values s504g    S504G   
label values s504h    S504H   
label values s504x    S504X   
label values s504z    S504Z   
label values s505a    S505A   
label values s505b    S505B   
label values s505c    S505C   
label values s505d    S505D   
label values s506     S506    
label values s507a    S507A   
label values s507b    S507B   
label values s507c    S507C   
label values s507d    S507D   
label values s507e    S507E   
label values s507x    S507X   
label values s507z    S507Z   
label values s508a    S508A   
label values s508b    S508B   
label values s508c    S508C   
label values s508d    S508D   
label values s508e    S508E   
label values s508f    S508F   
label values s508g    S508G   
label values s508h    S508H   
label values s508x    S508X   
label values s508z    S508Z   
label values s509     S509    
label values s510     S510    
label values s511     S511    
label values s512     S512    
label values s305ba_1 S305BA  
label values s305ba_2 S305BA  
label values s305ba_3 S305BA  
label values s305ba_4 S305BA  
label values s305ba_5 S305BA  
label values s305ba_6 S305BA  
label values s305bb_1 S305BB  
label values s305bb_2 S305BB  
label values s305bb_3 S305BB  
label values s305bb_4 S305BB  
label values s305bb_5 S305BB  
label values s305bb_6 S305BB  
label values s305bc_1 S305BC  
label values s305bc_2 S305BC  
label values s305bc_3 S305BC  
label values s305bc_4 S305BC  
label values s305bc_5 S305BC  
label values s305bc_6 S305BC  
label values s305bd_1 S305BD  
label values s305bd_2 S305BD  
label values s305bd_3 S305BD  
label values s305bd_4 S305BD  
label values s305bd_5 S305BD  
label values s305bd_6 S305BD  
label values s305be_1 S305BE  
label values s305be_2 S305BE  
label values s305be_3 S305BE  
label values s305be_4 S305BE  
label values s305be_5 S305BE  
label values s305be_6 S305BE  
label values s305bf_1 S305BF  
label values s305bf_2 S305BF  
label values s305bf_3 S305BF  
label values s305bf_4 S305BF  
label values s305bf_5 S305BF  
label values s305bf_6 S305BF  
label values s305bg_1 S305BG  
label values s305bg_2 S305BG  
label values s305bg_3 S305BG  
label values s305bg_4 S305BG  
label values s305bg_5 S305BG  
label values s305bg_6 S305BG  
label values s305bx_1 S305BX  
label values s305bx_2 S305BX  
label values s305bx_3 S305BX  
label values s305bx_4 S305BX  
label values s305bx_5 S305BX  
label values s305bx_6 S305BX  
label values s305bz_1 S305BZ  
label values s305bz_2 S305BZ  
label values s305bz_3 S305BZ  
label values s305bz_4 S305BZ  
label values s305bz_5 S305BZ  
label values s305bz_6 S305BZ  
label values s403a_1  S403A   
label values s403a_2  S403A   
label values s403a_3  S403A   
label values s403a_4  S403A   
label values s403a_5  S403A   
label values s403a_6  S403A   
label values s405a_1  S405A   
label values s405a_2  S405A   
label values s405a_3  S405A   
label values s405a_4  S405A   
label values s405a_5  S405A   
label values s405a_6  S405A   
label values s407ba_1 S407BA  
label values s407ba_2 S407BA  
label values s407ba_3 S407BA  
label values s407ba_4 S407BA  
label values s407ba_5 S407BA  
label values s407ba_6 S407BA  
label values s407bb_1 S407BB  
label values s407bb_2 S407BB  
label values s407bb_3 S407BB  
label values s407bb_4 S407BB  
label values s407bb_5 S407BB  
label values s407bb_6 S407BB  
label values s407bc_1 S407BC  
label values s407bc_2 S407BC  
label values s407bc_3 S407BC  
label values s407bc_4 S407BC  
label values s407bc_5 S407BC  
label values s407bc_6 S407BC  
label values s407bd_1 S407BD  
label values s407bd_2 S407BD  
label values s407bd_3 S407BD  
label values s407bd_4 S407BD  
label values s407bd_5 S407BD  
label values s407bd_6 S407BD  
label values s407be_1 S407BE  
label values s407be_2 S407BE  
label values s407be_3 S407BE  
label values s407be_4 S407BE  
label values s407be_5 S407BE  
label values s407be_6 S407BE  
label values s407bf_1 S407BF  
label values s407bf_2 S407BF  
label values s407bf_3 S407BF  
label values s407bf_4 S407BF  
label values s407bf_5 S407BF  
label values s407bf_6 S407BF  
label values s407bg_1 S407BG  
label values s407bg_2 S407BG  
label values s407bg_3 S407BG  
label values s407bg_4 S407BG  
label values s407bg_5 S407BG  
label values s407bg_6 S407BG  
label values s407bh_1 S407BH  
label values s407bh_2 S407BH  
label values s407bh_3 S407BH  
label values s407bh_4 S407BH  
label values s407bh_5 S407BH  
label values s407bh_6 S407BH  
label values s407bi_1 S407BI  
label values s407bi_2 S407BI  
label values s407bi_3 S407BI  
label values s407bi_4 S407BI  
label values s407bi_5 S407BI  
label values s407bi_6 S407BI  
label values s407bx_1 S407BX  
label values s407bx_2 S407BX  
label values s407bx_3 S407BX  
label values s407bx_4 S407BX  
label values s407bx_5 S407BX  
label values s407bx_6 S407BX  
label values s412ba_1 S412BA  
label values s412ba_2 S412BA  
label values s412ba_3 S412BA  
label values s412ba_4 S412BA  
label values s412ba_5 S412BA  
label values s412ba_6 S412BA  
label values s412bb_1 S412BB  
label values s412bb_2 S412BB  
label values s412bb_3 S412BB  
label values s412bb_4 S412BB  
label values s412bb_5 S412BB  
label values s412bb_6 S412BB  
label values s412bc_1 S412BC  
label values s412bc_2 S412BC  
label values s412bc_3 S412BC  
label values s412bc_4 S412BC  
label values s412bc_5 S412BC  
label values s412bc_6 S412BC  
label values s412bd_1 S412BD  
label values s412bd_2 S412BD  
label values s412bd_3 S412BD  
label values s412bd_4 S412BD  
label values s412bd_5 S412BD  
label values s412bd_6 S412BD  
label values s412be_1 S412BE  
label values s412be_2 S412BE  
label values s412be_3 S412BE  
label values s412be_4 S412BE  
label values s412be_5 S412BE  
label values s412be_6 S412BE  
label values s412bf_1 S412BF  
label values s412bf_2 S412BF  
label values s412bf_3 S412BF  
label values s412bf_4 S412BF  
label values s412bf_5 S412BF  
label values s412bf_6 S412BF  
label values s412bg_1 S412BG  
label values s412bg_2 S412BG  
label values s412bg_3 S412BG  
label values s412bg_4 S412BG  
label values s412bg_5 S412BG  
label values s412bg_6 S412BG  
label values s412bh_1 S412BH  
label values s412bh_2 S412BH  
label values s412bh_3 S412BH  
label values s412bh_4 S412BH  
label values s412bh_5 S412BH  
label values s412bh_6 S412BH  
label values s412bi_1 S412BI  
label values s412bi_2 S412BI  
label values s412bi_3 S412BI  
label values s412bi_4 S412BI  
label values s412bi_5 S412BI  
label values s412bi_6 S412BI  
label values s412bj_1 S412BJ  
label values s412bj_2 S412BJ  
label values s412bj_3 S412BJ  
label values s412bj_4 S412BJ  
label values s412bj_5 S412BJ  
label values s412bj_6 S412BJ  
label values s412bk_1 S412BK  
label values s412bk_2 S412BK  
label values s412bk_3 S412BK  
label values s412bk_4 S412BK  
label values s412bk_5 S412BK  
label values s412bk_6 S412BK  
label values s412bx_1 S412BX  
label values s412bx_2 S412BX  
label values s412bx_3 S412BX  
label values s412bx_4 S412BX  
label values s412bx_5 S412BX  
label values s412bx_6 S412BX  
