infix using "C:\COUNTRIES\KE72\KEMR72FL.dct"

label variable mcaseid  "Case Identification"
label variable mv000    "Country code and phase"
label variable mv001    "Cluster number"
label variable mv002    "Household number"
label variable mv003    "Respondent's line number"
label variable mv004    "Ultimate area unit"
label variable mv005    "Men's sample weight (6 decimals)"
label variable mv006    "Month of interview"
label variable mv007    "Year of interview"
label variable mv008    "Date of interview (CMC)"
label variable mv009    "Month of birth"
label variable mv010    "Year of birth"
label variable mv011    "Date of birth (CMC)"
label variable mv012    "Current age"
label variable mv013    "Age in 5-year groups"
label variable mv014    "Completeness of age information"
label variable mv015    "Result of interview"
label variable mv016    "Day of interview"
label variable mv021    "Primary sampling unit"
label variable mv022    "Sample stratum number"
label variable mv023    "Sample domain"
label variable mv024    "Region"
label variable mv025    "Type of place of residence"
label variable mv026    "NA - De facto place of residence"
label variable mv027    "Number of visits"
label variable mv028    "Interviewer identification"
label variable mv029    "Keyer identification"
label variable mv030    "Field supervisor"
label variable mv031    "Field editor"
label variable mv032    "Office editor"
label variable mv034_1  "Line number of wife/partner"
label variable mv034_2  "Line number of wife/partner"
label variable mv034_3  "Line number of wife/partner"
label variable mv034_4  "Line number of wife/partner"
label variable mv034_5  "Line number of wife/partner"
label variable mv034_6  "Line number of wife/partner"
label variable mv034_7  "Line number of wife/partner"
label variable mv034_8  "Line number of wife/partner"
label variable mv034a_1 "NA - Wife or partner***"
label variable mv034a_2 "NA - Wife or partner***"
label variable mv034a_3 "NA - Wife or partner***"
label variable mv034a_4 "NA - Wife or partner***"
label variable mv034a_5 "NA - Wife or partner***"
label variable mv034a_6 "NA - Wife or partner***"
label variable mv034a_7 "NA - Wife or partner***"
label variable mv034a_8 "NA - Wife or partner***"
label variable mv034b_1 "Age of wife/partner"
label variable mv034b_2 "Age of wife/partner"
label variable mv034b_3 "Age of wife/partner"
label variable mv034b_4 "Age of wife/partner"
label variable mv034b_5 "Age of wife/partner"
label variable mv034b_6 "Age of wife/partner"
label variable mv034b_7 "Age of wife/partner"
label variable mv034b_8 "Age of wife/partner"
label variable mv035    "Number of wives/partners"
label variable mv801    "Time interview started (hhmm - 24 hour clock)"
label variable mv802    "Time interview ended (hhmm - 24 hour clock)"
label variable mv803    "Length of interview in minutes"
label variable mv101    "Region"
label variable mv102    "Type of place of residence"
label variable mv103    "Childhood place of residence***"
label variable mv104    "Years lived in place of residence"
label variable mv105    "Type of place of previous residence"
label variable mv106    "Educational level"
label variable mv107    "Highest year of education (at level in MV106)"
label variable mv130    "Religion"
label variable mv131    "Ethnicity"
label variable mv133    "Total number of years of education"
label variable mv134    "NA - De facto place of residence"
label variable mv135    "Usual resident or visitor"
label variable mv136    "Number of household members (total listed)"
label variable mv138    "Number of eligible men in household (de facto)"
label variable mv149    "Educational attainment"
label variable mv150    "Relationship to household head"
label variable mv151    "Sex of household head"
label variable mv152    "Age of household head"
label variable mv155    "Literacy"
label variable mv156    "NA - Ever participated in a literacy program (excluding primary school)"
label variable mv157    "Frequency of reading newspaper or magazine"
label variable mv158    "Frequency of listening to radio"
label variable mv159    "Frequency of watching television"
label variable mv167    "Times away from home in last 12 months"
label variable mv168    "Away for more than one month in last 12 months"
label variable mv190    "Wealth index"
label variable mv191    "Wealth index factor score (5 decimals)"
label variable mv201    "Total children ever born"
label variable mv202    "Sons at home"
label variable mv203    "Daughters at home"
label variable mv204    "Sons elsewhere"
label variable mv205    "Daughters elsewhere"
label variable mv206    "Sons who have died"
label variable mv207    "Daughters who have died"
label variable mv212    "Age of respondent at 1st birth"
label variable mv213    "Partner currently pregnant"
label variable mv217    "Knowledge of ovulatory cycle"
label variable mv218    "Number of living children"
label variable mv225    "NA - Most recent pregnancy wanted***"
label variable mv245    "Number of women fathered children with"
label variable mv246    "NA - Married to mother when first child was born***"
label variable mv247    "Age of most recent child"
label variable mv248    "Antenatal check-ups for the mother of most recent child"
label variable mv249    "Respondent present during check-ups for most recent child"
label variable mv250    "Place of birth of most recent child"
label variable mv251    "NA - Reason for not delivering most recent child in health facility"
label variable mv252    "Amount a child should drink, when that child has diarrhea"
label variable mv301    "Knowledge of any contraceptive method"
label variable mv302    "NA - Ever use of any contraceptive method"
label variable m304a_01 "Type of contraceptive method"
label variable m304a_02 "Type of contraceptive method"
label variable m304a_03 "Type of contraceptive method"
label variable m304a_04 "Type of contraceptive method"
label variable m304a_05 "Type of contraceptive method"
label variable m304a_06 "Type of contraceptive method"
label variable m304a_07 "Type of contraceptive method"
label variable m304a_08 "Type of contraceptive method"
label variable m304a_09 "Type of contraceptive method"
label variable m304a_10 "Type of contraceptive method"
label variable m304a_11 "Type of contraceptive method"
label variable m304a_12 "Type of contraceptive method"
label variable m304a_13 "Type of contraceptive method"
label variable m304a_14 "Type of contraceptive method"
label variable m304a_15 "Type of contraceptive method"
label variable m304a_16 "Type of contraceptive method"
label variable m304a_17 "Type of contraceptive method"
label variable m304a_18 "Type of contraceptive method"
label variable m304a_19 "Type of contraceptive method"
label variable m304a_20 "Type of contraceptive method"
label variable mv304_01 "Knows contraceptive method"
label variable mv304_02 "Knows contraceptive method"
label variable mv304_03 "Knows contraceptive method"
label variable mv304_04 "Knows contraceptive method"
label variable mv304_05 "Knows contraceptive method"
label variable mv304_06 "Knows contraceptive method"
label variable mv304_07 "Knows contraceptive method"
label variable mv304_08 "Knows contraceptive method"
label variable mv304_09 "Knows contraceptive method"
label variable mv304_10 "Knows contraceptive method"
label variable mv304_11 "Knows contraceptive method"
label variable mv304_12 "Knows contraceptive method"
label variable mv304_13 "Knows contraceptive method"
label variable mv304_14 "Knows contraceptive method"
label variable mv304_15 "Knows contraceptive method"
label variable mv304_16 "Knows contraceptive method"
label variable mv304_17 "Knows contraceptive method"
label variable mv304_18 "Knows contraceptive method"
label variable mv304_19 "Knows contraceptive method"
label variable mv304_20 "Knows contraceptive method"
label variable mv305_01 "NA - Ever used contraceptive method"
label variable mv305_02 "NA - Ever used contraceptive method"
label variable mv305_03 "NA - Ever used contraceptive method"
label variable mv305_04 "NA - Ever used contraceptive method"
label variable mv305_05 "NA - Ever used contraceptive method"
label variable mv305_06 "NA - Ever used contraceptive method"
label variable mv305_07 "NA - Ever used contraceptive method"
label variable mv305_08 "NA - Ever used contraceptive method"
label variable mv305_09 "NA - Ever used contraceptive method"
label variable mv305_10 "NA - Ever used contraceptive method"
label variable mv305_11 "NA - Ever used contraceptive method"
label variable mv305_12 "NA - Ever used contraceptive method"
label variable mv305_13 "NA - Ever used contraceptive method"
label variable mv305_14 "NA - Ever used contraceptive method"
label variable mv305_15 "NA - Ever used contraceptive method"
label variable mv305_16 "NA - Ever used contraceptive method"
label variable mv305_17 "NA - Ever used contraceptive method"
label variable mv305_18 "NA - Ever used contraceptive method"
label variable mv305_19 "NA - Ever used contraceptive method"
label variable mv305_20 "NA - Ever used contraceptive method"
label variable mv307_01 "Contraceptive method currently used"
label variable mv307_02 "Contraceptive method currently used"
label variable mv307_03 "Contraceptive method currently used"
label variable mv307_04 "Contraceptive method currently used"
label variable mv307_05 "Contraceptive method currently used"
label variable mv307_06 "Contraceptive method currently used"
label variable mv307_07 "Contraceptive method currently used"
label variable mv307_08 "Contraceptive method currently used"
label variable mv307_09 "Contraceptive method currently used"
label variable mv307_10 "Contraceptive method currently used"
label variable mv307_11 "Contraceptive method currently used"
label variable mv307_12 "Contraceptive method currently used"
label variable mv307_13 "Contraceptive method currently used"
label variable mv307_14 "Contraceptive method currently used"
label variable mv307_15 "Contraceptive method currently used"
label variable mv307_16 "Contraceptive method currently used"
label variable mv307_17 "Contraceptive method currently used"
label variable mv307_18 "Contraceptive method currently used"
label variable mv307_19 "Contraceptive method currently used"
label variable mv307_20 "Contraceptive method currently used"
label variable mv312    "Current contraceptive method"
label variable mv313    "Current contraceptive by method type"
label variable mv323a   "NA - Brand of condom used"
label variable mv325b   "NA - Cost of condoms (in CURRENCY) last time obtained"
label variable mv372a   "NA - Interviewer shown condom package"
label variable mv384a   "On radio heard about Family Planning in the last few months"
label variable mv384b   "On TV saw about Family Planning in the last few months"
label variable mv384c   "In newspaper read about Family Planning in the last few months"
label variable mv395    "Discussed Family Planning with health worker in last few months"
label variable mv396    "NA - Possible for a breastfeeding woman to get pregnant"
label variable mv3a09b  "NA - Number of condoms did get last time"
label variable mv3b17   "Source of condoms"
label variable mv3b25a  "Contraception is woman's business, man should not worry"
label variable mv3b25b  "Women who use contraception become promiscuous"
label variable mv463a   "Smokes cigarettes"
label variable mv463b   "Smokes pipe"
label variable mv463c   "Uses chewing tobacco"
label variable mv463d   "Uses snuff"
label variable mv463e   "Smokes CS: water pipe"
label variable mv463f   "NA - Smokes CS"
label variable mv463g   "NA - Smokes CS"
label variable mv463x   "Smokes other"
label variable mv463z   "Smokes nothing"
label variable mv464    "Number of cigarettes in last 24 hours"
label variable mv474    "Heard of tuberculosis or TB"
label variable mv474a   "Tuberculosis spread by: air through coughing or sneezing"
label variable mv474b   "Tuberculosis spread by: sharing utensils"
label variable mv474c   "Tuberculosis spread by: touching a person with TB"
label variable mv474d   "Tuberculosis spread by: food"
label variable mv474e   "Tuberculosis spread by: sexual contact"
label variable mv474f   "Tuberculosis spread by: mosquito bites"
label variable mv474g   "NA - Tuberculosis spread by: CS"
label variable mv474h   "NA - Tuberculosis spread by: CS"
label variable mv474i   "NA - Tuberculosis spread by: CS"
label variable mv474j   "NA - Tuberculosis spread by: CS"
label variable mv474x   "Tuberculosis spread by: other"
label variable mv474z   "Don't know how tuberculosis is spread"
label variable mv475    "NA - Tuberculosis can be cured"
label variable mv476    "NA - Would want tuberculosis infection in family to remain secret"
label variable mv477    "Number of injections in last 12 months"
label variable mv478    "Number of injections administered by a health worker"
label variable mv479    "NA - Place where given injection by health worker"
label variable mv480    "Syringe and needle from new, unopened package"
label variable mv481    "Covered by health insurance"
label variable mv481a   "Health insurance type: mutual/community organization"
label variable mv481b   "Health insurance type: provided by employer"
label variable mv481c   "Health insurance type: social security"
label variable mv481d   "Health insurance type: private/commercially purchased"
label variable mv481e   "Health insurance type: CS - Pre-payment scheme"
label variable mv481f   "NA - Health insurance type: CS"
label variable mv481g   "NA - Health insurance type: CS"
label variable mv481h   "NA - Health insurance type: CS"
label variable mv481x   "Health insurance type: other"
label variable mv482a   "NA - Arrange care of biological children under age 18***"
label variable mv482b   "NA - Primary caregiver of children under age 18***"
label variable mv482c   "NA - Arrange care of non-biological children < 18***"
label variable mv483    "Respondent circumcised"
label variable mv483a   "Age at circumcision"
label variable mv483b   "Who performed the circumcision"
label variable mv483c   "Place where circumcision was done"
label variable mv501    "Current marital status"
label variable mv502    "Currently/formerly/never in union"
label variable mv503    "Number of unions"
label variable mv504    "Currently residing with wife/partner"
label variable mv505    "Number of wives/partners"
label variable mv507    "Month of first cohabitation"
label variable mv508    "Year of first cohabitation"
label variable mv509    "Date of first cohabitation (CMC)"
label variable mv510    "Completeness of date information in MV509"
label variable mv511    "Age at first cohabitation"
label variable mv512    "Years since first cohabitation"
label variable mv513    "Cohabitation duration (grouped)"
label variable mv525    "Age at first sex"
label variable mv527    "Time since last sex"
label variable mv528    "Time since last sex (in days)"
label variable mv529    "Time since last sex (in months)"
label variable mv531    "Age at first sex (imputed)"
label variable mv532    "Flag for MV531"
label variable mv535    "Ever been married or in union"
label variable mv536    "Recent sexual activity"
label variable mv541    "NA - Intends to wait until marriage to have sex"
label variable mv602    "Fertility preference"
label variable mv603    "Preferred waiting time for birth of a/another child"
label variable mv604    "Preferred waiting time for birth of a/another child (grouped)"
label variable mv605    "Desire for more children"
label variable mv613    "Ideal number of children"
label variable mv614    "Ideal number of children (grouped)"
label variable mv616    "Desired time for future birth"
label variable mv621    "NA - Wife's desire for children***"
label variable mv627    "Ideal number of boys"
label variable mv628    "Ideal number of girls"
label variable mv629    "Ideal number of either sex"
label variable mv631    "NA - Problem if wife became pregnant***"
label variable mv633a   "NA - Wife justified refusing sex: husband has STI"
label variable mv633b   "Wife justified refusing sex: husband has other women"
label variable mv633c   "NA - Wife justified refusing sex: recent birth"
label variable mv633d   "NA - Wife justified refusing sex: tired, not in mood"
label variable mv633e   "NA - Wife justified refusing sex: CS reason"
label variable mv633f   "NA - Wife justified refusing sex: CS reason"
label variable mv633g   "NA - Wife justified refusing sex: CS reason"
label variable mv634a   "NA - Wife refuses to have sex, husband has right to: get angry"
label variable mv634b   "NA - Wife refuses to have sex, husband has right to: refuse financial support"
label variable mv634c   "NA - Wife refuses to have sex, husband has right to: use force for sex"
label variable mv634d   "NA - Wife refuses to have sex, husband has right to: have sex with another women"
label variable mv714    "Currently working"
label variable mv714a   "Have a job, but currently absent"
label variable mv716    "Occupation"
label variable mv717    "Occupation (grouped)"
label variable mv719    "NA - Works for family, others, self"
label variable mv721    "NA - Works at home or away"
label variable mv731    "Worked in last 12 months"
label variable mv732    "Employment all year/seasonal"
label variable mv739    "Person who usually decides how to spend respondent's earnings"
label variable mv740    "NA - Type of land where respondent works"
label variable mv741    "Type of earnings from respondent's work"
label variable mv743a   "Person who should have greater say: respondent's health care"
label variable mv743b   "Person who should have greater say: large household purchases"
label variable mv743c   "NA - Person who should have greater say: daily household purchases"
label variable mv743d   "NA - Person who should have greater say: visits to family or relatives"
label variable mv743e   "NA - Person who should have greater say: food to be cooked each day"
label variable mv743f   "NA - Person who should have greater say: deciding what to do with money wife ear"
label variable mv743g   "NA - Person who should have greater say: deciding how many children to have"
label variable mv744a   "Beating justified: wife goes out without telling husband"
label variable mv744b   "Beating justified: wife neglects the children"
label variable mv744c   "Beating justified: wife argues with husband"
label variable mv744d   "Beating justified: wife refuses to have sex with husband"
label variable mv744e   "Beating justified: wife burns food"
label variable mv745a   "Owns a house alone or jointly"
label variable mv745b   "Owns land alone or jointly"
label variable mv747a   "NA - Childbearing is a woman's concern"
label variable mv747b   "NA - Important for mother/child health to get assistance at delivery"
label variable mv750    "Ever heard of a Sexually Transmitted Infection (STI)"
label variable mv751    "Ever heard of AIDS"
label variable mv754bp  "Reduce risk of getting HIV: do not have sex at all"
label variable mv754cp  "Reduce risk of getting HIV: always use condoms during sex"
label variable mv754dp  "Reduce risk of getting HIV: have 1 sex partner only, who has no other partners"
label variable mv754jp  "Can get HIV from mosquito bites"
label variable mv754wp  "Can get HIV by sharing food with person who has AIDS"
label variable mv756    "A healthy looking person can have HIV"
label variable mv761    "Condom used during last sex with most recent partner"
label variable mv761b   "Condom used during last sex with 2nd to most recent partner"
label variable mv761c   "Condom used during last sex with 3rd to most recent partner"
label variable mv762aa  "Source for condoms: government hospital"
label variable mv762ab  "Source for condoms: government health center"
label variable mv762ac  "Source for condoms: government dispensary"
label variable mv762ad  "Source for condoms: other public sector"
label variable mv762ae  "NA - Source for condoms: CS public"
label variable mv762af  "NA - Source for condoms: CS public"
label variable mv762ag  "NA - Source for condoms: CS public"
label variable mv762ah  "NA - Source for condoms: CS public"
label variable mv762ai  "NA - Source for condoms: CS public"
label variable mv762aj  "Source for condoms: private hospital/clinic"
label variable mv762ak  "Source for condoms: pharmacy"
label variable mv762al  "NA - Source for condoms: private doctor"
label variable mv762am  "Source for condoms: nursing/maternity home"
label variable mv762an  "Source for condoms: faith-based, church, mission hospital, clinic"
label variable mv762ao  "Source for condoms: family options/FHOK clinic"
label variable mv762ap  "Source for condoms: other private medical sector"
label variable mv762aq  "Source for condoms: mobile clinic"
label variable mv762ar  "NA - Source for condoms: CS private"
label variable mv762as  "Source for condoms: shop"
label variable mv762at  "Source for condoms: community-based distributor"
label variable mv762au  "Source for condoms: community health worker/CHW"
label variable mv762av  "Source for condoms: friend/relative"
label variable mv762aw  "Source for condoms: dispenser"
label variable mv762ax  "Source for condoms: other"
label variable mv762az  "Don't know any source for condoms"
label variable mv762ba  "Source for female condoms: government hospital"
label variable mv762bb  "Source for female condoms: government health center"
label variable mv762bc  "Source for female condoms: government dispensary"
label variable mv762bd  "Source for female condoms: other public sector"
label variable mv762be  "NA - Source for female condoms: CS public"
label variable mv762bf  "NA - Source for female condoms: CS public"
label variable mv762bg  "NA - Source for female condoms: CS public"
label variable mv762bh  "NA - Source for female condoms: CS public"
label variable mv762bi  "NA - Source for female condoms: CS public"
label variable mv762bj  "Source for female condoms: private hospital/clinic"
label variable mv762bk  "Source for female condoms: pharmacy"
label variable mv762bl  "NA - Source for female condoms: private doctor"
label variable mv762bm  "Source for female condoms: nursing/maternity home"
label variable mv762bn  "Source for female condoms: faith-based/church/mission hospital/ clinic"
label variable mv762bo  "Source for female condoms: family options/ FHOK clinic"
label variable mv762bp  "Source for female condoms: other private"
label variable mv762bq  "NA - Source for female condoms: CS private"
label variable mv762br  "NA - Source for female condoms: CS private"
label variable mv762bs  "Source for female condoms: shop"
label variable mv762bt  "Source for female condoms: mobile clinic"
label variable mv762bu  "Source for female condoms: community-based distributor"
label variable mv762bv  "Source for female condoms: community-health worker/CHW"
label variable mv762bw  "Source for female condoms: friend/relative"
label variable mv762bx  "Source for female condoms: other"
label variable mv762bz  "Don't know any source for female condoms"
label variable mv763a   "Had any STI in last 12 months"
label variable mv763b   "Had genital sore/ulcer in last 12 months"
label variable mv763c   "Had genital discharge in last 12 months"
label variable mv763d   "NA - Had CS STI in last 12 months"
label variable mv763e   "NA - Had CS STI in last 12 months"
label variable mv763f   "NA - Had CS STI in last 12 months"
label variable mv763g   "NA - Had CS STI in last 12 months"
label variable mv766a   "Number of sex partners, excluding spouse, in last 12 months"
label variable mv766b   "Number of sex partners, including spouse, in last 12 months"
label variable mv767a   "Relationship with most recent sex partner"
label variable mv767b   "Relationship with 2nd to most recent sex partner"
label variable mv767c   "Relationship with 3rd to most recent sex partner"
label variable mv768a   "NA - Length of time had sex relations with most recent partner"
label variable mv768b   "NA - Length of time had sex relations with 2nd to most recent partner"
label variable mv768c   "NA - Length of time had sex relations with 3rd to most recent partner"
label variable mv769    "Can get a condom"
label variable mv769a   "Can get a female condom"
label variable mv770    "Sought advice/treatment for last STI infection"
label variable mv770a   "Sought STI advice/treatment from: government hospital"
label variable mv770b   "Sought STI advice/treatment from: government health centre/clinic"
label variable mv770c   "Sought STI advice/treatment from: government dispensary"
label variable mv770d   "Sought STI advice/treatment from: other public"
label variable mv770e   "NA - Sought STI advice/treatment from: CS public"
label variable mv770f   "NA - Sought STI advice/treatment from: CS public"
label variable mv770g   "NA - Sought STI advice/treatment from: CS public"
label variable mv770h   "NA - Sought STI advice/treatment from: CS public"
label variable mv770i   "NA - Sought STI advice/treatment from: CS public"
label variable mv770j   "NA - Sought STI advice/treatment from: CS public"
label variable mv770k   "Sought STI advice/treatment from: private hospital/clinic/doctor"
label variable mv770l   "Sought STI advice/treatment from: missionary/church hospital/clinic"
label variable mv770m   "Sought STI advice/treatment from: family option/FHOK clinic"
label variable mv770n   "Sought STI advice/treatment from: VCT centre"
label variable mv770o   "Sought STI advice/treatment from: nursing/maternity homes"
label variable mv770p   "Sought STI advice/treatment from: blood transfusion services"
label variable mv770q   "Sought STI advice/treatment from: other private"
label variable mv770r   "NA - Sought STI advice/treatment from: CS private"
label variable mv770s   "NA - Sought STI advice/treatment from: CS private"
label variable mv770t   "Sought STI advice/treatment from: shop/pharmacy"
label variable mv770u   "Sought STI advice/treatment from: traditional healer"
label variable mv770v   "Sought STI advice/treatment from: friends/relatives"
label variable mv770w   "NA - Sought STI advice/treatment from: CS other"
label variable mv770x   "Sought STI advice/treatment from: other"
label variable mv774a   "HIV transmitted during pregnancy"
label variable mv774b   "HIV transmitted during delivery"
label variable mv774c   "HIV transmitted by breastfeeding"
label variable mv775    "NA - Knows someone who has, or is suspected of having, HIV"
label variable mv777    "Would want HIV infection in family to remain secret"
label variable mv778    "Willing to care for relative with AIDS"
label variable mv779    "A female teacher infected with HIV, but is not sick, should be allowed to contin"
label variable mv780    "Children should be taught about condoms to avoid AIDS"
label variable mv781    "Ever been tested for HIV"
label variable mv783    "Know a place to get HIV test"
label variable mv784a   "Place for HIV test: government hospital"
label variable mv784b   "Place for HIV test: government health center/clinic"
label variable mv784c   "Place for HIV test: Government dispensary"
label variable mv784d   "Place for HIV test: Other public sector"
label variable mv784e   "NA - Place for HIV test: CS public"
label variable mv784f   "NA - Place for HIV test: CS public"
label variable mv784g   "NA - Place for HIV test: CS public"
label variable mv784h   "NA - Place for HIV test: CS public"
label variable mv784i   "NA - Place for HIV test: CS public"
label variable mv784j   "NA - Place for HIV test: CS public"
label variable mv784k   "Place for HIV test: private hospital/clinic/doctor"
label variable mv784l   "Place for HIV test: missionary health hospital"
label variable mv784m   "Place for HIV test: family options/FHOK clinic"
label variable mv784n   "Place for HIV test: VCT center"
label variable mv784o   "Place for HIV test: nursing/ maternity homes"
label variable mv784p   "Place for HIV test: blood transfusion services"
label variable mv784q   "Place for HIV test: other private medical sector"
label variable mv784r   "NA - Place for HIV test: CS private"
label variable mv784s   "NA - Place for HIV test: CS other"
label variable mv784t   "NA - Place for HIV test: CS other"
label variable mv784u   "NA - Place for HIV test: CS other"
label variable mv784v   "NA - Place for HIV test: CS other"
label variable mv784x   "Place for HIV test: other"
label variable mv785    "Heard about other STIs"
label variable mv791    "Have ever paid anyone in exchange for sex"
label variable mv793    "Paid for sex in last 12 months"
label variable mv793a   "Condom used last time paid for sex in last 12 months"
label variable mv793b   "Condom used every time paid for sex in last 12 months"
label variable mv820    "Condom used at first sex"
label variable mv822    "Wife justified asking husband to use condom if he has STI"
label variable mv823    "Can get HIV by witchcraft or supernatural means"
label variable mv824    "Drugs to avoid HIV transmission to baby during pregnancy"
label variable mv825    "Would buy vegetables from vendor with HIV"
label variable mv826    "NA - Last time tested for HIV"
label variable mv826a   "Months ago most recent HIV test"
label variable mv827    "NA - Last HIV test: on your own, offered or required"
label variable mv828    "Received result from last HIV test"
label variable mv829    "Place where last HIV test was taken"
label variable mv832b   "Time since last sex with 2nd to most recent partner"
label variable mv832c   "Time since last sex with 3rd to most recent partner"
label variable mv833a   "Used condom every time had sex with most recent partner in last 12 months"
label variable mv833b   "Used condom every time had sex with 2nd to most recent partner in last 12 months"
label variable mv833c   "Used condom every time had sex with 3rd to most recent partner in last 12 months"
label variable mv834a   "Age of most recent partner"
label variable mv834b   "Age of 2nd to most recent partner"
label variable mv834c   "Age of 3rd to most recent partner"
label variable mv835a   "NA - Alcohol consumption at last sex with most recent partner"
label variable mv835b   "NA - Alcohol consumption at last sex with 2nd to most recent partner"
label variable mv835c   "NA - Alcohol consumption at last sex with 3rd to most recent partner"
label variable mv836    "Total lifetime number of sex partners"
label variable mv837    "NA - Heard of drugs to help HIV infected people live longer"
label variable mv844    "NA - Knows someone denied health services for having, or suspected of having, HI"
label variable mv845    "NA - Knows someone denied social event for having, or suspected of having, HIV; "
label variable mv846    "NA - Knows someone verbally abused for having, or suspected of having, HIV; in l"
label variable mv847    "NA - People with HIV should be ashamed of themselves"
label variable mv848    "NA - People with HIV should be blamed for bringing disease to community"
label variable mv849    "NA - Children 12-14 should be taught to wait for sex until marriage"
label variable mv851a   "NA - Young men should wait for sex until marriage"
label variable mv851b   "NA - Most young men wait for sex until marriage"
label variable mv851c   "NA - Unmarried sexually active men should have only one partner"
label variable mv851d   "NA - Most unmarried sexually active men have only one partner"
label variable mv851e   "NA - Married men should only have sex with their wives"
label variable mv851f   "NA - Most married men only have sex with their wives"
label variable mv851g   "NA - Young women should wait for sex until marriage"
label variable mv851h   "NA - Most young women wait for sex until marriage"
label variable mv851i   "NA - Unmarried sexually active women should have only one partner"
label variable mv851j   "NA - Most unmarried sexually active women have only one partner"
label variable mv851k   "NA - Married women should only have sex with their husbands"
label variable mv851l   "NA - Most married women only have sex with their husbands"
label variable mv852a   "How long ago first had sex with most recent partner"
label variable mv852b   "How long ago first had sex with 2nd most recent partner"
label variable mv852c   "How long ago first had sex with 3rd most recent partner"
label variable mv853a   "Times in last 12 months had sex with most recent partner"
label variable mv853b   "Times in last 12 months had sex with 2nd most recent partner"
label variable mv853c   "Times in last 12 months had sex with 3rd most recent partner"
label variable mv854a   "NA - Concurrent sexual partners"
label variable mv854b   "NA - Cumulative concurrent sexual partners"
label variable mg100    "Ever heard of female circumcision"
label variable mg101    "Ever heard of genital cutting (probed)"
label variable mg117a   "NA - Female circumcision benefit: cleanliness/hygiene"
label variable mg117b   "NA - Female circumcision benefit: social acceptance"
label variable mg117c   "NA - Female circumcision benefit: better marriage prospects"
label variable mg117d   "NA - Female circumcision benefit: virginity/prevent premarital sex"
label variable mg117e   "NA - Female circumcision benefit: greater sexual pleasure for men"
label variable mg117f   "NA - Female circumcision benefit: religious approval"
label variable mg117g   "NA - Female circumcision benefit: CS"
label variable mg117h   "NA - Female circumcision benefit: CS"
label variable mg117i   "NA - Female circumcision benefit: CS"
label variable mg117j   "NA - Female circumcision benefit: CS"
label variable mg117x   "NA - Female circumcision benefit: other"
label variable mg117y   "NA - No benefit from female circumcision"
label variable mg118    "Female circumcision required by religion"
label variable mg119    "Female circumcision: continue or be stopped"
label variable smregion "County of residence - As in the sample file"
label variable smcounty "County - as in the final tables"
label variable smdist   "NA - District"
label variable smcluster "NA - NASSEP Cluster Number"
label variable smdv     "Individual selected for DV"
label variable smlquest "Language of questionnaire"
label variable smlinterview "Language of interview"
label variable smlnative "Native language"
label variable smtranslator "Translator used"
label variable smeduc   "Highest educational level"
label variable mv044    "Selected for Domestic Violence module"
label variable sm101d   "Nationality"
label variable sm101e   "Main reason for moving to Kenya"
label variable sm105    "Highest educational level"
label variable sm309q   "Place where to get condom?"
label variable sm313q   "Knows where to get a condom: bar"
label variable sm418a1  "Main reason for using condom - last sexual partner"
label variable sm418a2  "Main reason for using condom - second to last sexual partner"
label variable sm418a3  "Main reason for using condom - third to last sexual partner"
label variable sm604b   "Work mainly on your own land or on family land"
label variable sm707a   "Know someone personally who has AIDS virus"
label variable sm717b   "Talked with husband / partner about ways to prevent getting AIDS"
label variable sm723aa  "Symptons man has a sexually transmitted disease: Abdominal pain"
label variable sm723ab  "Symptons man has a sexually transmitted disease: genital discharge/ dripping"
label variable sm723ac  "Symptons man has a sexually transmitted disease: foul smell/discharge"
label variable sm723ad  "Symptons man has a sexually transmitted disease: burning pain on urination"
label variable sm723ae  "Symptons man has a sexually transmitted disease: redness/ inflamation in genital"
label variable sm723af  "Symptons man has a sexually transmitted disease: swelling in genital area"
label variable sm723ag  "Symptons man has a sexually transmitted disease: genital sore/ ulcers"
label variable sm723ah  "Symptons man has a sexually transmitted disease: genital warts"
label variable sm723ai  "Symptons man has a sexually transmitted disease: genital itching"
label variable sm723aj  "Symptons man has a sexually transmitted disease: blood in urine"
label variable sm723ak  "Symptons man has a sexually transmitted disease: loss of weight"
label variable sm723al  "Symptons man has a sexually transmitted disease: impotence/ no erection"
label variable sm723aw  "Symptons man has a sexually transmitted disease: other"
label variable sm723ax  "Symptons man has a sexually transmitted disease: other"
label variable sm723ay  "Symptons man has a sexually transmitted disease: no symptoms"
label variable sm723az  "Symptons man has a sexually transmitted disease: does not know"
label variable sm723ba  "Symptons woman has a sexually transmitted disease: Abdominal pain"
label variable sm723bb  "Symptons woman has a sexually transmitted disease: genital discharge/ dripping"
label variable sm723bc  "Symptons woman has a sexually transmitted disease: foul smell/discharge"
label variable sm723bd  "Symptons woman has a sexually transmitted disease: burning pain on urination"
label variable sm723be  "Symptons woman has a sexually transmitted disease: redness/ inflamation in genit"
label variable sm723bf  "Symptons woman has a sexually transmitted disease: swelling in genital area"
label variable sm723bg  "Symptons woman has a sexually transmitted disease: genital sore/ ulcers"
label variable sm723bh  "Symptons woman has a sexually transmitted disease: genital warts"
label variable sm723bi  "Symptons woman has a sexually transmitted disease: genital itching"
label variable sm723bj  "Symptons woman has a sexually transmitted disease: blood in urine"
label variable sm723bk  "Symptons woman has a sexually transmitted disease: loss of weight"
label variable sm723bl  "Symptons woman has a sexually transmitted disease: hard to get pregnant"
label variable sm723bw  "Symptons woman has a sexually transmitted disease: other"
label variable sm723bx  "Symptons woman has a sexually transmitted disease: other"
label variable sm723by  "Symptons woman has a sexually transmitted disease: : no symptoms"
label variable sm723bz  "Symptons woman has a sexually transmitted disease: does not know"
label variable sm731a   "Inform the persons with whom you were having sex of STI"
label variable sm731b   "Anything to avoid infecting your sexual partner"
label variable sm731ca  "Use medicine to avoid infecting partner"
label variable sm731cb  "Stop sex to avoid infecting partner"
label variable sm731cc  "Use a condom when having sex to avoid infecting partner"
label variable sm807a   "Raised blood pressure or hypertension?"
label variable sm807b   "Blood sugar or diabetes?"
label variable sm807c   "Involved in a road traffic accident"
label variable sm807d   "Injured accidentally,"
label variable sm807ea  "Tell how you were injured: fall"
label variable sm807eb  "Tell how you were injured: burn"
label variable sm807ec  "Tell how you were injured: poisoning"
label variable sm807ed  "Tell how you were injured: cut"
label variable sm807ee  "Tell how you were injured: near-drowning"
label variable sm807ef  "Tell how you were injured: animal bite"
label variable sm807eg  "Tell how you were injured: shooting"
label variable sm807ex  "Tell how you were injured: other"
label variable sm811a   "Do you drink alcohol?"
label variable sm811b   "At least one alcoholic drink"
label variable sm811ca  "At work?"
label variable sm811cb  "During other physical activities?"
label variable sm811d   "Ever heard of prostate cancer"
label variable sm811e   "Ever examined you to detect or test for prostate cancer"
label variable sm811f   "Prostate exam happen within the last 5 years"
label variable sm811g   "Have a problem with your prostate"
label variable sm811h   "Treated or referred for treatment for the prostate problem"
label variable sm811i   "Constant leakage of urine or stool from her vagina"
label variable sm902a   "Ever heard of genital cutting (probed)"
label variable md005    "Weight for Domestic Violence (6 decimals)"
label variable md101a   "Wife/partner jealous if respondent talks with other women"
label variable md101b   "Wife/partner accuses respondent of unfaithfulness"
label variable md101c   "Wife/partner does not permit respondent to meet female friends"
label variable md101d   "Wife/partner tries to limit respondent's contact with family"
label variable md101e   "Wife/partner insists on knowing where respondent is"
label variable md101f   "NA - Wife/partner doesn't trust respondent with money"
label variable md101g   "NA - CS control issue"
label variable md101h   "NA - CS control issue"
label variable md101i   "CS control issue"
label variable md101j   "CS control issue"
label variable md102    "Number of control issues answered 'Yes'  (MD101x = 1)***"
label variable md103a   "Ever been humiliated by wife/partner"
label variable md103b   "Ever been threatened with harm by wife/partner"
label variable md103c   "Ever been insulted or made to feel bad by wife/partner"
label variable md103d   "Ever CS emotional abuse by wife/partner"
label variable md103e   "Ever CS emotional abuse by wife/partner"
label variable md103f   "Ever CS emotional abuse by wife/partner"
label variable md104    "Experienced any emotional violence (MD103x series)***"
label variable md105a   "Ever been pushed, shook or had something thrown by wife/partner"
label variable md105b   "Ever been slapped by wife/partner"
label variable md105c   "Ever been punched with fist or hit by something harmful by wife/partner"
label variable md105d   "Ever been kicked or dragged by wife/partner"
label variable md105e   "Ever been strangled or burnt by wife/partner"
label variable md105f   "Ever been threatened with knife/gun or other weapon by wife/partner"
label variable md105g   "Ever CS physical violence by wife/partner"
label variable md105h   "Ever been physically forced into unwanted sex by wife/partner"
label variable md105i   "Ever been forced into other unwanted sexual acts by wife/partner"
label variable md105j   "Ever had arm twisted or hair pulled by wife/partner"
label variable md105k   "Ever been physically forced to perform sexual acts respondent didn't want to"
label variable md105l   "Ever CS physical violence by wife/partner"
label variable md105m   "Ever CS physical violence by wife/partner"
label variable md105n   "Ever CS physical violence by wife/partner"
label variable md106    "Experienced any less severe violence (MD105A-C,J) by wife/partner"
label variable md107    "Experienced any severe violence (MD105D-F) by wife/partner"
label variable md108    "Experienced any sexual violence (MD105H-I,K) by wife/partner"
label variable md109    "Timing of first event (from MD105 series) in years after marriage"
label variable md110a   "Ever had bruises because of wife/partner's actions"
label variable md110b   "Ever had eye injuries, sprains, dislocations or burns because of wife/partner's "
label variable md110c   "NA - Ever went to health facility because of wife/partner's actions"
label variable md110d   "Ever had wounds, broken bones, broken teeth or other serious injury because of w"
label variable md110e   "NA - CS because of wife/partner's actions"
label variable md110f   "CS because of wife/partner's actions"
label variable md110g   "CS because of wife/partner's actions"
label variable md110h   "CS because of wife/partner's actions"
label variable md111    "Experienced any of listed wife/partner's actions (MD110x series)***"
label variable md112    "Respondent ever physically hurt wife/partner when he was not hurting her"
label variable md112a   "Frequency of physically hurting wife/partner in last 12 months"
label variable md113    "Wife/partner drinks alcohol"
label variable md114    "Frequency of wife/partner being drunk"
label variable md115b   "Mother: Person who has ever physically hurt respondent"
label variable md115c   "Father: Person who has ever physically hurt respondent"
label variable md115d   "Daughter: Person who has ever physically hurt respondent"
label variable md115e   "NA - Son: Person who has ever physically hurt respondent"
label variable md115f   "Sister/brother: Person who has ever physically hurt respondent"
label variable md115g   "Other relative: Person who has ever physically hurt respondent"
label variable md115h   "Other female family: Person who has ever physically hurt respondent"
label variable md115i   "Other male family: Person who has ever physically hurt respondent"
label variable md115j   "NA - Former partner: Person who has ever physically hurt respondent"
label variable md115k   "Current boyfriend: Person who has ever physically hurt respondent"
label variable md115l   "Former boyfriend: Person who has ever physically hurt respondent"
label variable md115m   "Step-mother: Person who has ever physically hurt respondent"
label variable md115n   "Step-father: Person who has ever physically hurt respondent"
label variable md115o   "Mother-in-law: Person who has ever physically hurt respondent"
label variable md115p   "Father-in-law: Person who has ever physically hurt respondent"
label variable md115q   "Other in-law: Person who has ever physically hurt respondent"
label variable md115r   "NA - Other male in-law: Person who has ever physically hurt respondent"
label variable md115s   "Female friend: Person who has ever physically hurt respondent"
label variable md115t   "Male friend: Person who has ever physically hurt respondent"
label variable md115u   "Neighbor: Person who has ever physically hurt respondent"
label variable md115v   "Teacher: Person who has ever physically hurt respondent"
label variable md115w   "Employer: Person who has ever physically hurt respondent"
label variable md115x   "Other: Person who has ever physically hurt respondent"
label variable md115y   "No person other than husband/partner ever physically hurt respondent"
label variable md115xa  "NA - Stranger: Person who has ever physically hurt respondent"
label variable md115xb  "Other female in-law/family: Person who has ever physically hurt respondent"
label variable md115xc  "NA - Other male in-law/family: Person who has ever physically hurt respondent"
label variable md115xd  "NA - Friend: Person who has ever physically hurt respondent"
label variable md115xe  "Police: Person who has ever physically hurt respondent"
label variable md115xf  "NA - Religious leader: Person who has ever physically hurt respondent"
label variable md115xg  "NA - Lawyer: Person who has ever physically hurt respondent"
label variable md115xh  "NA - Doctor: Person who has ever physically hurt respondent"
label variable md115xi  "NA - Mother/step mother: Person who has ever physically hurt respondent"
label variable md115xj  "NA - Father/step father: Person who has ever physically hurt respondent"
label variable md115xk  "Daughter/son: Person who has ever physically hurt respondent"
label variable md116    "NA - Person who hurt respondent most often"
label variable md117a   "Frequency of being hit in last 12 months by other than wife/partner"
label variable md119a   "NA - Wife/partner: Person respondent went to seek help"
label variable md119b   "NA - Mother: Person respondent went to seek help"
label variable md119c   "NA - Father: Person respondent went to seek help"
label variable md119d   "NA - Daughter: Person respondent went to seek help"
label variable md119e   "Son: Person respondent went to seek help"
label variable md119f   "Sister: Person respondent went to seek help"
label variable md119g   "Brother: Person respondent went to seek help"
label variable md119h   "Own family: Person respondent went to seek help"
label variable md119i   "Husband/partner family: Person respondent went to seek help"
label variable md119j   "Current/former husband/partner: Person respondent went to seek help"
label variable md119k   "Current/former boyfriend: Person respondent went to seek help"
label variable md119l   "NA - Former boyfriend alone: Person respondent went to seek help"
label variable md119m   "NA - Step-mother: Person respondent went to seek help"
label variable md119n   "NA - Step-father: Person respondent went to seek help"
label variable md119o   "NA - Mother-in-law: Person respondent went to seek help"
label variable md119p   "NA - Father-in-law: Person respondent went to seek help"
label variable md119q   "NA - Other female in-law: Person respondent went to seek help"
label variable md119r   "Other male in-law: Person respondent went to seek help"
label variable md119s   "NA - Female friend: Person respondent went to seek help"
label variable md119t   "NA - Male friend: Person respondent went to seek help"
label variable md119u   "Neighbor: Person respondent went to seek help"
label variable md119v   "Teacher: Person respondent went to seek help"
label variable md119w   "NA - Employer: Person respondent went to seek help"
label variable md119x   "Other: Person respondent went to seek help"
label variable md119y   "Respondent did not seek help from anyone"
label variable md119xa  "Stranger: Person respondent went to seek help"
label variable md119xb  "Social service organization: Person respondent went to seek help"
label variable md119xc  "CS: Person respondent went to seek help"
label variable md119xd  "Friend: Person respondent went to seek help"
label variable md119xe  "Police: Person respondent went to seek help"
label variable md119xf  "Religious leader: Person respondent went to seek help"
label variable md119xg  "Lawyer: Person respondent went to seek help"
label variable md119xh  "Doctor: Person respondent went to seek help"
label variable md119xi  "NA - CS: Person respondent went to seek help"
label variable md119xj  "NA - CS: Person respondent went to seek help"
label variable md119xk  "CS: Person respondent went to seek help"
label variable md120    "Main reason never sought help"
label variable md121    "Respondent's father ever beat her mother"
label variable md122a   "Interview interrupted: husband's presence"
label variable md122b   "Interview interrupted: other adult male's presence"
label variable md122c   "Interview interrupted: adult female's presence"
label variable md123    "First sex was wanted or forced"
label variable md124    "Ever forced to have sex by anyone other than wife/partner in last 12 months"
label variable md125    "Ever forced to perform unwanted sexual acts"
label variable md126    "Age at first forced sexual act"
label variable md127    "Person who forced respondent into first sexual act"
label variable md128    "Ever told anyone else about violence"
label variable md129    "Respondent afraid of wife/partner most of the time, sometimes or never"
label variable md130a   "Previous wife: ever hit, slap, kick or physically hurt respondent"
label variable md130b   "Previous wife: physically forced to have sex or to perform sexual acts"

#delimit ;
label define MV013   
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
     8 "50-54"
     9 "55-59"
    10 "60-64"
;
label define MV014   
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define MV015   
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define MV024   
     1 "Coast"
     2 "North Eastern"
     3 "Eastern"
     4 "Central"
     5 "Rift Valley"
     7 "Western"
     8 "Nyanza"
     9 "Nairobi"
;
label define MV025   
     1 "Urban"
     2 "Rural"
;
label define MV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV027   
     9 "Missing"
;
label define MV028   
   999 "Missing"
;
label define MV029   
    99 "Missing"
;
label define MV030   
   999 "Missing"
;
label define MV031   
   999 "Missing"
;
label define MV032   
    99 "Missing"
;
label define MV034   
     0 "Wife not in household"
;
label define MV034A  
     1 "Wife"
     2 "Partner"
;
label define MV034B  
    99 "Missing"
;
label define MV035   
     0 "No wives/partners"
;
label define MV801   
  9999 "Missing"
;
label define MV802   
  9999 "Missing"
;
label define MV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define MV101   
     1 "Coast"
     2 "North Eastern"
     3 "Eastern"
     4 "Central"
     5 "Rift Valley"
     7 "Western"
     8 "Nyanza"
     9 "Nairobi"
;
label define MV102   
     1 "Urban"
     2 "Rural"
;
label define MV103   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     5 "Other city/ town"
;
label define MV104   
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV105   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     5 "Other city/ town"
;
label define MV106   
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define MV107   
     0 "No years completed at level MV106"
;
label define MV130   
     1 "Roman Catholic"
     2 "Protestant/ Other Christian"
     3 "Muslim"
     4 "No religion"
    96 "Other"
;
label define MV131   
     1 "Embu"
     2 "Kalenjin"
     3 "Kamba"
     4 "Kikuyu"
     5 "Kisii"
     6 "Luhya"
     7 "Luo"
     8 "Maasai"
     9 "Meru"
    10 "Mijikenda/ Swahili"
    11 "Somali"
    12 "Taita/ Taveta"
    13 "Turkana"
    14 "Samburu"
    15 "Pokomo"
    16 "Iteso"
    17 "Boran"
    18 "Gabbra"
    19 "Kuria"
    20 "Orma"
    21 "Mbere"
    22 "Rendille"
    96 "Other"
;
label define MV133   
    97 "Inconsistent"
;
label define MV134   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV135   
     1 "Usual resident"
     2 "Visitor"
;
label define MV149   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define MV150   
     1 "Head"
     2 "Husband"
     3 "Son"
     4 "Son-in-law"
     5 "Grandson"
     6 "Father"
     7 "Father-in-law"
     8 "Brother"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "Don't know"
;
label define MV151   
     1 "Male"
     2 "Female"
;
label define MV152   
    97 "97+"
    98 "Don't know"
;
label define MV155   
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define MV156   
     0 "No"
     1 "Yes"
;
label define MV157   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV158   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV159   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV167   
     0 "None"
    90 "90+"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV168   
     0 "No"
     1 "Yes"
;
label define MV190   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define MV212   
    99 "Missing"
;
label define MV213   
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV217   
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define MV225   
     1 "Then"
     2 "Later"
     3 "Not at all"
;
label define MV245   
    99 "Missing"
;
label define MV246   
     0 "No"
     1 "Yes"
;
label define MV247   
    99 "Missing"
;
label define MV248   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV249   
     0 "Not present"
     1 "Present"
;
label define MV250   
     1 "Hospital, health facility"
     2 "Other"
;
label define MV251   
     1 "Cost too much"
     2 "Facility closed"
     3 "Too far/no transportation"
     4 "Don't trust facility/poor quality service"
     5 "No female provider"
     6 "Not the first child"
     7 "Mother did not think it necessary"
     8 "Respondent did not think it necessary"
     9 "Family did not think it necessary"
    96 "Other"
    98 "Don't know"
;
label define MV252   
     0 "Nothing to drink"
     2 "Less than usual/much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define MV301   
     0 "Knows no method"
     1 "Knows only folkloric method"
     2 "Knows only traditional method"
     3 "Knows modern method"
;
label define MV302   
     0 "Never used"
     1 "Used only folkloric method"
     2 "Used only traditional method"
     3 "Used modern method"
;
label define M304A   
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define MV304   
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV305   
     0 "No"
     1 "Yes"
;
label define MV307   
     0 "No"
     1 "Yes"
;
label define MV312   
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Implants/Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea (LAM)"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Other modern method"
    18 "Survey Specific method 2"
    19 "Survey Specific method 3"
    20 "Survey Specific method 4"
    98 "Don't know"
;
label define MV313   
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     8 "Don't know"
;
label define MV323A  
    96 "Other"
    98 "Don't know"
;
label define MV325B  
9999995 "Free"
9999998 "Don't know"
;
label define MV372A  
     0 "Package not seen"
     1 "Package seen"
;
label define MV384A  
     0 "No"
     1 "Yes"
;
label define MV384B  
     0 "No"
     1 "Yes"
;
label define MV384C  
     0 "No"
     1 "Yes"
;
label define MV395   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "Don't know"
;
label define MV396   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "Don't know"
;
label define MV3A09B 
   998 "Don't know"
;
label define MV3B17  
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Government dispensary"
    16 "Other public"
    20 "PRIVATE SECTOR"
    21 "Private hospital, clinic"
    22 "Pharmacy/Chemist"
    23 "Nursing/Maternity Home"
    24 "Faith-based, church, mission hospital"
    25 "Family Options/FHOK clinic"
    26 "Other private medical"
    30 "OTHER"
    31 "Shop"
    32 "Mobile clinic"
    33 "Community-based distributor"
    34 "Community health worker"
    35 "Friend/Relative"
    96 "Other"
;
label define MV3B25A 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV3B25B 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV463A  
     0 "No"
     1 "Yes"
;
label define MV463B  
     0 "No"
     1 "Yes"
;
label define MV463C  
     0 "No"
     1 "Yes"
;
label define MV463D  
     0 "No"
     1 "Yes"
;
label define MV463E  
     0 "No"
     1 "Yes"
;
label define MV463F  
     0 "No"
     1 "Yes"
;
label define MV463G  
     0 "No"
     1 "Yes"
;
label define MV463X  
     0 "No"
     1 "Yes"
;
label define MV463Z  
     0 "No"
     1 "Yes, smokes nothing"
;
label define MV464   
    98 "DK"
;
label define MV474   
     0 "No"
     1 "Yes"
;
label define MV474A  
     0 "No"
     1 "Yes"
;
label define MV474B  
     0 "No"
     1 "Yes"
;
label define MV474C  
     0 "No"
     1 "Yes"
;
label define MV474D  
     0 "No"
     1 "Yes"
;
label define MV474E  
     0 "No"
     1 "Yes"
;
label define MV474F  
     0 "No"
     1 "Yes"
;
label define MV474G  
     0 "No"
     1 "Yes"
;
label define MV474H  
     0 "No"
     1 "Yes"
;
label define MV474I  
     0 "No"
     1 "Yes"
;
label define MV474J  
     0 "No"
     1 "Yes"
;
label define MV474X  
     0 "No"
     1 "Yes"
;
label define MV474Z  
     0 "No"
     1 "Yes"
;
label define MV475   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV476   
     0 "No"
     1 "Yes, remain a secret"
     8 "Don't know/not sure/depends"
;
label define MV477   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV478   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV479   
    10 "PUBLIC SECTOR"
    20 "PRIVATE SECTOR"
    30 "OTHER"
    96 "Other"
;
label define MV480   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV481   
     0 "No"
     1 "Yes"
;
label define MV481A  
     0 "No"
     1 "Yes"
;
label define MV481B  
     0 "No"
     1 "Yes"
;
label define MV481C  
     0 "No"
     1 "Yes"
;
label define MV481D  
     0 "No"
     1 "Yes"
;
label define MV481E  
     0 "No"
     1 "Yes"
;
label define MV481F  
     0 "No"
     1 "Yes"
;
label define MV481G  
     0 "No"
     1 "Yes"
;
label define MV481H  
     0 "No"
     1 "Yes"
;
label define MV481X  
     0 "No"
     1 "Yes"
;
label define MV482A  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV482B  
     0 "No"
     1 "Yes"
;
label define MV482C  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV483   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV483A  
    95 "During childhood <5 years"
    98 "Don't know"
;
label define MV483B  
     1 "Traditional practitioner / family friend"
     2 "Health worker / professional"
    96 "Other"
    98 "Don't know"
;
label define MV483C  
     1 "Health facility"
     2 "Home of a health worker / professional"
     3 "Circumcision done at home"
     4 "Ritual site"
    96 "Other home / place"
    98 "Don't know"
;
label define MV501   
     0 "Never in union"
     1 "Married"
     2 "Living with partner"
     3 "Widowed"
     4 "Divorced"
     5 "No longer living together/separated"
;
label define MV502   
     0 "Never in union"
     1 "Currently in union/living with a woman"
     2 "Formerly in union/living with a woman"
;
label define MV503   
     1 "Once"
     2 "More than once"
;
label define MV504   
     1 "Living with him"
     2 "Staying elsewhere"
;
label define MV505   
    99 "Missing"
;
label define MV510   
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define MV513   
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define MV525   
     0 "Not had sex"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV527   
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV528   
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV529   
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV531   
     0 "Not had sex"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV532   
     0 "No flag"
     1 "After interview"
     2 "After conception >= 1 year"
     3 "After conception < 1 year"
     4 "At marriage, but never married"
     5 "At marriage, but after conception"
     6 "After marriage"
;
label define MV535   
     0 "No"
     1 "Formerly married"
     2 "Formerly lived with a woman"
     3 "Both, formerly married and lived with a woman"
;
label define MV536   
     0 "Never had sex"
     1 "Active in last 4 weeks"
     3 "Not active in last 4 weeks"
;
label define MV541   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV602   
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized (respondent or partner(s))"
     5 "Declared infecund (respondent or partner(s))"
     6 "Never had sex"
     7 "Man declared infecund"
     8 "Man has no partner"
;
label define MV603   
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon, now"
   996 "Other, non-numeric"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV604   
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
;
label define MV605   
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized (respondent or partner(s))"
     7 "Declared infecund (respondent or partner(s))"
     8 "Never had sex"
;
label define MV613   
    96 "Non-numeric response"
    98 "Don't know"
;
label define MV614   
     6 "6+"
     7 "Non-numeric response"
;
label define MV616   
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "Don't know"
;
label define MV621   
     1 "Both want same"
     2 "Wife wants more"
     3 "Wife wants fewer"
     8 "Don't know"
;
label define MV627   
    96 "Other"
    98 "Don't know"
;
label define MV628   
    96 "Other"
    98 "Don't know"
;
label define MV629   
    96 "Other"
    98 "Don't know"
;
label define MV631   
     1 "Big problem"
     2 "Small problem"
     3 "No problem"
     4 "Says she can't get pregnant/not having sex"
;
label define MV633A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV634A  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634B  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634C  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634D  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV714   
     0 "No"
     1 "Yes"
;
label define MV714A  
     0 "No"
     1 "Yes"
;
label define MV716   
     1 "Armed Forces"
    11 "Legislators and Constitutional Officials"
    12 "Administrators and Senior Officials of Special Interest Organizations"
    13 "Corporate Managers"
    14 "Non-Departmental Managers"
    15 "Other Administrators and Managers"
    21 "Physical Science Professionals"
    22 "Mathematicians, Statisticians and Computing Professionals"
    23 "Engineering Science Professionals"
    24 "Health and Life Science Professionals"
    25 "Teaching Professionals"
    26 "Legal Professionals"
    27 "Social Science and Related Professionals"
    28 "Business Professionals"
    29 "Other Professionals"
    31 "Engineering Technicians"
    32 "Medical and Health Science Associate Professionals"
    33 "Physical and Life Science Technicians"
    34 "Farming Advisors"
    35 "Business and Social Services Associate Professionals"
    36 "Administration and Middle Level Personnel"
    37 "Primary and Pre-primary education and Other Teachers"
    39 "Other Business, Social Services, Athletics, Sports and Related Workers"
    41 "Secretaries and Office Clerks"
    42 "Client Oriented Clerks"
    51 "Models, Shop Assistants and Demonstrators"
    52 "Personal and Protective Service Workers"
    53 "House Stewards, Caterers, Waiters and Related Workers"
    54 "Travel Attendants and Guides"
    61 "Farm Workers (except fish)"
    62 "Fishery and Related Workers"
    63 "Subsistence Agricultural and Fishery Workers"
    64 "Forestry and Related Workers"
    65 "Hunting and Wildlife Workers"
    71 "Extraction and Building Trades Workers"
    72 "Metal, Machinery and Related Trades Workers"
    73 "Precision and Handicraft Workers"
    74 "Printing and Related Trades Workers"
    75 "Food Processing and Related Trades"
    76 "Woodworking Trades Workers"
    77 "Textile, Garment and Related Trades"
    78 "Upholsterers, Pelt, Leather and Shoemaking Trades Workers"
    81 "Drilling and Mining Plant and Mineral Products Machine Operators"
    82 "Metal Processing Plant and Metal Working Machine Operators"
    83 "Wood Processing Plant and Wood, Rubbers and Plastic Machine Operators"
    84 "Chemical-Processing Plant and Chemical Products Machine Operators"
    85 "Power Production Plant Operators"
    86 "Food and Related Products Machine Operators"
    87 "Assemblers"
    88 "Drivers and Mobile Machinery Operators"
    89 "Other Plant and Machine Operators and Assemblers"
    91 "Sales and Services Elementary Occupations"
    92 "Agricultural, Fishery and Related Labourers"
    93 "Labourers in Mining, Construction, Manufacturing and Transport"
    96 "Other"
     0 "Not working"
;
label define MV717   
     0 "Not working"
     1 "Professional/technical/managerial"
     2 "Clerical"
     3 "Sales"
     4 "Agriculture - self employed"
     5 "Agriculture - employee"
     6 "Household and domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
;
label define MV719   
     1 "For family member"
     2 "For someone else"
     3 "Self-employed"
;
label define MV721   
     1 "At home"
     2 "Away"
;
label define MV731   
     0 "No"
     1 "In the past year"
     2 "Currently working"
;
label define MV732   
     1 "All year"
     2 "Seasonal"
     3 "Occasional"
;
label define MV739   
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
;
label define MV740   
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
;
label define MV741   
     0 "Not paid"
     1 "Cash only"
     2 "Cash and in-kind"
     3 "In-kind only"
;
label define MV743A  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Other"
     8 "Don't know/depends"
;
label define MV743B  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Other"
     8 "Don't know/depends"
;
label define MV743C  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743D  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743E  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743F  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743G  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV744A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV745A  
     0 "Does not own"
     1 "Alone only"
     2 "Jointly only"
     3 "Both alone and jointly"
;
label define MV745B  
     0 "Does not own"
     1 "Alone only"
     2 "Jointly only"
     3 "Both alone and jointly"
;
label define MV747A  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV747B  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV750   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV751   
     0 "No"
     1 "Yes"
;
label define MV754BP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754CP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754DP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754JP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754WP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV756   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV762AA 
     0 "No"
     1 "Yes"
;
label define MV762AB 
     0 "No"
     1 "Yes"
;
label define MV762AC 
     0 "No"
     1 "Yes"
;
label define MV762AD 
     0 "No"
     1 "Yes"
;
label define MV762AE 
     0 "No"
     1 "Yes"
;
label define MV762AF 
     0 "No"
     1 "Yes"
;
label define MV762AG 
     0 "No"
     1 "Yes"
;
label define MV762AH 
     0 "No"
     1 "Yes"
;
label define MV762AI 
     0 "No"
     1 "Yes"
;
label define MV762AJ 
     0 "No"
     1 "Yes"
;
label define MV762AK 
     0 "No"
     1 "Yes"
;
label define MV762AL 
     0 "No"
     1 "Yes"
;
label define MV762AM 
     0 "No"
     1 "Yes"
;
label define MV762AN 
     0 "No"
     1 "Yes"
;
label define MV762AO 
     0 "No"
     1 "Yes"
;
label define MV762AP 
     0 "No"
     1 "Yes"
;
label define MV762AQ 
     0 "No"
     1 "Yes"
;
label define MV762AR 
     0 "No"
     1 "Yes"
;
label define MV762AS 
     0 "No"
     1 "Yes"
;
label define MV762AT 
     0 "No"
     1 "Yes"
;
label define MV762AU 
     0 "No"
     1 "Yes"
;
label define MV762AV 
     0 "No"
     1 "Yes"
;
label define MV762AW 
     0 "No"
     1 "Yes"
;
label define MV762AX 
     0 "No"
     1 "Yes"
;
label define MV762AZ 
     0 "No"
     1 "Yes: don't know"
;
label define MV762BA 
     0 "No"
     1 "Yes"
;
label define MV762BB 
     0 "No"
     1 "Yes"
;
label define MV762BC 
     0 "No"
     1 "Yes"
;
label define MV762BD 
     0 "No"
     1 "Yes"
;
label define MV762BE 
     0 "No"
     1 "Yes"
;
label define MV762BF 
     0 "No"
     1 "Yes"
;
label define MV762BG 
     0 "No"
     1 "Yes"
;
label define MV762BH 
     0 "No"
     1 "Yes"
;
label define MV762BI 
     0 "No"
     1 "Yes"
;
label define MV762BJ 
     0 "No"
     1 "Yes"
;
label define MV762BK 
     0 "No"
     1 "Yes"
;
label define MV762BL 
     0 "No"
     1 "Yes"
;
label define MV762BM 
     0 "No"
     1 "Yes"
;
label define MV762BN 
     0 "No"
     1 "Yes"
;
label define MV762BO 
     0 "No"
     1 "Yes"
;
label define MV762BP 
     0 "No"
     1 "Yes"
;
label define MV762BQ 
     0 "No"
     1 "Yes"
;
label define MV762BR 
     0 "No"
     1 "Yes"
;
label define MV762BS 
     0 "No"
     1 "Yes"
;
label define MV762BT 
     0 "No"
     1 "Yes"
;
label define MV762BU 
     0 "No"
     1 "Yes"
;
label define MV762BV 
     0 "No"
     1 "Yes"
;
label define MV762BW 
     0 "No"
     1 "Yes"
;
label define MV762BX 
     0 "No"
     1 "Yes"
;
label define MV762BZ 
     0 "No"
     1 "Yes: don't know"
;
label define MV763A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV766A  
    98 "Don't know"
;
label define MV766B  
    98 "Don't know"
;
label define MV767A  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767B  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767C  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV768A  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768B  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768C  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV769   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV769A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV770   
     0 "No"
     1 "Yes"
;
label define MV770A  
     0 "No"
     1 "Yes"
;
label define MV770B  
     0 "No"
     1 "Yes"
;
label define MV770C  
     0 "No"
     1 "Yes"
;
label define MV770D  
     0 "No"
     1 "Yes"
;
label define MV770E  
     0 "No"
     1 "Yes"
;
label define MV770F  
     0 "No"
     1 "Yes"
;
label define MV770G  
     0 "No"
     1 "Yes"
;
label define MV770H  
     0 "No"
     1 "Yes"
;
label define MV770I  
     0 "No"
     1 "Yes"
;
label define MV770J  
     0 "No"
     1 "Yes"
;
label define MV770K  
     0 "No"
     1 "Yes"
;
label define MV770L  
     0 "No"
     1 "Yes"
;
label define MV770M  
     0 "No"
     1 "Yes"
;
label define MV770N  
     0 "No"
     1 "Yes"
;
label define MV770O  
     0 "No"
     1 "Yes"
;
label define MV770P  
     0 "No"
     1 "Yes"
;
label define MV770Q  
     0 "No"
     1 "Yes"
;
label define MV770R  
     0 "No"
     1 "Yes"
;
label define MV770S  
     0 "No"
     1 "Yes"
;
label define MV770T  
     0 "No"
     1 "Yes"
;
label define MV770U  
     0 "No"
     1 "Yes"
;
label define MV770V  
     0 "No"
     1 "Yes"
;
label define MV770W  
     0 "No"
     1 "Yes"
;
label define MV770X  
     0 "No"
     1 "Yes"
;
label define MV774A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV774B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV774C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV775   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV777   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV778   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV779   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV780   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV781   
     0 "No"
     1 "Yes"
;
label define MV783   
     0 "No"
     1 "Yes"
;
label define MV784A  
     0 "No"
     1 "Yes"
;
label define MV784B  
     0 "No"
     1 "Yes"
;
label define MV784C  
     0 "No"
     1 "Yes"
;
label define MV784D  
     0 "No"
     1 "Yes"
;
label define MV784E  
     0 "No"
     1 "Yes"
;
label define MV784F  
     0 "No"
     1 "Yes"
;
label define MV784G  
     0 "No"
     1 "Yes"
;
label define MV784H  
     0 "No"
     1 "Yes"
;
label define MV784I  
     0 "No"
     1 "Yes"
;
label define MV784J  
     0 "No"
     1 "Yes"
;
label define MV784K  
     0 "No"
     1 "Yes"
;
label define MV784L  
     0 "No"
     1 "Yes"
;
label define MV784M  
     0 "No"
     1 "Yes"
;
label define MV784N  
     0 "No"
     1 "Yes"
;
label define MV784O  
     0 "No"
     1 "Yes"
;
label define MV784P  
     0 "No"
     1 "Yes"
;
label define MV784Q  
     0 "No"
     1 "Yes"
;
label define MV784R  
     0 "No"
     1 "Yes"
;
label define MV784S  
     0 "No"
     1 "Yes"
;
label define MV784T  
     0 "No"
     1 "Yes"
;
label define MV784U  
     0 "No"
     1 "Yes"
;
label define MV784V  
     0 "No"
     1 "Yes"
;
label define MV784X  
     0 "No"
     1 "Yes"
;
label define MV785   
     0 "No"
     1 "Yes"
;
label define MV791   
     0 "No"
     1 "Yes"
;
label define MV793   
     0 "No"
     1 "Yes"
;
label define MV793A  
     0 "No"
     1 "Yes"
;
label define MV793B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV820   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV822   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV823   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV824   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV825   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV826   
     1 "Less than 12 months"
     2 "12-23 months"
     3 "2 years or more"
;
label define MV826A  
    95 "Two or more years"
    98 "Don't know"
;
label define MV827   
     1 "Asked for the test"
     2 "Offered and accepted"
     3 "Required"
;
label define MV828   
     0 "No"
     1 "Yes"
;
label define MV829   
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Government dispensary"
    18 "Other public"
    20 "PRIVATE SECTOR"
    21 "Private hospital, clinic"
    22 "Faith-based, church, mission hospital/clinic"
    23 "Family Options/FHOK Clinic"
    24 "VCT centre"
    25 "Nursing/Maternity home"
    26 "Blood transfusion services"
    27 "Other private medical"
    30 "OTHER"
    31 "Home"
    32 "Correctional facility"
    96 "Other"
;
label define MV832B  
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV832C  
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV833A  
     0 "No"
     1 "Yes"
;
label define MV833B  
     0 "No"
     1 "Yes"
;
label define MV833C  
     0 "No"
     1 "Yes"
;
label define MV834A  
    95 "95+"
    98 "Don't know"
;
label define MV834B  
    95 "95+"
    98 "Don't know"
;
label define MV834C  
    95 "95+"
    98 "Don't know"
;
label define MV835A  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835B  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835C  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV836   
    95 "95+"
    98 "Don't know"
;
label define MV837   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV844   
     0 "No"
     1 "Yes"
     8 "Don't know anyone with AIDS"
;
label define MV845   
     0 "No"
     1 "Yes"
;
label define MV846   
     0 "No"
     1 "Yes"
;
label define MV847   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/no opinion"
;
label define MV848   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/no opinion"
;
label define MV849   
     0 "No"
     1 "Yes"
     8 "Don't know/depends"
;
label define MV851A  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851B  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851C  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851D  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851E  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851F  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851G  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851H  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851I  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851J  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851K  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851L  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV852A  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV852B  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV852C  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV853A  
    95 "95+"
    98 "Don't know"
;
label define MV853B  
    95 "95+"
    98 "Don't know"
;
label define MV853C  
    95 "95+"
    98 "Don't know"
;
label define MV854A  
     0 "No"
     1 "Yes"
;
label define MV854B  
     0 "No"
     1 "Yes"
;
label define MG100   
     0 "No"
     1 "Yes"
;
label define MG101   
     0 "No"
     1 "Yes"
;
label define MG117A  
     0 "No"
     1 "Yes"
;
label define MG117B  
     0 "No"
     1 "Yes"
;
label define MG117C  
     0 "No"
     1 "Yes"
;
label define MG117D  
     0 "No"
     1 "Yes"
;
label define MG117E  
     0 "No"
     1 "Yes"
;
label define MG117F  
     0 "No"
     1 "Yes"
;
label define MG117G  
     0 "No"
     1 "Yes"
;
label define MG117H  
     0 "No"
     1 "Yes"
;
label define MG117I  
     0 "No"
     1 "Yes"
;
label define MG117J  
     0 "No"
     1 "Yes"
;
label define MG117X  
     0 "No"
     1 "Yes"
;
label define MG117Y  
     0 "No"
     1 "Yes"
;
label define MG118   
     0 "No"
     1 "Yes"
     3 "No religion"
     8 "Don't know"
;
label define MG119   
     1 "Continued"
     2 "Stopped"
     3 "Depends"
     8 "Don't know"
;
label define SMREGION
   101 "Nairobi"
   201 "Nyandarua"
   202 "Nyeri"
   203 "Kirinyaga"
   204 "Muranga"
   205 "Kiambu"
   301 "Mombasa"
   302 "Kwale"
   303 "Kilifi"
   304 "Tana River"
   305 "Lamu"
   306 "Taita Taveta"
   401 "Marsabit"
   402 "Isiolo"
   403 "Meru"
   404 "Tharaka"
   405 "Embu"
   406 "Kitui"
   407 "Machakos"
   408 "Makueni"
   501 "Garissa"
   502 "Wajir"
   503 "Mandera"
   601 "Siaya"
   602 "Kisumu"
   603 "Migori"
   604 "Homa Bay"
   605 "Kisii"
   606 "Nyamira"
   701 "Turkana"
   702 "West Pokot"
   703 "Samburu"
   704 "Trans-Nzoia"
   705 "Baringo"
   706 "Uasin Gishu"
   707 "Elgeyo Marak"
   708 "Nandi"
   709 "Laikipia"
   710 "Nakuru"
   711 "Narok"
   712 "Kajiado"
   713 "Kericho"
   714 "Bomet"
   801 "Kakamega"
   802 "Vihiga"
   803 "Bungoma"
   804 "Busia"
;
label define SMCOUNTY
    10 "Coast"
    11 ".   Mombasa"
    12 ".   Kwale"
    13 ".   Kilifi"
    14 ".   Tana River"
    15 ".   Lamu"
    16 ".   Taita Taveta"
    20 "North Eastern"
    21 ".   Garissa"
    22 ".   Wajir"
    23 ".   Mandera"
    30 "Eastern"
    31 ".   Marsabit"
    32 ".   Isiolo"
    33 ".   Meru"
    34 ".   Tharaka-Nithi"
    35 ".   Embu"
    36 ".   Kitui"
    37 ".   Machakos"
    38 ".   Makueni"
    40 "Central"
    41 ".   Nyandarua"
    42 ".   Nyeri"
    43 ".   Kirinyaga"
    44 ".   Murang'a"
    45 ".   Kiambu"
    50 "Rift Valley"
    51 ".   Turkana"
    52 ".   West Pokot"
    53 ".   Samburu"
    54 ".   Trans-Nzoia"
    55 ".   Uasin Gishu"
    56 ".   Elgeyo Marakwet"
    57 ".   Nandi"
    58 ".   Baringo"
    59 ".   Laikipia"
    60 ".   Nakuru"
    61 ".   Narok"
    62 ".   Kajiado"
    63 ".   Kericho"
    64 ".   Bomet"
    70 "Western"
    71 ".   Kakamega"
    72 ".   Vihiga"
    73 ".   Bungoma"
    74 ".   Busia"
    80 "Nyanza"
    81 ".   Siaya"
    82 ".   Kisumu"
    83 ".   Homa Bay"
    84 ".   Migori"
    85 ".   Kisii"
    86 ".   Nyamira"
    90 "Nairobi"
;
label define SMDV    
     0 "No"
     1 "Yes"
;
label define SMLQUEST
     1 "Borana"
     2 "Embu"
     3 "Kalenjin"
     4 "Kamba"
     5 "Kikuyu"
     6 "Kisii"
     7 "Luhya"
     8 "Maragoli"
     9 "Luo"
    10 "Maasai"
    11 "Meru"
    12 "Mijikenda"
    13 "Pokot"
    14 "Somali"
    15 "Swahili"
    16 "Turkana"
    17 "English"
;
label define SMLINTERVIEW
     1 "Borana"
     2 "Embu"
     3 "Kalenjin"
     4 "Kamba"
     5 "Kikuyu"
     6 "Kisii"
     7 "Luhya"
     8 "Maragoli"
     9 "Luo"
    10 "Maasai"
    11 "Meru"
    12 "Mijikenda"
    13 "Pokot"
    14 "Somali"
    15 "Swahili"
    16 "Turkana"
    17 "English"
    18 "Other"
;
label define SMLNATIVE
     1 "Borana"
     2 "Embu"
     3 "Kalenjin"
     4 "Kamba"
     5 "Kikuyu"
     6 "Kisii"
     7 "Luhya"
     8 "Maragoli"
     9 "Luo"
    10 "Maasai"
    11 "Meru"
    12 "Mijikenda"
    13 "Pokot"
    14 "Somali"
    15 "Swahili"
    16 "Turkana"
    17 "English"
    18 "Other"
;
label define SMTRANSLATOR
     0 "No"
     1 "Yes"
;
label define SMEDUC  
     0 "No education"
     1 "Primary incomplete"
     2 "Primary complete"
     3 "Secondary incomplete"
     4 "Secondary complete"
     5 "Higher"
;
label define MV044   
     0 "Man not selected"
     1 "Man selected and interviewed"
     2 "Man selected, but privacy not possible"
     3 "Man selected, but not interviewed"
;
label define SM101D  
     1 "Kenyan"
     2 "Tanzanian"
     3 "Ugandan"
     4 "Somali"
     5 "Ethiopian"
     6 "Sudanese"
    96 "Other"
;
label define SM101E  
     1 "Join family living In Kenya"
     2 "Marriage"
     3 "Work"
     4 "School"
     5 "Escape insecurity/war"
     6 "Escape environmental disaster (e.g. flood, drought, etc.)"
    96 "Other"
;
label define SM105   
     1 "Primary"
     2 "Post Primary/ Vocational"
     3 "Secondary/ 'A' Level"
     4 "College (Middle Level)"
     5 "University"
     8 "DK"
;
label define SM309Q  
     1 "Yes"
     0 "No"
     8 "Don't know"
;
label define SM313Q  
     1 "Yes"
     0 "No"
     8 "Don't know"
;
label define SM418A1 
     1 "Prevent STD/HIV"
     2 "Avoid Pregnancy"
     3 "Both Prevent STD/HIV and pregnancy"
     4 "Did not trust partner"
     5 "Partner wanted to use"
     6 "Other"
;
label define SM418A2 
     1 "Prevent STD/HIV"
     2 "Avoid Pregnancy"
     3 "Both Prevent STD/HIV and pregnancy"
     4 "Did not trust partner"
     5 "Partner wanted to use"
     6 "Other"
;
label define SM418A3 
     1 "Prevent STD/HIV"
     2 "Avoid Pregnancy"
     3 "Both Prevent STD/HIV and pregnancy"
     4 "Did not trust partner"
     5 "Partner wanted to use"
     6 "Other"
;
label define SM604B  
     1 "Own land"
     2 "Family land"
     3 "Rented land"
     4 "Someone else's land"
     6 "Other"
;
label define SM707A  
     1 "Yes"
     0 "No"
;
label define SM717B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM723AA 
     0 "No"
     1 "Yes"
;
label define SM723AB 
     0 "No"
     1 "Yes"
;
label define SM723AC 
     0 "No"
     1 "Yes"
;
label define SM723AD 
     0 "No"
     1 "Yes"
;
label define SM723AE 
     0 "No"
     1 "Yes"
;
label define SM723AF 
     0 "No"
     1 "Yes"
;
label define SM723AG 
     0 "No"
     1 "Yes"
;
label define SM723AH 
     0 "No"
     1 "Yes"
;
label define SM723AI 
     0 "No"
     1 "Yes"
;
label define SM723AJ 
     0 "No"
     1 "Yes"
;
label define SM723AK 
     0 "No"
     1 "Yes"
;
label define SM723AL 
     0 "No"
     1 "Yes"
;
label define SM723AW 
     0 "No"
     1 "Yes"
;
label define SM723AX 
     0 "No"
     1 "Yes"
;
label define SM723AY 
     0 "No"
     1 "Yes"
;
label define SM723AZ 
     0 "No"
     1 "Yes"
;
label define SM723BA 
     0 "No"
     1 "Yes"
;
label define SM723BB 
     0 "No"
     1 "Yes"
;
label define SM723BC 
     0 "No"
     1 "Yes"
;
label define SM723BD 
     0 "No"
     1 "Yes"
;
label define SM723BE 
     0 "No"
     1 "Yes"
;
label define SM723BF 
     0 "No"
     1 "Yes"
;
label define SM723BG 
     0 "No"
     1 "Yes"
;
label define SM723BH 
     0 "No"
     1 "Yes"
;
label define SM723BI 
     0 "No"
     1 "Yes"
;
label define SM723BJ 
     0 "No"
     1 "Yes"
;
label define SM723BK 
     0 "No"
     1 "Yes"
;
label define SM723BL 
     0 "No"
     1 "Yes"
;
label define SM723BW 
     0 "No"
     1 "Yes"
;
label define SM723BX 
     0 "No"
     1 "Yes"
;
label define SM723BY 
     0 "No"
     1 "Yes"
;
label define SM723BZ 
     0 "No"
     1 "Yes"
;
label define SM731A  
     1 "Yes, informed all partners"
     2 "Informed some, not all"
     3 "No, informed none"
     4 "Did not have a partner"
;
label define SM731B  
     0 "No"
     1 "Yes"
;
label define SM731CA 
     0 "No"
     1 "Yes"
;
label define SM731CB 
     0 "No"
     1 "Yes"
;
label define SM731CC 
     0 "No"
     1 "Yes"
;
label define SM807A  
     0 "No"
     1 "Yes"
;
label define SM807B  
     0 "No"
     1 "Yes"
;
label define SM807C  
     0 "No"
     1 "Yes"
;
label define SM807D  
     0 "No"
     1 "Yes"
;
label define SM807EA 
     0 "No"
     1 "Yes"
;
label define SM807EB 
     0 "No"
     1 "Yes"
;
label define SM807EC 
     0 "No"
     1 "Yes"
;
label define SM807ED 
     0 "No"
     1 "Yes"
;
label define SM807EE 
     0 "No"
     1 "Yes"
;
label define SM807EF 
     0 "No"
     1 "Yes"
;
label define SM807EG 
     0 "No"
     1 "Yes"
;
label define SM807EX 
     0 "No"
     1 "Yes"
;
label define SM811A  
     0 "No"
     1 "Yes"
;
label define SM811B  
    99 "Missing"
;
label define SM811CA 
     0 "No"
     1 "Yes"
;
label define SM811CB 
     0 "No"
     1 "Yes"
;
label define SM811D  
     0 "No"
     1 "Yes"
;
label define SM811E  
     0 "No"
     1 "Yes"
;
label define SM811F  
     0 "No"
     1 "Yes"
;
label define SM811G  
     0 "No"
     1 "Yes"
;
label define SM811H  
     0 "No"
     1 "Yes"
;
label define SM811I  
     0 "No"
     1 "Yes"
;
label define SM902A  
     0 "No"
     1 "Yes"
     8 "dont know"
;
label define MD101A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MD101B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MD101C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MD101D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MD101E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MD101F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MD101G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MD101H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MD101I  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MD101J  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MD102   
    99 "Missing"
;
label define MD103A  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD103B  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD103C  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD103D  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD103E  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD103F  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD104   
     0 "No"
     1 "Yes"
;
label define MD105A  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD105B  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD105C  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD105D  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD105E  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD105F  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD105G  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD105H  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD105I  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD105J  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD105K  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD105L  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD105M  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD105N  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD106   
     0 "No"
     1 "Yes"
;
label define MD107   
     0 "No"
     1 "Yes"
;
label define MD108   
     0 "No"
     1 "Yes"
;
label define MD109   
    95 "Before union"
    96 "After separation/divorce"
    98 "Don't know"
;
label define MD110A  
     0 "No"
     1 "Yes"
;
label define MD110B  
     0 "No"
     1 "Yes"
;
label define MD110C  
     0 "No"
     1 "Yes"
;
label define MD110D  
     0 "No"
     1 "Yes"
;
label define MD110E  
     0 "No"
     1 "Yes"
;
label define MD110F  
     0 "No"
     1 "Yes"
;
label define MD110G  
     0 "No"
     1 "Yes"
;
label define MD110H  
     0 "No"
     1 "Yes"
;
label define MD111   
     0 "No"
     1 "Yes"
;
label define MD112   
     0 "No"
     1 "Yes"
;
label define MD112A  
     0 "Not at all in last 12 months"
     1 "Often"
     2 "Sometimes"
     8 "Don't know"
;
label define MD113   
     0 "No"
     1 "Yes"
;
label define MD114   
     0 "Never"
     1 "Often"
     2 "Sometimes"
;
label define MD115B  
     0 "No"
     1 "Yes"
;
label define MD115C  
     0 "No"
     1 "Yes"
;
label define MD115D  
     0 "No"
     1 "Yes"
;
label define MD115E  
     0 "No"
     1 "Yes"
;
label define MD115F  
     0 "No"
     1 "Yes"
;
label define MD115G  
     0 "No"
     1 "Yes"
;
label define MD115H  
     0 "No"
     1 "Yes"
;
label define MD115I  
     0 "No"
     1 "Yes"
;
label define MD115J  
     0 "No"
     1 "Yes"
;
label define MD115K  
     0 "No"
     1 "Yes"
;
label define MD115L  
     0 "No"
     1 "Yes"
;
label define MD115M  
     0 "No"
     1 "Yes"
;
label define MD115N  
     0 "No"
     1 "Yes"
;
label define MD115O  
     0 "No"
     1 "Yes"
;
label define MD115P  
     0 "No"
     1 "Yes"
;
label define MD115Q  
     0 "No"
     1 "Yes"
;
label define MD115R  
     0 "No"
     1 "Yes"
;
label define MD115S  
     0 "No"
     1 "Yes"
;
label define MD115T  
     0 "No"
     1 "Yes"
;
label define MD115U  
     0 "No"
     1 "Yes"
;
label define MD115V  
     0 "No"
     1 "Yes"
;
label define MD115W  
     0 "No"
     1 "Yes"
;
label define MD115X  
     0 "No"
     1 "Yes"
;
label define MD115Y  
     0 "Someone physically hurt respondent"
     1 "None of these people ever physically hurt respondent"
     6 "No response to question"
;
label define MD115XA 
     0 "No"
     1 "Yes"
;
label define MD115XB 
     0 "No"
     1 "Yes"
;
label define MD115XC 
     0 "No"
     1 "Yes"
;
label define MD115XD 
     0 "No"
     1 "Yes"
;
label define MD115XE 
     0 "No"
     1 "Yes"
;
label define MD115XF 
     0 "No"
     1 "Yes"
;
label define MD115XG 
     0 "No"
     1 "Yes"
;
label define MD115XH 
     0 "No"
     1 "Yes"
;
label define MD115XI 
     0 "No"
     1 "Yes"
;
label define MD115XJ 
     0 "No"
     1 "Yes"
;
label define MD115XK 
     0 "No"
     1 "Yes"
;
label define MD116   
     0 "No one else ever physically hurt respondent"
     1 "BLANK (Husband/partner skipped for this question)"
     2 "Mother"
     3 "Father"
     4 "Daughter"
     5 "Son"
     6 "Sister"
     7 "Brother"
     8 "Other female relatives"
     9 "Other male relatives"
    10 "Former partner"
    11 "Current boyfriend"
    12 "Former boyfriend"
    13 "Step-mother"
    14 "Step-father"
    15 "Mother-in-law"
    16 "Father-in-law"
    17 "Other female in-laws"
    18 "Other male in-laws"
    19 "Female friend, acquaintance"
    20 "Male friend, acquaintance"
    21 "Neighbor"
    22 "Teacher"
    23 "Employer"
    27 "Stranger"
    28 "Other female relative/in-law"
    29 "Other male relative/in-law"
    30 "Friend"
    31 "Police"
    95 "No response (MD115Y=6)"
    96 "Other"
;
label define MD117A  
     0 "Not at all"
     1 "Often"
     2 "Sometimes"
;
label define MD119A  
     0 "No"
     1 "Yes"
;
label define MD119B  
     0 "No"
     1 "Yes"
;
label define MD119C  
     0 "No"
     1 "Yes"
;
label define MD119D  
     0 "No"
     1 "Yes"
;
label define MD119E  
     0 "No"
     1 "Yes"
;
label define MD119F  
     0 "No"
     1 "Yes"
;
label define MD119G  
     0 "No"
     1 "Yes"
;
label define MD119H  
     0 "No"
     1 "Yes"
;
label define MD119I  
     0 "No"
     1 "Yes"
;
label define MD119J  
     0 "No"
     1 "Yes"
;
label define MD119K  
     0 "No"
     1 "Yes"
;
label define MD119L  
     0 "No"
     1 "Yes"
;
label define MD119M  
     0 "No"
     1 "Yes"
;
label define MD119N  
     0 "No"
     1 "Yes"
;
label define MD119O  
     0 "No"
     1 "Yes"
;
label define MD119P  
     0 "No"
     1 "Yes"
;
label define MD119Q  
     0 "No"
     1 "Yes"
;
label define MD119R  
     0 "No"
     1 "Yes"
;
label define MD119S  
     0 "No"
     1 "Yes"
;
label define MD119T  
     0 "No"
     1 "Yes"
;
label define MD119U  
     0 "No"
     1 "Yes"
;
label define MD119V  
     0 "No"
     1 "Yes"
;
label define MD119W  
     0 "No"
     1 "Yes"
;
label define MD119X  
     0 "No"
     1 "Yes"
;
label define MD119Y  
     0 "Sought help from someone"
     1 "No help was sought"
;
label define MD119XA 
     0 "No"
     1 "Yes"
;
label define MD119XB 
     0 "No"
     1 "Yes"
;
label define MD119XC 
     0 "No"
     1 "Yes"
;
label define MD119XD 
     0 "No"
     1 "Yes"
;
label define MD119XE 
     0 "No"
     1 "Yes"
;
label define MD119XF 
     0 "No"
     1 "Yes"
;
label define MD119XG 
     0 "No"
     1 "Yes"
;
label define MD119XH 
     0 "No"
     1 "Yes"
;
label define MD119XI 
     0 "No"
     1 "Yes"
;
label define MD119XJ 
     0 "No"
     1 "Yes"
;
label define MD119XK 
     0 "No"
     1 "Yes"
;
label define MD120   
     1 "Don't know where to go to"
     2 "No use"
     3 "Part of life"
     4 "Afraid of divorce"
     5 "Afraid of further beatings"
     6 "Afraid of getting the person in trouble"
     7 "Embarrassed"
     8 "Don't want to disgrace family"
     9 "No money"
    96 "Other"
;
label define MD121   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MD122A  
     0 "No"
     1 "Yes, once"
     2 "Yes, more than once"
;
label define MD122B  
     0 "No"
     1 "Yes, once"
     2 "Yes, more than once"
;
label define MD122C  
     0 "No"
     1 "Yes, once"
     2 "Yes, more than once"
;
label define MD123   
     1 "Wanted"
     2 "Forced"
     6 "Refused to answer/no response"
;
label define MD124   
     0 "No"
     1 "Yes"
     6 "Refused to answer/no response"
;
label define MD125   
     0 "No"
     1 "Yes"
     6 "Refused to answer/no response"
;
label define MD126   
    98 "Don't know"
;
label define MD127   
     1 "Current husband/partner"
     2 "Former husband/partner"
     3 "Current/former boyfriend"
     4 "Father/step father"
     5 "Brother/step brother"
     6 "Other relative"
     7 "In-law"
     8 "Own friend/acquaintance"
     9 "Family friend"
    10 "Teacher"
    11 "Employer/someone at work"
    12 "Police/soldier"
    13 "Priest/religious leader"
    14 "Stranger"
    96 "Other"
;
label define MD128   
     0 "No"
     1 "Yes"
;
label define MD129   
     0 "Never afraid"
     1 "Most of the time afraid"
     2 "Sometimes afraid"
;
label define MD130A  
     0 "Never"
     1 "0-11 months ago"
     2 "12+ months ago"
     3 "Yes, but don't remember when"
     4 "Yes, but frequency in last 12 months missing"
;
label define MD130B  
     0 "Never"
     1 "0-11 months ago"
     2 "12+ months ago"
     3 "Yes, but don't remember when"
     4 "Yes, but frequency in last 12 months missing"
;

#delimit cr
label values mv013    MV013   
label values mv014    MV014   
label values mv015    MV015   
label values mv024    MV024   
label values mv025    MV025   
label values mv026    MV026   
label values mv034_1  MV034   
label values mv034_2  MV034   
label values mv034_3  MV034   
label values mv034_4  MV034   
label values mv034_5  MV034   
label values mv034_6  MV034   
label values mv034_7  MV034   
label values mv034_8  MV034   
label values mv034a_1 MV034A  
label values mv034a_2 MV034A  
label values mv034a_3 MV034A  
label values mv034a_4 MV034A  
label values mv034a_5 MV034A  
label values mv034a_6 MV034A  
label values mv034a_7 MV034A  
label values mv034a_8 MV034A  
label values mv035    MV035   
label values mv803    MV803   
label values mv101    MV101   
label values mv102    MV102   
label values mv103    MV103   
label values mv104    MV104   
label values mv105    MV105   
label values mv106    MV106   
label values mv107    MV107   
label values mv130    MV130   
label values mv131    MV131   
label values mv133    MV133   
label values mv134    MV134   
label values mv135    MV135   
label values mv149    MV149   
label values mv150    MV150   
label values mv151    MV151   
label values mv152    MV152   
label values mv155    MV155   
label values mv156    MV156   
label values mv157    MV157   
label values mv158    MV158   
label values mv159    MV159   
label values mv167    MV167   
label values mv168    MV168   
label values mv190    MV190   
label values mv213    MV213   
label values mv217    MV217   
label values mv225    MV225   
label values mv246    MV246   
label values mv248    MV248   
label values mv249    MV249   
label values mv250    MV250   
label values mv251    MV251   
label values mv252    MV252   
label values mv301    MV301   
label values mv302    MV302   
label values m304a_01 M304A   
label values m304a_02 M304A   
label values m304a_03 M304A   
label values m304a_04 M304A   
label values m304a_05 M304A   
label values m304a_06 M304A   
label values m304a_07 M304A   
label values m304a_08 M304A   
label values m304a_09 M304A   
label values m304a_10 M304A   
label values m304a_11 M304A   
label values m304a_12 M304A   
label values m304a_13 M304A   
label values m304a_14 M304A   
label values m304a_15 M304A   
label values m304a_16 M304A   
label values m304a_17 M304A   
label values m304a_18 M304A   
label values m304a_19 M304A   
label values m304a_20 M304A   
label values mv304_01 MV304   
label values mv304_02 MV304   
label values mv304_03 MV304   
label values mv304_04 MV304   
label values mv304_05 MV304   
label values mv304_06 MV304   
label values mv304_07 MV304   
label values mv304_08 MV304   
label values mv304_09 MV304   
label values mv304_10 MV304   
label values mv304_11 MV304   
label values mv304_12 MV304   
label values mv304_13 MV304   
label values mv304_14 MV304   
label values mv304_15 MV304   
label values mv304_16 MV304   
label values mv304_17 MV304   
label values mv304_18 MV304   
label values mv304_19 MV304   
label values mv304_20 MV304   
label values mv305_01 MV305   
label values mv305_02 MV305   
label values mv305_03 MV305   
label values mv305_04 MV305   
label values mv305_05 MV305   
label values mv305_06 MV305   
label values mv305_07 MV305   
label values mv305_08 MV305   
label values mv305_09 MV305   
label values mv305_10 MV305   
label values mv305_11 MV305   
label values mv305_12 MV305   
label values mv305_13 MV305   
label values mv305_14 MV305   
label values mv305_15 MV305   
label values mv305_16 MV305   
label values mv305_17 MV305   
label values mv305_18 MV305   
label values mv305_19 MV305   
label values mv305_20 MV305   
label values mv307_01 MV307   
label values mv307_02 MV307   
label values mv307_03 MV307   
label values mv307_04 MV307   
label values mv307_05 MV307   
label values mv307_06 MV307   
label values mv307_07 MV307   
label values mv307_08 MV307   
label values mv307_09 MV307   
label values mv307_10 MV307   
label values mv307_11 MV307   
label values mv307_12 MV307   
label values mv307_13 MV307   
label values mv307_14 MV307   
label values mv307_15 MV307   
label values mv307_16 MV307   
label values mv307_17 MV307   
label values mv307_18 MV307   
label values mv307_19 MV307   
label values mv307_20 MV307   
label values mv312    MV312   
label values mv313    MV313   
label values mv323a   MV323A  
label values mv325b   MV325B  
label values mv372a   MV372A  
label values mv384a   MV384A  
label values mv384b   MV384B  
label values mv384c   MV384C  
label values mv395    MV395   
label values mv396    MV396   
label values mv3a09b  MV3A09B 
label values mv3b17   MV3B17  
label values mv3b25a  MV3B25A 
label values mv3b25b  MV3B25B 
label values mv463a   MV463A  
label values mv463b   MV463B  
label values mv463c   MV463C  
label values mv463d   MV463D  
label values mv463e   MV463E  
label values mv463f   MV463F  
label values mv463g   MV463G  
label values mv463x   MV463X  
label values mv463z   MV463Z  
label values mv464    MV464   
label values mv474    MV474   
label values mv474a   MV474A  
label values mv474b   MV474B  
label values mv474c   MV474C  
label values mv474d   MV474D  
label values mv474e   MV474E  
label values mv474f   MV474F  
label values mv474g   MV474G  
label values mv474h   MV474H  
label values mv474i   MV474I  
label values mv474j   MV474J  
label values mv474x   MV474X  
label values mv474z   MV474Z  
label values mv475    MV475   
label values mv476    MV476   
label values mv477    MV477   
label values mv478    MV478   
label values mv479    MV479   
label values mv480    MV480   
label values mv481    MV481   
label values mv481a   MV481A  
label values mv481b   MV481B  
label values mv481c   MV481C  
label values mv481d   MV481D  
label values mv481e   MV481E  
label values mv481f   MV481F  
label values mv481g   MV481G  
label values mv481h   MV481H  
label values mv481x   MV481X  
label values mv482a   MV482A  
label values mv482b   MV482B  
label values mv482c   MV482C  
label values mv483    MV483   
label values mv483a   MV483A  
label values mv483b   MV483B  
label values mv483c   MV483C  
label values mv501    MV501   
label values mv502    MV502   
label values mv503    MV503   
label values mv504    MV504   
label values mv510    MV510   
label values mv513    MV513   
label values mv525    MV525   
label values mv527    MV527   
label values mv528    MV528   
label values mv529    MV529   
label values mv531    MV531   
label values mv532    MV532   
label values mv535    MV535   
label values mv536    MV536   
label values mv541    MV541   
label values mv602    MV602   
label values mv603    MV603   
label values mv604    MV604   
label values mv605    MV605   
label values mv613    MV613   
label values mv614    MV614   
label values mv616    MV616   
label values mv621    MV621   
label values mv627    MV627   
label values mv628    MV628   
label values mv629    MV629   
label values mv631    MV631   
label values mv633a   MV633A  
label values mv633b   MV633B  
label values mv633c   MV633C  
label values mv633d   MV633D  
label values mv633e   MV633E  
label values mv633f   MV633F  
label values mv633g   MV633G  
label values mv634a   MV634A  
label values mv634b   MV634B  
label values mv634c   MV634C  
label values mv634d   MV634D  
label values mv714    MV714   
label values mv714a   MV714A  
label values mv716    MV716   
label values mv717    MV717   
label values mv719    MV719   
label values mv721    MV721   
label values mv731    MV731   
label values mv732    MV732   
label values mv739    MV739   
label values mv740    MV740   
label values mv741    MV741   
label values mv743a   MV743A  
label values mv743b   MV743B  
label values mv743c   MV743C  
label values mv743d   MV743D  
label values mv743e   MV743E  
label values mv743f   MV743F  
label values mv743g   MV743G  
label values mv744a   MV744A  
label values mv744b   MV744B  
label values mv744c   MV744C  
label values mv744d   MV744D  
label values mv744e   MV744E  
label values mv745a   MV745A  
label values mv745b   MV745B  
label values mv747a   MV747A  
label values mv747b   MV747B  
label values mv750    MV750   
label values mv751    MV751   
label values mv754bp  MV754BP 
label values mv754cp  MV754CP 
label values mv754dp  MV754DP 
label values mv754jp  MV754JP 
label values mv754wp  MV754WP 
label values mv756    MV756   
label values mv761    MV761   
label values mv761b   MV761B  
label values mv761c   MV761C  
label values mv762aa  MV762AA 
label values mv762ab  MV762AB 
label values mv762ac  MV762AC 
label values mv762ad  MV762AD 
label values mv762ae  MV762AE 
label values mv762af  MV762AF 
label values mv762ag  MV762AG 
label values mv762ah  MV762AH 
label values mv762ai  MV762AI 
label values mv762aj  MV762AJ 
label values mv762ak  MV762AK 
label values mv762al  MV762AL 
label values mv762am  MV762AM 
label values mv762an  MV762AN 
label values mv762ao  MV762AO 
label values mv762ap  MV762AP 
label values mv762aq  MV762AQ 
label values mv762ar  MV762AR 
label values mv762as  MV762AS 
label values mv762at  MV762AT 
label values mv762au  MV762AU 
label values mv762av  MV762AV 
label values mv762aw  MV762AW 
label values mv762ax  MV762AX 
label values mv762az  MV762AZ 
label values mv762ba  MV762BA 
label values mv762bb  MV762BB 
label values mv762bc  MV762BC 
label values mv762bd  MV762BD 
label values mv762be  MV762BE 
label values mv762bf  MV762BF 
label values mv762bg  MV762BG 
label values mv762bh  MV762BH 
label values mv762bi  MV762BI 
label values mv762bj  MV762BJ 
label values mv762bk  MV762BK 
label values mv762bl  MV762BL 
label values mv762bm  MV762BM 
label values mv762bn  MV762BN 
label values mv762bo  MV762BO 
label values mv762bp  MV762BP 
label values mv762bq  MV762BQ 
label values mv762br  MV762BR 
label values mv762bs  MV762BS 
label values mv762bt  MV762BT 
label values mv762bu  MV762BU 
label values mv762bv  MV762BV 
label values mv762bw  MV762BW 
label values mv762bx  MV762BX 
label values mv762bz  MV762BZ 
label values mv763a   MV763A  
label values mv763b   MV763B  
label values mv763c   MV763C  
label values mv763d   MV763D  
label values mv763e   MV763E  
label values mv763f   MV763F  
label values mv763g   MV763G  
label values mv766a   MV766A  
label values mv766b   MV766B  
label values mv767a   MV767A  
label values mv767b   MV767B  
label values mv767c   MV767C  
label values mv768a   MV768A  
label values mv768b   MV768B  
label values mv768c   MV768C  
label values mv769    MV769   
label values mv769a   MV769A  
label values mv770    MV770   
label values mv770a   MV770A  
label values mv770b   MV770B  
label values mv770c   MV770C  
label values mv770d   MV770D  
label values mv770e   MV770E  
label values mv770f   MV770F  
label values mv770g   MV770G  
label values mv770h   MV770H  
label values mv770i   MV770I  
label values mv770j   MV770J  
label values mv770k   MV770K  
label values mv770l   MV770L  
label values mv770m   MV770M  
label values mv770n   MV770N  
label values mv770o   MV770O  
label values mv770p   MV770P  
label values mv770q   MV770Q  
label values mv770r   MV770R  
label values mv770s   MV770S  
label values mv770t   MV770T  
label values mv770u   MV770U  
label values mv770v   MV770V  
label values mv770w   MV770W  
label values mv770x   MV770X  
label values mv774a   MV774A  
label values mv774b   MV774B  
label values mv774c   MV774C  
label values mv775    MV775   
label values mv777    MV777   
label values mv778    MV778   
label values mv779    MV779   
label values mv780    MV780   
label values mv781    MV781   
label values mv783    MV783   
label values mv784a   MV784A  
label values mv784b   MV784B  
label values mv784c   MV784C  
label values mv784d   MV784D  
label values mv784e   MV784E  
label values mv784f   MV784F  
label values mv784g   MV784G  
label values mv784h   MV784H  
label values mv784i   MV784I  
label values mv784j   MV784J  
label values mv784k   MV784K  
label values mv784l   MV784L  
label values mv784m   MV784M  
label values mv784n   MV784N  
label values mv784o   MV784O  
label values mv784p   MV784P  
label values mv784q   MV784Q  
label values mv784r   MV784R  
label values mv784s   MV784S  
label values mv784t   MV784T  
label values mv784u   MV784U  
label values mv784v   MV784V  
label values mv784x   MV784X  
label values mv785    MV785   
label values mv791    MV791   
label values mv793    MV793   
label values mv793a   MV793A  
label values mv793b   MV793B  
label values mv820    MV820   
label values mv822    MV822   
label values mv823    MV823   
label values mv824    MV824   
label values mv825    MV825   
label values mv826    MV826   
label values mv826a   MV826A  
label values mv827    MV827   
label values mv828    MV828   
label values mv829    MV829   
label values mv832b   MV832B  
label values mv832c   MV832C  
label values mv833a   MV833A  
label values mv833b   MV833B  
label values mv833c   MV833C  
label values mv834a   MV834A  
label values mv834b   MV834B  
label values mv834c   MV834C  
label values mv835a   MV835A  
label values mv835b   MV835B  
label values mv835c   MV835C  
label values mv836    MV836   
label values mv837    MV837   
label values mv844    MV844   
label values mv845    MV845   
label values mv846    MV846   
label values mv847    MV847   
label values mv848    MV848   
label values mv849    MV849   
label values mv851a   MV851A  
label values mv851b   MV851B  
label values mv851c   MV851C  
label values mv851d   MV851D  
label values mv851e   MV851E  
label values mv851f   MV851F  
label values mv851g   MV851G  
label values mv851h   MV851H  
label values mv851i   MV851I  
label values mv851j   MV851J  
label values mv851k   MV851K  
label values mv851l   MV851L  
label values mv852a   MV852A  
label values mv852b   MV852B  
label values mv852c   MV852C  
label values mv853a   MV853A  
label values mv853b   MV853B  
label values mv853c   MV853C  
label values mv854a   MV854A  
label values mv854b   MV854B  
label values mg100    MG100   
label values mg101    MG101   
label values mg117a   MG117A  
label values mg117b   MG117B  
label values mg117c   MG117C  
label values mg117d   MG117D  
label values mg117e   MG117E  
label values mg117f   MG117F  
label values mg117g   MG117G  
label values mg117h   MG117H  
label values mg117i   MG117I  
label values mg117j   MG117J  
label values mg117x   MG117X  
label values mg117y   MG117Y  
label values mg118    MG118   
label values mg119    MG119   
label values smregion SMREGION
label values smcounty SMCOUNTY
label values smdv     SMDV    
label values smlquest SMLQUEST
label values smlinterview SMLINTERVIEW
label values smlnative SMLNATIVE
label values smtranslator SMTRANSLATOR
label values smeduc   SMEDUC  
label values mv044    MV044   
label values sm101d   SM101D  
label values sm101e   SM101E  
label values sm105    SM105   
label values sm309q   SM309Q  
label values sm313q   SM313Q  
label values sm418a1  SM418A1 
label values sm418a2  SM418A2 
label values sm418a3  SM418A3 
label values sm604b   SM604B  
label values sm707a   SM707A  
label values sm717b   SM717B  
label values sm723aa  SM723AA 
label values sm723ab  SM723AB 
label values sm723ac  SM723AC 
label values sm723ad  SM723AD 
label values sm723ae  SM723AE 
label values sm723af  SM723AF 
label values sm723ag  SM723AG 
label values sm723ah  SM723AH 
label values sm723ai  SM723AI 
label values sm723aj  SM723AJ 
label values sm723ak  SM723AK 
label values sm723al  SM723AL 
label values sm723aw  SM723AW 
label values sm723ax  SM723AX 
label values sm723ay  SM723AY 
label values sm723az  SM723AZ 
label values sm723ba  SM723BA 
label values sm723bb  SM723BB 
label values sm723bc  SM723BC 
label values sm723bd  SM723BD 
label values sm723be  SM723BE 
label values sm723bf  SM723BF 
label values sm723bg  SM723BG 
label values sm723bh  SM723BH 
label values sm723bi  SM723BI 
label values sm723bj  SM723BJ 
label values sm723bk  SM723BK 
label values sm723bl  SM723BL 
label values sm723bw  SM723BW 
label values sm723bx  SM723BX 
label values sm723by  SM723BY 
label values sm723bz  SM723BZ 
label values sm731a   SM731A  
label values sm731b   SM731B  
label values sm731ca  SM731CA 
label values sm731cb  SM731CB 
label values sm731cc  SM731CC 
label values sm807a   SM807A  
label values sm807b   SM807B  
label values sm807c   SM807C  
label values sm807d   SM807D  
label values sm807ea  SM807EA 
label values sm807eb  SM807EB 
label values sm807ec  SM807EC 
label values sm807ed  SM807ED 
label values sm807ee  SM807EE 
label values sm807ef  SM807EF 
label values sm807eg  SM807EG 
label values sm807ex  SM807EX 
label values sm811a   SM811A  
label values sm811ca  SM811CA 
label values sm811cb  SM811CB 
label values sm811d   SM811D  
label values sm811e   SM811E  
label values sm811f   SM811F  
label values sm811g   SM811G  
label values sm811h   SM811H  
label values sm811i   SM811I  
label values sm902a   SM902A  
label values md101a   MD101A  
label values md101b   MD101B  
label values md101c   MD101C  
label values md101d   MD101D  
label values md101e   MD101E  
label values md101f   MD101F  
label values md101g   MD101G  
label values md101h   MD101H  
label values md101i   MD101I  
label values md101j   MD101J  
label values md103a   MD103A  
label values md103b   MD103B  
label values md103c   MD103C  
label values md103d   MD103D  
label values md103e   MD103E  
label values md103f   MD103F  
label values md104    MD104   
label values md105a   MD105A  
label values md105b   MD105B  
label values md105c   MD105C  
label values md105d   MD105D  
label values md105e   MD105E  
label values md105f   MD105F  
label values md105g   MD105G  
label values md105h   MD105H  
label values md105i   MD105I  
label values md105j   MD105J  
label values md105k   MD105K  
label values md105l   MD105L  
label values md105m   MD105M  
label values md105n   MD105N  
label values md106    MD106   
label values md107    MD107   
label values md108    MD108   
label values md109    MD109   
label values md110a   MD110A  
label values md110b   MD110B  
label values md110c   MD110C  
label values md110d   MD110D  
label values md110e   MD110E  
label values md110f   MD110F  
label values md110g   MD110G  
label values md110h   MD110H  
label values md111    MD111   
label values md112    MD112   
label values md112a   MD112A  
label values md113    MD113   
label values md114    MD114   
label values md115b   MD115B  
label values md115c   MD115C  
label values md115d   MD115D  
label values md115e   MD115E  
label values md115f   MD115F  
label values md115g   MD115G  
label values md115h   MD115H  
label values md115i   MD115I  
label values md115j   MD115J  
label values md115k   MD115K  
label values md115l   MD115L  
label values md115m   MD115M  
label values md115n   MD115N  
label values md115o   MD115O  
label values md115p   MD115P  
label values md115q   MD115Q  
label values md115r   MD115R  
label values md115s   MD115S  
label values md115t   MD115T  
label values md115u   MD115U  
label values md115v   MD115V  
label values md115w   MD115W  
label values md115x   MD115X  
label values md115y   MD115Y  
label values md115xa  MD115XA 
label values md115xb  MD115XB 
label values md115xc  MD115XC 
label values md115xd  MD115XD 
label values md115xe  MD115XE 
label values md115xf  MD115XF 
label values md115xg  MD115XG 
label values md115xh  MD115XH 
label values md115xi  MD115XI 
label values md115xj  MD115XJ 
label values md115xk  MD115XK 
label values md116    MD116   
label values md117a   MD117A  
label values md119a   MD119A  
label values md119b   MD119B  
label values md119c   MD119C  
label values md119d   MD119D  
label values md119e   MD119E  
label values md119f   MD119F  
label values md119g   MD119G  
label values md119h   MD119H  
label values md119i   MD119I  
label values md119j   MD119J  
label values md119k   MD119K  
label values md119l   MD119L  
label values md119m   MD119M  
label values md119n   MD119N  
label values md119o   MD119O  
label values md119p   MD119P  
label values md119q   MD119Q  
label values md119r   MD119R  
label values md119s   MD119S  
label values md119t   MD119T  
label values md119u   MD119U  
label values md119v   MD119V  
label values md119w   MD119W  
label values md119x   MD119X  
label values md119y   MD119Y  
label values md119xa  MD119XA 
label values md119xb  MD119XB 
label values md119xc  MD119XC 
label values md119xd  MD119XD 
label values md119xe  MD119XE 
label values md119xf  MD119XF 
label values md119xg  MD119XG 
label values md119xh  MD119XH 
label values md119xi  MD119XI 
label values md119xj  MD119XJ 
label values md119xk  MD119XK 
label values md120    MD120   
label values md121    MD121   
label values md122a   MD122A  
label values md122b   MD122B  
label values md122c   MD122C  
label values md123    MD123   
label values md124    MD124   
label values md125    MD125   
label values md126    MD126   
label values md127    MD127   
label values md128    MD128   
label values md129    MD129   
label values md130a   MD130A  
label values md130b   MD130B  
