infix using "C:\COUNTRIES\GH7B\GHKR7BFL.dct"

label variable caseid   "Case Identification"
label variable hidxa    "Index to birth history"
label variable v000     "Country code and phase"
label variable v001     "Cluster number"
label variable v002     "Household number"
label variable v003     "Respondent's line number"
label variable v004     "Ultimate area unit"
label variable v005     "Women's individual sample weight (6 decimals)"
label variable v006     "Month of interview"
label variable v007     "Year of interview"
label variable v008     "Date of interview (CMC)"
label variable v008a    "Date of interview Century Day Code (CDC)"
label variable v009     "Respondent's month of birth"
label variable v010     "Respondent's year of birth"
label variable v011     "Date of birth (CMC)"
label variable v012     "Respondent's current age"
label variable v013     "Age in 5-year groups"
label variable v014     "Completeness of age information"
label variable v015     "Result of individual interview"
label variable v016     "Day of interview"
label variable v020     "Ever-married sample"
label variable v021     "Primary sampling unit"
label variable v022     "Sample strata for sampling errors"
label variable v023     "Stratification used in sample design"
label variable v024     "Region"
label variable v025     "Type of place of residence"
label variable v027     "Number of visits"
label variable v028     "Interviewer identification"
label variable v030     "Field supervisor"
label variable v040     "Cluster altitude in meters"
label variable v042     "Household selected for hemoglobin"
label variable v045a    "Language of questionnaire"
label variable v045b    "Language of interview"
label variable v045c    "Native language of respondent"
label variable v046     "Translator used"
label variable v101     "Region"
label variable v102     "Type of place of residence"
label variable v106     "Highest educational level"
label variable v107     "Highest year of education"
label variable v113     "Source of drinking water"
label variable v115     "Time to get to water source"
label variable v116     "Type of toilet facility"
label variable v119     "Household has: electricity"
label variable v120     "Household has: radio"
label variable v121     "Household has: television"
label variable v122     "Household has: refrigerator"
label variable v123     "Household has: bicycle"
label variable v124     "Household has: motorcycle/scooter"
label variable v125     "Household has: car/truck"
label variable v127     "Main floor material"
label variable v128     "Main wall material"
label variable v129     "Main roof material"
label variable v130     "Religion"
label variable v131     "Ethnicity"
label variable v133     "Education in single years"
label variable v135     "Usual resident or visitor"
label variable v136     "Number of household members (listed)"
label variable v137     "Number of children 5 and under in household (de jure)"
label variable v138     "Number of eligible women in household (de facto)"
label variable v139     "De jure region of residence"
label variable v140     "De jure type of place of residence"
label variable v149     "Educational attainment"
label variable v150     "Relationship to household head"
label variable v151     "Sex of household head"
label variable v152     "Age of household head"
label variable v153     "Household has: telephone (land-line)"
label variable v155     "Literacy"
label variable v160     "Toilet facilities shared with other households"
label variable v161     "Type of cooking fuel"
label variable v190     "Wealth index combined"
label variable v191     "Wealth index factor score combined (5 decimals)"
label variable v190a    "Wealth index for urban/rural"
label variable v191a    "Wealth index factor score for urban/rural (5 decimals)"
label variable ml101    "Type of mosquito bed net(s) slept under last night"
label variable v201     "Total children ever born"
label variable v202     "Sons at home"
label variable v203     "Daughters at home"
label variable v204     "Sons elsewhere"
label variable v205     "Daughters elsewhere"
label variable v206     "Sons who have died"
label variable v207     "Daughters who have died"
label variable v208     "Births in last five years"
label variable v209     "Births in past year"
label variable v210     "Births in month of interview"
label variable v213     "Currently pregnant"
label variable v214     "Duration of current pregnancy"
label variable v218     "Number of living children"
label variable v219     "Living children + current pregnancy"
label variable v220     "Living children + current pregnancy (grouped)"
label variable v222     "Last birth to interview (months)"
label variable v223     "Completeness of current pregnancy information"
label variable v224     "Entries in birth history"
label variable v237     "Birth between last and interview"
label variable v238     "Births in last three years"
label variable v417     "Entries in pregnancy and postnatal care roster"
label variable v418a    "Entries in child health roster"
label variable v419     "Entries in height/weight roster"
label variable v459     "Have mosquito bed net for sleeping (from household questionnaire)"
label variable v460     "Children under 5 slept under mosquito bed net last night (household questionnair"
label variable v461     "Respondent slept under mosquito bed net"
label variable v468     "Record for Last Birth"
label variable v481     "Covered by health insurance"
label variable v481a    "Health insurance type: mutual/community organization"
label variable v481b    "Health insurance type: provided by employer"
label variable v481c    "Health insurance type: social security (National/district health insurance by NH"
label variable v481d    "Health insurance type: private/commercially purchased"
label variable v481e    "NA - Health insurance type: CS"
label variable v481f    "NA - Health insurance type: CS"
label variable v481g    "NA - Health insurance type: CS"
label variable v481h    "NA - Health insurance type: CS"
label variable v481x    "Health insurance type: other"
label variable bidx     "Birth column number"
label variable bord     "Birth order number"
label variable b0       "Child is twin"
label variable b1       "Month of birth"
label variable b2       "Year of birth"
label variable b3       "Date of birth (CMC)"
label variable b4       "Sex of child"
label variable b5       "Child is alive"
label variable b8       "Current age of child"
label variable b9       "Child lives with whom"
label variable b10      "Completeness of information"
label variable b11      "Preceding birth interval (months)"
label variable b12      "Succeeding birth interval (months)"
label variable b15      "Live birth between births"
label variable b16      "Child's line number in household"
label variable b17      "Day of birth"
label variable b18      "Century Day Code of birth (CDC)"
label variable b19      "Current age of child in months (months since birth for dead children)"
label variable midx     "Index to Birth History"
label variable m2a      "Prenatal: doctor"
label variable m2b      "Prenatal: nurse/midwife"
label variable m2c      "Prenatal: community health officer/nurse"
label variable m2d      "NA - Prenatal: CS health professional"
label variable m2e      "NA - Prenatal: CS health professional"
label variable m2f      "NA - Prenatal: CS health professional"
label variable m2g      "Prenatal: traditional birth attendant"
label variable m2h      "Prenatal: community/village health worker"
label variable m2i      "Prenatal: traditional health practitioner"
label variable m2j      "NA - Prenatal: CS other person"
label variable m2k      "Prenatal: other"
label variable m2l      "NA - Prenatal: CS other"
label variable m2m      "NA - Prenatal: CS other"
label variable m2n      "Prenatal: no one"
label variable m49a     "During pregnancy took: SP/fansidar for malaria"
label variable m49b     "NA - During pregnancy took: chloroquine for malaria"
label variable m49c     "NA - During pregnancy took: CS drug for malaria"
label variable m49d     "NA - During pregnancy took: CS drug for malaria"
label variable m49e     "NA - During pregnancy took: CS drug for malaria"
label variable m49f     "NA - During pregnancy took: CS drug for malaria"
label variable m49g     "NA - During pregnancy took: CS drug for malaria"
label variable m49x     "NA - During pregnancy took: other drug for malaria"
label variable m49z     "NA - During pregnancy took: don't know"
label variable m49y     "NA - During pregnancy took: no drug for malaria"
label variable h22      "Had fever in last two weeks"
label variable h32a     "Fever/cough: government hospital"
label variable h32b     "Fever/cough: government health center"
label variable h32c     "Fever/cough: government health post/CHPS"
label variable h32d     "Fever/cough: mobile clinic"
label variable h32e     "Fever/cough: fieldworker/community health worker"
label variable h32f     "Fever/cough: other public sector"
label variable h32g     "NA - Fever/cough: CS public sector"
label variable h32h     "NA - Fever/cough: CS public sector"
label variable h32i     "NA - Fever/cough: CS public sector"
label variable h32j     "Fever/cough: private hospital/ clinic"
label variable h32k     "Fever/cough: private pharmacy"
label variable h32l     "Fever/cough: private doctor"
label variable h32m     "Fever/cough: chemist/drug store"
label variable h32n     "Fever/cough: FPG/PPAG clinic"
label variable h32o     "Fever/cough: mobile clinic"
label variable h32p     "Fever/cough: fieldworker/community health worker"
label variable h32q     "Fever/cough: other private medical sector"
label variable h32r     "NA - Fever/cough: CS private medical"
label variable h32s     "Fever/cough: shop"
label variable h32t     "Fever/cough: traditional practitioner"
label variable h32u     "Fever/cough: market"
label variable h32v     "Fever/cough: itinerant drug seller"
label variable h32w     "NA - Fever/cough: CS other sector"
label variable h32x     "Fever/cough: other"
label variable h32y     "Fever/cough: no treatment"
label variable h32z     "Fever/cough: medical treatment"
label variable h46a     "Place first sought treatment for fever"
label variable h46b     "Number of days after fever began sought advice or treatment"
label variable h47      "Blood taken from child's finger/heel for testing"
label variable hwidx    "Index to Birth History"
label variable hw1      "Child's age in months"
label variable hw16     "Day of birth of child"
label variable hw17     "Date measured (day)"
label variable hw18     "Date measured (month)"
label variable hw19     "Date measured (year)"
label variable hw51     "Line number of parent/caretaker"
label variable hw52     "Read consent statement - hemoglobin"
label variable hw53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hw55     "Result of measurement - hemoglobin"
label variable hw56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hw57     "Anemia level"
label variable idxml    "Index to Birth History"
label variable ml0      "Type of mosquito bed net(s) child slept under last night"
label variable ml1      "Number of times took fansidar during pregnancy"
label variable ml2      "Source of antimalarial during pregnancy"
label variable ml11     "NA - Child has fever/cough now"
label variable ml12     "NA - Child has had convulsions in last 2 weeks"
label variable ml13a    "SP/Sulphadoxine-Pyrimethamine taken for fever"
label variable ml13b    "Chloroquine taken for fever"
label variable ml13c    "NA - Amodiaquine taken for fever"
label variable ml13d    "Quinine taken for fever"
label variable ml13da   "Quinine injection/IV taken for fever"
label variable ml13e    "Combination with artemisinin taken for fever"
label variable ml13aa   "NA - Artesunate rectal taken for fever"
label variable ml13ab   "NA - Artesunate injection/IV taken for fever"
label variable ml13f    "DP/Dihydroartemisinin-Piperaquine taken for fever"
label variable ml13g    "AL/Artemether Lumefantrine taken for fever"
label variable ml13h    "Other antimalarial taken for fever"
label variable ml13i    "Antibiotic pill/syrup taken for fever"
label variable ml13j    "Antibiotic injection/IV taken for fever"
label variable ml13k    "Aspirin taken for fever"
label variable ml13l    "Acetaminophen/paracetamol/panadol taken for fever"
label variable ml13m    "Ibuprofen taken for fever"
label variable ml13n    "Herbal medicine taken for fever"
label variable ml13o    "Supplements taken for fever"
label variable ml13p    "NA - CS other taken for fever"
label variable ml13x    "Other taken for fever"
label variable ml13y    "Nothing taken and didn't seek treatment for fever"
label variable ml13z    "Don't know if or what was taken for fever"
label variable ml14a    "NA - Injection given for fever/convulsion***"
label variable ml14b    "NA - Suppository given for fever/convulsion***"
label variable ml14y    "NA - No suppository or injection given for fever/convulsion***"
label variable ml14z    "NA - Don't know if suppository or injection given for fever/convulsion***"
label variable ml15a    "Timing of start of SP/Sulphadoxine-Pyrimethamine"
label variable ml15b    "NA - Number of days child took fansidar"
label variable ml15c    "NA - First source for fansidar"
label variable ml16a    "Timing of start of chloroquine"
label variable ml16b    "NA - Number of days child took chloroquine"
label variable ml16c    "NA - First source for chloroquine"
label variable ml17a    "NA - Timing of start of amodiaquine"
label variable ml17b    "NA - Number of days child took amodiaquine"
label variable ml17c    "NA - First source for amodiaquine"
label variable ml18a    "Timing of start of quinine"
label variable ml18b    "NA - Number of days child took quinine"
label variable ml18c    "NA - First source for quinine"
label variable ml19a    "NA - For fever/convulsion: consulted traditional healer***"
label variable ml19b    "NA - For fever/convulsion: gave tepid sponging***"
label variable ml19c    "NA - For fever/convulsion: gave herbs***"
label variable ml19d    "NA - For fever/convulsion: CS***"
label variable ml19e    "NA - For fever/convulsion: CS***"
label variable ml19f    "NA - For fever/convulsion: CS***"
label variable ml19x    "NA - For fever/convulsion: other***"
label variable ml19y    "NA - For fever/convulsion: gave/did nothing***"
label variable ml19z    "NA - For fever/convulsion: don't know if something else was done***"
label variable ml20a    "Timing of start of combination with artemisinin"
label variable ml20b    "NA - Number of days child took combination with artemisinin"
label variable ml20c    "NA - First source for combination with artemisinin"
label variable ml21a    "Timing of start of DP/Dihydroartemisinin-Piperaquine"
label variable ml21b    "NA - Number of days child took CS antimalarial"
label variable ml21c    "NA - First source for CS antimalarial"
label variable ml22a    "Timing of start of AL/Artemether Lumefantrine"
label variable ml22b    "NA - Number of days child took CS antimalarial"
label variable ml22c    "NA - First source for CS antimalarial"
label variable ml23a    "Timing of start of other anti-malarial use"
label variable ml23b    "NA - Number of days child took other anti-malarial"
label variable ml23c    "NA - First source for other anti-malarial"
label variable ml24c    "NA - First source for antibiotic pill/syrup"
label variable ml25a    "NA - Timing of start of artesunate"
label variable sdistrict "District"
label variable s105     "Highest educational level"
label variable s105a    "Highest educational level final report"
label variable s110aa   "Causes of malaria: eating sweet foods"
label variable s110ab   "Causes of malaria: standing/working in the sun"
label variable s110ac   "Causes of malaria: eating contaminated food"
label variable s110ad   "Causes of malaria: mosquito bites"
label variable s110ae   "Causes of malaria: malaria parasite (P. Falciparum)"
label variable s110af   "Causes of malaria: hereditary"
label variable s110ag   "Causes of malaria: dirty surroundings"
label variable s110ah   "Causes of malaria: weedy surroundings"
label variable s110ai   "Causes of malaria: stagnant water"
label variable s110aj   "Causes of malaria: eating oily food"
label variable s110ak   "Causes of malaria: insects, houseflies"
label variable s110al   "Causes of malaria: personal hygiene"
label variable s110ax   "Causes of malaria: other"
label variable s110az   "Causes of malaria: don't know"
label variable s110ba   "How to know if someone has malaria: hot body fever"
label variable s110bb   "How to know if someone has malaria: vomiting/diarrhea"
label variable s110bc   "How to know if someone has malaria: strong headaches/dizziness"
label variable s110bd   "How to know if someone has malaria: loss of appetite"
label variable s110be   "How to know if someone has malaria: weakness of the body"
label variable s110bf   "How to know if someone has malaria: cough"
label variable s110bg   "How to know if someone has malaria: chills"
label variable s110bh   "How to know if someone has malaria: bitterness in the mouth"
label variable s110bi   "How to know if someone has malaria: urine color"
label variable s110bj   "How to know if someone has malaria: eye color"
label variable s110bx   "How to know if someone has malaria: other"
label variable s110bz   "How to know if someone has malaria: don't know"
label variable s110ca   "How to protect against malaria: sleep under a mosquito net"
label variable s110cb   "How to protect against malaria: sleep under an insecticide-treated mosquito net"
label variable s110cc   "How to protect against malaria: use mosquito repellent"
label variable s110cd   "How to protect against malaria: spray the house/rooms with insecticide"
label variable s110ce   "How to protect against malaria: clear weeds around the house"
label variable s110cf   "How to protect against malaria: fill in stagnant waters (puddles)"
label variable s110cg   "How to protect against malaria: keep surrounding clean"
label variable s110ch   "How to protect against malaria: put mosquito screen on windows"
label variable s110ci   "How to protect against malaria: avoid sitting/staying outside for long/staying i"
label variable s110cj   "How to protect against malaria: avoid eating oily/cold food"
label variable s110ck   "How to protect against malaria: avoid contaminated food"
label variable s110cl   "How to protect against malaria: personal hygiene"
label variable s110cm   "How to protect against malaria: wearing protective clothes"
label variable s110cx   "How to protect against malaria: other"
label variable s110cz   "How to protect against malaria: don't know"
label variable s110d    "Malaria can be treated"
label variable s111     "Seen or heard any messages about malaria in the past 6 months"
label variable s112aa   "Where saw or heard malaria messages: radio"
label variable s112ab   "Where saw or heard malaria messages: television"
label variable s112ac   "Where saw or heard malaria messages: poster/billboard"
label variable s112ad   "Where saw or heard malaria messages: newspaper/magazine"
label variable s112ae   "Where saw or heard malaria messages: leaflet/brochure"
label variable s112af   "Where saw or heard malaria messages: health worker"
label variable s112ag   "Where saw or heard malaria messages: community health worker"
label variable s112ah   "Where saw or heard malaria messages: community volunteer/CBA"
label variable s112ai   "Where saw or heard malaria messages: word of mouth/Viva Voce"
label variable s112aj   "Where saw or heard malaria messages: community event"
label variable s112ak   "Where saw or heard malaria messages: school"
label variable s112ax   "Where saw or heard malaria messages: anywhere else"
label variable s112az   "Where saw or heard malaria messages: don't remember"
label variable s112a    "Heard malaria message on the radio in the past 6 months"
label variable s112b    "Seen malaria message on the television in the past 6 months"
label variable s112c    "Seen malaria message on a poster or billboard in the past 6 months"
label variable s112d    "Seen malaria message on a newspaper or magazine in the past 6 months"
label variable s112e    "Seen malaria message on a leaflet or brochure in the past 6 months"
label variable s112f    "Heard malaria message from a health worker in the past 6 months"
label variable s112g    "Heard malaria message from a Community Health Worker in the past 6 months"
label variable s112h    "Heard malaria message from a community volunteer or a CBA the past 6 months"
label variable s112i    "Heard malaria message from a word of moth in the past 6 months"
label variable s112j    "Heard malaria message at a community event in the past 6 months"
label variable s113a    "Messages seen/heard in the past 6 months: if have fever go to health facility"
label variable s113b    "Messages seen/heard in the past 6 months: sleep under an insecticide-treated mos"
label variable s113c    "Messages seen/heard in the past 6 months: pregnant women should take drugs to pr"
label variable s113d    "Messages seen/heard in the past 6 months: SP protects pregnant women and unborn "
label variable s113e    "Messages seen/heard in the past 6 months: always test before treating malaria"
label variable s113f    "Messages seen/heard in the past 6 months: treat malaria with ACTs"
label variable s113g    "Messages seen/heard in the past 6 months: malaria kills"
label variable s113h    "Messages seen/heard in the past 6 months: clean environment/spray rooms with ins"
label variable s113i    "Messages seen/heard in the past 6 months: avoid eating cold/ oily/ contaminated/"
label variable s113j    "Messages seen/heard in the past 6 months: personal hygiene"
label variable s113x    "Messages seen/heard in the past 6 months: other"
label variable s113z    "Messages seen/heard in the past 6 months: don't know/ don't remember"
label variable s114a    "Seen/heard message 'Mea menya me net, Ntontom mpo suro' music video/song in the "
label variable s114b    "Seen/heard advert recommending everyone to sleep under treated net by musician K"
label variable s114c    "Seen/heard advert where people were asked to test first before taking malaria me"
label variable s115     "Seen/heard any advert on the use of ACTs/malaria medicines in the past 6 months"
label variable s116a    "Where saw/heard the advert on the use of ACTs/malaria medicines: television"
label variable s116b    "Where saw/heard the advert on the use of ACTs/malaria medicines: radio"
label variable s116c    "Where saw/heard the advert on the use of ACTs/malaria medicines: newspaper/magaz"
label variable s116d    "Where saw/heard the advert on the use of ACTs/malaria medicines: poster/leaflets"
label variable s116e    "Where saw/heard the advert on the use of ACTs/malaria medicines: billboard"
label variable s116f    "Where saw/heard the advert on the use of ACTs/malaria medicines: health worker"
label variable s116x    "Where saw/heard the advert on the use of ACTs/malaria medicines: other"
label variable s116z    "Where saw/heard the advert on the use of ACTs/malaria medicines: don't know/ don"
label variable s117     "Participated in any community event educating members on prevention/control of m"
label variable s120     "Experienced an episode of malaria in the past the 12 months"
label variable s121     "Sought advice/treatment the last time had malaria"
label variable s122a    "Place sought advice/treatment: government hospital"
label variable s122b    "Place sought advice/treatment: government health center/clinic"
label variable s122c    "Place sought advice/treatment: Government health post/CHPS"
label variable s122d    "Place sought advice/treatment: mobile clinic"
label variable s122e    "Place sought advice/treatment: fieldworker/community health worker"
label variable s122f    "Place sought advice/treatment: other public sector"
label variable s122g    "Place sought advice/treatment: private hospital/clinic"
label variable s122h    "Place sought advice/treatment: pharmacy"
label variable s122i    "Place sought advice/treatment: chemist/drug store"
label variable s122j    "Place sought advice/treatment: FPG/PPAG clinic"
label variable s122k    "Place sought advice/treatment: private doctor"
label variable s122l    "Place sought advice/treatment: mobile clinic"
label variable s122m    "Place sought advice/treatment: fieldworker/community health worker"
label variable s122n    "Place sought advice/treatment: other private medical sector"
label variable s122x    "Place sought advice/treatment: other"
label variable s123     "Laboratory test conducted to confirm the malaria diagnosis"
label variable s124     "Any antimalaria medicine prescribed to treat the malaria or took medicines witho"
label variable s125a    "Antimalaria medicines prescribed or taken: SP/Sulphadoxine Pyrimethamine"
label variable s125b    "Antimalaria medicines prescribed or taken: chloroquine"
label variable s125c    "Antimalaria medicines prescribed or taken: DP/Dihydroartemisinin-Piperaquine"
label variable s125d    "Antimalaria medicines prescribed or taken: quinine"
label variable s125e    "Antimalaria medicines prescribed or taken: AA/Artesunate Amodiaquine"
label variable s125f    "Antimalaria medicines prescribed or taken: artemisinin"
label variable s125g    "Antimalaria medicines prescribed or taken: AL/Artemether-Lumefantrine"
label variable s125h    "Antimalaria medicines prescribed or taken: herbal medicine"
label variable s125i    "Antimalaria medicines prescribed or taken: non-antimalarial (paracetamol, antibi"
label variable s125x    "Antimalaria medicines prescribed or taken: other"
label variable s125z    "Antimalaria medicines prescribed or taken: don't know"
label variable s126     "Antimalaria medicine purchased"
label variable s127     "Paid out of pocket for the antimalaria medicines"
label variable s129     "Antimalaria medicine purchased at the same place sought care"
label variable s130a    "Place purchased antimalaria medicine: government hospital"
label variable s130b    "Place purchased antimalaria medicine: government health center"
label variable s130c    "Place purchased antimalaria medicine: government health post/chips"
label variable s130d    "Place purchased antimalaria medicine: mobile clinic"
label variable s130e    "Place purchased antimalaria medicine: fieldworker/community health worker"
label variable s130f    "Place purchased antimalaria medicine: other public sector"
label variable s130g    "Place purchased antimalaria medicine: private hospital/clinic"
label variable s130h    "Place purchased antimalaria medicine: pharmacy"
label variable s130i    "Place purchased antimalaria medicine: chemist/drug store"
label variable s130j    "Place purchased antimalaria medicine: FPG/PPAG clinic"
label variable s130k    "Place purchased antimalaria medicine: private doctor"
label variable s130l    "Place purchased antimalaria medicine: mobile clinic"
label variable s130m    "Place purchased antimalaria medicine: Fieldworker/CHW"
label variable s130n    "Place purchased antimalaria medicine: other private medical sector"
label variable s130o    "Place purchased antimalaria medicine: shop"
label variable s130p    "Place purchased antimalaria medicine: traditional practitioner"
label variable s130q    "Place purchased antimalaria medicine: market"
label variable s130r    "Place purchased antimalaria medicine: itinerant drug seller"
label variable s130x    "Place purchased antimalaria medicine: other"
label variable s131     "Paid out of pocket for other services received related to the malaria infection"
label variable s132     "Aware that malaria is covered under the NHIS"
label variable s211     "Number of births in 2011-2016"
label variable idx95    "Index to Birth History"
label variable s403a    "In 2015, enrolled in program to receive medicine monthly for 4 months to prevent"
label variable s403b1   "Number of doses taken in 2015"
label variable s403b2   "Number of doses taken in 2016"
label variable s405a    "Result of malaria blood test"
label variable s412f    "Drugs for fever: Artesunate amodiaquine rectal"
label variable s412g    "Drugs for fever: Artesunate amodiaquine injection/IV"
label variable s412h    "Drugs for fever: Artemisinin"
label variable s412n    "Drugs for fever: Paracetamol/Panadol"
label variable s412o    "Drugs for fever: Acetaminophen"
label variable s423     "How long after fever started did first take Artesunate with amodiaquine"
label variable s425     "How long after fever started did first take Artemisinin"

#delimit ;
label define V006    
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
;
label define V013    
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define V014    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define V015    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partially completed"
     6 "Respondent incapacitated"
     7 "Other"
;
label define V020    
     0 "All woman sample"
     1 "Ever married sample"
;
label define V024    
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Brong Ahafo"
     8 "Northern"
     9 "Upper East"
    10 "Upper West"
;
label define V025    
     1 "Urban"
     2 "Rural"
;
label define V027    
     9 "Missing"
;
label define V028    
 99999 "Missing"
;
label define V030    
 99999 "Missing"
;
label define V040    
  9999 "Missing"
;
label define V042    
     0 "Not selected"
     1 "Selected"
;
label define V045A   
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
;
label define V045B   
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     6 "Other"
;
label define V045C   
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     6 "Other"
;
label define V046    
     0 "No"
     1 "Yes"
;
label define V101    
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Brong Ahafo"
     8 "Northern"
     9 "Upper East"
    10 "Upper West"
;
label define V102    
     1 "Urban"
     2 "Rural"
;
label define V106    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define V107    
     0 "No years completed at level V106"
;
label define V113    
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    72 "Sachet water"
    96 "Other"
    97 "Not a dejure resident"
;
label define V115    
   996 "On premises"
   997 "Not a dejure resident"
   998 "Don't know"
;
label define V116    
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
    97 "Not a dejure resident"
;
label define V119    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V120    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V121    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V122    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V123    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V124    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V125    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V127    
    10 "NATURAL"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic/marble/porcelain tiles/terrazo"
    34 "Cement"
    35 "Woolen carpet/synthetic carpet"
    36 "Linoleum/rubber carpet"
    96 "Other"
    97 "Not a dejure resident"
;
label define V128    
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Mud/landcrete"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
    97 "Not a dejure resident"
;
label define V129    
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Zinc/aluminum"
    32 "Wood"
    33 "Calamine/cement fiber"
    34 "Ceramic/brick tiles"
    35 "Cement"
    36 "Roofing shingles"
    37 "Asbestos/slate roofing sheets"
    96 "Other"
    97 "Not a dejure resident"
;
label define V130    
     1 "Catholic"
     2 "Anglican"
     3 "Methodist"
     4 "Presbyterian"
     5 "Pentecostal/Charismatic"
     6 "Other Christian"
     7 "Islam"
     8 "Traditional/spiritualist"
    95 "No religion"
    96 "Other"
;
label define V131    
     1 "Akan"
     2 "Ga/Dangme"
     3 "Ewe"
     4 "Guan"
     5 "Mole-Dagbani"
     6 "Grusi"
     7 "Gurma"
     8 "Mande"
    96 "Other"
;
label define V133    
    97 "Inconsistent"
;
label define V135    
     1 "Usual resident"
     2 "Visitor"
;
label define V139    
     0 "Abroad"
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Brong Ahafo"
     8 "Northern"
     9 "Upper East"
    10 "Upper West"
    97 "Not dejure resident"
;
label define V140    
     0 "Abroad"
     1 "Urban"
     2 "Rural"
     7 "Not a dejure resident"
;
label define V149    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define V150    
     1 "Head"
     2 "Wife"
     3 "Daughter"
     4 "Daughter-in-law"
     5 "Granddaughter"
     6 "Mother"
     7 "Mother-in-law"
     8 "Sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "Don't know"
;
label define V151    
     1 "Male"
     2 "Female"
;
label define V152    
    95 "95+"
    98 "Don't know"
;
label define V153    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V155    
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define V160    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V161    
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop residue"
    11 "Animal dung"
    95 "No food cooked in household"
    96 "Other"
    97 "Not a dejure resident"
;
label define V190    
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define V190A   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define ML101   
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define V208    
     0 "No births"
;
label define V209    
     0 "No births"
;
label define V213    
     0 "No or unsure"
     1 "Yes"
;
label define V220    
     6 "6+"
;
label define V223    
     7 "Month - exact date"
     8 "None - date placed"
;
label define V237    
     0 "No"
     1 "Yes"
;
label define V459    
     0 "No"
     1 "Yes"
;
label define V460    
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define V461    
     0 "No"
     1 "Yes"
;
label define V468    
     0 "See specific questions"
     1 "Last birth only"
     2 "All births in last 5 years"
;
label define V481    
     0 "No"
     1 "Yes"
;
label define V481A   
     0 "No"
     1 "Yes"
;
label define V481B   
     0 "No"
     1 "Yes"
;
label define V481C   
     0 "No"
     1 "Yes"
;
label define V481D   
     0 "No"
     1 "Yes"
;
label define V481E   
     0 "No"
     1 "Yes"
;
label define V481F   
     0 "No"
     1 "Yes"
;
label define V481G   
     0 "No"
     1 "Yes"
;
label define V481H   
     0 "No"
     1 "Yes"
;
label define V481X   
     0 "No"
     1 "Yes"
;
label define B0      
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
;
label define B1      
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
;
label define B4      
     1 "Male"
     2 "Female"
;
label define B5      
     0 "No"
     1 "Yes"
;
label define B9      
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
;
label define B10     
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define B15     
     0 "No"
     1 "Yes"
;
label define B16     
     0 "Not listed in household"
;
label define M2A     
     0 "No"
     1 "Yes"
;
label define M2B     
     0 "No"
     1 "Yes"
;
label define M2C     
     0 "No"
     1 "Yes"
;
label define M2D     
     0 "No"
     1 "Yes"
;
label define M2E     
     0 "No"
     1 "Yes"
;
label define M2F     
     0 "No"
     1 "Yes"
;
label define M2G     
     0 "No"
     1 "Yes"
;
label define M2H     
     0 "No"
     1 "Yes"
;
label define M2I     
     0 "No"
     1 "Yes"
;
label define M2J     
     0 "No"
     1 "Yes"
;
label define M2K     
     0 "No"
     1 "Yes"
;
label define M2L     
     0 "No"
     1 "Yes"
;
label define M2M     
     0 "No"
     1 "Yes"
;
label define M2N     
     0 "No: some care"
     1 "Yes: no care"
;
label define M49A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49C    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49D    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49E    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49F    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49G    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49X    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49Z    
     0 "No"
     1 "Yes: don't know which drug taken"
     8 "Don't know"
;
label define M49Y    
     0 "No"
     1 "Yes, took no drug"
     8 "Don't know"
;
label define H22     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H32A    
     0 "No"
     1 "Yes"
;
label define H32B    
     0 "No"
     1 "Yes"
;
label define H32C    
     0 "No"
     1 "Yes"
;
label define H32D    
     0 "No"
     1 "Yes"
;
label define H32E    
     0 "No"
     1 "Yes"
;
label define H32F    
     0 "No"
     1 "Yes"
;
label define H32G    
     0 "No"
     1 "Yes"
;
label define H32H    
     0 "No"
     1 "Yes"
;
label define H32I    
     0 "No"
     1 "Yes"
;
label define H32J    
     0 "No"
     1 "Yes"
;
label define H32K    
     0 "No"
     1 "Yes"
;
label define H32L    
     0 "No"
     1 "Yes"
;
label define H32M    
     0 "No"
     1 "Yes"
;
label define H32N    
     0 "No"
     1 "Yes"
;
label define H32O    
     0 "No"
     1 "Yes"
;
label define H32P    
     0 "No"
     1 "Yes"
;
label define H32Q    
     0 "No"
     1 "Yes"
;
label define H32R    
     0 "No"
     1 "Yes"
;
label define H32S    
     0 "No"
     1 "Yes"
;
label define H32T    
     0 "No"
     1 "Yes"
;
label define H32U    
     0 "No"
     1 "Yes"
;
label define H32V    
     0 "No"
     1 "Yes"
;
label define H32W    
     0 "No"
     1 "Yes"
;
label define H32X    
     0 "No"
     1 "Yes"
;
label define H32Y    
     0 "No: received treatment"
     1 "Yes: no treatment"
;
label define H32Z    
     0 "No"
     1 "Yes"
;
label define H46A    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Government health post/CHPS"
    14 "Mobile clinic"
    15 "Fieldworker/Community health worker"
    16 "Other public sector"
    20 "PRIVATE SECTOR"
    21 "Private hospital, clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "Chemist/drug store"
    25 "FPG/PPAG clinic"
    26 "Mobile clinic"
    27 "Fieldworker/Community health worker"
    28 "Other private medical sector"
    30 "OTHER"
    31 "Shop"
    32 "Traditional practitioner"
    33 "Market"
    34 "Itinerant drug seller"
    96 "Other"
;
label define H46B    
     0 "Same day"
    98 "Don't know"
;
label define H47     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HW16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HW18    
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
;
label define HW51    
     0 "Not in household"
;
label define HW52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HW53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HW55    
     0 "Measured"
     1 "Dead"
     3 "Not present/other"
     4 "Refused"
     6 "Other"
     7 "No measurement found in household"
;
label define HW56    
   997 "Inconsistent"
;
label define HW57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define ML0     
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define ML1     
    98 "Don't know"
;
label define ML2     
     1 "Antenatal visit"
     2 "Another facility visit"
     6 "Other source"
;
label define ML11    
     0 "No"
     1 "Yes, fever only"
     2 "Yes, cough only"
     3 "Both fever and cough"
     8 "Don't know"
;
label define ML12    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define ML13A   
     0 "No"
     1 "Yes"
;
label define ML13B   
     0 "No"
     1 "Yes"
;
label define ML13C   
     0 "No"
     1 "Yes"
;
label define ML13D   
     0 "No"
     1 "Yes"
;
label define ML13DA  
     0 "No"
     1 "Yes"
;
label define ML13E   
     0 "No"
     1 "Yes"
;
label define ML13AA  
     0 "No"
     1 "Yes"
;
label define ML13AB  
     0 "No"
     1 "Yes"
;
label define ML13F   
     0 "No"
     1 "Yes"
;
label define ML13G   
     0 "No"
     1 "Yes"
;
label define ML13H   
     0 "No"
     1 "Yes"
;
label define ML13I   
     0 "No"
     1 "Yes"
;
label define ML13J   
     0 "No"
     1 "Yes"
;
label define ML13K   
     0 "No"
     1 "Yes"
;
label define ML13L   
     0 "No"
     1 "Yes"
;
label define ML13M   
     0 "No"
     1 "Yes"
;
label define ML13N   
     0 "No"
     1 "Yes"
;
label define ML13O   
     0 "No"
     1 "Yes"
;
label define ML13P   
     0 "No"
     1 "Yes"
;
label define ML13X   
     0 "No"
     1 "Yes"
;
label define ML13Y   
     0 "No"
     1 "Yes, nothing taken"
;
label define ML13Z   
     0 "No"
     1 "Yes, don't know"
;
label define ML14A   
     0 "No"
     1 "Yes"
;
label define ML14B   
     0 "No"
     1 "Yes"
;
label define ML14Y   
     0 "No"
     1 "Yes"
;
label define ML14Z   
     0 "No"
     1 "Yes"
;
label define ML15A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3+ days after"
     8 "Don't know"
;
label define ML15B   
     7 "7+ days"
     8 "Don't know"
;
label define ML15C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML16A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3+ days after"
     8 "Don't know"
;
label define ML16B   
     7 "7+ days"
     8 "Don't know"
;
label define ML16C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML17A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML17B   
     7 "7+ days"
     8 "Don't know"
;
label define ML17C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML18A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3+ days after"
     8 "Don't know"
;
label define ML18B   
     7 "7+ days"
     8 "Don't know"
;
label define ML18C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML19A   
     0 "No"
     1 "Yes"
;
label define ML19B   
     0 "No"
     1 "Yes"
;
label define ML19C   
     0 "No"
     1 "Yes"
;
label define ML19D   
     0 "No"
     1 "Yes"
;
label define ML19E   
     0 "No"
     1 "Yes"
;
label define ML19F   
     0 "No"
     1 "Yes"
;
label define ML19X   
     0 "No"
     1 "Yes"
;
label define ML19Y   
     0 "No"
     1 "Yes"
;
label define ML19Z   
     0 "No"
     1 "Yes"
;
label define ML20A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3+ days after"
     8 "Don't know"
;
label define ML20B   
     7 "7+ days"
     8 "Don't know"
;
label define ML20C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML21A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3+ days after"
     8 "Don't know"
;
label define ML21B   
     7 "7+ days"
     8 "Don't know"
;
label define ML21C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML22A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3+ days after"
     8 "Don't know"
;
label define ML22B   
     7 "7+ days"
     8 "Don't know"
;
label define ML22C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML23A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3+ days after"
     8 "Don't know"
;
label define ML23B   
     7 "7+ days"
     8 "Don't know"
;
label define ML23C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML24C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML25A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define S105    
     0 "No education"
     1 "Primary"
     2 "Middle"
     3 "JSS/JHS"
     4 "Secondary"
     5 "SSS/SHS"
     6 "Higher"
;
label define S105A   
     0 "No education"
     1 "Primary"
     2 "Middle/JSS/JHS"
     3 "Secondary/SSS/SHS or Higher"
;
label define S110AA  
     0 "No"
     1 "Yes"
;
label define S110AB  
     0 "No"
     1 "Yes"
;
label define S110AC  
     0 "No"
     1 "Yes"
;
label define S110AD  
     0 "No"
     1 "Yes"
;
label define S110AE  
     0 "No"
     1 "Yes"
;
label define S110AF  
     0 "No"
     1 "Yes"
;
label define S110AG  
     0 "No"
     1 "Yes"
;
label define S110AH  
     0 "No"
     1 "Yes"
;
label define S110AI  
     0 "No"
     1 "Yes"
;
label define S110AJ  
     0 "No"
     1 "Yes"
;
label define S110AK  
     0 "No"
     1 "Yes"
;
label define S110AL  
     0 "No"
     1 "Yes"
;
label define S110AX  
     0 "No"
     1 "Yes"
;
label define S110AZ  
     0 "No"
     1 "Yes, don't know"
;
label define S110BA  
     0 "No"
     1 "Yes"
;
label define S110BB  
     0 "No"
     1 "Yes"
;
label define S110BC  
     0 "No"
     1 "Yes"
;
label define S110BD  
     0 "No"
     1 "Yes"
;
label define S110BE  
     0 "No"
     1 "Yes"
;
label define S110BF  
     0 "No"
     1 "Yes"
;
label define S110BG  
     0 "No"
     1 "Yes"
;
label define S110BH  
     0 "No"
     1 "Yes"
;
label define S110BI  
     0 "No"
     1 "Yes"
;
label define S110BJ  
     0 "No"
     1 "Yes"
;
label define S110BX  
     0 "No"
     1 "Yes"
;
label define S110BZ  
     0 "No"
     1 "Yes, don't know"
;
label define S110CA  
     0 "No"
     1 "Yes"
;
label define S110CB  
     0 "No"
     1 "Yes"
;
label define S110CC  
     0 "No"
     1 "Yes"
;
label define S110CD  
     0 "No"
     1 "Yes"
;
label define S110CE  
     0 "No"
     1 "Yes"
;
label define S110CF  
     0 "No"
     1 "Yes"
;
label define S110CG  
     0 "No"
     1 "Yes"
;
label define S110CH  
     0 "No"
     1 "Yes"
;
label define S110CI  
     0 "No"
     1 "Yes"
;
label define S110CJ  
     0 "No"
     1 "Yes"
;
label define S110CK  
     0 "No"
     1 "Yes"
;
label define S110CL  
     0 "No"
     1 "Yes"
;
label define S110CM  
     0 "No"
     1 "Yes"
;
label define S110CX  
     0 "No"
     1 "Yes"
;
label define S110CZ  
     0 "No"
     1 "Yes, don't know"
;
label define S110D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define S111    
     0 "No"
     1 "Yes"
;
label define S112AA  
     0 "No"
     1 "Yes"
;
label define S112AB  
     0 "No"
     1 "Yes"
;
label define S112AC  
     0 "No"
     1 "Yes"
;
label define S112AD  
     0 "No"
     1 "Yes"
;
label define S112AE  
     0 "No"
     1 "Yes"
;
label define S112AF  
     0 "No"
     1 "Yes"
;
label define S112AG  
     0 "No"
     1 "Yes"
;
label define S112AH  
     0 "No"
     1 "Yes"
;
label define S112AI  
     0 "No"
     1 "Yes"
;
label define S112AJ  
     0 "No"
     1 "Yes"
;
label define S112AK  
     0 "No"
     1 "Yes"
;
label define S112AX  
     0 "No"
     1 "Yes"
;
label define S112AZ  
     0 "No"
     1 "Yes, don't remember"
;
label define S112A   
     0 "No"
     1 "Yes"
     2 "Mentioned in S112AA"
;
label define S112B   
     0 "No"
     1 "Yes"
     2 "Mentioned in Q112AB"
;
label define S112C   
     0 "No"
     1 "Yes"
     2 "Mentioned in Q112AC"
;
label define S112D   
     0 "No"
     1 "Yes"
     2 "Mentioned in Q112AD"
;
label define S112E   
     0 "No"
     1 "Yes"
     2 "Mentioned in Q112AE"
;
label define S112F   
     0 "No"
     1 "Yes"
     2 "Mentioned in Q112AF"
;
label define S112G   
     0 "No"
     1 "Yes"
     2 "Mentioned in Q112AG"
;
label define S112H   
     0 "No"
     1 "Yes"
     2 "Mentioned in Q112AH"
;
label define S112I   
     0 "No"
     1 "Yes"
     2 "Mentioned in Q112AI"
;
label define S112J   
     0 "No"
     1 "Yes"
     2 "Mentioned in Q112AJ"
;
label define S113A   
     0 "No"
     1 "Yes"
;
label define S113B   
     0 "No"
     1 "Yes"
;
label define S113C   
     0 "No"
     1 "Yes"
;
label define S113D   
     0 "No"
     1 "Yes"
;
label define S113E   
     0 "No"
     1 "Yes"
;
label define S113F   
     0 "No"
     1 "Yes"
;
label define S113G   
     0 "No"
     1 "Yes"
;
label define S113H   
     0 "No"
     1 "Yes"
;
label define S113I   
     0 "No"
     1 "Yes"
;
label define S113J   
     0 "No"
     1 "Yes"
;
label define S113X   
     0 "No"
     1 "Yes"
;
label define S113Z   
     0 "No"
     1 "Yes, don't know or don't remember"
;
label define S114A   
     0 "No"
     1 "Yes, on TV"
     2 "Yes, on radio"
     3 "Yes, on both"
;
label define S114B   
     0 "No"
     1 "Yes, on TV"
     2 "Yes, on radio"
     3 "Yes, on both"
;
label define S114C   
     0 "No"
     1 "Yes, on TV"
     2 "Yes, on radio"
     3 "Yes, on both"
;
label define S115    
     0 "No"
     1 "Yes"
;
label define S116A   
     0 "No"
     1 "Yes"
;
label define S116B   
     0 "No"
     1 "Yes"
;
label define S116C   
     0 "No"
     1 "Yes"
;
label define S116D   
     0 "No"
     1 "Yes"
;
label define S116E   
     0 "No"
     1 "Yes"
;
label define S116F   
     0 "No"
     1 "Yes"
;
label define S116X   
     0 "No"
     1 "Yes"
;
label define S116Z   
     0 "No"
     1 "Yes, don't know or don't remember"
;
label define S117    
     0 "No"
     1 "Yes"
;
label define S120    
     0 "No"
     1 "Yes"
;
label define S121    
     0 "No"
     1 "Yes"
;
label define S122A   
     0 "No"
     1 "Yes"
;
label define S122B   
     0 "No"
     1 "Yes"
;
label define S122C   
     0 "No"
     1 "Yes"
;
label define S122D   
     0 "No"
     1 "Yes"
;
label define S122E   
     0 "No"
     1 "Yes"
;
label define S122F   
     0 "No"
     1 "Yes"
;
label define S122G   
     0 "No"
     1 "Yes"
;
label define S122H   
     0 "No"
     1 "Yes"
;
label define S122I   
     0 "No"
     1 "Yes"
;
label define S122J   
     0 "No"
     1 "Yes"
;
label define S122K   
     0 "No"
     1 "Yes"
;
label define S122L   
     0 "No"
     1 "Yes"
;
label define S122M   
     0 "No"
     1 "Yes"
;
label define S122N   
     0 "No"
     1 "Yes"
;
label define S122X   
     0 "No"
     1 "Yes"
;
label define S123    
     0 "No"
     1 "Yes"
;
label define S124    
     0 "Neither prescribed nor taken"
     1 "Yes, prescribed"
     2 "Yes, took without prescription"
;
label define S125A   
     0 "No"
     1 "Yes"
;
label define S125B   
     0 "No"
     1 "Yes"
;
label define S125C   
     0 "No"
     1 "Yes"
;
label define S125D   
     0 "No"
     1 "Yes"
;
label define S125E   
     0 "No"
     1 "Yes"
;
label define S125F   
     0 "No"
     1 "Yes"
;
label define S125G   
     0 "No"
     1 "Yes"
;
label define S125H   
     0 "No"
     1 "Yes"
;
label define S125I   
     0 "No"
     1 "Yes"
;
label define S125X   
     0 "No"
     1 "Yes"
;
label define S125Z   
     0 "No"
     1 "Yes, don't know"
;
label define S126    
     0 "No"
     1 "Yes"
;
label define S127    
     0 "No"
     1 "Yes"
;
label define S129    
     0 "No"
     1 "Yes"
;
label define S130A   
     0 "No"
     1 "Yes"
;
label define S130B   
     0 "No"
     1 "Yes"
;
label define S130C   
     0 "No"
     1 "Yes"
;
label define S130D   
     0 "No"
     1 "Yes"
;
label define S130E   
     0 "No"
     1 "Yes"
;
label define S130F   
     0 "No"
     1 "Yes"
;
label define S130G   
     0 "No"
     1 "Yes"
;
label define S130H   
     0 "No"
     1 "Yes"
;
label define S130I   
     0 "No"
     1 "Yes"
;
label define S130J   
     0 "No"
     1 "Yes"
;
label define S130K   
     0 "No"
     1 "Yes"
;
label define S130L   
     0 "No"
     1 "Yes"
;
label define S130M   
     0 "No"
     1 "Yes"
;
label define S130N   
     0 "No"
     1 "Yes"
;
label define S130O   
     0 "No"
     1 "Yes"
;
label define S130P   
     0 "No"
     1 "Yes"
;
label define S130Q   
     0 "No"
     1 "Yes"
;
label define S130R   
     0 "No"
     1 "Yes"
;
label define S130X   
     0 "No"
     1 "Yes"
;
label define S131    
     0 "No"
     1 "Yes"
;
label define S132    
     0 "No"
     1 "Yes"
;
label define S211    
     0 "None"
;
label define S403A   
     0 "No, never enrolled"
     1 "Yes, in 2015"
     2 "Yes, in 2016"
     3 "Yes, in 2015 and 2016"
;
label define S405A   
     0 "Negative"
     1 "Positive malaria"
     2 "Positive other illness"
     8 "Don't know/don't remember"
;
label define S412F   
     0 "No"
     1 "Yes"
;
label define S412G   
     0 "No"
     1 "Yes"
;
label define S412H   
     0 "No"
     1 "Yes"
;
label define S412N   
     0 "No"
     1 "Yes"
;
label define S412O   
     0 "No"
     1 "Yes"
;
label define S423    
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3+ days after"
     8 "Don't know"
;
label define S425    
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3+ days after"
     8 "Don't know"
;

#delimit cr
label values v006     V006    
label values v013     V013    
label values v014     V014    
label values v015     V015    
label values v020     V020    
label values v024     V024    
label values v025     V025    
label values v042     V042    
label values v045a    V045A   
label values v045b    V045B   
label values v045c    V045C   
label values v046     V046    
label values v101     V101    
label values v102     V102    
label values v106     V106    
label values v107     V107    
label values v113     V113    
label values v115     V115    
label values v116     V116    
label values v119     V119    
label values v120     V120    
label values v121     V121    
label values v122     V122    
label values v123     V123    
label values v124     V124    
label values v125     V125    
label values v127     V127    
label values v128     V128    
label values v129     V129    
label values v130     V130    
label values v131     V131    
label values v133     V133    
label values v135     V135    
label values v139     V139    
label values v140     V140    
label values v149     V149    
label values v150     V150    
label values v151     V151    
label values v152     V152    
label values v153     V153    
label values v155     V155    
label values v160     V160    
label values v161     V161    
label values v190     V190    
label values v190a    V190A   
label values ml101    ML101   
label values v208     V208    
label values v209     V209    
label values v213     V213    
label values v220     V220    
label values v223     V223    
label values v237     V237    
label values v459     V459    
label values v460     V460    
label values v461     V461    
label values v468     V468    
label values v481     V481    
label values v481a    V481A   
label values v481b    V481B   
label values v481c    V481C   
label values v481d    V481D   
label values v481e    V481E   
label values v481f    V481F   
label values v481g    V481G   
label values v481h    V481H   
label values v481x    V481X   
label values b0       B0      
label values b1       B1      
label values b4       B4      
label values b5       B5      
label values b9       B9      
label values b10      B10     
label values b15      B15     
label values b16      B16     
label values m2a      M2A     
label values m2b      M2B     
label values m2c      M2C     
label values m2d      M2D     
label values m2e      M2E     
label values m2f      M2F     
label values m2g      M2G     
label values m2h      M2H     
label values m2i      M2I     
label values m2j      M2J     
label values m2k      M2K     
label values m2l      M2L     
label values m2m      M2M     
label values m2n      M2N     
label values m49a     M49A    
label values m49b     M49B    
label values m49c     M49C    
label values m49d     M49D    
label values m49e     M49E    
label values m49f     M49F    
label values m49g     M49G    
label values m49x     M49X    
label values m49z     M49Z    
label values m49y     M49Y    
label values h22      H22     
label values h32a     H32A    
label values h32b     H32B    
label values h32c     H32C    
label values h32d     H32D    
label values h32e     H32E    
label values h32f     H32F    
label values h32g     H32G    
label values h32h     H32H    
label values h32i     H32I    
label values h32j     H32J    
label values h32k     H32K    
label values h32l     H32L    
label values h32m     H32M    
label values h32n     H32N    
label values h32o     H32O    
label values h32p     H32P    
label values h32q     H32Q    
label values h32r     H32R    
label values h32s     H32S    
label values h32t     H32T    
label values h32u     H32U    
label values h32v     H32V    
label values h32w     H32W    
label values h32x     H32X    
label values h32y     H32Y    
label values h32z     H32Z    
label values h46a     H46A    
label values h46b     H46B    
label values h47      H47     
label values hw16     HW16    
label values hw18     HW18    
label values hw51     HW51    
label values hw52     HW52    
label values hw53     HW53    
label values hw55     HW55    
label values hw56     HW56    
label values hw57     HW57    
label values ml0      ML0     
label values ml1      ML1     
label values ml2      ML2     
label values ml11     ML11    
label values ml12     ML12    
label values ml13a    ML13A   
label values ml13b    ML13B   
label values ml13c    ML13C   
label values ml13d    ML13D   
label values ml13da   ML13DA  
label values ml13e    ML13E   
label values ml13aa   ML13AA  
label values ml13ab   ML13AB  
label values ml13f    ML13F   
label values ml13g    ML13G   
label values ml13h    ML13H   
label values ml13i    ML13I   
label values ml13j    ML13J   
label values ml13k    ML13K   
label values ml13l    ML13L   
label values ml13m    ML13M   
label values ml13n    ML13N   
label values ml13o    ML13O   
label values ml13p    ML13P   
label values ml13x    ML13X   
label values ml13y    ML13Y   
label values ml13z    ML13Z   
label values ml14a    ML14A   
label values ml14b    ML14B   
label values ml14y    ML14Y   
label values ml14z    ML14Z   
label values ml15a    ML15A   
label values ml15b    ML15B   
label values ml15c    ML15C   
label values ml16a    ML16A   
label values ml16b    ML16B   
label values ml16c    ML16C   
label values ml17a    ML17A   
label values ml17b    ML17B   
label values ml17c    ML17C   
label values ml18a    ML18A   
label values ml18b    ML18B   
label values ml18c    ML18C   
label values ml19a    ML19A   
label values ml19b    ML19B   
label values ml19c    ML19C   
label values ml19d    ML19D   
label values ml19e    ML19E   
label values ml19f    ML19F   
label values ml19x    ML19X   
label values ml19y    ML19Y   
label values ml19z    ML19Z   
label values ml20a    ML20A   
label values ml20b    ML20B   
label values ml20c    ML20C   
label values ml21a    ML21A   
label values ml21b    ML21B   
label values ml21c    ML21C   
label values ml22a    ML22A   
label values ml22b    ML22B   
label values ml22c    ML22C   
label values ml23a    ML23A   
label values ml23b    ML23B   
label values ml23c    ML23C   
label values ml24c    ML24C   
label values ml25a    ML25A   
label values s105     S105    
label values s105a    S105A   
label values s110aa   S110AA  
label values s110ab   S110AB  
label values s110ac   S110AC  
label values s110ad   S110AD  
label values s110ae   S110AE  
label values s110af   S110AF  
label values s110ag   S110AG  
label values s110ah   S110AH  
label values s110ai   S110AI  
label values s110aj   S110AJ  
label values s110ak   S110AK  
label values s110al   S110AL  
label values s110ax   S110AX  
label values s110az   S110AZ  
label values s110ba   S110BA  
label values s110bb   S110BB  
label values s110bc   S110BC  
label values s110bd   S110BD  
label values s110be   S110BE  
label values s110bf   S110BF  
label values s110bg   S110BG  
label values s110bh   S110BH  
label values s110bi   S110BI  
label values s110bj   S110BJ  
label values s110bx   S110BX  
label values s110bz   S110BZ  
label values s110ca   S110CA  
label values s110cb   S110CB  
label values s110cc   S110CC  
label values s110cd   S110CD  
label values s110ce   S110CE  
label values s110cf   S110CF  
label values s110cg   S110CG  
label values s110ch   S110CH  
label values s110ci   S110CI  
label values s110cj   S110CJ  
label values s110ck   S110CK  
label values s110cl   S110CL  
label values s110cm   S110CM  
label values s110cx   S110CX  
label values s110cz   S110CZ  
label values s110d    S110D   
label values s111     S111    
label values s112aa   S112AA  
label values s112ab   S112AB  
label values s112ac   S112AC  
label values s112ad   S112AD  
label values s112ae   S112AE  
label values s112af   S112AF  
label values s112ag   S112AG  
label values s112ah   S112AH  
label values s112ai   S112AI  
label values s112aj   S112AJ  
label values s112ak   S112AK  
label values s112ax   S112AX  
label values s112az   S112AZ  
label values s112a    S112A   
label values s112b    S112B   
label values s112c    S112C   
label values s112d    S112D   
label values s112e    S112E   
label values s112f    S112F   
label values s112g    S112G   
label values s112h    S112H   
label values s112i    S112I   
label values s112j    S112J   
label values s113a    S113A   
label values s113b    S113B   
label values s113c    S113C   
label values s113d    S113D   
label values s113e    S113E   
label values s113f    S113F   
label values s113g    S113G   
label values s113h    S113H   
label values s113i    S113I   
label values s113j    S113J   
label values s113x    S113X   
label values s113z    S113Z   
label values s114a    S114A   
label values s114b    S114B   
label values s114c    S114C   
label values s115     S115    
label values s116a    S116A   
label values s116b    S116B   
label values s116c    S116C   
label values s116d    S116D   
label values s116e    S116E   
label values s116f    S116F   
label values s116x    S116X   
label values s116z    S116Z   
label values s117     S117    
label values s120     S120    
label values s121     S121    
label values s122a    S122A   
label values s122b    S122B   
label values s122c    S122C   
label values s122d    S122D   
label values s122e    S122E   
label values s122f    S122F   
label values s122g    S122G   
label values s122h    S122H   
label values s122i    S122I   
label values s122j    S122J   
label values s122k    S122K   
label values s122l    S122L   
label values s122m    S122M   
label values s122n    S122N   
label values s122x    S122X   
label values s123     S123    
label values s124     S124    
label values s125a    S125A   
label values s125b    S125B   
label values s125c    S125C   
label values s125d    S125D   
label values s125e    S125E   
label values s125f    S125F   
label values s125g    S125G   
label values s125h    S125H   
label values s125i    S125I   
label values s125x    S125X   
label values s125z    S125Z   
label values s126     S126    
label values s127     S127    
label values s129     S129    
label values s130a    S130A   
label values s130b    S130B   
label values s130c    S130C   
label values s130d    S130D   
label values s130e    S130E   
label values s130f    S130F   
label values s130g    S130G   
label values s130h    S130H   
label values s130i    S130I   
label values s130j    S130J   
label values s130k    S130K   
label values s130l    S130L   
label values s130m    S130M   
label values s130n    S130N   
label values s130o    S130O   
label values s130p    S130P   
label values s130q    S130Q   
label values s130r    S130R   
label values s130x    S130X   
label values s131     S131    
label values s132     S132    
label values s211     S211    
label values s403a    S403A   
label values s405a    S405A   
label values s412f    S412F   
label values s412g    S412G   
label values s412h    S412H   
label values s412n    S412N   
label values s412o    S412O   
label values s423     S423    
label values s425     S425    
