infile using "C:\USERS\61097\ICF\DATA ARCHIVE - DOCUMENTS\EXPORT MENU\NG8B\NGMR8BFL.dct"

label variable mcaseid  "Case Identification"
label variable mv000    "Country code and phase"
label variable mv001    "Cluster number"
label variable mv002    "Household number"
label variable mv003    "Respondent's line number"
label variable mv004    "Ultimate area unit"
label variable mv005    "Men's sample weight (6 decimals)"
label variable mv006    "Month of interview"
label variable mv007    "Year of interview"
label variable mv008    "Date of interview (CMC)"
label variable mv008a   "Date of interview Century Day Code (CDC)"
label variable mv009    "Month of birth"
label variable mv010    "Year of birth"
label variable mv011    "Date of birth (CMC)"
label variable mv012    "Current age"
label variable mv013    "Age in 5-year groups"
label variable mv014    "Completeness of age information"
label variable mv015    "Result of interview"
label variable mv016    "Day of interview"
label variable mv021    "Primary sampling unit"
label variable mv022    "Sample stratum number"
label variable mv023    "Sample domain"
label variable mv024    "Zone (codes are as per sample frame)"
label variable mv025    "Type of place of residence"
label variable mv026    "NA - De facto place of residence"
label variable mv027    "Number of visits"
label variable mv028    "Interviewer identification"
label variable mv029    "NA - Keyer identification"
label variable mv030    "Field supervisor"
label variable mv031    "NA - Field editor"
label variable mv032    "NA - Office editor"
label variable mv034_1  "Line number of wife/partner"
label variable mv034_2  "Line number of wife/partner"
label variable mv034_3  "Line number of wife/partner"
label variable mv034_4  "Line number of wife/partner"
label variable mv034_5  "Line number of wife/partner"
label variable mv034_6  "Line number of wife/partner"
label variable mv034_7  "Line number of wife/partner"
label variable mv034_8  "Line number of wife/partner"
label variable mv034a_1 "NA - Wife or partner"
label variable mv034a_2 "NA - Wife or partner"
label variable mv034a_3 "NA - Wife or partner"
label variable mv034a_4 "NA - Wife or partner"
label variable mv034a_5 "NA - Wife or partner"
label variable mv034a_6 "NA - Wife or partner"
label variable mv034a_7 "NA - Wife or partner"
label variable mv034a_8 "NA - Wife or partner"
label variable mv034b_1 "Age of wife/partner"
label variable mv034b_2 "Age of wife/partner"
label variable mv034b_3 "Age of wife/partner"
label variable mv034b_4 "Age of wife/partner"
label variable mv034b_5 "Age of wife/partner"
label variable mv034b_6 "Age of wife/partner"
label variable mv034b_7 "Age of wife/partner"
label variable mv034b_8 "Age of wife/partner"
label variable mv035    "Number of wives/partners"
label variable mv045a   "Language of questionnaire"
label variable mv045b   "Language of interview"
label variable mv045c   "Native language of respondent"
label variable mv046    "Translator used"
label variable mv047    "Team number"
label variable mv048    "NA - Team supervisor"
label variable mv801    "Time interview started (hhmm - 24 hour clock)"
label variable mv802    "Time interview ended (hhmm - 24 hour clock)"
label variable mv803    "Length of interview in minutes"
label variable mv101    "Zone (codes are as per sample frame)"
label variable mv102    "Type of place of residence"
label variable mv103    "NA - Childhood place of residence"
label variable mv104    "Years lived in place of residence"
label variable mv105    "Type of place of previous residence"
label variable mv105a   "Zone of previous residence"
label variable mv106    "Educational level"
label variable mv107    "Highest year of education (at level in MV106)"
label variable mv130    "Religion"
label variable mv131    "Ethnicity"
label variable mv133    "Total number of years of education"
label variable mv134    "NA - De facto place of residence"
label variable mv135    "Usual resident or visitor"
label variable mv136    "Number of household members (total listed)"
label variable mv138    "Number of eligible men in household (de facto)"
label variable mv149    "Educational attainment"
label variable mv150    "Relationship to household head"
label variable mv151    "Sex of household head"
label variable mv152    "Age of household head"
label variable mv155    "Literacy"
label variable mv156    "NA - Ever participated in a literacy program (excluding primary school)"
label variable mv157    "Frequency of reading newspaper or magazine"
label variable mv158    "Frequency of listening to radio"
label variable mv159    "Frequency of watching television"
label variable mv167    "NA - Times away from home in last 12 months"
label variable mv168    "NA - Away for more than one month in last 12 months"
label variable mv169a   "Owns a mobile telephone"
label variable mv169b   "Last 12 months use mobile telephone for financial transactions"
label variable mv169c   "Is respondent's mobile phone a smart phone"
label variable mv170    "Has an account in a bank or other financial institution"
label variable mv171a   "Use of internet"
label variable mv171b   "Frequency of using internet last month"
label variable mv172    "Respondent state of birth"
label variable mv173    "Respondent country of birth"
label variable mv174m   "Month move to current place of residence"
label variable mv174y   "Year move to current place of residence"
label variable mv175    "Reason for moving to current place of residence"
label variable mv176    "Self reported health status"
label variable mv177    "Money put/taken from bank account last 12 months"
label variable mv190    "Wealth index combined"
label variable mv191    "Wealth index factor score combined (5 decimals)"
label variable mv190a   "Wealth index for urban/rural"
label variable mv191a   "Wealth index factor score for urban/rural (5 decimals)"
label variable mv201    "Total children ever born"
label variable mv202    "Sons at home"
label variable mv203    "Daughters at home"
label variable mv204    "Sons elsewhere"
label variable mv205    "Daughters elsewhere"
label variable mv206    "Sons who have died"
label variable mv207    "Daughters who have died"
label variable mv212    "Age of respondent at 1st birth"
label variable mv213    "Partner currently pregnant"
label variable mv217    "Knowledge of ovulatory cycle"
label variable mv218    "Number of living children"
label variable mv225    "NA - Most recent pregnancy wanted"
label variable mv245    "Number of women fathered children with"
label variable mv246    "NA - Married to mother when first child was born"
label variable mv247    "Age of most recent child"
label variable mv248    "Antenatal check-ups for the mother of most recent child"
label variable mv249    "Respondent present during check-ups for most recent child"
label variable mv250    "Place of birth of most recent child"
label variable mv251    "NA - Reason for not delivering most recent child in health facility"
label variable mv252    "NA - Amount a child should drink, when that child has diarrhea"
label variable mv253    "Did go with child's mother to health facility for birth"
label variable mv301    "Knowledge of any contraceptive method"
label variable mv302    "NA - Ever use of any contraceptive method"
label variable m304a_01 "Type of contraceptive method"
label variable m304a_02 "Type of contraceptive method"
label variable m304a_03 "Type of contraceptive method"
label variable m304a_04 "Type of contraceptive method"
label variable m304a_05 "Type of contraceptive method"
label variable m304a_06 "Type of contraceptive method"
label variable m304a_07 "Type of contraceptive method"
label variable m304a_08 "Type of contraceptive method"
label variable m304a_09 "Type of contraceptive method"
label variable m304a_10 "Type of contraceptive method"
label variable m304a_11 "Type of contraceptive method"
label variable m304a_12 "Type of contraceptive method"
label variable m304a_13 "Type of contraceptive method"
label variable m304a_14 "Type of contraceptive method"
label variable m304a_15 "Type of contraceptive method"
label variable m304a_16 "Type of contraceptive method"
label variable m304a_17 "Type of contraceptive method"
label variable m304a_18 "Type of contraceptive method"
label variable m304a_19 "Type of contraceptive method"
label variable m304a_20 "Type of contraceptive method"
label variable mv304_01 "Knows contraceptive method"
label variable mv304_02 "Knows contraceptive method"
label variable mv304_03 "Knows contraceptive method"
label variable mv304_04 "Knows contraceptive method"
label variable mv304_05 "Knows contraceptive method"
label variable mv304_06 "Knows contraceptive method"
label variable mv304_07 "Knows contraceptive method"
label variable mv304_08 "Knows contraceptive method"
label variable mv304_09 "Knows contraceptive method"
label variable mv304_10 "Knows contraceptive method"
label variable mv304_11 "Knows contraceptive method"
label variable mv304_12 "Knows contraceptive method"
label variable mv304_13 "Knows contraceptive method"
label variable mv304_14 "Knows contraceptive method"
label variable mv304_15 "Knows contraceptive method"
label variable mv304_16 "Knows contraceptive method"
label variable mv304_17 "Knows contraceptive method"
label variable mv304_18 "Knows contraceptive method"
label variable mv304_19 "Knows contraceptive method"
label variable mv304_20 "Knows contraceptive method"
label variable mv305_01 "NA - Ever used contraceptive method"
label variable mv305_02 "NA - Ever used contraceptive method"
label variable mv305_03 "NA - Ever used contraceptive method"
label variable mv305_04 "NA - Ever used contraceptive method"
label variable mv305_05 "NA - Ever used contraceptive method"
label variable mv305_06 "NA - Ever used contraceptive method"
label variable mv305_07 "NA - Ever used contraceptive method"
label variable mv305_08 "NA - Ever used contraceptive method"
label variable mv305_09 "NA - Ever used contraceptive method"
label variable mv305_10 "NA - Ever used contraceptive method"
label variable mv305_11 "NA - Ever used contraceptive method"
label variable mv305_12 "NA - Ever used contraceptive method"
label variable mv305_13 "NA - Ever used contraceptive method"
label variable mv305_14 "NA - Ever used contraceptive method"
label variable mv305_15 "NA - Ever used contraceptive method"
label variable mv305_16 "NA - Ever used contraceptive method"
label variable mv305_17 "NA - Ever used contraceptive method"
label variable mv305_18 "NA - Ever used contraceptive method"
label variable mv305_19 "NA - Ever used contraceptive method"
label variable mv305_20 "NA - Ever used contraceptive method"
label variable mv307_01 "Contraceptive method currently used"
label variable mv307_02 "Contraceptive method currently used"
label variable mv307_03 "Contraceptive method currently used"
label variable mv307_04 "Contraceptive method currently used"
label variable mv307_05 "Contraceptive method currently used"
label variable mv307_06 "Contraceptive method currently used"
label variable mv307_07 "Contraceptive method currently used"
label variable mv307_08 "Contraceptive method currently used"
label variable mv307_09 "Contraceptive method currently used"
label variable mv307_10 "Contraceptive method currently used"
label variable mv307_11 "Contraceptive method currently used"
label variable mv307_12 "Contraceptive method currently used"
label variable mv307_13 "Contraceptive method currently used"
label variable mv307_14 "Contraceptive method currently used"
label variable mv307_15 "Contraceptive method currently used"
label variable mv307_16 "Contraceptive method currently used"
label variable mv307_17 "Contraceptive method currently used"
label variable mv307_18 "Contraceptive method currently used"
label variable mv307_19 "Contraceptive method currently used"
label variable mv307_20 "Contraceptive method currently used"
label variable mv312    "Current contraceptive method"
label variable mv312a   "You/your partner used any method to avoid pregnancy during last intercourse"
label variable mv313    "Current contraceptive by method type"
label variable mv323a   "NA - Brand of condom used"
label variable mv325b   "NA - Cost of condoms (in CURRENCY) last time obtained"
label variable mv372a   "NA - Interviewer shown condom package"
label variable mv384a   "On radio heard about Family Planning in the last few months"
label variable mv384b   "On TV saw about Family Planning in the last few months"
label variable mv384c   "In newspaper read about Family Planning in the last few months"
label variable mv384d   "Heard family planning by text messages on mobile phone"
label variable mv384e   "Seen about family planning on facebook, twitter, instagram, others"
label variable mv384f   "Seen about family planning on poster, brochure"
label variable mv384g   "Seen about family planning on outdoor sign, billboard"
label variable mv384h   "Heard family planning at community meetings events"
label variable mv384i   "NA - Heard/seen family planning CS"
label variable mv384j   "NA - Heard/seen family planning CS"
label variable mv384k   "NA - Heard/seen family planning CS"
label variable mv395    "Discussed Family Planning with health worker in last few months"
label variable mv396    "NA - Possible for a breastfeeding woman to get pregnant"
label variable mv396a   "Can women get pregnant after birth of a child before period return"
label variable mv3a00y  "Source of family planning for non-users: no source"
label variable mv3a00z  "Source of family planning for non-users: any source"
label variable mv3a09b  "NA - Number of condoms did get last time"
label variable mv3b17   "NA - Source of condoms"
label variable mv3b25a  "Contraception is woman's business, man should not worry"
label variable mv3b25b  "Women who use contraception become promiscuous"
label variable mv463a   "NA - Smokes cigarettes"
label variable mv463b   "NA - Smokes pipe"
label variable mv463c   "NA - Uses chewing tobacco"
label variable mv463d   "NA - Uses snuff"
label variable mv463e   "NA - Smokes/uses CS"
label variable mv463f   "NA - Smokes/uses CS"
label variable mv463g   "NA - Smokes/uses CS"
label variable mv463x   "NA - Smokes/uses other"
label variable mv463z   "NA - Smokes nothing"
label variable mv463aa  "Frequency currently smokes tobacco"
label variable mv463ab  "Frequency currently uses smokeless tobacco"
label variable mv463ac  "In the past smoked tobacco every day"
label variable mv463ad  "Frequency in the past smoked tobacco"
label variable mv464    "NA - Number of cigarettes in last 24 hours"
label variable mv464a   "On average respondent smokes daily: manufactured cigarettes"
label variable mv464b   "On average respondent smokes daily: hand roll cigarettes"
label variable mv464c   "On average respondent smokes daily: kreteks"
label variable mv464d   "On average respondent smokes daily: pipes full of tobacco"
label variable mv464e   "On average respondent smokes daily: cigars, cheroots, cigarillos"
label variable mv464f   "On average respondent smokes daily: water pipe sessions"
label variable mv464g   "On average respondent smokes daily: others"
label variable mv464h   "On average respondent uses daily: snuff by mouth"
label variable mv464i   "On average respondent uses daily: snuff by nose"
label variable mv464j   "On average respondent uses daily: chewing tobacco"
label variable mv464k   "On average respondent uses daily: betel quid with tobacco"
label variable mv464l   "On average respondent uses daily: any others"
label variable mv477    "NA - Number of injections in last 12 months"
label variable mv478    "NA - Number of injections administered by a health worker"
label variable mv479    "NA - Place where given injection by health worker"
label variable mv480    "NA - Syringe and needle from new, unopened package"
label variable mv481    "Covered by health insurance"
label variable mv481a   "Health insurance type: mutual/community organization"
label variable mv481b   "Health insurance type: provided by employer"
label variable mv481c   "Health insurance type: social security"
label variable mv481d   "Health insurance type: private/commercially purchased"
label variable mv481e   "NA - Health insurance type: CS"
label variable mv481f   "NA - Health insurance type: CS"
label variable mv481g   "NA - Health insurance type: CS"
label variable mv481h   "NA - Health insurance type: CS"
label variable mv481x   "Health insurance type: other"
label variable mv482a   "NA - Arrange care of biological children under age 18"
label variable mv482b   "NA - Primary caregiver of children under age 18"
label variable mv482c   "NA - Arrange care of non-biological children < 18"
label variable mv483    "Respondent circumcised"
label variable mv483a   "Age at traditional circumcision"
label variable mv483b   "NA - Who performed the circumcision"
label variable mv483c   "NA - Place where circumcision was done"
label variable mv483d   "Is respondent traditionally circumcised"
label variable mv483e   "Is respondent medically circumcised"
label variable mv483f   "Age at medical circumcision"
label variable mv484a   "On average respondent smokes weekly: manufactured cigarettes"
label variable mv484b   "On average respondent smokes weekly: hand roll cigarettes"
label variable mv484c   "On average respondent smokes weekly: kreteks"
label variable mv484d   "On average respondent smokes weekly: pipes full of tobacco"
label variable mv484e   "On average respondent smokes weekly: cigars, cheroots, cigarillos"
label variable mv484f   "On average respondent smokes weekly: water pipe sessions"
label variable mv484g   "On average respondent smokes weekly: others"
label variable mv484h   "On average respondent uses weekly: snuff by mouth"
label variable mv484i   "On average respondent uses weekly: snuff by nose"
label variable mv484j   "On average respondent uses weekly: chewing tobacco"
label variable mv484k   "On average respondent uses weekly: betel quid with tobacco"
label variable mv484l   "On average respondent uses weekly: any others"
label variable mv485a   "Number of days respondent drank alcoholic drinks in the past month"
label variable mv485b   "Number of alcoholic drinks per day"
label variable mv501    "Current marital status"
label variable mv502    "Currently/formerly/never in union"
label variable mv503    "Number of unions"
label variable mv504    "Currently residing with wife/partner"
label variable mv505    "Number of wives/partners"
label variable mv507    "Month of first cohabitation"
label variable mv508    "Year of first cohabitation"
label variable mv509    "Date of first cohabitation (CMC)"
label variable mv510    "Completeness of date information in MV509"
label variable mv511    "Age at first cohabitation"
label variable mv512    "Years since first cohabitation"
label variable mv513    "Cohabitation duration (grouped)"
label variable mv525    "Age at first sex"
label variable mv527    "Time since last sex"
label variable mv528    "Time since last sex (in days)"
label variable mv529    "Time since last sex (in months)"
label variable mv531    "Age at first sex (imputed)"
label variable mv532    "Flag for MV531"
label variable mv535    "Ever been married or in union"
label variable mv536    "Recent sexual activity"
label variable mv541    "NA - Intends to wait until marriage to have sex"
label variable mv602    "Fertility preference"
label variable mv603    "Preferred waiting time for birth of a/another child"
label variable mv604    "Preferred waiting time for birth of a/another child (grouped)"
label variable mv605    "Desire for more children"
label variable mv613    "Ideal number of children"
label variable mv614    "Ideal number of children (grouped)"
label variable mv616    "Desired time for future birth"
label variable mv621    "NA - Wife's desire for children"
label variable mv627    "Ideal number of boys"
label variable mv628    "Ideal number of girls"
label variable mv629    "Ideal number of either sex"
label variable mv631    "NA - Problem if wife became pregnant"
label variable mv633a   "NA - Wife justified refusing sex: husband has STI"
label variable mv633b   "Wife justified refusing sex: husband has other women"
label variable mv633c   "NA - Wife justified refusing sex: recent birth"
label variable mv633d   "NA - Wife justified refusing sex: tired, not in mood"
label variable mv633e   "NA - Wife justified refusing sex: CS reason"
label variable mv633f   "NA - Wife justified refusing sex: CS reason"
label variable mv633g   "NA - Wife justified refusing sex: CS reason"
label variable mv634a   "NA - Wife refuses to have sex, husband has right to: get angry"
label variable mv634b   "NA - Wife refuses to have sex, husband has right to: refuse financial support"
label variable mv634c   "NA - Wife refuses to have sex, husband has right to: use force for sex"
label variable mv634d   "NA - Wife refuses to have sex, husband has right to: have sex with another women"
label variable mv714    "Currently working"
label variable mv714a   "Have a job, but currently absent"
label variable mv716    "Occupation"
label variable mv717    "Occupation (grouped)"
label variable mv719    "NA - Works for family, others, self"
label variable mv721    "NA - Works at home or away"
label variable mv731    "Worked in last 12 months"
label variable mv732    "Employment all year/seasonal"
label variable mv739    "Person who usually decides how to spend respondent's earnings"
label variable mv740    "NA - Type of land where respondent works"
label variable mv741    "Type of earnings from respondent's work"
label variable mv743a   "Person who usually decides on: respondent's health care"
label variable mv743b   "Person who usually decides on: large household purchases"
label variable mv743c   "NA - Person who usually decides on: daily household purchases"
label variable mv743d   "NA - Person who usually decides on: visits to family or relatives"
label variable mv743e   "NA - Person who usually decides on: food to be cooked each day"
label variable mv743f   "NA - Person who usually decides on: deciding what to do with money wife earns"
label variable mv743g   "NA - Person who usually decides on: deciding how many children to have"
label variable mv744a   "Beating justified: wife goes out without telling husband"
label variable mv744b   "Beating justified: wife neglects the children"
label variable mv744c   "Beating justified: wife argues with husband"
label variable mv744d   "Beating justified: wife refuses to have sex with husband"
label variable mv744e   "Beating justified: wife burns food"
label variable mv745a   "Owns a house alone or jointly"
label variable mv745b   "Owns land alone or jointly"
label variable mv745c   "Title deed on house own by respondent"
label variable mv745d   "Title deed on land own by respondent"
label variable mv747a   "NA - Childbearing is a woman's concern"
label variable mv747b   "NA - Important for mother/child health to get assistance at delivery"
label variable md121    "Respondent's father ever beat his mother"
label variable mv750    "Ever heard of a Sexually Transmitted Infection (STI)"
label variable mv751    "NA - Ever heard of AIDS"
label variable mv754bp  "NA - Reduce risk of getting HIV: do not have sex at all"
label variable mv754cp  "Reduce risk of getting HIV: always use condoms during sex"
label variable mv754dp  "Reduce risk of getting HIV: have 1 sex partner only, who has no other partners"
label variable mv754jp  "Can get HIV from mosquito bites"
label variable mv754wp  "Can get HIV by sharing food with person who has AIDS"
label variable mv756    "A healthy looking person can have HIV"
label variable mv761    "Condom used during last sex with most recent partner"
label variable mv761b   "Condom used during last sex with 2nd to most recent partner"
label variable mv761c   "Condom used during last sex with 3rd to most recent partner"
label variable mv762    "Source of condoms used for last sex"
label variable mv762a   "Brand of condom used for last sex"
label variable mv763a   "Had any STI in last 12 months"
label variable mv763b   "Had genital sore/ulcer in last 12 months"
label variable mv763c   "Had genital discharge in last 12 months"
label variable mv763d   "NA - Had CS STI in last 12 months"
label variable mv763e   "NA - Had CS STI in last 12 months"
label variable mv763f   "NA - Had CS STI in last 12 months"
label variable mv763g   "NA - Had CS STI in last 12 months"
label variable mv766a   "Number of sex partners, excluding spouse, in last 12 months"
label variable mv766b   "Number of sex partners, including spouse, in last 12 months"
label variable mv767a   "Relationship with most recent sex partner"
label variable mv767b   "Relationship with 2nd to most recent sex partner"
label variable mv767c   "Relationship with 3rd to most recent sex partner"
label variable mv768a   "NA - Length of time had sex relations with most recent partner"
label variable mv768b   "NA - Length of time had sex relations with 2nd to most recent partner"
label variable mv768c   "NA - Length of time had sex relations with 3rd to most recent partner"
label variable mv770    "Sought advice/treatment for last STI infection"
label variable mv770a   "Sought STI advice/treatment from: Teaching hospital"
label variable mv770b   "Sought STI advice/treatment from: Federal medical center"
label variable mv770c   "Sought STI advice/treatment from: General hospital"
label variable mv770d   "Sought STI advice/treatment from: Primary health care center"
label variable mv770e   "Sought STI advice/treatment from: Primary health clinic"
label variable mv770f   "Sought STI advice/treatment from: Health post"
label variable mv770g   "Sought STI advice/treatment from: Stand-alone HTC center"
label variable mv770h   "Sought STI advice/treatment from: Mobile HTC services"
label variable mv770i   "Sought STI advice/treatment from: Other public sector"
label variable mv770k   "Sought STI advice/treatment from: Private hospital"
label variable mv770l   "Sought STI advice/treatment from: Private clinic"
label variable mv770m   "Sought STI advice/treatment from: Pharmacy"
label variable mv770n   "Sought STI advice/treatment from: Patent & proprietary medicine vendors (PPMV)"
label variable mv770o   "Sought STI advice/treatment from: Private doctor"
label variable mv770p   "Sought STI advice/treatment from: Mobile clinic"
label variable mv770q   "Sought STI advice/treatment from: Maternity center"
label variable mv770r   "Sought STI advice/treatment from: Stand-alone HTC center"
label variable mv770s   "Sought STI advice/treatment from: Mobile HTC services"
label variable mv770t   "Sought STI advice/treatment from: Other private medical sector"
label variable mv770na  "Sought STI advice/treatment from: Faith-based hospital"
label variable mv770nb  "Sought STI advice/treatment from: Faith-based clinic"
label variable mv770nc  "Sought STI advice/treatment from: Family planning clinic"
label variable mv770nd  "Sought STI advice/treatment from: Other NGO medical sector"
label variable mv770x   "Sought STI advice/treatment from: Other"
label variable mv770u   "Sought STI advice/treatment from: Traditional herbs"
label variable mv774a   "NA - HIV transmitted during pregnancy"
label variable mv774b   "NA - HIV transmitted during delivery"
label variable mv774c   "NA - HIV transmitted by breastfeeding"
label variable mv775    "NA - Knows someone who has, or is suspected of having, HIV"
label variable mv777    "NA - Would want HIV infection in family to remain secret"
label variable mv777a   "NA - Would be ashamed if someone in the family had HIV"
label variable mv778    "NA - Willing to care for relative with AIDS"
label variable mv779    "NA - A female teacher infected with HIV, but is not sick, should be allowed to c"
label variable mv780    "NA - Children should be taught about condoms to avoid AIDS"
label variable mv781    "Ever been tested for HIV"
label variable mv783    "NA - Know a place to get HIV test"
label variable mv784a   "NA - Place for HIV test: government hospital"
label variable mv784b   "NA - Place for HIV test: CS public"
label variable mv784c   "NA - Place for HIV test: CS public"
label variable mv784d   "NA - Place for HIV test: CS public"
label variable mv784e   "NA - Place for HIV test: CS public"
label variable mv784f   "NA - Place for HIV test: CS public"
label variable mv784g   "NA - Place for HIV test: CS public"
label variable mv784h   "NA - Place for HIV test: CS public"
label variable mv784i   "NA - Place for HIV test: CS public"
label variable mv784j   "NA - Place for HIV test: CS public"
label variable mv784k   "NA - Place for HIV test: private hospital/clinic/doctor"
label variable mv784l   "NA - Place for HIV test: CS private"
label variable mv784m   "NA - Place for HIV test: CS private"
label variable mv784n   "NA - Place for HIV test: CS private"
label variable mv784o   "NA - Place for HIV test: CS private"
label variable mv784p   "NA - Place for HIV test: CS private"
label variable mv784q   "NA - Place for HIV test: CS private"
label variable mv784r   "NA - Place for HIV test: CS private"
label variable mv784s   "NA - Place for HIV test: CS other"
label variable mv784t   "NA - Place for HIV test: CS other"
label variable mv784u   "NA - Place for HIV test: CS other"
label variable mv784v   "NA - Place for HIV test: CS other"
label variable mv784x   "NA - Place for HIV test: other"
label variable mv785    "Heard about other STIs"
label variable mv791    "NA - Have ever paid anyone in exchange for sex"
label variable mv791a   "NA - Last 12 months have given gifts or other goods to have sex"
label variable mv791b   "NA - Have ever given gifts or other goods to have sex"
label variable mv793    "NA - Paid for sex in last 12 months"
label variable mv793a   "NA - Condom used last time paid for sex in last 12 months"
label variable mv793b   "NA - Condom used every time paid for sex in last 12 months"
label variable mv820    "NA - Condom used at first sex"
label variable mv822    "Wife justified asking husband to use condom if he has STI"
label variable mv823    "NA - Can get HIV by witchcraft or supernatural means"
label variable mv824    "Drugs to avoid HIV transmission to baby during pregnancy"
label variable mv825    "Would buy vegetables from vendor with HIV"
label variable mv826    "NA - Last time tested for HIV"
label variable mv826a   "Months ago most recent HIV test"
label variable mv827    "NA - Last HIV test: on your own, offered or required"
label variable mv828    "Received result from last HIV test"
label variable mv829    "Place where last HIV test was taken"
label variable mv832b   "NA - Time since last sex with 2nd to most recent partner"
label variable mv832c   "NA - Time since last sex with 3rd to most recent partner"
label variable mv833a   "NA - Used condom every time had sex with most recent partner in last 12 months"
label variable mv833b   "NA - Used condom every time had sex with 2nd to most recent partner in last 12 m"
label variable mv833c   "NA - Used condom every time had sex with 3rd to most recent partner in last 12 m"
label variable mv834a   "NA - Age of most recent partner"
label variable mv834b   "NA - Age of 2nd to most recent partner"
label variable mv834c   "NA - Age of 3rd to most recent partner"
label variable mv835a   "NA - Alcohol consumption at last sex with most recent partner"
label variable mv835b   "NA - Alcohol consumption at last sex with 2nd to most recent partner"
label variable mv835c   "NA - Alcohol consumption at last sex with 3rd to most recent partner"
label variable mv836    "Total lifetime number of sex partners"
label variable mv837    "Heard of drugs to help HIV infected people live longer"
label variable mv852a   "NA - How long ago first had sex with most recent partner"
label variable mv852b   "NA - How long ago first had sex with 2nd most recent partner"
label variable mv852c   "NA - How long ago first had sex with 3rd most recent partner"
label variable mv853a   "NA - Times in last 12 months had sex with most recent partner"
label variable mv853b   "NA - Times in last 12 months had sex with 2nd most recent partner"
label variable mv853c   "NA - Times in last 12 months had sex with 3rd most recent partner"
label variable mv856    "Knowledge and use of HIV test kits"
label variable mv857a   "Children with HIV should be allowed to attend school with children without HIV"
label variable mv857b   "NA - People hesitate to take HIV test because reaction of other people if positi"
label variable mv857c   "NA - People talk badly about people with or believed to have HIV"
label variable mv857d   "NA - People with or believed to have HIV lose respect from other people"
label variable mv858    "NA - Would be afraid to get HIV from contact with saliva from infected person"
label variable mv859    "Knowledge and attitude to PrEP to prevent getting HIV"
label variable mv860m   "Month of most recent HIV test"
label variable mv860y   "Year of most recent HIV test"
label variable mv860c   "Date of most recent HIV test (CMC)"
label variable mv861    "Result of HIV test"
label variable mv862m   "Month received first HIV test positve"
label variable mv862y   "Year received first HIV test positve"
label variable mv862c   "Date received first HIV test positve (CMC)"
label variable mv863    "Currently taking ARVs"
label variable mv864    "Number of HIV tests"
label variable mv865    "Disclosed HIV status to others"
label variable mv866    "Respondent feels ashamed of HIV status"
label variable mv867a   "Things happened because HIV positive status: people talk badly"
label variable mv867b   "Things happened because HIV positive status: someone else disclosed status"
label variable mv867c   "Things happened because HIV positive status: verbally insulted/harassed/threaten"
label variable mv867d   "Things happened because HIV positive status: healthcare workers talked badly"
label variable mv867e   "Things happened because HIV positive status: healthcare workers verbally abused"
label variable mv867f   "NA - Things happened because HIV positive status: CS"
label variable mv867g   "NA - Things happened because HIV positive status: CS"
label variable mg100    "Ever heard of female circumcision"
label variable mg101    "Ever heard of genital cutting (probed)"
label variable mg117a   "NA - Female circumcision benefit: cleanliness/hygiene"
label variable mg117b   "NA - Female circumcision benefit: social acceptance"
label variable mg117c   "NA - Female circumcision benefit: better marriage prospects"
label variable mg117d   "NA - Female circumcision benefit: virginity/prevent premarital sex"
label variable mg117e   "NA - Female circumcision benefit: greater sexual pleasure for men"
label variable mg117f   "NA - Female circumcision benefit: religious approval"
label variable mg117g   "NA - Female circumcision benefit: CS"
label variable mg117h   "NA - Female circumcision benefit: CS"
label variable mg117i   "NA - Female circumcision benefit: CS"
label variable mg117j   "NA - Female circumcision benefit: CS"
label variable mg117x   "NA - Female circumcision benefit: other"
label variable mg117y   "NA - No benefit from female circumcision"
label variable mg118    "Female circumcision required by religion"
label variable mg119    "Female circumcision: continue or be stopped"
label variable mchd01   "Ever had blood pressure measured by doctor other healthcare worker"
label variable mchd02   "Ever been told that you have high blood pressure or hypertension"
label variable mchd03   "In past 12 months have been told that you have high blood pressure or hypertensi"
label variable mchd04   "Have been prescribed medication to control high blood pressure"
label variable mchd05   "Are you taken medication to control your blood pressure"
label variable mchd06   "Ever had blood sugar measured by doctor other healthcare worker"
label variable mchd07   "Ever been told that you have high blood sugar or diabetes"
label variable mchd08   "In past 12 months have been told that you have high blood sugar or diabetes"
label variable mchd09   "Have been prescribed medication to control high blood sugar"
label variable mchd10   "Are you taken medication to control your blood sugar"
label variable sm107    "Province/state lived before moved to place of interview"
label variable sm114    "Highest educational level"
label variable sm115    "Highest class at that level"
label variable smstate  "State (codes are as per sample frame)"
label variable smzone   "Zone (for final report)"
label variable smstate1 "State (for final report)"
label variable sm302ba  "Heard/seen family planning message: as for me and my partner"
label variable sm302bb  "Heard/seen family planning message: unspaced children"
label variable sm302bc  "Heard/seen family planning message: well-spaced children"
label variable sm302bd  "Heard/seen family planning message: it's not too late"
label variable sm302be  "Heard/seen family planning message: why is your wife"
label variable sm302bx  "Heard/seen family planning message: other"
label variable sm813a   "Heard of TB"
label variable sm813ba  "Way of TB spread: through coughing and sneezing"
label variable sm813bb  "Way of TB spread: through sharing utensil"
label variable sm813bc  "Way of TB spread: through touching a person with TB"
label variable sm813bd  "Way of TB spread: through food"
label variable sm813be  "Way of TB spread: through sexual contact"
label variable sm813bf  "Way of TB spread: through mosquito bites"
label variable sm813bx  "Way of TB spread: through other"
label variable sm813bz  "Way of TB spread: Don't know"
label variable sm813ca  "Sign and symptoms of TB: persistent cough (2 weeks or more)"
label variable sm813cb  "Sign and symptoms of TB: coughing with sputum"
label variable sm813cc  "Sign and symptoms of TB: weight loss"
label variable sm813cd  "Sign and symptoms of TB: coughing blood"
label variable sm813ce  "Sign and symptoms of TB: fever"
label variable sm813cf  "Sign and symptoms of TB: night sweats"
label variable sm813cg  "Sign and symptoms of TB: shortness of breath"
label variable sm813ch  "Sign and symptoms of TB: loss of appetite"
label variable sm813ci  "Sign and symptoms of TB: chest pain"
label variable sm813cj  "Sign and symptoms of TB: fatigue/tiredness"
label variable sm813cx  "Sign and symptoms of TB: other"
label variable sm813cz  "Sign and symptoms of TB: don't know"
label variable sm813d   "TB can be cured"
label variable sm813e   "Would keep it secret if family go TB"
label variable sm813fa  "Belief about TB: individual with TB should be admitted until disease is over"
label variable sm813fb  "Belief about TB: individuals with TB should be supported to take drugs"
label variable sm813fc  "Belief about TB: will not marry from family with TB"
label variable sm813fd  "Belief about TB: will not use same toilet as someone with TB"
label variable sm813fe  "Belief about TB: people with TB brought it on themselves"
label variable sm813ff  "Belief about TB: having TB is a punishment from God"
label variable sm816a   "Heard of viral hepatitis B"
label variable sm816b   "Tested for viral hepatitis B"
label variable sm816c   "Result of test"
label variable sm816d   "Treated for viral hepatitis B in last year"
label variable sm816e   "Vaccinated for hep B"
label variable sm816ea  "Heard of hep C"
label variable sm816eb  "Tested for hep C in last 12 months"
label variable sm816ec  "Result of test"
label variable sm816ed  "Treated for hep C in last 12 months"
label variable sm816f   "Heard of COVID-19"
label variable sm816ga  "Source of information: community health workers"
label variable sm816gb  "Source of information: other frontline workers from I/NGO"
label variable sm816gc  "Source of information: radio program"
label variable sm816gd  "Source of information: SMS/Text messaging"
label variable sm816ge  "Source of information: health facility"
label variable sm816gf  "Source of information: photo counseling"
label variable sm816gg  "Source of information: television"
label variable sm816gh  "Source of information: mobile ring tone"
label variable sm816gi  "Source of information: family/relatives/friends/neighbors"
label variable sm816gj  "Source of information: social media"
label variable sm816gx  "Source of information: other"
label variable sm816gz  "Source of information: don't know"
label variable sm816ha  "Symptoms of COVID-19: fever"
label variable sm816hb  "Symptoms of COVID-19: cough"
label variable sm816hc  "Symptoms of COVID-19: shortness of breath and breathing difficulties"
label variable sm816hd  "Symptoms of COVID-19: muscle pain"
label variable sm816he  "Symptoms of COVID-19: headache"
label variable sm816hf  "Symptoms of COVID-19: loss of taste or smell"
label variable sm816hg  "Symptoms of COVID-19: diarrhea"
label variable sm816hh  "Symptoms of COVID-19: common cold and running nose"
label variable sm816hx  "Symptoms of COVID-19: other"
label variable sm816hz  "Symptoms of COVID-19: don't know"
label variable sm816ia  "Risks for spread: essential worker"
label variable sm816ib  "Risks for spread: immunocompromised"
label variable sm816ic  "Risks for spread: not wearing a mask"
label variable sm816id  "Risks for spread: poor room ventilation"
label variable sm816ie  "Risks for spread: senior citizen"
label variable sm816if  "Risks for spread: not being vaccinated"
label variable sm816ig  "Risks for spread: not maintaining social distance"
label variable sm816ix  "Risks for spread: other"
label variable sm816iz  "Risks for spread: don't know"
label variable sm816ja  "Measures taken to reduce risk:  wearing as mask"
label variable sm816jb  "Measures taken to reduce risk: washing hands properly"
label variable sm816jc  "Measures taken to reduce risk: using sanitizer"
label variable sm816jd  "Measures taken to reduce risk: maintaining distance"
label variable sm816je  "Measures taken to reduce risk: avoid touching eyes/nose/mouth"
label variable sm816jf  "Measures taken to reduce risk: practice respiratory hygiene"
label variable sm816jg  "Measures taken to reduce risk: get vaccinated"
label variable sm816jh  "Measures taken to reduce risk: focus on cleanliness"
label variable sm816ji  "Measures taken to reduce risk: drink hot water (with or without herbs)"
label variable sm816jx  "Measures taken to reduce risk: other"
label variable sm816jz  "Measures taken to reduce risk: did nothing"
label variable sm816k   "Received COVID-19 vaccination"
label variable sm816l   "Type of COVID-19 vaccination received"
label variable sm816m   "Number of doses of COVID-19 vaccination received"
label variable sm816n   "Willing to be vaccinated against COVID-19"
label variable sm816o   "Bitten by snake"
label variable sm816p   "Sought health care attention after bite"
label variable sm816q   "Source of care sought after bite"
label variable sm816r   "Given snake antivenom"
label variable sml101   "NA - Type of mosquito bed net(s) slept under last night"
label variable sml901   "Last six months heard/seen malaria messages"
label variable sml901a  "Malaria messages were heard/seen: radio"
label variable sml901b  "Malaria messages were heard/seen: television"
label variable sml901c  "Malaria messages were heard/seen: poster/billboard"
label variable sml901d  "Malaria messages were heard/seen: newspaper/magazine"
label variable sml901e  "Malaria messages were heard/seen: leaflet/brochure"
label variable sml901f  "Malaria messages were heard/seen: healthcare provider"
label variable sml901g  "Malaria messages were heard/seen: community health worker"
label variable sml901h  "Malaria messages were heard/seen: social media"
label variable sml901i  "Malaria messages were heard/seen: family/friends/neighbor"
label variable sml901x  "Malaria messages were heard/seen: other"
label variable sml901z  "Malaria messages were heard/seen: don't remember"
label variable sml903   "Are there ways to avoid getting malaria"
label variable sml903a  "Malaria can be prevented by: sleep under a mosquito net"
label variable sml903b  "Malaria can be prevented by: sleep under an insecticide-treated mosquito net"
label variable sml903c  "Malaria can be prevented by: use mosquito repellent"
label variable sml903d  "Malaria can be prevented by: take preventive medications"
label variable sml903e  "Malaria can be prevented by: spray house with insecticide"
label variable sml903f  "Malaria can be prevented by: fill in stagnant waters"
label variable sml903g  "Malaria can be prevented by: keep surroundings clean"
label variable sml903h  "Malaria can be prevented by: put mosquito screen on windows"
label variable sml903x  "Malaria can be prevented by: other"
label variable sml903z  "Malaria can be prevented by: don't know"
label variable sml905   "Agree/disagree with: people in community get malaria in rainy season"
label variable sml906   "Agree/disagree with: when child has fever worry it is malaria"
label variable sml907   "Agree/disagree with: getting malaria not a problem as can be treated"
label variable sml908   "Agree/disagree with: only weak children can die from malaria"
label variable sml909   "Agree/disagree with: sleep under net when there are lots of mosquitoes"
label variable sml910   "Agree/disagree with: sleep under net when there are few mosquitoes"
label variable sml911   "Agree/disagree with: don't like sleep in a net when is too warm"
label variable sml912   "Agree/disagree with: if child has fever good to give medicine available at home"
label variable sml913   "Agree/disagree with: people take children to health provider same day develop fe"
label variable sml914   "Agree/disagree with: people who have nets usually sleep under every night"

#delimit ;
label define MV013   
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
     8 "50-54"
     9 "55-59"
    10 "60-64"
;
label define MV014   
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define MV015   
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define MV022   
     1 "Sokoto Urban"
     2 "Sokoto Rural"
     3 "Zamfara Urban"
     4 "Zamfara Rural"
     5 "Katsina Urban"
     6 "Katsina Rural"
     7 "Jigawa Urban"
     8 "Jigawa Rural"
     9 "Yobe Urban"
    10 "Yobe Rural"
    11 "Borno Urban"
    12 "Borno Rural"
    13 "Adamawa Urban"
    14 "Adamawa Rural"
    15 "Gombe Urban"
    16 "Gombe Rural"
    17 "Bauchi Urban"
    18 "Bauchi Rural"
    19 "Kano Urban"
    20 "Kano Rural"
    21 "Kaduna Urban"
    22 "Kaduna Rural"
    23 "Kebbi Urban"
    24 "Kebbi Rural"
    25 "Niger Urban"
    26 "Niger Rural"
    27 "FCT Urban"
    28 "FCT Rural"
    29 "Nasarawa Urban"
    30 "Nasarawa Rural"
    31 "Plateau Urban"
    32 "Plateau Rural"
    33 "Taraba Urban"
    34 "Taraba Rural"
    35 "Benue Urban"
    36 "Benue Rural"
    37 "Kogi Urban"
    38 "Kogi Rural"
    39 "Kwara Urban"
    40 "Kwara Rural"
    41 "Oyo Urban"
    42 "Oyo Rural"
    43 "Osun Urban"
    44 "Osun Rural"
    45 "Ekiti Urban"
    46 "Ekiti Rural"
    47 "Ondo Urban"
    48 "Ondo Rural"
    49 "Edo Urban"
    50 "Edo Rural"
    51 "Anambra Urban"
    52 "Anambra Rural"
    53 "Enugu Urban"
    54 "Enugu Rural"
    55 "Ebonyi Urban"
    56 "Ebonyi Rural"
    57 "Cross River Urban"
    58 "Cross River Rural"
    59 "Akwa Ibom Urban"
    60 "Akwa Ibom Rural"
    61 "Abia Urban"
    62 "Abia Rural"
    63 "Imo Urban"
    64 "Imo Rural"
    65 "Rivers Urban"
    66 "Rivers Rural"
    67 "Bayelsa Urban"
    68 "Bayelsa Rural"
    69 "Delta Urban"
    70 "Delta Rural"
    71 "Lagos Urban"
    72 "Lagos Rural"
    73 "Ogun Urban"
    74 "Ogun Rural"
;
label define MV023   
     1 "Sokoto Urban"
     2 "Sokoto Rural"
     3 "Zamfara Urban"
     4 "Zamfara Rural"
     5 "Katsina Urban"
     6 "Katsina Rural"
     7 "Jigawa Urban"
     8 "Jigawa Rural"
     9 "Yobe Urban"
    10 "Yobe Rural"
    11 "Borno Urban"
    12 "Borno Rural"
    13 "Adamawa Urban"
    14 "Adamawa Rural"
    15 "Gombe Urban"
    16 "Gombe Rural"
    17 "Bauchi Urban"
    18 "Bauchi Rural"
    19 "Kano Urban"
    20 "Kano Rural"
    21 "Kaduna Urban"
    22 "Kaduna Rural"
    23 "Kebbi Urban"
    24 "Kebbi Rural"
    25 "Niger Urban"
    26 "Niger Rural"
    27 "FCT Urban"
    28 "FCT Rural"
    29 "Nasarawa Urban"
    30 "Nasarawa Rural"
    31 "Plateau Urban"
    32 "Plateau Rural"
    33 "Taraba Urban"
    34 "Taraba Rural"
    35 "Benue Urban"
    36 "Benue Rural"
    37 "Kogi Urban"
    38 "Kogi Rural"
    39 "Kwara Urban"
    40 "Kwara Rural"
    41 "Oyo Urban"
    42 "Oyo Rural"
    43 "Osun Urban"
    44 "Osun Rural"
    45 "Ekiti Urban"
    46 "Ekiti Rural"
    47 "Ondo Urban"
    48 "Ondo Rural"
    49 "Edo Urban"
    50 "Edo Rural"
    51 "Anambra Urban"
    52 "Anambra Rural"
    53 "Enugu Urban"
    54 "Enugu Rural"
    55 "Ebonyi Urban"
    56 "Ebonyi Rural"
    57 "Cross River Urban"
    58 "Cross River Rural"
    59 "Akwa Ibom Urban"
    60 "Akwa Ibom Rural"
    61 "Abia Urban"
    62 "Abia Rural"
    63 "Imo Urban"
    64 "Imo Rural"
    65 "Rivers Urban"
    66 "Rivers Rural"
    67 "Bayelsa Urban"
    68 "Bayelsa Rural"
    69 "Delta Urban"
    70 "Delta Rural"
    71 "Lagos Urban"
    72 "Lagos Rural"
    73 "Ogun Urban"
    74 "Ogun Rural"
;
label define MV024   
     1 "North west"
     2 "North east"
     3 "North central"
     4 "South east"
     5 "South south"
     6 "South west"
;
label define MV025   
     1 "Urban"
     2 "Rural"
;
label define MV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV027   
     9 "Missing"
;
label define MV029   
   999 "Missing"
;
label define MV034   
     0 "Wife not in household"
;
label define MV034A  
     1 "Wife"
     2 "Partner"
;
label define MV034B  
    98 "Don't know"
;
label define MV035   
     0 "No wives/partners"
;
label define MV045A  
     1 "English"
     2 "Hausa"
     3 "Yoruba"
     4 "Igbo"
;
label define MV045B  
     1 "English"
     2 "Hausa"
     3 "Yoruba"
     4 "Igbo"
;
label define MV045C  
     1 "English"
     2 "Hausa"
     3 "Yoruba"
     4 "Igbo"
     6 "Other language"
;
label define MV046   
     0 "No"
     1 "Yes"
;
label define MV801   
  9999 "Missing"
;
label define MV802   
  9999 "Missing"
;
label define MV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define MV101   
     1 "North west"
     2 "North east"
     3 "North central"
     4 "South east"
     5 "South south"
     6 "South west"
;
label define MV102   
     1 "Urban"
     2 "Rural"
;
label define MV103   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV104   
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV105   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV105A  
     1 "North central"
     2 "North east"
     3 "North west"
     4 "South east"
     5 "South south"
     6 "South west"
    96 "Abroad"
;
label define MV106   
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define MV107   
     0 "No years completed at level MV106"
;
label define MV130   
     1 "Catholic"
     2 "Other Christian"
     3 "Islam"
     4 "Traditionalist"
    96 "Other"
;
label define MV131   
     1 "Abua"
     2 "Adra/Adarawa"
     3 "Adun"
     4 "Afcabeya"
     5 "Afemai"
     6 "Afizire"
     7 "Agatu"
     8 "Agbassa"
     9 "Agbor"
    10 "Afo"
    11 "Ajowa"
    12 "Akpa"
    13 "Akwai"
    14 "Akye"
    15 "Alago"
    16 "Amamong"
    17 "Amo"
    18 "Ana"
    19 "Anaguta"
    20 "Ankwai"
    21 "Annang"
    22 "Arab"
    23 "Arabo"
    24 "Arbar"
    25 "Arugu"
    26 "Aten/Atam"
    27 "Attakar"
    28 "Auchi"
    29 "Aulliminden"
    30 "Awo"
    31 "Ayetoro Gbede"
    32 "Badarare"
    33 "Bade/Badawe"
    34 "Bafeke"
    35 "Bagathiya"
    36 "Baggara"
    37 "Bagunge/Badagire"
    38 "Bahnake"
    39 "Baji/Biji"
    40 "Bajju"
    41 "Bambaro"
    42 "Bambuka"
    43 "Bandawa"
    44 "Banguji"
    45 "Bankalawa"
    46 "Bchama"
    47 "Barabaci"
    48 "Barawa"
    49 "Bargawa"
    50 "Bassa"
    51 "Bekworas"
    53 "Berom"
    54 "Bini/Edo"
    55 "Bogom"
    56 "Boiyawa/Bozaya"
    57 "Bolawa/Bolewa"
    59 "Buduma"
    60 "Buko"
    61 "Bura/Babur"
    62 "Buzu"
    63 "Byazhi"
    64 "Calabar"
    65 "Chala"
    66 "Chamba"
    67 "Chiba"
    68 "Chibok(g)"
    69 "Chip"
    70 "Dadiya"
    71 "Badakare/Dakarkari"
    72 "Dakka/Doka"
    73 "Dangula"
    74 "Daurawa/Dagarawa"
    75 "Defaka"
    76 "Degima"
    77 "Delta Ibo"
    78 "Dibo"
    79 "Diguza"
    80 "Djerma"
    81 "Dmoko"
    82 "Dolchi"
    83 "Ebira/Igbira"
    84 "Ebu"
    85 "Efik"
    86 "Egba"
    87 "Egbado"
    88 "Eggon"
    89 "Egun"
    90 "Eket"
    91 "Ekoi"
    92 "Ekpeye/Afisa/Epie"
    94 "Ekulu"
    95 "Eleme"
    96 "Emu"
    97 "Esan"
    98 "Etina"
    99 "Etsako"
   100 "Etulo"
   101 "Hadejawa"
   102 "Fanso"
   103 "Femawa"
   104 "Fer"
   105 "Filiya/Fali"
   106 "Fon"
   107 "Foron"
   108 "French"
   109 "Fulani"
   110 "Gamaku"
   111 "Gamaru"
   112 "Gamuni"
   113 "Gana Gana"
   114 "Ganawuri"
   115 "Gbaju/Gbagi"
   116 "Gede/Gude/Gai"
   117 "Gerawa"
   118 "Gizmawa"
   119 "Glauda"
   120 "Gmenchi"
   121 "Gomo/Gamoyaya"
   122 "Gobiri/Gobirawa/Bogobiri"
   123 "Gujjurawa"
   124 "Guemai"
   125 "Gumbarawa"
   126 "Gunganchi"
   127 "Gwandara"
   128 "Gwantu"
   129 "Hankwe"
   130 "Hausa"
   131 "Higgi"
   132 "Ibariba"
   133 "Ibibio"
   134 "Ichen"
   135 "Idanre"
   136 "Idoma"
   137 "Igala"
   138 "Igbo/Ibo"
   139 "Igede"
   140 "Ijaw/Izon"
   141 "Ijede"
   142 "Ijeme"
   143 "Ika"
   144 "Ikajo"
   145 "Ikara"
   146 "Ikpeshi"
   147 "Ikpide"
   148 "Ikulu"
   149 "Ikwere"
   150 "Ilaje"
   151 "Irigwe"
   152 "Ishan"
   153 "Isoko"
   154 "Itsekiri"
   155 "Jaba"
   156 "Jajiri"
   157 "Jakatoe"
   158 "Jaku"
   159 "Jara"
   160 "Jarawa"
   162 "Jibu"
   163 "Jonjo"
   164 "Jukun"
   165 "Kabawa"
   166 "Kadara"
   167 "Kagoma"
   168 "Kagoro"
   169 "Kaka"
   170 "Kakanda"
   171 "Kamantam"
   172 "Kambari"
   173 "Kambu/Kangu"
   174 "Kamuku"
   175 "Kanakuru"
   176 "Kanawa"
   177 "Kaninko"
   178 "Kantanawa"
   179 "Kanuri/Beriberi"
   180 "Manga"
   181 "Karekare"
   182 "Kataf/Atyap"
   183 "Kento"
   184 "Kibaku"
   185 "Kilba"
   186 "Kirdi"
   187 "Kodki"
   188 "Kofyar"
   189 "Kona"
   190 "Koro"
   191 "Koto"
   192 "Kuenuem"
   193 "Kumbo"
   194 "Kunkawa/Kawa"
   195 "Kurama"
   196 "Kuteb"
   197 "Kuturm"
   198 "Kwale/Ukwuani"
   199 "Kwanzo"
   200 "Lagelu"
   201 "Lantang"
   202 "Lemoro"
   203 "Loh"
   204 "Lunguda"
   205 "Maba/Mbadowa"
   206 "Mada"
   207 "Mafa/Maka/Maga"
   208 "Mambila"
   209 "Mandara"
   210 "Mangus/Manju"
   211 "Marghi/mangi"
   212 "Mbwa"
   213 "Mingo"
   214 "Mirnang"
   215 "Montor"
   216 "Mtchiga/Michika"
   217 "Mumuye"
   218 "Munga"
   219 "Mupung"
   220 "Mushere"
   221 "Mwagavol"
   222 "Naiawum"
   223 "Namoen"
   224 "Ndokwa"
   225 "Ndola"
   226 "Ngamo"
   227 "Ukale"
   228 "Ngoshe"
   229 "Nili"
   230 "Ninnma"
   231 "Ninzom"
   232 "Nkoroo"
   233 "Nnebe"
   234 "Numana"
   235 "Nungu"
   236 "nunku"
   237 "Nupe"
   238 "Obubua"
   239 "Odu"
   240 "Ogoja"
   241 "Ogoni"
   242 "Ogugu"
   243 "Okori/Ogori"
   244 "Omele"
   245 "Ora"
   246 "Oron"
   247 "Owan"
   249 "Owo"
   250 "Pa'awa"
   251 "Paburi"
   252 "Paibun"
   253 "Panya"
   254 "Pasama"
   255 "Pero"
   256 "Piya"
   257 "Pyem"
   258 "Rukuba"
   259 "Rulere"
   260 "Rundawa"
   261 "Sayawa/Siyawa"
   262 "Sekere"
   263 "Sharawa"
   264 "Shomo"
   265 "Shuwa"
   266 "Somunka"
   267 "Sullubawa"
   268 "Sura"
   269 "Taira"
   270 "Tangale"
   272 "Tarok"
   273 "Tera"
   274 "Teskwa"
   275 "Tiguni ( ? )"
   276 "Tiv"
   277 "Tiyari"
   278 "Tula"
   279 "Ubaija"
   280 "Ugbia"
   281 "Uhionigbe"
   282 "Ukwuani"
   283 "Urhobo"
   284 "Uyo"
   285 "Uzaurue"
   286 "Uzeba"
   287 "Waja"
   288 "Waka"
   289 "Wanu"
   290 "Wari"
   291 "Warjawa"
   292 "Wodaabe"
   293 "Wurkum"
   294 "Yakurr"
   295 "Yandang"
   296 "Yendre"
   297 "Yonubi"
   298 "Yoruba"
   299 "Zabarmawa"
   301 "Kaje"
   302 "Igbanko"
   303 "Okori/Ogori"
   304 "Migili"
   305 "Gwari"
   306 "Uru"
   307 "Okirika"
   308 "Egi"
   309 "Ogba"
   310 "Moroa"
   311 "Marwa"
   312 "Toff"
   313 "Fulfulde"
   314 "Kabba/Okun"
   315 "Bakabe"
   316 "Burmanch"
   317 "Kalabari"
   320 "Miship"
   321 "Karimjo"
   322 "Kwa"
   323 "Angas"
   324 "Bobari"
   325 "Yarimawa"
   326 "Bakenga"
   327 "Agazawa"
   328 "Gwoza"
   329 "Zalidva"
   330 "Nyangdang"
   331 "Ngezim"
   332 "Hanbagda"
   333 "Njanyi"
   334 "Dumak"
   335 "Kwalla"
   336 "Yeskwa and Mubula"
   337 "Bile"
   338 "Offa"
   339 "Yungur"
   340 "Pura Pura"
   341 "Rindre"
   342 "Dukawa"
   343 "Ningi"
   344 "Cham"
   345 "Kamo"
   346 "Lala"
   347 "Laru"
   348 "Lisa"
   349 "Gaanda"
   350 "Ezza"
   351 "Kubasawa."
   352 "Gusu"
   353 "Ikpoma"
   354 "Buh"
   355 "Mushere"
   356 "Chakeem"
   357 "Jipal"
   358 "Ugeb"
   359 "Koma"
   360 "Verre/Kila"
   361 "Zuru"
   362 "Honna"
   363 "Kapsiki"
   364 "Jere"
   365 "Gizi Yobe"
   366 "Karekare"
   367 "Kulere"
   368 "Beteer"
   369 "Bashama"
   370 "Antocha"
   371 "Baruba/Baruntin"
   372 "Nezou"
   373 "Dibba"
   374 "Kanum"
   375 "Gasawa"
   376 "Muryan"
   377 "Bageri"
   378 "Ahu"
   379 "Basange"
   380 "Nakere"
   381 "Batunu"
   382 "Sanga"
   383 "Ohari"
   384 "Numuro"
   385 "Tangale"
   386 "Guruma"
   387 "Otuwo"
   388 "Batala"
   389 "Ogbo"
   390 "Egbema"
   391 "Dara"
   392 "Andoni"
   393 "Obolo"
   394 "Pegan"
   395 "Iyala"
   396 "Jibawa"
   397 "Mungaduso"
   398 "Okobo"
   996 "Others"
   998 "Don't know"
;
label define MV133   
    97 "Inconsistent"
;
label define MV134   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV135   
     1 "Usual resident"
     2 "Visitor"
;
label define MV149   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define MV150   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    15 "Brother/sister in law"
    98 "Don't know"
;
label define MV151   
     1 "Male"
     2 "Female"
;
label define MV152   
    97 "97+"
    98 "Don't know"
;
label define MV155   
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define MV156   
     0 "No"
     1 "Yes"
;
label define MV157   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV158   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV159   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV167   
     0 "None"
    90 "90+"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV168   
     0 "No"
     1 "Yes"
;
label define MV169A  
     0 "No"
     1 "Yes"
;
label define MV169B  
     0 "No"
     1 "Yes"
;
label define MV169C  
     0 "No"
     1 "Yes"
;
label define MV170   
     0 "No"
     1 "Yes"
;
label define MV171A  
     0 "Never"
     1 "Yes, last 12 months"
     2 "Yes, before last 12 months"
     3 "Yes, can't establish when"
;
label define MV171B  
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV172   
     1 "FCT-Abuja"
     2 "Benue"
     3 "Kogi"
     4 "Kwara"
     5 "Nasarawa"
     6 "Niger"
     7 "Plateau"
     8 "Adamawa"
     9 "Bauchi"
    10 "Borno"
    11 "Gombe"
    12 "Taraba"
    13 "Yobe"
    14 "Jigawa"
    15 "Kaduna"
    16 "Kano"
    17 "Katsina"
    18 "Kebbi"
    19 "Sokoto"
    20 "Zamfara"
    21 "Abia"
    22 "Anambra"
    23 "Ebonyi"
    24 "Enugu"
    25 "Imo"
    26 "Akwa Ibom"
    27 "Bayelsa"
    28 "Cross River"
    29 "Delta"
    30 "Edo"
    31 "Rivers"
    32 "Ekiti"
    33 "Lagos"
    34 "Ogun"
    35 "Ondo"
    36 "Osun"
    37 "Oyo"
    96 "Abroad"
;
label define MV173   
     2 "Algeria"
     3 "Angola"
     4 "Benin"
     5 "Botswana"
     6 "Burkina Faso"
     7 "Burundi"
     8 "Cabo Verde"
     9 "Cameroon"
    10 "Central African Republic (CAR)"
    11 "Chad"
    12 "Comoros"
    13 "Democratic Republic of the Congo"
    14 "Republic of the Congo"
    15 "Cote d'Ivoire"
    16 "Djibouti"
    17 "Egypt"
    18 "Equatorial Guinea"
    19 "Eritrea"
    20 "Eswatini"
    21 "Ethiopia"
    22 "Gabon"
    23 "Gambia"
    24 "Ghana"
    25 "Guinea"
    26 "Guinea-Bissau"
    27 "Kenya"
    28 "Lesotho"
    29 "Liberia"
    30 "Libya"
    31 "Madagascar"
    32 "Malawi"
    33 "Mali"
    34 "Mauritania"
    35 "Morocco"
    36 "Mozambique"
    37 "Namibia"
    38 "Niger"
    39 "Rwanda"
    40 "Sao Tome and Principe"
    41 "Senegal"
    42 "Seychelles"
    43 "Sierra Leone"
    44 "Somalia"
    45 "South Africa"
    46 "South Sudan"
    47 "Sudan"
    48 "Tanzania"
    49 "Togo"
    50 "Tunisia"
    51 "Uganda"
    52 "Zambia"
    53 "Zimbabwe"
    96 "Other country"
;
label define MV174M  
    98 "Don't know month"
;
label define MV174Y  
  9998 "Don't know year"
;
label define MV175   
     1 "Employment"
     2 "Education/training"
     3 "Marriage formation"
     4 "Family reunification/other family-related reason"
     5 "Forced displacement"
    10 "CS"
    11 "CS"
    19 "CS"
    96 "Other"
;
label define MV176   
     1 "Very good"
     2 "Good"
     3 "Moderate"
     4 "Bad"
     5 "Very bad"
;
label define MV177   
     0 "No"
     1 "Yes"
;
label define MV190   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define MV190A  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define MV212   
    99 "Missing"
;
label define MV213   
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV217   
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define MV225   
     1 "Then"
     2 "Later"
     3 "Not at all"
;
label define MV245   
    95 "More than one woman, but unknown number"
;
label define MV246   
     0 "No"
     1 "Yes"
;
label define MV247   
    99 "Missing"
;
label define MV248   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV249   
     0 "Not present"
     1 "Present"
;
label define MV250   
     1 "Hospital, health facility"
     2 "Other"
;
label define MV251   
     1 "Cost too much"
     2 "Facility closed"
     3 "Too far/no transportation"
     4 "Don't trust facility/poor quality service"
     5 "No female provider"
     6 "Not the first child"
     7 "Mother did not think it necessary"
     8 "Respondent did not think it necessary"
     9 "Family did not think it necessary"
    96 "Other"
    98 "Don't know"
;
label define MV252   
     0 "Nothing to drink"
     2 "Less than usual/much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define MV253   
     0 "No"
     1 "Yes"
;
label define MV301   
     0 "Knows no method"
     1 "Knows only folkloric method"
     2 "Knows only traditional method"
     3 "Knows modern method"
;
label define MV302   
     0 "Never used"
     1 "Used only folkloric method"
     2 "Used only traditional method"
     3 "Used modern method"
;
label define M304A   
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define MV304   
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV305   
     0 "No"
     1 "Yes"
;
label define MV307   
     0 "No"
     1 "Yes"
;
label define MV312   
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Male condom"
     6 "Female sterilization"
     7 "Male sterilization"
     8 "Periodic abstinence"
     9 "Withdrawal"
    10 "Other traditional"
    11 "Implants/Norplant"
    12 "Prolonged abstinence"
    13 "Lactational amenorrhea (LAM)"
    14 "Female condom"
    15 "Foam or jelly"
    16 "Emergency contraception"
    17 "Other modern method"
    18 "Standard days method (SDM)"
    19 "Specific method 1"
    20 "Specific method 2"
;
label define MV312A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV313   
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     8 "Don't know"
;
label define MV323A  
    96 "Other"
    98 "Don't know"
;
label define MV325B  
9999995 "Free"
9999998 "Don't know"
;
label define MV372A  
     0 "Package not seen"
     1 "Package seen"
;
label define MV384A  
     0 "No"
     1 "Yes"
;
label define MV384B  
     0 "No"
     1 "Yes"
;
label define MV384C  
     0 "No"
     1 "Yes"
;
label define MV384D  
     0 "No"
     1 "Yes"
;
label define MV384E  
     0 "No"
     1 "Yes"
;
label define MV384F  
     0 "No"
     1 "Yes"
;
label define MV384G  
     0 "No"
     1 "Yes"
;
label define MV384H  
     0 "No"
     1 "Yes"
;
label define MV384I  
     0 "No"
     1 "Yes"
;
label define MV384J  
     0 "No"
     1 "Yes"
;
label define MV384K  
     0 "No"
     1 "Yes"
;
label define MV395   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "Don't know"
;
label define MV396   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "Don't know"
;
label define MV396A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV3A00Y 
     0 "No: knows a source"
     1 "Yes: knows no source"
;
label define MV3A00Z 
     0 "No"
     1 "Yes"
;
label define MV3A09B 
   998 "Don't know"
;
label define MV3B17  
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    20 "PRIVATE SECTOR"
    21 "Private hospital"
    30 "NGO"
    31 "NGO hospital"
    40 "OTHER SOURCE"
    96 "Other"
    98 "Don't know"
;
label define MV3B25A 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV3B25B 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV463A  
     0 "No"
     1 "Yes"
;
label define MV463B  
     0 "No"
     1 "Yes"
;
label define MV463C  
     0 "No"
     1 "Yes"
;
label define MV463D  
     0 "No"
     1 "Yes"
;
label define MV463E  
     0 "No"
     1 "Yes"
;
label define MV463F  
     0 "No"
     1 "Yes"
;
label define MV463G  
     0 "No"
     1 "Yes"
;
label define MV463X  
     0 "No"
     1 "Yes"
;
label define MV463Z  
     0 "No"
     1 "Yes, smokes nothing"
;
label define MV463AA 
     0 "Does not smoke"
     1 "Every day"
     2 "Some days"
;
label define MV463AB 
     0 "Does not smoke"
     1 "Every day"
     2 "Some days"
;
label define MV463AC 
     0 "No"
     1 "Yes"
;
label define MV463AD 
     0 "Does not smoke"
     1 "Every day"
     2 "Some days"
;
label define MV464   
    98 "Don't know"
;
label define MV464A  
     0 "Product not used"
   888 "Not every day"
;
label define MV464B  
     0 "Product not used"
   888 "Not every day"
;
label define MV464C  
     0 "Product not used"
   888 "Not every day"
;
label define MV464D  
     0 "Product not used"
   888 "Not every day"
;
label define MV464E  
     0 "Product not used"
   888 "Not every day"
;
label define MV464F  
     0 "Product not used"
   888 "Not every day"
;
label define MV464G  
     0 "Product not used"
   888 "Not every day"
;
label define MV464H  
     0 "Product not used"
   888 "Not every day"
;
label define MV464I  
     0 "Product not used"
   888 "Not every day"
;
label define MV464J  
     0 "Product not used"
   888 "Not every day"
;
label define MV464K  
     0 "Product not used"
   888 "Not every day"
;
label define MV464L  
     0 "Product not used"
   888 "Not every day"
;
label define MV477   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV478   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV479   
    10 "PUBLIC SECTOR"
    20 "PRIVATE SECTOR"
    30 "OTHER"
    96 "Other"
;
label define MV480   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV481   
     0 "No"
     1 "Yes"
;
label define MV481A  
     0 "No"
     1 "Yes"
;
label define MV481B  
     0 "No"
     1 "Yes"
;
label define MV481C  
     0 "No"
     1 "Yes"
;
label define MV481D  
     0 "No"
     1 "Yes"
;
label define MV481E  
     0 "No"
     1 "Yes"
;
label define MV481F  
     0 "No"
     1 "Yes"
;
label define MV481G  
     0 "No"
     1 "Yes"
;
label define MV481H  
     0 "No"
     1 "Yes"
;
label define MV481X  
     0 "No"
     1 "Yes"
;
label define MV482A  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV482B  
     0 "No"
     1 "Yes"
;
label define MV482C  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV483   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV483A  
    95 "During childhood <5 years"
    98 "Don't know"
;
label define MV483B  
     1 "Traditional practitioner / family friend"
     2 "Health worker / professional"
    96 "Other"
    98 "Don't know"
;
label define MV483C  
     1 "Health facility"
     2 "Home of a health worker / professional"
     3 "Circumcision done at home"
     4 "Ritual site"
    96 "Other home / place"
    98 "Don't know"
;
label define MV483D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV483E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV483F  
    95 "During childhood (<5 years)"
    98 "Don't know"
;
label define MV484A  
     0 "Product not used"
   888 "Not every week"
;
label define MV484B  
     0 "Product not used"
   888 "Not every week"
;
label define MV484C  
     0 "Product not used"
   888 "Not every week"
;
label define MV484D  
     0 "Product not used"
   888 "Not every week"
;
label define MV484E  
     0 "Product not used"
   888 "Not every week"
;
label define MV484F  
     0 "Product not used"
   888 "Not every week"
;
label define MV484G  
     0 "Product not used"
   888 "Not every week"
;
label define MV484H  
     0 "Product not used"
   888 "Not every week"
;
label define MV484I  
     0 "Product not used"
   888 "Not every week"
;
label define MV484J  
     0 "Product not used"
   888 "Not every week"
;
label define MV484K  
     0 "Product not used"
   888 "Not every week"
;
label define MV484L  
     0 "Product not used"
   888 "Not every week"
;
label define MV485A  
     0 "Did not have even one drink"
    95 "Every day/almost every day"
    96 "Never have consumed alcohol"
;
label define MV485B  
    99 "Missing"
;
label define MV501   
     0 "Never in union"
     1 "Married"
     2 "Living with partner"
     3 "Widowed"
     4 "Divorced"
     5 "No longer living together/separated"
;
label define MV502   
     0 "Never in union"
     1 "Currently in union/living with a woman"
     2 "Formerly in union/living with a woman"
;
label define MV503   
     1 "Once"
     2 "More than once"
;
label define MV504   
     1 "Living with him"
     2 "Staying elsewhere"
;
label define MV505   
    99 "Missing"
;
label define MV510   
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define MV513   
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define MV525   
     0 "Not had sex"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV527   
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV528   
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV529   
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV531   
     0 "Not had sex"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV532   
     0 "No flag"
     1 "After interview"
     2 "After conception >= 1 year"
     3 "After conception < 1 year"
     4 "At marriage, but never married"
     5 "At marriage, but after conception"
     6 "After marriage"
;
label define MV535   
     0 "No"
     1 "Formerly married"
     2 "Formerly lived with a woman"
     3 "Both, formerly married and lived with a woman"
;
label define MV536   
     0 "Never had sex"
     1 "Active in last 4 weeks"
     3 "Not active in last 4 weeks"
;
label define MV541   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV602   
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized (respondent)"
     5 "Declared infecund (respondent or partner(s))"
     6 "Never had sex"
     7 "Man declared infecund"
     8 "Man has no partner"
;
label define MV603   
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon, now"
   996 "Other, non-numeric"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV604   
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
;
label define MV605   
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized (respondent or partner(s))"
     7 "Declared infecund (respondent or partner(s))"
     8 "Never had sex"
;
label define MV613   
    96 "Non-numeric response"
    98 "Don't know"
;
label define MV614   
     6 "6+"
     7 "Non-numeric response"
;
label define MV616   
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "Don't know"
;
label define MV621   
     1 "Both want same"
     2 "Wife wants more"
     3 "Wife wants fewer"
     8 "Don't know"
;
label define MV627   
    96 "Other"
    98 "Don't know"
;
label define MV628   
    96 "Other"
    98 "Don't know"
;
label define MV629   
    96 "Other"
    98 "Don't know"
;
label define MV631   
     1 "Big problem"
     2 "Small problem"
     3 "No problem"
     4 "Says she can't get pregnant/not having sex"
;
label define MV633A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV634A  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634B  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634C  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634D  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV714   
     0 "No"
     1 "Yes"
;
label define MV714A  
     0 "No"
     1 "Yes"
;
label define MV716   
     0 "Not working and didn't work in last 12 months"
     1 "Professional, Technical and Related Workers"
     2 "Administrative and Managerial Workers"
     3 "Office/Administrative Support Workers"
     4 "Sales and Related Workers"
     5 "Service Workers"
     6 "Installations, Maintenance and Repair Workers"
     7 "Agricultural, Animal Husbandry, Forestry, Fishermen/Hunters"
     8 "Production, Construction and Extractions Workers"
     9 "Transportation and Material Moving Workers"
    96 "Other"
;
label define MV717   
     0 "Not working"
     1 "Professional/technical/managerial"
     2 "Clerical"
     3 "Sales"
     4 "Agriculture - self employed"
     5 "Agriculture - employee"
     6 "Household and domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    96 "Other"
    98 "Don't know"
;
label define MV719   
     1 "For family member"
     2 "For someone else"
     3 "Self-employed"
;
label define MV721   
     1 "At home"
     2 "Away"
;
label define MV731   
     0 "No"
     1 "In the past year"
     2 "Currently working"
;
label define MV732   
     1 "All year"
     2 "Seasonal"
     3 "Occasional"
;
label define MV739   
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
;
label define MV740   
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
;
label define MV741   
     0 "Not paid"
     1 "Cash only"
     2 "Cash and in-kind"
     3 "In-kind only"
;
label define MV743A  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Other"
     8 "Don't know/depends"
;
label define MV743B  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Other"
     8 "Don't know/depends"
;
label define MV743C  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743D  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743E  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743F  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743G  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV744A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV745A  
     0 "Does not own"
     1 "Alone only"
     2 "Jointly with wife/partner only"
     3 "Jointly with someone else only"
     4 "Jointly with wife/partner and someone else"
     5 "Both alone and jointly"
;
label define MV745B  
     0 "Does not own"
     1 "Alone only"
     2 "Jointly with wife/partner only"
     3 "Jointly with someone else only"
     4 "Jointly with wife/partner and someone else"
     5 "Both alone and jointly"
;
label define MV745C  
     0 "Does not have a title deed"
     1 "Has a title deed and respondent on title"
     2 "Has a title deed but respondent not on title"
     3 "Has a title deed, don't know if respondent on title"
     8 "Don't know if has a title deed"
;
label define MV745D  
     0 "Does not have a title deed"
     1 "Has a title deed and respondent on title"
     2 "Has a title deed but respondent not on title"
     3 "Has a title deed, don't know if respondent on title"
     8 "Don't know if has a title deed"
;
label define MV747A  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV747B  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MD121   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV750   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV751   
     0 "No"
     1 "Yes"
;
label define MV754BP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754CP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754DP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754JP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754WP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV756   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV762   
    10 "---PUBLIC SECTOR---"
    11 "Teaching hospital"
    12 "Federal medical center"
    13 "General hospital"
    14 "Primary health care center"
    15 "Primary health clinic"
    16 "Health post"
    17 "Other public sector"
    20 "---PRIVATE MEDICAL SECTOR---"
    21 "Private hospital"
    22 "Private clinic"
    23 "Pharmacy"
    24 "Patent and Proprietary medicine vendors (PPMV)"
    25 "Private doctor"
    26 "Mobile clinic"
    27 "Maternity center"
    28 "Other private medical"
    30 "---NGO MEDICAL SECTOR---"
    31 "Faith-based hospital"
    32 "Faith-based clinic"
    33 "Family planning clinic"
    36 "Other NGO medical sector"
    40 "---OTHER SOURCE---"
    41 "Shop"
    42 "Church"
    43 "Friend/relative"
    96 "Other"
    98 "Don't know"
;
label define MV762A  
     1 "Gold Circle"
     2 "Durex"
     3 "Rough Rider"
     4 "Twin Lotus"
     5 "Plain Condom"
     6 "Go Flex"
     7 "Kiss"
    96 "Other"
    98 "Don't know"
;
label define MV763A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV766A  
    98 "Don't know"
;
label define MV766B  
    95 "95+"
    98 "Unknown"
;
label define MV767A  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767B  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767C  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV768A  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768B  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768C  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV770   
     0 "No"
     1 "Yes"
;
label define MV770A  
     0 "No"
     1 "Yes"
;
label define MV770B  
     0 "No"
     1 "Yes"
;
label define MV770C  
     0 "No"
     1 "Yes"
;
label define MV770D  
     0 "No"
     1 "Yes"
;
label define MV770E  
     0 "No"
     1 "Yes"
;
label define MV770F  
     0 "No"
     1 "Yes"
;
label define MV770G  
     0 "No"
     1 "Yes"
;
label define MV770H  
     0 "No"
     1 "Yes"
;
label define MV770I  
     0 "No"
     1 "Yes"
;
label define MV770K  
     0 "No"
     1 "Yes"
;
label define MV770L  
     0 "No"
     1 "Yes"
;
label define MV770M  
     0 "No"
     1 "Yes"
;
label define MV770N  
     0 "No"
     1 "Yes"
;
label define MV770O  
     0 "No"
     1 "Yes"
;
label define MV770P  
     0 "No"
     1 "Yes"
;
label define MV770Q  
     0 "No"
     1 "Yes"
;
label define MV770R  
     0 "No"
     1 "Yes"
;
label define MV770S  
     0 "No"
     1 "Yes"
;
label define MV770T  
     0 "No"
     1 "Yes"
;
label define MV770NA 
     0 "No"
     1 "Yes"
;
label define MV770NB 
     0 "No"
     1 "Yes"
;
label define MV770NC 
     0 "No"
     1 "Yes"
;
label define MV770ND 
     0 "No"
     1 "Yes"
;
label define MV770X  
     0 "No"
     1 "Yes"
;
label define MV770U  
     0 "No"
     1 "Yes"
;
label define MV774A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV774B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV774C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV775   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV777   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV777A  
     0 "Disagree"
     1 "Agree"
     8 "Don't know/not sure/depends"
;
label define MV778   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV779   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV780   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV781   
     0 "No"
     1 "Yes"
;
label define MV783   
     0 "No"
     1 "Yes"
;
label define MV784A  
     0 "No"
     1 "Yes"
;
label define MV784B  
     0 "No"
     1 "Yes"
;
label define MV784C  
     0 "No"
     1 "Yes"
;
label define MV784D  
     0 "No"
     1 "Yes"
;
label define MV784E  
     0 "No"
     1 "Yes"
;
label define MV784F  
     0 "No"
     1 "Yes"
;
label define MV784G  
     0 "No"
     1 "Yes"
;
label define MV784H  
     0 "No"
     1 "Yes"
;
label define MV784I  
     0 "No"
     1 "Yes"
;
label define MV784J  
     0 "No"
     1 "Yes"
;
label define MV784K  
     0 "No"
     1 "Yes"
;
label define MV784L  
     0 "No"
     1 "Yes"
;
label define MV784M  
     0 "No"
     1 "Yes"
;
label define MV784N  
     0 "No"
     1 "Yes"
;
label define MV784O  
     0 "No"
     1 "Yes"
;
label define MV784P  
     0 "No"
     1 "Yes"
;
label define MV784Q  
     0 "No"
     1 "Yes"
;
label define MV784R  
     0 "No"
     1 "Yes"
;
label define MV784S  
     0 "No"
     1 "Yes"
;
label define MV784T  
     0 "No"
     1 "Yes"
;
label define MV784U  
     0 "No"
     1 "Yes"
;
label define MV784V  
     0 "No"
     1 "Yes"
;
label define MV784X  
     0 "No"
     1 "Yes"
;
label define MV785   
     0 "No"
     1 "Yes"
;
label define MV791   
     0 "No"
     1 "Yes"
;
label define MV791A  
     0 "No"
     1 "Yes"
;
label define MV791B  
     0 "No"
     1 "Yes"
;
label define MV793   
     0 "No"
     1 "Yes"
;
label define MV793A  
     0 "No"
     1 "Yes"
;
label define MV793B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV820   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV822   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV823   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV824   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV825   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV826   
     1 "Less than 12 months"
     2 "12-23 months"
     3 "2 years or more"
;
label define MV826A  
    96 "Eight or more years"
    98 "Don't know"
;
label define MV827   
     1 "Asked for the test"
     2 "Offered and accepted"
     3 "Required"
;
label define MV828   
     0 "No"
     1 "Yes"
;
label define MV829   
    10 "---PUBLIC SECTOR---"
    11 "Teaching hospital"
    12 "Federal medical center"
    13 "General hospital"
    14 "Primary health care center"
    15 "Primary health clinic"
    16 "Health post"
    17 "Stand-alone HTC center"
    18 "Mobile HTC services"
    19 "Other public sector"
    20 "---PRIVATE MEDICAL SECTOR---"
    21 "Private hospital"
    22 "Private clinic"
    23 "Pharmacy"
    24 "Patent and Proprietary medicine vendors (PPMV)"
    25 "Private doctor"
    26 "Mobile clinic"
    27 "Stand-alone HTC center"
    28 "Mobile HTC services"
    29 "Other private medical"
    30 "---NGO MEDICAL SECTOR---"
    31 "Faith-based hospital"
    32 "Faith-based clinic"
    33 "Family planning clinic"
    36 "Other NGO medical sector"
    40 "---OTHER SOURCE---"
    41 "Home"
    42 "Workplace"
    43 "Correctional facility"
    96 "Other"
    98 "Don't know"
;
label define MV832B  
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV832C  
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV833A  
     0 "No"
     1 "Yes"
;
label define MV833B  
     0 "No"
     1 "Yes"
;
label define MV833C  
     0 "No"
     1 "Yes"
;
label define MV834A  
    95 "95+"
    98 "Don't know"
;
label define MV834B  
    95 "95+"
    98 "Don't know"
;
label define MV834C  
    95 "95+"
    98 "Don't know"
;
label define MV835A  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835B  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835C  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV836   
    95 "95+"
    98 "Don't know"
;
label define MV837   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV852A  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV852B  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV852C  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV853A  
    95 "95+"
    98 "Don't know"
;
label define MV853B  
    95 "95+"
    98 "Don't know"
;
label define MV853C  
    95 "95+"
    98 "Don't know"
;
label define MV856   
     0 "Never heard of HIV test kits"
     1 "Has tested with HIV test kits"
     2 "Knows test kits but never tested with them"
     3 "Knows test kits un-known if tested"
;
label define MV857A  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV857B  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV857C  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV857D  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV858   
     0 "No"
     1 "Yes"
     2 "Says he has HIV"
     8 "Don't know/not sure/depends"
;
label define MV859   
     0 "Haven't heard"
     1 "Heard and approve to take it every day"
     2 "Heard, but don't approve to take it every day"
     3 "Heard, but not sure about approving its use"
;
label define MV860M  
    98 "Don't know"
;
label define MV860Y  
  9998 "Don't know"
;
label define MV860C  
  9998 "Don't know"
;
label define MV861   
     1 "Positive"
     2 "Negative"
     3 "Indeterminate"
     4 "Declined to answer"
     5 "Did not receive test result"
;
label define MV862M  
    95 "Same as most recent"
    98 "Don't know"
;
label define MV862Y  
  9995 "Same as most recent"
  9998 "Don't know"
;
label define MV862C  
  9998 "Don't know"
;
label define MV863   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV864   
    95 "95+"
;
label define MV865   
     0 "No"
     1 "Yes"
;
label define MV866   
     0 "Disagree"
     1 "Agree"
;
label define MV867A  
     0 "No"
     1 "Yes"
;
label define MV867B  
     0 "No"
     1 "Yes"
;
label define MV867C  
     0 "No"
     1 "Yes"
;
label define MV867D  
     0 "No"
     1 "Yes"
;
label define MV867E  
     0 "No"
     1 "Yes"
;
label define MV867F  
     0 "No"
     1 "Yes"
;
label define MV867G  
     0 "No"
     1 "Yes"
;
label define MG100   
     0 "No"
     1 "Yes"
;
label define MG101   
     0 "No"
     1 "Yes"
;
label define MG117A  
     0 "No"
     1 "Yes"
;
label define MG117B  
     0 "No"
     1 "Yes"
;
label define MG117C  
     0 "No"
     1 "Yes"
;
label define MG117D  
     0 "No"
     1 "Yes"
;
label define MG117E  
     0 "No"
     1 "Yes"
;
label define MG117F  
     0 "No"
     1 "Yes"
;
label define MG117G  
     0 "No"
     1 "Yes"
;
label define MG117H  
     0 "No"
     1 "Yes"
;
label define MG117I  
     0 "No"
     1 "Yes"
;
label define MG117J  
     0 "No"
     1 "Yes"
;
label define MG117X  
     0 "No"
     1 "Yes"
;
label define MG117Y  
     0 "No"
     1 "Yes"
;
label define MG118   
     0 "No"
     1 "Yes"
     3 "No religion"
     8 "Don't know"
;
label define MG119   
     1 "Continued"
     2 "Stopped"
     3 "Depends"
     8 "Don't know"
;
label define MCHD01  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MCHD02  
     0 "No"
     1 "Yes"
;
label define MCHD03  
     0 "No"
     1 "Yes"
;
label define MCHD04  
     0 "No"
     1 "Yes"
;
label define MCHD05  
     0 "No"
     1 "Yes"
;
label define MCHD06  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MCHD07  
     0 "No"
     1 "Yes"
;
label define MCHD08  
     0 "No"
     1 "Yes"
;
label define MCHD09  
     0 "No"
     1 "Yes"
;
label define MCHD10  
     0 "No"
     1 "Yes"
;
label define SM107   
     1 "FCT-Abuja"
     2 "Benue"
     3 "Kogi"
     4 "Kwara"
     5 "Nasarawa"
     6 "Niger"
     7 "Plateau"
     8 "Adamawa"
     9 "Bauchi"
    10 "Borno"
    11 "Gombe"
    12 "Taraba"
    13 "Yobe"
    14 "Jigawa"
    15 "Kaduna"
    16 "Kano"
    17 "Katsina"
    18 "Kebbi"
    19 "Sokoto"
    20 "Zamfara"
    21 "Abia"
    22 "Anambra"
    23 "Ebonyi"
    24 "Enugu"
    25 "Imo"
    26 "Akwa Ibom"
    27 "Bayelsa"
    28 "Cross River"
    29 "Delta"
    30 "Edo"
    31 "Rivers"
    32 "Ekiti"
    33 "Lagos"
    34 "Ogun"
    35 "Ondo"
    36 "Osun"
    37 "Oyo"
    96 "Abroad"
;
label define SM114   
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define SM115   
     0 "Less than one class"
     1 "Class 1"
     2 "Class 2"
     3 "Class 3"
     4 "Class 4"
     5 "Class 5"
     6 "Class 6"
     7 "Class 7"
     8 "Class 8"
;
label define SMSTATE 
     1 "Sokoto"
     2 "Zamfara"
     3 "Katsina"
     4 "Jigawa"
     5 "Yobe"
     6 "Borno"
     7 "Adamawa"
     8 "Gombe"
     9 "Bauchi"
    10 "Kano"
    11 "Kaduna"
    12 "Kebbi"
    13 "Niger"
    14 "FCT"
    15 "Nasarawa"
    16 "Plateau"
    17 "Taraba"
    18 "Benue"
    19 "Kogi"
    20 "Kwara"
    21 "Oyo"
    22 "Osun"
    23 "Ekiti"
    24 "Ondo"
    25 "Edo"
    26 "Anambra"
    27 "Enugu"
    28 "Ebonyi"
    29 "Cross river"
    30 "Akwa ibom"
    31 "Abia"
    32 "Imo"
    33 "Rivers"
    34 "Bayelsa"
    35 "Delta"
    36 "Lagos"
    37 "Ogun"
    96 "Abroad"
;
label define SMZONE  
     1 "North central"
     2 "North east"
     3 "North west"
     4 "South east"
     5 "South south"
     6 "South west"
;
label define SMSTATE1
     1 "FCT-Abuja"
     2 "Benue"
     3 "Kogi"
     4 "Kwara"
     5 "Nasarawa"
     6 "Niger"
     7 "Plateau"
     8 "Adamawa"
     9 "Bauchi"
    10 "Borno"
    11 "Gombe"
    12 "Taraba"
    13 "Yobe"
    14 "Jigawa"
    15 "Kaduna"
    16 "Kano"
    17 "Katsina"
    18 "Kebbi"
    19 "Sokoto"
    20 "Zamfara"
    21 "Abia"
    22 "Anambra"
    23 "Ebonyi"
    24 "Enugu"
    25 "Imo"
    26 "Akwa Ibom"
    27 "Bayelsa"
    28 "Cross River"
    29 "Delta"
    30 "Edo"
    31 "Rivers"
    32 "Ekiti"
    33 "Lagos"
    34 "Ogun"
    35 "Ondo"
    36 "Osun"
    37 "Oyo"
;
label define SM302BA 
     0 "No"
     1 "Yes"
;
label define SM302BB 
     0 "No"
     1 "Yes"
;
label define SM302BC 
     0 "No"
     1 "Yes"
;
label define SM302BD 
     0 "No"
     1 "Yes"
;
label define SM302BE 
     0 "No"
     1 "Yes"
;
label define SM302BX 
     0 "No"
     1 "Yes"
;
label define SM813A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813BA 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813BB 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813BC 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813BD 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813BE 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813BF 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813BX 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813BZ 
     0 "No"
     1 "Yes"
;
label define SM813CA 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813CB 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813CC 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813CD 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813CE 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813CF 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813CG 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813CH 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813CI 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813CJ 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813CX 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813CZ 
     0 "No"
     1 "Yes"
;
label define SM813D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM813FA 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define SM813FB 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define SM813FC 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define SM813FD 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define SM813FE 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define SM813FF 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define SM816A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816C  
     0 "Negative"
     1 "Positive"
     8 "Don't know"
;
label define SM816D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816EA 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816EB 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816EC 
     0 "Negative"
     1 "Positive"
     8 "Don't know"
;
label define SM816ED 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816GA 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816GB 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816GC 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816GD 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816GE 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816GF 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816GG 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816GH 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816GI 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816GJ 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816GX 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816GZ 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816HA 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816HB 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816HC 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816HD 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816HE 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816HF 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816HG 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816HH 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816HX 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816HZ 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816IA 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816IB 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816IC 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816ID 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816IE 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816IF 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816IG 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816IX 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816IZ 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816JA 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816JB 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816JC 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816JD 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816JE 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816JF 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816JG 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816JH 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816JI 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816JX 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816JZ 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816K  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816L  
     1 "Pfizer"
     2 "Astrazeneca/Oxford"
     3 "Moderna"
     4 "Johnson & Johnson"
     8 "Don't know"
;
label define SM816M  
     1 "One dose"
     2 "Two doses"
     3 "More than 2 doses"
     8 "Don't know"
;
label define SM816N  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816O  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816P  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816Q  
    10 "---PUBLIC SECTOR---"
    11 "Teaching hospital"
    12 "Federal medical center"
    13 "General hospital"
    14 "Primary health care center"
    15 "Primary health clinic"
    16 "Health post"
    17 "Other public sector"
    20 "---PRIVATE MEDICAL SECTOR---"
    21 "Private hospital"
    22 "Private clinic"
    23 "Pharmacy"
    24 "Patent and Proprietary medicine vendors (PPMV)"
    25 "Private doctor"
    26 "Mobile clinic"
    27 "Maternity center"
    28 "Other private medical"
    30 "---NGO MEDICAL SECTOR---"
    31 "Faith-based hospital"
    32 "Faith-based clinic"
    36 "Other NGO medical sector"
    40 "---OTHER SOURCE---"
    41 "Shop"
    42 "Church"
    43 "Friend/relative"
    96 "Other"
;
label define SM816R  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SML101  
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define SML901  
     0 "No"
     1 "Yes"
;
label define SML901A 
     0 "No"
     1 "Yes"
;
label define SML901B 
     0 "No"
     1 "Yes"
;
label define SML901C 
     0 "No"
     1 "Yes"
;
label define SML901D 
     0 "No"
     1 "Yes"
;
label define SML901E 
     0 "No"
     1 "Yes"
;
label define SML901F 
     0 "No"
     1 "Yes"
;
label define SML901G 
     0 "No"
     1 "Yes"
;
label define SML901H 
     0 "No"
     1 "Yes"
;
label define SML901I 
     0 "No"
     1 "Yes"
;
label define SML901X 
     0 "No"
     1 "Yes"
;
label define SML901Z 
     0 "No"
     1 "Yes"
;
label define SML903  
     0 "No"
     1 "Yes"
;
label define SML903A 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SML903B 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SML903C 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SML903D 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SML903E 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SML903F 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SML903G 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SML903H 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SML903X 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SML903Z 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SML905  
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define SML906  
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define SML907  
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define SML908  
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define SML909  
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define SML910  
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define SML911  
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define SML912  
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define SML913  
     0 "Disagree/less than half"
     1 "Agree/more than half"
     8 "Don't know/uncertain"
;
label define SML914  
     0 "Disagree/less than half"
     1 "Agree/more than half"
     8 "Don't know/uncertain"
;

#delimit cr
label values mv013    MV013   
label values mv014    MV014   
label values mv015    MV015   
label values mv022    MV022   
label values mv023    MV023   
label values mv024    MV024   
label values mv025    MV025   
label values mv026    MV026   
label values mv034_1  MV034   
label values mv034_2  MV034   
label values mv034_3  MV034   
label values mv034_4  MV034   
label values mv034_5  MV034   
label values mv034_6  MV034   
label values mv034_7  MV034   
label values mv034_8  MV034   
label values mv034a_1 MV034A  
label values mv034a_2 MV034A  
label values mv034a_3 MV034A  
label values mv034a_4 MV034A  
label values mv034a_5 MV034A  
label values mv034a_6 MV034A  
label values mv034a_7 MV034A  
label values mv034a_8 MV034A  
label values mv034b_1 MV034B  
label values mv034b_2 MV034B  
label values mv034b_3 MV034B  
label values mv034b_4 MV034B  
label values mv034b_5 MV034B  
label values mv034b_6 MV034B  
label values mv034b_7 MV034B  
label values mv034b_8 MV034B  
label values mv035    MV035   
label values mv045a   MV045A  
label values mv045b   MV045B  
label values mv045c   MV045C  
label values mv046    MV046   
label values mv803    MV803   
label values mv101    MV101   
label values mv102    MV102   
label values mv103    MV103   
label values mv104    MV104   
label values mv105    MV105   
label values mv105a   MV105A  
label values mv106    MV106   
label values mv107    MV107   
label values mv130    MV130   
label values mv131    MV131   
label values mv133    MV133   
label values mv134    MV134   
label values mv135    MV135   
label values mv149    MV149   
label values mv150    MV150   
label values mv151    MV151   
label values mv152    MV152   
label values mv155    MV155   
label values mv156    MV156   
label values mv157    MV157   
label values mv158    MV158   
label values mv159    MV159   
label values mv167    MV167   
label values mv168    MV168   
label values mv169a   MV169A  
label values mv169b   MV169B  
label values mv169c   MV169C  
label values mv170    MV170   
label values mv171a   MV171A  
label values mv171b   MV171B  
label values mv172    MV172   
label values mv173    MV173   
label values mv174m   MV174M  
label values mv174y   MV174Y  
label values mv175    MV175   
label values mv176    MV176   
label values mv177    MV177   
label values mv190    MV190   
label values mv190a   MV190A  
label values mv213    MV213   
label values mv217    MV217   
label values mv225    MV225   
label values mv245    MV245   
label values mv246    MV246   
label values mv248    MV248   
label values mv249    MV249   
label values mv250    MV250   
label values mv251    MV251   
label values mv252    MV252   
label values mv253    MV253   
label values mv301    MV301   
label values mv302    MV302   
label values m304a_01 M304A   
label values m304a_02 M304A   
label values m304a_03 M304A   
label values m304a_04 M304A   
label values m304a_05 M304A   
label values m304a_06 M304A   
label values m304a_07 M304A   
label values m304a_08 M304A   
label values m304a_09 M304A   
label values m304a_10 M304A   
label values m304a_11 M304A   
label values m304a_12 M304A   
label values m304a_13 M304A   
label values m304a_14 M304A   
label values m304a_15 M304A   
label values m304a_16 M304A   
label values m304a_17 M304A   
label values m304a_18 M304A   
label values m304a_19 M304A   
label values m304a_20 M304A   
label values mv304_01 MV304   
label values mv304_02 MV304   
label values mv304_03 MV304   
label values mv304_04 MV304   
label values mv304_05 MV304   
label values mv304_06 MV304   
label values mv304_07 MV304   
label values mv304_08 MV304   
label values mv304_09 MV304   
label values mv304_10 MV304   
label values mv304_11 MV304   
label values mv304_12 MV304   
label values mv304_13 MV304   
label values mv304_14 MV304   
label values mv304_15 MV304   
label values mv304_16 MV304   
label values mv304_17 MV304   
label values mv304_18 MV304   
label values mv304_19 MV304   
label values mv304_20 MV304   
label values mv305_01 MV305   
label values mv305_02 MV305   
label values mv305_03 MV305   
label values mv305_04 MV305   
label values mv305_05 MV305   
label values mv305_06 MV305   
label values mv305_07 MV305   
label values mv305_08 MV305   
label values mv305_09 MV305   
label values mv305_10 MV305   
label values mv305_11 MV305   
label values mv305_12 MV305   
label values mv305_13 MV305   
label values mv305_14 MV305   
label values mv305_15 MV305   
label values mv305_16 MV305   
label values mv305_17 MV305   
label values mv305_18 MV305   
label values mv305_19 MV305   
label values mv305_20 MV305   
label values mv307_01 MV307   
label values mv307_02 MV307   
label values mv307_03 MV307   
label values mv307_04 MV307   
label values mv307_05 MV307   
label values mv307_06 MV307   
label values mv307_07 MV307   
label values mv307_08 MV307   
label values mv307_09 MV307   
label values mv307_10 MV307   
label values mv307_11 MV307   
label values mv307_12 MV307   
label values mv307_13 MV307   
label values mv307_14 MV307   
label values mv307_15 MV307   
label values mv307_16 MV307   
label values mv307_17 MV307   
label values mv307_18 MV307   
label values mv307_19 MV307   
label values mv307_20 MV307   
label values mv312    MV312   
label values mv312a   MV312A  
label values mv313    MV313   
label values mv323a   MV323A  
label values mv325b   MV325B  
label values mv372a   MV372A  
label values mv384a   MV384A  
label values mv384b   MV384B  
label values mv384c   MV384C  
label values mv384d   MV384D  
label values mv384e   MV384E  
label values mv384f   MV384F  
label values mv384g   MV384G  
label values mv384h   MV384H  
label values mv384i   MV384I  
label values mv384j   MV384J  
label values mv384k   MV384K  
label values mv395    MV395   
label values mv396    MV396   
label values mv396a   MV396A  
label values mv3a00y  MV3A00Y 
label values mv3a00z  MV3A00Z 
label values mv3a09b  MV3A09B 
label values mv3b17   MV3B17  
label values mv3b25a  MV3B25A 
label values mv3b25b  MV3B25B 
label values mv463a   MV463A  
label values mv463b   MV463B  
label values mv463c   MV463C  
label values mv463d   MV463D  
label values mv463e   MV463E  
label values mv463f   MV463F  
label values mv463g   MV463G  
label values mv463x   MV463X  
label values mv463z   MV463Z  
label values mv463aa  MV463AA 
label values mv463ab  MV463AB 
label values mv463ac  MV463AC 
label values mv463ad  MV463AD 
label values mv464    MV464   
label values mv464a   MV464A  
label values mv464b   MV464B  
label values mv464c   MV464C  
label values mv464d   MV464D  
label values mv464e   MV464E  
label values mv464f   MV464F  
label values mv464g   MV464G  
label values mv464h   MV464H  
label values mv464i   MV464I  
label values mv464j   MV464J  
label values mv464k   MV464K  
label values mv464l   MV464L  
label values mv477    MV477   
label values mv478    MV478   
label values mv479    MV479   
label values mv480    MV480   
label values mv481    MV481   
label values mv481a   MV481A  
label values mv481b   MV481B  
label values mv481c   MV481C  
label values mv481d   MV481D  
label values mv481e   MV481E  
label values mv481f   MV481F  
label values mv481g   MV481G  
label values mv481h   MV481H  
label values mv481x   MV481X  
label values mv482a   MV482A  
label values mv482b   MV482B  
label values mv482c   MV482C  
label values mv483    MV483   
label values mv483a   MV483A  
label values mv483b   MV483B  
label values mv483c   MV483C  
label values mv483d   MV483D  
label values mv483e   MV483E  
label values mv483f   MV483F  
label values mv484a   MV484A  
label values mv484b   MV484B  
label values mv484c   MV484C  
label values mv484d   MV484D  
label values mv484e   MV484E  
label values mv484f   MV484F  
label values mv484g   MV484G  
label values mv484h   MV484H  
label values mv484i   MV484I  
label values mv484j   MV484J  
label values mv484k   MV484K  
label values mv484l   MV484L  
label values mv485a   MV485A  
label values mv501    MV501   
label values mv502    MV502   
label values mv503    MV503   
label values mv504    MV504   
label values mv510    MV510   
label values mv513    MV513   
label values mv525    MV525   
label values mv527    MV527   
label values mv528    MV528   
label values mv529    MV529   
label values mv531    MV531   
label values mv532    MV532   
label values mv535    MV535   
label values mv536    MV536   
label values mv541    MV541   
label values mv602    MV602   
label values mv603    MV603   
label values mv604    MV604   
label values mv605    MV605   
label values mv613    MV613   
label values mv614    MV614   
label values mv616    MV616   
label values mv621    MV621   
label values mv627    MV627   
label values mv628    MV628   
label values mv629    MV629   
label values mv631    MV631   
label values mv633a   MV633A  
label values mv633b   MV633B  
label values mv633c   MV633C  
label values mv633d   MV633D  
label values mv633e   MV633E  
label values mv633f   MV633F  
label values mv633g   MV633G  
label values mv634a   MV634A  
label values mv634b   MV634B  
label values mv634c   MV634C  
label values mv634d   MV634D  
label values mv714    MV714   
label values mv714a   MV714A  
label values mv716    MV716   
label values mv717    MV717   
label values mv719    MV719   
label values mv721    MV721   
label values mv731    MV731   
label values mv732    MV732   
label values mv739    MV739   
label values mv740    MV740   
label values mv741    MV741   
label values mv743a   MV743A  
label values mv743b   MV743B  
label values mv743c   MV743C  
label values mv743d   MV743D  
label values mv743e   MV743E  
label values mv743f   MV743F  
label values mv743g   MV743G  
label values mv744a   MV744A  
label values mv744b   MV744B  
label values mv744c   MV744C  
label values mv744d   MV744D  
label values mv744e   MV744E  
label values mv745a   MV745A  
label values mv745b   MV745B  
label values mv745c   MV745C  
label values mv745d   MV745D  
label values mv747a   MV747A  
label values mv747b   MV747B  
label values md121    MD121   
label values mv750    MV750   
label values mv751    MV751   
label values mv754bp  MV754BP 
label values mv754cp  MV754CP 
label values mv754dp  MV754DP 
label values mv754jp  MV754JP 
label values mv754wp  MV754WP 
label values mv756    MV756   
label values mv761    MV761   
label values mv761b   MV761B  
label values mv761c   MV761C  
label values mv762    MV762   
label values mv762a   MV762A  
label values mv763a   MV763A  
label values mv763b   MV763B  
label values mv763c   MV763C  
label values mv763d   MV763D  
label values mv763e   MV763E  
label values mv763f   MV763F  
label values mv763g   MV763G  
label values mv766a   MV766A  
label values mv766b   MV766B  
label values mv767a   MV767A  
label values mv767b   MV767B  
label values mv767c   MV767C  
label values mv768a   MV768A  
label values mv768b   MV768B  
label values mv768c   MV768C  
label values mv770    MV770   
label values mv770a   MV770A  
label values mv770b   MV770B  
label values mv770c   MV770C  
label values mv770d   MV770D  
label values mv770e   MV770E  
label values mv770f   MV770F  
label values mv770g   MV770G  
label values mv770h   MV770H  
label values mv770i   MV770I  
label values mv770k   MV770K  
label values mv770l   MV770L  
label values mv770m   MV770M  
label values mv770n   MV770N  
label values mv770o   MV770O  
label values mv770p   MV770P  
label values mv770q   MV770Q  
label values mv770r   MV770R  
label values mv770s   MV770S  
label values mv770t   MV770T  
label values mv770na  MV770NA 
label values mv770nb  MV770NB 
label values mv770nc  MV770NC 
label values mv770nd  MV770ND 
label values mv770x   MV770X  
label values mv770u   MV770U  
label values mv774a   MV774A  
label values mv774b   MV774B  
label values mv774c   MV774C  
label values mv775    MV775   
label values mv777    MV777   
label values mv777a   MV777A  
label values mv778    MV778   
label values mv779    MV779   
label values mv780    MV780   
label values mv781    MV781   
label values mv783    MV783   
label values mv784a   MV784A  
label values mv784b   MV784B  
label values mv784c   MV784C  
label values mv784d   MV784D  
label values mv784e   MV784E  
label values mv784f   MV784F  
label values mv784g   MV784G  
label values mv784h   MV784H  
label values mv784i   MV784I  
label values mv784j   MV784J  
label values mv784k   MV784K  
label values mv784l   MV784L  
label values mv784m   MV784M  
label values mv784n   MV784N  
label values mv784o   MV784O  
label values mv784p   MV784P  
label values mv784q   MV784Q  
label values mv784r   MV784R  
label values mv784s   MV784S  
label values mv784t   MV784T  
label values mv784u   MV784U  
label values mv784v   MV784V  
label values mv784x   MV784X  
label values mv785    MV785   
label values mv791    MV791   
label values mv791a   MV791A  
label values mv791b   MV791B  
label values mv793    MV793   
label values mv793a   MV793A  
label values mv793b   MV793B  
label values mv820    MV820   
label values mv822    MV822   
label values mv823    MV823   
label values mv824    MV824   
label values mv825    MV825   
label values mv826    MV826   
label values mv826a   MV826A  
label values mv827    MV827   
label values mv828    MV828   
label values mv829    MV829   
label values mv832b   MV832B  
label values mv832c   MV832C  
label values mv833a   MV833A  
label values mv833b   MV833B  
label values mv833c   MV833C  
label values mv834a   MV834A  
label values mv834b   MV834B  
label values mv834c   MV834C  
label values mv835a   MV835A  
label values mv835b   MV835B  
label values mv835c   MV835C  
label values mv836    MV836   
label values mv837    MV837   
label values mv852a   MV852A  
label values mv852b   MV852B  
label values mv852c   MV852C  
label values mv853a   MV853A  
label values mv853b   MV853B  
label values mv853c   MV853C  
label values mv856    MV856   
label values mv857a   MV857A  
label values mv857b   MV857B  
label values mv857c   MV857C  
label values mv857d   MV857D  
label values mv858    MV858   
label values mv859    MV859   
label values mv860m   MV860M  
label values mv860y   MV860Y  
label values mv860c   MV860C  
label values mv861    MV861   
label values mv862m   MV862M  
label values mv862y   MV862Y  
label values mv862c   MV862C  
label values mv863    MV863   
label values mv864    MV864   
label values mv865    MV865   
label values mv866    MV866   
label values mv867a   MV867A  
label values mv867b   MV867B  
label values mv867c   MV867C  
label values mv867d   MV867D  
label values mv867e   MV867E  
label values mv867f   MV867F  
label values mv867g   MV867G  
label values mg100    MG100   
label values mg101    MG101   
label values mg117a   MG117A  
label values mg117b   MG117B  
label values mg117c   MG117C  
label values mg117d   MG117D  
label values mg117e   MG117E  
label values mg117f   MG117F  
label values mg117g   MG117G  
label values mg117h   MG117H  
label values mg117i   MG117I  
label values mg117j   MG117J  
label values mg117x   MG117X  
label values mg117y   MG117Y  
label values mg118    MG118   
label values mg119    MG119   
label values mchd01   MCHD01  
label values mchd02   MCHD02  
label values mchd03   MCHD03  
label values mchd04   MCHD04  
label values mchd05   MCHD05  
label values mchd06   MCHD06  
label values mchd07   MCHD07  
label values mchd08   MCHD08  
label values mchd09   MCHD09  
label values mchd10   MCHD10  
label values sm107    SM107   
label values sm114    SM114   
label values sm115    SM115   
label values smstate  SMSTATE 
label values smzone   SMZONE  
label values smstate1 SMSTATE1
label values sm302ba  SM302BA 
label values sm302bb  SM302BB 
label values sm302bc  SM302BC 
label values sm302bd  SM302BD 
label values sm302be  SM302BE 
label values sm302bx  SM302BX 
label values sm813a   SM813A  
label values sm813ba  SM813BA 
label values sm813bb  SM813BB 
label values sm813bc  SM813BC 
label values sm813bd  SM813BD 
label values sm813be  SM813BE 
label values sm813bf  SM813BF 
label values sm813bx  SM813BX 
label values sm813bz  SM813BZ 
label values sm813ca  SM813CA 
label values sm813cb  SM813CB 
label values sm813cc  SM813CC 
label values sm813cd  SM813CD 
label values sm813ce  SM813CE 
label values sm813cf  SM813CF 
label values sm813cg  SM813CG 
label values sm813ch  SM813CH 
label values sm813ci  SM813CI 
label values sm813cj  SM813CJ 
label values sm813cx  SM813CX 
label values sm813cz  SM813CZ 
label values sm813d   SM813D  
label values sm813e   SM813E  
label values sm813fa  SM813FA 
label values sm813fb  SM813FB 
label values sm813fc  SM813FC 
label values sm813fd  SM813FD 
label values sm813fe  SM813FE 
label values sm813ff  SM813FF 
label values sm816a   SM816A  
label values sm816b   SM816B  
label values sm816c   SM816C  
label values sm816d   SM816D  
label values sm816e   SM816E  
label values sm816ea  SM816EA 
label values sm816eb  SM816EB 
label values sm816ec  SM816EC 
label values sm816ed  SM816ED 
label values sm816f   SM816F  
label values sm816ga  SM816GA 
label values sm816gb  SM816GB 
label values sm816gc  SM816GC 
label values sm816gd  SM816GD 
label values sm816ge  SM816GE 
label values sm816gf  SM816GF 
label values sm816gg  SM816GG 
label values sm816gh  SM816GH 
label values sm816gi  SM816GI 
label values sm816gj  SM816GJ 
label values sm816gx  SM816GX 
label values sm816gz  SM816GZ 
label values sm816ha  SM816HA 
label values sm816hb  SM816HB 
label values sm816hc  SM816HC 
label values sm816hd  SM816HD 
label values sm816he  SM816HE 
label values sm816hf  SM816HF 
label values sm816hg  SM816HG 
label values sm816hh  SM816HH 
label values sm816hx  SM816HX 
label values sm816hz  SM816HZ 
label values sm816ia  SM816IA 
label values sm816ib  SM816IB 
label values sm816ic  SM816IC 
label values sm816id  SM816ID 
label values sm816ie  SM816IE 
label values sm816if  SM816IF 
label values sm816ig  SM816IG 
label values sm816ix  SM816IX 
label values sm816iz  SM816IZ 
label values sm816ja  SM816JA 
label values sm816jb  SM816JB 
label values sm816jc  SM816JC 
label values sm816jd  SM816JD 
label values sm816je  SM816JE 
label values sm816jf  SM816JF 
label values sm816jg  SM816JG 
label values sm816jh  SM816JH 
label values sm816ji  SM816JI 
label values sm816jx  SM816JX 
label values sm816jz  SM816JZ 
label values sm816k   SM816K  
label values sm816l   SM816L  
label values sm816m   SM816M  
label values sm816n   SM816N  
label values sm816o   SM816O  
label values sm816p   SM816P  
label values sm816q   SM816Q  
label values sm816r   SM816R  
label values sml101   SML101  
label values sml901   SML901  
label values sml901a  SML901A 
label values sml901b  SML901B 
label values sml901c  SML901C 
label values sml901d  SML901D 
label values sml901e  SML901E 
label values sml901f  SML901F 
label values sml901g  SML901G 
label values sml901h  SML901H 
label values sml901i  SML901I 
label values sml901x  SML901X 
label values sml901z  SML901Z 
label values sml903   SML903  
label values sml903a  SML903A 
label values sml903b  SML903B 
label values sml903c  SML903C 
label values sml903d  SML903D 
label values sml903e  SML903E 
label values sml903f  SML903F 
label values sml903g  SML903G 
label values sml903h  SML903H 
label values sml903x  SML903X 
label values sml903z  SML903Z 
label values sml905   SML905  
label values sml906   SML906  
label values sml907   SML907  
label values sml908   SML908  
label values sml909   SML909  
label values sml910   SML910  
label values sml911   SML911  
label values sml912   SML912  
label values sml913   SML913  
label values sml914   SML914  
