infix using "C:\COUNTRIES\GH7I\GHVA7IFL_ALLYEARS.dct"

label variable qvhclust "Cluster number"
label variable qvhnumber "Household number"
label variable qline    "Individual line number"
label variable qregion  "Region"
label variable qdistr   "District"
label variable qintd    "Day of interview"
label variable qintm    "Month of interview"
label variable qinty    "Year of interview"
label variable qintnum  "Interviewer number"
label variable qresult  "Result of individual interview"
label variable qvisits  "Total number of visits"
label variable qsuperv  "Supervisor number"
label variable qlangq   "Language of questionnaire"
label variable qlangi   "Language of interview"
label variable qlangr   "Language of respondent"
label variable qtrans   "Translator used"
label variable qintc    "Date of interview (CMC)"
label variable qintcd   "Date of interview Century Day Code (CDC)"
label variable qweight  "Sample weight (6 decimals)"
label variable qtype    "Type of place of residence"
label variable qconsent "Consent agreement"
label variable q1007h   "End of interview (hour)"
label variable q1007m   "End of interview (minutes)"
label variable q100h    "Start of interview (hour)"
label variable q100m    "Start of interview (minutes)"
label variable q101d    "Day of birth"
label variable q101m    "Month of birth"
label variable q101y    "Year of birth"
label variable q102d    "Day of death"
label variable q102m    "Month of death"
label variable q102y    "Year of death"
label variable q104     "Age at death"
label variable q106     "Died while pregnant"
label variable q107     "Died during childbirth"
label variable q108a    "Died within 2 months of delivery"
label variable q108b    "Days after end of pregnancy/childbirth died"
label variable q108c    "Death due to violence"
label variable q108d    "Death due to accident"
label variable q109     "Marital status"
label variable q110     "Highest educational level attended"
label variable q111     "Work in last 12 months before died"
label variable q112     "Occupation"
label variable q113     "Religion"
label variable q114     "Ethnic group"
label variable q115     "Place of death"
label variable q116     "Usual place of residence"
label variable q117     "Place of burial"
label variable q118     "Season where she died"
label variable q119     "Relationship with main respondent"
label variable q120     "Living with respondent at period of death"
label variable qelig    "VA eligibility"
label variable q101c    "Date of birth (CMC)"
label variable q101f    "Date flag for Q101C"
label variable q102c    "Date of death (CMC)"
label variable q102f    "Date flag for Q102C"
label variable q201     "Description of events leading to death"
label variable q102cd   "Date of death Century Day Code (CDC)"
label variable q102di   "Imputed day of death"
label variable q301     "Suffered from any injury or accident that led to death"
label variable q302a    "Road traffic accident"
label variable q302b    "Role in road traffic accident"
label variable q302c    "Counterpart during the road traffic accident"
label variable q303     "Injured in a non-road transport accident"
label variable q304     "Injured in a fall"
label variable q305     "Was there any poisoning"
label variable q306     "Die of drowning"
label variable q307a    "Injured by a bite or sting of venomous animal"
label variable q307b    "Injured by an animal or insect (non-venomous)"
label variable q307c    "Type of animal or insect"
label variable q308     "Injured by burns or fire"
label variable q309     "Subject to violence (suicide, homicide, or abuse)"
label variable q310     "Injured by a firearm"
label variable q311     "Stabbed, cut, or pierced"
label variable q312     "Strangled"
label variable q313     "Injured by a blunt force"
label variable q314     "Injured by a force of nature"
label variable q315     "Electrocuted"
label variable q316     "Injured by some other injury"
label variable q317     "Injury accidental"
label variable q318     "Accident or injury self-inflicted"
label variable q319     "Accident or injury intentionally inflicted by someone else"
label variable q401au   "Length of illness before death (units)"
label variable q401an   "Length of illness before death (number)"
label variable q402     "Die suddenly"
label variable q403     "Any diagnosis by a physician or health worker of tuberculosis or TB"
label variable q404u    "Months or years prior to death was diagnosed with tuberculosis or TB (units)"
label variable q404n    "Months or years prior to death was diagnosed with tuberculosis or TB (number)"
label variable q405a    "HIV test ever positive"
label variable q405bu   "Days, weeks or months prior to death was tested for HIV (units)"
label variable q405bn   "Days, weeks or months prior to death was tested for HIV (number)"
label variable q406     "Hiv test result"
label variable q407     "Any diagnosis by a physician or health worker of AIDS"
label variable q408u    "Months or years prior to death was diagnosed with AIDS (units)"
label variable q408n    "Months or years prior to death was diagnosed with AIDS (number)"
label variable q409     "Had a recent test by a physician or health worker for malaria"
label variable q410a    "Malaria test result"
label variable q410bu   "Days, weeks or months prior to death was tested with malaria (units)"
label variable q410bn   "Days, weeks or months prior to death was tested with malaria (number)"
label variable q413     "Any diagnosis by a physician or health worker of measles"
label variable q414u    "Months or years prior to death was diagnosed with measles (units)"
label variable q414n    "Months or years prior to death was diagnosed with measles (number)"
label variable q415     "Any diagnosis by a physician or health worker of high blood pressure"
label variable q416u    "Months or years prior to death was diagnosed with high blood pressure (units)"
label variable q416n    "Months or years prior to death was diagnosed with high blood pressure (number)"
label variable q417     "Any diagnosis by a physician or health worker of heart disease"
label variable q418u    "Months or years prior to death was diagnosed with heart disease (units)"
label variable q418n    "Months or years prior to death was diagnosed with heart disease (number)"
label variable q419     "Any diagnosis by a physician or health worker of diabetes"
label variable q420u    "Months or years prior to death was diagnosed with diabetes (units)"
label variable q420n    "Months or years prior to death was diagnosed with diabetes (number)"
label variable q421     "Any diagnosis by a physician or health worker of asthma"
label variable q422u    "Months or years prior to death was diagnosed with asthma (units)"
label variable q422n    "Months or years prior to death was diagnosed with asthma (number)"
label variable q423     "Any diagnosis by a physician or health worker of epilepsy"
label variable q424u    "Months or years prior to death was diagnosed with epilepsy (units)"
label variable q424n    "Months or years prior to death was diagnosed with epilepsy (number)"
label variable q425     "Any diagnosis by a physician or health worker of cancer"
label variable q426     "Type of cancer"
label variable q427u    "Months or years prior to death was diagnosed with cancer (units)"
label variable q427n    "Months or years prior to death was diagnosed with cancer (number)"
label variable q428     "Any diagnosis by a physician or health worker of chronic obstructive pulmonary d"
label variable q429u    "Months or years prior to death was diagnosed with chronic obstructive pulmonary "
label variable q429n    "Months or years prior to death was diagnosed with chronic obstructive pulmonary "
label variable q430     "Any diagnosis by a physician or health worker of dementia"
label variable q431u    "Months or years prior to death was diagnosed with dementia (units)"
label variable q431n    "Months or years prior to death was diagnosed with dementia (number)"
label variable q432     "Any diagnosis by a physician or health worker of depression"
label variable q433u    "Months or years prior to death was diagnosed with depression (units)"
label variable q433n    "Months or years prior to death was diagnosed with depression (number)"
label variable q434     "Any diagnosis by a physician or health worker of other mental disorder"
label variable q435     "Type of mental disorder"
label variable q436u    "Months or years prior to death was diagnosed with other mental disorder (units)"
label variable q436n    "Months or years prior to death was diagnosed with other mental disorder (number)"
label variable q437     "Any diagnosis by a physician or health worker of stroke"
label variable q438u    "Months or years prior to death was diagnosed with stroke (units)"
label variable q438n    "Months or years prior to death was diagnosed with stroke (number)"
label variable q439     "Any diagnosis by a physician or health worker of sickle cell disease"
label variable q440u    "Months or years prior to death was diagnosed with sickle cell disease (units)"
label variable q440n    "Months or years prior to death was diagnosed with sickle cell disease (number)"
label variable q441     "Any diagnosis by a physician or health worker of kidney disease"
label variable q442u    "Months or years prior to death was diagnosed with kidkey disease (units)"
label variable q442n    "Months or years prior to death was diagnosed with kidkey disease (number)"
label variable q443     "Any diagnosis by a physician or health worker of liver disease"
label variable q444u    "Months or years prior to death was diagnosed with liver disease (units)"
label variable q444n    "Months or years prior to death was diagnosed with liver disease (number)"
label variable q445     "Any diagnosis by a physician or health worker of other chronic illness"
label variable q446     "Type of illness"
label variable q447u    "Months or years prior to death was diagnosed with other chronic illness (units)"
label variable q447n    "Months or years prior to death was diagnosed with other chronic illness (number)"
label variable q448     "Cause of death"
label variable q501a    "Had a fever"
label variable q501b    "Duration of fever"
label variable q501c    "Fever continued until death"
label variable q501d    "Fever severity"
label variable q501e    "Pattern of the fever"
label variable q501f    "Had night sweats"
label variable q502a    "Had a cough"
label variable q502bu   "Cough duration (units)"
label variable q502bn   "Cough duration (number)"
label variable q502c    "Cough productive, with sputum"
label variable q502d    "Cough very severe"
label variable q502e    "Coughed up blood"
label variable q503a    "Had any difficulty breathing"
label variable q503bu   "Difficulty breathing duration (units)"
label variable q503bn   "Difficulty breathing duration (number)"
label variable q503c    "Difficulty continuous or on and off"
label variable q504a    "Had fast breathing during illness/events that led to death"
label variable q504b    "Duration of fast breathing"
label variable q505a    "Had breathlessness"
label variable q505b    "Duration of breathlessness"
label variable q505c    "Unabled to carry out daily routines due to breathlessness"
label variable q505d    "Breathless while lying flat"
label variable q506     "Breathing sound like wheezing during the illness/events that led to death"
label variable q507a    "Had chest pain"
label variable q507b    "Chest pain severe"
label variable q507c    "Duration of chest pain before death (days)"
label variable q507du   "Duration of chest pain before death (units)"
label variable q507dn   "Duration of chest pain before death (number)"
label variable q508a    "Had more frequent loose or liquid stools than usual"
label variable q508b    "Duration of frequent loose or liquid stools"
label variable q508c    "Blood in the stools during final illness/events"
label variable q508d    "Blood in the stool up until death"
label variable q509a    "Vomited"
label variable q509b    "Vomited in the week preceding death"
label variable q509c    "Duration of vomiting  before death"
label variable q509d    "Vomited blood"
label variable q509e    "Vomited black"
label variable q510     "Had any belly (abdominal) problems"
label variable q511a    "Had any belly (abdominal) pain"
label variable q511b    "Belly (abdominal) pain severe"
label variable q511cu   "Duration of abdominal pain before death (units)"
label variable q511cn   "Duration of abdominal pain before death (number)"
label variable q511d    "Pain in the upper or lower abdomen"
label variable q512a    "Had more than usually protruding abdomen"
label variable q512bu   "Duration had a more than usually protruding abdomen (units)"
label variable q512bn   "Duration had a more than usually protruding abdomen (number)"
label variable q512c    "Speed of developing the protruding abdomen"
label variable q513a    "Had any mass in the abdomen"
label variable q513bu   "Duration had a mass in the abdomen before death (units)"
label variable q513bn   "Duration had a mass in the abdomen before death (number)"
label variable q514     "Had a severe headache"
label variable q515a    "Had a stiff neck during the illness/events that led to death"
label variable q515b    "Duration has a stiff neck before death"
label variable q516a    "Had a painful neck during the illness/events that led to death"
label variable q516b    "Duration had  painful neck before death"
label variable q517a    "Had mental confusion"
label variable q517bu   "Duration of mental confusion (units)"
label variable q517bn   "Duration of mental confusion (number)"
label variable q518a    "Unconscious during the illness/events that led to death"
label variable q518b    "Unconscious for more than 24 hours before death"
label variable q518c    "Unconsciousness start suddenly or quickly, at least within a single day"
label variable q518d    "Unconsciousness continue until death"
label variable q519a    "Had convulsions"
label variable q519b    "Duration of convulsions"
label variable q519c    "Became unconscious immediately after the convulsion"
label variable q520a    "Had any urine problems"
label variable q520b    "Stopped urinating"
label variable q520c    "Went to urinate more often than usual"
label variable q520d    "Ever passes blood in the urine"
label variable q522a    "Had sores"
label variable q522b    "Sores had clear fluid or pus"
label variable q523a    "Had an ulcer or pit on the foot"
label variable q523b    "Ulcer on the foot oozed pus"
label variable q523c    "Duration of the ulcer on the foot that oozed pus"
label variable q524a    "Had any skin rash during the illness/events that led to death"
label variable q524b    "Duration had the skin rash"
label variable q524c    "Place of the rash"
label variable q525     "Did she ever have shingles or herpes zoster?"
label variable q526     "Skin flaked off in patches during the illness/events that led to death,"
label variable q527a    "Bled from anywhere during the illness/events that led to death"
label variable q527b    "Bled from the mouth, nose, or anus"
label variable q528     "Had noticeable weight loss"
label variable q529     "Was severely thin or wasted"
label variable q530     "Had a whitish rash inside the mouth or on the tongue during the illness/events t"
label variable q531     "Had stiffness of the whole body or was unable to open the mouth"
label variable q532a    "Had puffiness of the face"
label variable q532b    "Duration of puffiness of the face"
label variable q533a    "Had swollen legs or feet during the illness/events that led to death"
label variable q533b    "Duration of the swelling"
label variable q533c    "Had both feet swollen"
label variable q534     "Had  general puffiness all over her body"
label variable q535a    "Had any lumps"
label variable q535b    "Had any lumps or lesions in the mouth"
label variable q535c    "Had any lumps on the neck"
label variable q535d    "Had any lumps on the armpit"
label variable q535e    "Had any lumps on the groin"
label variable q536a    "Was in any way paralysed"
label variable q536b    "Had paralysis of only one side of the body"
label variable q536c    "Which were the limbs or body parts paralysed"
label variable q537a    "Had difficulty swallowing"
label variable q537b    "Duration of difficulty swallowing"
label variable q537c    "Difficulty with swallowing with solids, liquids, or both"
label variable q538     "Had pain upon swallowing"
label variable q539a    "Had yellow discoloration of the eyes"
label variable q539b    "Duration of yellow discoloration"
label variable q540     "Hair changed in colour to a reddish or yellowish colour"
label variable q541     "Looked pale (thinning/lack of blood) or have pale palms, eyes, or nail beds"
label variable q542     "Drank a lot more water than usual"
label variable q601     "Had any swelling or lump in the breast"
label variable q602     "Had any ulcers (pits) in the breast"
label variable q603a    "Ever had a period or menstruate"
label variable q603b    "Had vaginal bleeding in between menstrual periods"
label variable q603c    "Vaginal bleeding excessive"
label variable q603e    "Menstrual period stopped naturally because of menopause"
label variable q603f    "Had vaginal bleeding after cessation of menstruation"
label variable q603g    "Excessive vaginal bleeding in the week prior to death"
label variable q603i    "Period overdue at the time of death"
label variable q603j    "Duration of period overdue"
label variable q604     "Had a sharp pain in her abdomen shortly before death"
label variable q605     "Pregnant at the time of death"
label variable q606     "Died during or within 6 weeks of labour, delivery, abortion or miscarriage"
label variable q608     "Died less than 1 year after being pregnant or delivering a baby"
label variable q608a    "Confirmation: not pregnant and had not been pregnant or delivered in the 12 mont"
label variable q609     "Duration of pregnancy"
label variable q611     "Died during labour or delivery"
label variable q612a    "Died after delivering a baby"
label variable q612b    "Died within 24 hours after delivery"
label variable q613     "Died within 6 weeks of childbirth"
label variable q614     "Gave birth to a live baby (within 6 weeks of death)"
label variable q615     "Died during or after a multiple pregnancy"
label variable q616b    "Breastfeeding the child in the days before death"
label variable q617a    "Births/stillbirths before this baby/pregnancy"
label variable q617c    "Had any previous caesarean section"
label variable q618     "During this pregnancy, suffered from high blood pressure"
label variable q619     "Had foul smelling vaginal discharge during pregnancy or after delivery"
label variable q620     "Bleeding while pregnant"
label variable q621     "Vaginal bleeding during the first 6 months of pregnancy"
label variable q622b    "During the last 3 months of pregnancy, suffered from convulsions"
label variable q622c    "During the last 3 months of pregnancy, suffered from blurred vision"
label variable q622d    "Vaginal bleeding during the last 3 months of pregnancy but before labour started"
label variable q623a    "Had excessive bleeding during labour or delivery"
label variable q623b    "Water broken before labour started or delivery"
label variable q623c    "Baby delivered less than 24 hours after water broke"
label variable q623d    "Water broke smell foul"
label variable q624     "Had excessive bleeding after delivery/miscarriage/abortion"
label variable q625     "Attempted to terminate the pregnancy"
label variable q626     "Had a recently pregnancy that ended in a miscarriage or abortion"
label variable q627     "Died during a miscarriage or abortion"
label variable q628     "Died within 6 weeks of having a miscarriage or abortion"
label variable q630     "Place she gave birth"
label variable q631     "Received professional assistance during the delivery"
label variable q632     "Person who delivered the baby"
label variable q633     "Had an operation to remove her uterus shortly before death because problems with"
label variable q634     "Delivery normal vaginal, without forceps or vacuum"
label variable q635     "Delivery vaginal, with forceps or vacuum"
label variable q636     "Delivery a caesarean section"
label variable q637     "Baby born more than one month early"
label variable q638     "Placenta completely delivered"
label variable q639     "Deliver or tried to deliver an abnormally positioned baby"
label variable q640     "Duration of labour"
label variable q701     "Drank alcohol at least once a week"
label variable q702a    "Used tobacco (Cigarette, cigar, pipe, etc.)"
label variable q702b    "Kind of tobacco used"
label variable q702c    "Amount of cigarettes smoked daily"
label variable q801     "Received any treatment for the illness/events/circumstances that led to her deat"
label variable q802     "Received oral rehydration salts"
label variable q803     "Received (or needed) intravenous fluids (drip) treatment"
label variable q804     "Received (or needed) a blood transfusion"
label variable q805     "Received (or needed treatment/food through a tube passed through the nose"
label variable q806     "Receive (or needed) injectable antibiotics"
label variable q807     "Received  (or needed) antiretroviral therapy (ART)"
label variable q808a    "Had  (or needed) an operation for the illness/events"
label variable q808b    "Had the operation within 1 month before death"
label variable q809     "Discharged from hospital very ill"
label variable q810a    "Care sought outside the home while she had this illness/events"
label variable q810b    "Where was care sought"
label variable q810c    "Name or address of the main source of care"
label variable q811a    "Did a health care worker tell you the cause of death?"
label variable q811b    "What the health care worker said"
label variable q812a    "Had any health records that belonged to the deceased"
label variable q812b    "Health record seen"
label variable q812c    "Kind of health record provided"
label variable q813ad   "Day of the most recent (last) visit"
label variable q813am   "Month of the most recent (last) visit"
label variable q813ay   "Year of the most recent (last) visit"
label variable q813b    "Weight written at the most recent (last) visit"
label variable q814ad   "Day of the last but one (second last) visit"
label variable q814am   "Month of the last but one (second last) visit"
label variable q814ay   "Year of the last but one (second last) visit"
label variable q814b    "Weight written at the last but one (second last) visit"
label variable q815ad   "Day of the most recent (last) note"
label variable q815am   "Month of the most recent (last) note"
label variable q815ay   "Year of the most recent (last) note"
label variable q815b    "Last note on health records"
label variable q901a    "Traveled to a hospital or health facility, in the final days before death"
label variable q901b    "Health facility name"
label variable q902a    "Used motorised transport to get to the hospital or health facility"
label variable q902b    "Main means of transport used to get to hospital/health facility"
label variable q902c    "Time to get to the health facility"
label variable q903     "Any problems in being received at the hospital or health facility"
label variable q904     "Any problems with the way she was treated in the hospital or health facility"
label variable q905     "Any problems getting medications or diagnostic tests in the hospital or health f"
label variable q906     "Time to get to the nearest health facility"
label variable q907     "Any doubts about whether medical care was needed, in the final days before death"
label variable q908     "Traditional/herbal or spiritual medicine used, in the final days before death"
label variable q909     "Anyone used a telephone or cell phone to call for help, in the final days before"
label variable q910     "Total costs of care and treatment prohibit other household payments,  over the c"
label variable q1001a   "Had a death certificate"
label variable q1001b   "Can see the death certificate"
label variable q1002ad  "Day of death from death certificate"
label variable q1002am  "Month of death from death certificate"
label variable q1002ay  "Year of death from death certificate"
label variable q1002bd  "Day of issue of death certificate"
label variable q1002bm  "Month of issue of death certificate"
label variable q1002by  "Year of issue of death certificate"
label variable q1003a   "Cause of death from the first (top) line of death certificate"
label variable q1003b   "Cause of death from the second line of death certificate"
label variable q1003c   "Cause of death from the third line of death certificate"
label variable q1003d   "Cause of death from the fourth line of death certificate"
label variable q1004a   "Had a burial permit"
label variable q1004b   "Can see the burial permit"
label variable q1005d   "Day of issue of burial permit"
label variable q1005m   "Month of issue of burial permit"
label variable q1005y   "Year of issue of burial permit"
label variable q1006    "Cause of death from the burial permit"
label variable cdicd10i "ICD-10 Code (After application of m1-m4, final underlying cause of death)"
label variable cddeathp "Death during pregnancy, childbirth, or within 42 days or 1 year of end of pregna"

#delimit ;
label define QREGION 
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Brong Ahafo"
     8 "Northern"
     9 "Upper East"
    10 "Upper West"
;
label define QINTM   
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
;
label define QRESULT 
     1 "Completed"
     2 "No household member at home or no competent respondent"
     3 "Entire household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define QLANGQ  
     0 "English"
     1 "Akan"
     2 "Ga"
     3 "Ewe"
;
label define QLANGI  
     0 "English"
     1 "Akan"
     2 "Ga"
     3 "Ewe"
     4 "Guan"
     5 "Mole-dagbani"
     6 "Grusi"
     7 "Gurma"
     8 "Mande"
    96 "Other"
;
label define QLANGR  
     0 "English"
     1 "Akan"
     2 "Ga"
     3 "Ewe"
     4 "Guan"
     5 "Mole-dagbani"
     6 "Grusi"
     7 "Gurma"
     8 "Mande"
    96 "Other"
;
label define QTRANS  
     1 "Yes"
     2 "No"
;
label define QTYPE   
     1 "Urban"
     2 "Rural"
;
label define QCONSENT
     1 "Respondent agrees to be interviewed"
     2 "Respondent does not agree to be interviewed"
;
label define Q101D   
    98 "Don't know day"
;
label define Q101M   
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    98 "Don't know month"
;
label define Q102D   
    98 "Don't know day"
;
label define Q102M   
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    98 "Don't know month"
;
label define Q104    
    95 "95 or more"
;
label define Q106    
     1 "Yes"
     2 "No"
;
label define Q107    
     1 "Yes"
     2 "No"
;
label define Q108A   
     1 "Yes"
     2 "No"
;
label define Q108C   
     1 "Yes"
     2 "No"
;
label define Q108D   
     1 "Yes"
     2 "No"
;
label define Q109    
     1 "Never married"
     2 "Married"
     3 "Living with a partner"
     4 "Separated"
     5 "Divorced"
     6 "Widowed"
;
label define Q110    
     1 "Primary"
     2 "Middle"
     3 "Jss/jhs"
     4 "Secondary/Tech/Voc/Comm"
     5 "Sss/Shs/Tech/Voc/Comm"
     6 "Higher"
     7 "Never attended school"
     8 "Don't know"
;
label define Q111    
     1 "Yes"
     2 "No"
;
label define Q112    
     1 "Commissioned armed forces officers"
     2 "Non-commissioned armed forces officers"
     3 "Armed forces occupations, other ranks"
    11 "Chief executive, senior officers and legislators"
    12 "Administrative and commercial managers"
    13 "Production and specialized service managers"
    14 "Hospitality, retail and other services managers"
    21 "Science and engineering professionals"
    22 "Health professionals"
    23 "Teaching professionals"
    24 "Business and administrative professionals"
    25 "Information and communication technology professionals"
    26 "Legal, social and cultural professional"
    31 "Science and engineering associate professionals"
    32 "Health associate professionals"
    33 "Business and administration associate professionals"
    34 "Legal, social cultural and related associate professionals"
    35 "Information and communications technicians"
    41 "General and keyboard clerks"
    42 "Customer service clerks"
    43 "Numerical and mateial recording clerks"
    44 "Other clerical support workers"
    51 "Personal sales workers"
    52 "Sales workers"
    53 "Personal care workers"
    61 "Market-oriented agricultural workers"
    62 "Market-oriented skilled forestry, fishery and hunting workers"
    63 "Subsistence farmers, fishers, hunters and gatherers"
    71 "Building and related trades workers, excluding electricians"
    72 "Metal, machinery and related trades workers"
    73 "Handicraft and printing workers"
    74 "Electrical and electronic trades workers"
    75 "Food processing, wood working, garment and other craft and related trades workers"
    81 "Stationary plant and machine operators"
    82 "Assemblers"
    83 "Drivers and mobile plant operators"
    91 "Cleaners and helpers"
    92 "Agricultural, forestry and fishery labourers"
    93 "Labours in mining, construction, manufacturing and transport"
    94 "Food preparation assistants"
    95 "Street and related sales and service workers"
    96 "Refuse workers and other elementary workers"
    97 "Other occupations"
;
label define Q113    
     1 "Catholic"
     2 "Anglican"
     3 "Methodist"
     4 "Presbyterian"
     5 "Pentecostal/charismatic"
     6 "Other christian"
     7 "Islam"
     8 "Traditional/spiritualist"
     9 "No religion"
    96 "Other"
    98 "Don't know"
;
label define Q114    
     1 "Akan"
     2 "Ga/dangme"
     3 "Ewe"
     4 "Guan"
     5 "Mole-dagbani"
     6 "Grusi"
     7 "Gurma"
     8 "Mande"
    96 "Other"
;
label define Q115    
     1 "Her home"
     2 "Other home"
     3 "Health facility"
     4 "En route to health facility"
     5 "Shrine/prayer camp"
     6 "Other"
;
label define Q116    
     1 "In this house"
     2 "In this locality"
     3 "In a different village/town"
     6 "Other"
;
label define Q117    
     1 "In this house"
     2 "In this locality"
     3 "In a different village/town"
     4 "Burial not yet performed"
     6 "Other"
;
label define Q118    
     1 "Wet season"
     2 "Dry season"
     6 "Other"
;
label define Q119    
     1 "Husband/partner"
     2 "Parent"
     3 "Child"
     4 "Sibling"
     5 "Other family member"
     6 "Friend"
     7 "Another relationship"
;
label define Q120    
     1 "Yes"
     2 "No"
;
label define QELIG   
     1 "Eligible for VA"
     2 "Not eligible based on date of death"
     3 "Not eligible based on age of death"
;
label define Q101F   
     0 "Ruled ineligible for survey"
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define Q102F   
     0 "Ruled ineligible for survey"
     1 "M of death and Y of death"
     2 "Y of death, Age of Death, Y of Birth, M of Birth - M of death imputed"
     3 "Y of death, Age of death, Year of birth - M of death imputed"
     4 "Y of death, Age of death, M of birth - M of death imputed"
     5 "Y of death, Age of death - M of death imputed"
     6 "Y of deah - M of death imputed"
     7 "None - Y of death, M of death imputed"
     8 "Other"
;
label define Q201    
     6 "Narrative events"
;
label define Q301    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q302A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q302B   
     1 "Pedestrian"
     2 "Driver or passenger in car or light vehicle"
     3 "Driver or passenger in bus or heavy vehicle"
     4 "Driver or passenger on motorcycle"
     5 "Driver or passenger on pedal cycle"
     6 "Other"
     8 "Don't know"
;
label define Q303    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q304    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q305    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q306    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q307A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q307B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q307C   
     1 "Dog"
     2 "Snake"
     3 "Insect"
     4 "Scorpion"
     6 "Other"
     8 "Don't know"
;
label define Q308    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q309    
     1 "Yes, suicide"
     2 "Yes, homicide"
     3 "Yes, abuse"
     4 "No"
     8 "Don't know"
;
label define Q310    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q311    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q312    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q313    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q314    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q315    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q316    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q317    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q318    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q319    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q401AU  
     1 "Days"
     2 "Weeks"
     3 "Months"
     4 "Years"
;
label define Q401AN  
    95 "95 or more"
;
label define Q402    
     1 "Yes"
     2 "No"
;
label define Q403    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q404U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q404N   
    95 "95 or more"
    98 "Don't know"
;
label define Q405A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q405BU  
     1 "Days"
     2 "Weeks"
     3 "Months"
     9 "Special answers"
;
label define Q405BN  
    95 "95 or more"
    98 "Don't know"
;
label define Q406    
     1 "Positive"
     2 "Negative"
     8 "Don't know"
;
label define Q407    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q408U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q408N   
    95 "95 or more"
    98 "Don't know"
;
label define Q409    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q410A   
     1 "Positive"
     2 "Negative"
     8 "Don't know"
;
label define Q410BU  
     1 "Days"
     2 "Weeks"
     3 "Months"
     9 "Special answers"
;
label define Q410BN  
    95 "95 or more"
    98 "Don't know"
;
label define Q413    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q414U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q414N   
    95 "95 or more"
    98 "Don't know"
;
label define Q415    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q416U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q416N   
    95 "95 or more"
    98 "Don't know"
;
label define Q417    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q418U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q418N   
    95 "95 or more"
    98 "Don't know"
;
label define Q419    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q420U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q420N   
    95 "95 or more"
    98 "Don't know"
;
label define Q421    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q422U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q422N   
    95 "95 or more"
    98 "Don't know"
;
label define Q423    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q424U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q424N   
    95 "95 or more"
    98 "Don't know"
;
label define Q425    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q426    
    11 "Lung"
    12 "Breast"
    13 "Cervix"
    14 "Liver"
    15 "Throat"
    16 "Colon"
    96 "Other"
    98 "Don't know"
;
label define Q427U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q427N   
    95 "95 or more"
    98 "Don't know"
;
label define Q428    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q429U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q429N   
    95 "95 or more"
    98 "Don't know"
;
label define Q430    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q431U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q431N   
    95 "95 or more"
    98 "Don't know"
;
label define Q432    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q433U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q433N   
    95 "95 or more"
    98 "Don't know"
;
label define Q434    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q435    
     1 "Bipolar disorder"
     2 "Schizophrenia"
     6 "Other"
     8 "Don't know"
;
label define Q436U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q436N   
    95 "95 or more"
    98 "Don't know"
;
label define Q437    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q438U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q438N   
    95 "95 or more"
    98 "Don't know"
;
label define Q439    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q440U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q440N   
    95 "95 or more"
    98 "Don't know"
;
label define Q441    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q442U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q442N   
    95 "95 or more"
    98 "Don't know"
;
label define Q443    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q444U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q444N   
    95 "95 or more"
    98 "Don't know"
;
label define Q445    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q446    
     1 "Lupus"
     2 "Rheumatoid arthritis"
     6 "Other"
     8 "Don't know"
;
label define Q447U   
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q447N   
    95 "95 or more"
    98 "Don't know"
;
label define Q448    
     6 "Cause of death"
;
label define Q501A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q501B   
    95 "95 or more"
    98 "Don't know"
;
label define Q501C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q501D   
     1 "Mild"
     2 "Moderate"
     3 "Severe"
;
label define Q501E   
     1 "Continuous"
     2 "On and off"
     3 "Only at night"
     4 "Only during day"
     8 "Don't know"
;
label define Q501F   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q502A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q502BU  
     1 "Days"
     2 "Months"
     3 "Years"
     9 "Special answers"
;
label define Q502BN  
    95 "95 or more"
    98 "Don't know"
;
label define Q502C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q502D   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q502E   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q503A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q503BU  
     1 "Days"
     2 "Months"
     3 "Years"
     9 "Special answers"
;
label define Q503BN  
    95 "95 or more"
    98 "Don't know"
;
label define Q503C   
     1 "Continuous"
     2 "On and off"
     8 "Don't know"
;
label define Q504A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q504B   
    95 "95 or more"
    98 "Don't know"
;
label define Q505A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q505B   
    95 "95 or more"
    98 "Don't know"
;
label define Q505C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q505D   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q506    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q507A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q507B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q507C   
    95 "95 or more"
    98 "Don't know"
;
label define Q507DU  
     1 "Minutes"
     2 "Hours"
     9 "Special answers"
;
label define Q507DN  
    95 "95 or more"
    98 "Don't know"
;
label define Q508A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q508B   
    95 "95 or more"
    98 "Don't know"
;
label define Q508C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q508D   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q509A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q509B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q509C   
    95 "95 or more"
    98 "Don't know"
;
label define Q509D   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q509E   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q510    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q511A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q511B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q511CU  
     1 "Hours"
     2 "Days"
     3 "Weeks"
     4 "Months"
     9 "Special answers"
;
label define Q511CN  
    95 "95 or more"
    98 "Don't know"
;
label define Q511D   
     1 "Upper abdomen"
     2 "Lower abdomen"
     3 "Upper and lower abdomen"
     8 "Don't know"
;
label define Q512A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q512BU  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define Q512BN  
    95 "95 or more"
    98 "Don't know"
;
label define Q512C   
     1 "Rapidly"
     2 "Slowly"
     8 "Don't know"
;
label define Q513A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q513BU  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define Q513BN  
    95 "95 or more"
    98 "Don't know"
;
label define Q514    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q515A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q515B   
    95 "95 or more"
    98 "Don't know"
;
label define Q516A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q516B   
    95 "95 or more"
    98 "Don't know"
;
label define Q517A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q517BU  
     1 "Months"
     2 "Years"
     9 "Special answers"
;
label define Q517BN  
    95 "95 or more"
    98 "Don't know"
;
label define Q518A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q518B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q518C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q518D   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q519A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q519B   
    95 "95 or more"
    98 "Don't know"
;
label define Q519C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q520A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q520B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q520C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q520D   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q522A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q522B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q523A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q523B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q523C   
    95 "95 or more"
    98 "Don't know"
;
label define Q524A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q524B   
    95 "95 or more"
    98 "Don't know"
;
label define Q525    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q526    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q527A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q527B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q528    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q529    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q530    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q531    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q532A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q532B   
    95 "95 or more"
    98 "Don't know"
;
label define Q533A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q533B   
    95 "95 or more"
    98 "Don't know"
;
label define Q533C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q534    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q535A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q535B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q535C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q535D   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q535E   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q536A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q536B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q536C   
     1 "Right side of body"
     2 "Left side of body"
     3 "Lower part of body"
     4 "Upper part of body"
     5 "One leg only"
     6 "One arm only"
     7 "Whole body"
     8 "Other"
    98 "Don't know"
;
label define Q537A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q537B   
    95 "95 or more"
    98 "Don't know"
;
label define Q537C   
     1 "Solids"
     2 "Liquids"
     3 "Both"
     8 "Don't know"
;
label define Q538    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q539A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q539B   
    95 "95 or more"
    98 "Don't know"
;
label define Q540    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q541    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q542    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q601    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q602    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q603A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q603B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q603C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q603E   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q603F   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q603G   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q603I   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q603J   
    95 "95 or more"
    98 "Don't know"
;
label define Q604    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q605    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q606    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q608    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q608A   
     1 "Yes, no pregnancy in 12 months before death"
     2 "No"
     8 "Don't know"
;
label define Q609    
    98 "Don't know"
;
label define Q611    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q612A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q612B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q613    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q614    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q615    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q616B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q617A   
    98 "Don't know"
;
label define Q617C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q618    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q619    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q620    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q621    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q622B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q622C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q622D   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q623A   
     1 "Yes"
     2 "No"
     3 "NA-Labour never started"
     8 "Don't know"
;
label define Q623B   
     1 "Before labour started"
     2 "During labour"
     3 "NA-Water never broke"
     8 "Don't know"
;
label define Q623C   
     1 "Less than 24 hours"
     2 "More than 24 hours"
     3 "NA-Baby never delivered"
     8 "Don't know"
;
label define Q623D   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q624    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q625    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q626    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q627    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q628    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q630    
    11 "Govt hospital"
    12 "Govt health center/clinic"
    13 "Govt health post/chps"
    14 "Mobile clinic/outreach"
    16 "Other public sector"
    21 "Private hospital/clinic"
    22 "Fp/ppag clinic"
    23 "Mobile clinic/outreach"
    24 "Maternity home"
    26 "Other private medical sector"
    31 "Deceased woman's home"
    32 "Other home"
    33 "TBA's home"
    96 "Other"
;
label define Q631    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q633    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q634    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q635    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q636    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q637    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q638    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q639    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q640    
    95 "95 or more"
    96 "Never in labour"
    98 "Don't know"
;
label define Q701    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q702A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q702C   
    80 "80 or more"
    98 "Don't know"
;
label define Q801    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q802    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q803    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q804    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q805    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q806    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q807    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q808A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q808B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q809    
     1 "Yes"
     2 "No"
     3 "Never admitted"
     4 "Never discharged"
     8 "Don't know"
;
label define Q810A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q810C   
     6 "Name or address of health facility"
;
label define Q811A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q811B   
     6 "Health worker said"
;
label define Q812A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q812B   
     1 "Yes"
     2 "No"
;
label define Q813AD  
    98 "Day not recorded"
;
label define Q813AM  
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    98 "Month not recorded"
;
label define Q813AY  
  9998 "Year not recorded"
;
label define Q814AD  
    96 "No second last visit"
    98 "Day not recorded"
;
label define Q814AM  
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    98 "Month not recorded"
;
label define Q814AY  
  9998 "Year not recorded"
;
label define Q815AD  
    96 "No note"
    98 "Day not recorded"
;
label define Q815AM  
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    98 "Month not recorded"
;
label define Q815AY  
  9998 "Year not recorded"
;
label define Q815B   
     6 "Last note on health records"
;
label define Q901A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q901B   
     1 "Name"
     8 "Don't know"
;
label define Q902A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q902B   
    11 "Shared taxi"
    12 "Individual taxi"
    13 "Trotro"
    14 "Bus (metro mass)"
    15 "Private car"
    16 "Train"
    17 "Motorcycle"
    18 "Canoe/boat/ferry with motor"
    19 "Ambulance"
    20 "Canoe/boat/ferry, no motor"
    21 "Bicycle"
    22 "On foot"
    96 "Other"
    98 "Don't know"
;
label define Q902C   
   995 "995 or more minutes"
   998 "Don't know"
;
label define Q903    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q904    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q905    
     1 "Yes"
     2 "No"
     3 "NA-Dead on arrival"
     8 "Don't know"
;
label define Q906    
   995 "995 or more minutes"
   998 "Don't know"
;
label define Q907    
     1 "Yes, there were doubts"
     2 "No doubts-illness not serious"
     3 "No doubts-death inevitable"
     4 "No doubts-went to facility"
     5 "No doubts-not sick before death"
     8 "Don't know"
;
label define Q908    
     1 "Yes, traditional/herbal only"
     2 "Yes, spiritual only"
     3 "Yes, both"
     4 "No"
     8 "Don't know"
;
label define Q909    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q910    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q1001A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q1001B  
     1 "Yes"
     2 "No"
;
label define Q1002AD 
    98 "Day not recorded"
;
label define Q1002AM 
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    98 "Month not recorded"
;
label define Q1002AY 
  9998 "Year not recorded"
;
label define Q1002BD 
    98 "Day not recorded"
;
label define Q1002BM 
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    98 "Month not recorded"
;
label define Q1002BY 
  9998 "Year not recorded"
;
label define Q1003A  
     6 "Cause of death (first line)"
;
label define Q1003B  
     6 "Cause of death (second line)"
;
label define Q1003C  
     6 "Cause of death (third line)"
;
label define Q1003D  
     6 "Cause of death (fourth line)"
;
label define Q1004A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q1004B  
     1 "Yes"
     2 "No"
;
label define Q1005D  
    98 "Day not recorded"
;
label define Q1005M  
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    98 "Month not recorded"
;
label define Q1005Y  
  9998 "Year not recorded"
;
label define Q1006   
     6 "Cause of death from the burial permit"
;
label define CDDEATHP
     1 "No, death not during pregnancy, childbirth, or 42 days or 1 year of end of pregnancy"
     2 "Yes, during pregnancy"
     3 "Yes, during childbirth"
     4 "Yes, within 42 days of end of pregnancy"
     5 "Yes, between 43 days and 1 year of end of pregnancy"
;

#delimit cr
label values qregion  QREGION 
label values qintm    QINTM   
label values qresult  QRESULT 
label values qlangq   QLANGQ  
label values qlangi   QLANGI  
label values qlangr   QLANGR  
label values qtrans   QTRANS  
label values qtype    QTYPE   
label values qconsent QCONSENT
label values q101d    Q101D   
label values q101m    Q101M   
label values q102d    Q102D   
label values q102m    Q102M   
label values q104     Q104    
label values q106     Q106    
label values q107     Q107    
label values q108a    Q108A   
label values q108c    Q108C   
label values q108d    Q108D   
label values q109     Q109    
label values q110     Q110    
label values q111     Q111    
label values q112     Q112    
label values q113     Q113    
label values q114     Q114    
label values q115     Q115    
label values q116     Q116    
label values q117     Q117    
label values q118     Q118    
label values q119     Q119    
label values q120     Q120    
label values qelig    QELIG   
label values q101f    Q101F   
label values q102f    Q102F   
label values q201     Q201    
label values q301     Q301    
label values q302a    Q302A   
label values q302b    Q302B   
label values q303     Q303    
label values q304     Q304    
label values q305     Q305    
label values q306     Q306    
label values q307a    Q307A   
label values q307b    Q307B   
label values q307c    Q307C   
label values q308     Q308    
label values q309     Q309    
label values q310     Q310    
label values q311     Q311    
label values q312     Q312    
label values q313     Q313    
label values q314     Q314    
label values q315     Q315    
label values q316     Q316    
label values q317     Q317    
label values q318     Q318    
label values q319     Q319    
label values q401au   Q401AU  
label values q401an   Q401AN  
label values q402     Q402    
label values q403     Q403    
label values q404u    Q404U   
label values q404n    Q404N   
label values q405a    Q405A   
label values q405bu   Q405BU  
label values q405bn   Q405BN  
label values q406     Q406    
label values q407     Q407    
label values q408u    Q408U   
label values q408n    Q408N   
label values q409     Q409    
label values q410a    Q410A   
label values q410bu   Q410BU  
label values q410bn   Q410BN  
label values q413     Q413    
label values q414u    Q414U   
label values q414n    Q414N   
label values q415     Q415    
label values q416u    Q416U   
label values q416n    Q416N   
label values q417     Q417    
label values q418u    Q418U   
label values q418n    Q418N   
label values q419     Q419    
label values q420u    Q420U   
label values q420n    Q420N   
label values q421     Q421    
label values q422u    Q422U   
label values q422n    Q422N   
label values q423     Q423    
label values q424u    Q424U   
label values q424n    Q424N   
label values q425     Q425    
label values q426     Q426    
label values q427u    Q427U   
label values q427n    Q427N   
label values q428     Q428    
label values q429u    Q429U   
label values q429n    Q429N   
label values q430     Q430    
label values q431u    Q431U   
label values q431n    Q431N   
label values q432     Q432    
label values q433u    Q433U   
label values q433n    Q433N   
label values q434     Q434    
label values q435     Q435    
label values q436u    Q436U   
label values q436n    Q436N   
label values q437     Q437    
label values q438u    Q438U   
label values q438n    Q438N   
label values q439     Q439    
label values q440u    Q440U   
label values q440n    Q440N   
label values q441     Q441    
label values q442u    Q442U   
label values q442n    Q442N   
label values q443     Q443    
label values q444u    Q444U   
label values q444n    Q444N   
label values q445     Q445    
label values q446     Q446    
label values q447u    Q447U   
label values q447n    Q447N   
label values q448     Q448    
label values q501a    Q501A   
label values q501b    Q501B   
label values q501c    Q501C   
label values q501d    Q501D   
label values q501e    Q501E   
label values q501f    Q501F   
label values q502a    Q502A   
label values q502bu   Q502BU  
label values q502bn   Q502BN  
label values q502c    Q502C   
label values q502d    Q502D   
label values q502e    Q502E   
label values q503a    Q503A   
label values q503bu   Q503BU  
label values q503bn   Q503BN  
label values q503c    Q503C   
label values q504a    Q504A   
label values q504b    Q504B   
label values q505a    Q505A   
label values q505b    Q505B   
label values q505c    Q505C   
label values q505d    Q505D   
label values q506     Q506    
label values q507a    Q507A   
label values q507b    Q507B   
label values q507c    Q507C   
label values q507du   Q507DU  
label values q507dn   Q507DN  
label values q508a    Q508A   
label values q508b    Q508B   
label values q508c    Q508C   
label values q508d    Q508D   
label values q509a    Q509A   
label values q509b    Q509B   
label values q509c    Q509C   
label values q509d    Q509D   
label values q509e    Q509E   
label values q510     Q510    
label values q511a    Q511A   
label values q511b    Q511B   
label values q511cu   Q511CU  
label values q511cn   Q511CN  
label values q511d    Q511D   
label values q512a    Q512A   
label values q512bu   Q512BU  
label values q512bn   Q512BN  
label values q512c    Q512C   
label values q513a    Q513A   
label values q513bu   Q513BU  
label values q513bn   Q513BN  
label values q514     Q514    
label values q515a    Q515A   
label values q515b    Q515B   
label values q516a    Q516A   
label values q516b    Q516B   
label values q517a    Q517A   
label values q517bu   Q517BU  
label values q517bn   Q517BN  
label values q518a    Q518A   
label values q518b    Q518B   
label values q518c    Q518C   
label values q518d    Q518D   
label values q519a    Q519A   
label values q519b    Q519B   
label values q519c    Q519C   
label values q520a    Q520A   
label values q520b    Q520B   
label values q520c    Q520C   
label values q520d    Q520D   
label values q522a    Q522A   
label values q522b    Q522B   
label values q523a    Q523A   
label values q523b    Q523B   
label values q523c    Q523C   
label values q524a    Q524A   
label values q524b    Q524B   
label values q525     Q525    
label values q526     Q526    
label values q527a    Q527A   
label values q527b    Q527B   
label values q528     Q528    
label values q529     Q529    
label values q530     Q530    
label values q531     Q531    
label values q532a    Q532A   
label values q532b    Q532B   
label values q533a    Q533A   
label values q533b    Q533B   
label values q533c    Q533C   
label values q534     Q534    
label values q535a    Q535A   
label values q535b    Q535B   
label values q535c    Q535C   
label values q535d    Q535D   
label values q535e    Q535E   
label values q536a    Q536A   
label values q536b    Q536B   
label values q536c    Q536C   
label values q537a    Q537A   
label values q537b    Q537B   
label values q537c    Q537C   
label values q538     Q538    
label values q539a    Q539A   
label values q539b    Q539B   
label values q540     Q540    
label values q541     Q541    
label values q542     Q542    
label values q601     Q601    
label values q602     Q602    
label values q603a    Q603A   
label values q603b    Q603B   
label values q603c    Q603C   
label values q603e    Q603E   
label values q603f    Q603F   
label values q603g    Q603G   
label values q603i    Q603I   
label values q603j    Q603J   
label values q604     Q604    
label values q605     Q605    
label values q606     Q606    
label values q608     Q608    
label values q608a    Q608A   
label values q609     Q609    
label values q611     Q611    
label values q612a    Q612A   
label values q612b    Q612B   
label values q613     Q613    
label values q614     Q614    
label values q615     Q615    
label values q616b    Q616B   
label values q617a    Q617A   
label values q617c    Q617C   
label values q618     Q618    
label values q619     Q619    
label values q620     Q620    
label values q621     Q621    
label values q622b    Q622B   
label values q622c    Q622C   
label values q622d    Q622D   
label values q623a    Q623A   
label values q623b    Q623B   
label values q623c    Q623C   
label values q623d    Q623D   
label values q624     Q624    
label values q625     Q625    
label values q626     Q626    
label values q627     Q627    
label values q628     Q628    
label values q630     Q630    
label values q631     Q631    
label values q633     Q633    
label values q634     Q634    
label values q635     Q635    
label values q636     Q636    
label values q637     Q637    
label values q638     Q638    
label values q639     Q639    
label values q640     Q640    
label values q701     Q701    
label values q702a    Q702A   
label values q702c    Q702C   
label values q801     Q801    
label values q802     Q802    
label values q803     Q803    
label values q804     Q804    
label values q805     Q805    
label values q806     Q806    
label values q807     Q807    
label values q808a    Q808A   
label values q808b    Q808B   
label values q809     Q809    
label values q810a    Q810A   
label values q810c    Q810C   
label values q811a    Q811A   
label values q811b    Q811B   
label values q812a    Q812A   
label values q812b    Q812B   
label values q813ad   Q813AD  
label values q813am   Q813AM  
label values q813ay   Q813AY  
label values q813b    Q813B   
label values q814ad   Q814AD  
label values q814am   Q814AM  
label values q814ay   Q814AY  
label values q814b    Q814B   
label values q815ad   Q815AD  
label values q815am   Q815AM  
label values q815ay   Q815AY  
label values q815b    Q815B   
label values q901a    Q901A   
label values q901b    Q901B   
label values q902a    Q902A   
label values q902b    Q902B   
label values q902c    Q902C   
label values q903     Q903    
label values q904     Q904    
label values q905     Q905    
label values q906     Q906    
label values q907     Q907    
label values q908     Q908    
label values q909     Q909    
label values q910     Q910    
label values q1001a   Q1001A  
label values q1001b   Q1001B  
label values q1002ad  Q1002AD 
label values q1002am  Q1002AM 
label values q1002ay  Q1002AY 
label values q1002bd  Q1002BD 
label values q1002bm  Q1002BM 
label values q1002by  Q1002BY 
label values q1003a   Q1003A  
label values q1003b   Q1003B  
label values q1003c   Q1003C  
label values q1003d   Q1003D  
label values q1004a   Q1004A  
label values q1004b   Q1004B  
label values q1005d   Q1005D  
label values q1005m   Q1005M  
label values q1005y   Q1005Y  
label values q1006    Q1006   
label values cddeathp CDDEATHP
