infix using "C:\COUNTRIES\GH7J\GHIQ7JFL.dct"

label variable qhclust  "Cluster number"
label variable qhnumber "Household number"
label variable qline    "Individual line number"
label variable qregion  "Region"
label variable qdistr   "District"
label variable qintd    "Day of interview"
label variable qintm    "Month of interview"
label variable qinty    "Year of interview"
label variable qintnum  "Interviewer number"
label variable qresult  "Result of individual interview"
label variable qvisits  "Total number of visits"
label variable qsuperv  "Supervisor number"
label variable qlangq   "Language of questionnaire"
label variable qlangi   "Language of interview"
label variable qlangr   "Language of respondent"
label variable qtrans   "Translator used"
label variable qintc    "Date of interview (CMC)"
label variable qintcd   "Date of interview Century Day Code (CDC)"
label variable qweight  "Sample weight (6 decimals)"
label variable qtype    "Type of place of residence"
label variable qconsent "Consent agreement"
label variable q101h    "Start of interview (hour)"
label variable q101m    "Start of interview (minutes)"
label variable q102     "Time living in place of interview"
label variable q103     "Lived in a city/town or rural area"
label variable q104     "Region lived before moved to place of interview"
label variable q105m    "Month of birth"
label variable q105y    "Year of birth"
label variable q106     "Current age of respondent"
label variable q107     "Ever attended school"
label variable q108     "Highest educational level"
label variable q109     "Highest grade/form/year at that level"
label variable q111     "Sentence read"
label variable q113     "Reads newspaper"
label variable q114     "Listens to radio"
label variable q115     "Watches television"
label variable q116     "Own a mobile telephone"
label variable q117     "Use mobile telephone for financial transactions"
label variable q118     "Have a bank or other financial account"
label variable q119     "Have ever used the internet"
label variable q120     "Have used the internet last 12 months"
label variable q121     "How often used internet the last month"
label variable q122     "Religion"
label variable q123     "Ethnicity"
label variable q105c    "Date of birth (CMC)"
label variable q105f    "Date flag for Q105C"
label variable q106c    "Age of respondent calculated"
label variable q108a    "Highest educational level"
label variable qwftotal "All woman factor - total"
label variable qwftype  "All woman factor - urban/rural"
label variable qwfreg   "All woman factor - regional"
label variable qwfeduc  "All woman factor - educational"
label variable qwfwlth  "All woman factor - wealth index"
label variable q201     "Ever given birth"
label variable q202     "Sons or daughters living with"
label variable q203a    "Sons at home"
label variable q203b    "Daughters at home"
label variable q204     "Sons or daughters living away"
label variable q205a    "Sons living elsewhere"
label variable q205b    "Daughters living elsewhere"
label variable q206     "Sons or daughters who died"
label variable q206aa   "Boys who died"
label variable q206ab   "Girls who died"
label variable q207a    "Ever had miscarriage"
label variable q207b    "Number of miscarriages"
label variable q207c    "Ever had abortion"
label variable q207d    "Number of abortions"
label variable q207e    "Ever had a stillbirth"
label variable q207f    "Number of stillbirths"
label variable q208a    "Total births"
label variable q208b    "Total pregnancy outcomes"
label variable q208c    "Total pregnancies with no live births"
label variable q209     "Probe to pregnancies"
label variable q222     "Birth between last & interview"
label variable q224a    "Abortions since January 2012"
label variable q224ay   "Year of most recent abortion in 2012 or after"
label variable q224b    "Miscarriages since January 2012"
label variable q224by   "Year of most recent miscarriage in 2012 or after"
label variable q224c    "Births since January 2012"
label variable q224d    "Stillbirths since January 2012"
label variable q226     "Currently pregnant"
label variable q227     "Duration of current pregnancy"
label variable q228     "Wanted pregnancy at that time"
label variable q229     "Wanted pregnancy"
label variable q230u    "Time since last period (unit)"
label variable q230n    "Time since last period (number)"
label variable q231     "Knowledge of fertile period"
label variable q232     "When is the fertile period"
label variable q233     "After birth, can a woman get pregnant before period returns"
label variable q227c    "Date of conception (CMC)"
label variable q227f    "Date flag for Q227C"
label variable q238f    "Flag for Q239"
label variable q301n_01 "Contraceptive method"
label variable q301n_02 "Contraceptive method"
label variable q301n_03 "Contraceptive method"
label variable q301n_04 "Contraceptive method"
label variable q301n_05 "Contraceptive method"
label variable q301n_06 "Contraceptive method"
label variable q301n_07 "Contraceptive method"
label variable q301n_08 "Contraceptive method"
label variable q301n_09 "Contraceptive method"
label variable q301n_10 "Contraceptive method"
label variable q301n_11 "Contraceptive method"
label variable q301n_12 "Contraceptive method"
label variable q301n_13 "Contraceptive method"
label variable q301n_14 "Contraceptive method"
label variable q301_01  "Heard of method"
label variable q301_02  "Heard of method"
label variable q301_03  "Heard of method"
label variable q301_04  "Heard of method"
label variable q301_05  "Heard of method"
label variable q301_06  "Heard of method"
label variable q301_07  "Heard of method"
label variable q301_08  "Heard of method"
label variable q301_09  "Heard of method"
label variable q301_10  "Heard of method"
label variable q301_11  "Heard of method"
label variable q301_12  "Heard of method"
label variable q301_13  "Heard of method"
label variable q301_14  "Heard of method"
label variable q303     "Currently using any method"
label variable q304     "Current contraceptive method"
label variable q305     "Know source for FP"
label variable q306     "Place known for FP"
label variable q304n    "Current contraceptive method (major method)"
label variable q403     "Line number"
label variable q405     "Received antenatal care for pregnancy"
label variable q406     "Reason not seeing anyone for antenatal care"
label variable q407     "Provider of antenatal care for pregnancy"
label variable q408     "Where antenatal care took place"
label variable q409     "Months pregnant at first antenatal care"
label variable q410     "First antenatal care because of problems or checkup"
label variable q411     "Problems during first antenatal care"
label variable q412     "Antenatal visits during pregnancy"
label variable q413a    "Antenatal care: Blood pressure"
label variable q413b    "Antenatal care: Urine sample"
label variable q413c    "Antenatal care: Blood sample"
label variable q413d    "Antenatal care: Weight"
label variable q413e    "During any antenatal care told about pregnancy complications"
label variable q413f    "Told about where to go if had any complications"
label variable q414     "Tetanus injection during pregnancy"
label variable q415     "Number of tetanus injections"
label variable q417     "Tetanus injections before pregnancy"
label variable q418     "Number of tetanus injections before pregnancy"
label variable q419     "Years ago received last tetanus injection before pregnancy"
label variable q420     "Iron tablets during pregnancy"
label variable q421     "Number of days took iron tablets"
label variable q422     "Drugs for intestinal parasites"
label variable q423     "During pregnancy took SP/Fansidar for malaria"
label variable q424     "How many times took SP/Fansidar (Malaria)"
label variable q425     "Took SP/Fansidar during antenatal visit (Malaria)"
label variable q426b    "Size of child at birth"
label variable q427     "Weighed at birth"
label variable q428u    "Weight at birth (units)"
label variable q428n    "Weight in Kilograms"
label variable q429     "Assistance at delivery"
label variable q430     "Place of delivery"
label variable q431a    "Reason not delivering at hospital/health centre"
label variable q431ba   "Procedure at delivery: Forceps or vacuum"
label variable q431bb   "Procedure at delivery: Blood transfusion"
label variable q431bc   "Procedure at delivery: Intravenous fluid"
label variable q431c    "Suffered from any problem before/after delivery"
label variable q431d    "Problems suffered before/after delivery"
label variable q431e    "Saw anyone about the problem"
label variable q431f    "Reason not seeing anyone about the problem"
label variable q431g    "Who saw the problem"
label variable q431h    "Where was treated for the problem"
label variable q431i    "Condition improved after treated"
label variable q431j    "Referred/told to go to another place"
label variable q431k    "Where was referred/told to go for treatment"
label variable q431l    "Went to the referred place"
label variable q431m    "Reason not going to the referred place for treatment"
label variable q432u    "Time spent in health facility after delivery (Units)"
label variable q432n    "Time spent in health facility after delivery (Number)"
label variable q433a    "Delivery by caesarean section"
label variable q433b    "Timing of decision on caesarean section"
label variable q434     "Child was put on the chest immediately after birth"
label variable q434a    "Child bare skin touched respondent bare skin"
label variable q435     "Postnatal check on respondent before discharge"
label variable q436u    "First postnatal check on respondent (Units)"
label variable q436n    "First postnatal check on respondent (Number)"
label variable q437     "Person giving postnatal care to respondent"
label variable q438b    "First postnatal check on child in facility"
label variable q439u    "Time first postnatal check on child in facility (unit)"
label variable q439n    "Time first postnatal check on child in facility (number)"
label variable q440     "Person giving postnatal care to child  in facility"
label variable q441     "Checkup on respondent after discharge from place of delivery"
label variable q442u    "Time checkup on respondent after discharge (unit)"
label variable q442n    "Time checkup on respondent after discharge (number)"
label variable q443     "Person giving checkup on respondent after discharge"
label variable q444     "Place of checkup on respondent after discharge"
label variable q445b    "Health child checked in first 2 months after birth"
label variable q446u    "First postnatal check on child (unit)"
label variable q446n    "First postnatal check on child (number)"
label variable q447     "Person giving postnatal check on child"
label variable q448     "Place of first postnatal check"
label variable q449     "Respondent received postnatal check after home delivery"
label variable q450u    "Time respondent received postnatal check after home delivery (units)"
label variable q450n    "Time respondent received postnatal check after home delivery (number)"
label variable q451     "Person giving postnatal check on respondent after home delivery"
label variable q452     "Place postnatal check on respondent after home delivery"
label variable q453b    "Child received postnatal check after home delivery"
label variable q454u    "Time child received postnatal check after home delivery (units)"
label variable q454n    "Time child received postnatal check after home delivery (number)"
label variable q455     "Person giving postnatal check on child after home delivery"
label variable q456     "Place postnatal check on child after home delivery"
label variable q457a    "During first two days, health care provider: examine the cord"
label variable q457b    "During first two days, health care provider: measure temperature"
label variable q457c    "During first two days, health care provider: counsel on danger signs for newborn"
label variable q457d    "During first two days, health care provider: counsel on breastfeeding"
label variable q457e    "During first two days, health care provider: observe breastfeeding"
label variable q500     "Line number of recent abortion in 2012 or later"
label variable q501     "Year of most recent abortion in 2012 or after"
label variable q502a    "Main reason for abortion"
label variable q502b    "Any other reason for abortion"
label variable q502c    "Other reasons for abortion"
label variable q503     "Partner's attitude toward abortion"
label variable q504     "Multiple steps to end pregnancy"
label variable q505u    "Time between first attempt and final (Units)"
label variable q505n    "Time between first attempt and final (Number)"
label variable q506     "First action to end pregnancy"
label variable q507     "Provider for first step to end pregnancy"
label variable q508     "Source for first step to end pregnancy"
label variable q509a    "Anything paid to get procedure done"
label variable q509b    "Person who paid for first step to end pregnancy"
label variable q510     "Bleeding from first step to end pregnancy"
label variable q511     "Bleeding was mild/moderate/severe"
label variable q512     "Pain from first step to end pregnancy"
label variable q513     "Pain was mild/moderate/severe"
label variable q514     "Fever from first step to end pregnancy"
label variable q515     "Fever was mild/moderate/severe"
label variable q516     "Injury or perforation from first step to end pregnancy"
label variable q517     "Injury or perforation was mild/moderate/severe"
label variable q518     "Vaginal discharge from first step to end pregnancy"
label variable q519     "Vaginal discharge was mild/moderate/severe"
label variable q520     "Any other problem (1) from first step to end pregnancy"
label variable q521     "Problem (1) from first step to end pregnancy"
label variable q522     "Problem (1) mild/moderate/severe from first step to end pregnancy"
label variable q523     "Any other problem (2) from first step to end pregnancy"
label variable q524     "Problem (2) from first step to end pregnancy"
label variable q525     "Problem (2) mild/moderate/severe from first step to end pregnancy"
label variable q526     "Any other problem (3) from first step to end pregnancy"
label variable q527     "Problem (3) from first step to end pregnancy"
label variable q528     "Problem (3) mild/moderate/severe from first step to end pregnancy"
label variable q529     "Any other problem (4) from first step to end pregnancy"
label variable q530     "Problem (4) from first step to end pregnancy"
label variable q531     "Problem (4) mild/moderate/severe from first step to end pregnancy"
label variable q532     "Took any pain relievers after first step to end pregnancy"
label variable q533     "Last action to end pregnancy"
label variable q534     "Provider for last step to end pregnancy"
label variable q535     "Source for last step to end pregnancy"
label variable q536a    "Anything paid to get procedure done"
label variable q536b    "Person who paid for last step to end pregnancy"
label variable q537     "Took antibiotics after abortion"
label variable q538     "Took any pain relievers after last step to end pregnancy"
label variable q539b    "Local anesthesia for abortion"
label variable q540     "Health problems in first month after abortion"
label variable q541     "Bleeding in first month after abortion"
label variable q542     "Bleeding was mild/moderate/severe"
label variable q543     "Pain in first month after abortion"
label variable q544     "Pain was mild/moderate/severe"
label variable q545     "Fever in first month after abortion"
label variable q546     "Fever was mild/moderate/severe"
label variable q547     "Injury or perforation in first month after abortion"
label variable q548     "Injury or perforation was mild/moderate/severe"
label variable q549     "Foul-smelling discharge in first month after abortion"
label variable q550     "Foul-smelling discharge was mild/moderate/severe"
label variable q551     "Any other problem (1) in first month after abortion"
label variable q552     "Problem (1) in first month after abortion"
label variable q553     "Problem (1) mild/moderate/severe in first month after abortion"
label variable q554     "Any other problem (2) in first month after abortion"
label variable q555     "Problem (2) in first month after abortion"
label variable q556     "Problem (2) mild/moderate/severe in first month after abortion"
label variable q557     "Any other problem (3) in first month after abortion"
label variable q558     "Problem (3) in first month after abortion"
label variable q559     "Problem (3) mild/moderate/severe in first month after abortion"
label variable q560     "Any other problem (4) in first month after abortion"
label variable q561     "Problem (4) in first month after abortion"
label variable q562     "Problem (4) mild/moderate/severe in first month after abortion"
label variable q563b    "Received treatment for health problems due to abortion"
label variable q564     "Type of treatment received for health problems due to abortion"
label variable q565     "Source of treatment for health problems due to abortion"
label variable q566a    "Spent any nights in a health facility in the first month after abortion"
label variable q566bu   "Time spent in health facility due to abortion (Units)"
label variable q566bn   "Time spent in health facility due to abortion (Number)"
label variable q567     "Visited by doctor or health worker before or after abortion"
label variable q568     "Any health problems six months after abortion"
label variable q569     "Health problems six months after abortion"
label variable q570     "Using contraception at the time she became pregnant"
label variable q571     "Contraception used at the time she became pregnant"
label variable q572     "Health professional spoke about contraception before or after abortion"
label variable q573     "When health professional spoke about contraception"
label variable q574     "Health worker gave contraception method or FP advice after abortion"
label variable q575     "Given method of contraception, prescription or referral after abortion"
label variable q577     "Ever heard of abortion"
label variable q578     "Could decide on your own to get an abortion"
label variable q579     "Knows where to get an abortion"
label variable q580     "Where to go for abortion"
label variable q581     "Abortion legal in Ghana"
label variable q582     "Conditions of legal abortion in Ghana"
label variable q600     "Line number of recent miscarriage in 2012 or later"
label variable q601     "Year of most recent miscarriage in 2012 or after"
label variable q602     "Cause of miscarriage"
label variable q603     "Where miscarriage occurred"
label variable q604a    "Sought help for miscarriage"
label variable q604b    "From whom sought help for miscarriage"
label variable q604c    "Place got help for miscarriage"
label variable q605     "Uterus cleaned after miscarriage"
label variable q606     "Method to clean uterus"
label variable q607     "Took antibiotics after miscarriage"
label variable q608     "Given pain relievers after miscarriage"
label variable q609b    "Anesthesia for miscarriage"
label variable q610     "Any health problems due to miscarriage"
label variable q611     "Bleeding from miscarriage"
label variable q612     "Bleeding was mild/moderate/severe"
label variable q613     "Pain from miscarriage"
label variable q614     "Pain was mild/moderate/severe"
label variable q615     "Fever from miscarriage"
label variable q616     "Fever was mild/moderate/severe"
label variable q617     "Injury or perforation from miscarriage"
label variable q618     "Injury or perforation was mild/moderate/severe"
label variable q619     "Foul-smelling discharge from miscarriage"
label variable q620     "Foul-smelling discharge was mild/moderate/severe"
label variable q621     "Any other problem (1) from miscarriage"
label variable q622     "Problem (1) from miscarriage"
label variable q623     "Problem (1) mild/moderate/severe from miscarriage"
label variable q624     "Any other problem (2) from miscarriage"
label variable q625     "Problem (2) from miscarriage"
label variable q626     "Problem (2) mild/moderate/severe from miscarriage"
label variable q627     "Any other problem (3) from miscarriage"
label variable q628     "Problem (3) from miscarriage"
label variable q629     "Problem (3) mild/moderate/severe from miscarriage"
label variable q630     "Any other problem (4) from miscarriage"
label variable q631     "Problem (4) from miscarriage"
label variable q632     "Problem (4) mild/moderate/severe from miscarriage"
label variable q633     "Received treatment for health problems due to miscarriage"
label variable q634     "Type of treatment received for health problems due to miscarriage"
label variable q635     "Source of treatment for health problems due to miscarriage"
label variable q636a    "Spent any nights in a health facility in the first month after miscarriage"
label variable q636bu   "Time spent in health facility due to miscarriage (Units)"
label variable q636bn   "Time spent in health facility due to miscarriage (Number)"
label variable q637     "Visited by doctor or health worker before or after miscarriage"
label variable q638     "Any health problems six months after miscarriage"
label variable q639     "Health problems six months after miscarriage"
label variable q640     "Using contraception at the time she became pregnant"
label variable q641     "Contraception used at the time she became pregnant"
label variable q642     "Health professional spoke about contraception before or after miscarriage"
label variable q643     "When health professional spoke about contraception"
label variable q644     "Health worker gave contraception method or FP advice after miscarriage"
label variable q645     "Given method of contraception, prescription or referral after miscarriage"
label variable q701     "Currently in union"
label variable q702     "Have ever been married or lived with a man"
label variable q703     "Current marital status"
label variable q704     "Partner living with respondent"
label variable q705     "Line number of husband"
label variable q706     "Husband has other wives"
label variable q707     "Number of wives including respondent"
label variable q708     "Wife's rank number"
label variable q709     "In union more than once"
label variable q710m    "Time of first union (month)"
label variable q710y    "Time of first union (year)"
label variable q711     "Age at first union"
label variable q713     "Age at first intercourse"
label variable q714u    "Time since last intercourse (unit)"
label variable q714n    "Time since last intercourse (number)"
label variable q710c    "Date of first union (CMC)"
label variable q710f    "Date flag for Q710C"
label variable q711c    "Age at first union (calculated)"
label variable q713f    "Flag for Q713"
label variable q714f    "Flag for Q714"
label variable q813_01  "Column number"
label variable q813_02  "Column number"
label variable q813_03  "Column number"
label variable q813_04  "Column number"
label variable q813_05  "Column number"
label variable q813_06  "Column number"
label variable q813_07  "Column number"
label variable q813_08  "Column number"
label variable q813_09  "Column number"
label variable q813_10  "Column number"
label variable q813_11  "Column number"
label variable q813_12  "Column number"
label variable q813_13  "Column number"
label variable q813_14  "Column number"
label variable q813_15  "Column number"
label variable q813_16  "Column number"
label variable q813_17  "Column number"
label variable q813_18  "Column number"
label variable q813_19  "Column number"
label variable q813_20  "Column number"
label variable q814_01  "Sex of sibling"
label variable q814_02  "Sex of sibling"
label variable q814_03  "Sex of sibling"
label variable q814_04  "Sex of sibling"
label variable q814_05  "Sex of sibling"
label variable q814_06  "Sex of sibling"
label variable q814_07  "Sex of sibling"
label variable q814_08  "Sex of sibling"
label variable q814_09  "Sex of sibling"
label variable q814_10  "Sex of sibling"
label variable q814_11  "Sex of sibling"
label variable q814_12  "Sex of sibling"
label variable q814_13  "Sex of sibling"
label variable q814_14  "Sex of sibling"
label variable q814_15  "Sex of sibling"
label variable q814_16  "Sex of sibling"
label variable q814_17  "Sex of sibling"
label variable q814_18  "Sex of sibling"
label variable q814_19  "Sex of sibling"
label variable q814_20  "Sex of sibling"
label variable q815_01  "Sibling alive"
label variable q815_02  "Sibling alive"
label variable q815_03  "Sibling alive"
label variable q815_04  "Sibling alive"
label variable q815_05  "Sibling alive"
label variable q815_06  "Sibling alive"
label variable q815_07  "Sibling alive"
label variable q815_08  "Sibling alive"
label variable q815_09  "Sibling alive"
label variable q815_10  "Sibling alive"
label variable q815_11  "Sibling alive"
label variable q815_12  "Sibling alive"
label variable q815_13  "Sibling alive"
label variable q815_14  "Sibling alive"
label variable q815_15  "Sibling alive"
label variable q815_16  "Sibling alive"
label variable q815_17  "Sibling alive"
label variable q815_18  "Sibling alive"
label variable q815_19  "Sibling alive"
label variable q815_20  "Sibling alive"
label variable q816_01  "Age of sibling"
label variable q816_02  "Age of sibling"
label variable q816_03  "Age of sibling"
label variable q816_04  "Age of sibling"
label variable q816_05  "Age of sibling"
label variable q816_06  "Age of sibling"
label variable q816_07  "Age of sibling"
label variable q816_08  "Age of sibling"
label variable q816_09  "Age of sibling"
label variable q816_10  "Age of sibling"
label variable q816_11  "Age of sibling"
label variable q816_12  "Age of sibling"
label variable q816_13  "Age of sibling"
label variable q816_14  "Age of sibling"
label variable q816_15  "Age of sibling"
label variable q816_16  "Age of sibling"
label variable q816_17  "Age of sibling"
label variable q816_18  "Age of sibling"
label variable q816_19  "Age of sibling"
label variable q816_20  "Age of sibling"
label variable q817_01  "Years since siblings death"
label variable q817_02  "Years since siblings death"
label variable q817_03  "Years since siblings death"
label variable q817_04  "Years since siblings death"
label variable q817_05  "Years since siblings death"
label variable q817_06  "Years since siblings death"
label variable q817_07  "Years since siblings death"
label variable q817_08  "Years since siblings death"
label variable q817_09  "Years since siblings death"
label variable q817_10  "Years since siblings death"
label variable q817_11  "Years since siblings death"
label variable q817_12  "Years since siblings death"
label variable q817_13  "Years since siblings death"
label variable q817_14  "Years since siblings death"
label variable q817_15  "Years since siblings death"
label variable q817_16  "Years since siblings death"
label variable q817_17  "Years since siblings death"
label variable q817_18  "Years since siblings death"
label variable q817_19  "Years since siblings death"
label variable q817_20  "Years since siblings death"
label variable q818_01  "Age of sibling at death"
label variable q818_02  "Age of sibling at death"
label variable q818_03  "Age of sibling at death"
label variable q818_04  "Age of sibling at death"
label variable q818_05  "Age of sibling at death"
label variable q818_06  "Age of sibling at death"
label variable q818_07  "Age of sibling at death"
label variable q818_08  "Age of sibling at death"
label variable q818_09  "Age of sibling at death"
label variable q818_10  "Age of sibling at death"
label variable q818_11  "Age of sibling at death"
label variable q818_12  "Age of sibling at death"
label variable q818_13  "Age of sibling at death"
label variable q818_14  "Age of sibling at death"
label variable q818_15  "Age of sibling at death"
label variable q818_16  "Age of sibling at death"
label variable q818_17  "Age of sibling at death"
label variable q818_18  "Age of sibling at death"
label variable q818_19  "Age of sibling at death"
label variable q818_20  "Age of sibling at death"
label variable q819_01  "Died while pregnant"
label variable q819_02  "Died while pregnant"
label variable q819_03  "Died while pregnant"
label variable q819_04  "Died while pregnant"
label variable q819_05  "Died while pregnant"
label variable q819_06  "Died while pregnant"
label variable q819_07  "Died while pregnant"
label variable q819_08  "Died while pregnant"
label variable q819_09  "Died while pregnant"
label variable q819_10  "Died while pregnant"
label variable q819_11  "Died while pregnant"
label variable q819_12  "Died while pregnant"
label variable q819_13  "Died while pregnant"
label variable q819_14  "Died while pregnant"
label variable q819_15  "Died while pregnant"
label variable q819_16  "Died while pregnant"
label variable q819_17  "Died while pregnant"
label variable q819_18  "Died while pregnant"
label variable q819_19  "Died while pregnant"
label variable q819_20  "Died while pregnant"
label variable q820_01  "Died during childbirth"
label variable q820_02  "Died during childbirth"
label variable q820_03  "Died during childbirth"
label variable q820_04  "Died during childbirth"
label variable q820_05  "Died during childbirth"
label variable q820_06  "Died during childbirth"
label variable q820_07  "Died during childbirth"
label variable q820_08  "Died during childbirth"
label variable q820_09  "Died during childbirth"
label variable q820_10  "Died during childbirth"
label variable q820_11  "Died during childbirth"
label variable q820_12  "Died during childbirth"
label variable q820_13  "Died during childbirth"
label variable q820_14  "Died during childbirth"
label variable q820_15  "Died during childbirth"
label variable q820_16  "Died during childbirth"
label variable q820_17  "Died during childbirth"
label variable q820_18  "Died during childbirth"
label variable q820_19  "Died during childbirth"
label variable q820_20  "Died during childbirth"
label variable q821_01  "Died within 2 months of delivery"
label variable q821_02  "Died within 2 months of delivery"
label variable q821_03  "Died within 2 months of delivery"
label variable q821_04  "Died within 2 months of delivery"
label variable q821_05  "Died within 2 months of delivery"
label variable q821_06  "Died within 2 months of delivery"
label variable q821_07  "Died within 2 months of delivery"
label variable q821_08  "Died within 2 months of delivery"
label variable q821_09  "Died within 2 months of delivery"
label variable q821_10  "Died within 2 months of delivery"
label variable q821_11  "Died within 2 months of delivery"
label variable q821_12  "Died within 2 months of delivery"
label variable q821_13  "Died within 2 months of delivery"
label variable q821_14  "Died within 2 months of delivery"
label variable q821_15  "Died within 2 months of delivery"
label variable q821_16  "Died within 2 months of delivery"
label variable q821_17  "Died within 2 months of delivery"
label variable q821_18  "Died within 2 months of delivery"
label variable q821_19  "Died within 2 months of delivery"
label variable q821_20  "Died within 2 months of delivery"
label variable q822_01  "Days after end of pregnancy/childbirth sister died"
label variable q822_02  "Days after end of pregnancy/childbirth sister died"
label variable q822_03  "Days after end of pregnancy/childbirth sister died"
label variable q822_04  "Days after end of pregnancy/childbirth sister died"
label variable q822_05  "Days after end of pregnancy/childbirth sister died"
label variable q822_06  "Days after end of pregnancy/childbirth sister died"
label variable q822_07  "Days after end of pregnancy/childbirth sister died"
label variable q822_08  "Days after end of pregnancy/childbirth sister died"
label variable q822_09  "Days after end of pregnancy/childbirth sister died"
label variable q822_10  "Days after end of pregnancy/childbirth sister died"
label variable q822_11  "Days after end of pregnancy/childbirth sister died"
label variable q822_12  "Days after end of pregnancy/childbirth sister died"
label variable q822_13  "Days after end of pregnancy/childbirth sister died"
label variable q822_14  "Days after end of pregnancy/childbirth sister died"
label variable q822_15  "Days after end of pregnancy/childbirth sister died"
label variable q822_16  "Days after end of pregnancy/childbirth sister died"
label variable q822_17  "Days after end of pregnancy/childbirth sister died"
label variable q822_18  "Days after end of pregnancy/childbirth sister died"
label variable q822_19  "Days after end of pregnancy/childbirth sister died"
label variable q822_20  "Days after end of pregnancy/childbirth sister died"
label variable q823_01  "Death due to violence"
label variable q823_02  "Death due to violence"
label variable q823_03  "Death due to violence"
label variable q823_04  "Death due to violence"
label variable q823_05  "Death due to violence"
label variable q823_06  "Death due to violence"
label variable q823_07  "Death due to violence"
label variable q823_08  "Death due to violence"
label variable q823_09  "Death due to violence"
label variable q823_10  "Death due to violence"
label variable q823_11  "Death due to violence"
label variable q823_12  "Death due to violence"
label variable q823_13  "Death due to violence"
label variable q823_14  "Death due to violence"
label variable q823_15  "Death due to violence"
label variable q823_16  "Death due to violence"
label variable q823_17  "Death due to violence"
label variable q823_18  "Death due to violence"
label variable q823_19  "Death due to violence"
label variable q823_20  "Death due to violence"
label variable q824_01  "Death due to accident"
label variable q824_02  "Death due to accident"
label variable q824_03  "Death due to accident"
label variable q824_04  "Death due to accident"
label variable q824_05  "Death due to accident"
label variable q824_06  "Death due to accident"
label variable q824_07  "Death due to accident"
label variable q824_08  "Death due to accident"
label variable q824_09  "Death due to accident"
label variable q824_10  "Death due to accident"
label variable q824_11  "Death due to accident"
label variable q824_12  "Death due to accident"
label variable q824_13  "Death due to accident"
label variable q824_14  "Death due to accident"
label variable q824_15  "Death due to accident"
label variable q824_16  "Death due to accident"
label variable q824_17  "Death due to accident"
label variable q824_18  "Death due to accident"
label variable q824_19  "Death due to accident"
label variable q824_20  "Death due to accident"
label variable q816c_01 "CMC date of birth of sibling"
label variable q816c_02 "CMC date of birth of sibling"
label variable q816c_03 "CMC date of birth of sibling"
label variable q816c_04 "CMC date of birth of sibling"
label variable q816c_05 "CMC date of birth of sibling"
label variable q816c_06 "CMC date of birth of sibling"
label variable q816c_07 "CMC date of birth of sibling"
label variable q816c_08 "CMC date of birth of sibling"
label variable q816c_09 "CMC date of birth of sibling"
label variable q816c_10 "CMC date of birth of sibling"
label variable q816c_11 "CMC date of birth of sibling"
label variable q816c_12 "CMC date of birth of sibling"
label variable q816c_13 "CMC date of birth of sibling"
label variable q816c_14 "CMC date of birth of sibling"
label variable q816c_15 "CMC date of birth of sibling"
label variable q816c_16 "CMC date of birth of sibling"
label variable q816c_17 "CMC date of birth of sibling"
label variable q816c_18 "CMC date of birth of sibling"
label variable q816c_19 "CMC date of birth of sibling"
label variable q816c_20 "CMC date of birth of sibling"
label variable q817c_01 "CMC date of death of sibling"
label variable q817c_02 "CMC date of death of sibling"
label variable q817c_03 "CMC date of death of sibling"
label variable q817c_04 "CMC date of death of sibling"
label variable q817c_05 "CMC date of death of sibling"
label variable q817c_06 "CMC date of death of sibling"
label variable q817c_07 "CMC date of death of sibling"
label variable q817c_08 "CMC date of death of sibling"
label variable q817c_09 "CMC date of death of sibling"
label variable q817c_10 "CMC date of death of sibling"
label variable q817c_11 "CMC date of death of sibling"
label variable q817c_12 "CMC date of death of sibling"
label variable q817c_13 "CMC date of death of sibling"
label variable q817c_14 "CMC date of death of sibling"
label variable q817c_15 "CMC date of death of sibling"
label variable q817c_16 "CMC date of death of sibling"
label variable q817c_17 "CMC date of death of sibling"
label variable q817c_18 "CMC date of death of sibling"
label variable q817c_19 "CMC date of death of sibling"
label variable q817c_20 "CMC date of death of sibling"
label variable q901a    "Care factors: Getting permission"
label variable q901b    "Care factors: Getting money needed for treatment"
label variable q901c    "Care factors: Distance, no nearby health facility"
label variable q901d    "Care factors: Not wanting to go alone"
label variable q902     "Registered with any health insurance"
label variable q903     "Covered by health insurance"
label variable q904     "Type of health insurance"
label variable q905a    "Insurance coverage: Antenatal"
label variable q905b    "Insurance coverage: Childbirth"
label variable q905c    "Insurance coverage: Postnatal care for mother"
label variable q905d    "Insurance coverage: Postnatal care for child"
label variable q905e    "Insurance coverage: Cash benefits"
label variable q905f    "Insurance coverage: Other maternity benefits"
label variable q906     "Pay for drugs/services"
label variable q908     "Asked to make any payment during antenatal care"
label variable q909a    "Asked to pay for services during antenatal care"
label variable q909b    "Asked to pay for drugs during antenatal care"
label variable q909c    "Asked to pay for laboratory tests during antenatal care"
label variable q909d    "Asked to pay for other supplies during antenatal care"
label variable q909e    "Asked to pay for anything else during antenatal care"
label variable q911     "Asked to make any payment during delivery"
label variable q912a    "Asked to pay for services during delivery"
label variable q912b    "Asked to pay for drugs during delivery"
label variable q912c    "Asked to pay for laboratory tests during delivery"
label variable q912d    "Asked to pay for other supplies during delivery"
label variable q912e    "Asked to pay for anything else during delivery"
label variable q914     "Asked to make any payment for checks on woman health after given birth"
label variable q916     "Asked to make any payment for checks on child health after given birth"
label variable q917     "Wears glasses or contact lens"
label variable q918     "Type of seeing difficulty using glasses or contact lens"
label variable q919     "Type of seeing difficulty"
label variable q920     "Type of hearing difficulty"
label variable q921     "Type of communication difficulty"
label variable q922     "Type of remembering difficulty"
label variable q923     "Type of walking/climbing steps difficulty"
label variable q924     "Type of washing/cleaning difficulty"
label variable q925h    "End of interview (hour)"
label variable q925m    "End of interview (minutes)"

#delimit ;
label define QREGION 
     1 "Western"
     2 "Central"
     3 "Greater accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Brong ahafo"
     8 "Northern"
     9 "Upper east"
    10 "Upper west"
;
label define QINTM   
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
;
label define QRESULT 
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define QLANGQ  
     0 "English"
     1 "Akan"
     2 "Ga"
     3 "Ewe"
;
label define QLANGI  
     0 "English"
     1 "Akan"
     2 "Ga"
     3 "Ewe"
     4 "Guan"
     5 "Mole-dagbani"
     6 "Grusi"
     7 "Gurma"
     8 "Mande"
    96 "Other"
;
label define QLANGR  
     0 "English"
     1 "Akan"
     2 "Ga"
     3 "Ewe"
     4 "Guan"
     5 "Mole-dagbani"
     6 "Grusi"
     7 "Gurma"
     8 "Mande"
    96 "Other"
;
label define QTRANS  
     1 "Yes"
     2 "No"
;
label define QTYPE   
     1 "Urban"
     2 "Rural"
;
label define QCONSENT
     1 "Respondent agrees to be interviewed"
     2 "Respondent does not agree to be interviewed"
;
label define Q101H   
    97 "Inconsistent"
;
label define Q101M   
    97 "Inconsistent"
;
label define Q102    
     0 "Less than one year"
    95 "Always"
    96 "Visitor"
;
label define Q103    
     1 "City"
     2 "Town"
     3 "Rural area"
;
label define Q104    
     1 "Western"
     2 "Central"
     3 "Greater accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Brong ahafo"
     8 "Northern"
     9 "Upper east"
    10 "Upper west"
    96 "Outside of ghana"
;
label define Q105M   
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    98 "Don't know month"
;
label define Q105Y   
  9998 "Don't know year"
;
label define Q106    
    98 "DK"
;
label define Q107    
     1 "Yes"
     2 "No"
;
label define Q108    
     1 "Primary"
     2 "Middle"
     3 "Jss/jhs"
     4 "Secondary/Tech/Voc/Comm"
     5 "Sss/Shs/Tech/Voc/Comm"
     6 "Higher"
;
label define Q109    
     0 "Less than one year"
;
label define Q111    
     1 "Cannot read at all"
     2 "Able to read only part of the sentence"
     3 "Able to read whole sentence"
     4 "No card with required language"
     5 "Blind/visually impaired"
;
label define Q113    
     1 "At least once a week"
     2 "Less than once a week"
     3 "Not at all"
;
label define Q114    
     1 "At least once a week"
     2 "Less than once a week"
     3 "Not at all"
;
label define Q115    
     1 "At least once a week"
     2 "Less than once a week"
     3 "Not at all"
;
label define Q116    
     1 "Yes"
     2 "No"
;
label define Q117    
     1 "Yes"
     2 "No"
;
label define Q118    
     1 "Yes"
     2 "No"
;
label define Q119    
     1 "Yes"
     2 "No"
;
label define Q120    
     1 "Yes"
     2 "No"
;
label define Q121    
     1 "Almost every day"
     2 "At least once a week"
     3 "Less than once a week"
     4 "Not at all"
;
label define Q122    
     1 "Catholic"
     2 "Anglican"
     3 "Methodist"
     4 "Presbyterian"
     5 "Pentecostal/charismatic"
     6 "Other christian"
     7 "Islam"
     8 "Traditional/spiritualist"
     9 "No religion"
    96 "Other"
;
label define Q123    
     1 "Akan"
     2 "Ga/dangme"
     3 "Ewe"
     4 "Guan"
     5 "Mole-dagbani"
     6 "Grusi"
     7 "Gurma"
     8 "Mande"
    96 "Other"
;
label define Q105F   
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define Q108A   
     0 "No education"
     1 "Primary incomplete"
     2 "Primary complete"
     3 "Secondary incomplete"
     4 "Secondary complete"
     5 "Higher"
;
label define QWFTOTAL
     0 "NotAppl"
;
label define QWFTYPE 
     0 "NotAppl"
;
label define QWFREG  
     0 "NotAppl"
;
label define QWFEDUC 
     0 "NotAppl"
;
label define QWFWLTH 
     0 "NotAppl"
;
label define Q201    
     1 "Yes"
     2 "No"
;
label define Q202    
     1 "Yes"
     2 "No"
;
label define Q204    
     1 "Yes"
     2 "No"
;
label define Q206    
     1 "Yes"
     2 "No"
;
label define Q207A   
     1 "Yes"
     2 "No"
;
label define Q207C   
     1 "Yes"
     2 "No"
;
label define Q207E   
     1 "Yes"
     2 "No"
;
label define Q209    
     1 "Yes, is correct"
     2 "No, is not correct"
;
label define Q222    
     1 "Yes"
     2 "No"
;
label define Q224A   
     0 "None"
;
label define Q224AY  
     0 "None"
  2012 "2012"
  2013 "2013"
  2014 "2014"
  2015 "2015"
  2016 "2016"
  2017 "2017"
  9998 "DK year"
;
label define Q224B   
     0 "None"
;
label define Q224BY  
     0 "None"
  2012 "2012"
  2013 "2013"
  2014 "2014"
  2015 "2015"
  2016 "2016"
  2017 "2017"
  9998 "DK year"
;
label define Q224C   
     0 "None"
;
label define Q224D   
     0 "None"
;
label define Q226    
     1 "Yes"
     2 "No"
     8 "Unsure"
;
label define Q228    
     1 "Yes"
     2 "No"
;
label define Q229    
     1 "Later"
     2 "No more/none"
;
label define Q230U   
     1 "Days ago"
     2 "Weeks ago"
     3 "Months ago"
     4 "Years ago"
     9 "Special answers"
;
label define Q230N   
    94 "In menopause, has had hysterectomy"
    95 "Before last birth"
    96 "Never menstruated"
    98 "Don't know"
;
label define Q231    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q232    
     1 "Just before her period begins"
     2 "During her period"
     3 "Right after her period has ended"
     4 "Halfway between two periods"
     6 "Other"
     8 "Don't know"
;
label define Q233    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q227F   
     7 "Month - exact date"
     8 "None - imputed"
;
label define Q238F   
     1 "N > interval since birth"
     2 "N + amenorrhea > interval"
     3 "N, but period not returned"
     4 "95, but no birth"
     5 "95, but period returned"
     6 "96, but period returned"
     7 "N, last period in pregnancy"
     8 "96, had children"
     9 "N, period before last birth"
;
label define Q301N   
     1 "Female Sterilization"
     2 "Male Sterilization"
     3 "IUD"
     4 "Injectables"
     5 "Implants"
     6 "Pill"
     7 "Condom"
     8 "Female condom"
     9 "Emergency contraception"
    10 "Lactational amenorrhea method (LAM)"
    11 "Rhythm method"
    12 "Withdrawal"
    13 "Other modern method"
    14 "Other traditional method"
;
label define Q301    
     1 "Yes"
     2 "No"
;
label define Q303    
     1 "Yes"
     2 "No"
;
label define Q305    
     1 "Yes"
     2 "No"
;
label define Q304N   
     1 "Female Sterilization"
     2 "Male Sterilization"
     3 "IUD"
     4 "Injectables"
     5 "Implants"
     6 "Pill"
     7 "Condom"
     8 "Female condom"
     9 "Diaphragm"
    10 "Foam/jelly"
    11 "Emergency contraception"
    12 "Lactational amenorrhea method (LAM)"
    13 "Rhythm method"
    14 "Withdrawal"
    95 "Other modern method"
    96 "Other traditional method"
;
label define Q405    
     1 "Yes"
     2 "No"
;
label define Q409    
    98 "Don't know"
;
label define Q410    
     1 "Problem"
     2 "Just checkup"
;
label define Q412    
    98 "Don't know"
;
label define Q413A   
     1 "Yes"
     2 "No"
;
label define Q413B   
     1 "Yes"
     2 "No"
;
label define Q413C   
     1 "Yes"
     2 "No"
;
label define Q413D   
     1 "Yes"
     2 "No"
;
label define Q413E   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q413F   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q414    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q415    
     7 "7 or more"
     8 "Don't know"
;
label define Q417    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q418    
     7 "7 or more"
     8 "Don't know"
;
label define Q420    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q421    
     0 "Didn't take any"
   998 "Don't know"
;
label define Q422    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q423    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q424    
    98 "Don't know"
;
label define Q425    
     1 "Antenatal visit"
     2 "Another facility visit"
     6 "Other source"
;
label define Q426B   
     1 "Very large"
     2 "Larger than average"
     3 "Average"
     4 "Smaller than average"
     5 "Very small"
     8 "Don't know"
;
label define Q427    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q428U   
     1 "Kilograms from card"
     2 "Kilograms from recall"
     9 "Special answers"
;
label define Q430    
    11 "Her home"
    12 "Other home"
    21 "Public: Govt hospital"
    22 "Public: Govt health center/clinic"
    23 "Public: Govt health post/chps"
    24 "Public: Mobile clinic/outreach"
    26 "Public: Other public sector"
    31 "Private: Hospital/clinic"
    32 "Private: Fp/ppag clinic"
    33 "Private: Mobile clinic/outreach"
    34 "Private: Maternity home"
    36 "Private: Other private med sector"
    96 "Other"
;
label define Q431BA  
     1 "Yes"
     2 "No"
;
label define Q431BB  
     1 "Yes"
     2 "No"
;
label define Q431BC  
     1 "Yes"
     2 "No"
;
label define Q431C   
     1 "Yes"
     2 "No"
;
label define Q431E   
     1 "Yes"
     2 "No"
;
label define Q431H   
    11 "Her home"
    12 "Other home"
    21 "Public: Govt hospital"
    22 "Public: Govt health center/clinic"
    23 "Public: Govt health post/chps"
    24 "Public: Mobile clinic/outreach"
    26 "Public: Other public sector"
    31 "Private: Hospital/clinic"
    32 "Private: Fp/ppag clinic"
    33 "Private: Mobile clinic/outreach"
    34 "Private: Maternity home"
    36 "Private: Other private med sector"
    96 "Other"
;
label define Q431I   
     1 "No change"
     2 "Improved"
     3 "Worsened"
     8 "Don't know"
;
label define Q431J   
     1 "Yes"
     2 "No"
;
label define Q431K   
    21 "Public: Govt hospital"
    22 "Public: Govt health center/clinic"
    23 "Public: Govt health post/chps"
    24 "Public: Mobile clinic/outreach"
    26 "Public: Other public sector"
    31 "Private: Hospital/clinic"
    32 "Private: Fp/ppag clinic"
    33 "Private: Mobile clinic/outreach"
    34 "Private: Maternity home"
    36 "Private: Other private med sector"
    96 "Other"
;
label define Q431L   
     1 "Yes"
     2 "No"
;
label define Q432U   
     1 "Hours"
     2 "Days"
     3 "Weeks"
     9 "Special answers"
;
label define Q432N   
    98 "Don't know"
;
label define Q433A   
     1 "Yes"
     2 "No"
;
label define Q433B   
     1 "Before"
     2 "After"
;
label define Q434    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q434A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q435    
     1 "Yes"
     2 "No"
;
label define Q436U   
     1 "Hours"
     2 "Days"
     3 "Weeks"
     9 "Special answers"
;
label define Q436N   
    98 "Don't know"
;
label define Q437    
    11 "Health personnel: Doctor"
    12 "Health personnel: Nurse/midwife"
    13 "Health personnel: Com  health officer/nurse"
    21 "Other person: Traditional birth attendant"
    22 "Other person: Village health volunteer"
    23 "Other person: Traditional health practitioner"
    96 "Other"
;
label define Q438B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q439U   
     1 "Hours"
     2 "Days"
     3 "Weeks"
     9 "Special answers"
;
label define Q439N   
    98 "Don't know"
;
label define Q440    
    11 "Health personnel: Doctor"
    12 "Health personnel: Nurse/midwife"
    13 "Health personnel: Com  health officer/nurse"
    21 "Other person: Traditional birth attendant"
    22 "Other person: Village health volunteer"
    23 "Other person: Traditional health practitioner"
    96 "Other"
;
label define Q441    
     1 "Yes"
     2 "No"
;
label define Q442U   
     1 "Hours"
     2 "Days"
     3 "Weeks"
     9 "Special answers"
;
label define Q442N   
    98 "Don't know"
;
label define Q443    
    11 "Health personnel: Doctor"
    12 "Health personnel: Nurse/midwife"
    13 "Health personnel: Com  health officer/nurse"
    21 "Other person: Traditional birth attendant"
    22 "Other person: Village health volunteer"
    23 "Other person: Traditional health practitioner"
    96 "Other"
;
label define Q444    
    11 "Her home"
    12 "Other home"
    21 "Public: Govt hospital"
    22 "Public: Govt health center/clinic"
    23 "Public: Govt health post/chps"
    24 "Public: Mobile clinic/outreach"
    26 "Public: Other public sector"
    31 "Private: Hospital/clinic"
    32 "Private: Fp/ppag clinic"
    33 "Private: Mobile clinic/outreach"
    34 "Private: Maternity home"
    36 "Private: Other private med sector"
    96 "Other"
;
label define Q445B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q446U   
     1 "Hours"
     2 "Days"
     3 "Weeks"
     9 "Special answers"
;
label define Q446N   
    98 "Don't know"
;
label define Q447    
    11 "Health personnel: Doctor"
    12 "Health personnel: Nurse/midwife"
    13 "Health personnel: Com  health officer/nurse"
    21 "Other person: Traditional birth attendant"
    22 "Other person: Village health volunteer"
    23 "Other person: Traditional health practitioner"
    96 "Other"
;
label define Q448    
    11 "Her home"
    12 "Other home"
    21 "Public: Govt hospital"
    22 "Public: Govt health center/clinic"
    23 "Public: Govt health post/chps"
    24 "Public: Mobile clinic/outreach"
    26 "Public: Other public sector"
    31 "Private: Hospital/clinic"
    32 "Private: Fp/ppag clinic"
    33 "Private: Mobile clinic/outreach"
    34 "Private: Maternity home"
    36 "Private: Other private med sector"
    96 "Other"
;
label define Q449    
     1 "Yes"
     2 "No"
;
label define Q450U   
     1 "Hours"
     2 "Days"
     3 "Weeks"
     9 "Special answers"
;
label define Q450N   
    98 "Don't know"
;
label define Q451    
    11 "Health personnel: Doctor"
    12 "Health personnel: Nurse/midwife"
    13 "Health personnel: Com  health officer/nurse"
    21 "Other person: Traditional birth attendant"
    22 "Other person: Village health volunteer"
    23 "Other person: Traditional health practitioner"
    96 "Other"
;
label define Q452    
    11 "Her home"
    12 "Other home"
    21 "Public: Govt hospital"
    22 "Public: Govt health center/clinic"
    23 "Public: Govt health post/chps"
    24 "Public: Mobile clinic/outreach"
    26 "Public: Other public sector"
    31 "Private: Hospital/clinic"
    32 "Private: Fp/ppag clinic"
    33 "Private: Mobile clinic/outreach"
    34 "Private: Maternity home"
    36 "Private: Other private med sector"
    96 "Other"
;
label define Q453B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q454U   
     1 "Hours after birth"
     2 "Days after birth"
     3 "Weeks after birth"
     9 "Special answers"
;
label define Q454N   
    98 "Don't know"
;
label define Q455    
    11 "Health personnel: Doctor"
    12 "Health personnel: Nurse/midwife"
    13 "Health personnel: Com  health officer/nurse"
    21 "Other person: Traditional birth attendant"
    22 "Other person: Village health volunteer"
    23 "Other person: Traditional health practitioner"
    96 "Other"
;
label define Q456    
    11 "Her home"
    12 "Other home"
    21 "Public: Govt hospital"
    22 "Public: Govt health center/clinic"
    23 "Public: Govt health post/chps"
    24 "Public: Mobile clinic/outreach"
    26 "Public: Other public sector"
    31 "Private: Hospital/clinic"
    32 "Private: Fp/ppag clinic"
    33 "Private: Mobile clinic/outreach"
    34 "Private: Maternity home"
    36 "Private: Other private med sector"
    96 "Other"
;
label define Q457A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q457B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q457C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q457D   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q457E   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q501    
  2012 "2012"
  2013 "2013"
  2014 "2014"
  2015 "2015"
  2016 "2016"
  2017 "2017"
  9998 "DK year"
;
label define Q502A   
     1 "Health of mother"
     2 "Risk of birth defect"
     3 "Fetus not viable"
     4 "No money to take care of baby"
     5 "Too young to have child"
     6 "Not ready to be a mother"
     7 "No one to help me look after the child"
     8 "Wanted to delay childbearing"
     9 "Wanted to space child"
    10 "Wanted to continue schooling"
    11 "Wanted to continue working"
    12 "Wanted no more children"
    13 "Did not love the father"
    14 "Did not want to stay with the father"
    15 "Partner did not want child/denied the pregnancy"
    16 "Father of child died"
    17 "Child's sex"
    18 "Because of rape"
    19 "To avoid shame"
    20 "Afraid of parents"
    21 "Parents insisted"
    96 "Other"
;
label define Q502B   
     1 "Yes"
     2 "No"
;
label define Q503    
     1 "Favored"
     2 "Opposed"
     3 "Neutral"
     4 "He did not know"
     5 "Don't know/don't remember"
;
label define Q504    
     1 "Yes"
     2 "No"
;
label define Q505U   
     1 "Days"
     2 "Weeks"
     9 "Special answers"
;
label define Q505N   
    98 "Don't know"
;
label define Q506    
    11 "Drank milk/coffee/alcohol/other liquid with lots of sugar"
    12 "Drank herbal concoction"
    13 "Drank other home remedies"
    14 "Used any herbal enema"
    15 "Inserted herb/object/other substance in the vagina"
    16 "Heavy massage"
    17 "Excessive physical activity"
    18 "Tablets (exact kind unknown)"
    21 "Cytotec tablets (Misoprostol)"
    22 "Mifepristone + Misoprostol (Medabon,etc)"
    23 "IV / Oxytocin"
    31 "D&C / D&E"
    32 "Vacuum aspiration"
    33 "Injection in abdomen (saline instillation)"
    34 "Catheter"
    35 "Other injection"
    96 "Other"
;
label define Q507    
     1 "Health personnel: Doctor"
     2 "Health personnel: Nurse/midwife"
     3 "Health personnel: Com  health officer/nurse"
     4 "Other person: Pharmacist/chemical seller"
     5 "Other person: Traditional birth attendant"
     6 "Other person: Community health volunteer"
     7 "Other person: Relative/friend"
     8 "Other person: Traditional practitioner"
     9 "No one"
    96 "Other"
;
label define Q508    
    11 "Public: Govt hospital"
    12 "Public: Govt health center/clinic"
    13 "Public: Govt health post/chps"
    14 "Public: Mobile clinic/outreach"
    16 "Public: Other public sector"
    21 "Private: Hospital/clinic"
    22 "Private: Fp/ppag clinic"
    23 "Private: Mobile clinic/outreach"
    24 "Private: Maternity home"
    25 "Private: Pharmacy/chemist/drug store"
    26 "Private: Other private medical sector"
    31 "Respondent's home"
    32 "Other home"
    33 "TBA's home"
    96 "Other"
;
label define Q509A   
     1 "Yes"
     2 "No"
;
label define Q510    
     1 "Yes"
     2 "No"
;
label define Q511    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q512    
     1 "Yes"
     2 "No"
;
label define Q513    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q514    
     1 "Yes"
     2 "No"
;
label define Q515    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q516    
     1 "Yes"
     2 "No"
;
label define Q517    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q518    
     1 "Yes"
     2 "No"
;
label define Q519    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q520    
     1 "Yes"
     2 "No"
;
label define Q521    
  9996 "Other problem"
;
label define Q522    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q523    
     1 "Yes"
     2 "No"
;
label define Q524    
  9996 "Other problem"
;
label define Q525    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q526    
     1 "Yes"
     2 "No"
;
label define Q527    
  9996 "Other problem"
;
label define Q528    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q529    
     1 "Yes"
     2 "No"
;
label define Q530    
  9996 "Other problem"
;
label define Q531    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q532    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q533    
    11 "Drank milk/coffee/alcohol/other liquid with lots of sugar"
    12 "Drank herbal concoction"
    13 "Drank other home remedies"
    14 "Used any herbal enema"
    15 "Inserted herb/object/other substance in the vagina"
    16 "Heavy massage"
    17 "Excessive physical activity"
    18 "Tablets (exact kind unknown)"
    21 "Cytotec tablets (Misoprostol)"
    22 "Mifepristone + Misoprostol (Medabon,etc)"
    23 "IV / Oxytocin"
    31 "D&C / D&E"
    32 "Vacuum aspiration"
    33 "Injection in abdomen (saline instillation)"
    34 "Catheter"
    35 "Other injection"
    96 "Other"
;
label define Q534    
     1 "Health personnel: Doctor"
     2 "Health personnel: Nurse/midwife"
     3 "Health personnel: Com  health officer/nurse"
     4 "Other person: Pharmacist/chemical seller"
     5 "Other person: Traditional birth attendant"
     6 "Other person: Community health volunteer"
     7 "Other person: Relative/friend"
     8 "Other person: Traditional practitioner"
     9 "No one"
    96 "Other"
;
label define Q535    
    11 "Public: Govt hospital"
    12 "Public: Govt health center/clinic"
    13 "Public: Govt health post/chps"
    14 "Public: Mobile clinic/outreach"
    16 "Public: Other public sector"
    21 "Private: Hospital/clinic"
    22 "Private: Fp/ppag clinic"
    23 "Private: Mobile clinic/outreach"
    24 "Private: Maternity home"
    25 "Private: Pharmacy/chemist/drug store"
    26 "Private: Other private medical sector"
    31 "Respondent's home"
    32 "Other home"
    33 "TBA's home"
    96 "Other"
;
label define Q536A   
     1 "Yes"
     2 "No"
;
label define Q537    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q538    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q539B   
     1 "Local"
     2 "General"
     3 "Neither"
     8 "Don't know"
;
label define Q540    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q541    
     1 "Yes"
     2 "No"
;
label define Q542    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q543    
     1 "Yes"
     2 "No"
;
label define Q544    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q545    
     1 "Yes"
     2 "No"
;
label define Q546    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q547    
     1 "Yes"
     2 "No"
;
label define Q548    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q549    
     1 "Yes"
     2 "No"
;
label define Q550    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q551    
     1 "Yes"
     2 "No"
;
label define Q552    
  9996 "Other problem"
;
label define Q553    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q554    
     1 "Yes"
     2 "No"
;
label define Q555    
  9996 "Other problem"
;
label define Q556    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q557    
     1 "Yes"
     2 "No"
;
label define Q558    
  9996 "Other problem"
;
label define Q559    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q560    
     1 "Yes"
     2 "No"
;
label define Q561    
  9996 "Other problem"
;
label define Q562    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q563B   
     1 "Yes"
     2 "No"
;
label define Q566A   
     1 "Yes"
     2 "No"
;
label define Q566BU  
     1 "Nights"
     2 "Weeks"
     9 "Special answers"
;
label define Q566BN  
    98 "Don't know"
;
label define Q567    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q568    
     1 "Yes"
     2 "No"
     3 "Not yet 6 months"
     8 "Don't know"
;
label define Q570    
     1 "Yes"
     2 "No"
;
label define Q571    
     1 "Female sterilization"
     2 "Male sterilization"
     3 "Iud"
     4 "Injectables"
     5 "Implants"
     6 "Pill"
     7 "Condom"
     8 "Female condom"
     9 "Diaphragm"
    10 "Foam/jelly"
    11 "Lactational amenorrhea method"
    12 "Rhythm method"
    13 "Withdrawal"
    96 "Other"
;
label define Q572    
     1 "Yes"
     2 "No"
;
label define Q573    
     1 "Before the abortion"
     2 "After the abortion"
     3 "Both before and after the abortion"
     8 "Don't know"
;
label define Q574    
     1 "Yes"
     2 "No"
;
label define Q575    
     1 "Gave method"
     2 "Prescribed a method"
     3 "Gave referral"
     8 "Don't know"
;
label define Q577    
     1 "Yes"
     2 "No"
;
label define Q578    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q579    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q581    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q601    
  2012 "2012"
  2013 "2013"
  2014 "2014"
  2015 "2015"
  2016 "2016"
  2017 "2017"
  9998 "DK year"
;
label define Q602    
     1 "Accident"
     2 "Ate something"
     3 "Someone hurt me"
     4 "Spontaneous"
     6 "Other"
     8 "Don't know"
;
label define Q603    
    11 "Public: Govt hospital"
    12 "Public: Govt health center/clinic"
    13 "Public: Govt health post/chps"
    14 "Public: Mobile clinic/outreach"
    16 "Public: Other public sector"
    21 "Private: Hospital/clinic"
    22 "Private: Fp/ppag clinic"
    23 "Private: Mobile clinic/outreach"
    24 "Private: Maternity home"
    25 "Private: Pharmacy/chemist/drug store"
    26 "Private: Other private medical sector"
    31 "Respondent's home"
    32 "Other home"
    33 "TBA's home"
    41 "Workplace"
    51 "Public place"
    96 "Other"
;
label define Q604A   
     1 "Yes"
     2 "No"
;
label define Q605    
     1 "Yes"
     2 "No"
;
label define Q606    
     1 "D&c"
     2 "Vacuum aspiration"
     3 "Oxytocin"
     4 "Cytotec tablets (misoprostol)"
     5 "Mifepristone + misoprostol"
     6 "Catheter"
     7 "Tablets for insertion"
     8 "Herbal mixture insertion"
    96 "Other"
    98 "Don't know"
;
label define Q607    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q608    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q609B   
     1 "Local"
     2 "General"
     3 "Neither"
     8 "Don't know"
;
label define Q610    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q611    
     1 "Yes"
     2 "No"
;
label define Q612    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q613    
     1 "Yes"
     2 "No"
;
label define Q614    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q615    
     1 "Yes"
     2 "No"
;
label define Q616    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q617    
     1 "Yes"
     2 "No"
;
label define Q618    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q619    
     1 "Yes"
     2 "No"
;
label define Q620    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q621    
     1 "Yes"
     2 "No"
;
label define Q622    
  9996 "Other problem"
;
label define Q623    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q624    
     1 "Yes"
     2 "No"
;
label define Q625    
  9996 "Other problem"
;
label define Q626    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q627    
     1 "Yes"
     2 "No"
;
label define Q628    
  9996 "Other problem"
;
label define Q629    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q630    
     1 "Yes"
     2 "No"
;
label define Q631    
  9996 "Other problem"
;
label define Q632    
     1 "Mild"
     2 "Moderate"
     3 "Severe"
     8 "Don't know"
;
label define Q633    
     1 "Yes"
     2 "No"
;
label define Q636A   
     1 "Yes"
     2 "No"
;
label define Q636BU  
     1 "Nights"
     2 "Weeks"
     9 "Special answers"
;
label define Q636BN  
    98 "Don't know"
;
label define Q637    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q638    
     1 "Yes"
     2 "No"
     3 "Not yet 6 months"
     8 "Don't know"
;
label define Q640    
     1 "Yes"
     2 "No"
;
label define Q641    
     1 "Female sterilization"
     2 "Male sterilization"
     3 "Iud"
     4 "Injectables"
     5 "Implants"
     6 "Pill"
     7 "Condom"
     8 "Female condom"
     9 "Diaphragm"
    10 "Foam/jelly"
    11 "Lactational amenorrhea method"
    12 "Rhythm method"
    13 "Withdrawal"
    96 "Other"
;
label define Q642    
     1 "Yes"
     2 "No"
;
label define Q643    
     1 "Before the miscarriage"
     2 "After the miscarriage"
     3 "Both before and after the miscarriage"
     8 "Don't know"
;
label define Q644    
     1 "Yes"
     2 "No"
;
label define Q645    
     1 "Gave method"
     2 "Prescribed a method"
     3 "Gave referral"
     8 "Don't know"
;
label define Q701    
     1 "Yes, currently married"
     2 "Yes, living with a man"
     3 "No, not in union"
;
label define Q702    
     1 "Yes, formerly married"
     2 "Yes, lived with a man"
     3 "No"
;
label define Q703    
     1 "Widowed"
     2 "Divorced"
     3 "Separated"
;
label define Q704    
     1 "Lives with her"
     2 "Staying elsewhere"
;
label define Q705    
     0 "Not listed in the household"
;
label define Q706    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q707    
    98 "Don't know"
;
label define Q709    
     1 "Only once"
     2 "More than once"
;
label define Q710M   
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    97 "Inconsistent"
    98 "Don't know month"
;
label define Q710Y   
  9997 "Inconsistent"
  9998 "Don't know year"
;
label define Q711    
    97 "Inconsistent"
;
label define Q713    
     0 "Never had sexual intercourse"
    97 "Refuse to answer"
;
label define Q714U   
     1 "Days ago"
     2 "Weeks ago"
     3 "Months ago"
     4 "Years ago"
;
label define Q710F   
     1 "Month and year"
     2 "Month and age -y imp"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define Q713F   
     0 "No flag"
     1 "After interview"
     2 "After conception >= 1 yr"
     3 "After conception < 1 yr"
     4 "At marriage, never married"
     5 "At marriage, after conception"
     6 "After marriage"
;
label define Q714F   
     0 "No flag"
     1 "N > interval since birth"
     2 "N + abstinence > interval"
     3 "N, but sex not resumed"
     4 "96, but no birth"
     5 "96, but currently pregnant"
     6 "96, but resumed sex"
     7 "N, last sex before pregnancy"
     8 "N, inconsistent with sex in last 4 weeks"
     9 "N, sex before last birth"
;
label define Q814    
     1 "Male"
     2 "Female"
;
label define Q815    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q819    
     1 "Yes"
     2 "No"
;
label define Q820    
     1 "Yes"
     2 "No"
;
label define Q821    
     1 "Yes"
     2 "No"
;
label define Q823    
     1 "Yes"
     2 "No"
;
label define Q824    
     1 "Yes"
     2 "No"
;
label define Q901A   
     1 "Big problem"
     2 "Not a big problem"
;
label define Q901B   
     1 "Big problem"
     2 "Not a big problem"
;
label define Q901C   
     1 "Big problem"
     2 "Not a big problem"
;
label define Q901D   
     1 "Big problem"
     2 "Not a big problem"
;
label define Q902    
     1 "Yes"
     2 "No"
;
label define Q903    
     1 "Yes"
     2 "No"
;
label define Q905A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q905B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q905C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q905D   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q905E   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q905F   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q906    
     1 "Yes, always"
     2 "Yes, sometimes"
     3 "No, never"
     8 "Don't know"
;
label define Q908    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q909A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q909B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q909C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q909D   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q909E   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q911    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q912A   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q912B   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q912C   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q912D   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q912E   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q914    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q916    
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define Q917    
     1 "Yes"
     2 "No"
;
label define Q918    
     1 "No difficulty"
     2 "Some difficulty"
     3 "A lot of difficulty"
     4 "Cannot at all"
     8 "Don't know"
;
label define Q919    
     1 "No difficulty"
     2 "Some difficulty"
     3 "A lot of difficulty"
     4 "Cannot at all"
     8 "Don't know"
;
label define Q920    
     1 "No difficulty"
     2 "Some difficulty"
     3 "A lot of difficulty"
     4 "Cannot at all"
     8 "Don't know"
;
label define Q921    
     1 "No difficulty"
     2 "Some difficulty"
     3 "A lot of difficulty"
     4 "Cannot at all"
     8 "Don't know"
;
label define Q922    
     1 "No difficulty"
     2 "Some difficulty"
     3 "A lot of difficulty"
     4 "Cannot at all"
     8 "Don't know"
;
label define Q923    
     1 "No difficulty"
     2 "Some difficulty"
     3 "A lot of difficulty"
     4 "Cannot at all"
     8 "Don't know"
;
label define Q924    
     1 "No difficulty"
     2 "Some difficulty"
     3 "A lot of difficulty"
     4 "Cannot at all"
     8 "Don't know"
;

#delimit cr
label values qregion  QREGION 
label values qintm    QINTM   
label values qresult  QRESULT 
label values qlangq   QLANGQ  
label values qlangi   QLANGI  
label values qlangr   QLANGR  
label values qtrans   QTRANS  
label values qtype    QTYPE   
label values qconsent QCONSENT
label values q101h    Q101H   
label values q101m    Q101M   
label values q102     Q102    
label values q103     Q103    
label values q104     Q104    
label values q105m    Q105M   
label values q105y    Q105Y   
label values q106     Q106    
label values q107     Q107    
label values q108     Q108    
label values q109     Q109    
label values q111     Q111    
label values q113     Q113    
label values q114     Q114    
label values q115     Q115    
label values q116     Q116    
label values q117     Q117    
label values q118     Q118    
label values q119     Q119    
label values q120     Q120    
label values q121     Q121    
label values q122     Q122    
label values q123     Q123    
label values q105f    Q105F   
label values q108a    Q108A   
label values qwftotal QWFTOTAL
label values qwftype  QWFTYPE 
label values qwfreg   QWFREG  
label values qwfeduc  QWFEDUC 
label values qwfwlth  QWFWLTH 
label values q201     Q201    
label values q202     Q202    
label values q204     Q204    
label values q206     Q206    
label values q207a    Q207A   
label values q207c    Q207C   
label values q207e    Q207E   
label values q209     Q209    
label values q222     Q222    
label values q224a    Q224A   
label values q224ay   Q224AY  
label values q224b    Q224B   
label values q224by   Q224BY  
label values q224c    Q224C   
label values q224d    Q224D   
label values q226     Q226    
label values q228     Q228    
label values q229     Q229    
label values q230u    Q230U   
label values q230n    Q230N   
label values q231     Q231    
label values q232     Q232    
label values q233     Q233    
label values q227f    Q227F   
label values q238f    Q238F   
label values q301n_01 Q301N   
label values q301n_02 Q301N   
label values q301n_03 Q301N   
label values q301n_04 Q301N   
label values q301n_05 Q301N   
label values q301n_06 Q301N   
label values q301n_07 Q301N   
label values q301n_08 Q301N   
label values q301n_09 Q301N   
label values q301n_10 Q301N   
label values q301n_11 Q301N   
label values q301n_12 Q301N   
label values q301n_13 Q301N   
label values q301n_14 Q301N   
label values q301_01  Q301    
label values q301_02  Q301    
label values q301_03  Q301    
label values q301_04  Q301    
label values q301_05  Q301    
label values q301_06  Q301    
label values q301_07  Q301    
label values q301_08  Q301    
label values q301_09  Q301    
label values q301_10  Q301    
label values q301_11  Q301    
label values q301_12  Q301    
label values q301_13  Q301    
label values q301_14  Q301    
label values q303     Q303    
label values q305     Q305    
label values q304n    Q304N   
label values q405     Q405    
label values q409     Q409    
label values q410     Q410    
label values q412     Q412    
label values q413a    Q413A   
label values q413b    Q413B   
label values q413c    Q413C   
label values q413d    Q413D   
label values q413e    Q413E   
label values q413f    Q413F   
label values q414     Q414    
label values q415     Q415    
label values q417     Q417    
label values q418     Q418    
label values q420     Q420    
label values q421     Q421    
label values q422     Q422    
label values q423     Q423    
label values q424     Q424    
label values q425     Q425    
label values q426b    Q426B   
label values q427     Q427    
label values q428u    Q428U   
label values q428n    Q428N   
label values q430     Q430    
label values q431ba   Q431BA  
label values q431bb   Q431BB  
label values q431bc   Q431BC  
label values q431c    Q431C   
label values q431e    Q431E   
label values q431h    Q431H   
label values q431i    Q431I   
label values q431j    Q431J   
label values q431k    Q431K   
label values q431l    Q431L   
label values q432u    Q432U   
label values q432n    Q432N   
label values q433a    Q433A   
label values q433b    Q433B   
label values q434     Q434    
label values q434a    Q434A   
label values q435     Q435    
label values q436u    Q436U   
label values q436n    Q436N   
label values q437     Q437    
label values q438b    Q438B   
label values q439u    Q439U   
label values q439n    Q439N   
label values q440     Q440    
label values q441     Q441    
label values q442u    Q442U   
label values q442n    Q442N   
label values q443     Q443    
label values q444     Q444    
label values q445b    Q445B   
label values q446u    Q446U   
label values q446n    Q446N   
label values q447     Q447    
label values q448     Q448    
label values q449     Q449    
label values q450u    Q450U   
label values q450n    Q450N   
label values q451     Q451    
label values q452     Q452    
label values q453b    Q453B   
label values q454u    Q454U   
label values q454n    Q454N   
label values q455     Q455    
label values q456     Q456    
label values q457a    Q457A   
label values q457b    Q457B   
label values q457c    Q457C   
label values q457d    Q457D   
label values q457e    Q457E   
label values q501     Q501    
label values q502a    Q502A   
label values q502b    Q502B   
label values q503     Q503    
label values q504     Q504    
label values q505u    Q505U   
label values q505n    Q505N   
label values q506     Q506    
label values q507     Q507    
label values q508     Q508    
label values q509a    Q509A   
label values q510     Q510    
label values q511     Q511    
label values q512     Q512    
label values q513     Q513    
label values q514     Q514    
label values q515     Q515    
label values q516     Q516    
label values q517     Q517    
label values q518     Q518    
label values q519     Q519    
label values q520     Q520    
label values q521     Q521    
label values q522     Q522    
label values q523     Q523    
label values q524     Q524    
label values q525     Q525    
label values q526     Q526    
label values q527     Q527    
label values q528     Q528    
label values q529     Q529    
label values q530     Q530    
label values q531     Q531    
label values q532     Q532    
label values q533     Q533    
label values q534     Q534    
label values q535     Q535    
label values q536a    Q536A   
label values q537     Q537    
label values q538     Q538    
label values q539b    Q539B   
label values q540     Q540    
label values q541     Q541    
label values q542     Q542    
label values q543     Q543    
label values q544     Q544    
label values q545     Q545    
label values q546     Q546    
label values q547     Q547    
label values q548     Q548    
label values q549     Q549    
label values q550     Q550    
label values q551     Q551    
label values q552     Q552    
label values q553     Q553    
label values q554     Q554    
label values q555     Q555    
label values q556     Q556    
label values q557     Q557    
label values q558     Q558    
label values q559     Q559    
label values q560     Q560    
label values q561     Q561    
label values q562     Q562    
label values q563b    Q563B   
label values q566a    Q566A   
label values q566bu   Q566BU  
label values q566bn   Q566BN  
label values q567     Q567    
label values q568     Q568    
label values q570     Q570    
label values q571     Q571    
label values q572     Q572    
label values q573     Q573    
label values q574     Q574    
label values q575     Q575    
label values q577     Q577    
label values q578     Q578    
label values q579     Q579    
label values q581     Q581    
label values q601     Q601    
label values q602     Q602    
label values q603     Q603    
label values q604a    Q604A   
label values q605     Q605    
label values q606     Q606    
label values q607     Q607    
label values q608     Q608    
label values q609b    Q609B   
label values q610     Q610    
label values q611     Q611    
label values q612     Q612    
label values q613     Q613    
label values q614     Q614    
label values q615     Q615    
label values q616     Q616    
label values q617     Q617    
label values q618     Q618    
label values q619     Q619    
label values q620     Q620    
label values q621     Q621    
label values q622     Q622    
label values q623     Q623    
label values q624     Q624    
label values q625     Q625    
label values q626     Q626    
label values q627     Q627    
label values q628     Q628    
label values q629     Q629    
label values q630     Q630    
label values q631     Q631    
label values q632     Q632    
label values q633     Q633    
label values q636a    Q636A   
label values q636bu   Q636BU  
label values q636bn   Q636BN  
label values q637     Q637    
label values q638     Q638    
label values q640     Q640    
label values q641     Q641    
label values q642     Q642    
label values q643     Q643    
label values q644     Q644    
label values q645     Q645    
label values q701     Q701    
label values q702     Q702    
label values q703     Q703    
label values q704     Q704    
label values q705     Q705    
label values q706     Q706    
label values q707     Q707    
label values q709     Q709    
label values q710m    Q710M   
label values q710y    Q710Y   
label values q711     Q711    
label values q713     Q713    
label values q714u    Q714U   
label values q710f    Q710F   
label values q713f    Q713F   
label values q714f    Q714F   
label values q814_01  Q814    
label values q814_02  Q814    
label values q814_03  Q814    
label values q814_04  Q814    
label values q814_05  Q814    
label values q814_06  Q814    
label values q814_07  Q814    
label values q814_08  Q814    
label values q814_09  Q814    
label values q814_10  Q814    
label values q814_11  Q814    
label values q814_12  Q814    
label values q814_13  Q814    
label values q814_14  Q814    
label values q814_15  Q814    
label values q814_16  Q814    
label values q814_17  Q814    
label values q814_18  Q814    
label values q814_19  Q814    
label values q814_20  Q814    
label values q815_01  Q815    
label values q815_02  Q815    
label values q815_03  Q815    
label values q815_04  Q815    
label values q815_05  Q815    
label values q815_06  Q815    
label values q815_07  Q815    
label values q815_08  Q815    
label values q815_09  Q815    
label values q815_10  Q815    
label values q815_11  Q815    
label values q815_12  Q815    
label values q815_13  Q815    
label values q815_14  Q815    
label values q815_15  Q815    
label values q815_16  Q815    
label values q815_17  Q815    
label values q815_18  Q815    
label values q815_19  Q815    
label values q815_20  Q815    
label values q819_01  Q819    
label values q819_02  Q819    
label values q819_03  Q819    
label values q819_04  Q819    
label values q819_05  Q819    
label values q819_06  Q819    
label values q819_07  Q819    
label values q819_08  Q819    
label values q819_09  Q819    
label values q819_10  Q819    
label values q819_11  Q819    
label values q819_12  Q819    
label values q819_13  Q819    
label values q819_14  Q819    
label values q819_15  Q819    
label values q819_16  Q819    
label values q819_17  Q819    
label values q819_18  Q819    
label values q819_19  Q819    
label values q819_20  Q819    
label values q820_01  Q820    
label values q820_02  Q820    
label values q820_03  Q820    
label values q820_04  Q820    
label values q820_05  Q820    
label values q820_06  Q820    
label values q820_07  Q820    
label values q820_08  Q820    
label values q820_09  Q820    
label values q820_10  Q820    
label values q820_11  Q820    
label values q820_12  Q820    
label values q820_13  Q820    
label values q820_14  Q820    
label values q820_15  Q820    
label values q820_16  Q820    
label values q820_17  Q820    
label values q820_18  Q820    
label values q820_19  Q820    
label values q820_20  Q820    
label values q821_01  Q821    
label values q821_02  Q821    
label values q821_03  Q821    
label values q821_04  Q821    
label values q821_05  Q821    
label values q821_06  Q821    
label values q821_07  Q821    
label values q821_08  Q821    
label values q821_09  Q821    
label values q821_10  Q821    
label values q821_11  Q821    
label values q821_12  Q821    
label values q821_13  Q821    
label values q821_14  Q821    
label values q821_15  Q821    
label values q821_16  Q821    
label values q821_17  Q821    
label values q821_18  Q821    
label values q821_19  Q821    
label values q821_20  Q821    
label values q823_01  Q823    
label values q823_02  Q823    
label values q823_03  Q823    
label values q823_04  Q823    
label values q823_05  Q823    
label values q823_06  Q823    
label values q823_07  Q823    
label values q823_08  Q823    
label values q823_09  Q823    
label values q823_10  Q823    
label values q823_11  Q823    
label values q823_12  Q823    
label values q823_13  Q823    
label values q823_14  Q823    
label values q823_15  Q823    
label values q823_16  Q823    
label values q823_17  Q823    
label values q823_18  Q823    
label values q823_19  Q823    
label values q823_20  Q823    
label values q824_01  Q824    
label values q824_02  Q824    
label values q824_03  Q824    
label values q824_04  Q824    
label values q824_05  Q824    
label values q824_06  Q824    
label values q824_07  Q824    
label values q824_08  Q824    
label values q824_09  Q824    
label values q824_10  Q824    
label values q824_11  Q824    
label values q824_12  Q824    
label values q824_13  Q824    
label values q824_14  Q824    
label values q824_15  Q824    
label values q824_16  Q824    
label values q824_17  Q824    
label values q824_18  Q824    
label values q824_19  Q824    
label values q824_20  Q824    
label values q901a    Q901A   
label values q901b    Q901B   
label values q901c    Q901C   
label values q901d    Q901D   
label values q902     Q902    
label values q903     Q903    
label values q905a    Q905A   
label values q905b    Q905B   
label values q905c    Q905C   
label values q905d    Q905D   
label values q905e    Q905E   
label values q905f    Q905F   
label values q906     Q906    
label values q908     Q908    
label values q909a    Q909A   
label values q909b    Q909B   
label values q909c    Q909C   
label values q909d    Q909D   
label values q909e    Q909E   
label values q911     Q911    
label values q912a    Q912A   
label values q912b    Q912B   
label values q912c    Q912C   
label values q912d    Q912D   
label values q912e    Q912E   
label values q914     Q914    
label values q916     Q916    
label values q917     Q917    
label values q918     Q918    
label values q919     Q919    
label values q920     Q920    
label values q921     Q921    
label values q922     Q922    
label values q923     Q923    
label values q924     Q924    
