infix using "C:\COUNTRIES\KE7A\KEPR7AFL.dct"

label variable hhid     "Case Identification"
label variable hvidx    "Line number"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv011    "NA - Number of eligible men in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 14 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "NA - Household selected for male interview"
label variable hv028    "NA - Household weight for male subsample (6 decimals)"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv035    "Number of eligible children for biomarker"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "NA - Total adults measured"
label variable hv042    "Household selected for hemoglobin"
label variable hv044    "NA - Household selected for Domestic Violence module"
label variable hv201    "Source of drinking water"
label variable hv202    "NA - Source of non-drinking water"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv225    "Share toilet with other households"
label variable hv226    "NA - Type of cooking fuel"
label variable hv227    "Has mosquito bed net for sleeping"
label variable hv228    "Children under 5 slept under mosquito bed net last night"
label variable hv230a   "NA - Place where household members wash their hands"
label variable hv230b   "NA - Presence of water at hand washing place"
label variable hv232    "NA - Items present: Soap or detergent"
label variable hv232b   "NA - Items present: Ash, mud, sand"
label variable hv232c   "NA - Items present: CS"
label variable hv232d   "NA - Items present: CS"
label variable hv232e   "NA - Items present: CS"
label variable hv232y   "NA - Items present: None"
label variable hv234    "NA - Result of salt test for iodine (PPM)"
label variable hv234a   "NA - Result of salt test for iodine"
label variable hv235    "Location of source for water"
label variable hv236    "NA - Person fetching water"
label variable hv237    "NA - Anything done to water to make safe to drink"
label variable hv237a   "NA - Water usually treated by: boil"
label variable hv237b   "NA - Water usually treated by: add bleach/chlorine"
label variable hv237c   "NA - Water usually treated by: strain through a cloth"
label variable hv237d   "NA - Water usually treated by: use water filter"
label variable hv237e   "NA - Water usually treated by: solar disinfection"
label variable hv237f   "NA - Water usually treated by: let it stand and settle"
label variable hv237g   "NA - Water usually treated by: CS"
label variable hv237h   "NA - Water usually treated by: CS"
label variable hv237i   "NA - Water usually treated by: CS"
label variable hv237j   "NA - Water usually treated by: CS"
label variable hv237k   "NA - Water usually treated by: CS"
label variable hv237x   "NA - Water usually treated by: other"
label variable hv237z   "NA - Water usually treated by: don't know"
label variable hv238    "Number of households sharing toilet"
label variable hv239    "NA - Food cooked on stove or open fire"
label variable hv240    "NA - Household has a chimney, hood or neither"
label variable hv241    "NA - Food cooked in the house/ separate building/ outdoors"
label variable hv242    "NA - Household has separate room used as kitchen"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "Has watch"
label variable hv243c   "Has animal-drawn cart"
label variable hv243d   "Has boat with a motor"
label variable hv244    "Owns land usable for agriculture"
label variable hv245    "Hectares of agricultural land (1 decimal)"
label variable hv246    "Owns livestock, herds or farm animals"
label variable hv246a   "Owns cattle"
label variable hv246b   "NA - Owns cows/ bulls"
label variable hv246c   "Owns horses/ donkeys/ mules"
label variable hv246d   "Owns goats"
label variable hv246e   "Owns sheep"
label variable hv246f   "Owns chickens"
label variable hv246g   "Owns exotic cattle"
label variable hv246h   "NA - Owns CS"
label variable hv246i   "NA - Owns CS"
label variable hv246j   "NA - Owns CS"
label variable hv246k   "NA - Owns CS"
label variable hv247    "Has bank account"
label variable hv252    "NA - Frequency household members smoke inside the house"
label variable hv253    "NA - Has dwelling been sprayed against mosquitoes in last 12 months"
label variable hv253a   "NA - Dwelling sprayed by: government worker/program"
label variable hv253b   "NA - Dwelling sprayed by: private company"
label variable hv253c   "NA - Dwelling sprayed by: NGO"
label variable hv253d   "NA - Dwelling sprayed by: CS"
label variable hv253e   "NA - Dwelling sprayed by: CS"
label variable hv253f   "NA - Dwelling sprayed by: CS"
label variable hv253g   "NA - Dwelling sprayed by: CS"
label variable hv253h   "NA - Dwelling sprayed by: CS"
label variable hv253x   "NA - Dwelling sprayed by: other"
label variable hv253z   "NA - Dwelling sprayed by: don't know"
label variable hv270    "Wealth index"
label variable hv271    "Wealth index factor score (5 decimals)"
label variable hml1     "Number of mosquito bed nets"
label variable hml1a    "Number of mosquito bed nets with specific information"
label variable hml2     "Number of children under mosquito bed net previous night"
label variable shcounty "County"
label variable shzone   "Malaria endemicity"
label variable shbegin  "Hour interview begins"
label variable shend    "Hour interview ends"
label variable shlang   "Language of questionnaire"
label variable shlangint "Language of interview"
label variable shtransl "Translator used"
label variable sh101a   "Source of water for other purposes"
label variable sh109b   "Exotic/grade cattle"
label variable sh111u   "Units for Acres or Hectares for agricultural land"
label variable sh111    "Size of agricultural land"
label variable sh112e   "Computer"
label variable sh112g   "Solar panel"
label variable sh112h   "Table"
label variable sh112i   "Chair"
label variable sh112j   "Sofa"
label variable sh112k   "Bed"
label variable sh112l   "Cupboard"
label variable sh112m   "Clock"
label variable sh112n   "Microwave oven"
label variable sh112o   "DVD player"
label variable sh112p   "CD player"
label variable sh113aa  "Household head ever attended school"
label variable sh113bb  "Household head's highest level of education"
label variable sh113cc  "Household head completed the highest level of education"
label variable sh128a   "Given away a mosquito net"
label variable sh128b   "Sold a mosquito net"
label variable sh128c   "Whether nets are used alternatively in this community"
label variable sh128d   "Type of nets used alternatively"
label variable sh128e1  "How old nets were disposed last time: burn"
label variable sh128e2  "How old nets were disposed last time: bury"
label variable sh128e3  "How old nets were disposed last time: throw away"
label variable sh128e4  "How old nets were disposed last time: recycle"
label variable sh128e5  "How old nets were disposed last time: gave to someone else"
label variable sh128e6  "How old nets were disposed last time: exchanged for a new one"
label variable sh128e7  "How old nets were disposed last time: other"
label variable sh128e8  "How old nets were disposed last time: don't know"
label variable sh128f   "Heard about the 2014-15 net mass distribution campaign"
label variable sh128g1  "Where heard about the 2014-2015 net distribution campaign: brochures/posters"
label variable sh128g2  "Where heard about the 2014-2015 net distribution campaign: radio"
label variable sh128g3  "Where heard about the 2014-2015 net distribution campaign: television"
label variable sh128g4  "Where heard about the 2014-2015 net distribution campaign: newspaper"
label variable sh128g5  "Where heard about the 2014-2015 net distribution campaign: chief's barazas"
label variable sh128g6  "Where heard about the 2014-2015 net distribution campaign: health workers"
label variable sh128g7  "Where heard about the 2014-2015 net distribution campaign: home visit for regist"
label variable sh128g8  "Where heard about the 2014-2015 net distribution campaign: community leaders"
label variable sh128g9  "Where heard about the 2014-2015 net distribution campaign: family/friends"
label variable sh128g10 "Where heard about the 2014-2015 net distribution campaign: other"
label variable sh128h1  "The content of the messages about 2014-15 campaign: go get registered"
label variable sh128h2  "The content of the messages about 2014-15 campaign: go collect your net"
label variable sh128h3  "The content of the messages about 2014-15 campaign: sleep under your net every n"
label variable sh128h4  "The content of the messages about 2014-15 campaign: other"
label variable sh128i   "Communications on net use or malaria prevention not linked to the campaign"
label variable sh128j   "Radio message on net use or malaria prevention not linked to the campaign"
label variable sh128k   "Radio message include 'lala ndani ya neti kila siku kila msimu'"
label variable sh128l   "Community based health talk on net use or malaria prevention not linked to the c"
label variable sh128m   "Mosquito net hanging demonstration during the health talk"
label variable sh128n   "Attended a net hanging demonstration last year"
label variable sh128o   "Household registered to receive nets last year"
label variable sh128p   "The reason household was not registered"
label variable sh128q   "Household member collected nets in a 2014-15 campaign distribution point"
label variable sh128r   "Reason not going to a distribution point"
label variable sh128s   "Received vouchers at a distribution point"
label variable sh128t   "Received nets at a distribution point"
label variable sh128u   "Number of nets received at a distribution point"
label variable sh128v   "Number of remaining nets in the household"
label variable sh128x1  "What happened to the missing mosquito nets: net was stolen"
label variable sh128x2  "What happened to the missing mosquito nets: net was destroyed accidentally"
label variable sh128x3  "What happened to the missing mosquito nets: net was sold"
label variable sh128x4  "What happened to the missing mosquito nets: net was given away"
label variable sh128x5  "What happened to the missing mosquito nets: other"
label variable sh128y   "Reason not receiving nets at a distribution point"
label variable sh128z   "Preferred color of net"
label variable sh129a   "Preferred shape of net"
label variable sh129b   "Confidence about hanging a mosquito net"
label variable sh129c   "Importance of having children sleep under a treated net"
label variable sh129d   "Frequency of using the net for things other than sleeping"
label variable sh129e   "Treated nets are safe to sleep under"
label variable sh129f   "Most people in the community sleep under an ITN all the time"
label variable sh129g   "A net can be hanged everywhere in the house"
label variable sh129h   "Risk of malaria in the rainy season"
label variable hv101    "Relationship to head"
label variable hv102    "Usual resident"
label variable hv103    "Slept last night"
label variable hv104    "Sex of household member"
label variable hv105    "Age of household members"
label variable hv106    "NA - Highest educational level attained"
label variable hv107    "NA - Highest year of education completed"
label variable hv108    "NA - Education completed in single years"
label variable hv109    "NA - Educational attainment"
label variable hv110    "NA - Member still in school"
label variable hv111    "NA - Mother alive"
label variable hv112    "NA - Mother's line number"
label variable hv113    "NA - Father alive"
label variable hv114    "NA - Father's line number"
label variable hv115    "NA - Current marital status"
label variable hv116    "NA - Currently, formerly, never married"
label variable hv117    "Eligibility for female interview"
label variable hv118    "NA - Eligibility for male interview"
label variable hv120    "Children eligibility for height/weight and hemoglobin"
label variable hv121    "NA - Member attended school during current school year"
label variable hv122    "NA - Educational level during current school year"
label variable hv123    "NA - Grade of education during current school year"
label variable hv124    "NA - Education in single years - current school year"
label variable hv125    "NA - Member attended school during previous school year"
label variable hv126    "NA - Educational level during previous school year"
label variable hv127    "NA - Grade of education during previous school year"
label variable hv128    "NA - Education in single years - previous school year"
label variable hv129    "NA - School attendance status"
label variable hv140    "NA - Member has a birth certificate"
label variable hc0      "Index to Household Schedule"
label variable hc1      "Child's age in months"
label variable hc2      "NA - Child's weight in kilograms (1 decimal)"
label variable hc3      "NA - Child's height in centimeters (1 decimal)"
label variable hc4      "NA - Height/Age percentile"
label variable hc5      "Height/Age standard deviation"
label variable hc6      "NA - Height/Age percent of ref. median"
label variable hc7      "NA - Weight/Age percentile"
label variable hc8      "Weight/Age standard deviation"
label variable hc9      "NA - Weight/Age percent of ref. median"
label variable hc10     "NA - Weight/Height percentile"
label variable hc11     "Weight/Height standard deviation"
label variable hc12     "NA - Weight/Height percent of ref. median"
label variable hc13     "NA - Result of measurement - height/weight"
label variable hc15     "NA - Height: lying or standing"
label variable hc16     "Day of birth"
label variable hc17     "Date measured (day)"
label variable hc18     "Date measured (month)"
label variable hc19     "Date measured (year)"
label variable hc27     "Sex"
label variable hc30     "Month of birth"
label variable hc31     "Year of birth"
label variable hc32     "Date of birth (CMC)"
label variable hc33     "Completeness of HC32 information"
label variable hc51     "Line number of parent/caretaker"
label variable hc52     "Read consent statement - hemoglobin"
label variable hc53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55     "Result of measurement - hemoglobin"
label variable hc56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57     "Anemia level"
label variable hc58     "NA - Agrees to referral - anemia"
label variable hc60     "Mother's line number (woman's questionnaire)"
label variable hc61     "Mother's highest educational level"
label variable hc62     "Mother's highest year of education"
label variable hc63     "Preceding birth interval (months)"
label variable hc64     "Birth order number"
label variable hc68     "Mother's highest educational level (for preliminary and final report)"
label variable hc70     "Height/Age standard deviation (new WHO)"
label variable hc71     "Weight/Age standard deviation (new WHO)"
label variable hc72     "Weight/Height standard deviation (new WHO)"
label variable hc73     "BMI standard deviation (new WHO)"
label variable shc1     "Child's age in months ( country specific version of HC1 )"
label variable hmlidx   "Mosquito Bed Net Designation Number"
label variable hml3     "Net observed by interviewer"
label variable hml4     "Months ago net obtained"
label variable hml5     "NA - Net treated with insecticide when bought"
label variable hml6     "Net treatment status"
label variable hml7     "Brand of net"
label variable hml8     "Net treated since receiving"
label variable hml9     "NA - Time since last re-treatment (months)"
label variable hml10    "Insecticide-Treated Net (ITN)"
label variable hml11    "Number of persons who slept under this net"
label variable hml21    "Someone slept under this net last night"
label variable hmla     "Line number of person who slept in this net"
label variable hmlb     "Line number of person who slept in this net"
label variable hmlc     "Line number of person who slept in this net"
label variable hmld     "Line number of person who slept in this net"
label variable hmle     "NA - Line number of person who slept in this net"
label variable sh121a   "Net has holes"
label variable sh125    "Place where the net was obtained"
label variable sh125a   "Cost of the net in shilling"
label variable sh126a1  "Reason for not sleeping under the net: net never used"
label variable sh126a2  "Reason for not sleeping under the net: excess nets"
label variable sh126a3  "Reason for not sleeping under the net: too hot"
label variable sh126a4  "Reason for not sleeping under the net: no mosquitos"
label variable sh126a5  "Reason for not sleeping under the net: net was being washed"
label variable sh126a6  "Reason for not sleeping under the net: person normally using net did not stay he"
label variable sh126a7  "Reason for not sleeping under the net: other"
label variable sh127bb  "Net is hanging for sleeping"
label variable sh127cc1 "Reason net not hanging for sleeping: shape difficult to hang up"
label variable sh127cc2 "Reason net not hanging for sleeping: too short to give protection"
label variable sh127cc3 "Reason net not hanging for sleeping: no space to hang net"
label variable sh127cc4 "Reason net not hanging for sleeping: person normally using net did not stay here"
label variable sh127cc5 "Reason net not hanging for sleeping: other"
label variable hmhidx   "Index to Household Schedule"
label variable hml12    "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml13    "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml14    "NA - Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml15    "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml16    "Corrected age from Individual file"
label variable hml16a   "Age in months (for children)"
label variable hml17    "Flag for age from Individual file"
label variable hml18    "Pregnancy status from Individual file"
label variable hml19    "Person slept under an ever-treated net"
label variable hml20    "Person slept under an LLIN net"
label variable hml30    "Line number of parent/caretaker (for malaria testing)"
label variable hml31    "Read consent statement for malaria"
label variable hml32    "Final result of malaria from blood smear test"
label variable hml32a   "Presence of species: falciparum (Pf)"
label variable hml32b   "Presence of species: malariae (Pm)"
label variable hml32c   "Presence of species: ovale (Po)"
label variable hml32d   "Presence of species: vivax (Pv)"
label variable hml32e   "Presence of species: no parasite present"
label variable hml32f   "NA - Presence of species: CS"
label variable hml32g   "NA - Presence of species: CS"
label variable hml33    "Result of malaria measurement"
label variable hml34    "Bar code for blood smear sample"
label variable hml35    "Result of malaria rapid test"
label variable shb118a  "Illness or symptoms: extreme weakness"
label variable shb118b  "Illness or symptoms: heart problems"
label variable shb118c  "Illness or symptoms: loss of consciousness"
label variable shb118d  "Illness or symptoms: rapid breathing"
label variable shb118e  "Illness or symptoms: seizures"
label variable shb118f  "Illness or symptoms: abnormal bleeding"
label variable shb118g  "Illness or symptoms: jaundice or yellow skin"
label variable shb118h  "Illness or symptoms: dark urine"
label variable shb121   "Taken ACT for malaria treatment in the past two weeks"
label variable shb125   "Accepted medicine"
label variable shml16a  "Age in months (for children) ( country specific version )"
label variable shb108t  "Health technician's ID number for anemia testing"
label variable shb110t  "Health technician's ID number for malaria testing"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV018   
   999 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV024   
     1 "Coast"
     2 "North Eastern"
     3 "Eastern"
     4 "Central"
     5 "Rift Valley"
     7 "Western"
     8 "Nyanza"
     9 "Nairobi"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV030   
   999 "Missing"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    14 "Public to neighborhood"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    11 "Earth/sand"
    12 "Dung"
    21 "Wood planks"
    22 "Palm/bamboo"
    31 "Parquet or polished wood"
    32 "Vinyl/PVC or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
;
label define HV214   
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Dung/mud/sod"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    27 "Iron sheets"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
;
label define HV215   
    11 "No roof"
    12 "Thatch/grass/makuti"
    13 "Dung/mud/sod"
    21 "Iron sheets"
    22 "Tin cans"
    31 "Asbestos sheet"
    32 "Concrete"
    33 "Tiles"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in house"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV230A  
     1 "Observed"
     2 "Not observed: not in dwelling"
     3 "Not observed: no permission to see"
     4 "Not observed: other reason"
;
label define HV230B  
     0 "Water not available"
     1 "Water is available"
;
label define HV232   
     0 "No"
     1 "Yes"
;
label define HV232B  
     0 "No"
     1 "Yes"
;
label define HV232C  
     0 "No"
     1 "Yes"
;
label define HV232D  
     0 "No"
     1 "Yes"
;
label define HV232E  
     0 "No"
     1 "Yes"
;
label define HV232Y  
     0 "No"
     1 "Yes: no cleansing agent observed"
;
label define HV234   
     0 "0 PPM (no iodine)"
     7 "Below 15 PPM"
    15 "15 PPM and above"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define HV234A  
     0 "No iodine"
     1 "Iodine present"
     3 "No salt in household"
     6 "Salt not tested"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV236   
     1 "Adult woman"
     2 "Adult man"
     3 "Female child under 15 years old"
     4 "Male child under 15 years old"
     6 "Other"
;
label define HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237I  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237J  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237K  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237Z  
     0 "No"
     1 "Yes: don't know what is done to water"
     8 "Don't know"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     0 "Neither chimney or hood"
     1 "Chimney"
     2 "Hood"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
   950 "95 or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV252   
     0 "Never"
     1 "Daily"
     2 "Weekly"
     3 "Monthly"
     4 "Less than monthly"
;
label define HV253   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253Z  
     0 "No"
     1 "Yes: don't know who sprayed the dwelling"
     8 "Don't know if it was sprayed"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SHCOUNTY
   101 "NAIROBI"
   201 "NYANDARUA"
   202 "NYERI"
   203 "KIRINYAGA"
   204 "MURANGA"
   205 "KIAMBU"
   301 "MOMBASA"
   302 "KWALE"
   303 "KILIFI"
   304 "TANA RIVER"
   305 "LAMU"
   306 "TAITA TAVETA"
   401 "MARSABIT"
   402 "ISIOLO"
   403 "MERU"
   404 "THARAKA"
   405 "EMBU"
   406 "KITUI"
   407 "MACHAKOS"
   408 "MAKUENI"
   501 "GARISSA"
   502 "WAJIR"
   503 "MANDERA"
   601 "SIAYA"
   602 "KISUMU"
   603 "MIGORI"
   604 "HOMA BAY"
   605 "KISII"
   606 "NYAMIRA"
   701 "TURKANA"
   702 "WEST POKOT"
   703 "SAMBURU"
   704 "TRANS-NZOIA"
   705 "BARINGO"
   706 "UASIN GISHU"
   707 "ELGEYO MARAKWET"
   708 "NANDI"
   709 "LAIKIPIA"
   710 "NAKURU"
   711 "NAROK"
   712 "KAJIADO"
   713 "KERICHO"
   714 "BOMET"
   801 "KAKAMEGA"
   802 "VIHIGA"
   803 "BUNGOMA"
   804 "BUSIA"
;
label define SHZONE  
     1 "Highland epidemic"
     2 "Lake endemic"
     3 "Coast endemic"
     4 "Semi-arid, seasonal"
     5 "Low risk"
;
label define SHLANG  
     1 "English"
     2 "Kiswahili"
;
label define SHLANGINT
     1 "English"
     2 "Kiswahili"
     3 "Borana"
     4 "Embu"
     5 "Kalenjin"
     6 "Kamba"
     7 "Kikuyu"
     8 "Kisii"
     9 "Luhya"
    10 "Maragoli"
    11 "Luo"
    12 "Maasai"
    13 "Meru"
    14 "Mijikenda"
    15 "Pokot"
    16 "Somali"
    17 "Turkana"
    18 "Other"
;
label define SHTRANSL
     0 "No"
     1 "Yes"
;
label define SH101A  
    11 "Piped - into dwelling"
    12 "Piped - into yard/plot"
    13 "Piped - into neighbour"
    14 "Piped - public tap / standpipe"
    21 "Tube well or borehole"
    31 "Dug well - protected"
    32 "Dug well - unprotected"
    41 "Spring - protected"
    42 "Spring - unprotected"
    51 "Rainwater"
    61 "Tanker truck"
    71 "Cart with small tank"
    81 "Surface water (river/dam/lake/pond/stream/canal/irrigation channel)"
    96 "Other"
;
label define SH109B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define SH111U  
     1 "Acres"
     2 "Hectares"
     3 "Plot size ( square feet)"
     9 "Special answers"
;
label define SH111   
 995.0 "995 acres/hectares or more"
99995.0 "99995 sq. ft or more"
;
label define SH112E  
     0 "No"
     1 "Yes"
;
label define SH112G  
     0 "No"
     1 "Yes"
;
label define SH112H  
     0 "No"
     1 "Yes"
;
label define SH112I  
     0 "No"
     1 "Yes"
;
label define SH112J  
     0 "No"
     1 "Yes"
;
label define SH112K  
     0 "No"
     1 "Yes"
;
label define SH112L  
     0 "No"
     1 "Yes"
;
label define SH112M  
     0 "No"
     1 "Yes"
;
label define SH112N  
     0 "No"
     1 "Yes"
;
label define SH112O  
     0 "No"
     1 "Yes"
;
label define SH112P  
     0 "No"
     1 "Yes"
;
label define SH113AA 
     0 "No"
     1 "Yes"
;
label define SH113BB 
     1 "Primary"
     2 "Post-primary/vocational"
     3 "Secondary / 'A' level"
     4 "College ( middle level )"
     5 "University"
;
label define SH113CC 
     0 "No"
     1 "Yes"
;
label define SH128A  
     0 "No"
     1 "Yes"
;
label define SH128B  
     0 "No"
     1 "Yes"
;
label define SH128C  
     0 "No"
     1 "Yes"
;
label define SH128D  
     1 "New nets"
     2 "Old nets"
     3 "Both old and new"
;
label define SH128E1 
     0 "No"
     1 "Yes"
;
label define SH128E2 
     0 "No"
     1 "Yes"
;
label define SH128E3 
     0 "No"
     1 "Yes"
;
label define SH128E4 
     0 "No"
     1 "Yes"
;
label define SH128E5 
     0 "No"
     1 "Yes"
;
label define SH128E6 
     0 "No"
     1 "Yes"
;
label define SH128E7 
     0 "No"
     1 "Yes"
;
label define SH128E8 
     0 "No"
     1 "Yes"
;
label define SH128F  
     0 "No"
     1 "Yes"
;
label define SH128G1 
     0 "No"
     1 "Yes"
;
label define SH128G2 
     0 "No"
     1 "Yes"
;
label define SH128G3 
     0 "No"
     1 "Yes"
;
label define SH128G4 
     0 "No"
     1 "Yes"
;
label define SH128G5 
     0 "No"
     1 "Yes"
;
label define SH128G6 
     0 "No"
     1 "Yes"
;
label define SH128G7 
     0 "No"
     1 "Yes"
;
label define SH128G8 
     0 "No"
     1 "Yes"
;
label define SH128G9 
     0 "No"
     1 "Yes"
;
label define SH128G10
     0 "No"
     1 "Yes"
;
label define SH128H1 
     0 "No"
     1 "Yes"
;
label define SH128H2 
     0 "No"
     1 "Yes"
;
label define SH128H3 
     0 "No"
     1 "Yes"
;
label define SH128H4 
     0 "No"
     1 "Yes"
;
label define SH128I  
     0 "No"
     1 "Yes"
;
label define SH128J  
     0 "No"
     1 "Yes"
;
label define SH128K  
     0 "No"
     1 "Yes"
;
label define SH128L  
     0 "No"
     1 "Yes"
;
label define SH128M  
     0 "No"
     1 "Yes"
;
label define SH128N  
     0 "No"
     1 "Yes"
;
label define SH128O  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH128P  
     1 "Absent"
     2 "Refused"
     3 "Not visited by registrar"
     4 "Did not know about the registration"
     6 "Other"
;
label define SH128Q  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH128R  
     1 "No time / means"
     2 "Not interested"
     3 "Forgot or missed the date"
     6 "Other"
;
label define SH128S  
     0 "No"
     1 "Yes"
;
label define SH128T  
     0 "No"
     1 "Yes"
;
label define SH128U  
    95 "more than 95"
;
label define SH128V  
    95 "more than 95"
;
label define SH128X1 
     0 "No"
     1 "Yes"
;
label define SH128X2 
     0 "No"
     1 "Yes"
;
label define SH128X3 
     0 "No"
     1 "Yes"
;
label define SH128X4 
     0 "No"
     1 "Yes"
;
label define SH128X5 
     0 "No"
     1 "Yes"
;
label define SH128Y  
     1 "No nets available at this time"
     2 "Waiting time too long"
     3 "They refused to give nets"
     8 "Don't know"
     6 "Other"
;
label define SH128Z  
     1 "Green"
     2 "Blue"
     3 "White"
     4 "Don't care"
;
label define SH129A  
     1 "Conical"
     2 "Rectangular"
     3 "Does not care"
;
label define SH129B  
     1 "Extremely confident"
     2 "Very confident"
     3 "A little confident"
     4 "Not at all confident"
;
label define SH129C  
     1 "Extremely important"
     2 "Very important"
     3 "A little important"
     4 "Not at all important"
;
label define SH129D  
     1 "All the time"
     2 "Sometimes"
     3 "Rarely"
     4 "Never"
;
label define SH129E  
     1 "Strongly agree"
     2 "Somewhat agree"
     3 "Somewhat disagree"
     4 "Strongly disagree"
;
label define SH129F  
     1 "Strongly agree"
     2 "Somewhat agree"
     3 "Somewhat disagree"
     4 "Strongly disagree"
;
label define SH129G  
     1 "Strongly agree"
     2 "Somewhat agree"
     3 "Somewhat disagree"
     4 "Strongly disagree"
;
label define SH129H  
     1 "Strongly agree"
     2 "Somewhat agree"
     3 "Somewhat disagree"
     4 "Strongly disagree"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    98 "Don't know"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV107   
    98 "Don't know"
;
label define HV108   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
;
label define HV110   
     0 "No"
     1 "Yes"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV112   
     0 "Mother not in household"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV114   
     0 "Father not in household"
;
label define HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever married"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV123   
    98 "Don't know"
;
label define HV124   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV127   
    98 "Don't know"
;
label define HV128   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "Don't know"
;
label define HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     8 "Don't know"
;
label define HC1     
    60 "60+"
;
label define HC2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC4     
  9998 "Flagged cases"
;
label define HC5     
  9998 "Flagged cases"
;
label define HC6     
 99998 "Flagged cases"
;
label define HC7     
  9998 "Flagged cases"
;
label define HC8     
  9998 "Flagged cases"
;
label define HC9     
 99998 "Flagged cases"
;
label define HC10    
  9998 "Flagged cases"
;
label define HC11    
  9998 "Flagged cases"
;
label define HC12    
 99998 "Flagged cases"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC15    
     0 "Not measured"
     1 "Lying"
     2 "Standing"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC62    
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HML3    
     0 "Not seen"
     1 "Yes, seen"
;
label define HML4    
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML5    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HML6    
     0 "Not pretreated"
     1 "Pretreated, permanent treatment"
     2 "Pretreated, requiring future treatment"
     3 "Not pretreated, came with kit and treated at home"
     4 "Pretreated, treatment type not known"
     6 "Other"
     7 "Unbranded"
     8 "Don't know"
;
label define HML7    
    11 "Olyset ( Supanet extra )"
    12 "Permanet ( Supanet extra )"
    13 "Netprotect"
    14 "Yorkool"
    16 "Other/Don't know brand (permanent)"
    71 "Unbranded"
    96 "Other type"
    98 "Don't know type"
;
label define HML8    
     0 "No"
     1 "Yes"
     2 "Permanent net"
     8 "Not sure"
;
label define HML9    
    95 "25+ months ago"
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML10   
     0 "No, don't know"
     1 "Yes"
;
label define HML11   
     5 "5+"
;
label define HML21   
     0 "No"
     1 "Yes"
     8 "Not sure (DK)"
;
label define HMLA    
     0 "No one"
;
label define HMLB    
    99 "Missing"
;
label define HMLC    
    99 "Missing"
;
label define SH121A  
     1 "Hole smaller than a thumb/figer 0.2-2 cm"
     2 "Hole larger than thumb but smaller than fist/hand 2-10 cm"
     3 "Hole larger than fist but smaller than head 10-25 cm"
     4 "Hole larger than head, more than 25 cm"
     5 "No holes"
;
label define SH125   
     1 "2014-15 campaign"
     2 "Other campaign"
     3 "Government/FBO Clinic/Hospital"
     4 "DUKA/Rural shop"
     5 "Supermarket/retail shop"
     6 "Friends/relative"
    96 "Other"
    98 "Don't know"
;
label define SH125A  
  9995 "Free"
  9998 "Not sure"
;
label define SH126A1 
     0 "No"
     1 "Yes"
     8 "Not sure"
;
label define SH126A2 
     0 "No"
     1 "Yes"
     8 "Not sure"
;
label define SH126A3 
     0 "No"
     1 "Yes"
     8 "Not sure"
;
label define SH126A4 
     0 "No"
     1 "Yes"
     8 " Not sure"
;
label define SH126A5 
     0 "No"
     1 "Yes"
     8 "Not sure"
;
label define SH126A6 
     0 "No"
     1 "Yes"
     8 "Not sure"
;
label define SH126A7 
     0 "No"
     1 "Yes"
     8 "Not sure"
;
label define SH127BB 
     0 "Not hanging"
     1 "Hanging"
;
label define SH127CC1
     0 "No"
     1 "Yes"
;
label define SH127CC2
     0 "No"
     1 "Yes"
;
label define SH127CC3
     0 "No"
     1 "Yes"
;
label define SH127CC4
     0 "No"
     1 "Yes"
;
label define SH127CC5
     0 "No"
     1 "Yes"
;
label define HML12   
     0 "Did not sleep under a net"
     1 "Only treated (ITN) nets"
     2 "Both treated (ITN) and untreated nets"
     3 "Only untreated nets"
;
label define HML13   
     0 "Did not sleep under net"
;
label define HML16   
     5 "5- 14"
    95 "95+"
    97 "97+"
    98 "Don't know"
;
label define HML16A  
    60 "60+"
;
label define HML17   
     0 "No data from Individual file"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HML18   
     0 "Not pregnant, don't know"
     1 "Pregnant"
;
label define HML19   
     0 "No"
     1 "Yes"
;
label define HML20   
     0 "No"
     1 "Yes"
;
label define HML30   
     0 "Not in household"
;
label define HML31   
     1 "Granted"
     2 "Refused"
     3 "No present/other"
;
label define HML32   
     0 "Negative"
     1 "Positive"
     6 "Test undetermined"
     7 "Sample not found in lab database"
;
label define HML32A  
     0 "No"
     1 "Yes"
;
label define HML32B  
     0 "No"
     1 "Yes"
;
label define HML32C  
     0 "No"
     1 "Yes"
;
label define HML32D  
     0 "No"
     1 "Yes"
;
label define HML32E  
     0 "No"
     1 "Yes"
;
label define HML32F  
     0 "No"
     1 "Yes"
;
label define HML32G  
     0 "No"
     1 "Yes"
;
label define HML33   
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HML35   
     0 "Negative"
     1 "Positive"
     6 "Other"
;
label define SHB118A 
     0 "No"
     1 "Yes"
;
label define SHB118B 
     0 "No"
     1 "Yes"
;
label define SHB118C 
     0 "No"
     1 "Yes"
;
label define SHB118D 
     0 "No"
     1 "Yes"
;
label define SHB118E 
     0 "No"
     1 "Yes"
;
label define SHB118F 
     0 "No"
     1 "Yes"
;
label define SHB118G 
     0 "No"
     1 "Yes"
;
label define SHB118H 
     0 "No"
     1 "Yes"
;
label define SHB121  
     0 "No"
     1 "Yes"
;
label define SHB125  
     1 "Accepted medicine"
     2 "Refused"
     6 "Other"
;

#delimit cr
label values hv003    HV003   
label values hv015    HV015   
label values hv020    HV020   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv044    HV044   
label values hv201    HV201   
label values hv202    HV202   
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv230a   HV230A  
label values hv230b   HV230B  
label values hv232    HV232   
label values hv232b   HV232B  
label values hv232c   HV232C  
label values hv232d   HV232D  
label values hv232e   HV232E  
label values hv232y   HV232Y  
label values hv234    HV234   
label values hv234a   HV234A  
label values hv235    HV235   
label values hv236    HV236   
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237g   HV237G  
label values hv237h   HV237H  
label values hv237i   HV237I  
label values hv237j   HV237J  
label values hv237k   HV237K  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv252    HV252   
label values hv253    HV253   
label values hv253a   HV253A  
label values hv253b   HV253B  
label values hv253c   HV253C  
label values hv253d   HV253D  
label values hv253e   HV253E  
label values hv253f   HV253F  
label values hv253g   HV253G  
label values hv253h   HV253H  
label values hv253x   HV253X  
label values hv253z   HV253Z  
label values hv270    HV270   
label values hml1     HML1    
label values shcounty SHCOUNTY
label values shzone   SHZONE  
label values shlang   SHLANG  
label values shlangint SHLANGINT
label values shtransl SHTRANSL
label values sh101a   SH101A  
label values sh109b   SH109B  
label values sh111u   SH111U  
label values sh111    SH111   
label values sh112e   SH112E  
label values sh112g   SH112G  
label values sh112h   SH112H  
label values sh112i   SH112I  
label values sh112j   SH112J  
label values sh112k   SH112K  
label values sh112l   SH112L  
label values sh112m   SH112M  
label values sh112n   SH112N  
label values sh112o   SH112O  
label values sh112p   SH112P  
label values sh113aa  SH113AA 
label values sh113bb  SH113BB 
label values sh113cc  SH113CC 
label values sh128a   SH128A  
label values sh128b   SH128B  
label values sh128c   SH128C  
label values sh128d   SH128D  
label values sh128e1  SH128E1 
label values sh128e2  SH128E2 
label values sh128e3  SH128E3 
label values sh128e4  SH128E4 
label values sh128e5  SH128E5 
label values sh128e6  SH128E6 
label values sh128e7  SH128E7 
label values sh128e8  SH128E8 
label values sh128f   SH128F  
label values sh128g1  SH128G1 
label values sh128g2  SH128G2 
label values sh128g3  SH128G3 
label values sh128g4  SH128G4 
label values sh128g5  SH128G5 
label values sh128g6  SH128G6 
label values sh128g7  SH128G7 
label values sh128g8  SH128G8 
label values sh128g9  SH128G9 
label values sh128g10 SH128G10
label values sh128h1  SH128H1 
label values sh128h2  SH128H2 
label values sh128h3  SH128H3 
label values sh128h4  SH128H4 
label values sh128i   SH128I  
label values sh128j   SH128J  
label values sh128k   SH128K  
label values sh128l   SH128L  
label values sh128m   SH128M  
label values sh128n   SH128N  
label values sh128o   SH128O  
label values sh128p   SH128P  
label values sh128q   SH128Q  
label values sh128r   SH128R  
label values sh128s   SH128S  
label values sh128t   SH128T  
label values sh128u   SH128U  
label values sh128v   SH128V  
label values sh128x1  SH128X1 
label values sh128x2  SH128X2 
label values sh128x3  SH128X3 
label values sh128x4  SH128X4 
label values sh128x5  SH128X5 
label values sh128y   SH128Y  
label values sh128z   SH128Z  
label values sh129a   SH129A  
label values sh129b   SH129B  
label values sh129c   SH129C  
label values sh129d   SH129D  
label values sh129e   SH129E  
label values sh129f   SH129F  
label values sh129g   SH129G  
label values sh129h   SH129H  
label values hv101    HV101   
label values hv102    HV102   
label values hv103    HV103   
label values hv104    HV104   
label values hv105    HV105   
label values hv106    HV106   
label values hv107    HV107   
label values hv108    HV108   
label values hv109    HV109   
label values hv110    HV110   
label values hv111    HV111   
label values hv112    HV112   
label values hv113    HV113   
label values hv114    HV114   
label values hv115    HV115   
label values hv116    HV116   
label values hv117    HV117   
label values hv118    HV118   
label values hv120    HV120   
label values hv121    HV121   
label values hv122    HV122   
label values hv123    HV123   
label values hv124    HV124   
label values hv125    HV125   
label values hv126    HV126   
label values hv127    HV127   
label values hv128    HV128   
label values hv129    HV129   
label values hv140    HV140   
label values hc1      HC1     
label values hc2      HC2     
label values hc3      HC3     
label values hc4      HC4     
label values hc5      HC5     
label values hc6      HC6     
label values hc7      HC7     
label values hc8      HC8     
label values hc9      HC9     
label values hc10     HC10    
label values hc11     HC11    
label values hc12     HC12    
label values hc13     HC13    
label values hc15     HC15    
label values hc16     HC16    
label values hc27     HC27    
label values hc30     HC30    
label values hc31     HC31    
label values hc33     HC33    
label values hc51     HC51    
label values hc52     HC52    
label values hc53     HC53    
label values hc55     HC55    
label values hc56     HC56    
label values hc57     HC57    
label values hc58     HC58    
label values hc60     HC60    
label values hc61     HC61    
label values hc62     HC62    
label values hc68     HC68    
label values hc70     HC70    
label values hc71     HC71    
label values hc72     HC72    
label values hc73     HC73    
label values hml3     HML3    
label values hml4     HML4    
label values hml5     HML5    
label values hml6     HML6    
label values hml7     HML7    
label values hml8     HML8    
label values hml9     HML9    
label values hml10    HML10   
label values hml11    HML11   
label values hml21    HML21   
label values hmla     HMLA    
label values sh121a   SH121A  
label values sh125    SH125   
label values sh125a   SH125A  
label values sh126a1  SH126A1 
label values sh126a2  SH126A2 
label values sh126a3  SH126A3 
label values sh126a4  SH126A4 
label values sh126a5  SH126A5 
label values sh126a6  SH126A6 
label values sh126a7  SH126A7 
label values sh127bb  SH127BB 
label values sh127cc1 SH127CC1
label values sh127cc2 SH127CC2
label values sh127cc3 SH127CC3
label values sh127cc4 SH127CC4
label values sh127cc5 SH127CC5
label values hml12    HML12   
label values hml13    HML13   
label values hml16    HML16   
label values hml16a   HML16A  
label values hml17    HML17   
label values hml18    HML18   
label values hml19    HML19   
label values hml20    HML20   
label values hml30    HML30   
label values hml31    HML31   
label values hml32    HML32   
label values hml32a   HML32A  
label values hml32b   HML32B  
label values hml32c   HML32C  
label values hml32d   HML32D  
label values hml32e   HML32E  
label values hml32f   HML32F  
label values hml32g   HML32G  
label values hml33    HML33   
label values hml35    HML35   
label values shb118a  SHB118A 
label values shb118b  SHB118B 
label values shb118c  SHB118C 
label values shb118d  SHB118D 
label values shb118e  SHB118E 
label values shb118f  SHB118F 
label values shb118g  SHB118G 
label values shb118h  SHB118H 
label values shb121   SHB121  
label values shb125   SHB125  
