infile using "C:\USERS\61097\ICF\DATA ARCHIVE - DOCUMENTS\EXPORT MENU\NG8B\NGSR8BFL.dct"

label variable caseid   "Case identification"
label variable mmidx    "Index to Maternal Mortality"
label variable v000     "Country code and phase"
label variable v001     "Cluster number"
label variable v002     "Household number"
label variable v003     "Respondent's line number"
label variable v004     "Ultimate area unit"
label variable v005     "Women's individual sample weight (6 decimals)"
label variable v006     "Month of interview"
label variable v007     "Year of interview"
label variable v008     "Date of interview (CMC)"
label variable v008a    "Date of interview Century Day Code (CDC)"
label variable v009     "Respondent's month of birth"
label variable v010     "Respondent's year of birth"
label variable v011     "Date of birth (CMC)"
label variable v012     "Respondent's current age"
label variable v013     "Age in 5-year groups"
label variable v014     "Completeness of age information"
label variable v015     "Result of individual interview"
label variable v016     "Day of interview"
label variable v017     "CMC start of calendar"
label variable v018     "Row of month of interview"
label variable v019     "Length of calendar"
label variable v019a    "Number of calendar columns"
label variable v020     "Ever-married sample"
label variable v021     "Primary sampling unit"
label variable v022     "Sample strata for sampling errors"
label variable v023     "Stratification used in sample design"
label variable v024     "Zone (code are as per sample frame)"
label variable v025     "Type of place of residence"
label variable v026     "NA - De facto place of residence"
label variable v027     "Number of visits"
label variable v028     "Interviewer identification"
label variable v029     "NA - Keyer identification"
label variable v030     "Field supervisor"
label variable v031     "NA - Field editor"
label variable v032     "NA - Office editor"
label variable v034     "Line number of husband"
label variable v040     "Cluster altitude in meters"
label variable v042     "Household selected for hemoglobin"
label variable v044     "Selected for Domestic Violence module"
label variable v045a    "Language of questionnaire"
label variable v045b    "Language of interview"
label variable v045c    "Native language of respondent"
label variable v046     "Translator used"
label variable v047     "Team number"
label variable v048     "Team supervisor"
label variable v101     "Zone (codes are as per sample frame)"
label variable v102     "Type of place of residence"
label variable v103     "NA - Childhood place of residence"
label variable v104     "Years lived in place of residence"
label variable v105     "Type of place of previous residence"
label variable v105a    "Zone of previous residence"
label variable v106     "Highest educational level"
label variable v107     "Highest year of education"
label variable v113     "Source of drinking water"
label variable v115     "Time to get to water source"
label variable v116     "Type of toilet facility"
label variable v119     "Household has: electricity"
label variable v120     "Household has: radio"
label variable v121     "Household has: television"
label variable v122     "Household has: refrigerator"
label variable v123     "Household has: bicycle"
label variable v124     "Household has: motorcycle/scooter"
label variable v125     "Household has: car/truck"
label variable v127     "Main floor material"
label variable v128     "Main wall material"
label variable v129     "Main roof material"
label variable v130     "Religion"
label variable v131     "Ethnicity"
label variable v133     "Education in single years"
label variable v134     "NA - De facto place of residence"
label variable v135     "Usual resident or visitor"
label variable v136     "Number of household members (listed)"
label variable v137     "Number of children 5 and under in household (de jure)"
label variable v138     "Number of eligible women in household (de facto)"
label variable v139     "De jure region of residence"
label variable v140     "De jure type of place of residence"
label variable v141     "NA - De jure place of residence"
label variable v149     "Educational attainment"
label variable v150     "Relationship to household head"
label variable v151     "Sex of household head"
label variable v152     "Age of household head"
label variable v153     "Household has: telephone (land-line)"
label variable awfactt  "All woman factor - total"
label variable awfactu  "All woman factor - urban/rural"
label variable awfactr  "All woman factor - regional"
label variable awfacte  "All woman factor - educational"
label variable awfactw  "All woman factor - wealth index"
label variable v155     "Literacy"
label variable v156     "NA - Ever participated in a literacy program outside of primary"
label variable v157     "Frequency of reading newspaper or magazine"
label variable v158     "Frequency of listening to radio"
label variable v159     "Frequency of watching television"
label variable v160     "Toilet facilities shared with other households"
label variable v161     "Type of cooking fuel"
label variable v166     "NA - Result of salt test for iodine"
label variable v167     "NA - Number of trips in last 12 months"
label variable v168     "NA - Away for more than one month in last 12 months"
label variable v169a    "Owns a mobile telephone"
label variable v169b    "Last 12 months use mobile telephone for financial transactions"
label variable v169c    "Is respondent's mobile phone a smart phone"
label variable v170     "Has an account in a bank or other financial institution"
label variable v171a    "Use of internet"
label variable v171b    "Frequency of using internet last month"
label variable v172     "Respondent state of birth"
label variable v173     "Respondent country of birth"
label variable v174m    "Month move to current place of residence"
label variable v174y    "Year move to current place of residence"
label variable v175     "Reason for moving to current place of residence"
label variable v176     "Self reported health status"
label variable v177     "Money put/taken from bank account last 12 months"
label variable v190     "Wealth index combined"
label variable v191     "Wealth index factor score combined (5 decimals)"
label variable v190a    "Wealth index for urban/rural"
label variable v191a    "Wealth index factor score for urban/rural (5 decimals)"
label variable ml101    "Type of mosquito bed net(s) slept under last night"
label variable mm1      "Sex of sibling"
label variable mm2      "Survival status of sibling"
label variable mm3      "Sibling's current age"
label variable mm4      "Sibling's date of birth (CMC)"
label variable mm5      "NA - Sibling's marital status"
label variable mm6      "Years since sibling died"
label variable mm7      "Sibling's age at death"
label variable mm8      "Date of death of sibling (CMC)"
label variable mm9      "Sibling's death and pregnancy"
label variable mm10     "NA - Death and a pregnancy are related"
label variable mm11     "NA - Cause of death sibling"
label variable mm12     "Amount of time between sibling's delivery and death"
label variable mm13     "NA - Place of sibling's death"
label variable mm14     "NA - Number of sibling's children"
label variable mm15     "NA - Sibling's year of death"
label variable mm16     "Sibling's death due to violence or accident"
label variable mmc1     "Number of siblings of respondent"
label variable mmc2     "Number of siblings born before respondent's birth"
label variable mmc3     "NA - Sister's reporting"
label variable mmc4_1   "NA - Sister's line number from Household Schedule"
label variable mmc4_2   "NA - Sister's line number from Household Schedule"
label variable mmc4_3   "NA - Sister's line number from Household Schedule"
label variable mmc4_4   "NA - Sister's line number from Household Schedule"
label variable mmc4_5   "NA - Sister's line number from Household Schedule"
label variable mmc4_6   "NA - Sister's line number from Household Schedule"
label variable mmc5     "Cut off age for Maternal Mortality collection (in questionnaire)"

#delimit ;
label define V013    
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define V014    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define V015    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partially completed"
     6 "Respondent incapacitated"
     7 "Other"
;
label define V018    
     0 "No calendar"
;
label define V019    
     0 "No calendar"
;
label define V019A   
     0 "No calendar"
;
label define V020    
     0 "All woman sample"
     1 "Ever married sample"
;
label define V022    
     1 "Sokoto Urban"
     2 "Sokoto Rural"
     3 "Zamfara Urban"
     4 "Zamfara Rural"
     5 "Katsina Urban"
     6 "Katsina Rural"
     7 "Jigawa Urban"
     8 "Jigawa Rural"
     9 "Yobe Urban"
    10 "Yobe Rural"
    11 "Borno Urban"
    12 "Borno Rural"
    13 "Adamawa Urban"
    14 "Adamawa Rural"
    15 "Gombe Urban"
    16 "Gombe Rural"
    17 "Bauchi Urban"
    18 "Bauchi Rural"
    19 "Kano Urban"
    20 "Kano Rural"
    21 "Kaduna Urban"
    22 "Kaduna Rural"
    23 "Kebbi Urban"
    24 "Kebbi Rural"
    25 "Niger Urban"
    26 "Niger Rural"
    27 "FCT Urban"
    28 "FCT Rural"
    29 "Nasarawa Urban"
    30 "Nasarawa Rural"
    31 "Plateau Urban"
    32 "Plateau Rural"
    33 "Taraba Urban"
    34 "Taraba Rural"
    35 "Benue Urban"
    36 "Benue Rural"
    37 "Kogi Urban"
    38 "Kogi Rural"
    39 "Kwara Urban"
    40 "Kwara Rural"
    41 "Oyo Urban"
    42 "Oyo Rural"
    43 "Osun Urban"
    44 "Osun Rural"
    45 "Ekiti Urban"
    46 "Ekiti Rural"
    47 "Ondo Urban"
    48 "Ondo Rural"
    49 "Edo Urban"
    50 "Edo Rural"
    51 "Anambra Urban"
    52 "Anambra Rural"
    53 "Enugu Urban"
    54 "Enugu Rural"
    55 "Ebonyi Urban"
    56 "Ebonyi Rural"
    57 "Cross River Urban"
    58 "Cross River Rural"
    59 "Akwa Ibom Urban"
    60 "Akwa Ibom Rural"
    61 "Abia Urban"
    62 "Abia Rural"
    63 "Imo Urban"
    64 "Imo Rural"
    65 "Rivers Urban"
    66 "Rivers Rural"
    67 "Bayelsa Urban"
    68 "Bayelsa Rural"
    69 "Delta Urban"
    70 "Delta Rural"
    71 "Lagos Urban"
    72 "Lagos Rural"
    73 "Ogun Urban"
    74 "Ogun Rural"
;
label define V023    
     1 "Sokoto Urban"
     2 "Sokoto Rural"
     3 "Zamfara Urban"
     4 "Zamfara Rural"
     5 "Katsina Urban"
     6 "Katsina Rural"
     7 "Jigawa Urban"
     8 "Jigawa Rural"
     9 "Yobe Urban"
    10 "Yobe Rural"
    11 "Borno Urban"
    12 "Borno Rural"
    13 "Adamawa Urban"
    14 "Adamawa Rural"
    15 "Gombe Urban"
    16 "Gombe Rural"
    17 "Bauchi Urban"
    18 "Bauchi Rural"
    19 "Kano Urban"
    20 "Kano Rural"
    21 "Kaduna Urban"
    22 "Kaduna Rural"
    23 "Kebbi Urban"
    24 "Kebbi Rural"
    25 "Niger Urban"
    26 "Niger Rural"
    27 "FCT Urban"
    28 "FCT Rural"
    29 "Nasarawa Urban"
    30 "Nasarawa Rural"
    31 "Plateau Urban"
    32 "Plateau Rural"
    33 "Taraba Urban"
    34 "Taraba Rural"
    35 "Benue Urban"
    36 "Benue Rural"
    37 "Kogi Urban"
    38 "Kogi Rural"
    39 "Kwara Urban"
    40 "Kwara Rural"
    41 "Oyo Urban"
    42 "Oyo Rural"
    43 "Osun Urban"
    44 "Osun Rural"
    45 "Ekiti Urban"
    46 "Ekiti Rural"
    47 "Ondo Urban"
    48 "Ondo Rural"
    49 "Edo Urban"
    50 "Edo Rural"
    51 "Anambra Urban"
    52 "Anambra Rural"
    53 "Enugu Urban"
    54 "Enugu Rural"
    55 "Ebonyi Urban"
    56 "Ebonyi Rural"
    57 "Cross River Urban"
    58 "Cross River Rural"
    59 "Akwa Ibom Urban"
    60 "Akwa Ibom Rural"
    61 "Abia Urban"
    62 "Abia Rural"
    63 "Imo Urban"
    64 "Imo Rural"
    65 "Rivers Urban"
    66 "Rivers Rural"
    67 "Bayelsa Urban"
    68 "Bayelsa Rural"
    69 "Delta Urban"
    70 "Delta Rural"
    71 "Lagos Urban"
    72 "Lagos Rural"
    73 "Ogun Urban"
    74 "Ogun Rural"
;
label define V024    
     1 "North west"
     2 "North east"
     3 "North central"
     4 "South east"
     5 "South south"
     6 "South west"
;
label define V025    
     1 "Urban"
     2 "Rural"
;
label define V026    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V027    
     9 "Missing"
;
label define V029    
   999 "Missing"
;
label define V034    
     0 "Husband not in household"
;
label define V040    
  9999 "Missing"
;
label define V042    
     0 "Not selected"
     1 "Selected"
;
label define V044    
     0 "Woman not selected"
     1 "Woman selected and interviewed"
     2 "Woman selected, but privacy not possible"
     3 "Woman selected, but not interviewed"
;
label define V045A   
     1 "English"
     2 "Hausa"
     3 "Yoruba"
     4 "Igbo"
;
label define V045B   
     1 "English"
     2 "Hausa"
     3 "Yoruba"
     4 "Igbo"
;
label define V045C   
     1 "English"
     2 "Hausa"
     3 "Yoruba"
     4 "Igbo"
     6 "Other language"
;
label define V046    
     0 "No"
     1 "Yes"
;
label define V101    
     1 "North west"
     2 "North east"
     3 "North central"
     4 "South east"
     5 "South south"
     6 "South west"
;
label define V102    
     1 "Urban"
     2 "Rural"
;
label define V103    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define V104    
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define V105    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define V105A   
     1 "North central"
     2 "North east"
     3 "North west"
     4 "South east"
     5 "South south"
     6 "South west"
    96 "Abroad"
;
label define V106    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define V107    
     0 "No years completed at level V106"
;
label define V113    
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    72 "Sachet water"
    96 "Other"
    97 "Not a de jure resident"
;
label define V115    
   996 "On premises"
   997 "Not a de jure resident"
   998 "Don't know"
;
label define V116    
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
    97 "Not a de jure resident"
;
label define V119    
     0 "No"
     1 "Yes"
     7 "Not a de jure resident"
;
label define V120    
     0 "No"
     1 "Yes"
     7 "Not a de jure resident"
;
label define V121    
     0 "No"
     1 "Yes"
     7 "Not a de jure resident"
;
label define V122    
     0 "No"
     1 "Yes"
     7 "Not a de jure resident"
;
label define V123    
     0 "No"
     1 "Yes"
     7 "Not a de jure resident"
;
label define V124    
     0 "No"
     1 "Yes"
     7 "Not a de jure resident"
;
label define V125    
     0 "No"
     1 "Yes"
     7 "Not a de jure resident"
;
label define V127    
    10 "---NATURAL FLOOR---"
    11 "Earth/sand"
    12 "Dung"
    20 "---RUDIMENTARY FLOOR---"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "---FINISHED FLOOR---"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
    97 "Not a de jure resident"
;
label define V128    
    10 "---NATURAL WALLS---"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Dirt"
    14 "Mud"
    20 "---RUDIMENTARY WALLS---"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "---FINISHED WALLS---"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
    97 "Not a de jure resident"
;
label define V129    
    10 "---NATURAL ROOFING---"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Mud"
    20 "---RUDIMENTARY ROOFING---"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "---FINISHED ROOFING---"
    31 "Metal/zinc"
    32 "Wood"
    33 "Calamine/cement fiber"
    34 "Ceramic tiles"
    35 "Cement"
    36 "Roofing shingles"
    96 "Other"
    97 "Not a de jure resident"
;
label define V130    
     1 "Catholic"
     2 "Other Christian"
     3 "Islam"
     4 "Traditionalist"
    96 "Other"
;
label define V131    
     1 "Abua"
     2 "Adra/Adarawa"
     3 "Adun"
     4 "Afcabeya"
     5 "Afemai"
     6 "Afizire"
     7 "Agatu"
     8 "Agbassa"
     9 "Agbor"
    10 "Afo"
    11 "Ajowa"
    12 "Akpa"
    13 "Akwai"
    14 "Akye"
    15 "Alago"
    16 "Amamong"
    17 "Amo"
    18 "Ana"
    19 "Anaguta"
    20 "Ankwai"
    21 "Annang"
    22 "Arab"
    23 "Arabo"
    24 "Arbar"
    25 "Arugu"
    26 "Aten/Atam"
    27 "Attakar"
    28 "Auchi"
    29 "Aulliminden"
    30 "Awo"
    31 "Ayetoro Gbede"
    32 "Badarare"
    33 "Bade/Badawe"
    34 "Bafeke"
    35 "Bagathiya"
    36 "Baggara"
    37 "Bagunge/Badagire"
    38 "Bahnake"
    39 "Baji/Biji"
    40 "Bajju"
    41 "Bambaro"
    42 "Bambuka"
    43 "Bandawa"
    44 "Banguji"
    45 "Bankalawa"
    46 "Bchama"
    47 "Barabaci"
    48 "Barawa"
    49 "Bargawa"
    50 "Bassa"
    51 "Bekworas"
    53 "Berom"
    54 "Bini/Edo"
    55 "Bogom"
    56 "Boiyawa/Bozaya"
    57 "Bolawa/Bolewa"
    59 "Buduma"
    60 "Buko"
    61 "Bura/Babur"
    62 "Buzu"
    63 "Byazhi"
    64 "Calabar"
    65 "Chala"
    66 "Chamba"
    67 "Chiba"
    68 "Chibok(g)"
    69 "Chip"
    70 "Dadiya"
    71 "Badakare/Dakarkari"
    72 "Dakka/Doka"
    73 "Dangula"
    74 "Daurawa/Dagarawa"
    75 "Defaka"
    76 "Degima"
    77 "Delta Ibo"
    78 "Dibo"
    79 "Diguza"
    80 "Djerma"
    81 "Dmoko"
    82 "Dolchi"
    83 "Ebira/Igbira"
    84 "Ebu"
    85 "Efik"
    86 "Egba"
    87 "Egbado"
    88 "Eggon"
    89 "Egun"
    90 "Eket"
    91 "Ekoi"
    92 "Ekpeye/Afisa/Epie"
    94 "Ekulu"
    95 "Eleme"
    96 "Emu"
    97 "Esan"
    98 "Etina"
    99 "Etsako"
   100 "Etulo"
   101 "Hadejawa"
   102 "Fanso"
   103 "Femawa"
   104 "Fer"
   105 "Filiya/Fali"
   106 "Fon"
   107 "Foron"
   108 "French"
   109 "Fulani"
   110 "Gamaku"
   111 "Gamaru"
   112 "Gamuni"
   113 "Gana Gana"
   114 "Ganawuri"
   115 "Gbaju/Gbagi"
   116 "Gede/Gude/Gai"
   117 "Gerawa"
   118 "Gizmawa"
   119 "Glauda"
   120 "Gmenchi"
   121 "Gomo/Gamoyaya"
   122 "Gobiri/Gobirawa/Bogobiri"
   123 "Gujjurawa"
   124 "Guemai"
   125 "Gumbarawa"
   126 "Gunganchi"
   127 "Gwandara"
   128 "Gwantu"
   129 "Hankwe"
   130 "Hausa"
   131 "Higgi"
   132 "Ibariba"
   133 "Ibibio"
   134 "Ichen"
   135 "Idanre"
   136 "Idoma"
   137 "Igala"
   138 "Igbo/Ibo"
   139 "Igede"
   140 "Ijaw/Izon"
   141 "Ijede"
   142 "Ijeme"
   143 "Ika"
   144 "Ikajo"
   145 "Ikara"
   146 "Ikpeshi"
   147 "Ikpide"
   148 "Ikulu"
   149 "Ikwere"
   150 "Ilaje"
   151 "Irigwe"
   152 "Ishan"
   153 "Isoko"
   154 "Itsekiri"
   155 "Jaba"
   156 "Jajiri"
   157 "Jakatoe"
   158 "Jaku"
   159 "Jara"
   160 "Jarawa"
   162 "Jibu"
   163 "Jonjo"
   164 "Jukun"
   165 "Kabawa"
   166 "Kadara"
   167 "Kagoma"
   168 "Kagoro"
   169 "Kaka"
   170 "Kakanda"
   171 "Kamantam"
   172 "Kambari"
   173 "Kambu/Kangu"
   174 "Kamuku"
   175 "Kanakuru"
   176 "Kanawa"
   177 "Kaninko"
   178 "Kantanawa"
   179 "Kanuri/Beriberi"
   180 "Manga"
   181 "Karekare"
   182 "Kataf/Atyap"
   183 "Kento"
   184 "Kibaku"
   185 "Kilba"
   186 "Kirdi"
   187 "Kodki"
   188 "Kofyar"
   189 "Kona"
   190 "Koro"
   191 "Koto"
   192 "Kuenuem"
   193 "Kumbo"
   194 "Kunkawa/Kawa"
   195 "Kurama"
   196 "Kuteb"
   197 "Kuturm"
   198 "Kwale/Ukwuani"
   199 "Kwanzo"
   200 "Lagelu"
   201 "Lantang"
   202 "Lemoro"
   203 "Loh"
   204 "Lunguda"
   205 "Maba/Mbadowa"
   206 "Mada"
   207 "Mafa/Maka/Maga"
   208 "Mambila"
   209 "Mandara"
   210 "Mangus/Manju"
   211 "Marghi/mangi"
   212 "Mbwa"
   213 "Mingo"
   214 "Mirnang"
   215 "Montor"
   216 "Mtchiga/Michika"
   217 "Mumuye"
   218 "Munga"
   219 "Mupung"
   220 "Mushere"
   221 "Mwagavol"
   222 "Naiawum"
   223 "Namoen"
   224 "Ndokwa"
   225 "Ndola"
   226 "Ngamo"
   227 "Ukale"
   228 "Ngoshe"
   229 "Nili"
   230 "Ninnma"
   231 "Ninzom"
   232 "Nkoroo"
   233 "Nnebe"
   234 "Numana"
   235 "Nungu"
   236 "nunku"
   237 "Nupe"
   238 "Obubua"
   239 "Odu"
   240 "Ogoja"
   241 "Ogoni"
   242 "Ogugu"
   243 "Okori/Ogori"
   244 "Omele"
   245 "Ora"
   246 "Oron"
   247 "Owan"
   249 "Owo"
   250 "Pa'awa"
   251 "Paburi"
   252 "Paibun"
   253 "Panya"
   254 "Pasama"
   255 "Pero"
   256 "Piya"
   257 "Pyem"
   258 "Rukuba"
   259 "Rulere"
   260 "Rundawa"
   261 "Sayawa/Siyawa"
   262 "Sekere"
   263 "Sharawa"
   264 "Shomo"
   265 "Shuwa"
   266 "Somunka"
   267 "Sullubawa"
   268 "Sura"
   269 "Taira"
   270 "Tangale"
   272 "Tarok"
   273 "Tera"
   274 "Teskwa"
   275 "Tiguni"
   276 "Tiv"
   277 "Tiyari"
   278 "Tula"
   279 "Ubaija"
   280 "Ugbia"
   281 "Uhionigbe"
   282 "Ukwuani"
   283 "Urhobo"
   284 "Uyo"
   285 "Uzaurue"
   286 "Uzeba"
   287 "Waja"
   288 "Waka"
   289 "Wanu"
   290 "Wari"
   291 "Warjawa"
   292 "Wodaabe"
   293 "Wurkum"
   294 "Yakurr"
   295 "Yandang"
   296 "Yendre"
   297 "Yonubi"
   298 "Yoruba"
   299 "Zabarmawa"
   301 "Kaje"
   302 "Igbanko"
   303 "Okori/Ogori"
   304 "Migili"
   305 "Gwari"
   306 "Uru"
   307 "Okirika"
   308 "Egi"
   309 "Ogba"
   310 "Moroa"
   311 "Marwa"
   312 "Toff"
   313 "Fulfulde"
   314 "Kabba/Okun"
   315 "Bakabe"
   316 "Burmanch"
   317 "Kalabari"
   320 "Miship"
   321 "Karimjo"
   322 "Kwa"
   323 "Angas"
   324 "Bobari"
   325 "Yarimawa"
   326 "Bakenga"
   327 "Agazawa"
   328 "Gwoza"
   329 "Zalidva"
   330 "Nyangdang"
   331 "Ngezim"
   332 "Hanbagda"
   333 "Njanyi"
   334 "Dumak"
   335 "Kwalla"
   336 "Yeskwa and Mubula"
   337 "Bile"
   338 "Offa"
   339 "Yungur"
   340 "Pura Pura"
   341 "Rindre"
   342 "Dukawa"
   343 "Ningi"
   344 "Cham"
   345 "Kamo"
   346 "Lala"
   347 "Laru"
   348 "Lisa"
   349 "Gaanda"
   350 "Ezza"
   351 "Kubasawa."
   352 "Gusu"
   353 "Ikpoma"
   354 "Buh"
   355 "Mushere"
   356 "Chakeem"
   357 "Jipal"
   358 "Ugeb"
   359 "Koma"
   360 "Verre/Kila"
   361 "Zuru"
   362 "Honna"
   363 "Kapsiki"
   364 "Jere"
   365 "Gizi Yobe"
   366 "Karekare"
   367 "Kulere"
   368 "Beteer"
   369 "Bashama"
   370 "Antocha"
   371 "Baruba/Baruntin"
   372 "Nezou"
   373 "Dibba"
   374 "Kanum"
   375 "Gasawa"
   376 "Muryan"
   377 "Bageri"
   378 "Ahu"
   379 "Basange"
   380 "Nakere"
   381 "Batunu"
   382 "Sanga"
   383 "Ohari"
   384 "Numuro"
   385 "Tangale"
   386 "Guruma"
   387 "Otuwo"
   388 "Batala"
   389 "Ogbo"
   390 "Egbema"
   391 "Dara"
   392 "Andoni"
   393 "Obolo"
   394 "Pegan"
   395 "Iyala"
   396 "Jibawa"
   397 "Mungaduso"
   398 "Okobo"
   996 "Others"
   998 "Don't know"
;
label define V133    
    97 "Inconsistent"
;
label define V134    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V135    
     1 "Usual resident"
     2 "Visitor"
;
label define V139    
     0 "Abroad"
     1 "North west"
     2 "North east"
     3 "North central"
     4 "South east"
     5 "South south"
     6 "South west"
    97 "Not a de jure resident"
;
label define V140    
     0 "Abroad"
     1 "Urban"
     2 "Rural"
     7 "Not a de jure resident"
;
label define V141    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     7 "Not a de jure resident"
;
label define V149    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define V150    
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    15 "Brother/sister in law"
    98 "Don't know"
;
label define V151    
     1 "Male"
     2 "Female"
;
label define V152    
    97 "97+"
    98 "Don't know"
;
label define V153    
     0 "No"
     1 "Yes"
     7 "Not a de jure resident"
;
label define V155    
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define V156    
     0 "No"
     1 "Yes"
;
label define V157    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V158    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V159    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V160    
     0 "No"
     1 "Yes"
     7 "Not a de jure resident"
;
label define V161    
     1 "Electricity"
     2 "Solar energy"
     3 "Liquefied petroleum gas (LPG)/cooking gas"
     4 "Piped natural gas"
     5 "Biogas"
     6 "Alcohol/ethanol"
     7 "Gasoline/diesel"
     8 "Kerosene/paraffin"
     9 "Coal/lignite"
    10 "Charcoal"
    11 "Wood"
    12 "Straw/shrubs/grass"
    13 "Agricultural crop"
    14 "Animal dung/waste"
    15 "Processed biomass (pellets) or woodchips"
    16 "Garbage/plastic"
    17 "Sawdust"
    95 "No food cooked in house"
    96 "Other"
    97 "Not a de jure resident"
;
label define V166    
     0 "0 ppm (no iodine)"
     7 "7 ppm"
    15 "15 ppm"
    30 "30 ppm"
   994 "Salt not tested"
   995 "No salt"
   997 "Not a de jure resident"
;
label define V167    
     0 "None"
    90 "90+"
;
label define V168    
     0 "No"
     1 "Yes"
;
label define V169A   
     0 "No"
     1 "Yes"
;
label define V169B   
     0 "No"
     1 "Yes"
;
label define V169C   
     0 "No"
     1 "Yes"
;
label define V170    
     0 "No"
     1 "Yes"
;
label define V171A   
     0 "Never"
     1 "Yes, last 12 months"
     2 "Yes, before last 12 months"
     3 "Yes, can't establish when"
;
label define V171B   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V172    
     1 "FCT-Abuja"
     2 "Benue"
     3 "Kogi"
     4 "Kwara"
     5 "Nasarawa"
     6 "Niger"
     7 "Plateau"
     8 "Adamawa"
     9 "Bauchi"
    10 "Borno"
    11 "Gombe"
    12 "Taraba"
    13 "Yobe"
    14 "Jigawa"
    15 "Kaduna"
    16 "Kano"
    17 "Katsina"
    18 "Kebbi"
    19 "Sokoto"
    20 "Zamfara"
    21 "Abia"
    22 "Anambra"
    23 "Ebonyi"
    24 "Enugu"
    25 "Imo"
    26 "Akwa Ibom"
    27 "Bayelsa"
    28 "Cross River"
    29 "Delta"
    30 "Edo"
    31 "Rivers"
    32 "Ekiti"
    33 "Lagos"
    34 "Ogun"
    35 "Ondo"
    36 "Osun"
    37 "Oyo"
    96 "Outside of Nigeria"
;
label define V173    
     2 "Algeria"
     3 "Angola"
     4 "Benin"
     5 "Botswana"
     6 "Burkina Faso"
     7 "Burundi"
     8 "Cabo Verde"
     9 "Cameroon"
    10 "Central African Republic (CAR)"
    11 "Chad"
    12 "Comoros"
    13 "Democratic Republic of the Congo"
    14 "Republic of the Congo"
    15 "Cote d'Ivoire"
    16 "Djibouti"
    17 "Egypt"
    18 "Equatorial Guinea"
    19 "Eritrea"
    20 "Eswatini"
    21 "Ethiopia"
    22 "Gabon"
    23 "Gambia"
    24 "Ghana"
    25 "Guinea"
    26 "Guinea-Bissau"
    27 "Kenya"
    28 "Lesotho"
    29 "Liberia"
    30 "Libya"
    31 "Madagascar"
    32 "Malawi"
    33 "Mali"
    34 "Mauritania"
    35 "Morocco"
    36 "Mozambique"
    37 "Namibia"
    38 "Niger"
    39 "Rwanda"
    40 "Sao Tome and Principe"
    41 "Senegal"
    42 "Seychelles"
    43 "Sierra Leone"
    44 "Somalia"
    45 "South Africa"
    46 "South Sudan"
    47 "Sudan"
    48 "Tanzania"
    49 "Togo"
    50 "Tunisia"
    51 "Uganda"
    52 "Zambia"
    53 "Zimbabwe"
    96 "Other country"
;
label define V174M   
    98 "Don't know month"
;
label define V174Y   
  9998 "Don't know year"
;
label define V175    
     1 "Employment"
     2 "Education/training"
     3 "Marriage formation"
     4 "Family reunification/other family-related reason"
     5 "Forced displacement"
    96 "Other"
;
label define V176    
     1 "Very good"
     2 "Good"
     3 "Moderate"
     4 "Bad"
     5 "Very bad"
;
label define V177    
     0 "No"
     1 "Yes"
;
label define V190    
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define V190A   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define ML101   
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define MM1     
     1 "Male"
     2 "Female"
     8 "Don't know"
;
label define MM2     
     0 "Dead"
     1 "Alive"
     8 "Don't know"
;
label define MM3     
    96 "96+"
    98 "Don't know"
;
label define MM5     
     0 "Never married"
     1 "Ever married"
     8 "Don't know"
;
label define MM6     
    96 "96+"
    98 "Don't know"
;
label define MM7     
    96 "96+"
    98 "Don't know"
;
label define MM9     
     0 "Never pregnant"
     1 "Death not related"
     2 "Died while pregnant"
     3 "Died during delivery"
     4 "Since delivery"
     5 "6 weeks after delivery"
     6 "2 months after delivery"
    98 "Don't know"
;
label define MM10    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MM11    
     0 "Country specific"
;
label define MM12    
   100 "Same day"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
   997 "Inconsistent"
   998 "Don't know"
;
label define MM13    
     0 "Country specific"
;
label define MM14    
    99 "Missing"
;
label define MM15    
  9998 "Don't know"
;
label define MM16    
     0 "No"
     1 "Violence"
     2 "Accident"
;
label define MMC1    
    99 "Missing"
;
label define MMC2    
    99 "Missing"
;
label define MMC3    
     0 "Respondent reported"
;
label define MMC4    
    99 "Missing"
;
label define MMC5    
    10 "10 years"
    12 "12 years"
    13 "13 years"
    15 "15 years"
;

#delimit cr
label values v013     V013    
label values v014     V014    
label values v015     V015    
label values v018     V018    
label values v019     V019    
label values v019a    V019A   
label values v020     V020    
label values v022     V022    
label values v023     V023    
label values v024     V024    
label values v025     V025    
label values v026     V026    
label values v034     V034    
label values v042     V042    
label values v044     V044    
label values v045a    V045A   
label values v045b    V045B   
label values v045c    V045C   
label values v046     V046    
label values v101     V101    
label values v102     V102    
label values v103     V103    
label values v104     V104    
label values v105     V105    
label values v105a    V105A   
label values v106     V106    
label values v107     V107    
label values v113     V113    
label values v115     V115    
label values v116     V116    
label values v119     V119    
label values v120     V120    
label values v121     V121    
label values v122     V122    
label values v123     V123    
label values v124     V124    
label values v125     V125    
label values v127     V127    
label values v128     V128    
label values v129     V129    
label values v130     V130    
label values v131     V131    
label values v133     V133    
label values v134     V134    
label values v135     V135    
label values v139     V139    
label values v140     V140    
label values v141     V141    
label values v149     V149    
label values v150     V150    
label values v151     V151    
label values v152     V152    
label values v153     V153    
label values v155     V155    
label values v156     V156    
label values v157     V157    
label values v158     V158    
label values v159     V159    
label values v160     V160    
label values v161     V161    
label values v166     V166    
label values v167     V167    
label values v168     V168    
label values v169a    V169A   
label values v169b    V169B   
label values v169c    V169C   
label values v170     V170    
label values v171a    V171A   
label values v171b    V171B   
label values v172     V172    
label values v173     V173    
label values v174m    V174M   
label values v174y    V174Y   
label values v175     V175    
label values v176     V176    
label values v177     V177    
label values v190     V190    
label values v190a    V190A   
label values ml101    ML101   
label values mm1      MM1     
label values mm2      MM2     
label values mm3      MM3     
label values mm5      MM5     
label values mm6      MM6     
label values mm7      MM7     
label values mm9      MM9     
label values mm10     MM10    
label values mm11     MM11    
label values mm12     MM12    
label values mm13     MM13    
label values mm15     MM15    
label values mm16     MM16    
label values mmc3     MMC3    
label values mmc5     MMC5    
