infix using "C:\COUNTRIES\NG53\NGPR53FL.dct"

label variable hhid     "Case Identification"
label variable hvidx    "Line number"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number"
label variable hv004    "Ultimate area unit"
label variable hv005    "Sample weight"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in HH"
label variable hv011    "Number of eligible men in HH"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample stratum number"
label variable hv023    "Sample domain"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "[NA] Place of residence"
label variable hv027    "Selection for male/husb. int."
label variable hv028    "Sample weight for male subsamp"
label variable hv030    "Field supervisor"
label variable hv031    "Field editor"
label variable hv032    "Office editor"
label variable hv033    "[NA] Ultimate area selection prob."
label variable hv035    "Number of eligible children for height & weight"
label variable hv040    "[NA] Cluster altitude in meters"
label variable hv041    "Total adults measured"
label variable hv042    "[NA] Selection for hemoglobin"
label variable hv043    "[NA] Selection for women's status module"
label variable hv044    "Selection for domestic violence module"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv204    "Time to get to water source"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of househ."
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "Have bednet for sleeping"
label variable hv228    "Children under 5 slept under bednet last night"
label variable hv234    "Test salt for Iodine"
label variable hv235    "Location of source for water"
label variable hv236    "Person fetching water"
label variable hv237    "Anything done to water to make safe to drink"
label variable hv237a   "Water usually treated by: boil"
label variable hv237b   "Water usually treated by: add bleach/chlorine"
label variable hv237c   "Water usually treated by: strain through a cloth"
label variable hv237d   "Water usually treated by: use water filter"
label variable hv237e   "Water usually treated by: solar disinfection"
label variable hv237f   "Water usually treated by: let it stand and settle"
label variable hv237g   "Water usually treated by: alum (CS)"
label variable hv237h   "[NA] Water usually treated by: CS"
label variable hv237i   "[NA] Water usually treated by: CS"
label variable hv237j   "[NA] Water usually treated by: CS"
label variable hv237k   "[NA] Water usually treated by: CS"
label variable hv237x   "Water usually treated by: other"
label variable hv237z   "Water usually treated by: don't know"
label variable hv238    "Number of households sharing toilet"
label variable hv239    "Food cooked on stove or open fire"
label variable hv240    "Household has a chimney, hood or neither"
label variable hv241    "Food cooked in the house / in separate building / outdoors"
label variable hv242    "Household has separate room used as kitchen"
label variable hv243a   "Has a mobile telephone"
label variable hv243b   "[NA] Has a watch"
label variable hv243c   "Has an animal-drawn cart"
label variable hv243d   "Has a boat with a motor"
label variable hv244    "Own land usable for agriculture"
label variable hv245    "[NA] Hectares for agricultural land"
label variable hv246    "Livestock, herds or farm animals"
label variable hv246a   "[NA] Cattle own"
label variable hv246b   "Cows, bulls own"
label variable hv246c   "Horses, donkeys, mules own"
label variable hv246d   "Goats own"
label variable hv246e   "Sheep own"
label variable hv246f   "Chickens own"
label variable hv246g   "CS: pigs"
label variable hv246h   "CS own Other 1"
label variable hv246i   "CS own Other 2"
label variable hv246j   "[NA] CS own"
label variable hv246k   "[NA] CS own"
label variable hv247    "Owns a bank account"
label variable hv248    "Number of sick people 18-59"
label variable hv249    "Member of the HH died last 12 months"
label variable hv250    "Number of members who died last 12 months"
label variable hv251    "Number of orphans and vulnerable children"
label variable hv270    "Wealth index"
label variable hv271    "Wealth index factor score (5 decimals)"
label variable hml1     "Number of mosquito nets"
label variable hml1a    "Number of mosquito nets with specific information"
label variable hml2     "Number of children under bednet previous night"
label variable shstate  "State"
label variable shlocgov "Local Government area"
label variable shlocality "Locality"
label variable shea     "Enumeration Area"
label variable shbldg   "Building number"
label variable shintnums "Interviewer's assigned state"
label variable shvisits "Number of household visits"
label variable shlangint "Language of interview"
label variable shnlang  "Native language of respondent"
label variable shtrans  "Translator used"
label variable shnumdv  "Line number of woman eligible for domestic violence"
label variable sh111g   "Cable TV"
label variable sh111h   "Generating set"
label variable sh111i   "Air conditioner"
label variable sh111j   "Computer"
label variable sh111k   "Electric iron"
label variable sh111l   "Fan"
label variable sh120a   "Total number of rooms in HH"
label variable sh121a   "Canoe"
label variable sh123    "Agricultural land owned"
label variable s2003st  "2008 state codes reclassified into 2003 state codes"
label variable hv101    "Relationship to head"
label variable hv102    "Usual resident"
label variable hv103    "Slept last night"
label variable hv104    "Sex of household member"
label variable hv105    "Age of household members"
label variable hv106    "Highest educational level"
label variable hv107    "Highest year of education"
label variable hv108    "Education in single years"
label variable hv109    "Educational attainment"
label variable hv110    "[NA] Member still in school"
label variable hv111    "Mother alive"
label variable hv112    "Mother's line number"
label variable hv113    "Father alive"
label variable hv114    "Father's line number"
label variable hv115    "Current marital status"
label variable hv116    "Currently, formerly, never m."
label variable hv117    "Eligibility for female interview"
label variable hv118    "Eligibility for male interview"
label variable hv120    "Children eligibility for height/weight and hemoglobin"
label variable hv121    "Member attended school during current school year"
label variable hv122    "Educational level during current school year"
label variable hv123    "Grade of education during current school year"
label variable hv124    "Education in single years - current school year"
label variable hv125    "Member attended school during previous school year"
label variable hv126    "Educational level during previous school year"
label variable hv127    "Grade of education during previous school year"
label variable hv128    "Education in single years - previous school year"
label variable hv129    "School attendance status"
label variable hv130    "Member has been very sick for 3+ months last year"
label variable hv131    "Mother has been very sick for 3+ months last year"
label variable hv132    "Father has been very sick for 3+ months last year"
label variable hv133    "Mother/father dead or been very sick for 3+ months"
label variable hv134    "Both parents alive"
label variable hv135    "Has brothers/sisters under 18 of the same father and mother"
label variable hv136    "Brothers/sisters under 18 that don't live in household"
label variable hv137    "Member has a blanket"
label variable hv138    "Member has a pair of shoes"
label variable hv139    "Member has 2+ sets of clothes"
label variable hv140    "[NA] Member has a birth certificate"
label variable idxh4    "Index to household schedule"
label variable sh03     "Relationship to head"
label variable sh24a    "Level of education attended"
label variable sh24b    "Highest grade completed"
label variable sh26a    "Level of education attending"
label variable sh26b    "Grade attending"
label variable sh28a    "Level of education last year"
label variable sh28b    "Grade attended last year"
label variable sh32     "Registered"
label variable sh33     "Authority where birth cert registered"
label variable sh33a    "Birth cert seen"
label variable sh34     "Last 12 mos, any drug taken for river blindness"
label variable sh35     "Last 12 mos, any drug taken for elephantitis"
label variable sh36     "Last 12 mos, suffer from guinea worms"
label variable sh37     "Last 12 mos, any drug taken for bilharazia"
label variable sh38     "Any blood in urine during last month"
label variable ha0      "Index to household schedule"
label variable ha1      "Women's age in years"
label variable ha2      "Respondent's weight (kilos-1d)"
label variable ha3      "Respondent's height (cms-1d)"
label variable ha4      "Ht/A Percentile (resp.)"
label variable ha5      "Ht/A Standard deviations (resp"
label variable ha6      "Ht/A Percent ref. median (resp"
label variable ha11     "Wt/Ht Std deviations(resp) DHS"
label variable ha12     "Wt/Ht Percent ref. median (DHS"
label variable ha12a    "Wt/Ht Percent ref. median (Fog"
label variable ha12b    "Wt/Ht Percent ref. median (WHO"
label variable ha13     "Result of measurement of resp."
label variable ha32     "Date of birth (cmc)"
label variable ha33     "Completeness of information"
label variable ha35     "Smoking"
label variable ha40     "Body mass index for respondent"
label variable ha41     "Rohrer's index for respondent"
label variable ha50     "[NA] Under age 18"
label variable ha51     "[NA] Line no. of parent/caretaker"
label variable ha52     "[NA] Read consent statement"
label variable ha53     "[NA] Hemoglobin level (g/dl - 1 decimal)"
label variable ha54     "[NA] Currently pregnant"
label variable ha55     "[NA] Result of measuring (Hemoglobin)"
label variable ha56     "[NA] Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable ha57     "[NA] Anemia level"
label variable ha58     "[NA] Agrees to referral"
label variable ha60     "[NA] Marital status"
label variable ha61     "[NA] Read consent statement (HIV)"
label variable ha62     "[NA] Blood sample ID number"
label variable ha63     "[NA] Result of measuring (HIV)"
label variable ha64     "[NA] Consent for additional tests"
label variable ha65     "Result of woman individual interview"
label variable ha66     "Woman's highest educational level"
label variable ha67     "Woman's highest year of education"
label variable ha68     "Highest educational level (CS for preliminary & final report)"
label variable ha69     "[NA] HIV weight (6 decimals)"
label variable hc0      "Index to household schedule"
label variable hc1      "Age in months"
label variable hc2      "Weight in kilograms (1 dec.)"
label variable hc3      "Height in centimeters (1 dec.)"
label variable hc4      "Ht/A Percentile"
label variable hc5      "Ht/A Standard deviations"
label variable hc6      "Ht/A Percent of ref. median"
label variable hc7      "Wt/A Percentile"
label variable hc8      "Wt/A Standard deviations"
label variable hc9      "Wt/A Percent of ref. median"
label variable hc10     "Wt/Ht Percentile"
label variable hc11     "Wt/Ht Standard deviations"
label variable hc12     "Wt/Ht Percent of ref. median"
label variable hc13     "Reason not measured"
label variable hc15     "Height: lying or standing"
label variable hc16     "Day of birth of child"
label variable hc17     "Date measured (day)"
label variable hc18     "Date measured (month)"
label variable hc19     "Date measured (year)"
label variable hc27     "Sex"
label variable hc30     "Month of birth of child"
label variable hc31     "Year of birth of child"
label variable hc32     "Date of birth (cmc)"
label variable hc33     "Completeness of information"
label variable hc51     "[NA] Line no. of parent/caretaker"
label variable hc52     "[NA] Read consent statement"
label variable hc53     "[NA] Hemoglobin level (g/dl - 1 decimal)"
label variable hc55     "[NA] Result of measuring (Hemoglobin)"
label variable hc56     "[NA] Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable hc57     "[NA] Anemia level"
label variable hc58     "[NA] Agrees to referral"
label variable hc60     "Mother's line number from woman's questionnaire"
label variable hc61     "Mother's highest educational level"
label variable hc62     "Mother's highest year of education"
label variable hc63     "Preceding birth interval"
label variable hc64     "Birth order number"
label variable hc68     "Highest educational level (CS for preliminary & final report)"
label variable hc70     "Ht/A Standard deviations (according to WHO)"
label variable hc71     "Wt/A Standard deviations (according to WHO)"
label variable hc72     "Wt/Ht Standard deviations (according to WHO)"
label variable hc73     "BMI Standard deviations (according to WHO)"
label variable hmlidx   "Net number"
label variable hml3     "Net observed"
label variable hml4     "Months ago obtained mosquito net"
label variable hml5     "Was net treated with insecticide when bought"
label variable hml6     "Mosquito net treated with insecticide"
label variable hml7     "Brand of bednet"
label variable hml8     "Bednet treated since receiving"
label variable hml9     "Months ago re-treated"
label variable hml10    "ITN net"
label variable hml11    "Number of persons who slept under this net"
label variable hml21    "Did someone sleep under bednet last night"
label variable hmla     "Person who slept in mosquito net"
label variable hmlb     "Person who slept in mosquito net"
label variable hmlc     "Person who slept in mosquito net"
label variable hmld     "Person who slept in mosquito net"
label variable hmle     "[NA] Person who slept in mosquito net"
label variable hmhidx   "Index to household schedule"
label variable hml12    "Type of bednet(s) person slept under last night"
label variable hml13    "1st net number for net person slept under last night"
label variable hml14    "2nd net number for net person slept under last night"
label variable hml15    "[NA] 3rd net number for net person slept under last night"
label variable hml16    "Corrected age from individual questionnaire"
label variable hml17    "Flag for AH07 age from individual file"
label variable hml18    "Pregnancy from individual questionnaire"
label variable hml19    "Person sleep under an ever treated bednet"
label variable hskidx   "Index to household schedule"
label variable hs100    "Free medical support last 12 months"
label variable hs101    "Medical support at least once a month"
label variable hs102    "Free emotinal support last 12 months"
label variable hs103    "Emotional support last 30 days"
label variable hs104    "Free material support last 12 months"
label variable hs105    "Material support last 30 days"
label variable hs106    "Free social support last 12 months"
label variable hs107    "Social support last 30 days"
label variable hs108    "Pain last 30 days"
label variable hs109    "Able to reduce the pain"
label variable hs110    "Nausea last 30 days"
label variable hs111    "Able to reduce the nausea"
label variable hovidx   "Index to household schedule"
label variable ho100    "Age of child"
label variable ho101    "Free medical support last 12 months"
label variable ho102    "Free emotional support last 12 months"
label variable ho103    "Emotional support last 3 months"
label variable ho104    "Free material support last 12 months"
label variable ho105    "Material support last 3 months"
label variable ho106    "Free social support last 12 months"
label variable ho107    "Social support last 3 months"
label variable ho108    "Free support for schooling"

#delimit ;
label define HV003   
   999 "Missing"
;
label define HV006   
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
;
label define HV015   
     1 "Completed"
     2 "HH present, no resp"
     3 "HH absent"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     3 "3+"
;
label define HV018   
   999 "Missing"
;
label define HV019   
    99 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV022   
     1 "North Central Urban"
     2 "North Central Rural"
     3 "North East Urban"
     4 "North East Rural"
     5 "North West Urban"
     6 "North West Rural"
     7 "South East Urban"
     8 "South East Rural"
     9 "South South Urban"
    10 "South South Rural"
    11 "South West Urban"
    12 "South West Rural"
;
label define HV023   
     0 "National"
     1 "Sokoto"
     2 "Zamfara"
     3 "Katsina"
     4 "Jigawa"
     5 "Yobe"
     6 "Borno"
     7 "Adamawa"
     8 "Gombe"
     9 "Bauchi"
    10 "Kano"
    11 "Kaduna"
    12 "Kebbi"
    13 "Niger"
    14 "Abuja"
    15 "Nasarawa"
    16 "Plateau"
    17 "Taraba"
    18 "Benue"
    19 "Kogi"
    20 "Kwara"
    21 "Oyo"
    22 "Osun"
    23 "Ekiti"
    24 "Ondo"
    25 "Edo"
    26 "Anambra"
    27 "Enugu"
    28 "Ebonyi"
    29 "Cross River"
    30 "Akwa Ibom"
    31 "Abia"
    32 "Imo"
    33 "Rivers"
    34 "Bayelsa"
    35 "Delta"
    36 "Lagos"
    37 "Ogun"
;
label define HV024   
     1 "North Central"
     2 "North East"
     3 "North West"
     4 "South East"
     5 "South South"
     6 "South West"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV043   
     0 "Household not selected"
     1 "Household selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irirgation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irirgation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    11 "Flush - to piped sewer system"
    12 "Flush - to septic tank"
    13 "Flush - to pit latrine"
    14 "Flush - to somewhere else"
    15 "Flush - don't know where"
    21 "Pit latrine - ventilated improved pit (VIP)"
    22 "Pit latrine - with slab"
    23 "Pit latrine - without slab / open pit"
    31 "No facility"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "OTHER"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth, sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm, bamboo"
    30 "FINISHED"
    31 "Parquet, polished wood"
    32 "Vinyl, asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "OTHER"
;
label define HV214   
    10 "NATURAL"
    11 "No walls"
    12 "Cane / palm / trunks"
    13 "Dirt"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime / cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks / shingles"
    96 "Other"
;
label define HV215   
    10 "NATURAL"
    11 "No roof"
    12 "Thatch / palm leaf"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm / bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Metal"
    32 "Wood"
    33 "Calamine / cement fiber"
    34 "Ceramic tiles"
    35 "Cement"
    36 "Roofing shingles"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opp. sex"
     3 "Two adults, same sex"
     4 "Three+ related adult"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "DK"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw / shrubs / grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in HH"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No bednet in HH"
;
label define HV234   
     0 "0 PPM (No Iodine)"
     7 "Below 15 PPM"
    15 "15 PPM and above"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV236   
     1 "Adult woman"
     2 "Adult man"
     3 "Female child under 15 years old"
     4 "Male child under 15 years old"
     5 "Adult woman with child"
     6 "Other"
     7 "Female and male child under 15 years old"
     8 "Any household member"
;
label define HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237I  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237J  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237K  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237Z  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     0 "Neither chimney or hood"
     1 "Chimney"
     2 "Hood"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
    95 "More than 95"
    98 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV249   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define HV250   
     8 "DK"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SHSTATE 
    10 "Sokoto"
    20 "Zamfara"
    30 "Katsina"
    40 "Jigawa"
    50 "Yobe"
    60 "Borno"
    70 "Adamawa"
    80 "Gombe"
    90 "Bauchi"
   100 "Kano"
   110 "Kaduna"
   120 "Kebbi"
   130 "Niger"
   140 "Abuja"
   150 "Nasarawa"
   160 "Plateau"
   170 "Taraba"
   180 "Benue"
   190 "Kogi"
   200 "Kwara"
   210 "Oyo"
   220 "Osun"
   230 "Ekiti"
   240 "Ondo"
   250 "Edo"
   260 "Anambra"
   270 "Enugu"
   280 "Ebonyi"
   290 "Cross River"
   300 "Akwa Ibom"
   310 "Abia"
   320 "Imo"
   330 "Rivers"
   340 "Bayelsa"
   350 "Delta"
   360 "Lagos"
   370 "Ogun"
;
label define SHINTNUMS
     1 "Sokoto"
     2 "Zamfara"
     3 "Katsina"
     4 "Jigawa"
     5 "Yobe"
     6 "Borno"
     7 "Adamawa"
     8 "Gombe"
     9 "Bauchi"
    10 "Kano"
    11 "Kaduna"
    12 "Kebbi"
    13 "Niger"
    14 "Abuja"
    15 "Nasarawa"
    16 "Plateau"
    17 "Taraba"
    18 "Benue"
    19 "Kogi"
    20 "Kwara"
    21 "Oyo"
    22 "Osun"
    23 "Ekiti"
    24 "Ondo"
    25 "Edo"
    26 "Anambra"
    27 "Enugu"
    28 "Ebonyi"
    29 "Cross River"
    30 "Akwa Ibom"
    31 "Abia"
    32 "Imo"
    33 "Rivers"
    34 "Bayelsa"
    35 "Delta"
    36 "Lagos"
    37 "Ogun"
;
label define SHVISITS
     9 "Missing"
;
label define SHLANGINT
     1 "Hausa"
     2 "Yoruba"
     3 "Igbo"
     4 "English"
     6 "Other"
;
label define SHNLANG 
     1 "Hausa"
     2 "Yoruba"
     3 "Igbo"
     4 "English"
     6 "Other"
;
label define SHTRANS 
     0 "No"
     1 "Yes"
;
label define SH111G  
     0 "No"
     1 "Yes"
;
label define SH111H  
     0 "No"
     1 "Yes"
;
label define SH111I  
     0 "No"
     1 "Yes"
;
label define SH111J  
     0 "No"
     1 "Yes"
;
label define SH111K  
     0 "No"
     1 "Yes"
;
label define SH111L  
     0 "No"
     1 "Yes"
;
label define SH120A  
    99 "Missing"
;
label define SH121A  
     0 "No"
     1 "Yes"
;
label define SH123   
   995 "95+ Plots/Acres/Hectares"
   998 "DK"
;
label define S2003ST 
     1 "Akwa Ibom"
     2 "Anambra"
     3 "Bauchi"
     4 "Edo"
     5 "Benue"
     6 "Borno"
     7 "Cross River"
     8 "Adamawa"
     9 "Imo"
    10 "Kaduna"
    11 "Kano"
    12 "Katsina"
    13 "Kwara"
    14 "Lagos"
    15 "Niger"
    16 "Ogun"
    17 "Ondo"
    18 "Oyo"
    19 "Plateau"
    20 "Rivers"
    21 "Sokoto"
    22 "Abia"
    23 "Delta"
    24 "Enugu"
    25 "Jigawa"
    26 "Kebbi"
    27 "Kogi"
    28 "Osun"
    29 "Taraba"
    30 "Yobe"
    31 "Bayelsa"
    32 "Ebonyi"
    33 "Ekiti"
    34 "Gombe"
    35 "Nassarawa"
    36 "Zamfora"
    37 "Abuja (FCT)"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/ nephew by blood"
    14 "Niece/ nephew by marriage"
    98 "DK"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    96 "96+"
    98 "DK"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV107   
    98 "DK"
;
label define HV108   
    97 "Inconsistent"
    98 "DK"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
;
label define HV110   
     0 "No"
     1 "Yes"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV112   
     0 "Mother not in HH"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV114   
     0 "Father not in HH"
;
label define HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV123   
    98 "DK"
;
label define HV124   
    97 "Inconsistent"
    98 "DK"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV127   
    98 "DK"
;
label define HV128   
    97 "Inconsistent"
    98 "DK"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
;
label define HV130   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV131   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV132   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV133   
     0 "No"
     1 "Yes"
;
label define HV134   
     0 "No"
     1 "Yes"
;
label define HV135   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV136   
     0 "No"
     1 "Yes"
;
label define HV137   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV138   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV139   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     8 "DK"
;
label define SH03    
     1 "Head"
     2 "Wife or husband"
     3 "Son, daughter"
     4 "Son-in-law, daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother, sister"
     9 "Brother/ sister-in-law"
    10 "Niece/Nephew by blood"
    11 "Niece/Nephew by marriage"
    12 "Other relative"
    13 "Adopted/foster/step child"
    14 "Not related"
    98 "DK"
;
label define SH24A   
     0 "Pre-school/kindergarten"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define SH24B   
     0 "< 1 year completed"
     1 "1"
     2 "2"
     3 "3"
     4 "4"
     5 "5"
     6 "6"
     7 "7"
     8 "8"
     9 "9"
    10 "10"
    11 "11"
    12 "12"
    98 "DK"
;
label define SH26A   
     0 "Pre-school/kindergarten"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define SH26B   
     0 "< 1 year completed"
     1 "1"
     2 "2"
     3 "3"
     4 "4"
     5 "5"
     6 "6"
     7 "7"
     8 "8"
     9 "9"
    10 "10"
    11 "11"
    12 "12"
    98 "DK"
;
label define SH28A   
     0 "Pre-school/kindergarten"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define SH28B   
     0 "< 1 year completed"
     1 "1"
     2 "2"
     3 "3"
     4 "4"
     5 "5"
     6 "6"
     7 "7"
     8 "8"
     9 "9"
    10 "10"
    11 "11"
    12 "12"
    98 "DK"
;
label define SH32    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH33    
     1 "National Population Commission"
     2 "Local Governemt Administration"
     3 "Private clinic/ hospital"
     4 "Other"
;
label define SH33A   
     0 "Not seen"
     1 "Seen"
;
label define SH34    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH35    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH36    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH37    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH38    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HA2     
  9999 "Missing"
;
label define HA3     
  9999 "Missing"
;
label define HA4     
  9998 "Flagged cases"
;
label define HA5     
  9998 "Flagged cases"
;
label define HA6     
 99998 "Flagged cases"
;
label define HA11    
  9998 "Flagged cases"
;
label define HA12    
 99998 "Flagged cases"
;
label define HA12A   
 99998 "Flagged cases"
;
label define HA12B   
 99998 "Flagged cases"
;
label define HA13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA33    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define HA35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
;
label define HA40    
  9998 "Flagged cases"
;
label define HA41    
  9998 "Flagged cases"
;
label define HA50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HA51    
     0 "Not in household"
;
label define HA52    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
;
label define HA53    
   999 "Missing"
;
label define HA54    
     0 "No/don't know"
     1 "Yes"
;
label define HA55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA56    
   999 "Missing"
;
label define HA57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HA58    
     0 "No"
     1 "Yes"
;
label define HA60    
     1 "Never in union"
     2 "Other"
;
label define HA61    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
     4 "Sample not tested/lost/not enough DBS"
;
label define HA63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HA64    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
;
label define HA65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HA66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define HA67    
    99 "Missing"
;
label define HA68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define HC2     
  9999 "Missing"
;
label define HC3     
  9999 "Missing"
;
label define HC4     
  9998 "Flagged cases"
;
label define HC5     
  9998 "Flagged cases"
;
label define HC6     
 99998 "Flagged cases"
;
label define HC7     
  9998 "Flagged cases"
;
label define HC8     
  9998 "Flagged cases"
;
label define HC9     
 99998 "Flagged cases"
;
label define HC10    
  9998 "Flagged cases"
;
label define HC11    
  9998 "Flagged cases"
;
label define HC12    
 99998 "Flagged cases"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC15    
     1 "Lying"
     2 "Standing"
;
label define HC16    
    99 "Missing"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "DK"
;
label define HC31    
  9997 "Inconsistent"
  9998 "DK"
;
label define HC33    
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
;
label define HC53    
   999 "Missing"
;
label define HC55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC56    
   999 "Missing"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define HC62    
    99 "Missing"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HML3    
     0 "Not seen"
     1 "Yes, seen"
;
label define HML4    
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML5    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HML6    
     0 "Not pretreated"
     1 "Pretreated, permanent tx"
     2 "Pretreated, requiring future tx"
     3 "Not pretreated, came with kit and treated at home"
     4 "Pretreated, treatment type not known"
     6 "Other"
     8 "Don't know"
;
label define HML7    
    11 "Untreated net"
    21 "Long-lasting net"
    31 "Re-treatable net"
    41 "Other"
    98 "DK Brand"
;
label define HML8    
     0 "No"
     1 "Yes"
     2 "Permanent net"
     8 "Not sure"
;
label define HML9    
    96 "More than 2 years ago"
    98 "Don't know"
;
label define HML10   
     0 "No, don't know"
     1 "Yes"
;
label define HML11   
     5 "5+"
;
label define HML21   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HMLA    
     0 "No one"
;
label define HMLB    
    99 "Missing"
;
label define HMLC    
    99 "Missing"
;
label define HML12   
     0 "No bednet"
     1 "Only treated bednets"
     2 "Both treated and untreated bednets"
     3 "Only untreated bednets"
;
label define HML13   
     0 "Did not sleep under net"
;
label define HML16   
    97 "97+"
    98 "DK"
;
label define HML17   
     0 "No data from individual questionnaire"
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define HML18   
     0 "Not pregnant, don't know"
     1 "Pregnant"
;
label define HML19   
     0 "No"
     1 "Yes"
;
label define HS100   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS101   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS102   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS103   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS104   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS105   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS106   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS107   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS108   
     0 "Not at all"
     1 "Severe"
     2 "Mild"
     8 "DK"
;
label define HS109   
     0 "Not at all"
     1 "Most of the time"
     2 "Some time"
;
label define HS110   
     0 "No"
     1 "Yes, severe"
     2 "Yes, never severe"
;
label define HS111   
     0 "Not at all"
     1 "Most of the time"
     2 "Some time"
;
label define HO100   
    99 "Missing"
;
label define HO101   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO102   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO103   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO104   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO105   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO106   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO107   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO108   
     0 "No"
     1 "Yes"
     8 "DK"
;

#delimit cr
label values hv006    HV006   
label values hv015    HV015   
label values hv017    HV017   
label values hv020    HV020   
label values hv022    HV022   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv043    HV043   
label values hv044    HV044   
label values hv201    HV201   
label values hv202    HV202   
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv234    HV234   
label values hv235    HV235   
label values hv236    HV236   
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237g   HV237G  
label values hv237h   HV237H  
label values hv237i   HV237I  
label values hv237j   HV237J  
label values hv237k   HV237K  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv249    HV249   
label values hv250    HV250   
label values hv270    HV270   
label values hml1     HML1    
label values shstate  SHSTATE 
label values shintnums SHINTNUMS
label values shlangint SHLANGINT
label values shnlang  SHNLANG 
label values shtrans  SHTRANS 
label values sh111g   SH111G  
label values sh111h   SH111H  
label values sh111i   SH111I  
label values sh111j   SH111J  
label values sh111k   SH111K  
label values sh111l   SH111L  
label values sh121a   SH121A  
label values sh123    SH123   
label values s2003st  S2003ST 
label values hv101    HV101   
label values hv102    HV102   
label values hv103    HV103   
label values hv104    HV104   
label values hv105    HV105   
label values hv106    HV106   
label values hv107    HV107   
label values hv108    HV108   
label values hv109    HV109   
label values hv110    HV110   
label values hv111    HV111   
label values hv112    HV112   
label values hv113    HV113   
label values hv114    HV114   
label values hv115    HV115   
label values hv116    HV116   
label values hv117    HV117   
label values hv118    HV118   
label values hv120    HV120   
label values hv121    HV121   
label values hv122    HV122   
label values hv123    HV123   
label values hv124    HV124   
label values hv125    HV125   
label values hv126    HV126   
label values hv127    HV127   
label values hv128    HV128   
label values hv129    HV129   
label values hv130    HV130   
label values hv131    HV131   
label values hv132    HV132   
label values hv133    HV133   
label values hv134    HV134   
label values hv135    HV135   
label values hv136    HV136   
label values hv137    HV137   
label values hv138    HV138   
label values hv139    HV139   
label values hv140    HV140   
label values sh03     SH03    
label values sh24a    SH24A   
label values sh24b    SH24B   
label values sh26a    SH26A   
label values sh26b    SH26B   
label values sh28a    SH28A   
label values sh28b    SH28B   
label values sh32     SH32    
label values sh33     SH33    
label values sh33a    SH33A   
label values sh34     SH34    
label values sh35     SH35    
label values sh36     SH36    
label values sh37     SH37    
label values sh38     SH38    
label values ha4      HA4     
label values ha5      HA5     
label values ha6      HA6     
label values ha11     HA11    
label values ha12     HA12    
label values ha12a    HA12A   
label values ha12b    HA12B   
label values ha13     HA13    
label values ha33     HA33    
label values ha35     HA35    
label values ha40     HA40    
label values ha41     HA41    
label values ha50     HA50    
label values ha51     HA51    
label values ha52     HA52    
label values ha54     HA54    
label values ha55     HA55    
label values ha57     HA57    
label values ha58     HA58    
label values ha60     HA60    
label values ha61     HA61    
label values ha63     HA63    
label values ha64     HA64    
label values ha65     HA65    
label values ha66     HA66    
label values ha68     HA68    
label values hc4      HC4     
label values hc5      HC5     
label values hc6      HC6     
label values hc7      HC7     
label values hc8      HC8     
label values hc9      HC9     
label values hc10     HC10    
label values hc11     HC11    
label values hc12     HC12    
label values hc13     HC13    
label values hc15     HC15    
label values hc27     HC27    
label values hc30     HC30    
label values hc31     HC31    
label values hc33     HC33    
label values hc51     HC51    
label values hc52     HC52    
label values hc55     HC55    
label values hc57     HC57    
label values hc58     HC58    
label values hc60     HC60    
label values hc61     HC61    
label values hc68     HC68    
label values hc70     HC70    
label values hc71     HC71    
label values hc72     HC72    
label values hc73     HC73    
label values hml3     HML3    
label values hml4     HML4    
label values hml5     HML5    
label values hml6     HML6    
label values hml7     HML7    
label values hml8     HML8    
label values hml9     HML9    
label values hml10    HML10   
label values hml11    HML11   
label values hml21    HML21   
label values hmla     HMLA    
label values hml12    HML12   
label values hml13    HML13   
label values hml16    HML16   
label values hml17    HML17   
label values hml18    HML18   
label values hml19    HML19   
label values hs100    HS100   
label values hs101    HS101   
label values hs102    HS102   
label values hs103    HS103   
label values hs104    HS104   
label values hs105    HS105   
label values hs106    HS106   
label values hs107    HS107   
label values hs108    HS108   
label values hs109    HS109   
label values hs110    HS110   
label values hs111    HS111   
label values ho101    HO101   
label values ho102    HO102   
label values ho103    HO103   
label values ho104    HO104   
label values ho105    HO105   
label values ho106    HO106   
label values ho107    HO107   
label values ho108    HO108   
