infix using "C:\COUNTRIES\KE7A\KEIR7AFL.dct"

label variable caseid   "Case Identification"
label variable v000     "Country code and phase"
label variable v001     "Cluster number"
label variable v002     "Household number"
label variable v003     "Respondent's line number"
label variable v004     "Ultimate area unit"
label variable v005     "Women's individual sample weight (6 decimals)"
label variable v006     "Month of interview"
label variable v007     "Year of interview"
label variable v008     "Date of interview (CMC)"
label variable v009     "Respondent's month of birth"
label variable v010     "Respondent's year of birth"
label variable v011     "Date of birth (CMC)"
label variable v012     "Respondent's current age"
label variable v013     "Age in 5-year groups"
label variable v014     "Completeness of age information"
label variable v015     "Result of individual interview"
label variable v016     "Day of interview"
label variable v017     "NA - CMC start of calendar"
label variable v018     "NA - Row of month of interview"
label variable v019     "NA - Length of calendar"
label variable v019a    "NA - Number of calendar columns"
label variable v020     "Ever-married sample"
label variable v021     "Primary sampling unit"
label variable v022     "Sample strata for sampling errors"
label variable v023     "Stratification used in sample design"
label variable v024     "Region"
label variable v025     "Type of place of residence"
label variable v026     "NA - De facto place of residence"
label variable v027     "Number of visits"
label variable v028     "Interviewer identification"
label variable v029     "NA - Keyer identification"
label variable v030     "Field supervisor"
label variable v031     "NA - Field editor"
label variable v032     "NA - Office editor"
label variable v034     "NA - Line number of husband"
label variable v040     "Cluster altitude in meters"
label variable v042     "Household selected for hemoglobin"
label variable v044     "NA - Selected for Domestic Violence module"
label variable v101     "Region"
label variable v102     "Type of place of residence"
label variable v103     "NA - Childhood place of residence"
label variable v104     "NA - Years lived in place of residence"
label variable v105     "NA - Type of place of previous residence"
label variable v106     "Highest educational level"
label variable v107     "Highest year of education"
label variable v113     "Source of drinking water"
label variable v115     "Time to get to water source"
label variable v116     "Type of toilet facility"
label variable v119     "Household has: electricity"
label variable v120     "Household has: radio"
label variable v121     "Household has: television"
label variable v122     "Household has: refrigerator"
label variable v123     "Household has: bicycle"
label variable v124     "Household has: motorcycle/scooter"
label variable v125     "Household has: car/truck"
label variable v127     "Main floor material"
label variable v128     "Main wall material"
label variable v129     "Main roof material"
label variable v130     "Religion"
label variable v131     "Ethnicity"
label variable v133     "Education in single years"
label variable v134     "NA - De facto place of residence"
label variable v135     "Usual resident or visitor"
label variable v136     "Number of household members (listed)"
label variable v137     "Number of children 14 and under in household (de jure)"
label variable v138     "Number of eligible women in household (de facto)"
label variable v139     "De jure region of residence"
label variable v140     "De jure type of place of residence"
label variable v141     "NA - De jure place of residence"
label variable v149     "Educational attainment"
label variable v150     "Relationship to household head"
label variable v151     "Sex of household head"
label variable v152     "Age of household head"
label variable v153     "Household has: telephone (land-line)"
label variable awfactt  "All woman factor - total"
label variable awfactu  "All woman factor - urban/rural"
label variable awfactr  "All woman factor - regional"
label variable awfacte  "All woman factor - educational"
label variable awfactw  "All woman factor - wealth index"
label variable v155     "Literacy"
label variable v156     "NA - Ever participated in a literacy program outside of primary"
label variable v157     "NA - Frequency of reading newspaper or magazine"
label variable v158     "NA - Frequency of listening to radio"
label variable v159     "NA - Frequency of watching television"
label variable v160     "Toilet facilities shared with other households"
label variable v161     "NA - Type of cooking fuel"
label variable v166     "NA - Result of salt test for iodine"
label variable v167     "NA - Number of trips in last 12 months"
label variable v168     "NA - Away for more than one month in last 12 months"
label variable v190     "Wealth index"
label variable v191     "Wealth index factor score (5 decimals)"
label variable ml101    "Type of mosquito bed net(s) slept under last night"
label variable bidx_01  "Birth column number"
label variable bidx_02  "Birth column number"
label variable bidx_03  "Birth column number"
label variable bidx_04  "Birth column number"
label variable bidx_05  "Birth column number"
label variable bidx_06  "Birth column number"
label variable bidx_07  "Birth column number"
label variable bidx_08  "Birth column number"
label variable bidx_09  "Birth column number"
label variable bidx_10  "Birth column number"
label variable bidx_11  "Birth column number"
label variable bidx_12  "Birth column number"
label variable bidx_13  "Birth column number"
label variable bidx_14  "Birth column number"
label variable bidx_15  "Birth column number"
label variable bidx_16  "Birth column number"
label variable bidx_17  "Birth column number"
label variable bidx_18  "Birth column number"
label variable bidx_19  "Birth column number"
label variable bidx_20  "Birth column number"
label variable bord_01  "Birth order number"
label variable bord_02  "Birth order number"
label variable bord_03  "Birth order number"
label variable bord_04  "Birth order number"
label variable bord_05  "Birth order number"
label variable bord_06  "Birth order number"
label variable bord_07  "Birth order number"
label variable bord_08  "Birth order number"
label variable bord_09  "Birth order number"
label variable bord_10  "Birth order number"
label variable bord_11  "Birth order number"
label variable bord_12  "Birth order number"
label variable bord_13  "Birth order number"
label variable bord_14  "Birth order number"
label variable bord_15  "Birth order number"
label variable bord_16  "Birth order number"
label variable bord_17  "Birth order number"
label variable bord_18  "Birth order number"
label variable bord_19  "Birth order number"
label variable bord_20  "Birth order number"
label variable b0_01    "Child is twin"
label variable b0_02    "Child is twin"
label variable b0_03    "Child is twin"
label variable b0_04    "Child is twin"
label variable b0_05    "Child is twin"
label variable b0_06    "Child is twin"
label variable b0_07    "Child is twin"
label variable b0_08    "Child is twin"
label variable b0_09    "Child is twin"
label variable b0_10    "Child is twin"
label variable b0_11    "Child is twin"
label variable b0_12    "Child is twin"
label variable b0_13    "Child is twin"
label variable b0_14    "Child is twin"
label variable b0_15    "Child is twin"
label variable b0_16    "Child is twin"
label variable b0_17    "Child is twin"
label variable b0_18    "Child is twin"
label variable b0_19    "Child is twin"
label variable b0_20    "Child is twin"
label variable b1_01    "Month of birth"
label variable b1_02    "Month of birth"
label variable b1_03    "Month of birth"
label variable b1_04    "Month of birth"
label variable b1_05    "Month of birth"
label variable b1_06    "Month of birth"
label variable b1_07    "Month of birth"
label variable b1_08    "Month of birth"
label variable b1_09    "Month of birth"
label variable b1_10    "Month of birth"
label variable b1_11    "Month of birth"
label variable b1_12    "Month of birth"
label variable b1_13    "Month of birth"
label variable b1_14    "Month of birth"
label variable b1_15    "Month of birth"
label variable b1_16    "Month of birth"
label variable b1_17    "Month of birth"
label variable b1_18    "Month of birth"
label variable b1_19    "Month of birth"
label variable b1_20    "Month of birth"
label variable b2_01    "Year of birth"
label variable b2_02    "Year of birth"
label variable b2_03    "Year of birth"
label variable b2_04    "Year of birth"
label variable b2_05    "Year of birth"
label variable b2_06    "Year of birth"
label variable b2_07    "Year of birth"
label variable b2_08    "Year of birth"
label variable b2_09    "Year of birth"
label variable b2_10    "Year of birth"
label variable b2_11    "Year of birth"
label variable b2_12    "Year of birth"
label variable b2_13    "Year of birth"
label variable b2_14    "Year of birth"
label variable b2_15    "Year of birth"
label variable b2_16    "Year of birth"
label variable b2_17    "Year of birth"
label variable b2_18    "Year of birth"
label variable b2_19    "Year of birth"
label variable b2_20    "Year of birth"
label variable b3_01    "Date of birth (CMC)"
label variable b3_02    "Date of birth (CMC)"
label variable b3_03    "Date of birth (CMC)"
label variable b3_04    "Date of birth (CMC)"
label variable b3_05    "Date of birth (CMC)"
label variable b3_06    "Date of birth (CMC)"
label variable b3_07    "Date of birth (CMC)"
label variable b3_08    "Date of birth (CMC)"
label variable b3_09    "Date of birth (CMC)"
label variable b3_10    "Date of birth (CMC)"
label variable b3_11    "Date of birth (CMC)"
label variable b3_12    "Date of birth (CMC)"
label variable b3_13    "Date of birth (CMC)"
label variable b3_14    "Date of birth (CMC)"
label variable b3_15    "Date of birth (CMC)"
label variable b3_16    "Date of birth (CMC)"
label variable b3_17    "Date of birth (CMC)"
label variable b3_18    "Date of birth (CMC)"
label variable b3_19    "Date of birth (CMC)"
label variable b3_20    "Date of birth (CMC)"
label variable b4_01    "Sex of child"
label variable b4_02    "Sex of child"
label variable b4_03    "Sex of child"
label variable b4_04    "Sex of child"
label variable b4_05    "Sex of child"
label variable b4_06    "Sex of child"
label variable b4_07    "Sex of child"
label variable b4_08    "Sex of child"
label variable b4_09    "Sex of child"
label variable b4_10    "Sex of child"
label variable b4_11    "Sex of child"
label variable b4_12    "Sex of child"
label variable b4_13    "Sex of child"
label variable b4_14    "Sex of child"
label variable b4_15    "Sex of child"
label variable b4_16    "Sex of child"
label variable b4_17    "Sex of child"
label variable b4_18    "Sex of child"
label variable b4_19    "Sex of child"
label variable b4_20    "Sex of child"
label variable b5_01    "Child is alive"
label variable b5_02    "Child is alive"
label variable b5_03    "Child is alive"
label variable b5_04    "Child is alive"
label variable b5_05    "Child is alive"
label variable b5_06    "Child is alive"
label variable b5_07    "Child is alive"
label variable b5_08    "Child is alive"
label variable b5_09    "Child is alive"
label variable b5_10    "Child is alive"
label variable b5_11    "Child is alive"
label variable b5_12    "Child is alive"
label variable b5_13    "Child is alive"
label variable b5_14    "Child is alive"
label variable b5_15    "Child is alive"
label variable b5_16    "Child is alive"
label variable b5_17    "Child is alive"
label variable b5_18    "Child is alive"
label variable b5_19    "Child is alive"
label variable b5_20    "Child is alive"
label variable b6_01    "NA - Age at death"
label variable b6_02    "NA - Age at death"
label variable b6_03    "NA - Age at death"
label variable b6_04    "NA - Age at death"
label variable b6_05    "NA - Age at death"
label variable b6_06    "NA - Age at death"
label variable b6_07    "NA - Age at death"
label variable b6_08    "NA - Age at death"
label variable b6_09    "NA - Age at death"
label variable b6_10    "NA - Age at death"
label variable b6_11    "NA - Age at death"
label variable b6_12    "NA - Age at death"
label variable b6_13    "NA - Age at death"
label variable b6_14    "NA - Age at death"
label variable b6_15    "NA - Age at death"
label variable b6_16    "NA - Age at death"
label variable b6_17    "NA - Age at death"
label variable b6_18    "NA - Age at death"
label variable b6_19    "NA - Age at death"
label variable b6_20    "NA - Age at death"
label variable b7_01    "NA - Age at death (months, imputed)"
label variable b7_02    "NA - Age at death (months, imputed)"
label variable b7_03    "NA - Age at death (months, imputed)"
label variable b7_04    "NA - Age at death (months, imputed)"
label variable b7_05    "NA - Age at death (months, imputed)"
label variable b7_06    "NA - Age at death (months, imputed)"
label variable b7_07    "NA - Age at death (months, imputed)"
label variable b7_08    "NA - Age at death (months, imputed)"
label variable b7_09    "NA - Age at death (months, imputed)"
label variable b7_10    "NA - Age at death (months, imputed)"
label variable b7_11    "NA - Age at death (months, imputed)"
label variable b7_12    "NA - Age at death (months, imputed)"
label variable b7_13    "NA - Age at death (months, imputed)"
label variable b7_14    "NA - Age at death (months, imputed)"
label variable b7_15    "NA - Age at death (months, imputed)"
label variable b7_16    "NA - Age at death (months, imputed)"
label variable b7_17    "NA - Age at death (months, imputed)"
label variable b7_18    "NA - Age at death (months, imputed)"
label variable b7_19    "NA - Age at death (months, imputed)"
label variable b7_20    "NA - Age at death (months, imputed)"
label variable b8_01    "Current age of child"
label variable b8_02    "Current age of child"
label variable b8_03    "Current age of child"
label variable b8_04    "Current age of child"
label variable b8_05    "Current age of child"
label variable b8_06    "Current age of child"
label variable b8_07    "Current age of child"
label variable b8_08    "Current age of child"
label variable b8_09    "Current age of child"
label variable b8_10    "Current age of child"
label variable b8_11    "Current age of child"
label variable b8_12    "Current age of child"
label variable b8_13    "Current age of child"
label variable b8_14    "Current age of child"
label variable b8_15    "Current age of child"
label variable b8_16    "Current age of child"
label variable b8_17    "Current age of child"
label variable b8_18    "Current age of child"
label variable b8_19    "Current age of child"
label variable b8_20    "Current age of child"
label variable b9_01    "Child lives with whom"
label variable b9_02    "Child lives with whom"
label variable b9_03    "Child lives with whom"
label variable b9_04    "Child lives with whom"
label variable b9_05    "Child lives with whom"
label variable b9_06    "Child lives with whom"
label variable b9_07    "Child lives with whom"
label variable b9_08    "Child lives with whom"
label variable b9_09    "Child lives with whom"
label variable b9_10    "Child lives with whom"
label variable b9_11    "Child lives with whom"
label variable b9_12    "Child lives with whom"
label variable b9_13    "Child lives with whom"
label variable b9_14    "Child lives with whom"
label variable b9_15    "Child lives with whom"
label variable b9_16    "Child lives with whom"
label variable b9_17    "Child lives with whom"
label variable b9_18    "Child lives with whom"
label variable b9_19    "Child lives with whom"
label variable b9_20    "Child lives with whom"
label variable b10_01   "Completeness of information"
label variable b10_02   "Completeness of information"
label variable b10_03   "Completeness of information"
label variable b10_04   "Completeness of information"
label variable b10_05   "Completeness of information"
label variable b10_06   "Completeness of information"
label variable b10_07   "Completeness of information"
label variable b10_08   "Completeness of information"
label variable b10_09   "Completeness of information"
label variable b10_10   "Completeness of information"
label variable b10_11   "Completeness of information"
label variable b10_12   "Completeness of information"
label variable b10_13   "Completeness of information"
label variable b10_14   "Completeness of information"
label variable b10_15   "Completeness of information"
label variable b10_16   "Completeness of information"
label variable b10_17   "Completeness of information"
label variable b10_18   "Completeness of information"
label variable b10_19   "Completeness of information"
label variable b10_20   "Completeness of information"
label variable b11_01   "Preceding birth interval (months)"
label variable b11_02   "Preceding birth interval (months)"
label variable b11_03   "Preceding birth interval (months)"
label variable b11_04   "Preceding birth interval (months)"
label variable b11_05   "Preceding birth interval (months)"
label variable b11_06   "Preceding birth interval (months)"
label variable b11_07   "Preceding birth interval (months)"
label variable b11_08   "Preceding birth interval (months)"
label variable b11_09   "Preceding birth interval (months)"
label variable b11_10   "Preceding birth interval (months)"
label variable b11_11   "Preceding birth interval (months)"
label variable b11_12   "Preceding birth interval (months)"
label variable b11_13   "Preceding birth interval (months)"
label variable b11_14   "Preceding birth interval (months)"
label variable b11_15   "Preceding birth interval (months)"
label variable b11_16   "Preceding birth interval (months)"
label variable b11_17   "Preceding birth interval (months)"
label variable b11_18   "Preceding birth interval (months)"
label variable b11_19   "Preceding birth interval (months)"
label variable b11_20   "Preceding birth interval (months)"
label variable b12_01   "Succeeding birth interval (months)"
label variable b12_02   "Succeeding birth interval (months)"
label variable b12_03   "Succeeding birth interval (months)"
label variable b12_04   "Succeeding birth interval (months)"
label variable b12_05   "Succeeding birth interval (months)"
label variable b12_06   "Succeeding birth interval (months)"
label variable b12_07   "Succeeding birth interval (months)"
label variable b12_08   "Succeeding birth interval (months)"
label variable b12_09   "Succeeding birth interval (months)"
label variable b12_10   "Succeeding birth interval (months)"
label variable b12_11   "Succeeding birth interval (months)"
label variable b12_12   "Succeeding birth interval (months)"
label variable b12_13   "Succeeding birth interval (months)"
label variable b12_14   "Succeeding birth interval (months)"
label variable b12_15   "Succeeding birth interval (months)"
label variable b12_16   "Succeeding birth interval (months)"
label variable b12_17   "Succeeding birth interval (months)"
label variable b12_18   "Succeeding birth interval (months)"
label variable b12_19   "Succeeding birth interval (months)"
label variable b12_20   "Succeeding birth interval (months)"
label variable b13_01   "NA - Flag for age at death"
label variable b13_02   "NA - Flag for age at death"
label variable b13_03   "NA - Flag for age at death"
label variable b13_04   "NA - Flag for age at death"
label variable b13_05   "NA - Flag for age at death"
label variable b13_06   "NA - Flag for age at death"
label variable b13_07   "NA - Flag for age at death"
label variable b13_08   "NA - Flag for age at death"
label variable b13_09   "NA - Flag for age at death"
label variable b13_10   "NA - Flag for age at death"
label variable b13_11   "NA - Flag for age at death"
label variable b13_12   "NA - Flag for age at death"
label variable b13_13   "NA - Flag for age at death"
label variable b13_14   "NA - Flag for age at death"
label variable b13_15   "NA - Flag for age at death"
label variable b13_16   "NA - Flag for age at death"
label variable b13_17   "NA - Flag for age at death"
label variable b13_18   "NA - Flag for age at death"
label variable b13_19   "NA - Flag for age at death"
label variable b13_20   "NA - Flag for age at death"
label variable b15_01   "Live birth between births"
label variable b15_02   "Live birth between births"
label variable b15_03   "Live birth between births"
label variable b15_04   "Live birth between births"
label variable b15_05   "Live birth between births"
label variable b15_06   "Live birth between births"
label variable b15_07   "Live birth between births"
label variable b15_08   "Live birth between births"
label variable b15_09   "Live birth between births"
label variable b15_10   "Live birth between births"
label variable b15_11   "Live birth between births"
label variable b15_12   "Live birth between births"
label variable b15_13   "Live birth between births"
label variable b15_14   "Live birth between births"
label variable b15_15   "Live birth between births"
label variable b15_16   "Live birth between births"
label variable b15_17   "Live birth between births"
label variable b15_18   "Live birth between births"
label variable b15_19   "Live birth between births"
label variable b15_20   "Live birth between births"
label variable b16_01   "Child's line number in household"
label variable b16_02   "Child's line number in household"
label variable b16_03   "Child's line number in household"
label variable b16_04   "Child's line number in household"
label variable b16_05   "Child's line number in household"
label variable b16_06   "Child's line number in household"
label variable b16_07   "Child's line number in household"
label variable b16_08   "Child's line number in household"
label variable b16_09   "Child's line number in household"
label variable b16_10   "Child's line number in household"
label variable b16_11   "Child's line number in household"
label variable b16_12   "Child's line number in household"
label variable b16_13   "Child's line number in household"
label variable b16_14   "Child's line number in household"
label variable b16_15   "Child's line number in household"
label variable b16_16   "Child's line number in household"
label variable b16_17   "Child's line number in household"
label variable b16_18   "Child's line number in household"
label variable b16_19   "Child's line number in household"
label variable b16_20   "Child's line number in household"
label variable s216d_01 "Day of birth"
label variable s216d_02 "Day of birth"
label variable s216d_03 "Day of birth"
label variable s216d_04 "Day of birth"
label variable s216d_05 "Day of birth"
label variable s216d_06 "Day of birth"
label variable s216d_07 "Day of birth"
label variable s216d_08 "Day of birth"
label variable s216d_09 "Day of birth"
label variable s216d_10 "Day of birth"
label variable s216d_11 "Day of birth"
label variable s216d_12 "Day of birth"
label variable s216d_13 "Day of birth"
label variable s216d_14 "Day of birth"
label variable s216d_15 "Day of birth"
label variable s216d_16 "Day of birth"
label variable s216d_17 "Day of birth"
label variable s216d_18 "Day of birth"
label variable s216d_19 "Day of birth"
label variable s216d_20 "Day of birth"
label variable v201     "Total children ever born"
label variable v202     "Sons at home"
label variable v203     "Daughters at home"
label variable v204     "Sons elsewhere"
label variable v205     "Daughters elsewhere"
label variable v206     "Sons who have died"
label variable v207     "Daughters who have died"
label variable v208     "Births in last five years"
label variable v209     "Births in past year"
label variable v210     "Births in month of interview"
label variable v211     "NA - Date of first birth (CMC)"
label variable v212     "NA - Age of respondent at 1st birth"
label variable v213     "Currently pregnant"
label variable v214     "Duration of current pregnancy"
label variable v215     "NA - Time since last menstrual period"
label variable v216     "NA - Menstruated in last six weeks"
label variable v217     "NA - Knowledge of ovulatory cycle"
label variable v218     "Number of living children"
label variable v219     "Living children + current pregnancy"
label variable v220     "Living children + current pregnancy (grouped)"
label variable v221     "NA - Marriage to first birth interval (months)"
label variable v222     "Last birth to interview (months)"
label variable v223     "Completeness of current pregnancy information"
label variable v224     "Entries in birth history"
label variable v225     "NA - Current pregnancy wanted"
label variable v226     "NA - Time since last period (comp) (months)"
label variable v227     "NA - Flag for last period"
label variable v228     "NA - Ever had a terminated pregnancy"
label variable v229     "NA - Month pregnancy ended"
label variable v230     "NA - Year pregnancy ended"
label variable v231     "NA - CMC pregnancy ended"
label variable v232     "NA - Completeness of last termination information"
label variable v233     "NA - Months when pregnancy ended"
label variable v234     "NA - Other such pregnancies"
label variable v235     "NA - Index last child prior to maternity-health (calendar)"
label variable v237     "NA - Birth between last and interview"
label variable v238     "Births in last three years"
label variable v239     "NA - Pregnancies terminated before calendar beginning"
label variable v240     "NA - Month of last termination prior to calendar"
label variable v241     "NA - Year of last termination prior to calendar"
label variable v242     "NA - CMC termination ended prior to calendar"
label variable v243     "NA - Completeness of last termination date prior to calendar"
label variable midx_1   "Index to Birth History"
label variable midx_2   "Index to Birth History"
label variable midx_3   "Index to Birth History"
label variable midx_4   "Index to Birth History"
label variable midx_5   "Index to Birth History"
label variable midx_6   "Index to Birth History"
label variable m2a_1    "Prenatal: doctor"
label variable m2a_2    "Prenatal: doctor"
label variable m2a_3    "Prenatal: doctor"
label variable m2a_4    "Prenatal: doctor"
label variable m2a_5    "Prenatal: doctor"
label variable m2a_6    "Prenatal: doctor"
label variable m2b_1    "Prenatal: nurse/midwife"
label variable m2b_2    "Prenatal: nurse/midwife"
label variable m2b_3    "Prenatal: nurse/midwife"
label variable m2b_4    "Prenatal: nurse/midwife"
label variable m2b_5    "Prenatal: nurse/midwife"
label variable m2b_6    "Prenatal: nurse/midwife"
label variable m2c_1    "NA - Prenatal: CS health professional"
label variable m2c_2    "NA - Prenatal: CS health professional"
label variable m2c_3    "NA - Prenatal: CS health professional"
label variable m2c_4    "NA - Prenatal: CS health professional"
label variable m2c_5    "NA - Prenatal: CS health professional"
label variable m2c_6    "NA - Prenatal: CS health professional"
label variable m2d_1    "NA - Prenatal: CS health professional"
label variable m2d_2    "NA - Prenatal: CS health professional"
label variable m2d_3    "NA - Prenatal: CS health professional"
label variable m2d_4    "NA - Prenatal: CS health professional"
label variable m2d_5    "NA - Prenatal: CS health professional"
label variable m2d_6    "NA - Prenatal: CS health professional"
label variable m2e_1    "NA - Prenatal: CS health professional"
label variable m2e_2    "NA - Prenatal: CS health professional"
label variable m2e_3    "NA - Prenatal: CS health professional"
label variable m2e_4    "NA - Prenatal: CS health professional"
label variable m2e_5    "NA - Prenatal: CS health professional"
label variable m2e_6    "NA - Prenatal: CS health professional"
label variable m2f_1    "NA - Prenatal: CS health professional"
label variable m2f_2    "NA - Prenatal: CS health professional"
label variable m2f_3    "NA - Prenatal: CS health professional"
label variable m2f_4    "NA - Prenatal: CS health professional"
label variable m2f_5    "NA - Prenatal: CS health professional"
label variable m2f_6    "NA - Prenatal: CS health professional"
label variable m2g_1    "Prenatal: traditional birth attendant"
label variable m2g_2    "Prenatal: traditional birth attendant"
label variable m2g_3    "Prenatal: traditional birth attendant"
label variable m2g_4    "Prenatal: traditional birth attendant"
label variable m2g_5    "Prenatal: traditional birth attendant"
label variable m2g_6    "Prenatal: traditional birth attendant"
label variable m2h_1    "Prenatal: community health worker"
label variable m2h_2    "Prenatal: community health worker"
label variable m2h_3    "Prenatal: community health worker"
label variable m2h_4    "Prenatal: community health worker"
label variable m2h_5    "Prenatal: community health worker"
label variable m2h_6    "Prenatal: community health worker"
label variable m2i_1    "NA - Prenatal: CS other person"
label variable m2i_2    "NA - Prenatal: CS other person"
label variable m2i_3    "NA - Prenatal: CS other person"
label variable m2i_4    "NA - Prenatal: CS other person"
label variable m2i_5    "NA - Prenatal: CS other person"
label variable m2i_6    "NA - Prenatal: CS other person"
label variable m2j_1    "NA - Prenatal: CS other person"
label variable m2j_2    "NA - Prenatal: CS other person"
label variable m2j_3    "NA - Prenatal: CS other person"
label variable m2j_4    "NA - Prenatal: CS other person"
label variable m2j_5    "NA - Prenatal: CS other person"
label variable m2j_6    "NA - Prenatal: CS other person"
label variable m2k_1    "Prenatal: other"
label variable m2k_2    "Prenatal: other"
label variable m2k_3    "Prenatal: other"
label variable m2k_4    "Prenatal: other"
label variable m2k_5    "Prenatal: other"
label variable m2k_6    "Prenatal: other"
label variable m2l_1    "NA - Prenatal: CS other"
label variable m2l_2    "NA - Prenatal: CS other"
label variable m2l_3    "NA - Prenatal: CS other"
label variable m2l_4    "NA - Prenatal: CS other"
label variable m2l_5    "NA - Prenatal: CS other"
label variable m2l_6    "NA - Prenatal: CS other"
label variable m2m_1    "NA - Prenatal: CS other"
label variable m2m_2    "NA - Prenatal: CS other"
label variable m2m_3    "NA - Prenatal: CS other"
label variable m2m_4    "NA - Prenatal: CS other"
label variable m2m_5    "NA - Prenatal: CS other"
label variable m2m_6    "NA - Prenatal: CS other"
label variable m2n_1    "Prenatal: no one"
label variable m2n_2    "Prenatal: no one"
label variable m2n_3    "Prenatal: no one"
label variable m2n_4    "Prenatal: no one"
label variable m2n_5    "Prenatal: no one"
label variable m2n_6    "Prenatal: no one"
label variable m14_1    "Number of antenatal visits during pregnancy"
label variable m14_2    "Number of antenatal visits during pregnancy"
label variable m14_3    "Number of antenatal visits during pregnancy"
label variable m14_4    "Number of antenatal visits during pregnancy"
label variable m14_5    "Number of antenatal visits during pregnancy"
label variable m14_6    "Number of antenatal visits during pregnancy"
label variable m49a_1   "During pregnancy took: SP/fansidar for malaria"
label variable m49a_2   "During pregnancy took: SP/fansidar for malaria"
label variable m49a_3   "During pregnancy took: SP/fansidar for malaria"
label variable m49a_4   "During pregnancy took: SP/fansidar for malaria"
label variable m49a_5   "During pregnancy took: SP/fansidar for malaria"
label variable m49a_6   "During pregnancy took: SP/fansidar for malaria"
label variable hidx_1   "Index to birth history"
label variable hidx_2   "Index to birth history"
label variable hidx_3   "Index to birth history"
label variable hidx_4   "Index to birth history"
label variable hidx_5   "Index to birth history"
label variable hidx_6   "Index to birth history"
label variable h22_1    "Had fever in last two weeks"
label variable h22_2    "Had fever in last two weeks"
label variable h22_3    "Had fever in last two weeks"
label variable h22_4    "Had fever in last two weeks"
label variable h22_5    "Had fever in last two weeks"
label variable h22_6    "Had fever in last two weeks"
label variable h31_1    "NA - Had cough in last two weeks"
label variable h31_2    "NA - Had cough in last two weeks"
label variable h31_3    "NA - Had cough in last two weeks"
label variable h31_4    "NA - Had cough in last two weeks"
label variable h31_5    "NA - Had cough in last two weeks"
label variable h31_6    "NA - Had cough in last two weeks"
label variable h31b_1   "NA - Short, rapid breaths"
label variable h31b_2   "NA - Short, rapid breaths"
label variable h31b_3   "NA - Short, rapid breaths"
label variable h31b_4   "NA - Short, rapid breaths"
label variable h31b_5   "NA - Short, rapid breaths"
label variable h31b_6   "NA - Short, rapid breaths"
label variable h31c_1   "NA - Problem in the chest or blocked or running nose"
label variable h31c_2   "NA - Problem in the chest or blocked or running nose"
label variable h31c_3   "NA - Problem in the chest or blocked or running nose"
label variable h31c_4   "NA - Problem in the chest or blocked or running nose"
label variable h31c_5   "NA - Problem in the chest or blocked or running nose"
label variable h31c_6   "NA - Problem in the chest or blocked or running nose"
label variable h31d_1   "NA - Had fever/cough in last 2 weeks: amount offered to drink"
label variable h31d_2   "NA - Had fever/cough in last 2 weeks: amount offered to drink"
label variable h31d_3   "NA - Had fever/cough in last 2 weeks: amount offered to drink"
label variable h31d_4   "NA - Had fever/cough in last 2 weeks: amount offered to drink"
label variable h31d_5   "NA - Had fever/cough in last 2 weeks: amount offered to drink"
label variable h31d_6   "NA - Had fever/cough in last 2 weeks: amount offered to drink"
label variable h31e_1   "NA - Had fever/cough in last 2 weeks: amount offered to eat"
label variable h31e_2   "NA - Had fever/cough in last 2 weeks: amount offered to eat"
label variable h31e_3   "NA - Had fever/cough in last 2 weeks: amount offered to eat"
label variable h31e_4   "NA - Had fever/cough in last 2 weeks: amount offered to eat"
label variable h31e_5   "NA - Had fever/cough in last 2 weeks: amount offered to eat"
label variable h31e_6   "NA - Had fever/cough in last 2 weeks: amount offered to eat"
label variable h32a_1   "Fever/cough: government hospital"
label variable h32a_2   "Fever/cough: government hospital"
label variable h32a_3   "Fever/cough: government hospital"
label variable h32a_4   "Fever/cough: government hospital"
label variable h32a_5   "Fever/cough: government hospital"
label variable h32a_6   "Fever/cough: government hospital"
label variable h32b_1   "Fever/cough: government health center"
label variable h32b_2   "Fever/cough: government health center"
label variable h32b_3   "Fever/cough: government health center"
label variable h32b_4   "Fever/cough: government health center"
label variable h32b_5   "Fever/cough: government health center"
label variable h32b_6   "Fever/cough: government health center"
label variable h32c_1   "Fever/cough: government dispensary"
label variable h32c_2   "Fever/cough: government dispensary"
label variable h32c_3   "Fever/cough: government dispensary"
label variable h32c_4   "Fever/cough: government dispensary"
label variable h32c_5   "Fever/cough: government dispensary"
label variable h32c_6   "Fever/cough: government dispensary"
label variable h32d_1   "Fever/cough: other public"
label variable h32d_2   "Fever/cough: other public"
label variable h32d_3   "Fever/cough: other public"
label variable h32d_4   "Fever/cough: other public"
label variable h32d_5   "Fever/cough: other public"
label variable h32d_6   "Fever/cough: other public"
label variable h32e_1   "NA - Fever/cough: CS public sector"
label variable h32e_2   "NA - Fever/cough: CS public sector"
label variable h32e_3   "NA - Fever/cough: CS public sector"
label variable h32e_4   "NA - Fever/cough: CS public sector"
label variable h32e_5   "NA - Fever/cough: CS public sector"
label variable h32e_6   "NA - Fever/cough: CS public sector"
label variable h32f_1   "NA - Fever/cough: CS public sector"
label variable h32f_2   "NA - Fever/cough: CS public sector"
label variable h32f_3   "NA - Fever/cough: CS public sector"
label variable h32f_4   "NA - Fever/cough: CS public sector"
label variable h32f_5   "NA - Fever/cough: CS public sector"
label variable h32f_6   "NA - Fever/cough: CS public sector"
label variable h32g_1   "NA - Fever/cough: CS public sector"
label variable h32g_2   "NA - Fever/cough: CS public sector"
label variable h32g_3   "NA - Fever/cough: CS public sector"
label variable h32g_4   "NA - Fever/cough: CS public sector"
label variable h32g_5   "NA - Fever/cough: CS public sector"
label variable h32g_6   "NA - Fever/cough: CS public sector"
label variable h32h_1   "NA - Fever/cough: CS public sector"
label variable h32h_2   "NA - Fever/cough: CS public sector"
label variable h32h_3   "NA - Fever/cough: CS public sector"
label variable h32h_4   "NA - Fever/cough: CS public sector"
label variable h32h_5   "NA - Fever/cough: CS public sector"
label variable h32h_6   "NA - Fever/cough: CS public sector"
label variable h32i_1   "NA - Fever/cough: CS public sector"
label variable h32i_2   "NA - Fever/cough: CS public sector"
label variable h32i_3   "NA - Fever/cough: CS public sector"
label variable h32i_4   "NA - Fever/cough: CS public sector"
label variable h32i_5   "NA - Fever/cough: CS public sector"
label variable h32i_6   "NA - Fever/cough: CS public sector"
label variable h32j_1   "Fever/cough: mission hospital / clinic"
label variable h32j_2   "Fever/cough: mission hospital / clinic"
label variable h32j_3   "Fever/cough: mission hospital / clinic"
label variable h32j_4   "Fever/cough: mission hospital / clinic"
label variable h32j_5   "Fever/cough: mission hospital / clinic"
label variable h32j_6   "Fever/cough: mission hospital / clinic"
label variable h32k_1   "Fever/cough: pharmacy"
label variable h32k_2   "Fever/cough: pharmacy"
label variable h32k_3   "Fever/cough: pharmacy"
label variable h32k_4   "Fever/cough: pharmacy"
label variable h32k_5   "Fever/cough: pharmacy"
label variable h32k_6   "Fever/cough: pharmacy"
label variable h32l_1   "Fever/cough: private hospital / clinic"
label variable h32l_2   "Fever/cough: private hospital / clinic"
label variable h32l_3   "Fever/cough: private hospital / clinic"
label variable h32l_4   "Fever/cough: private hospital / clinic"
label variable h32l_5   "Fever/cough: private hospital / clinic"
label variable h32l_6   "Fever/cough: private hospital / clinic"
label variable h32m_1   "Fever/cough: other private"
label variable h32m_2   "Fever/cough: other private"
label variable h32m_3   "Fever/cough: other private"
label variable h32m_4   "Fever/cough: other private"
label variable h32m_5   "Fever/cough: other private"
label variable h32m_6   "Fever/cough: other private"
label variable h32n_1   "Fever/cough: mobile clinic"
label variable h32n_2   "Fever/cough: mobile clinic"
label variable h32n_3   "Fever/cough: mobile clinic"
label variable h32n_4   "Fever/cough: mobile clinic"
label variable h32n_5   "Fever/cough: mobile clinic"
label variable h32n_6   "Fever/cough: mobile clinic"
label variable h32o_1   "Fever/cough: community health worker"
label variable h32o_2   "Fever/cough: community health worker"
label variable h32o_3   "Fever/cough: community health worker"
label variable h32o_4   "Fever/cough: community health worker"
label variable h32o_5   "Fever/cough: community health worker"
label variable h32o_6   "Fever/cough: community health worker"
label variable h32p_1   "NA - Fever/cough: CS private medical"
label variable h32p_2   "NA - Fever/cough: CS private medical"
label variable h32p_3   "NA - Fever/cough: CS private medical"
label variable h32p_4   "NA - Fever/cough: CS private medical"
label variable h32p_5   "NA - Fever/cough: CS private medical"
label variable h32p_6   "NA - Fever/cough: CS private medical"
label variable h32q_1   "NA - Fever/cough: CS private medical"
label variable h32q_2   "NA - Fever/cough: CS private medical"
label variable h32q_3   "NA - Fever/cough: CS private medical"
label variable h32q_4   "NA - Fever/cough: CS private medical"
label variable h32q_5   "NA - Fever/cough: CS private medical"
label variable h32q_6   "NA - Fever/cough: CS private medical"
label variable h32r_1   "NA - Fever/cough: CS private medical"
label variable h32r_2   "NA - Fever/cough: CS private medical"
label variable h32r_3   "NA - Fever/cough: CS private medical"
label variable h32r_4   "NA - Fever/cough: CS private medical"
label variable h32r_5   "NA - Fever/cough: CS private medical"
label variable h32r_6   "NA - Fever/cough: CS private medical"
label variable h32s_1   "Fever/cough: shop"
label variable h32s_2   "Fever/cough: shop"
label variable h32s_3   "Fever/cough: shop"
label variable h32s_4   "Fever/cough: shop"
label variable h32s_5   "Fever/cough: shop"
label variable h32s_6   "Fever/cough: shop"
label variable h32t_1   "Fever/cough: traditional healer"
label variable h32t_2   "Fever/cough: traditional healer"
label variable h32t_3   "Fever/cough: traditional healer"
label variable h32t_4   "Fever/cough: traditional healer"
label variable h32t_5   "Fever/cough: traditional healer"
label variable h32t_6   "Fever/cough: traditional healer"
label variable h32u_1   "Fever/cough: relative/friend"
label variable h32u_2   "Fever/cough: relative/friend"
label variable h32u_3   "Fever/cough: relative/friend"
label variable h32u_4   "Fever/cough: relative/friend"
label variable h32u_5   "Fever/cough: relative/friend"
label variable h32u_6   "Fever/cough: relative/friend"
label variable h32v_1   "NA - Fever/cough: CS other sector"
label variable h32v_2   "NA - Fever/cough: CS other sector"
label variable h32v_3   "NA - Fever/cough: CS other sector"
label variable h32v_4   "NA - Fever/cough: CS other sector"
label variable h32v_5   "NA - Fever/cough: CS other sector"
label variable h32v_6   "NA - Fever/cough: CS other sector"
label variable h32w_1   "NA - Fever/cough: CS other sector"
label variable h32w_2   "NA - Fever/cough: CS other sector"
label variable h32w_3   "NA - Fever/cough: CS other sector"
label variable h32w_4   "NA - Fever/cough: CS other sector"
label variable h32w_5   "NA - Fever/cough: CS other sector"
label variable h32w_6   "NA - Fever/cough: CS other sector"
label variable h32x_1   "Fever/cough: other"
label variable h32x_2   "Fever/cough: other"
label variable h32x_3   "Fever/cough: other"
label variable h32x_4   "Fever/cough: other"
label variable h32x_5   "Fever/cough: other"
label variable h32x_6   "Fever/cough: other"
label variable h32y_1   "Fever/cough: no treatment"
label variable h32y_2   "Fever/cough: no treatment"
label variable h32y_3   "Fever/cough: no treatment"
label variable h32y_4   "Fever/cough: no treatment"
label variable h32y_5   "Fever/cough: no treatment"
label variable h32y_6   "Fever/cough: no treatment"
label variable h32z_1   "Fever/cough: medical treatment"
label variable h32z_2   "Fever/cough: medical treatment"
label variable h32z_3   "Fever/cough: medical treatment"
label variable h32z_4   "Fever/cough: medical treatment"
label variable h32z_5   "Fever/cough: medical treatment"
label variable h32z_6   "Fever/cough: medical treatment"
label variable h37a_1   "NA - SP/Fansidar taken for fever/cough"
label variable h37a_2   "NA - SP/Fansidar taken for fever/cough"
label variable h37a_3   "NA - SP/Fansidar taken for fever/cough"
label variable h37a_4   "NA - SP/Fansidar taken for fever/cough"
label variable h37a_5   "NA - SP/Fansidar taken for fever/cough"
label variable h37a_6   "NA - SP/Fansidar taken for fever/cough"
label variable h37b_1   "NA - Chloroquine taken for fever/cough"
label variable h37b_2   "NA - Chloroquine taken for fever/cough"
label variable h37b_3   "NA - Chloroquine taken for fever/cough"
label variable h37b_4   "NA - Chloroquine taken for fever/cough"
label variable h37b_5   "NA - Chloroquine taken for fever/cough"
label variable h37b_6   "NA - Chloroquine taken for fever/cough"
label variable h37c_1   "NA - Amodiaquine taken for fever/cough"
label variable h37c_2   "NA - Amodiaquine taken for fever/cough"
label variable h37c_3   "NA - Amodiaquine taken for fever/cough"
label variable h37c_4   "NA - Amodiaquine taken for fever/cough"
label variable h37c_5   "NA - Amodiaquine taken for fever/cough"
label variable h37c_6   "NA - Amodiaquine taken for fever/cough"
label variable h37d_1   "NA - Quinine taken for fever/cough"
label variable h37d_2   "NA - Quinine taken for fever/cough"
label variable h37d_3   "NA - Quinine taken for fever/cough"
label variable h37d_4   "NA - Quinine taken for fever/cough"
label variable h37d_5   "NA - Quinine taken for fever/cough"
label variable h37d_6   "NA - Quinine taken for fever/cough"
label variable h37e_1   "NA - Combination with artemisinin taken for fever/cough"
label variable h37e_2   "NA - Combination with artemisinin taken for fever/cough"
label variable h37e_3   "NA - Combination with artemisinin taken for fever/cough"
label variable h37e_4   "NA - Combination with artemisinin taken for fever/cough"
label variable h37e_5   "NA - Combination with artemisinin taken for fever/cough"
label variable h37e_6   "NA - Combination with artemisinin taken for fever/cough"
label variable h37f_1   "NA - CS antimalarial taken for fever/cough"
label variable h37f_2   "NA - CS antimalarial taken for fever/cough"
label variable h37f_3   "NA - CS antimalarial taken for fever/cough"
label variable h37f_4   "NA - CS antimalarial taken for fever/cough"
label variable h37f_5   "NA - CS antimalarial taken for fever/cough"
label variable h37f_6   "NA - CS antimalarial taken for fever/cough"
label variable h37g_1   "NA - CS antimalarial taken for fever/cough"
label variable h37g_2   "NA - CS antimalarial taken for fever/cough"
label variable h37g_3   "NA - CS antimalarial taken for fever/cough"
label variable h37g_4   "NA - CS antimalarial taken for fever/cough"
label variable h37g_5   "NA - CS antimalarial taken for fever/cough"
label variable h37g_6   "NA - CS antimalarial taken for fever/cough"
label variable h37h_1   "NA - Other antimalarial taken for fever/cough"
label variable h37h_2   "NA - Other antimalarial taken for fever/cough"
label variable h37h_3   "NA - Other antimalarial taken for fever/cough"
label variable h37h_4   "NA - Other antimalarial taken for fever/cough"
label variable h37h_5   "NA - Other antimalarial taken for fever/cough"
label variable h37h_6   "NA - Other antimalarial taken for fever/cough"
label variable h37i_1   "NA - Antibiotic pill/syrup taken for fever/cough"
label variable h37i_2   "NA - Antibiotic pill/syrup taken for fever/cough"
label variable h37i_3   "NA - Antibiotic pill/syrup taken for fever/cough"
label variable h37i_4   "NA - Antibiotic pill/syrup taken for fever/cough"
label variable h37i_5   "NA - Antibiotic pill/syrup taken for fever/cough"
label variable h37i_6   "NA - Antibiotic pill/syrup taken for fever/cough"
label variable h37j_1   "NA - Antibiotic injection taken for fever/cough"
label variable h37j_2   "NA - Antibiotic injection taken for fever/cough"
label variable h37j_3   "NA - Antibiotic injection taken for fever/cough"
label variable h37j_4   "NA - Antibiotic injection taken for fever/cough"
label variable h37j_5   "NA - Antibiotic injection taken for fever/cough"
label variable h37j_6   "NA - Antibiotic injection taken for fever/cough"
label variable h37k_1   "NA - Aspirin taken for fever/cough"
label variable h37k_2   "NA - Aspirin taken for fever/cough"
label variable h37k_3   "NA - Aspirin taken for fever/cough"
label variable h37k_4   "NA - Aspirin taken for fever/cough"
label variable h37k_5   "NA - Aspirin taken for fever/cough"
label variable h37k_6   "NA - Aspirin taken for fever/cough"
label variable h37l_1   "NA - Acetaminophen/paracetamol/panadol taken for fever/cough"
label variable h37l_2   "NA - Acetaminophen/paracetamol/panadol taken for fever/cough"
label variable h37l_3   "NA - Acetaminophen/paracetamol/panadol taken for fever/cough"
label variable h37l_4   "NA - Acetaminophen/paracetamol/panadol taken for fever/cough"
label variable h37l_5   "NA - Acetaminophen/paracetamol/panadol taken for fever/cough"
label variable h37l_6   "NA - Acetaminophen/paracetamol/panadol taken for fever/cough"
label variable h37m_1   "NA - Ibuprofen taken for fever/cough"
label variable h37m_2   "NA - Ibuprofen taken for fever/cough"
label variable h37m_3   "NA - Ibuprofen taken for fever/cough"
label variable h37m_4   "NA - Ibuprofen taken for fever/cough"
label variable h37m_5   "NA - Ibuprofen taken for fever/cough"
label variable h37m_6   "NA - Ibuprofen taken for fever/cough"
label variable h37n_1   "NA - CS other taken for fever/cough"
label variable h37n_2   "NA - CS other taken for fever/cough"
label variable h37n_3   "NA - CS other taken for fever/cough"
label variable h37n_4   "NA - CS other taken for fever/cough"
label variable h37n_5   "NA - CS other taken for fever/cough"
label variable h37n_6   "NA - CS other taken for fever/cough"
label variable h37o_1   "NA - CS other for fever/cough"
label variable h37o_2   "NA - CS other for fever/cough"
label variable h37o_3   "NA - CS other for fever/cough"
label variable h37o_4   "NA - CS other for fever/cough"
label variable h37o_5   "NA - CS other for fever/cough"
label variable h37o_6   "NA - CS other for fever/cough"
label variable h37p_1   "NA - CS other for fever/cough"
label variable h37p_2   "NA - CS other for fever/cough"
label variable h37p_3   "NA - CS other for fever/cough"
label variable h37p_4   "NA - CS other for fever/cough"
label variable h37p_5   "NA - CS other for fever/cough"
label variable h37p_6   "NA - CS other for fever/cough"
label variable h37x_1   "NA - Other taken for fever/cough"
label variable h37x_2   "NA - Other taken for fever/cough"
label variable h37x_3   "NA - Other taken for fever/cough"
label variable h37x_4   "NA - Other taken for fever/cough"
label variable h37x_5   "NA - Other taken for fever/cough"
label variable h37x_6   "NA - Other taken for fever/cough"
label variable h37y_1   "NA - Nothing taken and didn't seek treatment for fever/cough"
label variable h37y_2   "NA - Nothing taken and didn't seek treatment for fever/cough"
label variable h37y_3   "NA - Nothing taken and didn't seek treatment for fever/cough"
label variable h37y_4   "NA - Nothing taken and didn't seek treatment for fever/cough"
label variable h37y_5   "NA - Nothing taken and didn't seek treatment for fever/cough"
label variable h37y_6   "NA - Nothing taken and didn't seek treatment for fever/cough"
label variable h37z_1   "NA - Don't know if or what was taken for fever/cough"
label variable h37z_2   "NA - Don't know if or what was taken for fever/cough"
label variable h37z_3   "NA - Don't know if or what was taken for fever/cough"
label variable h37z_4   "NA - Don't know if or what was taken for fever/cough"
label variable h37z_5   "NA - Don't know if or what was taken for fever/cough"
label variable h37z_6   "NA - Don't know if or what was taken for fever/cough"
label variable h46a_1   "Place first sought treatment for fever"
label variable h46a_2   "Place first sought treatment for fever"
label variable h46a_3   "Place first sought treatment for fever"
label variable h46a_4   "Place first sought treatment for fever"
label variable h46a_5   "Place first sought treatment for fever"
label variable h46a_6   "Place first sought treatment for fever"
label variable h46b_1   "NA - Days after fever sought advice or treatment"
label variable h46b_2   "NA - Days after fever sought advice or treatment"
label variable h46b_3   "NA - Days after fever sought advice or treatment"
label variable h46b_4   "NA - Days after fever sought advice or treatment"
label variable h46b_5   "NA - Days after fever sought advice or treatment"
label variable h46b_6   "NA - Days after fever sought advice or treatment"
label variable h47_1    "Blood taken from child's finger/heel for testing"
label variable h47_2    "Blood taken from child's finger/heel for testing"
label variable h47_3    "Blood taken from child's finger/heel for testing"
label variable h47_4    "Blood taken from child's finger/heel for testing"
label variable h47_5    "Blood taken from child's finger/heel for testing"
label variable h47_6    "Blood taken from child's finger/heel for testing"
label variable v801     "Time interview started (hhmm - 24 hour clock)"
label variable v802     "Time interview ended (hhmm - 24 hour clock)"
label variable v803     "Length of interview in minutes"
label variable v804     "Number of visits"
label variable v805     "Interviewer identification"
label variable v806     "NA - Keyer identification"
label variable v811     "NA - Presence of children < 10 for 'Wife beating justified' questions"
label variable v812     "NA - Presence of husband for 'Wife beating justified' questions"
label variable v813     "NA - Presence of other males for 'Wife beating justified' questions"
label variable v814     "NA - Presence of other females for 'Wife beating justified' questions"
label variable v815a    "NA - Presence of children < 10 during sexual activity section"
label variable v815b    "NA - Presence of male adults during sexual activity section"
label variable v815c    "NA - Presence of female adults during sexual activity section"
label variable idxml_1  "Index to Birth History"
label variable idxml_2  "Index to Birth History"
label variable idxml_3  "Index to Birth History"
label variable idxml_4  "Index to Birth History"
label variable idxml_5  "Index to Birth History"
label variable idxml_6  "Index to Birth History"
label variable ml0_1    "Type of mosquito bed net(s) child slept under last night"
label variable ml0_2    "Type of mosquito bed net(s) child slept under last night"
label variable ml0_3    "Type of mosquito bed net(s) child slept under last night"
label variable ml0_4    "Type of mosquito bed net(s) child slept under last night"
label variable ml0_5    "Type of mosquito bed net(s) child slept under last night"
label variable ml0_6    "Type of mosquito bed net(s) child slept under last night"
label variable ml1_1    "Number of times took fansidar during pregnancy"
label variable ml1_2    "Number of times took fansidar during pregnancy"
label variable ml1_3    "Number of times took fansidar during pregnancy"
label variable ml1_4    "Number of times took fansidar during pregnancy"
label variable ml1_5    "Number of times took fansidar during pregnancy"
label variable ml1_6    "Number of times took fansidar during pregnancy"
label variable ml2_1    "Source of antimalarial during pregnancy"
label variable ml2_2    "Source of antimalarial during pregnancy"
label variable ml2_3    "Source of antimalarial during pregnancy"
label variable ml2_4    "Source of antimalarial during pregnancy"
label variable ml2_5    "Source of antimalarial during pregnancy"
label variable ml2_6    "Source of antimalarial during pregnancy"
label variable ml11_1   "NA - Child has fever/cough now"
label variable ml11_2   "NA - Child has fever/cough now"
label variable ml11_3   "NA - Child has fever/cough now"
label variable ml11_4   "NA - Child has fever/cough now"
label variable ml11_5   "NA - Child has fever/cough now"
label variable ml11_6   "NA - Child has fever/cough now"
label variable ml12_1   "NA - Child has had convulsions in last 2 weeks"
label variable ml12_2   "NA - Child has had convulsions in last 2 weeks"
label variable ml12_3   "NA - Child has had convulsions in last 2 weeks"
label variable ml12_4   "NA - Child has had convulsions in last 2 weeks"
label variable ml12_5   "NA - Child has had convulsions in last 2 weeks"
label variable ml12_6   "NA - Child has had convulsions in last 2 weeks"
label variable ml13a_1  "Fansidar taken for fever/cough"
label variable ml13a_2  "Fansidar taken for fever/cough"
label variable ml13a_3  "Fansidar taken for fever/cough"
label variable ml13a_4  "Fansidar taken for fever/cough"
label variable ml13a_5  "Fansidar taken for fever/cough"
label variable ml13a_6  "Fansidar taken for fever/cough"
label variable ml13b_1  "Chloroquine taken for fever/cough"
label variable ml13b_2  "Chloroquine taken for fever/cough"
label variable ml13b_3  "Chloroquine taken for fever/cough"
label variable ml13b_4  "Chloroquine taken for fever/cough"
label variable ml13b_5  "Chloroquine taken for fever/cough"
label variable ml13b_6  "Chloroquine taken for fever/cough"
label variable ml13c_1  "Amodiaquine taken for fever/cough"
label variable ml13c_2  "Amodiaquine taken for fever/cough"
label variable ml13c_3  "Amodiaquine taken for fever/cough"
label variable ml13c_4  "Amodiaquine taken for fever/cough"
label variable ml13c_5  "Amodiaquine taken for fever/cough"
label variable ml13c_6  "Amodiaquine taken for fever/cough"
label variable ml13d_1  "Quinine ( pills ) taken for fever/cough"
label variable ml13d_2  "Quinine ( pills ) taken for fever/cough"
label variable ml13d_3  "Quinine ( pills ) taken for fever/cough"
label variable ml13d_4  "Quinine ( pills ) taken for fever/cough"
label variable ml13d_5  "Quinine ( pills ) taken for fever/cough"
label variable ml13d_6  "Quinine ( pills ) taken for fever/cough"
label variable ml13e_1  "Combination with artemisinin taken for fever/cough"
label variable ml13e_2  "Combination with artemisinin taken for fever/cough"
label variable ml13e_3  "Combination with artemisinin taken for fever/cough"
label variable ml13e_4  "Combination with artemisinin taken for fever/cough"
label variable ml13e_5  "Combination with artemisinin taken for fever/cough"
label variable ml13e_6  "Combination with artemisinin taken for fever/cough"
label variable ml13f_1  "Quinine ( injection/IV )taken for fever/cough"
label variable ml13f_2  "Quinine ( injection/IV )taken for fever/cough"
label variable ml13f_3  "Quinine ( injection/IV )taken for fever/cough"
label variable ml13f_4  "Quinine ( injection/IV )taken for fever/cough"
label variable ml13f_5  "Quinine ( injection/IV )taken for fever/cough"
label variable ml13f_6  "Quinine ( injection/IV )taken for fever/cough"
label variable ml13g_1  "Artesunate ( rectal ) taken for fever/cough"
label variable ml13g_2  "Artesunate ( rectal ) taken for fever/cough"
label variable ml13g_3  "Artesunate ( rectal ) taken for fever/cough"
label variable ml13g_4  "Artesunate ( rectal ) taken for fever/cough"
label variable ml13g_5  "Artesunate ( rectal ) taken for fever/cough"
label variable ml13g_6  "Artesunate ( rectal ) taken for fever/cough"
label variable ml13h_1  "Other antimalarial taken for fever/cough"
label variable ml13h_2  "Other antimalarial taken for fever/cough"
label variable ml13h_3  "Other antimalarial taken for fever/cough"
label variable ml13h_4  "Other antimalarial taken for fever/cough"
label variable ml13h_5  "Other antimalarial taken for fever/cough"
label variable ml13h_6  "Other antimalarial taken for fever/cough"
label variable ml13i_1  "Antibiotic pill/syrup taken for fever/cough"
label variable ml13i_2  "Antibiotic pill/syrup taken for fever/cough"
label variable ml13i_3  "Antibiotic pill/syrup taken for fever/cough"
label variable ml13i_4  "Antibiotic pill/syrup taken for fever/cough"
label variable ml13i_5  "Antibiotic pill/syrup taken for fever/cough"
label variable ml13i_6  "Antibiotic pill/syrup taken for fever/cough"
label variable ml13j_1  "Antibiotic injection taken for fever/cough"
label variable ml13j_2  "Antibiotic injection taken for fever/cough"
label variable ml13j_3  "Antibiotic injection taken for fever/cough"
label variable ml13j_4  "Antibiotic injection taken for fever/cough"
label variable ml13j_5  "Antibiotic injection taken for fever/cough"
label variable ml13j_6  "Antibiotic injection taken for fever/cough"
label variable ml13k_1  "Aspirin taken for fever/cough"
label variable ml13k_2  "Aspirin taken for fever/cough"
label variable ml13k_3  "Aspirin taken for fever/cough"
label variable ml13k_4  "Aspirin taken for fever/cough"
label variable ml13k_5  "Aspirin taken for fever/cough"
label variable ml13k_6  "Aspirin taken for fever/cough"
label variable ml13l_1  "Acetaminophen/paracetamol/panadol taken for fever/cough"
label variable ml13l_2  "Acetaminophen/paracetamol/panadol taken for fever/cough"
label variable ml13l_3  "Acetaminophen/paracetamol/panadol taken for fever/cough"
label variable ml13l_4  "Acetaminophen/paracetamol/panadol taken for fever/cough"
label variable ml13l_5  "Acetaminophen/paracetamol/panadol taken for fever/cough"
label variable ml13l_6  "Acetaminophen/paracetamol/panadol taken for fever/cough"
label variable ml13m_1  "Ibuprofen taken for fever/cough"
label variable ml13m_2  "Ibuprofen taken for fever/cough"
label variable ml13m_3  "Ibuprofen taken for fever/cough"
label variable ml13m_4  "Ibuprofen taken for fever/cough"
label variable ml13m_5  "Ibuprofen taken for fever/cough"
label variable ml13m_6  "Ibuprofen taken for fever/cough"
label variable ml13n_1  "Artesunate ( injection ) taken for fever/cough"
label variable ml13n_2  "Artesunate ( injection ) taken for fever/cough"
label variable ml13n_3  "Artesunate ( injection ) taken for fever/cough"
label variable ml13n_4  "Artesunate ( injection ) taken for fever/cough"
label variable ml13n_5  "Artesunate ( injection ) taken for fever/cough"
label variable ml13n_6  "Artesunate ( injection ) taken for fever/cough"
label variable ml13o_1  "NA - CS other taken for fever/cough"
label variable ml13o_2  "NA - CS other taken for fever/cough"
label variable ml13o_3  "NA - CS other taken for fever/cough"
label variable ml13o_4  "NA - CS other taken for fever/cough"
label variable ml13o_5  "NA - CS other taken for fever/cough"
label variable ml13o_6  "NA - CS other taken for fever/cough"
label variable ml13p_1  "NA - CS other taken for fever/cough"
label variable ml13p_2  "NA - CS other taken for fever/cough"
label variable ml13p_3  "NA - CS other taken for fever/cough"
label variable ml13p_4  "NA - CS other taken for fever/cough"
label variable ml13p_5  "NA - CS other taken for fever/cough"
label variable ml13p_6  "NA - CS other taken for fever/cough"
label variable ml13x_1  "Other taken for fever/cough"
label variable ml13x_2  "Other taken for fever/cough"
label variable ml13x_3  "Other taken for fever/cough"
label variable ml13x_4  "Other taken for fever/cough"
label variable ml13x_5  "Other taken for fever/cough"
label variable ml13x_6  "Other taken for fever/cough"
label variable ml13y_1  "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13y_2  "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13y_3  "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13y_4  "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13y_5  "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13y_6  "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13z_1  "Don't know if or what was taken for fever/cough"
label variable ml13z_2  "Don't know if or what was taken for fever/cough"
label variable ml13z_3  "Don't know if or what was taken for fever/cough"
label variable ml13z_4  "Don't know if or what was taken for fever/cough"
label variable ml13z_5  "Don't know if or what was taken for fever/cough"
label variable ml13z_6  "Don't know if or what was taken for fever/cough"
label variable ml14a_1  "NA - Injection given for fever/convulsion***"
label variable ml14a_2  "NA - Injection given for fever/convulsion***"
label variable ml14a_3  "NA - Injection given for fever/convulsion***"
label variable ml14a_4  "NA - Injection given for fever/convulsion***"
label variable ml14a_5  "NA - Injection given for fever/convulsion***"
label variable ml14a_6  "NA - Injection given for fever/convulsion***"
label variable ml14b_1  "NA - Suppository given for fever/convulsion***"
label variable ml14b_2  "NA - Suppository given for fever/convulsion***"
label variable ml14b_3  "NA - Suppository given for fever/convulsion***"
label variable ml14b_4  "NA - Suppository given for fever/convulsion***"
label variable ml14b_5  "NA - Suppository given for fever/convulsion***"
label variable ml14b_6  "NA - Suppository given for fever/convulsion***"
label variable ml14y_1  "NA - No suppository or injection given for fever/convulsion***"
label variable ml14y_2  "NA - No suppository or injection given for fever/convulsion***"
label variable ml14y_3  "NA - No suppository or injection given for fever/convulsion***"
label variable ml14y_4  "NA - No suppository or injection given for fever/convulsion***"
label variable ml14y_5  "NA - No suppository or injection given for fever/convulsion***"
label variable ml14y_6  "NA - No suppository or injection given for fever/convulsion***"
label variable ml14z_1  "NA - Don't know if suppository or injection given for fever/convulsion***"
label variable ml14z_2  "NA - Don't know if suppository or injection given for fever/convulsion***"
label variable ml14z_3  "NA - Don't know if suppository or injection given for fever/convulsion***"
label variable ml14z_4  "NA - Don't know if suppository or injection given for fever/convulsion***"
label variable ml14z_5  "NA - Don't know if suppository or injection given for fever/convulsion***"
label variable ml14z_6  "NA - Don't know if suppository or injection given for fever/convulsion***"
label variable ml15a_1  "Timing of start of fansidar"
label variable ml15a_2  "Timing of start of fansidar"
label variable ml15a_3  "Timing of start of fansidar"
label variable ml15a_4  "Timing of start of fansidar"
label variable ml15a_5  "Timing of start of fansidar"
label variable ml15a_6  "Timing of start of fansidar"
label variable ml15b_1  "NA - Number of days child took fansidar"
label variable ml15b_2  "NA - Number of days child took fansidar"
label variable ml15b_3  "NA - Number of days child took fansidar"
label variable ml15b_4  "NA - Number of days child took fansidar"
label variable ml15b_5  "NA - Number of days child took fansidar"
label variable ml15b_6  "NA - Number of days child took fansidar"
label variable ml15c_1  "NA - First source for fansidar"
label variable ml15c_2  "NA - First source for fansidar"
label variable ml15c_3  "NA - First source for fansidar"
label variable ml15c_4  "NA - First source for fansidar"
label variable ml15c_5  "NA - First source for fansidar"
label variable ml15c_6  "NA - First source for fansidar"
label variable ml16a_1  "Timing of start of chloroquine"
label variable ml16a_2  "Timing of start of chloroquine"
label variable ml16a_3  "Timing of start of chloroquine"
label variable ml16a_4  "Timing of start of chloroquine"
label variable ml16a_5  "Timing of start of chloroquine"
label variable ml16a_6  "Timing of start of chloroquine"
label variable ml16b_1  "NA - Number of days child took chloroquine"
label variable ml16b_2  "NA - Number of days child took chloroquine"
label variable ml16b_3  "NA - Number of days child took chloroquine"
label variable ml16b_4  "NA - Number of days child took chloroquine"
label variable ml16b_5  "NA - Number of days child took chloroquine"
label variable ml16b_6  "NA - Number of days child took chloroquine"
label variable ml16c_1  "NA - First source for chloroquine"
label variable ml16c_2  "NA - First source for chloroquine"
label variable ml16c_3  "NA - First source for chloroquine"
label variable ml16c_4  "NA - First source for chloroquine"
label variable ml16c_5  "NA - First source for chloroquine"
label variable ml16c_6  "NA - First source for chloroquine"
label variable ml17a_1  "Timing of start of amodiaquine"
label variable ml17a_2  "Timing of start of amodiaquine"
label variable ml17a_3  "Timing of start of amodiaquine"
label variable ml17a_4  "Timing of start of amodiaquine"
label variable ml17a_5  "Timing of start of amodiaquine"
label variable ml17a_6  "Timing of start of amodiaquine"
label variable ml17b_1  "NA - Number of days child took amodiaquine"
label variable ml17b_2  "NA - Number of days child took amodiaquine"
label variable ml17b_3  "NA - Number of days child took amodiaquine"
label variable ml17b_4  "NA - Number of days child took amodiaquine"
label variable ml17b_5  "NA - Number of days child took amodiaquine"
label variable ml17b_6  "NA - Number of days child took amodiaquine"
label variable ml17c_1  "NA - First source for amodiaquine"
label variable ml17c_2  "NA - First source for amodiaquine"
label variable ml17c_3  "NA - First source for amodiaquine"
label variable ml17c_4  "NA - First source for amodiaquine"
label variable ml17c_5  "NA - First source for amodiaquine"
label variable ml17c_6  "NA - First source for amodiaquine"
label variable ml18a_1  "Timing of start of quinine"
label variable ml18a_2  "Timing of start of quinine"
label variable ml18a_3  "Timing of start of quinine"
label variable ml18a_4  "Timing of start of quinine"
label variable ml18a_5  "Timing of start of quinine"
label variable ml18a_6  "Timing of start of quinine"
label variable ml18b_1  "NA - Number of days child took quinine"
label variable ml18b_2  "NA - Number of days child took quinine"
label variable ml18b_3  "NA - Number of days child took quinine"
label variable ml18b_4  "NA - Number of days child took quinine"
label variable ml18b_5  "NA - Number of days child took quinine"
label variable ml18b_6  "NA - Number of days child took quinine"
label variable ml18c_1  "NA - First source for quinine"
label variable ml18c_2  "NA - First source for quinine"
label variable ml18c_3  "NA - First source for quinine"
label variable ml18c_4  "NA - First source for quinine"
label variable ml18c_5  "NA - First source for quinine"
label variable ml18c_6  "NA - First source for quinine"
label variable ml19a_1  "NA - For fever/convulsion: consulted traditional healer***"
label variable ml19a_2  "NA - For fever/convulsion: consulted traditional healer***"
label variable ml19a_3  "NA - For fever/convulsion: consulted traditional healer***"
label variable ml19a_4  "NA - For fever/convulsion: consulted traditional healer***"
label variable ml19a_5  "NA - For fever/convulsion: consulted traditional healer***"
label variable ml19a_6  "NA - For fever/convulsion: consulted traditional healer***"
label variable ml19b_1  "NA - For fever/convulsion: gave tepid sponging***"
label variable ml19b_2  "NA - For fever/convulsion: gave tepid sponging***"
label variable ml19b_3  "NA - For fever/convulsion: gave tepid sponging***"
label variable ml19b_4  "NA - For fever/convulsion: gave tepid sponging***"
label variable ml19b_5  "NA - For fever/convulsion: gave tepid sponging***"
label variable ml19b_6  "NA - For fever/convulsion: gave tepid sponging***"
label variable ml19c_1  "NA - For fever/convulsion: gave herbs***"
label variable ml19c_2  "NA - For fever/convulsion: gave herbs***"
label variable ml19c_3  "NA - For fever/convulsion: gave herbs***"
label variable ml19c_4  "NA - For fever/convulsion: gave herbs***"
label variable ml19c_5  "NA - For fever/convulsion: gave herbs***"
label variable ml19c_6  "NA - For fever/convulsion: gave herbs***"
label variable ml19d_1  "NA - For fever/convulsion: CS***"
label variable ml19d_2  "NA - For fever/convulsion: CS***"
label variable ml19d_3  "NA - For fever/convulsion: CS***"
label variable ml19d_4  "NA - For fever/convulsion: CS***"
label variable ml19d_5  "NA - For fever/convulsion: CS***"
label variable ml19d_6  "NA - For fever/convulsion: CS***"
label variable ml19e_1  "NA - For fever/convulsion: CS***"
label variable ml19e_2  "NA - For fever/convulsion: CS***"
label variable ml19e_3  "NA - For fever/convulsion: CS***"
label variable ml19e_4  "NA - For fever/convulsion: CS***"
label variable ml19e_5  "NA - For fever/convulsion: CS***"
label variable ml19e_6  "NA - For fever/convulsion: CS***"
label variable ml19f_1  "NA - For fever/convulsion: CS***"
label variable ml19f_2  "NA - For fever/convulsion: CS***"
label variable ml19f_3  "NA - For fever/convulsion: CS***"
label variable ml19f_4  "NA - For fever/convulsion: CS***"
label variable ml19f_5  "NA - For fever/convulsion: CS***"
label variable ml19f_6  "NA - For fever/convulsion: CS***"
label variable ml19x_1  "NA - For fever/convulsion: other***"
label variable ml19x_2  "NA - For fever/convulsion: other***"
label variable ml19x_3  "NA - For fever/convulsion: other***"
label variable ml19x_4  "NA - For fever/convulsion: other***"
label variable ml19x_5  "NA - For fever/convulsion: other***"
label variable ml19x_6  "NA - For fever/convulsion: other***"
label variable ml19y_1  "NA - For fever/convulsion: gave/did nothing***"
label variable ml19y_2  "NA - For fever/convulsion: gave/did nothing***"
label variable ml19y_3  "NA - For fever/convulsion: gave/did nothing***"
label variable ml19y_4  "NA - For fever/convulsion: gave/did nothing***"
label variable ml19y_5  "NA - For fever/convulsion: gave/did nothing***"
label variable ml19y_6  "NA - For fever/convulsion: gave/did nothing***"
label variable ml19z_1  "NA - For fever/convulsion: don't know if something else was done***"
label variable ml19z_2  "NA - For fever/convulsion: don't know if something else was done***"
label variable ml19z_3  "NA - For fever/convulsion: don't know if something else was done***"
label variable ml19z_4  "NA - For fever/convulsion: don't know if something else was done***"
label variable ml19z_5  "NA - For fever/convulsion: don't know if something else was done***"
label variable ml19z_6  "NA - For fever/convulsion: don't know if something else was done***"
label variable ml20a_1  "Timing of start of DHAP"
label variable ml20a_2  "Timing of start of DHAP"
label variable ml20a_3  "Timing of start of DHAP"
label variable ml20a_4  "Timing of start of DHAP"
label variable ml20a_5  "Timing of start of DHAP"
label variable ml20a_6  "Timing of start of DHAP"
label variable ml20b_1  "NA - Number of days child took combination with artemisinin"
label variable ml20b_2  "NA - Number of days child took combination with artemisinin"
label variable ml20b_3  "NA - Number of days child took combination with artemisinin"
label variable ml20b_4  "NA - Number of days child took combination with artemisinin"
label variable ml20b_5  "NA - Number of days child took combination with artemisinin"
label variable ml20b_6  "NA - Number of days child took combination with artemisinin"
label variable ml20c_1  "NA - First source for combination with artemisinin"
label variable ml20c_2  "NA - First source for combination with artemisinin"
label variable ml20c_3  "NA - First source for combination with artemisinin"
label variable ml20c_4  "NA - First source for combination with artemisinin"
label variable ml20c_5  "NA - First source for combination with artemisinin"
label variable ml20c_6  "NA - First source for combination with artemisinin"
label variable ml21a_1  "Timing of start AL use"
label variable ml21a_2  "Timing of start AL use"
label variable ml21a_3  "Timing of start AL use"
label variable ml21a_4  "Timing of start AL use"
label variable ml21a_5  "Timing of start AL use"
label variable ml21a_6  "Timing of start AL use"
label variable ml21b_1  "NA - Number of days child took CS antimalarial"
label variable ml21b_2  "NA - Number of days child took CS antimalarial"
label variable ml21b_3  "NA - Number of days child took CS antimalarial"
label variable ml21b_4  "NA - Number of days child took CS antimalarial"
label variable ml21b_5  "NA - Number of days child took CS antimalarial"
label variable ml21b_6  "NA - Number of days child took CS antimalarial"
label variable ml21c_1  "NA - First source for CS antimalarial"
label variable ml21c_2  "NA - First source for CS antimalarial"
label variable ml21c_3  "NA - First source for CS antimalarial"
label variable ml21c_4  "NA - First source for CS antimalarial"
label variable ml21c_5  "NA - First source for CS antimalarial"
label variable ml21c_6  "NA - First source for CS antimalarial"
label variable ml22a_1  "Timing of start of Artesunate/Amodiaquine"
label variable ml22a_2  "Timing of start of Artesunate/Amodiaquine"
label variable ml22a_3  "Timing of start of Artesunate/Amodiaquine"
label variable ml22a_4  "Timing of start of Artesunate/Amodiaquine"
label variable ml22a_5  "Timing of start of Artesunate/Amodiaquine"
label variable ml22a_6  "Timing of start of Artesunate/Amodiaquine"
label variable ml22b_1  "NA - Number of days child took CS antimalarial"
label variable ml22b_2  "NA - Number of days child took CS antimalarial"
label variable ml22b_3  "NA - Number of days child took CS antimalarial"
label variable ml22b_4  "NA - Number of days child took CS antimalarial"
label variable ml22b_5  "NA - Number of days child took CS antimalarial"
label variable ml22b_6  "NA - Number of days child took CS antimalarial"
label variable ml22c_1  "NA - First source for CS antimalarial"
label variable ml22c_2  "NA - First source for CS antimalarial"
label variable ml22c_3  "NA - First source for CS antimalarial"
label variable ml22c_4  "NA - First source for CS antimalarial"
label variable ml22c_5  "NA - First source for CS antimalarial"
label variable ml22c_6  "NA - First source for CS antimalarial"
label variable ml23a_1  "NA - Timing of start of other anti-malarial use"
label variable ml23a_2  "NA - Timing of start of other anti-malarial use"
label variable ml23a_3  "NA - Timing of start of other anti-malarial use"
label variable ml23a_4  "NA - Timing of start of other anti-malarial use"
label variable ml23a_5  "NA - Timing of start of other anti-malarial use"
label variable ml23a_6  "NA - Timing of start of other anti-malarial use"
label variable ml23b_1  "NA - Number of days child took other anti-malarial"
label variable ml23b_2  "NA - Number of days child took other anti-malarial"
label variable ml23b_3  "NA - Number of days child took other anti-malarial"
label variable ml23b_4  "NA - Number of days child took other anti-malarial"
label variable ml23b_5  "NA - Number of days child took other anti-malarial"
label variable ml23b_6  "NA - Number of days child took other anti-malarial"
label variable ml23c_1  "NA - First source for other anti-malarial"
label variable ml23c_2  "NA - First source for other anti-malarial"
label variable ml23c_3  "NA - First source for other anti-malarial"
label variable ml23c_4  "NA - First source for other anti-malarial"
label variable ml23c_5  "NA - First source for other anti-malarial"
label variable ml23c_6  "NA - First source for other anti-malarial"
label variable ml24c_1  "NA - First source for antibiotic pill/syrup"
label variable ml24c_2  "NA - First source for antibiotic pill/syrup"
label variable ml24c_3  "NA - First source for antibiotic pill/syrup"
label variable ml24c_4  "NA - First source for antibiotic pill/syrup"
label variable ml24c_5  "NA - First source for antibiotic pill/syrup"
label variable ml24c_6  "NA - First source for antibiotic pill/syrup"
label variable s411a_1  "AL taken for fever/cough ( part of ML13E )"
label variable s411a_2  "AL taken for fever/cough ( part of ML13E )"
label variable s411a_3  "AL taken for fever/cough ( part of ML13E )"
label variable s411a_4  "AL taken for fever/cough ( part of ML13E )"
label variable s411a_5  "AL taken for fever/cough ( part of ML13E )"
label variable s411a_6  "AL taken for fever/cough ( part of ML13E )"
label variable s411b_1  "Artesunate/Amodiaquine taken for fever/cough ( part of ML13E )"
label variable s411b_2  "Artesunate/Amodiaquine taken for fever/cough ( part of ML13E )"
label variable s411b_3  "Artesunate/Amodiaquine taken for fever/cough ( part of ML13E )"
label variable s411b_4  "Artesunate/Amodiaquine taken for fever/cough ( part of ML13E )"
label variable s411b_5  "Artesunate/Amodiaquine taken for fever/cough ( part of ML13E )"
label variable s411b_6  "Artesunate/Amodiaquine taken for fever/cough ( part of ML13E )"
label variable s411c_1  "DHAP taken for fever/cough ( part of ML13E )"
label variable s411c_2  "DHAP taken for fever/cough ( part of ML13E )"
label variable s411c_3  "DHAP taken for fever/cough ( part of ML13E )"
label variable s411c_4  "DHAP taken for fever/cough ( part of ML13E )"
label variable s411c_5  "DHAP taken for fever/cough ( part of ML13E )"
label variable s411c_6  "DHAP taken for fever/cough ( part of ML13E )"
label variable ml25a_1  "Timing of start of artesunate"
label variable ml25a_2  "Timing of start of artesunate"
label variable ml25a_3  "Timing of start of artesunate"
label variable ml25a_4  "Timing of start of artesunate"
label variable ml25a_5  "Timing of start of artesunate"
label variable ml25a_6  "Timing of start of artesunate"
label variable s412b_1  "Logo for AL/Artesunate-Amodiaquine"
label variable s412b_2  "Logo for AL/Artesunate-Amodiaquine"
label variable s412b_3  "Logo for AL/Artesunate-Amodiaquine"
label variable s412b_4  "Logo for AL/Artesunate-Amodiaquine"
label variable s412b_5  "Logo for AL/Artesunate-Amodiaquine"
label variable s412b_6  "Logo for AL/Artesunate-Amodiaquine"
label variable scounty  "County"
label variable szone    "Malaria endemicity"
label variable slang    "Language of questionnaire"
label variable slangint "Language of interview"
label variable stransl  "Translator used"
label variable s105     "Highest educational level"
label variable s106     "Highest grade/form/year at that level"
label variable s111     "Have seen or heard any messages about malaria"
label variable s112a    "Have seen or heard messages on the radio"
label variable s112b    "Have seen or heard messages on the television"
label variable s112c    "Have seen or heard messages on a poster or billboard"
label variable s112d    "Have seen or heard messages from a community health worker"
label variable s112e    "Have seen or heard messages at a community event"
label variable s112f    "Have seen or heard messages anywhere else"
label variable s427b    "Importance of seeking antimalarial treatment"
label variable s427c    "Affordability of fever treatment"
label variable s427d    "Recommended treatment for malaria"
label variable s427e    "Seen or heard any information about ACT or AL"
label variable s427f1   "Where heard about ACT or AL: television"
label variable s427f2   "Where heard about ACT or AL: radio"
label variable s427f3   "Where heard about ACT or AL: newspaper"
label variable s427f4   "Where heard about ACT or AL: baraza"
label variable s427f5   "Where heard about ACT or AL: relative/friend"
label variable s427f6   "Where heard about ACT or AL: community leader/elder"
label variable s427f7   "Where heard about ACT or AL: community health worker"
label variable s427f8   "Where heard about ACT or AL: road show"
label variable s427f9   "Where heard about ACT or AL: other"
label variable sv112e   "Computer"
label variable sv112g   "Solar panel"
label variable sv112h   "Table"
label variable sv112i   "Chair"
label variable sv112j   "Sofa"
label variable sv112k   "Bed"
label variable sv112l   "Cupboard"
label variable sv112m   "Clock"
label variable sv112n   "Microwave oven"
label variable sv112o   "DVD player"
label variable sv112p   "CD player"

#delimit ;
label define V013    
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define V014    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define V015    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partially completed"
     6 "Respondent incapacitated"
     7 "Other"
;
label define V018    
     0 "No calendar"
;
label define V019    
     0 "No calendar"
;
label define V019A   
     0 "No calendar"
;
label define V020    
     0 "All woman sample"
     1 "Ever married sample"
;
label define V024    
     1 "Coast"
     2 "North Eastern"
     3 "Eastern"
     4 "Central"
     5 "Rift Valley"
     7 "Western"
     8 "Nyanza"
     9 "Nairobi"
;
label define V025    
     1 "Urban"
     2 "Rural"
;
label define V026    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V027    
     9 "Missing"
;
label define V028    
   999 "Missing"
;
label define V029    
    99 "Missing"
;
label define V030    
   999 "Missing"
;
label define V031    
   999 "Missing"
;
label define V032    
    99 "Missing"
;
label define V034    
     0 "Husband not in household"
;
label define V040    
  9999 "Missing"
;
label define V042    
     0 "Not selected"
     1 "Selected"
;
label define V044    
     0 "Woman not selected"
     1 "Woman selected and interviewed"
     2 "Woman selected, but privacy not possible"
     3 "Woman selected, but not interviewed"
;
label define V101    
     1 "Coast"
     2 "North Eastern"
     3 "Eastern"
     4 "Central"
     5 "Rift Valley"
     7 "Western"
     8 "Nyanza"
     9 "Nairobi"
;
label define V102    
     1 "Urban"
     2 "Rural"
;
label define V103    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define V104    
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define V105    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define V106    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define V107    
     0 "No years completed at level V106"
;
label define V113    
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    14 "Public to neighborhood"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
    97 "Not a dejure resident"
;
label define V115    
   996 "On premises"
   997 "Not a dejure resident"
   998 "Don't know"
;
label define V116    
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
    97 "Not a dejure resident"
;
label define V119    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V120    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V121    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V122    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V123    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V124    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V125    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V127    
    11 "Earth/sand"
    12 "Dung"
    21 "Wood planks"
    22 "Palm/bamboo"
    31 "Parquet or polished wood"
    32 "Vinyl/PVC or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
    97 "Not a dejure resident"
;
label define V128    
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Dung/mud/sod"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    27 "Iron sheets"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
    97 "Not a dejure resident"
;
label define V129    
    11 "No walls"
    12 "Thatch/grass/makuti"
    13 "Dung/mud/sod"
    21 "Iron sheets"
    22 "Tin cans"
    31 "Asbestos sheet"
    32 "Concrete"
    33 "Tiles"
    96 "Other"
    97 "Not a dejure resident"
;
label define V130    
     1 "Roman Catholic"
     2 "Protestant/other Christian"
     3 "Muslim"
     4 "No religion"
    96 "Other"
;
label define V131    
     1 "Embu"
     2 "Kalenjin"
     3 "Kamba"
     4 "Kikuyu"
     5 "Kisii"
     6 "Luhya"
     7 "Luo"
     8 "Maasai"
     9 "Meru"
    10 "Mijikenda/Swahili"
    11 "Somali"
    12 "Taita/Taveta"
    13 "Borana"
    14 "Maragoli"
    15 "Pokot"
    16 "Turkana"
    96 "Other"
;
label define V133    
    97 "Inconsistent"
;
label define V134    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V135    
     1 "Usual resident"
     2 "Visitor"
;
label define V139    
     0 "Abroad"
     1 "Coast"
     2 "North Eastern"
     3 "Eastern"
     4 "Central"
     5 "Rift Valley"
     7 "Western"
     8 "Nyanza"
     9 "Nairobi"
    97 "Not dejure resident"
;
label define V140    
     0 "Abroad"
     1 "Urban"
     2 "Rural"
     7 "Not a dejure resident"
;
label define V141    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     7 "Not a dejure resident"
;
label define V149    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     6 "to be added"
;
label define V150    
     1 "Head"
     2 "Wife"
     3 "Daughter"
     4 "Daughter-in-law"
     5 "Granddaughter"
     6 "Mother"
     7 "Mother-in-law"
     8 "Sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "Don't know"
;
label define V151    
     1 "Male"
     2 "Female"
;
label define V152    
    97 "97+"
    98 "Don't know"
;
label define V153    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V155    
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define V156    
     0 "No"
     1 "Yes"
;
label define V157    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V158    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V159    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V160    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V161    
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in house"
    96 "Other"
    97 "Not a dejure resident"
;
label define V166    
     0 "0 ppm (no iodine)"
     7 "7 ppm"
    15 "15 ppm"
    30 "30 ppm"
   994 "Salt not tested"
   995 "No salt"
   997 "Not a dejure resident"
;
label define V167    
     0 "None"
    90 "90+"
;
label define V168    
     0 "No"
     1 "Yes"
;
label define V190    
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define ML101   
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define B0      
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
;
label define B4      
     1 "Male"
     2 "Female"
;
label define B5      
     0 "No"
     1 "Yes"
;
label define B6      
   100 "Died on day of birth"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
   997 "Inconsistent"
   998 "Don't know"
;
label define B9      
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
;
label define B10     
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define B13     
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
;
label define B15     
     0 "No"
     1 "Yes"
;
label define B16     
     0 "Not listed in household"
;
label define S216D   
    98 "Don't know"
;
label define V208    
     0 "No births"
;
label define V209    
     0 "No births"
;
label define V213    
     0 "No or unsure"
     1 "Yes"
;
label define V215    
   100 "Day of interview"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
   994 "In menopause/had hysterectomy"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
;
label define V216    
     0 "No"
     1 "Yes"
;
label define V217    
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define V220    
     6 "6+"
;
label define V221    
   996 "Negative interval"
;
label define V223    
     7 "Month - exact date"
     8 "None - date placed"
;
label define V225    
     1 "Then"
     2 "Later"
     3 "Not at all"
;
label define V226    
   994 "In menopause"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
;
label define V227    
     0 "No flag"
     1 "N > interval since birth"
     2 "N + amen. > interval"
     3 "N, but period not returned"
     4 "95, but no birth"
     5 "95, but period returned"
     6 "96, but period returned"
     7 "N, last period during pregnancy"
     8 "96, had children"
     9 "N, period before last birth"
;
label define V228    
     0 "No"
     1 "Yes"
;
label define V229    
    97 "Inconsistent"
    98 "Don't know"
;
label define V230    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V231    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V232    
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     7 "Month"
     8 "None"
;
label define V233    
    97 "Inconsistent"
    98 "Don't know"
;
label define V234    
     0 "No"
     1 "Yes"
;
label define V235    
     0 "No prior child"
;
label define V237    
     0 "No"
     1 "Yes"
;
label define V239    
     0 "No"
     1 "Yes"
;
label define V240    
    97 "Inconsistent"
    98 "Don't know"
;
label define V241    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V242    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V243    
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     7 "Month"
     8 "None"
;
label define M2A     
     0 "No"
     1 "Yes"
;
label define M2B     
     0 "No"
     1 "Yes"
;
label define M2C     
     0 "No"
     1 "Yes"
;
label define M2D     
     0 "No"
     1 "Yes"
;
label define M2E     
     0 "No"
     1 "Yes"
;
label define M2F     
     0 "No"
     1 "Yes"
;
label define M2G     
     0 "No"
     1 "Yes"
;
label define M2H     
     0 "No"
     1 "Yes"
;
label define M2I     
     0 "No"
     1 "Yes"
;
label define M2J     
     0 "No"
     1 "Yes"
;
label define M2K     
     0 "No"
     1 "Yes"
;
label define M2L     
     0 "No"
     1 "Yes"
;
label define M2M     
     0 "No"
     1 "Yes"
;
label define M2N     
     0 "No: some care"
     1 "Yes: no care"
;
label define M14     
     0 "No antenatal visits"
    98 "Don't know"
;
label define M49A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H22     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H31     
     0 "No"
     1 "Yes, last 24 hours"
     2 "Yes, last two weeks"
     8 "Don't know"
;
label define H31B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H31C    
     1 "Chest only"
     2 "Nose only"
     3 "Both"
     6 "Other"
     8 "Don't know"
;
label define H31D    
     0 "Nothing to drink"
     2 "Much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define H31E    
     0 "Stopped food"
     1 "Never gave food"
     2 "Much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define H32A    
     0 "No"
     1 "Yes"
;
label define H32B    
     0 "No"
     1 "Yes"
;
label define H32C    
     0 "No"
     1 "Yes"
;
label define H32D    
     0 "No"
     1 "Yes"
;
label define H32E    
     0 "No"
     1 "Yes"
;
label define H32F    
     0 "No"
     1 "Yes"
;
label define H32G    
     0 "No"
     1 "Yes"
;
label define H32H    
     0 "No"
     1 "Yes"
;
label define H32I    
     0 "No"
     1 "Yes"
;
label define H32J    
     0 "No"
     1 "Yes"
;
label define H32K    
     0 "No"
     1 "Yes"
;
label define H32L    
     0 "No"
     1 "Yes"
;
label define H32M    
     0 "No"
     1 "Yes"
;
label define H32N    
     0 "No"
     1 "Yes"
;
label define H32O    
     0 "No"
     1 "Yes"
;
label define H32P    
     0 "No"
     1 "Yes"
;
label define H32Q    
     0 "No"
     1 "Yes"
;
label define H32R    
     0 "No"
     1 "Yes"
;
label define H32S    
     0 "No"
     1 "Yes"
;
label define H32T    
     0 "No"
     1 "Yes"
;
label define H32U    
     0 "No"
     1 "Yes"
;
label define H32V    
     0 "No"
     1 "Yes"
;
label define H32W    
     0 "No"
     1 "Yes"
;
label define H32X    
     0 "No"
     1 "Yes"
;
label define H32Y    
     0 "No: received treatment"
     1 "Yes: no treatment"
;
label define H32Z    
     0 "No"
     1 "Yes"
;
label define H37A    
     0 "No"
     1 "Yes"
;
label define H37B    
     0 "No"
     1 "Yes"
;
label define H37C    
     0 "No"
     1 "Yes"
;
label define H37D    
     0 "No"
     1 "Yes"
;
label define H37E    
     0 "No"
     1 "Yes"
;
label define H37F    
     0 "No"
     1 "Yes"
;
label define H37G    
     0 "No"
     1 "Yes"
;
label define H37H    
     0 "No"
     1 "Yes"
;
label define H37I    
     0 "No"
     1 "Yes"
;
label define H37J    
     0 "No"
     1 "Yes"
;
label define H37K    
     0 "No"
     1 "Yes"
;
label define H37L    
     0 "No"
     1 "Yes"
;
label define H37M    
     0 "No"
     1 "Yes"
;
label define H37N    
     0 "No"
     1 "Yes"
;
label define H37O    
     0 "No"
     1 "Yes"
;
label define H37P    
     0 "No"
     1 "Yes"
;
label define H37X    
     0 "No"
     1 "Yes"
;
label define H37Y    
     0 "No"
     1 "Yes, nothing taken"
;
label define H37Z    
     0 "No"
     1 "Yes, don't know"
;
label define H46A    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Government dispensary"
    14 "Other public"
    20 "PRIVATE SECTOR"
    21 "Mission hospital, clinic"
    22 "Private hospital, clinic"
    23 "Pharmacy"
    24 "Other private"
    25 "Mobile clinic"
    26 "Community health worker"
    30 "OTHER"
    31 "Shop"
    32 "Traditional healer"
    33 "Relative/friend"
    96 "Other"
;
label define H46B    
     0 "Same day"
    98 "Don't know"
;
label define H47     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V801    
  9999 "Missing"
;
label define V802    
  9999 "Missing"
;
label define V803    
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define V804    
     9 "Missing"
;
label define V805    
   999 "Missing"
;
label define V806    
    99 "Missing"
;
label define V811    
     0 "No"
     1 "Yes - listening"
     2 "Yes - not listening"
;
label define V812    
     0 "No"
     1 "Yes - listening"
     2 "Yes - not listening"
;
label define V813    
     0 "No"
     1 "Yes - listening"
     2 "Yes - not listening"
;
label define V814    
     0 "No"
     1 "Yes - listening"
     2 "Yes - not listening"
;
label define V815A   
     0 "No"
     1 "Yes"
;
label define V815B   
     0 "No"
     1 "Yes"
;
label define V815C   
     0 "No"
     1 "Yes"
;
label define ML0     
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define ML1     
    98 "Don't know"
;
label define ML2     
     1 "Antenatal visit"
     2 "Another facility visit"
     6 "Other source"
;
label define ML11    
     0 "No"
     1 "Yes, fever only"
     2 "Yes, cough only"
     3 "Both fever and cough"
     8 "Don't know"
;
label define ML12    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define ML13A   
     0 "No"
     1 "Yes"
;
label define ML13B   
     0 "No"
     1 "Yes"
;
label define ML13C   
     0 "No"
     1 "Yes"
;
label define ML13D   
     0 "No"
     1 "Yes"
;
label define ML13E   
     0 "No"
     1 "Yes"
;
label define ML13F   
     0 "No"
     1 "Yes"
;
label define ML13G   
     0 "No"
     1 "Yes"
;
label define ML13H   
     0 "No"
     1 "Yes"
;
label define ML13I   
     0 "No"
     1 "Yes"
;
label define ML13J   
     0 "No"
     1 "Yes"
;
label define ML13K   
     0 "No"
     1 "Yes"
;
label define ML13L   
     0 "No"
     1 "Yes"
;
label define ML13M   
     0 "No"
     1 "Yes"
;
label define ML13N   
     0 "No"
     1 "Yes"
;
label define ML13O   
     0 "No"
     1 "Yes"
;
label define ML13P   
     0 "No"
     1 "Yes"
;
label define ML13X   
     0 "No"
     1 "Yes"
;
label define ML13Y   
     0 "No"
     1 "Yes, nothing taken"
;
label define ML13Z   
     0 "No"
     1 "Yes, don't know"
;
label define ML14A   
     0 "No"
     1 "Yes"
;
label define ML14B   
     0 "No"
     1 "Yes"
;
label define ML14Y   
     0 "No"
     1 "Yes"
;
label define ML14Z   
     0 "No"
     1 "Yes"
;
label define ML15A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML15B   
     7 "7+ days"
     8 "Don't know"
;
label define ML15C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML16A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML16B   
     7 "7+ days"
     8 "Don't know"
;
label define ML16C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML17A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML17B   
     7 "7+ days"
     8 "Don't know"
;
label define ML17C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML18A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML18B   
     7 "7+ days"
     8 "Don't know"
;
label define ML18C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML19A   
     0 "No"
     1 "Yes"
;
label define ML19B   
     0 "No"
     1 "Yes"
;
label define ML19C   
     0 "No"
     1 "Yes"
;
label define ML19D   
     0 "No"
     1 "Yes"
;
label define ML19E   
     0 "No"
     1 "Yes"
;
label define ML19F   
     0 "No"
     1 "Yes"
;
label define ML19X   
     0 "No"
     1 "Yes"
;
label define ML19Y   
     0 "No"
     1 "Yes"
;
label define ML19Z   
     0 "No"
     1 "Yes"
;
label define ML20A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML20B   
     7 "7+ days"
     8 "Don't know"
;
label define ML20C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML21A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML21B   
     7 "7+ days"
     8 "Don't know"
;
label define ML21C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML22A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML22B   
     7 "7+ days"
     8 "Don't know"
;
label define ML22C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML23A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML23B   
     7 "7+ days"
     8 "Don't know"
;
label define ML23C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML24C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define S411A   
     0 "No"
     1 "Yes"
;
label define S411B   
     0 "No"
     1 "Yes"
;
label define S411C   
     0 "No"
     1 "Yes"
;
label define ML25A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define S412B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SCOUNTY 
   101 "NAIROBI"
   201 "NYANDARUA"
   202 "NYERI"
   203 "KIRINYAGA"
   204 "MURANGA"
   205 "KIAMBU"
   301 "MOMBASA"
   302 "KWALE"
   303 "KILIFI"
   304 "TANA RIVER"
   305 "LAMU"
   306 "TAITA TAVETA"
   401 "MARSABIT"
   402 "ISIOLO"
   403 "MERU"
   404 "THARAKA"
   405 "EMBU"
   406 "KITUI"
   407 "MACHAKOS"
   408 "MAKUENI"
   501 "GARISSA"
   502 "WAJIR"
   503 "MANDERA"
   601 "SIAYA"
   602 "KISUMU"
   603 "MIGORI"
   604 "HOMA BAY"
   605 "KISII"
   606 "NYAMIRA"
   701 "TURKANA"
   702 "WEST POKOT"
   703 "SAMBURU"
   704 "TRANS-NZOIA"
   705 "BARINGO"
   706 "UASIN GISHU"
   707 "ELGEYO MARAKWET"
   708 "NANDI"
   709 "LAIKIPIA"
   710 "NAKURU"
   711 "NAROK"
   712 "KAJIADO"
   713 "KERICHO"
   714 "BOMET"
   801 "KAKAMEGA"
   802 "VIHIGA"
   803 "BUNGOMA"
   804 "BUSIA"
;
label define SZONE   
     1 "Highland epidemic"
     2 "Lake endemic"
     3 "Coast endemic"
     4 "Semi-arid, seasonal"
     5 "Low risk"
;
label define SLANG   
     1 "English"
     2 "Kiswahili"
;
label define SLANGINT
     1 "English"
     2 "Kiswahili"
     3 "Borana"
     4 "Embu"
     5 "Kalenjin"
     6 "Kamba"
     7 "Kikuyu"
     8 "Kisii"
     9 "Luhya"
    10 "Maragoli"
    11 "Luo"
    12 "Maasai"
    13 "Meru"
    14 "Mijikenda"
    15 "Pokot"
    16 "Somali"
    17 "Turkana"
    18 "Other"
;
label define STRANSL 
     0 "No"
     1 "Yes"
;
label define S105    
     1 "Primary"
     2 "Post-primary/vocational"
     3 "Secondary / 'A' level"
     4 "College ( middle level )"
     5 "University"
;
label define S111    
     0 "No"
     1 "Yes"
;
label define S112A   
     0 "No"
     1 "Yes"
;
label define S112B   
     0 "No"
     1 "Yes"
;
label define S112C   
     0 "No"
     1 "Yes"
;
label define S112D   
     0 "No"
     1 "Yes"
;
label define S112E   
     0 "No"
     1 "Yes"
;
label define S112F   
     0 "No"
     1 "Yes"
;
label define S427B   
     1 "Extremely important"
     2 "Very important"
     3 "A little important"
     4 "Not at all important"
;
label define S427C   
     1 "Very affordable"
     2 "Affordable"
     3 "Unaffordable"
     4 "Very unaffordable"
;
label define S427D   
     1 "ACT/AL"
     2 "SP/Fansidar"
     3 "Chloroquine"
     4 "Amodiaquine"
     6 "Other"
     8 "Don't know"
;
label define S427E   
     0 "No"
     1 "Yes"
;
label define S427F1  
     0 "No"
     1 "Yes"
;
label define S427F2  
     0 "No"
     1 "Yes"
;
label define S427F3  
     0 "No"
     1 "Yes"
;
label define S427F4  
     0 "No"
     1 "Yes"
;
label define S427F5  
     0 "No"
     1 "Yes"
;
label define S427F6  
     0 "No"
     1 "Yes"
;
label define S427F7  
     0 "No"
     1 "Yes"
;
label define S427F8  
     0 "No"
     1 "Yes"
;
label define S427F9  
     0 "No"
     1 "Yes"
;
label define SV112E  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112G  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112H  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112I  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112J  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112K  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112L  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112M  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112N  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112O  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define SV112P  
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;

#delimit cr
label values v013     V013    
label values v014     V014    
label values v015     V015    
label values v018     V018    
label values v019     V019    
label values v019a    V019A   
label values v020     V020    
label values v024     V024    
label values v025     V025    
label values v026     V026    
label values v034     V034    
label values v042     V042    
label values v044     V044    
label values v101     V101    
label values v102     V102    
label values v103     V103    
label values v104     V104    
label values v105     V105    
label values v106     V106    
label values v107     V107    
label values v113     V113    
label values v115     V115    
label values v116     V116    
label values v119     V119    
label values v120     V120    
label values v121     V121    
label values v122     V122    
label values v123     V123    
label values v124     V124    
label values v125     V125    
label values v127     V127    
label values v128     V128    
label values v129     V129    
label values v130     V130    
label values v131     V131    
label values v133     V133    
label values v134     V134    
label values v135     V135    
label values v139     V139    
label values v140     V140    
label values v141     V141    
label values v149     V149    
label values v150     V150    
label values v151     V151    
label values v152     V152    
label values v153     V153    
label values v155     V155    
label values v156     V156    
label values v157     V157    
label values v158     V158    
label values v159     V159    
label values v160     V160    
label values v161     V161    
label values v166     V166    
label values v167     V167    
label values v168     V168    
label values v190     V190    
label values ml101    ML101   
label values b0_01    B0      
label values b0_02    B0      
label values b0_03    B0      
label values b0_04    B0      
label values b0_05    B0      
label values b0_06    B0      
label values b0_07    B0      
label values b0_08    B0      
label values b0_09    B0      
label values b0_10    B0      
label values b0_11    B0      
label values b0_12    B0      
label values b0_13    B0      
label values b0_14    B0      
label values b0_15    B0      
label values b0_16    B0      
label values b0_17    B0      
label values b0_18    B0      
label values b0_19    B0      
label values b0_20    B0      
label values b4_01    B4      
label values b4_02    B4      
label values b4_03    B4      
label values b4_04    B4      
label values b4_05    B4      
label values b4_06    B4      
label values b4_07    B4      
label values b4_08    B4      
label values b4_09    B4      
label values b4_10    B4      
label values b4_11    B4      
label values b4_12    B4      
label values b4_13    B4      
label values b4_14    B4      
label values b4_15    B4      
label values b4_16    B4      
label values b4_17    B4      
label values b4_18    B4      
label values b4_19    B4      
label values b4_20    B4      
label values b5_01    B5      
label values b5_02    B5      
label values b5_03    B5      
label values b5_04    B5      
label values b5_05    B5      
label values b5_06    B5      
label values b5_07    B5      
label values b5_08    B5      
label values b5_09    B5      
label values b5_10    B5      
label values b5_11    B5      
label values b5_12    B5      
label values b5_13    B5      
label values b5_14    B5      
label values b5_15    B5      
label values b5_16    B5      
label values b5_17    B5      
label values b5_18    B5      
label values b5_19    B5      
label values b5_20    B5      
label values b6_01    B6      
label values b6_02    B6      
label values b6_03    B6      
label values b6_04    B6      
label values b6_05    B6      
label values b6_06    B6      
label values b6_07    B6      
label values b6_08    B6      
label values b6_09    B6      
label values b6_10    B6      
label values b6_11    B6      
label values b6_12    B6      
label values b6_13    B6      
label values b6_14    B6      
label values b6_15    B6      
label values b6_16    B6      
label values b6_17    B6      
label values b6_18    B6      
label values b6_19    B6      
label values b6_20    B6      
label values b9_01    B9      
label values b9_02    B9      
label values b9_03    B9      
label values b9_04    B9      
label values b9_05    B9      
label values b9_06    B9      
label values b9_07    B9      
label values b9_08    B9      
label values b9_09    B9      
label values b9_10    B9      
label values b9_11    B9      
label values b9_12    B9      
label values b9_13    B9      
label values b9_14    B9      
label values b9_15    B9      
label values b9_16    B9      
label values b9_17    B9      
label values b9_18    B9      
label values b9_19    B9      
label values b9_20    B9      
label values b10_01   B10     
label values b10_02   B10     
label values b10_03   B10     
label values b10_04   B10     
label values b10_05   B10     
label values b10_06   B10     
label values b10_07   B10     
label values b10_08   B10     
label values b10_09   B10     
label values b10_10   B10     
label values b10_11   B10     
label values b10_12   B10     
label values b10_13   B10     
label values b10_14   B10     
label values b10_15   B10     
label values b10_16   B10     
label values b10_17   B10     
label values b10_18   B10     
label values b10_19   B10     
label values b10_20   B10     
label values b13_01   B13     
label values b13_02   B13     
label values b13_03   B13     
label values b13_04   B13     
label values b13_05   B13     
label values b13_06   B13     
label values b13_07   B13     
label values b13_08   B13     
label values b13_09   B13     
label values b13_10   B13     
label values b13_11   B13     
label values b13_12   B13     
label values b13_13   B13     
label values b13_14   B13     
label values b13_15   B13     
label values b13_16   B13     
label values b13_17   B13     
label values b13_18   B13     
label values b13_19   B13     
label values b13_20   B13     
label values b15_01   B15     
label values b15_02   B15     
label values b15_03   B15     
label values b15_04   B15     
label values b15_05   B15     
label values b15_06   B15     
label values b15_07   B15     
label values b15_08   B15     
label values b15_09   B15     
label values b15_10   B15     
label values b15_11   B15     
label values b15_12   B15     
label values b15_13   B15     
label values b15_14   B15     
label values b15_15   B15     
label values b15_16   B15     
label values b15_17   B15     
label values b15_18   B15     
label values b15_19   B15     
label values b15_20   B15     
label values b16_01   B16     
label values b16_02   B16     
label values b16_03   B16     
label values b16_04   B16     
label values b16_05   B16     
label values b16_06   B16     
label values b16_07   B16     
label values b16_08   B16     
label values b16_09   B16     
label values b16_10   B16     
label values b16_11   B16     
label values b16_12   B16     
label values b16_13   B16     
label values b16_14   B16     
label values b16_15   B16     
label values b16_16   B16     
label values b16_17   B16     
label values b16_18   B16     
label values b16_19   B16     
label values b16_20   B16     
label values s216d_01 S216D   
label values s216d_02 S216D   
label values s216d_03 S216D   
label values s216d_04 S216D   
label values s216d_05 S216D   
label values s216d_06 S216D   
label values s216d_07 S216D   
label values s216d_08 S216D   
label values s216d_09 S216D   
label values s216d_10 S216D   
label values s216d_11 S216D   
label values s216d_12 S216D   
label values s216d_13 S216D   
label values s216d_14 S216D   
label values s216d_15 S216D   
label values s216d_16 S216D   
label values s216d_17 S216D   
label values s216d_18 S216D   
label values s216d_19 S216D   
label values s216d_20 S216D   
label values v208     V208    
label values v209     V209    
label values v213     V213    
label values v215     V215    
label values v216     V216    
label values v217     V217    
label values v220     V220    
label values v221     V221    
label values v223     V223    
label values v225     V225    
label values v226     V226    
label values v227     V227    
label values v228     V228    
label values v229     V229    
label values v230     V230    
label values v231     V231    
label values v232     V232    
label values v233     V233    
label values v234     V234    
label values v235     V235    
label values v237     V237    
label values v239     V239    
label values v240     V240    
label values v241     V241    
label values v242     V242    
label values v243     V243    
label values m2a_1    M2A     
label values m2a_2    M2A     
label values m2a_3    M2A     
label values m2a_4    M2A     
label values m2a_5    M2A     
label values m2a_6    M2A     
label values m2b_1    M2B     
label values m2b_2    M2B     
label values m2b_3    M2B     
label values m2b_4    M2B     
label values m2b_5    M2B     
label values m2b_6    M2B     
label values m2c_1    M2C     
label values m2c_2    M2C     
label values m2c_3    M2C     
label values m2c_4    M2C     
label values m2c_5    M2C     
label values m2c_6    M2C     
label values m2d_1    M2D     
label values m2d_2    M2D     
label values m2d_3    M2D     
label values m2d_4    M2D     
label values m2d_5    M2D     
label values m2d_6    M2D     
label values m2e_1    M2E     
label values m2e_2    M2E     
label values m2e_3    M2E     
label values m2e_4    M2E     
label values m2e_5    M2E     
label values m2e_6    M2E     
label values m2f_1    M2F     
label values m2f_2    M2F     
label values m2f_3    M2F     
label values m2f_4    M2F     
label values m2f_5    M2F     
label values m2f_6    M2F     
label values m2g_1    M2G     
label values m2g_2    M2G     
label values m2g_3    M2G     
label values m2g_4    M2G     
label values m2g_5    M2G     
label values m2g_6    M2G     
label values m2h_1    M2H     
label values m2h_2    M2H     
label values m2h_3    M2H     
label values m2h_4    M2H     
label values m2h_5    M2H     
label values m2h_6    M2H     
label values m2i_1    M2I     
label values m2i_2    M2I     
label values m2i_3    M2I     
label values m2i_4    M2I     
label values m2i_5    M2I     
label values m2i_6    M2I     
label values m2j_1    M2J     
label values m2j_2    M2J     
label values m2j_3    M2J     
label values m2j_4    M2J     
label values m2j_5    M2J     
label values m2j_6    M2J     
label values m2k_1    M2K     
label values m2k_2    M2K     
label values m2k_3    M2K     
label values m2k_4    M2K     
label values m2k_5    M2K     
label values m2k_6    M2K     
label values m2l_1    M2L     
label values m2l_2    M2L     
label values m2l_3    M2L     
label values m2l_4    M2L     
label values m2l_5    M2L     
label values m2l_6    M2L     
label values m2m_1    M2M     
label values m2m_2    M2M     
label values m2m_3    M2M     
label values m2m_4    M2M     
label values m2m_5    M2M     
label values m2m_6    M2M     
label values m2n_1    M2N     
label values m2n_2    M2N     
label values m2n_3    M2N     
label values m2n_4    M2N     
label values m2n_5    M2N     
label values m2n_6    M2N     
label values m14_1    M14     
label values m14_2    M14     
label values m14_3    M14     
label values m14_4    M14     
label values m14_5    M14     
label values m14_6    M14     
label values m49a_1   M49A    
label values m49a_2   M49A    
label values m49a_3   M49A    
label values m49a_4   M49A    
label values m49a_5   M49A    
label values m49a_6   M49A    
label values h22_1    H22     
label values h22_2    H22     
label values h22_3    H22     
label values h22_4    H22     
label values h22_5    H22     
label values h22_6    H22     
label values h31_1    H31     
label values h31_2    H31     
label values h31_3    H31     
label values h31_4    H31     
label values h31_5    H31     
label values h31_6    H31     
label values h31b_1   H31B    
label values h31b_2   H31B    
label values h31b_3   H31B    
label values h31b_4   H31B    
label values h31b_5   H31B    
label values h31b_6   H31B    
label values h31c_1   H31C    
label values h31c_2   H31C    
label values h31c_3   H31C    
label values h31c_4   H31C    
label values h31c_5   H31C    
label values h31c_6   H31C    
label values h31d_1   H31D    
label values h31d_2   H31D    
label values h31d_3   H31D    
label values h31d_4   H31D    
label values h31d_5   H31D    
label values h31d_6   H31D    
label values h31e_1   H31E    
label values h31e_2   H31E    
label values h31e_3   H31E    
label values h31e_4   H31E    
label values h31e_5   H31E    
label values h31e_6   H31E    
label values h32a_1   H32A    
label values h32a_2   H32A    
label values h32a_3   H32A    
label values h32a_4   H32A    
label values h32a_5   H32A    
label values h32a_6   H32A    
label values h32b_1   H32B    
label values h32b_2   H32B    
label values h32b_3   H32B    
label values h32b_4   H32B    
label values h32b_5   H32B    
label values h32b_6   H32B    
label values h32c_1   H32C    
label values h32c_2   H32C    
label values h32c_3   H32C    
label values h32c_4   H32C    
label values h32c_5   H32C    
label values h32c_6   H32C    
label values h32d_1   H32D    
label values h32d_2   H32D    
label values h32d_3   H32D    
label values h32d_4   H32D    
label values h32d_5   H32D    
label values h32d_6   H32D    
label values h32e_1   H32E    
label values h32e_2   H32E    
label values h32e_3   H32E    
label values h32e_4   H32E    
label values h32e_5   H32E    
label values h32e_6   H32E    
label values h32f_1   H32F    
label values h32f_2   H32F    
label values h32f_3   H32F    
label values h32f_4   H32F    
label values h32f_5   H32F    
label values h32f_6   H32F    
label values h32g_1   H32G    
label values h32g_2   H32G    
label values h32g_3   H32G    
label values h32g_4   H32G    
label values h32g_5   H32G    
label values h32g_6   H32G    
label values h32h_1   H32H    
label values h32h_2   H32H    
label values h32h_3   H32H    
label values h32h_4   H32H    
label values h32h_5   H32H    
label values h32h_6   H32H    
label values h32i_1   H32I    
label values h32i_2   H32I    
label values h32i_3   H32I    
label values h32i_4   H32I    
label values h32i_5   H32I    
label values h32i_6   H32I    
label values h32j_1   H32J    
label values h32j_2   H32J    
label values h32j_3   H32J    
label values h32j_4   H32J    
label values h32j_5   H32J    
label values h32j_6   H32J    
label values h32k_1   H32K    
label values h32k_2   H32K    
label values h32k_3   H32K    
label values h32k_4   H32K    
label values h32k_5   H32K    
label values h32k_6   H32K    
label values h32l_1   H32L    
label values h32l_2   H32L    
label values h32l_3   H32L    
label values h32l_4   H32L    
label values h32l_5   H32L    
label values h32l_6   H32L    
label values h32m_1   H32M    
label values h32m_2   H32M    
label values h32m_3   H32M    
label values h32m_4   H32M    
label values h32m_5   H32M    
label values h32m_6   H32M    
label values h32n_1   H32N    
label values h32n_2   H32N    
label values h32n_3   H32N    
label values h32n_4   H32N    
label values h32n_5   H32N    
label values h32n_6   H32N    
label values h32o_1   H32O    
label values h32o_2   H32O    
label values h32o_3   H32O    
label values h32o_4   H32O    
label values h32o_5   H32O    
label values h32o_6   H32O    
label values h32p_1   H32P    
label values h32p_2   H32P    
label values h32p_3   H32P    
label values h32p_4   H32P    
label values h32p_5   H32P    
label values h32p_6   H32P    
label values h32q_1   H32Q    
label values h32q_2   H32Q    
label values h32q_3   H32Q    
label values h32q_4   H32Q    
label values h32q_5   H32Q    
label values h32q_6   H32Q    
label values h32r_1   H32R    
label values h32r_2   H32R    
label values h32r_3   H32R    
label values h32r_4   H32R    
label values h32r_5   H32R    
label values h32r_6   H32R    
label values h32s_1   H32S    
label values h32s_2   H32S    
label values h32s_3   H32S    
label values h32s_4   H32S    
label values h32s_5   H32S    
label values h32s_6   H32S    
label values h32t_1   H32T    
label values h32t_2   H32T    
label values h32t_3   H32T    
label values h32t_4   H32T    
label values h32t_5   H32T    
label values h32t_6   H32T    
label values h32u_1   H32U    
label values h32u_2   H32U    
label values h32u_3   H32U    
label values h32u_4   H32U    
label values h32u_5   H32U    
label values h32u_6   H32U    
label values h32v_1   H32V    
label values h32v_2   H32V    
label values h32v_3   H32V    
label values h32v_4   H32V    
label values h32v_5   H32V    
label values h32v_6   H32V    
label values h32w_1   H32W    
label values h32w_2   H32W    
label values h32w_3   H32W    
label values h32w_4   H32W    
label values h32w_5   H32W    
label values h32w_6   H32W    
label values h32x_1   H32X    
label values h32x_2   H32X    
label values h32x_3   H32X    
label values h32x_4   H32X    
label values h32x_5   H32X    
label values h32x_6   H32X    
label values h32y_1   H32Y    
label values h32y_2   H32Y    
label values h32y_3   H32Y    
label values h32y_4   H32Y    
label values h32y_5   H32Y    
label values h32y_6   H32Y    
label values h32z_1   H32Z    
label values h32z_2   H32Z    
label values h32z_3   H32Z    
label values h32z_4   H32Z    
label values h32z_5   H32Z    
label values h32z_6   H32Z    
label values h37a_1   H37A    
label values h37a_2   H37A    
label values h37a_3   H37A    
label values h37a_4   H37A    
label values h37a_5   H37A    
label values h37a_6   H37A    
label values h37b_1   H37B    
label values h37b_2   H37B    
label values h37b_3   H37B    
label values h37b_4   H37B    
label values h37b_5   H37B    
label values h37b_6   H37B    
label values h37c_1   H37C    
label values h37c_2   H37C    
label values h37c_3   H37C    
label values h37c_4   H37C    
label values h37c_5   H37C    
label values h37c_6   H37C    
label values h37d_1   H37D    
label values h37d_2   H37D    
label values h37d_3   H37D    
label values h37d_4   H37D    
label values h37d_5   H37D    
label values h37d_6   H37D    
label values h37e_1   H37E    
label values h37e_2   H37E    
label values h37e_3   H37E    
label values h37e_4   H37E    
label values h37e_5   H37E    
label values h37e_6   H37E    
label values h37f_1   H37F    
label values h37f_2   H37F    
label values h37f_3   H37F    
label values h37f_4   H37F    
label values h37f_5   H37F    
label values h37f_6   H37F    
label values h37g_1   H37G    
label values h37g_2   H37G    
label values h37g_3   H37G    
label values h37g_4   H37G    
label values h37g_5   H37G    
label values h37g_6   H37G    
label values h37h_1   H37H    
label values h37h_2   H37H    
label values h37h_3   H37H    
label values h37h_4   H37H    
label values h37h_5   H37H    
label values h37h_6   H37H    
label values h37i_1   H37I    
label values h37i_2   H37I    
label values h37i_3   H37I    
label values h37i_4   H37I    
label values h37i_5   H37I    
label values h37i_6   H37I    
label values h37j_1   H37J    
label values h37j_2   H37J    
label values h37j_3   H37J    
label values h37j_4   H37J    
label values h37j_5   H37J    
label values h37j_6   H37J    
label values h37k_1   H37K    
label values h37k_2   H37K    
label values h37k_3   H37K    
label values h37k_4   H37K    
label values h37k_5   H37K    
label values h37k_6   H37K    
label values h37l_1   H37L    
label values h37l_2   H37L    
label values h37l_3   H37L    
label values h37l_4   H37L    
label values h37l_5   H37L    
label values h37l_6   H37L    
label values h37m_1   H37M    
label values h37m_2   H37M    
label values h37m_3   H37M    
label values h37m_4   H37M    
label values h37m_5   H37M    
label values h37m_6   H37M    
label values h37n_1   H37N    
label values h37n_2   H37N    
label values h37n_3   H37N    
label values h37n_4   H37N    
label values h37n_5   H37N    
label values h37n_6   H37N    
label values h37o_1   H37O    
label values h37o_2   H37O    
label values h37o_3   H37O    
label values h37o_4   H37O    
label values h37o_5   H37O    
label values h37o_6   H37O    
label values h37p_1   H37P    
label values h37p_2   H37P    
label values h37p_3   H37P    
label values h37p_4   H37P    
label values h37p_5   H37P    
label values h37p_6   H37P    
label values h37x_1   H37X    
label values h37x_2   H37X    
label values h37x_3   H37X    
label values h37x_4   H37X    
label values h37x_5   H37X    
label values h37x_6   H37X    
label values h37y_1   H37Y    
label values h37y_2   H37Y    
label values h37y_3   H37Y    
label values h37y_4   H37Y    
label values h37y_5   H37Y    
label values h37y_6   H37Y    
label values h37z_1   H37Z    
label values h37z_2   H37Z    
label values h37z_3   H37Z    
label values h37z_4   H37Z    
label values h37z_5   H37Z    
label values h37z_6   H37Z    
label values h46a_1   H46A    
label values h46a_2   H46A    
label values h46a_3   H46A    
label values h46a_4   H46A    
label values h46a_5   H46A    
label values h46a_6   H46A    
label values h46b_1   H46B    
label values h46b_2   H46B    
label values h46b_3   H46B    
label values h46b_4   H46B    
label values h46b_5   H46B    
label values h46b_6   H46B    
label values h47_1    H47     
label values h47_2    H47     
label values h47_3    H47     
label values h47_4    H47     
label values h47_5    H47     
label values h47_6    H47     
label values v803     V803    
label values v811     V811    
label values v812     V812    
label values v813     V813    
label values v814     V814    
label values v815a    V815A   
label values v815b    V815B   
label values v815c    V815C   
label values ml0_1    ML0     
label values ml0_2    ML0     
label values ml0_3    ML0     
label values ml0_4    ML0     
label values ml0_5    ML0     
label values ml0_6    ML0     
label values ml1_1    ML1     
label values ml1_2    ML1     
label values ml1_3    ML1     
label values ml1_4    ML1     
label values ml1_5    ML1     
label values ml1_6    ML1     
label values ml2_1    ML2     
label values ml2_2    ML2     
label values ml2_3    ML2     
label values ml2_4    ML2     
label values ml2_5    ML2     
label values ml2_6    ML2     
label values ml11_1   ML11    
label values ml11_2   ML11    
label values ml11_3   ML11    
label values ml11_4   ML11    
label values ml11_5   ML11    
label values ml11_6   ML11    
label values ml12_1   ML12    
label values ml12_2   ML12    
label values ml12_3   ML12    
label values ml12_4   ML12    
label values ml12_5   ML12    
label values ml12_6   ML12    
label values ml13a_1  ML13A   
label values ml13a_2  ML13A   
label values ml13a_3  ML13A   
label values ml13a_4  ML13A   
label values ml13a_5  ML13A   
label values ml13a_6  ML13A   
label values ml13b_1  ML13B   
label values ml13b_2  ML13B   
label values ml13b_3  ML13B   
label values ml13b_4  ML13B   
label values ml13b_5  ML13B   
label values ml13b_6  ML13B   
label values ml13c_1  ML13C   
label values ml13c_2  ML13C   
label values ml13c_3  ML13C   
label values ml13c_4  ML13C   
label values ml13c_5  ML13C   
label values ml13c_6  ML13C   
label values ml13d_1  ML13D   
label values ml13d_2  ML13D   
label values ml13d_3  ML13D   
label values ml13d_4  ML13D   
label values ml13d_5  ML13D   
label values ml13d_6  ML13D   
label values ml13e_1  ML13E   
label values ml13e_2  ML13E   
label values ml13e_3  ML13E   
label values ml13e_4  ML13E   
label values ml13e_5  ML13E   
label values ml13e_6  ML13E   
label values ml13f_1  ML13F   
label values ml13f_2  ML13F   
label values ml13f_3  ML13F   
label values ml13f_4  ML13F   
label values ml13f_5  ML13F   
label values ml13f_6  ML13F   
label values ml13g_1  ML13G   
label values ml13g_2  ML13G   
label values ml13g_3  ML13G   
label values ml13g_4  ML13G   
label values ml13g_5  ML13G   
label values ml13g_6  ML13G   
label values ml13h_1  ML13H   
label values ml13h_2  ML13H   
label values ml13h_3  ML13H   
label values ml13h_4  ML13H   
label values ml13h_5  ML13H   
label values ml13h_6  ML13H   
label values ml13i_1  ML13I   
label values ml13i_2  ML13I   
label values ml13i_3  ML13I   
label values ml13i_4  ML13I   
label values ml13i_5  ML13I   
label values ml13i_6  ML13I   
label values ml13j_1  ML13J   
label values ml13j_2  ML13J   
label values ml13j_3  ML13J   
label values ml13j_4  ML13J   
label values ml13j_5  ML13J   
label values ml13j_6  ML13J   
label values ml13k_1  ML13K   
label values ml13k_2  ML13K   
label values ml13k_3  ML13K   
label values ml13k_4  ML13K   
label values ml13k_5  ML13K   
label values ml13k_6  ML13K   
label values ml13l_1  ML13L   
label values ml13l_2  ML13L   
label values ml13l_3  ML13L   
label values ml13l_4  ML13L   
label values ml13l_5  ML13L   
label values ml13l_6  ML13L   
label values ml13m_1  ML13M   
label values ml13m_2  ML13M   
label values ml13m_3  ML13M   
label values ml13m_4  ML13M   
label values ml13m_5  ML13M   
label values ml13m_6  ML13M   
label values ml13n_1  ML13N   
label values ml13n_2  ML13N   
label values ml13n_3  ML13N   
label values ml13n_4  ML13N   
label values ml13n_5  ML13N   
label values ml13n_6  ML13N   
label values ml13o_1  ML13O   
label values ml13o_2  ML13O   
label values ml13o_3  ML13O   
label values ml13o_4  ML13O   
label values ml13o_5  ML13O   
label values ml13o_6  ML13O   
label values ml13p_1  ML13P   
label values ml13p_2  ML13P   
label values ml13p_3  ML13P   
label values ml13p_4  ML13P   
label values ml13p_5  ML13P   
label values ml13p_6  ML13P   
label values ml13x_1  ML13X   
label values ml13x_2  ML13X   
label values ml13x_3  ML13X   
label values ml13x_4  ML13X   
label values ml13x_5  ML13X   
label values ml13x_6  ML13X   
label values ml13y_1  ML13Y   
label values ml13y_2  ML13Y   
label values ml13y_3  ML13Y   
label values ml13y_4  ML13Y   
label values ml13y_5  ML13Y   
label values ml13y_6  ML13Y   
label values ml13z_1  ML13Z   
label values ml13z_2  ML13Z   
label values ml13z_3  ML13Z   
label values ml13z_4  ML13Z   
label values ml13z_5  ML13Z   
label values ml13z_6  ML13Z   
label values ml14a_1  ML14A   
label values ml14a_2  ML14A   
label values ml14a_3  ML14A   
label values ml14a_4  ML14A   
label values ml14a_5  ML14A   
label values ml14a_6  ML14A   
label values ml14b_1  ML14B   
label values ml14b_2  ML14B   
label values ml14b_3  ML14B   
label values ml14b_4  ML14B   
label values ml14b_5  ML14B   
label values ml14b_6  ML14B   
label values ml14y_1  ML14Y   
label values ml14y_2  ML14Y   
label values ml14y_3  ML14Y   
label values ml14y_4  ML14Y   
label values ml14y_5  ML14Y   
label values ml14y_6  ML14Y   
label values ml14z_1  ML14Z   
label values ml14z_2  ML14Z   
label values ml14z_3  ML14Z   
label values ml14z_4  ML14Z   
label values ml14z_5  ML14Z   
label values ml14z_6  ML14Z   
label values ml15a_1  ML15A   
label values ml15a_2  ML15A   
label values ml15a_3  ML15A   
label values ml15a_4  ML15A   
label values ml15a_5  ML15A   
label values ml15a_6  ML15A   
label values ml15b_1  ML15B   
label values ml15b_2  ML15B   
label values ml15b_3  ML15B   
label values ml15b_4  ML15B   
label values ml15b_5  ML15B   
label values ml15b_6  ML15B   
label values ml15c_1  ML15C   
label values ml15c_2  ML15C   
label values ml15c_3  ML15C   
label values ml15c_4  ML15C   
label values ml15c_5  ML15C   
label values ml15c_6  ML15C   
label values ml16a_1  ML16A   
label values ml16a_2  ML16A   
label values ml16a_3  ML16A   
label values ml16a_4  ML16A   
label values ml16a_5  ML16A   
label values ml16a_6  ML16A   
label values ml16b_1  ML16B   
label values ml16b_2  ML16B   
label values ml16b_3  ML16B   
label values ml16b_4  ML16B   
label values ml16b_5  ML16B   
label values ml16b_6  ML16B   
label values ml16c_1  ML16C   
label values ml16c_2  ML16C   
label values ml16c_3  ML16C   
label values ml16c_4  ML16C   
label values ml16c_5  ML16C   
label values ml16c_6  ML16C   
label values ml17a_1  ML17A   
label values ml17a_2  ML17A   
label values ml17a_3  ML17A   
label values ml17a_4  ML17A   
label values ml17a_5  ML17A   
label values ml17a_6  ML17A   
label values ml17b_1  ML17B   
label values ml17b_2  ML17B   
label values ml17b_3  ML17B   
label values ml17b_4  ML17B   
label values ml17b_5  ML17B   
label values ml17b_6  ML17B   
label values ml17c_1  ML17C   
label values ml17c_2  ML17C   
label values ml17c_3  ML17C   
label values ml17c_4  ML17C   
label values ml17c_5  ML17C   
label values ml17c_6  ML17C   
label values ml18a_1  ML18A   
label values ml18a_2  ML18A   
label values ml18a_3  ML18A   
label values ml18a_4  ML18A   
label values ml18a_5  ML18A   
label values ml18a_6  ML18A   
label values ml18b_1  ML18B   
label values ml18b_2  ML18B   
label values ml18b_3  ML18B   
label values ml18b_4  ML18B   
label values ml18b_5  ML18B   
label values ml18b_6  ML18B   
label values ml18c_1  ML18C   
label values ml18c_2  ML18C   
label values ml18c_3  ML18C   
label values ml18c_4  ML18C   
label values ml18c_5  ML18C   
label values ml18c_6  ML18C   
label values ml19a_1  ML19A   
label values ml19a_2  ML19A   
label values ml19a_3  ML19A   
label values ml19a_4  ML19A   
label values ml19a_5  ML19A   
label values ml19a_6  ML19A   
label values ml19b_1  ML19B   
label values ml19b_2  ML19B   
label values ml19b_3  ML19B   
label values ml19b_4  ML19B   
label values ml19b_5  ML19B   
label values ml19b_6  ML19B   
label values ml19c_1  ML19C   
label values ml19c_2  ML19C   
label values ml19c_3  ML19C   
label values ml19c_4  ML19C   
label values ml19c_5  ML19C   
label values ml19c_6  ML19C   
label values ml19d_1  ML19D   
label values ml19d_2  ML19D   
label values ml19d_3  ML19D   
label values ml19d_4  ML19D   
label values ml19d_5  ML19D   
label values ml19d_6  ML19D   
label values ml19e_1  ML19E   
label values ml19e_2  ML19E   
label values ml19e_3  ML19E   
label values ml19e_4  ML19E   
label values ml19e_5  ML19E   
label values ml19e_6  ML19E   
label values ml19f_1  ML19F   
label values ml19f_2  ML19F   
label values ml19f_3  ML19F   
label values ml19f_4  ML19F   
label values ml19f_5  ML19F   
label values ml19f_6  ML19F   
label values ml19x_1  ML19X   
label values ml19x_2  ML19X   
label values ml19x_3  ML19X   
label values ml19x_4  ML19X   
label values ml19x_5  ML19X   
label values ml19x_6  ML19X   
label values ml19y_1  ML19Y   
label values ml19y_2  ML19Y   
label values ml19y_3  ML19Y   
label values ml19y_4  ML19Y   
label values ml19y_5  ML19Y   
label values ml19y_6  ML19Y   
label values ml19z_1  ML19Z   
label values ml19z_2  ML19Z   
label values ml19z_3  ML19Z   
label values ml19z_4  ML19Z   
label values ml19z_5  ML19Z   
label values ml19z_6  ML19Z   
label values ml20a_1  ML20A   
label values ml20a_2  ML20A   
label values ml20a_3  ML20A   
label values ml20a_4  ML20A   
label values ml20a_5  ML20A   
label values ml20a_6  ML20A   
label values ml20b_1  ML20B   
label values ml20b_2  ML20B   
label values ml20b_3  ML20B   
label values ml20b_4  ML20B   
label values ml20b_5  ML20B   
label values ml20b_6  ML20B   
label values ml20c_1  ML20C   
label values ml20c_2  ML20C   
label values ml20c_3  ML20C   
label values ml20c_4  ML20C   
label values ml20c_5  ML20C   
label values ml20c_6  ML20C   
label values ml21a_1  ML21A   
label values ml21a_2  ML21A   
label values ml21a_3  ML21A   
label values ml21a_4  ML21A   
label values ml21a_5  ML21A   
label values ml21a_6  ML21A   
label values ml21b_1  ML21B   
label values ml21b_2  ML21B   
label values ml21b_3  ML21B   
label values ml21b_4  ML21B   
label values ml21b_5  ML21B   
label values ml21b_6  ML21B   
label values ml21c_1  ML21C   
label values ml21c_2  ML21C   
label values ml21c_3  ML21C   
label values ml21c_4  ML21C   
label values ml21c_5  ML21C   
label values ml21c_6  ML21C   
label values ml22a_1  ML22A   
label values ml22a_2  ML22A   
label values ml22a_3  ML22A   
label values ml22a_4  ML22A   
label values ml22a_5  ML22A   
label values ml22a_6  ML22A   
label values ml22b_1  ML22B   
label values ml22b_2  ML22B   
label values ml22b_3  ML22B   
label values ml22b_4  ML22B   
label values ml22b_5  ML22B   
label values ml22b_6  ML22B   
label values ml22c_1  ML22C   
label values ml22c_2  ML22C   
label values ml22c_3  ML22C   
label values ml22c_4  ML22C   
label values ml22c_5  ML22C   
label values ml22c_6  ML22C   
label values ml23a_1  ML23A   
label values ml23a_2  ML23A   
label values ml23a_3  ML23A   
label values ml23a_4  ML23A   
label values ml23a_5  ML23A   
label values ml23a_6  ML23A   
label values ml23b_1  ML23B   
label values ml23b_2  ML23B   
label values ml23b_3  ML23B   
label values ml23b_4  ML23B   
label values ml23b_5  ML23B   
label values ml23b_6  ML23B   
label values ml23c_1  ML23C   
label values ml23c_2  ML23C   
label values ml23c_3  ML23C   
label values ml23c_4  ML23C   
label values ml23c_5  ML23C   
label values ml23c_6  ML23C   
label values ml24c_1  ML24C   
label values ml24c_2  ML24C   
label values ml24c_3  ML24C   
label values ml24c_4  ML24C   
label values ml24c_5  ML24C   
label values ml24c_6  ML24C   
label values s411a_1  S411A   
label values s411a_2  S411A   
label values s411a_3  S411A   
label values s411a_4  S411A   
label values s411a_5  S411A   
label values s411a_6  S411A   
label values s411b_1  S411B   
label values s411b_2  S411B   
label values s411b_3  S411B   
label values s411b_4  S411B   
label values s411b_5  S411B   
label values s411b_6  S411B   
label values s411c_1  S411C   
label values s411c_2  S411C   
label values s411c_3  S411C   
label values s411c_4  S411C   
label values s411c_5  S411C   
label values s411c_6  S411C   
label values ml25a_1  ML25A   
label values ml25a_2  ML25A   
label values ml25a_3  ML25A   
label values ml25a_4  ML25A   
label values ml25a_5  ML25A   
label values ml25a_6  ML25A   
label values s412b_1  S412B   
label values s412b_2  S412B   
label values s412b_3  S412B   
label values s412b_4  S412B   
label values s412b_5  S412B   
label values s412b_6  S412B   
label values scounty  SCOUNTY 
label values szone    SZONE   
label values slang    SLANG   
label values slangint SLANGINT
label values stransl  STRANSL 
label values s105     S105    
label values s111     S111    
label values s112a    S112A   
label values s112b    S112B   
label values s112c    S112C   
label values s112d    S112D   
label values s112e    S112E   
label values s112f    S112F   
label values s427b    S427B   
label values s427c    S427C   
label values s427d    S427D   
label values s427e    S427E   
label values s427f1   S427F1  
label values s427f2   S427F2  
label values s427f3   S427F3  
label values s427f4   S427F4  
label values s427f5   S427F5  
label values s427f6   S427F6  
label values s427f7   S427F7  
label values s427f8   S427F8  
label values s427f9   S427F9  
label values sv112e   SV112E  
label values sv112g   SV112G  
label values sv112h   SV112H  
label values sv112i   SV112I  
label values sv112j   SV112J  
label values sv112k   SV112K  
label values sv112l   SV112L  
label values sv112m   SV112M  
label values sv112n   SV112N  
label values sv112o   SV112O  
label values sv112p   SV112P  
