infile using "C:\USERS\21429\ICF\DATA ARCHIVE - DOCUMENTS\EXPORT MENU\GH8C\GHGR8CFL.dct"

label variable caseid   "Case identification"
label variable pidx     "Pregnancy column number"
label variable v000     "Country code and phase"
label variable v001     "Cluster number"
label variable v002     "Household number"
label variable v003     "Respondent's line number"
label variable v004     "Ultimate area unit"
label variable v005     "Women's individual sample weight (6 decimals)"
label variable v006     "Month of interview"
label variable v007     "Year of interview"
label variable v008     "Date of interview (CMC)"
label variable v008a    "Date of interview Century Day Code (CDC)"
label variable v009     "Respondent's month of birth"
label variable v010     "Respondent's year of birth"
label variable v011     "Date of birth (CMC)"
label variable v012     "Respondent's current age"
label variable v013     "Age in 5-year groups"
label variable v014     "Completeness of age information"
label variable v015     "Result of individual interview"
label variable v016     "Day of interview"
label variable v017     "CMC start of calendar"
label variable v018     "Row of month of interview"
label variable v019     "Length of calendar"
label variable v019a    "Number of calendar columns"
label variable v020     "Ever-married sample"
label variable v021     "Primary sampling unit"
label variable v022     "Sample strata for sampling errors"
label variable v023     "Stratification used in sample design"
label variable v024     "Region"
label variable v025     "Type of place of residence"
label variable v026     "NA - De facto place of residence"
label variable v027     "Number of visits"
label variable v028     "Interviewer identification"
label variable v029     "NA - Keyer identification"
label variable v030     "Field supervisor"
label variable v031     "NA - Field editor"
label variable v032     "NA - Office editor"
label variable v034     "Line number of husband"
label variable v040     "Cluster altitude in meters"
label variable v042     "Household selected for hemoglobin"
label variable v044     "Selected for Domestic Violence module"
label variable v045a    "Language of questionnaire"
label variable v045b    "Language of interview"
label variable v045c    "Native language of respondent"
label variable v046     "Translator used"
label variable v047     "Team number"
label variable v048     "NA - Team supervisor"
label variable v101     "Region"
label variable v102     "Type of place of residence"
label variable v103     "NA - Childhood place of residence"
label variable v104     "Years lived in place of residence"
label variable v105     "Type of place of previous residence"
label variable v105a    "Region of previous residence"
label variable v106     "Highest educational level"
label variable v107     "Highest year of education"
label variable v113     "Source of drinking water"
label variable v115     "Time to get to water source"
label variable v116     "Type of toilet facility"
label variable v119     "Household has: electricity"
label variable v120     "Household has: radio"
label variable v121     "Household has: television"
label variable v122     "Household has: refrigerator"
label variable v123     "Household has: bicycle"
label variable v124     "Household has: motorcycle/scooter"
label variable v125     "Household has: car/truck"
label variable v127     "Main floor material"
label variable v128     "Main wall material"
label variable v129     "Main roof material"
label variable v130     "Religion"
label variable v131     "Ethnicity"
label variable v133     "Education in single years"
label variable v134     "NA - De facto place of residence"
label variable v135     "Usual resident or visitor"
label variable v136     "Number of household members (listed)"
label variable v137     "Number of children 5 and under in household (de jure)"
label variable v138     "Number of eligible women in household (de facto)"
label variable v139     "De jure region of residence"
label variable v140     "De jure type of place of residence"
label variable v141     "NA - De jure place of residence"
label variable v149     "Educational attainment"
label variable v150     "Relationship to household head"
label variable v151     "Sex of household head"
label variable v152     "Age of household head"
label variable v153     "Household has: telephone (land-line)"
label variable awfactt  "All woman factor - total"
label variable awfactu  "All woman factor - urban/rural"
label variable awfactr  "All woman factor - regional"
label variable awfacte  "All woman factor - educational"
label variable awfactw  "All woman factor - wealth index"
label variable v155     "Literacy"
label variable v156     "NA - Ever participated in a literacy program outside of primary"
label variable v157     "Frequency of reading newspaper or magazine"
label variable v158     "Frequency of listening to radio"
label variable v159     "Frequency of watching television"
label variable v160     "Toilet facilities shared with other households"
label variable v161     "Type of cooking fuel"
label variable v166     "Result of salt test for iodine"
label variable v167     "NA - Number of trips in last 12 months"
label variable v168     "NA - Away for more than one month in last 12 months"
label variable v169a    "Owns a mobile telephone"
label variable v169b    "Last 12 months use mobile telephone for financial transactions"
label variable v169c    "Is respondent's mobile phone a smart phone"
label variable v170     "Has an account in a bank or other financial institution"
label variable v171a    "Use of internet"
label variable v171b    "Frequency of using internet last month"
label variable v172     "Respondent state of birth"
label variable v173     "Respondent country of birth"
label variable v174m    "Month move to current place of residence"
label variable v174y    "Year move to current place of residence"
label variable v175     "Reason for moving to current place of residence"
label variable v176     "Self reported health status"
label variable v177     "Money put/taken from bank account last 12 months"
label variable v190     "Wealth index combined"
label variable v191     "Wealth index factor score combined (5 decimals)"
label variable v190a    "Wealth index for urban/rural"
label variable v191a    "Wealth index factor score for urban/rural (5 decimals)"
label variable ml101    "Type of mosquito bed net(s) slept under last night"
label variable v201     "Total children ever born"
label variable v202     "Sons at home"
label variable v203     "Daughters at home"
label variable v204     "Sons elsewhere"
label variable v205     "Daughters elsewhere"
label variable v206     "Sons who have died"
label variable v207     "Daughters who have died"
label variable v208     "Births in last five years"
label variable v209     "Births in past year"
label variable v210     "Births in month of interview"
label variable v211     "Date of first birth (CMC)"
label variable v212     "Age of respondent at 1st birth"
label variable v213     "Currently pregnant"
label variable v214     "Duration of current pregnancy in months"
label variable v214a    "Duration of current pregnancy original"
label variable v215     "Time since last menstrual period"
label variable v216     "Menstruated in last six weeks"
label variable v217     "Knowledge of ovulatory cycle"
label variable v218     "Number of living children"
label variable v219     "Living children + current pregnancy"
label variable v220     "Living children + current pregnancy (grouped)"
label variable v221     "Marriage to first birth interval (months)"
label variable v222     "Last birth to interview (months)"
label variable v223     "Completeness of current pregnancy information"
label variable v224     "Entries in birth history"
label variable v225     "Current pregnancy wanted"
label variable v226     "Time since last period (comp) (months)"
label variable v227     "Flag for last period"
label variable v228     "Ever had a terminated pregnancy"
label variable v229     "Month pregnancy ended"
label variable v230     "Year pregnancy ended"
label variable v231     "CMC pregnancy ended"
label variable v232     "Completeness of last termination information"
label variable v233     "Months when pregnancy ended"
label variable v234     "Other such pregnancies"
label variable v235     "Index last child prior to maternity-health (calendar)"
label variable v237     "Birth between last and interview"
label variable v238     "Births in last three years"
label variable v239     "Pregnancies terminated before calendar beginning"
label variable v240     "Month of last termination prior to calendar"
label variable v241     "Year of last termination prior to calendar"
label variable v242     "CMC termination ended prior to calendar"
label variable v243     "Completeness of last termination date prior to calendar"
label variable v244     "Can women get pregnant after birth and before period"
label variable v245     "Pregnancy losses"
label variable v246     "Entries in pregnancy history"
label variable v247a    "Collection of menstrual blood: reusable sanitary pads"
label variable v247b    "Collection of menstrual blood: disposable sanitary pads"
label variable v247c    "Collection of menstrual blood: tampons"
label variable v247d    "Collection of menstrual blood: menstrual cup"
label variable v247e    "Collection of menstrual blood: cloth"
label variable v247f    "Collection of menstrual blood: toilet paper"
label variable v247g    "Collection of menstrual blood: cotton wool"
label variable v247h    "Collection of menstrual blood: underwear only"
label variable v247i    "NA - Collection of menstrual blood: CS"
label variable v247j    "NA - Collection of menstrual blood: CS"
label variable v247k    "NA - Collection of menstrual blood: CS"
label variable v247l    "NA - Collection of menstrual blood: CS"
label variable v247x    "Collection of menstrual blood: other"
label variable v247y    "Collection of menstrual blood: nothing"
label variable v248     "Able to change in privacy during last menstrual cycle"
label variable v249     "Age at first menstrual period"
label variable v310     "NA - Living children at first use"
label variable v311     "NA - Children at first use (grouped)"
label variable v312     "Current contraceptive method"
label variable v313     "Current use by method type"
label variable v315     "Month of start of use of method"
label variable v316     "Year of start of use of method"
label variable v317     "Date of start of use of method (CMC)"
label variable v318     "Completeness of information"
label variable v319     "Years since sterilization"
label variable v320     "Age at sterilization"
label variable v321     "Years since first union at sterilization"
label variable v321a    "Years since current union at sterilization"
label variable v322     "Parity at sterilization"
label variable v323     "Brand of pill used"
label variable v323a    "Brand of condom used"
label variable v325a    "NA - Cost of current method (in CURRENCY)"
label variable v326     "Last source for current users"
label variable v327     "Last source for users by type"
label variable v337     "Months of use of current method"
label variable v359     "Last method discontinued in last 5 years"
label variable v360     "Reason of last discontinuation"
label variable v361     "Pattern of use"
label variable v362     "Intention to use"
label variable v363     "NA - Preferred future method"
label variable v364     "Contraceptive use and intention"
label variable v367     "Wanted last child"
label variable v367a    "Wanted last pregnancy"
label variable v372     "NA - Shown pill package"
label variable v372a    "NA - Shown condom package"
label variable v375a    "NA - Main reason not using a method"
label variable v376     "NA - Main reason not to use a method"
label variable v376a    "NA - Would ever use method if married"
label variable v379     "Source known for any method"
label variable v380     "Source known for any method"
label variable v384a    "Heard family planning on radio last few months"
label variable v384b    "Heard family planning on TV last few months"
label variable v384c    "Heard family planning in newspaper/magazine last few months"
label variable v384d    "Heard family planning by text messages on mobile phone"
label variable v384e    "Seen about family planning on facebook, twitter, instagram, others"
label variable v384f    "Seen about family planning on poster, brochure"
label variable v384g    "Seen about family planning on outdoor sign, billboard"
label variable v384h    "Heard family planning at community meetings events"
label variable v384i    "NA - Heard/seen family planning CS"
label variable v384j    "NA - Heard/seen family planning CS"
label variable v384k    "NA - Heard/seen family planning CS"
label variable v393     "Visited by fieldworker in last 12 months"
label variable v393a    "Did fieldworker talk about family planning"
label variable v394     "Visited health facility last 12 months"
label variable v395     "At health facility, told of family planning"
label variable v3a00a   "NA - Source of family planning for non-users: government hospital"
label variable v3a00b   "NA - Source of family planning for non-users: CS public sector"
label variable v3a00c   "NA - Source of family planning for non-users: CS public sector"
label variable v3a00d   "NA - Source of family planning for non-users: CS public sector"
label variable v3a00e   "NA - Source of family planning for non-users: CS public sector"
label variable v3a00f   "NA - Source of family planning for non-users: CS public sector"
label variable v3a00g   "NA - Source of family planning for non-users: CS public sector"
label variable v3a00h   "NA - Source of family planning for non-users: CS public sector"
label variable v3a00i   "NA - Source of family planning for non-users: CS public sector"
label variable v3a00j   "NA - Source of family planning for non-users: private hospital/clinic"
label variable v3a00k   "NA - Source of family planning for non-users: pharmacy"
label variable v3a00l   "NA - Source of family planning for non-users: private doctor"
label variable v3a00m   "NA - Source of family planning for non-users: CS private sector"
label variable v3a00n   "NA - Source of family planning for non-users: CS private sector"
label variable v3a00o   "NA - Source of family planning for non-users: CS private sector"
label variable v3a00p   "NA - Source of family planning for non-users: CS private sector"
label variable v3a00q   "NA - Source of family planning for non-users: CS private sector"
label variable v3a00r   "NA - Source of family planning for non-users: CS private sector"
label variable v3a00s   "NA - Source of family planning for non-users: CS other"
label variable v3a00t   "NA - Source of family planning for non-users: CS other"
label variable v3a00u   "NA - Source of family planning for non-users: CS other"
label variable v3a00v   "NA - Source of family planning for non-users: CS other"
label variable v3a00w   "NA - Source of family planning for non-users: CS other"
label variable v3a00x   "NA - Source of family planning for non-users: other"
label variable v3a00y   "Source of family planning for non-users: no source"
label variable v3a00z   "Source of family planning for non-users: any source"
label variable v3a01    "NA - Told sterilization would mean no more children"
label variable v3a02    "Told about side effects"
label variable v3a03    "NA - Told about side effects by health or family planning worker"
label variable v3a04    "Told how to deal with side effects"
label variable v3a05    "Told about other family planning methods"
label variable v3a06    "NA - Told about other family planning methods by health or family planning worke"
label variable v3a07    "First source for current method"
label variable v3a08a   "Reason not using: not married"
label variable v3a08b   "Reason not using: not having sex"
label variable v3a08c   "Reason not using: infrequent sex"
label variable v3a08d   "Reason not using: menopausal/hysterectomy"
label variable v3a08e   "Reason not using: subfecund/infecund"
label variable v3a08f   "Reason not using: postpartum amenorrheic"
label variable v3a08g   "Reason not using: breastfeeding"
label variable v3a08h   "Reason not using: fatalistic"
label variable v3a08i   "Reason not using: respondent opposed"
label variable v3a08j   "Reason not using: husband/partner opposed"
label variable v3a08k   "Reason not using: others opposed"
label variable v3a08l   "Reason not using: religious prohibition"
label variable v3a08m   "Reason not using: knows no method"
label variable v3a08n   "Reason not using: knows no source"
label variable v3a08o   "NA - Reason not using: health concerns"
label variable v3a08p   "Reason not using: other side effects"
label variable v3a08q   "Reason not using: lack of access/too far"
label variable v3a08r   "Reason not using: costs too much"
label variable v3a08s   "Reason not using: inconvenient to use"
label variable v3a08t   "Reason not using: interferes with body's processes"
label variable v3a08u   "Reason not using: preferred method not available"
label variable v3a08v   "Reason not using: no method available"
label variable v3a08w   "Reason not using: changes in menstrual bleeding"
label variable v3a08aa  "Reason not using: methods could cause infertitlity"
label variable v3a08ab  "NA - Reason not using: CS"
label variable v3a08ac  "NA - Reason not using: CS"
label variable v3a08ad  "NA - Reason not using: CS"
label variable v3a08ae  "NA - Reason not using: CS"
label variable v3a08af  "NA - Reason not using: CS"
label variable v3a08x   "Reason not using: other"
label variable v3a08z   "Reason not using: don't know"
label variable v3a09a   "NA - How many pill cycles did get last time"
label variable v3a09b   "NA - How many condoms did get last time"
label variable v3a10    "Probe for respondent/partner sterilized"
label variable v3a11    "Type of injectable based on picture observation"
label variable v3a12    "Person who injected last time"
label variable v3a13    "Used emergency contraception in past 12 months"
label variable v3a14    "Could switch method if wanted/needed"
label variable v401     "Last birth a caesarean section"
label variable v404     "Currently breastfeeding"
label variable v405     "Currently amenorrheic"
label variable v406     "Currently abstaining"
label variable v407     "NA - Number of times breastfed during night"
label variable v408     "NA - Number of times breastfed during day"
label variable v415     "Drank from bottle with nipple yesterday/last night"
label variable v416     "NA - Heard of oral rehydration"
label variable v417     "Entries in pregnancy and postnatal care roster"
label variable v418     "Entries in immunization roster"
label variable v418a    "Entries in child health roster"
label variable v419     "Entries in height/weight roster"
label variable v420     "Measurer's code"
label variable v421     "Assistant measurer's code"
label variable v426     "When child put to breast"
label variable v437     "Respondent's weight in kilograms (1 decimal)"
label variable v438     "Respondent's height in centimeters (1 decimal)"
label variable v445     "Body Mass Index"
label variable v447     "Result of measurement - height/weight"
label variable v446a    "Height/Age standard deviation (new WHO) (women age 15-19)"
label variable v446d    "BMI/Age standard deviation (new WHO) (women age 15-19)"
label variable v447a    "Women's age in years (from household questionnaire)"
label variable v452a    "Under age 18 (from household questionnaire)"
label variable v452b    "Line number of parent/caretaker"
label variable v452c    "Read consent statement - hemoglobin"
label variable v453     "Hemoglobin level (g/dl - 1 decimal)"
label variable v454     "Currently pregnant (from household questionnaire)"
label variable v455     "Result of measurement - hemoglobin"
label variable v456     "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable v457     "Anemia level"
label variable v458     "NA - Agrees to referral - anemia"
label variable v459     "Have mosquito bed net for sleeping (from household questionnaire)"
label variable v460     "Children under 5 slept under mosquito bed net last night (household questionnair"
label variable v461     "Respondent slept under mosquito bed net"
label variable v462     "NA - Washed hands before preparing last meal"
label variable v463a    "Smokes cigarettes"
label variable v463b    "Smokes pipe full of tobacco"
label variable v463c    "Chews tobacco"
label variable v463d    "Snuffs by nose"
label variable v463e    "Smokes kreteks"
label variable v463f    "Smokes cigars, cheroots or cigarillos"
label variable v463g    "Smokes water pipe"
label variable v463h    "Snuff by mouth"
label variable v463i    "Chews betel quid with tobacco"
label variable v463j    "NA - Smokes/uses country specific"
label variable v463k    "NA - Smokes/uses country specific"
label variable v463l    "NA - Smokes/uses country specific"
label variable v463x    "Smokes/uses other"
label variable v463z    "Does not use cigarettes and tobacco"
label variable v463aa   "Frequency smokes cigarettes"
label variable v463ab   "Frequency currently uses other type of tobacco"
label variable v464     "Number of cigarettes in last 24 hours"
label variable v466     "NA - When child is seriously ill, can decide whether medical treatment sought"
label variable v467a    "NA - Getting medical help for self: know where to go"
label variable v467b    "Getting medical help for self: getting permission to go"
label variable v467c    "Getting medical help for self: getting money needed for treatment"
label variable v467d    "Getting medical help for self: distance to health facility"
label variable v467e    "NA - Getting medical help for self: having to take transport"
label variable v467f    "Getting medical help for self: not wanting to go alone"
label variable v467g    "NA - Getting medical help for self: concern no female health provider"
label variable v467h    "NA - Getting medical help for self: concern no provider"
label variable v467i    "NA - Getting medical help for self: concern no drugs available"
label variable v467j    "NA - Getting medical help for self: CS"
label variable v467k    "NA - Getting medical help for self: CS"
label variable v467l    "NA - Getting medical help for self: CS"
label variable v467m    "NA - Getting medical help for self: CS"
label variable v468     "Record for Last Birth"
label variable v471a    "NA - Woman had tinned, powdered or fresh milk"
label variable v471b    "NA - Woman had tea or coffee"
label variable v471c    "Woman had any other liquid"
label variable v471cs   "Woman other liquid - sweetened"
label variable v471d    "Woman had sodas/malt/sports/energy drinks"
label variable v471e    "Woman had fruit juice, fruit-flavored drinks"
label variable v471f    "NA - Woman had CS liquid"
label variable v471g    "NA - Woman had CS liquid"
label variable v471h    "NA - Woman had CS liquid"
label variable v471i    "NA - Woman had CS liquid"
label variable v472a    "Woman had other vegetables"
label variable v472b    "Woman had sausages, hot dogs, frankfurters, ham, bacon, salami, canned food"
label variable v472c    "Woman had nuts, seeds"
label variable v472d    "Woman had any insects"
label variable v472e    "Woman had porridge, bread, rice, noodles, pasta"
label variable v472f    "Woman had plantains, white potatoes, yams, manioc cassava, or other tubers"
label variable v472g    "Woman had eggs"
label variable v472h    "Woman had any other meat (beef, pork, lamb, chicken, etc)"
label variable v472i    "Woman had pumpkin, carrots, squash, sweet potatoes (yellow or orange inside)"
label variable v472j    "Woman had any dark green leafy vegetables"
label variable v472k    "Woman had mangoes, papayas, other vitamin A fruits"
label variable v472l    "Woman had any other fruits"
label variable v472m    "Woman had liver, heart, other organs"
label variable v472n    "Woman had fish or shellfish"
label variable v472o    "Woman had food made from beans, peas, lentils"
label variable v472p    "Woman had cheese, yogurt, other milk products"
label variable v472q    "NA - Woman had oil, fats, butter, products made of them"
label variable v472r    "Woman had sweet foods, chocolates, candies, pastries, cakes, ice cream, etc"
label variable v472s    "Woman had any other food"
label variable v472t    "Woman had chips, crisps, french fries, fried dough, instant noodles"
label variable v472u    "Woman had red palm oil"
label variable v472v    "Woman had sweetened tea, coffee or herbal drinks"
label variable v472w    "Woman had sentinel sweet foods"
label variable v472wa   "NA - Woman had CS foods"
label variable v472wb   "NA - Woman had CS foods"
label variable v472wc   "NA - Woman had CS foods"
label variable v472wd   "NA - Woman had CS foods"
label variable v472we   "NA - Woman had CS foods"
label variable v473a    "NA - Read consent statement - HIV"
label variable v473b    "NA - Result of measurement - HIV"
label variable v477     "NA - Number of injections in last 12 months"
label variable v478     "NA - Number of injections administered by a health worker"
label variable v479     "NA - Place of injection by health worker"
label variable v480     "NA - Syringe and needle from new, unopened package"
label variable v481     "Covered by health insurance"
label variable v481a    "Health insurance type: mutual/community organization"
label variable v481b    "Health insurance type: provided by employer"
label variable v481c    "NA - Health insurance type: social security"
label variable v481d    "Health insurance type: private/commercially purchased"
label variable v481e    "Health insurance type: national/district health insurance"
label variable v481f    "NA - Health insurance type: CS"
label variable v481g    "NA - Health insurance type: CS"
label variable v481h    "NA - Health insurance type: CS"
label variable v481x    "Health insurance type: other"
label variable v482a    "NA - Arrange care of biological children under age 18"
label variable v482b    "NA - Primary caregiver of children under age 18"
label variable v482c    "NA - Arrange care of non-biological children < 18"
label variable v483a    "Minutes to nearest healthcare facility"
label variable v483b    "Mode of transportation to nearest healthcare facility"
label variable v484a    "Breasts examined for cancer by health care provider"
label variable v484b    "Ever tested for cervical cancer by health care provider"
label variable v485a    "Number of days respondent drank alcoholic drinks in the past month"
label variable v485b    "Number of alcoholic drinks per day"
label variable v501     "Current marital status"
label variable v502     "Currently/formerly/never in union"
label variable v503     "Number of unions"
label variable v504     "Currently residing with husband/partner"
label variable v505     "Number of other wives"
label variable v506     "Respondent's rank among wives"
label variable v507     "Month of first cohabitation"
label variable v508     "Year of first cohabitation"
label variable v509     "Date of first cohabitation (CMC)"
label variable v510     "Completeness of date information in V509"
label variable v511     "Age at first cohabitation"
label variable v507a    "Month of current cohabitation"
label variable v508a    "Year of current cohabitation"
label variable v509a    "Date of current cohabitation (CMC)"
label variable v510a    "Completeness of date information in V509A"
label variable v511a    "Age at current cohabitation"
label variable v512     "Years since first cohabitation"
label variable v513     "Cohabitation duration (grouped)"
label variable v525     "Age at first sex"
label variable v527     "Time since last sex"
label variable v528     "Time since last sex (in days)"
label variable v529     "Time since last sex (in months)"
label variable v530     "Flag for V529"
label variable v531     "Age at first sex (imputed)"
label variable v532     "Flag for V531"
label variable v535     "Ever been married or in union"
label variable v536     "Recent sexual activity"
label variable v537     "Months of abstinence"
label variable v538     "NA - How previous marriage or union ended"
label variable v539     "NA - Person who received most of late husband's property"
label variable v540     "NA - Respondent received any of late husband's assets or valuables"
label variable v541     "NA - Intends to wait until marriage to have sex"
label variable v542     "Has a marriage certificate for current marriage/union"
label variable v543a    "Marriage certificate from church, mosque or other religious institution"
label variable v543b    "Marriage certificatet from civil authority"
label variable v543c    "Other document from religious institution"
label variable v543d    "Other document from civil aouthority"
label variable v543e    "NA - Marriage document: CS"
label variable v543f    "NA - Marriage document: CS"
label variable v543g    "NA - Marriage document: CS"
label variable v543x    "Other marriage document:"
label variable v544     "Current marriage ever registered with civil authority"
label variable v602     "Fertility preference"
label variable v603     "Preferred waiting time for birth of a/another child"
label variable v604     "Preferred waiting time for birth of a/another child (grouped)"
label variable v605     "Desire for more children"
label variable v613     "Ideal number of children"
label variable v614     "Ideal number of children (grouped)"
label variable v616     "Time for future birth"
label variable v621     "Husband's desire for children"
label variable v623     "Exposure"
label variable v624     "Unmet need"
label variable v625     "Exposure (definition 2)"
label variable v626     "Unmet need (definition 2)"
label variable v625a    "Exposure to need for contraception (definition 3)"
label variable v626a    "Unmet need for contraception (definition 3)"
label variable v627     "Ideal number of boys"
label variable v628     "Ideal number of girls"
label variable v629     "Ideal number of either sex"
label variable v631     "NA - Problem if became pregnant"
label variable v632     "Decision maker for using contraception"
label variable v632a    "NA - Decision maker for not using contraception"
label variable v633a    "NA - Reason for not having sex: husband has STI"
label variable v633b    "Reason for not having sex: husband has other women"
label variable v633c    "NA - Reason for not having sex: recent birth"
label variable v633d    "NA - Reason for not having sex: tired, not in mood"
label variable v633e    "NA - Reason for not having sex: CS"
label variable v633f    "NA - Reason for not having sex: CS"
label variable v633g    "NA - Reason for not having sex: CS"
label variable v634     "NA - Husband knows that respondent is using contraception"
label variable v635     "Respondent opinion compared to husband's on use of contraception"
label variable v636     "Husband or family member pressured respondent to become pregnant"
label variable v701     "Husband/partner's education level"
label variable v702     "Husband/partner's highest year of education (at level in V701)"
label variable v704     "Husband/partner's occupation"
label variable v704a    "Husband/partner worked in last 7 days/12 months"
label variable v705     "Husband/partner's occupation (grouped)"
label variable v714     "Respondent currently working"
label variable v714a    "Respondent has a job, but currently absent"
label variable v715     "Husband/partner's total number of years of education"
label variable v716     "Respondent's occupation"
label variable v717     "Respondent's occupation (grouped)"
label variable v719     "Respondent works for family, others, self"
label variable v721     "NA - Respondent works at home or away"
label variable v729     "Husband/partner's educational attainment"
label variable v730     "Husband/partner's age"
label variable v731     "Respondent worked in last 12 months"
label variable v732     "Respondent employed all year/seasonal"
label variable v739     "Person who usually decides how to spend respondent's earnings"
label variable v740     "NA - Type of land where respondent works"
label variable v741     "Type of earnings from respondent's work"
label variable v743a    "Person who usually decides on: respondent's health care"
label variable v743b    "Person who usually decides on: large household purchases"
label variable v743c    "NA - Person who usually decides on: household purchases for daily needs"
label variable v743d    "Person who usually decides on: visits to family or relatives"
label variable v743e    "NA - Person who usually decides on: food to be cooked each day"
label variable v743f    "Person who usually decides on: what to do with money husband earns"
label variable v744a    "Beating justified if wife goes out without telling husband"
label variable v744b    "Beating justified if wife neglects the children"
label variable v744c    "Beating justified if wife argues with husband"
label variable v744d    "Beating justified if wife refuses to have sex with husband"
label variable v744e    "Beating justified if wife burns the food"
label variable v745a    "Owns a house alone or jointly"
label variable v745b    "Owns land alone or jointly"
label variable v745c    "Title deed on house own by respondent"
label variable v745d    "Title deed on land own by respondent"
label variable v746     "Respondent earns more than husband/partner"
label variable pidxb    "Index to birth history"
label variable pord     "Pregnancy order number"
label variable p0       "Pregnancy is multiple"
label variable p1       "Month of pregnancy outcome"
label variable p2       "Year of pregnancy outcome"
label variable p3       "Date of end of pregnancy (CMC)"
label variable p4       "Sex of child"
label variable p5       "Child is alive"
label variable p6       "Age at death"
label variable p7       "Age at death (months, imputed)"
label variable p8       "Current age of child"
label variable p9       "Child lives with whom"
label variable p10      "Completeness of information"
label variable p11      "Preceding pregnancy interval (months)"
label variable p12      "Succeeding pregnancy interval (months)"
label variable p13      "Flag for age at death"
label variable p15      "Other pregnancies between pregnancies"
label variable p16      "Child's line number in household"
label variable p17      "Day of pregnancy outcome"
label variable p18      "Century Day Code of end of pregnancy (CDC)"
label variable p19      "Months since pregnancy outcome"
label variable p20      "Duration of pregnancy in months"
label variable p21      "Duration of pregnancy"
label variable p30      "Pregnancy outcome declared by respondent"
label variable p31      "Baby cried, moved or breathed"
label variable p32      "Pregnancy outcome reclassified"
label variable midx     "Index to Birth History"
label variable midxp    "Index to Pregnancy History"
label variable m1       "Number of tetanus injections before birth"
label variable m1a      "Number of tetanus injections before pregnancy"
label variable m1b      "NA - Month of last tetanus injection before pregnancy"
label variable m1c      "NA - Year of last tetanus injection before pregnancy"
label variable m1d      "Years ago received last tetanus injection before pregnancy"
label variable m1e      "Last tetanus injection before pregnancy (CMC)"
label variable m2a      "Prenatal: doctor"
label variable m2b      "Prenatal: nurse/midwife"
label variable m2c      "NA - Prenatal: CS health professional"
label variable m2d      "NA - Prenatal: CS health professional"
label variable m2e      "NA - Prenatal: CS health professional"
label variable m2f      "NA - Prenatal: CS health professional"
label variable m2g      "Prenatal: traditional birth attendant"
label variable m2h      "Prenatal: community health worker/volunteer"
label variable m2i      "NA - Prenatal: CS other person"
label variable m2j      "NA - Prenatal: CS other person"
label variable m2k      "Prenatal: other"
label variable m2l      "NA - Prenatal: CS other"
label variable m2m      "NA - Prenatal: CS other"
label variable m2n      "Prenatal: no one"
label variable m3a      "Assistance: doctor"
label variable m3b      "Assistance: nurse/midwife"
label variable m3c      "NA - Assistance: CS health professional"
label variable m3d      "NA - Assistance: CS health professional"
label variable m3e      "NA - Assistance: CS health professional"
label variable m3f      "NA - Assistance: CS health professional"
label variable m3g      "Assistance: traditional birth attendant"
label variable m3h      "Assistance: community health worker/volunteer"
label variable m3i      "Assistance: family/other relatives"
label variable m3j      "NA - Assistance: CS other person"
label variable m3k      "Assistance: other"
label variable m3l      "NA - Assistance: CS other"
label variable m3m      "NA - Assistance: CS other"
label variable m3n      "Assistance: no one"
label variable m4       "Duration of breastfeeding"
label variable m5       "Months of breastfeeding"
label variable m6       "Duration of amenorrhea"
label variable m7       "Months of amenorrhea"
label variable m8       "Duration of abstinence"
label variable m9       "Months of abstinence"
label variable m10      "Wanted pregnancy when became pregnant"
label variable m11      "Desired time would have waited"
label variable m13      "Timing of 1st antenatal check (months)"
label variable m13a     "Timing of 1st antenatal check (original)"
label variable m14      "Number of antenatal visits during pregnancy"
label variable m15      "Place of delivery"
label variable m17      "Delivery by caesarean section"
label variable m17a     "NA - Timing on decision for caesarean section"
label variable m18      "Size of child at birth"
label variable m19      "Birth weight in kilograms (3 decimals)"
label variable m19a     "Weight at birth/recall"
label variable m27      "NA - Flag for breastfeeding"
label variable m28      "NA - Flag for amenorrhea"
label variable m29      "NA - Flag for abstinence"
label variable m34      "When child put to breast"
label variable m35      "NA - Number of times breastfed during previous night"
label variable m36      "NA - Number of times breastfed during previous day"
label variable m38      "Drank from bottle with nipple yesterday/last night"
label variable m39a     "Did eat any solid, semi-solid or soft foods yesterday"
label variable m39      "Number of times ate solid, semi-solid or soft food yesterday"
label variable m42a     "NA - During pregnancy: weighed"
label variable m42b     "NA - During pregnancy: height measured"
label variable m42c     "During pregnancy: blood pressure taken"
label variable m42d     "During pregnancy: urine sample taken"
label variable m42e     "During pregnancy: blood sample taken"
label variable m42f     "During pregnancy: listen to baby's heartbeat"
label variable m42g     "During pregnancy: talk about foods to eat"
label variable m42h     "During pregnancy: talk about breastfeeding"
label variable m42i     "During pregnancy: ask about vaginal bleeding"
label variable m42j     "NA - During pregnancy: talk about when baby is due"
label variable m42k     "NA - During pregnancy: pay attention to baby movements"
label variable m42l     "NA - During pregnancy: CS"
label variable m42m     "NA - During pregnancy: CS"
label variable m42n     "NA - During pregnancy: CS"
label variable m43      "NA - Told about pregnancy complications"
label variable m44      "NA - Told where to go for pregnancy complications"
label variable m45      "During pregnancy, given or bought iron tablets/syrup"
label variable m46      "Days tablets or syrup taken"
label variable m47      "NA - During pregnancy, had difficulty with daylight vision"
label variable m48      "NA - During pregnancy, had difficulty with night blindness"
label variable m49a     "During pregnancy took: SP/fansidar for malaria"
label variable m49b     "NA - During pregnancy took: chloroquine for malaria"
label variable m49c     "NA - During pregnancy took: CS drug for malaria"
label variable m49d     "NA - During pregnancy took: CS drug for malaria"
label variable m49e     "NA - During pregnancy took: CS drug for malaria"
label variable m49f     "NA - During pregnancy took: CS drug for malaria"
label variable m49g     "NA - During pregnancy took: CS drug for malaria"
label variable m49x     "NA - During pregnancy took: other drug for malaria"
label variable m49z     "NA - During pregnancy took: don't know"
label variable m49y     "NA - During pregnancy took: no drug for malaria"
label variable m54      "NA - Received Vitamin A dose in first 2 months after delivery"
label variable m55      "Given child anything other than breast milk"
label variable m57a     "Antenatal care: respondent's home"
label variable m57b     "Antenatal care: other home"
label variable m57c     "NA - Antenatal care: CS home"
label variable m57d     "NA - Antenatal care: CS home"
label variable m57e     "Antenatal care: government hospital"
label variable m57f     "Antenatal care: government polyclinic"
label variable m57g     "Antenatal care: government health center"
label variable m57h     "Antenatal care: government clinic"
label variable m57i     "Antenatal care: CHPS center/government health post"
label variable m57j     "Antenatal care: community health services (outreach)"
label variable m57k     "Antenatal care: Other public sector"
label variable m57l     "NA - Antenatal care: CS public health"
label variable m57m     "Antenatal care: private hospital"
label variable m57n     "Antenatal care: private clinic"
label variable m57o     "Antenatal care: maternity home"
label variable m57p     "Antenatal care: community health services (mobile clinic)"
label variable m57q     "Antenatal care: other private medical sector"
label variable m57r     "NA - Antenatal care: CS private medical"
label variable m57na    "Antenatal care: NGO hospital"
label variable m57nb    "Antenatal care: Other NGO medical sector"
label variable m57nc    "NA - Antenatal care: NGO medical"
label variable m57nd    "NA - Antenatal care: NGO medical"
label variable m57ne    "NA - Antenatal care: NGO medical"
label variable m57s     "NA - Antenatal care: CS other"
label variable m57t     "NA - Antenatal care: CS other"
label variable m57u     "NA - Antenatal care: CS other"
label variable m57v     "NA - Antenatal care: CS other"
label variable m57x     "Antenatal care: other"
label variable m60      "Drugs for intestinal parasites during pregnancy"
label variable m61      "Time spent at place of delivery"
label variable m62      "Respondent's health checked after delivery before discharge"
label variable m63      "How long after delivery respondent's health check before discharge took place"
label variable m64      "Who checked respondent's health before discharge"
label variable m66      "Respondent's health checked after discharge/delivery at home"
label variable m67      "How long after delivery respondent's health check (after discharge/home delivery"
label variable m68      "Who checked respondent's health after discharge/delivery at home"
label variable m69      "Where respondent's check after discharge/delivery at home took place"
label variable m70      "Child's health checked after discharge/delivery at home"
label variable m71      "How long after delivery child's health check (after discharge/home delivery) too"
label variable m72      "Who checked child's health after discharge/home delivery"
label variable m73      "Where child's health check after discharge/home delivery took place"
label variable m74      "Child's health checked before discharge"
label variable m75      "How long after delivery child's health check before discharge took place"
label variable m76      "Who checked child's health before discharge"
label variable m77      "Was child put on mother's chest and bare skin after birth"
label variable m77a     "Time after birth baby was put on bare skin"
label variable m78a     "During first 2 days health provider: examine cord"
label variable m78b     "During first 2 days health provider: measure temperature"
label variable m78c     "During first 2 days health provider: signs baby needs medical attentions"
label variable m78d     "During first 2 days health provider: counsel on breastfeeding"
label variable m78e     "During first 2 days health provider: observe breastfeeding"
label variable m78f     "During first 2 days health provider: measure blood pressure"
label variable m78g     "During first 2 days health provider: discuss vaginal bleeding"
label variable m78h     "During first 2 days health provider: discuss family planning"
label variable m78i     "NA - During first 2 days health provider: tell where to get help with breastfeed"
label variable m78j     "NA - During first 2 days health provider: ask if have problems with urination"
label variable m78k     "NA - During first 2 days health provider: ask if have pain"
label variable m78l     "NA - During first 2 days health provider: ask if feel sad or depressed"
label variable m78m     "NA - During first 2 days health provider: CS"
label variable m78n     "NA - During first 2 days health provider: CS"
label variable m78o     "NA - During first 2 days health provider: CS"
label variable m78p     "NA - During first 2 days health provider: CS"
label variable m80      "Pregnancy outcome for this section"
label variable m81a     "Place obtained iron tablets/syrup: government hospital"
label variable m81b     "Place obtained iron tablets/syrup: government polyclinic"
label variable m81c     "Place obtained iron tablets/syrup: government health center"
label variable m81d     "Place obtained iron tablets/syrup: government clinic"
label variable m81e     "Place obtained iron tablets/syrup: CHPS center/government health post"
label variable m81f     "Place obtained iron tablets/syrup: Community health services (outreach)"
label variable m81g     "Place obtained iron tablets/syrup: Other public sector"
label variable m81h     "NA - Place obtained iron tablets/syrup: CS public sector"
label variable m81i     "NA - Place obtained iron tablets/syrup: CS public sector"
label variable m81j     "Place obtained iron tablets/syrup: private hospital"
label variable m81k     "Place obtained iron tablets/syrup: pharmacy"
label variable m81l     "NA - Place obtained iron tablets/syrup: private doctor"
label variable m81m     "Place obtained iron tablets/syrup: private clinic"
label variable m81n     "Place obtained iron tablets/syrup: maternity home"
label variable m81o     "Place obtained iron tablets/syrup: Community health services (mobile clinic)"
label variable m81p     "Place obtained iron tablets/syrup: Other private medical sector"
label variable m81q     "NA - Place obtained iron tablets/syrup: CS private medical"
label variable m81r     "NA - Place obtained iron tablets/syrup: CS private medical"
label variable m81na    "Place obtained iron tablets/syrup: NGO hospital"
label variable m81nb    "Place obtained iron tablets/syrup: Other NGO medical sector"
label variable m81nc    "NA - Place obtained iron tablets/syrup: CS NGO"
label variable m81nd    "NA - Place obtained iron tablets/syrup: CS NGO"
label variable m81ne    "NA - Place obtained iron tablets/syrup: CS NGO"
label variable m81s     "Place obtained iron tablets/syrup: shop"
label variable m81t     "Place obtained iron tablets/syrup: market"
label variable m81u     "NA - Place obtained iron tablets/syrup: CS other sector"
label variable m81v     "NA - Place obtained iron tablets/syrup: CS other sector"
label variable m81w     "NA - Place obtained iron tablets/syrup: CS other sector"
label variable m81x     "Place obtained iron tablets/syrup: other"
label variable m82      "NA - During pregnancy received food/cash through assistance program"
label variable ml0      "Type of mosquito bed net(s) child slept under last night"
label variable ml1      "Number of times took fansidar during pregnancy"
label variable ml2      "Source of antimalarial during pregnancy"
label variable mnb1     "NA - Time after birth child was bathed"
label variable mnb3     "NA - Device used to cut the cord"
label variable mnb4     "NA - Was the device new or had it been used before"
label variable mnb5     "NA - Was the device boiled before used to cut the cord"
label variable mnb6     "NA - Anyting applied to the cord from the time it was cut until it fell off"
label variable mnb7a    "NA - What was applied to the cord: chlorhexidine"
label variable mnb7b    "NA - What was applied to the cord: other antiseptic (alcohol, spirit, gentian vi"
label variable mnb7c    "NA - What was applied to the cord: mustard oil"
label variable mnb7d    "NA - What was applied to the cord: ash"
label variable mnb7e    "NA - What was applied to the cord: animal dung"
label variable mnb7f    "NA - What was applied to the cord: CS"
label variable mnb7g    "NA - What was applied to the cord: CS"
label variable mnb7h    "NA - What was applied to the cord: CS"
label variable mnb7i    "NA - What was applied to the cord: CS"
label variable mnb7j    "NA - What was applied to the cord: CS"
label variable mnb7x    "NA - What was applied to the cord: other"
label variable mnb7z    "NA - What was applied to the cord: don't know"
label variable mnb10    "NA - Was chlorhexidine applied to the cord at any time"
label variable mnb11    "NA - Time after cord was cut chlorhexidine was first applied"
label variable mnb12    "NA - Days chlorhexidine was applied to the cord"
label variable mh3a     "NA - During antenatal care discussed: where to deliver baby"
label variable mh3b     "NA - During antenatal care discussed: if wanted a relative, friend, neighbor dur"
label variable mh3c     "NA - During antenatal care discussed: transportation to delivery place"
label variable mh3d     "NA - During antenatal care discussed: source of funds for delivery"
label variable mh3e     "NA - During antenatal care discussed: asking someone as blood donor if necessary"
label variable mh3f     "NA - During antenatal care discussed: find healthcare provider to deliver child"
label variable mh3g     "NA - During antenatal care discussed: CS"
label variable mh3h     "NA - During antenatal care discussed: CS"
label variable mh3i     "NA - During antenatal care discussed: CS"
label variable mh5      "NA - Healthcare provider measure blood pressure before delivery"
label variable mh6      "NA - While in labor wanted to have someone by your side"
label variable mh7      "NA - While in labor the person you wanted by your side was with you"
label variable mh8      "NA - While in labor how much time the person you wanted by your side was allowed"
label variable mh9      "NA - Reason the person you wanted by your side was not with you during labor"
label variable mh10     "NA - During delivery wanted to have someone by your side"
label variable mh11     "NA - During delivery the person you wanted by your side was with you"
label variable mh12     "NA - During delivery how much time the person you wanted by your side was allowe"
label variable mh13     "NA - Reason the person you wanted by your side was not with you during delivery"
label variable mh14     "NA - Was an instrument used to help pull out the baby"
label variable mh15     "NA - While in labor or delivery did feel ignored/neglected by facility staff"
label variable mh16     "NA - While in labor or delivery did have privacy"
label variable mh17a    "NA - At delivery place did healthcare providers: treated you with respect"
label variable mh17b    "NA - At delivery place did healthcare providers: explained examinations/procedur"
label variable mh17c    "NA - At delivery place did healthcare providers: took best care of you"
label variable mh17d    "NA - At delivery place did healthcare providers: CS"
label variable mh17e    "NA - At delivery place did healthcare providers: CS"
label variable mh18a    "NA - During stay at health facility: shared bed with other patient"
label variable mh18b    "NA - During stay at health facility: rest/sleep on floor without mattress"
label variable mh18c    "NA - During stay at health facility: CS"
label variable mh18d    "NA - During stay at health facility: CS"
label variable mh19     "NA - During stay at health facility were denied medical services for lack of mon"
label variable mh20     "NA - Were delayed or prevented to leave facility because of lack of payment"
label variable mh21a    "NA - During stay staff at health facility: slap you"
label variable mh21b    "NA - During stay staff at health facility: hit or punch you"
label variable mh21c    "NA - During stay staff at health facility: physically threaten you"
label variable mh21d    "NA - During stay staff at health facility: physically mistreat or harm you"
label variable mh21e    "NA - During stay staff at health facility: CS"
label variable mh21f    "NA - During stay staff at health facility: CS"
label variable mh22a    "NA - During stay staff at health facility: shout at you"
label variable mh22b    "NA - During stay staff at health facility: say or do something to humilliate you"
label variable mh22c    "NA - During stay staff at health facility: verbally threaten"
label variable mh22d    "NA - During stay staff at health facility: verbally mistreat you in any other wa"
label variable mh22e    "NA - During stay staff at health facility: CS"
label variable mh22f    "NA - During stay staff at health facility: CS"
label variable mh23     "NA - Did health facility have toilet/latrine for patitents"
label variable mh24     "NA - At any time wanted to use toilet/latrine but was not working"
label variable mh25     "NA - Where did baby stay in first two days after birth"
label variable s114     "Highest educational level"
label variable s115     "Highest grade/form/year at that level"
label variable s904     "Partner's level of education"
label variable s905     "Partner's highest grade"
label variable s1116    "Registered with the National Health Insurance Scheme or NHIS"
label variable s1117a   "Reason not registered with NHIDS: Not heard of NIHS"
label variable s1117b   "Reason not registered with NHIDS: Cannot afford premium"
label variable s1117c   "Reason not registered with NHIDS: Do not trust"
label variable s1117d   "Reason not registered with NHIDS: Don't need health insurance"
label variable s1117e   "Reason not registered with NHIDS: NHIS does not cover health services I need"
label variable s1117f   "Reason not registered with NHIDS: Don't understand scheme"
label variable s1117g   "Reason not registered with NHIDS: Dont know where to register"
label variable s1117h   "Reason not registered with NHIDS: No easy access to health facility"
label variable s1117i   "Reason not registered with NHIDS: Do not like the attitude of staff in a health "
label variable s1117j   "Reason not registered with NHIDS: Those with insurance are given substandard ser"
label variable s1117k   "Reason not registered with NHIDS: Don't get sick (CS)"
label variable s1117l   "Reason not registered with NHIDS: Has no time to go (CS)"
label variable s1117x   "Reason not registered with NHIDS: other"
label variable s1118b   "Reason for dropping out of NHIS: Cannot afford premium"
label variable s1118c   "Reason for dropping out of NHIS: Do not trust"
label variable s1118d   "Reason for dropping out of NHIS: Don't need health insurance"
label variable s1118e   "Reason for dropping out of NHIS: NHIS does not cover health services I need"
label variable s1118f   "Reason for dropping out of NHIS: Don't understand scheme"
label variable s1118g   "Reason for dropping out of NHIS: Don't know where to register"
label variable s1118h   "Reason for dropping out of NHIS: No easy access to health facility"
label variable s1118i   "Reason for dropping out of NHIS: Do not like the attitute of staff in a health f"
label variable s1118j   "Reason for dropping out of NHIS:Those with insurance are given substandard servi"
label variable s1118k   "Reason for dropping out of NHIS: Don't get sick (CS)"
label variable s1118l   "Reason for dropping out of NHIS: Has no time to go (CS)"
label variable s1118m   "Reason for dropping out of NHIS: Card not renewed/ missing or lost/ burnt or bro"
label variable s1118x   "Reason for dropping out of NHIS: other"
label variable s1119    "Hold a valid NHIS card"
label variable s1120a   "Reason for not having a valid NHIS: Registered, not paid fully"
label variable s1120b   "Reason for not having a valid NHIS: Registered, card not received"
label variable s1120c   "Reason for not having a valid NHIS: Registered, waiting period"
label variable s1120d   "Reason for not having a valid NHIS: Not renewed registration"
label variable s1120e   "Reason for not having a valid NHIS: Lost NHIS card"
label variable s1120x   "Reason for not having a valid NHIS: other"
label variable s1121    "Times visited health facility last 6 month"
label variable s1122    "Times accessed health facility using NHIS"
label variable s1123a1  "Out of pocket payments for consultation"
label variable s1123a2  "Co-payment of full payment for consultation"
label variable s1123b1  "Out of pocket payment for drugs"
label variable s1123b2  "Co-payment of full payment for drugs"
label variable s1123c1  "Out of pocket payment for diagnosis"
label variable s1123c2  "Co-payment of full payment for diagnosis"
label variable s1123d1  "Out of pocket payment for admission"
label variable s1123d2  "Co-payment of full payment for admission"
label variable s1123e1  "Out of pocket payment for surgical"
label variable s1123e2  "Co-payment of full payment for surgical"
label variable s1123f1  "Out of pocket payment for other health services"
label variable s1123f2  "Co-payment of full payment for other health services"
label variable s1202aa  "Message seen/heard: Zero malaria starts with you and me"
label variable s1202ab  "Message seen/heard: Malaria 360, everything malaria"
label variable s1202ac  "Message seen/heard: Good life is an everyday thing"
label variable s1214a   "Last six months seen/heard advert on the use of ACTs/ malaria medicines"
label variable s1214ba  "Source of advert on the use of ACTs/ malaria medicines: Television"
label variable s1214bb  "Source of advert on the use of ACTs/ malaria medicines: Radio"
label variable s1214bc  "Source of advert on the use of ACTs/ malaria medicines: Newspaper/ magazine"
label variable s1214bd  "Source of advert on the use of ACTs/ malaria medicines: Poster/ leaflets"
label variable s1214be  "Source of advert on the use of ACTs/ malaria medicines: Billboard"
label variable s1214bf  "Source of advert on the use of ACTs/ malaria medicines: Health facility (CS)"
label variable s1214bg  "Source of advert on the use of ACTs/ malaria medicines: Health care provider (CS"
label variable s1214bh  "Source of advert on the use of ACTs/ malaria medicines: Pharmacy/ drugstore (CS)"
label variable s1214bi  "Source of advert on the use of ACTs/ malaria medicines: Social media (CS)"
label variable s1214bj  "Source of advert on the use of ACTs/ malaria medicines: Public address system (i"
label variable s1214bx  "Source of advert on the use of ACTs/ malaria medicines: other"
label variable s1214bz  "Source of advert on the use of ACTs/ malaria medicines: don't know"
label variable s1337b   "Allow short interview for the qualitative survey"
label variable idx94    "Index to Birth History"
label variable idx94p   "Index to Pregnancy History"
label variable s432ba   "Reasons took SP/Fansidar only one or two times: facility too far"
label variable s432bb   "Reasons took SP/Fansidar only one or two times: had no money"
label variable s432bc   "Reasons took SP/Fansidar only one or two times: side effects"
label variable s432bd   "Reasons took SP/Fansidar only one or two times: not aware had to take more"
label variable s432be   "Reasons took SP/Fansidar only one or two times: did not want to take"
label variable s432bf   "Reasons took SP/Fansidar only one or two times: not given"
label variable s432bg   "Reasons took SP/Fansidar only one or two times: not available"
label variable s432bx   "Reasons took SP/Fansidar only one or two times: other"
label variable s432bz   "Reasons took SP/Fansidar only one or two times: don't know"

#delimit ;
label define V013    
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define V014    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define V015    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partially completed"
     6 "Respondent incapacitated"
     7 "Other"
;
label define V018    
     0 "No calendar"
;
label define V019    
     0 "No calendar"
;
label define V019A   
     0 "No calendar"
;
label define V020    
     0 "All woman sample"
     1 "Ever married sample"
;
label define V022    
     1 "Western, urban"
     2 "Western, rural"
     3 "Central, urban"
     4 "Central, rural"
     5 "Greater Accra, urban"
     6 "Greater Accra, rural"
     7 "Volta, urban"
     8 "Volta, rural"
     9 "Eastern, urban"
    10 "Eastern, rural"
    11 "Ashanti, urban"
    12 "Ashanti, rural"
    13 "Western North, urban"
    14 "Western North, rural"
    15 "Ahafo, urban"
    16 "Ahafo, rural"
    17 "Bono, urban"
    18 "Bono, rural"
    19 "Bono East, urban"
    20 "Bono East, rural"
    21 "Oti, urban"
    22 "Oti, rural"
    23 "Northern, urban"
    24 "Northern, rural"
    25 "Savannah, urban"
    26 "Savannah, rural"
    27 "North East, urban"
    28 "North East, rural"
    29 "Upper East, urban"
    30 "Upper East, rural"
    31 "Upper West, urban"
    32 "Upper West, rural"
;
label define V023    
     1 "Western, urban"
     2 "Western, rural"
     3 "Central, urban"
     4 "Central, rural"
     5 "Greater Accra, urban"
     6 "Greater Accra, rural"
     7 "Volta, urban"
     8 "Volta, rural"
     9 "Eastern, urban"
    10 "Eastern, rural"
    11 "Ashanti, urban"
    12 "Ashanti, rural"
    13 "Western North, urban"
    14 "Western North, rural"
    15 "Ahafo, urban"
    16 "Ahafo, rural"
    17 "Bono, urban"
    18 "Bono, rural"
    19 "Bono East, urban"
    20 "Bono East, rural"
    21 "Oti, urban"
    22 "Oti, rural"
    23 "Northern, urban"
    24 "Northern, rural"
    25 "Savannah, urban"
    26 "Savannah, rural"
    27 "North East, urban"
    28 "North East, rural"
    29 "Upper East, urban"
    30 "Upper East, rural"
    31 "Upper West, urban"
    32 "Upper West, rural"
;
label define V024    
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Western North"
     8 "Ahafo"
     9 "Bono"
    10 "Bono East"
    11 "Oti"
    12 "Northern"
    13 "Savannah"
    14 "North East"
    15 "Upper East"
    16 "Upper West"
;
label define V025    
     1 "Urban"
     2 "Rural"
;
label define V026    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V027    
     9 "Missing"
;
label define V029    
   999 "Missing"
;
label define V034    
     0 "Husband not in household"
;
label define V040    
  9999 "Missing"
;
label define V042    
     0 "Not selected"
     1 "Selected"
;
label define V044    
     0 "Woman not selected"
     1 "Woman selected and interviewed"
     2 "Woman selected, but privacy not possible"
     3 "Woman selected, but not interviewed"
;
label define V045A   
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     5 "Dagbani"
     6 "Other"
;
label define V045B   
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     5 "Dagbani"
     6 "Other"
;
label define V045C   
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     5 "Dagbani"
     6 "Other"
;
label define V046    
     0 "No"
     1 "Yes"
;
label define V101    
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Western North"
     8 "Ahafo"
     9 "Bono"
    10 "Bono East"
    11 "Oti"
    12 "Northern"
    13 "Savannah"
    14 "North East"
    15 "Upper East"
    16 "Upper West"
;
label define V102    
     1 "Urban"
     2 "Rural"
;
label define V103    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define V104    
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define V105    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define V105A   
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Western North"
     8 "Ahafo"
     9 "Bono"
    10 "Bono East"
    11 "Oti"
    12 "Northern"
    13 "Savannah"
    14 "North East"
    15 "Upper East"
    16 "Upper West"
    96 "Abroad"
;
label define V106    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define V107    
     0 "No years completed at level V106"
;
label define V113    
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    72 "sachet water"
    96 "Other"
    97 "Not a dejure resident"
;
label define V115    
   996 "On premises"
   997 "Not a dejure resident"
   998 "Don't know"
;
label define V116    
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    16 "Flush, bio-digester (Biofil)"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
    97 "Not a dejure resident"
;
label define V119    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V120    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V121    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V122    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V123    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V124    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V125    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V127    
    10 "NATURAL"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic/Marble/Porcelain/Tiles/Terrazo"
    34 "Cement"
    35 "Woolen carpet/Synthetic carpet"
    36 "Linoleum/rubber carpet"
    96 "Other"
    97 "Not a dejure resident"
;
label define V128    
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Dirt"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
    97 "Not a dejure resident"
;
label define V129    
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Zinc/aluminum"
    32 "Wood"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Roofing shingles"
    36 "Asbestos/slate roofing sheets"
    96 "Other"
    97 "Not a dejure resident"
;
label define V130    
     1 "Catholic"
     2 "Anglican"
     3 "Methodist"
     4 "Presbyterian"
     5 "Pentecostal/charismatic"
     6 "Other Christian"
     7 "Islam"
     8 "Traditional/spiritualist"
    95 "No religion"
    96 "Other"
;
label define V131    
     1 "AKAN"
     2 "GA/DANGME"
     3 "EWE"
     4 "GUAN"
     5 "MOLE-DAGBANI"
     6 "GRUSI"
     7 "GURMA"
     8 "MANDE"
    96 "Other"
;
label define V133    
    97 "Inconsistent"
;
label define V134    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V135    
     1 "Usual resident"
     2 "Visitor"
;
label define V139    
     1 "Western"
     2 "Central"
     3 "Greater accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Western north"
     8 "Ahafo"
     9 "Bono"
    10 "Bono east"
    11 "Oti"
    12 "Northern"
    13 "Savannah"
    14 "North east"
    15 "Upper east"
    16 "Upper west"
    97 "Not dejure resident"
;
label define V140    
     0 "Abroad"
     1 "Urban"
     2 "Rural"
     7 "Not a dejure resident"
;
label define V141    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     7 "Not a dejure resident"
;
label define V149    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define V150    
     1 "Head"
     2 "Wife"
     3 "Daughter"
     4 "Daughter-in-law"
     5 "Granddaughter"
     6 "Mother"
     7 "Mother-in-law"
     8 "Sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "Don't know"
;
label define V151    
     1 "Male"
     2 "Female"
;
label define V152    
    97 "97+"
    98 "Don't know"
;
label define V153    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V155    
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define V156    
     0 "No"
     1 "Yes"
;
label define V157    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V158    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V159    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V160    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V161    
     1 "Electricity"
     2 "Solar energy"
     3 "Liquefied petroleum gas (LPG)/cooking gas"
     4 "Piped natural gas"
     5 "Biogas"
     6 "Alcohol/ethanol"
     7 "Gasoline/diesel"
     8 "Kerosene/paraffin"
     9 "Coal/lignite"
    10 "Charcoal"
    11 "Wood"
    12 "Straw/shrubs/grass"
    13 "Agricultural crop"
    14 "Animal dung/waste"
    15 "Processed biomass (pellets) or woodchips"
    16 "Garbage/plastic"
    17 "Sawdust"
    95 "No food cooked in house"
    96 "Other"
    97 "Not a dejure resident"
;
label define V166    
     0 "0 ppm (no iodine)"
     7 "7 ppm"
    15 "15 ppm"
    30 "30 ppm"
   994 "Salt not tested"
   995 "No salt"
   997 "Not a dejure resident"
;
label define V167    
     0 "None"
    90 "90+"
;
label define V168    
     0 "No"
     1 "Yes"
;
label define V169A   
     0 "No"
     1 "Yes"
;
label define V169B   
     0 "No"
     1 "Yes"
;
label define V169C   
     0 "No"
     1 "Yes"
;
label define V170    
     0 "No"
     1 "Yes"
;
label define V171A   
     0 "Never"
     1 "Yes, last 12 months"
     2 "Yes, before last 12 months"
     3 "Yes, can't establish when"
;
label define V171B   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V172    
     1 "Western"
     2 "Central"
     3 "Greater accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Western north"
     8 "Ahafo"
     9 "Bono"
    10 "Bono east"
    11 "Oti"
    12 "Northern"
    13 "Savannah"
    14 "North east"
    15 "Upper east"
    16 "Upper west"
    96 "Outside Ghana"
;
label define V173    
     1 "Benin"
     2 "Burkina Faso"
     3 "Cote d'Ivoire"
     4 "Cameroon"
     5 "France"
     6 "Gabon"
     7 "Liberia"
     8 "Mali"
     9 "Niger"
    10 "Nigeria"
    11 "Pakistan"
    12 "Togo"
    13 "Antarctica"
    14 "French Southern Territories"
    96 "Other country"
;
label define V174M   
    98 "Don't know month"
;
label define V174Y   
  9998 "Don't know year"
;
label define V175    
     1 "Employment"
     2 "Education/training"
     3 "Marriage formation"
     4 "Family reunification/other family-related reason"
     5 "Forced displacement"
    96 "Other"
;
label define V176    
     1 "Very good"
     2 "Good"
     3 "Moderate"
     4 "Bad"
     5 "Very bad"
;
label define V177    
     0 "No"
     1 "Yes"
;
label define V190    
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define V190A   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define ML101   
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define V208    
     0 "No births"
;
label define V209    
     0 "No births"
;
label define V213    
     0 "No or unsure"
     1 "Yes"
;
label define V214A   
   101 "Weeks: 1"
   199 "Weeks: number missing"
   201 "Months: 1"
   299 "Months: number missing"
;
label define V215    
   100 "Day of interview"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
   994 "In menopause/had hysterectomy"
   995 "Before last pregnancy"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
;
label define V216    
     0 "No"
     1 "Yes"
;
label define V217    
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define V220    
     6 "6+"
;
label define V221    
   996 "Negative interval"
;
label define V223    
     7 "Month - exact date"
     8 "None - date placed"
;
label define V225    
     1 "Then"
     2 "Later"
     3 "Not at all"
;
label define V226    
   994 "In menopause"
   995 "Before last pregnancy"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
;
label define V227    
     0 "No flag"
     1 "N > interval since birth"
     2 "N + amen. > interval"
     3 "N, but period not returned"
     4 "95, but no  pregnancy"
     5 "95, but period returned"
     6 "96, but period returned"
     7 "N, last period during pregnancy"
     8 "96, had children"
     9 "N, period before last pregnancy"
;
label define V228    
     0 "No"
     1 "Yes"
;
label define V229    
    97 "Inconsistent"
    98 "Don't know"
;
label define V230    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V231    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V232    
     0 "Month, year and day"
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     7 "Month"
     8 "None"
;
label define V233    
    97 "Inconsistent"
    98 "Don't know"
;
label define V234    
     0 "No"
     1 "Yes"
;
label define V235    
     0 "No prior child"
;
label define V237    
     0 "No"
     1 "Yes"
;
label define V239    
     0 "No"
     1 "Yes"
;
label define V240    
    97 "Inconsistent"
    98 "Don't know"
;
label define V241    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V242    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V243    
     0 "Day, month and year"
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     7 "Month"
     8 "None"
;
label define V244    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V247A   
     0 "No"
     1 "Yes"
;
label define V247B   
     0 "No"
     1 "Yes"
;
label define V247C   
     0 "No"
     1 "Yes"
;
label define V247D   
     0 "No"
     1 "Yes"
;
label define V247E   
     0 "No"
     1 "Yes"
;
label define V247F   
     0 "No"
     1 "Yes"
;
label define V247G   
     0 "No"
     1 "Yes"
;
label define V247H   
     0 "No"
     1 "Yes"
;
label define V247I   
     0 "No"
     1 "Yes"
;
label define V247J   
     0 "No"
     1 "Yes"
;
label define V247K   
     0 "No"
     1 "Yes"
;
label define V247L   
     0 "No"
     1 "Yes"
;
label define V247X   
     0 "No"
     1 "Yes"
;
label define V247Y   
     0 "No"
     1 "Yes, nothing was used"
;
label define V248    
     0 "No"
     1 "Yes"
     2 "Away from home during last menstrual period"
;
label define V249    
    96 "Never menstruated"
    98 "Don't know"
;
label define V310    
    99 "Missing"
;
label define V311    
     4 "4+"
     5 "Never used"
;
label define V312    
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Male condom"
     6 "Female sterilization"
     7 "Male sterilization"
     8 "Periodic abstinence"
     9 "Withdrawal"
    10 "Other traditional"
    11 "Implants/Norplant"
    12 "Prolonged abstinence"
    13 "Lactational amenorrhea (LAM)"
    14 "Female condom"
    15 "Foam or jelly"
    16 "Emergency contraception"
    17 "Other modern method"
    18 "Standard days method (SDM)"
    19 "Specific method 1"
    20 "Specific method 2"
;
label define V313    
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
;
label define V318    
     1 "Month and year - information complete"
     5 "Year - month imputed, age calculated"
     7 "Month - date placed"
     8 "None - date placed"
     9 "From calendar"
;
label define V319    
     1 "<2"
     2 "2-3"
     3 "4-5"
     4 "6-7"
     5 "8-9"
     6 "10+"
;
label define V320    
     1 "<25"
     2 "25-29"
     3 "30-34"
     4 "35-39"
     5 "40-44"
     6 "45-49"
;
label define V321    
     0 "Single, before first marriage"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25+"
;
label define V321A   
     0 "Single, before current union, or married only once"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25+"
;
label define V322    
     5 "5+"
;
label define V323    
     1 "Secure"
     2 "Microgynon"
     3 "Duofem"
     4 "N/M tablets"
     5 "Microlut"
    96 "Other"
    98 "Don't know"
;
label define V323A   
     1 "Fiesta"
     2 "Kiss"
     3 "Durex"
     4 "Gold circle"
     5 "Be safe/no logo"
     6 "Cupid"
     7 "FC2"
    96 "Other"
    98 "Don't know"
;
label define V325A   
9999995 "Free"
9999998 "Don't know"
;
label define V326    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government polyclinic"
    13 "Government health center"
    14 "Government clinic"
    15 "CHPS center/government health post"
    16 "Community health services (outreach)"
    17 "Other public sector"
    20 "PRIVATE SECTOR"
    21 "Private hospital"
    22 "Private clinic"
    23 "Pharmacy"
    24 "Drug store"
    25 "Community health services (mobile clinic)"
    26 "Maternity home"
    27 "Other private medical sector"
    30 "NGO SECTOR"
    31 "NGO hospital/clinic"
    32 "Other NGO medical sector"
    40 "OTHER SOURCE"
    41 "Shop"
    42 "Church"
    43 "Friend/relative"
    44 "Drug Peddlers"
    96 "Other"
    98 "Don't know"
;
label define V327    
     1 "Government clinic/pharmacy"
     2 "Government home/community delivery"
     3 "NGO"
     4 "Private clinic/delivery"
     5 "Pharmacy"
     6 "Shop, church, friend"
     7 "Other"
     8 "Don't know"
;
label define V337    
    95 "All calendar {A core}"
    96 "96+ {B core}"
   997 "Inconsistent"
   998 "Don't know"
;
label define V359    
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Male condom"
     6 "Female sterilization"
     7 "Male sterilization"
     8 "Periodic abstinence"
     9 "Withdrawal"
    10 "Other traditional"
    11 "Implants/Norplant"
    12 "Prolonged abstinence"
    13 "Lactational amenorrhea (LAM)"
    14 "Female condom"
    15 "Foam or jelly"
    16 "Emergency contraception"
    17 "Other modern method"
    18 "Standard days method (SDM)"
    19 "Specific method 1"
    20 "Specific method 2"
;
label define V360    
     1 "Became pregnant"
     2 "Wanted to become pregnant"
     3 "Husband disapproved"
     4 "Side effects"
     5 "Health concerns"
     6 "Access, availability"
     7 "Wanted more effective method"
     8 "Inconvenient to use"
     9 "Infrequent sex, husband away"
    10 "Cost"
    11 "Fatalistic"
    12 "Difficult pregnancy, menopause"
    13 "Marital dissolution"
    14 "Other"
    15 "Changes in mesntrual bleeding"
    98 "Don't know"
;
label define V361    
     1 "Currently using"
     2 "Used since last birth"
     3 "Used before last birth"
     4 "Never used"
;
label define V362    
     1 "In next 12 months"
     2 "Use later"
     3 "Unsure about timing"
     4 "Unsure about use"
     5 "Does not intend"
     6 "Never had sex"
;
label define V363    
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Male condom"
     6 "Female sterilization"
     7 "Male sterilization"
     8 "Periodic abstinence"
     9 "Withdrawal"
    10 "Other traditional"
    11 "Implants/Norplant"
    12 "Prolonged abstinence"
    13 "Lactational amenorrhea (LAM)"
    14 "Female condom"
    15 "Foam or jelly"
    16 "Emergency contraception"
    17 "Other modern method"
    18 "Standard days method (SDM)"
    19 "Specific method 1"
    20 "Specific method 2"
    98 "Don't know"
;
label define V364    
     1 "Using modern method"
     2 "Using traditional method"
     3 "Non-user - intends to use later"
     4 "Does not intend to use"
     5 "Never had sex"
;
label define V367    
     1 "Wanted then"
     2 "Wanted later"
     3 "Wanted no more"
;
label define V367A   
     1 "Wanted then"
     2 "Wanted later"
     3 "Wanted no more"
;
label define V372    
     0 "Package not seen"
     1 "Package seen"
;
label define V372A   
     0 "Package not seen"
     1 "Package seen"
;
label define V375A   
    11 "Not married"
    20 "FERTILITY-RELATED"
    21 "Not having sex"
    22 "Infrequent sex"
    23 "Menopausal, hysterectomy"
    24 "Subfecund, infecund"
    25 "Postpartum, breastfeeding"
    26 "Wants more children"
    27 "Pregnant"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Husband opposed"
    33 "Others opposed"
    34 "Religious prohibition"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fears side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interferes with body"
    96 "Other"
    98 "Don't know"
;
label define V376    
    11 "Not married"
    20 "FERTILITY-RELATED"
    22 "Infrequent sex"
    23 "Menopausal, hysterectomy"
    24 "Subfecund, infecund"
    26 "Wants more children"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Husband opposed"
    33 "Others opposed"
    34 "Religious prohibition"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fears side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interferes with body"
    96 "Other"
    98 "Don't know"
;
label define V376A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V379    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government polyclinic"
    13 "Government health center"
    14 "Government clinic"
    15 "CHPS center/government health post"
    16 "Community health services (outreach)"
    17 "Other public sector"
    20 "PRIVATE SECTOR"
    21 "Private hospital"
    22 "Private clinic"
    23 "Pharmacy"
    24 "Drug store"
    25 "Community health services (mobile clinic)"
    26 "Maternity home"
    27 "Other private medical sector"
    30 "NGO SECTOR"
    31 "NGO hospital/clinic"
    32 "Other NGO medical sector"
    40 "OTHER SOURCE"
    41 "Shop/market"
    42 "Church"
    43 "Friend/relative"
    44 "Drug peddler"
    94 "Knows source, place wasn't asked"
    95 "Knowledge of source wasn't asked"
    96 "Other"
    98 "Don't know"
;
label define V380    
     1 "Government clinic/pharmacy"
     2 "Government home/community delivery"
     3 "NGO"
     4 "Private clinic/delivery"
     5 "Pharmacy"
     6 "Shop, church, friend"
     7 "Other"
     8 "Don't know"
;
label define V384A   
     0 "No"
     1 "Yes"
;
label define V384B   
     0 "No"
     1 "Yes"
;
label define V384C   
     0 "No"
     1 "Yes"
;
label define V384D   
     0 "No"
     1 "Yes"
;
label define V384E   
     0 "No"
     1 "Yes"
;
label define V384F   
     0 "No"
     1 "Yes"
;
label define V384G   
     0 "No"
     1 "Yes"
;
label define V384H   
     0 "No"
     1 "Yes"
;
label define V384I   
     0 "No"
     1 "Yes"
;
label define V384J   
     0 "No"
     1 "Yes"
;
label define V384K   
     0 "No"
     1 "Yes"
;
label define V393    
     0 "No"
     1 "Yes"
;
label define V393A   
     0 "No"
     1 "Yes"
;
label define V394    
     0 "No"
     1 "Yes"
;
label define V395    
     0 "No"
     1 "Yes"
;
label define V3A00A  
     0 "No"
     1 "Yes"
;
label define V3A00B  
     0 "No"
     1 "Yes"
;
label define V3A00C  
     0 "No"
     1 "Yes"
;
label define V3A00D  
     0 "No"
     1 "Yes"
;
label define V3A00E  
     0 "No"
     1 "Yes"
;
label define V3A00F  
     0 "No"
     1 "Yes"
;
label define V3A00G  
     0 "No"
     1 "Yes"
;
label define V3A00H  
     0 "No"
     1 "Yes"
;
label define V3A00I  
     0 "No"
     1 "Yes"
;
label define V3A00J  
     0 "No"
     1 "Yes"
;
label define V3A00K  
     0 "No"
     1 "Yes"
;
label define V3A00L  
     0 "No"
     1 "Yes"
;
label define V3A00M  
     0 "No"
     1 "Yes"
;
label define V3A00N  
     0 "No"
     1 "Yes"
;
label define V3A00O  
     0 "No"
     1 "Yes"
;
label define V3A00P  
     0 "No"
     1 "Yes"
;
label define V3A00Q  
     0 "No"
     1 "Yes"
;
label define V3A00R  
     0 "No"
     1 "Yes"
;
label define V3A00S  
     0 "No"
     1 "Yes"
;
label define V3A00T  
     0 "No"
     1 "Yes"
;
label define V3A00U  
     0 "No"
     1 "Yes"
;
label define V3A00V  
     0 "No"
     1 "Yes"
;
label define V3A00W  
     0 "No"
     1 "Yes"
;
label define V3A00X  
     0 "No"
     1 "Yes"
;
label define V3A00Y  
     0 "No: knows a source"
     1 "Yes: knows no source"
;
label define V3A00Z  
     0 "No"
     1 "Yes"
;
label define V3A01   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V3A02   
     0 "No"
     1 "Yes"
;
label define V3A03   
     0 "No"
     1 "Yes"
;
label define V3A04   
     0 "No"
     1 "Yes"
;
label define V3A05   
     0 "No"
     1 "Yes"
;
label define V3A06   
     0 "No"
     1 "Yes"
;
label define V3A07   
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government polyclinic"
    13 "Government health center"
    14 "Government clinic"
    15 "CHPS center/government health post"
    16 "Community health services (outreach)"
    17 "Other public sector"
    20 "PRIVATE SECTOR"
    21 "Private hospital"
    22 "Private clinic"
    23 "Pharmacy"
    24 "Drug store"
    25 "Community health services (mobile clinic)"
    26 "Maternity home"
    27 "Other private medical sector"
    30 "NGO SECTOR"
    31 "NGO hospital/clinic"
    32 "Other NGO medical sector"
    40 "OTHER SOURCE"
    41 "Shop"
    42 "Church"
    43 "Friend/relative"
    44 "Drug Peddlers"
    96 "Other"
    98 "Don't know"
;
label define V3A08A  
     0 "No"
     1 "Yes"
;
label define V3A08B  
     0 "No"
     1 "Yes"
;
label define V3A08C  
     0 "No"
     1 "Yes"
;
label define V3A08D  
     0 "No"
     1 "Yes"
;
label define V3A08E  
     0 "No"
     1 "Yes"
;
label define V3A08F  
     0 "No"
     1 "Yes"
;
label define V3A08G  
     0 "No"
     1 "Yes"
;
label define V3A08H  
     0 "No"
     1 "Yes"
;
label define V3A08I  
     0 "No"
     1 "Yes"
;
label define V3A08J  
     0 "No"
     1 "Yes"
;
label define V3A08K  
     0 "No"
     1 "Yes"
;
label define V3A08L  
     0 "No"
     1 "Yes"
;
label define V3A08M  
     0 "No"
     1 "Yes"
;
label define V3A08N  
     0 "No"
     1 "Yes"
;
label define V3A08O  
     0 "No"
     1 "Yes"
;
label define V3A08P  
     0 "No"
     1 "Yes"
;
label define V3A08Q  
     0 "No"
     1 "Yes"
;
label define V3A08R  
     0 "No"
     1 "Yes"
;
label define V3A08S  
     0 "No"
     1 "Yes"
;
label define V3A08T  
     0 "No"
     1 "Yes"
;
label define V3A08U  
     0 "No"
     1 "Yes"
;
label define V3A08V  
     0 "No"
     1 "Yes"
;
label define V3A08W  
     0 "No"
     1 "Yes"
;
label define V3A08AA 
     0 "No"
     1 "Yes"
;
label define V3A08AB 
     0 "No"
     1 "Yes"
;
label define V3A08AC 
     0 "No"
     1 "Yes"
;
label define V3A08AD 
     0 "No"
     1 "Yes"
;
label define V3A08AE 
     0 "No"
     1 "Yes"
;
label define V3A08AF 
     0 "No"
     1 "Yes"
;
label define V3A08X  
     0 "No"
     1 "Yes"
;
label define V3A08Z  
     0 "No"
     1 "Yes: don't know"
;
label define V3A09A  
   998 "Don't know"
;
label define V3A09B  
   998 "Don't know"
;
label define V3A10   
     1 "Yes, respondent sterilized only"
     2 "Yes, partner sterilized only"
     3 "Yes, both sterilized"
     4 "No, neither sterilized"
;
label define V3A11   
     1 "DMPA-SC/Sayana press"
     2 "Needle and syringe"
     8 "Don't know"
;
label define V3A12   
     1 "Self-injection"
     2 "Injection given by health care provider"
     8 "Don't know"
;
label define V3A13   
     0 "No"
     1 "Yes"
;
label define V3A14   
     0 "No"
     1 "Yes"
;
label define V401    
     0 "No"
     1 "Yes"
;
label define V404    
     0 "No"
     1 "Yes"
;
label define V405    
     0 "No"
     1 "Yes"
;
label define V406    
     0 "No"
     1 "Yes"
;
label define V407    
    96 "On demand"
;
label define V408    
    96 "On demand"
;
label define V415    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V416    
     0 "Never heard of"
     1 "Used ORS"
     2 "Heard of ORS"
;
label define V426    
     0 "Immediately"
   100 "Within first hour"
   101 "Hours: 1"
   199 "Hours: number missing"
   201 "Days: 1"
   299 "Days: number missing"
;
label define V437    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define V438    
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define V445    
  9998 "Flagged cases"
;
label define V447    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
     7 "No measurement found in household"
;
label define V446A   
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define V446D   
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define V452A   
     1 "Under age 18"
     2 "Age 18 or older"
;
label define V452B   
     0 "Not in household"
;
label define V452C   
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define V453    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define V454    
     0 "No/don't know"
     1 "Yes"
;
label define V455    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
     7 "No measurement found in household"
;
label define V456    
   999 "Missing"
;
label define V457    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define V458    
     0 "No"
     1 "Yes"
;
label define V459    
     0 "No"
     1 "Yes"
;
label define V460    
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define V461    
     0 "No"
     1 "Yes"
;
label define V462    
     0 "No"
     1 "Yes"
     2 "Never prepared meal"
;
label define V463A   
     0 "No"
     1 "Yes"
;
label define V463B   
     0 "No"
     1 "Yes"
;
label define V463C   
     0 "No"
     1 "Yes"
;
label define V463D   
     0 "No"
     1 "Yes"
;
label define V463E   
     0 "No"
     1 "Yes"
;
label define V463F   
     0 "No"
     1 "Yes"
;
label define V463G   
     0 "No"
     1 "Yes"
;
label define V463H   
     0 "No"
     1 "Yes"
;
label define V463I   
     0 "No"
     1 "Yes"
;
label define V463J   
     0 "No"
     1 "Yes"
;
label define V463K   
     0 "No"
     1 "Yes"
;
label define V463L   
     0 "No"
     1 "Yes"
;
label define V463X   
     0 "No"
     1 "Yes"
;
label define V463Z   
     0 "No"
     1 "Yes, smokes nothing"
;
label define V463AA  
     0 "Does not smoke"
     1 "Every day"
     2 "Some days"
;
label define V463AB  
     0 "Does not smoke"
     1 "Every day"
     2 "Some days"
;
label define V464    
    80 "80+"
    98 "Don't know"
;
label define V466    
     0 "No"
     1 "Yes"
     2 "Depends"
;
label define V467A   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467B   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467C   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467D   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467E   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467F   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467G   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467H   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467I   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467J   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467K   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467L   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467M   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V468    
     0 "See specific questions"
     1 "Last birth only"
     2 "All births in last 5 years"
;
label define V471A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471CS  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471F   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471G   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471H   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471I   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472F   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472G   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472H   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472I   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472J   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472K   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472L   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472M   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472N   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472O   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472P   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472Q   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472R   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472S   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472T   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472U   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472V   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472W   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472WA  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472WB  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472WC  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472WD  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472WE  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V473A   
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
     6 "Sample not tested/lost/not enough DBS"
;
label define V473B   
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost/damaged/insufficient"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define V477    
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define V478    
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define V479    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    16 "Other public sector"
    20 "PRIVATE SECTOR"
    21 "Private hospital/clinic/doctor"
    22 "Dental clinic/office"
    23 "Pharmacy"
    24 "Office or home of nurse/health worker"
    26 "Other private sector"
    30 "OTHER NON-MEDICAL"
    31 "Respondent's home"
    96 "Other"
;
label define V480    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V481    
     0 "No"
     1 "Yes"
;
label define V481A   
     0 "No"
     1 "Yes"
;
label define V481B   
     0 "No"
     1 "Yes"
;
label define V481C   
     0 "No"
     1 "Yes"
;
label define V481D   
     0 "No"
     1 "Yes"
;
label define V481E   
     0 "No"
     1 "Yes"
;
label define V481F   
     0 "No"
     1 "Yes"
;
label define V481G   
     0 "No"
     1 "Yes"
;
label define V481H   
     0 "No"
     1 "Yes"
;
label define V481X   
     0 "No"
     1 "Yes"
;
label define V482A   
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define V482B   
     0 "No"
     1 "Yes"
;
label define V482C   
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define V483A   
   600 "600+"
;
label define V483B   
    10 "---MOTORIZED---"
    11 "Car/truck"
    12 "Public bus"
    13 "Motorcycle/scooter"
    14 "Boat with motor"
    20 "---NOT MOTORIZED---"
    21 "Animal-drawn cart"
    22 "Bicycle"
    23 "Boat without motor"
    24 "Walking"
    96 "Other"
;
label define V484A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V484B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V485A   
     0 "Did not have even one drink"
    95 "Every day/almost every day"
    96 "Never have consumed alcohol"
;
label define V485B   
    40 "40+"
;
label define V501    
     0 "Never in union"
     1 "Married"
     2 "Living with partner"
     3 "Widowed"
     4 "Divorced"
     5 "No longer living together/separated"
;
label define V502    
     0 "Never in union"
     1 "Currently in union/living with a man"
     2 "Formerly in union/living with a man"
;
label define V503    
     1 "Once"
     2 "More than once"
;
label define V504    
     1 "Living with her"
     2 "Staying elsewhere"
;
label define V505    
     0 "No other wives"
    98 "Don't know"
;
label define V506    
    98 "Don't know"
;
label define V510    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define V510A   
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define V513    
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define V525    
     0 "Not had sex"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
;
label define V527    
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define V528    
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
;
label define V529    
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define V530    
     0 "No flag"
     1 "N > interval since birth"
     2 "N + abstinence > interval"
     3 "N, but sex not res."
     4 "96, but no birth"
     5 "96, but currently pregnant"
     6 "96, but resumed sex"
     7 "N, last sex before pregnancy"
     8 "N, inconsistent 4 weeks"
     9 "N, sex before last birth"
;
label define V531    
     0 "Not had sex"
    97 "Inconsistent"
    98 "Don't know"
;
label define V532    
     0 "No flag"
     1 "After interview"
     2 "After conception >= 1 year"
     3 "After conception < 1 year"
     4 "At marriage, but never married"
     5 "At marriage, but after conception"
     6 "After marriage"
;
label define V535    
     0 "No"
     1 "Formerly married"
     2 "Lived with a man"
;
label define V536    
     0 "Never had sex"
     1 "Active in last 4 weeks"
     2 "Not active in last 4 weeks - postpartum abstinence"
     3 "Not active in last 4 weeks - not postpartum abstinence"
;
label define V537    
    60 "60+"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
;
label define V538    
     1 "Death/widowhood"
     2 "Divorce"
     3 "Separation"
;
label define V539    
     1 "Respondent"
     2 "Other wife"
     3 "Spouse's children"
     4 "Spouse's family"
     6 "Other"
     7 "No property"
;
label define V540    
     0 "No"
     1 "Yes"
;
label define V541    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V542    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V543A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V543B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V543C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V543D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V543E   
     0 "No"
     1 "Yes"
;
label define V543F   
     0 "No"
     1 "Yes"
;
label define V543G   
     0 "No"
     1 "Yes"
;
label define V543X   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V544    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V602    
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized (respondent or partner)"
     5 "Declared infecund"
     6 "Never had sex"
;
label define V603    
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon, now"
   996 "Other, non-numeric"
   997 "Inconsistent"
   998 "Don't know"
;
label define V604    
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
;
label define V605    
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized (respondent or partner)"
     7 "Declared infecund"
     8 "Never had sex"
;
label define V613    
    96 "Non-numeric response"
    98 "Don't know"
;
label define V614    
     6 "6+"
     7 "Non-numeric response"
;
label define V616    
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "Don't know"
;
label define V621    
     1 "Both want same"
     2 "Husband wants more"
     3 "Husband wants fewer"
     8 "Don't know"
;
label define V623    
     0 "Fecund"
     1 "Pregnant"
     2 "Postpartum amenorrheic"
     3 "Infecund, menopausal"
;
label define V624    
     0 "Never had sex"
     1 "Unmet need for spacing"
     2 "Unmet need for limiting"
     3 "Using for spacing"
     4 "Using for limiting"
     5 "Spacing failure"
     6 "Limiting failure"
     7 "No unmet need"
     8 "Not married and no sex in last 30 days"
     9 "Infecund, menopausal"
;
label define V625    
     0 "Fecund"
     1 "Pregnant"
     2 "Postpartum amenorrheic"
     3 "Infecund, menopausal"
;
label define V626    
     0 "Never had sex"
     1 "Unmet need for spacing"
     2 "Unmet need for limiting"
     3 "Using for spacing"
     4 "Using for limiting"
     5 "Spacing failure"
     6 "Limiting failure"
     7 "No unmet need"
     8 "Not married and no sex in last 30 days"
     9 "Infecund, menopausal"
;
label define V625A   
     0 "Fecund"
     1 "Pregnant"
     2 "Postpartum amenorrheic"
     3 "Infecund, menopausal"
;
label define V626A   
     0 "Never had sex"
     1 "Unmet need for spacing"
     2 "Unmet need for limiting"
     3 "Using for spacing"
     4 "Using for limiting"
     7 "No unmet need"
     8 "Not married and no sex in last 30 days"
     9 "Infecund, menopausal"
;
label define V627    
    96 "Other"
    98 "Don't know"
;
label define V628    
    96 "Other"
    98 "Don't know"
;
label define V629    
    96 "Other"
    98 "Don't know"
;
label define V631    
     1 "Big problem"
     2 "Small problem"
     3 "No problem"
     4 "Says she can't get pregnant/not having sex"
;
label define V632    
     1 "Respondent"
     2 "Husband/partner"
     3 "Joint decision"
     4 "Someone else"
     6 "Other"
;
label define V632A   
     1 "Mainly respondent"
     2 "Mainly husband, partner"
     3 "Joint decision"
     6 "Other"
;
label define V633A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V633B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V633C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V633D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V633E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V633F   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V633G   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V634    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V635    
     1 "More important"
     2 "Equally important"
     3 "Less important"
;
label define V636    
     0 "No"
     1 "Yes"
;
label define V701    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define V702    
     0 "No years completed at level V701"
    98 "Don't know"
;
label define V704    
     0 "Not working and didn't work in last 12 months"
     1 "Related to forces/ Security forces/ Armed forces"
    11 "Legislators and Senior Officials"
    12 "Corporate Managers"
    13 "General Managers"
    21 "Physical, mathematical and engineering science professionals"
    22 " Life science and health professionals"
    23 "Teaching professionals"
    24 "Other professionals"
    31 "Physical science and engineering associate professionals"
    32 "Life science and health associate professionals"
    33 "Teaching associate professionals"
    34 "Other associate professionals"
    41 "Office clerks"
    42 "Customer services clerks"
    51 "Personal and protective  services workers"
    52 "Salespersons, demonstrators and models"
    61 "Market-oriented skilled agricultural and fishery workers"
    62 "Subsistence agricultural, fishery and related workers"
    71 "Extraction and building trades workers"
    72 "Metal and machinery trades workers"
    73 "Precision, handicraft, printing and related trades workers"
    74 "Other craft and related workers"
    81 "Industrial plant operators"
    82 "Stationary machine operators and assemblers"
    83 "Drivers and mobile machine operators"
    91 "Sales and services elementary occupations"
    92 "Agricultural, fishery and related labourers"
    93 "Labourers in mining, construction, manufacturing and transport"
    96 "No classification"
 99998 "Don't know"
;
label define V704A   
     0 "Didn't work last 12 months"
     1 "Worked last 7 days"
     2 "Worked last 12 months"
     8 "Don't know"
;
label define V705    
     0 "Did not work"
     1 "Professional/technical/managerial"
     2 "Clerical"
     3 "Sales"
     4 "Agricultural - self employed"
     5 "Agricultural - employee"
     6 "Household and domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    10 "Related to forces/ Security forces/ Armed forces"
    96 "Other"
    98 "Don't know"
;
label define V714    
     0 "No"
     1 "Yes"
;
label define V714A   
     0 "No"
     1 "Yes"
;
label define V715    
    97 "Inconsistent"
    98 "Don't know"
;
label define V716    
     0 "Not working and didn't work in last 12 months"
     1 "Related to forces/ Security forces/ Armed forces"
    11 "Legislators and Senior Officials"
    12 "Corporate Managers"
    13 "General Managers"
    21 "Physical, mathematical and engineering science professionals"
    22 " Life science and health professionals"
    23 "Teaching professionals"
    24 "Other professionals"
    31 "Physical science and engineering associate professionals"
    32 "Life science and health associate professionals"
    33 "Teaching associate professionals"
    34 "Other associate professionals"
    41 "Office clerks"
    42 "Customer services clerks"
    51 "Personal and protective  services workers"
    52 "Salespersons, demonstrators and models"
    61 "Market-oriented skilled agricultural and fishery workers"
    62 "Subsistence agricultural, fishery and related workers"
    71 "Extraction and building trades workers"
    72 "Metal and machinery trades workers"
    73 "Precision, handicraft, printing and related trades workers"
    74 "Other craft and related workers"
    81 "Industrial plant operators"
    82 "Stationary machine operators and assemblers"
    83 "Drivers and mobile machine operators"
    91 "Sales and services elementary occupations"
    92 "Agricultural, fishery and related labourers"
    93 "Labourers in mining, construction, manufacturing and transport"
    96 "No classification"
 99998 "Don't know"
;
label define V717    
     0 "Not working"
     1 "Professional/technical/managerial"
     2 "Clerical"
     3 "Sales"
     4 "Agricultural - self employed"
     5 "Agricultural - employee"
     6 "Household and domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    10 "Related to forces/ Security forces/ Armed forces"
    96 "Other"
    98 "Don't know"
;
label define V719    
     1 "For family member"
     2 "For someone else"
     3 "Self-employed"
;
label define V721    
     1 "At home"
     2 "Away"
;
label define V729    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
;
label define V730    
    96 "96+"
    98 "Don't know"
;
label define V731    
     0 "No"
     1 "In the past year"
     2 "Currently working"
     3 "Have a job, but on leave last 7 days"
;
label define V732    
     1 "All year"
     2 "Seasonal"
     3 "Occasional"
;
label define V739    
     1 "Respondent alone"
     2 "Respondent and husband/partner"
     3 "Respondent and other person"
     4 "Husband/partner alone"
     5 "Someone else"
;
label define V740    
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
;
label define V741    
     0 "Not paid"
     1 "Cash only"
     2 "Cash and in-kind"
     3 "In-kind only"
;
label define V743A   
     1 "Respondent alone"
     2 "Respondent and husband/partner"
     3 "Respondent and other person"
     4 "Husband/partner alone"
     5 "Someone else"
     6 "Other"
;
label define V743B   
     1 "Respondent alone"
     2 "Respondent and husband/partner"
     3 "Respondent and other person"
     4 "Husband/partner alone"
     5 "Someone else"
     6 "Other"
;
label define V743C   
     1 "Respondent alone"
     2 "Respondent and husband/partner"
     3 "Respondent and other person"
     4 "Husband/partner alone"
     5 "Someone else"
     6 "Other"
;
label define V743D   
     1 "Respondent alone"
     2 "Respondent and husband/partner"
     3 "Respondent and other person"
     4 "Husband/partner alone"
     5 "Someone else"
     6 "Other"
;
label define V743E   
     1 "Respondent alone"
     2 "Respondent and husband/partner"
     3 "Respondent and other person"
     4 "Husband/partner alone"
     5 "Someone else"
     6 "Other"
;
label define V743F   
     1 "Respondent alone"
     2 "Respondent and husband/partner"
     3 "Respondent and other person"
     4 "Husband/partner alone"
     5 "Someone else"
     6 "Other"
     7 "Husband/partner has no earnings"
;
label define V744A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V744B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V744C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V744D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V744E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V745A   
     0 "Does not own"
     1 "Alone only"
     2 "Jointly with husband/partner only"
     3 "Jointly with someone else only"
     4 "Jointly with husband/partner and someone else"
     5 "Both alone and jointly"
;
label define V745B   
     0 "Does not own"
     1 "Alone only"
     2 "Jointly with husband/partner only"
     3 "Jointly with someone else only"
     4 "Jointly with husband/partner and someone else"
     5 "Both alone and jointly"
;
label define V745C   
     0 "Does not have a title deed"
     1 "Has a title deed and respondent on title"
     2 "Has a title deed but respondent not on title"
     3 "Has a title deed, don't know if respondent on title"
     8 "Don't know if has a title deed"
;
label define V745D   
     0 "Does not have a title deed"
     1 "Has a title deed and respondent on title"
     2 "Has a title deed but respondent not on title"
     3 "Has a title deed, don't know if respondent on title"
     8 "Don't know if has a title deed"
;
label define V746    
     1 "More than him"
     2 "Less than him"
     3 "About the same"
     4 "Husband/partner doesn't bring in money"
     8 "Don't know"
;
label define PIDXB   
     0 "Tremination (not in birth history)"
;
label define P0      
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
;
label define P4      
     1 "Male"
     2 "Female"
;
label define P5      
     0 "No"
     1 "Yes"
;
label define P6      
   100 "Died on day of birth"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
   997 "Inconsistent"
   998 "Don't know"
;
label define P9      
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
;
label define P10     
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define P13     
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
;
label define P15     
     0 "No"
     1 "Yes"
;
label define P16     
     0 "Not listed in household"
;
label define P21     
   999 "Missing"
;
label define P30     
     1 "Born alive"
     2 "Born dead"
     3 "Miscarriage"
     4 "Abortion"
;
label define P31     
     0 "No"
     1 "Yes"
;
label define P32     
     1 "Born alive"
     2 "Born dead"
     3 "Miscarriage"
     4 "Abortion"
;
label define MIDX    
     0 "Not a live birth"
;
label define M1      
     0 "Received no injection"
     7 "7+"
     8 "Don't know"
;
label define M1A     
     0 "Received no injection"
     7 "7+"
     8 "Don't know"
;
label define M1B     
    97 "Inconsistent"
    98 "Don't know month"
;
label define M1C     
  9997 "Inconsistent"
  9998 "Don't know year"
;
label define M1D     
    99 "Missing"
;
label define M1E     
  9996 "Can't be determined"
;
label define M2A     
     0 "No"
     1 "Yes"
;
label define M2B     
     0 "No"
     1 "Yes"
;
label define M2C     
     0 "No"
     1 "Yes"
;
label define M2D     
     0 "No"
     1 "Yes"
;
label define M2E     
     0 "No"
     1 "Yes"
;
label define M2F     
     0 "No"
     1 "Yes"
;
label define M2G     
     0 "No"
     1 "Yes"
;
label define M2H     
     0 "No"
     1 "Yes"
;
label define M2I     
     0 "No"
     1 "Yes"
;
label define M2J     
     0 "No"
     1 "Yes"
;
label define M2K     
     0 "No"
     1 "Yes"
;
label define M2L     
     0 "No"
     1 "Yes"
;
label define M2M     
     0 "No"
     1 "Yes"
;
label define M2N     
     0 "No: some care"
     1 "Yes: no care"
;
label define M3A     
     0 "No"
     1 "Yes"
;
label define M3B     
     0 "No"
     1 "Yes"
;
label define M3C     
     0 "No"
     1 "Yes"
;
label define M3D     
     0 "No"
     1 "Yes"
;
label define M3E     
     0 "No"
     1 "Yes"
;
label define M3F     
     0 "No"
     1 "Yes"
;
label define M3G     
     0 "No"
     1 "Yes"
;
label define M3H     
     0 "No"
     1 "Yes"
;
label define M3I     
     0 "No"
     1 "Yes"
;
label define M3J     
     0 "No"
     1 "Yes"
;
label define M3K     
     0 "No"
     1 "Yes"
;
label define M3L     
     0 "No"
     1 "Yes"
;
label define M3M     
     0 "No"
     1 "Yes"
;
label define M3N     
     0 "No: some assistance"
     1 "Yes: no assistance"
;
label define M4      
    93 "Ever breastfed, not currently breastfeeding"
    94 "Never breastfed"
    95 "Still breastfeeding"
    96 "Breastfed until died"
    97 "Inconsistent"
    98 "Don't know"
;
label define M5      
    93 "Ever breastfed, not currently breastfeeding"
    94 "Never breastfed"
    97 "Inconsistent"
    98 "Don't know"
;
label define M6      
    96 "Period not returned"
    97 "Inconsistent"
    98 "Unknown"
;
label define M7      
    97 "Inconsistent"
    98 "Unknown"
;
label define M8      
    96 "Still abstaining"
    97 "Inconsistent"
    98 "Unknown"
;
label define M9      
    97 "Inconsistent"
    98 "Unknown"
;
label define M10     
     1 "Then"
     2 "Later"
     3 "No more"
;
label define M11     
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   998 "Don't know"
;
label define M13     
    98 "Don't know"
;
label define M13A    
   101 "Weeks: 1"
   199 "Weeks: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   998 "Don't know"
;
label define M14     
     0 "No antenatal visits"
    98 "Don't know"
;
label define M15     
    10 "HOME"
    11 "Her home"
    12 "Other home"
    20 "PUBLIC SECTOR"
    21 "Government hospital"
    22 "Government polyclinic"
    23 "Government health center"
    24 "Government clinic"
    25 "CHPS center/government health post"
    26 "Community health services (outreach)"
    27 "Other public sector"
    30 "PRIVATE MEDICAL SECTOR"
    31 "Private hospital"
    32 "Private clinic"
    33 "Maternity home"
    34 "Community health services (mobile clinic)"
    35 "Other private medical sector"
    40 "NGO SECTOR"
    41 "NGO hospital/clinic"
    42 "Other NGO medical sector"
    96 "Other"
;
label define M17     
     0 "No"
     1 "Yes"
;
label define M17A    
     1 "Before labor started"
     2 "After labor started"
;
label define M18     
     1 "Very large"
     2 "Larger than average"
     3 "Average"
     4 "Smaller than average"
     5 "Very small"
     8 "Don't know"
;
label define M19     
  9996 "Not weighed at birth"
  9998 "Don't know"
;
label define M19A    
     0 "Not weighed"
     1 "From written card"
     2 "From mother's recall"
     8 "Don't know"
     9 "Special answers"
;
label define M27     
     0 "No flag"
     1 "> interval"
     2 "> interval by 1 month"
     3 "> age at death"
     4 "During pregnancy in calendar"
;
label define M28     
     0 "No flag"
     1 "> interval"
     2 "> interval by 1 month"
     4 "During pregnancy in calendar"
;
label define M29     
     0 "No flag"
     1 "> interval"
     2 "> interval by 1 month"
     4 "During pregnancy in calendar"
;
label define M34     
     0 "Immediately"
   100 "Within first hour"
   101 "Hours: 1"
   199 "Hours: number missing"
   201 "Days: 1"
   299 "Days: number missing"
;
label define M35     
    96 "On demand"
;
label define M36     
    96 "On demand"
;
label define M38     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M39A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M39     
     0 "None"
     7 "7+"
     8 "Don't know"
;
label define M42A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M42B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M42C    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M42D    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M42E    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M42F    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M42G    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M42H    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M42I    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M42J    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M42K    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M42L    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M42M    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M42N    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M43     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M44     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M45     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M46     
     0 "Were not taken"
   998 "Don't know"
;
label define M47     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M48     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49C    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49D    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49E    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49F    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49G    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49X    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49Z    
     0 "No"
     1 "Yes: don't know which drug taken"
     8 "Don't know"
;
label define M49Y    
     0 "No"
     1 "Yes, took no drug"
     8 "Don't know"
;
label define M54     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M55     
     0 "No"
     1 "Yes"
;
label define M57A    
     0 "No"
     1 "Yes"
;
label define M57B    
     0 "No"
     1 "Yes"
;
label define M57C    
     0 "No"
     1 "Yes"
;
label define M57D    
     0 "No"
     1 "Yes"
;
label define M57E    
     0 "No"
     1 "Yes"
;
label define M57F    
     0 "No"
     1 "Yes"
;
label define M57G    
     0 "No"
     1 "Yes"
;
label define M57H    
     0 "No"
     1 "Yes"
;
label define M57I    
     0 "No"
     1 "Yes"
;
label define M57J    
     0 "No"
     1 "Yes"
;
label define M57K    
     0 "No"
     1 "Yes"
;
label define M57L    
     0 "No"
     1 "Yes"
;
label define M57M    
     0 "No"
     1 "Yes"
;
label define M57N    
     0 "No"
     1 "Yes"
;
label define M57O    
     0 "No"
     1 "Yes"
;
label define M57P    
     0 "No"
     1 "Yes"
;
label define M57Q    
     0 "No"
     1 "Yes"
;
label define M57R    
     0 "No"
     1 "Yes"
;
label define M57NA   
     0 "No"
     1 "Yes"
;
label define M57NB   
     0 "No"
     1 "Yes"
;
label define M57NC   
     0 "No"
     1 "Yes"
;
label define M57ND   
     0 "No"
     1 "Yes"
;
label define M57NE   
     0 "No"
     1 "Yes"
;
label define M57S    
     0 "No"
     1 "Yes"
;
label define M57T    
     0 "No"
     1 "Yes"
;
label define M57U    
     0 "No"
     1 "Yes"
;
label define M57V    
     0 "No"
     1 "Yes"
;
label define M57X    
     0 "No"
     1 "Yes"
;
label define M60     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M61     
   100 "Hours: 0"
   101 "Hours: 1"
   199 "Hours: number missing"
   201 "Days: 1"
   299 "Days: number missing"
   301 "Weeks: 1"
   399 "Weeks: number missing"
   998 "Don't know"
;
label define M62     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M63     
   100 "Zero hours"
   201 "One day"
   301 "One week"
   998 "DK"
;
label define M64     
    10 "HEALTH PERSONNEL"
    11 "Doctor"
    12 "Nurse, midwife"
    13 "Auxiliary midwife"
    20 "OTHER PERSON"
    21 "Traditional birth attendant"
    22 "Community/village health worker"
    96 "Other"
;
label define M66     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M67     
   100 "Zero hours"
   201 "One day"
   301 "One week"
   998 "DK"
;
label define M68     
    10 "HEALTH PERSONNEL"
    11 "Doctor"
    12 "Nurse, midwife"
    13 "Auxiliary midwife"
    20 "OTHER PERSON"
    21 "Traditional birth attendant"
    22 "Community/village health worker"
    96 "Other"
;
label define M69     
    10 "HOME"
    11 "Her home"
    12 "Other home"
    20 "PUBLIC SECTOR"
    21 "Government hospital"
    22 "Government polyclinic"
    23 "Government health center"
    24 "Government clinic"
    25 "CHPS center/government health post"
    26 "Community health services (outreach)"
    27 "Other public sector"
    30 "PRIVATE MEDICAL SECTOR"
    31 "Private hospital"
    32 "Private clinic"
    33 "Maternity home"
    34 "Community health services (mobile clinic)"
    35 "Other private medical sector"
    40 "NGO SECTOR"
    41 "NGO hospital/clinic"
    42 "Other NGO medical sector"
    96 "Other"
;
label define M70     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M71     
   100 "Immediately/in first hour"
   101 "Hours: 1"
   199 "Hours: number missing"
   201 "Days: 1"
   299 "Days: number missing"
   301 "Weeks: 1"
   399 "Weeks: number missing"
   998 "Don't know"
;
label define M72     
    10 "MEDICAL PERSONNEL"
    11 "Doctor"
    12 "Nurse, midwife"
    13 "Auxiliary midwife"
    20 "OTHER PERSON"
    21 "Traditional birth attendant"
    22 "Community/village health worker"
    96 "Other"
;
label define M73     
    10 "HOME"
    11 "Her home"
    12 "Other home"
    20 "PUBLIC SECTOR"
    21 "Government hospital"
    22 "Government polyclinic"
    23 "Government health center"
    24 "Government clinic"
    25 "CHPS center/government health post"
    26 "Community health services (outreach)"
    27 "Other public sector"
    30 "PRIVATE MEDICAL SECTOR"
    31 "Private hospital"
    32 "Private clinic"
    33 "Maternity home"
    34 "Community health services (mobile clinic)"
    35 "Other private medical sector"
    40 "NGO SECTOR"
    41 "NGO hospital/clinic"
    42 "Other NGO medical sector"
    96 "Other"
;
label define M74     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M75     
   100 "Zero hours"
   201 "One day"
   301 "One week"
   998 "DK"
;
label define M76     
    10 "HEALTH PERSONNEL"
    11 "Doctor"
    12 "Nurse, midwife"
    13 "Auxiliary midwife"
    20 "OTHER PERSON"
    21 "Traditional birth attendant"
    22 "Community/village health worker"
    96 "Other"
;
label define M77     
     0 "No"
     1 "Put on chest, touching bare skin"
     2 "Put on chest, no touching of bare skin"
     3 "Put on chest, DK/Missing on touching of bare skin"
     8 "Don't know"
;
label define M77A    
     0 "Immediately"
    24 "24+"
    98 "Don't know"
;
label define M78A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M78B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M78C    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M78D    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M78E    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M78F    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M78G    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M78H    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M78I    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M78J    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M78K    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M78L    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M78M    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M78N    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M78O    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M78P    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M80     
     1 "Most recent live birth"
     2 "Prior live birth"
     3 "Most recent stillbirth"
     4 "Prior stillbirth"
     5 "Miscarriage/abortion"
;
label define M81A    
     0 "No"
     1 "Yes"
;
label define M81B    
     0 "No"
     1 "Yes"
;
label define M81C    
     0 "No"
     1 "Yes"
;
label define M81D    
     0 "No"
     1 "Yes"
;
label define M81E    
     0 "No"
     1 "Yes"
;
label define M81F    
     0 "No"
     1 "Yes"
;
label define M81G    
     0 "No"
     1 "Yes"
;
label define M81H    
     0 "No"
     1 "Yes"
;
label define M81I    
     0 "No"
     1 "Yes"
;
label define M81J    
     0 "No"
     1 "Yes"
;
label define M81K    
     0 "No"
     1 "Yes"
;
label define M81L    
     0 "No"
     1 "Yes"
;
label define M81M    
     0 "No"
     1 "Yes"
;
label define M81N    
     0 "No"
     1 "Yes"
;
label define M81O    
     0 "No"
     1 "Yes"
;
label define M81P    
     0 "No"
     1 "Yes"
;
label define M81Q    
     0 "No"
     1 "Yes"
;
label define M81R    
     0 "No"
     1 "Yes"
;
label define M81NA   
     0 "No"
     1 "Yes"
;
label define M81NB   
     0 "No"
     1 "Yes"
;
label define M81NC   
     0 "No"
     1 "Yes"
;
label define M81ND   
     0 "No"
     1 "Yes"
;
label define M81NE   
     0 "No"
     1 "Yes"
;
label define M81S    
     0 "No"
     1 "Yes"
;
label define M81T    
     0 "No"
     1 "Yes"
;
label define M81U    
     0 "No"
     1 "Yes"
;
label define M81V    
     0 "No"
     1 "Yes"
;
label define M81W    
     0 "No"
     1 "Yes"
;
label define M81X    
     0 "No"
     1 "Yes"
;
label define M82     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define ML0     
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define ML1     
    98 "Don't know"
;
label define ML2     
     1 "Antenatal visit"
     2 "Another facility visit"
     6 "Other source"
;
label define MNB1    
     0 "Immediately"
   100 "Within first hour"
   101 "Hours: 1"
   199 "Hours: number missing"
   201 "Days: 1"
   299 "Days: number missing"
;
label define MNB3    
     1 "Razor blade"
     2 "Knife"
     3 "Scissors"
     6 "Other"
     8 "Don't know"
;
label define MNB4    
     1 "New"
     2 "Used before"
     8 "Don't know"
;
label define MNB5    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MNB6    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MNB7A   
     0 "No"
     1 "Yes"
;
label define MNB7B   
     0 "No"
     1 "Yes"
;
label define MNB7C   
     0 "No"
     1 "Yes"
;
label define MNB7D   
     0 "No"
     1 "Yes"
;
label define MNB7E   
     0 "No"
     1 "Yes"
;
label define MNB7F   
     0 "No"
     1 "Yes"
;
label define MNB7G   
     0 "No"
     1 "Yes"
;
label define MNB7H   
     0 "No"
     1 "Yes"
;
label define MNB7I   
     0 "No"
     1 "Yes"
;
label define MNB7J   
     0 "No"
     1 "Yes"
;
label define MNB7X   
     0 "No"
     1 "Yes"
;
label define MNB7Z   
     0 "No"
     1 "Yes"
;
label define MNB10   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MNB11   
     0 "Immediately"
   100 "Within first hour"
   101 "Hours: 1"
   199 "Hours: number missing"
   201 "Days: 1"
   299 "Days: number missing"
;
label define MNB12   
     7 "7+"
     8 "Don't know"
;
label define MH3A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH3B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH3C    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH3D    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH3E    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH3F    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH3G    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH3H    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH3I    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH5     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH6     
     0 "No"
     1 "Yes"
     2 "No labor/planned caesarean section"
;
label define MH7     
     0 "No"
     1 "Yes"
;
label define MH8     
     1 "Some of the time"
     2 "Most of the time"
     3 "All of the time"
;
label define MH9     
     1 "Facility did not allow"
     2 "Absent for other reason"
     8 "Don't know"
;
label define MH10    
     0 "No"
     1 "Yes"
;
label define MH11    
     0 "No"
     1 "Yes"
;
label define MH12    
     1 "Some of the time"
     2 "Most of the time"
     3 "All of the time"
;
label define MH13    
     1 "Facility did not allow"
     2 "Absent for other reason"
     8 "Don't know"
;
label define MH14    
     0 "No"
     1 "Yes, forceps"
     2 "Yes, suction"
     3 "Yes, don't know what instrument"
     8 "Don't know"
;
label define MH15    
     1 "Facility did not allow"
     2 "Absent for other reason"
     8 "Don't know"
;
label define MH16    
     0 "No"
     1 "Yes, separate room"
     2 "Yes, curtains"
     6 "Yes, other"
     8 "Don't know"
;
label define MH17A   
     0 "Not at all"
     1 "All of the time"
     2 "Some of the time"
;
label define MH17B   
     0 "Not at all"
     1 "All of the time"
     2 "Some of the time"
;
label define MH17C   
     0 "Not at all"
     1 "All of the time"
     2 "Some of the time"
;
label define MH17D   
     0 "Not at all"
     1 "All of the time"
     2 "Some of the time"
;
label define MH17E   
     0 "Not at all"
     1 "All of the time"
     2 "Some of the time"
;
label define MH18A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH18B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH18C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH18D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH19    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH20    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH21A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH21B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH21C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH21D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH21E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH21F   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH22A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH22B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH22C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH22D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH22E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH22F   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH23    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH24    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MH25    
     1 "Same room"
     2 "Separate room"
     8 "Don't know"
;
label define S114    
     0 "No education"
     1 "Pre-primary"
     2 "Primary"
     3 "Middle"
     4 "JSS/JHS"
     5 "Secondary"
     6 "SSS/SHS"
     7 "Higher"
     8 "Don't know"
;
label define S115    
     0 "Less than one year"
;
label define S904    
     0 "No education"
     1 "Pre-primary"
     2 "Primary"
     3 "Middle"
     4 "JSS/JHS"
     5 "Secondary"
     6 "SSS/SHS"
     7 "Higher"
     8 "Don't know"
;
label define S905    
     0 "Less than one year"
    98 "Don't know"
;
label define S1116   
     0 "No"
     1 "Yes"
;
label define S1117A  
     0 "No"
     1 "Yes"
;
label define S1117B  
     0 "No"
     1 "Yes"
;
label define S1117C  
     0 "No"
     1 "Yes"
;
label define S1117D  
     0 "No"
     1 "Yes"
;
label define S1117E  
     0 "No"
     1 "Yes"
;
label define S1117F  
     0 "No"
     1 "Yes"
;
label define S1117G  
     0 "No"
     1 "Yes"
;
label define S1117H  
     0 "No"
     1 "Yes"
;
label define S1117I  
     0 "No"
     1 "Yes"
;
label define S1117J  
     0 "No"
     1 "Yes"
;
label define S1117K  
     0 "No"
     1 "Yes"
;
label define S1117L  
     0 "No"
     1 "Yes"
;
label define S1117X  
     0 "No"
     1 "Yes"
;
label define S1118B  
     0 "No"
     1 "Yes"
;
label define S1118C  
     0 "No"
     1 "Yes"
;
label define S1118D  
     0 "No"
     1 "Yes"
;
label define S1118E  
     0 "No"
     1 "Yes"
;
label define S1118F  
     0 "No"
     1 "Yes"
;
label define S1118G  
     0 "No"
     1 "Yes"
;
label define S1118H  
     0 "No"
     1 "Yes"
;
label define S1118I  
     0 "No"
     1 "Yes"
;
label define S1118J  
     0 "No"
     1 "Yes"
;
label define S1118K  
     0 "No"
     1 "Yes"
;
label define S1118L  
     0 "No"
     1 "Yes"
;
label define S1118M  
     0 "No"
     1 "Yes"
;
label define S1118X  
     0 "No"
     1 "Yes"
;
label define S1119   
     1 "Yes, card seen"
     2 "Yes, card not seen"
     3 "No"
;
label define S1120A  
     0 "No"
     1 "Yes"
;
label define S1120B  
     0 "No"
     1 "Yes"
;
label define S1120C  
     0 "No"
     1 "Yes"
;
label define S1120D  
     0 "No"
     1 "Yes"
;
label define S1120E  
     0 "No"
     1 "Yes"
;
label define S1120X  
     0 "No"
     1 "Yes"
;
label define S1121   
     0 "None"
    98 "Don't know"
;
label define S1122   
     0 "None"
    98 "Don't know"
;
label define S1123A1 
     0 "No"
     1 "Yes"
;
label define S1123A2 
     1 "Copayment"
     2 "Full payment"
     3 "Don't remember"
;
label define S1123B1 
     0 "No"
     1 "Yes"
;
label define S1123B2 
     1 "Copayment"
     2 "Full payment"
     3 "Don't remember"
;
label define S1123C1 
     0 "No"
     1 "Yes"
;
label define S1123C2 
     1 "Copayment"
     2 "Full payment"
     3 "Don't remember"
;
label define S1123D1 
     0 "No"
     1 "Yes"
;
label define S1123D2 
     1 "Copayment"
     2 "Full payment"
     3 "Don't remember"
;
label define S1123E1 
     0 "No"
     1 "Yes"
;
label define S1123E2 
     1 "Copayment"
     2 "Full payment"
     3 "Don't remember"
;
label define S1123F1 
     0 "No"
     1 "Yes"
;
label define S1123F2 
     1 "Copayment"
     2 "Full payment"
     3 "Don't remember"
;
label define S1202AA 
     0 "No"
     1 "Yes, TV"
     2 "Yes, radio"
     3 "Yes, TV and radio"
;
label define S1202AB 
     0 "No"
     1 "Yes, TV"
     2 "Yes, radio"
     3 "Yes, TV and radio"
;
label define S1202AC 
     0 "No"
     1 "Yes, TV"
     2 "Yes, radio"
     3 "Yes, TV and radio"
;
label define S1214A  
     0 "No"
     1 "Yes"
;
label define S1214BA 
     0 "No"
     1 "Yes"
;
label define S1214BB 
     0 "No"
     1 "Yes"
;
label define S1214BC 
     0 "No"
     1 "Yes"
;
label define S1214BD 
     0 "No"
     1 "Yes"
;
label define S1214BE 
     0 "No"
     1 "Yes"
;
label define S1214BF 
     0 "No"
     1 "Yes"
;
label define S1214BG 
     0 "No"
     1 "Yes"
;
label define S1214BH 
     0 "No"
     1 "Yes"
;
label define S1214BI 
     0 "No"
     1 "Yes"
;
label define S1214BJ 
     0 "No"
     1 "Yes"
;
label define S1214BX 
     0 "No"
     1 "Yes"
;
label define S1214BZ 
     0 "No"
     1 "Yes"
;
label define S1337B  
     0 "No"
     1 "Yes"
;
label define IDX94   
     0 "Not a live birth"
;
label define S432BA  
     0 "No"
     1 "Yes"
;
label define S432BB  
     0 "No"
     1 "Yes"
;
label define S432BC  
     0 "No"
     1 "Yes"
;
label define S432BD  
     0 "No"
     1 "Yes"
;
label define S432BE  
     0 "No"
     1 "Yes"
;
label define S432BF  
     0 "No"
     1 "Yes"
;
label define S432BG  
     0 "No"
     1 "Yes"
;
label define S432BX  
     0 "No"
     1 "Yes"
;
label define S432BZ  
     0 "No"
     1 "Yes"
;

#delimit cr
label values v013     V013    
label values v014     V014    
label values v015     V015    
label values v018     V018    
label values v019     V019    
label values v019a    V019A   
label values v020     V020    
label values v022     V022    
label values v023     V023    
label values v024     V024    
label values v025     V025    
label values v026     V026    
label values v034     V034    
label values v042     V042    
label values v044     V044    
label values v045a    V045A   
label values v045b    V045B   
label values v045c    V045C   
label values v046     V046    
label values v101     V101    
label values v102     V102    
label values v103     V103    
label values v104     V104    
label values v105     V105    
label values v105a    V105A   
label values v106     V106    
label values v107     V107    
label values v113     V113    
label values v115     V115    
label values v116     V116    
label values v119     V119    
label values v120     V120    
label values v121     V121    
label values v122     V122    
label values v123     V123    
label values v124     V124    
label values v125     V125    
label values v127     V127    
label values v128     V128    
label values v129     V129    
label values v130     V130    
label values v131     V131    
label values v133     V133    
label values v134     V134    
label values v135     V135    
label values v139     V139    
label values v140     V140    
label values v141     V141    
label values v149     V149    
label values v150     V150    
label values v151     V151    
label values v152     V152    
label values v153     V153    
label values v155     V155    
label values v156     V156    
label values v157     V157    
label values v158     V158    
label values v159     V159    
label values v160     V160    
label values v161     V161    
label values v166     V166    
label values v167     V167    
label values v168     V168    
label values v169a    V169A   
label values v169b    V169B   
label values v169c    V169C   
label values v170     V170    
label values v171a    V171A   
label values v171b    V171B   
label values v172     V172    
label values v173     V173    
label values v174m    V174M   
label values v174y    V174Y   
label values v175     V175    
label values v176     V176    
label values v177     V177    
label values v190     V190    
label values v190a    V190A   
label values ml101    ML101   
label values v208     V208    
label values v209     V209    
label values v213     V213    
label values v214a    V214A   
label values v215     V215    
label values v216     V216    
label values v217     V217    
label values v220     V220    
label values v221     V221    
label values v223     V223    
label values v225     V225    
label values v226     V226    
label values v227     V227    
label values v228     V228    
label values v229     V229    
label values v230     V230    
label values v231     V231    
label values v232     V232    
label values v233     V233    
label values v234     V234    
label values v235     V235    
label values v237     V237    
label values v239     V239    
label values v240     V240    
label values v241     V241    
label values v242     V242    
label values v243     V243    
label values v244     V244    
label values v247a    V247A   
label values v247b    V247B   
label values v247c    V247C   
label values v247d    V247D   
label values v247e    V247E   
label values v247f    V247F   
label values v247g    V247G   
label values v247h    V247H   
label values v247i    V247I   
label values v247j    V247J   
label values v247k    V247K   
label values v247l    V247L   
label values v247x    V247X   
label values v247y    V247Y   
label values v248     V248    
label values v249     V249    
label values v311     V311    
label values v312     V312    
label values v313     V313    
label values v318     V318    
label values v319     V319    
label values v320     V320    
label values v321     V321    
label values v321a    V321A   
label values v322     V322    
label values v323     V323    
label values v323a    V323A   
label values v325a    V325A   
label values v326     V326    
label values v327     V327    
label values v337     V337    
label values v359     V359    
label values v360     V360    
label values v361     V361    
label values v362     V362    
label values v363     V363    
label values v364     V364    
label values v367     V367    
label values v367a    V367A   
label values v372     V372    
label values v372a    V372A   
label values v375a    V375A   
label values v376     V376    
label values v376a    V376A   
label values v379     V379    
label values v380     V380    
label values v384a    V384A   
label values v384b    V384B   
label values v384c    V384C   
label values v384d    V384D   
label values v384e    V384E   
label values v384f    V384F   
label values v384g    V384G   
label values v384h    V384H   
label values v384i    V384I   
label values v384j    V384J   
label values v384k    V384K   
label values v393     V393    
label values v393a    V393A   
label values v394     V394    
label values v395     V395    
label values v3a00a   V3A00A  
label values v3a00b   V3A00B  
label values v3a00c   V3A00C  
label values v3a00d   V3A00D  
label values v3a00e   V3A00E  
label values v3a00f   V3A00F  
label values v3a00g   V3A00G  
label values v3a00h   V3A00H  
label values v3a00i   V3A00I  
label values v3a00j   V3A00J  
label values v3a00k   V3A00K  
label values v3a00l   V3A00L  
label values v3a00m   V3A00M  
label values v3a00n   V3A00N  
label values v3a00o   V3A00O  
label values v3a00p   V3A00P  
label values v3a00q   V3A00Q  
label values v3a00r   V3A00R  
label values v3a00s   V3A00S  
label values v3a00t   V3A00T  
label values v3a00u   V3A00U  
label values v3a00v   V3A00V  
label values v3a00w   V3A00W  
label values v3a00x   V3A00X  
label values v3a00y   V3A00Y  
label values v3a00z   V3A00Z  
label values v3a01    V3A01   
label values v3a02    V3A02   
label values v3a03    V3A03   
label values v3a04    V3A04   
label values v3a05    V3A05   
label values v3a06    V3A06   
label values v3a07    V3A07   
label values v3a08a   V3A08A  
label values v3a08b   V3A08B  
label values v3a08c   V3A08C  
label values v3a08d   V3A08D  
label values v3a08e   V3A08E  
label values v3a08f   V3A08F  
label values v3a08g   V3A08G  
label values v3a08h   V3A08H  
label values v3a08i   V3A08I  
label values v3a08j   V3A08J  
label values v3a08k   V3A08K  
label values v3a08l   V3A08L  
label values v3a08m   V3A08M  
label values v3a08n   V3A08N  
label values v3a08o   V3A08O  
label values v3a08p   V3A08P  
label values v3a08q   V3A08Q  
label values v3a08r   V3A08R  
label values v3a08s   V3A08S  
label values v3a08t   V3A08T  
label values v3a08u   V3A08U  
label values v3a08v   V3A08V  
label values v3a08w   V3A08W  
label values v3a08aa  V3A08AA 
label values v3a08ab  V3A08AB 
label values v3a08ac  V3A08AC 
label values v3a08ad  V3A08AD 
label values v3a08ae  V3A08AE 
label values v3a08af  V3A08AF 
label values v3a08x   V3A08X  
label values v3a08z   V3A08Z  
label values v3a09a   V3A09A  
label values v3a09b   V3A09B  
label values v3a10    V3A10   
label values v3a11    V3A11   
label values v3a12    V3A12   
label values v3a13    V3A13   
label values v3a14    V3A14   
label values v401     V401    
label values v404     V404    
label values v405     V405    
label values v406     V406    
label values v407     V407    
label values v408     V408    
label values v415     V415    
label values v416     V416    
label values v426     V426    
label values v437     V437    
label values v438     V438    
label values v445     V445    
label values v447     V447    
label values v446a    V446A   
label values v446d    V446D   
label values v452a    V452A   
label values v452b    V452B   
label values v452c    V452C   
label values v453     V453    
label values v454     V454    
label values v455     V455    
label values v457     V457    
label values v458     V458    
label values v459     V459    
label values v460     V460    
label values v461     V461    
label values v462     V462    
label values v463a    V463A   
label values v463b    V463B   
label values v463c    V463C   
label values v463d    V463D   
label values v463e    V463E   
label values v463f    V463F   
label values v463g    V463G   
label values v463h    V463H   
label values v463i    V463I   
label values v463j    V463J   
label values v463k    V463K   
label values v463l    V463L   
label values v463x    V463X   
label values v463z    V463Z   
label values v463aa   V463AA  
label values v463ab   V463AB  
label values v464     V464    
label values v466     V466    
label values v467a    V467A   
label values v467b    V467B   
label values v467c    V467C   
label values v467d    V467D   
label values v467e    V467E   
label values v467f    V467F   
label values v467g    V467G   
label values v467h    V467H   
label values v467i    V467I   
label values v467j    V467J   
label values v467k    V467K   
label values v467l    V467L   
label values v467m    V467M   
label values v468     V468    
label values v471a    V471A   
label values v471b    V471B   
label values v471c    V471C   
label values v471cs   V471CS  
label values v471d    V471D   
label values v471e    V471E   
label values v471f    V471F   
label values v471g    V471G   
label values v471h    V471H   
label values v471i    V471I   
label values v472a    V472A   
label values v472b    V472B   
label values v472c    V472C   
label values v472d    V472D   
label values v472e    V472E   
label values v472f    V472F   
label values v472g    V472G   
label values v472h    V472H   
label values v472i    V472I   
label values v472j    V472J   
label values v472k    V472K   
label values v472l    V472L   
label values v472m    V472M   
label values v472n    V472N   
label values v472o    V472O   
label values v472p    V472P   
label values v472q    V472Q   
label values v472r    V472R   
label values v472s    V472S   
label values v472t    V472T   
label values v472u    V472U   
label values v472v    V472V   
label values v472w    V472W   
label values v472wa   V472WA  
label values v472wb   V472WB  
label values v472wc   V472WC  
label values v472wd   V472WD  
label values v472we   V472WE  
label values v473a    V473A   
label values v473b    V473B   
label values v477     V477    
label values v478     V478    
label values v479     V479    
label values v480     V480    
label values v481     V481    
label values v481a    V481A   
label values v481b    V481B   
label values v481c    V481C   
label values v481d    V481D   
label values v481e    V481E   
label values v481f    V481F   
label values v481g    V481G   
label values v481h    V481H   
label values v481x    V481X   
label values v482a    V482A   
label values v482b    V482B   
label values v482c    V482C   
label values v483a    V483A   
label values v483b    V483B   
label values v484a    V484A   
label values v484b    V484B   
label values v485a    V485A   
label values v485b    V485B   
label values v501     V501    
label values v502     V502    
label values v503     V503    
label values v504     V504    
label values v505     V505    
label values v506     V506    
label values v510     V510    
label values v510a    V510A   
label values v513     V513    
label values v525     V525    
label values v527     V527    
label values v528     V528    
label values v529     V529    
label values v530     V530    
label values v531     V531    
label values v532     V532    
label values v535     V535    
label values v536     V536    
label values v537     V537    
label values v538     V538    
label values v539     V539    
label values v540     V540    
label values v541     V541    
label values v542     V542    
label values v543a    V543A   
label values v543b    V543B   
label values v543c    V543C   
label values v543d    V543D   
label values v543e    V543E   
label values v543f    V543F   
label values v543g    V543G   
label values v543x    V543X   
label values v544     V544    
label values v602     V602    
label values v603     V603    
label values v604     V604    
label values v605     V605    
label values v613     V613    
label values v614     V614    
label values v616     V616    
label values v621     V621    
label values v623     V623    
label values v624     V624    
label values v625     V625    
label values v626     V626    
label values v625a    V625A   
label values v626a    V626A   
label values v627     V627    
label values v628     V628    
label values v629     V629    
label values v631     V631    
label values v632     V632    
label values v632a    V632A   
label values v633a    V633A   
label values v633b    V633B   
label values v633c    V633C   
label values v633d    V633D   
label values v633e    V633E   
label values v633f    V633F   
label values v633g    V633G   
label values v634     V634    
label values v635     V635    
label values v636     V636    
label values v701     V701    
label values v702     V702    
label values v704     V704    
label values v704a    V704A   
label values v705     V705    
label values v714     V714    
label values v714a    V714A   
label values v715     V715    
label values v716     V716    
label values v717     V717    
label values v719     V719    
label values v721     V721    
label values v729     V729    
label values v730     V730    
label values v731     V731    
label values v732     V732    
label values v739     V739    
label values v740     V740    
label values v741     V741    
label values v743a    V743A   
label values v743b    V743B   
label values v743c    V743C   
label values v743d    V743D   
label values v743e    V743E   
label values v743f    V743F   
label values v744a    V744A   
label values v744b    V744B   
label values v744c    V744C   
label values v744d    V744D   
label values v744e    V744E   
label values v745a    V745A   
label values v745b    V745B   
label values v745c    V745C   
label values v745d    V745D   
label values v746     V746    
label values pidxb    PIDXB   
label values p0       P0      
label values p4       P4      
label values p5       P5      
label values p6       P6      
label values p9       P9      
label values p10      P10     
label values p13      P13     
label values p15      P15     
label values p16      P16     
label values p30      P30     
label values p31      P31     
label values p32      P32     
label values midx     MIDX    
label values m1       M1      
label values m1a      M1A     
label values m1b      M1B     
label values m1c      M1C     
label values m1e      M1E     
label values m2a      M2A     
label values m2b      M2B     
label values m2c      M2C     
label values m2d      M2D     
label values m2e      M2E     
label values m2f      M2F     
label values m2g      M2G     
label values m2h      M2H     
label values m2i      M2I     
label values m2j      M2J     
label values m2k      M2K     
label values m2l      M2L     
label values m2m      M2M     
label values m2n      M2N     
label values m3a      M3A     
label values m3b      M3B     
label values m3c      M3C     
label values m3d      M3D     
label values m3e      M3E     
label values m3f      M3F     
label values m3g      M3G     
label values m3h      M3H     
label values m3i      M3I     
label values m3j      M3J     
label values m3k      M3K     
label values m3l      M3L     
label values m3m      M3M     
label values m3n      M3N     
label values m4       M4      
label values m5       M5      
label values m6       M6      
label values m7       M7      
label values m8       M8      
label values m9       M9      
label values m10      M10     
label values m11      M11     
label values m13      M13     
label values m13a     M13A    
label values m14      M14     
label values m15      M15     
label values m17      M17     
label values m17a     M17A    
label values m18      M18     
label values m19      M19     
label values m19a     M19A    
label values m27      M27     
label values m28      M28     
label values m29      M29     
label values m34      M34     
label values m35      M35     
label values m36      M36     
label values m38      M38     
label values m39a     M39A    
label values m39      M39     
label values m42a     M42A    
label values m42b     M42B    
label values m42c     M42C    
label values m42d     M42D    
label values m42e     M42E    
label values m42f     M42F    
label values m42g     M42G    
label values m42h     M42H    
label values m42i     M42I    
label values m42j     M42J    
label values m42k     M42K    
label values m42l     M42L    
label values m42m     M42M    
label values m42n     M42N    
label values m43      M43     
label values m44      M44     
label values m45      M45     
label values m46      M46     
label values m47      M47     
label values m48      M48     
label values m49a     M49A    
label values m49b     M49B    
label values m49c     M49C    
label values m49d     M49D    
label values m49e     M49E    
label values m49f     M49F    
label values m49g     M49G    
label values m49x     M49X    
label values m49z     M49Z    
label values m49y     M49Y    
label values m54      M54     
label values m55      M55     
label values m57a     M57A    
label values m57b     M57B    
label values m57c     M57C    
label values m57d     M57D    
label values m57e     M57E    
label values m57f     M57F    
label values m57g     M57G    
label values m57h     M57H    
label values m57i     M57I    
label values m57j     M57J    
label values m57k     M57K    
label values m57l     M57L    
label values m57m     M57M    
label values m57n     M57N    
label values m57o     M57O    
label values m57p     M57P    
label values m57q     M57Q    
label values m57r     M57R    
label values m57na    M57NA   
label values m57nb    M57NB   
label values m57nc    M57NC   
label values m57nd    M57ND   
label values m57ne    M57NE   
label values m57s     M57S    
label values m57t     M57T    
label values m57u     M57U    
label values m57v     M57V    
label values m57x     M57X    
label values m60      M60     
label values m61      M61     
label values m62      M62     
label values m63      M63     
label values m64      M64     
label values m66      M66     
label values m67      M67     
label values m68      M68     
label values m69      M69     
label values m70      M70     
label values m71      M71     
label values m72      M72     
label values m73      M73     
label values m74      M74     
label values m75      M75     
label values m76      M76     
label values m77      M77     
label values m77a     M77A    
label values m78a     M78A    
label values m78b     M78B    
label values m78c     M78C    
label values m78d     M78D    
label values m78e     M78E    
label values m78f     M78F    
label values m78g     M78G    
label values m78h     M78H    
label values m78i     M78I    
label values m78j     M78J    
label values m78k     M78K    
label values m78l     M78L    
label values m78m     M78M    
label values m78n     M78N    
label values m78o     M78O    
label values m78p     M78P    
label values m80      M80     
label values m81a     M81A    
label values m81b     M81B    
label values m81c     M81C    
label values m81d     M81D    
label values m81e     M81E    
label values m81f     M81F    
label values m81g     M81G    
label values m81h     M81H    
label values m81i     M81I    
label values m81j     M81J    
label values m81k     M81K    
label values m81l     M81L    
label values m81m     M81M    
label values m81n     M81N    
label values m81o     M81O    
label values m81p     M81P    
label values m81q     M81Q    
label values m81r     M81R    
label values m81na    M81NA   
label values m81nb    M81NB   
label values m81nc    M81NC   
label values m81nd    M81ND   
label values m81ne    M81NE   
label values m81s     M81S    
label values m81t     M81T    
label values m81u     M81U    
label values m81v     M81V    
label values m81w     M81W    
label values m81x     M81X    
label values m82      M82     
label values ml0      ML0     
label values ml1      ML1     
label values ml2      ML2     
label values mnb1     MNB1    
label values mnb3     MNB3    
label values mnb4     MNB4    
label values mnb5     MNB5    
label values mnb6     MNB6    
label values mnb7a    MNB7A   
label values mnb7b    MNB7B   
label values mnb7c    MNB7C   
label values mnb7d    MNB7D   
label values mnb7e    MNB7E   
label values mnb7f    MNB7F   
label values mnb7g    MNB7G   
label values mnb7h    MNB7H   
label values mnb7i    MNB7I   
label values mnb7j    MNB7J   
label values mnb7x    MNB7X   
label values mnb7z    MNB7Z   
label values mnb10    MNB10   
label values mnb11    MNB11   
label values mnb12    MNB12   
label values mh3a     MH3A    
label values mh3b     MH3B    
label values mh3c     MH3C    
label values mh3d     MH3D    
label values mh3e     MH3E    
label values mh3f     MH3F    
label values mh3g     MH3G    
label values mh3h     MH3H    
label values mh3i     MH3I    
label values mh5      MH5     
label values mh6      MH6     
label values mh7      MH7     
label values mh8      MH8     
label values mh9      MH9     
label values mh10     MH10    
label values mh11     MH11    
label values mh12     MH12    
label values mh13     MH13    
label values mh14     MH14    
label values mh15     MH15    
label values mh16     MH16    
label values mh17a    MH17A   
label values mh17b    MH17B   
label values mh17c    MH17C   
label values mh17d    MH17D   
label values mh17e    MH17E   
label values mh18a    MH18A   
label values mh18b    MH18B   
label values mh18c    MH18C   
label values mh18d    MH18D   
label values mh19     MH19    
label values mh20     MH20    
label values mh21a    MH21A   
label values mh21b    MH21B   
label values mh21c    MH21C   
label values mh21d    MH21D   
label values mh21e    MH21E   
label values mh21f    MH21F   
label values mh22a    MH22A   
label values mh22b    MH22B   
label values mh22c    MH22C   
label values mh22d    MH22D   
label values mh22e    MH22E   
label values mh22f    MH22F   
label values mh23     MH23    
label values mh24     MH24    
label values mh25     MH25    
label values s114     S114    
label values s115     S115    
label values s904     S904    
label values s905     S905    
label values s1116    S1116   
label values s1117a   S1117A  
label values s1117b   S1117B  
label values s1117c   S1117C  
label values s1117d   S1117D  
label values s1117e   S1117E  
label values s1117f   S1117F  
label values s1117g   S1117G  
label values s1117h   S1117H  
label values s1117i   S1117I  
label values s1117j   S1117J  
label values s1117k   S1117K  
label values s1117l   S1117L  
label values s1117x   S1117X  
label values s1118b   S1118B  
label values s1118c   S1118C  
label values s1118d   S1118D  
label values s1118e   S1118E  
label values s1118f   S1118F  
label values s1118g   S1118G  
label values s1118h   S1118H  
label values s1118i   S1118I  
label values s1118j   S1118J  
label values s1118k   S1118K  
label values s1118l   S1118L  
label values s1118m   S1118M  
label values s1118x   S1118X  
label values s1119    S1119   
label values s1120a   S1120A  
label values s1120b   S1120B  
label values s1120c   S1120C  
label values s1120d   S1120D  
label values s1120e   S1120E  
label values s1120x   S1120X  
label values s1121    S1121   
label values s1122    S1122   
label values s1123a1  S1123A1 
label values s1123a2  S1123A2 
label values s1123b1  S1123B1 
label values s1123b2  S1123B2 
label values s1123c1  S1123C1 
label values s1123c2  S1123C2 
label values s1123d1  S1123D1 
label values s1123d2  S1123D2 
label values s1123e1  S1123E1 
label values s1123e2  S1123E2 
label values s1123f1  S1123F1 
label values s1123f2  S1123F2 
label values s1202aa  S1202AA 
label values s1202ab  S1202AB 
label values s1202ac  S1202AC 
label values s1214a   S1214A  
label values s1214ba  S1214BA 
label values s1214bb  S1214BB 
label values s1214bc  S1214BC 
label values s1214bd  S1214BD 
label values s1214be  S1214BE 
label values s1214bf  S1214BF 
label values s1214bg  S1214BG 
label values s1214bh  S1214BH 
label values s1214bi  S1214BI 
label values s1214bj  S1214BJ 
label values s1214bx  S1214BX 
label values s1214bz  S1214BZ 
label values s1337b   S1337B  
label values idx94    IDX94   
label values s432ba   S432BA  
label values s432bb   S432BB  
label values s432bc   S432BC  
label values s432bd   S432BD  
label values s432be   S432BE  
label values s432bf   S432BF  
label values s432bg   S432BG  
label values s432bx   S432BX  
label values s432bz   S432BZ  
