infix using "C:\COUNTRIES\NG71\NGPR71FL.dct"

label variable hhid     "Case Identification"
label variable hvidx    "Line number"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv011    "NA - Number of eligible men in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "Household selected for male interview"
label variable hv028    "Household weight for male subsample (6 decimals)"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv035    "Number of eligible children for height and weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "NA - Total adults measured"
label variable hv042    "Household selected for hemoglobin"
label variable hv044    "NA - Household selected for Domestic Violence module"
label variable chla     "NA - Number of de-jure children 5-14 for child labor module"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "Has mosquito bed net for sleeping"
label variable hv228    "Children under 5 slept under mosquito bed net last night"
label variable hv230a   "NA - Place where household members wash their hands"
label variable hv230b   "NA - Presence of water at hand washing place"
label variable hv232    "NA - Items present: Soap or detergent"
label variable hv232b   "NA - Items present: Ash, mud, sand"
label variable hv232c   "NA - Items present: CS"
label variable hv232d   "NA - Items present: CS"
label variable hv232e   "NA - Items present: CS"
label variable hv232y   "NA - Items present: None"
label variable hv234    "NA - Result of salt test for iodine (PPM)"
label variable hv234a   "NA - Result of salt test for iodine"
label variable hv235    "Location of source for water"
label variable hv236    "NA - Person fetching water"
label variable hv237    "NA - Anything done to water to make safe to drink"
label variable hv237a   "NA - Water usually treated by: boil"
label variable hv237b   "NA - Water usually treated by: add bleach/chlorine"
label variable hv237c   "NA - Water usually treated by: strain through a cloth"
label variable hv237d   "NA - Water usually treated by: use water filter"
label variable hv237e   "NA - Water usually treated by: solar disinfection"
label variable hv237f   "NA - Water usually treated by: let it stand and settle"
label variable hv237g   "NA - Water usually treated by: CS"
label variable hv237h   "NA - Water usually treated by: CS"
label variable hv237i   "NA - Water usually treated by: CS"
label variable hv237j   "NA - Water usually treated by: CS"
label variable hv237k   "NA - Water usually treated by: CS"
label variable hv237x   "NA - Water usually treated by: other"
label variable hv237z   "NA - Water usually treated by: don't know"
label variable hv238    "Number of households sharing toilet"
label variable hv239    "NA - Food cooked on stove or open fire"
label variable hv240    "NA - Household has a chimney, hood or neither"
label variable hv241    "NA - Food cooked in the house/ separate building/ outdoors"
label variable hv242    "NA - Household has separate room used as kitchen"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "Has watch"
label variable hv243c   "Has animal-drawn cart"
label variable hv243d   "Has boat with a motor"
label variable hv244    "Owns land usable for agriculture"
label variable hv245    "Hectares of agricultural land (1 decimal)"
label variable hv246    "Owns livestock, herds or farm animals"
label variable hv246a   "Owns cattle"
label variable hv246b   "Owns cows/ bulls"
label variable hv246c   "Owns horses/ donkeys/ mules"
label variable hv246d   "Owns goats"
label variable hv246e   "Owns sheep"
label variable hv246f   "Owns chickens"
label variable hv246g   "NA - Owns CS"
label variable hv246h   "NA - Owns CS"
label variable hv246i   "NA - Owns CS"
label variable hv246j   "NA - Owns CS"
label variable hv246k   "NA - Owns CS"
label variable hv247    "Has bank account"
label variable hv252    "NA - Frequency household members smoke inside the house"
label variable hv253    "Has dwelling been sprayed against mosquitoes in last 12 months"
label variable hv253a   "Dwelling sprayed by: government worker/program"
label variable hv253b   "Dwelling sprayed by: private company"
label variable hv253c   "Dwelling sprayed by: NGO"
label variable hv253d   "NA - Dwelling sprayed by: CS"
label variable hv253e   "NA - Dwelling sprayed by: CS"
label variable hv253f   "NA - Dwelling sprayed by: CS"
label variable hv253g   "NA - Dwelling sprayed by: CS"
label variable hv253h   "NA - Dwelling sprayed by: CS"
label variable hv253x   "Dwelling sprayed by: other"
label variable hv253z   "Dwelling sprayed by: don't know"
label variable hv270    "Wealth index"
label variable hv271    "Wealth index factor score (5 decimals)"
label variable hv270a   "Wealth index for urban/rural"
label variable hv271a   "Wealth index factor score for urban/rural (5 decimals)"
label variable hml1     "Number of mosquito bed nets"
label variable hml1a    "Number of mosquito bed nets with specific information"
label variable hml2     "Number of children under mosquito bed net previous night"
label variable shstate  "State"
label variable shlangint "Language of interview"
label variable shlangnat "Native language of respondent"
label variable shtransl "Translator used"
label variable shbeginh "Hour interview begins"
label variable shbeginm "Minutes interview begins"
label variable shendh   "Hour interview ends"
label variable shendm   "Minute interview ends"
label variable sh107g   "Has cable TV"
label variable sh107h   "Has generating set"
label variable sh107i   "Has air conditioner"
label variable sh107j   "Has computer"
label variable sh107k   "Has electric iron"
label variable sh107l   "Has fan"
label variable sh112    "Number of rooms total"
label variable sh112b   "Number of sleeping facilities (sleeping bed, mattresses, etc)"
label variable sh121a   "Household respondent slept under a mosquito net"
label variable sh121ba  "Encourage use of net: could easily hang net"
label variable sh121bb  "Encourage use of net: if net were not hot"
label variable sh121bc  "Encourage use of net: if net did not smell"
label variable sh121bd  "Encourage use of net: if net had a different color"
label variable sh121be  "Encourage use of net: if net were not itchy/irritating"
label variable sh121bf  "Encourage use of net: if net were bigger/not claustrophobic"
label variable sh121bg  "Encourage use of net: if there were mosquitos present"
label variable sh121bx  "Encourage use of net: other"
label variable sh121bz  "Encourage use of net: don't know"
label variable sh122a   "Reason household doesn't have mosquito nets: no mosquitos"
label variable sh122b   "Reason household doesn't have mosquito nets: not available"
label variable sh122c   "Reason household doesn't have mosquito nets: don't like to use nets"
label variable sh122d   "Reason household doesn't have mosquito nets: too expensive"
label variable sh122x   "Reason household doesn't have mosquito nets: other"
label variable sh123    "Household has ever owned a mosquito net"
label variable sh124a   "Reason no longer have net: no mosquitos"
label variable sh124b   "Reason no longer have net: not available"
label variable sh124c   "Reason no longer have net: don't like to use nets"
label variable sh124d   "Reason no longer have net: too expensive"
label variable sh124e   "Reason no longer have net: net was old"
label variable sh124f   "Reason no longer have net: threw away net"
label variable sh124g   "Reason no longer have net: have window nets"
label variable sh124x   "Reason no longer have net: other"
label variable shmlweight "Malaria sample weight (6 decimals)"
label variable hv101    "Relationship to head"
label variable hv102    "Usual resident"
label variable hv103    "Slept last night"
label variable hv104    "Sex of household member"
label variable hv105    "Age of household members"
label variable hv106    "Highest educational level attained"
label variable hv107    "Highest year of education completed"
label variable hv108    "Education completed in single years"
label variable hv109    "Educational attainment"
label variable hv110    "NA - Member still in school"
label variable hv111    "NA - Mother alive"
label variable hv112    "NA - Mother's line number"
label variable hv113    "NA - Father alive"
label variable hv114    "NA - Father's line number"
label variable hv115    "NA - Current marital status"
label variable hv116    "NA - Currently, formerly, never married"
label variable hv117    "Eligibility for female interview"
label variable hv118    "NA - Eligibility for male interview"
label variable hv120    "Children eligibility for height/weight and hemoglobin"
label variable hv121    "NA - Member attended school during current school year"
label variable hv122    "NA - Educational level during current school year"
label variable hv123    "NA - Grade of education during current school year"
label variable hv124    "NA - Education in single years - current school year"
label variable hv125    "NA - Member attended school during previous school year"
label variable hv126    "NA - Educational level during previous school year"
label variable hv127    "NA - Grade of education during previous school year"
label variable hv128    "NA - Education in single years - previous school year"
label variable hv129    "NA - School attendance status"
label variable hv140    "NA - Member has a birth certificate"
label variable idxh4    "Index to Household Schedule"
label variable sh09     "Currently pregnant"
label variable sh12a    "Level of education attended"
label variable sh12b    "Highest grade attended"
label variable sh13     "Fever in last two weeks"
label variable sh14     "Treatment for fever in last two weeks"
label variable sh15     "Place first sought treatment"
label variable sh16     "Cost of treatment for fever (Naira)"
label variable hc0      "Index to Household Schedule"
label variable hc1      "Child's age in months"
label variable hc2      "NA - Child's weight in kilograms (1 decimal)"
label variable hc3      "NA - Child's height in centimeters (1 decimal)"
label variable hc4      "NA - Height/Age percentile"
label variable hc5      "NA - Height/Age standard deviation"
label variable hc6      "NA - Height/Age percent of ref. median"
label variable hc7      "NA - Weight/Age percentile"
label variable hc8      "NA - Weight/Age standard deviation"
label variable hc9      "NA - Weight/Age percent of ref. median"
label variable hc10     "NA - Weight/Height percentile"
label variable hc11     "NA - Weight/Height standard deviation"
label variable hc12     "NA - Weight/Height percent of ref. median"
label variable hc13     "NA - Result of measurement - height/weight"
label variable hc15     "NA - Height: lying or standing"
label variable hc16     "Day of birth"
label variable hc17     "Date measured (day)"
label variable hc18     "Date measured (month)"
label variable hc19     "Date measured (year)"
label variable hc27     "Sex"
label variable hc30     "Month of birth"
label variable hc31     "Year of birth"
label variable hc32     "Date of birth (CMC)"
label variable hc33     "Completeness of HC32 information"
label variable hc51     "Line number of parent/caretaker"
label variable hc52     "Read consent statement - hemoglobin"
label variable hc53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55     "Result of measurement - hemoglobin"
label variable hc56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57     "Anemia level"
label variable hc58     "NA - Agrees to referral - anemia"
label variable hc60     "Mother's line number (woman's questionnaire)"
label variable hc61     "Mother's highest educational level"
label variable hc62     "Mother's highest year of education"
label variable hc63     "Preceding birth interval (months)"
label variable hc64     "Birth order number"
label variable hc68     "Mother's highest educational level (for preliminary and final report)"
label variable hc70     "NA - Height/Age standard deviation (new WHO)"
label variable hc71     "NA - Weight/Age standard deviation (new WHO)"
label variable hc72     "NA - Weight/Height standard deviation (new WHO)"
label variable hc73     "NA - BMI standard deviation (new WHO)"
label variable hmlidx   "Mosquito Bed Net Designation Number"
label variable hml3     "Net observed by interviewer"
label variable hml4     "Months ago net obtained"
label variable hml5     "NA - Net treated with insecticide when bought"
label variable hml6     "Net treatment status"
label variable hml7     "Brand of net"
label variable hml8     "Net treated since receiving"
label variable hml9     "Time since last re-treatment (months)"
label variable hml10    "Insecticide-Treated Net (ITN)"
label variable hml11    "Number of persons who slept under this net"
label variable hml21    "Someone slept under this net last night"
label variable hmla     "Line number of person who slept in this net"
label variable hmlb     "Line number of person who slept in this net"
label variable hmlc     "Line number of person who slept in this net"
label variable hmld     "Line number of person who slept in this net"
label variable hmle     "Line number of person who slept in this net"
label variable hmhidx   "Index to Household Schedule"
label variable hml12    "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml13    "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml14    "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml15    "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml16    "Corrected age from Individual file"
label variable hml16a   "Age in months (for children)"
label variable hml17    "Flag for age from Individual file"
label variable hml18    "Pregnancy status from Individual file"
label variable hml19    "Person slept under an ever-treated net"
label variable hml20    "Person slept under an LLIN net"
label variable hml30    "Line number of parent/caretaker (for malaria testing)"
label variable hml31    "Read consent statement for malaria"
label variable hml32    "Final result of malaria from blood smear test"
label variable hml32a   "Presence of species: falciparum (Pf)"
label variable hml32b   "Presence of species: malariae (Pm)"
label variable hml32c   "Presence of species: ovale (Po)"
label variable hml32d   "NA - Presence of species: vivax (Pv)"
label variable hml32e   "NA - Presence of species: CS"
label variable hml32f   "NA - Presence of species: CS"
label variable hml32g   "NA - Presence of species: CS"
label variable hml33    "Result of malaria measurement"
label variable hml34    "Bar code for blood smear sample"
label variable hml35    "Result of malaria rapid test"
label variable hmcsidx  "Index to net"
label variable sh126    "Shown Net"
label variable sh127    "Observe or ask if net hanging"
label variable sh127a   "Color of net, observed"
label variable sh127b   "Shape of net, observed"
label variable sh127c   "Size of net, observed"
label variable sh128a   "Obtained net from campaign, ANC, or immunizations"
label variable sh129    "Place obtained net"
label variable sh130    "Net bought"
label variable sh131    "Cost of net (Naira)"
label variable sh136    "Reason nobody slept under net"
label variable hmla1    "Line number of person who slept in this net"
label variable hmlb1    "Line number of person who slept in this net"
label variable hmlc1    "Line number of person who slept in this net"
label variable hmld1    "Line number of person who slept in this net"
label variable hmle1    "Line number of person who slept in this net"
label variable h6bidx   "Index to household schedule"
label variable sh216    "Hemoglobin result (of children with positive RDT)"
label variable sh218a   "Child with positive RDT suffers from: extreme weakness"
label variable sh218b   "Child with positive RDT suffers from: heart problems"
label variable sh218c   "Child with positive RDT suffers from: loss of consciousness"
label variable sh218d   "Child with positive RDT suffers from: rapid breathing"
label variable sh218e   "Child with positive RDT suffers from: seizures"
label variable sh218f   "Child with positive RDT suffers from: bleeding"
label variable sh218g   "Child with positive RDT suffers from: jaundice"
label variable sh218h   "Child with positive RDT suffers from: dark urine"
label variable sh218y   "Child with positive RDT suffers from: no symptoms"
label variable sh219    "Child with positive RDT suffers from any symptoms"
label variable sh221    "Child has taken Coartem/ACT from doctor or health center"
label variable sh225    "Accepted malaria treatement medicine"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV022   
     0 "National"
     1 "Sokoto - Urban"
     2 "Sokoto - Rural"
     3 "Zamfara - Urban"
     4 "Zamfara - Rural"
     5 "Katsina - Urban"
     6 "Katsina - Rural"
     7 "Jigawa - Urban"
     8 "Jigawa - Rural"
     9 "Yobe - Urban"
    10 "Yobe - Rural"
    11 "Borno - Urban"
    13 "Adamawa - Urban"
    14 "Adamawa - Rural"
    15 "Gombe - Urban"
    16 "Gombe - Rural"
    17 "Bauchi - Urban"
    18 "Bauchi - Rural"
    19 "Kano - Urban"
    20 "Kano - Rural"
    21 "Kaduna - Urban"
    22 "Kaduna - Rural"
    23 "Kebbi - Urban"
    24 "Kebbi - Rural"
    25 "Niger - Urban"
    26 "Niger - Rural"
    27 "FCT Abuja - Urban"
    28 "FCT Abuja - Rural"
    29 "Nasarawa - Urban"
    30 "Nasarawa - Rural"
    31 "Plateau - Urban"
    32 "Plateau - Rural"
    33 "Taraba - Urban"
    34 "Taraba - Rural"
    35 "Benue - Urban"
    36 "Benue - Rural"
    37 "Kogi - Urban"
    38 "Kogi - Rural"
    39 "Kwara - Urban"
    40 "Kwara - Rural"
    41 "Oyo - Urban"
    42 "Oyo - Rural"
    43 "Osun - Urban"
    44 "Osun - Rural"
    45 "Ekiti - Urban"
    46 "Ekiti - Rural"
    47 "Ondo - Urban"
    48 "Ondo - Rural"
    49 "Edo - Urban"
    50 "Edo - Rural"
    51 "Anambra - Urban"
    52 "Anambra - Rural"
    53 "Enugu - Urban"
    54 "Enugu - Rural"
    55 "Ebonyi - Urban"
    56 "Ebonyi - Rural"
    57 "Cross River - Urban"
    58 "Cross River - Rural"
    59 "Akwa Ibom - Urban"
    60 "Akwa Ibom - Rural"
    61 "Abia - Urban"
    62 "Abia - Rural"
    63 "Imo - Urban"
    64 "Imo - Rural"
    65 "Rivers - Urban"
    66 "Rivers - Rural"
    67 "Bayelsa - Urban"
    68 "Bayelsa - Rural"
    69 "Delta - Urban"
    70 "Delta - Rural"
    71 "Lagos - Urban"
    73 "Ogun - Urban"
    74 "Ogun - Rural"
;
label define HV023   
     0 "National"
     1 "Sokoto - Urban"
     2 "Sokoto - Rural"
     3 "Zamfara - Urban"
     4 "Zamfara - Rural"
     5 "Katsina - Urban"
     6 "Katsina - Rural"
     7 "Jigawa - Urban"
     8 "Jigawa - Rural"
     9 "Yobe - Urban"
    10 "Yobe - Rural"
    11 "Borno - Urban"
    13 "Adamawa - Urban"
    14 "Adamawa - Rural"
    15 "Gombe - Urban"
    16 "Gombe - Rural"
    17 "Bauchi - Urban"
    18 "Bauchi - Rural"
    19 "Kano - Urban"
    20 "Kano - Rural"
    21 "Kaduna - Urban"
    22 "Kaduna - Rural"
    23 "Kebbi - Urban"
    24 "Kebbi - Rural"
    25 "Niger - Urban"
    26 "Niger - Rural"
    27 "FCT Abuja - Urban"
    28 "FCT Abuja - Rural"
    29 "Nasarawa - Urban"
    30 "Nasarawa - Rural"
    31 "Plateau - Urban"
    32 "Plateau - Rural"
    33 "Taraba - Urban"
    34 "Taraba - Rural"
    35 "Benue - Urban"
    36 "Benue - Rural"
    37 "Kogi - Urban"
    38 "Kogi - Rural"
    39 "Kwara - Urban"
    40 "Kwara - Rural"
    41 "Oyo - Urban"
    42 "Oyo - Rural"
    43 "Osun - Urban"
    44 "Osun - Rural"
    45 "Ekiti - Urban"
    46 "Ekiti - Rural"
    47 "Ondo - Urban"
    48 "Ondo - Rural"
    49 "Edo - Urban"
    50 "Edo - Rural"
    51 "Anambra - Urban"
    52 "Anambra - Rural"
    53 "Enugu - Urban"
    54 "Enugu - Rural"
    55 "Ebonyi - Urban"
    56 "Ebonyi - Rural"
    57 "Cross River - Urban"
    58 "Cross River - Rural"
    59 "Akwa Ibom - Urban"
    60 "Akwa Ibom - Rural"
    61 "Abia - Urban"
    62 "Abia - Rural"
    63 "Imo - Urban"
    64 "Imo - Rural"
    65 "Rivers - Urban"
    66 "Rivers - Rural"
    67 "Bayelsa - Urban"
    68 "Bayelsa - Rural"
    69 "Delta - Urban"
    70 "Delta - Rural"
    71 "Lagos - Urban"
    73 "Ogun - Urban"
    74 "Ogun - Rural"
;
label define HV024   
     1 "North central"
     2 "North east"
     3 "North west"
     4 "South east"
     5 "South south"
     6 "South west"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    14 "Piped to neighbor"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    72 "Sachet water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    14 "Piped to neighbor"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    72 "Sachet water"
    96 "Other"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth, sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm, bamboo"
    30 "FINISHED"
    31 "Parquet, polished wood"
    32 "Vinyl, asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
;
label define HV214   
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Dirt"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
;
label define HV215   
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Zinc/metal"
    32 "Wood"
    33 "Calamine/cement fiber"
    34 "Ceramic tiles"
    35 "Cement"
    36 "Roofing shingles"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in house"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV230A  
     1 "Observed"
     2 "Not observed: not in dwelling"
     3 "Not observed: no permission to see"
     4 "Not observed: other reason"
;
label define HV230B  
     0 "Water not available"
     1 "Water is available"
;
label define HV232   
     0 "No"
     1 "Yes"
;
label define HV232B  
     0 "No"
     1 "Yes"
;
label define HV232C  
     0 "No"
     1 "Yes"
;
label define HV232D  
     0 "No"
     1 "Yes"
;
label define HV232E  
     0 "No"
     1 "Yes"
;
label define HV232Y  
     0 "No"
     1 "Yes: no cleansing agent observed"
;
label define HV234   
     0 "0 PPM (no iodine)"
     7 "Below 15 PPM"
    15 "15 PPM and above"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define HV234A  
     0 "No iodine"
     1 "Iodine present"
     3 "No salt in household"
     6 "Salt not tested"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV236   
     1 "Adult woman"
     2 "Adult man"
     3 "Female child under 15 years old"
     4 "Male child under 15 years old"
     6 "Other"
;
label define HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237I  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237J  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237K  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237Z  
     0 "No"
     1 "Yes: don't know what is done to water"
     8 "Don't know"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     0 "Neither chimney or hood"
     1 "Chimney"
     2 "Hood"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
   950 "95 or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV252   
     0 "Never"
     1 "Daily"
     2 "Weekly"
     3 "Monthly"
     4 "Less than monthly"
;
label define HV253   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253Z  
     0 "No"
     1 "Yes: don't know who sprayed the dwelling"
     8 "Don't know if it was sprayed"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HV270A  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SHSTATE 
    10 "Sokoto"
    20 "Zamfara"
    30 "Katsina"
    40 "Jigawa"
    50 "Yobe"
    60 "Borno - Urban"
    70 "Adamawa"
    80 "Gombe"
    90 "Bauchi"
   100 "Kano"
   110 "Kaduna"
   120 "Kebbi"
   130 "Niger"
   140 "FCT Abuja"
   150 "Nasarawa"
   160 "Plateau"
   170 "Taraba"
   180 "Benue"
   190 "Kogi"
   200 "Kwara"
   210 "Oyo"
   220 "Osun"
   230 "Ekiti"
   240 "Ondo"
   250 "Edo"
   260 "Anambra"
   270 "Enugu"
   280 "Ebonyi"
   290 "Cross River"
   300 "Akwa Ibom"
   310 "Abia"
   320 "Imo"
   330 "Rivers"
   340 "Bayelsa"
   350 "Delta"
   360 "Lagos"
   370 "Ogun"
;
label define SHLANGINT
     1 "Hausa"
     2 "Yoruba"
     3 "Igbo"
     4 "English"
     6 "Other"
;
label define SHLANGNAT
     1 "Hausa"
     2 "Yoruba"
     3 "Igbo"
     4 "English"
     6 "Other"
;
label define SHTRANSL
     0 "No"
     1 "Yes"
;
label define SH107G  
     0 "No"
     1 "Yes"
;
label define SH107H  
     0 "No"
     1 "Yes"
;
label define SH107I  
     0 "No"
     1 "Yes"
;
label define SH107J  
     0 "No"
     1 "Yes"
;
label define SH107K  
     0 "No"
     1 "Yes"
;
label define SH107L  
     0 "No"
     1 "Yes"
;
label define SH121A  
     0 "No"
     1 "Yes"
;
label define SH121BA 
     0 "No"
     1 "Yes"
;
label define SH121BB 
     0 "No"
     1 "Yes"
;
label define SH121BC 
     0 "No"
     1 "Yes"
;
label define SH121BD 
     0 "No"
     1 "Yes"
;
label define SH121BE 
     0 "No"
     1 "Yes"
;
label define SH121BF 
     0 "No"
     1 "Yes"
;
label define SH121BG 
     0 "No"
     1 "Yes"
;
label define SH121BX 
     0 "No"
     1 "Yes"
;
label define SH121BZ 
     0 "No"
     1 "Yes"
;
label define SH122A  
     0 "No"
     1 "Yes"
;
label define SH122B  
     0 "No"
     1 "Yes"
;
label define SH122C  
     0 "No"
     1 "Yes"
;
label define SH122D  
     0 "No"
     1 "Yes"
;
label define SH122X  
     0 "No"
     1 "Yes"
;
label define SH123   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH124A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH124B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH124C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH124D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH124E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH124F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH124G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH124X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster/step child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    98 "Don't know"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV107   
    98 "Don't know"
;
label define HV108   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
;
label define HV110   
     0 "No"
     1 "Yes"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV112   
     0 "Mother not in household"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV114   
     0 "Father not in household"
;
label define HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever married"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV123   
    98 "Don't know"
;
label define HV124   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV127   
    98 "Don't know"
;
label define HV128   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "Don't know"
;
label define HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     8 "Don't know"
;
label define SH09    
     0 "No/Don't know"
     1 "Yes"
;
label define SH12A   
     0 "Pre-school"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define SH12B   
     0 "< 1 year completed"
     7 "7+ years"
    98 "Don't know"
;
label define SH13    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH14    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH15    
     1 "Government hospital"
     2 "Government health center"
     3 "Government health clinic"
     4 "Private hospital/clinic"
     5 "Pharmacy"
     6 "Private doctor"
     7 "Mobile clinic"
     8 "Chemist/PMV"
     9 "Shop"
    10 "Traditional practitioner"
    11 "Role model caregiver/community worker"
    12 "Drug hawker"
    13 "Self treatment at home"
    96 "Other"
    98 "Don't know"
;
label define SH16    
 99990 "99990 or more Naira"
 99995 "Free"
 99998 "Don't know"
;
label define HC2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC4     
  9998 "Flagged cases"
;
label define HC5     
  9998 "Flagged cases"
;
label define HC6     
 99998 "Flagged cases"
;
label define HC7     
  9998 "Flagged cases"
;
label define HC8     
  9998 "Flagged cases"
;
label define HC9     
 99998 "Flagged cases"
;
label define HC10    
  9998 "Flagged cases"
;
label define HC11    
  9998 "Flagged cases"
;
label define HC12    
 99998 "Flagged cases"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC15    
     0 "Not measured"
     1 "Lying"
     2 "Standing"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
     4 "Not present"
     6 "Other"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC62    
     0 "No education"
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HML3    
     0 "Not seen"
     1 "Yes, seen"
;
label define HML4    
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML5    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HML6    
     0 "Not pretreated"
     1 "Pretreated, permanent treatment"
     2 "Pretreated, requiring future treatment"
     3 "Not pretreated, came with kit and treated at home"
     4 "Pretreated, treatment type not known"
     6 "Other"
     8 "Don't know"
;
label define HML7    
    10 "Long-lasting insectiside treated nets (LLIN)"
    11 "Permanet"
    12 "Olyset"
    13 "Iconlife"
    14 "Duranet"
    15 "Netprotect"
    16 "BASF Interceptor"
    17 "Other/Don't know brand LLIN"
    96 "Other brand"
    98 "Don't know brand"
;
label define HML8    
     0 "No"
     1 "Yes"
     2 "Permanent net"
     8 "Not sure"
;
label define HML9    
    95 "25+ months ago"
    96 "More than 2 years ago"
    98 "Don't know"
;
label define HML10   
     0 "No, don't know"
     1 "Yes"
;
label define HML11   
     5 "5+"
;
label define HML21   
     0 "No"
     1 "Yes"
     8 "Not sure (DK)"
;
label define HMLA    
     0 "No one"
;
label define HMLB    
    99 "Missing"
;
label define HMLC    
    99 "Missing"
;
label define HML12   
     0 "Did not sleep under a net"
     1 "Only treated (ITN) nets"
     2 "Both treated (ITN) and untreated nets"
     3 "Only untreated nets"
;
label define HML13   
     0 "Did not sleep under net"
;
label define HML16   
    97 "97+"
    98 "Don't know"
;
label define HML17   
     0 "No data from Individual file"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HML18   
     0 "Not pregnant, don't know"
     1 "Pregnant"
;
label define HML19   
     0 "No"
     1 "Yes"
;
label define HML20   
     0 "No"
     1 "Yes"
;
label define HML30   
     0 "Not in household"
;
label define HML31   
     1 "Granted"
     2 "Refused"
     4 "Not present"
     6 "Other"
;
label define HML32   
     0 "Negative"
     1 "Positive"
     6 "Test undetermined"
     7 "Sample not found in lab database"
;
label define HML32A  
     0 "No"
     1 "Yes"
;
label define HML32B  
     0 "No"
     1 "Yes"
;
label define HML32C  
     0 "No"
     1 "Yes"
;
label define HML32D  
     0 "No"
     1 "Yes"
;
label define HML32E  
     0 "No"
     1 "Yes"
;
label define HML32F  
     0 "No"
     1 "Yes"
;
label define HML32G  
     0 "No"
     1 "Yes"
;
label define HML33   
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HML35   
     0 "Negative"
     1 "Positive"
;
label define SH126   
     0 "Not observed"
     1 "Observed, but has holes"
     2 "Observed, does not have holes"
;
label define SH127   
     1 "Observed, hanging"
     2 "Observed, not hanging"
     3 "Not observed, hanging"
     4 "Not observed, not hanging"
;
label define SH127A  
     1 "Green"
     2 "Dark blue"
     3 "Light blue"
     4 "Red"
     5 "Black"
     6 "White"
    96 "Other"
;
label define SH127B  
     1 "Conical"
     2 "Rectangle"
     6 "Other"
;
label define SH127C  
     1 "Cot/crib"
     2 "Single"
     3 "Double (usual campaign net)"
     4 "Triple"
     6 "Other"
;
label define SH128A  
     0 "No"
     1 "Yes, campaign"
     2 "Yes, ANC"
     3 "Yes, immunization"
;
label define SH129   
     1 "Primary health center / health post"
     2 "Government hospital"
     3 "Private hospital"
     4 "NGO clinic"
     5 "Mission clinic"
     6 "Mosque/church"
     7 "Pharmacy"
     8 "Patent medicine store"
     9 "Shop/supermarket"
    10 "Open market"
    11 "Hawker"
    12 "School"
    13 "Community directed distributors (CDD)"
    96 "Other"
    98 "Don't know"
;
label define SH130   
     1 "Bought"
     2 "Free"
     8 "Don't know"
;
label define SH131   
 99998 "Don't know"
;
label define SH136   
     1 "No mosquitos"
     2 "No malaria"
     3 "Too hot"
     4 "Difficult to hang"
     5 "Don't like smell"
     6 "Feel 'closed in' or contstrained"
     7 "Net too old or torn"
     8 "Net too dirty"
     9 "Net not available last night (washing)"
    10 "Feel ITN chemicals are unsage"
    11 "ITN provokes coughing"
    12 "Usual users did not sleep here last night"
    13 "Net not needed last night"
    14 "No space to hang"
    96 "Other"
    98 "Don't know"
;
label define HMLA1   
     0 "No one"
;
label define HMLB1   
    99 "Missing"
;
label define HMLC1   
    99 "Missing"
;
label define SH216   
     1 "Below 8.0 g/dL, severe anemia"
     2 "8.0 g/dL or above"
     4 "Not present"
     5 "Refused"
     6 "Other"
;
label define SH218A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH218B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH218C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH218D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH218E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH218F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH218G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH218H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH218Y  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH219   
     0 "No"
     1 "Yes"
;
label define SH221   
     0 "No"
     1 "Yes"
;
label define SH225   
     1 "Accepted medicine"
     2 "Refused"
     6 "Other"
;

#delimit cr
label values hv003    HV003   
label values hv015    HV015   
label values hv020    HV020   
label values hv022    HV022   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv044    HV044   
label values hv201    HV201   
label values hv202    HV202   
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv230a   HV230A  
label values hv230b   HV230B  
label values hv232    HV232   
label values hv232b   HV232B  
label values hv232c   HV232C  
label values hv232d   HV232D  
label values hv232e   HV232E  
label values hv232y   HV232Y  
label values hv234    HV234   
label values hv234a   HV234A  
label values hv235    HV235   
label values hv236    HV236   
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237g   HV237G  
label values hv237h   HV237H  
label values hv237i   HV237I  
label values hv237j   HV237J  
label values hv237k   HV237K  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv252    HV252   
label values hv253    HV253   
label values hv253a   HV253A  
label values hv253b   HV253B  
label values hv253c   HV253C  
label values hv253d   HV253D  
label values hv253e   HV253E  
label values hv253f   HV253F  
label values hv253g   HV253G  
label values hv253h   HV253H  
label values hv253x   HV253X  
label values hv253z   HV253Z  
label values hv270    HV270   
label values hv270a   HV270A  
label values hml1     HML1    
label values shstate  SHSTATE 
label values shlangint SHLANGINT
label values shlangnat SHLANGNAT
label values shtransl SHTRANSL
label values sh107g   SH107G  
label values sh107h   SH107H  
label values sh107i   SH107I  
label values sh107j   SH107J  
label values sh107k   SH107K  
label values sh107l   SH107L  
label values sh121a   SH121A  
label values sh121ba  SH121BA 
label values sh121bb  SH121BB 
label values sh121bc  SH121BC 
label values sh121bd  SH121BD 
label values sh121be  SH121BE 
label values sh121bf  SH121BF 
label values sh121bg  SH121BG 
label values sh121bx  SH121BX 
label values sh121bz  SH121BZ 
label values sh122a   SH122A  
label values sh122b   SH122B  
label values sh122c   SH122C  
label values sh122d   SH122D  
label values sh122x   SH122X  
label values sh123    SH123   
label values sh124a   SH124A  
label values sh124b   SH124B  
label values sh124c   SH124C  
label values sh124d   SH124D  
label values sh124e   SH124E  
label values sh124f   SH124F  
label values sh124g   SH124G  
label values sh124x   SH124X  
label values hv101    HV101   
label values hv102    HV102   
label values hv103    HV103   
label values hv104    HV104   
label values hv105    HV105   
label values hv106    HV106   
label values hv107    HV107   
label values hv108    HV108   
label values hv109    HV109   
label values hv110    HV110   
label values hv111    HV111   
label values hv112    HV112   
label values hv113    HV113   
label values hv114    HV114   
label values hv115    HV115   
label values hv116    HV116   
label values hv117    HV117   
label values hv118    HV118   
label values hv120    HV120   
label values hv121    HV121   
label values hv122    HV122   
label values hv123    HV123   
label values hv124    HV124   
label values hv125    HV125   
label values hv126    HV126   
label values hv127    HV127   
label values hv128    HV128   
label values hv129    HV129   
label values hv140    HV140   
label values sh09     SH09    
label values sh12a    SH12A   
label values sh12b    SH12B   
label values sh13     SH13    
label values sh14     SH14    
label values sh15     SH15    
label values sh16     SH16    
label values hc2      HC2     
label values hc3      HC3     
label values hc4      HC4     
label values hc5      HC5     
label values hc6      HC6     
label values hc7      HC7     
label values hc8      HC8     
label values hc9      HC9     
label values hc10     HC10    
label values hc11     HC11    
label values hc12     HC12    
label values hc13     HC13    
label values hc15     HC15    
label values hc16     HC16    
label values hc27     HC27    
label values hc30     HC30    
label values hc31     HC31    
label values hc33     HC33    
label values hc51     HC51    
label values hc52     HC52    
label values hc53     HC53    
label values hc55     HC55    
label values hc56     HC56    
label values hc57     HC57    
label values hc58     HC58    
label values hc60     HC60    
label values hc61     HC61    
label values hc62     HC62    
label values hc68     HC68    
label values hc70     HC70    
label values hc71     HC71    
label values hc72     HC72    
label values hc73     HC73    
label values hml3     HML3    
label values hml4     HML4    
label values hml5     HML5    
label values hml6     HML6    
label values hml7     HML7    
label values hml8     HML8    
label values hml9     HML9    
label values hml10    HML10   
label values hml11    HML11   
label values hml21    HML21   
label values hmla     HMLA    
label values hml12    HML12   
label values hml13    HML13   
label values hml16    HML16   
label values hml17    HML17   
label values hml18    HML18   
label values hml19    HML19   
label values hml20    HML20   
label values hml30    HML30   
label values hml31    HML31   
label values hml32    HML32   
label values hml32a   HML32A  
label values hml32b   HML32B  
label values hml32c   HML32C  
label values hml32d   HML32D  
label values hml32e   HML32E  
label values hml32f   HML32F  
label values hml32g   HML32G  
label values hml33    HML33   
label values hml35    HML35   
label values sh126    SH126   
label values sh127    SH127   
label values sh127a   SH127A  
label values sh127b   SH127B  
label values sh127c   SH127C  
label values sh128a   SH128A  
label values sh129    SH129   
label values sh130    SH130   
label values sh131    SH131   
label values sh136    SH136   
label values hmla1    HMLA1   
label values sh216    SH216   
label values sh218a   SH218A  
label values sh218b   SH218B  
label values sh218c   SH218C  
label values sh218d   SH218D  
label values sh218e   SH218E  
label values sh218f   SH218F  
label values sh218g   SH218G  
label values sh218h   SH218H  
label values sh218y   SH218Y  
label values sh219    SH219   
label values sh221    SH221   
label values sh225    SH225   
