infix using "C:\COUNTRIES\KE81\KEKR81FL.dct"

label variable caseid   "Case Identification"
label variable hidxa    "Index to birth history"
label variable v000     "Country code and phase"
label variable v001     "Cluster number"
label variable v002     "Household number"
label variable v003     "Respondent's line number"
label variable v004     "Ultimate area unit"
label variable v005     "Women's individual sample weight (6 decimals)"
label variable v006     "Month of interview"
label variable v007     "Year of interview"
label variable v008     "Date of interview (CMC)"
label variable v008a    "Date of interview Century Day Code (CDC)"
label variable v009     "Respondent's month of birth"
label variable v010     "Respondent's year of birth"
label variable v011     "Date of birth (CMC)"
label variable v012     "Respondent's current age"
label variable v013     "Age in 5-year groups"
label variable v014     "Completeness of age information"
label variable v015     "Result of individual interview"
label variable v016     "Day of interview"
label variable v021     "Primary sampling unit"
label variable v022     "Sample strata for sampling errors"
label variable v023     "Stratification used in sample design"
label variable v024     "Region"
label variable v025     "Type of place of residence"
label variable v026     "NA - De facto place of residence"
label variable v027     "Number of visits"
label variable v028     "Interviewer identification"
label variable v029     "NA - Keyer identification"
label variable v030     "Field supervisor"
label variable v031     "NA - Field editor"
label variable v032     "NA - Office editor"
label variable v034     "NA - Line number of husband"
label variable v040     "Cluster altitude in meters"
label variable v042     "Household selected for hemoglobin"
label variable v045a    "Language of questionnaire"
label variable v045b    "Language of interview"
label variable v045c    "Native language of respondent"
label variable v046     "Translator used"
label variable v101     "Region"
label variable v102     "Type of place of residence"
label variable v106     "Highest educational level"
label variable v107     "Highest year of education"
label variable v113     "Source of drinking water"
label variable v115     "Time to get to water source"
label variable v116     "Type of toilet facility"
label variable v119     "Household has: electricity"
label variable v120     "Household has: radio"
label variable v121     "Household has: television"
label variable v122     "Household has: refrigerator"
label variable v123     "Household has: bicycle"
label variable v124     "Household has: motorcycle/scooter"
label variable v125     "Household has: car/truck"
label variable v127     "Main floor material"
label variable v128     "Main wall material"
label variable v129     "Main roof material"
label variable v130     "Religion"
label variable v131     "NA - Ethnicity"
label variable v133     "Education in single years"
label variable v134     "NA - De facto place of residence"
label variable v135     "Usual resident or visitor"
label variable v136     "Number of household members (listed)"
label variable v137     "Number of children 14 and under in household (de jure)"
label variable v138     "Number of eligible women in household (de facto)"
label variable v139     "De jure region of residence"
label variable v140     "De jure type of place of residence"
label variable v141     "De jure place of residence"
label variable v149     "Educational attainment"
label variable v150     "Relationship to household head"
label variable v151     "Sex of household head"
label variable v152     "Age of household head"
label variable v153     "Household has: telephone (land-line)"
label variable v155     "Literacy"
label variable v157     "Frequency of reading newspaper or magazine"
label variable v158     "Frequency of listening to radio"
label variable v159     "Frequency of watching television"
label variable v160     "Toilet facilities shared with other households"
label variable v161     "Type of cooking fuel"
label variable v169a    "Owns a mobile telephone"
label variable v171a    "Use of internet"
label variable v171b    "Frequency of using internet last month"
label variable v190     "Wealth index combined"
label variable v191     "Wealth index factor score combined (5 decimals)"
label variable v190a    "Wealth index for urban/rural"
label variable v191a    "Wealth index factor score for urban/rural (5 decimals)"
label variable ml101    "Type of mosquito bed net(s) slept under last night"
label variable v201     "Total children ever born"
label variable v202     "Sons at home"
label variable v203     "Daughters at home"
label variable v204     "Sons elsewhere"
label variable v205     "Daughters elsewhere"
label variable v206     "Sons who have died"
label variable v207     "Daughters who have died"
label variable v208     "Births in last five years"
label variable v209     "Births in past year"
label variable v210     "Births in month of interview"
label variable v213     "Currently pregnant"
label variable v214     "Duration of current pregnancy"
label variable v218     "Number of living children"
label variable v219     "Living children + current pregnancy"
label variable v220     "Living children + current pregnancy (grouped)"
label variable v222     "Last birth to interview (months)"
label variable v223     "Completeness of current pregnancy information"
label variable v224     "Entries in birth history"
label variable v237     "Birth between last and interview"
label variable v238     "Births in last three years"
label variable v417     "Entries in pregnancy and postnatal care roster"
label variable v418a    "Entries in child health roster"
label variable v419     "Entries in height/weight roster"
label variable v459     "Have mosquito bed net for sleeping (from household questionnaire)"
label variable v460     "Children under 5 slept under mosquito bed net last night (household questionnair"
label variable v461     "Respondent slept under mosquito bed net"
label variable v468     "Record for Last Birth"
label variable bidx     "Birth column number"
label variable bord     "Birth order number"
label variable b0       "Child is twin"
label variable b1       "Month of birth"
label variable b2       "Year of birth"
label variable b3       "Date of birth (CMC)"
label variable b4       "Sex of child"
label variable b5       "Child is alive"
label variable b6       "NA - Age at death"
label variable b7       "NA - Age at death (months, imputed)"
label variable b8       "Current age of child"
label variable b9       "Child lives with whom"
label variable b10      "Completeness of information"
label variable b11      "Preceding birth interval (months)"
label variable b12      "Succeeding birth interval (months)"
label variable b13      "NA - Flag for age at death"
label variable b15      "Live birth between births"
label variable b16      "Child's line number in household"
label variable b17      "Day of birth"
label variable b18      "Century Day Code of birth (CDC)"
label variable b19      "Current age of child in months (months since birth for dead children)"
label variable midx     "Index to Birth History"
label variable m2a      "Prenatal: doctor"
label variable m2b      "NA - Prenatal: CS health professional"
label variable m2c      "NA - Prenatal: CS health professional"
label variable m2d      "NA - Prenatal: CS health professional"
label variable m2e      "NA - Prenatal: CS health professional"
label variable m2f      "NA - Prenatal: CS health professional"
label variable m2g      "Prenatal: traditional birth attendant"
label variable m2h      "Prenatal: community health worker"
label variable m2i      "NA - Prenatal: CS other person"
label variable m2j      "NA - Prenatal: CS other person"
label variable m2k      "Prenatal: other"
label variable m2l      "NA - Prenatal: CS other"
label variable m2m      "NA - Prenatal: CS other"
label variable m2n      "Prenatal: no one"
label variable m13      "Timing of 1st antenatal check (months)"
label variable m14      "Number of antenatal visits during pregnancy"
label variable m49a     "During pregnancy took: SP/fansidar for malaria"
label variable m49b     "NA - During pregnancy took: chloroquine for malaria"
label variable m49c     "NA - During pregnancy took: CS drug for malaria"
label variable m49d     "NA - During pregnancy took: CS drug for malaria"
label variable m49e     "NA - During pregnancy took: CS drug for malaria"
label variable m49f     "NA - During pregnancy took: CS drug for malaria"
label variable m49g     "NA - During pregnancy took: CS drug for malaria"
label variable m49x     "NA - During pregnancy took: other drug for malaria"
label variable m49z     "NA - During pregnancy took: don't know"
label variable m49y     "NA - During pregnancy took: no drug for malaria"
label variable m57a     "Antenatal care: respondent's home"
label variable m57b     "Antenatal care: other home"
label variable m57c     "NA - Antenatal care: CS home"
label variable m57d     "NA - Antenatal care: CS home"
label variable m57e     "Antenatal care: government hospital"
label variable m57f     "Antenatal care: government health center"
label variable m57g     "Antenatal care: government dispensary"
label variable m57h     "Antenatal care: other public sector"
label variable m57i     "NA - Antenatal care: CS public health"
label variable m57j     "NA - Antenatal care: CS public health"
label variable m57k     "NA - Antenatal care: CS public health"
label variable m57l     "NA - Antenatal care: CS public health"
label variable m57m     "Antenatal care: private hospital"
label variable m57n     "Antenatal care: private clinic"
label variable m57o     "Antenatal care: private faith-based, church hospital/clinic"
label variable m57p     "Antenatal care: other private medical sector"
label variable m57q     "NA - Antenatal care: CS private medical"
label variable m57r     "NA - Antenatal care: CS private medical"
label variable m57s     "NA - Antenatal care: CS other"
label variable m57t     "NA - Antenatal care: CS other"
label variable m57u     "NA - Antenatal care: CS other"
label variable m57v     "NA - Antenatal care: CS other"
label variable m57x     "Antenatal care: other"
label variable h22      "Had fever in last two weeks"
label variable h31      "NA - Had cough in last two weeks"
label variable h32a     "Fever/cough: government hospital"
label variable h32b     "Fever/cough: public health center"
label variable h32c     "Fever/cough: government dispensary"
label variable h32d     "Fever/cough: public mobile clinic"
label variable h32e     "Fever/cough: public community health worker/fieldworker"
label variable h32f     "Fever/cough: other public sector"
label variable h32g     "NA - Fever/cough: CS public sector"
label variable h32h     "NA - Fever/cough: CS public sector"
label variable h32i     "NA - Fever/cough: CS public sector"
label variable h32j     "Fever/cough: private hospital"
label variable h32k     "Fever/cough: private pharmacy"
label variable h32l     "Fever/cough: private doctor"
label variable h32m     "Fever/cough: private clinic"
label variable h32n     "Fever/cough: private mobile clinic"
label variable h32o     "Fever/cough: private community health worker"
label variable h32p     "Fever/cough: other private medical sector"
label variable h32q     "NA - Fever/cough: CS private medical"
label variable h32r     "NA - Fever/cough: CS private medical"
label variable h32s     "Fever/cough: shop"
label variable h32t     "Fever/cough: traditional practitioner"
label variable h32u     "Fever/cough: market"
label variable h32v     "Fever/cough: itinerant drug seller"
label variable h32w     "NA - Fever/cough: CS other sector"
label variable h32x     "Fever/cough: other"
label variable h32y     "Fever/cough: no treatment"
label variable h32z     "Fever/cough: medical treatment"
label variable h46a     "Place first sought treatment for fever"
label variable h46b     "Number of days after fever began sought advice or treatment"
label variable h47      "Blood taken from child's finger/heel for testing"
label variable s406     "Told child had malaria"
label variable hwidx    "Index to Birth History"
label variable hw1      "Child's age in months"
label variable hw16     "Day of birth of child"
label variable hw17     "Date measured (day)"
label variable hw18     "Date measured (month)"
label variable hw19     "Date measured (year)"
label variable hw51     "Line number of parent/caretaker"
label variable hw52     "Read consent statement - hemoglobin"
label variable hw53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hw55     "Result of measurement - hemoglobin"
label variable hw56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hw57     "Anemia level"
label variable hw58     "NA - Agrees to referral - anemia"
label variable v801     "Time interview started (hhmm - 24 hour clock)"
label variable v802     "Time interview ended (hhmm - 24 hour clock)"
label variable v803     "Length of interview in minutes"
label variable v804     "Number of visits"
label variable v805     "Interviewer identification"
label variable v806     "NA - Keyer identification"
label variable idxml    "Index to Birth History"
label variable ml0      "Type of mosquito bed net(s) child slept under last night"
label variable ml1      "Number of times took fansidar during pregnancy"
label variable ml2      "Source of antimalarial during pregnancy"
label variable ml11     "NA - Child has fever/cough now"
label variable ml12     "NA - Child has had convulsions in last 2 weeks"
label variable ml13a    "Fansidar taken for fever"
label variable ml13b    "Chloroquine taken for fever"
label variable ml13c    "Amodiaquine taken for fever"
label variable ml13d    "Quinine taken for fever"
label variable ml13da   "Quinine injection/IV taken for fever"
label variable ml13e    "NA - Combination with artemisinin taken for fever"
label variable ml13aa   "Artesunate rectal taken for fever"
label variable ml13ab   "Artesunate injection/IV taken for fever"
label variable ml13f    "NA - CS antimalarial taken for fever"
label variable ml13g    "NA - CS antimalarial taken for fever"
label variable ml13h    "Other antimalarial taken for fever"
label variable ml13i    "Antibiotic pill/syrup taken for fever"
label variable ml13j    "Antibiotic injection taken for fever"
label variable ml13k    "Aspirin taken for fever"
label variable ml13l    "Acetaminophen/paracetamol/panadol taken for fever"
label variable ml13m    "Ibuprofen taken for fever"
label variable ml13n    "Amoxicillin taken for fever"
label variable ml13o    "Cotrimoxazole taken for fever"
label variable ml13p    "NA - CS other taken for fever"
label variable ml13x    "Other taken for fever"
label variable ml13y    "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13z    "Don't know if or what was taken for fever"
label variable ml14a    "NA - Injection given for fever/convulsion"
label variable ml14b    "NA - Suppository given for fever/convulsion"
label variable ml14y    "NA - No suppository or injection given for fever/convulsion"
label variable ml14z    "NA - Don't know if suppository or injection given for fever/convulsion"
label variable ml15a    "NA - Timing of start of fansidar"
label variable ml15b    "NA - Number of days child took fansidar"
label variable ml15c    "NA - First source for fansidar"
label variable ml16a    "NA - Timing of start of chloroquine"
label variable ml16b    "NA - Number of days child took chloroquine"
label variable ml16c    "NA - First source for chloroquine"
label variable ml17a    "NA - Timing of start of amodiaquine"
label variable ml17b    "NA - Number of days child took amodiaquine"
label variable ml17c    "NA - First source for amodiaquine"
label variable ml18a    "NA - Timing of start of quinine"
label variable ml18b    "NA - Number of days child took quinine"
label variable ml18c    "NA - First source for quinine"
label variable ml19a    "NA - For fever/convulsion: consulted traditional healer"
label variable ml19b    "NA - For fever/convulsion: gave tepid sponging"
label variable ml19c    "NA - For fever/convulsion: gave herbs"
label variable ml19d    "NA - For fever/convulsion: CS"
label variable ml19e    "NA - For fever/convulsion: CS"
label variable ml19f    "NA - For fever/convulsion: CS"
label variable ml19x    "NA - For fever/convulsion: other"
label variable ml19y    "NA - For fever/convulsion: gave/did nothing"
label variable ml19z    "NA - For fever/convulsion: don't know if something else was done"
label variable ml20a    "Timing of start of combination with artemisinin"
label variable ml20b    "NA - Number of days child took combination with artemisinin"
label variable ml20c    "NA - First source for combination with artemisinin"
label variable ml21a    "NA - Timing of start of CS antimalarial use"
label variable ml21b    "NA - Number of days child took CS antimalarial"
label variable ml21c    "NA - First source for CS antimalarial"
label variable ml22a    "NA - Timing of start of CS antimalarial use"
label variable ml22b    "NA - Number of days child took CS antimalarial"
label variable ml22c    "NA - First source for CS antimalarial"
label variable ml23a    "NA - Timing of start of other anti-malarial use"
label variable ml23b    "NA - Number of days child took other anti-malarial"
label variable ml23c    "NA - First source for other anti-malarial"
label variable ml24c    "NA - First source for antibiotic pill/syrup"
label variable ml25a    "NA - Timing of start of artesunate"
label variable s413a    "AL taken for fever"
label variable s413b    "DHAP taken for fever"
label variable s413c    "Other ACT (not AL or DHAP) taken for fever"
label variable scounty  "County"
label variable szone    "Malaria endemicity zone"
label variable s114     "Mobile phone is a smart phone"
label variable s211     "Total births in 2015-2020"
label variable s225     "Length of pregnancy"
label variable s501     "Seen malaria messages in past 6 months"
label variable s502a    "Where malaria messages were seen: radio"
label variable s502b    "Where malaria messages were seen: television"
label variable s502c    "Where malaria messages were seen: poster/billboard"
label variable s502d    "Where malaria messages were seen: newspaper/magazine"
label variable s502e    "Where malaria messages were seen: leaflet/brochure"
label variable s502f    "Where malaria messages were seen: healthcare provider"
label variable s502g    "Where malaria messages were seen: community health worker"
label variable s502h    "Where malaria messages were seen: social media"
label variable s502i    "Where malaria messages were seen: relative/friend"
label variable s502j    "Where malaria messages were seen: community dialogue/baraza"
label variable s502k    "Where malaria messages were seen: community leader/elder"
label variable s502l    "Where malaria messages were seen: community event/roadshow"
label variable s502m    "Where malaria messages were seen: school pupils"
label variable s502x    "Where malaria messages were seen: anywhere else"
label variable s502z    "Where malaria messages were seen: don't know/don't remember"
label variable s502aa   "What malaria messages were seen or heard: If you have symptoms of malaria go to "
label variable s502ab   "What malaria messages were seen or heard: Sleep under an insecticide-treated mos"
label variable s502ac   "What malaria messages were seen or heard: Pregnant women should take medicine to"
label variable s502ad   "What malaria messages were seen or heard: SP protects pregnant women and unborn "
label variable s502ae   "What malaria messages were seen or heard: Always test before treating malaria"
label variable s502af   "What malaria messages were seen or heard: Treat malaria with ACTs"
label variable s502ag   "What malaria messages were seen or heard: malaria kills"
label variable s502ax   "What malaria messages were seen or heard: other"
label variable s502az   "What malaria messages were seen or heard: don't know/don't remember"
label variable s503     "Are there ways to prevent malaria"
label variable s504a    "Things to do to prevent malaria: Sleep under a mosquito net"
label variable s504b    "Things to do to prevent malaria: Sleep under an insecticide-treated mosquito net"
label variable s504c    "Things to do to prevent malaria: Use mosquito repellent"
label variable s504d    "Things to do to prevent malaria: Take preventative medications"
label variable s504e    "Things to do to prevent malaria: Spray house with insecticide"
label variable s504f    "Things to do to prevent malaria: Fill in stagnant waters (puddles)"
label variable s504g    "Things to do to prevent malaria: Keep surroundings clean"
label variable s504h    "Things to do to prevent malaria: Put mosquito screen on windows"
label variable s504i    "Things to do to prevent malaria: Pregnant women take SP/Fansidar"
label variable s504x    "Things to do to prevent malaria: other"
label variable s504z    "Things to do to prevent malaria: don't know"
label variable s504aa   "What is the recommended treatment for malaria: ACT/AL"
label variable s504ab   "What is the recommended treatment for malaria: SP/fansidar"
label variable s504ac   "What is the recommended treatment for malaria: chloroquine"
label variable s504ad   "What is the recommended treatment for malaria: amodiaquine"
label variable s504ax   "What is the recommended treatment for malaria: other"
label variable s504az   "What is the recommended treatment for malaria: don't know"
label variable s505     "Agree/disagree: get malaria during rainy season"
label variable s506     "Agree/disagree: worry child's fever may be malaria"
label variable s507     "Agree/disagree: don't worry about malaria because of treatment"
label variable s508     "Agree/disagree: only weak children die of malaria"
label variable s509     "Agree/disagree: sleep under a bed net all night with many mosquitoes"
label variable s510     "Agree/disagree: sleep under a bed net all night with few mosquitoes"
label variable s511     "Agree/disagree: not sleeping under a bed net when its too warm"
label variable s511a    "Agree/disagree: confident in hanging a bed net"
label variable s512     "Agree/disagree: give medicine to child with fever"
label variable s513     "Agree/disagree: take child to HC right away when they have a fever"
label variable s514     "Agree/disagree: people sleep under a bed net every night"
label variable s514a    "bed net used for other than sleeping"
label variable s514ba   "Other uses of bed net: Cover/protect the garden or chicks"
label variable s514bb   "Other uses of bed net: Fishing activities"
label variable s514bc   "Other uses of bed net: window screen"
label variable s514bd   "Other uses of bed net: clothing/wedding veil"
label variable s514bx   "Other uses of bed net: other"
label variable s514bz   "Other uses of bed net: don't know"
label variable idx94    "Index to Birth History"
label variable s306     "Length of pregnancy at first antenatal visit"
label variable s307a    "Decision maker for going to antenatal care"
label variable s309ba   "Reason took SP/Fansidar one or two times during pregnancy: facility too far"
label variable s309bb   "Reason took SP/Fansidar one or two times during pregnancy: had no money"
label variable s309bc   "Reason took SP/Fansidar one or two times during pregnancy: side effects"
label variable s309bd   "Reason took SP/Fansidar one or two times during pregnancy: not aware had to take"
label variable s309be   "Reason took SP/Fansidar one or two times during pregnancy: did not want to take"
label variable s309bf   "Reason took SP/Fansidar one or two times during pregnancy: not given"
label variable s309bg   "Reason took SP/Fansidar one or two times during pregnancy: not available"
label variable s309bx   "Reason took SP/Fansidar one or two times during pregnancy: other"
label variable s309bz   "Reason took SP/Fansidar one or two times during pregnancy: don't know"

#delimit ;
label define V013    
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define V014    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define V015    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partially completed"
     6 "Respondent incapacitated"
     7 "Other"
;
label define V022    
     1 "Urban Nairobi"
     2 "Rural Nyandarua"
     3 "Urban Nyandarua"
     4 "Rural Nyeri"
     5 "Urban Nyeri"
     6 "Rural Kirinyaga"
     7 "Urban Kirinyaga"
     8 "Rural Muranga"
     9 "Urban Muranga"
    10 "Rural Kiambu"
    11 "Urban Kiambu"
    12 "Urban Mombasa"
    13 "Rural Kwale"
    14 "Urban Kwale"
    15 "Rural Kilifi"
    16 "Urban Kilifi"
    17 "Rural Tana River"
    18 "Urban Tana River"
    19 "Rural Lamu"
    20 "Urban Lamu"
    21 "Rural Taita Taveta"
    22 "Urban Taita Taveta"
    23 "Rural Marsabit"
    24 "Urban Marsabit"
    25 "Rural Isiolo"
    26 "Urban Isiolo"
    27 "Rural Meru"
    28 "Urban Meru"
    29 "Rural Tharaka"
    30 "Urban Tharaka"
    31 "Rural Embu"
    32 "Urban Embu"
    33 "Rural Kitui"
    34 "Urban Kitui"
    35 "Rural Machakos"
    36 "Urban Machakos"
    37 "Rural Makueni"
    38 "Urban Makueni"
    39 "Rural Garissa"
    40 "Urban Garissa"
    41 "Rural Wajir"
    42 "Urban Wajir"
    43 "Rural Mandera"
    44 "Urban Mandera"
    45 "Rural Siaya"
    46 "Urban Siaya"
    47 "Rural Kisumu"
    48 "Urban Kisumu"
    49 "Rural Migori"
    50 "Urban Migori"
    51 "Rural Homa Bay"
    52 "Urban Homa Bay"
    53 "Rural Kisii"
    54 "Urban Kisii"
    55 "Rural Nyamira"
    56 "Urban Nyamira"
    57 "Rural Turkana"
    58 "Urban Turkana"
    59 "Rural West Pokot"
    60 "Urban West Pokot"
    61 "Rural Samburu"
    62 "Urban Samburu"
    63 "Rural Trans-Nzoia"
    64 "Urban Trans-Nzoia"
    65 "Rural Baringo"
    66 "Urban Baringo"
    67 "Rural Uasin Gishu"
    68 "Urban Uasin Gishu"
    69 "Rural Elgeyo Marakwet"
    70 "Urban Elgeyo Marakwet"
    71 "Rural Nandi"
    72 "Urban Nandi"
    73 "Rural Laikipia"
    74 "Urban Laikipia"
    75 "Rural Nakuru"
    76 "Urban Nakuru"
    77 "Rural Narok"
    78 "Urban Narok"
    79 "Rural Kajiado"
    80 "Urban Kajiado"
    81 "Rural Kericho"
    82 "Urban Kericho"
    83 "Rural Bomet"
    84 "Urban Bomet"
    85 "Rural Kakamega"
    86 "Urban Kakamega"
    87 "Rural Vihiga"
    88 "Urban Vihiga"
    89 "Rural Bungoma"
    90 "Urban Bungoma"
    91 "Rural Busia"
    92 "Urban Busia"
;
label define V023    
     1 "Urban Nairobi"
     2 "Rural Nyandarua"
     3 "Urban Nyandarua"
     4 "Rural Nyeri"
     5 "Urban Nyeri"
     6 "Rural Kirinyaga"
     7 "Urban Kirinyaga"
     8 "Rural Muranga"
     9 "Urban Muranga"
    10 "Rural Kiambu"
    11 "Urban Kiambu"
    12 "Urban Mombasa"
    13 "Rural Kwale"
    14 "Urban Kwale"
    15 "Rural Kilifi"
    16 "Urban Kilifi"
    17 "Rural Tana River"
    18 "Urban Tana River"
    19 "Rural Lamu"
    20 "Urban Lamu"
    21 "Rural Taita Taveta"
    22 "Urban Taita Taveta"
    23 "Rural Marsabit"
    24 "Urban Marsabit"
    25 "Rural Isiolo"
    26 "Urban Isiolo"
    27 "Rural Meru"
    28 "Urban Meru"
    29 "Rural Tharaka"
    30 "Urban Tharaka"
    31 "Rural Embu"
    32 "Urban Embu"
    33 "Rural Kitui"
    34 "Urban Kitui"
    35 "Rural Machakos"
    36 "Urban Machakos"
    37 "Rural Makueni"
    38 "Urban Makueni"
    39 "Rural Garissa"
    40 "Urban Garissa"
    41 "Rural Wajir"
    42 "Urban Wajir"
    43 "Rural Mandera"
    44 "Urban Mandera"
    45 "Rural Siaya"
    46 "Urban Siaya"
    47 "Rural Kisumu"
    48 "Urban Kisumu"
    49 "Rural Migori"
    50 "Urban Migori"
    51 "Rural Homa Bay"
    52 "Urban Homa Bay"
    53 "Rural Kisii"
    54 "Urban Kisii"
    55 "Rural Nyamira"
    56 "Urban Nyamira"
    57 "Rural Turkana"
    58 "Urban Turkana"
    59 "Rural West Pokot"
    60 "Urban West Pokot"
    61 "Rural Samburu"
    62 "Urban Samburu"
    63 "Rural Trans-Nzoia"
    64 "Urban Trans-Nzoia"
    65 "Rural Baringo"
    66 "Urban Baringo"
    67 "Rural Uasin Gishu"
    68 "Urban Uasin Gishu"
    69 "Rural Elgeyo Marakwet"
    70 "Urban Elgeyo Marakwet"
    71 "Rural Nandi"
    72 "Urban Nandi"
    73 "Rural Laikipia"
    74 "Urban Laikipia"
    75 "Rural Nakuru"
    76 "Urban Nakuru"
    77 "Rural Narok"
    78 "Urban Narok"
    79 "Rural Kajiado"
    80 "Urban Kajiado"
    81 "Rural Kericho"
    82 "Urban Kericho"
    83 "Rural Bomet"
    84 "Urban Bomet"
    85 "Rural Kakamega"
    86 "Urban Kakamega"
    87 "Rural Vihiga"
    88 "Urban Vihiga"
    89 "Rural Bungoma"
    90 "Urban Bungoma"
    91 "Rural Busia"
    92 "Urban Busia"
;
label define V024    
     1 "Coast"
     2 "North Eastern"
     3 "Eastern"
     4 "Central"
     5 "Rift Valley"
     7 "Western"
     8 "Nyanza"
     9 "Nairobi"
;
label define V025    
     1 "Urban"
     2 "Rural"
;
label define V026    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V027    
     9 "Missing"
;
label define V029    
   999 "Missing"
;
label define V034    
     0 "Husband not in household"
;
label define V040    
  9999 "Missing"
;
label define V042    
     0 "Not selected"
     1 "Selected"
;
label define V045A   
     1 "English"
     2 "Kiswahili"
;
label define V045B   
     1 "English"
     2 "Kiswahili"
     3 "Borana"
     4 "Embu"
     5 "Kalenjin"
     6 "Kamba"
     7 "Kikuyu"
     8 "Kisii"
     9 "Luhya"
    10 "Maragoli"
    11 "Luo"
    12 "Maasi"
    13 "Meru"
    14 "Mijkenda"
    15 "Pokot"
    16 "Somali"
    17 "Turkana"
    96 "Other"
;
label define V045C   
     1 "English"
     2 "Kiswahili"
     3 "Borana"
     4 "Embu"
     5 "Kalenjin"
     6 "Kamba"
     7 "Kikuyu"
     8 "Kisii"
     9 "Luhya"
    10 "Maragoli"
    11 "Luo"
    12 "Maasi"
    13 "Meru"
    14 "Mijkenda"
    15 "Pokot"
    16 "Somali"
    17 "Turkana"
    96 "Other"
;
label define V046    
     0 "No"
     1 "Yes"
;
label define V101    
     1 "Coast"
     2 "North Eastern"
     3 "Eastern"
     4 "Central"
     5 "Rift Valley"
     7 "Western"
     8 "Nyanza"
     9 "Nairobi"
;
label define V102    
     1 "Urban"
     2 "Rural"
;
label define V106    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define V107    
     0 "No years completed at level V106"
;
label define V113    
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
    97 "Not a dejure resident"
;
label define V115    
   996 "On premises"
   997 "Not a dejure resident"
   998 "Don't know"
;
label define V116    
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
    97 "Not a dejure resident"
;
label define V119    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V120    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V121    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V122    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V123    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V124    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V125    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V127    
    10 "NATURAL"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
    97 "Not a dejure resident"
;
label define V128    
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Dirt"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
    97 "Not a dejure resident"
;
label define V129    
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Iron sheets"
    32 "Wood"
    33 "Calamine/cement fiber"
    34 "Brick/clay tiles"
    35 "Cement"
    36 "Roofing shingles"
    96 "Other"
    97 "Not a dejure resident"
;
label define V130    
     1 "Roman Catholic"
     2 "Protestant/other Christian"
     3 "Muslim"
     4 "No religion"
    96 "Other"
;
label define V131    
   999 "Missing"
;
label define V133    
    97 "Inconsistent"
;
label define V134    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V135    
     1 "Usual resident"
     2 "Visitor"
;
label define V139    
     0 "Abroad"
     1 "Coast"
     2 "North Eastern"
     3 "Eastern"
     4 "Central"
     5 "Rift Valley"
     7 "Western"
     8 "Nyanza"
     9 "Nairobi"
    97 "Not dejure resident"
;
label define V140    
     0 "Abroad"
     1 "Urban"
     2 "Rural"
     7 "Not a dejure resident"
;
label define V141    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     7 "Not a dejure resident"
;
label define V149    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define V150    
     1 "Head"
     2 "Wife"
     3 "Daughter"
     4 "Daughter-in-law"
     5 "Granddaughter"
     6 "Mother"
     7 "Mother-in-law"
     8 "Sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "Don't know"
;
label define V151    
     1 "Male"
     2 "Female"
;
label define V152    
    97 "97+"
    98 "Don't know"
;
label define V153    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V155    
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define V157    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V158    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V159    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V160    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V161    
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    12 "Solar"
    13 "Alcohol/ethanol"
    14 "Gasoline/diesel"
    95 "No food cooked in house"
    96 "Other"
    97 "Not a dejure resident"
;
label define V169A   
     0 "No"
     1 "Yes"
;
label define V171A   
     0 "Never"
     1 "Yes, last 12 months"
     2 "Yes, before last 12 months"
     3 "Yes, can't establish when"
;
label define V171B   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V190    
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define V190A   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define ML101   
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define V208    
     0 "No births"
;
label define V209    
     0 "No births"
;
label define V213    
     0 "No or unsure"
     1 "Yes"
;
label define V214    
     0 "Less than one month"
;
label define V220    
     6 "6+"
;
label define V223    
     7 "Month - exact date"
     8 "None - date placed"
;
label define V237    
     0 "No"
     1 "Yes"
;
label define V459    
     0 "No"
     1 "Yes"
;
label define V460    
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define V461    
     0 "No"
     1 "Yes"
;
label define V468    
     0 "See specific questions"
     1 "Last birth only"
     2 "All births in last 5 years"
;
label define B0      
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
;
label define B4      
     1 "Male"
     2 "Female"
;
label define B5      
     0 "No"
     1 "Yes"
;
label define B6      
   100 "Died on day of birth"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
   997 "Inconsistent"
   998 "Don't know"
;
label define B9      
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
;
label define B10     
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define B13     
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
;
label define B15     
     0 "No"
     1 "Yes"
;
label define B16     
     0 "Not listed in household"
;
label define M2A     
     0 "No"
     1 "Yes"
;
label define M2B     
     0 "No"
     1 "Yes"
;
label define M2C     
     0 "No"
     1 "Yes"
;
label define M2D     
     0 "No"
     1 "Yes"
;
label define M2E     
     0 "No"
     1 "Yes"
;
label define M2F     
     0 "No"
     1 "Yes"
;
label define M2G     
     0 "No"
     1 "Yes"
;
label define M2H     
     0 "No"
     1 "Yes"
;
label define M2I     
     0 "No"
     1 "Yes"
;
label define M2J     
     0 "No"
     1 "Yes"
;
label define M2K     
     0 "No"
     1 "Yes"
;
label define M2L     
     0 "No"
     1 "Yes"
;
label define M2M     
     0 "No"
     1 "Yes"
;
label define M2N     
     0 "No: some care"
     1 "Yes: no care"
;
label define M13     
    98 "Don't know"
;
label define M14     
     0 "No antenatal visits"
    98 "Don't know"
;
label define M49A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49C    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49D    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49E    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49F    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49G    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49X    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49Z    
     0 "No"
     1 "Yes: don't know which drug taken"
     8 "Don't know"
;
label define M49Y    
     0 "No"
     1 "Yes, took no drug"
     8 "Don't know"
;
label define M57A    
     0 "No"
     1 "Yes"
;
label define M57B    
     0 "No"
     1 "Yes"
;
label define M57C    
     0 "No"
     1 "Yes"
;
label define M57D    
     0 "No"
     1 "Yes"
;
label define M57E    
     0 "No"
     1 "Yes"
;
label define M57F    
     0 "No"
     1 "Yes"
;
label define M57G    
     0 "No"
     1 "Yes"
;
label define M57H    
     0 "No"
     1 "Yes"
;
label define M57I    
     0 "No"
     1 "Yes"
;
label define M57J    
     0 "No"
     1 "Yes"
;
label define M57K    
     0 "No"
     1 "Yes"
;
label define M57L    
     0 "No"
     1 "Yes"
;
label define M57M    
     0 "No"
     1 "Yes"
;
label define M57N    
     0 "No"
     1 "Yes"
;
label define M57O    
     0 "No"
     1 "Yes"
;
label define M57P    
     0 "No"
     1 "Yes"
;
label define M57Q    
     0 "No"
     1 "Yes"
;
label define M57R    
     0 "No"
     1 "Yes"
;
label define M57S    
     0 "No"
     1 "Yes"
;
label define M57T    
     0 "No"
     1 "Yes"
;
label define M57U    
     0 "No"
     1 "Yes"
;
label define M57V    
     0 "No"
     1 "Yes"
;
label define M57X    
     0 "No"
     1 "Yes"
;
label define H22     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H31     
     0 "No"
     1 "Yes, last 24 hours"
     2 "Yes, last two weeks"
     8 "Don't know"
;
label define H32A    
     0 "No"
     1 "Yes"
;
label define H32B    
     0 "No"
     1 "Yes"
;
label define H32C    
     0 "No"
     1 "Yes"
;
label define H32D    
     0 "No"
     1 "Yes"
;
label define H32E    
     0 "No"
     1 "Yes"
;
label define H32F    
     0 "No"
     1 "Yes"
;
label define H32G    
     0 "No"
     1 "Yes"
;
label define H32H    
     0 "No"
     1 "Yes"
;
label define H32I    
     0 "No"
     1 "Yes"
;
label define H32J    
     0 "No"
     1 "Yes"
;
label define H32K    
     0 "No"
     1 "Yes"
;
label define H32L    
     0 "No"
     1 "Yes"
;
label define H32M    
     0 "No"
     1 "Yes"
;
label define H32N    
     0 "No"
     1 "Yes"
;
label define H32O    
     0 "No"
     1 "Yes"
;
label define H32P    
     0 "No"
     1 "Yes"
;
label define H32Q    
     0 "No"
     1 "Yes"
;
label define H32R    
     0 "No"
     1 "Yes"
;
label define H32S    
     0 "No"
     1 "Yes"
;
label define H32T    
     0 "No"
     1 "Yes"
;
label define H32U    
     0 "No"
     1 "Yes"
;
label define H32V    
     0 "No"
     1 "Yes"
;
label define H32W    
     0 "No"
     1 "Yes"
;
label define H32X    
     0 "No"
     1 "Yes"
;
label define H32Y    
     0 "No: received treatment"
     1 "Yes: no treatment"
;
label define H32Z    
     0 "No"
     1 "Yes"
;
label define H46A    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Government dispensary"
    14 "Mobile clinic"
    15 "Community health worker/fieldworker"
    16 "Other public sector"
    20 "PRIVATE SECTOR"
    21 "Private hospital"
    22 "Pharmacy"
    23 "Private doctor"
    24 "Private clinic"
    25 "Mobile clinic"
    26 "Community health worker"
    27 "Other private medical sector"
    30 "OTHER"
    31 "Shop"
    32 "Traditional practitioner"
    33 "Market"
    34 "Itinerant drug seller"
    96 "Other"
;
label define H46B    
     0 "Same day"
    98 "Don't know"
;
label define H47     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define S406    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HW16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HW51    
     0 "Not in household"
;
label define HW52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HW53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HW55    
     0 "Measured"
     1 "Dead"
     3 "Not present"
     4 "Refused"
     6 "Other"
     7 "No measurement found in household"
;
label define HW56    
   997 "Inconsistent"
;
label define HW57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HW58    
     0 "No"
     1 "Yes"
;
label define V801    
  9999 "Missing"
;
label define V802    
  9999 "Missing"
;
label define V803    
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define V804    
     9 "Missing"
;
label define V806    
    99 "Missing"
;
label define ML0     
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define ML1     
    98 "Don't know"
;
label define ML2     
     1 "Antenatal visit"
     2 "Another facility visit"
     6 "Other source"
;
label define ML11    
     0 "No"
     1 "Yes, fever only"
     2 "Yes, cough only"
     3 "Both fever and cough"
     8 "Don't know"
;
label define ML12    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define ML13A   
     0 "No"
     1 "Yes"
;
label define ML13B   
     0 "No"
     1 "Yes"
;
label define ML13C   
     0 "No"
     1 "Yes"
;
label define ML13D   
     0 "No"
     1 "Yes"
;
label define ML13DA  
     0 "No"
     1 "Yes"
;
label define ML13E   
     0 "No"
     1 "Yes"
;
label define ML13AA  
     0 "No"
     1 "Yes"
;
label define ML13AB  
     0 "No"
     1 "Yes"
;
label define ML13F   
     0 "No"
     1 "Yes"
;
label define ML13G   
     0 "No"
     1 "Yes"
;
label define ML13H   
     0 "No"
     1 "Yes"
;
label define ML13I   
     0 "No"
     1 "Yes"
;
label define ML13J   
     0 "No"
     1 "Yes"
;
label define ML13K   
     0 "No"
     1 "Yes"
;
label define ML13L   
     0 "No"
     1 "Yes"
;
label define ML13M   
     0 "No"
     1 "Yes"
;
label define ML13N   
     0 "No"
     1 "Yes"
;
label define ML13O   
     0 "No"
     1 "Yes"
;
label define ML13P   
     0 "No"
     1 "Yes"
;
label define ML13X   
     0 "No"
     1 "Yes"
;
label define ML13Y   
     0 "No"
     1 "Yes, nothing taken"
;
label define ML13Z   
     0 "No"
     1 "Yes, don't know"
;
label define ML14A   
     0 "No"
     1 "Yes"
;
label define ML14B   
     0 "No"
     1 "Yes"
;
label define ML14Y   
     0 "No"
     1 "Yes"
;
label define ML14Z   
     0 "No"
     1 "Yes"
;
label define ML15A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML15B   
     7 "7+ days"
     8 "Don't know"
;
label define ML15C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML16A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML16B   
     7 "7+ days"
     8 "Don't know"
;
label define ML16C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML17A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML17B   
     7 "7+ days"
     8 "Don't know"
;
label define ML17C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML18A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML18B   
     7 "7+ days"
     8 "Don't know"
;
label define ML18C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML19A   
     0 "No"
     1 "Yes"
;
label define ML19B   
     0 "No"
     1 "Yes"
;
label define ML19C   
     0 "No"
     1 "Yes"
;
label define ML19D   
     0 "No"
     1 "Yes"
;
label define ML19E   
     0 "No"
     1 "Yes"
;
label define ML19F   
     0 "No"
     1 "Yes"
;
label define ML19X   
     0 "No"
     1 "Yes"
;
label define ML19Y   
     0 "No"
     1 "Yes"
;
label define ML19Z   
     0 "No"
     1 "Yes"
;
label define ML20A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML20B   
     7 "7+ days"
     8 "Don't know"
;
label define ML20C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML21A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML21B   
     7 "7+ days"
     8 "Don't know"
;
label define ML21C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML22A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML22B   
     7 "7+ days"
     8 "Don't know"
;
label define ML22C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML23A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML23B   
     7 "7+ days"
     8 "Don't know"
;
label define ML23C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML24C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML25A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define S413A   
     0 "No"
     1 "Yes"
;
label define S413B   
     0 "No"
     1 "Yes"
;
label define S413C   
     0 "No"
     1 "Yes"
;
label define SCOUNTY 
   101 "Nairobi"
   201 "Nyandarua"
   202 "Nyeri"
   203 "Kirinyaga"
   204 "Muranga"
   205 "Kiambu"
   301 "Mombasa"
   302 "Kwale"
   303 "Kilifi"
   304 "Tana River"
   305 "Lamu"
   306 "Taita Taveta"
   401 "Marsabit"
   402 "Isiolo"
   403 "Meru"
   404 "Tharaka"
   405 "Embu"
   406 "Kitui"
   407 "Machakos"
   408 "Makueni"
   501 "Garissa"
   502 "Wajir"
   503 "Mandera"
   601 "Siaya"
   602 "Kisumu"
   603 "Migori"
   604 "Homa Bay"
   605 "Kisii"
   606 "Nyamira"
   701 "Turkana"
   702 "West Pokot"
   703 "Samburu"
   704 "Trans-Nzoia"
   705 "Baringo"
   706 "Uasin Gishu"
   707 "Elgeyo Marakwet"
   708 "Nandi"
   709 "Laikipia"
   710 "Nakuru"
   711 "Narok"
   712 "Kajiado"
   713 "Kericho"
   714 "Bomet"
   801 "Kakamega"
   802 "Vihiga"
   803 "Bungoma"
   804 "Busia"
;
label define SZONE   
     1 "Highland Epidemic Prone"
     2 "Lake Endemic"
     3 "Coastal Endemic"
     4 "Seasonal"
     5 "Low Risk"
;
label define S114    
     0 "No"
     1 "Yes"
;
label define S225    
   101 "Weeks: 1"
   201 "Months 1"
;
label define S501    
     0 "No"
     1 "Yes"
;
label define S502A   
     0 "No"
     1 "Yes"
;
label define S502B   
     0 "No"
     1 "Yes"
;
label define S502C   
     0 "No"
     1 "Yes"
;
label define S502D   
     0 "No"
     1 "Yes"
;
label define S502E   
     0 "No"
     1 "Yes"
;
label define S502F   
     0 "No"
     1 "Yes"
;
label define S502G   
     0 "No"
     1 "Yes"
;
label define S502H   
     0 "No"
     1 "Yes"
;
label define S502I   
     0 "No"
     1 "Yes"
;
label define S502J   
     0 "No"
     1 "Yes"
;
label define S502K   
     0 "No"
     1 "Yes"
;
label define S502L   
     0 "No"
     1 "Yes"
;
label define S502M   
     0 "No"
     1 "Yes"
;
label define S502X   
     0 "No"
     1 "Yes"
;
label define S502Z   
     0 "No"
     1 "Yes"
;
label define S502AA  
     0 "No"
     1 "Yes"
;
label define S502AB  
     0 "No"
     1 "Yes"
;
label define S502AC  
     0 "No"
     1 "Yes"
;
label define S502AD  
     0 "No"
     1 "Yes"
;
label define S502AE  
     0 "No"
     1 "Yes"
;
label define S502AF  
     0 "No"
     1 "Yes"
;
label define S502AG  
     0 "No"
     1 "Yes"
;
label define S502AX  
     0 "No"
     1 "Yes"
;
label define S502AZ  
     0 "No"
     1 "Yes"
;
label define S503    
     0 "No"
     1 "Yes"
;
label define S504A   
     0 "No"
     1 "Yes"
;
label define S504B   
     0 "No"
     1 "Yes"
;
label define S504C   
     0 "No"
     1 "Yes"
;
label define S504D   
     0 "No"
     1 "Yes"
;
label define S504E   
     0 "No"
     1 "Yes"
;
label define S504F   
     0 "No"
     1 "Yes"
;
label define S504G   
     0 "No"
     1 "Yes"
;
label define S504H   
     0 "No"
     1 "Yes"
;
label define S504I   
     0 "No"
     1 "Yes"
;
label define S504X   
     0 "No"
     1 "Yes"
;
label define S504Z   
     0 "No"
     1 "Yes"
;
label define S504AA  
     0 "No"
     1 "Yes"
;
label define S504AB  
     0 "No"
     1 "Yes"
;
label define S504AC  
     0 "No"
     1 "Yes"
;
label define S504AD  
     0 "No"
     1 "Yes"
;
label define S504AX  
     0 "No"
     1 "Yes"
;
label define S504AZ  
     0 "No"
     1 "Yes"
;
label define S505    
     1 "Agree"
     2 "Disagree"
     8 "Don't know/uncertain"
;
label define S506    
     1 "Agree"
     2 "Disagree"
     8 "Don't know/uncertain"
;
label define S507    
     1 "Agree"
     2 "Disagree"
     8 "Don't know/uncertain"
;
label define S508    
     1 "Agree"
     2 "Disagree"
     8 "Don't know/uncertain"
;
label define S509    
     1 "Agree"
     2 "Disagree"
     8 "Don't know/uncertain"
;
label define S510    
     1 "Agree"
     2 "Disagree"
     8 "Don't know/uncertain"
;
label define S511    
     1 "Agree"
     2 "Disagree"
     8 "Don't know/uncertain"
;
label define S511A   
     1 "Agree"
     2 "Disagree"
     8 "Don't know/uncertain"
;
label define S512    
     1 "Agree"
     2 "Disagree"
     8 "Don't know/uncertain"
;
label define S513    
     1 "Agree"
     2 "Disagree"
     8 "Don't know/uncertain"
;
label define S514    
     1 "Agree"
     2 "Disagree"
     8 "Don't know/uncertain"
;
label define S514A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define S514BA  
     0 "No"
     1 "Yes"
;
label define S514BB  
     0 "No"
     1 "Yes"
;
label define S514BC  
     0 "No"
     1 "Yes"
;
label define S514BD  
     0 "No"
     1 "Yes"
;
label define S514BX  
     0 "No"
     1 "Yes"
;
label define S514BZ  
     0 "No"
     1 "Yes"
;
label define S306    
   101 "Weeks: 1"
   201 "Months 1"
   998 "Don't know"
;
label define S307A   
     1 "Respondent"
     2 "Spouse"
     3 "Joint decision with spouse"
     4 "Someone else"
     8 "Don't know"
;
label define S309BA  
     0 "No"
     1 "Yes"
;
label define S309BB  
     0 "No"
     1 "Yes"
;
label define S309BC  
     0 "No"
     1 "Yes"
;
label define S309BD  
     0 "No"
     1 "Yes"
;
label define S309BE  
     0 "No"
     1 "Yes"
;
label define S309BF  
     0 "No"
     1 "Yes"
;
label define S309BG  
     0 "No"
     1 "Yes"
;
label define S309BX  
     0 "No"
     1 "Yes"
;
label define S309BZ  
     0 "No"
     1 "Yes"
;

#delimit cr
label values v013     V013    
label values v014     V014    
label values v015     V015    
label values v022     V022    
label values v023     V023    
label values v024     V024    
label values v025     V025    
label values v026     V026    
label values v034     V034    
label values v042     V042    
label values v045a    V045A   
label values v045b    V045B   
label values v045c    V045C   
label values v046     V046    
label values v101     V101    
label values v102     V102    
label values v106     V106    
label values v107     V107    
label values v113     V113    
label values v115     V115    
label values v116     V116    
label values v119     V119    
label values v120     V120    
label values v121     V121    
label values v122     V122    
label values v123     V123    
label values v124     V124    
label values v125     V125    
label values v127     V127    
label values v128     V128    
label values v129     V129    
label values v130     V130    
label values v133     V133    
label values v134     V134    
label values v135     V135    
label values v139     V139    
label values v140     V140    
label values v141     V141    
label values v149     V149    
label values v150     V150    
label values v151     V151    
label values v152     V152    
label values v153     V153    
label values v155     V155    
label values v157     V157    
label values v158     V158    
label values v159     V159    
label values v160     V160    
label values v161     V161    
label values v169a    V169A   
label values v171a    V171A   
label values v171b    V171B   
label values v190     V190    
label values v190a    V190A   
label values ml101    ML101   
label values v208     V208    
label values v209     V209    
label values v213     V213    
label values v214     V214    
label values v220     V220    
label values v223     V223    
label values v237     V237    
label values v459     V459    
label values v460     V460    
label values v461     V461    
label values v468     V468    
label values b0       B0      
label values b4       B4      
label values b5       B5      
label values b6       B6      
label values b9       B9      
label values b10      B10     
label values b13      B13     
label values b15      B15     
label values b16      B16     
label values m2a      M2A     
label values m2b      M2B     
label values m2c      M2C     
label values m2d      M2D     
label values m2e      M2E     
label values m2f      M2F     
label values m2g      M2G     
label values m2h      M2H     
label values m2i      M2I     
label values m2j      M2J     
label values m2k      M2K     
label values m2l      M2L     
label values m2m      M2M     
label values m2n      M2N     
label values m13      M13     
label values m14      M14     
label values m49a     M49A    
label values m49b     M49B    
label values m49c     M49C    
label values m49d     M49D    
label values m49e     M49E    
label values m49f     M49F    
label values m49g     M49G    
label values m49x     M49X    
label values m49z     M49Z    
label values m49y     M49Y    
label values m57a     M57A    
label values m57b     M57B    
label values m57c     M57C    
label values m57d     M57D    
label values m57e     M57E    
label values m57f     M57F    
label values m57g     M57G    
label values m57h     M57H    
label values m57i     M57I    
label values m57j     M57J    
label values m57k     M57K    
label values m57l     M57L    
label values m57m     M57M    
label values m57n     M57N    
label values m57o     M57O    
label values m57p     M57P    
label values m57q     M57Q    
label values m57r     M57R    
label values m57s     M57S    
label values m57t     M57T    
label values m57u     M57U    
label values m57v     M57V    
label values m57x     M57X    
label values h22      H22     
label values h31      H31     
label values h32a     H32A    
label values h32b     H32B    
label values h32c     H32C    
label values h32d     H32D    
label values h32e     H32E    
label values h32f     H32F    
label values h32g     H32G    
label values h32h     H32H    
label values h32i     H32I    
label values h32j     H32J    
label values h32k     H32K    
label values h32l     H32L    
label values h32m     H32M    
label values h32n     H32N    
label values h32o     H32O    
label values h32p     H32P    
label values h32q     H32Q    
label values h32r     H32R    
label values h32s     H32S    
label values h32t     H32T    
label values h32u     H32U    
label values h32v     H32V    
label values h32w     H32W    
label values h32x     H32X    
label values h32y     H32Y    
label values h32z     H32Z    
label values h46a     H46A    
label values h46b     H46B    
label values h47      H47     
label values s406     S406    
label values hw16     HW16    
label values hw51     HW51    
label values hw52     HW52    
label values hw53     HW53    
label values hw55     HW55    
label values hw56     HW56    
label values hw57     HW57    
label values hw58     HW58    
label values v803     V803    
label values ml0      ML0     
label values ml1      ML1     
label values ml2      ML2     
label values ml11     ML11    
label values ml12     ML12    
label values ml13a    ML13A   
label values ml13b    ML13B   
label values ml13c    ML13C   
label values ml13d    ML13D   
label values ml13da   ML13DA  
label values ml13e    ML13E   
label values ml13aa   ML13AA  
label values ml13ab   ML13AB  
label values ml13f    ML13F   
label values ml13g    ML13G   
label values ml13h    ML13H   
label values ml13i    ML13I   
label values ml13j    ML13J   
label values ml13k    ML13K   
label values ml13l    ML13L   
label values ml13m    ML13M   
label values ml13n    ML13N   
label values ml13o    ML13O   
label values ml13p    ML13P   
label values ml13x    ML13X   
label values ml13y    ML13Y   
label values ml13z    ML13Z   
label values ml14a    ML14A   
label values ml14b    ML14B   
label values ml14y    ML14Y   
label values ml14z    ML14Z   
label values ml15a    ML15A   
label values ml15b    ML15B   
label values ml15c    ML15C   
label values ml16a    ML16A   
label values ml16b    ML16B   
label values ml16c    ML16C   
label values ml17a    ML17A   
label values ml17b    ML17B   
label values ml17c    ML17C   
label values ml18a    ML18A   
label values ml18b    ML18B   
label values ml18c    ML18C   
label values ml19a    ML19A   
label values ml19b    ML19B   
label values ml19c    ML19C   
label values ml19d    ML19D   
label values ml19e    ML19E   
label values ml19f    ML19F   
label values ml19x    ML19X   
label values ml19y    ML19Y   
label values ml19z    ML19Z   
label values ml20a    ML20A   
label values ml20b    ML20B   
label values ml20c    ML20C   
label values ml21a    ML21A   
label values ml21b    ML21B   
label values ml21c    ML21C   
label values ml22a    ML22A   
label values ml22b    ML22B   
label values ml22c    ML22C   
label values ml23a    ML23A   
label values ml23b    ML23B   
label values ml23c    ML23C   
label values ml24c    ML24C   
label values ml25a    ML25A   
label values s413a    S413A   
label values s413b    S413B   
label values s413c    S413C   
label values scounty  SCOUNTY 
label values szone    SZONE   
label values s114     S114    
label values s225     S225    
label values s501     S501    
label values s502a    S502A   
label values s502b    S502B   
label values s502c    S502C   
label values s502d    S502D   
label values s502e    S502E   
label values s502f    S502F   
label values s502g    S502G   
label values s502h    S502H   
label values s502i    S502I   
label values s502j    S502J   
label values s502k    S502K   
label values s502l    S502L   
label values s502m    S502M   
label values s502x    S502X   
label values s502z    S502Z   
label values s502aa   S502AA  
label values s502ab   S502AB  
label values s502ac   S502AC  
label values s502ad   S502AD  
label values s502ae   S502AE  
label values s502af   S502AF  
label values s502ag   S502AG  
label values s502ax   S502AX  
label values s502az   S502AZ  
label values s503     S503    
label values s504a    S504A   
label values s504b    S504B   
label values s504c    S504C   
label values s504d    S504D   
label values s504e    S504E   
label values s504f    S504F   
label values s504g    S504G   
label values s504h    S504H   
label values s504i    S504I   
label values s504x    S504X   
label values s504z    S504Z   
label values s504aa   S504AA  
label values s504ab   S504AB  
label values s504ac   S504AC  
label values s504ad   S504AD  
label values s504ax   S504AX  
label values s504az   S504AZ  
label values s505     S505    
label values s506     S506    
label values s507     S507    
label values s508     S508    
label values s509     S509    
label values s510     S510    
label values s511     S511    
label values s511a    S511A   
label values s512     S512    
label values s513     S513    
label values s514     S514    
label values s514a    S514A   
label values s514ba   S514BA  
label values s514bb   S514BB  
label values s514bc   S514BC  
label values s514bd   S514BD  
label values s514bx   S514BX  
label values s514bz   S514BZ  
label values s306     S306    
label values s307a    S307A   
label values s309ba   S309BA  
label values s309bb   S309BB  
label values s309bc   S309BC  
label values s309bd   S309BD  
label values s309be   S309BE  
label values s309bf   S309BF  
label values s309bg   S309BG  
label values s309bx   S309BX  
label values s309bz   S309BZ  
