infix using "C:\COUNTRIES\NG6A\NGMR6AFL.dct"

label variable mcaseid  "Case Identification"
label variable mv000    "Country code and phase"
label variable mv001    "Cluster number"
label variable mv002    "Household number"
label variable mv003    "Respondent's line number"
label variable mv004    "Ultimate area unit"
label variable mv005    "Men's sample weight (6 decimals)"
label variable mv006    "Month of interview"
label variable mv007    "Year of interview"
label variable mv008    "Date of interview (CMC)"
label variable mv009    "Month of birth"
label variable mv010    "Year of birth"
label variable mv011    "Date of birth (CMC)"
label variable mv012    "Current age"
label variable mv013    "Age in 5-year groups"
label variable mv014    "Completeness of age information"
label variable mv015    "Result of interview"
label variable mv016    "Day of interview"
label variable mv021    "Primary sampling unit"
label variable mv022    "Sample stratum number"
label variable mv023    "Sample domain"
label variable mv024    "Region"
label variable mv025    "Type of place of residence"
label variable mv026    "NA - De facto place of residence"
label variable mv027    "Number of visits"
label variable mv028    "Interviewer identification"
label variable mv029    "Keyer identification"
label variable mv030    "Field supervisor"
label variable mv031    "Field editor"
label variable mv032    "Office editor"
label variable mv034_1  "Line number of wife/partner"
label variable mv034_2  "Line number of wife/partner"
label variable mv034_3  "Line number of wife/partner"
label variable mv034_4  "Line number of wife/partner"
label variable mv034_5  "Line number of wife/partner"
label variable mv034_6  "Line number of wife/partner"
label variable mv034_7  "Line number of wife/partner"
label variable mv034_8  "Line number of wife/partner"
label variable mv034a_1 "NA - Wife or partner***"
label variable mv034a_2 "NA - Wife or partner***"
label variable mv034a_3 "NA - Wife or partner***"
label variable mv034a_4 "NA - Wife or partner***"
label variable mv034a_5 "NA - Wife or partner***"
label variable mv034a_6 "NA - Wife or partner***"
label variable mv034a_7 "NA - Wife or partner***"
label variable mv034a_8 "NA - Wife or partner***"
label variable mv034b_1 "Age of wife/partner"
label variable mv034b_2 "Age of wife/partner"
label variable mv034b_3 "Age of wife/partner"
label variable mv034b_4 "Age of wife/partner"
label variable mv034b_5 "Age of wife/partner"
label variable mv034b_6 "Age of wife/partner"
label variable mv034b_7 "Age of wife/partner"
label variable mv034b_8 "Age of wife/partner"
label variable mv035    "Number of wives/partners"
label variable mv801    "Time interview started (hhmm - 24 hour clock)"
label variable mv802    "Time interview ended (hhmm - 24 hour clock)"
label variable mv803    "Length of interview in minutes"
label variable mv101    "Region"
label variable mv102    "Type of place of residence"
label variable mv103    "NA - Childhood place of residence***"
label variable mv104    "NA - Years lived in place of residence"
label variable mv105    "NA - Type of place of previous residence"
label variable mv106    "Educational level"
label variable mv107    "Highest year of education (at level in MV106)"
label variable mv130    "Religion"
label variable mv131    "Ethnicity"
label variable mv133    "Total number of years of education"
label variable mv134    "NA - De facto place of residence"
label variable mv135    "Usual resident or visitor"
label variable mv136    "Number of household members (total listed)"
label variable mv138    "Number of eligible men in household (de facto)"
label variable mv149    "Educational attainment"
label variable mv150    "Relationship to household head"
label variable mv151    "Sex of household head"
label variable mv152    "Age of household head"
label variable mv155    "Literacy"
label variable mv156    "NA - Ever participated in a literacy program (excluding primary school)"
label variable mv157    "Frequency of reading newspaper or magazine"
label variable mv158    "Frequency of listening to radio"
label variable mv159    "Frequency of watching television"
label variable mv167    "Times away from home in last 12 months"
label variable mv168    "Away for more than one month in last 12 months"
label variable mv190    "Wealth index"
label variable mv191    "Wealth index factor score (5 decimals)"
label variable mv201    "Total children ever born"
label variable mv202    "Sons at home"
label variable mv203    "Daughters at home"
label variable mv204    "Sons elsewhere"
label variable mv205    "Daughters elsewhere"
label variable mv206    "Sons who have died"
label variable mv207    "Daughters who have died"
label variable mv212    "Age of respondent at 1st birth"
label variable mv213    "Partner currently pregnant"
label variable mv217    "Knowledge of ovulatory cycle"
label variable mv218    "Number of living children"
label variable mv225    "NA - Most recent pregnancy wanted***"
label variable mv245    "Number of women fathered children with"
label variable mv246    "NA - Married to mother when first child was born***"
label variable mv247    "Age of most recent child"
label variable mv248    "Antenatal check-ups for the mother of most recent child"
label variable mv249    "Respondent present during check-ups for most recent child"
label variable mv250    "Place of birth of most recent child"
label variable mv251    "Reason for not delivering most recent child in health facility"
label variable mv252    "Amount a child should drink, when that child has diarrhea"
label variable mv301    "Knowledge of any contraceptive method"
label variable mv302    "NA - Ever use of any contraceptive method"
label variable m304a_01 "Type of contraceptive method"
label variable m304a_02 "Type of contraceptive method"
label variable m304a_03 "Type of contraceptive method"
label variable m304a_04 "Type of contraceptive method"
label variable m304a_05 "Type of contraceptive method"
label variable m304a_06 "Type of contraceptive method"
label variable m304a_07 "Type of contraceptive method"
label variable m304a_08 "Type of contraceptive method"
label variable m304a_09 "Type of contraceptive method"
label variable m304a_10 "Type of contraceptive method"
label variable m304a_11 "Type of contraceptive method"
label variable m304a_12 "Type of contraceptive method"
label variable m304a_13 "Type of contraceptive method"
label variable m304a_14 "Type of contraceptive method"
label variable m304a_15 "Type of contraceptive method"
label variable m304a_16 "Type of contraceptive method"
label variable m304a_17 "Type of contraceptive method"
label variable m304a_18 "Type of contraceptive method"
label variable m304a_19 "Type of contraceptive method"
label variable m304a_20 "Type of contraceptive method"
label variable mv304_01 "Knows contraceptive method"
label variable mv304_02 "Knows contraceptive method"
label variable mv304_03 "Knows contraceptive method"
label variable mv304_04 "Knows contraceptive method"
label variable mv304_05 "Knows contraceptive method"
label variable mv304_06 "Knows contraceptive method"
label variable mv304_07 "Knows contraceptive method"
label variable mv304_08 "Knows contraceptive method"
label variable mv304_09 "Knows contraceptive method"
label variable mv304_10 "Knows contraceptive method"
label variable mv304_11 "Knows contraceptive method"
label variable mv304_12 "Knows contraceptive method"
label variable mv304_13 "Knows contraceptive method"
label variable mv304_14 "Knows contraceptive method"
label variable mv304_15 "Knows contraceptive method"
label variable mv304_16 "Knows contraceptive method"
label variable mv304_17 "Knows contraceptive method"
label variable mv304_18 "Knows contraceptive method"
label variable mv304_19 "Knows contraceptive method"
label variable mv304_20 "Knows contraceptive method"
label variable mv305_01 "NA - Ever used contraceptive method"
label variable mv305_02 "NA - Ever used contraceptive method"
label variable mv305_03 "NA - Ever used contraceptive method"
label variable mv305_04 "NA - Ever used contraceptive method"
label variable mv305_05 "NA - Ever used contraceptive method"
label variable mv305_06 "NA - Ever used contraceptive method"
label variable mv305_07 "NA - Ever used contraceptive method"
label variable mv305_08 "NA - Ever used contraceptive method"
label variable mv305_09 "NA - Ever used contraceptive method"
label variable mv305_10 "NA - Ever used contraceptive method"
label variable mv305_11 "NA - Ever used contraceptive method"
label variable mv305_12 "NA - Ever used contraceptive method"
label variable mv305_13 "NA - Ever used contraceptive method"
label variable mv305_14 "NA - Ever used contraceptive method"
label variable mv305_15 "NA - Ever used contraceptive method"
label variable mv305_16 "NA - Ever used contraceptive method"
label variable mv305_17 "NA - Ever used contraceptive method"
label variable mv305_18 "NA - Ever used contraceptive method"
label variable mv305_19 "NA - Ever used contraceptive method"
label variable mv305_20 "NA - Ever used contraceptive method"
label variable mv307_01 "Contraceptive method currently used"
label variable mv307_02 "Contraceptive method currently used"
label variable mv307_03 "Contraceptive method currently used"
label variable mv307_04 "Contraceptive method currently used"
label variable mv307_05 "Contraceptive method currently used"
label variable mv307_06 "Contraceptive method currently used"
label variable mv307_07 "Contraceptive method currently used"
label variable mv307_08 "Contraceptive method currently used"
label variable mv307_09 "Contraceptive method currently used"
label variable mv307_10 "Contraceptive method currently used"
label variable mv307_11 "Contraceptive method currently used"
label variable mv307_12 "Contraceptive method currently used"
label variable mv307_13 "Contraceptive method currently used"
label variable mv307_14 "Contraceptive method currently used"
label variable mv307_15 "Contraceptive method currently used"
label variable mv307_16 "Contraceptive method currently used"
label variable mv307_17 "Contraceptive method currently used"
label variable mv307_18 "Contraceptive method currently used"
label variable mv307_19 "Contraceptive method currently used"
label variable mv307_20 "Contraceptive method currently used"
label variable mv312    "Current contraceptive method"
label variable mv313    "Current contraceptive by method type"
label variable mv323a   "Brand of condom used"
label variable mv325b   "NA - Cost of condoms (in CURRENCY) last time obtained"
label variable mv372a   "NA - Interviewer shown condom package"
label variable mv384a   "On radio heard about Family Planning in the last few months"
label variable mv384b   "On TV saw about Family Planning in the last few months"
label variable mv384c   "In newspaper read about Family Planning in the last few months"
label variable mv395    "Discussed Family Planning with health worker in last few months"
label variable mv396    "NA - Possible for a breastfeeding woman to get pregnant"
label variable mv3a09b  "NA - Number of condoms did get last time"
label variable mv3b17   "Source of condoms"
label variable mv3b25a  "Contraception is woman's business, man should not worry"
label variable mv3b25b  "Women who use contraception become promiscuous"
label variable mv463a   "Smokes cigarettes"
label variable mv463b   "Smokes pipe"
label variable mv463c   "Uses chewing tobacco"
label variable mv463d   "Uses snuff"
label variable mv463e   "NA - Smokes CS"
label variable mv463f   "NA - Smokes CS"
label variable mv463g   "NA - Smokes CS"
label variable mv463x   "Smokes other"
label variable mv463z   "Smokes nothing"
label variable mv464    "Number of cigarettes in last 24 hours"
label variable mv474    "NA - Heard of tuberculosis or TB"
label variable mv474a   "NA - Tuberculosis spread by: air through coughing or sneezing"
label variable mv474b   "NA - Tuberculosis spread by: sharing utensils"
label variable mv474c   "NA - Tuberculosis spread by: touching a person with TB"
label variable mv474d   "NA - Tuberculosis spread by: food"
label variable mv474e   "NA - Tuberculosis spread by: sexual contact"
label variable mv474f   "NA - Tuberculosis spread by: mosquito bites"
label variable mv474g   "NA - Tuberculosis spread by: CS"
label variable mv474h   "NA - Tuberculosis spread by: CS"
label variable mv474i   "NA - Tuberculosis spread by: CS"
label variable mv474j   "NA - Tuberculosis spread by: CS"
label variable mv474x   "NA - Tuberculosis spread by: other"
label variable mv474z   "NA - Don't know how tuberculosis is spread"
label variable mv475    "NA - Tuberculosis can be cured"
label variable mv476    "NA - Would want tuberculosis infection in family to remain secret"
label variable mv477    "Number of injections in last 12 months"
label variable mv478    "Number of injections administered by a health worker"
label variable mv479    "NA - Place where given injection by health worker"
label variable mv480    "Syringe and needle from new, unopened package"
label variable mv481    "Covered by health insurance"
label variable mv481a   "Health insurance type: mutual/community organization"
label variable mv481b   "Health insurance type: provided by employer"
label variable mv481c   "Health insurance type: social security"
label variable mv481d   "Health insurance type: private/commercially purchased"
label variable mv481e   "NA - Health insurance type: CS"
label variable mv481f   "NA - Health insurance type: CS"
label variable mv481g   "NA - Health insurance type: CS"
label variable mv481h   "NA - Health insurance type: CS"
label variable mv481x   "Health insurance type: other"
label variable mv482a   "NA - Arrange care of biological children under age 18***"
label variable mv482b   "NA - Primary caregiver of children under age 18***"
label variable mv482c   "NA - Arrange care of non-biological children < 18***"
label variable mv483    "Respondent circumcised"
label variable mv483a   "Age at circumcision"
label variable mv483b   "Who performed the circumcision"
label variable mv483c   "Place where circumcision was done"
label variable mv501    "Current marital status"
label variable mv502    "Currently/formerly/never in union"
label variable mv503    "Number of unions"
label variable mv504    "Currently residing with wife/partner"
label variable mv505    "Number of wives/partners"
label variable mv507    "Month of first cohabitation"
label variable mv508    "Year of first cohabitation"
label variable mv509    "Date of first cohabitation (CMC)"
label variable mv510    "Completeness of date information in MV509"
label variable mv511    "Age at first cohabitation"
label variable mv512    "Years since first cohabitation"
label variable mv513    "Cohabitation duration (grouped)"
label variable mv525    "Age at first sex"
label variable mv527    "Time since last sex"
label variable mv528    "Time since last sex (in days)"
label variable mv529    "Time since last sex (in months)"
label variable mv531    "Age at first sex (imputed)"
label variable mv532    "Flag for MV531"
label variable mv535    "Ever been married or in union"
label variable mv536    "Recent sexual activity"
label variable mv541    "NA - Intends to wait until marriage to have sex"
label variable mv602    "Fertility preference"
label variable mv603    "Preferred waiting time for birth of a/another child"
label variable mv604    "Preferred waiting time for birth of a/another child (grouped)"
label variable mv605    "Desire for more children"
label variable mv613    "Ideal number of children"
label variable mv614    "Ideal number of children (grouped)"
label variable mv616    "Desired time for future birth"
label variable mv621    "NA - Wife's desire for children***"
label variable mv627    "Ideal number of boys"
label variable mv628    "Ideal number of girls"
label variable mv629    "Ideal number of either sex"
label variable mv631    "NA - Problem if wife became pregnant***"
label variable mv633a   "NA - Wife justified refusing sex: husband has STI"
label variable mv633b   "Wife justified refusing sex: husband has other women"
label variable mv633c   "NA - Wife justified refusing sex: recent birth"
label variable mv633d   "NA - Wife justified refusing sex: tired, not in mood"
label variable mv633e   "NA - Wife justified refusing sex: CS reason"
label variable mv633f   "NA - Wife justified refusing sex: CS reason"
label variable mv633g   "NA - Wife justified refusing sex: CS reason"
label variable mv634a   "NA - Wife refuses to have sex, husband has right to: get angry"
label variable mv634b   "NA - Wife refuses to have sex, husband has right to: refuse financial support"
label variable mv634c   "NA - Wife refuses to have sex, husband has right to: use force for sex"
label variable mv634d   "NA - Wife refuses to have sex, husband has right to: have sex with another women"
label variable mv714    "Currently working"
label variable mv714a   "Have a job, but currently absent"
label variable mv716    "Occupation"
label variable mv717    "Occupation (grouped)"
label variable mv719    "NA - Works for family, others, self"
label variable mv721    "NA - Works at home or away"
label variable mv731    "Worked in last 12 months"
label variable mv732    "Employment all year/seasonal"
label variable mv739    "Person who usually decides how to spend respondent's earnings"
label variable mv740    "NA - Type of land where respondent works"
label variable mv741    "Type of earnings from respondent's work"
label variable mv743a   "Person who should have greater say: respondent's health care"
label variable mv743b   "Person who should have greater say: large household purchases"
label variable mv743c   "NA - Person who should have greater say: daily household purchases"
label variable mv743d   "NA - Person who should have greater say: visits to family or relatives"
label variable mv743e   "NA - Person who should have greater say: food to be cooked each day"
label variable mv743f   "NA - Person who should have greater say: deciding what to do with money wife ear"
label variable mv743g   "NA - Person who should have greater say: deciding how many children to have"
label variable mv744a   "Beating justified: wife goes out without telling husband"
label variable mv744b   "Beating justified: wife neglects the children"
label variable mv744c   "Beating justified: wife argues with husband"
label variable mv744d   "Beating justified: wife refuses to have sex with husband"
label variable mv744e   "Beating justified: wife burns food"
label variable mv745a   "Owns a house alone or jointly"
label variable mv745b   "Owns land alone or jointly"
label variable mv747a   "NA - Childbearing is a woman's concern"
label variable mv747b   "NA - Important for mother/child health to get assistance at delivery"
label variable mv750    "Ever heard of a Sexually Transmitted Infection (STI)"
label variable mv751    "Ever heard of AIDS"
label variable mv754bp  "NA - Reduce risk of getting HIV: do not have sex at all"
label variable mv754cp  "Reduce risk of getting HIV: always use condoms during sex"
label variable mv754dp  "Reduce risk of getting HIV: have 1 sex partner only, who has no other partners"
label variable mv754jp  "Can get HIV from mosquito bites"
label variable mv754wp  "Can get HIV by sharing food with person who has AIDS"
label variable mv756    "A healthy looking person can have HIV"
label variable mv761    "Condom used during last sex with most recent partner"
label variable mv761b   "Condom used during last sex with 2nd to most recent partner"
label variable mv761c   "Condom used during last sex with 3rd to most recent partner"
label variable mv762aa  "Source for condoms: government hospital"
label variable mv762ab  "Source for condoms: government health center"
label variable mv762ac  "Source for condoms: family planning clinic"
label variable mv762ad  "Source for condoms: mobile clinic"
label variable mv762ae  "Source for condoms: fieldworker"
label variable mv762af  "NA - Source for condoms: CS public"
label variable mv762ag  "NA - Source for condoms: CS public"
label variable mv762ah  "NA - Source for condoms: CS public"
label variable mv762ai  "Source for condoms: other public sector"
label variable mv762aj  "Source for condoms: private hospital/clinic"
label variable mv762ak  "Source for condoms: pharmacy"
label variable mv762al  "Source for condoms: private doctor"
label variable mv762am  "Source for condoms: chemist/ PMS"
label variable mv762an  "Source for condoms: mobile clinic"
label variable mv762ao  "Source for condoms: fieldworker"
label variable mv762ap  "Source for condoms: NGO"
label variable mv762aq  "NA - Source for condoms: CS private"
label variable mv762ar  "Source for condoms: other private medical sector"
label variable mv762as  "Source for condoms: shop"
label variable mv762at  "Source for condoms: church"
label variable mv762au  "Source for condoms: friends/ relatives"
label variable mv762av  "NA - Source for condoms: CS other"
label variable mv762aw  "NA - Source for condoms: CS other"
label variable mv762ax  "Source for condoms: other"
label variable mv762az  "Don't know any source for condoms"
label variable mv762ba  "Source for female condoms: government hospital"
label variable mv762bb  "Source for female condoms: government health center"
label variable mv762bc  "Source for female condoms: family planning clinic"
label variable mv762bd  "Source for female condoms: mobile clinic"
label variable mv762be  "Source for female condoms: fieldworker"
label variable mv762bf  "NA - Source for female condoms: CS public"
label variable mv762bg  "NA - Source for female condoms: CS public"
label variable mv762bh  "NA - Source for female condoms: CS public"
label variable mv762bi  "Source for female condoms: other public sector"
label variable mv762bj  "Source for female condoms: private hospital/clinic"
label variable mv762bk  "Source for female condoms: pharmacy"
label variable mv762bl  "Source for female condoms: private doctor"
label variable mv762bm  "Source for female condoms: chemist/ PMS"
label variable mv762bn  "Source for female condoms: mobile clinic"
label variable mv762bo  "Source for female condoms: fieldworker"
label variable mv762bp  "Source for female condoms: NGO"
label variable mv762bq  "NA - Source for female condoms: CS private"
label variable mv762br  "Source for female condoms: other private medical sector"
label variable mv762bs  "Source for female condoms: shop"
label variable mv762bt  "Source for female condoms: church"
label variable mv762bu  "Source for female condoms: friend/ relative"
label variable mv762bv  "NA - Source for female condoms: CS other"
label variable mv762bw  "NA - Source for female condoms: CS other"
label variable mv762bx  "Source for female condoms: other"
label variable mv762bz  "Don't know any source for female condoms"
label variable mv763a   "Had any STI in last 12 months"
label variable mv763b   "Had genital sore/ulcer in last 12 months"
label variable mv763c   "Had genital discharge in last 12 months"
label variable mv763d   "NA - Had CS STI in last 12 months"
label variable mv763e   "NA - Had CS STI in last 12 months"
label variable mv763f   "NA - Had CS STI in last 12 months"
label variable mv763g   "NA - Had CS STI in last 12 months"
label variable mv766a   "Number of sex partners, excluding spouse, in last 12 months"
label variable mv766b   "Number of sex partners, including spouse, in last 12 months"
label variable mv767a   "Relationship with most recent sex partner"
label variable mv767b   "Relationship with 2nd to most recent sex partner"
label variable mv767c   "Relationship with 3rd to most recent sex partner"
label variable mv768a   "NA - Length of time had sex relations with most recent partner"
label variable mv768b   "NA - Length of time had sex relations with 2nd to most recent partner"
label variable mv768c   "NA - Length of time had sex relations with 3rd to most recent partner"
label variable mv769    "Can get a condom"
label variable mv769a   "Can get a female condom"
label variable mv770    "Sought advice/treatment for last STI infection"
label variable mv770a   "Sought STI advice/treatment from: government hospital"
label variable mv770b   "Sought STI advice/treatment from: government health center"
label variable mv770c   "Sought STI advice/treatment from: family planning clinic"
label variable mv770d   "Sought STI advice/treatment from: mobile clinic"
label variable mv770e   "Sought STI advice/treatment from: fieldworker"
label variable mv770f   "NA - Sought STI advice/treatment from: CS public"
label variable mv770g   "NA - Sought STI advice/treatment from: CS public"
label variable mv770h   "Sought STI advice/treatment from: stand-alone VCT center"
label variable mv770i   "Sought STI advice/treatment from: other public sector"
label variable mv770j   "NA - Sought STI advice/treatment from: CS public"
label variable mv770k   "Sought STI advice/treatment from: pharmacy"
label variable mv770l   "Sought STI advice/treatment from: private hospital/clinic/doctor"
label variable mv770m   "Sought STI advice/treatment from: chemist/ PMS"
label variable mv770n   "Sought STI advice/treatment from: mobile clinic"
label variable mv770o   "Sought STI advice/treatment from: fieldworker"
label variable mv770p   "NA - Sought STI advice/treatment from: CS private"
label variable mv770q   "Sought STI advice/treatment from: stand-alone VCT center"
label variable mv770r   "Sought STI advice/treatment from: other private medical sector"
label variable mv770s   "Sought STI advice/treatment from: shop"
label variable mv770t   "NA - Sought STI advice/treatment from: CS other"
label variable mv770u   "NA - Sought STI advice/treatment from: CS other"
label variable mv770v   "NA - Sought STI advice/treatment from: CS other"
label variable mv770w   "NA - Sought STI advice/treatment from: CS other"
label variable mv770x   "Sought STI advice/treatment from: other"
label variable mv774a   "HIV transmitted during pregnancy"
label variable mv774b   "HIV transmitted during delivery"
label variable mv774c   "HIV transmitted by breastfeeding"
label variable mv775    "Knows someone who has, or is suspected of having, HIV"
label variable mv777    "Would want HIV infection in family to remain secret"
label variable mv778    "Willing to care for relative with AIDS"
label variable mv779    "A female teacher infected with HIV, but is not sick, should be allowed to contin"
label variable mv780    "Children should be taught about condoms to avoid AIDS"
label variable mv781    "Ever been tested for HIV"
label variable mv783    "Know a place to get HIV test"
label variable mv784a   "Place for HIV test: government hospital"
label variable mv784b   "Place for HIV test: government health center"
label variable mv784c   "Place for HIV test: family planning clinic"
label variable mv784d   "Place for HIV test: mobile clinic"
label variable mv784e   "Place for HIV test: fieldworker"
label variable mv784f   "NA - Place for HIV test: CS public"
label variable mv784g   "NA - Place for HIV test: CS public"
label variable mv784h   "Place for HIV test: stand-alone VCT center"
label variable mv784i   "Place for HIV test: other public sector"
label variable mv784j   "NA - Place for HIV test: CS public"
label variable mv784k   "Place for HIV test: pharmacy"
label variable mv784l   "Place for HIV test: private hospital/clinic/doctor"
label variable mv784m   "NA - Place for HIV test: CS private"
label variable mv784n   "Place for HIV test: mobile clinic"
label variable mv784o   "Place for HIV test: fieldworker"
label variable mv784p   "NA - Place for HIV test: CS private"
label variable mv784q   "Place for HIV test: stand-alone VCT center"
label variable mv784r   "Place for HIV test: other private medical sector"
label variable mv784s   "NA - Place for HIV test: CS other"
label variable mv784t   "NA - Place for HIV test: CS other"
label variable mv784u   "NA - Place for HIV test: CS other"
label variable mv784v   "NA - Place for HIV test: CS other"
label variable mv784x   "Place for HIV test: other"
label variable mv785    "Heard about other STIs"
label variable mv791    "Have ever paid anyone in exchange for sex"
label variable mv793    "Paid for sex in last 12 months"
label variable mv793a   "Condom used last time paid for sex in last 12 months"
label variable mv793b   "Condom used every time paid for sex in last 12 months"
label variable mv820    "NA - Condom used at first sex"
label variable mv822    "Wife justified asking husband to use condom if he has STI"
label variable mv823    "Can get HIV by witchcraft or supernatural means"
label variable mv824    "Drugs to avoid HIV transmission to baby during pregnancy"
label variable mv825    "Would buy vegetables from vendor with HIV"
label variable mv826    "NA - Last time tested for HIV"
label variable mv826a   "Months ago most recent HIV test"
label variable mv827    "NA - Last HIV test: on your own, offered or required"
label variable mv828    "Received result from last HIV test"
label variable mv829    "Place where last HIV test was taken"
label variable mv832b   "Time since last sex with 2nd to most recent partner"
label variable mv832c   "Time since last sex with 3rd to most recent partner"
label variable mv833a   "Used condom every time had sex with most recent partner in last 12 months"
label variable mv833b   "Used condom every time had sex with 2nd to most recent partner in last 12 months"
label variable mv833c   "Used condom every time had sex with 3rd to most recent partner in last 12 months"
label variable mv834a   "Age of most recent partner"
label variable mv834b   "Age of 2nd to most recent partner"
label variable mv834c   "Age of 3rd to most recent partner"
label variable mv835a   "NA - Alcohol consumption at last sex with most recent partner"
label variable mv835b   "NA - Alcohol consumption at last sex with 2nd to most recent partner"
label variable mv835c   "NA - Alcohol consumption at last sex with 3rd to most recent partner"
label variable mv836    "Total lifetime number of sex partners"
label variable mv837    "NA - Heard of drugs to help HIV infected people live longer"
label variable mv844    "Knows someone denied health services for having, or suspected of having HIV in l"
label variable mv845    "Knows someone denied social event for having, or suspected of having HIV in last"
label variable mv846    "Knows someone verbally abused for having, or suspected of having HIV in last 12 "
label variable mv847    "People with HIV should be ashamed of themselves"
label variable mv848    "People with HIV should be blamed for bringing disease to community"
label variable mv849    "NA - Children 12-14 should be taught to wait for sex until marriage"
label variable mv851a   "NA - Young men should wait for sex until marriage"
label variable mv851b   "NA - Most young men wait for sex until marriage"
label variable mv851c   "NA - Unmarried sexually active men should have only one partner"
label variable mv851d   "NA - Most unmarried sexually active men have only one partner"
label variable mv851e   "NA - Married men should only have sex with their wives"
label variable mv851f   "NA - Most married men only have sex with their wives"
label variable mv851g   "NA - Young women should wait for sex until marriage"
label variable mv851h   "NA - Most young women wait for sex until marriage"
label variable mv851i   "NA - Unmarried sexually active women should have only one partner"
label variable mv851j   "NA - Most unmarried sexually active women have only one partner"
label variable mv851k   "NA - Married women should only have sex with their husbands"
label variable mv851l   "NA - Most married women only have sex with their husbands"
label variable mv852a   "How long ago first had sex with most recent partner"
label variable mv852b   "How long ago first had sex with 2nd most recent partner"
label variable mv852c   "How long ago first had sex with 3rd most recent partner"
label variable mv853a   "Times in last 12 months had sex with most recent partner"
label variable mv853b   "Times in last 12 months had sex with 2nd most recent partner"
label variable mv853c   "Times in last 12 months had sex with 3rd most recent partner"
label variable mv854a   "Concurrent sexual partners"
label variable mv854b   "Cumulative concurrent sexual partners"
label variable mg100    "Ever heard of female circumcision"
label variable mg101    "NA - Ever heard of genital cutting (probed)"
label variable mg117a   "NA - Female circumcision benefit: cleanliness/hygiene"
label variable mg117b   "NA - Female circumcision benefit: social acceptance"
label variable mg117c   "NA - Female circumcision benefit: better marriage prospects"
label variable mg117d   "NA - Female circumcision benefit: virginity/prevent premarital sex"
label variable mg117e   "NA - Female circumcision benefit: greater sexual pleasure for men"
label variable mg117f   "NA - Female circumcision benefit: religious approval"
label variable mg117g   "NA - Female circumcision benefit: CS"
label variable mg117h   "NA - Female circumcision benefit: CS"
label variable mg117i   "NA - Female circumcision benefit: CS"
label variable mg117j   "NA - Female circumcision benefit: CS"
label variable mg117x   "NA - Female circumcision benefit: other"
label variable mg117y   "NA - No benefit from female circumcision"
label variable mg118    "Female circumcision required by religion"
label variable mg119    "Female circumcision: continue or be stopped"
label variable mmmidx_01 "Index to Maternal Mortality"
label variable mmmidx_02 "Index to Maternal Mortality"
label variable mmmidx_03 "Index to Maternal Mortality"
label variable mmmidx_04 "Index to Maternal Mortality"
label variable mmmidx_05 "Index to Maternal Mortality"
label variable mmmidx_06 "Index to Maternal Mortality"
label variable mmmidx_07 "Index to Maternal Mortality"
label variable mmmidx_08 "Index to Maternal Mortality"
label variable mmmidx_09 "Index to Maternal Mortality"
label variable mmmidx_10 "Index to Maternal Mortality"
label variable mmmidx_11 "Index to Maternal Mortality"
label variable mmmidx_12 "Index to Maternal Mortality"
label variable mmmidx_13 "Index to Maternal Mortality"
label variable mmmidx_14 "Index to Maternal Mortality"
label variable mmmidx_15 "Index to Maternal Mortality"
label variable mmmidx_16 "Index to Maternal Mortality"
label variable mmmidx_17 "Index to Maternal Mortality"
label variable mmmidx_18 "Index to Maternal Mortality"
label variable mmmidx_19 "Index to Maternal Mortality"
label variable mmmidx_20 "Index to Maternal Mortality"
label variable mmm1_01  "Sex of sibling"
label variable mmm1_02  "Sex of sibling"
label variable mmm1_03  "Sex of sibling"
label variable mmm1_04  "Sex of sibling"
label variable mmm1_05  "Sex of sibling"
label variable mmm1_06  "Sex of sibling"
label variable mmm1_07  "Sex of sibling"
label variable mmm1_08  "Sex of sibling"
label variable mmm1_09  "Sex of sibling"
label variable mmm1_10  "Sex of sibling"
label variable mmm1_11  "Sex of sibling"
label variable mmm1_12  "Sex of sibling"
label variable mmm1_13  "Sex of sibling"
label variable mmm1_14  "Sex of sibling"
label variable mmm1_15  "Sex of sibling"
label variable mmm1_16  "Sex of sibling"
label variable mmm1_17  "Sex of sibling"
label variable mmm1_18  "Sex of sibling"
label variable mmm1_19  "Sex of sibling"
label variable mmm1_20  "Sex of sibling"
label variable mmm2_01  "Survival status of sibling"
label variable mmm2_02  "Survival status of sibling"
label variable mmm2_03  "Survival status of sibling"
label variable mmm2_04  "Survival status of sibling"
label variable mmm2_05  "Survival status of sibling"
label variable mmm2_06  "Survival status of sibling"
label variable mmm2_07  "Survival status of sibling"
label variable mmm2_08  "Survival status of sibling"
label variable mmm2_09  "Survival status of sibling"
label variable mmm2_10  "Survival status of sibling"
label variable mmm2_11  "Survival status of sibling"
label variable mmm2_12  "Survival status of sibling"
label variable mmm2_13  "Survival status of sibling"
label variable mmm2_14  "Survival status of sibling"
label variable mmm2_15  "Survival status of sibling"
label variable mmm2_16  "Survival status of sibling"
label variable mmm2_17  "Survival status of sibling"
label variable mmm2_18  "Survival status of sibling"
label variable mmm2_19  "Survival status of sibling"
label variable mmm2_20  "Survival status of sibling"
label variable mmm3_01  "Sibling's current age"
label variable mmm3_02  "Sibling's current age"
label variable mmm3_03  "Sibling's current age"
label variable mmm3_04  "Sibling's current age"
label variable mmm3_05  "Sibling's current age"
label variable mmm3_06  "Sibling's current age"
label variable mmm3_07  "Sibling's current age"
label variable mmm3_08  "Sibling's current age"
label variable mmm3_09  "Sibling's current age"
label variable mmm3_10  "Sibling's current age"
label variable mmm3_11  "Sibling's current age"
label variable mmm3_12  "Sibling's current age"
label variable mmm3_13  "Sibling's current age"
label variable mmm3_14  "Sibling's current age"
label variable mmm3_15  "Sibling's current age"
label variable mmm3_16  "Sibling's current age"
label variable mmm3_17  "Sibling's current age"
label variable mmm3_18  "Sibling's current age"
label variable mmm3_19  "Sibling's current age"
label variable mmm3_20  "Sibling's current age"
label variable mmm4_01  "Sibling's date of birth (CMC)"
label variable mmm4_02  "Sibling's date of birth (CMC)"
label variable mmm4_03  "Sibling's date of birth (CMC)"
label variable mmm4_04  "Sibling's date of birth (CMC)"
label variable mmm4_05  "Sibling's date of birth (CMC)"
label variable mmm4_06  "Sibling's date of birth (CMC)"
label variable mmm4_07  "Sibling's date of birth (CMC)"
label variable mmm4_08  "Sibling's date of birth (CMC)"
label variable mmm4_09  "Sibling's date of birth (CMC)"
label variable mmm4_10  "Sibling's date of birth (CMC)"
label variable mmm4_11  "Sibling's date of birth (CMC)"
label variable mmm4_12  "Sibling's date of birth (CMC)"
label variable mmm4_13  "Sibling's date of birth (CMC)"
label variable mmm4_14  "Sibling's date of birth (CMC)"
label variable mmm4_15  "Sibling's date of birth (CMC)"
label variable mmm4_16  "Sibling's date of birth (CMC)"
label variable mmm4_17  "Sibling's date of birth (CMC)"
label variable mmm4_18  "Sibling's date of birth (CMC)"
label variable mmm4_19  "Sibling's date of birth (CMC)"
label variable mmm4_20  "Sibling's date of birth (CMC)"
label variable mmm6_01  "Years since sibling died"
label variable mmm6_02  "Years since sibling died"
label variable mmm6_03  "Years since sibling died"
label variable mmm6_04  "Years since sibling died"
label variable mmm6_05  "Years since sibling died"
label variable mmm6_06  "Years since sibling died"
label variable mmm6_07  "Years since sibling died"
label variable mmm6_08  "Years since sibling died"
label variable mmm6_09  "Years since sibling died"
label variable mmm6_10  "Years since sibling died"
label variable mmm6_11  "Years since sibling died"
label variable mmm6_12  "Years since sibling died"
label variable mmm6_13  "Years since sibling died"
label variable mmm6_14  "Years since sibling died"
label variable mmm6_15  "Years since sibling died"
label variable mmm6_16  "Years since sibling died"
label variable mmm6_17  "Years since sibling died"
label variable mmm6_18  "Years since sibling died"
label variable mmm6_19  "Years since sibling died"
label variable mmm6_20  "Years since sibling died"
label variable mmm7_01  "Sibling's age at death"
label variable mmm7_02  "Sibling's age at death"
label variable mmm7_03  "Sibling's age at death"
label variable mmm7_04  "Sibling's age at death"
label variable mmm7_05  "Sibling's age at death"
label variable mmm7_06  "Sibling's age at death"
label variable mmm7_07  "Sibling's age at death"
label variable mmm7_08  "Sibling's age at death"
label variable mmm7_09  "Sibling's age at death"
label variable mmm7_10  "Sibling's age at death"
label variable mmm7_11  "Sibling's age at death"
label variable mmm7_12  "Sibling's age at death"
label variable mmm7_13  "Sibling's age at death"
label variable mmm7_14  "Sibling's age at death"
label variable mmm7_15  "Sibling's age at death"
label variable mmm7_16  "Sibling's age at death"
label variable mmm7_17  "Sibling's age at death"
label variable mmm7_18  "Sibling's age at death"
label variable mmm7_19  "Sibling's age at death"
label variable mmm7_20  "Sibling's age at death"
label variable mmm8_01  "Date of death of sibling (CMC)"
label variable mmm8_02  "Date of death of sibling (CMC)"
label variable mmm8_03  "Date of death of sibling (CMC)"
label variable mmm8_04  "Date of death of sibling (CMC)"
label variable mmm8_05  "Date of death of sibling (CMC)"
label variable mmm8_06  "Date of death of sibling (CMC)"
label variable mmm8_07  "Date of death of sibling (CMC)"
label variable mmm8_08  "Date of death of sibling (CMC)"
label variable mmm8_09  "Date of death of sibling (CMC)"
label variable mmm8_10  "Date of death of sibling (CMC)"
label variable mmm8_11  "Date of death of sibling (CMC)"
label variable mmm8_12  "Date of death of sibling (CMC)"
label variable mmm8_13  "Date of death of sibling (CMC)"
label variable mmm8_14  "Date of death of sibling (CMC)"
label variable mmm8_15  "Date of death of sibling (CMC)"
label variable mmm8_16  "Date of death of sibling (CMC)"
label variable mmm8_17  "Date of death of sibling (CMC)"
label variable mmm8_18  "Date of death of sibling (CMC)"
label variable mmm8_19  "Date of death of sibling (CMC)"
label variable mmm8_20  "Date of death of sibling (CMC)"
label variable mmm9_01  "Sibling's death and pregnancy"
label variable mmm9_02  "Sibling's death and pregnancy"
label variable mmm9_03  "Sibling's death and pregnancy"
label variable mmm9_04  "Sibling's death and pregnancy"
label variable mmm9_05  "Sibling's death and pregnancy"
label variable mmm9_06  "Sibling's death and pregnancy"
label variable mmm9_07  "Sibling's death and pregnancy"
label variable mmm9_08  "Sibling's death and pregnancy"
label variable mmm9_09  "Sibling's death and pregnancy"
label variable mmm9_10  "Sibling's death and pregnancy"
label variable mmm9_11  "Sibling's death and pregnancy"
label variable mmm9_12  "Sibling's death and pregnancy"
label variable mmm9_13  "Sibling's death and pregnancy"
label variable mmm9_14  "Sibling's death and pregnancy"
label variable mmm9_15  "Sibling's death and pregnancy"
label variable mmm9_16  "Sibling's death and pregnancy"
label variable mmm9_17  "Sibling's death and pregnancy"
label variable mmm9_18  "Sibling's death and pregnancy"
label variable mmm9_19  "Sibling's death and pregnancy"
label variable mmm9_20  "Sibling's death and pregnancy"
label variable mmm14_01 "Number of sibling's children"
label variable mmm14_02 "Number of sibling's children"
label variable mmm14_03 "Number of sibling's children"
label variable mmm14_04 "Number of sibling's children"
label variable mmm14_05 "Number of sibling's children"
label variable mmm14_06 "Number of sibling's children"
label variable mmm14_07 "Number of sibling's children"
label variable mmm14_08 "Number of sibling's children"
label variable mmm14_09 "Number of sibling's children"
label variable mmm14_10 "Number of sibling's children"
label variable mmm14_11 "Number of sibling's children"
label variable mmm14_12 "Number of sibling's children"
label variable mmm14_13 "Number of sibling's children"
label variable mmm14_14 "Number of sibling's children"
label variable mmm14_15 "Number of sibling's children"
label variable mmm14_16 "Number of sibling's children"
label variable mmm14_17 "Number of sibling's children"
label variable mmm14_18 "Number of sibling's children"
label variable mmm14_19 "Number of sibling's children"
label variable mmm14_20 "Number of sibling's children"
label variable mmmc1    "Number of siblings of respondent"
label variable mmmc2    "Number of siblings born before respondent's birth"
label variable mmmc5    "Cut off age for Maternal Mortality collection (in questionnaire)"
label variable smbuild  "Building number"
label variable smstate  "State of residence"
label variable smlarea  "Local government area"
label variable smlocal  "Locality"
label variable smenumer "Enumeration area"
label variable smlang1  "Language of interview"
label variable smlang2  "Respondent's native language"
label variable smtransl "Translator used"
label variable sm302d   "Read about family planning: in a poster"
label variable sm302e   "Read about family planning: in leaflets or brochures"
label variable sm302f   "Heard about family planning: from town crier"
label variable sm302g   "Heard about family planning: from mobile public announcement"
label variable sm302ba  "FP message: As for me and my partner we 'dey kampe' with female condom"
label variable sm302bb  "FP message: Unspaced children make the going tough. For the love of your family,"
label variable sm302bc  "FP message: Well-spaced children are every parent's joy"
label variable sm302bd  "FP message: It's not too late to prevent unwanted pregnancy"
label variable sm302be  "FP message: Why is your wife looking so good?"
label variable sm302bf  "FP message: Garin munafata (Hoping)/Get it together for family planning"
label variable sm302bg  "FP message: Ya take ne/Hakan take/E fetosomo bibi (How is it? / That is how it i"
label variable sm302bx  "FP message: Other"
label variable sm302bz  "FP message: Don't remember"

#delimit ;
label define MV013   
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define MV014   
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define MV015   
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define MV022   
     1 "NW Sokoto Rural"
     2 "NW Sokoto Urban"
     3 "NW Zamfara Rural"
     4 "NW Zamfara Urban"
     5 "NW Katsina Rural"
     6 "NW Katsina Urban"
     7 "NW Jigawa Rural"
     8 "NW Jigawa Urban"
     9 "NE Yobe Rural"
    10 "NE Yobe Urban"
    11 "NE Borno Rural"
    12 "NE Borno Urban"
    13 "NE Adamawa Rural"
    14 "NE Adamawa Urban"
    15 "NE Gombe Rural"
    16 "NE Gombe Urban"
    17 "NE Bauchi Rural"
    18 "NE Bauchi Urban"
    19 "NW Kano Rural"
    20 "NW Kano Urban"
    21 "NW Kaduna Rural"
    22 "NW Kaduna Urban"
    23 "NW Kebbi Rural"
    24 "NW Kebbi Urban"
    25 "NC Niger Rural"
    26 "NC Niger Urban"
    27 "NC FCT Abuja Rural"
    28 "NC FCT Abuja Urban"
    29 "NC Nasarawa Rural"
    30 "NC Nasarawa Urban"
    31 "NC Plateau Rural"
    32 "NC Plateau Urban"
    33 "NE Taraba Rural"
    34 "NE Taraba Urban"
    35 "NC Benue Rural"
    36 "NC Benue Urban"
    37 "NC Kogi Rural"
    38 "NC Kogi Urban"
    39 "NC Kwara Rural"
    40 "NC Kwara Urban"
    41 "SW Oyo Rural"
    42 "SW Oyo Urban"
    43 "SW Osun Rural"
    44 "SW Osun Urban"
    45 "SW Ekiti Rural"
    46 "SW Ekiti Urban"
    47 "SW Ondo Rural"
    48 "SW Ondo Urban"
    49 "SS Edo Rural"
    50 "SS Edo Urban"
    51 "SE Anambra Rural"
    52 "SE Anambra Urban"
    53 "SE Enugu Rural"
    54 "SE Enugu Urban"
    55 "SE Ebonyi Rural"
    56 "SE Ebonyi Urban"
    57 "SS Cross River Rural"
    58 "SS Cross River Urban"
    59 "SS Akwa Ibom Rural"
    60 "SS Akwa Ibom Urban"
    61 "SE Abia Rural"
    62 "SE Abia Urban"
    63 "SE Imo Rural"
    64 "SE Imo Urban"
    65 "SS Rivers Rural"
    66 "SS Rivers Urban"
    67 "SS Bayelsa Rural"
    68 "SS Bayelsa Urban"
    69 "SS Delta Rural"
    70 "SS Delta Urban"
    71 "SW Lagos Urban"
    72 "SW Ogun Rural"
    73 "SW Ogun Urban"
;
label define MV023   
     1 "NW Sokoto Rural"
     2 "NW Sokoto Urban"
     3 "NW Zamfara Rural"
     4 "NW Zamfara Urban"
     5 "NW Katsina Rural"
     6 "NW Katsina Urban"
     7 "NW Jigawa Rural"
     8 "NW Jigawa Urban"
     9 "NE Yobe Rural"
    10 "NE Yobe Urban"
    11 "NE Borno Rural"
    12 "NE Borno Urban"
    13 "NE Adamawa Rural"
    14 "NE Adamawa Urban"
    15 "NE Gombe Rural"
    16 "NE Gombe Urban"
    17 "NE Bauchi Rural"
    18 "NE Bauchi Urban"
    19 "NW Kano Rural"
    20 "NW Kano Urban"
    21 "NW Kaduna Rural"
    22 "NW Kaduna Urban"
    23 "NW Kebbi Rural"
    24 "NW Kebbi Urban"
    25 "NC Niger Rural"
    26 "NC Niger Urban"
    27 "NC FCT Abuja Rural"
    28 "NC FCT Abuja Urban"
    29 "NC Nasarawa Rural"
    30 "NC Nasarawa Urban"
    31 "NC Plateau Rural"
    32 "NC Plateau Urban"
    33 "NE Taraba Rural"
    34 "NE Taraba Urban"
    35 "NC Benue Rural"
    36 "NC Benue Urban"
    37 "NC Kogi Rural"
    38 "NC Kogi Urban"
    39 "NC Kwara Rural"
    40 "NC Kwara Urban"
    41 "SW Oyo Rural"
    42 "SW Oyo Urban"
    43 "SW Osun Rural"
    44 "SW Osun Urban"
    45 "SW Ekiti Rural"
    46 "SW Ekiti Urban"
    47 "SW Ondo Rural"
    48 "SW Ondo Urban"
    49 "SS Edo Rural"
    50 "SS Edo Urban"
    51 "SE Anambra Rural"
    52 "SE Anambra Urban"
    53 "SE Enugu Rural"
    54 "SE Enugu Urban"
    55 "SE Ebonyi Rural"
    56 "SE Ebonyi Urban"
    57 "SS Cross River Rural"
    58 "SS Cross River Urban"
    59 "SS Akwa Ibom Rural"
    60 "SS Akwa Ibom Urban"
    61 "SE Abia Rural"
    62 "SE Abia Urban"
    63 "SE Imo Rural"
    64 "SE Imo Urban"
    65 "SS Rivers Rural"
    66 "SS Rivers Urban"
    67 "SS Bayelsa Rural"
    68 "SS Bayelsa Urban"
    69 "SS Delta Rural"
    70 "SS Delta Urban"
    71 "SW Lagos Urban"
    72 "SW Ogun Rural"
    73 "SW Ogun Urban"
;
label define MV024   
     1 "North Central"
     2 "North East"
     3 "North West"
     4 "South East"
     5 "South South"
     6 "South West"
;
label define MV025   
     1 "Urban"
     2 "Rural"
;
label define MV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV027   
     9 "Missing"
;
label define MV028   
   999 "Missing"
;
label define MV029   
    99 "Missing"
;
label define MV030   
   999 "Missing"
;
label define MV031   
   999 "Missing"
;
label define MV032   
    99 "Missing"
;
label define MV034   
     0 "Wife not in household"
;
label define MV034A  
     1 "Wife"
     2 "Partner"
;
label define MV034B  
    99 "Missing"
;
label define MV035   
     0 "No wives/partners"
;
label define MV801   
  9999 "Missing"
;
label define MV802   
  9999 "Missing"
;
label define MV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define MV101   
     1 "North Central"
     2 "North East"
     3 "North West"
     4 "South East"
     5 "South South"
     6 "South West"
;
label define MV102   
     1 "Urban"
     2 "Rural"
;
label define MV103   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV104   
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV105   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV106   
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define MV107   
     0 "No years completed at level MV106"
;
label define MV130   
     1 "Catholic"
     2 "Other Christian"
     3 "Islam"
     4 "Tradicionalist"
    96 "Other"
;
label define MV131   
     1 "Abua"
     2 "Adra/Adarawa"
     3 "Adun"
     4 "Afcabeya"
     5 "Afemai"
     6 "Afizire"
     7 "Agatu"
     8 "Agbassa"
     9 "Agbor"
    10 "Afo"
    11 "Ajowa"
    12 "Akpa"
    13 "Akwai"
    14 "Akye"
    15 "Alago"
    16 "Amamong"
    17 "Amo"
    18 "Ana"
    19 "Anaguta"
    20 "Ankwai"
    21 "Annang"
    22 "Arab"
    23 "Arabo"
    24 "Arbar"
    25 "Arugu"
    26 "Aten/Atam"
    27 "Attakar"
    28 "Auchi"
    29 "Aulliminden"
    30 "Awo"
    31 "Ayetoro Gbede"
    32 "Badarare"
    33 "Bade/Badawe"
    34 "Bafeke"
    35 "Bagathiya"
    36 "Baggara"
    37 "Bagunge/Badagire"
    38 "Bahnake"
    39 "Baji/Biji"
    40 "Bajju"
    41 "Bambaro"
    42 "Bambuka"
    43 "Bandawa"
    44 "Banguji"
    45 "Bankalawa"
    46 "Bchama"
    47 "Barabaci"
    48 "Barawa"
    49 "Bargawa"
    50 "Bassa"
    51 "Bekworas"
    53 "Berom"
    54 "Bini/Edo"
    55 "Bogom"
    56 "Boiyawa/Bozaya"
    57 "Bolawa/Bolewa"
    59 "Buduma"
    60 "Buko"
    61 "Bura/Babur"
    62 "Buzu"
    63 "Byazhi"
    64 "Calabar"
    65 "Chala"
    66 "Chamba"
    67 "Chiba"
    68 "Chibok(g)"
    69 "Chip"
    70 "Dadiya"
    71 "Badakare/Dakarkari"
    72 "Dakka/Doka"
    73 "Dangula"
    74 "Daurawa/Dagarawa"
    75 "Defaka"
    76 "Degima"
    77 "Delta Ibo"
    78 "Dibo"
    79 "Diguza"
    80 "Djerma"
    81 "Dmoko"
    82 "Dolchi"
    83 "Ebira/Igbira"
    84 "Ebu"
    85 "Efik"
    86 "Egba"
    87 "Egbado"
    88 "Eggon"
    89 "Egun"
    90 "Eket"
    91 "Ekoi"
    92 "Ekpeye/Afisa/Epie"
    94 "Ekulu"
    95 "Eleme"
    96 "Emu"
    97 "Esan"
    98 "Etina"
    99 "Etsako"
   100 "Etulo"
   101 "Hadejawa"
   102 "Fanso"
   103 "Femawa"
   104 "Fer"
   105 "Filiya/Fali"
   106 "Fon"
   107 "Foron"
   108 "French"
   109 "Fulani"
   110 "Gamaku"
   111 "Gamaru"
   112 "Gamuni"
   113 "Gana Gana"
   114 "Ganawuri"
   115 "Gbaju/Gbagi"
   116 "Gede/Gude/Gai"
   117 "Gerawa"
   118 "Gizmawa"
   119 "Glauda"
   120 "Gmenchi"
   121 "Gomo/Gamoyaya"
   122 "Gobiri/Gobirawa/Bogobiri"
   123 "Gujjurawa"
   124 "Guemai"
   125 "Gumbarawa"
   126 "Gunganchi"
   127 "Gwandara"
   128 "Gwantu"
   129 "Hankwe"
   130 "Hausa"
   131 "Higgi"
   132 "Ibariba"
   133 "Ibibio"
   134 "Ichen"
   135 "Idanre"
   136 "Idoma"
   137 "Igala"
   138 "Igbo/Ibo"
   139 "Igede"
   140 "Ijaw/Izon"
   141 "Ijede"
   142 "Ijeme"
   143 "Ika"
   144 "Ikajo"
   145 "Ikara"
   146 "Ikpeshi"
   147 "Ikpide"
   148 "Ikulu"
   149 "Ikwere"
   150 "Ilaje"
   151 "Irigwe"
   152 "Ishan"
   153 "Isoko"
   154 "Itsekiri"
   155 "Jaba"
   156 "Jajiri"
   157 "Jakatoe"
   158 "Jaku"
   159 "Jara"
   160 "Jarawa"
   162 "Jibu"
   163 "Jonjo"
   164 "Jukun"
   165 "Kabawa"
   166 "Kadara"
   167 "Kagoma"
   168 "Kagoro"
   169 "Kaka"
   170 "Kakanda"
   171 "Kamantam"
   172 "Kambari"
   173 "Kambu/Kangu"
   174 "Kamuku"
   175 "Kanakuru"
   176 "Kanawa"
   177 "Kaninko"
   178 "Kantanawa"
   179 "Kanuri/Beriberi"
   180 "Manga"
   181 "Karekare"
   182 "Kataf/Atyap"
   183 "Kento"
   184 "Kibaku"
   185 "Kilba"
   186 "Kirdi"
   187 "Kodki"
   188 "Kofyar"
   189 "Kona"
   190 "Koro"
   191 "Koto"
   192 "Kuenuem"
   193 "Kumbo"
   194 "Kunkawa/Kawa"
   195 "Kurama"
   196 "Kuteb"
   197 "Kuturm"
   198 "Kwale/Ukwuani"
   199 "Kwanzo"
   200 "Lagelu"
   201 "Lantang"
   202 "Lemoro"
   203 "Loh"
   204 "Lunguda"
   205 "Maba/Mbadowa"
   206 "Mada"
   207 "Mafa/Maka/Maga"
   208 "Mambila"
   209 "Mandara"
   210 "Mangus/Manju"
   211 "Marghi/mangi"
   212 "Mbwa"
   213 "Mingo"
   214 "Mirnang"
   215 "Montor"
   216 "Mtchiga/Michika"
   217 "Mumuye"
   218 "Munga"
   219 "Mupung"
   220 "Mushere"
   221 "Mwagavol"
   222 "Naiawum"
   223 "Namoen"
   224 "Ndokwa"
   225 "Ndola"
   226 "Ngamo"
   227 "Ukale"
   228 "Ngoshe"
   229 "Nili"
   230 "Ninnma"
   231 "Ninzom"
   232 "Nkoroo"
   233 "Nnebe"
   234 "Numana"
   235 "Nungu"
   236 "nunku"
   237 "Nupe"
   238 "Obubua"
   239 "Odu"
   240 "Ogoja"
   241 "Ogoni"
   242 "Ogugu"
   243 "Okori/Ogori"
   244 "Omele"
   245 "Ora"
   246 "Oron"
   247 "Owan"
   249 "Owo"
   250 "Pa'awa"
   251 "Paburi"
   252 "Paibun"
   253 "Panya"
   254 "Pasama"
   255 "Pero"
   256 "Piya"
   257 "Pyem"
   258 "Rukuba"
   259 "Rulere"
   260 "Rundawa"
   261 "Sayawa/Siyawa"
   262 "Sekere"
   263 "Sharawa"
   264 "Shomo"
   265 "Shuwa"
   266 "Somunka"
   267 "Sullubawa"
   268 "Sura"
   269 "Taira"
   270 "Tangale"
   272 "Tarok"
   273 "Tera"
   274 "Teskwa"
   275 "Tiguni ( ? )"
   276 "Tiv"
   277 "Tiyari"
   278 "Tula"
   279 "Ubaija"
   280 "Ugbia"
   281 "Uhionigbe"
   282 "Ukwuani"
   283 "Urhobo"
   284 "Uyo"
   285 "Uzaurue"
   286 "Uzeba"
   287 "Waja"
   288 "Waka"
   289 "Wanu"
   290 "Wari"
   291 "Warjawa"
   292 "Wodaabe"
   293 "Wurkum"
   294 "Yakurr"
   295 "Yandang"
   296 "Yendre"
   297 "Yonubi"
   298 "Yoruba"
   299 "Zabarmawa"
   301 "Kaje"
   302 "Igbanko"
   303 "Okori/Ogori"
   304 "Migili"
   305 "Gwari"
   306 "Uru"
   307 "Okirika"
   308 "Egi"
   309 "Ogba"
   310 "Moroa"
   311 "Marwa"
   312 "Toff"
   313 "Fulfulde"
   314 "Kabba/Okun"
   315 "Bakabe"
   316 "Burmanch"
   317 "Kalabari"
   320 "Miship"
   321 "Karimjo"
   322 "Kwa"
   323 "Angas"
   324 "Bobari"
   325 "Yarimawa"
   326 "Bakenga"
   327 "Agazawa"
   328 "Gwoza"
   329 "Zalidva"
   330 "Nyangdang"
   331 "Ngezim"
   332 "Hanbagda"
   333 "Njanyi"
   334 "Dumak"
   335 "Kwalla"
   336 "Yeskwa and Mubula"
   337 "Bile"
   338 "Offa"
   339 "Yungur"
   340 "Pura Pura"
   341 "Rindre"
   342 "Dukawa"
   343 "Ningi"
   344 "Cham"
   345 "Kamo"
   346 "Lala"
   347 "Laru"
   348 "Lisa"
   349 "Gaanda"
   350 "Ezza"
   351 "Kubasawa."
   352 "Gusu"
   353 "Ikpoma"
   354 "Buh"
   355 "Mushere"
   356 "Chakeem"
   357 "Jipal"
   358 "Ugeb"
   359 "Koma"
   360 "Verre/Kila"
   361 "Zuru"
   362 "Honna"
   363 "Kapsiki"
   364 "Jere"
   365 "Gizi Yobe"
   366 "Karekare"
   367 "Kulere"
   368 "Beteer"
   369 "Bashama"
   370 "Antocha"
   371 "Baruba/Baruntin"
   372 "Nezou"
   373 "Dibba"
   374 "Kanum"
   375 "Gasawa"
   376 "Muryan"
   377 "Bageri"
   378 "Ahu"
   379 "Basange"
   380 "Nakere"
   381 "Batunu"
   382 "Sanga"
   383 "Ohari"
   384 "Numuro"
   385 "Tangale"
   386 "Guruma"
   387 "Otuwo"
   388 "Batala"
   389 "Ogbo"
   390 "Egbema"
   391 "Dara"
   392 "Andoni"
   393 "Obolo"
   394 "Pegan"
   395 "Iyala"
   396 "Jibawa"
   397 "Mungaduso"
   398 "Okobo"
   996 "Other"
   998 "Don't know"
;
label define MV133   
    97 "Inconsistent"
;
label define MV134   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV135   
     1 "Usual resident"
     2 "Visitor"
;
label define MV149   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define MV150   
     1 "Head"
     2 "Husband"
     3 "Son"
     4 "Son-in-law"
     5 "Grandson"
     6 "Father"
     7 "Father-in-law"
     8 "Brother"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Nephew by blood"
    14 "Nephew by marriage"
    15 "Brother in law"
    98 "Don't know"
;
label define MV151   
     1 "Male"
     2 "Female"
;
label define MV152   
    97 "97+"
    98 "Don't know"
;
label define MV155   
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define MV156   
     0 "No"
     1 "Yes"
;
label define MV157   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV158   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV159   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV167   
     0 "None"
    90 "90+"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV168   
     0 "No"
     1 "Yes"
;
label define MV190   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define MV212   
    97 "Inconsistent"
;
label define MV213   
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV217   
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define MV225   
     1 "Then"
     2 "Later"
     3 "Not at all"
;
label define MV245   
    99 "Missing"
;
label define MV246   
     0 "No"
     1 "Yes"
;
label define MV247   
    99 "Missing"
;
label define MV248   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV249   
     0 "Not present"
     1 "Present"
;
label define MV250   
     1 "Hospital, health facility"
     2 "Other"
;
label define MV251   
     1 "Cost too much"
     2 "Facility closed"
     3 "Too far/no transportation"
     4 "Don't trust facility/poor quality service"
     5 "No female provider"
     6 "Not the first child"
     7 "Mother did not think it was necessary"
     8 "Respondent did not think it was necessary"
     9 "Family did not think it was necessary"
    10 "No time because baby came suddenly/unexpected"
    96 "Other"
    98 "Don't know"
;
label define MV252   
     0 "Nothing to drink"
     2 "Less than usual"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define MV301   
     0 "Knows no method"
     1 "Knows only folkloric method"
     2 "Knows only traditional method"
     3 "Knows modern method"
;
label define MV302   
     0 "Never used"
     1 "Used only folkloric method"
     2 "Used only traditional method"
     3 "Used modern method"
;
label define M304A   
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define MV304   
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV305   
     0 "No"
     1 "Yes"
;
label define MV307   
     0 "No"
     1 "Yes"
;
label define MV312   
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Implants/Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea (LAM)"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Other modern method"
    18 "Standard days method"
    19 "Survey Specific method 3"
    20 "Survey Specific method 4"
    98 "Don't know"
;
label define MV313   
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     8 "Don't know"
;
label define MV323A  
     1 "Gold circle"
     2 "Durex"
     3 "Rugh rider"
     4 "Twin lotus"
     5 "Femidom"
    96 "Other"
    98 "Don't know"
;
label define MV325B  
9999995 "Free"
9999998 "Don't know"
;
label define MV372A  
     0 "Package not seen"
     1 "Package seen"
;
label define MV384A  
     0 "No"
     1 "Yes"
;
label define MV384B  
     0 "No"
     1 "Yes"
;
label define MV384C  
     0 "No"
     1 "Yes"
;
label define MV395   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "Don't know"
;
label define MV396   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "Don't know"
;
label define MV3A09B 
   998 "Don't know"
;
label define MV3B17  
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Family planning clinic"
    14 "Mobile clinic"
    15 "Fieldworker"
    16 "Other public sector"
    20 "PRIVATE SECTOR"
    21 "Private hospital/ clinic"
    22 "Pharmacy"
    23 "Chemist/ PMS"
    24 "Private doctor"
    25 "Mobile clinic"
    26 "Other private medical sector"
    27 "Fieldworker"
    30 "OTHER"
    31 "Shop"
    32 "Church"
    33 "Friend/ relative"
    34 "NGO"
    96 "Other"
;
label define MV3B25A 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV3B25B 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV463A  
     0 "No"
     1 "Yes"
;
label define MV463B  
     0 "No"
     1 "Yes"
;
label define MV463C  
     0 "No"
     1 "Yes"
;
label define MV463D  
     0 "No"
     1 "Yes"
;
label define MV463E  
     0 "No"
     1 "Yes"
;
label define MV463F  
     0 "No"
     1 "Yes"
;
label define MV463G  
     0 "No"
     1 "Yes"
;
label define MV463X  
     0 "No"
     1 "Yes"
;
label define MV463Z  
     0 "No"
     1 "Yes, smokes nothing"
;
label define MV464   
    98 "Don't know"
;
label define MV474   
     0 "No"
     1 "Yes"
;
label define MV474A  
     0 "No"
     1 "Yes"
;
label define MV474B  
     0 "No"
     1 "Yes"
;
label define MV474C  
     0 "No"
     1 "Yes"
;
label define MV474D  
     0 "No"
     1 "Yes"
;
label define MV474E  
     0 "No"
     1 "Yes"
;
label define MV474F  
     0 "No"
     1 "Yes"
;
label define MV474G  
     0 "No"
     1 "Yes"
;
label define MV474H  
     0 "No"
     1 "Yes"
;
label define MV474I  
     0 "No"
     1 "Yes"
;
label define MV474J  
     0 "No"
     1 "Yes"
;
label define MV474X  
     0 "No"
     1 "Yes"
;
label define MV474Z  
     0 "No"
     1 "Yes"
;
label define MV475   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV476   
     0 "No"
     1 "Yes, remain a secret"
     8 "Don't know/not sure/depends"
;
label define MV477   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV478   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV479   
    10 "PUBLIC SECTOR"
    20 "PRIVATE SECTOR"
    30 "OTHER"
    96 "Other"
;
label define MV480   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV481   
     0 "No"
     1 "Yes"
;
label define MV481A  
     0 "No"
     1 "Yes"
;
label define MV481B  
     0 "No"
     1 "Yes"
;
label define MV481C  
     0 "No"
     1 "Yes"
;
label define MV481D  
     0 "No"
     1 "Yes"
;
label define MV481E  
     0 "No"
     1 "Yes"
;
label define MV481F  
     0 "No"
     1 "Yes"
;
label define MV481G  
     0 "No"
     1 "Yes"
;
label define MV481H  
     0 "No"
     1 "Yes"
;
label define MV481X  
     0 "No"
     1 "Yes"
;
label define MV482A  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV482B  
     0 "No"
     1 "Yes"
;
label define MV482C  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV483   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV483A  
    95 "During childhood (<5 years)"
    98 "Don't know"
;
label define MV483B  
     1 "Traditional practitioner / family friend"
     2 "Health worker / professional"
    96 "Other"
    98 "Don't know"
;
label define MV483C  
     1 "Health facility"
     2 "Home of a health worker / professional"
     3 "Circumcision done at home"
     4 "Ritual site"
    96 "Other home / place"
    98 "Don't know"
;
label define MV501   
     0 "Never in union"
     1 "Married"
     2 "Living with partner"
     3 "Widowed"
     4 "Divorced"
     5 "No longer living together/separated"
;
label define MV502   
     0 "Never in union"
     1 "Currently in union/living with a woman"
     2 "Formerly in union/living with a woman"
;
label define MV503   
     1 "Once"
     2 "More than once"
;
label define MV504   
     1 "Living with him"
     2 "Staying elsewhere"
;
label define MV505   
    99 "Missing"
;
label define MV510   
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define MV513   
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define MV525   
     0 "Not had sex"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV527   
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV528   
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV529   
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV531   
     0 "Not had sex"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV532   
     0 "No flag"
     1 "After interview"
     2 "After conception >= 1 year"
     3 "After conception < 1 year"
     4 "At marriage, but never married"
     5 "At marriage, but after conception"
     6 "After marriage"
;
label define MV535   
     0 "No"
     1 "Formerly married"
     2 "Formerly lived with a woman"
     3 "Both, formerly married and lived with a woman"
;
label define MV536   
     0 "Never had sex"
     1 "Active in last 4 weeks"
     3 "Not active in last 4 weeks"
;
label define MV541   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV602   
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized (respondent or partner(s))"
     5 "Declared infecund (respondent or partner(s))"
     6 "Never had sex"
     7 "Man declared infecund"
     8 "Man has no partner"
;
label define MV603   
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon, now"
   996 "Other, non-numeric"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV604   
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
;
label define MV605   
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized (respondent or partner(s))"
     7 "Declared infecund (respondent or partner(s))"
     8 "Never had sex"
;
label define MV613   
    96 "Non-numeric response"
    98 "Don't know"
;
label define MV614   
     6 "6+"
     7 "Non-numeric response"
;
label define MV616   
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "Don't know"
;
label define MV621   
     1 "Both want same"
     2 "Wife wants more"
     3 "Wife wants fewer"
     8 "Don't know"
;
label define MV627   
    96 "Other"
    98 "Don't know"
;
label define MV628   
    96 "Other"
    98 "Don't know"
;
label define MV629   
    96 "Other"
    98 "Don't know"
;
label define MV631   
     1 "Big problem"
     2 "Small problem"
     3 "No problem"
     4 "Says she can't get pregnant/not having sex"
;
label define MV633A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV634A  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634B  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634C  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634D  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV714   
     0 "No"
     1 "Yes"
;
label define MV714A  
     0 "No"
     1 "Yes"
;
label define MV716   
     0 "Not working"
   100 "Professional, Technical and Related Workers"
   101 "Accountant, bursar"
   102 "Aeronautic/ Aerospace Engineer"
   103 "Agricultural Engineer"
   104 "Agronomist"
   105 "Architect, Building Designer"
   106 "Artiste: Comedian, Composer, Film Actor, Musician, Singer"
   107 "Auditor"
   108 "Author/ Editor (Electronic or Print)"
   109 "Automobile Engineer"
   110 "Bacteriologist"
   111 "Banker"
   112 "Building Engineer"
   113 "Cartographer, Geographer"
   114 "Chemical Engineer"
   115 "Chemist"
   116 "Civil Engineer"
   117 "Civil Servant, Council worker, Director Social, Education Authority Worker"
   118 "Coach, Physical Trainer"
   119 "Communication Engineer"
   120 "Computer Engineer"
   121 "Computer Network Administrator"
   122 "Computer Programmer, System Analyst"
   123 "Demographer"
   124 "Dentist"
   125 "Dietician, Nutritionist"
   126 "Diver"
   127 "Draughtsman or Related Technician"
   128 "Economist"
   129 "Electrical Engineer, Electronics Engineer"
   130 "Aluminum Engineer, Engineer (General)"
   131 "Banner maker, Fine Artist, Graphic Artist, Sculptor, Sign writer"
   132 "Industrial Engineer"
   133 "Insurance Broker"
   134 "Interior Decorator/ Designer (Industrial and Commercial inclusive)"
   135 "Journalist/ Reporter (Electronic or Print)"
   136 "Alkali (Judge), Judge, Magistrate"
   137 "Laboratory Technologist"
   138 "Advocate, Barrister, Lawyer, Legal Practitioner, Solicitor, State Counsel"
   139 "Academician, Instructor, Lecturer, Computer Educationist"
   140 "Archivist, Curator, Librarian"
   141 "Biologist, Microbiologist"
   142 "Marine Engineer"
   143 "Mathematician"
   144 "Mechanical Engineer"
   145 "Gynecologist, Medical Doctor"
   146 "Metallurgist"
   147 "Meteorologist (Weather Forecasters)"
   148 "Mining Engineer"
   149 "Clergy, Rev. Father, Imam, Islamic Scholar, Juju Worshipper"
   150 "Navigator"
   151 "Midwife, Nurse"
   152 "Oceanographer"
   153 "Optician"
   154 "Petroleum Engineer"
   155 "Pharmacist"
   156 "Pharmacologist"
   157 "Cameramen, Photographer"
   158 "Geologist, Petroleum Geologist"
   159 "Physiotherapist"
   160 "Captain (Ship)"
   161 "Politician, Special Adviser"
   162 "Primary Health Worker, Public Health Worker"
   163 "Community Liaison Officer (C.L.O), Information Officer"
   164 "NEPA Official, Personal Assistant, Public Servant, Salary Worker"
   165 "Broadcaster, Radio and Television Programmer"
   166 "Radiologist or X-Ray Worker"
   167 "Able Seaman, Sailor"
   168 "School Inspector"
   169 "Scientist (General)"
   170 "Athlete, Basket-Ball Player, Boxer, Footballer, Sports Man/Woman"
   171 "Statistician"
   172 "Stock Broker"
   173 "Surveyor (Estate, Land Quantity)"
   174 "Governess, Teacher"
   175 "Town Planner"
   176 "Bone Setter, Herbalist, Occultist, Traditional/Native Doctor"
   177 "Translator/ Interpreter"
   178 "Veterinary Doctor"
   179 "Zoologist"
   180 "Archeologist"
   181 "Chartered Accountant"
   182 "Consultancy/Consultant, Management Consultant"
   183 "Environmentalist"
   184 "GIS Expert"
   185 "Guidance and Counseling"
   186 "International Organization Worker"
   187 "Judiciary Worker, Legal Assistant"
   188 "Life Scientist"
   189 "Modeling"
   190 "Physical Scientist"
   191 "Physiologist"
   192 "Pilot (Aircraft)"
   193 "Quranic or Arabic Teacher"
   194 "Research Officer"
   195 "Social Scientist"
   196 "Technologist"
   197 "Town Crier"
   198 "Traditional Birth Attendants (TBA)"
   199 "Technical/ Professional or Related Worker NC"
   200 "Administrative and Managerial Workers"
   201 "Administrative/ District/ Pension Manager, Administrator"
   202 "Administrative Officer, Head of Department"
   203 "Catering or Lodging Services Manager"
   204 "Computer or Information System Manager"
   205 "Construction Manager"
   206 "Diplomat"
   207 "Education Administrator, Principal (Secondary Schools), Rector"
   208 "Agricultural Manager, Farm Manager"
   209 "Financial Manager"
   210 "Office Manager"
   212 "Legislative Official, Supervisory/ Ward Councilor, Legislator"
   213 "Marketing or Sales Manager"
   214 "Matron (Schools/Hospitals inclusive)"
   215 "Medical or Health Services Manager"
   216 "Civil Society Organization (CSO), Non-Governmental Organization (NGOs)"
   217 "Officials of Political Organization"
   218 "Bakery Manager"
   219 "Property Manager, Real Estate Manager"
   220 "Purchasing Manager"
   221 "Quality Control Officer"
   222 "Storage or Distribution Manager"
   223 "NUPENG worker, Trade Unionist"
   224 "Head of Village, Traditional Chief"
   225 "Human Resource Manager, Resource Developer, Training Officer"
   226 "Transportation Manager"
   227 "Government Administrator"
   228 "Manager (General)"
   229 "Production Manager"
   299 "Administrative or Managerial Worker NC"
   300 "Office and Administrative Support Workers"
   301 "Bookkeeper, Accounts Clerk, Finance Clerk"
   302 "Clerical Staff/Clerk, Office Practice"
   303 "Correspondence or Reporting Clerk"
   304 "Business Centre Worker, Cyber Café Worker, Laminating Staff"
   305 "Executive Officer"
   306 "Library or Filing Clerk"
   307 "Mail Distribution Clerk"
   308 "Messenger"
   309 "National Youth Service Corps (NYSC)"
   310 "Post Man, Post Master"
   311 "Receptionist"
   312 "Secretary"
   313 "Stenographer, Typist"
   314 "Stock Clerk (Inventory Clerk)"
   315 "Store Attendant, Store Officer"
   316 "Telephone or Telegraph Operator"
   317 "Travel Agency Clerk"
   318 "Computer Operator, Data Entry Operator"
   319 "Shop Keeper"
   320 "Treasurer"
   399 "Office or Administrative Support Workers NC"
   400 "Sales and Related Workers"
   401 "Advertising Sales Agent"
   402 "Auctioneer"
   403 "Block Seller"
   404 "Bottle Seller"
   405 "Building Material Dealer"
   406 "Business Man/Woman"
   407 "Business Proprietor, Canopy Business Man, Land Lord"
   408 "Car/Vehicle Dealer"
   409 "Bureau de change Agent (Money Changer), Commodities"
   410 "Contractor (General)"
   411 "Cow/ Goat/ Sheep Seller"
   412 "Cow Milk Seller, Dairy Product Seller, Milk Seller"
   413 "Fish Seller"
   414 "Food Stuff Seller, Grocery Seller, Selling Rice or Bean"
   415 "Food Seller, Food Vendor, Mama Put"
   416 "Fruit Seller (Oranges, Mangoes, Pawpaw, etc.)"
   417 "Groundnut Seller"
   418 "Hand Set Dealer"
   419 "Ice Block Seller"
   420 "Insurance Sales Agent, Underwriter"
   421 "Kerosene Seller"
   422 "Kola nut Sellers"
   423 "Marketing Agent"
   424 "Meat Seller"
   425 "Mineral (Soft drink) Seller"
   426 "News vendor"
   427 "Drug Seller, Medicine Seller, Patent Medicine Seller"
   428 "Loan Officer"
   429 "Fuel Clerk, Petrol Seller"
   430 "Kunu Seller, Petty Trader, Selling Bread, Selling Ogogoro (local gin)"
   431 "Plastic Seller"
   432 "Pool Promoter/Agent"
   433 "Provision Seller"
   434 "Purchasing Agent"
   435 "Real Estate Sales Agent"
   436 "Retail Sales Agent"
   437 "Retail Trade Salesmen/ women"
   438 "Sales Representative"
   439 "Sales Supervisor"
   440 "Sales Clerk"
   441 "Shoe Seller"
   442 "Smoking Fish/Meat"
   443 "Snail Seller"
   444 "Green Leaves Seller, Soup Ingredient Seller (Onions, Crayfish, Vegetables, etc.)"
   445 "Spare Parts Dealer"
   446 "Street Hawker, Street Vendor"
   447 "Sugar cane Seller"
   448 "Tea Preparer (Mai-shayi)"
   449 "Ticket Seller"
   450 "Timber Dealer (Plywood, Planks inclusive)"
   451 "Trader (Beans)"
   452 "Trader (Cassava)"
   453 "Trader (Cement)"
   454 "Trader (Cocoa)"
   455 "Trader (Cosmetics)"
   456 "Trader (Garri)"
   457 "Trader (General)"
   458 "Trader (Groundnuts)"
   459 "Trader (Maize/ Grains)"
   460 "Trader (Onions/Gallic)"
   461 "Palm oil Seller/ Trader"
   462 "Trader (Plantain)"
   463 "Trader (Rice)"
   464 "Boutique Trading"
   465 "Trader (Yam)"
   466 "Fetching Water, Water Seller, Water Vendor"
   467 "Whole Salesmen/ women"
   468 "Wood Seller (Firewood inclusive)"
   469 "Babies Wear Seller"
   470 "Book Seller"
   471 "Electronics Dealer"
   472 "Electrical Contractor"
   473 "Gravel Seller"
   474 "Importer/Exporter"
   475 "Jewelry Seller"
   476 "Pawnbroker"
   477 "Petroleum Marketer"
   478 "Radio Seller"
   479 "Salesman/woman (except advertising)"
   480 "Sand Dealer"
   481 "Trader (Textile/Cloth)"
   482 "Trader Pepper"
   483 "Trader (Electric Item)"
   499 "Sales or Related Worker NC"
   500 "Service Workers"
   501 "Airline Hostess"
   502 "Attendant (General)"
   503 "Barber, Stylist, Beautician, Hairdresser, Hair Stylist"
   504 "Bar Operator, Bartender or Related Worker"
   505 "Building Caretaker"
   506 "Car Wash Men/Women"
   507 "Cashier"
   508 "Catering or Lodging Service Worker, Hotelier"
   509 "Cleaner"
   510 "Clearing / Forwarding Agent"
   511 "Cook, Steward, Waiter"
   512 "Courier or Mail Carrier"
   513 "Cafeteria Attendant, Dining Attendant, Dishwasher"
   514 "Embalmer, Mortuary Attendant, Undertaker"
   515 "Estate Officer"
   516 "Fire Fighter"
   517 "Food Preparation Worker, Worker in Food Preparation Company"
   518 "Food Business, Food Service Worker"
   519 "Grinder (Pepper, Melon, Tomatoes, Corn, etc.)"
   520 "GSM Call Operator"
   521 "Hotel Receptionist"
   522 "House help, Houseboy, Minder, Nanny"
   523 "Housekeeper"
   524 "Laboratory Attendant"
   525 "Farm Assistant, Job Man, Laborer (Casual Workers), Palm Cutter"
   526 "Dry Cleaner, Launderer"
   527 "Health Worker, Medical or Health Service Worker"
   528 "Military Personnel (Army, Navy and Air force), Staff Officer"
   529 "Night Guard, Night watchman"
   530 "Auxiliary Nurse, Nursing Aide"
   531 "Civil Defense (security Service Worker), Immigration Service"
   532 "Detective, Police Personnel"
   533 "Recreation Worker"
   534 "Rate Collector, Revenue/ Tax Collector"
   535 "Janitor, Security Guard or Porter"
   536 "Fumigator, Sanitation Agent, Sewage or Sanitary Inspection Worker"
   537 "Social Welfare Worker"
   538 "Telephone Service Worker"
   539 "Travel Guide and Flight Attendant"
   540 "Veterinary Related worker"
   541 "Daily Collector, Thrift Collector (Isusu, Ajo, Adashi, etc.)"
   542 "General Duties, Worker (General)"
   543 "Library Attendant"
   544 "Market Attendant"
   545 "Restaurant Owner/Worker"
   546 "Vigilante Personnel"
   547 "Volunteer Force"
   548 "Clinic/Clinical Attendant, Hospital Assistance"
   549 "Community Health"
   550 "Dispenser"
   551 "Nat. Drug Law & Enforcement Agencies (NDLEA)"
   599 "Service Workers NC"
   600 "Installations, Maintenance and Repair Workers"
   601 "Automotive Body or Related Repairer, Motor Body Sprayer"
   602 "Battery Charger"
   603 "Bicycle Repairer"
   604 "Boat Repairer"
   605 "Builder (General)"
   606 "Electrical Power-line Installer/Repairer"
   607 "Camera/ Electronic Equipment/ Radio Repairer"
   608 "Elevator Installer or Repairer"
   609 "Air conditioning/ Heating/ Refrigerator Mechanic or Repairer"
   610 "Mechanic (General)"
   611 "Motor Rewire Worker"
   612 "Re-winder"
   613 "Jober (Oil Rig Worker), Rigger or Related Worker"
   614 "Security or Fire Alarm Systems Installer"
   615 "Shoe/ Leather work Repairer, Shoe Doctor/ Repairer"
   616 "Telecommunications Equipment or Line Installer/Repairer"
   617 "Tire Repairer and Changer, Vulcanizer"
   618 "Watch Repairer"
   619 "Mechanic (Motor vehicles)"
   620 "Mechanic (Motorcycle)"
   699 "Installations, Maintenance or Repair Workers NC"
   700 "Agricultural, Animal Husbandry and Forestry Workers, Fishermen and Hunters"
   701 "Agricultural Extension Worker"
   702 "Animal Keeping/ Rearing (Cattle, Goat, Sheep, etc.), Nomadic"
   703 "Bee Rearing/Collection, Farming Honey"
   704 "Farmer (Cocoa)"
   705 "Farmer (Cotton)"
   706 "Farmer (Dairy)"
   707 "Farmer (Fish)"
   708 "Farmer (General)"
   709 "Farmer (Groundnut)"
   710 "Farmer (Livestock)"
   711 "Farmer (Mixed)"
   712 "Farmer (Poultry)"
   713 "Farmer (Sugar-cane)"
   714 "Farmer (Vegetable)"
   715 "Farmer-Cereal and Legume (Rice, Beans, Wheat, etc.)"
   716 "Farmer-Plantation (Tea, Rubber, Palm, etc.)"
   717 "Farmer-Root Crop (Cassava, Yam, etc.)"
   718 "Fisherman"
   719 "Forest or Conservation Worker"
   720 "Gardener (Nursery inclusive)"
   721 "Farmer (Fruits)"
   722 "Hunter or Related Worker"
   723 "Palm Wine Tapper"
   724 "Rubber Tapper"
   725 "Tree Fellers and Logger"
   726 "Farmer (Cash Crop)"
   727 "Tobacco Farming"
   728 "Farmer (Onions)"
   729 "Farmer (Tomatoes)"
   730 "Horticulturist"
   799 "Agricultural/ Animal Husbandry/ Forest/ Fishermen Workers NC"
   800 "Production, Construction and Extractions Workers"
   801 "Artisan, Craftsman"
   802 "Baker, Cake Designer, Confectionery Maker, Pastry Cook"
   803 "Blacksmith or Toolmaker"
   804 "Block Molder or Brick maker"
   805 "Brewer or Distiller (Local Gin, Burkutu, etc.)"
   806 "Bricklayer or Mason"
   807 "Building Contractor"
   808 "Butcher"
   809 "Carpenter or Related Wood Worker"
   810 "Chemical Processor or Related worker"
   811 "Company Worker"
   812 "Construction Worker"
   813 "Dock Worker"
   814 "Electrician or Related worker"
   815 "Engine/Machine Operator, Operator"
   816 "Factory Worker"
   817 "Fiber Preparer"
   818 "Food or Beverage Processor"
   819 "Furniture Maker"
   820 "Glass Former or Related worker"
   821 "Glazier (Window Fitters inclusive)"
   822 "Diamond Polisher/ Cutter, Gold Smith (Silver inclusive)"
   823 "Machine Assembler, Machinery Fitter, Precision Instrument Maker"
   824 "Aluminum Maker/ Smelter"
   825 "Miller (Ground nut oil, Corn, etc.)"
   826 "Miner"
   827 "Net maker"
   828 "Painter"
   829 "Paper or Paperboard Product Maker"
   830 "Petroleum Refinery Worker"
   831 "Pipe layer"
   832 "Plumber"
   833 "Printers and Related Worker"
   834 "General Foreman, Production Supervisor"
   835 "Property Developer"
   836 "Publisher (Books, Journals, Monographs, etc.)"
   837 "Rock Splitter or Quarry Worker"
   838 "Roofer"
   839 "Rubber or Plastics Product Maker"
   840 "Canoe Carving, Paddle Maker"
   841 "Shoe or Leather Goods Maker"
   842 "Stationary Engine and Related Equipment Operator"
   843 "Stone Cutter or Carver"
   844 "Structural Iron or Steel Worker"
   845 "Dressmaker, Seamstress, Tailor"
   846 "Pelt Dresser (Hides or Skin Workers), Tanner (Hide or skin worker)"
   847 "Knitter, Spinner, Textile Worker"
   848 "Ceramic Worker, Flooring, Tiles, Terrazzo and Marbles Setter"
   849 "Snuff Maker, Tobacco preparer, Tobacco Product Maker"
   850 "Upholsterer"
   851 "Cap Making, Weaver (Cap and Clothes, etc.)"
   852 "Rope Making"
   853 "Weaver (Mats, Baskets, Chairs, etc.)"
   854 "Fabricator, Iron Bender, Structural Metal Preparer, Welder"
   855 "Water Bore hole Driller, Well Drillers and Related Worker"
   856 "Wood Preparation Worker"
   857 "Fashion Designer"
   858 "Freight Handler"
   859 "Garri Processor"
   860 "Industrialist"
   861 "Light Operator"
   862 "Local Soap Making, Soap Production"
   863 "Metal Processor"
   864 "Oil Servicing Worker"
   865 "Palm oil Production"
   866 "Pipe fitter"
   867 "Potter (Pottery)"
   868 "Safety Officer"
   869 "Ship or Boat Builder"
   870 "Soldering"
   871 "Steamfitter"
   872 "Weaver (General)"
   873 "Well Digging Worker"
   874 "Dyer"
   875 "Saw Mill Worker"
   899 "Production, Construction or Extraction Workers NC"
   900 "Transportation and Material Moving Workers"
   901 "Aircraft Cargo Handling Supervisor"
   902 "Cinema Projectionist, Sound Equipment/ Studio Operator"
   903 "Achaba Rider (Okada Rider), Commercial Motor Cycle rider"
   904 "Dredge Operator"
   905 "Driver (Trailer)"
   906 "Driver (Bus/Danfo)"
   907 "Driver (General)"
   908 "Driver (Tanker)"
   909 "Driver (Taxi/Cabs)"
   910 "Driver (Truck)"
   911 "Cater pillar Operator, Excavating or Loading Machine Operator"
   912 "Gas Compressors/ Gas Pumping Station Operator"
   913 "Machine Tool Operator"
   914 "Marine Oiler or Related Marine Worker"
   915 "Material Handling or Related Equipment Operators"
   916 "Bus Conductor, Motor Vehicle Transport Conductor"
   917 "Motorboat Operator"
   918 "Railroad Conductors or Yardmaster"
   919 "Traffic Controller (Air)"
   920 "Transport Clerk"
   921 "Crane/ Forklift Operator"
   922 "Truck Pusher, Wheelbarrow Pusher"
   923 "Broadcasting Station Worker"
   924 "Commercial Driver"
   925 "Traffic Controller (Road/ Vehicle)"
   926 "Traffic Controller (Ship)"
   927 "Traffic Controller (Train)"
   928 "Transport Equipment Operator"
   929 "Transporter (General)"
   995 "Commercial Sex Worker"
   998 "Transportation or Material Moving Workers NC"
   996 "Other"
;
label define MV717   
     0 "Not working"
     1 "Professional/technical/managerial"
     2 "Clerical"
     3 "Sales"
     4 "Agriculture - self employed"
     5 "Agriculture - employee"
     6 "Household and domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    96 "Other"
    98 "Don't know"
;
label define MV719   
     1 "For family member"
     2 "For someone else"
     3 "Self-employed"
;
label define MV721   
     1 "At home"
     2 "Away"
;
label define MV731   
     0 "No"
     1 "In the past year"
     2 "Currently working"
;
label define MV732   
     1 "All year"
     2 "Seasonal"
     3 "Occasional"
;
label define MV739   
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Other"
;
label define MV740   
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
;
label define MV741   
     0 "Not paid"
     1 "Cash only"
     2 "Cash and in-kind"
     3 "In-kind only"
;
label define MV743A  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Other"
     8 "Don't know/depends"
;
label define MV743B  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Other"
     8 "Don't know/depends"
;
label define MV743C  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743D  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743E  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743F  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743G  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV744A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV745A  
     0 "Does not own"
     1 "Alone only"
     2 "Jointly only"
     3 "Both alone and jointly"
;
label define MV745B  
     0 "Does not own"
     1 "Alone only"
     2 "Jointly only"
     3 "Both alone and jointly"
;
label define MV747A  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV747B  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV750   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV751   
     0 "No"
     1 "Yes"
;
label define MV754BP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754CP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754DP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754JP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754WP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV756   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV762AA 
     0 "No"
     1 "Yes"
;
label define MV762AB 
     0 "No"
     1 "Yes"
;
label define MV762AC 
     0 "No"
     1 "Yes"
;
label define MV762AD 
     0 "No"
     1 "Yes"
;
label define MV762AE 
     0 "No"
     1 "Yes"
;
label define MV762AF 
     0 "No"
     1 "Yes"
;
label define MV762AG 
     0 "No"
     1 "Yes"
;
label define MV762AH 
     0 "No"
     1 "Yes"
;
label define MV762AI 
     0 "No"
     1 "Yes"
;
label define MV762AJ 
     0 "No"
     1 "Yes"
;
label define MV762AK 
     0 "No"
     1 "Yes"
;
label define MV762AL 
     0 "No"
     1 "Yes"
;
label define MV762AM 
     0 "No"
     1 "Yes"
;
label define MV762AN 
     0 "No"
     1 "Yes"
;
label define MV762AO 
     0 "No"
     1 "Yes"
;
label define MV762AP 
     0 "No"
     1 "Yes"
;
label define MV762AQ 
     0 "No"
     1 "Yes"
;
label define MV762AR 
     0 "No"
     1 "Yes"
;
label define MV762AS 
     0 "No"
     1 "Yes"
;
label define MV762AT 
     0 "No"
     1 "Yes"
;
label define MV762AU 
     0 "No"
     1 "Yes"
;
label define MV762AV 
     0 "No"
     1 "Yes"
;
label define MV762AW 
     0 "No"
     1 "Yes"
;
label define MV762AX 
     0 "No"
     1 "Yes"
;
label define MV762AZ 
     0 "No"
     1 "Yes: don't know"
;
label define MV762BA 
     0 "No"
     1 "Yes"
;
label define MV762BB 
     0 "No"
     1 "Yes"
;
label define MV762BC 
     0 "No"
     1 "Yes"
;
label define MV762BD 
     0 "No"
     1 "Yes"
;
label define MV762BE 
     0 "No"
     1 "Yes"
;
label define MV762BF 
     0 "No"
     1 "Yes"
;
label define MV762BG 
     0 "No"
     1 "Yes"
;
label define MV762BH 
     0 "No"
     1 "Yes"
;
label define MV762BI 
     0 "No"
     1 "Yes"
;
label define MV762BJ 
     0 "No"
     1 "Yes"
;
label define MV762BK 
     0 "No"
     1 "Yes"
;
label define MV762BL 
     0 "No"
     1 "Yes"
;
label define MV762BM 
     0 "No"
     1 "Yes"
;
label define MV762BN 
     0 "No"
     1 "Yes"
;
label define MV762BO 
     0 "No"
     1 "Yes"
;
label define MV762BP 
     0 "No"
     1 "Yes"
;
label define MV762BQ 
     0 "No"
     1 "Yes"
;
label define MV762BR 
     0 "No"
     1 "Yes"
;
label define MV762BS 
     0 "No"
     1 "Yes"
;
label define MV762BT 
     0 "No"
     1 "Yes"
;
label define MV762BU 
     0 "No"
     1 "Yes"
;
label define MV762BV 
     0 "No"
     1 "Yes"
;
label define MV762BW 
     0 "No"
     1 "Yes"
;
label define MV762BX 
     0 "No"
     1 "Yes"
;
label define MV762BZ 
     0 "No"
     1 "Yes: don't know"
;
label define MV763A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV766A  
    95 "95+"
    98 "Don't know"
;
label define MV766B  
    95 "95+"
    98 "Don't know"
;
label define MV767A  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767B  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767C  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV768A  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768B  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768C  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV769   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV769A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV770   
     0 "No"
     1 "Yes"
;
label define MV770A  
     0 "No"
     1 "Yes"
;
label define MV770B  
     0 "No"
     1 "Yes"
;
label define MV770C  
     0 "No"
     1 "Yes"
;
label define MV770D  
     0 "No"
     1 "Yes"
;
label define MV770E  
     0 "No"
     1 "Yes"
;
label define MV770F  
     0 "No"
     1 "Yes"
;
label define MV770G  
     0 "No"
     1 "Yes"
;
label define MV770H  
     0 "No"
     1 "Yes"
;
label define MV770I  
     0 "No"
     1 "Yes"
;
label define MV770J  
     0 "No"
     1 "Yes"
;
label define MV770K  
     0 "No"
     1 "Yes"
;
label define MV770L  
     0 "No"
     1 "Yes"
;
label define MV770M  
     0 "No"
     1 "Yes"
;
label define MV770N  
     0 "No"
     1 "Yes"
;
label define MV770O  
     0 "No"
     1 "Yes"
;
label define MV770P  
     0 "No"
     1 "Yes"
;
label define MV770Q  
     0 "No"
     1 "Yes"
;
label define MV770R  
     0 "No"
     1 "Yes"
;
label define MV770S  
     0 "No"
     1 "Yes"
;
label define MV770T  
     0 "No"
     1 "Yes"
;
label define MV770U  
     0 "No"
     1 "Yes"
;
label define MV770V  
     0 "No"
     1 "Yes"
;
label define MV770W  
     0 "No"
     1 "Yes"
;
label define MV770X  
     0 "No"
     1 "Yes"
;
label define MV774A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV774B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV774C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV775   
     0 "No"
     1 "Yes"
;
label define MV777   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV778   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV779   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV780   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV781   
     0 "No"
     1 "Yes"
;
label define MV783   
     0 "No"
     1 "Yes"
;
label define MV784A  
     0 "No"
     1 "Yes"
;
label define MV784B  
     0 "No"
     1 "Yes"
;
label define MV784C  
     0 "No"
     1 "Yes"
;
label define MV784D  
     0 "No"
     1 "Yes"
;
label define MV784E  
     0 "No"
     1 "Yes"
;
label define MV784F  
     0 "No"
     1 "Yes"
;
label define MV784G  
     0 "No"
     1 "Yes"
;
label define MV784H  
     0 "No"
     1 "Yes"
;
label define MV784I  
     0 "No"
     1 "Yes"
;
label define MV784J  
     0 "No"
     1 "Yes"
;
label define MV784K  
     0 "No"
     1 "Yes"
;
label define MV784L  
     0 "No"
     1 "Yes"
;
label define MV784M  
     0 "No"
     1 "Yes"
;
label define MV784N  
     0 "No"
     1 "Yes"
;
label define MV784O  
     0 "No"
     1 "Yes"
;
label define MV784P  
     0 "No"
     1 "Yes"
;
label define MV784Q  
     0 "No"
     1 "Yes"
;
label define MV784R  
     0 "No"
     1 "Yes"
;
label define MV784S  
     0 "No"
     1 "Yes"
;
label define MV784T  
     0 "No"
     1 "Yes"
;
label define MV784U  
     0 "No"
     1 "Yes"
;
label define MV784V  
     0 "No"
     1 "Yes"
;
label define MV784X  
     0 "No"
     1 "Yes"
;
label define MV785   
     0 "No"
     1 "Yes"
;
label define MV791   
     0 "No"
     1 "Yes"
;
label define MV793   
     0 "No"
     1 "Yes"
;
label define MV793A  
     0 "No"
     1 "Yes"
;
label define MV793B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV820   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV822   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV823   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV824   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV825   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV826   
     1 "Less than 12 months"
     2 "12-23 months"
     3 "2 years or more"
;
label define MV826A  
    95 "Two or more years"
    98 "Don't know"
;
label define MV827   
     1 "Asked for the test"
     2 "Offered and accepted"
     3 "Required"
;
label define MV828   
     0 "No"
     1 "Yes"
;
label define MV829   
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Stand-alone VCT center"
    14 "Family planning clinic"
    15 "Mobile clinic"
    16 "Fieldworker"
    17 "School based clinic"
    18 "Other public sector"
    20 "PRIVATE SECTOR"
    21 "Private hospital/ clinic/ private doctor"
    22 "Stand-alone VCT center"
    23 "Pharmacy"
    24 "Mobile clinic"
    25 "Fieldworker"
    26 "School based clinic"
    27 "Other private medical sector"
    30 "OTHER"
    31 "Home"
    32 "Correctional facility"
    96 "Other"
;
label define MV832B  
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV832C  
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV833A  
     0 "No"
     1 "Yes"
;
label define MV833B  
     0 "No"
     1 "Yes"
;
label define MV833C  
     0 "No"
     1 "Yes"
;
label define MV834A  
    95 "95+"
    98 "Don't know"
;
label define MV834B  
    95 "95+"
    98 "Don't know"
;
label define MV834C  
    95 "95+"
    98 "Don't know"
;
label define MV835A  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835B  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835C  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV836   
    95 "95+"
    98 "Don't know"
;
label define MV837   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV844   
     0 "No"
     1 "Yes"
     8 "Don't know anyone with AIDS"
;
label define MV845   
     0 "No"
     1 "Yes"
;
label define MV846   
     0 "No"
     1 "Yes"
;
label define MV847   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/no opinion"
;
label define MV848   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/no opinion"
;
label define MV849   
     0 "No"
     1 "Yes"
     8 "Don't know/depends"
;
label define MV851A  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851B  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851C  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851D  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851E  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851F  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851G  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851H  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851I  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851J  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851K  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851L  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV852A  
   100 "Less than one day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV852B  
   100 "Less than one day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV852C  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV853A  
    95 "95+"
    98 "Don't know"
;
label define MV853B  
    95 "95+"
    98 "Don't know"
;
label define MV853C  
    95 "95+"
    98 "Don't know"
;
label define MV854A  
     0 "No"
     1 "Yes"
;
label define MV854B  
     0 "No"
     1 "Yes"
;
label define MG100   
     0 "No"
     1 "Yes"
;
label define MG101   
     0 "No"
     1 "Yes"
;
label define MG117A  
     0 "No"
     1 "Yes"
;
label define MG117B  
     0 "No"
     1 "Yes"
;
label define MG117C  
     0 "No"
     1 "Yes"
;
label define MG117D  
     0 "No"
     1 "Yes"
;
label define MG117E  
     0 "No"
     1 "Yes"
;
label define MG117F  
     0 "No"
     1 "Yes"
;
label define MG117G  
     0 "No"
     1 "Yes"
;
label define MG117H  
     0 "No"
     1 "Yes"
;
label define MG117I  
     0 "No"
     1 "Yes"
;
label define MG117J  
     0 "No"
     1 "Yes"
;
label define MG117X  
     0 "No"
     1 "Yes"
;
label define MG117Y  
     0 "No"
     1 "Yes"
;
label define MG118   
     0 "No"
     1 "Yes"
     3 "No religion"
     8 "Don't know"
;
label define MG119   
     1 "Continued"
     2 "Stopped"
     3 "Depends"
     8 "Don't know"
;
label define MMM1    
     1 "Male"
     2 "Female"
     8 "Don't know"
;
label define MMM2    
     0 "Dead"
     1 "Alive"
     8 "Don't know"
;
label define MMM3    
    97 "97+"
    98 "Don't know"
;
label define MMM6    
    97 "97+"
    98 "Don't know"
;
label define MMM7    
    97 "97+"
    98 "Don't know"
;
label define MMM9    
     0 "Never pregnant"
     1 "Death not related"
     2 "Died while pregnant"
     3 "Died during delivery"
     4 "Since delivery"
     5 "6 weeks after delivery"
     6 "2 months after delivery"
    98 "Don't know if died while pregnant"
;
label define MMM14   
    99 "Missing"
;
label define MMMC1   
    99 "Missing"
;
label define MMMC2   
    99 "Missing"
;
label define MMMC5   
    12 "12 years"
;
label define SMSTATE 
    10 "SOKOTO"
    20 "ZAMFARA"
    30 "KATSINA"
    40 "JIGAWA"
    50 "YOBE"
    60 "BORNO"
    70 "ADAMAWA"
    80 "GOMBE"
    90 "BAUCHI"
   100 "KANO"
   110 "KADUNA"
   120 "KEBBI"
   130 "NIGER"
   140 "FCT-ABUJA"
   150 "NASARAWA"
   160 "PLATEAU"
   170 "TARABA"
   180 "BENUE"
   190 "KOGI"
   200 "KWARA"
   210 "OYO"
   220 "OSUN"
   230 "EKITI"
   240 "ONDO"
   250 "EDO"
   260 "ANAMBRA"
   270 "ENUGU"
   280 "EBONYI"
   290 "CROSS RIVER"
   300 "AKWA IBOM"
   310 "ABIA"
   320 "IMO"
   330 "RIVERS"
   340 "BAYELSA"
   350 "DELTA"
   360 "LAGOS"
   370 "OGUN"
;
label define SMLANG1 
     1 "Hausa"
     2 "Yoruba"
     3 "Igbo"
     4 "English"
     5 "Ibibio"
     6 "Other"
     7 "Pidgin"
     8 "Tiv"
;
label define SMLANG2 
     1 "Hausa"
     2 "Yoruba"
     3 "Igbo"
     4 "English"
     5 "Ibibio"
     6 "Other"
     7 "Fulani"
     8 "Ijaw/Izon/Ogbia/Nembe"
;
label define SMTRANSL
     0 "No"
     1 "Yes"
;
label define SM302D  
     0 "No"
     1 "Yes"
;
label define SM302E  
     0 "No"
     1 "Yes"
;
label define SM302F  
     0 "No"
     1 "Yes"
;
label define SM302G  
     0 "No"
     1 "Yes"
;
label define SM302BA 
     0 "No"
     1 "Yes"
;
label define SM302BB 
     0 "No"
     1 "Yes"
;
label define SM302BC 
     0 "No"
     1 "Yes"
;
label define SM302BD 
     0 "No"
     1 "Yes"
;
label define SM302BE 
     0 "No"
     1 "Yes"
;
label define SM302BF 
     0 "No"
     1 "Yes"
;
label define SM302BG 
     0 "No"
     1 "Yes"
;
label define SM302BX 
     0 "No"
     1 "Yes"
;
label define SM302BZ 
     0 "No"
     1 "Yes"
;

#delimit cr
label values mv013    MV013   
label values mv014    MV014   
label values mv015    MV015   
label values mv022    MV022   
label values mv023    MV023   
label values mv024    MV024   
label values mv025    MV025   
label values mv026    MV026   
label values mv034_1  MV034   
label values mv034_2  MV034   
label values mv034_3  MV034   
label values mv034_4  MV034   
label values mv034_5  MV034   
label values mv034_6  MV034   
label values mv034_7  MV034   
label values mv034_8  MV034   
label values mv034a_1 MV034A  
label values mv034a_2 MV034A  
label values mv034a_3 MV034A  
label values mv034a_4 MV034A  
label values mv034a_5 MV034A  
label values mv034a_6 MV034A  
label values mv034a_7 MV034A  
label values mv034a_8 MV034A  
label values mv035    MV035   
label values mv803    MV803   
label values mv101    MV101   
label values mv102    MV102   
label values mv103    MV103   
label values mv104    MV104   
label values mv105    MV105   
label values mv106    MV106   
label values mv107    MV107   
label values mv130    MV130   
label values mv131    MV131   
label values mv133    MV133   
label values mv134    MV134   
label values mv135    MV135   
label values mv149    MV149   
label values mv150    MV150   
label values mv151    MV151   
label values mv152    MV152   
label values mv155    MV155   
label values mv156    MV156   
label values mv157    MV157   
label values mv158    MV158   
label values mv159    MV159   
label values mv167    MV167   
label values mv168    MV168   
label values mv190    MV190   
label values mv212    MV212   
label values mv213    MV213   
label values mv217    MV217   
label values mv225    MV225   
label values mv246    MV246   
label values mv248    MV248   
label values mv249    MV249   
label values mv250    MV250   
label values mv251    MV251   
label values mv252    MV252   
label values mv301    MV301   
label values mv302    MV302   
label values m304a_01 M304A   
label values m304a_02 M304A   
label values m304a_03 M304A   
label values m304a_04 M304A   
label values m304a_05 M304A   
label values m304a_06 M304A   
label values m304a_07 M304A   
label values m304a_08 M304A   
label values m304a_09 M304A   
label values m304a_10 M304A   
label values m304a_11 M304A   
label values m304a_12 M304A   
label values m304a_13 M304A   
label values m304a_14 M304A   
label values m304a_15 M304A   
label values m304a_16 M304A   
label values m304a_17 M304A   
label values m304a_18 M304A   
label values m304a_19 M304A   
label values m304a_20 M304A   
label values mv304_01 MV304   
label values mv304_02 MV304   
label values mv304_03 MV304   
label values mv304_04 MV304   
label values mv304_05 MV304   
label values mv304_06 MV304   
label values mv304_07 MV304   
label values mv304_08 MV304   
label values mv304_09 MV304   
label values mv304_10 MV304   
label values mv304_11 MV304   
label values mv304_12 MV304   
label values mv304_13 MV304   
label values mv304_14 MV304   
label values mv304_15 MV304   
label values mv304_16 MV304   
label values mv304_17 MV304   
label values mv304_18 MV304   
label values mv304_19 MV304   
label values mv304_20 MV304   
label values mv305_01 MV305   
label values mv305_02 MV305   
label values mv305_03 MV305   
label values mv305_04 MV305   
label values mv305_05 MV305   
label values mv305_06 MV305   
label values mv305_07 MV305   
label values mv305_08 MV305   
label values mv305_09 MV305   
label values mv305_10 MV305   
label values mv305_11 MV305   
label values mv305_12 MV305   
label values mv305_13 MV305   
label values mv305_14 MV305   
label values mv305_15 MV305   
label values mv305_16 MV305   
label values mv305_17 MV305   
label values mv305_18 MV305   
label values mv305_19 MV305   
label values mv305_20 MV305   
label values mv307_01 MV307   
label values mv307_02 MV307   
label values mv307_03 MV307   
label values mv307_04 MV307   
label values mv307_05 MV307   
label values mv307_06 MV307   
label values mv307_07 MV307   
label values mv307_08 MV307   
label values mv307_09 MV307   
label values mv307_10 MV307   
label values mv307_11 MV307   
label values mv307_12 MV307   
label values mv307_13 MV307   
label values mv307_14 MV307   
label values mv307_15 MV307   
label values mv307_16 MV307   
label values mv307_17 MV307   
label values mv307_18 MV307   
label values mv307_19 MV307   
label values mv307_20 MV307   
label values mv312    MV312   
label values mv313    MV313   
label values mv323a   MV323A  
label values mv325b   MV325B  
label values mv372a   MV372A  
label values mv384a   MV384A  
label values mv384b   MV384B  
label values mv384c   MV384C  
label values mv395    MV395   
label values mv396    MV396   
label values mv3a09b  MV3A09B 
label values mv3b17   MV3B17  
label values mv3b25a  MV3B25A 
label values mv3b25b  MV3B25B 
label values mv463a   MV463A  
label values mv463b   MV463B  
label values mv463c   MV463C  
label values mv463d   MV463D  
label values mv463e   MV463E  
label values mv463f   MV463F  
label values mv463g   MV463G  
label values mv463x   MV463X  
label values mv463z   MV463Z  
label values mv464    MV464   
label values mv474    MV474   
label values mv474a   MV474A  
label values mv474b   MV474B  
label values mv474c   MV474C  
label values mv474d   MV474D  
label values mv474e   MV474E  
label values mv474f   MV474F  
label values mv474g   MV474G  
label values mv474h   MV474H  
label values mv474i   MV474I  
label values mv474j   MV474J  
label values mv474x   MV474X  
label values mv474z   MV474Z  
label values mv475    MV475   
label values mv476    MV476   
label values mv477    MV477   
label values mv478    MV478   
label values mv479    MV479   
label values mv480    MV480   
label values mv481    MV481   
label values mv481a   MV481A  
label values mv481b   MV481B  
label values mv481c   MV481C  
label values mv481d   MV481D  
label values mv481e   MV481E  
label values mv481f   MV481F  
label values mv481g   MV481G  
label values mv481h   MV481H  
label values mv481x   MV481X  
label values mv482a   MV482A  
label values mv482b   MV482B  
label values mv482c   MV482C  
label values mv483    MV483   
label values mv483a   MV483A  
label values mv483b   MV483B  
label values mv483c   MV483C  
label values mv501    MV501   
label values mv502    MV502   
label values mv503    MV503   
label values mv504    MV504   
label values mv510    MV510   
label values mv513    MV513   
label values mv525    MV525   
label values mv527    MV527   
label values mv528    MV528   
label values mv529    MV529   
label values mv531    MV531   
label values mv532    MV532   
label values mv535    MV535   
label values mv536    MV536   
label values mv541    MV541   
label values mv602    MV602   
label values mv603    MV603   
label values mv604    MV604   
label values mv605    MV605   
label values mv613    MV613   
label values mv614    MV614   
label values mv616    MV616   
label values mv621    MV621   
label values mv627    MV627   
label values mv628    MV628   
label values mv629    MV629   
label values mv631    MV631   
label values mv633a   MV633A  
label values mv633b   MV633B  
label values mv633c   MV633C  
label values mv633d   MV633D  
label values mv633e   MV633E  
label values mv633f   MV633F  
label values mv633g   MV633G  
label values mv634a   MV634A  
label values mv634b   MV634B  
label values mv634c   MV634C  
label values mv634d   MV634D  
label values mv714    MV714   
label values mv714a   MV714A  
label values mv716    MV716   
label values mv717    MV717   
label values mv719    MV719   
label values mv721    MV721   
label values mv731    MV731   
label values mv732    MV732   
label values mv739    MV739   
label values mv740    MV740   
label values mv741    MV741   
label values mv743a   MV743A  
label values mv743b   MV743B  
label values mv743c   MV743C  
label values mv743d   MV743D  
label values mv743e   MV743E  
label values mv743f   MV743F  
label values mv743g   MV743G  
label values mv744a   MV744A  
label values mv744b   MV744B  
label values mv744c   MV744C  
label values mv744d   MV744D  
label values mv744e   MV744E  
label values mv745a   MV745A  
label values mv745b   MV745B  
label values mv747a   MV747A  
label values mv747b   MV747B  
label values mv750    MV750   
label values mv751    MV751   
label values mv754bp  MV754BP 
label values mv754cp  MV754CP 
label values mv754dp  MV754DP 
label values mv754jp  MV754JP 
label values mv754wp  MV754WP 
label values mv756    MV756   
label values mv761    MV761   
label values mv761b   MV761B  
label values mv761c   MV761C  
label values mv762aa  MV762AA 
label values mv762ab  MV762AB 
label values mv762ac  MV762AC 
label values mv762ad  MV762AD 
label values mv762ae  MV762AE 
label values mv762af  MV762AF 
label values mv762ag  MV762AG 
label values mv762ah  MV762AH 
label values mv762ai  MV762AI 
label values mv762aj  MV762AJ 
label values mv762ak  MV762AK 
label values mv762al  MV762AL 
label values mv762am  MV762AM 
label values mv762an  MV762AN 
label values mv762ao  MV762AO 
label values mv762ap  MV762AP 
label values mv762aq  MV762AQ 
label values mv762ar  MV762AR 
label values mv762as  MV762AS 
label values mv762at  MV762AT 
label values mv762au  MV762AU 
label values mv762av  MV762AV 
label values mv762aw  MV762AW 
label values mv762ax  MV762AX 
label values mv762az  MV762AZ 
label values mv762ba  MV762BA 
label values mv762bb  MV762BB 
label values mv762bc  MV762BC 
label values mv762bd  MV762BD 
label values mv762be  MV762BE 
label values mv762bf  MV762BF 
label values mv762bg  MV762BG 
label values mv762bh  MV762BH 
label values mv762bi  MV762BI 
label values mv762bj  MV762BJ 
label values mv762bk  MV762BK 
label values mv762bl  MV762BL 
label values mv762bm  MV762BM 
label values mv762bn  MV762BN 
label values mv762bo  MV762BO 
label values mv762bp  MV762BP 
label values mv762bq  MV762BQ 
label values mv762br  MV762BR 
label values mv762bs  MV762BS 
label values mv762bt  MV762BT 
label values mv762bu  MV762BU 
label values mv762bv  MV762BV 
label values mv762bw  MV762BW 
label values mv762bx  MV762BX 
label values mv762bz  MV762BZ 
label values mv763a   MV763A  
label values mv763b   MV763B  
label values mv763c   MV763C  
label values mv763d   MV763D  
label values mv763e   MV763E  
label values mv763f   MV763F  
label values mv763g   MV763G  
label values mv766a   MV766A  
label values mv766b   MV766B  
label values mv767a   MV767A  
label values mv767b   MV767B  
label values mv767c   MV767C  
label values mv768a   MV768A  
label values mv768b   MV768B  
label values mv768c   MV768C  
label values mv769    MV769   
label values mv769a   MV769A  
label values mv770    MV770   
label values mv770a   MV770A  
label values mv770b   MV770B  
label values mv770c   MV770C  
label values mv770d   MV770D  
label values mv770e   MV770E  
label values mv770f   MV770F  
label values mv770g   MV770G  
label values mv770h   MV770H  
label values mv770i   MV770I  
label values mv770j   MV770J  
label values mv770k   MV770K  
label values mv770l   MV770L  
label values mv770m   MV770M  
label values mv770n   MV770N  
label values mv770o   MV770O  
label values mv770p   MV770P  
label values mv770q   MV770Q  
label values mv770r   MV770R  
label values mv770s   MV770S  
label values mv770t   MV770T  
label values mv770u   MV770U  
label values mv770v   MV770V  
label values mv770w   MV770W  
label values mv770x   MV770X  
label values mv774a   MV774A  
label values mv774b   MV774B  
label values mv774c   MV774C  
label values mv775    MV775   
label values mv777    MV777   
label values mv778    MV778   
label values mv779    MV779   
label values mv780    MV780   
label values mv781    MV781   
label values mv783    MV783   
label values mv784a   MV784A  
label values mv784b   MV784B  
label values mv784c   MV784C  
label values mv784d   MV784D  
label values mv784e   MV784E  
label values mv784f   MV784F  
label values mv784g   MV784G  
label values mv784h   MV784H  
label values mv784i   MV784I  
label values mv784j   MV784J  
label values mv784k   MV784K  
label values mv784l   MV784L  
label values mv784m   MV784M  
label values mv784n   MV784N  
label values mv784o   MV784O  
label values mv784p   MV784P  
label values mv784q   MV784Q  
label values mv784r   MV784R  
label values mv784s   MV784S  
label values mv784t   MV784T  
label values mv784u   MV784U  
label values mv784v   MV784V  
label values mv784x   MV784X  
label values mv785    MV785   
label values mv791    MV791   
label values mv793    MV793   
label values mv793a   MV793A  
label values mv793b   MV793B  
label values mv820    MV820   
label values mv822    MV822   
label values mv823    MV823   
label values mv824    MV824   
label values mv825    MV825   
label values mv826    MV826   
label values mv826a   MV826A  
label values mv827    MV827   
label values mv828    MV828   
label values mv829    MV829   
label values mv832b   MV832B  
label values mv832c   MV832C  
label values mv833a   MV833A  
label values mv833b   MV833B  
label values mv833c   MV833C  
label values mv834a   MV834A  
label values mv834b   MV834B  
label values mv834c   MV834C  
label values mv835a   MV835A  
label values mv835b   MV835B  
label values mv835c   MV835C  
label values mv836    MV836   
label values mv837    MV837   
label values mv844    MV844   
label values mv845    MV845   
label values mv846    MV846   
label values mv847    MV847   
label values mv848    MV848   
label values mv849    MV849   
label values mv851a   MV851A  
label values mv851b   MV851B  
label values mv851c   MV851C  
label values mv851d   MV851D  
label values mv851e   MV851E  
label values mv851f   MV851F  
label values mv851g   MV851G  
label values mv851h   MV851H  
label values mv851i   MV851I  
label values mv851j   MV851J  
label values mv851k   MV851K  
label values mv851l   MV851L  
label values mv852a   MV852A  
label values mv852b   MV852B  
label values mv852c   MV852C  
label values mv853a   MV853A  
label values mv853b   MV853B  
label values mv853c   MV853C  
label values mv854a   MV854A  
label values mv854b   MV854B  
label values mg100    MG100   
label values mg101    MG101   
label values mg117a   MG117A  
label values mg117b   MG117B  
label values mg117c   MG117C  
label values mg117d   MG117D  
label values mg117e   MG117E  
label values mg117f   MG117F  
label values mg117g   MG117G  
label values mg117h   MG117H  
label values mg117i   MG117I  
label values mg117j   MG117J  
label values mg117x   MG117X  
label values mg117y   MG117Y  
label values mg118    MG118   
label values mg119    MG119   
label values mmm1_01  MMM1    
label values mmm1_02  MMM1    
label values mmm1_03  MMM1    
label values mmm1_04  MMM1    
label values mmm1_05  MMM1    
label values mmm1_06  MMM1    
label values mmm1_07  MMM1    
label values mmm1_08  MMM1    
label values mmm1_09  MMM1    
label values mmm1_10  MMM1    
label values mmm1_11  MMM1    
label values mmm1_12  MMM1    
label values mmm1_13  MMM1    
label values mmm1_14  MMM1    
label values mmm1_15  MMM1    
label values mmm1_16  MMM1    
label values mmm1_17  MMM1    
label values mmm1_18  MMM1    
label values mmm1_19  MMM1    
label values mmm1_20  MMM1    
label values mmm2_01  MMM2    
label values mmm2_02  MMM2    
label values mmm2_03  MMM2    
label values mmm2_04  MMM2    
label values mmm2_05  MMM2    
label values mmm2_06  MMM2    
label values mmm2_07  MMM2    
label values mmm2_08  MMM2    
label values mmm2_09  MMM2    
label values mmm2_10  MMM2    
label values mmm2_11  MMM2    
label values mmm2_12  MMM2    
label values mmm2_13  MMM2    
label values mmm2_14  MMM2    
label values mmm2_15  MMM2    
label values mmm2_16  MMM2    
label values mmm2_17  MMM2    
label values mmm2_18  MMM2    
label values mmm2_19  MMM2    
label values mmm2_20  MMM2    
label values mmm3_01  MMM3    
label values mmm3_02  MMM3    
label values mmm3_03  MMM3    
label values mmm3_04  MMM3    
label values mmm3_05  MMM3    
label values mmm3_06  MMM3    
label values mmm3_07  MMM3    
label values mmm3_08  MMM3    
label values mmm3_09  MMM3    
label values mmm3_10  MMM3    
label values mmm3_11  MMM3    
label values mmm3_12  MMM3    
label values mmm3_13  MMM3    
label values mmm3_14  MMM3    
label values mmm3_15  MMM3    
label values mmm3_16  MMM3    
label values mmm3_17  MMM3    
label values mmm3_18  MMM3    
label values mmm3_19  MMM3    
label values mmm3_20  MMM3    
label values mmm6_01  MMM6    
label values mmm6_02  MMM6    
label values mmm6_03  MMM6    
label values mmm6_04  MMM6    
label values mmm6_05  MMM6    
label values mmm6_06  MMM6    
label values mmm6_07  MMM6    
label values mmm6_08  MMM6    
label values mmm6_09  MMM6    
label values mmm6_10  MMM6    
label values mmm6_11  MMM6    
label values mmm6_12  MMM6    
label values mmm6_13  MMM6    
label values mmm6_14  MMM6    
label values mmm6_15  MMM6    
label values mmm6_16  MMM6    
label values mmm6_17  MMM6    
label values mmm6_18  MMM6    
label values mmm6_19  MMM6    
label values mmm6_20  MMM6    
label values mmm7_01  MMM7    
label values mmm7_02  MMM7    
label values mmm7_03  MMM7    
label values mmm7_04  MMM7    
label values mmm7_05  MMM7    
label values mmm7_06  MMM7    
label values mmm7_07  MMM7    
label values mmm7_08  MMM7    
label values mmm7_09  MMM7    
label values mmm7_10  MMM7    
label values mmm7_11  MMM7    
label values mmm7_12  MMM7    
label values mmm7_13  MMM7    
label values mmm7_14  MMM7    
label values mmm7_15  MMM7    
label values mmm7_16  MMM7    
label values mmm7_17  MMM7    
label values mmm7_18  MMM7    
label values mmm7_19  MMM7    
label values mmm7_20  MMM7    
label values mmm9_01  MMM9    
label values mmm9_02  MMM9    
label values mmm9_03  MMM9    
label values mmm9_04  MMM9    
label values mmm9_05  MMM9    
label values mmm9_06  MMM9    
label values mmm9_07  MMM9    
label values mmm9_08  MMM9    
label values mmm9_09  MMM9    
label values mmm9_10  MMM9    
label values mmm9_11  MMM9    
label values mmm9_12  MMM9    
label values mmm9_13  MMM9    
label values mmm9_14  MMM9    
label values mmm9_15  MMM9    
label values mmm9_16  MMM9    
label values mmm9_17  MMM9    
label values mmm9_18  MMM9    
label values mmm9_19  MMM9    
label values mmm9_20  MMM9    
label values mmmc5    MMMC5   
label values smstate  SMSTATE 
label values smlang1  SMLANG1 
label values smlang2  SMLANG2 
label values smtransl SMTRANSL
label values sm302d   SM302D  
label values sm302e   SM302E  
label values sm302f   SM302F  
label values sm302g   SM302G  
label values sm302ba  SM302BA 
label values sm302bb  SM302BB 
label values sm302bc  SM302BC 
label values sm302bd  SM302BD 
label values sm302be  SM302BE 
label values sm302bf  SM302BF 
label values sm302bg  SM302BG 
label values sm302bx  SM302BX 
label values sm302bz  SM302BZ 
