infix using "CGPR5AFL.dct"

label variable hhid     "Case Identification"
label variable hvidx    "Line number"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number"
label variable hv004    "Ultimate area unit"
label variable hv005    "Sample weight"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in HH"
label variable hv011    "Number of eligible men in HH"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample stratum number"
label variable hv023    "Sample domain"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "Place of residence"
label variable hv027    "Selection for male/husb. int."
label variable hv028    "Sample weight for male subsamp"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "Office editor"
label variable hv033    "NA - Ultimate area selection prob."
label variable hv035    "NA - Number of eligible children for height & weight"
label variable hv040    "NA - Cluster altitude in meters"
label variable hv041    "NA - Total adults measured"
label variable hv042    "NA - Selection for hemoglobin"
label variable hv043    "NA - Selection for women's status module"
label variable hv044    "NA - Selection for domestic violence module"
label variable hv201    "Source of drinking water"
label variable hv202    "NA - Source of non-drinking water"
label variable hv204    "NA - Time to get to water source"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of househ."
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "NA - Have bednet for sleeping"
label variable hv228    "NA - Children under 5 slept under bednet last night"
label variable hv234    "NA - Test salt for Iodine"
label variable hv235    "NA - Location of source for water"
label variable hv236    "NA - Person fetching water"
label variable hv237    "NA - Anything done to water to make safe to drink"
label variable hv237a   "NA - Water usually treated by: boil"
label variable hv237b   "NA - Water usually treated by: add bleach/chlorine"
label variable hv237c   "NA - Water usually treated by: strain through a cloth"
label variable hv237d   "NA - Water usually treated by: use water filter"
label variable hv237e   "NA - Water usually treated by: solar disinfection"
label variable hv237f   "NA - Water usually treated by: let it stand and settle"
label variable hv237g   "NA - Water usually treated by: CS"
label variable hv237h   "NA - Water usually treated by: CS"
label variable hv237i   "NA - Water usually treated by: CS"
label variable hv237j   "NA - Water usually treated by: CS"
label variable hv237k   "NA - Water usually treated by: CS"
label variable hv237x   "NA - Water usually treated by: other"
label variable hv237z   "NA - Water usually treated by: don't know"
label variable hv238    "NA - Number of households sharing toilet"
label variable hv239    "NA - Food cooked on stove or open fire"
label variable hv240    "NA - Household has a chimney, hood or neither"
label variable hv241    "NA - Food cooked in the house / in separate building / outdo"
label variable hv242    "NA - Household has separate room used as kitchen"
label variable hv243a   "Has a mobile telephone"
label variable hv243b   "Has a watch"
label variable hv243c   "NA - Has an animal-drawn cart"
label variable hv243d   "Has a boat with a motor"
label variable hv244    "NA - Own land usable for agriculture"
label variable hv245    "NA - Hectares for agricultural land"
label variable hv246    "NA - Livestock, herds or farm animals"
label variable hv246a   "NA - Cattle own"
label variable hv246b   "NA - Cows, bulls own"
label variable hv246c   "NA - Horses, donkeys, mules own"
label variable hv246d   "NA - Goats own"
label variable hv246e   "NA - Sheep own"
label variable hv246f   "NA - Chickens own"
label variable hv246g   "NA - CS own"
label variable hv246h   "NA - CS own"
label variable hv246i   "NA - CS own"
label variable hv246j   "NA - CS own"
label variable hv246k   "NA - CS own"
label variable hv247    "NA - Owns a bank account"
label variable hv248    "NA - Number of sick people 18-59"
label variable hv249    "NA - Member of the HH died last 12 months"
label variable hv250    "NA - Number of members who died last 12 months"
label variable hv251    "NA - Number of orphans and vulnerable children"
label variable hv270    "Wealth index"
label variable hv271    "Wealth index factor score (5 decimals)"
label variable hml1     "NA - Number of mosquito nets"
label variable hml1a    "NA - Number of mosquito nets with specific information"
label variable hml2     "NA - Number of children under bednet previous night"
label variable shdistr  "District of residence"
label variable sharrond "Arrondissement of residence"
label variable shreg    "Region"
label variable shvilles "Eleven cities"
label variable shurbrur "Urban/semi-urban/rural"
label variable sh101    "Source of drinking water"
label variable sh104f   "Has a computer"
label variable sh104h   "Has gas stove"
label variable sh104i   "Has oil stove"
label variable sh110e   "Has a boat without motor"
label variable hv101    "Relationship to head"
label variable hv102    "Usual resident"
label variable hv103    "Slept last night"
label variable hv104    "Sex of household member"
label variable hv105    "Age of household members"
label variable hv106    "Highest educational level"
label variable hv107    "Highest year of education"
label variable hv108    "Education in single years"
label variable hv109    "Educational attainment"
label variable hv110    "NA - Member still in school"
label variable hv111    "Mother alive"
label variable hv112    "Mother's line number"
label variable hv113    "Father alive"
label variable hv114    "Father's line number"
label variable hv115    "Current marital status"
label variable hv116    "Currently, formerly, never m."
label variable hv117    "Eligibility for female interview"
label variable hv118    "Eligibility for male interview"
label variable hv120    "Children eligibility for height/weight and hemoglobin"
label variable hv121    "Member attended school during current school year"
label variable hv122    "NA - Educational level during current school year"
label variable hv123    "NA - Grade of education during current school year"
label variable hv124    "NA - Education in single years - current school year"
label variable hv125    "NA - Member attended school during previous school year"
label variable hv126    "NA - Educational level during previous school year"
label variable hv127    "NA - Grade of education during previous school year"
label variable hv128    "NA - Education in single years - previous school year"
label variable hv129    "NA - School attendance status"
label variable hv130    "NA - Member has been very sick for 3+ months last year"
label variable hv131    "NA - Mother has been very sick for 3+ months last year"
label variable hv132    "NA - Father has been very sick for 3+ months last year"
label variable hv133    "NA - Mother/father dead or been very sick for 3+ months"
label variable hv134    "NA - Both parents alive"
label variable hv135    "NA - Has brothers/sisters under 18 of the same father and mo"
label variable hv136    "NA - Brothers/sisters under 18 that don't live in household"
label variable hv137    "NA - Member has a blanket"
label variable hv138    "NA - Member has a pair of shoes"
label variable hv139    "NA - Member has 2+ sets of clothes"
label variable hv140    "NA - Member has a birth certificate"
label variable idxh4    "Index to household schedule"
label variable sh14     "Attended school"
label variable sh15a    "Level of education"
label variable sh15b    "Highest grade completed"

#delimit ;
label define HV007   
  2009 "***Undefined Label"
;
label define HV015   
     1 "Completed"
     2 "HH present, no resp"
     3 "HH absent"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV023   
     0 "National"
     1 "Country specific"
;
label define HV024   
     1 "Kouilou"
     2 "Niari"
     3 "Lékoumou"
     4 "Bouénza"
     5 "Pool"
     6 "Plateaux"
     7 "Cuvette"
     8 "Cuvette-Ouest"
     9 "Sangha"
    10 "Likouala"
    11 "Brazzaville"
    12 "Pointe-Noire"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV043   
     0 "Household not selected"
     1 "Household selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irirgation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irirgation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV204   
   996 "On premises"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush toilet"
    20 "PIT TOILET LATRINE"
    21 "Improved pit latrine"
    22 "Traditional pit toilet"
    30 "NO FACILITY"
    31 "No facility, bush, field"
    96 "OTHER"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth, sand"
    20 "RUDIMENTARY"
    21 "Wood planks"
    30 "FINISHED"
    31 "Parquet, polished wood"
    32 "Vinyl, linoleum"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "OTHER"
;
label define HV214   
    10 "NATURAL"
    11 "Sand"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Sand bricks"
    23 "Metal"
    30 "FINISHED"
    31 "Bricks"
    32 "Cement"
    96 "OTHER"
;
label define HV215   
    10 "NATURAL"
    11 "Grass"
    30 "FINISHED"
    31 "Metal"
    32 "Roofing shingles"
    96 "OTHER"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opp. sex"
     3 "Two adults, same sex"
     4 "Three+ related adult"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "DK"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw / shrubs / grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in HH"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No bednet in HH"
;
label define HV234   
     0 "0 PPM (No Iodine)"
     7 "Below 15 PPM"
    15 "15 PPM and above"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV236   
     1 "Adult woman"
     2 "Adult man"
     3 "Female child under 15 years old"
     4 "Male child under 15 years old"
     6 "Other"
;
label define HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237A  
     0 "No"
     1 "Yes"
;
label define HV237B  
     0 "No"
     1 "Yes"
;
label define HV237C  
     0 "No"
     1 "Yes"
;
label define HV237D  
     0 "No"
     1 "Yes"
;
label define HV237E  
     0 "No"
     1 "Yes"
;
label define HV237F  
     0 "No"
     1 "Yes"
;
label define HV237G  
     0 "No"
     1 "Yes"
;
label define HV237H  
     0 "No"
     1 "Yes"
;
label define HV237I  
     0 "No"
     1 "Yes"
;
label define HV237J  
     0 "No"
     1 "Yes"
;
label define HV237K  
     0 "No"
     1 "Yes"
;
label define HV237X  
     0 "No"
     1 "Yes"
;
label define HV237Z  
     0 "No"
     1 "Yes"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     0 "Neither chimney or hood"
     1 "Chimney"
     2 "Hood"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
    95 "More than 95"
    98 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV249   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define HV250   
     8 "DK"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SHREG   
     1 "Brazzaville"
     2 "Pointe-Noire"
     3 "Sud"
     4 "Nord"
;
label define SHVILLES
     0 "No"
     1 "Yes"
;
label define SHURBRUR
     1 "Urban"
     2 "Semi-urban"
     3 "Rural"
;
label define SH101   
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped out of yard/plot"
    21 "Protected well into dwelling"
    22 "Tube well or borehole"
    31 "Unprotected well into dwelling"
    32 "Public unprotected well"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream"
    51 "Rainwater"
    52 "Tanker truck"
    53 "Bottled water"
    96 "Other"
;
label define SH104F  
     0 "No"
     1 "Yes"
;
label define SH104H  
     0 "No"
     1 "Yes"
;
label define SH104I  
     0 "No"
     1 "Yes"
;
label define SH110E  
     0 "No"
     1 "Yes"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    98 "DK"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    97 "97+"
    98 "DK"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV107   
    98 "DK"
;
label define HV108   
    97 "Inconsistent"
    98 "DK"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
;
label define HV110   
     0 "No"
     1 "Yes"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV112   
     0 "Mother not in HH"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV114   
     0 "Father not in HH"
;
label define HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV123   
    98 "DK"
;
label define HV124   
    97 "Inconsistent"
    98 "DK"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV127   
    98 "DK"
;
label define HV128   
    97 "Inconsistent"
    98 "DK"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
;
label define HV130   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV131   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV132   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV133   
     0 "No"
     1 "Yes"
;
label define HV134   
     0 "No"
     1 "Yes"
;
label define HV135   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV136   
     0 "No"
     1 "Yes"
;
label define HV137   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV138   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV139   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     8 "DK"
;
label define SH14    
     0 "No"
     1 "Yes"
;
label define SH15A   
     0 "Pre-school"
     1 "Primary"
     2 "Secondary I"
     3 "Secondary II"
     4 "Higher"
     8 "DK"
;
label define SH15B   
     0 "< 1 year completed"
     8 "DK"
;

#delimit cr
label values hv007    HV007   
label values hv015    HV015   
label values hv020    HV020   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv043    HV043   
label values hv044    HV044   
label values hv201    HV201   
label values hv202    HV202   
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv234    HV234   
label values hv235    HV235   
label values hv236    HV236   
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237g   HV237G  
label values hv237h   HV237H  
label values hv237i   HV237I  
label values hv237j   HV237J  
label values hv237k   HV237K  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv249    HV249   
label values hv250    HV250   
label values hv270    HV270   
label values hml1     HML1    
label values shreg    SHREG   
label values shvilles SHVILLES
label values shurbrur SHURBRUR
label values sh101    SH101   
label values sh104f   SH104F  
label values sh104h   SH104H  
label values sh104i   SH104I  
label values sh110e   SH110E  
label values hv101    HV101   
label values hv102    HV102   
label values hv103    HV103   
label values hv104    HV104   
label values hv105    HV105   
label values hv106    HV106   
label values hv107    HV107   
label values hv108    HV108   
label values hv109    HV109   
label values hv110    HV110   
label values hv111    HV111   
label values hv112    HV112   
label values hv113    HV113   
label values hv114    HV114   
label values hv115    HV115   
label values hv116    HV116   
label values hv117    HV117   
label values hv118    HV118   
label values hv120    HV120   
label values hv121    HV121   
label values hv122    HV122   
label values hv123    HV123   
label values hv124    HV124   
label values hv125    HV125   
label values hv126    HV126   
label values hv127    HV127   
label values hv128    HV128   
label values hv129    HV129   
label values hv130    HV130   
label values hv131    HV131   
label values hv132    HV132   
label values hv133    HV133   
label values hv134    HV134   
label values hv135    HV135   
label values hv136    HV136   
label values hv137    HV137   
label values hv138    HV138   
label values hv139    HV139   
label values hv140    HV140   
label values sh14     SH14    
label values sh15a    SH15A   
label values sh15b    SH15B   
