infix using "C:\COUNTRIES\ET71\ETHR71FL.dct"

label variable hhid     "Case Identification"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv008a   "Date of interview Century Day Code (CDC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv011    "Number of eligible men in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "Household selected for male interview"
label variable hv028    "NA - Household weight for male subsample (6 decimals)"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv035    "Number of eligible children for height and weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "Total adults measured"
label variable hv042    "Household selected for hemoglobin"
label variable hv044    "Household selected for Domestic Violence module"
label variable hv045a   "Language of questionnaire"
label variable hv045b   "Language of interview"
label variable hv045c   "Native language of respondent"
label variable hv046    "Translator used"
label variable hv801    "Time interview started (hhmm - 24 hour clock)"
label variable hv802    "Time interview ended (hhmm - 24 hour clock)"
label variable hv803    "Length of interview in minutes"
label variable hv804    "Number of visits for biomarker"
label variable hv807d   "Day of biomarker visit"
label variable hv807m   "Month of biomarker visit"
label variable hv807y   "Year of biomarker visit"
label variable hv807c   "Date of biomarker (CMC)"
label variable hv807a   "Date of biomarker Century Day Code (CDC)"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv201a   "Water not available for at least a day last two weeks"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "NA - Has mosquito bed net for sleeping"
label variable hv228    "NA - Children under 5 slept under mosquito bed net last night"
label variable hv230a   "Place where household members wash their hands"
label variable hv230b   "Presence of water at hand washing place"
label variable hv232    "Items present: Soap or detergent"
label variable hv232b   "Items present: Ash, mud, sand"
label variable hv232c   "NA - Items present: CS"
label variable hv232d   "NA - Items present: CS"
label variable hv232e   "NA - Items present: CS"
label variable hv232y   "Items present: None"
label variable hv234    "NA - Result of salt test for iodine (PPM)"
label variable hv234a   "Result of salt test for iodine"
label variable hv235    "Location of source for water"
label variable hv236    "Person fetching water"
label variable hv237    "Anything done to water to make safe to drink"
label variable hv237a   "Water usually treated by: boil"
label variable hv237b   "Water usually treated by: add bleach/chlorine"
label variable hv237c   "Water usually treated by: strain through a cloth"
label variable hv237d   "Water usually treated by: use water filter"
label variable hv237e   "Water usually treated by: solar disinfection"
label variable hv237f   "Water usually treated by: let it stand and settle"
label variable hv237g   "NA - Water usually treated by: CS"
label variable hv237h   "NA - Water usually treated by: CS"
label variable hv237i   "NA - Water usually treated by: CS"
label variable hv237j   "NA - Water usually treated by: CS"
label variable hv237k   "NA - Water usually treated by: CS"
label variable hv237x   "Water usually treated by: other"
label variable hv237z   "Water usually treated by: don't know"
label variable hv238    "Number of households sharing toilet"
label variable hv238a   "Location of toilet facility"
label variable hv239    "NA - Food cooked on stove or open fire"
label variable hv240    "NA - Household has a chimney, hood or neither"
label variable hv241    "Food cooked in the house/ separate building/ outdoors"
label variable hv242    "Household has separate room used as kitchen"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "Has watch"
label variable hv243c   "Has animal-drawn cart"
label variable hv243d   "Has boat with a motor"
label variable hv243e   "Has a computer"
label variable hv244    "Owns land usable for agriculture"
label variable hv245    "Hectares of agricultural land (1 decimal)"
label variable hv246    "Owns livestock, herds or farm animals"
label variable hv246a   "Owns cattle"
label variable hv246b   "Owns cows/ bulls"
label variable hv246c   "Owns horses/ donkeys/ mules"
label variable hv246d   "Owns goats"
label variable hv246e   "Owns sheep"
label variable hv246f   "Owns chickens/poultry"
label variable hv246g   "Owns camels"
label variable hv246h   "Owns beehives"
label variable hv246i   "NA - Owns CS"
label variable hv246j   "NA - Owns CS"
label variable hv246k   "NA - Owns CS"
label variable hv247    "Has bank account"
label variable hv252    "Frequency household members smoke inside the house"
label variable hv253    "NA - Has dwelling been sprayed against mosquitoes in last 12 months"
label variable hv253a   "NA - Dwelling sprayed by: government worker/program"
label variable hv253b   "NA - Dwelling sprayed by: private company"
label variable hv253c   "NA - Dwelling sprayed by: NGO"
label variable hv253d   "NA - Dwelling sprayed by: CS"
label variable hv253e   "NA - Dwelling sprayed by: CS"
label variable hv253f   "NA - Dwelling sprayed by: CS"
label variable hv253g   "NA - Dwelling sprayed by: CS"
label variable hv253h   "NA - Dwelling sprayed by: CS"
label variable hv253x   "NA - Dwelling sprayed by: other"
label variable hv253z   "NA - Dwelling sprayed by: don't know"
label variable hv270    "Wealth index combined"
label variable hv271    "Wealth index factor score combined (5 decimals)"
label variable hv270a   "Wealth index for urban/rural"
label variable hv271a   "Wealth index factor score for urban/rural (5 decimals)"
label variable hml1     "NA - Number of mosquito bed nets"
label variable hml1a    "NA - Number of mosquito bed nets with specific information"
label variable hml2     "NA - Number of children under mosquito bed net previous night"
label variable chl0     "NA - Number of de-jure children 5-14 for child labor module"
label variable shintd   "Day of household interview (Ethiopia calendar)"
label variable shintm   "Month of household interview  (Ethiopia calendar)"
label variable sh121g   "Table"
label variable sh121h   "Chair"
label variable sh121i   "Bed with cotton/spring mattress"
label variable sh121j   "Electric mitad"
label variable sh121k   "Kerosene lamp/ pressure lamp"
label variable sh122h   "Bagag"
label variable sh146    "Any child or adult killed or injured in the last 12 months"
label variable hvidx_01 "Line number"
label variable hvidx_02 "Line number"
label variable hvidx_03 "Line number"
label variable hvidx_04 "Line number"
label variable hvidx_05 "Line number"
label variable hvidx_06 "Line number"
label variable hvidx_07 "Line number"
label variable hvidx_08 "Line number"
label variable hvidx_09 "Line number"
label variable hvidx_10 "Line number"
label variable hvidx_11 "Line number"
label variable hvidx_12 "Line number"
label variable hvidx_13 "Line number"
label variable hvidx_14 "Line number"
label variable hvidx_15 "Line number"
label variable hvidx_16 "Line number"
label variable hvidx_17 "Line number"
label variable hvidx_18 "Line number"
label variable hvidx_19 "Line number"
label variable hvidx_20 "Line number"
label variable hv101_01 "Relationship to head"
label variable hv101_02 "Relationship to head"
label variable hv101_03 "Relationship to head"
label variable hv101_04 "Relationship to head"
label variable hv101_05 "Relationship to head"
label variable hv101_06 "Relationship to head"
label variable hv101_07 "Relationship to head"
label variable hv101_08 "Relationship to head"
label variable hv101_09 "Relationship to head"
label variable hv101_10 "Relationship to head"
label variable hv101_11 "Relationship to head"
label variable hv101_12 "Relationship to head"
label variable hv101_13 "Relationship to head"
label variable hv101_14 "Relationship to head"
label variable hv101_15 "Relationship to head"
label variable hv101_16 "Relationship to head"
label variable hv101_17 "Relationship to head"
label variable hv101_18 "Relationship to head"
label variable hv101_19 "Relationship to head"
label variable hv101_20 "Relationship to head"
label variable hv102_01 "Usual resident"
label variable hv102_02 "Usual resident"
label variable hv102_03 "Usual resident"
label variable hv102_04 "Usual resident"
label variable hv102_05 "Usual resident"
label variable hv102_06 "Usual resident"
label variable hv102_07 "Usual resident"
label variable hv102_08 "Usual resident"
label variable hv102_09 "Usual resident"
label variable hv102_10 "Usual resident"
label variable hv102_11 "Usual resident"
label variable hv102_12 "Usual resident"
label variable hv102_13 "Usual resident"
label variable hv102_14 "Usual resident"
label variable hv102_15 "Usual resident"
label variable hv102_16 "Usual resident"
label variable hv102_17 "Usual resident"
label variable hv102_18 "Usual resident"
label variable hv102_19 "Usual resident"
label variable hv102_20 "Usual resident"
label variable hv103_01 "Slept last night"
label variable hv103_02 "Slept last night"
label variable hv103_03 "Slept last night"
label variable hv103_04 "Slept last night"
label variable hv103_05 "Slept last night"
label variable hv103_06 "Slept last night"
label variable hv103_07 "Slept last night"
label variable hv103_08 "Slept last night"
label variable hv103_09 "Slept last night"
label variable hv103_10 "Slept last night"
label variable hv103_11 "Slept last night"
label variable hv103_12 "Slept last night"
label variable hv103_13 "Slept last night"
label variable hv103_14 "Slept last night"
label variable hv103_15 "Slept last night"
label variable hv103_16 "Slept last night"
label variable hv103_17 "Slept last night"
label variable hv103_18 "Slept last night"
label variable hv103_19 "Slept last night"
label variable hv103_20 "Slept last night"
label variable hv104_01 "Sex of household member"
label variable hv104_02 "Sex of household member"
label variable hv104_03 "Sex of household member"
label variable hv104_04 "Sex of household member"
label variable hv104_05 "Sex of household member"
label variable hv104_06 "Sex of household member"
label variable hv104_07 "Sex of household member"
label variable hv104_08 "Sex of household member"
label variable hv104_09 "Sex of household member"
label variable hv104_10 "Sex of household member"
label variable hv104_11 "Sex of household member"
label variable hv104_12 "Sex of household member"
label variable hv104_13 "Sex of household member"
label variable hv104_14 "Sex of household member"
label variable hv104_15 "Sex of household member"
label variable hv104_16 "Sex of household member"
label variable hv104_17 "Sex of household member"
label variable hv104_18 "Sex of household member"
label variable hv104_19 "Sex of household member"
label variable hv104_20 "Sex of household member"
label variable hv105_01 "Age of household members"
label variable hv105_02 "Age of household members"
label variable hv105_03 "Age of household members"
label variable hv105_04 "Age of household members"
label variable hv105_05 "Age of household members"
label variable hv105_06 "Age of household members"
label variable hv105_07 "Age of household members"
label variable hv105_08 "Age of household members"
label variable hv105_09 "Age of household members"
label variable hv105_10 "Age of household members"
label variable hv105_11 "Age of household members"
label variable hv105_12 "Age of household members"
label variable hv105_13 "Age of household members"
label variable hv105_14 "Age of household members"
label variable hv105_15 "Age of household members"
label variable hv105_16 "Age of household members"
label variable hv105_17 "Age of household members"
label variable hv105_18 "Age of household members"
label variable hv105_19 "Age of household members"
label variable hv105_20 "Age of household members"
label variable hv106_01 "Highest educational level attained"
label variable hv106_02 "Highest educational level attained"
label variable hv106_03 "Highest educational level attained"
label variable hv106_04 "Highest educational level attained"
label variable hv106_05 "Highest educational level attained"
label variable hv106_06 "Highest educational level attained"
label variable hv106_07 "Highest educational level attained"
label variable hv106_08 "Highest educational level attained"
label variable hv106_09 "Highest educational level attained"
label variable hv106_10 "Highest educational level attained"
label variable hv106_11 "Highest educational level attained"
label variable hv106_12 "Highest educational level attained"
label variable hv106_13 "Highest educational level attained"
label variable hv106_14 "Highest educational level attained"
label variable hv106_15 "Highest educational level attained"
label variable hv106_16 "Highest educational level attained"
label variable hv106_17 "Highest educational level attained"
label variable hv106_18 "Highest educational level attained"
label variable hv106_19 "Highest educational level attained"
label variable hv106_20 "Highest educational level attained"
label variable hv107_01 "Highest year of education completed"
label variable hv107_02 "Highest year of education completed"
label variable hv107_03 "Highest year of education completed"
label variable hv107_04 "Highest year of education completed"
label variable hv107_05 "Highest year of education completed"
label variable hv107_06 "Highest year of education completed"
label variable hv107_07 "Highest year of education completed"
label variable hv107_08 "Highest year of education completed"
label variable hv107_09 "Highest year of education completed"
label variable hv107_10 "Highest year of education completed"
label variable hv107_11 "Highest year of education completed"
label variable hv107_12 "Highest year of education completed"
label variable hv107_13 "Highest year of education completed"
label variable hv107_14 "Highest year of education completed"
label variable hv107_15 "Highest year of education completed"
label variable hv107_16 "Highest year of education completed"
label variable hv107_17 "Highest year of education completed"
label variable hv107_18 "Highest year of education completed"
label variable hv107_19 "Highest year of education completed"
label variable hv107_20 "Highest year of education completed"
label variable hv108_01 "Education completed in single years"
label variable hv108_02 "Education completed in single years"
label variable hv108_03 "Education completed in single years"
label variable hv108_04 "Education completed in single years"
label variable hv108_05 "Education completed in single years"
label variable hv108_06 "Education completed in single years"
label variable hv108_07 "Education completed in single years"
label variable hv108_08 "Education completed in single years"
label variable hv108_09 "Education completed in single years"
label variable hv108_10 "Education completed in single years"
label variable hv108_11 "Education completed in single years"
label variable hv108_12 "Education completed in single years"
label variable hv108_13 "Education completed in single years"
label variable hv108_14 "Education completed in single years"
label variable hv108_15 "Education completed in single years"
label variable hv108_16 "Education completed in single years"
label variable hv108_17 "Education completed in single years"
label variable hv108_18 "Education completed in single years"
label variable hv108_19 "Education completed in single years"
label variable hv108_20 "Education completed in single years"
label variable hv109_01 "Educational attainment"
label variable hv109_02 "Educational attainment"
label variable hv109_03 "Educational attainment"
label variable hv109_04 "Educational attainment"
label variable hv109_05 "Educational attainment"
label variable hv109_06 "Educational attainment"
label variable hv109_07 "Educational attainment"
label variable hv109_08 "Educational attainment"
label variable hv109_09 "Educational attainment"
label variable hv109_10 "Educational attainment"
label variable hv109_11 "Educational attainment"
label variable hv109_12 "Educational attainment"
label variable hv109_13 "Educational attainment"
label variable hv109_14 "Educational attainment"
label variable hv109_15 "Educational attainment"
label variable hv109_16 "Educational attainment"
label variable hv109_17 "Educational attainment"
label variable hv109_18 "Educational attainment"
label variable hv109_19 "Educational attainment"
label variable hv109_20 "Educational attainment"
label variable hv110_01 "NA - Member still in school"
label variable hv110_02 "NA - Member still in school"
label variable hv110_03 "NA - Member still in school"
label variable hv110_04 "NA - Member still in school"
label variable hv110_05 "NA - Member still in school"
label variable hv110_06 "NA - Member still in school"
label variable hv110_07 "NA - Member still in school"
label variable hv110_08 "NA - Member still in school"
label variable hv110_09 "NA - Member still in school"
label variable hv110_10 "NA - Member still in school"
label variable hv110_11 "NA - Member still in school"
label variable hv110_12 "NA - Member still in school"
label variable hv110_13 "NA - Member still in school"
label variable hv110_14 "NA - Member still in school"
label variable hv110_15 "NA - Member still in school"
label variable hv110_16 "NA - Member still in school"
label variable hv110_17 "NA - Member still in school"
label variable hv110_18 "NA - Member still in school"
label variable hv110_19 "NA - Member still in school"
label variable hv110_20 "NA - Member still in school"
label variable hv111_01 "Mother alive"
label variable hv111_02 "Mother alive"
label variable hv111_03 "Mother alive"
label variable hv111_04 "Mother alive"
label variable hv111_05 "Mother alive"
label variable hv111_06 "Mother alive"
label variable hv111_07 "Mother alive"
label variable hv111_08 "Mother alive"
label variable hv111_09 "Mother alive"
label variable hv111_10 "Mother alive"
label variable hv111_11 "Mother alive"
label variable hv111_12 "Mother alive"
label variable hv111_13 "Mother alive"
label variable hv111_14 "Mother alive"
label variable hv111_15 "Mother alive"
label variable hv111_16 "Mother alive"
label variable hv111_17 "Mother alive"
label variable hv111_18 "Mother alive"
label variable hv111_19 "Mother alive"
label variable hv111_20 "Mother alive"
label variable hv112_01 "Mother's line number"
label variable hv112_02 "Mother's line number"
label variable hv112_03 "Mother's line number"
label variable hv112_04 "Mother's line number"
label variable hv112_05 "Mother's line number"
label variable hv112_06 "Mother's line number"
label variable hv112_07 "Mother's line number"
label variable hv112_08 "Mother's line number"
label variable hv112_09 "Mother's line number"
label variable hv112_10 "Mother's line number"
label variable hv112_11 "Mother's line number"
label variable hv112_12 "Mother's line number"
label variable hv112_13 "Mother's line number"
label variable hv112_14 "Mother's line number"
label variable hv112_15 "Mother's line number"
label variable hv112_16 "Mother's line number"
label variable hv112_17 "Mother's line number"
label variable hv112_18 "Mother's line number"
label variable hv112_19 "Mother's line number"
label variable hv112_20 "Mother's line number"
label variable hv113_01 "Father alive"
label variable hv113_02 "Father alive"
label variable hv113_03 "Father alive"
label variable hv113_04 "Father alive"
label variable hv113_05 "Father alive"
label variable hv113_06 "Father alive"
label variable hv113_07 "Father alive"
label variable hv113_08 "Father alive"
label variable hv113_09 "Father alive"
label variable hv113_10 "Father alive"
label variable hv113_11 "Father alive"
label variable hv113_12 "Father alive"
label variable hv113_13 "Father alive"
label variable hv113_14 "Father alive"
label variable hv113_15 "Father alive"
label variable hv113_16 "Father alive"
label variable hv113_17 "Father alive"
label variable hv113_18 "Father alive"
label variable hv113_19 "Father alive"
label variable hv113_20 "Father alive"
label variable hv114_01 "Father's line number"
label variable hv114_02 "Father's line number"
label variable hv114_03 "Father's line number"
label variable hv114_04 "Father's line number"
label variable hv114_05 "Father's line number"
label variable hv114_06 "Father's line number"
label variable hv114_07 "Father's line number"
label variable hv114_08 "Father's line number"
label variable hv114_09 "Father's line number"
label variable hv114_10 "Father's line number"
label variable hv114_11 "Father's line number"
label variable hv114_12 "Father's line number"
label variable hv114_13 "Father's line number"
label variable hv114_14 "Father's line number"
label variable hv114_15 "Father's line number"
label variable hv114_16 "Father's line number"
label variable hv114_17 "Father's line number"
label variable hv114_18 "Father's line number"
label variable hv114_19 "Father's line number"
label variable hv114_20 "Father's line number"
label variable hv115_01 "Current marital status"
label variable hv115_02 "Current marital status"
label variable hv115_03 "Current marital status"
label variable hv115_04 "Current marital status"
label variable hv115_05 "Current marital status"
label variable hv115_06 "Current marital status"
label variable hv115_07 "Current marital status"
label variable hv115_08 "Current marital status"
label variable hv115_09 "Current marital status"
label variable hv115_10 "Current marital status"
label variable hv115_11 "Current marital status"
label variable hv115_12 "Current marital status"
label variable hv115_13 "Current marital status"
label variable hv115_14 "Current marital status"
label variable hv115_15 "Current marital status"
label variable hv115_16 "Current marital status"
label variable hv115_17 "Current marital status"
label variable hv115_18 "Current marital status"
label variable hv115_19 "Current marital status"
label variable hv115_20 "Current marital status"
label variable hv116_01 "Currently, formerly, never married"
label variable hv116_02 "Currently, formerly, never married"
label variable hv116_03 "Currently, formerly, never married"
label variable hv116_04 "Currently, formerly, never married"
label variable hv116_05 "Currently, formerly, never married"
label variable hv116_06 "Currently, formerly, never married"
label variable hv116_07 "Currently, formerly, never married"
label variable hv116_08 "Currently, formerly, never married"
label variable hv116_09 "Currently, formerly, never married"
label variable hv116_10 "Currently, formerly, never married"
label variable hv116_11 "Currently, formerly, never married"
label variable hv116_12 "Currently, formerly, never married"
label variable hv116_13 "Currently, formerly, never married"
label variable hv116_14 "Currently, formerly, never married"
label variable hv116_15 "Currently, formerly, never married"
label variable hv116_16 "Currently, formerly, never married"
label variable hv116_17 "Currently, formerly, never married"
label variable hv116_18 "Currently, formerly, never married"
label variable hv116_19 "Currently, formerly, never married"
label variable hv116_20 "Currently, formerly, never married"
label variable hv117_01 "Eligibility for female interview"
label variable hv117_02 "Eligibility for female interview"
label variable hv117_03 "Eligibility for female interview"
label variable hv117_04 "Eligibility for female interview"
label variable hv117_05 "Eligibility for female interview"
label variable hv117_06 "Eligibility for female interview"
label variable hv117_07 "Eligibility for female interview"
label variable hv117_08 "Eligibility for female interview"
label variable hv117_09 "Eligibility for female interview"
label variable hv117_10 "Eligibility for female interview"
label variable hv117_11 "Eligibility for female interview"
label variable hv117_12 "Eligibility for female interview"
label variable hv117_13 "Eligibility for female interview"
label variable hv117_14 "Eligibility for female interview"
label variable hv117_15 "Eligibility for female interview"
label variable hv117_16 "Eligibility for female interview"
label variable hv117_17 "Eligibility for female interview"
label variable hv117_18 "Eligibility for female interview"
label variable hv117_19 "Eligibility for female interview"
label variable hv117_20 "Eligibility for female interview"
label variable hv118_01 "Eligibility for male interview"
label variable hv118_02 "Eligibility for male interview"
label variable hv118_03 "Eligibility for male interview"
label variable hv118_04 "Eligibility for male interview"
label variable hv118_05 "Eligibility for male interview"
label variable hv118_06 "Eligibility for male interview"
label variable hv118_07 "Eligibility for male interview"
label variable hv118_08 "Eligibility for male interview"
label variable hv118_09 "Eligibility for male interview"
label variable hv118_10 "Eligibility for male interview"
label variable hv118_11 "Eligibility for male interview"
label variable hv118_12 "Eligibility for male interview"
label variable hv118_13 "Eligibility for male interview"
label variable hv118_14 "Eligibility for male interview"
label variable hv118_15 "Eligibility for male interview"
label variable hv118_16 "Eligibility for male interview"
label variable hv118_17 "Eligibility for male interview"
label variable hv118_18 "Eligibility for male interview"
label variable hv118_19 "Eligibility for male interview"
label variable hv118_20 "Eligibility for male interview"
label variable hv120_01 "Children eligibility for height/weight and hemoglobin"
label variable hv120_02 "Children eligibility for height/weight and hemoglobin"
label variable hv120_03 "Children eligibility for height/weight and hemoglobin"
label variable hv120_04 "Children eligibility for height/weight and hemoglobin"
label variable hv120_05 "Children eligibility for height/weight and hemoglobin"
label variable hv120_06 "Children eligibility for height/weight and hemoglobin"
label variable hv120_07 "Children eligibility for height/weight and hemoglobin"
label variable hv120_08 "Children eligibility for height/weight and hemoglobin"
label variable hv120_09 "Children eligibility for height/weight and hemoglobin"
label variable hv120_10 "Children eligibility for height/weight and hemoglobin"
label variable hv120_11 "Children eligibility for height/weight and hemoglobin"
label variable hv120_12 "Children eligibility for height/weight and hemoglobin"
label variable hv120_13 "Children eligibility for height/weight and hemoglobin"
label variable hv120_14 "Children eligibility for height/weight and hemoglobin"
label variable hv120_15 "Children eligibility for height/weight and hemoglobin"
label variable hv120_16 "Children eligibility for height/weight and hemoglobin"
label variable hv120_17 "Children eligibility for height/weight and hemoglobin"
label variable hv120_18 "Children eligibility for height/weight and hemoglobin"
label variable hv120_19 "Children eligibility for height/weight and hemoglobin"
label variable hv120_20 "Children eligibility for height/weight and hemoglobin"
label variable hv121_01 "Member attended school during current school year"
label variable hv121_02 "Member attended school during current school year"
label variable hv121_03 "Member attended school during current school year"
label variable hv121_04 "Member attended school during current school year"
label variable hv121_05 "Member attended school during current school year"
label variable hv121_06 "Member attended school during current school year"
label variable hv121_07 "Member attended school during current school year"
label variable hv121_08 "Member attended school during current school year"
label variable hv121_09 "Member attended school during current school year"
label variable hv121_10 "Member attended school during current school year"
label variable hv121_11 "Member attended school during current school year"
label variable hv121_12 "Member attended school during current school year"
label variable hv121_13 "Member attended school during current school year"
label variable hv121_14 "Member attended school during current school year"
label variable hv121_15 "Member attended school during current school year"
label variable hv121_16 "Member attended school during current school year"
label variable hv121_17 "Member attended school during current school year"
label variable hv121_18 "Member attended school during current school year"
label variable hv121_19 "Member attended school during current school year"
label variable hv121_20 "Member attended school during current school year"
label variable hv122_01 "Educational level during current school year"
label variable hv122_02 "Educational level during current school year"
label variable hv122_03 "Educational level during current school year"
label variable hv122_04 "Educational level during current school year"
label variable hv122_05 "Educational level during current school year"
label variable hv122_06 "Educational level during current school year"
label variable hv122_07 "Educational level during current school year"
label variable hv122_08 "Educational level during current school year"
label variable hv122_09 "Educational level during current school year"
label variable hv122_10 "Educational level during current school year"
label variable hv122_11 "Educational level during current school year"
label variable hv122_12 "Educational level during current school year"
label variable hv122_13 "Educational level during current school year"
label variable hv122_14 "Educational level during current school year"
label variable hv122_15 "Educational level during current school year"
label variable hv122_16 "Educational level during current school year"
label variable hv122_17 "Educational level during current school year"
label variable hv122_18 "Educational level during current school year"
label variable hv122_19 "Educational level during current school year"
label variable hv122_20 "Educational level during current school year"
label variable hv123_01 "Grade of education during current school year"
label variable hv123_02 "Grade of education during current school year"
label variable hv123_03 "Grade of education during current school year"
label variable hv123_04 "Grade of education during current school year"
label variable hv123_05 "Grade of education during current school year"
label variable hv123_06 "Grade of education during current school year"
label variable hv123_07 "Grade of education during current school year"
label variable hv123_08 "Grade of education during current school year"
label variable hv123_09 "Grade of education during current school year"
label variable hv123_10 "Grade of education during current school year"
label variable hv123_11 "Grade of education during current school year"
label variable hv123_12 "Grade of education during current school year"
label variable hv123_13 "Grade of education during current school year"
label variable hv123_14 "Grade of education during current school year"
label variable hv123_15 "Grade of education during current school year"
label variable hv123_16 "Grade of education during current school year"
label variable hv123_17 "Grade of education during current school year"
label variable hv123_18 "Grade of education during current school year"
label variable hv123_19 "Grade of education during current school year"
label variable hv123_20 "Grade of education during current school year"
label variable hv124_01 "Education in single years - current school year"
label variable hv124_02 "Education in single years - current school year"
label variable hv124_03 "Education in single years - current school year"
label variable hv124_04 "Education in single years - current school year"
label variable hv124_05 "Education in single years - current school year"
label variable hv124_06 "Education in single years - current school year"
label variable hv124_07 "Education in single years - current school year"
label variable hv124_08 "Education in single years - current school year"
label variable hv124_09 "Education in single years - current school year"
label variable hv124_10 "Education in single years - current school year"
label variable hv124_11 "Education in single years - current school year"
label variable hv124_12 "Education in single years - current school year"
label variable hv124_13 "Education in single years - current school year"
label variable hv124_14 "Education in single years - current school year"
label variable hv124_15 "Education in single years - current school year"
label variable hv124_16 "Education in single years - current school year"
label variable hv124_17 "Education in single years - current school year"
label variable hv124_18 "Education in single years - current school year"
label variable hv124_19 "Education in single years - current school year"
label variable hv124_20 "Education in single years - current school year"
label variable hv125_01 "NA - Member attended school during previous school year"
label variable hv125_02 "NA - Member attended school during previous school year"
label variable hv125_03 "NA - Member attended school during previous school year"
label variable hv125_04 "NA - Member attended school during previous school year"
label variable hv125_05 "NA - Member attended school during previous school year"
label variable hv125_06 "NA - Member attended school during previous school year"
label variable hv125_07 "NA - Member attended school during previous school year"
label variable hv125_08 "NA - Member attended school during previous school year"
label variable hv125_09 "NA - Member attended school during previous school year"
label variable hv125_10 "NA - Member attended school during previous school year"
label variable hv125_11 "NA - Member attended school during previous school year"
label variable hv125_12 "NA - Member attended school during previous school year"
label variable hv125_13 "NA - Member attended school during previous school year"
label variable hv125_14 "NA - Member attended school during previous school year"
label variable hv125_15 "NA - Member attended school during previous school year"
label variable hv125_16 "NA - Member attended school during previous school year"
label variable hv125_17 "NA - Member attended school during previous school year"
label variable hv125_18 "NA - Member attended school during previous school year"
label variable hv125_19 "NA - Member attended school during previous school year"
label variable hv125_20 "NA - Member attended school during previous school year"
label variable hv126_01 "NA - Educational level during previous school year"
label variable hv126_02 "NA - Educational level during previous school year"
label variable hv126_03 "NA - Educational level during previous school year"
label variable hv126_04 "NA - Educational level during previous school year"
label variable hv126_05 "NA - Educational level during previous school year"
label variable hv126_06 "NA - Educational level during previous school year"
label variable hv126_07 "NA - Educational level during previous school year"
label variable hv126_08 "NA - Educational level during previous school year"
label variable hv126_09 "NA - Educational level during previous school year"
label variable hv126_10 "NA - Educational level during previous school year"
label variable hv126_11 "NA - Educational level during previous school year"
label variable hv126_12 "NA - Educational level during previous school year"
label variable hv126_13 "NA - Educational level during previous school year"
label variable hv126_14 "NA - Educational level during previous school year"
label variable hv126_15 "NA - Educational level during previous school year"
label variable hv126_16 "NA - Educational level during previous school year"
label variable hv126_17 "NA - Educational level during previous school year"
label variable hv126_18 "NA - Educational level during previous school year"
label variable hv126_19 "NA - Educational level during previous school year"
label variable hv126_20 "NA - Educational level during previous school year"
label variable hv127_01 "NA - Grade of education during previous school year"
label variable hv127_02 "NA - Grade of education during previous school year"
label variable hv127_03 "NA - Grade of education during previous school year"
label variable hv127_04 "NA - Grade of education during previous school year"
label variable hv127_05 "NA - Grade of education during previous school year"
label variable hv127_06 "NA - Grade of education during previous school year"
label variable hv127_07 "NA - Grade of education during previous school year"
label variable hv127_08 "NA - Grade of education during previous school year"
label variable hv127_09 "NA - Grade of education during previous school year"
label variable hv127_10 "NA - Grade of education during previous school year"
label variable hv127_11 "NA - Grade of education during previous school year"
label variable hv127_12 "NA - Grade of education during previous school year"
label variable hv127_13 "NA - Grade of education during previous school year"
label variable hv127_14 "NA - Grade of education during previous school year"
label variable hv127_15 "NA - Grade of education during previous school year"
label variable hv127_16 "NA - Grade of education during previous school year"
label variable hv127_17 "NA - Grade of education during previous school year"
label variable hv127_18 "NA - Grade of education during previous school year"
label variable hv127_19 "NA - Grade of education during previous school year"
label variable hv127_20 "NA - Grade of education during previous school year"
label variable hv128_01 "NA - Education in single years - previous school year"
label variable hv128_02 "NA - Education in single years - previous school year"
label variable hv128_03 "NA - Education in single years - previous school year"
label variable hv128_04 "NA - Education in single years - previous school year"
label variable hv128_05 "NA - Education in single years - previous school year"
label variable hv128_06 "NA - Education in single years - previous school year"
label variable hv128_07 "NA - Education in single years - previous school year"
label variable hv128_08 "NA - Education in single years - previous school year"
label variable hv128_09 "NA - Education in single years - previous school year"
label variable hv128_10 "NA - Education in single years - previous school year"
label variable hv128_11 "NA - Education in single years - previous school year"
label variable hv128_12 "NA - Education in single years - previous school year"
label variable hv128_13 "NA - Education in single years - previous school year"
label variable hv128_14 "NA - Education in single years - previous school year"
label variable hv128_15 "NA - Education in single years - previous school year"
label variable hv128_16 "NA - Education in single years - previous school year"
label variable hv128_17 "NA - Education in single years - previous school year"
label variable hv128_18 "NA - Education in single years - previous school year"
label variable hv128_19 "NA - Education in single years - previous school year"
label variable hv128_20 "NA - Education in single years - previous school year"
label variable hv129_01 "NA - School attendance status"
label variable hv129_02 "NA - School attendance status"
label variable hv129_03 "NA - School attendance status"
label variable hv129_04 "NA - School attendance status"
label variable hv129_05 "NA - School attendance status"
label variable hv129_06 "NA - School attendance status"
label variable hv129_07 "NA - School attendance status"
label variable hv129_08 "NA - School attendance status"
label variable hv129_09 "NA - School attendance status"
label variable hv129_10 "NA - School attendance status"
label variable hv129_11 "NA - School attendance status"
label variable hv129_12 "NA - School attendance status"
label variable hv129_13 "NA - School attendance status"
label variable hv129_14 "NA - School attendance status"
label variable hv129_15 "NA - School attendance status"
label variable hv129_16 "NA - School attendance status"
label variable hv129_17 "NA - School attendance status"
label variable hv129_18 "NA - School attendance status"
label variable hv129_19 "NA - School attendance status"
label variable hv129_20 "NA - School attendance status"
label variable hv140_01 "Member has a birth certificate"
label variable hv140_02 "Member has a birth certificate"
label variable hv140_03 "Member has a birth certificate"
label variable hv140_04 "Member has a birth certificate"
label variable hv140_05 "Member has a birth certificate"
label variable hv140_06 "Member has a birth certificate"
label variable hv140_07 "Member has a birth certificate"
label variable hv140_08 "Member has a birth certificate"
label variable hv140_09 "Member has a birth certificate"
label variable hv140_10 "Member has a birth certificate"
label variable hv140_11 "Member has a birth certificate"
label variable hv140_12 "Member has a birth certificate"
label variable hv140_13 "Member has a birth certificate"
label variable hv140_14 "Member has a birth certificate"
label variable hv140_15 "Member has a birth certificate"
label variable hv140_16 "Member has a birth certificate"
label variable hv140_17 "Member has a birth certificate"
label variable hv140_18 "Member has a birth certificate"
label variable hv140_19 "Member has a birth certificate"
label variable hv140_20 "Member has a birth certificate"
label variable idxh4_01 "Index to Household Schedule"
label variable idxh4_02 "Index to Household Schedule"
label variable idxh4_03 "Index to Household Schedule"
label variable idxh4_04 "Index to Household Schedule"
label variable idxh4_05 "Index to Household Schedule"
label variable idxh4_06 "Index to Household Schedule"
label variable idxh4_07 "Index to Household Schedule"
label variable idxh4_08 "Index to Household Schedule"
label variable idxh4_09 "Index to Household Schedule"
label variable idxh4_10 "Index to Household Schedule"
label variable idxh4_11 "Index to Household Schedule"
label variable idxh4_12 "Index to Household Schedule"
label variable idxh4_13 "Index to Household Schedule"
label variable idxh4_14 "Index to Household Schedule"
label variable idxh4_15 "Index to Household Schedule"
label variable idxh4_16 "Index to Household Schedule"
label variable idxh4_17 "Index to Household Schedule"
label variable idxh4_18 "Index to Household Schedule"
label variable idxh4_19 "Index to Household Schedule"
label variable idxh4_20 "Index to Household Schedule"
label variable sh16_01  "Ever attended school"
label variable sh16_02  "Ever attended school"
label variable sh16_03  "Ever attended school"
label variable sh16_04  "Ever attended school"
label variable sh16_05  "Ever attended school"
label variable sh16_06  "Ever attended school"
label variable sh16_07  "Ever attended school"
label variable sh16_08  "Ever attended school"
label variable sh16_09  "Ever attended school"
label variable sh16_10  "Ever attended school"
label variable sh16_11  "Ever attended school"
label variable sh16_12  "Ever attended school"
label variable sh16_13  "Ever attended school"
label variable sh16_14  "Ever attended school"
label variable sh16_15  "Ever attended school"
label variable sh16_16  "Ever attended school"
label variable sh16_17  "Ever attended school"
label variable sh16_18  "Ever attended school"
label variable sh16_19  "Ever attended school"
label variable sh16_20  "Ever attended school"
label variable sh17a_01 "Level of education attended"
label variable sh17a_02 "Level of education attended"
label variable sh17a_03 "Level of education attended"
label variable sh17a_04 "Level of education attended"
label variable sh17a_05 "Level of education attended"
label variable sh17a_06 "Level of education attended"
label variable sh17a_07 "Level of education attended"
label variable sh17a_08 "Level of education attended"
label variable sh17a_09 "Level of education attended"
label variable sh17a_10 "Level of education attended"
label variable sh17a_11 "Level of education attended"
label variable sh17a_12 "Level of education attended"
label variable sh17a_13 "Level of education attended"
label variable sh17a_14 "Level of education attended"
label variable sh17a_15 "Level of education attended"
label variable sh17a_16 "Level of education attended"
label variable sh17a_17 "Level of education attended"
label variable sh17a_18 "Level of education attended"
label variable sh17a_19 "Level of education attended"
label variable sh17a_20 "Level of education attended"
label variable sh17b_01 "Highest grade completed"
label variable sh17b_02 "Highest grade completed"
label variable sh17b_03 "Highest grade completed"
label variable sh17b_04 "Highest grade completed"
label variable sh17b_05 "Highest grade completed"
label variable sh17b_06 "Highest grade completed"
label variable sh17b_07 "Highest grade completed"
label variable sh17b_08 "Highest grade completed"
label variable sh17b_09 "Highest grade completed"
label variable sh17b_10 "Highest grade completed"
label variable sh17b_11 "Highest grade completed"
label variable sh17b_12 "Highest grade completed"
label variable sh17b_13 "Highest grade completed"
label variable sh17b_14 "Highest grade completed"
label variable sh17b_15 "Highest grade completed"
label variable sh17b_16 "Highest grade completed"
label variable sh17b_17 "Highest grade completed"
label variable sh17b_18 "Highest grade completed"
label variable sh17b_19 "Highest grade completed"
label variable sh17b_20 "Highest grade completed"
label variable sh18_01  "Attend school current year"
label variable sh18_02  "Attend school current year"
label variable sh18_03  "Attend school current year"
label variable sh18_04  "Attend school current year"
label variable sh18_05  "Attend school current year"
label variable sh18_06  "Attend school current year"
label variable sh18_07  "Attend school current year"
label variable sh18_08  "Attend school current year"
label variable sh18_09  "Attend school current year"
label variable sh18_10  "Attend school current year"
label variable sh18_11  "Attend school current year"
label variable sh18_12  "Attend school current year"
label variable sh18_13  "Attend school current year"
label variable sh18_14  "Attend school current year"
label variable sh18_15  "Attend school current year"
label variable sh18_16  "Attend school current year"
label variable sh18_17  "Attend school current year"
label variable sh18_18  "Attend school current year"
label variable sh18_19  "Attend school current year"
label variable sh18_20  "Attend school current year"
label variable sh19a_01 "Level of education attending"
label variable sh19a_02 "Level of education attending"
label variable sh19a_03 "Level of education attending"
label variable sh19a_04 "Level of education attending"
label variable sh19a_05 "Level of education attending"
label variable sh19a_06 "Level of education attending"
label variable sh19a_07 "Level of education attending"
label variable sh19a_08 "Level of education attending"
label variable sh19a_09 "Level of education attending"
label variable sh19a_10 "Level of education attending"
label variable sh19a_11 "Level of education attending"
label variable sh19a_12 "Level of education attending"
label variable sh19a_13 "Level of education attending"
label variable sh19a_14 "Level of education attending"
label variable sh19a_15 "Level of education attending"
label variable sh19a_16 "Level of education attending"
label variable sh19a_17 "Level of education attending"
label variable sh19a_18 "Level of education attending"
label variable sh19a_19 "Level of education attending"
label variable sh19a_20 "Level of education attending"
label variable sh19b_01 "Grade attending"
label variable sh19b_02 "Grade attending"
label variable sh19b_03 "Grade attending"
label variable sh19b_04 "Grade attending"
label variable sh19b_05 "Grade attending"
label variable sh19b_06 "Grade attending"
label variable sh19b_07 "Grade attending"
label variable sh19b_08 "Grade attending"
label variable sh19b_09 "Grade attending"
label variable sh19b_10 "Grade attending"
label variable sh19b_11 "Grade attending"
label variable sh19b_12 "Grade attending"
label variable sh19b_13 "Grade attending"
label variable sh19b_14 "Grade attending"
label variable sh19b_15 "Grade attending"
label variable sh19b_16 "Grade attending"
label variable sh19b_17 "Grade attending"
label variable sh19b_18 "Grade attending"
label variable sh19b_19 "Grade attending"
label variable sh19b_20 "Grade attending"
label variable sm07i_01 "Age corrected from individual questionnaire"
label variable sm07i_02 "Age corrected from individual questionnaire"
label variable sm07i_03 "Age corrected from individual questionnaire"
label variable sm07i_04 "Age corrected from individual questionnaire"
label variable sm07i_05 "Age corrected from individual questionnaire"
label variable sm07i_06 "Age corrected from individual questionnaire"
label variable sm07i_07 "Age corrected from individual questionnaire"
label variable sm07i_08 "Age corrected from individual questionnaire"
label variable sm07i_09 "Age corrected from individual questionnaire"
label variable sm07i_10 "Age corrected from individual questionnaire"
label variable sm07i_11 "Age corrected from individual questionnaire"
label variable sm07i_12 "Age corrected from individual questionnaire"
label variable sm07i_13 "Age corrected from individual questionnaire"
label variable sm07i_14 "Age corrected from individual questionnaire"
label variable sm07i_15 "Age corrected from individual questionnaire"
label variable sm07i_16 "Age corrected from individual questionnaire"
label variable sm07i_17 "Age corrected from individual questionnaire"
label variable sm07i_18 "Age corrected from individual questionnaire"
label variable sm07i_19 "Age corrected from individual questionnaire"
label variable sm07i_20 "Age corrected from individual questionnaire"
label variable sm07f_01 "Flag for age correction"
label variable sm07f_02 "Flag for age correction"
label variable sm07f_03 "Flag for age correction"
label variable sm07f_04 "Flag for age correction"
label variable sm07f_05 "Flag for age correction"
label variable sm07f_06 "Flag for age correction"
label variable sm07f_07 "Flag for age correction"
label variable sm07f_08 "Flag for age correction"
label variable sm07f_09 "Flag for age correction"
label variable sm07f_10 "Flag for age correction"
label variable sm07f_11 "Flag for age correction"
label variable sm07f_12 "Flag for age correction"
label variable sm07f_13 "Flag for age correction"
label variable sm07f_14 "Flag for age correction"
label variable sm07f_15 "Flag for age correction"
label variable sm07f_16 "Flag for age correction"
label variable sm07f_17 "Flag for age correction"
label variable sm07f_18 "Flag for age correction"
label variable sm07f_19 "Flag for age correction"
label variable sm07f_20 "Flag for age correction"
label variable smpreg_01 "Pregnancy status from individual questionnaire"
label variable smpreg_02 "Pregnancy status from individual questionnaire"
label variable smpreg_03 "Pregnancy status from individual questionnaire"
label variable smpreg_04 "Pregnancy status from individual questionnaire"
label variable smpreg_05 "Pregnancy status from individual questionnaire"
label variable smpreg_06 "Pregnancy status from individual questionnaire"
label variable smpreg_07 "Pregnancy status from individual questionnaire"
label variable smpreg_08 "Pregnancy status from individual questionnaire"
label variable smpreg_09 "Pregnancy status from individual questionnaire"
label variable smpreg_10 "Pregnancy status from individual questionnaire"
label variable smpreg_11 "Pregnancy status from individual questionnaire"
label variable smpreg_12 "Pregnancy status from individual questionnaire"
label variable smpreg_13 "Pregnancy status from individual questionnaire"
label variable smpreg_14 "Pregnancy status from individual questionnaire"
label variable smpreg_15 "Pregnancy status from individual questionnaire"
label variable smpreg_16 "Pregnancy status from individual questionnaire"
label variable smpreg_17 "Pregnancy status from individual questionnaire"
label variable smpreg_18 "Pregnancy status from individual questionnaire"
label variable smpreg_19 "Pregnancy status from individual questionnaire"
label variable smpreg_20 "Pregnancy status from individual questionnaire"
label variable swmos_01 "Months of pregnancy"
label variable swmos_02 "Months of pregnancy"
label variable swmos_03 "Months of pregnancy"
label variable swmos_04 "Months of pregnancy"
label variable swmos_05 "Months of pregnancy"
label variable swmos_06 "Months of pregnancy"
label variable swmos_07 "Months of pregnancy"
label variable swmos_08 "Months of pregnancy"
label variable swmos_09 "Months of pregnancy"
label variable swmos_10 "Months of pregnancy"
label variable swmos_11 "Months of pregnancy"
label variable swmos_12 "Months of pregnancy"
label variable swmos_13 "Months of pregnancy"
label variable swmos_14 "Months of pregnancy"
label variable swmos_15 "Months of pregnancy"
label variable swmos_16 "Months of pregnancy"
label variable swmos_17 "Months of pregnancy"
label variable swmos_18 "Months of pregnancy"
label variable swmos_19 "Months of pregnancy"
label variable swmos_20 "Months of pregnancy"
label variable sb103d_01 "Day of birth (Ethiopia calendar)"
label variable sb103d_02 "Day of birth (Ethiopia calendar)"
label variable sb103d_03 "Day of birth (Ethiopia calendar)"
label variable sb103d_04 "Day of birth (Ethiopia calendar)"
label variable sb103d_05 "Day of birth (Ethiopia calendar)"
label variable sb103d_06 "Day of birth (Ethiopia calendar)"
label variable sb103d_07 "Day of birth (Ethiopia calendar)"
label variable sb103d_08 "Day of birth (Ethiopia calendar)"
label variable sb103d_09 "Day of birth (Ethiopia calendar)"
label variable sb103d_10 "Day of birth (Ethiopia calendar)"
label variable sb103d_11 "Day of birth (Ethiopia calendar)"
label variable sb103d_12 "Day of birth (Ethiopia calendar)"
label variable sb103d_13 "Day of birth (Ethiopia calendar)"
label variable sb103d_14 "Day of birth (Ethiopia calendar)"
label variable sb103d_15 "Day of birth (Ethiopia calendar)"
label variable sb103d_16 "Day of birth (Ethiopia calendar)"
label variable sb103d_17 "Day of birth (Ethiopia calendar)"
label variable sb103d_18 "Day of birth (Ethiopia calendar)"
label variable sb103d_19 "Day of birth (Ethiopia calendar)"
label variable sb103d_20 "Day of birth (Ethiopia calendar)"
label variable sb103m_01 "Month of birth (Ethiopia calendar)"
label variable sb103m_02 "Month of birth (Ethiopia calendar)"
label variable sb103m_03 "Month of birth (Ethiopia calendar)"
label variable sb103m_04 "Month of birth (Ethiopia calendar)"
label variable sb103m_05 "Month of birth (Ethiopia calendar)"
label variable sb103m_06 "Month of birth (Ethiopia calendar)"
label variable sb103m_07 "Month of birth (Ethiopia calendar)"
label variable sb103m_08 "Month of birth (Ethiopia calendar)"
label variable sb103m_09 "Month of birth (Ethiopia calendar)"
label variable sb103m_10 "Month of birth (Ethiopia calendar)"
label variable sb103m_11 "Month of birth (Ethiopia calendar)"
label variable sb103m_12 "Month of birth (Ethiopia calendar)"
label variable sb103m_13 "Month of birth (Ethiopia calendar)"
label variable sb103m_14 "Month of birth (Ethiopia calendar)"
label variable sb103m_15 "Month of birth (Ethiopia calendar)"
label variable sb103m_16 "Month of birth (Ethiopia calendar)"
label variable sb103m_17 "Month of birth (Ethiopia calendar)"
label variable sb103m_18 "Month of birth (Ethiopia calendar)"
label variable sb103m_19 "Month of birth (Ethiopia calendar)"
label variable sb103m_20 "Month of birth (Ethiopia calendar)"
label variable ha0_1    "Index to Household Schedule"
label variable ha0_2    "Index to Household Schedule"
label variable ha0_3    "Index to Household Schedule"
label variable ha0_4    "Index to Household Schedule"
label variable ha0_5    "Index to Household Schedule"
label variable ha0_6    "Index to Household Schedule"
label variable ha0_7    "Index to Household Schedule"
label variable ha0_8    "Index to Household Schedule"
label variable ha0_9    "Index to Household Schedule"
label variable ha1_1    "Woman's age in years"
label variable ha1_2    "Woman's age in years"
label variable ha1_3    "Woman's age in years"
label variable ha1_4    "Woman's age in years"
label variable ha1_5    "Woman's age in years"
label variable ha1_6    "Woman's age in years"
label variable ha1_7    "Woman's age in years"
label variable ha1_8    "Woman's age in years"
label variable ha1_9    "Woman's age in years"
label variable ha2_1    "Woman's weight in kilograms (1 decimal)"
label variable ha2_2    "Woman's weight in kilograms (1 decimal)"
label variable ha2_3    "Woman's weight in kilograms (1 decimal)"
label variable ha2_4    "Woman's weight in kilograms (1 decimal)"
label variable ha2_5    "Woman's weight in kilograms (1 decimal)"
label variable ha2_6    "Woman's weight in kilograms (1 decimal)"
label variable ha2_7    "Woman's weight in kilograms (1 decimal)"
label variable ha2_8    "Woman's weight in kilograms (1 decimal)"
label variable ha2_9    "Woman's weight in kilograms (1 decimal)"
label variable ha3_1    "Woman's height in centimeters (1 decimal)"
label variable ha3_2    "Woman's height in centimeters (1 decimal)"
label variable ha3_3    "Woman's height in centimeters (1 decimal)"
label variable ha3_4    "Woman's height in centimeters (1 decimal)"
label variable ha3_5    "Woman's height in centimeters (1 decimal)"
label variable ha3_6    "Woman's height in centimeters (1 decimal)"
label variable ha3_7    "Woman's height in centimeters (1 decimal)"
label variable ha3_8    "Woman's height in centimeters (1 decimal)"
label variable ha3_9    "Woman's height in centimeters (1 decimal)"
label variable ha4_1    "Height/Age percentile"
label variable ha4_2    "Height/Age percentile"
label variable ha4_3    "Height/Age percentile"
label variable ha4_4    "Height/Age percentile"
label variable ha4_5    "Height/Age percentile"
label variable ha4_6    "Height/Age percentile"
label variable ha4_7    "Height/Age percentile"
label variable ha4_8    "Height/Age percentile"
label variable ha4_9    "Height/Age percentile"
label variable ha5_1    "Height/Age standard deviation"
label variable ha5_2    "Height/Age standard deviation"
label variable ha5_3    "Height/Age standard deviation"
label variable ha5_4    "Height/Age standard deviation"
label variable ha5_5    "Height/Age standard deviation"
label variable ha5_6    "Height/Age standard deviation"
label variable ha5_7    "Height/Age standard deviation"
label variable ha5_8    "Height/Age standard deviation"
label variable ha5_9    "Height/Age standard deviation"
label variable ha6_1    "Height/Age percent ref. median"
label variable ha6_2    "Height/Age percent ref. median"
label variable ha6_3    "Height/Age percent ref. median"
label variable ha6_4    "Height/Age percent ref. median"
label variable ha6_5    "Height/Age percent ref. median"
label variable ha6_6    "Height/Age percent ref. median"
label variable ha6_7    "Height/Age percent ref. median"
label variable ha6_8    "Height/Age percent ref. median"
label variable ha6_9    "Height/Age percent ref. median"
label variable ha11_1   "Weight/Height standard deviation (DHS)"
label variable ha11_2   "Weight/Height standard deviation (DHS)"
label variable ha11_3   "Weight/Height standard deviation (DHS)"
label variable ha11_4   "Weight/Height standard deviation (DHS)"
label variable ha11_5   "Weight/Height standard deviation (DHS)"
label variable ha11_6   "Weight/Height standard deviation (DHS)"
label variable ha11_7   "Weight/Height standard deviation (DHS)"
label variable ha11_8   "Weight/Height standard deviation (DHS)"
label variable ha11_9   "Weight/Height standard deviation (DHS)"
label variable ha12_1   "Weight/Height percent ref. median (DHS)"
label variable ha12_2   "Weight/Height percent ref. median (DHS)"
label variable ha12_3   "Weight/Height percent ref. median (DHS)"
label variable ha12_4   "Weight/Height percent ref. median (DHS)"
label variable ha12_5   "Weight/Height percent ref. median (DHS)"
label variable ha12_6   "Weight/Height percent ref. median (DHS)"
label variable ha12_7   "Weight/Height percent ref. median (DHS)"
label variable ha12_8   "Weight/Height percent ref. median (DHS)"
label variable ha12_9   "Weight/Height percent ref. median (DHS)"
label variable ha12a_1  "Weight/Height percent ref. median (Fog)"
label variable ha12a_2  "Weight/Height percent ref. median (Fog)"
label variable ha12a_3  "Weight/Height percent ref. median (Fog)"
label variable ha12a_4  "Weight/Height percent ref. median (Fog)"
label variable ha12a_5  "Weight/Height percent ref. median (Fog)"
label variable ha12a_6  "Weight/Height percent ref. median (Fog)"
label variable ha12a_7  "Weight/Height percent ref. median (Fog)"
label variable ha12a_8  "Weight/Height percent ref. median (Fog)"
label variable ha12a_9  "Weight/Height percent ref. median (Fog)"
label variable ha12b_1  "Weight/Height percent ref. median (WHO)"
label variable ha12b_2  "Weight/Height percent ref. median (WHO)"
label variable ha12b_3  "Weight/Height percent ref. median (WHO)"
label variable ha12b_4  "Weight/Height percent ref. median (WHO)"
label variable ha12b_5  "Weight/Height percent ref. median (WHO)"
label variable ha12b_6  "Weight/Height percent ref. median (WHO)"
label variable ha12b_7  "Weight/Height percent ref. median (WHO)"
label variable ha12b_8  "Weight/Height percent ref. median (WHO)"
label variable ha12b_9  "Weight/Height percent ref. median (WHO)"
label variable ha13_1   "Result of measurement - height/weight"
label variable ha13_2   "Result of measurement - height/weight"
label variable ha13_3   "Result of measurement - height/weight"
label variable ha13_4   "Result of measurement - height/weight"
label variable ha13_5   "Result of measurement - height/weight"
label variable ha13_6   "Result of measurement - height/weight"
label variable ha13_7   "Result of measurement - height/weight"
label variable ha13_8   "Result of measurement - height/weight"
label variable ha13_9   "Result of measurement - height/weight"
label variable ha21_1   "Fieldworker measurer code"
label variable ha21_2   "Fieldworker measurer code"
label variable ha21_3   "Fieldworker measurer code"
label variable ha21_4   "Fieldworker measurer code"
label variable ha21_5   "Fieldworker measurer code"
label variable ha21_6   "Fieldworker measurer code"
label variable ha21_7   "Fieldworker measurer code"
label variable ha21_8   "Fieldworker measurer code"
label variable ha21_9   "Fieldworker measurer code"
label variable ha32_1   "Date of birth (CMC)"
label variable ha32_2   "Date of birth (CMC)"
label variable ha32_3   "Date of birth (CMC)"
label variable ha32_4   "Date of birth (CMC)"
label variable ha32_5   "Date of birth (CMC)"
label variable ha32_6   "Date of birth (CMC)"
label variable ha32_7   "Date of birth (CMC)"
label variable ha32_8   "Date of birth (CMC)"
label variable ha32_9   "Date of birth (CMC)"
label variable ha33_1   "Completeness of HA32 information"
label variable ha33_2   "Completeness of HA32 information"
label variable ha33_3   "Completeness of HA32 information"
label variable ha33_4   "Completeness of HA32 information"
label variable ha33_5   "Completeness of HA32 information"
label variable ha33_6   "Completeness of HA32 information"
label variable ha33_7   "Completeness of HA32 information"
label variable ha33_8   "Completeness of HA32 information"
label variable ha33_9   "Completeness of HA32 information"
label variable ha35_1   "Smoking (cigarettes in last 24 hours)"
label variable ha35_2   "Smoking (cigarettes in last 24 hours)"
label variable ha35_3   "Smoking (cigarettes in last 24 hours)"
label variable ha35_4   "Smoking (cigarettes in last 24 hours)"
label variable ha35_5   "Smoking (cigarettes in last 24 hours)"
label variable ha35_6   "Smoking (cigarettes in last 24 hours)"
label variable ha35_7   "Smoking (cigarettes in last 24 hours)"
label variable ha35_8   "Smoking (cigarettes in last 24 hours)"
label variable ha35_9   "Smoking (cigarettes in last 24 hours)"
label variable ha40_1   "Body Mass Index"
label variable ha40_2   "Body Mass Index"
label variable ha40_3   "Body Mass Index"
label variable ha40_4   "Body Mass Index"
label variable ha40_5   "Body Mass Index"
label variable ha40_6   "Body Mass Index"
label variable ha40_7   "Body Mass Index"
label variable ha40_8   "Body Mass Index"
label variable ha40_9   "Body Mass Index"
label variable ha41_1   "Rohrer's index"
label variable ha41_2   "Rohrer's index"
label variable ha41_3   "Rohrer's index"
label variable ha41_4   "Rohrer's index"
label variable ha41_5   "Rohrer's index"
label variable ha41_6   "Rohrer's index"
label variable ha41_7   "Rohrer's index"
label variable ha41_8   "Rohrer's index"
label variable ha41_9   "Rohrer's index"
label variable ha50_1   "Under age 18"
label variable ha50_2   "Under age 18"
label variable ha50_3   "Under age 18"
label variable ha50_4   "Under age 18"
label variable ha50_5   "Under age 18"
label variable ha50_6   "Under age 18"
label variable ha50_7   "Under age 18"
label variable ha50_8   "Under age 18"
label variable ha50_9   "Under age 18"
label variable ha51_1   "Line number of parent/caretaker"
label variable ha51_2   "Line number of parent/caretaker"
label variable ha51_3   "Line number of parent/caretaker"
label variable ha51_4   "Line number of parent/caretaker"
label variable ha51_5   "Line number of parent/caretaker"
label variable ha51_6   "Line number of parent/caretaker"
label variable ha51_7   "Line number of parent/caretaker"
label variable ha51_8   "Line number of parent/caretaker"
label variable ha51_9   "Line number of parent/caretaker"
label variable ha52_1   "Read consent statement - hemoglobin"
label variable ha52_2   "Read consent statement - hemoglobin"
label variable ha52_3   "Read consent statement - hemoglobin"
label variable ha52_4   "Read consent statement - hemoglobin"
label variable ha52_5   "Read consent statement - hemoglobin"
label variable ha52_6   "Read consent statement - hemoglobin"
label variable ha52_7   "Read consent statement - hemoglobin"
label variable ha52_8   "Read consent statement - hemoglobin"
label variable ha52_9   "Read consent statement - hemoglobin"
label variable ha53_1   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_2   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_3   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_4   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_5   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_6   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_7   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_8   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha53_9   "Hemoglobin level (g/dl - 1 decimal)"
label variable ha54_1   "Currently pregnant"
label variable ha54_2   "Currently pregnant"
label variable ha54_3   "Currently pregnant"
label variable ha54_4   "Currently pregnant"
label variable ha54_5   "Currently pregnant"
label variable ha54_6   "Currently pregnant"
label variable ha54_7   "Currently pregnant"
label variable ha54_8   "Currently pregnant"
label variable ha54_9   "Currently pregnant"
label variable ha55_1   "Result of measurement - hemoglobin"
label variable ha55_2   "Result of measurement - hemoglobin"
label variable ha55_3   "Result of measurement - hemoglobin"
label variable ha55_4   "Result of measurement - hemoglobin"
label variable ha55_5   "Result of measurement - hemoglobin"
label variable ha55_6   "Result of measurement - hemoglobin"
label variable ha55_7   "Result of measurement - hemoglobin"
label variable ha55_8   "Result of measurement - hemoglobin"
label variable ha55_9   "Result of measurement - hemoglobin"
label variable ha56_1   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_2   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_3   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_4   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_5   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_6   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_7   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_8   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha56_9   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable ha57_1   "Anemia level"
label variable ha57_2   "Anemia level"
label variable ha57_3   "Anemia level"
label variable ha57_4   "Anemia level"
label variable ha57_5   "Anemia level"
label variable ha57_6   "Anemia level"
label variable ha57_7   "Anemia level"
label variable ha57_8   "Anemia level"
label variable ha57_9   "Anemia level"
label variable ha58_1   "NA - Agrees to referral - anemia"
label variable ha58_2   "NA - Agrees to referral - anemia"
label variable ha58_3   "NA - Agrees to referral - anemia"
label variable ha58_4   "NA - Agrees to referral - anemia"
label variable ha58_5   "NA - Agrees to referral - anemia"
label variable ha58_6   "NA - Agrees to referral - anemia"
label variable ha58_7   "NA - Agrees to referral - anemia"
label variable ha58_8   "NA - Agrees to referral - anemia"
label variable ha58_9   "NA - Agrees to referral - anemia"
label variable ha60_1   "Marital status"
label variable ha60_2   "Marital status"
label variable ha60_3   "Marital status"
label variable ha60_4   "Marital status"
label variable ha60_5   "Marital status"
label variable ha60_6   "Marital status"
label variable ha60_7   "Marital status"
label variable ha60_8   "Marital status"
label variable ha60_9   "Marital status"
label variable ha61_1   "Read consent statement - HIV"
label variable ha61_2   "Read consent statement - HIV"
label variable ha61_3   "Read consent statement - HIV"
label variable ha61_4   "Read consent statement - HIV"
label variable ha61_5   "Read consent statement - HIV"
label variable ha61_6   "Read consent statement - HIV"
label variable ha61_7   "Read consent statement - HIV"
label variable ha61_8   "Read consent statement - HIV"
label variable ha61_9   "Read consent statement - HIV"
label variable ha62_1   "Bar code for HIV blood sample"
label variable ha62_2   "Bar code for HIV blood sample"
label variable ha62_3   "Bar code for HIV blood sample"
label variable ha62_4   "Bar code for HIV blood sample"
label variable ha62_5   "Bar code for HIV blood sample"
label variable ha62_6   "Bar code for HIV blood sample"
label variable ha62_7   "Bar code for HIV blood sample"
label variable ha62_8   "Bar code for HIV blood sample"
label variable ha62_9   "Bar code for HIV blood sample"
label variable ha63_1   "Result of measurement - HIV"
label variable ha63_2   "Result of measurement - HIV"
label variable ha63_3   "Result of measurement - HIV"
label variable ha63_4   "Result of measurement - HIV"
label variable ha63_5   "Result of measurement - HIV"
label variable ha63_6   "Result of measurement - HIV"
label variable ha63_7   "Result of measurement - HIV"
label variable ha63_8   "Result of measurement - HIV"
label variable ha63_9   "Result of measurement - HIV"
label variable ha64_1   "Consent for additional tests"
label variable ha64_2   "Consent for additional tests"
label variable ha64_3   "Consent for additional tests"
label variable ha64_4   "Consent for additional tests"
label variable ha64_5   "Consent for additional tests"
label variable ha64_6   "Consent for additional tests"
label variable ha64_7   "Consent for additional tests"
label variable ha64_8   "Consent for additional tests"
label variable ha64_9   "Consent for additional tests"
label variable ha65_1   "Result of woman's individual interview"
label variable ha65_2   "Result of woman's individual interview"
label variable ha65_3   "Result of woman's individual interview"
label variable ha65_4   "Result of woman's individual interview"
label variable ha65_5   "Result of woman's individual interview"
label variable ha65_6   "Result of woman's individual interview"
label variable ha65_7   "Result of woman's individual interview"
label variable ha65_8   "Result of woman's individual interview"
label variable ha65_9   "Result of woman's individual interview"
label variable ha66_1   "Woman's highest educational level"
label variable ha66_2   "Woman's highest educational level"
label variable ha66_3   "Woman's highest educational level"
label variable ha66_4   "Woman's highest educational level"
label variable ha66_5   "Woman's highest educational level"
label variable ha66_6   "Woman's highest educational level"
label variable ha66_7   "Woman's highest educational level"
label variable ha66_8   "Woman's highest educational level"
label variable ha66_9   "Woman's highest educational level"
label variable ha67_1   "Woman's highest year of education"
label variable ha67_2   "Woman's highest year of education"
label variable ha67_3   "Woman's highest year of education"
label variable ha67_4   "Woman's highest year of education"
label variable ha67_5   "Woman's highest year of education"
label variable ha67_6   "Woman's highest year of education"
label variable ha67_7   "Woman's highest year of education"
label variable ha67_8   "Woman's highest year of education"
label variable ha67_9   "Woman's highest year of education"
label variable ha68_1   "Woman's highest educational level (for preliminary and final report)"
label variable ha68_2   "Woman's highest educational level (for preliminary and final report)"
label variable ha68_3   "Woman's highest educational level (for preliminary and final report)"
label variable ha68_4   "Woman's highest educational level (for preliminary and final report)"
label variable ha68_5   "Woman's highest educational level (for preliminary and final report)"
label variable ha68_6   "Woman's highest educational level (for preliminary and final report)"
label variable ha68_7   "Woman's highest educational level (for preliminary and final report)"
label variable ha68_8   "Woman's highest educational level (for preliminary and final report)"
label variable ha68_9   "Woman's highest educational level (for preliminary and final report)"
label variable ha69_1   "HIV weight (6 decimals)"
label variable ha69_2   "HIV weight (6 decimals)"
label variable ha69_3   "HIV weight (6 decimals)"
label variable ha69_4   "HIV weight (6 decimals)"
label variable ha69_5   "HIV weight (6 decimals)"
label variable ha69_6   "HIV weight (6 decimals)"
label variable ha69_7   "HIV weight (6 decimals)"
label variable ha69_8   "HIV weight (6 decimals)"
label variable ha69_9   "HIV weight (6 decimals)"
label variable ha70_1   "Interviewer that took blood for HIV testing"
label variable ha70_2   "Interviewer that took blood for HIV testing"
label variable ha70_3   "Interviewer that took blood for HIV testing"
label variable ha70_4   "Interviewer that took blood for HIV testing"
label variable ha70_5   "Interviewer that took blood for HIV testing"
label variable ha70_6   "Interviewer that took blood for HIV testing"
label variable ha70_7   "Interviewer that took blood for HIV testing"
label variable ha70_8   "Interviewer that took blood for HIV testing"
label variable ha70_9   "Interviewer that took blood for HIV testing"
label variable hc0_1    "Index to Household Schedule"
label variable hc0_2    "Index to Household Schedule"
label variable hc0_3    "Index to Household Schedule"
label variable hc0_4    "Index to Household Schedule"
label variable hc0_5    "Index to Household Schedule"
label variable hc0_6    "Index to Household Schedule"
label variable hc1_1    "Child's age in months"
label variable hc1_2    "Child's age in months"
label variable hc1_3    "Child's age in months"
label variable hc1_4    "Child's age in months"
label variable hc1_5    "Child's age in months"
label variable hc1_6    "Child's age in months"
label variable hc1a_1   "Child's age in days"
label variable hc1a_2   "Child's age in days"
label variable hc1a_3   "Child's age in days"
label variable hc1a_4   "Child's age in days"
label variable hc1a_5   "Child's age in days"
label variable hc1a_6   "Child's age in days"
label variable hc2_1    "Child's weight in kilograms (1 decimal)"
label variable hc2_2    "Child's weight in kilograms (1 decimal)"
label variable hc2_3    "Child's weight in kilograms (1 decimal)"
label variable hc2_4    "Child's weight in kilograms (1 decimal)"
label variable hc2_5    "Child's weight in kilograms (1 decimal)"
label variable hc2_6    "Child's weight in kilograms (1 decimal)"
label variable hc3_1    "Child's height in centimeters (1 decimal)"
label variable hc3_2    "Child's height in centimeters (1 decimal)"
label variable hc3_3    "Child's height in centimeters (1 decimal)"
label variable hc3_4    "Child's height in centimeters (1 decimal)"
label variable hc3_5    "Child's height in centimeters (1 decimal)"
label variable hc3_6    "Child's height in centimeters (1 decimal)"
label variable hc4_1    "Height/Age percentile"
label variable hc4_2    "Height/Age percentile"
label variable hc4_3    "Height/Age percentile"
label variable hc4_4    "Height/Age percentile"
label variable hc4_5    "Height/Age percentile"
label variable hc4_6    "Height/Age percentile"
label variable hc5_1    "Height/Age standard deviation"
label variable hc5_2    "Height/Age standard deviation"
label variable hc5_3    "Height/Age standard deviation"
label variable hc5_4    "Height/Age standard deviation"
label variable hc5_5    "Height/Age standard deviation"
label variable hc5_6    "Height/Age standard deviation"
label variable hc6_1    "Height/Age percent of ref. median"
label variable hc6_2    "Height/Age percent of ref. median"
label variable hc6_3    "Height/Age percent of ref. median"
label variable hc6_4    "Height/Age percent of ref. median"
label variable hc6_5    "Height/Age percent of ref. median"
label variable hc6_6    "Height/Age percent of ref. median"
label variable hc7_1    "Weight/Age percentile"
label variable hc7_2    "Weight/Age percentile"
label variable hc7_3    "Weight/Age percentile"
label variable hc7_4    "Weight/Age percentile"
label variable hc7_5    "Weight/Age percentile"
label variable hc7_6    "Weight/Age percentile"
label variable hc8_1    "Weight/Age standard deviation"
label variable hc8_2    "Weight/Age standard deviation"
label variable hc8_3    "Weight/Age standard deviation"
label variable hc8_4    "Weight/Age standard deviation"
label variable hc8_5    "Weight/Age standard deviation"
label variable hc8_6    "Weight/Age standard deviation"
label variable hc9_1    "Weight/Age percent of ref. median"
label variable hc9_2    "Weight/Age percent of ref. median"
label variable hc9_3    "Weight/Age percent of ref. median"
label variable hc9_4    "Weight/Age percent of ref. median"
label variable hc9_5    "Weight/Age percent of ref. median"
label variable hc9_6    "Weight/Age percent of ref. median"
label variable hc10_1   "Weight/Height percentile"
label variable hc10_2   "Weight/Height percentile"
label variable hc10_3   "Weight/Height percentile"
label variable hc10_4   "Weight/Height percentile"
label variable hc10_5   "Weight/Height percentile"
label variable hc10_6   "Weight/Height percentile"
label variable hc11_1   "Weight/Height standard deviation"
label variable hc11_2   "Weight/Height standard deviation"
label variable hc11_3   "Weight/Height standard deviation"
label variable hc11_4   "Weight/Height standard deviation"
label variable hc11_5   "Weight/Height standard deviation"
label variable hc11_6   "Weight/Height standard deviation"
label variable hc12_1   "Weight/Height percent of ref. median"
label variable hc12_2   "Weight/Height percent of ref. median"
label variable hc12_3   "Weight/Height percent of ref. median"
label variable hc12_4   "Weight/Height percent of ref. median"
label variable hc12_5   "Weight/Height percent of ref. median"
label variable hc12_6   "Weight/Height percent of ref. median"
label variable hc13_1   "Result of measurement - height/weight"
label variable hc13_2   "Result of measurement - height/weight"
label variable hc13_3   "Result of measurement - height/weight"
label variable hc13_4   "Result of measurement - height/weight"
label variable hc13_5   "Result of measurement - height/weight"
label variable hc13_6   "Result of measurement - height/weight"
label variable hc15_1   "Height: lying or standing"
label variable hc15_2   "Height: lying or standing"
label variable hc15_3   "Height: lying or standing"
label variable hc15_4   "Height: lying or standing"
label variable hc15_5   "Height: lying or standing"
label variable hc15_6   "Height: lying or standing"
label variable hc16_1   "Day of birth"
label variable hc16_2   "Day of birth"
label variable hc16_3   "Day of birth"
label variable hc16_4   "Day of birth"
label variable hc16_5   "Day of birth"
label variable hc16_6   "Day of birth"
label variable hc17_1   "Date measured (day)"
label variable hc17_2   "Date measured (day)"
label variable hc17_3   "Date measured (day)"
label variable hc17_4   "Date measured (day)"
label variable hc17_5   "Date measured (day)"
label variable hc17_6   "Date measured (day)"
label variable hc18_1   "Date measured (month)"
label variable hc18_2   "Date measured (month)"
label variable hc18_3   "Date measured (month)"
label variable hc18_4   "Date measured (month)"
label variable hc18_5   "Date measured (month)"
label variable hc18_6   "Date measured (month)"
label variable hc19_1   "Date measured (year)"
label variable hc19_2   "Date measured (year)"
label variable hc19_3   "Date measured (year)"
label variable hc19_4   "Date measured (year)"
label variable hc19_5   "Date measured (year)"
label variable hc19_6   "Date measured (year)"
label variable hc20_1   "Century Day Code (CDC) of measurement"
label variable hc20_2   "Century Day Code (CDC) of measurement"
label variable hc20_3   "Century Day Code (CDC) of measurement"
label variable hc20_4   "Century Day Code (CDC) of measurement"
label variable hc20_5   "Century Day Code (CDC) of measurement"
label variable hc20_6   "Century Day Code (CDC) of measurement"
label variable hc21_1   "Fieldworker measurer code"
label variable hc21_2   "Fieldworker measurer code"
label variable hc21_3   "Fieldworker measurer code"
label variable hc21_4   "Fieldworker measurer code"
label variable hc21_5   "Fieldworker measurer code"
label variable hc21_6   "Fieldworker measurer code"
label variable hc27_1   "Sex"
label variable hc27_2   "Sex"
label variable hc27_3   "Sex"
label variable hc27_4   "Sex"
label variable hc27_5   "Sex"
label variable hc27_6   "Sex"
label variable hc30_1   "Month of birth"
label variable hc30_2   "Month of birth"
label variable hc30_3   "Month of birth"
label variable hc30_4   "Month of birth"
label variable hc30_5   "Month of birth"
label variable hc30_6   "Month of birth"
label variable hc31_1   "Year of birth"
label variable hc31_2   "Year of birth"
label variable hc31_3   "Year of birth"
label variable hc31_4   "Year of birth"
label variable hc31_5   "Year of birth"
label variable hc31_6   "Year of birth"
label variable hc32_1   "Date of birth (CMC)"
label variable hc32_2   "Date of birth (CMC)"
label variable hc32_3   "Date of birth (CMC)"
label variable hc32_4   "Date of birth (CMC)"
label variable hc32_5   "Date of birth (CMC)"
label variable hc32_6   "Date of birth (CMC)"
label variable hc32a_1  "Century Day Code (CDC) of birth"
label variable hc32a_2  "Century Day Code (CDC) of birth"
label variable hc32a_3  "Century Day Code (CDC) of birth"
label variable hc32a_4  "Century Day Code (CDC) of birth"
label variable hc32a_5  "Century Day Code (CDC) of birth"
label variable hc32a_6  "Century Day Code (CDC) of birth"
label variable hc33_1   "Completeness of HC32 information"
label variable hc33_2   "Completeness of HC32 information"
label variable hc33_3   "Completeness of HC32 information"
label variable hc33_4   "Completeness of HC32 information"
label variable hc33_5   "Completeness of HC32 information"
label variable hc33_6   "Completeness of HC32 information"
label variable hc51_1   "Line number of parent/caretaker"
label variable hc51_2   "Line number of parent/caretaker"
label variable hc51_3   "Line number of parent/caretaker"
label variable hc51_4   "Line number of parent/caretaker"
label variable hc51_5   "Line number of parent/caretaker"
label variable hc51_6   "Line number of parent/caretaker"
label variable hc52_1   "Read consent statement - hemoglobin"
label variable hc52_2   "Read consent statement - hemoglobin"
label variable hc52_3   "Read consent statement - hemoglobin"
label variable hc52_4   "Read consent statement - hemoglobin"
label variable hc52_5   "Read consent statement - hemoglobin"
label variable hc52_6   "Read consent statement - hemoglobin"
label variable hc53_1   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_2   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_3   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_4   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_5   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_6   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55_1   "Result of measurement - hemoglobin"
label variable hc55_2   "Result of measurement - hemoglobin"
label variable hc55_3   "Result of measurement - hemoglobin"
label variable hc55_4   "Result of measurement - hemoglobin"
label variable hc55_5   "Result of measurement - hemoglobin"
label variable hc55_6   "Result of measurement - hemoglobin"
label variable hc56_1   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_2   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_3   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_4   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_5   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_6   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57_1   "Anemia level"
label variable hc57_2   "Anemia level"
label variable hc57_3   "Anemia level"
label variable hc57_4   "Anemia level"
label variable hc57_5   "Anemia level"
label variable hc57_6   "Anemia level"
label variable hc58_1   "NA - Agrees to referral - anemia"
label variable hc58_2   "NA - Agrees to referral - anemia"
label variable hc58_3   "NA - Agrees to referral - anemia"
label variable hc58_4   "NA - Agrees to referral - anemia"
label variable hc58_5   "NA - Agrees to referral - anemia"
label variable hc58_6   "NA - Agrees to referral - anemia"
label variable hc60_1   "Mother's line number (woman's questionnaire)"
label variable hc60_2   "Mother's line number (woman's questionnaire)"
label variable hc60_3   "Mother's line number (woman's questionnaire)"
label variable hc60_4   "Mother's line number (woman's questionnaire)"
label variable hc60_5   "Mother's line number (woman's questionnaire)"
label variable hc60_6   "Mother's line number (woman's questionnaire)"
label variable hc61_1   "Mother's highest educational level"
label variable hc61_2   "Mother's highest educational level"
label variable hc61_3   "Mother's highest educational level"
label variable hc61_4   "Mother's highest educational level"
label variable hc61_5   "Mother's highest educational level"
label variable hc61_6   "Mother's highest educational level"
label variable hc62_1   "Mother's highest year of education"
label variable hc62_2   "Mother's highest year of education"
label variable hc62_3   "Mother's highest year of education"
label variable hc62_4   "Mother's highest year of education"
label variable hc62_5   "Mother's highest year of education"
label variable hc62_6   "Mother's highest year of education"
label variable hc63_1   "Preceding birth interval (months)"
label variable hc63_2   "Preceding birth interval (months)"
label variable hc63_3   "Preceding birth interval (months)"
label variable hc63_4   "Preceding birth interval (months)"
label variable hc63_5   "Preceding birth interval (months)"
label variable hc63_6   "Preceding birth interval (months)"
label variable hc64_1   "Birth order number"
label variable hc64_2   "Birth order number"
label variable hc64_3   "Birth order number"
label variable hc64_4   "Birth order number"
label variable hc64_5   "Birth order number"
label variable hc64_6   "Birth order number"
label variable hc68_1   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_2   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_3   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_4   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_5   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_6   "Mother's highest educational level (for preliminary and final report)"
label variable hc70_1   "Height/Age standard deviation (new WHO)"
label variable hc70_2   "Height/Age standard deviation (new WHO)"
label variable hc70_3   "Height/Age standard deviation (new WHO)"
label variable hc70_4   "Height/Age standard deviation (new WHO)"
label variable hc70_5   "Height/Age standard deviation (new WHO)"
label variable hc70_6   "Height/Age standard deviation (new WHO)"
label variable hc71_1   "Weight/Age standard deviation (new WHO)"
label variable hc71_2   "Weight/Age standard deviation (new WHO)"
label variable hc71_3   "Weight/Age standard deviation (new WHO)"
label variable hc71_4   "Weight/Age standard deviation (new WHO)"
label variable hc71_5   "Weight/Age standard deviation (new WHO)"
label variable hc71_6   "Weight/Age standard deviation (new WHO)"
label variable hc72_1   "Weight/Height standard deviation (new WHO)"
label variable hc72_2   "Weight/Height standard deviation (new WHO)"
label variable hc72_3   "Weight/Height standard deviation (new WHO)"
label variable hc72_4   "Weight/Height standard deviation (new WHO)"
label variable hc72_5   "Weight/Height standard deviation (new WHO)"
label variable hc72_6   "Weight/Height standard deviation (new WHO)"
label variable hc73_1   "BMI standard deviation (new WHO)"
label variable hc73_2   "BMI standard deviation (new WHO)"
label variable hc73_3   "BMI standard deviation (new WHO)"
label variable hc73_4   "BMI standard deviation (new WHO)"
label variable hc73_5   "BMI standard deviation (new WHO)"
label variable hc73_6   "BMI standard deviation (new WHO)"
label variable hb0_1    "Index to Household Schedule"
label variable hb0_2    "Index to Household Schedule"
label variable hb0_3    "Index to Household Schedule"
label variable hb0_4    "Index to Household Schedule"
label variable hb0_5    "Index to Household Schedule"
label variable hb0_6    "Index to Household Schedule"
label variable hb0_7    "Index to Household Schedule"
label variable hb0_8    "Index to Household Schedule"
label variable hb1_1    "Man's age in years"
label variable hb1_2    "Man's age in years"
label variable hb1_3    "Man's age in years"
label variable hb1_4    "Man's age in years"
label variable hb1_5    "Man's age in years"
label variable hb1_6    "Man's age in years"
label variable hb1_7    "Man's age in years"
label variable hb1_8    "Man's age in years"
label variable hb2_1    "Man's weight in kilograms (1 decimal)"
label variable hb2_2    "Man's weight in kilograms (1 decimal)"
label variable hb2_3    "Man's weight in kilograms (1 decimal)"
label variable hb2_4    "Man's weight in kilograms (1 decimal)"
label variable hb2_5    "Man's weight in kilograms (1 decimal)"
label variable hb2_6    "Man's weight in kilograms (1 decimal)"
label variable hb2_7    "Man's weight in kilograms (1 decimal)"
label variable hb2_8    "Man's weight in kilograms (1 decimal)"
label variable hb3_1    "Man's height in centimeters (1 decimal)"
label variable hb3_2    "Man's height in centimeters (1 decimal)"
label variable hb3_3    "Man's height in centimeters (1 decimal)"
label variable hb3_4    "Man's height in centimeters (1 decimal)"
label variable hb3_5    "Man's height in centimeters (1 decimal)"
label variable hb3_6    "Man's height in centimeters (1 decimal)"
label variable hb3_7    "Man's height in centimeters (1 decimal)"
label variable hb3_8    "Man's height in centimeters (1 decimal)"
label variable hb4_1    "Height/Age percentile"
label variable hb4_2    "Height/Age percentile"
label variable hb4_3    "Height/Age percentile"
label variable hb4_4    "Height/Age percentile"
label variable hb4_5    "Height/Age percentile"
label variable hb4_6    "Height/Age percentile"
label variable hb4_7    "Height/Age percentile"
label variable hb4_8    "Height/Age percentile"
label variable hb5_1    "Height/Age standard deviation"
label variable hb5_2    "Height/Age standard deviation"
label variable hb5_3    "Height/Age standard deviation"
label variable hb5_4    "Height/Age standard deviation"
label variable hb5_5    "Height/Age standard deviation"
label variable hb5_6    "Height/Age standard deviation"
label variable hb5_7    "Height/Age standard deviation"
label variable hb5_8    "Height/Age standard deviation"
label variable hb6_1    "Height/Age percent ref. median"
label variable hb6_2    "Height/Age percent ref. median"
label variable hb6_3    "Height/Age percent ref. median"
label variable hb6_4    "Height/Age percent ref. median"
label variable hb6_5    "Height/Age percent ref. median"
label variable hb6_6    "Height/Age percent ref. median"
label variable hb6_7    "Height/Age percent ref. median"
label variable hb6_8    "Height/Age percent ref. median"
label variable hb11_1   "Weight/Height standard deviation (DHS)"
label variable hb11_2   "Weight/Height standard deviation (DHS)"
label variable hb11_3   "Weight/Height standard deviation (DHS)"
label variable hb11_4   "Weight/Height standard deviation (DHS)"
label variable hb11_5   "Weight/Height standard deviation (DHS)"
label variable hb11_6   "Weight/Height standard deviation (DHS)"
label variable hb11_7   "Weight/Height standard deviation (DHS)"
label variable hb11_8   "Weight/Height standard deviation (DHS)"
label variable hb12_1   "Weight/Height percent ref. median (DHS)"
label variable hb12_2   "Weight/Height percent ref. median (DHS)"
label variable hb12_3   "Weight/Height percent ref. median (DHS)"
label variable hb12_4   "Weight/Height percent ref. median (DHS)"
label variable hb12_5   "Weight/Height percent ref. median (DHS)"
label variable hb12_6   "Weight/Height percent ref. median (DHS)"
label variable hb12_7   "Weight/Height percent ref. median (DHS)"
label variable hb12_8   "Weight/Height percent ref. median (DHS)"
label variable hb12a_1  "Weight/Height percent ref. median (Fog)"
label variable hb12a_2  "Weight/Height percent ref. median (Fog)"
label variable hb12a_3  "Weight/Height percent ref. median (Fog)"
label variable hb12a_4  "Weight/Height percent ref. median (Fog)"
label variable hb12a_5  "Weight/Height percent ref. median (Fog)"
label variable hb12a_6  "Weight/Height percent ref. median (Fog)"
label variable hb12a_7  "Weight/Height percent ref. median (Fog)"
label variable hb12a_8  "Weight/Height percent ref. median (Fog)"
label variable hb12b_1  "Weight/Height percent ref. median (WHO)"
label variable hb12b_2  "Weight/Height percent ref. median (WHO)"
label variable hb12b_3  "Weight/Height percent ref. median (WHO)"
label variable hb12b_4  "Weight/Height percent ref. median (WHO)"
label variable hb12b_5  "Weight/Height percent ref. median (WHO)"
label variable hb12b_6  "Weight/Height percent ref. median (WHO)"
label variable hb12b_7  "Weight/Height percent ref. median (WHO)"
label variable hb12b_8  "Weight/Height percent ref. median (WHO)"
label variable hb13_1   "Result of measurement - height/weight"
label variable hb13_2   "Result of measurement - height/weight"
label variable hb13_3   "Result of measurement - height/weight"
label variable hb13_4   "Result of measurement - height/weight"
label variable hb13_5   "Result of measurement - height/weight"
label variable hb13_6   "Result of measurement - height/weight"
label variable hb13_7   "Result of measurement - height/weight"
label variable hb13_8   "Result of measurement - height/weight"
label variable hb21_1   "Fieldworker measurer code"
label variable hb21_2   "Fieldworker measurer code"
label variable hb21_3   "Fieldworker measurer code"
label variable hb21_4   "Fieldworker measurer code"
label variable hb21_5   "Fieldworker measurer code"
label variable hb21_6   "Fieldworker measurer code"
label variable hb21_7   "Fieldworker measurer code"
label variable hb21_8   "Fieldworker measurer code"
label variable hb32_1   "Date of birth (CMC)"
label variable hb32_2   "Date of birth (CMC)"
label variable hb32_3   "Date of birth (CMC)"
label variable hb32_4   "Date of birth (CMC)"
label variable hb32_5   "Date of birth (CMC)"
label variable hb32_6   "Date of birth (CMC)"
label variable hb32_7   "Date of birth (CMC)"
label variable hb32_8   "Date of birth (CMC)"
label variable hb33_1   "Completeness of HB32 information"
label variable hb33_2   "Completeness of HB32 information"
label variable hb33_3   "Completeness of HB32 information"
label variable hb33_4   "Completeness of HB32 information"
label variable hb33_5   "Completeness of HB32 information"
label variable hb33_6   "Completeness of HB32 information"
label variable hb33_7   "Completeness of HB32 information"
label variable hb33_8   "Completeness of HB32 information"
label variable hb35_1   "Smoking (cigarettes in last 24 hours)"
label variable hb35_2   "Smoking (cigarettes in last 24 hours)"
label variable hb35_3   "Smoking (cigarettes in last 24 hours)"
label variable hb35_4   "Smoking (cigarettes in last 24 hours)"
label variable hb35_5   "Smoking (cigarettes in last 24 hours)"
label variable hb35_6   "Smoking (cigarettes in last 24 hours)"
label variable hb35_7   "Smoking (cigarettes in last 24 hours)"
label variable hb35_8   "Smoking (cigarettes in last 24 hours)"
label variable hb40_1   "Body Mass Index"
label variable hb40_2   "Body Mass Index"
label variable hb40_3   "Body Mass Index"
label variable hb40_4   "Body Mass Index"
label variable hb40_5   "Body Mass Index"
label variable hb40_6   "Body Mass Index"
label variable hb40_7   "Body Mass Index"
label variable hb40_8   "Body Mass Index"
label variable hb41_1   "Rohrer's index"
label variable hb41_2   "Rohrer's index"
label variable hb41_3   "Rohrer's index"
label variable hb41_4   "Rohrer's index"
label variable hb41_5   "Rohrer's index"
label variable hb41_6   "Rohrer's index"
label variable hb41_7   "Rohrer's index"
label variable hb41_8   "Rohrer's index"
label variable hb50_1   "Under age 18"
label variable hb50_2   "Under age 18"
label variable hb50_3   "Under age 18"
label variable hb50_4   "Under age 18"
label variable hb50_5   "Under age 18"
label variable hb50_6   "Under age 18"
label variable hb50_7   "Under age 18"
label variable hb50_8   "Under age 18"
label variable hb51_1   "Line number of parent/caretaker"
label variable hb51_2   "Line number of parent/caretaker"
label variable hb51_3   "Line number of parent/caretaker"
label variable hb51_4   "Line number of parent/caretaker"
label variable hb51_5   "Line number of parent/caretaker"
label variable hb51_6   "Line number of parent/caretaker"
label variable hb51_7   "Line number of parent/caretaker"
label variable hb51_8   "Line number of parent/caretaker"
label variable hb52_1   "Read consent statement - hemoglobin"
label variable hb52_2   "Read consent statement - hemoglobin"
label variable hb52_3   "Read consent statement - hemoglobin"
label variable hb52_4   "Read consent statement - hemoglobin"
label variable hb52_5   "Read consent statement - hemoglobin"
label variable hb52_6   "Read consent statement - hemoglobin"
label variable hb52_7   "Read consent statement - hemoglobin"
label variable hb52_8   "Read consent statement - hemoglobin"
label variable hb53_1   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_2   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_3   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_4   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_5   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_6   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_7   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb53_8   "Hemoglobin level (g/dl - 1 decimal)"
label variable hb55_1   "Result of measurement - hemoglobin"
label variable hb55_2   "Result of measurement - hemoglobin"
label variable hb55_3   "Result of measurement - hemoglobin"
label variable hb55_4   "Result of measurement - hemoglobin"
label variable hb55_5   "Result of measurement - hemoglobin"
label variable hb55_6   "Result of measurement - hemoglobin"
label variable hb55_7   "Result of measurement - hemoglobin"
label variable hb55_8   "Result of measurement - hemoglobin"
label variable hb56_1   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb56_2   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb56_3   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb56_4   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb56_5   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb56_6   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb56_7   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb56_8   "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
label variable hb57_1   "Anemia level"
label variable hb57_2   "Anemia level"
label variable hb57_3   "Anemia level"
label variable hb57_4   "Anemia level"
label variable hb57_5   "Anemia level"
label variable hb57_6   "Anemia level"
label variable hb57_7   "Anemia level"
label variable hb57_8   "Anemia level"
label variable hb58_1   "NA - Agrees to referral - anemia"
label variable hb58_2   "NA - Agrees to referral - anemia"
label variable hb58_3   "NA - Agrees to referral - anemia"
label variable hb58_4   "NA - Agrees to referral - anemia"
label variable hb58_5   "NA - Agrees to referral - anemia"
label variable hb58_6   "NA - Agrees to referral - anemia"
label variable hb58_7   "NA - Agrees to referral - anemia"
label variable hb58_8   "NA - Agrees to referral - anemia"
label variable hb60_1   "Marital status"
label variable hb60_2   "Marital status"
label variable hb60_3   "Marital status"
label variable hb60_4   "Marital status"
label variable hb60_5   "Marital status"
label variable hb60_6   "Marital status"
label variable hb60_7   "Marital status"
label variable hb60_8   "Marital status"
label variable hb61_1   "Read consent statement - HIV"
label variable hb61_2   "Read consent statement - HIV"
label variable hb61_3   "Read consent statement - HIV"
label variable hb61_4   "Read consent statement - HIV"
label variable hb61_5   "Read consent statement - HIV"
label variable hb61_6   "Read consent statement - HIV"
label variable hb61_7   "Read consent statement - HIV"
label variable hb61_8   "Read consent statement - HIV"
label variable hb62_1   "Bar code for HIV blood sample"
label variable hb62_2   "Bar code for HIV blood sample"
label variable hb62_3   "Bar code for HIV blood sample"
label variable hb62_4   "Bar code for HIV blood sample"
label variable hb62_5   "Bar code for HIV blood sample"
label variable hb62_6   "Bar code for HIV blood sample"
label variable hb62_7   "Bar code for HIV blood sample"
label variable hb62_8   "Bar code for HIV blood sample"
label variable hb63_1   "Result of measurement - HIV"
label variable hb63_2   "Result of measurement - HIV"
label variable hb63_3   "Result of measurement - HIV"
label variable hb63_4   "Result of measurement - HIV"
label variable hb63_5   "Result of measurement - HIV"
label variable hb63_6   "Result of measurement - HIV"
label variable hb63_7   "Result of measurement - HIV"
label variable hb63_8   "Result of measurement - HIV"
label variable hb64_1   "Consent for additional tests"
label variable hb64_2   "Consent for additional tests"
label variable hb64_3   "Consent for additional tests"
label variable hb64_4   "Consent for additional tests"
label variable hb64_5   "Consent for additional tests"
label variable hb64_6   "Consent for additional tests"
label variable hb64_7   "Consent for additional tests"
label variable hb64_8   "Consent for additional tests"
label variable hb65_1   "Result of man's individual interview"
label variable hb65_2   "Result of man's individual interview"
label variable hb65_3   "Result of man's individual interview"
label variable hb65_4   "Result of man's individual interview"
label variable hb65_5   "Result of man's individual interview"
label variable hb65_6   "Result of man's individual interview"
label variable hb65_7   "Result of man's individual interview"
label variable hb65_8   "Result of man's individual interview"
label variable hb66_1   "Man's highest educational level"
label variable hb66_2   "Man's highest educational level"
label variable hb66_3   "Man's highest educational level"
label variable hb66_4   "Man's highest educational level"
label variable hb66_5   "Man's highest educational level"
label variable hb66_6   "Man's highest educational level"
label variable hb66_7   "Man's highest educational level"
label variable hb66_8   "Man's highest educational level"
label variable hb67_1   "Man's highest year of education"
label variable hb67_2   "Man's highest year of education"
label variable hb67_3   "Man's highest year of education"
label variable hb67_4   "Man's highest year of education"
label variable hb67_5   "Man's highest year of education"
label variable hb67_6   "Man's highest year of education"
label variable hb67_7   "Man's highest year of education"
label variable hb67_8   "Man's highest year of education"
label variable hb68_1   "Man's highest educational level (for preliminary and final report)"
label variable hb68_2   "Man's highest educational level (for preliminary and final report)"
label variable hb68_3   "Man's highest educational level (for preliminary and final report)"
label variable hb68_4   "Man's highest educational level (for preliminary and final report)"
label variable hb68_5   "Man's highest educational level (for preliminary and final report)"
label variable hb68_6   "Man's highest educational level (for preliminary and final report)"
label variable hb68_7   "Man's highest educational level (for preliminary and final report)"
label variable hb68_8   "Man's highest educational level (for preliminary and final report)"
label variable hb69_1   "HIV weight (6 decimals)"
label variable hb69_2   "HIV weight (6 decimals)"
label variable hb69_3   "HIV weight (6 decimals)"
label variable hb69_4   "HIV weight (6 decimals)"
label variable hb69_5   "HIV weight (6 decimals)"
label variable hb69_6   "HIV weight (6 decimals)"
label variable hb69_7   "HIV weight (6 decimals)"
label variable hb69_8   "HIV weight (6 decimals)"
label variable hb70_1   "Interviewer that took blood for HIV testing"
label variable hb70_2   "Interviewer that took blood for HIV testing"
label variable hb70_3   "Interviewer that took blood for HIV testing"
label variable hb70_4   "Interviewer that took blood for HIV testing"
label variable hb70_5   "Interviewer that took blood for HIV testing"
label variable hb70_6   "Interviewer that took blood for HIV testing"
label variable hb70_7   "Interviewer that took blood for HIV testing"
label variable hb70_8   "Interviewer that took blood for HIV testing"
label variable shcol5_1 "Column number"
label variable shcol5_2 "Column number"
label variable shcol5_3 "Column number"
label variable shcol5_4 "Column number"
label variable sh148_1  "Alive or dead?"
label variable sh148_2  "Alive or dead?"
label variable sh148_3  "Alive or dead?"
label variable sh148_4  "Alive or dead?"
label variable sh149_1  "Type of accident"
label variable sh149_2  "Type of accident"
label variable sh149_3  "Type of accident"
label variable sh149_4  "Type of accident"
label variable sh150_1  "Type of road accident"
label variable sh150_2  "Type of road accident"
label variable sh150_3  "Type of road accident"
label variable sh150_4  "Type of road accident"
label variable sh152_1  "For how long stop doing normal activities"
label variable sh152_2  "For how long stop doing normal activities"
label variable sh152_3  "For how long stop doing normal activities"
label variable sh152_4  "For how long stop doing normal activities"
label variable sh153_1  "Line number in household schedule"
label variable sh153_2  "Line number in household schedule"
label variable sh153_3  "Line number in household schedule"
label variable sh153_4  "Line number in household schedule"
label variable sh154_1  "Sex"
label variable sh154_2  "Sex"
label variable sh154_3  "Sex"
label variable sh154_4  "Sex"
label variable sh154a_1 "Age"
label variable sh154a_2 "Age"
label variable sh154a_3 "Age"
label variable sh154a_4 "Age"
label variable sh155_1  "Was death due to accident?"
label variable sh155_2  "Was death due to accident?"
label variable sh155_3  "Was death due to accident?"
label variable sh155_4  "Was death due to accident?"
label variable sh156_1  "Age at death"
label variable sh156_2  "Age at death"
label variable sh156_3  "Age at death"
label variable sh156_4  "Age at death"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV023   
     0 "National"
;
label define HV024   
     1 "Tigray"
     2 "Afar"
     3 "Amhara"
     4 "Oromia"
     5 "Somali"
     6 "Benishangul"
     7 "SNNPR"
     8 "Gambela"
     9 "Harari"
    10 "Addis Adaba"
    11 "Dire Dawa"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV045A  
     1 "English"
     2 "Amarigna"
     3 "Tigrigna"
     4 "Oromigna"
    96 "Other"
;
label define HV045B  
     1 "English"
     2 "Amarigna"
     3 "Tigrigna"
     4 "Oromigna"
     6 "Afarigna"
     7 "Somaligna"
     8 "Wolyitgna"
     9 "Gamogna/Dorzigna/Zagulna"
    10 "Hadiygna"
    11 "Kembatigna"
    12 "Sidamigna"
    13 "Gedeogna"
    14 "Guragigna/Meskan/Welane"
    15 "Keffigna/Kefficho"
    16 "Hararigna/Adirigna"
    17 "Agewigna/Awi"
    18 "Agnwakigna"
    19 "Nuwerigna/Gambeligna"
    20 "Ginirgna"
    21 "Mezengrigna"
    22 "Gumuzigna/Bangagna"
    23 "Siltigna"
    24 "Arigna"
    25 "Basketigna"
    26 "Burjigna"
    27 "Dawerogna"
    28 "Goffagna"
    29 "Halibigna"
    30 "Ruteangna"
    31 "Shehogna"
    32 "Shekogna"
    33 "Benichigna"
    34 "Darashegna"
    35 "Kebegna"
    36 "Kontegna"
    37 "Konsogna"
    38 "Maogna"
    39 "Shekichogna/Mochagna"
    40 "Shinashigna"
    41 "Yemigna"
    42 "Zeyisegna"
    43 "Bertigna"
    44 "Komogna"
    45 "Dezigna/Majigna"
    46 "Saho/Erobigna"
    47 "Gofegna"
    48 "Hemetgna"
    96 "Other"
;
label define HV045C  
     1 "English"
     2 "Amarigna"
     3 "Tigrigna"
     4 "Oromigna"
     6 "Afarigna"
     7 "Somaligna"
     8 "Wolyitgna"
     9 "Gamogna/Dorzigna/Zagulna"
    10 "Hadiygna"
    11 "Kembatigna"
    12 "Sidamigna"
    13 "Gedeogna"
    14 "Guragigna/Meskan/Welane"
    15 "Keffigna/Kefficho"
    16 "Hararigna/Adirigna"
    17 "Agewigna/Awi"
    18 "Agnwakigna"
    19 "Nuwerigna/Gambeligna"
    20 "Ginirgna"
    21 "Mezengrigna"
    22 "Gumuzigna/Bangagna"
    23 "Siltigna"
    24 "Arigna"
    25 "Basketigna"
    26 "Burjigna"
    27 "Dawerogna"
    28 "Goffagna"
    29 "Halibigna"
    30 "Ruteangna"
    31 "Shehogna"
    32 "Shekogna"
    33 "Benichigna"
    34 "Darashegna"
    35 "Kebegna"
    36 "Kontegna"
    37 "Konsogna"
    38 "Maogna"
    39 "Shekichogna/Mochagna"
    40 "Shinashigna"
    41 "Yemigna"
    42 "Zeyisegna"
    43 "Bertigna"
    44 "Komogna"
    45 "Dezigna/Majigna"
    46 "Saho/Erobigna"
    47 "Gofegna"
    48 "Hemetgna"
    96 "Other"
;
label define HV046   
     0 "No"
     1 "Yes"
;
label define HV801   
  9999 "Missing"
;
label define HV802   
  9999 "Missing"
;
label define HV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define HV804   
     9 "Missing"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV201A  
     0 "No, not interrupted for a full day"
     1 "Yes, interruped for a full day or more"
     8 "Don't know"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
;
label define HV214   
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Dirt"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
;
label define HV215   
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/mud"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Metal/ corrugated iron"
    32 "Wood"
    33 "Calamine/cement fiber"
    34 "Ceramic tiles"
    35 "Cement"
    36 "Roofing shingles"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in house"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV230A  
     1 "Observed, fixed place"
     2 "Observed, mobile place"
     3 "Not observed: not in dwelling"
     4 "Not observed: no permission to see"
     5 "Not observed: other reason"
;
label define HV230B  
     0 "Water not available"
     1 "Water is available"
;
label define HV232   
     0 "No"
     1 "Yes"
;
label define HV232B  
     0 "No"
     1 "Yes"
;
label define HV232C  
     0 "No"
     1 "Yes"
;
label define HV232D  
     0 "No"
     1 "Yes"
;
label define HV232E  
     0 "No"
     1 "Yes"
;
label define HV232Y  
     0 "No"
     1 "Yes: no cleansing agent observed"
;
label define HV234   
     0 "0 PPM (no iodine)"
     7 "Below 15 PPM"
    15 "15 PPM and above"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define HV234A  
     0 "No iodine"
     1 "Iodine present"
     3 "No salt in household"
     6 "Salt not tested"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV236   
     1 "Adult woman"
     2 "Adult man"
     3 "Female child under 15 years old"
     4 "Male child under 15 years old"
     6 "Other"
;
label define HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237I  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237J  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237K  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237Z  
     0 "No"
     1 "Yes: don't know what is done to water"
     8 "Don't know"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV238A  
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     0 "Neither chimney or hood"
     1 "Chimney"
     2 "Hood"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV243E  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
   950 "95 or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV252   
     0 "Never"
     1 "Daily"
     2 "Weekly"
     3 "Monthly"
     4 "Less than once a month"
;
label define HV253   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253Z  
     0 "No"
     1 "Yes: don't know who sprayed the dwelling"
     8 "Don't know if it was sprayed"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HV270A  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SH121G  
     0 "No"
     1 "Yes"
;
label define SH121H  
     0 "No"
     1 "Yes"
;
label define SH121I  
     0 "No"
     1 "Yes"
;
label define SH121J  
     0 "No"
     1 "Yes"
;
label define SH121K  
     0 "No"
     1 "Yes"
;
label define SH122H  
     0 "No"
     1 "Yes"
;
label define SH146   
     0 "No"
     1 "Yes"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    98 "Don't know"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV107   
    98 "Don't know"
;
label define HV108   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
;
label define HV110   
     0 "No"
     1 "Yes"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV112   
     0 "Mother not in household"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV114   
     0 "Father not in household"
;
label define HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever married"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV123   
    98 "Don't know"
;
label define HV124   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HV127   
    98 "Don't know"
;
label define HV128   
    97 "Inconsistent"
    98 "Don't know"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "Don't know"
;
label define HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     8 "Don't know"
;
label define SH16    
     0 "No"
     1 "Yes"
;
label define SH17A   
     0 "Preschool"
     1 "Primary"
     2 "Secondary"
     3 "Technical/ vocational"
     4 "Higher"
     8 "Don't know"
;
label define SH17B   
     0 "Less than 1 year completed"
    98 "Don't know"
;
label define SH18    
     0 "No"
     1 "Yes"
;
label define SH19A   
     0 "Preschool"
     1 "Primary"
     2 "Secondary"
     3 "Technical/ vocational"
     4 "Higher"
     8 "Don't know"
;
label define SH19B   
    98 "Don't know"
;
label define SM07I   
    95 "95+"
    98 "Don't know"
;
label define SM07F   
     0 "No data from individual questionnaire"
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define SMPREG  
     1 "Yes"
     0 "No, don't know"
;
label define SB103D  
    98 "DK"
;
label define SB103M  
    97 "Inconsistent"
    98 "DK"
;
label define HA2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HA4     
  9998 "Flagged cases"
;
label define HA5     
  9998 "Flagged cases"
;
label define HA6     
 99998 "Flagged cases"
;
label define HA11    
  9998 "Flagged cases"
;
label define HA12    
 99998 "Flagged cases"
;
label define HA12A   
 99998 "Flagged cases"
;
label define HA12B   
 99998 "Flagged cases"
;
label define HA13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA33    
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HA35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
;
label define HA40    
  9998 "Flagged cases"
;
label define HA41    
  9998 "Flagged cases"
;
label define HA50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HA51    
     0 "Not in household"
;
label define HA52    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define HA53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HA54    
     0 "No/don't know"
     1 "Yes"
;
label define HA55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA56    
   997 "Inconsistent"
;
label define HA57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HA58    
     0 "No"
     1 "Yes"
;
label define HA60    
     1 "Never in union"
     2 "Other"
;
label define HA61    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
     6 "Sample not tested/lost/not enough DBS"
;
label define HA63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost/damaged/insufficient"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HA64    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     6 "Sample not tested/lost/not enough DBS"
;
label define HA65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HA66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Technical/ vocational"
     4 "Higher"
     8 "Don't know"
;
label define HA67    
    98 "Don't know"
;
label define HA68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "More than secondary"
     8 "Don't know"
;
label define HC2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HC4     
  9998 "Flagged cases"
;
label define HC5     
  9998 "Flagged cases"
;
label define HC6     
 99998 "Flagged cases"
;
label define HC7     
  9998 "Flagged cases"
;
label define HC8     
  9998 "Flagged cases"
;
label define HC9     
 99998 "Flagged cases"
;
label define HC10    
  9998 "Flagged cases"
;
label define HC11    
  9998 "Flagged cases"
;
label define HC12    
 99998 "Flagged cases"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC15    
     0 "Not measured"
     1 "Lying"
     2 "Standing"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     0 "Day, month and year - information complete"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present/other"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Technical/ vocational"
     4 "Higher"
     8 "Don't know"
;
label define HC62    
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "More than secondary"
     8 "Don't know"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HB2     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HB3     
  9994 "Not present"
  9995 "Refused"
  9996 "Other"
;
label define HB4     
  9998 "Flagged cases"
;
label define HB5     
  9998 "Flagged cases"
;
label define HB6     
 99998 "Flagged cases"
;
label define HB11    
  9998 "Flagged cases"
;
label define HB12    
 99998 "Flagged cases"
;
label define HB12A   
 99998 "Flagged cases"
;
label define HB12B   
 99998 "Flagged cases"
;
label define HB13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HB33    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HB35    
     0 "Doesn't smoke"
    90 "90+"
    94 "Smokes pipes, cigars, etc"
;
label define HB40    
  9998 "Flagged cases"
;
label define HB41    
  9998 "Flagged cases"
;
label define HB50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HB51    
     0 "Not in household"
;
label define HB52    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define HB53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HB55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HB56    
   997 "Inconsistent"
;
label define HB57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HB58    
     0 "No"
     1 "Yes"
;
label define HB60    
     1 "Never in union"
     2 "Other"
;
label define HB61    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
     6 "Sample not tested/lost/not enough DBS"
;
label define HB63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Sample not tested/lost/damaged/insufficient"
     5 "Not enough DBS to complete protocol"
     6 "Other"
;
label define HB64    
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define HB65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HB66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Technical/ vocational"
     4 "Higher"
     8 "Don't know"
;
label define HB67    
    98 "Don't know"
;
label define HB68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "More than secondary"
     8 "Don't know"
;
label define SH148   
     1 "Alive"
     2 "Dead"
;
label define SH149   
     1 "Road traffic accident"
     2 "Violence/assault"
     3 "Fire/burning"
     4 "Animal bite"
     5 "Accidental fall"
     6 "Drowning"
     7 "Poisoning"
     8 "Kicked by cattle"
     9 "Fall from tree/building"
    96 "Other"
    98 "Dont know"
;
label define SH150   
     1 "Road accident driver"
     2 "Road accident occupant"
     3 "Pedestrian"
     4 "Road accident bicycle"
     5 "Motorized two wheeler"
    96 "Other"
;
label define SH152   
     1 "Less than 7 days"
     2 "Between 8 to 30 days"
     3 "Between 2 to 6 months"
     4 "Longer than 6 months"
     8 "Don't know"
;
label define SH153   
     0 "Not in the household"
;
label define SH154   
     1 "Male"
     2 "Female"
;
label define SH154A  
    95 "95+"
    98 "Don't know"
;
label define SH155   
     0 "No"
     1 "Yes"
;
label define SH156   
    95 "95+"
    98 "Don't know"
;

#delimit cr
label values hv003    HV003   
label values hv015    HV015   
label values hv020    HV020   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv044    HV044   
label values hv045a   HV045A  
label values hv045b   HV045B  
label values hv045c   HV045C  
label values hv046    HV046   
label values hv803    HV803   
label values hv201    HV201   
label values hv202    HV202   
label values hv201a   HV201A  
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv230a   HV230A  
label values hv230b   HV230B  
label values hv232    HV232   
label values hv232b   HV232B  
label values hv232c   HV232C  
label values hv232d   HV232D  
label values hv232e   HV232E  
label values hv232y   HV232Y  
label values hv234    HV234   
label values hv234a   HV234A  
label values hv235    HV235   
label values hv236    HV236   
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237g   HV237G  
label values hv237h   HV237H  
label values hv237i   HV237I  
label values hv237j   HV237J  
label values hv237k   HV237K  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv238a   HV238A  
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv243e   HV243E  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv252    HV252   
label values hv253    HV253   
label values hv253a   HV253A  
label values hv253b   HV253B  
label values hv253c   HV253C  
label values hv253d   HV253D  
label values hv253e   HV253E  
label values hv253f   HV253F  
label values hv253g   HV253G  
label values hv253h   HV253H  
label values hv253x   HV253X  
label values hv253z   HV253Z  
label values hv270    HV270   
label values hv270a   HV270A  
label values hml1     HML1    
label values sh121g   SH121G  
label values sh121h   SH121H  
label values sh121i   SH121I  
label values sh121j   SH121J  
label values sh121k   SH121K  
label values sh122h   SH122H  
label values sh146    SH146   
label values hv101_01 HV101   
label values hv101_02 HV101   
label values hv101_03 HV101   
label values hv101_04 HV101   
label values hv101_05 HV101   
label values hv101_06 HV101   
label values hv101_07 HV101   
label values hv101_08 HV101   
label values hv101_09 HV101   
label values hv101_10 HV101   
label values hv101_11 HV101   
label values hv101_12 HV101   
label values hv101_13 HV101   
label values hv101_14 HV101   
label values hv101_15 HV101   
label values hv101_16 HV101   
label values hv101_17 HV101   
label values hv101_18 HV101   
label values hv101_19 HV101   
label values hv101_20 HV101   
label values hv102_01 HV102   
label values hv102_02 HV102   
label values hv102_03 HV102   
label values hv102_04 HV102   
label values hv102_05 HV102   
label values hv102_06 HV102   
label values hv102_07 HV102   
label values hv102_08 HV102   
label values hv102_09 HV102   
label values hv102_10 HV102   
label values hv102_11 HV102   
label values hv102_12 HV102   
label values hv102_13 HV102   
label values hv102_14 HV102   
label values hv102_15 HV102   
label values hv102_16 HV102   
label values hv102_17 HV102   
label values hv102_18 HV102   
label values hv102_19 HV102   
label values hv102_20 HV102   
label values hv103_01 HV103   
label values hv103_02 HV103   
label values hv103_03 HV103   
label values hv103_04 HV103   
label values hv103_05 HV103   
label values hv103_06 HV103   
label values hv103_07 HV103   
label values hv103_08 HV103   
label values hv103_09 HV103   
label values hv103_10 HV103   
label values hv103_11 HV103   
label values hv103_12 HV103   
label values hv103_13 HV103   
label values hv103_14 HV103   
label values hv103_15 HV103   
label values hv103_16 HV103   
label values hv103_17 HV103   
label values hv103_18 HV103   
label values hv103_19 HV103   
label values hv103_20 HV103   
label values hv104_01 HV104   
label values hv104_02 HV104   
label values hv104_03 HV104   
label values hv104_04 HV104   
label values hv104_05 HV104   
label values hv104_06 HV104   
label values hv104_07 HV104   
label values hv104_08 HV104   
label values hv104_09 HV104   
label values hv104_10 HV104   
label values hv104_11 HV104   
label values hv104_12 HV104   
label values hv104_13 HV104   
label values hv104_14 HV104   
label values hv104_15 HV104   
label values hv104_16 HV104   
label values hv104_17 HV104   
label values hv104_18 HV104   
label values hv104_19 HV104   
label values hv104_20 HV104   
label values hv105_01 HV105   
label values hv105_02 HV105   
label values hv105_03 HV105   
label values hv105_04 HV105   
label values hv105_05 HV105   
label values hv105_06 HV105   
label values hv105_07 HV105   
label values hv105_08 HV105   
label values hv105_09 HV105   
label values hv105_10 HV105   
label values hv105_11 HV105   
label values hv105_12 HV105   
label values hv105_13 HV105   
label values hv105_14 HV105   
label values hv105_15 HV105   
label values hv105_16 HV105   
label values hv105_17 HV105   
label values hv105_18 HV105   
label values hv105_19 HV105   
label values hv105_20 HV105   
label values hv106_01 HV106   
label values hv106_02 HV106   
label values hv106_03 HV106   
label values hv106_04 HV106   
label values hv106_05 HV106   
label values hv106_06 HV106   
label values hv106_07 HV106   
label values hv106_08 HV106   
label values hv106_09 HV106   
label values hv106_10 HV106   
label values hv106_11 HV106   
label values hv106_12 HV106   
label values hv106_13 HV106   
label values hv106_14 HV106   
label values hv106_15 HV106   
label values hv106_16 HV106   
label values hv106_17 HV106   
label values hv106_18 HV106   
label values hv106_19 HV106   
label values hv106_20 HV106   
label values hv107_01 HV107   
label values hv107_02 HV107   
label values hv107_03 HV107   
label values hv107_04 HV107   
label values hv107_05 HV107   
label values hv107_06 HV107   
label values hv107_07 HV107   
label values hv107_08 HV107   
label values hv107_09 HV107   
label values hv107_10 HV107   
label values hv107_11 HV107   
label values hv107_12 HV107   
label values hv107_13 HV107   
label values hv107_14 HV107   
label values hv107_15 HV107   
label values hv107_16 HV107   
label values hv107_17 HV107   
label values hv107_18 HV107   
label values hv107_19 HV107   
label values hv107_20 HV107   
label values hv108_01 HV108   
label values hv108_02 HV108   
label values hv108_03 HV108   
label values hv108_04 HV108   
label values hv108_05 HV108   
label values hv108_06 HV108   
label values hv108_07 HV108   
label values hv108_08 HV108   
label values hv108_09 HV108   
label values hv108_10 HV108   
label values hv108_11 HV108   
label values hv108_12 HV108   
label values hv108_13 HV108   
label values hv108_14 HV108   
label values hv108_15 HV108   
label values hv108_16 HV108   
label values hv108_17 HV108   
label values hv108_18 HV108   
label values hv108_19 HV108   
label values hv108_20 HV108   
label values hv109_01 HV109   
label values hv109_02 HV109   
label values hv109_03 HV109   
label values hv109_04 HV109   
label values hv109_05 HV109   
label values hv109_06 HV109   
label values hv109_07 HV109   
label values hv109_08 HV109   
label values hv109_09 HV109   
label values hv109_10 HV109   
label values hv109_11 HV109   
label values hv109_12 HV109   
label values hv109_13 HV109   
label values hv109_14 HV109   
label values hv109_15 HV109   
label values hv109_16 HV109   
label values hv109_17 HV109   
label values hv109_18 HV109   
label values hv109_19 HV109   
label values hv109_20 HV109   
label values hv110_01 HV110   
label values hv110_02 HV110   
label values hv110_03 HV110   
label values hv110_04 HV110   
label values hv110_05 HV110   
label values hv110_06 HV110   
label values hv110_07 HV110   
label values hv110_08 HV110   
label values hv110_09 HV110   
label values hv110_10 HV110   
label values hv110_11 HV110   
label values hv110_12 HV110   
label values hv110_13 HV110   
label values hv110_14 HV110   
label values hv110_15 HV110   
label values hv110_16 HV110   
label values hv110_17 HV110   
label values hv110_18 HV110   
label values hv110_19 HV110   
label values hv110_20 HV110   
label values hv111_01 HV111   
label values hv111_02 HV111   
label values hv111_03 HV111   
label values hv111_04 HV111   
label values hv111_05 HV111   
label values hv111_06 HV111   
label values hv111_07 HV111   
label values hv111_08 HV111   
label values hv111_09 HV111   
label values hv111_10 HV111   
label values hv111_11 HV111   
label values hv111_12 HV111   
label values hv111_13 HV111   
label values hv111_14 HV111   
label values hv111_15 HV111   
label values hv111_16 HV111   
label values hv111_17 HV111   
label values hv111_18 HV111   
label values hv111_19 HV111   
label values hv111_20 HV111   
label values hv112_01 HV112   
label values hv112_02 HV112   
label values hv112_03 HV112   
label values hv112_04 HV112   
label values hv112_05 HV112   
label values hv112_06 HV112   
label values hv112_07 HV112   
label values hv112_08 HV112   
label values hv112_09 HV112   
label values hv112_10 HV112   
label values hv112_11 HV112   
label values hv112_12 HV112   
label values hv112_13 HV112   
label values hv112_14 HV112   
label values hv112_15 HV112   
label values hv112_16 HV112   
label values hv112_17 HV112   
label values hv112_18 HV112   
label values hv112_19 HV112   
label values hv112_20 HV112   
label values hv113_01 HV113   
label values hv113_02 HV113   
label values hv113_03 HV113   
label values hv113_04 HV113   
label values hv113_05 HV113   
label values hv113_06 HV113   
label values hv113_07 HV113   
label values hv113_08 HV113   
label values hv113_09 HV113   
label values hv113_10 HV113   
label values hv113_11 HV113   
label values hv113_12 HV113   
label values hv113_13 HV113   
label values hv113_14 HV113   
label values hv113_15 HV113   
label values hv113_16 HV113   
label values hv113_17 HV113   
label values hv113_18 HV113   
label values hv113_19 HV113   
label values hv113_20 HV113   
label values hv114_01 HV114   
label values hv114_02 HV114   
label values hv114_03 HV114   
label values hv114_04 HV114   
label values hv114_05 HV114   
label values hv114_06 HV114   
label values hv114_07 HV114   
label values hv114_08 HV114   
label values hv114_09 HV114   
label values hv114_10 HV114   
label values hv114_11 HV114   
label values hv114_12 HV114   
label values hv114_13 HV114   
label values hv114_14 HV114   
label values hv114_15 HV114   
label values hv114_16 HV114   
label values hv114_17 HV114   
label values hv114_18 HV114   
label values hv114_19 HV114   
label values hv114_20 HV114   
label values hv115_01 HV115   
label values hv115_02 HV115   
label values hv115_03 HV115   
label values hv115_04 HV115   
label values hv115_05 HV115   
label values hv115_06 HV115   
label values hv115_07 HV115   
label values hv115_08 HV115   
label values hv115_09 HV115   
label values hv115_10 HV115   
label values hv115_11 HV115   
label values hv115_12 HV115   
label values hv115_13 HV115   
label values hv115_14 HV115   
label values hv115_15 HV115   
label values hv115_16 HV115   
label values hv115_17 HV115   
label values hv115_18 HV115   
label values hv115_19 HV115   
label values hv115_20 HV115   
label values hv116_01 HV116   
label values hv116_02 HV116   
label values hv116_03 HV116   
label values hv116_04 HV116   
label values hv116_05 HV116   
label values hv116_06 HV116   
label values hv116_07 HV116   
label values hv116_08 HV116   
label values hv116_09 HV116   
label values hv116_10 HV116   
label values hv116_11 HV116   
label values hv116_12 HV116   
label values hv116_13 HV116   
label values hv116_14 HV116   
label values hv116_15 HV116   
label values hv116_16 HV116   
label values hv116_17 HV116   
label values hv116_18 HV116   
label values hv116_19 HV116   
label values hv116_20 HV116   
label values hv117_01 HV117   
label values hv117_02 HV117   
label values hv117_03 HV117   
label values hv117_04 HV117   
label values hv117_05 HV117   
label values hv117_06 HV117   
label values hv117_07 HV117   
label values hv117_08 HV117   
label values hv117_09 HV117   
label values hv117_10 HV117   
label values hv117_11 HV117   
label values hv117_12 HV117   
label values hv117_13 HV117   
label values hv117_14 HV117   
label values hv117_15 HV117   
label values hv117_16 HV117   
label values hv117_17 HV117   
label values hv117_18 HV117   
label values hv117_19 HV117   
label values hv117_20 HV117   
label values hv118_01 HV118   
label values hv118_02 HV118   
label values hv118_03 HV118   
label values hv118_04 HV118   
label values hv118_05 HV118   
label values hv118_06 HV118   
label values hv118_07 HV118   
label values hv118_08 HV118   
label values hv118_09 HV118   
label values hv118_10 HV118   
label values hv118_11 HV118   
label values hv118_12 HV118   
label values hv118_13 HV118   
label values hv118_14 HV118   
label values hv118_15 HV118   
label values hv118_16 HV118   
label values hv118_17 HV118   
label values hv118_18 HV118   
label values hv118_19 HV118   
label values hv118_20 HV118   
label values hv120_01 HV120   
label values hv120_02 HV120   
label values hv120_03 HV120   
label values hv120_04 HV120   
label values hv120_05 HV120   
label values hv120_06 HV120   
label values hv120_07 HV120   
label values hv120_08 HV120   
label values hv120_09 HV120   
label values hv120_10 HV120   
label values hv120_11 HV120   
label values hv120_12 HV120   
label values hv120_13 HV120   
label values hv120_14 HV120   
label values hv120_15 HV120   
label values hv120_16 HV120   
label values hv120_17 HV120   
label values hv120_18 HV120   
label values hv120_19 HV120   
label values hv120_20 HV120   
label values hv121_01 HV121   
label values hv121_02 HV121   
label values hv121_03 HV121   
label values hv121_04 HV121   
label values hv121_05 HV121   
label values hv121_06 HV121   
label values hv121_07 HV121   
label values hv121_08 HV121   
label values hv121_09 HV121   
label values hv121_10 HV121   
label values hv121_11 HV121   
label values hv121_12 HV121   
label values hv121_13 HV121   
label values hv121_14 HV121   
label values hv121_15 HV121   
label values hv121_16 HV121   
label values hv121_17 HV121   
label values hv121_18 HV121   
label values hv121_19 HV121   
label values hv121_20 HV121   
label values hv122_01 HV122   
label values hv122_02 HV122   
label values hv122_03 HV122   
label values hv122_04 HV122   
label values hv122_05 HV122   
label values hv122_06 HV122   
label values hv122_07 HV122   
label values hv122_08 HV122   
label values hv122_09 HV122   
label values hv122_10 HV122   
label values hv122_11 HV122   
label values hv122_12 HV122   
label values hv122_13 HV122   
label values hv122_14 HV122   
label values hv122_15 HV122   
label values hv122_16 HV122   
label values hv122_17 HV122   
label values hv122_18 HV122   
label values hv122_19 HV122   
label values hv122_20 HV122   
label values hv123_01 HV123   
label values hv123_02 HV123   
label values hv123_03 HV123   
label values hv123_04 HV123   
label values hv123_05 HV123   
label values hv123_06 HV123   
label values hv123_07 HV123   
label values hv123_08 HV123   
label values hv123_09 HV123   
label values hv123_10 HV123   
label values hv123_11 HV123   
label values hv123_12 HV123   
label values hv123_13 HV123   
label values hv123_14 HV123   
label values hv123_15 HV123   
label values hv123_16 HV123   
label values hv123_17 HV123   
label values hv123_18 HV123   
label values hv123_19 HV123   
label values hv123_20 HV123   
label values hv124_01 HV124   
label values hv124_02 HV124   
label values hv124_03 HV124   
label values hv124_04 HV124   
label values hv124_05 HV124   
label values hv124_06 HV124   
label values hv124_07 HV124   
label values hv124_08 HV124   
label values hv124_09 HV124   
label values hv124_10 HV124   
label values hv124_11 HV124   
label values hv124_12 HV124   
label values hv124_13 HV124   
label values hv124_14 HV124   
label values hv124_15 HV124   
label values hv124_16 HV124   
label values hv124_17 HV124   
label values hv124_18 HV124   
label values hv124_19 HV124   
label values hv124_20 HV124   
label values hv125_01 HV125   
label values hv125_02 HV125   
label values hv125_03 HV125   
label values hv125_04 HV125   
label values hv125_05 HV125   
label values hv125_06 HV125   
label values hv125_07 HV125   
label values hv125_08 HV125   
label values hv125_09 HV125   
label values hv125_10 HV125   
label values hv125_11 HV125   
label values hv125_12 HV125   
label values hv125_13 HV125   
label values hv125_14 HV125   
label values hv125_15 HV125   
label values hv125_16 HV125   
label values hv125_17 HV125   
label values hv125_18 HV125   
label values hv125_19 HV125   
label values hv125_20 HV125   
label values hv126_01 HV126   
label values hv126_02 HV126   
label values hv126_03 HV126   
label values hv126_04 HV126   
label values hv126_05 HV126   
label values hv126_06 HV126   
label values hv126_07 HV126   
label values hv126_08 HV126   
label values hv126_09 HV126   
label values hv126_10 HV126   
label values hv126_11 HV126   
label values hv126_12 HV126   
label values hv126_13 HV126   
label values hv126_14 HV126   
label values hv126_15 HV126   
label values hv126_16 HV126   
label values hv126_17 HV126   
label values hv126_18 HV126   
label values hv126_19 HV126   
label values hv126_20 HV126   
label values hv127_01 HV127   
label values hv127_02 HV127   
label values hv127_03 HV127   
label values hv127_04 HV127   
label values hv127_05 HV127   
label values hv127_06 HV127   
label values hv127_07 HV127   
label values hv127_08 HV127   
label values hv127_09 HV127   
label values hv127_10 HV127   
label values hv127_11 HV127   
label values hv127_12 HV127   
label values hv127_13 HV127   
label values hv127_14 HV127   
label values hv127_15 HV127   
label values hv127_16 HV127   
label values hv127_17 HV127   
label values hv127_18 HV127   
label values hv127_19 HV127   
label values hv127_20 HV127   
label values hv128_01 HV128   
label values hv128_02 HV128   
label values hv128_03 HV128   
label values hv128_04 HV128   
label values hv128_05 HV128   
label values hv128_06 HV128   
label values hv128_07 HV128   
label values hv128_08 HV128   
label values hv128_09 HV128   
label values hv128_10 HV128   
label values hv128_11 HV128   
label values hv128_12 HV128   
label values hv128_13 HV128   
label values hv128_14 HV128   
label values hv128_15 HV128   
label values hv128_16 HV128   
label values hv128_17 HV128   
label values hv128_18 HV128   
label values hv128_19 HV128   
label values hv128_20 HV128   
label values hv129_01 HV129   
label values hv129_02 HV129   
label values hv129_03 HV129   
label values hv129_04 HV129   
label values hv129_05 HV129   
label values hv129_06 HV129   
label values hv129_07 HV129   
label values hv129_08 HV129   
label values hv129_09 HV129   
label values hv129_10 HV129   
label values hv129_11 HV129   
label values hv129_12 HV129   
label values hv129_13 HV129   
label values hv129_14 HV129   
label values hv129_15 HV129   
label values hv129_16 HV129   
label values hv129_17 HV129   
label values hv129_18 HV129   
label values hv129_19 HV129   
label values hv129_20 HV129   
label values hv140_01 HV140   
label values hv140_02 HV140   
label values hv140_03 HV140   
label values hv140_04 HV140   
label values hv140_05 HV140   
label values hv140_06 HV140   
label values hv140_07 HV140   
label values hv140_08 HV140   
label values hv140_09 HV140   
label values hv140_10 HV140   
label values hv140_11 HV140   
label values hv140_12 HV140   
label values hv140_13 HV140   
label values hv140_14 HV140   
label values hv140_15 HV140   
label values hv140_16 HV140   
label values hv140_17 HV140   
label values hv140_18 HV140   
label values hv140_19 HV140   
label values hv140_20 HV140   
label values sh16_01  SH16    
label values sh16_02  SH16    
label values sh16_03  SH16    
label values sh16_04  SH16    
label values sh16_05  SH16    
label values sh16_06  SH16    
label values sh16_07  SH16    
label values sh16_08  SH16    
label values sh16_09  SH16    
label values sh16_10  SH16    
label values sh16_11  SH16    
label values sh16_12  SH16    
label values sh16_13  SH16    
label values sh16_14  SH16    
label values sh16_15  SH16    
label values sh16_16  SH16    
label values sh16_17  SH16    
label values sh16_18  SH16    
label values sh16_19  SH16    
label values sh16_20  SH16    
label values sh17a_01 SH17A   
label values sh17a_02 SH17A   
label values sh17a_03 SH17A   
label values sh17a_04 SH17A   
label values sh17a_05 SH17A   
label values sh17a_06 SH17A   
label values sh17a_07 SH17A   
label values sh17a_08 SH17A   
label values sh17a_09 SH17A   
label values sh17a_10 SH17A   
label values sh17a_11 SH17A   
label values sh17a_12 SH17A   
label values sh17a_13 SH17A   
label values sh17a_14 SH17A   
label values sh17a_15 SH17A   
label values sh17a_16 SH17A   
label values sh17a_17 SH17A   
label values sh17a_18 SH17A   
label values sh17a_19 SH17A   
label values sh17a_20 SH17A   
label values sh17b_01 SH17B   
label values sh17b_02 SH17B   
label values sh17b_03 SH17B   
label values sh17b_04 SH17B   
label values sh17b_05 SH17B   
label values sh17b_06 SH17B   
label values sh17b_07 SH17B   
label values sh17b_08 SH17B   
label values sh17b_09 SH17B   
label values sh17b_10 SH17B   
label values sh17b_11 SH17B   
label values sh17b_12 SH17B   
label values sh17b_13 SH17B   
label values sh17b_14 SH17B   
label values sh17b_15 SH17B   
label values sh17b_16 SH17B   
label values sh17b_17 SH17B   
label values sh17b_18 SH17B   
label values sh17b_19 SH17B   
label values sh17b_20 SH17B   
label values sh18_01  SH18    
label values sh18_02  SH18    
label values sh18_03  SH18    
label values sh18_04  SH18    
label values sh18_05  SH18    
label values sh18_06  SH18    
label values sh18_07  SH18    
label values sh18_08  SH18    
label values sh18_09  SH18    
label values sh18_10  SH18    
label values sh18_11  SH18    
label values sh18_12  SH18    
label values sh18_13  SH18    
label values sh18_14  SH18    
label values sh18_15  SH18    
label values sh18_16  SH18    
label values sh18_17  SH18    
label values sh18_18  SH18    
label values sh18_19  SH18    
label values sh18_20  SH18    
label values sh19a_01 SH19A   
label values sh19a_02 SH19A   
label values sh19a_03 SH19A   
label values sh19a_04 SH19A   
label values sh19a_05 SH19A   
label values sh19a_06 SH19A   
label values sh19a_07 SH19A   
label values sh19a_08 SH19A   
label values sh19a_09 SH19A   
label values sh19a_10 SH19A   
label values sh19a_11 SH19A   
label values sh19a_12 SH19A   
label values sh19a_13 SH19A   
label values sh19a_14 SH19A   
label values sh19a_15 SH19A   
label values sh19a_16 SH19A   
label values sh19a_17 SH19A   
label values sh19a_18 SH19A   
label values sh19a_19 SH19A   
label values sh19a_20 SH19A   
label values sh19b_01 SH19B   
label values sh19b_02 SH19B   
label values sh19b_03 SH19B   
label values sh19b_04 SH19B   
label values sh19b_05 SH19B   
label values sh19b_06 SH19B   
label values sh19b_07 SH19B   
label values sh19b_08 SH19B   
label values sh19b_09 SH19B   
label values sh19b_10 SH19B   
label values sh19b_11 SH19B   
label values sh19b_12 SH19B   
label values sh19b_13 SH19B   
label values sh19b_14 SH19B   
label values sh19b_15 SH19B   
label values sh19b_16 SH19B   
label values sh19b_17 SH19B   
label values sh19b_18 SH19B   
label values sh19b_19 SH19B   
label values sh19b_20 SH19B   
label values sm07i_01 SM07I   
label values sm07i_02 SM07I   
label values sm07i_03 SM07I   
label values sm07i_04 SM07I   
label values sm07i_05 SM07I   
label values sm07i_06 SM07I   
label values sm07i_07 SM07I   
label values sm07i_08 SM07I   
label values sm07i_09 SM07I   
label values sm07i_10 SM07I   
label values sm07i_11 SM07I   
label values sm07i_12 SM07I   
label values sm07i_13 SM07I   
label values sm07i_14 SM07I   
label values sm07i_15 SM07I   
label values sm07i_16 SM07I   
label values sm07i_17 SM07I   
label values sm07i_18 SM07I   
label values sm07i_19 SM07I   
label values sm07i_20 SM07I   
label values sm07f_01 SM07F   
label values sm07f_02 SM07F   
label values sm07f_03 SM07F   
label values sm07f_04 SM07F   
label values sm07f_05 SM07F   
label values sm07f_06 SM07F   
label values sm07f_07 SM07F   
label values sm07f_08 SM07F   
label values sm07f_09 SM07F   
label values sm07f_10 SM07F   
label values sm07f_11 SM07F   
label values sm07f_12 SM07F   
label values sm07f_13 SM07F   
label values sm07f_14 SM07F   
label values sm07f_15 SM07F   
label values sm07f_16 SM07F   
label values sm07f_17 SM07F   
label values sm07f_18 SM07F   
label values sm07f_19 SM07F   
label values sm07f_20 SM07F   
label values smpreg_01 SMPREG  
label values smpreg_02 SMPREG  
label values smpreg_03 SMPREG  
label values smpreg_04 SMPREG  
label values smpreg_05 SMPREG  
label values smpreg_06 SMPREG  
label values smpreg_07 SMPREG  
label values smpreg_08 SMPREG  
label values smpreg_09 SMPREG  
label values smpreg_10 SMPREG  
label values smpreg_11 SMPREG  
label values smpreg_12 SMPREG  
label values smpreg_13 SMPREG  
label values smpreg_14 SMPREG  
label values smpreg_15 SMPREG  
label values smpreg_16 SMPREG  
label values smpreg_17 SMPREG  
label values smpreg_18 SMPREG  
label values smpreg_19 SMPREG  
label values smpreg_20 SMPREG  
label values sb103d_01 SB103D  
label values sb103d_02 SB103D  
label values sb103d_03 SB103D  
label values sb103d_04 SB103D  
label values sb103d_05 SB103D  
label values sb103d_06 SB103D  
label values sb103d_07 SB103D  
label values sb103d_08 SB103D  
label values sb103d_09 SB103D  
label values sb103d_10 SB103D  
label values sb103d_11 SB103D  
label values sb103d_12 SB103D  
label values sb103d_13 SB103D  
label values sb103d_14 SB103D  
label values sb103d_15 SB103D  
label values sb103d_16 SB103D  
label values sb103d_17 SB103D  
label values sb103d_18 SB103D  
label values sb103d_19 SB103D  
label values sb103d_20 SB103D  
label values sb103m_01 SB103M  
label values sb103m_02 SB103M  
label values sb103m_03 SB103M  
label values sb103m_04 SB103M  
label values sb103m_05 SB103M  
label values sb103m_06 SB103M  
label values sb103m_07 SB103M  
label values sb103m_08 SB103M  
label values sb103m_09 SB103M  
label values sb103m_10 SB103M  
label values sb103m_11 SB103M  
label values sb103m_12 SB103M  
label values sb103m_13 SB103M  
label values sb103m_14 SB103M  
label values sb103m_15 SB103M  
label values sb103m_16 SB103M  
label values sb103m_17 SB103M  
label values sb103m_18 SB103M  
label values sb103m_19 SB103M  
label values sb103m_20 SB103M  
label values ha2_1    HA2     
label values ha2_2    HA2     
label values ha2_3    HA2     
label values ha2_4    HA2     
label values ha2_5    HA2     
label values ha2_6    HA2     
label values ha2_7    HA2     
label values ha2_8    HA2     
label values ha2_9    HA2     
label values ha3_1    HA3     
label values ha3_2    HA3     
label values ha3_3    HA3     
label values ha3_4    HA3     
label values ha3_5    HA3     
label values ha3_6    HA3     
label values ha3_7    HA3     
label values ha3_8    HA3     
label values ha3_9    HA3     
label values ha4_1    HA4     
label values ha4_2    HA4     
label values ha4_3    HA4     
label values ha4_4    HA4     
label values ha4_5    HA4     
label values ha4_6    HA4     
label values ha4_7    HA4     
label values ha4_8    HA4     
label values ha4_9    HA4     
label values ha5_1    HA5     
label values ha5_2    HA5     
label values ha5_3    HA5     
label values ha5_4    HA5     
label values ha5_5    HA5     
label values ha5_6    HA5     
label values ha5_7    HA5     
label values ha5_8    HA5     
label values ha5_9    HA5     
label values ha6_1    HA6     
label values ha6_2    HA6     
label values ha6_3    HA6     
label values ha6_4    HA6     
label values ha6_5    HA6     
label values ha6_6    HA6     
label values ha6_7    HA6     
label values ha6_8    HA6     
label values ha6_9    HA6     
label values ha11_1   HA11    
label values ha11_2   HA11    
label values ha11_3   HA11    
label values ha11_4   HA11    
label values ha11_5   HA11    
label values ha11_6   HA11    
label values ha11_7   HA11    
label values ha11_8   HA11    
label values ha11_9   HA11    
label values ha12_1   HA12    
label values ha12_2   HA12    
label values ha12_3   HA12    
label values ha12_4   HA12    
label values ha12_5   HA12    
label values ha12_6   HA12    
label values ha12_7   HA12    
label values ha12_8   HA12    
label values ha12_9   HA12    
label values ha12a_1  HA12A   
label values ha12a_2  HA12A   
label values ha12a_3  HA12A   
label values ha12a_4  HA12A   
label values ha12a_5  HA12A   
label values ha12a_6  HA12A   
label values ha12a_7  HA12A   
label values ha12a_8  HA12A   
label values ha12a_9  HA12A   
label values ha12b_1  HA12B   
label values ha12b_2  HA12B   
label values ha12b_3  HA12B   
label values ha12b_4  HA12B   
label values ha12b_5  HA12B   
label values ha12b_6  HA12B   
label values ha12b_7  HA12B   
label values ha12b_8  HA12B   
label values ha12b_9  HA12B   
label values ha13_1   HA13    
label values ha13_2   HA13    
label values ha13_3   HA13    
label values ha13_4   HA13    
label values ha13_5   HA13    
label values ha13_6   HA13    
label values ha13_7   HA13    
label values ha13_8   HA13    
label values ha13_9   HA13    
label values ha33_1   HA33    
label values ha33_2   HA33    
label values ha33_3   HA33    
label values ha33_4   HA33    
label values ha33_5   HA33    
label values ha33_6   HA33    
label values ha33_7   HA33    
label values ha33_8   HA33    
label values ha33_9   HA33    
label values ha35_1   HA35    
label values ha35_2   HA35    
label values ha35_3   HA35    
label values ha35_4   HA35    
label values ha35_5   HA35    
label values ha35_6   HA35    
label values ha35_7   HA35    
label values ha35_8   HA35    
label values ha35_9   HA35    
label values ha40_1   HA40    
label values ha40_2   HA40    
label values ha40_3   HA40    
label values ha40_4   HA40    
label values ha40_5   HA40    
label values ha40_6   HA40    
label values ha40_7   HA40    
label values ha40_8   HA40    
label values ha40_9   HA40    
label values ha41_1   HA41    
label values ha41_2   HA41    
label values ha41_3   HA41    
label values ha41_4   HA41    
label values ha41_5   HA41    
label values ha41_6   HA41    
label values ha41_7   HA41    
label values ha41_8   HA41    
label values ha41_9   HA41    
label values ha50_1   HA50    
label values ha50_2   HA50    
label values ha50_3   HA50    
label values ha50_4   HA50    
label values ha50_5   HA50    
label values ha50_6   HA50    
label values ha50_7   HA50    
label values ha50_8   HA50    
label values ha50_9   HA50    
label values ha51_1   HA51    
label values ha51_2   HA51    
label values ha51_3   HA51    
label values ha51_4   HA51    
label values ha51_5   HA51    
label values ha51_6   HA51    
label values ha51_7   HA51    
label values ha51_8   HA51    
label values ha51_9   HA51    
label values ha52_1   HA52    
label values ha52_2   HA52    
label values ha52_3   HA52    
label values ha52_4   HA52    
label values ha52_5   HA52    
label values ha52_6   HA52    
label values ha52_7   HA52    
label values ha52_8   HA52    
label values ha52_9   HA52    
label values ha53_1   HA53    
label values ha53_2   HA53    
label values ha53_3   HA53    
label values ha53_4   HA53    
label values ha53_5   HA53    
label values ha53_6   HA53    
label values ha53_7   HA53    
label values ha53_8   HA53    
label values ha53_9   HA53    
label values ha54_1   HA54    
label values ha54_2   HA54    
label values ha54_3   HA54    
label values ha54_4   HA54    
label values ha54_5   HA54    
label values ha54_6   HA54    
label values ha54_7   HA54    
label values ha54_8   HA54    
label values ha54_9   HA54    
label values ha55_1   HA55    
label values ha55_2   HA55    
label values ha55_3   HA55    
label values ha55_4   HA55    
label values ha55_5   HA55    
label values ha55_6   HA55    
label values ha55_7   HA55    
label values ha55_8   HA55    
label values ha55_9   HA55    
label values ha56_1   HA56    
label values ha56_2   HA56    
label values ha56_3   HA56    
label values ha56_4   HA56    
label values ha56_5   HA56    
label values ha56_6   HA56    
label values ha56_7   HA56    
label values ha56_8   HA56    
label values ha56_9   HA56    
label values ha57_1   HA57    
label values ha57_2   HA57    
label values ha57_3   HA57    
label values ha57_4   HA57    
label values ha57_5   HA57    
label values ha57_6   HA57    
label values ha57_7   HA57    
label values ha57_8   HA57    
label values ha57_9   HA57    
label values ha58_1   HA58    
label values ha58_2   HA58    
label values ha58_3   HA58    
label values ha58_4   HA58    
label values ha58_5   HA58    
label values ha58_6   HA58    
label values ha58_7   HA58    
label values ha58_8   HA58    
label values ha58_9   HA58    
label values ha60_1   HA60    
label values ha60_2   HA60    
label values ha60_3   HA60    
label values ha60_4   HA60    
label values ha60_5   HA60    
label values ha60_6   HA60    
label values ha60_7   HA60    
label values ha60_8   HA60    
label values ha60_9   HA60    
label values ha61_1   HA61    
label values ha61_2   HA61    
label values ha61_3   HA61    
label values ha61_4   HA61    
label values ha61_5   HA61    
label values ha61_6   HA61    
label values ha61_7   HA61    
label values ha61_8   HA61    
label values ha61_9   HA61    
label values ha63_1   HA63    
label values ha63_2   HA63    
label values ha63_3   HA63    
label values ha63_4   HA63    
label values ha63_5   HA63    
label values ha63_6   HA63    
label values ha63_7   HA63    
label values ha63_8   HA63    
label values ha63_9   HA63    
label values ha64_1   HA64    
label values ha64_2   HA64    
label values ha64_3   HA64    
label values ha64_4   HA64    
label values ha64_5   HA64    
label values ha64_6   HA64    
label values ha64_7   HA64    
label values ha64_8   HA64    
label values ha64_9   HA64    
label values ha65_1   HA65    
label values ha65_2   HA65    
label values ha65_3   HA65    
label values ha65_4   HA65    
label values ha65_5   HA65    
label values ha65_6   HA65    
label values ha65_7   HA65    
label values ha65_8   HA65    
label values ha65_9   HA65    
label values ha66_1   HA66    
label values ha66_2   HA66    
label values ha66_3   HA66    
label values ha66_4   HA66    
label values ha66_5   HA66    
label values ha66_6   HA66    
label values ha66_7   HA66    
label values ha66_8   HA66    
label values ha66_9   HA66    
label values ha67_1   HA67    
label values ha67_2   HA67    
label values ha67_3   HA67    
label values ha67_4   HA67    
label values ha67_5   HA67    
label values ha67_6   HA67    
label values ha67_7   HA67    
label values ha67_8   HA67    
label values ha67_9   HA67    
label values ha68_1   HA68    
label values ha68_2   HA68    
label values ha68_3   HA68    
label values ha68_4   HA68    
label values ha68_5   HA68    
label values ha68_6   HA68    
label values ha68_7   HA68    
label values ha68_8   HA68    
label values ha68_9   HA68    
label values hc2_1    HC2     
label values hc2_2    HC2     
label values hc2_3    HC2     
label values hc2_4    HC2     
label values hc2_5    HC2     
label values hc2_6    HC2     
label values hc3_1    HC3     
label values hc3_2    HC3     
label values hc3_3    HC3     
label values hc3_4    HC3     
label values hc3_5    HC3     
label values hc3_6    HC3     
label values hc4_1    HC4     
label values hc4_2    HC4     
label values hc4_3    HC4     
label values hc4_4    HC4     
label values hc4_5    HC4     
label values hc4_6    HC4     
label values hc5_1    HC5     
label values hc5_2    HC5     
label values hc5_3    HC5     
label values hc5_4    HC5     
label values hc5_5    HC5     
label values hc5_6    HC5     
label values hc6_1    HC6     
label values hc6_2    HC6     
label values hc6_3    HC6     
label values hc6_4    HC6     
label values hc6_5    HC6     
label values hc6_6    HC6     
label values hc7_1    HC7     
label values hc7_2    HC7     
label values hc7_3    HC7     
label values hc7_4    HC7     
label values hc7_5    HC7     
label values hc7_6    HC7     
label values hc8_1    HC8     
label values hc8_2    HC8     
label values hc8_3    HC8     
label values hc8_4    HC8     
label values hc8_5    HC8     
label values hc8_6    HC8     
label values hc9_1    HC9     
label values hc9_2    HC9     
label values hc9_3    HC9     
label values hc9_4    HC9     
label values hc9_5    HC9     
label values hc9_6    HC9     
label values hc10_1   HC10    
label values hc10_2   HC10    
label values hc10_3   HC10    
label values hc10_4   HC10    
label values hc10_5   HC10    
label values hc10_6   HC10    
label values hc11_1   HC11    
label values hc11_2   HC11    
label values hc11_3   HC11    
label values hc11_4   HC11    
label values hc11_5   HC11    
label values hc11_6   HC11    
label values hc12_1   HC12    
label values hc12_2   HC12    
label values hc12_3   HC12    
label values hc12_4   HC12    
label values hc12_5   HC12    
label values hc12_6   HC12    
label values hc13_1   HC13    
label values hc13_2   HC13    
label values hc13_3   HC13    
label values hc13_4   HC13    
label values hc13_5   HC13    
label values hc13_6   HC13    
label values hc15_1   HC15    
label values hc15_2   HC15    
label values hc15_3   HC15    
label values hc15_4   HC15    
label values hc15_5   HC15    
label values hc15_6   HC15    
label values hc16_1   HC16    
label values hc16_2   HC16    
label values hc16_3   HC16    
label values hc16_4   HC16    
label values hc16_5   HC16    
label values hc16_6   HC16    
label values hc27_1   HC27    
label values hc27_2   HC27    
label values hc27_3   HC27    
label values hc27_4   HC27    
label values hc27_5   HC27    
label values hc27_6   HC27    
label values hc30_1   HC30    
label values hc30_2   HC30    
label values hc30_3   HC30    
label values hc30_4   HC30    
label values hc30_5   HC30    
label values hc30_6   HC30    
label values hc31_1   HC31    
label values hc31_2   HC31    
label values hc31_3   HC31    
label values hc31_4   HC31    
label values hc31_5   HC31    
label values hc31_6   HC31    
label values hc33_1   HC33    
label values hc33_2   HC33    
label values hc33_3   HC33    
label values hc33_4   HC33    
label values hc33_5   HC33    
label values hc33_6   HC33    
label values hc51_1   HC51    
label values hc51_2   HC51    
label values hc51_3   HC51    
label values hc51_4   HC51    
label values hc51_5   HC51    
label values hc51_6   HC51    
label values hc52_1   HC52    
label values hc52_2   HC52    
label values hc52_3   HC52    
label values hc52_4   HC52    
label values hc52_5   HC52    
label values hc52_6   HC52    
label values hc53_1   HC53    
label values hc53_2   HC53    
label values hc53_3   HC53    
label values hc53_4   HC53    
label values hc53_5   HC53    
label values hc53_6   HC53    
label values hc55_1   HC55    
label values hc55_2   HC55    
label values hc55_3   HC55    
label values hc55_4   HC55    
label values hc55_5   HC55    
label values hc55_6   HC55    
label values hc56_1   HC56    
label values hc56_2   HC56    
label values hc56_3   HC56    
label values hc56_4   HC56    
label values hc56_5   HC56    
label values hc56_6   HC56    
label values hc57_1   HC57    
label values hc57_2   HC57    
label values hc57_3   HC57    
label values hc57_4   HC57    
label values hc57_5   HC57    
label values hc57_6   HC57    
label values hc58_1   HC58    
label values hc58_2   HC58    
label values hc58_3   HC58    
label values hc58_4   HC58    
label values hc58_5   HC58    
label values hc58_6   HC58    
label values hc60_1   HC60    
label values hc60_2   HC60    
label values hc60_3   HC60    
label values hc60_4   HC60    
label values hc60_5   HC60    
label values hc60_6   HC60    
label values hc61_1   HC61    
label values hc61_2   HC61    
label values hc61_3   HC61    
label values hc61_4   HC61    
label values hc61_5   HC61    
label values hc61_6   HC61    
label values hc62_1   HC62    
label values hc62_2   HC62    
label values hc62_3   HC62    
label values hc62_4   HC62    
label values hc62_5   HC62    
label values hc62_6   HC62    
label values hc68_1   HC68    
label values hc68_2   HC68    
label values hc68_3   HC68    
label values hc68_4   HC68    
label values hc68_5   HC68    
label values hc68_6   HC68    
label values hc70_1   HC70    
label values hc70_2   HC70    
label values hc70_3   HC70    
label values hc70_4   HC70    
label values hc70_5   HC70    
label values hc70_6   HC70    
label values hc71_1   HC71    
label values hc71_2   HC71    
label values hc71_3   HC71    
label values hc71_4   HC71    
label values hc71_5   HC71    
label values hc71_6   HC71    
label values hc72_1   HC72    
label values hc72_2   HC72    
label values hc72_3   HC72    
label values hc72_4   HC72    
label values hc72_5   HC72    
label values hc72_6   HC72    
label values hc73_1   HC73    
label values hc73_2   HC73    
label values hc73_3   HC73    
label values hc73_4   HC73    
label values hc73_5   HC73    
label values hc73_6   HC73    
label values hb2_1    HB2     
label values hb2_2    HB2     
label values hb2_3    HB2     
label values hb2_4    HB2     
label values hb2_5    HB2     
label values hb2_6    HB2     
label values hb2_7    HB2     
label values hb2_8    HB2     
label values hb3_1    HB3     
label values hb3_2    HB3     
label values hb3_3    HB3     
label values hb3_4    HB3     
label values hb3_5    HB3     
label values hb3_6    HB3     
label values hb3_7    HB3     
label values hb3_8    HB3     
label values hb4_1    HB4     
label values hb4_2    HB4     
label values hb4_3    HB4     
label values hb4_4    HB4     
label values hb4_5    HB4     
label values hb4_6    HB4     
label values hb4_7    HB4     
label values hb4_8    HB4     
label values hb5_1    HB5     
label values hb5_2    HB5     
label values hb5_3    HB5     
label values hb5_4    HB5     
label values hb5_5    HB5     
label values hb5_6    HB5     
label values hb5_7    HB5     
label values hb5_8    HB5     
label values hb6_1    HB6     
label values hb6_2    HB6     
label values hb6_3    HB6     
label values hb6_4    HB6     
label values hb6_5    HB6     
label values hb6_6    HB6     
label values hb6_7    HB6     
label values hb6_8    HB6     
label values hb11_1   HB11    
label values hb11_2   HB11    
label values hb11_3   HB11    
label values hb11_4   HB11    
label values hb11_5   HB11    
label values hb11_6   HB11    
label values hb11_7   HB11    
label values hb11_8   HB11    
label values hb12_1   HB12    
label values hb12_2   HB12    
label values hb12_3   HB12    
label values hb12_4   HB12    
label values hb12_5   HB12    
label values hb12_6   HB12    
label values hb12_7   HB12    
label values hb12_8   HB12    
label values hb12a_1  HB12A   
label values hb12a_2  HB12A   
label values hb12a_3  HB12A   
label values hb12a_4  HB12A   
label values hb12a_5  HB12A   
label values hb12a_6  HB12A   
label values hb12a_7  HB12A   
label values hb12a_8  HB12A   
label values hb12b_1  HB12B   
label values hb12b_2  HB12B   
label values hb12b_3  HB12B   
label values hb12b_4  HB12B   
label values hb12b_5  HB12B   
label values hb12b_6  HB12B   
label values hb12b_7  HB12B   
label values hb12b_8  HB12B   
label values hb13_1   HB13    
label values hb13_2   HB13    
label values hb13_3   HB13    
label values hb13_4   HB13    
label values hb13_5   HB13    
label values hb13_6   HB13    
label values hb13_7   HB13    
label values hb13_8   HB13    
label values hb33_1   HB33    
label values hb33_2   HB33    
label values hb33_3   HB33    
label values hb33_4   HB33    
label values hb33_5   HB33    
label values hb33_6   HB33    
label values hb33_7   HB33    
label values hb33_8   HB33    
label values hb35_1   HB35    
label values hb35_2   HB35    
label values hb35_3   HB35    
label values hb35_4   HB35    
label values hb35_5   HB35    
label values hb35_6   HB35    
label values hb35_7   HB35    
label values hb35_8   HB35    
label values hb40_1   HB40    
label values hb40_2   HB40    
label values hb40_3   HB40    
label values hb40_4   HB40    
label values hb40_5   HB40    
label values hb40_6   HB40    
label values hb40_7   HB40    
label values hb40_8   HB40    
label values hb41_1   HB41    
label values hb41_2   HB41    
label values hb41_3   HB41    
label values hb41_4   HB41    
label values hb41_5   HB41    
label values hb41_6   HB41    
label values hb41_7   HB41    
label values hb41_8   HB41    
label values hb50_1   HB50    
label values hb50_2   HB50    
label values hb50_3   HB50    
label values hb50_4   HB50    
label values hb50_5   HB50    
label values hb50_6   HB50    
label values hb50_7   HB50    
label values hb50_8   HB50    
label values hb51_1   HB51    
label values hb51_2   HB51    
label values hb51_3   HB51    
label values hb51_4   HB51    
label values hb51_5   HB51    
label values hb51_6   HB51    
label values hb51_7   HB51    
label values hb51_8   HB51    
label values hb52_1   HB52    
label values hb52_2   HB52    
label values hb52_3   HB52    
label values hb52_4   HB52    
label values hb52_5   HB52    
label values hb52_6   HB52    
label values hb52_7   HB52    
label values hb52_8   HB52    
label values hb53_1   HB53    
label values hb53_2   HB53    
label values hb53_3   HB53    
label values hb53_4   HB53    
label values hb53_5   HB53    
label values hb53_6   HB53    
label values hb53_7   HB53    
label values hb53_8   HB53    
label values hb55_1   HB55    
label values hb55_2   HB55    
label values hb55_3   HB55    
label values hb55_4   HB55    
label values hb55_5   HB55    
label values hb55_6   HB55    
label values hb55_7   HB55    
label values hb55_8   HB55    
label values hb56_1   HB56    
label values hb56_2   HB56    
label values hb56_3   HB56    
label values hb56_4   HB56    
label values hb56_5   HB56    
label values hb56_6   HB56    
label values hb56_7   HB56    
label values hb56_8   HB56    
label values hb57_1   HB57    
label values hb57_2   HB57    
label values hb57_3   HB57    
label values hb57_4   HB57    
label values hb57_5   HB57    
label values hb57_6   HB57    
label values hb57_7   HB57    
label values hb57_8   HB57    
label values hb58_1   HB58    
label values hb58_2   HB58    
label values hb58_3   HB58    
label values hb58_4   HB58    
label values hb58_5   HB58    
label values hb58_6   HB58    
label values hb58_7   HB58    
label values hb58_8   HB58    
label values hb60_1   HB60    
label values hb60_2   HB60    
label values hb60_3   HB60    
label values hb60_4   HB60    
label values hb60_5   HB60    
label values hb60_6   HB60    
label values hb60_7   HB60    
label values hb60_8   HB60    
label values hb61_1   HB61    
label values hb61_2   HB61    
label values hb61_3   HB61    
label values hb61_4   HB61    
label values hb61_5   HB61    
label values hb61_6   HB61    
label values hb61_7   HB61    
label values hb61_8   HB61    
label values hb63_1   HB63    
label values hb63_2   HB63    
label values hb63_3   HB63    
label values hb63_4   HB63    
label values hb63_5   HB63    
label values hb63_6   HB63    
label values hb63_7   HB63    
label values hb63_8   HB63    
label values hb64_1   HB64    
label values hb64_2   HB64    
label values hb64_3   HB64    
label values hb64_4   HB64    
label values hb64_5   HB64    
label values hb64_6   HB64    
label values hb64_7   HB64    
label values hb64_8   HB64    
label values hb65_1   HB65    
label values hb65_2   HB65    
label values hb65_3   HB65    
label values hb65_4   HB65    
label values hb65_5   HB65    
label values hb65_6   HB65    
label values hb65_7   HB65    
label values hb65_8   HB65    
label values hb66_1   HB66    
label values hb66_2   HB66    
label values hb66_3   HB66    
label values hb66_4   HB66    
label values hb66_5   HB66    
label values hb66_6   HB66    
label values hb66_7   HB66    
label values hb66_8   HB66    
label values hb67_1   HB67    
label values hb67_2   HB67    
label values hb67_3   HB67    
label values hb67_4   HB67    
label values hb67_5   HB67    
label values hb67_6   HB67    
label values hb67_7   HB67    
label values hb67_8   HB67    
label values hb68_1   HB68    
label values hb68_2   HB68    
label values hb68_3   HB68    
label values hb68_4   HB68    
label values hb68_5   HB68    
label values hb68_6   HB68    
label values hb68_7   HB68    
label values hb68_8   HB68    
label values sh148_1  SH148   
label values sh148_2  SH148   
label values sh148_3  SH148   
label values sh148_4  SH148   
label values sh149_1  SH149   
label values sh149_2  SH149   
label values sh149_3  SH149   
label values sh149_4  SH149   
label values sh150_1  SH150   
label values sh150_2  SH150   
label values sh150_3  SH150   
label values sh150_4  SH150   
label values sh152_1  SH152   
label values sh152_2  SH152   
label values sh152_3  SH152   
label values sh152_4  SH152   
label values sh153_1  SH153   
label values sh153_2  SH153   
label values sh153_3  SH153   
label values sh153_4  SH153   
label values sh154_1  SH154   
label values sh154_2  SH154   
label values sh154_3  SH154   
label values sh154_4  SH154   
label values sh154a_1 SH154A  
label values sh154a_2 SH154A  
label values sh154a_3 SH154A  
label values sh154a_4 SH154A  
label values sh155_1  SH155   
label values sh155_2  SH155   
label values sh155_3  SH155   
label values sh155_4  SH155   
label values sh156_1  SH156   
label values sh156_2  SH156   
label values sh156_3  SH156   
label values sh156_4  SH156   
