infix using "C:\COUNTRIES\NG81\NGKR81FL.dct"

label variable caseid   "Case Identification"
label variable hidxa    "Index to birth history"
label variable v000     "Country code and phase"
label variable v001     "Cluster number"
label variable v002     "Household number"
label variable v003     "Respondent's line number"
label variable v004     "Ultimate area unit"
label variable v005     "Women's individual sample weight (6 decimals)"
label variable v006     "Month of interview"
label variable v007     "Year of interview"
label variable v008     "Date of interview (CMC)"
label variable v008a    "Date of interview Century Day Code (CDC)"
label variable v009     "Respondent's month of birth"
label variable v010     "Respondent's year of birth"
label variable v011     "Date of birth (CMC)"
label variable v012     "Respondent's current age"
label variable v013     "Age in 5-year groups"
label variable v014     "Completeness of age information"
label variable v015     "Result of individual interview"
label variable v016     "Day of interview"
label variable v021     "Primary sampling unit"
label variable v022     "Sample strata for sampling errors"
label variable v023     "Stratification used in sample design"
label variable v024     "Region"
label variable v025     "Type of place of residence"
label variable v026     "NA - De facto place of residence"
label variable v027     "Number of visits"
label variable v028     "Interviewer identification"
label variable v029     "NA - Keyer identification"
label variable v030     "Field supervisor"
label variable v031     "NA - Field editor"
label variable v032     "NA - Office editor"
label variable v034     "NA - Line number of husband"
label variable v040     "Cluster altitude in meters"
label variable v042     "Household selected for hemoglobin"
label variable v045a    "Language of questionnaire"
label variable v045b    "Language of interview"
label variable v045c    "Native language of respondent"
label variable v046     "Translator used"
label variable v047     "Team number"
label variable v101     "Region"
label variable v102     "Type of place of residence"
label variable v106     "Highest educational level"
label variable v107     "Highest year of education"
label variable v113     "Source of drinking water"
label variable v115     "Time to get to water source"
label variable v116     "Type of toilet facility"
label variable v119     "Household has: electricity"
label variable v120     "Household has: radio"
label variable v121     "Household has: television"
label variable v122     "Household has: refrigerator"
label variable v123     "Household has: bicycle"
label variable v124     "Household has: motorcycle/scooter"
label variable v125     "Household has: car/truck"
label variable v127     "Main floor material"
label variable v128     "Main wall material"
label variable v129     "Main roof material"
label variable v130     "Religion"
label variable v131     "Ethnicity"
label variable v133     "Education in single years"
label variable v134     "NA - De facto place of residence"
label variable v135     "Usual resident or visitor"
label variable v136     "Number of household members (listed)"
label variable v137     "Number of children 5 and under in household (de jure)"
label variable v138     "Number of eligible women in household (de facto)"
label variable v139     "De jure region of residence"
label variable v140     "De jure type of place of residence"
label variable v141     "NA - De jure place of residence"
label variable v149     "Educational attainment"
label variable v150     "Relationship to household head"
label variable v151     "Sex of household head"
label variable v152     "Age of household head"
label variable v153     "Household has: telephone (land-line)"
label variable v155     "Literacy"
label variable v156     "NA - Ever participated in a literacy program outside of primary"
label variable v157     "Frequency of reading newspaper or magazine"
label variable v158     "Frequency of listening to radio"
label variable v159     "Frequency of watching television"
label variable v160     "Toilet facilities shared with other households"
label variable v161     "Type of cooking fuel"
label variable v169a    "Owns a mobile telephone"
label variable v169c    "Is respondent's mobile phone a smart phone"
label variable v171a    "Use of internet"
label variable v171b    "Frequency of using internet last month"
label variable v190     "Wealth index combined"
label variable v191     "Wealth index factor score combined (5 decimals)"
label variable v190a    "Wealth index for urban/rural"
label variable v191a    "Wealth index factor score for urban/rural (5 decimals)"
label variable ml101    "Type of mosquito bed net(s) slept under last night"
label variable v417     "Entries in pregnancy and postnatal care roster"
label variable v418a    "Entries in child health roster"
label variable v419     "Entries in height/weight roster"
label variable v459     "Have mosquito bed net for sleeping (from household questionnaire)"
label variable v460     "Children under 5 slept under mosquito bed net last night (household questionnair"
label variable v461     "Respondent slept under mosquito bed net"
label variable v468     "Record for Last Birth"
label variable bidx     "Birth column number"
label variable bord     "Birth order number"
label variable b0       "Child is twin"
label variable b1       "Month of birth"
label variable b2       "Year of birth"
label variable b3       "Date of birth (CMC)"
label variable b4       "Sex of child"
label variable b5       "Child is alive"
label variable b6       "NA - Age at death"
label variable b7       "NA - Age at death (months, imputed)"
label variable b8       "Current age of child"
label variable b9       "Child lives with whom"
label variable b10      "Completeness of information"
label variable b11      "Preceding birth interval (months)"
label variable b12      "Succeeding birth interval (months)"
label variable b13      "NA - Flag for age at death"
label variable b15      "Live birth between births"
label variable b16      "Child's line number in household"
label variable b17      "Day of birth"
label variable b18      "Century Day Code of birth (CDC)"
label variable b19      "Current age of child in months (months since birth for dead children)"
label variable v201     "Total children ever born"
label variable v202     "Sons at home"
label variable v203     "Daughters at home"
label variable v204     "Sons elsewhere"
label variable v205     "Daughters elsewhere"
label variable v206     "Sons who have died"
label variable v207     "Daughters who have died"
label variable v208     "Births in last five years"
label variable v209     "Births in past year"
label variable v210     "Births in month of interview"
label variable v213     "Currently pregnant"
label variable v214     "Duration of current pregnancy in months"
label variable v214a    "Duration of current pregnancy original"
label variable v218     "Number of living children"
label variable v219     "Living children + current pregnancy"
label variable v220     "Living children + current pregnancy (grouped)"
label variable v222     "Last birth to interview (months)"
label variable v223     "Completeness of current pregnancy information"
label variable v224     "Entries in birth history"
label variable v237     "Birth between last and interview"
label variable v238     "Births in last three years"
label variable midx     "Index to Birth History"
label variable m2a      "Prenatal: doctor"
label variable m2b      "Prenatal: nurse/midwife"
label variable m2c      "Prenatal: auxiliary midwife"
label variable m2d      "Prenatal: government health community extension health worker"
label variable m2e      "NA - Prenatal: CS health professional"
label variable m2f      "NA - Prenatal: CS health professional"
label variable m2g      "Prenatal: traditional birth attendant"
label variable m2h      "Prenatal: Community health worker/field worker"
label variable m2i      "NA - Prenatal: CS other person"
label variable m2j      "NA - Prenatal: CS other person"
label variable m2k      "Prenatal: other"
label variable m2l      "NA - Prenatal: CS other"
label variable m2m      "NA - Prenatal: CS other"
label variable m2n      "Prenatal: no one"
label variable m13      "Timing of 1st antenatal check (months)"
label variable m13a     "Timing of 1st antenatal check (original)"
label variable m14      "Number of antenatal visits during pregnancy"
label variable m49a     "During pregnancy took: SP/fansidar for malaria"
label variable m49b     "NA - During pregnancy took: chloroquine for malaria"
label variable m49c     "NA - During pregnancy took: CS drug for malaria"
label variable m49d     "NA - During pregnancy took: CS drug for malaria"
label variable m49e     "NA - During pregnancy took: CS drug for malaria"
label variable m49f     "NA - During pregnancy took: CS drug for malaria"
label variable m49g     "NA - During pregnancy took: CS drug for malaria"
label variable m49x     "NA - During pregnancy took: other drug for malaria"
label variable m49z     "NA - During pregnancy took: don't know"
label variable m49y     "NA - During pregnancy took: no drug for malaria"
label variable m57a     "Antenatal care: respondent's home"
label variable m57b     "Antenatal care: other home"
label variable m57c     "NA - Antenatal care: CS home"
label variable m57d     "NA - Antenatal care: CS home"
label variable m57e     "Antenatal care: government hospital"
label variable m57f     "Antenatal care: government health center"
label variable m57g     "Antenatal care: government health post"
label variable m57h     "Antenatal care: other public sector"
label variable m57i     "NA - Antenatal care: CS public health"
label variable m57j     "NA - Antenatal care: CS public health"
label variable m57k     "NA - Antenatal care: CS public health"
label variable m57l     "NA - Antenatal care: CS public health"
label variable m57m     "Antenatal care: private hospital"
label variable m57n     "Antenatal care: private clinic"
label variable m57o     "Antenatal care: other private medical sector"
label variable m57p     "NA - Antenatal care: CS private medical"
label variable m57q     "NA - Antenatal care: CS private medical"
label variable m57r     "NA - Antenatal care: CS private medical"
label variable m57na    "Antenatal care: NGO hospital"
label variable m57nb    "Antenatal care: NGO clinic"
label variable m57nc    "Antenatal care: other NGO medical sector"
label variable m57nd    "NA - Antenatal care: NGO medical"
label variable m57ne    "NA - Antenatal care: NGO medical"
label variable m57s     "NA - Antenatal care: CS other"
label variable m57t     "NA - Antenatal care: CS other"
label variable m57u     "NA - Antenatal care: CS other"
label variable m57v     "NA - Antenatal care: CS other"
label variable m57x     "Antenatal care: other"
label variable ml1      "Number of times took fansidar during pregnancy"
label variable ml2      "Source of antimalarial during pregnancy"
label variable h22      "Had fever in last two weeks"
label variable h31      "NA - Had cough in last two weeks"
label variable h32a     "Fever/cough: government hospital"
label variable h32b     "Fever/cough: government health center"
label variable h32c     "Fever/cough: government health post"
label variable h32d     "Fever/cough: government mobile clinic"
label variable h32e     "Fever/cough: government community health worker/fieldworker"
label variable h32f     "Fever/cough: other public sector"
label variable h32g     "NA - Fever/cough: CS public sector"
label variable h32h     "NA - Fever/cough: CS public sector"
label variable h32i     "NA - Fever/cough: CS public sector"
label variable h32j     "Fever/cough: private hospital"
label variable h32k     "Fever/cough: private pharmacy"
label variable h32l     "Fever/cough: private doctor"
label variable h32m     "Fever/cough: private clinic"
label variable h32n     "Fever/cough: private mobile clinic"
label variable h32o     "Fever/cough: private community health worker/fieldworker"
label variable h32p     "Fever/cough: other private medical sector"
label variable h32q     "NA - Fever/cough: CS private medical"
label variable h32r     "NA - Fever/cough: CS private medical"
label variable h32na    "Fever/cough: NGO hospital"
label variable h32nb    "Fever/cough: NGO clinic"
label variable h32nc    "Fever/cough: other NGO sector"
label variable h32nd    "NA - Fever/cough: CS NGO"
label variable h32ne    "NA - Fever/cough: CS NGO"
label variable h32s     "Fever/cough: chemist shop/PPMV"
label variable h32t     "Fever/cough: traditional practitioner"
label variable h32u     "Fever/cough: market"
label variable h32v     "Fever/cough: itinerant drug seller"
label variable h32w     "Fever/cough: community-oriented resource person"
label variable h32x     "Fever/cough: other"
label variable h32y     "Fever/cough: no treatment"
label variable h32z     "Fever/cough: medical treatment"
label variable h46a     "Place first sought treatment for fever"
label variable h46b     "Number of days after fever began sought advice or treatment"
label variable h47      "Blood taken from child's finger/heel for testing"
label variable h71      "Was respondent told that child had malaria"
label variable hwidx    "Index to Birth History"
label variable hw1      "Child's age in months"
label variable hw16     "Day of birth of child"
label variable hw17     "Date measured (day)"
label variable hw18     "Date measured (month)"
label variable hw19     "Date measured (year)"
label variable hw51     "Line number of parent/caretaker"
label variable hw52     "Read consent statement - hemoglobin"
label variable hw53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hw55     "Result of measurement - hemoglobin"
label variable hw56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hw57     "Anemia level"
label variable hw58     "NA - Agrees to referral - anemia"
label variable idxml    "Index to Birth History"
label variable ml0      "Type of mosquito bed net(s) child slept under last night"
label variable ml11     "NA - Child has fever/cough now"
label variable ml12     "NA - Child has had convulsions in last 2 weeks"
label variable ml13a    "Fansidar taken for fever"
label variable ml13b    "Chloroquine taken for fever"
label variable ml13c    "Amodiaquine taken for fever"
label variable ml13d    "Quinine taken for fever"
label variable ml13da   "Quinine injection/IV taken for fever"
label variable ml13e    "Combination with artemisinin taken for fever"
label variable ml13aa   "Artesunate rectal taken for fever"
label variable ml13ab   "Artesunate injection/IV taken for fever"
label variable ml13f    "NA - CS antimalarial taken for fever"
label variable ml13g    "NA - CS antimalarial taken for fever"
label variable ml13h    "Other antimalarial taken for fever"
label variable ml13i    "Antibiotic pill/syrup taken for fever"
label variable ml13j    "Antibiotic injection taken for fever"
label variable ml13k    "Aspirin taken for fever"
label variable ml13l    "Acetaminophen/paracetamol/panadol taken for fever"
label variable ml13m    "Ibuprofen taken for fever"
label variable ml13n    "Amoxicillin taken for fever"
label variable ml13o    "Cotrimoxazole taken for fever"
label variable ml13p    "NA - CS other taken for fever"
label variable ml13x    "Other taken for fever"
label variable ml13y    "Nothing taken and didn't seek treatment for fever/cough"
label variable ml13z    "Don't know if or what was taken for fever"
label variable ml14a    "NA - Injection given for fever/convulsion"
label variable ml14b    "NA - Suppository given for fever/convulsion"
label variable ml14y    "NA - No suppository or injection given for fever/convulsion"
label variable ml14z    "NA - Don't know if suppository or injection given for fever/convulsion"
label variable ml15a    "NA - Timing of start of fansidar"
label variable ml15b    "NA - Number of days child took fansidar"
label variable ml15c    "NA - First source for fansidar"
label variable ml16a    "NA - Timing of start of chloroquine"
label variable ml16b    "NA - Number of days child took chloroquine"
label variable ml16c    "NA - First source for chloroquine"
label variable ml17a    "NA - Timing of start of amodiaquine"
label variable ml17b    "NA - Number of days child took amodiaquine"
label variable ml17c    "NA - First source for amodiaquine"
label variable ml18a    "NA - Timing of start of quinine"
label variable ml18b    "NA - Number of days child took quinine"
label variable ml18c    "NA - First source for quinine"
label variable ml19a    "NA - For fever/convulsion: consulted traditional healer"
label variable ml19b    "NA - For fever/convulsion: gave tepid sponging"
label variable ml19c    "NA - For fever/convulsion: gave herbs"
label variable ml19d    "NA - For fever/convulsion: CS"
label variable ml19e    "NA - For fever/convulsion: CS"
label variable ml19f    "NA - For fever/convulsion: CS"
label variable ml19x    "NA - For fever/convulsion: other"
label variable ml19y    "NA - For fever/convulsion: gave/did nothing"
label variable ml19z    "NA - For fever/convulsion: don't know if something else was done"
label variable ml20a    "Timing of start of combination with artemisinin"
label variable ml20b    "NA - Number of days child took combination with artemisinin"
label variable ml20c    "NA - First source for combination with artemisinin"
label variable ml21a    "NA - Timing of start of CS antimalarial use"
label variable ml21b    "NA - Number of days child took CS antimalarial"
label variable ml21c    "NA - First source for CS antimalarial"
label variable ml22a    "NA - Timing of start of CS antimalarial use"
label variable ml22b    "NA - Number of days child took CS antimalarial"
label variable ml22c    "NA - First source for CS antimalarial"
label variable ml23a    "NA - Timing of start of other anti-malarial use"
label variable ml23b    "NA - Number of days child took other anti-malarial"
label variable ml23c    "NA - First source for other anti-malarial"
label variable ml24c    "NA - First source for antibiotic pill/syrup"
label variable ml25a    "NA - Timing of start of artesunate"
label variable ml501    "Last six months heard/seen malaria messages"
label variable ml501a   "Malaria messages were heard/seen: radio"
label variable ml501b   "Malaria messages were heard/seen: television"
label variable ml501c   "Malaria messages were heard/seen: poster/billboard"
label variable ml501d   "Malaria messages were heard/seen: newspaper/magazine"
label variable ml501e   "Malaria messages were heard/seen: leaflet/brochure"
label variable ml501f   "Malaria messages were heard/seen: healthcare provider"
label variable ml501g   "Malaria messages were heard/seen: community health worker"
label variable ml501h   "Malaria messages were heard/seen: social media"
label variable ml501i   "Malaria messages were heard/seen: town announcer"
label variable ml501j   "Malaria messages were heard/seen: inter-personal communication agent/community v"
label variable ml501k   "Malaria messages were heard/seen: family/friends"
label variable ml501x   "Malaria messages were heard/seen: other"
label variable ml501z   "Malaria messages were heard/seen: don't remember"
label variable ml503    "Are there ways to avoid getting malaria"
label variable ml503a   "Malaria can be prevented by: sleep inside a mosquito net"
label variable ml503b   "Malaria can be prevented by: sleep inside an insecticide-treated mosquito net"
label variable ml503c   "Malaria can be prevented by: use mosquito repellent or coil"
label variable ml503d   "Malaria can be prevented by: take preventive medications"
label variable ml503e   "Malaria can be prevented by: spray house with insecticide"
label variable ml503f   "Malaria can be prevented by: fill in stagnant waters (puddles)"
label variable ml503g   "Malaria can be prevented by: keep surroundings clean"
label variable ml503h   "Malaria can be prevented by: put mosquito screen on windows"
label variable ml503i   "NA - Malaria can be prevented by: CS"
label variable ml503j   "NA - Malaria can be prevented by: CS"
label variable ml503k   "NA - Malaria can be prevented by: CS"
label variable ml503x   "Malaria can be prevented by: other"
label variable ml503z   "Malaria can be prevented by: don't know"
label variable ml505    "Agree/disagree with: people in community get malaria in rainy season"
label variable ml506    "Agree/disagree with: when child has fever worry it is malaria"
label variable ml507    "Agree/disagree with: getting malaria not a problem as can be treated"
label variable ml508    "Agree/disagree with: only weak children can die from malaria"
label variable ml509    "Agree/disagree with: sleep inside net when there are lots of mosquitoes"
label variable ml510    "Agree/disagree with: sleep inside net when there are few mosquitoes"
label variable ml511    "Agree/disagree with: don't like sleep inside a net when is too warm"
label variable ml512    "Agree/disagree with: if child has fever best to give medicine available at home"
label variable ml513    "Agree/disagree with: people take children to health provider same day or next da"
label variable ml514    "Agree/disagree with: people who have nets usually sleep under every night"
label variable s512a    "Agree/disagree with: important children take full dose of medicine they are pres"
label variable slga     "Local government area"
label variable sregion  "Region"
label variable sbonny   "Bonny State"
label variable s104a    "Had informal education"
label variable s104b    "Type of informal education"
label variable s211     "Number of births 2016-2021"
label variable idx95    "Index to Birth History"
label variable s411a    "Referred to higher level of care"
label variable s415a    "Fever went away after took ACT"

#delimit ;
label define V013    
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define V014    
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define V015    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partially completed"
     6 "Respondent incapacitated"
     7 "Other"
;
label define V022    
     1 "Abia_Urban"
     2 "Abia_Rural"
     3 "Adamawa_Urban"
     4 "Adamawa_Rural"
     5 "Akwa Ibom_Urban"
     6 "Akwa Ibom_Rural"
     7 "Anambra_Urban"
     8 "Anambra_Rural"
     9 "Bauchi_Urban"
    10 "Bauchi_Rural"
    11 "Bayelsa_Urban"
    12 "Bayelsa_Rural"
    13 "Benue_Urban"
    14 "Benue_Rural"
    15 "Borno_Urban"
    16 "Borno_Rural"
    17 "Cross River_Urban"
    18 "Cross River_Rural"
    19 "Delta_Urban"
    20 "Delta_Rural"
    21 "Ebonyi_Urban"
    22 "Ebonyi_Rural"
    23 "Edo_Urban"
    24 "Edo_Rural"
    25 "Ekiti_Urban"
    26 "Ekiti_Rural"
    27 "Enugu_Urban"
    28 "Enugu_Rural"
    29 "Fct_Urban"
    30 "Fct_Rural"
    31 "Gombe_Urban"
    32 "Gombe_Rural"
    33 "Imo_Urban"
    34 "Imo_Rural"
    35 "Jigawa_Urban"
    36 "Jigawa_Rural"
    37 "Kaduna_Urban"
    38 "Kaduna_Rural"
    39 "Kano_Urban"
    40 "Kano_Rural"
    41 "Katsina_Urban"
    42 "Katsina_Rural"
    43 "Kebbi_Urban"
    44 "Kebbi_Rural"
    45 "Kogi_Urban"
    46 "Kogi_Rural"
    47 "Kwara_Urban"
    48 "Kwara_Rural"
    49 "Lagos_Urban"
    50 "Lagos_Rural"
    51 "Nasarawa_Urban"
    52 "Nasarawa_Rural"
    53 "Niger_Urban"
    54 "Niger_Rural"
    55 "Ogun_Urban"
    56 "Ogun_Rural"
    57 "Ondo_Urban"
    58 "Ondo_Rural"
    59 "Osun_Urban"
    60 "Osun_Rural"
    61 "Oyo_Urban"
    62 "Oyo_Rural"
    63 "Plateau_Urban"
    64 "Plateau_Rural"
    65 "Rivers_Urban"
    66 "Rivers_Urban"
    67 "Rivers_Rural"
    68 "Rivers_Rural"
    69 "Sokoto_Urban"
    70 "Sokoto_Rural"
    71 "Taraba_Urban"
    72 "Taraba_Rural"
    73 "Yobe_Urban"
    74 "Yobe_Rural"
    75 "Zamfara_Urban"
    76 "Zamfara_Rural"
;
label define V023    
     1 "Abia_Urban"
     2 "Abia_Rural"
     3 "Adamawa_Urban"
     4 "Adamawa_Rural"
     5 "Akwa Ibom_Urban"
     6 "Akwa Ibom_Rural"
     7 "Anambra_Urban"
     8 "Anambra_Rural"
     9 "Bauchi_Urban"
    10 "Bauchi_Rural"
    11 "Bayelsa_Urban"
    12 "Bayelsa_Rural"
    13 "Benue_Urban"
    14 "Benue_Rural"
    15 "Borno_Urban"
    16 "Borno_Rural"
    17 "Cross River_Urban"
    18 "Cross River_Rural"
    19 "Delta_Urban"
    20 "Delta_Rural"
    21 "Ebonyi_Urban"
    22 "Ebonyi_Rural"
    23 "Edo_Urban"
    24 "Edo_Rural"
    25 "Ekiti_Urban"
    26 "Ekiti_Rural"
    27 "Enugu_Urban"
    28 "Enugu_Rural"
    29 "Fct_Urban"
    30 "Fct_Rural"
    31 "Gombe_Urban"
    32 "Gombe_Rural"
    33 "Imo_Urban"
    34 "Imo_Rural"
    35 "Jigawa_Urban"
    36 "Jigawa_Rural"
    37 "Kaduna_Urban"
    38 "Kaduna_Rural"
    39 "Kano_Urban"
    40 "Kano_Rural"
    41 "Katsina_Urban"
    42 "Katsina_Rural"
    43 "Kebbi_Urban"
    44 "Kebbi_Rural"
    45 "Kogi_Urban"
    46 "Kogi_Rural"
    47 "Kwara_Urban"
    48 "Kwara_Rural"
    49 "Lagos_Urban"
    50 "Lagos_Rural"
    51 "Nasarawa_Urban"
    52 "Nasarawa_Rural"
    53 "Niger_Urban"
    54 "Niger_Rural"
    55 "Ogun_Urban"
    56 "Ogun_Rural"
    57 "Ondo_Urban"
    58 "Ondo_Rural"
    59 "Osun_Urban"
    60 "Osun_Rural"
    61 "Oyo_Urban"
    62 "Oyo_Rural"
    63 "Plateau_Urban"
    64 "Plateau_Rural"
    65 "Rivers_Urban"
    66 "Rivers_Urban"
    67 "Rivers_Rural"
    68 "Rivers_Rural"
    69 "Sokoto_Urban"
    70 "Sokoto_Rural"
    71 "Taraba_Urban"
    72 "Taraba_Rural"
    73 "Yobe_Urban"
    74 "Yobe_Rural"
    75 "Zamfara_Urban"
    76 "Zamfara_Rural"
;
label define V024    
     1 "Sokoto"
     2 "Zamfara"
     3 "Katsina"
     4 "Jigawa"
     5 "Yobe"
     6 "Borno"
     7 "Adamawa"
     8 "Gombe"
     9 "Bauchi"
    10 "Kano"
    11 "Kaduna"
    12 "Kebbi"
    13 "Niger"
    14 "FCT"
    15 "Nasarawa"
    16 "Plateau"
    17 "Taraba"
    18 "Benue"
    19 "Kogi"
    20 "Kwara"
    21 "Oyo"
    22 "Osun"
    23 "Ekiti"
    24 "Ondo"
    25 "Edo"
    26 "Anambra"
    27 "Enugu"
    28 "Ebonyi"
    29 "Cross River"
    30 "Akwa Ibom"
    31 "Abia"
    32 "Imo"
    33 "Rivers"
    34 "Bayelsa"
    35 "Delta"
    36 "Lagos"
    37 "Ogun"
;
label define V025    
     1 "Urban"
     2 "Rural"
;
label define V026    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V027    
     9 "Missing"
;
label define V029    
   999 "Missing"
;
label define V034    
     0 "Husband not in household"
;
label define V040    
  9999 "Missing"
;
label define V042    
     0 "Not selected"
     1 "Selected"
;
label define V045A   
     1 "English"
     2 "Hausa"
     3 "Yoruba"
     4 "Igbo"
;
label define V045B   
     1 "English"
     2 "Hausa"
     3 "Yoruba"
     4 "Igbo"
     5 "Fulfulde"
     6 "Other"
;
label define V045C   
     1 "English"
     2 "Hausa"
     3 "Yoruba"
     4 "Igbo"
     5 "Fulfulde"
     6 "Other"
;
label define V046    
     0 "No"
     1 "Yes"
;
label define V101    
     1 "Sokoto"
     2 "Zamfara"
     3 "Katsina"
     4 "Jigawa"
     5 "Yobe"
     6 "Borno"
     7 "Adamawa"
     8 "Gombe"
     9 "Bauchi"
    10 "Kano"
    11 "Kaduna"
    12 "Kebbi"
    13 "Niger"
    14 "FCT"
    15 "Nasarawa"
    16 "Plateau"
    17 "Taraba"
    18 "Benue"
    19 "Kogi"
    20 "Kwara"
    21 "Oyo"
    22 "Osun"
    23 "Ekiti"
    24 "Ondo"
    25 "Edo"
    26 "Anambra"
    27 "Enugu"
    28 "Ebonyi"
    29 "Cross River"
    30 "Akwa Ibom"
    31 "Abia"
    32 "Imo"
    33 "Rivers"
    34 "Bayelsa"
    35 "Delta"
    36 "Lagos"
    37 "Ogun"
;
label define V102    
     1 "Urban"
     2 "Rural"
;
label define V106    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define V107    
     0 "No years completed at level V106"
;
label define V113    
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    72 "Sachet water"
    96 "Other"
    97 "Not a dejure resident"
;
label define V115    
   996 "On premises"
   997 "Not a dejure resident"
   998 "Don't know"
;
label define V116    
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
    97 "Not a dejure resident"
;
label define V119    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V120    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V121    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V122    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V123    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V124    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V125    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V127    
    10 "NATURAL"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
    97 "Not a dejure resident"
;
label define V128    
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Dirt"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
    97 "Not a dejure resident"
;
label define V129    
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Grass"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Metal/Zinc"
    32 "Wood"
    33 "Calamine/cement fiber"
    34 "Ceramic tiles"
    35 "Cement"
    36 "Roofing shingles"
    37 "Asbestos"
    96 "Other"
    97 "Not a dejure resident"
;
label define V130    
     1 "Catholic"
     2 "Other Christian"
     3 "Islam"
     4 "Traditionalist"
    96 "Other"
;
label define V131    
     1 "Abua"
     2 "Adra/Adarawa"
     3 "Adun"
     4 "Afcabeya"
     5 "Afemai"
     6 "Afizire"
     7 "Agatu"
     8 "Agbassa"
     9 "Agbor"
    10 "Afo"
    11 "Ajowa"
    12 "Akpa"
    13 "Akwai"
    14 "Akye"
    15 "Alago"
    16 "Amamong"
    17 "Amo"
    18 "Ana"
    19 "Anaguta"
    20 "Ankwai"
    21 "Annang"
    22 "Arab"
    23 "Arabo"
    24 "Arbar"
    25 "Arugu"
    26 "Aten/Atam"
    27 "Attakar"
    28 "Auchi"
    29 "Aulliminden"
    30 "Awo"
    31 "Ayetoro Gbede"
    32 "Badarare"
    33 "Bade/Badawe"
    34 "Bafeke"
    35 "Bagathiya"
    36 "Baggara"
    37 "Bagunge/Badagire"
    38 "Bahnake"
    39 "Baji/Biji"
    40 "Bajju"
    41 "Bambaro"
    42 "Bambuka"
    43 "Bandawa"
    44 "Banguji"
    45 "Bankalawa"
    46 "Bchama"
    47 "Barabaci"
    48 "Barawa"
    49 "Bargawa"
    50 "Bassa"
    51 "Bekworas"
    53 "Berom"
    54 "Bini/Edo"
    55 "Bogom"
    56 "Boiyawa/Bozaya"
    57 "Bolawa/Bolewa"
    59 "Buduma"
    60 "Buko"
    61 "Bura/Babur"
    62 "Buzu"
    63 "Byazhi"
    64 "Calabar"
    65 "Chala"
    66 "Chamba"
    67 "Chiba"
    68 "Chibok(g)"
    69 "Chip"
    70 "Dadiya"
    71 "Badakare/Dakarkari"
    72 "Dakka/Doka"
    73 "Dangula"
    74 "Daurawa/Dagarawa"
    75 "Defaka"
    76 "Degima"
    77 "Delta Ibo"
    78 "Dibo"
    79 "Diguza"
    80 "Djerma"
    81 "Dmoko"
    82 "Dolchi"
    83 "Ebira/Igbira"
    84 "Ebu"
    85 "Efik"
    86 "Egba"
    87 "Egbado"
    88 "Eggon"
    89 "Egun"
    90 "Eket"
    91 "Ekoi"
    92 "Ekpeye/Afisa/Epie"
    94 "Ekulu"
    95 "Eleme"
    96 "Emu"
    97 "Esan"
    98 "Etina"
    99 "Etsako"
   100 "Etulo"
   101 "Hadejawa"
   102 "Fanso"
   103 "Femawa"
   104 "Fer"
   105 "Filiya/Fali"
   106 "Fon"
   107 "Foron"
   108 "French"
   109 "Fulani"
   110 "Gamaku"
   111 "Gamaru"
   112 "Gamuni"
   113 "Gana Gana"
   114 "Ganawuri"
   115 "Gbaju/Gbagi"
   116 "Gede/Gude/Gai"
   117 "Gerawa"
   118 "Gizmawa"
   119 "Glauda"
   120 "Gmenchi"
   121 "Gomo/Gamoyaya"
   122 "Gobiri/Gobirawa/Bogobiri"
   123 "Gujjurawa"
   124 "Guemai"
   125 "Gumbarawa"
   126 "Gunganchi"
   127 "Gwandara"
   128 "Gwantu"
   129 "Hankwe"
   130 "Hausa"
   131 "Higgi"
   132 "Ibariba"
   133 "Ibibio"
   134 "Ichen"
   135 "Idanre"
   136 "Idoma"
   137 "Igala"
   138 "Igbo/Ibo"
   139 "Igede"
   140 "Ijaw/Izon"
   141 "Ijede"
   142 "Ijeme"
   143 "Ika"
   144 "Ikajo"
   145 "Ikara"
   146 "Ikpeshi"
   147 "Ikpide"
   148 "Ikulu"
   149 "Ikwere"
   150 "Ilaje"
   151 "Irigwe"
   152 "Ishan"
   153 "Isoko"
   154 "Itsekiri"
   155 "Jaba"
   156 "Jajiri"
   157 "Jakatoe"
   158 "Jaku"
   159 "Jara"
   160 "Jarawa"
   162 "Jibu"
   163 "Jonjo"
   164 "Jukun"
   165 "Kabawa"
   166 "Kadara"
   167 "Kagoma"
   168 "Kagoro"
   169 "Kaka"
   170 "Kakanda"
   171 "Kamantam"
   172 "Kambari"
   173 "Kambu/Kangu"
   174 "Kamuku"
   175 "Kanakuru"
   176 "Kanawa"
   177 "Kaninko"
   178 "Kantanawa"
   179 "Kanuri/Beriberi"
   180 "Manga"
   181 "Karekare"
   182 "Kataf/Atyap"
   183 "Kento"
   184 "Kibaku"
   185 "Kilba"
   186 "Kirdi"
   187 "Kodki"
   188 "Kofyar"
   189 "Kona"
   190 "Koro"
   191 "Koto"
   192 "Kuenuem"
   193 "Kumbo"
   194 "Kunkawa/Kawa"
   195 "Kurama"
   196 "Kuteb"
   197 "Kuturm"
   198 "Kwale/Ukwuani"
   199 "Kwanzo"
   200 "Lagelu"
   201 "Lantang"
   202 "Lemoro"
   203 "Loh"
   204 "Lunguda"
   205 "Maba/Mbadowa"
   206 "Mada"
   207 "Mafa/Maka/Maga"
   208 "Mambila"
   209 "Mandara"
   210 "Mangus/Manju"
   211 "Marghi/mangi"
   212 "Mbwa"
   213 "Mingo"
   214 "Mirnang"
   215 "Montor"
   216 "Mtchiga/Michika"
   217 "Mumuye"
   218 "Munga"
   219 "Mupung"
   220 "Mushere"
   221 "Mwagavol"
   222 "Naiawum"
   223 "Namoen"
   224 "Ndokwa"
   225 "Ndola"
   226 "Ngamo"
   227 "Ukale"
   228 "Ngoshe"
   229 "Nili"
   230 "Ninnma"
   231 "Ninzom"
   232 "Nkoroo"
   233 "Nnebe"
   234 "Numana"
   235 "Nungu"
   236 "nunku"
   237 "Nupe"
   238 "Obubua"
   239 "Odu"
   240 "Ogoja"
   241 "Ogoni"
   242 "Ogugu"
   243 "Okori/Ogori"
   244 "Omele"
   245 "Ora"
   246 "Oron"
   247 "Owan"
   249 "Owo"
   250 "Pa'awa"
   251 "Paburi"
   252 "Paibun"
   253 "Panya"
   254 "Pasama"
   255 "Pero"
   256 "Piya"
   257 "Pyem"
   258 "Rukuba"
   259 "Rulere"
   260 "Rundawa"
   261 "Sayawa/Siyawa"
   262 "Sekere"
   263 "Sharawa"
   264 "Shomo"
   265 "Shuwa"
   266 "Somunka"
   267 "Sullubawa"
   268 "Sura"
   269 "Taira"
   270 "Tangale"
   272 "Tarok"
   273 "Tera"
   274 "Teskwa"
   275 "Tiguni ( ? )"
   276 "Tiv"
   277 "Tiyari"
   278 "Tula"
   279 "Ubaija"
   280 "Ugbia"
   281 "Uhionigbe"
   282 "Ukwuani"
   283 "Urhobo"
   284 "Uyo"
   285 "Uzaurue"
   286 "Uzeba"
   287 "Waja"
   288 "Waka"
   289 "Wanu"
   290 "Wari"
   291 "Warjawa"
   292 "Wodaabe"
   293 "Wurkum"
   294 "Yakurr"
   295 "Yandang"
   296 "Yendre"
   297 "Yonubi"
   298 "Yoruba"
   299 "Zabarmawa"
   301 "Kaje"
   302 "Igbanko"
   303 "Okori/Ogori"
   304 "Migili"
   305 "Gwari"
   306 "Uru"
   307 "Okirika"
   308 "Egi"
   309 "Ogba"
   310 "Moroa"
   311 "Marwa"
   312 "Toff"
   313 "Fulfulde"
   314 "Kabba/Okun"
   315 "Bakabe"
   316 "Burmanch"
   317 "Kalabari"
   320 "Miship"
   321 "Karimjo"
   322 "Kwa"
   323 "Angas"
   324 "Bobari"
   325 "Yarimawa"
   326 "Bakenga"
   327 "Agazawa"
   328 "Gwoza"
   329 "Zalidva"
   330 "Nyangdang"
   331 "Ngezim"
   332 "Hanbagda"
   333 "Njanyi"
   334 "Dumak"
   335 "Kwalla"
   336 "Yeskwa and Mubula"
   337 "Bile"
   338 "Offa"
   339 "Yungur"
   340 "Pura Pura"
   341 "Rindre"
   342 "Dukawa"
   343 "Ningi"
   344 "Cham"
   345 "Kamo"
   346 "Lala"
   347 "Laru"
   348 "Lisa"
   349 "Gaanda"
   350 "Ezza"
   351 "Kubasawa."
   352 "Gusu"
   353 "Ikpoma"
   354 "Buh"
   355 "Mushere"
   356 "Chakeem"
   357 "Jipal"
   358 "Ugeb"
   359 "Koma"
   360 "Verre/Kila"
   361 "Zuru"
   362 "Honna"
   363 "Kapsiki"
   364 "Jere"
   365 "Gizi Yobe"
   366 "Karekare"
   367 "Kulere"
   368 "Beteer"
   369 "Bashama"
   370 "Antocha"
   371 "Baruba/Baruntin"
   372 "Nezou"
   373 "Dibba"
   374 "Kanum"
   375 "Gasawa"
   376 "Muryan"
   377 "Bageri"
   378 "Ahu"
   379 "Basange"
   380 "Nakere"
   381 "Batunu"
   382 "Sanga"
   383 "Ohari"
   384 "Numuro"
   385 "Tangale"
   386 "Guruma"
   387 "Otuwo"
   388 "Batala"
   389 "Ogbo"
   390 "Egbema"
   391 "Dara"
   392 "Andoni"
   393 "Obolo"
   394 "Pegan"
   395 "Iyala"
   396 "Jibawa"
   397 "Mungaduso"
   398 "Okobo"
   996 "Others"
   998 "Don't Know"
;
label define V133    
    97 "Inconsistent"
;
label define V134    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V135    
     1 "Usual resident"
     2 "Visitor"
;
label define V139    
     0 "Abroad"
     1 "Sokoto"
     2 "Zamfara"
     3 "Katsina"
     4 "Jigawa"
     5 "Yobe"
     6 "Borno"
     7 "Adamawa"
     8 "Gombe"
     9 "Bauchi"
    10 "Kano"
    11 "Kaduna"
    12 "Kebbi"
    13 "Niger"
    14 "FCT"
    15 "Nasarawa"
    16 "Plateau"
    17 "Taraba"
    18 "Benue"
    19 "Kogi"
    20 "Kwara"
    21 "Oyo"
    22 "Osun"
    23 "Ekiti"
    24 "Ondo"
    25 "Edo"
    26 "Anambra"
    27 "Enugu"
    28 "Ebonyi"
    29 "Cross River"
    30 "Akwa Ibom"
    31 "Abia"
    32 "Imo"
    33 "Rivers"
    34 "Bayelsa"
    35 "Delta"
    36 "Lagos"
    37 "Ogun"
    97 "Not dejure resident"
;
label define V140    
     0 "Abroad"
     1 "Urban"
     2 "Rural"
     7 "Not a dejure resident"
;
label define V141    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     7 "Not a dejure resident"
;
label define V149    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define V150    
     1 "Head"
     2 "Wife"
     3 "Daughter"
     4 "Daughter-in-law"
     5 "Granddaughter"
     6 "Mother"
     7 "Mother-in-law"
     8 "Sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "Don't know"
;
label define V151    
     1 "Male"
     2 "Female"
;
label define V152    
    97 "97+"
    98 "Don't know"
;
label define V153    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V155    
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define V156    
     0 "No"
     1 "Yes"
;
label define V157    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V158    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V159    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V160    
     0 "No"
     1 "Yes"
     7 "Not a dejure resident"
;
label define V161    
     1 "Electricity"
     2 "Solar cooker"
     3 "LPG"
     4 "Natural gas"
     5 "Biogas"
     6 "Alcohol/ethanol"
     7 "Gasoline/diesel"
     8 "Kerosene/paraffin"
     9 "Coal/lignite"
    10 "Charcoal"
    11 "Wood"
    12 "Straw/shrubs/grass"
    13 "Agricultural crop"
    14 "Animal dung/waste"
    15 "Processed biomass (pellets) or woodchips"
    16 "Garbage/plastic"
    17 "Sawdust"
    95 "No food cooked in house"
    96 "Other"
    97 "Not a dejure resident"
;
label define V169A   
     0 "No"
     1 "Yes"
;
label define V169C   
     0 "No"
     1 "Yes"
;
label define V171A   
     0 "Never"
     1 "Yes, last 12 months"
     2 "Yes, before last 12 months"
     3 "Yes, can't establish when"
;
label define V171B   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V190    
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define V190A   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define ML101   
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define V459    
     0 "No"
     1 "Yes"
;
label define V460    
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define V461    
     0 "No"
     1 "Yes"
;
label define V468    
     0 "See specific questions"
     1 "Last birth only"
     2 "All births in last 5 years"
;
label define B0      
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
;
label define B4      
     1 "Male"
     2 "Female"
;
label define B5      
     0 "No"
     1 "Yes"
;
label define B6      
   100 "Died on day of birth"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
   997 "Inconsistent"
   998 "Don't know"
;
label define B9      
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
;
label define B10     
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define B13     
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
;
label define B15     
     0 "No"
     1 "Yes"
;
label define B16     
     0 "Not listed in household"
;
label define V208    
     0 "No births"
;
label define V209    
     0 "No births"
;
label define V213    
     0 "No or unsure"
     1 "Yes"
;
label define V214A   
   101 "Weeks: 1"
   199 "Weeks: number missing"
   201 "Months: 1"
   299 "Months: number missing"
;
label define V220    
     6 "6+"
;
label define V223    
     7 "Month - exact date"
     8 "None - date placed"
;
label define V237    
     0 "No"
     1 "Yes"
;
label define M2A     
     0 "No"
     1 "Yes"
;
label define M2B     
     0 "No"
     1 "Yes"
;
label define M2C     
     0 "No"
     1 "Yes"
;
label define M2D     
     0 "No"
     1 "Yes"
;
label define M2E     
     0 "No"
     1 "Yes"
;
label define M2F     
     0 "No"
     1 "Yes"
;
label define M2G     
     0 "No"
     1 "Yes"
;
label define M2H     
     0 "No"
     1 "Yes"
;
label define M2I     
     0 "No"
     1 "Yes"
;
label define M2J     
     0 "No"
     1 "Yes"
;
label define M2K     
     0 "No"
     1 "Yes"
;
label define M2L     
     0 "No"
     1 "Yes"
;
label define M2M     
     0 "No"
     1 "Yes"
;
label define M2N     
     0 "No: some care"
     1 "Yes: no care"
;
label define M13     
    98 "Don't know"
;
label define M13A    
   101 "Weeks: 1"
   199 "Weeks: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   998 "Don't know"
;
label define M14     
     0 "No antenatal visits"
    98 "Don't know"
;
label define M49A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49C    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49D    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49E    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49F    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49G    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49X    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49Z    
     0 "No"
     1 "Yes: don't know which drug taken"
     8 "Don't know"
;
label define M49Y    
     0 "No"
     1 "Yes, took no drug"
     8 "Don't know"
;
label define M57A    
     0 "No"
     1 "Yes"
;
label define M57B    
     0 "No"
     1 "Yes"
;
label define M57C    
     0 "No"
     1 "Yes"
;
label define M57D    
     0 "No"
     1 "Yes"
;
label define M57E    
     0 "No"
     1 "Yes"
;
label define M57F    
     0 "No"
     1 "Yes"
;
label define M57G    
     0 "No"
     1 "Yes"
;
label define M57H    
     0 "No"
     1 "Yes"
;
label define M57I    
     0 "No"
     1 "Yes"
;
label define M57J    
     0 "No"
     1 "Yes"
;
label define M57K    
     0 "No"
     1 "Yes"
;
label define M57L    
     0 "No"
     1 "Yes"
;
label define M57M    
     0 "No"
     1 "Yes"
;
label define M57N    
     0 "No"
     1 "Yes"
;
label define M57O    
     0 "No"
     1 "Yes"
;
label define M57P    
     0 "No"
     1 "Yes"
;
label define M57Q    
     0 "No"
     1 "Yes"
;
label define M57R    
     0 "No"
     1 "Yes"
;
label define M57NA   
     0 "No"
     1 "Yes"
;
label define M57NB   
     0 "No"
     1 "Yes"
;
label define M57NC   
     0 "No"
     1 "Yes"
;
label define M57ND   
     0 "No"
     1 "Yes"
;
label define M57NE   
     0 "No"
     1 "Yes"
;
label define M57S    
     0 "No"
     1 "Yes"
;
label define M57T    
     0 "No"
     1 "Yes"
;
label define M57U    
     0 "No"
     1 "Yes"
;
label define M57V    
     0 "No"
     1 "Yes"
;
label define M57X    
     0 "No"
     1 "Yes"
;
label define ML1     
    98 "Don't know"
;
label define ML2     
     1 "Antenatal visit"
     2 "Another facility visit"
     3 "Community health extension worker"
     6 "Other source"
;
label define H22     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H31     
     0 "No"
     1 "Yes, last 24 hours"
     2 "Yes, last two weeks"
     8 "Don't know"
;
label define H32A    
     0 "No"
     1 "Yes"
;
label define H32B    
     0 "No"
     1 "Yes"
;
label define H32C    
     0 "No"
     1 "Yes"
;
label define H32D    
     0 "No"
     1 "Yes"
;
label define H32E    
     0 "No"
     1 "Yes"
;
label define H32F    
     0 "No"
     1 "Yes"
;
label define H32G    
     0 "No"
     1 "Yes"
;
label define H32H    
     0 "No"
     1 "Yes"
;
label define H32I    
     0 "No"
     1 "Yes"
;
label define H32J    
     0 "No"
     1 "Yes"
;
label define H32K    
     0 "No"
     1 "Yes"
;
label define H32L    
     0 "No"
     1 "Yes"
;
label define H32M    
     0 "No"
     1 "Yes"
;
label define H32N    
     0 "No"
     1 "Yes"
;
label define H32O    
     0 "No"
     1 "Yes"
;
label define H32P    
     0 "No"
     1 "Yes"
;
label define H32Q    
     0 "No"
     1 "Yes"
;
label define H32R    
     0 "No"
     1 "Yes"
;
label define H32NA   
     0 "No"
     1 "Yes"
;
label define H32NB   
     0 "No"
     1 "Yes"
;
label define H32NC   
     0 "No"
     1 "Yes"
;
label define H32ND   
     0 "No"
     1 "Yes"
;
label define H32NE   
     0 "No"
     1 "Yes"
;
label define H32S    
     0 "No"
     1 "Yes"
;
label define H32T    
     0 "No"
     1 "Yes"
;
label define H32U    
     0 "No"
     1 "Yes"
;
label define H32V    
     0 "No"
     1 "Yes"
;
label define H32W    
     0 "No"
     1 "Yes"
;
label define H32X    
     0 "No"
     1 "Yes"
;
label define H32Y    
     0 "No: received treatment"
     1 "Yes: no treatment"
;
label define H32Z    
     0 "No"
     1 "Yes"
;
label define H46A    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Government health post"
    14 "Government mobile clinic"
    15 "Government CHW/fieldworker"
    16 "Other public sector"
    20 "PRIVATE SECTOR"
    21 "Private hospital"
    22 "Private clinic"
    23 "Private pharmacy"
    24 "Private doctor"
    25 "Private mobile clinic"
    26 "Private CHW/fieldworker"
    27 "Other private medical sector"
    30 "OTHER"
    31 "NGO hospital"
    32 "NGO clinic"
    33 "Other NGO medical sector"
    34 "Chemist shop/PPMV"
    35 "Traditional practitioner"
    36 "Market"
    37 "Itinerant drug seller"
    38 "Community-oriented resource-person"
    96 "Other"
;
label define H46B    
     0 "Same day"
    98 "Don't know"
;
label define H47     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H71     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HW16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HW51    
     0 "Not in household"
;
label define HW52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HW53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HW55    
     0 "Measured"
     1 "Dead"
     3 "Not present"
     4 "Refused"
     6 "Other"
     7 "No measurement found in household"
;
label define HW56    
   997 "Inconsistent"
;
label define HW57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HW58    
     0 "No"
     1 "Yes"
;
label define ML0     
     0 "No net"
     1 "Only treated nets"
     2 "Both treated and untreated nets"
     3 "Only untreated nets"
;
label define ML11    
     0 "No"
     1 "Yes, fever only"
     2 "Yes, cough only"
     3 "Both fever and cough"
     8 "Don't know"
;
label define ML12    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define ML13A   
     0 "No"
     1 "Yes"
;
label define ML13B   
     0 "No"
     1 "Yes"
;
label define ML13C   
     0 "No"
     1 "Yes"
;
label define ML13D   
     0 "No"
     1 "Yes"
;
label define ML13DA  
     0 "No"
     1 "Yes"
;
label define ML13E   
     0 "No"
     1 "Yes"
;
label define ML13AA  
     0 "No"
     1 "Yes"
;
label define ML13AB  
     0 "No"
     1 "Yes"
;
label define ML13F   
     0 "No"
     1 "Yes"
;
label define ML13G   
     0 "No"
     1 "Yes"
;
label define ML13H   
     0 "No"
     1 "Yes"
;
label define ML13I   
     0 "No"
     1 "Yes"
;
label define ML13J   
     0 "No"
     1 "Yes"
;
label define ML13K   
     0 "No"
     1 "Yes"
;
label define ML13L   
     0 "No"
     1 "Yes"
;
label define ML13M   
     0 "No"
     1 "Yes"
;
label define ML13N   
     0 "No"
     1 "Yes"
;
label define ML13O   
     0 "No"
     1 "Yes"
;
label define ML13P   
     0 "No"
     1 "Yes"
;
label define ML13X   
     0 "No"
     1 "Yes"
;
label define ML13Y   
     0 "No"
     1 "Yes, nothing taken"
;
label define ML13Z   
     0 "No"
     1 "Yes, don't know"
;
label define ML14A   
     0 "No"
     1 "Yes"
;
label define ML14B   
     0 "No"
     1 "Yes"
;
label define ML14Y   
     0 "No"
     1 "Yes"
;
label define ML14Z   
     0 "No"
     1 "Yes"
;
label define ML15A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML15B   
     7 "7+ days"
     8 "Don't know"
;
label define ML15C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML16A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML16B   
     7 "7+ days"
     8 "Don't know"
;
label define ML16C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML17A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML17B   
     7 "7+ days"
     8 "Don't know"
;
label define ML17C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML18A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML18B   
     7 "7+ days"
     8 "Don't know"
;
label define ML18C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML19A   
     0 "No"
     1 "Yes"
;
label define ML19B   
     0 "No"
     1 "Yes"
;
label define ML19C   
     0 "No"
     1 "Yes"
;
label define ML19D   
     0 "No"
     1 "Yes"
;
label define ML19E   
     0 "No"
     1 "Yes"
;
label define ML19F   
     0 "No"
     1 "Yes"
;
label define ML19X   
     0 "No"
     1 "Yes"
;
label define ML19Y   
     0 "No"
     1 "Yes"
;
label define ML19Z   
     0 "No"
     1 "Yes"
;
label define ML20A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML20B   
     7 "7+ days"
     8 "Don't know"
;
label define ML20C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML21A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML21B   
     7 "7+ days"
     8 "Don't know"
;
label define ML21C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML22A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML22B   
     7 "7+ days"
     8 "Don't know"
;
label define ML22C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML23A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML23B   
     7 "7+ days"
     8 "Don't know"
;
label define ML23C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML24C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML25A   
     0 "Same day as fever/cough"
     1 "Next day"
     2 "2 days after"
     3 "3 days after"
     4 "4+ days after"
     8 "Don't know"
;
label define ML501   
     0 "No"
     1 "Yes"
;
label define ML501A  
     0 "No"
     1 "Yes"
;
label define ML501B  
     0 "No"
     1 "Yes"
;
label define ML501C  
     0 "No"
     1 "Yes"
;
label define ML501D  
     0 "No"
     1 "Yes"
;
label define ML501E  
     0 "No"
     1 "Yes"
;
label define ML501F  
     0 "No"
     1 "Yes"
;
label define ML501G  
     0 "No"
     1 "Yes"
;
label define ML501H  
     0 "No"
     1 "Yes"
;
label define ML501I  
     0 "No"
     1 "Yes"
;
label define ML501J  
     0 "No"
     1 "Yes"
;
label define ML501K  
     0 "No"
     1 "Yes"
;
label define ML501X  
     0 "No"
     1 "Yes"
;
label define ML501Z  
     0 "No"
     1 "Yes"
;
label define ML503   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define ML503A  
     0 "No"
     1 "Yes"
;
label define ML503B  
     0 "No"
     1 "Yes"
;
label define ML503C  
     0 "No"
     1 "Yes"
;
label define ML503D  
     0 "No"
     1 "Yes"
;
label define ML503E  
     0 "No"
     1 "Yes"
;
label define ML503F  
     0 "No"
     1 "Yes"
;
label define ML503G  
     0 "No"
     1 "Yes"
;
label define ML503H  
     0 "No"
     1 "Yes"
;
label define ML503I  
     0 "No"
     1 "Yes"
;
label define ML503J  
     0 "No"
     1 "Yes"
;
label define ML503K  
     0 "No"
     1 "Yes"
;
label define ML503X  
     0 "No"
     1 "Yes"
;
label define ML503Z  
     0 "No"
     1 "Yes"
;
label define ML505   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define ML506   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define ML507   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define ML508   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define ML509   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define ML510   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define ML511   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define ML512   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define ML513   
     0 "Disagree/less than half"
     1 "Agree/more than half"
     8 "Don't know/uncertain"
;
label define ML514   
     0 "Disagree/less than half"
     1 "Agree/more than half"
     8 "Don't know/uncertain"
;
label define S512A   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/uncertain"
;
label define SREGION 
     1 "North Central"
     2 "North East"
     3 "North West"
     4 "South East"
     5 "South South"
     6 "South West"
;
label define SBONNY  
     0 "No"
     1 "Yes"
;
label define S104A   
     0 "No"
     1 "Yes"
;
label define S104B   
     1 "Adult education"
     2 "Tsangaya"
     3 "Quaranic"
;
label define S211    
     0 "No births"
;
label define S411A   
     0 "No"
     1 "Yes"
;
label define S415A   
     0 "No"
     1 "Yes"
;

#delimit cr
label values v013     V013    
label values v014     V014    
label values v015     V015    
label values v022     V022    
label values v023     V023    
label values v024     V024    
label values v025     V025    
label values v026     V026    
label values v034     V034    
label values v042     V042    
label values v045a    V045A   
label values v045b    V045B   
label values v045c    V045C   
label values v046     V046    
label values v101     V101    
label values v102     V102    
label values v106     V106    
label values v107     V107    
label values v113     V113    
label values v115     V115    
label values v116     V116    
label values v119     V119    
label values v120     V120    
label values v121     V121    
label values v122     V122    
label values v123     V123    
label values v124     V124    
label values v125     V125    
label values v127     V127    
label values v128     V128    
label values v129     V129    
label values v130     V130    
label values v131     V131    
label values v133     V133    
label values v134     V134    
label values v135     V135    
label values v139     V139    
label values v140     V140    
label values v141     V141    
label values v149     V149    
label values v150     V150    
label values v151     V151    
label values v152     V152    
label values v153     V153    
label values v155     V155    
label values v156     V156    
label values v157     V157    
label values v158     V158    
label values v159     V159    
label values v160     V160    
label values v161     V161    
label values v169a    V169A   
label values v169c    V169C   
label values v171a    V171A   
label values v171b    V171B   
label values v190     V190    
label values v190a    V190A   
label values ml101    ML101   
label values v459     V459    
label values v460     V460    
label values v461     V461    
label values v468     V468    
label values b0       B0      
label values b4       B4      
label values b5       B5      
label values b6       B6      
label values b9       B9      
label values b10      B10     
label values b13      B13     
label values b15      B15     
label values b16      B16     
label values v208     V208    
label values v209     V209    
label values v213     V213    
label values v214a    V214A   
label values v220     V220    
label values v223     V223    
label values v237     V237    
label values m2a      M2A     
label values m2b      M2B     
label values m2c      M2C     
label values m2d      M2D     
label values m2e      M2E     
label values m2f      M2F     
label values m2g      M2G     
label values m2h      M2H     
label values m2i      M2I     
label values m2j      M2J     
label values m2k      M2K     
label values m2l      M2L     
label values m2m      M2M     
label values m2n      M2N     
label values m13      M13     
label values m13a     M13A    
label values m14      M14     
label values m49a     M49A    
label values m49b     M49B    
label values m49c     M49C    
label values m49d     M49D    
label values m49e     M49E    
label values m49f     M49F    
label values m49g     M49G    
label values m49x     M49X    
label values m49z     M49Z    
label values m49y     M49Y    
label values m57a     M57A    
label values m57b     M57B    
label values m57c     M57C    
label values m57d     M57D    
label values m57e     M57E    
label values m57f     M57F    
label values m57g     M57G    
label values m57h     M57H    
label values m57i     M57I    
label values m57j     M57J    
label values m57k     M57K    
label values m57l     M57L    
label values m57m     M57M    
label values m57n     M57N    
label values m57o     M57O    
label values m57p     M57P    
label values m57q     M57Q    
label values m57r     M57R    
label values m57na    M57NA   
label values m57nb    M57NB   
label values m57nc    M57NC   
label values m57nd    M57ND   
label values m57ne    M57NE   
label values m57s     M57S    
label values m57t     M57T    
label values m57u     M57U    
label values m57v     M57V    
label values m57x     M57X    
label values ml1      ML1     
label values ml2      ML2     
label values h22      H22     
label values h31      H31     
label values h32a     H32A    
label values h32b     H32B    
label values h32c     H32C    
label values h32d     H32D    
label values h32e     H32E    
label values h32f     H32F    
label values h32g     H32G    
label values h32h     H32H    
label values h32i     H32I    
label values h32j     H32J    
label values h32k     H32K    
label values h32l     H32L    
label values h32m     H32M    
label values h32n     H32N    
label values h32o     H32O    
label values h32p     H32P    
label values h32q     H32Q    
label values h32r     H32R    
label values h32na    H32NA   
label values h32nb    H32NB   
label values h32nc    H32NC   
label values h32nd    H32ND   
label values h32ne    H32NE   
label values h32s     H32S    
label values h32t     H32T    
label values h32u     H32U    
label values h32v     H32V    
label values h32w     H32W    
label values h32x     H32X    
label values h32y     H32Y    
label values h32z     H32Z    
label values h46a     H46A    
label values h46b     H46B    
label values h47      H47     
label values h71      H71     
label values hw16     HW16    
label values hw51     HW51    
label values hw52     HW52    
label values hw53     HW53    
label values hw55     HW55    
label values hw56     HW56    
label values hw57     HW57    
label values hw58     HW58    
label values ml0      ML0     
label values ml11     ML11    
label values ml12     ML12    
label values ml13a    ML13A   
label values ml13b    ML13B   
label values ml13c    ML13C   
label values ml13d    ML13D   
label values ml13da   ML13DA  
label values ml13e    ML13E   
label values ml13aa   ML13AA  
label values ml13ab   ML13AB  
label values ml13f    ML13F   
label values ml13g    ML13G   
label values ml13h    ML13H   
label values ml13i    ML13I   
label values ml13j    ML13J   
label values ml13k    ML13K   
label values ml13l    ML13L   
label values ml13m    ML13M   
label values ml13n    ML13N   
label values ml13o    ML13O   
label values ml13p    ML13P   
label values ml13x    ML13X   
label values ml13y    ML13Y   
label values ml13z    ML13Z   
label values ml14a    ML14A   
label values ml14b    ML14B   
label values ml14y    ML14Y   
label values ml14z    ML14Z   
label values ml15a    ML15A   
label values ml15b    ML15B   
label values ml15c    ML15C   
label values ml16a    ML16A   
label values ml16b    ML16B   
label values ml16c    ML16C   
label values ml17a    ML17A   
label values ml17b    ML17B   
label values ml17c    ML17C   
label values ml18a    ML18A   
label values ml18b    ML18B   
label values ml18c    ML18C   
label values ml19a    ML19A   
label values ml19b    ML19B   
label values ml19c    ML19C   
label values ml19d    ML19D   
label values ml19e    ML19E   
label values ml19f    ML19F   
label values ml19x    ML19X   
label values ml19y    ML19Y   
label values ml19z    ML19Z   
label values ml20a    ML20A   
label values ml20b    ML20B   
label values ml20c    ML20C   
label values ml21a    ML21A   
label values ml21b    ML21B   
label values ml21c    ML21C   
label values ml22a    ML22A   
label values ml22b    ML22B   
label values ml22c    ML22C   
label values ml23a    ML23A   
label values ml23b    ML23B   
label values ml23c    ML23C   
label values ml24c    ML24C   
label values ml25a    ML25A   
label values ml501    ML501   
label values ml501a   ML501A  
label values ml501b   ML501B  
label values ml501c   ML501C  
label values ml501d   ML501D  
label values ml501e   ML501E  
label values ml501f   ML501F  
label values ml501g   ML501G  
label values ml501h   ML501H  
label values ml501i   ML501I  
label values ml501j   ML501J  
label values ml501k   ML501K  
label values ml501x   ML501X  
label values ml501z   ML501Z  
label values ml503    ML503   
label values ml503a   ML503A  
label values ml503b   ML503B  
label values ml503c   ML503C  
label values ml503d   ML503D  
label values ml503e   ML503E  
label values ml503f   ML503F  
label values ml503g   ML503G  
label values ml503h   ML503H  
label values ml503i   ML503I  
label values ml503j   ML503J  
label values ml503k   ML503K  
label values ml503x   ML503X  
label values ml503z   ML503Z  
label values ml505    ML505   
label values ml506    ML506   
label values ml507    ML507   
label values ml508    ML508   
label values ml509    ML509   
label values ml510    ML510   
label values ml511    ML511   
label values ml512    ML512   
label values ml513    ML513   
label values ml514    ML514   
label values s512a    S512A   
label values sregion  SREGION 
label values sbonny   SBONNY  
label values s104a    S104A   
label values s104b    S104B   
label values s211     S211    
label values s411a    S411A   
label values s415a    S415A   
