infix using "C:\COUNTRIES\KE81\KEHR81FL.dct"

label variable hhid     "Case Identification"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv008a   "Date of interview Century Day Code (CDC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv011    "NA - Number of eligible men in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 14 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "Household selected for male interview"
label variable hv028    "Household weight for male subsample (6 decimals)"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv035    "Number of eligible children for height and weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "Total adults measured"
label variable hv042    "Household selected for hemoglobin"
label variable hv045a   "Language of questionnaire"
label variable hv045b   "Language of interview"
label variable hv045c   "Native language of respondent"
label variable hv046    "Translator used"
label variable hv801    "Time interview started (hhmm - 24 hour clock)"
label variable hv802    "Time interview ended (hhmm - 24 hour clock)"
label variable hv803    "Length of interview in minutes"
label variable hv804    "Number of visits for biomarker"
label variable hv807d   "Day of biomarker visit"
label variable hv807m   "Month of biomarker visit"
label variable hv807y   "Year of biomarker visit"
label variable hv807c   "Date of biomarker (CMC)"
label variable hv807a   "Date of biomarker Century Day Code (CDC)"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv201a   "NA - Water not available for at least a day last two weeks"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "Has mosquito bed net for sleeping"
label variable hv228    "Children under 5 slept under mosquito bed net last night"
label variable hv235    "Location of source for water"
label variable hv238    "Number of households sharing toilet"
label variable hv238a   "Location of toilet facility"
label variable hv239    "NA - Food cooked on stove or open fire"
label variable hv240    "NA - Household has a chimney, hood or neither"
label variable hv241    "NA - Food cooked in the house/ separate building/ outdoors"
label variable hv242    "NA - Household has separate room used as kitchen"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "Has watch"
label variable hv243c   "Has animal-drawn cart"
label variable hv243d   "Has boat with a motor"
label variable hv243e   "Has a computer"
label variable hv244    "Owns land usable for agriculture"
label variable hv245    "Hectares of agricultural land (1 decimal)"
label variable hv246    "Owns livestock, herds or farm animals"
label variable hv246a   "Owns cattle"
label variable hv246b   "Owns cows/ bulls"
label variable hv246c   "NA - Owns horses/ donkeys/ mules"
label variable hv246d   "Owns goats"
label variable hv246e   "Owns sheep"
label variable hv246f   "Owns chickens/poultry"
label variable hv246g   "Owns horses"
label variable hv246h   "Owns donkeys"
label variable hv246i   "Owns mules"
label variable hv246j   "Owns pigs"
label variable hv246k   "NA - Owns CS"
label variable hv247    "Has bank account"
label variable hv270    "Wealth index combined"
label variable hv271    "Wealth index factor score combined (5 decimals)"
label variable hv270a   "Wealth index for urban/rural"
label variable hv271a   "Wealth index factor score for urban/rural (5 decimals)"
label variable hml1     "Number of mosquito bed nets"
label variable hml1a    "Number of mosquito bed nets with specific information"
label variable hml2     "Number of children under mosquito bed net previous night"
label variable shcounty "County"
label variable shzone   "Malaria endemicity zone"
label variable sh109    "Type of cooking device"
label variable sh110    "Type of fuel/energy source for cooking device"
label variable sh116g   "Has solar panel"
label variable sh116h   "Has table"
label variable sh116i   "Has chair"
label variable sh116j   "Has sofa"
label variable sh116k   "Has bed"
label variable sh116l   "Has cupboard"
label variable sh116m   "Has clock"
label variable sh116n   "Has microwave oven"
label variable sh116o   "Has DVD player"
label variable sh116p   "Has CD player"
label variable sh119    "Member use phone for financial transactions"
label variable sh119a   "Household used mosquito repellent spray"
label variable hvidx_01 "Line number"
label variable hvidx_02 "Line number"
label variable hvidx_03 "Line number"
label variable hvidx_04 "Line number"
label variable hvidx_05 "Line number"
label variable hvidx_06 "Line number"
label variable hvidx_07 "Line number"
label variable hvidx_08 "Line number"
label variable hvidx_09 "Line number"
label variable hvidx_10 "Line number"
label variable hvidx_11 "Line number"
label variable hvidx_12 "Line number"
label variable hvidx_13 "Line number"
label variable hvidx_14 "Line number"
label variable hvidx_15 "Line number"
label variable hvidx_16 "Line number"
label variable hvidx_17 "Line number"
label variable hvidx_18 "Line number"
label variable hvidx_19 "Line number"
label variable hvidx_20 "Line number"
label variable hvidx_21 "Line number"
label variable hvidx_22 "Line number"
label variable hvidx_23 "Line number"
label variable hvidx_24 "Line number"
label variable hv101_01 "Relationship to head"
label variable hv101_02 "Relationship to head"
label variable hv101_03 "Relationship to head"
label variable hv101_04 "Relationship to head"
label variable hv101_05 "Relationship to head"
label variable hv101_06 "Relationship to head"
label variable hv101_07 "Relationship to head"
label variable hv101_08 "Relationship to head"
label variable hv101_09 "Relationship to head"
label variable hv101_10 "Relationship to head"
label variable hv101_11 "Relationship to head"
label variable hv101_12 "Relationship to head"
label variable hv101_13 "Relationship to head"
label variable hv101_14 "Relationship to head"
label variable hv101_15 "Relationship to head"
label variable hv101_16 "Relationship to head"
label variable hv101_17 "Relationship to head"
label variable hv101_18 "Relationship to head"
label variable hv101_19 "Relationship to head"
label variable hv101_20 "Relationship to head"
label variable hv101_21 "Relationship to head"
label variable hv101_22 "Relationship to head"
label variable hv101_23 "Relationship to head"
label variable hv101_24 "Relationship to head"
label variable hv102_01 "Usual resident"
label variable hv102_02 "Usual resident"
label variable hv102_03 "Usual resident"
label variable hv102_04 "Usual resident"
label variable hv102_05 "Usual resident"
label variable hv102_06 "Usual resident"
label variable hv102_07 "Usual resident"
label variable hv102_08 "Usual resident"
label variable hv102_09 "Usual resident"
label variable hv102_10 "Usual resident"
label variable hv102_11 "Usual resident"
label variable hv102_12 "Usual resident"
label variable hv102_13 "Usual resident"
label variable hv102_14 "Usual resident"
label variable hv102_15 "Usual resident"
label variable hv102_16 "Usual resident"
label variable hv102_17 "Usual resident"
label variable hv102_18 "Usual resident"
label variable hv102_19 "Usual resident"
label variable hv102_20 "Usual resident"
label variable hv102_21 "Usual resident"
label variable hv102_22 "Usual resident"
label variable hv102_23 "Usual resident"
label variable hv102_24 "Usual resident"
label variable hv103_01 "Slept last night"
label variable hv103_02 "Slept last night"
label variable hv103_03 "Slept last night"
label variable hv103_04 "Slept last night"
label variable hv103_05 "Slept last night"
label variable hv103_06 "Slept last night"
label variable hv103_07 "Slept last night"
label variable hv103_08 "Slept last night"
label variable hv103_09 "Slept last night"
label variable hv103_10 "Slept last night"
label variable hv103_11 "Slept last night"
label variable hv103_12 "Slept last night"
label variable hv103_13 "Slept last night"
label variable hv103_14 "Slept last night"
label variable hv103_15 "Slept last night"
label variable hv103_16 "Slept last night"
label variable hv103_17 "Slept last night"
label variable hv103_18 "Slept last night"
label variable hv103_19 "Slept last night"
label variable hv103_20 "Slept last night"
label variable hv103_21 "Slept last night"
label variable hv103_22 "Slept last night"
label variable hv103_23 "Slept last night"
label variable hv103_24 "Slept last night"
label variable hv104_01 "Sex of household member"
label variable hv104_02 "Sex of household member"
label variable hv104_03 "Sex of household member"
label variable hv104_04 "Sex of household member"
label variable hv104_05 "Sex of household member"
label variable hv104_06 "Sex of household member"
label variable hv104_07 "Sex of household member"
label variable hv104_08 "Sex of household member"
label variable hv104_09 "Sex of household member"
label variable hv104_10 "Sex of household member"
label variable hv104_11 "Sex of household member"
label variable hv104_12 "Sex of household member"
label variable hv104_13 "Sex of household member"
label variable hv104_14 "Sex of household member"
label variable hv104_15 "Sex of household member"
label variable hv104_16 "Sex of household member"
label variable hv104_17 "Sex of household member"
label variable hv104_18 "Sex of household member"
label variable hv104_19 "Sex of household member"
label variable hv104_20 "Sex of household member"
label variable hv104_21 "Sex of household member"
label variable hv104_22 "Sex of household member"
label variable hv104_23 "Sex of household member"
label variable hv104_24 "Sex of household member"
label variable hv105_01 "Age of household members"
label variable hv105_02 "Age of household members"
label variable hv105_03 "Age of household members"
label variable hv105_04 "Age of household members"
label variable hv105_05 "Age of household members"
label variable hv105_06 "Age of household members"
label variable hv105_07 "Age of household members"
label variable hv105_08 "Age of household members"
label variable hv105_09 "Age of household members"
label variable hv105_10 "Age of household members"
label variable hv105_11 "Age of household members"
label variable hv105_12 "Age of household members"
label variable hv105_13 "Age of household members"
label variable hv105_14 "Age of household members"
label variable hv105_15 "Age of household members"
label variable hv105_16 "Age of household members"
label variable hv105_17 "Age of household members"
label variable hv105_18 "Age of household members"
label variable hv105_19 "Age of household members"
label variable hv105_20 "Age of household members"
label variable hv105_21 "Age of household members"
label variable hv105_22 "Age of household members"
label variable hv105_23 "Age of household members"
label variable hv105_24 "Age of household members"
label variable hv117_01 "Eligibility for female interview"
label variable hv117_02 "Eligibility for female interview"
label variable hv117_03 "Eligibility for female interview"
label variable hv117_04 "Eligibility for female interview"
label variable hv117_05 "Eligibility for female interview"
label variable hv117_06 "Eligibility for female interview"
label variable hv117_07 "Eligibility for female interview"
label variable hv117_08 "Eligibility for female interview"
label variable hv117_09 "Eligibility for female interview"
label variable hv117_10 "Eligibility for female interview"
label variable hv117_11 "Eligibility for female interview"
label variable hv117_12 "Eligibility for female interview"
label variable hv117_13 "Eligibility for female interview"
label variable hv117_14 "Eligibility for female interview"
label variable hv117_15 "Eligibility for female interview"
label variable hv117_16 "Eligibility for female interview"
label variable hv117_17 "Eligibility for female interview"
label variable hv117_18 "Eligibility for female interview"
label variable hv117_19 "Eligibility for female interview"
label variable hv117_20 "Eligibility for female interview"
label variable hv117_21 "Eligibility for female interview"
label variable hv117_22 "Eligibility for female interview"
label variable hv117_23 "Eligibility for female interview"
label variable hv117_24 "Eligibility for female interview"
label variable hv120_01 "Children eligibility for height/weight and hemoglobin"
label variable hv120_02 "Children eligibility for height/weight and hemoglobin"
label variable hv120_03 "Children eligibility for height/weight and hemoglobin"
label variable hv120_04 "Children eligibility for height/weight and hemoglobin"
label variable hv120_05 "Children eligibility for height/weight and hemoglobin"
label variable hv120_06 "Children eligibility for height/weight and hemoglobin"
label variable hv120_07 "Children eligibility for height/weight and hemoglobin"
label variable hv120_08 "Children eligibility for height/weight and hemoglobin"
label variable hv120_09 "Children eligibility for height/weight and hemoglobin"
label variable hv120_10 "Children eligibility for height/weight and hemoglobin"
label variable hv120_11 "Children eligibility for height/weight and hemoglobin"
label variable hv120_12 "Children eligibility for height/weight and hemoglobin"
label variable hv120_13 "Children eligibility for height/weight and hemoglobin"
label variable hv120_14 "Children eligibility for height/weight and hemoglobin"
label variable hv120_15 "Children eligibility for height/weight and hemoglobin"
label variable hv120_16 "Children eligibility for height/weight and hemoglobin"
label variable hv120_17 "Children eligibility for height/weight and hemoglobin"
label variable hv120_18 "Children eligibility for height/weight and hemoglobin"
label variable hv120_19 "Children eligibility for height/weight and hemoglobin"
label variable hv120_20 "Children eligibility for height/weight and hemoglobin"
label variable hv120_21 "Children eligibility for height/weight and hemoglobin"
label variable hv120_22 "Children eligibility for height/weight and hemoglobin"
label variable hv120_23 "Children eligibility for height/weight and hemoglobin"
label variable hv120_24 "Children eligibility for height/weight and hemoglobin"
label variable hc0_01   "Index to Household Schedule"
label variable hc0_02   "Index to Household Schedule"
label variable hc0_03   "Index to Household Schedule"
label variable hc0_04   "Index to Household Schedule"
label variable hc0_05   "Index to Household Schedule"
label variable hc0_06   "Index to Household Schedule"
label variable hc0_07   "Index to Household Schedule"
label variable hc0_08   "Index to Household Schedule"
label variable hc0_09   "Index to Household Schedule"
label variable hc0_10   "Index to Household Schedule"
label variable hc0_11   "Index to Household Schedule"
label variable hc0_12   "Index to Household Schedule"
label variable hc0_13   "Index to Household Schedule"
label variable hc0_14   "Index to Household Schedule"
label variable hc0_15   "Index to Household Schedule"
label variable hc0_16   "Index to Household Schedule"
label variable hc0_17   "Index to Household Schedule"
label variable hc0_18   "Index to Household Schedule"
label variable hc0_19   "Index to Household Schedule"
label variable hc0_20   "Index to Household Schedule"
label variable hc1_01   "Child's age in months"
label variable hc1_02   "Child's age in months"
label variable hc1_03   "Child's age in months"
label variable hc1_04   "Child's age in months"
label variable hc1_05   "Child's age in months"
label variable hc1_06   "Child's age in months"
label variable hc1_07   "Child's age in months"
label variable hc1_08   "Child's age in months"
label variable hc1_09   "Child's age in months"
label variable hc1_10   "Child's age in months"
label variable hc1_11   "Child's age in months"
label variable hc1_12   "Child's age in months"
label variable hc1_13   "Child's age in months"
label variable hc1_14   "Child's age in months"
label variable hc1_15   "Child's age in months"
label variable hc1_16   "Child's age in months"
label variable hc1_17   "Child's age in months"
label variable hc1_18   "Child's age in months"
label variable hc1_19   "Child's age in months"
label variable hc1_20   "Child's age in months"
label variable hc1a_01  "Child's age in days"
label variable hc1a_02  "Child's age in days"
label variable hc1a_03  "Child's age in days"
label variable hc1a_04  "Child's age in days"
label variable hc1a_05  "Child's age in days"
label variable hc1a_06  "Child's age in days"
label variable hc1a_07  "Child's age in days"
label variable hc1a_08  "Child's age in days"
label variable hc1a_09  "Child's age in days"
label variable hc1a_10  "Child's age in days"
label variable hc1a_11  "Child's age in days"
label variable hc1a_12  "Child's age in days"
label variable hc1a_13  "Child's age in days"
label variable hc1a_14  "Child's age in days"
label variable hc1a_15  "Child's age in days"
label variable hc1a_16  "Child's age in days"
label variable hc1a_17  "Child's age in days"
label variable hc1a_18  "Child's age in days"
label variable hc1a_19  "Child's age in days"
label variable hc1a_20  "Child's age in days"
label variable hc16_01  "Day of birth"
label variable hc16_02  "Day of birth"
label variable hc16_03  "Day of birth"
label variable hc16_04  "Day of birth"
label variable hc16_05  "Day of birth"
label variable hc16_06  "Day of birth"
label variable hc16_07  "Day of birth"
label variable hc16_08  "Day of birth"
label variable hc16_09  "Day of birth"
label variable hc16_10  "Day of birth"
label variable hc16_11  "Day of birth"
label variable hc16_12  "Day of birth"
label variable hc16_13  "Day of birth"
label variable hc16_14  "Day of birth"
label variable hc16_15  "Day of birth"
label variable hc16_16  "Day of birth"
label variable hc16_17  "Day of birth"
label variable hc16_18  "Day of birth"
label variable hc16_19  "Day of birth"
label variable hc16_20  "Day of birth"
label variable hc17_01  "Date measured (day)"
label variable hc17_02  "Date measured (day)"
label variable hc17_03  "Date measured (day)"
label variable hc17_04  "Date measured (day)"
label variable hc17_05  "Date measured (day)"
label variable hc17_06  "Date measured (day)"
label variable hc17_07  "Date measured (day)"
label variable hc17_08  "Date measured (day)"
label variable hc17_09  "Date measured (day)"
label variable hc17_10  "Date measured (day)"
label variable hc17_11  "Date measured (day)"
label variable hc17_12  "Date measured (day)"
label variable hc17_13  "Date measured (day)"
label variable hc17_14  "Date measured (day)"
label variable hc17_15  "Date measured (day)"
label variable hc17_16  "Date measured (day)"
label variable hc17_17  "Date measured (day)"
label variable hc17_18  "Date measured (day)"
label variable hc17_19  "Date measured (day)"
label variable hc17_20  "Date measured (day)"
label variable hc18_01  "Date measured (month)"
label variable hc18_02  "Date measured (month)"
label variable hc18_03  "Date measured (month)"
label variable hc18_04  "Date measured (month)"
label variable hc18_05  "Date measured (month)"
label variable hc18_06  "Date measured (month)"
label variable hc18_07  "Date measured (month)"
label variable hc18_08  "Date measured (month)"
label variable hc18_09  "Date measured (month)"
label variable hc18_10  "Date measured (month)"
label variable hc18_11  "Date measured (month)"
label variable hc18_12  "Date measured (month)"
label variable hc18_13  "Date measured (month)"
label variable hc18_14  "Date measured (month)"
label variable hc18_15  "Date measured (month)"
label variable hc18_16  "Date measured (month)"
label variable hc18_17  "Date measured (month)"
label variable hc18_18  "Date measured (month)"
label variable hc18_19  "Date measured (month)"
label variable hc18_20  "Date measured (month)"
label variable hc19_01  "Date measured (year)"
label variable hc19_02  "Date measured (year)"
label variable hc19_03  "Date measured (year)"
label variable hc19_04  "Date measured (year)"
label variable hc19_05  "Date measured (year)"
label variable hc19_06  "Date measured (year)"
label variable hc19_07  "Date measured (year)"
label variable hc19_08  "Date measured (year)"
label variable hc19_09  "Date measured (year)"
label variable hc19_10  "Date measured (year)"
label variable hc19_11  "Date measured (year)"
label variable hc19_12  "Date measured (year)"
label variable hc19_13  "Date measured (year)"
label variable hc19_14  "Date measured (year)"
label variable hc19_15  "Date measured (year)"
label variable hc19_16  "Date measured (year)"
label variable hc19_17  "Date measured (year)"
label variable hc19_18  "Date measured (year)"
label variable hc19_19  "Date measured (year)"
label variable hc19_20  "Date measured (year)"
label variable hc20_01  "Century Day Code (CDC) of measurement"
label variable hc20_02  "Century Day Code (CDC) of measurement"
label variable hc20_03  "Century Day Code (CDC) of measurement"
label variable hc20_04  "Century Day Code (CDC) of measurement"
label variable hc20_05  "Century Day Code (CDC) of measurement"
label variable hc20_06  "Century Day Code (CDC) of measurement"
label variable hc20_07  "Century Day Code (CDC) of measurement"
label variable hc20_08  "Century Day Code (CDC) of measurement"
label variable hc20_09  "Century Day Code (CDC) of measurement"
label variable hc20_10  "Century Day Code (CDC) of measurement"
label variable hc20_11  "Century Day Code (CDC) of measurement"
label variable hc20_12  "Century Day Code (CDC) of measurement"
label variable hc20_13  "Century Day Code (CDC) of measurement"
label variable hc20_14  "Century Day Code (CDC) of measurement"
label variable hc20_15  "Century Day Code (CDC) of measurement"
label variable hc20_16  "Century Day Code (CDC) of measurement"
label variable hc20_17  "Century Day Code (CDC) of measurement"
label variable hc20_18  "Century Day Code (CDC) of measurement"
label variable hc20_19  "Century Day Code (CDC) of measurement"
label variable hc20_20  "Century Day Code (CDC) of measurement"
label variable hc21_01  "Fieldworker measurer code"
label variable hc21_02  "Fieldworker measurer code"
label variable hc21_03  "Fieldworker measurer code"
label variable hc21_04  "Fieldworker measurer code"
label variable hc21_05  "Fieldworker measurer code"
label variable hc21_06  "Fieldworker measurer code"
label variable hc21_07  "Fieldworker measurer code"
label variable hc21_08  "Fieldworker measurer code"
label variable hc21_09  "Fieldworker measurer code"
label variable hc21_10  "Fieldworker measurer code"
label variable hc21_11  "Fieldworker measurer code"
label variable hc21_12  "Fieldworker measurer code"
label variable hc21_13  "Fieldworker measurer code"
label variable hc21_14  "Fieldworker measurer code"
label variable hc21_15  "Fieldworker measurer code"
label variable hc21_16  "Fieldworker measurer code"
label variable hc21_17  "Fieldworker measurer code"
label variable hc21_18  "Fieldworker measurer code"
label variable hc21_19  "Fieldworker measurer code"
label variable hc21_20  "Fieldworker measurer code"
label variable hc27_01  "Sex"
label variable hc27_02  "Sex"
label variable hc27_03  "Sex"
label variable hc27_04  "Sex"
label variable hc27_05  "Sex"
label variable hc27_06  "Sex"
label variable hc27_07  "Sex"
label variable hc27_08  "Sex"
label variable hc27_09  "Sex"
label variable hc27_10  "Sex"
label variable hc27_11  "Sex"
label variable hc27_12  "Sex"
label variable hc27_13  "Sex"
label variable hc27_14  "Sex"
label variable hc27_15  "Sex"
label variable hc27_16  "Sex"
label variable hc27_17  "Sex"
label variable hc27_18  "Sex"
label variable hc27_19  "Sex"
label variable hc27_20  "Sex"
label variable hc30_01  "Month of birth"
label variable hc30_02  "Month of birth"
label variable hc30_03  "Month of birth"
label variable hc30_04  "Month of birth"
label variable hc30_05  "Month of birth"
label variable hc30_06  "Month of birth"
label variable hc30_07  "Month of birth"
label variable hc30_08  "Month of birth"
label variable hc30_09  "Month of birth"
label variable hc30_10  "Month of birth"
label variable hc30_11  "Month of birth"
label variable hc30_12  "Month of birth"
label variable hc30_13  "Month of birth"
label variable hc30_14  "Month of birth"
label variable hc30_15  "Month of birth"
label variable hc30_16  "Month of birth"
label variable hc30_17  "Month of birth"
label variable hc30_18  "Month of birth"
label variable hc30_19  "Month of birth"
label variable hc30_20  "Month of birth"
label variable hc31_01  "Year of birth"
label variable hc31_02  "Year of birth"
label variable hc31_03  "Year of birth"
label variable hc31_04  "Year of birth"
label variable hc31_05  "Year of birth"
label variable hc31_06  "Year of birth"
label variable hc31_07  "Year of birth"
label variable hc31_08  "Year of birth"
label variable hc31_09  "Year of birth"
label variable hc31_10  "Year of birth"
label variable hc31_11  "Year of birth"
label variable hc31_12  "Year of birth"
label variable hc31_13  "Year of birth"
label variable hc31_14  "Year of birth"
label variable hc31_15  "Year of birth"
label variable hc31_16  "Year of birth"
label variable hc31_17  "Year of birth"
label variable hc31_18  "Year of birth"
label variable hc31_19  "Year of birth"
label variable hc31_20  "Year of birth"
label variable hc32_01  "Date of birth (CMC)"
label variable hc32_02  "Date of birth (CMC)"
label variable hc32_03  "Date of birth (CMC)"
label variable hc32_04  "Date of birth (CMC)"
label variable hc32_05  "Date of birth (CMC)"
label variable hc32_06  "Date of birth (CMC)"
label variable hc32_07  "Date of birth (CMC)"
label variable hc32_08  "Date of birth (CMC)"
label variable hc32_09  "Date of birth (CMC)"
label variable hc32_10  "Date of birth (CMC)"
label variable hc32_11  "Date of birth (CMC)"
label variable hc32_12  "Date of birth (CMC)"
label variable hc32_13  "Date of birth (CMC)"
label variable hc32_14  "Date of birth (CMC)"
label variable hc32_15  "Date of birth (CMC)"
label variable hc32_16  "Date of birth (CMC)"
label variable hc32_17  "Date of birth (CMC)"
label variable hc32_18  "Date of birth (CMC)"
label variable hc32_19  "Date of birth (CMC)"
label variable hc32_20  "Date of birth (CMC)"
label variable hc32a_01 "Century Day Code (CDC) of birth"
label variable hc32a_02 "Century Day Code (CDC) of birth"
label variable hc32a_03 "Century Day Code (CDC) of birth"
label variable hc32a_04 "Century Day Code (CDC) of birth"
label variable hc32a_05 "Century Day Code (CDC) of birth"
label variable hc32a_06 "Century Day Code (CDC) of birth"
label variable hc32a_07 "Century Day Code (CDC) of birth"
label variable hc32a_08 "Century Day Code (CDC) of birth"
label variable hc32a_09 "Century Day Code (CDC) of birth"
label variable hc32a_10 "Century Day Code (CDC) of birth"
label variable hc32a_11 "Century Day Code (CDC) of birth"
label variable hc32a_12 "Century Day Code (CDC) of birth"
label variable hc32a_13 "Century Day Code (CDC) of birth"
label variable hc32a_14 "Century Day Code (CDC) of birth"
label variable hc32a_15 "Century Day Code (CDC) of birth"
label variable hc32a_16 "Century Day Code (CDC) of birth"
label variable hc32a_17 "Century Day Code (CDC) of birth"
label variable hc32a_18 "Century Day Code (CDC) of birth"
label variable hc32a_19 "Century Day Code (CDC) of birth"
label variable hc32a_20 "Century Day Code (CDC) of birth"
label variable hc33_01  "Completeness of HC32 information"
label variable hc33_02  "Completeness of HC32 information"
label variable hc33_03  "Completeness of HC32 information"
label variable hc33_04  "Completeness of HC32 information"
label variable hc33_05  "Completeness of HC32 information"
label variable hc33_06  "Completeness of HC32 information"
label variable hc33_07  "Completeness of HC32 information"
label variable hc33_08  "Completeness of HC32 information"
label variable hc33_09  "Completeness of HC32 information"
label variable hc33_10  "Completeness of HC32 information"
label variable hc33_11  "Completeness of HC32 information"
label variable hc33_12  "Completeness of HC32 information"
label variable hc33_13  "Completeness of HC32 information"
label variable hc33_14  "Completeness of HC32 information"
label variable hc33_15  "Completeness of HC32 information"
label variable hc33_16  "Completeness of HC32 information"
label variable hc33_17  "Completeness of HC32 information"
label variable hc33_18  "Completeness of HC32 information"
label variable hc33_19  "Completeness of HC32 information"
label variable hc33_20  "Completeness of HC32 information"
label variable hc51_01  "Line number of parent/caretaker"
label variable hc51_02  "Line number of parent/caretaker"
label variable hc51_03  "Line number of parent/caretaker"
label variable hc51_04  "Line number of parent/caretaker"
label variable hc51_05  "Line number of parent/caretaker"
label variable hc51_06  "Line number of parent/caretaker"
label variable hc51_07  "Line number of parent/caretaker"
label variable hc51_08  "Line number of parent/caretaker"
label variable hc51_09  "Line number of parent/caretaker"
label variable hc51_10  "Line number of parent/caretaker"
label variable hc51_11  "Line number of parent/caretaker"
label variable hc51_12  "Line number of parent/caretaker"
label variable hc51_13  "Line number of parent/caretaker"
label variable hc51_14  "Line number of parent/caretaker"
label variable hc51_15  "Line number of parent/caretaker"
label variable hc51_16  "Line number of parent/caretaker"
label variable hc51_17  "Line number of parent/caretaker"
label variable hc51_18  "Line number of parent/caretaker"
label variable hc51_19  "Line number of parent/caretaker"
label variable hc51_20  "Line number of parent/caretaker"
label variable hc52_01  "Read consent statement - hemoglobin"
label variable hc52_02  "Read consent statement - hemoglobin"
label variable hc52_03  "Read consent statement - hemoglobin"
label variable hc52_04  "Read consent statement - hemoglobin"
label variable hc52_05  "Read consent statement - hemoglobin"
label variable hc52_06  "Read consent statement - hemoglobin"
label variable hc52_07  "Read consent statement - hemoglobin"
label variable hc52_08  "Read consent statement - hemoglobin"
label variable hc52_09  "Read consent statement - hemoglobin"
label variable hc52_10  "Read consent statement - hemoglobin"
label variable hc52_11  "Read consent statement - hemoglobin"
label variable hc52_12  "Read consent statement - hemoglobin"
label variable hc52_13  "Read consent statement - hemoglobin"
label variable hc52_14  "Read consent statement - hemoglobin"
label variable hc52_15  "Read consent statement - hemoglobin"
label variable hc52_16  "Read consent statement - hemoglobin"
label variable hc52_17  "Read consent statement - hemoglobin"
label variable hc52_18  "Read consent statement - hemoglobin"
label variable hc52_19  "Read consent statement - hemoglobin"
label variable hc52_20  "Read consent statement - hemoglobin"
label variable hc53_01  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_02  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_03  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_04  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_05  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_06  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_07  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_08  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_09  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_10  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_11  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_12  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_13  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_14  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_15  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_16  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_17  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_18  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_19  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_20  "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55_01  "Result of measurement - hemoglobin"
label variable hc55_02  "Result of measurement - hemoglobin"
label variable hc55_03  "Result of measurement - hemoglobin"
label variable hc55_04  "Result of measurement - hemoglobin"
label variable hc55_05  "Result of measurement - hemoglobin"
label variable hc55_06  "Result of measurement - hemoglobin"
label variable hc55_07  "Result of measurement - hemoglobin"
label variable hc55_08  "Result of measurement - hemoglobin"
label variable hc55_09  "Result of measurement - hemoglobin"
label variable hc55_10  "Result of measurement - hemoglobin"
label variable hc55_11  "Result of measurement - hemoglobin"
label variable hc55_12  "Result of measurement - hemoglobin"
label variable hc55_13  "Result of measurement - hemoglobin"
label variable hc55_14  "Result of measurement - hemoglobin"
label variable hc55_15  "Result of measurement - hemoglobin"
label variable hc55_16  "Result of measurement - hemoglobin"
label variable hc55_17  "Result of measurement - hemoglobin"
label variable hc55_18  "Result of measurement - hemoglobin"
label variable hc55_19  "Result of measurement - hemoglobin"
label variable hc55_20  "Result of measurement - hemoglobin"
label variable hc56_01  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_02  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_03  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_04  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_05  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_06  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_07  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_08  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_09  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_10  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_11  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_12  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_13  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_14  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_15  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_16  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_17  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_18  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_19  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_20  "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57_01  "Anemia level"
label variable hc57_02  "Anemia level"
label variable hc57_03  "Anemia level"
label variable hc57_04  "Anemia level"
label variable hc57_05  "Anemia level"
label variable hc57_06  "Anemia level"
label variable hc57_07  "Anemia level"
label variable hc57_08  "Anemia level"
label variable hc57_09  "Anemia level"
label variable hc57_10  "Anemia level"
label variable hc57_11  "Anemia level"
label variable hc57_12  "Anemia level"
label variable hc57_13  "Anemia level"
label variable hc57_14  "Anemia level"
label variable hc57_15  "Anemia level"
label variable hc57_16  "Anemia level"
label variable hc57_17  "Anemia level"
label variable hc57_18  "Anemia level"
label variable hc57_19  "Anemia level"
label variable hc57_20  "Anemia level"
label variable hc58_01  "NA - Agrees to referral - anemia"
label variable hc58_02  "NA - Agrees to referral - anemia"
label variable hc58_03  "NA - Agrees to referral - anemia"
label variable hc58_04  "NA - Agrees to referral - anemia"
label variable hc58_05  "NA - Agrees to referral - anemia"
label variable hc58_06  "NA - Agrees to referral - anemia"
label variable hc58_07  "NA - Agrees to referral - anemia"
label variable hc58_08  "NA - Agrees to referral - anemia"
label variable hc58_09  "NA - Agrees to referral - anemia"
label variable hc58_10  "NA - Agrees to referral - anemia"
label variable hc58_11  "NA - Agrees to referral - anemia"
label variable hc58_12  "NA - Agrees to referral - anemia"
label variable hc58_13  "NA - Agrees to referral - anemia"
label variable hc58_14  "NA - Agrees to referral - anemia"
label variable hc58_15  "NA - Agrees to referral - anemia"
label variable hc58_16  "NA - Agrees to referral - anemia"
label variable hc58_17  "NA - Agrees to referral - anemia"
label variable hc58_18  "NA - Agrees to referral - anemia"
label variable hc58_19  "NA - Agrees to referral - anemia"
label variable hc58_20  "NA - Agrees to referral - anemia"
label variable hc60_01  "Mother's line number (woman's questionnaire)"
label variable hc60_02  "Mother's line number (woman's questionnaire)"
label variable hc60_03  "Mother's line number (woman's questionnaire)"
label variable hc60_04  "Mother's line number (woman's questionnaire)"
label variable hc60_05  "Mother's line number (woman's questionnaire)"
label variable hc60_06  "Mother's line number (woman's questionnaire)"
label variable hc60_07  "Mother's line number (woman's questionnaire)"
label variable hc60_08  "Mother's line number (woman's questionnaire)"
label variable hc60_09  "Mother's line number (woman's questionnaire)"
label variable hc60_10  "Mother's line number (woman's questionnaire)"
label variable hc60_11  "Mother's line number (woman's questionnaire)"
label variable hc60_12  "Mother's line number (woman's questionnaire)"
label variable hc60_13  "Mother's line number (woman's questionnaire)"
label variable hc60_14  "Mother's line number (woman's questionnaire)"
label variable hc60_15  "Mother's line number (woman's questionnaire)"
label variable hc60_16  "Mother's line number (woman's questionnaire)"
label variable hc60_17  "Mother's line number (woman's questionnaire)"
label variable hc60_18  "Mother's line number (woman's questionnaire)"
label variable hc60_19  "Mother's line number (woman's questionnaire)"
label variable hc60_20  "Mother's line number (woman's questionnaire)"
label variable hc61_01  "Mother's highest educational level"
label variable hc61_02  "Mother's highest educational level"
label variable hc61_03  "Mother's highest educational level"
label variable hc61_04  "Mother's highest educational level"
label variable hc61_05  "Mother's highest educational level"
label variable hc61_06  "Mother's highest educational level"
label variable hc61_07  "Mother's highest educational level"
label variable hc61_08  "Mother's highest educational level"
label variable hc61_09  "Mother's highest educational level"
label variable hc61_10  "Mother's highest educational level"
label variable hc61_11  "Mother's highest educational level"
label variable hc61_12  "Mother's highest educational level"
label variable hc61_13  "Mother's highest educational level"
label variable hc61_14  "Mother's highest educational level"
label variable hc61_15  "Mother's highest educational level"
label variable hc61_16  "Mother's highest educational level"
label variable hc61_17  "Mother's highest educational level"
label variable hc61_18  "Mother's highest educational level"
label variable hc61_19  "Mother's highest educational level"
label variable hc61_20  "Mother's highest educational level"
label variable hc62_01  "Mother's highest year of education"
label variable hc62_02  "Mother's highest year of education"
label variable hc62_03  "Mother's highest year of education"
label variable hc62_04  "Mother's highest year of education"
label variable hc62_05  "Mother's highest year of education"
label variable hc62_06  "Mother's highest year of education"
label variable hc62_07  "Mother's highest year of education"
label variable hc62_08  "Mother's highest year of education"
label variable hc62_09  "Mother's highest year of education"
label variable hc62_10  "Mother's highest year of education"
label variable hc62_11  "Mother's highest year of education"
label variable hc62_12  "Mother's highest year of education"
label variable hc62_13  "Mother's highest year of education"
label variable hc62_14  "Mother's highest year of education"
label variable hc62_15  "Mother's highest year of education"
label variable hc62_16  "Mother's highest year of education"
label variable hc62_17  "Mother's highest year of education"
label variable hc62_18  "Mother's highest year of education"
label variable hc62_19  "Mother's highest year of education"
label variable hc62_20  "Mother's highest year of education"
label variable hc63_01  "Preceding birth interval (months)"
label variable hc63_02  "Preceding birth interval (months)"
label variable hc63_03  "Preceding birth interval (months)"
label variable hc63_04  "Preceding birth interval (months)"
label variable hc63_05  "Preceding birth interval (months)"
label variable hc63_06  "Preceding birth interval (months)"
label variable hc63_07  "Preceding birth interval (months)"
label variable hc63_08  "Preceding birth interval (months)"
label variable hc63_09  "Preceding birth interval (months)"
label variable hc63_10  "Preceding birth interval (months)"
label variable hc63_11  "Preceding birth interval (months)"
label variable hc63_12  "Preceding birth interval (months)"
label variable hc63_13  "Preceding birth interval (months)"
label variable hc63_14  "Preceding birth interval (months)"
label variable hc63_15  "Preceding birth interval (months)"
label variable hc63_16  "Preceding birth interval (months)"
label variable hc63_17  "Preceding birth interval (months)"
label variable hc63_18  "Preceding birth interval (months)"
label variable hc63_19  "Preceding birth interval (months)"
label variable hc63_20  "Preceding birth interval (months)"
label variable hc64_01  "Birth order number"
label variable hc64_02  "Birth order number"
label variable hc64_03  "Birth order number"
label variable hc64_04  "Birth order number"
label variable hc64_05  "Birth order number"
label variable hc64_06  "Birth order number"
label variable hc64_07  "Birth order number"
label variable hc64_08  "Birth order number"
label variable hc64_09  "Birth order number"
label variable hc64_10  "Birth order number"
label variable hc64_11  "Birth order number"
label variable hc64_12  "Birth order number"
label variable hc64_13  "Birth order number"
label variable hc64_14  "Birth order number"
label variable hc64_15  "Birth order number"
label variable hc64_16  "Birth order number"
label variable hc64_17  "Birth order number"
label variable hc64_18  "Birth order number"
label variable hc64_19  "Birth order number"
label variable hc64_20  "Birth order number"
label variable hc68_01  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_02  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_03  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_04  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_05  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_06  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_07  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_08  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_09  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_10  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_11  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_12  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_13  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_14  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_15  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_16  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_17  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_18  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_19  "Mother's highest educational level (for preliminary and final report)"
label variable hc68_20  "Mother's highest educational level (for preliminary and final report)"
label variable shc1_01  "Child's age in months ( country specific version of HC1 )"
label variable shc1_02  "Child's age in months ( country specific version of HC1 )"
label variable shc1_03  "Child's age in months ( country specific version of HC1 )"
label variable shc1_04  "Child's age in months ( country specific version of HC1 )"
label variable shc1_05  "Child's age in months ( country specific version of HC1 )"
label variable shc1_06  "Child's age in months ( country specific version of HC1 )"
label variable shc1_07  "Child's age in months ( country specific version of HC1 )"
label variable shc1_08  "Child's age in months ( country specific version of HC1 )"
label variable shc1_09  "Child's age in months ( country specific version of HC1 )"
label variable shc1_10  "Child's age in months ( country specific version of HC1 )"
label variable shc1_11  "Child's age in months ( country specific version of HC1 )"
label variable shc1_12  "Child's age in months ( country specific version of HC1 )"
label variable shc1_13  "Child's age in months ( country specific version of HC1 )"
label variable shc1_14  "Child's age in months ( country specific version of HC1 )"
label variable shc1_15  "Child's age in months ( country specific version of HC1 )"
label variable shc1_16  "Child's age in months ( country specific version of HC1 )"
label variable shc1_17  "Child's age in months ( country specific version of HC1 )"
label variable shc1_18  "Child's age in months ( country specific version of HC1 )"
label variable shc1_19  "Child's age in months ( country specific version of HC1 )"
label variable shc1_20  "Child's age in months ( country specific version of HC1 )"
label variable shc1a_01 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_02 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_03 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_04 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_05 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_06 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_07 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_08 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_09 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_10 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_11 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_12 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_13 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_14 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_15 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_16 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_17 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_18 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_19 "Child's age in days ( country specific version of HC1A )"
label variable shc1a_20 "Child's age in days ( country specific version of HC1A )"
label variable sb115a_01 "Illness or symptoms: extreme weakness"
label variable sb115a_02 "Illness or symptoms: extreme weakness"
label variable sb115a_03 "Illness or symptoms: extreme weakness"
label variable sb115a_04 "Illness or symptoms: extreme weakness"
label variable sb115a_05 "Illness or symptoms: extreme weakness"
label variable sb115a_06 "Illness or symptoms: extreme weakness"
label variable sb115a_07 "Illness or symptoms: extreme weakness"
label variable sb115a_08 "Illness or symptoms: extreme weakness"
label variable sb115a_09 "Illness or symptoms: extreme weakness"
label variable sb115a_10 "Illness or symptoms: extreme weakness"
label variable sb115a_11 "Illness or symptoms: extreme weakness"
label variable sb115a_12 "Illness or symptoms: extreme weakness"
label variable sb115a_13 "Illness or symptoms: extreme weakness"
label variable sb115a_14 "Illness or symptoms: extreme weakness"
label variable sb115a_15 "Illness or symptoms: extreme weakness"
label variable sb115a_16 "Illness or symptoms: extreme weakness"
label variable sb115a_17 "Illness or symptoms: extreme weakness"
label variable sb115a_18 "Illness or symptoms: extreme weakness"
label variable sb115a_19 "Illness or symptoms: extreme weakness"
label variable sb115a_20 "Illness or symptoms: extreme weakness"
label variable sb115b_01 "Illness or symptoms: heart problems"
label variable sb115b_02 "Illness or symptoms: heart problems"
label variable sb115b_03 "Illness or symptoms: heart problems"
label variable sb115b_04 "Illness or symptoms: heart problems"
label variable sb115b_05 "Illness or symptoms: heart problems"
label variable sb115b_06 "Illness or symptoms: heart problems"
label variable sb115b_07 "Illness or symptoms: heart problems"
label variable sb115b_08 "Illness or symptoms: heart problems"
label variable sb115b_09 "Illness or symptoms: heart problems"
label variable sb115b_10 "Illness or symptoms: heart problems"
label variable sb115b_11 "Illness or symptoms: heart problems"
label variable sb115b_12 "Illness or symptoms: heart problems"
label variable sb115b_13 "Illness or symptoms: heart problems"
label variable sb115b_14 "Illness or symptoms: heart problems"
label variable sb115b_15 "Illness or symptoms: heart problems"
label variable sb115b_16 "Illness or symptoms: heart problems"
label variable sb115b_17 "Illness or symptoms: heart problems"
label variable sb115b_18 "Illness or symptoms: heart problems"
label variable sb115b_19 "Illness or symptoms: heart problems"
label variable sb115b_20 "Illness or symptoms: heart problems"
label variable sb115c_01 "Illness or symptoms: loss of consciousness"
label variable sb115c_02 "Illness or symptoms: loss of consciousness"
label variable sb115c_03 "Illness or symptoms: loss of consciousness"
label variable sb115c_04 "Illness or symptoms: loss of consciousness"
label variable sb115c_05 "Illness or symptoms: loss of consciousness"
label variable sb115c_06 "Illness or symptoms: loss of consciousness"
label variable sb115c_07 "Illness or symptoms: loss of consciousness"
label variable sb115c_08 "Illness or symptoms: loss of consciousness"
label variable sb115c_09 "Illness or symptoms: loss of consciousness"
label variable sb115c_10 "Illness or symptoms: loss of consciousness"
label variable sb115c_11 "Illness or symptoms: loss of consciousness"
label variable sb115c_12 "Illness or symptoms: loss of consciousness"
label variable sb115c_13 "Illness or symptoms: loss of consciousness"
label variable sb115c_14 "Illness or symptoms: loss of consciousness"
label variable sb115c_15 "Illness or symptoms: loss of consciousness"
label variable sb115c_16 "Illness or symptoms: loss of consciousness"
label variable sb115c_17 "Illness or symptoms: loss of consciousness"
label variable sb115c_18 "Illness or symptoms: loss of consciousness"
label variable sb115c_19 "Illness or symptoms: loss of consciousness"
label variable sb115c_20 "Illness or symptoms: loss of consciousness"
label variable sb115d_01 "Illness or symptoms: rapid breathing"
label variable sb115d_02 "Illness or symptoms: rapid breathing"
label variable sb115d_03 "Illness or symptoms: rapid breathing"
label variable sb115d_04 "Illness or symptoms: rapid breathing"
label variable sb115d_05 "Illness or symptoms: rapid breathing"
label variable sb115d_06 "Illness or symptoms: rapid breathing"
label variable sb115d_07 "Illness or symptoms: rapid breathing"
label variable sb115d_08 "Illness or symptoms: rapid breathing"
label variable sb115d_09 "Illness or symptoms: rapid breathing"
label variable sb115d_10 "Illness or symptoms: rapid breathing"
label variable sb115d_11 "Illness or symptoms: rapid breathing"
label variable sb115d_12 "Illness or symptoms: rapid breathing"
label variable sb115d_13 "Illness or symptoms: rapid breathing"
label variable sb115d_14 "Illness or symptoms: rapid breathing"
label variable sb115d_15 "Illness or symptoms: rapid breathing"
label variable sb115d_16 "Illness or symptoms: rapid breathing"
label variable sb115d_17 "Illness or symptoms: rapid breathing"
label variable sb115d_18 "Illness or symptoms: rapid breathing"
label variable sb115d_19 "Illness or symptoms: rapid breathing"
label variable sb115d_20 "Illness or symptoms: rapid breathing"
label variable sb115e_01 "Illness or symptoms: seizures"
label variable sb115e_02 "Illness or symptoms: seizures"
label variable sb115e_03 "Illness or symptoms: seizures"
label variable sb115e_04 "Illness or symptoms: seizures"
label variable sb115e_05 "Illness or symptoms: seizures"
label variable sb115e_06 "Illness or symptoms: seizures"
label variable sb115e_07 "Illness or symptoms: seizures"
label variable sb115e_08 "Illness or symptoms: seizures"
label variable sb115e_09 "Illness or symptoms: seizures"
label variable sb115e_10 "Illness or symptoms: seizures"
label variable sb115e_11 "Illness or symptoms: seizures"
label variable sb115e_12 "Illness or symptoms: seizures"
label variable sb115e_13 "Illness or symptoms: seizures"
label variable sb115e_14 "Illness or symptoms: seizures"
label variable sb115e_15 "Illness or symptoms: seizures"
label variable sb115e_16 "Illness or symptoms: seizures"
label variable sb115e_17 "Illness or symptoms: seizures"
label variable sb115e_18 "Illness or symptoms: seizures"
label variable sb115e_19 "Illness or symptoms: seizures"
label variable sb115e_20 "Illness or symptoms: seizures"
label variable sb115f_01 "Illness or symptoms: bleeding"
label variable sb115f_02 "Illness or symptoms: bleeding"
label variable sb115f_03 "Illness or symptoms: bleeding"
label variable sb115f_04 "Illness or symptoms: bleeding"
label variable sb115f_05 "Illness or symptoms: bleeding"
label variable sb115f_06 "Illness or symptoms: bleeding"
label variable sb115f_07 "Illness or symptoms: bleeding"
label variable sb115f_08 "Illness or symptoms: bleeding"
label variable sb115f_09 "Illness or symptoms: bleeding"
label variable sb115f_10 "Illness or symptoms: bleeding"
label variable sb115f_11 "Illness or symptoms: bleeding"
label variable sb115f_12 "Illness or symptoms: bleeding"
label variable sb115f_13 "Illness or symptoms: bleeding"
label variable sb115f_14 "Illness or symptoms: bleeding"
label variable sb115f_15 "Illness or symptoms: bleeding"
label variable sb115f_16 "Illness or symptoms: bleeding"
label variable sb115f_17 "Illness or symptoms: bleeding"
label variable sb115f_18 "Illness or symptoms: bleeding"
label variable sb115f_19 "Illness or symptoms: bleeding"
label variable sb115f_20 "Illness or symptoms: bleeding"
label variable sb115g_01 "Illness or symptoms: jaundice"
label variable sb115g_02 "Illness or symptoms: jaundice"
label variable sb115g_03 "Illness or symptoms: jaundice"
label variable sb115g_04 "Illness or symptoms: jaundice"
label variable sb115g_05 "Illness or symptoms: jaundice"
label variable sb115g_06 "Illness or symptoms: jaundice"
label variable sb115g_07 "Illness or symptoms: jaundice"
label variable sb115g_08 "Illness or symptoms: jaundice"
label variable sb115g_09 "Illness or symptoms: jaundice"
label variable sb115g_10 "Illness or symptoms: jaundice"
label variable sb115g_11 "Illness or symptoms: jaundice"
label variable sb115g_12 "Illness or symptoms: jaundice"
label variable sb115g_13 "Illness or symptoms: jaundice"
label variable sb115g_14 "Illness or symptoms: jaundice"
label variable sb115g_15 "Illness or symptoms: jaundice"
label variable sb115g_16 "Illness or symptoms: jaundice"
label variable sb115g_17 "Illness or symptoms: jaundice"
label variable sb115g_18 "Illness or symptoms: jaundice"
label variable sb115g_19 "Illness or symptoms: jaundice"
label variable sb115g_20 "Illness or symptoms: jaundice"
label variable sb115h_01 "Illness or symptoms: dark urine"
label variable sb115h_02 "Illness or symptoms: dark urine"
label variable sb115h_03 "Illness or symptoms: dark urine"
label variable sb115h_04 "Illness or symptoms: dark urine"
label variable sb115h_05 "Illness or symptoms: dark urine"
label variable sb115h_06 "Illness or symptoms: dark urine"
label variable sb115h_07 "Illness or symptoms: dark urine"
label variable sb115h_08 "Illness or symptoms: dark urine"
label variable sb115h_09 "Illness or symptoms: dark urine"
label variable sb115h_10 "Illness or symptoms: dark urine"
label variable sb115h_11 "Illness or symptoms: dark urine"
label variable sb115h_12 "Illness or symptoms: dark urine"
label variable sb115h_13 "Illness or symptoms: dark urine"
label variable sb115h_14 "Illness or symptoms: dark urine"
label variable sb115h_15 "Illness or symptoms: dark urine"
label variable sb115h_16 "Illness or symptoms: dark urine"
label variable sb115h_17 "Illness or symptoms: dark urine"
label variable sb115h_18 "Illness or symptoms: dark urine"
label variable sb115h_19 "Illness or symptoms: dark urine"
label variable sb115h_20 "Illness or symptoms: dark urine"
label variable sb119_01 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_02 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_03 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_04 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_05 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_06 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_07 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_08 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_09 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_10 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_11 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_12 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_13 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_14 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_15 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_16 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_17 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_18 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_19 "Taken ACT for malaria treatment in the past two weeks"
label variable sb119_20 "Taken ACT for malaria treatment in the past two weeks"
label variable sb122_01 "Accepted medicine"
label variable sb122_02 "Accepted medicine"
label variable sb122_03 "Accepted medicine"
label variable sb122_04 "Accepted medicine"
label variable sb122_05 "Accepted medicine"
label variable sb122_06 "Accepted medicine"
label variable sb122_07 "Accepted medicine"
label variable sb122_08 "Accepted medicine"
label variable sb122_09 "Accepted medicine"
label variable sb122_10 "Accepted medicine"
label variable sb122_11 "Accepted medicine"
label variable sb122_12 "Accepted medicine"
label variable sb122_13 "Accepted medicine"
label variable sb122_14 "Accepted medicine"
label variable sb122_15 "Accepted medicine"
label variable sb122_16 "Accepted medicine"
label variable sb122_17 "Accepted medicine"
label variable sb122_18 "Accepted medicine"
label variable sb122_19 "Accepted medicine"
label variable sb122_20 "Accepted medicine"
label variable sb123_01 "Fieldworker number for malaria medicine"
label variable sb123_02 "Fieldworker number for malaria medicine"
label variable sb123_03 "Fieldworker number for malaria medicine"
label variable sb123_04 "Fieldworker number for malaria medicine"
label variable sb123_05 "Fieldworker number for malaria medicine"
label variable sb123_06 "Fieldworker number for malaria medicine"
label variable sb123_07 "Fieldworker number for malaria medicine"
label variable sb123_08 "Fieldworker number for malaria medicine"
label variable sb123_09 "Fieldworker number for malaria medicine"
label variable sb123_10 "Fieldworker number for malaria medicine"
label variable sb123_11 "Fieldworker number for malaria medicine"
label variable sb123_12 "Fieldworker number for malaria medicine"
label variable sb123_13 "Fieldworker number for malaria medicine"
label variable sb123_14 "Fieldworker number for malaria medicine"
label variable sb123_15 "Fieldworker number for malaria medicine"
label variable sb123_16 "Fieldworker number for malaria medicine"
label variable sb123_17 "Fieldworker number for malaria medicine"
label variable sb123_18 "Fieldworker number for malaria medicine"
label variable sb123_19 "Fieldworker number for malaria medicine"
label variable sb123_20 "Fieldworker number for malaria medicine"
label variable sb128d_01 "Day of data collection"
label variable sb128d_02 "Day of data collection"
label variable sb128d_03 "Day of data collection"
label variable sb128d_04 "Day of data collection"
label variable sb128d_05 "Day of data collection"
label variable sb128d_06 "Day of data collection"
label variable sb128d_07 "Day of data collection"
label variable sb128d_08 "Day of data collection"
label variable sb128d_09 "Day of data collection"
label variable sb128d_10 "Day of data collection"
label variable sb128d_11 "Day of data collection"
label variable sb128d_12 "Day of data collection"
label variable sb128d_13 "Day of data collection"
label variable sb128d_14 "Day of data collection"
label variable sb128d_15 "Day of data collection"
label variable sb128d_16 "Day of data collection"
label variable sb128d_17 "Day of data collection"
label variable sb128d_18 "Day of data collection"
label variable sb128d_19 "Day of data collection"
label variable sb128d_20 "Day of data collection"
label variable sb128m_01 "Month of data collection"
label variable sb128m_02 "Month of data collection"
label variable sb128m_03 "Month of data collection"
label variable sb128m_04 "Month of data collection"
label variable sb128m_05 "Month of data collection"
label variable sb128m_06 "Month of data collection"
label variable sb128m_07 "Month of data collection"
label variable sb128m_08 "Month of data collection"
label variable sb128m_09 "Month of data collection"
label variable sb128m_10 "Month of data collection"
label variable sb128m_11 "Month of data collection"
label variable sb128m_12 "Month of data collection"
label variable sb128m_13 "Month of data collection"
label variable sb128m_14 "Month of data collection"
label variable sb128m_15 "Month of data collection"
label variable sb128m_16 "Month of data collection"
label variable sb128m_17 "Month of data collection"
label variable sb128m_18 "Month of data collection"
label variable sb128m_19 "Month of data collection"
label variable sb128m_20 "Month of data collection"
label variable sb128y_01 "Year of data collection"
label variable sb128y_02 "Year of data collection"
label variable sb128y_03 "Year of data collection"
label variable sb128y_04 "Year of data collection"
label variable sb128y_05 "Year of data collection"
label variable sb128y_06 "Year of data collection"
label variable sb128y_07 "Year of data collection"
label variable sb128y_08 "Year of data collection"
label variable sb128y_09 "Year of data collection"
label variable sb128y_10 "Year of data collection"
label variable sb128y_11 "Year of data collection"
label variable sb128y_12 "Year of data collection"
label variable sb128y_13 "Year of data collection"
label variable sb128y_14 "Year of data collection"
label variable sb128y_15 "Year of data collection"
label variable sb128y_16 "Year of data collection"
label variable sb128y_17 "Year of data collection"
label variable sb128y_18 "Year of data collection"
label variable sb128y_19 "Year of data collection"
label variable sb128y_20 "Year of data collection"
label variable hmlidx_1 "Mosquito Bed Net Designation Number"
label variable hmlidx_2 "Mosquito Bed Net Designation Number"
label variable hmlidx_3 "Mosquito Bed Net Designation Number"
label variable hmlidx_4 "Mosquito Bed Net Designation Number"
label variable hmlidx_5 "Mosquito Bed Net Designation Number"
label variable hmlidx_6 "Mosquito Bed Net Designation Number"
label variable hmlidx_7 "Mosquito Bed Net Designation Number"
label variable hml3_1   "Net observed by interviewer"
label variable hml3_2   "Net observed by interviewer"
label variable hml3_3   "Net observed by interviewer"
label variable hml3_4   "Net observed by interviewer"
label variable hml3_5   "Net observed by interviewer"
label variable hml3_6   "Net observed by interviewer"
label variable hml3_7   "Net observed by interviewer"
label variable hml4_1   "Months ago net obtained"
label variable hml4_2   "Months ago net obtained"
label variable hml4_3   "Months ago net obtained"
label variable hml4_4   "Months ago net obtained"
label variable hml4_5   "Months ago net obtained"
label variable hml4_6   "Months ago net obtained"
label variable hml4_7   "Months ago net obtained"
label variable hml5_1   "NA - Net treated with insecticide when bought"
label variable hml5_2   "NA - Net treated with insecticide when bought"
label variable hml5_3   "NA - Net treated with insecticide when bought"
label variable hml5_4   "NA - Net treated with insecticide when bought"
label variable hml5_5   "NA - Net treated with insecticide when bought"
label variable hml5_6   "NA - Net treated with insecticide when bought"
label variable hml5_7   "NA - Net treated with insecticide when bought"
label variable hml6_1   "NA - Net treatment status"
label variable hml6_2   "NA - Net treatment status"
label variable hml6_3   "NA - Net treatment status"
label variable hml6_4   "NA - Net treatment status"
label variable hml6_5   "NA - Net treatment status"
label variable hml6_6   "NA - Net treatment status"
label variable hml6_7   "NA - Net treatment status"
label variable hml7_1   "Brand of net"
label variable hml7_2   "Brand of net"
label variable hml7_3   "Brand of net"
label variable hml7_4   "Brand of net"
label variable hml7_5   "Brand of net"
label variable hml7_6   "Brand of net"
label variable hml7_7   "Brand of net"
label variable hml8_1   "NA - Net treated since received"
label variable hml8_2   "NA - Net treated since received"
label variable hml8_3   "NA - Net treated since received"
label variable hml8_4   "NA - Net treated since received"
label variable hml8_5   "NA - Net treated since received"
label variable hml8_6   "NA - Net treated since received"
label variable hml8_7   "NA - Net treated since received"
label variable hml9_1   "NA - Time since last re-treatment (months)"
label variable hml9_2   "NA - Time since last re-treatment (months)"
label variable hml9_3   "NA - Time since last re-treatment (months)"
label variable hml9_4   "NA - Time since last re-treatment (months)"
label variable hml9_5   "NA - Time since last re-treatment (months)"
label variable hml9_6   "NA - Time since last re-treatment (months)"
label variable hml9_7   "NA - Time since last re-treatment (months)"
label variable hml10_1  "Insecticide-Treated Net (ITN)"
label variable hml10_2  "Insecticide-Treated Net (ITN)"
label variable hml10_3  "Insecticide-Treated Net (ITN)"
label variable hml10_4  "Insecticide-Treated Net (ITN)"
label variable hml10_5  "Insecticide-Treated Net (ITN)"
label variable hml10_6  "Insecticide-Treated Net (ITN)"
label variable hml10_7  "Insecticide-Treated Net (ITN)"
label variable hml11_1  "Number of persons who slept under this net"
label variable hml11_2  "Number of persons who slept under this net"
label variable hml11_3  "Number of persons who slept under this net"
label variable hml11_4  "Number of persons who slept under this net"
label variable hml11_5  "Number of persons who slept under this net"
label variable hml11_6  "Number of persons who slept under this net"
label variable hml11_7  "Number of persons who slept under this net"
label variable hml21_1  "Someone slept under this net last night"
label variable hml21_2  "Someone slept under this net last night"
label variable hml21_3  "Someone slept under this net last night"
label variable hml21_4  "Someone slept under this net last night"
label variable hml21_5  "Someone slept under this net last night"
label variable hml21_6  "Someone slept under this net last night"
label variable hml21_7  "Someone slept under this net last night"
label variable hmla_1   "Line number of person who slept in this net"
label variable hmla_2   "Line number of person who slept in this net"
label variable hmla_3   "Line number of person who slept in this net"
label variable hmla_4   "Line number of person who slept in this net"
label variable hmla_5   "Line number of person who slept in this net"
label variable hmla_6   "Line number of person who slept in this net"
label variable hmla_7   "Line number of person who slept in this net"
label variable hmlb_1   "Line number of person who slept in this net"
label variable hmlb_2   "Line number of person who slept in this net"
label variable hmlb_3   "Line number of person who slept in this net"
label variable hmlb_4   "Line number of person who slept in this net"
label variable hmlb_5   "Line number of person who slept in this net"
label variable hmlb_6   "Line number of person who slept in this net"
label variable hmlb_7   "Line number of person who slept in this net"
label variable hmlc_1   "Line number of person who slept in this net"
label variable hmlc_2   "Line number of person who slept in this net"
label variable hmlc_3   "Line number of person who slept in this net"
label variable hmlc_4   "Line number of person who slept in this net"
label variable hmlc_5   "Line number of person who slept in this net"
label variable hmlc_6   "Line number of person who slept in this net"
label variable hmlc_7   "Line number of person who slept in this net"
label variable hmld_1   "Line number of person who slept in this net"
label variable hmld_2   "Line number of person who slept in this net"
label variable hmld_3   "Line number of person who slept in this net"
label variable hmld_4   "Line number of person who slept in this net"
label variable hmld_5   "Line number of person who slept in this net"
label variable hmld_6   "Line number of person who slept in this net"
label variable hmld_7   "Line number of person who slept in this net"
label variable hmle_1   "NA - Line number of person who slept in this net"
label variable hmle_2   "NA - Line number of person who slept in this net"
label variable hmle_3   "NA - Line number of person who slept in this net"
label variable hmle_4   "NA - Line number of person who slept in this net"
label variable hmle_5   "NA - Line number of person who slept in this net"
label variable hmle_6   "NA - Line number of person who slept in this net"
label variable hmle_7   "NA - Line number of person who slept in this net"
label variable hml22_1  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_2  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_3  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_4  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_5  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_6  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_7  "Obtained net from campaign, antenatal or immunization visit"
label variable hml23_1  "Place where net was obtained"
label variable hml23_2  "Place where net was obtained"
label variable hml23_3  "Place where net was obtained"
label variable hml23_4  "Place where net was obtained"
label variable hml23_5  "Place where net was obtained"
label variable hml23_6  "Place where net was obtained"
label variable hml23_7  "Place where net was obtained"
label variable sh130_1  "Main reason bed net not used"
label variable sh130_2  "Main reason bed net not used"
label variable sh130_3  "Main reason bed net not used"
label variable sh130_4  "Main reason bed net not used"
label variable sh130_5  "Main reason bed net not used"
label variable sh130_6  "Main reason bed net not used"
label variable sh130_7  "Main reason bed net not used"
label variable hmhidx_01 "Index to Household Schedule"
label variable hmhidx_02 "Index to Household Schedule"
label variable hmhidx_03 "Index to Household Schedule"
label variable hmhidx_04 "Index to Household Schedule"
label variable hmhidx_05 "Index to Household Schedule"
label variable hmhidx_06 "Index to Household Schedule"
label variable hmhidx_07 "Index to Household Schedule"
label variable hmhidx_08 "Index to Household Schedule"
label variable hmhidx_09 "Index to Household Schedule"
label variable hmhidx_10 "Index to Household Schedule"
label variable hmhidx_11 "Index to Household Schedule"
label variable hmhidx_12 "Index to Household Schedule"
label variable hmhidx_13 "Index to Household Schedule"
label variable hmhidx_14 "Index to Household Schedule"
label variable hmhidx_15 "Index to Household Schedule"
label variable hmhidx_16 "Index to Household Schedule"
label variable hmhidx_17 "Index to Household Schedule"
label variable hmhidx_18 "Index to Household Schedule"
label variable hmhidx_19 "Index to Household Schedule"
label variable hmhidx_20 "Index to Household Schedule"
label variable hmhidx_21 "Index to Household Schedule"
label variable hmhidx_22 "Index to Household Schedule"
label variable hmhidx_23 "Index to Household Schedule"
label variable hmhidx_24 "Index to Household Schedule"
label variable hml12_01 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_02 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_03 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_04 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_05 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_06 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_07 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_08 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_09 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_10 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_11 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_12 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_13 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_14 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_15 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_16 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_17 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_18 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_19 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_20 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_21 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_22 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_23 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_24 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml13_01 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_02 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_03 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_04 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_05 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_06 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_07 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_08 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_09 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_10 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_11 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_12 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_13 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_14 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_15 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_16 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_17 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_18 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_19 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_20 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_21 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_22 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_23 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_24 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml14_01 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_02 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_03 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_04 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_05 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_06 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_07 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_08 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_09 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_10 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_11 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_12 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_13 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_14 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_15 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_16 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_17 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_18 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_19 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_20 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_21 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_22 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_23 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_24 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml15_01 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_02 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_03 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_04 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_05 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_06 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_07 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_08 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_09 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_10 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_11 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_12 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_13 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_14 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_15 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_16 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_17 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_18 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_19 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_20 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_21 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_22 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_23 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_24 "Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml16_01 "Corrected age from Individual file"
label variable hml16_02 "Corrected age from Individual file"
label variable hml16_03 "Corrected age from Individual file"
label variable hml16_04 "Corrected age from Individual file"
label variable hml16_05 "Corrected age from Individual file"
label variable hml16_06 "Corrected age from Individual file"
label variable hml16_07 "Corrected age from Individual file"
label variable hml16_08 "Corrected age from Individual file"
label variable hml16_09 "Corrected age from Individual file"
label variable hml16_10 "Corrected age from Individual file"
label variable hml16_11 "Corrected age from Individual file"
label variable hml16_12 "Corrected age from Individual file"
label variable hml16_13 "Corrected age from Individual file"
label variable hml16_14 "Corrected age from Individual file"
label variable hml16_15 "Corrected age from Individual file"
label variable hml16_16 "Corrected age from Individual file"
label variable hml16_17 "Corrected age from Individual file"
label variable hml16_18 "Corrected age from Individual file"
label variable hml16_19 "Corrected age from Individual file"
label variable hml16_20 "Corrected age from Individual file"
label variable hml16_21 "Corrected age from Individual file"
label variable hml16_22 "Corrected age from Individual file"
label variable hml16_23 "Corrected age from Individual file"
label variable hml16_24 "Corrected age from Individual file"
label variable hml16a_01 "Age in months (for children)"
label variable hml16a_02 "Age in months (for children)"
label variable hml16a_03 "Age in months (for children)"
label variable hml16a_04 "Age in months (for children)"
label variable hml16a_05 "Age in months (for children)"
label variable hml16a_06 "Age in months (for children)"
label variable hml16a_07 "Age in months (for children)"
label variable hml16a_08 "Age in months (for children)"
label variable hml16a_09 "Age in months (for children)"
label variable hml16a_10 "Age in months (for children)"
label variable hml16a_11 "Age in months (for children)"
label variable hml16a_12 "Age in months (for children)"
label variable hml16a_13 "Age in months (for children)"
label variable hml16a_14 "Age in months (for children)"
label variable hml16a_15 "Age in months (for children)"
label variable hml16a_16 "Age in months (for children)"
label variable hml16a_17 "Age in months (for children)"
label variable hml16a_18 "Age in months (for children)"
label variable hml16a_19 "Age in months (for children)"
label variable hml16a_20 "Age in months (for children)"
label variable hml16a_21 "Age in months (for children)"
label variable hml16a_22 "Age in months (for children)"
label variable hml16a_23 "Age in months (for children)"
label variable hml16a_24 "Age in months (for children)"
label variable hml17_01 "Flag for age from Individual file"
label variable hml17_02 "Flag for age from Individual file"
label variable hml17_03 "Flag for age from Individual file"
label variable hml17_04 "Flag for age from Individual file"
label variable hml17_05 "Flag for age from Individual file"
label variable hml17_06 "Flag for age from Individual file"
label variable hml17_07 "Flag for age from Individual file"
label variable hml17_08 "Flag for age from Individual file"
label variable hml17_09 "Flag for age from Individual file"
label variable hml17_10 "Flag for age from Individual file"
label variable hml17_11 "Flag for age from Individual file"
label variable hml17_12 "Flag for age from Individual file"
label variable hml17_13 "Flag for age from Individual file"
label variable hml17_14 "Flag for age from Individual file"
label variable hml17_15 "Flag for age from Individual file"
label variable hml17_16 "Flag for age from Individual file"
label variable hml17_17 "Flag for age from Individual file"
label variable hml17_18 "Flag for age from Individual file"
label variable hml17_19 "Flag for age from Individual file"
label variable hml17_20 "Flag for age from Individual file"
label variable hml17_21 "Flag for age from Individual file"
label variable hml17_22 "Flag for age from Individual file"
label variable hml17_23 "Flag for age from Individual file"
label variable hml17_24 "Flag for age from Individual file"
label variable hml18_01 "Pregnancy status from Individual file"
label variable hml18_02 "Pregnancy status from Individual file"
label variable hml18_03 "Pregnancy status from Individual file"
label variable hml18_04 "Pregnancy status from Individual file"
label variable hml18_05 "Pregnancy status from Individual file"
label variable hml18_06 "Pregnancy status from Individual file"
label variable hml18_07 "Pregnancy status from Individual file"
label variable hml18_08 "Pregnancy status from Individual file"
label variable hml18_09 "Pregnancy status from Individual file"
label variable hml18_10 "Pregnancy status from Individual file"
label variable hml18_11 "Pregnancy status from Individual file"
label variable hml18_12 "Pregnancy status from Individual file"
label variable hml18_13 "Pregnancy status from Individual file"
label variable hml18_14 "Pregnancy status from Individual file"
label variable hml18_15 "Pregnancy status from Individual file"
label variable hml18_16 "Pregnancy status from Individual file"
label variable hml18_17 "Pregnancy status from Individual file"
label variable hml18_18 "Pregnancy status from Individual file"
label variable hml18_19 "Pregnancy status from Individual file"
label variable hml18_20 "Pregnancy status from Individual file"
label variable hml18_21 "Pregnancy status from Individual file"
label variable hml18_22 "Pregnancy status from Individual file"
label variable hml18_23 "Pregnancy status from Individual file"
label variable hml18_24 "Pregnancy status from Individual file"
label variable hml19_01 "Person slept under an ever-treated net"
label variable hml19_02 "Person slept under an ever-treated net"
label variable hml19_03 "Person slept under an ever-treated net"
label variable hml19_04 "Person slept under an ever-treated net"
label variable hml19_05 "Person slept under an ever-treated net"
label variable hml19_06 "Person slept under an ever-treated net"
label variable hml19_07 "Person slept under an ever-treated net"
label variable hml19_08 "Person slept under an ever-treated net"
label variable hml19_09 "Person slept under an ever-treated net"
label variable hml19_10 "Person slept under an ever-treated net"
label variable hml19_11 "Person slept under an ever-treated net"
label variable hml19_12 "Person slept under an ever-treated net"
label variable hml19_13 "Person slept under an ever-treated net"
label variable hml19_14 "Person slept under an ever-treated net"
label variable hml19_15 "Person slept under an ever-treated net"
label variable hml19_16 "Person slept under an ever-treated net"
label variable hml19_17 "Person slept under an ever-treated net"
label variable hml19_18 "Person slept under an ever-treated net"
label variable hml19_19 "Person slept under an ever-treated net"
label variable hml19_20 "Person slept under an ever-treated net"
label variable hml19_21 "Person slept under an ever-treated net"
label variable hml19_22 "Person slept under an ever-treated net"
label variable hml19_23 "Person slept under an ever-treated net"
label variable hml19_24 "Person slept under an ever-treated net"
label variable hml20_01 "Person slept under an LLIN net"
label variable hml20_02 "Person slept under an LLIN net"
label variable hml20_03 "Person slept under an LLIN net"
label variable hml20_04 "Person slept under an LLIN net"
label variable hml20_05 "Person slept under an LLIN net"
label variable hml20_06 "Person slept under an LLIN net"
label variable hml20_07 "Person slept under an LLIN net"
label variable hml20_08 "Person slept under an LLIN net"
label variable hml20_09 "Person slept under an LLIN net"
label variable hml20_10 "Person slept under an LLIN net"
label variable hml20_11 "Person slept under an LLIN net"
label variable hml20_12 "Person slept under an LLIN net"
label variable hml20_13 "Person slept under an LLIN net"
label variable hml20_14 "Person slept under an LLIN net"
label variable hml20_15 "Person slept under an LLIN net"
label variable hml20_16 "Person slept under an LLIN net"
label variable hml20_17 "Person slept under an LLIN net"
label variable hml20_18 "Person slept under an LLIN net"
label variable hml20_19 "Person slept under an LLIN net"
label variable hml20_20 "Person slept under an LLIN net"
label variable hml20_21 "Person slept under an LLIN net"
label variable hml20_22 "Person slept under an LLIN net"
label variable hml20_23 "Person slept under an LLIN net"
label variable hml20_24 "Person slept under an LLIN net"
label variable hml30_01 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_02 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_03 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_04 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_05 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_06 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_07 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_08 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_09 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_10 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_11 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_12 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_13 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_14 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_15 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_16 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_17 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_18 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_19 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_20 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_21 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_22 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_23 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_24 "Line number of parent/caretaker (for malaria testing)"
label variable hml31_01 "Read consent statement for malaria"
label variable hml31_02 "Read consent statement for malaria"
label variable hml31_03 "Read consent statement for malaria"
label variable hml31_04 "Read consent statement for malaria"
label variable hml31_05 "Read consent statement for malaria"
label variable hml31_06 "Read consent statement for malaria"
label variable hml31_07 "Read consent statement for malaria"
label variable hml31_08 "Read consent statement for malaria"
label variable hml31_09 "Read consent statement for malaria"
label variable hml31_10 "Read consent statement for malaria"
label variable hml31_11 "Read consent statement for malaria"
label variable hml31_12 "Read consent statement for malaria"
label variable hml31_13 "Read consent statement for malaria"
label variable hml31_14 "Read consent statement for malaria"
label variable hml31_15 "Read consent statement for malaria"
label variable hml31_16 "Read consent statement for malaria"
label variable hml31_17 "Read consent statement for malaria"
label variable hml31_18 "Read consent statement for malaria"
label variable hml31_19 "Read consent statement for malaria"
label variable hml31_20 "Read consent statement for malaria"
label variable hml31_21 "Read consent statement for malaria"
label variable hml31_22 "Read consent statement for malaria"
label variable hml31_23 "Read consent statement for malaria"
label variable hml31_24 "Read consent statement for malaria"
label variable hml32_01 "Final result of malaria from blood smear test"
label variable hml32_02 "Final result of malaria from blood smear test"
label variable hml32_03 "Final result of malaria from blood smear test"
label variable hml32_04 "Final result of malaria from blood smear test"
label variable hml32_05 "Final result of malaria from blood smear test"
label variable hml32_06 "Final result of malaria from blood smear test"
label variable hml32_07 "Final result of malaria from blood smear test"
label variable hml32_08 "Final result of malaria from blood smear test"
label variable hml32_09 "Final result of malaria from blood smear test"
label variable hml32_10 "Final result of malaria from blood smear test"
label variable hml32_11 "Final result of malaria from blood smear test"
label variable hml32_12 "Final result of malaria from blood smear test"
label variable hml32_13 "Final result of malaria from blood smear test"
label variable hml32_14 "Final result of malaria from blood smear test"
label variable hml32_15 "Final result of malaria from blood smear test"
label variable hml32_16 "Final result of malaria from blood smear test"
label variable hml32_17 "Final result of malaria from blood smear test"
label variable hml32_18 "Final result of malaria from blood smear test"
label variable hml32_19 "Final result of malaria from blood smear test"
label variable hml32_20 "Final result of malaria from blood smear test"
label variable hml32_21 "Final result of malaria from blood smear test"
label variable hml32_22 "Final result of malaria from blood smear test"
label variable hml32_23 "Final result of malaria from blood smear test"
label variable hml32_24 "Final result of malaria from blood smear test"
label variable hml32a_01 "Presence of species: falciparum (Pf)"
label variable hml32a_02 "Presence of species: falciparum (Pf)"
label variable hml32a_03 "Presence of species: falciparum (Pf)"
label variable hml32a_04 "Presence of species: falciparum (Pf)"
label variable hml32a_05 "Presence of species: falciparum (Pf)"
label variable hml32a_06 "Presence of species: falciparum (Pf)"
label variable hml32a_07 "Presence of species: falciparum (Pf)"
label variable hml32a_08 "Presence of species: falciparum (Pf)"
label variable hml32a_09 "Presence of species: falciparum (Pf)"
label variable hml32a_10 "Presence of species: falciparum (Pf)"
label variable hml32a_11 "Presence of species: falciparum (Pf)"
label variable hml32a_12 "Presence of species: falciparum (Pf)"
label variable hml32a_13 "Presence of species: falciparum (Pf)"
label variable hml32a_14 "Presence of species: falciparum (Pf)"
label variable hml32a_15 "Presence of species: falciparum (Pf)"
label variable hml32a_16 "Presence of species: falciparum (Pf)"
label variable hml32a_17 "Presence of species: falciparum (Pf)"
label variable hml32a_18 "Presence of species: falciparum (Pf)"
label variable hml32a_19 "Presence of species: falciparum (Pf)"
label variable hml32a_20 "Presence of species: falciparum (Pf)"
label variable hml32a_21 "Presence of species: falciparum (Pf)"
label variable hml32a_22 "Presence of species: falciparum (Pf)"
label variable hml32a_23 "Presence of species: falciparum (Pf)"
label variable hml32a_24 "Presence of species: falciparum (Pf)"
label variable hml32b_01 "Presence of species: malariae (Pm)"
label variable hml32b_02 "Presence of species: malariae (Pm)"
label variable hml32b_03 "Presence of species: malariae (Pm)"
label variable hml32b_04 "Presence of species: malariae (Pm)"
label variable hml32b_05 "Presence of species: malariae (Pm)"
label variable hml32b_06 "Presence of species: malariae (Pm)"
label variable hml32b_07 "Presence of species: malariae (Pm)"
label variable hml32b_08 "Presence of species: malariae (Pm)"
label variable hml32b_09 "Presence of species: malariae (Pm)"
label variable hml32b_10 "Presence of species: malariae (Pm)"
label variable hml32b_11 "Presence of species: malariae (Pm)"
label variable hml32b_12 "Presence of species: malariae (Pm)"
label variable hml32b_13 "Presence of species: malariae (Pm)"
label variable hml32b_14 "Presence of species: malariae (Pm)"
label variable hml32b_15 "Presence of species: malariae (Pm)"
label variable hml32b_16 "Presence of species: malariae (Pm)"
label variable hml32b_17 "Presence of species: malariae (Pm)"
label variable hml32b_18 "Presence of species: malariae (Pm)"
label variable hml32b_19 "Presence of species: malariae (Pm)"
label variable hml32b_20 "Presence of species: malariae (Pm)"
label variable hml32b_21 "Presence of species: malariae (Pm)"
label variable hml32b_22 "Presence of species: malariae (Pm)"
label variable hml32b_23 "Presence of species: malariae (Pm)"
label variable hml32b_24 "Presence of species: malariae (Pm)"
label variable hml32c_01 "Presence of species: ovale (Po)"
label variable hml32c_02 "Presence of species: ovale (Po)"
label variable hml32c_03 "Presence of species: ovale (Po)"
label variable hml32c_04 "Presence of species: ovale (Po)"
label variable hml32c_05 "Presence of species: ovale (Po)"
label variable hml32c_06 "Presence of species: ovale (Po)"
label variable hml32c_07 "Presence of species: ovale (Po)"
label variable hml32c_08 "Presence of species: ovale (Po)"
label variable hml32c_09 "Presence of species: ovale (Po)"
label variable hml32c_10 "Presence of species: ovale (Po)"
label variable hml32c_11 "Presence of species: ovale (Po)"
label variable hml32c_12 "Presence of species: ovale (Po)"
label variable hml32c_13 "Presence of species: ovale (Po)"
label variable hml32c_14 "Presence of species: ovale (Po)"
label variable hml32c_15 "Presence of species: ovale (Po)"
label variable hml32c_16 "Presence of species: ovale (Po)"
label variable hml32c_17 "Presence of species: ovale (Po)"
label variable hml32c_18 "Presence of species: ovale (Po)"
label variable hml32c_19 "Presence of species: ovale (Po)"
label variable hml32c_20 "Presence of species: ovale (Po)"
label variable hml32c_21 "Presence of species: ovale (Po)"
label variable hml32c_22 "Presence of species: ovale (Po)"
label variable hml32c_23 "Presence of species: ovale (Po)"
label variable hml32c_24 "Presence of species: ovale (Po)"
label variable hml32d_01 "Presence of species: vivax (Pv)"
label variable hml32d_02 "Presence of species: vivax (Pv)"
label variable hml32d_03 "Presence of species: vivax (Pv)"
label variable hml32d_04 "Presence of species: vivax (Pv)"
label variable hml32d_05 "Presence of species: vivax (Pv)"
label variable hml32d_06 "Presence of species: vivax (Pv)"
label variable hml32d_07 "Presence of species: vivax (Pv)"
label variable hml32d_08 "Presence of species: vivax (Pv)"
label variable hml32d_09 "Presence of species: vivax (Pv)"
label variable hml32d_10 "Presence of species: vivax (Pv)"
label variable hml32d_11 "Presence of species: vivax (Pv)"
label variable hml32d_12 "Presence of species: vivax (Pv)"
label variable hml32d_13 "Presence of species: vivax (Pv)"
label variable hml32d_14 "Presence of species: vivax (Pv)"
label variable hml32d_15 "Presence of species: vivax (Pv)"
label variable hml32d_16 "Presence of species: vivax (Pv)"
label variable hml32d_17 "Presence of species: vivax (Pv)"
label variable hml32d_18 "Presence of species: vivax (Pv)"
label variable hml32d_19 "Presence of species: vivax (Pv)"
label variable hml32d_20 "Presence of species: vivax (Pv)"
label variable hml32d_21 "Presence of species: vivax (Pv)"
label variable hml32d_22 "Presence of species: vivax (Pv)"
label variable hml32d_23 "Presence of species: vivax (Pv)"
label variable hml32d_24 "Presence of species: vivax (Pv)"
label variable hml32e_01 "NA - Presence of species: CS"
label variable hml32e_02 "NA - Presence of species: CS"
label variable hml32e_03 "NA - Presence of species: CS"
label variable hml32e_04 "NA - Presence of species: CS"
label variable hml32e_05 "NA - Presence of species: CS"
label variable hml32e_06 "NA - Presence of species: CS"
label variable hml32e_07 "NA - Presence of species: CS"
label variable hml32e_08 "NA - Presence of species: CS"
label variable hml32e_09 "NA - Presence of species: CS"
label variable hml32e_10 "NA - Presence of species: CS"
label variable hml32e_11 "NA - Presence of species: CS"
label variable hml32e_12 "NA - Presence of species: CS"
label variable hml32e_13 "NA - Presence of species: CS"
label variable hml32e_14 "NA - Presence of species: CS"
label variable hml32e_15 "NA - Presence of species: CS"
label variable hml32e_16 "NA - Presence of species: CS"
label variable hml32e_17 "NA - Presence of species: CS"
label variable hml32e_18 "NA - Presence of species: CS"
label variable hml32e_19 "NA - Presence of species: CS"
label variable hml32e_20 "NA - Presence of species: CS"
label variable hml32e_21 "NA - Presence of species: CS"
label variable hml32e_22 "NA - Presence of species: CS"
label variable hml32e_23 "NA - Presence of species: CS"
label variable hml32e_24 "NA - Presence of species: CS"
label variable hml32f_01 "NA - Presence of species: CS"
label variable hml32f_02 "NA - Presence of species: CS"
label variable hml32f_03 "NA - Presence of species: CS"
label variable hml32f_04 "NA - Presence of species: CS"
label variable hml32f_05 "NA - Presence of species: CS"
label variable hml32f_06 "NA - Presence of species: CS"
label variable hml32f_07 "NA - Presence of species: CS"
label variable hml32f_08 "NA - Presence of species: CS"
label variable hml32f_09 "NA - Presence of species: CS"
label variable hml32f_10 "NA - Presence of species: CS"
label variable hml32f_11 "NA - Presence of species: CS"
label variable hml32f_12 "NA - Presence of species: CS"
label variable hml32f_13 "NA - Presence of species: CS"
label variable hml32f_14 "NA - Presence of species: CS"
label variable hml32f_15 "NA - Presence of species: CS"
label variable hml32f_16 "NA - Presence of species: CS"
label variable hml32f_17 "NA - Presence of species: CS"
label variable hml32f_18 "NA - Presence of species: CS"
label variable hml32f_19 "NA - Presence of species: CS"
label variable hml32f_20 "NA - Presence of species: CS"
label variable hml32f_21 "NA - Presence of species: CS"
label variable hml32f_22 "NA - Presence of species: CS"
label variable hml32f_23 "NA - Presence of species: CS"
label variable hml32f_24 "NA - Presence of species: CS"
label variable hml32g_01 "NA - Presence of species: CS"
label variable hml32g_02 "NA - Presence of species: CS"
label variable hml32g_03 "NA - Presence of species: CS"
label variable hml32g_04 "NA - Presence of species: CS"
label variable hml32g_05 "NA - Presence of species: CS"
label variable hml32g_06 "NA - Presence of species: CS"
label variable hml32g_07 "NA - Presence of species: CS"
label variable hml32g_08 "NA - Presence of species: CS"
label variable hml32g_09 "NA - Presence of species: CS"
label variable hml32g_10 "NA - Presence of species: CS"
label variable hml32g_11 "NA - Presence of species: CS"
label variable hml32g_12 "NA - Presence of species: CS"
label variable hml32g_13 "NA - Presence of species: CS"
label variable hml32g_14 "NA - Presence of species: CS"
label variable hml32g_15 "NA - Presence of species: CS"
label variable hml32g_16 "NA - Presence of species: CS"
label variable hml32g_17 "NA - Presence of species: CS"
label variable hml32g_18 "NA - Presence of species: CS"
label variable hml32g_19 "NA - Presence of species: CS"
label variable hml32g_20 "NA - Presence of species: CS"
label variable hml32g_21 "NA - Presence of species: CS"
label variable hml32g_22 "NA - Presence of species: CS"
label variable hml32g_23 "NA - Presence of species: CS"
label variable hml32g_24 "NA - Presence of species: CS"
label variable hml33_01 "Result of malaria measurement"
label variable hml33_02 "Result of malaria measurement"
label variable hml33_03 "Result of malaria measurement"
label variable hml33_04 "Result of malaria measurement"
label variable hml33_05 "Result of malaria measurement"
label variable hml33_06 "Result of malaria measurement"
label variable hml33_07 "Result of malaria measurement"
label variable hml33_08 "Result of malaria measurement"
label variable hml33_09 "Result of malaria measurement"
label variable hml33_10 "Result of malaria measurement"
label variable hml33_11 "Result of malaria measurement"
label variable hml33_12 "Result of malaria measurement"
label variable hml33_13 "Result of malaria measurement"
label variable hml33_14 "Result of malaria measurement"
label variable hml33_15 "Result of malaria measurement"
label variable hml33_16 "Result of malaria measurement"
label variable hml33_17 "Result of malaria measurement"
label variable hml33_18 "Result of malaria measurement"
label variable hml33_19 "Result of malaria measurement"
label variable hml33_20 "Result of malaria measurement"
label variable hml33_21 "Result of malaria measurement"
label variable hml33_22 "Result of malaria measurement"
label variable hml33_23 "Result of malaria measurement"
label variable hml33_24 "Result of malaria measurement"
label variable hml34_01 "Bar code for blood smear sample"
label variable hml34_02 "Bar code for blood smear sample"
label variable hml34_03 "Bar code for blood smear sample"
label variable hml34_04 "Bar code for blood smear sample"
label variable hml34_05 "Bar code for blood smear sample"
label variable hml34_06 "Bar code for blood smear sample"
label variable hml34_07 "Bar code for blood smear sample"
label variable hml34_08 "Bar code for blood smear sample"
label variable hml34_09 "Bar code for blood smear sample"
label variable hml34_10 "Bar code for blood smear sample"
label variable hml34_11 "Bar code for blood smear sample"
label variable hml34_12 "Bar code for blood smear sample"
label variable hml34_13 "Bar code for blood smear sample"
label variable hml34_14 "Bar code for blood smear sample"
label variable hml34_15 "Bar code for blood smear sample"
label variable hml34_16 "Bar code for blood smear sample"
label variable hml34_17 "Bar code for blood smear sample"
label variable hml34_18 "Bar code for blood smear sample"
label variable hml34_19 "Bar code for blood smear sample"
label variable hml34_20 "Bar code for blood smear sample"
label variable hml34_21 "Bar code for blood smear sample"
label variable hml34_22 "Bar code for blood smear sample"
label variable hml34_23 "Bar code for blood smear sample"
label variable hml34_24 "Bar code for blood smear sample"
label variable hml35_01 "Result of malaria rapid test"
label variable hml35_02 "Result of malaria rapid test"
label variable hml35_03 "Result of malaria rapid test"
label variable hml35_04 "Result of malaria rapid test"
label variable hml35_05 "Result of malaria rapid test"
label variable hml35_06 "Result of malaria rapid test"
label variable hml35_07 "Result of malaria rapid test"
label variable hml35_08 "Result of malaria rapid test"
label variable hml35_09 "Result of malaria rapid test"
label variable hml35_10 "Result of malaria rapid test"
label variable hml35_11 "Result of malaria rapid test"
label variable hml35_12 "Result of malaria rapid test"
label variable hml35_13 "Result of malaria rapid test"
label variable hml35_14 "Result of malaria rapid test"
label variable hml35_15 "Result of malaria rapid test"
label variable hml35_16 "Result of malaria rapid test"
label variable hml35_17 "Result of malaria rapid test"
label variable hml35_18 "Result of malaria rapid test"
label variable hml35_19 "Result of malaria rapid test"
label variable hml35_20 "Result of malaria rapid test"
label variable hml35_21 "Result of malaria rapid test"
label variable hml35_22 "Result of malaria rapid test"
label variable hml35_23 "Result of malaria rapid test"
label variable hml35_24 "Result of malaria rapid test"
label variable hml36_01 "Fieldworker measurer code for malaria"
label variable hml36_02 "Fieldworker measurer code for malaria"
label variable hml36_03 "Fieldworker measurer code for malaria"
label variable hml36_04 "Fieldworker measurer code for malaria"
label variable hml36_05 "Fieldworker measurer code for malaria"
label variable hml36_06 "Fieldworker measurer code for malaria"
label variable hml36_07 "Fieldworker measurer code for malaria"
label variable hml36_08 "Fieldworker measurer code for malaria"
label variable hml36_09 "Fieldworker measurer code for malaria"
label variable hml36_10 "Fieldworker measurer code for malaria"
label variable hml36_11 "Fieldworker measurer code for malaria"
label variable hml36_12 "Fieldworker measurer code for malaria"
label variable hml36_13 "Fieldworker measurer code for malaria"
label variable hml36_14 "Fieldworker measurer code for malaria"
label variable hml36_15 "Fieldworker measurer code for malaria"
label variable hml36_16 "Fieldworker measurer code for malaria"
label variable hml36_17 "Fieldworker measurer code for malaria"
label variable hml36_18 "Fieldworker measurer code for malaria"
label variable hml36_19 "Fieldworker measurer code for malaria"
label variable hml36_20 "Fieldworker measurer code for malaria"
label variable hml36_21 "Fieldworker measurer code for malaria"
label variable hml36_22 "Fieldworker measurer code for malaria"
label variable hml36_23 "Fieldworker measurer code for malaria"
label variable hml36_24 "Fieldworker measurer code for malaria"
label variable sml16a_01 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_02 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_03 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_04 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_05 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_06 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_07 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_08 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_09 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_10 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_11 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_12 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_13 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_14 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_15 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_16 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_17 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_18 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_19 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_20 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_21 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_22 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_23 "Child's age in months ( country specific version of HML16A )"
label variable sml16a_24 "Child's age in months ( country specific version of HML16A )"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV022   
     1 "Urban Nairobi"
     2 "Rural Nyandarua"
     3 "Urban Nyandarua"
     4 "Rural Nyeri"
     5 "Urban Nyeri"
     6 "Rural Kirinyaga"
     7 "Urban Kirinyaga"
     8 "Rural Muranga"
     9 "Urban Muranga"
    10 "Rural Kiambu"
    11 "Urban Kiambu"
    12 "Urban Mombasa"
    13 "Rural Kwale"
    14 "Urban Kwale"
    15 "Rural Kilifi"
    16 "Urban Kilifi"
    17 "Rural Tana River"
    18 "Urban Tana River"
    19 "Rural Lamu"
    20 "Urban Lamu"
    21 "Rural Taita Taveta"
    22 "Urban Taita Taveta"
    23 "Rural Marsabit"
    24 "Urban Marsabit"
    25 "Rural Isiolo"
    26 "Urban Isiolo"
    27 "Rural Meru"
    28 "Urban Meru"
    29 "Rural Tharaka"
    30 "Urban Tharaka"
    31 "Rural Embu"
    32 "Urban Embu"
    33 "Rural Kitui"
    34 "Urban Kitui"
    35 "Rural Machakos"
    36 "Urban Machakos"
    37 "Rural Makueni"
    38 "Urban Makueni"
    39 "Rural Garissa"
    40 "Urban Garissa"
    41 "Rural Wajir"
    42 "Urban Wajir"
    43 "Rural Mandera"
    44 "Urban Mandera"
    45 "Rural Siaya"
    46 "Urban Siaya"
    47 "Rural Kisumu"
    48 "Urban Kisumu"
    49 "Rural Migori"
    50 "Urban Migori"
    51 "Rural Homa Bay"
    52 "Urban Homa Bay"
    53 "Rural Kisii"
    54 "Urban Kisii"
    55 "Rural Nyamira"
    56 "Urban Nyamira"
    57 "Rural Turkana"
    58 "Urban Turkana"
    59 "Rural West Pokot"
    60 "Urban West Pokot"
    61 "Rural Samburu"
    62 "Urban Samburu"
    63 "Rural Trans-Nzoia"
    64 "Urban Trans-Nzoia"
    65 "Rural Baringo"
    66 "Urban Baringo"
    67 "Rural Uasin Gishu"
    68 "Urban Uasin Gishu"
    69 "Rural Elgeyo Marakwet"
    70 "Urban Elgeyo Marakwet"
    71 "Rural Nandi"
    72 "Urban Nandi"
    73 "Rural Laikipia"
    74 "Urban Laikipia"
    75 "Rural Nakuru"
    76 "Urban Nakuru"
    77 "Rural Narok"
    78 "Urban Narok"
    79 "Rural Kajiado"
    80 "Urban Kajiado"
    81 "Rural Kericho"
    82 "Urban Kericho"
    83 "Rural Bomet"
    84 "Urban Bomet"
    85 "Rural Kakamega"
    86 "Urban Kakamega"
    87 "Rural Vihiga"
    88 "Urban Vihiga"
    89 "Rural Bungoma"
    90 "Urban Bungoma"
    91 "Rural Busia"
    92 "Urban Busia"
;
label define HV023   
     1 "Urban Nairobi"
     2 "Rural Nyandarua"
     3 "Urban Nyandarua"
     4 "Rural Nyeri"
     5 "Urban Nyeri"
     6 "Rural Kirinyaga"
     7 "Urban Kirinyaga"
     8 "Rural Muranga"
     9 "Urban Muranga"
    10 "Rural Kiambu"
    11 "Urban Kiambu"
    12 "Urban Mombasa"
    13 "Rural Kwale"
    14 "Urban Kwale"
    15 "Rural Kilifi"
    16 "Urban Kilifi"
    17 "Rural Tana River"
    18 "Urban Tana River"
    19 "Rural Lamu"
    20 "Urban Lamu"
    21 "Rural Taita Taveta"
    22 "Urban Taita Taveta"
    23 "Rural Marsabit"
    24 "Urban Marsabit"
    25 "Rural Isiolo"
    26 "Urban Isiolo"
    27 "Rural Meru"
    28 "Urban Meru"
    29 "Rural Tharaka"
    30 "Urban Tharaka"
    31 "Rural Embu"
    32 "Urban Embu"
    33 "Rural Kitui"
    34 "Urban Kitui"
    35 "Rural Machakos"
    36 "Urban Machakos"
    37 "Rural Makueni"
    38 "Urban Makueni"
    39 "Rural Garissa"
    40 "Urban Garissa"
    41 "Rural Wajir"
    42 "Urban Wajir"
    43 "Rural Mandera"
    44 "Urban Mandera"
    45 "Rural Siaya"
    46 "Urban Siaya"
    47 "Rural Kisumu"
    48 "Urban Kisumu"
    49 "Rural Migori"
    50 "Urban Migori"
    51 "Rural Homa Bay"
    52 "Urban Homa Bay"
    53 "Rural Kisii"
    54 "Urban Kisii"
    55 "Rural Nyamira"
    56 "Urban Nyamira"
    57 "Rural Turkana"
    58 "Urban Turkana"
    59 "Rural West Pokot"
    60 "Urban West Pokot"
    61 "Rural Samburu"
    62 "Urban Samburu"
    63 "Rural Trans-Nzoia"
    64 "Urban Trans-Nzoia"
    65 "Rural Baringo"
    66 "Urban Baringo"
    67 "Rural Uasin Gishu"
    68 "Urban Uasin Gishu"
    69 "Rural Elgeyo Marakwet"
    70 "Urban Elgeyo Marakwet"
    71 "Rural Nandi"
    72 "Urban Nandi"
    73 "Rural Laikipia"
    74 "Urban Laikipia"
    75 "Rural Nakuru"
    76 "Urban Nakuru"
    77 "Rural Narok"
    78 "Urban Narok"
    79 "Rural Kajiado"
    80 "Urban Kajiado"
    81 "Rural Kericho"
    82 "Urban Kericho"
    83 "Rural Bomet"
    84 "Urban Bomet"
    85 "Rural Kakamega"
    86 "Urban Kakamega"
    87 "Rural Vihiga"
    88 "Urban Vihiga"
    89 "Rural Bungoma"
    90 "Urban Bungoma"
    91 "Rural Busia"
    92 "Urban Busia"
;
label define HV024   
     1 "Coast"
     2 "North Eastern"
     3 "Eastern"
     4 "Central"
     5 "Rift Valley"
     7 "Western"
     8 "Nyanza"
     9 "Nairobi"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV045A  
     1 "English"
     2 "Kiswahili"
;
label define HV045B  
     1 "English"
     2 "Kiswahili"
     3 "Borana"
     4 "Embu"
     5 "Kalenjin"
     6 "Kamba"
     7 "Kikuyu"
     8 "Kisii"
     9 "Luhya"
    10 "Maragoli"
    11 "Luo"
    12 "Maasi"
    13 "Meru"
    14 "Mijkenda"
    15 "Pokot"
    16 "Somali"
    17 "Turkana"
    96 "Other"
;
label define HV045C  
     1 "English"
     2 "Kiswahili"
     3 "Borana"
     4 "Embu"
     5 "Kalenjin"
     6 "Kamba"
     7 "Kikuyu"
     8 "Kisii"
     9 "Luhya"
    10 "Maragoli"
    11 "Luo"
    12 "Maasi"
    13 "Meru"
    14 "Mijkenda"
    15 "Pokot"
    16 "Somali"
    17 "Turkana"
    96 "Other"
;
label define HV046   
     0 "No"
     1 "Yes"
;
label define HV801   
  9999 "Missing"
;
label define HV802   
  9999 "Missing"
;
label define HV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define HV804   
     9 "Missing"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    71 "Bottled water"
    96 "Other"
;
label define HV201A  
     0 "No, not interrupted for a full day"
     1 "Yes, interrupted for a full day or more"
     8 "Don't know"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "Other"
;
label define HV214   
    10 "NATURAL"
    11 "No walls"
    12 "Cane/palm/trunks"
    13 "Dirt"
    20 "RUDIMENTARY"
    21 "Bamboo with mud"
    22 "Stone with mud"
    23 "Uncovered adobe"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Covered adobe"
    36 "Wood planks/shingles"
    96 "Other"
;
label define HV215   
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Sod"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Palm/bamboo"
    23 "Wood planks"
    24 "Cardboard"
    30 "FINISHED"
    31 "Iron sheets"
    32 "Wood"
    33 "Calamine/cement fiber"
    34 "Brick/clay tiles"
    35 "Cement"
    36 "Roofing shingles"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    12 "Solar"
    13 "Alcohol/ethanol"
    14 "Gasoline/diesel"
    95 "No food cooked in house"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV238A  
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     0 "Neither chimney or hood"
     1 "Chimney"
     2 "Hood"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV243E  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
   950 "95 or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HV270A  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SHCOUNTY
   101 "Nairobi"
   201 "Nyandarua"
   202 "Nyeri"
   203 "Kirinyaga"
   204 "Muranga"
   205 "Kiambu"
   301 "Mombasa"
   302 "Kwale"
   303 "Kilifi"
   304 "Tana River"
   305 "Lamu"
   306 "Taita Taveta"
   401 "Marsabit"
   402 "Isiolo"
   403 "Meru"
   404 "Tharaka"
   405 "Embu"
   406 "Kitui"
   407 "Machakos"
   408 "Makueni"
   501 "Garissa"
   502 "Wajir"
   503 "Mandera"
   601 "Siaya"
   602 "Kisumu"
   603 "Migori"
   604 "Homa Bay"
   605 "Kisii"
   606 "Nyamira"
   701 "Turkana"
   702 "West Pokot"
   703 "Samburu"
   704 "Trans-Nzoia"
   705 "Baringo"
   706 "Uasin Gishu"
   707 "Elgeyo Marakwet"
   708 "Nandi"
   709 "Laikipia"
   710 "Nakuru"
   711 "Narok"
   712 "Kajiado"
   713 "Kericho"
   714 "Bomet"
   801 "Kakamega"
   802 "Vihiga"
   803 "Bungoma"
   804 "Busia"
;
label define SHZONE  
     1 "Highland Epidemic Prone"
     2 "Lake Endemic"
     3 "Coastal Endemic"
     4 "Seasonal"
     5 "Low Risk"
;
label define SH109   
     1 "Electric stove"
     2 "Solar cooker"
     3 "Liquefied petroleum gas (LPG)/cooking gas stove"
     4 "Piped natural gas stove"
     5 "Biogas stove"
     6 "Liquid fuel stove"
     7 "Manufactured solid fuel stove"
     8 "Traditional solid fuel stove"
     9 "Three stone stove/open fire"
    95 "No food cooked in household"
    96 "Other"
;
label define SH110   
     1 "Alcohol/ethanol"
     2 "Gasoline/diesel"
     3 "Kerosene/paraffin"
     4 "Coal/lignite"
     5 "Charcoal"
     6 "Wood"
     7 "Straw/shrubs/grass"
     8 "Agricultural crop"
     9 "Animal dung/waste"
    10 "Processed biomass (pellets) or woodchips"
    11 "Garbage/plastic"
    12 "Sawdust"
    96 "Other"
;
label define SH116G  
     0 "No"
     1 "Yes"
;
label define SH116H  
     0 "No"
     1 "Yes"
;
label define SH116I  
     0 "No"
     1 "Yes"
;
label define SH116J  
     0 "No"
     1 "Yes"
;
label define SH116K  
     0 "No"
     1 "Yes"
;
label define SH116L  
     0 "No"
     1 "Yes"
;
label define SH116M  
     0 "No"
     1 "Yes"
;
label define SH116N  
     0 "No"
     1 "Yes"
;
label define SH116O  
     0 "No"
     1 "Yes"
;
label define SH116P  
     0 "No"
     1 "Yes"
;
label define SH119   
     0 "No"
     1 "Yes"
;
label define SH119A  
     0 "No"
     1 "Yes"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster/step child"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    98 "Don't know"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HC1     
    60 "60+"
;
label define HC1A    
  2501 "2501+"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present/other"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC62    
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary"
     2 "Post-primary/vocational"
     3 "Secondary/'A' level"
     4 "College (middle level)"
     5 "University"
     8 "Don't know"
;
label define SB115A  
     0 "No"
     1 "Yes"
;
label define SB115B  
     0 "No"
     1 "Yes"
;
label define SB115C  
     0 "No"
     1 "Yes"
;
label define SB115D  
     0 "No"
     1 "Yes"
;
label define SB115E  
     0 "No"
     1 "Yes"
;
label define SB115F  
     0 "No"
     1 "Yes"
;
label define SB115G  
     0 "No"
     1 "Yes"
;
label define SB115H  
     0 "No"
     1 "Yes"
;
label define SB119   
     0 "No"
     1 "Yes"
;
label define SB122   
     1 "Accepted medicine"
     2 "Refused"
     6 "Other"
;
label define SB128D  
    98 "Don't know"
;
label define SB128M  
     1 "January"
     2 "February"
     3 "March"
     4 "April"
     5 "May"
     6 "June"
     7 "July"
     8 "August"
     9 "September"
    10 "October"
    11 "November"
    12 "December"
    98 "DK month"
;
label define SB128Y  
  2020 "2020"
  2021 "2021"
;
label define HML3    
     0 "Not seen"
     1 "Yes, seen"
;
label define HML4    
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML5    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HML6    
     0 "Not pretreated"
     1 "Pretreated, permanent treatment"
     2 "Pretreated, requiring future treatment"
     3 "Not pretreated, came with kit and treated at home"
     4 "Pretreated, treatment type not known"
     6 "Other"
     8 "Don't know"
;
label define HML7    
    10 "Long-lasting insecticide treated nets (LLIN)"
    11 "Olyset (Supanet extra)"
    12 "Permanet (Supanet extra)"
    13 "Netprotect"
    14 "Yorkool"
    15 "Dawa Plus"
    16 "Other/Don't know brand (LLIN)"
    20 "Pretreated net"
    96 "Other brand (not LLIN)"
    98 "Don't know type"
;
label define HML8    
     0 "No"
     1 "Yes"
     2 "Permanent/LLIN net"
     8 "Not sure"
;
label define HML9    
    95 "25+ months ago"
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML10   
     0 "No, don't know"
     1 "Yes"
;
label define HML11   
     5 "5+"
;
label define HML21   
     0 "No"
     1 "Yes"
     8 "Not sure (DK)"
;
label define HMLA    
     0 "No one"
;
label define HMLB    
    99 "Missing"
;
label define HMLC    
    99 "Missing"
;
label define HML22   
     0 "No"
     1 "Yes, campaign"
     2 "Yes, antenatal care"
     3 "Yes, child welfare visit"
;
label define HML23   
    10 "Government health facility"
    20 "Private health facility"
    30 "Other sources"
    31 "Pharmacy"
    32 "Shop/market"
    33 "CHW"
    34 "Religious institution"
    35 "School"
    96 "Other"
    98 "Don't know"
;
label define SH130   
     1 "Too hot"
     2 "Don't like net shape/color/size"
     3 "Don't like smell"
     4 "Unable to hang net"
     5 "Slept outdoors"
     6 "Usual user didn't sleep here last night"
     7 "No mosquitoes/no malaria"
     8 "Extra net/saving for later"
     9 "Net too small/short"
    10 "Net brought bedbugs"
    11 "Net in poor condition"
    96 "Other"
;
label define HML12   
     0 "Did not sleep under a net"
     1 "Only treated (ITN) nets"
     2 "Both treated (ITN) and untreated nets"
     3 "Only untreated nets"
;
label define HML13   
     0 "Did not sleep under net"
;
label define HML16   
    97 "97+"
    98 "Don't know"
;
label define HML16A  
    60 "60+"
;
label define HML17   
     0 "No data from Individual file"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HML18   
     0 "Not pregnant, don't know"
     1 "Pregnant"
;
label define HML19   
     0 "No"
     1 "Yes"
;
label define HML20   
     0 "No"
     1 "Yes"
;
label define HML30   
     0 "Not in household"
;
label define HML31   
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define HML32   
     0 "Negative"
     1 "Positive"
     6 "Test undetermined"
     7 "Sample not found in lab database"
;
label define HML32A  
     0 "No"
     1 "Yes"
;
label define HML32B  
     0 "No"
     1 "Yes"
;
label define HML32C  
     0 "No"
     1 "Yes"
;
label define HML32D  
     0 "No"
     1 "Yes"
;
label define HML32E  
     0 "No"
     1 "Yes"
;
label define HML32F  
     0 "No"
     1 "Yes"
;
label define HML32G  
     0 "No"
     1 "Yes"
;
label define HML33   
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HML35   
     0 "Negative"
     1 "Positive"
;

#delimit cr
label values hv003    HV003   
label values hv015    HV015   
label values hv020    HV020   
label values hv022    HV022   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv045a   HV045A  
label values hv045b   HV045B  
label values hv045c   HV045C  
label values hv046    HV046   
label values hv803    HV803   
label values hv201    HV201   
label values hv202    HV202   
label values hv201a   HV201A  
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv235    HV235   
label values hv238    HV238   
label values hv238a   HV238A  
label values hv239    HV239   
label values hv240    HV240   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv243e   HV243E  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv270    HV270   
label values hv270a   HV270A  
label values hml1     HML1    
label values shcounty SHCOUNTY
label values shzone   SHZONE  
label values sh109    SH109   
label values sh110    SH110   
label values sh116g   SH116G  
label values sh116h   SH116H  
label values sh116i   SH116I  
label values sh116j   SH116J  
label values sh116k   SH116K  
label values sh116l   SH116L  
label values sh116m   SH116M  
label values sh116n   SH116N  
label values sh116o   SH116O  
label values sh116p   SH116P  
label values sh119    SH119   
label values sh119a   SH119A  
label values hv101_01 HV101   
label values hv101_02 HV101   
label values hv101_03 HV101   
label values hv101_04 HV101   
label values hv101_05 HV101   
label values hv101_06 HV101   
label values hv101_07 HV101   
label values hv101_08 HV101   
label values hv101_09 HV101   
label values hv101_10 HV101   
label values hv101_11 HV101   
label values hv101_12 HV101   
label values hv101_13 HV101   
label values hv101_14 HV101   
label values hv101_15 HV101   
label values hv101_16 HV101   
label values hv101_17 HV101   
label values hv101_18 HV101   
label values hv101_19 HV101   
label values hv101_20 HV101   
label values hv101_21 HV101   
label values hv101_22 HV101   
label values hv101_23 HV101   
label values hv101_24 HV101   
label values hv102_01 HV102   
label values hv102_02 HV102   
label values hv102_03 HV102   
label values hv102_04 HV102   
label values hv102_05 HV102   
label values hv102_06 HV102   
label values hv102_07 HV102   
label values hv102_08 HV102   
label values hv102_09 HV102   
label values hv102_10 HV102   
label values hv102_11 HV102   
label values hv102_12 HV102   
label values hv102_13 HV102   
label values hv102_14 HV102   
label values hv102_15 HV102   
label values hv102_16 HV102   
label values hv102_17 HV102   
label values hv102_18 HV102   
label values hv102_19 HV102   
label values hv102_20 HV102   
label values hv102_21 HV102   
label values hv102_22 HV102   
label values hv102_23 HV102   
label values hv102_24 HV102   
label values hv103_01 HV103   
label values hv103_02 HV103   
label values hv103_03 HV103   
label values hv103_04 HV103   
label values hv103_05 HV103   
label values hv103_06 HV103   
label values hv103_07 HV103   
label values hv103_08 HV103   
label values hv103_09 HV103   
label values hv103_10 HV103   
label values hv103_11 HV103   
label values hv103_12 HV103   
label values hv103_13 HV103   
label values hv103_14 HV103   
label values hv103_15 HV103   
label values hv103_16 HV103   
label values hv103_17 HV103   
label values hv103_18 HV103   
label values hv103_19 HV103   
label values hv103_20 HV103   
label values hv103_21 HV103   
label values hv103_22 HV103   
label values hv103_23 HV103   
label values hv103_24 HV103   
label values hv104_01 HV104   
label values hv104_02 HV104   
label values hv104_03 HV104   
label values hv104_04 HV104   
label values hv104_05 HV104   
label values hv104_06 HV104   
label values hv104_07 HV104   
label values hv104_08 HV104   
label values hv104_09 HV104   
label values hv104_10 HV104   
label values hv104_11 HV104   
label values hv104_12 HV104   
label values hv104_13 HV104   
label values hv104_14 HV104   
label values hv104_15 HV104   
label values hv104_16 HV104   
label values hv104_17 HV104   
label values hv104_18 HV104   
label values hv104_19 HV104   
label values hv104_20 HV104   
label values hv104_21 HV104   
label values hv104_22 HV104   
label values hv104_23 HV104   
label values hv104_24 HV104   
label values hv105_01 HV105   
label values hv105_02 HV105   
label values hv105_03 HV105   
label values hv105_04 HV105   
label values hv105_05 HV105   
label values hv105_06 HV105   
label values hv105_07 HV105   
label values hv105_08 HV105   
label values hv105_09 HV105   
label values hv105_10 HV105   
label values hv105_11 HV105   
label values hv105_12 HV105   
label values hv105_13 HV105   
label values hv105_14 HV105   
label values hv105_15 HV105   
label values hv105_16 HV105   
label values hv105_17 HV105   
label values hv105_18 HV105   
label values hv105_19 HV105   
label values hv105_20 HV105   
label values hv105_21 HV105   
label values hv105_22 HV105   
label values hv105_23 HV105   
label values hv105_24 HV105   
label values hv117_01 HV117   
label values hv117_02 HV117   
label values hv117_03 HV117   
label values hv117_04 HV117   
label values hv117_05 HV117   
label values hv117_06 HV117   
label values hv117_07 HV117   
label values hv117_08 HV117   
label values hv117_09 HV117   
label values hv117_10 HV117   
label values hv117_11 HV117   
label values hv117_12 HV117   
label values hv117_13 HV117   
label values hv117_14 HV117   
label values hv117_15 HV117   
label values hv117_16 HV117   
label values hv117_17 HV117   
label values hv117_18 HV117   
label values hv117_19 HV117   
label values hv117_20 HV117   
label values hv117_21 HV117   
label values hv117_22 HV117   
label values hv117_23 HV117   
label values hv117_24 HV117   
label values hv120_01 HV120   
label values hv120_02 HV120   
label values hv120_03 HV120   
label values hv120_04 HV120   
label values hv120_05 HV120   
label values hv120_06 HV120   
label values hv120_07 HV120   
label values hv120_08 HV120   
label values hv120_09 HV120   
label values hv120_10 HV120   
label values hv120_11 HV120   
label values hv120_12 HV120   
label values hv120_13 HV120   
label values hv120_14 HV120   
label values hv120_15 HV120   
label values hv120_16 HV120   
label values hv120_17 HV120   
label values hv120_18 HV120   
label values hv120_19 HV120   
label values hv120_20 HV120   
label values hv120_21 HV120   
label values hv120_22 HV120   
label values hv120_23 HV120   
label values hv120_24 HV120   
label values hc1_01   HC1     
label values hc1_02   HC1     
label values hc1_03   HC1     
label values hc1_04   HC1     
label values hc1_05   HC1     
label values hc1_06   HC1     
label values hc1_07   HC1     
label values hc1_08   HC1     
label values hc1_09   HC1     
label values hc1_10   HC1     
label values hc1_11   HC1     
label values hc1_12   HC1     
label values hc1_13   HC1     
label values hc1_14   HC1     
label values hc1_15   HC1     
label values hc1_16   HC1     
label values hc1_17   HC1     
label values hc1_18   HC1     
label values hc1_19   HC1     
label values hc1_20   HC1     
label values hc1a_01  HC1A    
label values hc1a_02  HC1A    
label values hc1a_03  HC1A    
label values hc1a_04  HC1A    
label values hc1a_05  HC1A    
label values hc1a_06  HC1A    
label values hc1a_07  HC1A    
label values hc1a_08  HC1A    
label values hc1a_09  HC1A    
label values hc1a_10  HC1A    
label values hc1a_11  HC1A    
label values hc1a_12  HC1A    
label values hc1a_13  HC1A    
label values hc1a_14  HC1A    
label values hc1a_15  HC1A    
label values hc1a_16  HC1A    
label values hc1a_17  HC1A    
label values hc1a_18  HC1A    
label values hc1a_19  HC1A    
label values hc1a_20  HC1A    
label values hc16_01  HC16    
label values hc16_02  HC16    
label values hc16_03  HC16    
label values hc16_04  HC16    
label values hc16_05  HC16    
label values hc16_06  HC16    
label values hc16_07  HC16    
label values hc16_08  HC16    
label values hc16_09  HC16    
label values hc16_10  HC16    
label values hc16_11  HC16    
label values hc16_12  HC16    
label values hc16_13  HC16    
label values hc16_14  HC16    
label values hc16_15  HC16    
label values hc16_16  HC16    
label values hc16_17  HC16    
label values hc16_18  HC16    
label values hc16_19  HC16    
label values hc16_20  HC16    
label values hc27_01  HC27    
label values hc27_02  HC27    
label values hc27_03  HC27    
label values hc27_04  HC27    
label values hc27_05  HC27    
label values hc27_06  HC27    
label values hc27_07  HC27    
label values hc27_08  HC27    
label values hc27_09  HC27    
label values hc27_10  HC27    
label values hc27_11  HC27    
label values hc27_12  HC27    
label values hc27_13  HC27    
label values hc27_14  HC27    
label values hc27_15  HC27    
label values hc27_16  HC27    
label values hc27_17  HC27    
label values hc27_18  HC27    
label values hc27_19  HC27    
label values hc27_20  HC27    
label values hc30_01  HC30    
label values hc30_02  HC30    
label values hc30_03  HC30    
label values hc30_04  HC30    
label values hc30_05  HC30    
label values hc30_06  HC30    
label values hc30_07  HC30    
label values hc30_08  HC30    
label values hc30_09  HC30    
label values hc30_10  HC30    
label values hc30_11  HC30    
label values hc30_12  HC30    
label values hc30_13  HC30    
label values hc30_14  HC30    
label values hc30_15  HC30    
label values hc30_16  HC30    
label values hc30_17  HC30    
label values hc30_18  HC30    
label values hc30_19  HC30    
label values hc30_20  HC30    
label values hc31_01  HC31    
label values hc31_02  HC31    
label values hc31_03  HC31    
label values hc31_04  HC31    
label values hc31_05  HC31    
label values hc31_06  HC31    
label values hc31_07  HC31    
label values hc31_08  HC31    
label values hc31_09  HC31    
label values hc31_10  HC31    
label values hc31_11  HC31    
label values hc31_12  HC31    
label values hc31_13  HC31    
label values hc31_14  HC31    
label values hc31_15  HC31    
label values hc31_16  HC31    
label values hc31_17  HC31    
label values hc31_18  HC31    
label values hc31_19  HC31    
label values hc31_20  HC31    
label values hc33_01  HC33    
label values hc33_02  HC33    
label values hc33_03  HC33    
label values hc33_04  HC33    
label values hc33_05  HC33    
label values hc33_06  HC33    
label values hc33_07  HC33    
label values hc33_08  HC33    
label values hc33_09  HC33    
label values hc33_10  HC33    
label values hc33_11  HC33    
label values hc33_12  HC33    
label values hc33_13  HC33    
label values hc33_14  HC33    
label values hc33_15  HC33    
label values hc33_16  HC33    
label values hc33_17  HC33    
label values hc33_18  HC33    
label values hc33_19  HC33    
label values hc33_20  HC33    
label values hc51_01  HC51    
label values hc51_02  HC51    
label values hc51_03  HC51    
label values hc51_04  HC51    
label values hc51_05  HC51    
label values hc51_06  HC51    
label values hc51_07  HC51    
label values hc51_08  HC51    
label values hc51_09  HC51    
label values hc51_10  HC51    
label values hc51_11  HC51    
label values hc51_12  HC51    
label values hc51_13  HC51    
label values hc51_14  HC51    
label values hc51_15  HC51    
label values hc51_16  HC51    
label values hc51_17  HC51    
label values hc51_18  HC51    
label values hc51_19  HC51    
label values hc51_20  HC51    
label values hc52_01  HC52    
label values hc52_02  HC52    
label values hc52_03  HC52    
label values hc52_04  HC52    
label values hc52_05  HC52    
label values hc52_06  HC52    
label values hc52_07  HC52    
label values hc52_08  HC52    
label values hc52_09  HC52    
label values hc52_10  HC52    
label values hc52_11  HC52    
label values hc52_12  HC52    
label values hc52_13  HC52    
label values hc52_14  HC52    
label values hc52_15  HC52    
label values hc52_16  HC52    
label values hc52_17  HC52    
label values hc52_18  HC52    
label values hc52_19  HC52    
label values hc52_20  HC52    
label values hc53_01  HC53    
label values hc53_02  HC53    
label values hc53_03  HC53    
label values hc53_04  HC53    
label values hc53_05  HC53    
label values hc53_06  HC53    
label values hc53_07  HC53    
label values hc53_08  HC53    
label values hc53_09  HC53    
label values hc53_10  HC53    
label values hc53_11  HC53    
label values hc53_12  HC53    
label values hc53_13  HC53    
label values hc53_14  HC53    
label values hc53_15  HC53    
label values hc53_16  HC53    
label values hc53_17  HC53    
label values hc53_18  HC53    
label values hc53_19  HC53    
label values hc53_20  HC53    
label values hc55_01  HC55    
label values hc55_02  HC55    
label values hc55_03  HC55    
label values hc55_04  HC55    
label values hc55_05  HC55    
label values hc55_06  HC55    
label values hc55_07  HC55    
label values hc55_08  HC55    
label values hc55_09  HC55    
label values hc55_10  HC55    
label values hc55_11  HC55    
label values hc55_12  HC55    
label values hc55_13  HC55    
label values hc55_14  HC55    
label values hc55_15  HC55    
label values hc55_16  HC55    
label values hc55_17  HC55    
label values hc55_18  HC55    
label values hc55_19  HC55    
label values hc55_20  HC55    
label values hc56_01  HC56    
label values hc56_02  HC56    
label values hc56_03  HC56    
label values hc56_04  HC56    
label values hc56_05  HC56    
label values hc56_06  HC56    
label values hc56_07  HC56    
label values hc56_08  HC56    
label values hc56_09  HC56    
label values hc56_10  HC56    
label values hc56_11  HC56    
label values hc56_12  HC56    
label values hc56_13  HC56    
label values hc56_14  HC56    
label values hc56_15  HC56    
label values hc56_16  HC56    
label values hc56_17  HC56    
label values hc56_18  HC56    
label values hc56_19  HC56    
label values hc56_20  HC56    
label values hc57_01  HC57    
label values hc57_02  HC57    
label values hc57_03  HC57    
label values hc57_04  HC57    
label values hc57_05  HC57    
label values hc57_06  HC57    
label values hc57_07  HC57    
label values hc57_08  HC57    
label values hc57_09  HC57    
label values hc57_10  HC57    
label values hc57_11  HC57    
label values hc57_12  HC57    
label values hc57_13  HC57    
label values hc57_14  HC57    
label values hc57_15  HC57    
label values hc57_16  HC57    
label values hc57_17  HC57    
label values hc57_18  HC57    
label values hc57_19  HC57    
label values hc57_20  HC57    
label values hc58_01  HC58    
label values hc58_02  HC58    
label values hc58_03  HC58    
label values hc58_04  HC58    
label values hc58_05  HC58    
label values hc58_06  HC58    
label values hc58_07  HC58    
label values hc58_08  HC58    
label values hc58_09  HC58    
label values hc58_10  HC58    
label values hc58_11  HC58    
label values hc58_12  HC58    
label values hc58_13  HC58    
label values hc58_14  HC58    
label values hc58_15  HC58    
label values hc58_16  HC58    
label values hc58_17  HC58    
label values hc58_18  HC58    
label values hc58_19  HC58    
label values hc58_20  HC58    
label values hc60_01  HC60    
label values hc60_02  HC60    
label values hc60_03  HC60    
label values hc60_04  HC60    
label values hc60_05  HC60    
label values hc60_06  HC60    
label values hc60_07  HC60    
label values hc60_08  HC60    
label values hc60_09  HC60    
label values hc60_10  HC60    
label values hc60_11  HC60    
label values hc60_12  HC60    
label values hc60_13  HC60    
label values hc60_14  HC60    
label values hc60_15  HC60    
label values hc60_16  HC60    
label values hc60_17  HC60    
label values hc60_18  HC60    
label values hc60_19  HC60    
label values hc60_20  HC60    
label values hc61_01  HC61    
label values hc61_02  HC61    
label values hc61_03  HC61    
label values hc61_04  HC61    
label values hc61_05  HC61    
label values hc61_06  HC61    
label values hc61_07  HC61    
label values hc61_08  HC61    
label values hc61_09  HC61    
label values hc61_10  HC61    
label values hc61_11  HC61    
label values hc61_12  HC61    
label values hc61_13  HC61    
label values hc61_14  HC61    
label values hc61_15  HC61    
label values hc61_16  HC61    
label values hc61_17  HC61    
label values hc61_18  HC61    
label values hc61_19  HC61    
label values hc61_20  HC61    
label values hc62_01  HC62    
label values hc62_02  HC62    
label values hc62_03  HC62    
label values hc62_04  HC62    
label values hc62_05  HC62    
label values hc62_06  HC62    
label values hc62_07  HC62    
label values hc62_08  HC62    
label values hc62_09  HC62    
label values hc62_10  HC62    
label values hc62_11  HC62    
label values hc62_12  HC62    
label values hc62_13  HC62    
label values hc62_14  HC62    
label values hc62_15  HC62    
label values hc62_16  HC62    
label values hc62_17  HC62    
label values hc62_18  HC62    
label values hc62_19  HC62    
label values hc62_20  HC62    
label values hc68_01  HC68    
label values hc68_02  HC68    
label values hc68_03  HC68    
label values hc68_04  HC68    
label values hc68_05  HC68    
label values hc68_06  HC68    
label values hc68_07  HC68    
label values hc68_08  HC68    
label values hc68_09  HC68    
label values hc68_10  HC68    
label values hc68_11  HC68    
label values hc68_12  HC68    
label values hc68_13  HC68    
label values hc68_14  HC68    
label values hc68_15  HC68    
label values hc68_16  HC68    
label values hc68_17  HC68    
label values hc68_18  HC68    
label values hc68_19  HC68    
label values hc68_20  HC68    
label values sb115a_01 SB115A  
label values sb115a_02 SB115A  
label values sb115a_03 SB115A  
label values sb115a_04 SB115A  
label values sb115a_05 SB115A  
label values sb115a_06 SB115A  
label values sb115a_07 SB115A  
label values sb115a_08 SB115A  
label values sb115a_09 SB115A  
label values sb115a_10 SB115A  
label values sb115a_11 SB115A  
label values sb115a_12 SB115A  
label values sb115a_13 SB115A  
label values sb115a_14 SB115A  
label values sb115a_15 SB115A  
label values sb115a_16 SB115A  
label values sb115a_17 SB115A  
label values sb115a_18 SB115A  
label values sb115a_19 SB115A  
label values sb115a_20 SB115A  
label values sb115b_01 SB115B  
label values sb115b_02 SB115B  
label values sb115b_03 SB115B  
label values sb115b_04 SB115B  
label values sb115b_05 SB115B  
label values sb115b_06 SB115B  
label values sb115b_07 SB115B  
label values sb115b_08 SB115B  
label values sb115b_09 SB115B  
label values sb115b_10 SB115B  
label values sb115b_11 SB115B  
label values sb115b_12 SB115B  
label values sb115b_13 SB115B  
label values sb115b_14 SB115B  
label values sb115b_15 SB115B  
label values sb115b_16 SB115B  
label values sb115b_17 SB115B  
label values sb115b_18 SB115B  
label values sb115b_19 SB115B  
label values sb115b_20 SB115B  
label values sb115c_01 SB115C  
label values sb115c_02 SB115C  
label values sb115c_03 SB115C  
label values sb115c_04 SB115C  
label values sb115c_05 SB115C  
label values sb115c_06 SB115C  
label values sb115c_07 SB115C  
label values sb115c_08 SB115C  
label values sb115c_09 SB115C  
label values sb115c_10 SB115C  
label values sb115c_11 SB115C  
label values sb115c_12 SB115C  
label values sb115c_13 SB115C  
label values sb115c_14 SB115C  
label values sb115c_15 SB115C  
label values sb115c_16 SB115C  
label values sb115c_17 SB115C  
label values sb115c_18 SB115C  
label values sb115c_19 SB115C  
label values sb115c_20 SB115C  
label values sb115d_01 SB115D  
label values sb115d_02 SB115D  
label values sb115d_03 SB115D  
label values sb115d_04 SB115D  
label values sb115d_05 SB115D  
label values sb115d_06 SB115D  
label values sb115d_07 SB115D  
label values sb115d_08 SB115D  
label values sb115d_09 SB115D  
label values sb115d_10 SB115D  
label values sb115d_11 SB115D  
label values sb115d_12 SB115D  
label values sb115d_13 SB115D  
label values sb115d_14 SB115D  
label values sb115d_15 SB115D  
label values sb115d_16 SB115D  
label values sb115d_17 SB115D  
label values sb115d_18 SB115D  
label values sb115d_19 SB115D  
label values sb115d_20 SB115D  
label values sb115e_01 SB115E  
label values sb115e_02 SB115E  
label values sb115e_03 SB115E  
label values sb115e_04 SB115E  
label values sb115e_05 SB115E  
label values sb115e_06 SB115E  
label values sb115e_07 SB115E  
label values sb115e_08 SB115E  
label values sb115e_09 SB115E  
label values sb115e_10 SB115E  
label values sb115e_11 SB115E  
label values sb115e_12 SB115E  
label values sb115e_13 SB115E  
label values sb115e_14 SB115E  
label values sb115e_15 SB115E  
label values sb115e_16 SB115E  
label values sb115e_17 SB115E  
label values sb115e_18 SB115E  
label values sb115e_19 SB115E  
label values sb115e_20 SB115E  
label values sb115f_01 SB115F  
label values sb115f_02 SB115F  
label values sb115f_03 SB115F  
label values sb115f_04 SB115F  
label values sb115f_05 SB115F  
label values sb115f_06 SB115F  
label values sb115f_07 SB115F  
label values sb115f_08 SB115F  
label values sb115f_09 SB115F  
label values sb115f_10 SB115F  
label values sb115f_11 SB115F  
label values sb115f_12 SB115F  
label values sb115f_13 SB115F  
label values sb115f_14 SB115F  
label values sb115f_15 SB115F  
label values sb115f_16 SB115F  
label values sb115f_17 SB115F  
label values sb115f_18 SB115F  
label values sb115f_19 SB115F  
label values sb115f_20 SB115F  
label values sb115g_01 SB115G  
label values sb115g_02 SB115G  
label values sb115g_03 SB115G  
label values sb115g_04 SB115G  
label values sb115g_05 SB115G  
label values sb115g_06 SB115G  
label values sb115g_07 SB115G  
label values sb115g_08 SB115G  
label values sb115g_09 SB115G  
label values sb115g_10 SB115G  
label values sb115g_11 SB115G  
label values sb115g_12 SB115G  
label values sb115g_13 SB115G  
label values sb115g_14 SB115G  
label values sb115g_15 SB115G  
label values sb115g_16 SB115G  
label values sb115g_17 SB115G  
label values sb115g_18 SB115G  
label values sb115g_19 SB115G  
label values sb115g_20 SB115G  
label values sb115h_01 SB115H  
label values sb115h_02 SB115H  
label values sb115h_03 SB115H  
label values sb115h_04 SB115H  
label values sb115h_05 SB115H  
label values sb115h_06 SB115H  
label values sb115h_07 SB115H  
label values sb115h_08 SB115H  
label values sb115h_09 SB115H  
label values sb115h_10 SB115H  
label values sb115h_11 SB115H  
label values sb115h_12 SB115H  
label values sb115h_13 SB115H  
label values sb115h_14 SB115H  
label values sb115h_15 SB115H  
label values sb115h_16 SB115H  
label values sb115h_17 SB115H  
label values sb115h_18 SB115H  
label values sb115h_19 SB115H  
label values sb115h_20 SB115H  
label values sb119_01 SB119   
label values sb119_02 SB119   
label values sb119_03 SB119   
label values sb119_04 SB119   
label values sb119_05 SB119   
label values sb119_06 SB119   
label values sb119_07 SB119   
label values sb119_08 SB119   
label values sb119_09 SB119   
label values sb119_10 SB119   
label values sb119_11 SB119   
label values sb119_12 SB119   
label values sb119_13 SB119   
label values sb119_14 SB119   
label values sb119_15 SB119   
label values sb119_16 SB119   
label values sb119_17 SB119   
label values sb119_18 SB119   
label values sb119_19 SB119   
label values sb119_20 SB119   
label values sb122_01 SB122   
label values sb122_02 SB122   
label values sb122_03 SB122   
label values sb122_04 SB122   
label values sb122_05 SB122   
label values sb122_06 SB122   
label values sb122_07 SB122   
label values sb122_08 SB122   
label values sb122_09 SB122   
label values sb122_10 SB122   
label values sb122_11 SB122   
label values sb122_12 SB122   
label values sb122_13 SB122   
label values sb122_14 SB122   
label values sb122_15 SB122   
label values sb122_16 SB122   
label values sb122_17 SB122   
label values sb122_18 SB122   
label values sb122_19 SB122   
label values sb122_20 SB122   
label values sb128d_01 SB128D  
label values sb128d_02 SB128D  
label values sb128d_03 SB128D  
label values sb128d_04 SB128D  
label values sb128d_05 SB128D  
label values sb128d_06 SB128D  
label values sb128d_07 SB128D  
label values sb128d_08 SB128D  
label values sb128d_09 SB128D  
label values sb128d_10 SB128D  
label values sb128d_11 SB128D  
label values sb128d_12 SB128D  
label values sb128d_13 SB128D  
label values sb128d_14 SB128D  
label values sb128d_15 SB128D  
label values sb128d_16 SB128D  
label values sb128d_17 SB128D  
label values sb128d_18 SB128D  
label values sb128d_19 SB128D  
label values sb128d_20 SB128D  
label values sb128m_01 SB128M  
label values sb128m_02 SB128M  
label values sb128m_03 SB128M  
label values sb128m_04 SB128M  
label values sb128m_05 SB128M  
label values sb128m_06 SB128M  
label values sb128m_07 SB128M  
label values sb128m_08 SB128M  
label values sb128m_09 SB128M  
label values sb128m_10 SB128M  
label values sb128m_11 SB128M  
label values sb128m_12 SB128M  
label values sb128m_13 SB128M  
label values sb128m_14 SB128M  
label values sb128m_15 SB128M  
label values sb128m_16 SB128M  
label values sb128m_17 SB128M  
label values sb128m_18 SB128M  
label values sb128m_19 SB128M  
label values sb128m_20 SB128M  
label values sb128y_01 SB128Y  
label values sb128y_02 SB128Y  
label values sb128y_03 SB128Y  
label values sb128y_04 SB128Y  
label values sb128y_05 SB128Y  
label values sb128y_06 SB128Y  
label values sb128y_07 SB128Y  
label values sb128y_08 SB128Y  
label values sb128y_09 SB128Y  
label values sb128y_10 SB128Y  
label values sb128y_11 SB128Y  
label values sb128y_12 SB128Y  
label values sb128y_13 SB128Y  
label values sb128y_14 SB128Y  
label values sb128y_15 SB128Y  
label values sb128y_16 SB128Y  
label values sb128y_17 SB128Y  
label values sb128y_18 SB128Y  
label values sb128y_19 SB128Y  
label values sb128y_20 SB128Y  
label values hml3_1   HML3    
label values hml3_2   HML3    
label values hml3_3   HML3    
label values hml3_4   HML3    
label values hml3_5   HML3    
label values hml3_6   HML3    
label values hml3_7   HML3    
label values hml4_1   HML4    
label values hml4_2   HML4    
label values hml4_3   HML4    
label values hml4_4   HML4    
label values hml4_5   HML4    
label values hml4_6   HML4    
label values hml4_7   HML4    
label values hml5_1   HML5    
label values hml5_2   HML5    
label values hml5_3   HML5    
label values hml5_4   HML5    
label values hml5_5   HML5    
label values hml5_6   HML5    
label values hml5_7   HML5    
label values hml6_1   HML6    
label values hml6_2   HML6    
label values hml6_3   HML6    
label values hml6_4   HML6    
label values hml6_5   HML6    
label values hml6_6   HML6    
label values hml6_7   HML6    
label values hml7_1   HML7    
label values hml7_2   HML7    
label values hml7_3   HML7    
label values hml7_4   HML7    
label values hml7_5   HML7    
label values hml7_6   HML7    
label values hml7_7   HML7    
label values hml8_1   HML8    
label values hml8_2   HML8    
label values hml8_3   HML8    
label values hml8_4   HML8    
label values hml8_5   HML8    
label values hml8_6   HML8    
label values hml8_7   HML8    
label values hml9_1   HML9    
label values hml9_2   HML9    
label values hml9_3   HML9    
label values hml9_4   HML9    
label values hml9_5   HML9    
label values hml9_6   HML9    
label values hml9_7   HML9    
label values hml10_1  HML10   
label values hml10_2  HML10   
label values hml10_3  HML10   
label values hml10_4  HML10   
label values hml10_5  HML10   
label values hml10_6  HML10   
label values hml10_7  HML10   
label values hml11_1  HML11   
label values hml11_2  HML11   
label values hml11_3  HML11   
label values hml11_4  HML11   
label values hml11_5  HML11   
label values hml11_6  HML11   
label values hml11_7  HML11   
label values hml21_1  HML21   
label values hml21_2  HML21   
label values hml21_3  HML21   
label values hml21_4  HML21   
label values hml21_5  HML21   
label values hml21_6  HML21   
label values hml21_7  HML21   
label values hmla_1   HMLA    
label values hmla_2   HMLA    
label values hmla_3   HMLA    
label values hmla_4   HMLA    
label values hmla_5   HMLA    
label values hmla_6   HMLA    
label values hmla_7   HMLA    
label values hml22_1  HML22   
label values hml22_2  HML22   
label values hml22_3  HML22   
label values hml22_4  HML22   
label values hml22_5  HML22   
label values hml22_6  HML22   
label values hml22_7  HML22   
label values hml23_1  HML23   
label values hml23_2  HML23   
label values hml23_3  HML23   
label values hml23_4  HML23   
label values hml23_5  HML23   
label values hml23_6  HML23   
label values hml23_7  HML23   
label values sh130_1  SH130   
label values sh130_2  SH130   
label values sh130_3  SH130   
label values sh130_4  SH130   
label values sh130_5  SH130   
label values sh130_6  SH130   
label values sh130_7  SH130   
label values hml12_01 HML12   
label values hml12_02 HML12   
label values hml12_03 HML12   
label values hml12_04 HML12   
label values hml12_05 HML12   
label values hml12_06 HML12   
label values hml12_07 HML12   
label values hml12_08 HML12   
label values hml12_09 HML12   
label values hml12_10 HML12   
label values hml12_11 HML12   
label values hml12_12 HML12   
label values hml12_13 HML12   
label values hml12_14 HML12   
label values hml12_15 HML12   
label values hml12_16 HML12   
label values hml12_17 HML12   
label values hml12_18 HML12   
label values hml12_19 HML12   
label values hml12_20 HML12   
label values hml12_21 HML12   
label values hml12_22 HML12   
label values hml12_23 HML12   
label values hml12_24 HML12   
label values hml13_01 HML13   
label values hml13_02 HML13   
label values hml13_03 HML13   
label values hml13_04 HML13   
label values hml13_05 HML13   
label values hml13_06 HML13   
label values hml13_07 HML13   
label values hml13_08 HML13   
label values hml13_09 HML13   
label values hml13_10 HML13   
label values hml13_11 HML13   
label values hml13_12 HML13   
label values hml13_13 HML13   
label values hml13_14 HML13   
label values hml13_15 HML13   
label values hml13_16 HML13   
label values hml13_17 HML13   
label values hml13_18 HML13   
label values hml13_19 HML13   
label values hml13_20 HML13   
label values hml13_21 HML13   
label values hml13_22 HML13   
label values hml13_23 HML13   
label values hml13_24 HML13   
label values hml16_01 HML16   
label values hml16_02 HML16   
label values hml16_03 HML16   
label values hml16_04 HML16   
label values hml16_05 HML16   
label values hml16_06 HML16   
label values hml16_07 HML16   
label values hml16_08 HML16   
label values hml16_09 HML16   
label values hml16_10 HML16   
label values hml16_11 HML16   
label values hml16_12 HML16   
label values hml16_13 HML16   
label values hml16_14 HML16   
label values hml16_15 HML16   
label values hml16_16 HML16   
label values hml16_17 HML16   
label values hml16_18 HML16   
label values hml16_19 HML16   
label values hml16_20 HML16   
label values hml16_21 HML16   
label values hml16_22 HML16   
label values hml16_23 HML16   
label values hml16_24 HML16   
label values hml16a_01 HML16A  
label values hml16a_02 HML16A  
label values hml16a_03 HML16A  
label values hml16a_04 HML16A  
label values hml16a_05 HML16A  
label values hml16a_06 HML16A  
label values hml16a_07 HML16A  
label values hml16a_08 HML16A  
label values hml16a_09 HML16A  
label values hml16a_10 HML16A  
label values hml16a_11 HML16A  
label values hml16a_12 HML16A  
label values hml16a_13 HML16A  
label values hml16a_14 HML16A  
label values hml16a_15 HML16A  
label values hml16a_16 HML16A  
label values hml16a_17 HML16A  
label values hml16a_18 HML16A  
label values hml16a_19 HML16A  
label values hml16a_20 HML16A  
label values hml16a_21 HML16A  
label values hml16a_22 HML16A  
label values hml16a_23 HML16A  
label values hml16a_24 HML16A  
label values hml17_01 HML17   
label values hml17_02 HML17   
label values hml17_03 HML17   
label values hml17_04 HML17   
label values hml17_05 HML17   
label values hml17_06 HML17   
label values hml17_07 HML17   
label values hml17_08 HML17   
label values hml17_09 HML17   
label values hml17_10 HML17   
label values hml17_11 HML17   
label values hml17_12 HML17   
label values hml17_13 HML17   
label values hml17_14 HML17   
label values hml17_15 HML17   
label values hml17_16 HML17   
label values hml17_17 HML17   
label values hml17_18 HML17   
label values hml17_19 HML17   
label values hml17_20 HML17   
label values hml17_21 HML17   
label values hml17_22 HML17   
label values hml17_23 HML17   
label values hml17_24 HML17   
label values hml18_01 HML18   
label values hml18_02 HML18   
label values hml18_03 HML18   
label values hml18_04 HML18   
label values hml18_05 HML18   
label values hml18_06 HML18   
label values hml18_07 HML18   
label values hml18_08 HML18   
label values hml18_09 HML18   
label values hml18_10 HML18   
label values hml18_11 HML18   
label values hml18_12 HML18   
label values hml18_13 HML18   
label values hml18_14 HML18   
label values hml18_15 HML18   
label values hml18_16 HML18   
label values hml18_17 HML18   
label values hml18_18 HML18   
label values hml18_19 HML18   
label values hml18_20 HML18   
label values hml18_21 HML18   
label values hml18_22 HML18   
label values hml18_23 HML18   
label values hml18_24 HML18   
label values hml19_01 HML19   
label values hml19_02 HML19   
label values hml19_03 HML19   
label values hml19_04 HML19   
label values hml19_05 HML19   
label values hml19_06 HML19   
label values hml19_07 HML19   
label values hml19_08 HML19   
label values hml19_09 HML19   
label values hml19_10 HML19   
label values hml19_11 HML19   
label values hml19_12 HML19   
label values hml19_13 HML19   
label values hml19_14 HML19   
label values hml19_15 HML19   
label values hml19_16 HML19   
label values hml19_17 HML19   
label values hml19_18 HML19   
label values hml19_19 HML19   
label values hml19_20 HML19   
label values hml19_21 HML19   
label values hml19_22 HML19   
label values hml19_23 HML19   
label values hml19_24 HML19   
label values hml20_01 HML20   
label values hml20_02 HML20   
label values hml20_03 HML20   
label values hml20_04 HML20   
label values hml20_05 HML20   
label values hml20_06 HML20   
label values hml20_07 HML20   
label values hml20_08 HML20   
label values hml20_09 HML20   
label values hml20_10 HML20   
label values hml20_11 HML20   
label values hml20_12 HML20   
label values hml20_13 HML20   
label values hml20_14 HML20   
label values hml20_15 HML20   
label values hml20_16 HML20   
label values hml20_17 HML20   
label values hml20_18 HML20   
label values hml20_19 HML20   
label values hml20_20 HML20   
label values hml20_21 HML20   
label values hml20_22 HML20   
label values hml20_23 HML20   
label values hml20_24 HML20   
label values hml30_01 HML30   
label values hml30_02 HML30   
label values hml30_03 HML30   
label values hml30_04 HML30   
label values hml30_05 HML30   
label values hml30_06 HML30   
label values hml30_07 HML30   
label values hml30_08 HML30   
label values hml30_09 HML30   
label values hml30_10 HML30   
label values hml30_11 HML30   
label values hml30_12 HML30   
label values hml30_13 HML30   
label values hml30_14 HML30   
label values hml30_15 HML30   
label values hml30_16 HML30   
label values hml30_17 HML30   
label values hml30_18 HML30   
label values hml30_19 HML30   
label values hml30_20 HML30   
label values hml30_21 HML30   
label values hml30_22 HML30   
label values hml30_23 HML30   
label values hml30_24 HML30   
label values hml31_01 HML31   
label values hml31_02 HML31   
label values hml31_03 HML31   
label values hml31_04 HML31   
label values hml31_05 HML31   
label values hml31_06 HML31   
label values hml31_07 HML31   
label values hml31_08 HML31   
label values hml31_09 HML31   
label values hml31_10 HML31   
label values hml31_11 HML31   
label values hml31_12 HML31   
label values hml31_13 HML31   
label values hml31_14 HML31   
label values hml31_15 HML31   
label values hml31_16 HML31   
label values hml31_17 HML31   
label values hml31_18 HML31   
label values hml31_19 HML31   
label values hml31_20 HML31   
label values hml31_21 HML31   
label values hml31_22 HML31   
label values hml31_23 HML31   
label values hml31_24 HML31   
label values hml32_01 HML32   
label values hml32_02 HML32   
label values hml32_03 HML32   
label values hml32_04 HML32   
label values hml32_05 HML32   
label values hml32_06 HML32   
label values hml32_07 HML32   
label values hml32_08 HML32   
label values hml32_09 HML32   
label values hml32_10 HML32   
label values hml32_11 HML32   
label values hml32_12 HML32   
label values hml32_13 HML32   
label values hml32_14 HML32   
label values hml32_15 HML32   
label values hml32_16 HML32   
label values hml32_17 HML32   
label values hml32_18 HML32   
label values hml32_19 HML32   
label values hml32_20 HML32   
label values hml32_21 HML32   
label values hml32_22 HML32   
label values hml32_23 HML32   
label values hml32_24 HML32   
label values hml32a_01 HML32A  
label values hml32a_02 HML32A  
label values hml32a_03 HML32A  
label values hml32a_04 HML32A  
label values hml32a_05 HML32A  
label values hml32a_06 HML32A  
label values hml32a_07 HML32A  
label values hml32a_08 HML32A  
label values hml32a_09 HML32A  
label values hml32a_10 HML32A  
label values hml32a_11 HML32A  
label values hml32a_12 HML32A  
label values hml32a_13 HML32A  
label values hml32a_14 HML32A  
label values hml32a_15 HML32A  
label values hml32a_16 HML32A  
label values hml32a_17 HML32A  
label values hml32a_18 HML32A  
label values hml32a_19 HML32A  
label values hml32a_20 HML32A  
label values hml32a_21 HML32A  
label values hml32a_22 HML32A  
label values hml32a_23 HML32A  
label values hml32a_24 HML32A  
label values hml32b_01 HML32B  
label values hml32b_02 HML32B  
label values hml32b_03 HML32B  
label values hml32b_04 HML32B  
label values hml32b_05 HML32B  
label values hml32b_06 HML32B  
label values hml32b_07 HML32B  
label values hml32b_08 HML32B  
label values hml32b_09 HML32B  
label values hml32b_10 HML32B  
label values hml32b_11 HML32B  
label values hml32b_12 HML32B  
label values hml32b_13 HML32B  
label values hml32b_14 HML32B  
label values hml32b_15 HML32B  
label values hml32b_16 HML32B  
label values hml32b_17 HML32B  
label values hml32b_18 HML32B  
label values hml32b_19 HML32B  
label values hml32b_20 HML32B  
label values hml32b_21 HML32B  
label values hml32b_22 HML32B  
label values hml32b_23 HML32B  
label values hml32b_24 HML32B  
label values hml32c_01 HML32C  
label values hml32c_02 HML32C  
label values hml32c_03 HML32C  
label values hml32c_04 HML32C  
label values hml32c_05 HML32C  
label values hml32c_06 HML32C  
label values hml32c_07 HML32C  
label values hml32c_08 HML32C  
label values hml32c_09 HML32C  
label values hml32c_10 HML32C  
label values hml32c_11 HML32C  
label values hml32c_12 HML32C  
label values hml32c_13 HML32C  
label values hml32c_14 HML32C  
label values hml32c_15 HML32C  
label values hml32c_16 HML32C  
label values hml32c_17 HML32C  
label values hml32c_18 HML32C  
label values hml32c_19 HML32C  
label values hml32c_20 HML32C  
label values hml32c_21 HML32C  
label values hml32c_22 HML32C  
label values hml32c_23 HML32C  
label values hml32c_24 HML32C  
label values hml32d_01 HML32D  
label values hml32d_02 HML32D  
label values hml32d_03 HML32D  
label values hml32d_04 HML32D  
label values hml32d_05 HML32D  
label values hml32d_06 HML32D  
label values hml32d_07 HML32D  
label values hml32d_08 HML32D  
label values hml32d_09 HML32D  
label values hml32d_10 HML32D  
label values hml32d_11 HML32D  
label values hml32d_12 HML32D  
label values hml32d_13 HML32D  
label values hml32d_14 HML32D  
label values hml32d_15 HML32D  
label values hml32d_16 HML32D  
label values hml32d_17 HML32D  
label values hml32d_18 HML32D  
label values hml32d_19 HML32D  
label values hml32d_20 HML32D  
label values hml32d_21 HML32D  
label values hml32d_22 HML32D  
label values hml32d_23 HML32D  
label values hml32d_24 HML32D  
label values hml32e_01 HML32E  
label values hml32e_02 HML32E  
label values hml32e_03 HML32E  
label values hml32e_04 HML32E  
label values hml32e_05 HML32E  
label values hml32e_06 HML32E  
label values hml32e_07 HML32E  
label values hml32e_08 HML32E  
label values hml32e_09 HML32E  
label values hml32e_10 HML32E  
label values hml32e_11 HML32E  
label values hml32e_12 HML32E  
label values hml32e_13 HML32E  
label values hml32e_14 HML32E  
label values hml32e_15 HML32E  
label values hml32e_16 HML32E  
label values hml32e_17 HML32E  
label values hml32e_18 HML32E  
label values hml32e_19 HML32E  
label values hml32e_20 HML32E  
label values hml32e_21 HML32E  
label values hml32e_22 HML32E  
label values hml32e_23 HML32E  
label values hml32e_24 HML32E  
label values hml32f_01 HML32F  
label values hml32f_02 HML32F  
label values hml32f_03 HML32F  
label values hml32f_04 HML32F  
label values hml32f_05 HML32F  
label values hml32f_06 HML32F  
label values hml32f_07 HML32F  
label values hml32f_08 HML32F  
label values hml32f_09 HML32F  
label values hml32f_10 HML32F  
label values hml32f_11 HML32F  
label values hml32f_12 HML32F  
label values hml32f_13 HML32F  
label values hml32f_14 HML32F  
label values hml32f_15 HML32F  
label values hml32f_16 HML32F  
label values hml32f_17 HML32F  
label values hml32f_18 HML32F  
label values hml32f_19 HML32F  
label values hml32f_20 HML32F  
label values hml32f_21 HML32F  
label values hml32f_22 HML32F  
label values hml32f_23 HML32F  
label values hml32f_24 HML32F  
label values hml32g_01 HML32G  
label values hml32g_02 HML32G  
label values hml32g_03 HML32G  
label values hml32g_04 HML32G  
label values hml32g_05 HML32G  
label values hml32g_06 HML32G  
label values hml32g_07 HML32G  
label values hml32g_08 HML32G  
label values hml32g_09 HML32G  
label values hml32g_10 HML32G  
label values hml32g_11 HML32G  
label values hml32g_12 HML32G  
label values hml32g_13 HML32G  
label values hml32g_14 HML32G  
label values hml32g_15 HML32G  
label values hml32g_16 HML32G  
label values hml32g_17 HML32G  
label values hml32g_18 HML32G  
label values hml32g_19 HML32G  
label values hml32g_20 HML32G  
label values hml32g_21 HML32G  
label values hml32g_22 HML32G  
label values hml32g_23 HML32G  
label values hml32g_24 HML32G  
label values hml33_01 HML33   
label values hml33_02 HML33   
label values hml33_03 HML33   
label values hml33_04 HML33   
label values hml33_05 HML33   
label values hml33_06 HML33   
label values hml33_07 HML33   
label values hml33_08 HML33   
label values hml33_09 HML33   
label values hml33_10 HML33   
label values hml33_11 HML33   
label values hml33_12 HML33   
label values hml33_13 HML33   
label values hml33_14 HML33   
label values hml33_15 HML33   
label values hml33_16 HML33   
label values hml33_17 HML33   
label values hml33_18 HML33   
label values hml33_19 HML33   
label values hml33_20 HML33   
label values hml33_21 HML33   
label values hml33_22 HML33   
label values hml33_23 HML33   
label values hml33_24 HML33   
label values hml35_01 HML35   
label values hml35_02 HML35   
label values hml35_03 HML35   
label values hml35_04 HML35   
label values hml35_05 HML35   
label values hml35_06 HML35   
label values hml35_07 HML35   
label values hml35_08 HML35   
label values hml35_09 HML35   
label values hml35_10 HML35   
label values hml35_11 HML35   
label values hml35_12 HML35   
label values hml35_13 HML35   
label values hml35_14 HML35   
label values hml35_15 HML35   
label values hml35_16 HML35   
label values hml35_17 HML35   
label values hml35_18 HML35   
label values hml35_19 HML35   
label values hml35_20 HML35   
label values hml35_21 HML35   
label values hml35_22 HML35   
label values hml35_23 HML35   
label values hml35_24 HML35   
